### ISSUE TITLE
EXCEPTION: No Directive annotation found on AppComponent

### ISSUE THREAD

**Issue by amirmasoud** [angular/angular#10247]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Just trying to start working with AngularJS 2. in TOUR OF HEROES tutorial, when I add Hero class I face `No Directive annotation found` exception.

 Exception:
```
EXCEPTION: No Directive annotation found on AppComponent
platform-browser.umd.js:1900 EXCEPTION: No Directive annotation found on AppComponentBrowserDomAdapter.logError @ platform-browser.umd.js:1900
platform-browser.umd.js:1900 STACKTRACE:BrowserDomAdapter.logError @ platform-browser.umd.js:1900
platform-browser.umd.js:1900 Error: No Directive annotation found on AppComponent
    at new BaseException$1 (compiler.umd.js:971)
    at DirectiveResolver.resolve (compiler.umd.js:12167)
    at CompileMetadataResolver.getDirectiveMetadata (compiler.umd.js:12420)
    at RuntimeCompiler._getCompiledHostTemplate (compiler.umd.js:14604)
    at RuntimeCompiler._getTransitiveCompiledTemplates (compiler.umd.js:14637)
    at RuntimeCompiler.compileComponentAsync (compiler.umd.js:14563)
    at RuntimeCompiler.resolveComponent (compiler.umd.js:14559)
    at eval (core.umd.js:9645)
    at eval (core.umd.js:9840)
    at ZoneDelegate.invoke (zone.js:323)BrowserDomAdapter.logError @ platform-browser.umd.js:1900
localhost/:17 Error: Error: No Directive annotation found on AppComponent
	    at new BaseException$1 (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:971:27)
	    at DirectiveResolver.resolve (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:12167:19)
	    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:12420:55)
	    at RuntimeCompiler._getCompiledHostTemplate (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:14604:55)
	    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:14637:42)
	    at RuntimeCompiler.compileComponentAsync (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:14563:34)
	    at RuntimeCompiler.resolveComponent (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:14559:25)
	    at eval (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:9645:41)
	    at eval (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:9840:30)
	    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:323:29)
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js(anonymous function) @ localhost/:17
```

**Expected/desired behavior**
Works as tutorial says it will work.

**Reproduction of the problem**
The application is working just fine before adding Hero object and class.
https://angular.io/docs/ts/latest/tutorial/toh-pt1.html

**What is the expected behavior?**
See above.

**What is the motivation / use case for changing the behavior?**
See above.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome 51.0.2704.103 m| Firefox 47.0.1 ] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by vicb** [comment]
please re-open on https://github.com/angular/angular.io/issues
