### ISSUE TITLE
angular2 Only support at most 9 interpolation values!

### ISSUE THREAD

**Issue by asvifi85** [angular/angular#10253]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
```

**Current behavior**
When I am trying to interpolate more than 9 properties of an object in template I am getting the following error:
Error: Uncaught (in promise): Template parse errors:
Only support at most 9 interpolation values!

**Expected/desired behavior**
It should be able to print any number of properties of an object

**Reproduction of the problem**
The issue could be reproduced at : 
http://plnkr.co/edit/3M7lw6U4RAuOPacM4rmj?p=preview

**What is the expected behavior?**
It should be able to interpolate any number of properties of an object

**What is the motivation / use case for changing the behavior?**
I am unable to print all details details of users

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc4
- **Browser:** all 
- **Language:** Typescript

**Comment by vicb** [comment]
I don't think this is an issue, is it ?

IRW you would most certainly do `{{ lead|formatLead }}`

Without a pipe you can still do `{{ a + " " + b + ...}}`

**Comment by benaduggan** [comment]
I ran into this today and this seems like a ridiculous limitation. Are there any valid reason for such a low limit?

**Comment by freezy** [comment]
I'm getting this during `ngc` compilation on all my Pug templates when there are more than 9 expressions in the template. The expressions are *never* in the same HTML element like in the plnkr above. Snippet:

```pug

//- NAVBAR
//-------------------------------------------------------------------------
nav.navbar.navbar-dark.bg-inverse
	.container
		a.navbar-brand([routerLink]=" ['/']")
			md-icon.logo(svgSrc="assets/svg/logo.svg")
		ul.nav.navbar-nav([routerLinkActive]="['active']", *ngIf="auth.isAuthenticated | async")
			li.nav-item([routerLinkActive]="['active']")
				a.nav-link([routerLink]=" ['/account/dashboard']")
					span.hidden-md-up.m-l-1
						md-icon(svgSrc="assets/svg/home.svg")
					span.hidden-sm-down {{ 'account' | translate:lang }}
			li.nav-item([routerLinkActive]="['active']")
				a.nav-link([routerLink]=" ['/account/business']")
					span.hidden-md-up.m-l-1
						md-icon(svgSrc="assets/svg/location.svg")
					span.hidden-sm-down {{ 'business' | translate:lang }}
			li.nav-item([routerLinkActive]="['active']")
				a.nav-link([routerLink]=" ['/account/card-reader']")
					span.hidden-md-up.m-l-1
						md-icon(svgSrc="assets/svg/dongle.svg")
					span.hidden-sm-down {{ 'card_reader' | translate:lang }}
			li.nav-item([routerLinkActive]="['active']")
				a.nav-link([routerLink]=" ['/account/bank']")
					span.hidden-md-up.m-l-1
						md-icon(svgSrc="assets/svg/bank.svg")
					span.hidden-sm-down {{ 'bank' | translate:lang }}
		ul.nav.navbar-nav.pull-xs-right
			li.nav-item(*ngIf="!(auth.isAuthenticated | async)")
				a.nav-link((click)="clearBusinessData();track('Login');loginModal.show();") {{ 'login' | translate:lang }}
			li.nav-item(*ngIf="auth.isAuthenticated | async")
				a.nav-link((click)="auth.logout()") {{ 'logout' | translate:lang }}
hr.hr--separator
.container
	main
		router-outlet

	//- LOGIN MODAL
	//-------------------------------------------------------------------------
	.modal.fade(bsModal, #loginModal="bs-modal", tabindex="-1", role="dialog")
		.modal-dialog
			.modal-content
				.modal-header
					button.close(type="button", (click)="loginModal.hide()", aria-label="Close")
						span(aria-hidden="true") &times;
					h4.modal-title {{ 'google_signin_title' | translate:lang }}
				.modal-body
					p {{ 'google_signin_content' | translate:lang }}
					.text-xs-center
						button.btn.btn-outline-primary.btn--google-login((click)="auth.login()")
							md-icon(svgSrc="assets/svg/g-logo.svg")
							span {{ 'google_signin' | translate:lang }}
					p.m-t-1
						i {{ 'google_signin_note' | translate:lang }}
```

Fails with:

```
Error: Template parse errors:
Error: Only support at most 9 interpolation values! ("[ERROR ->]
//- NAVBAR
//-------------------------------------------------------------------------
nav.navbar.na"): AppComponent@0:0
    at TemplateParser.parse (C:\dev\website\node_modules\@angular\compiler\bundles\compiler.umd.js:8502:21)
    at OfflineCompiler._compileComponent (C:\dev\website\node_modules\@angular\compiler\bundles\compiler.umd.js:13024:53)
    at C:\dev\website\node_modules\@angular\compiler\bundles\compiler.umd.js:12976:109
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:456:3
Compilation failed
```

Using Angular 2.0.1. If I remove the last expression (`{{ 'google_signin_note' | translate:lang }}`), making it 9, it works. What the...?

**Comment by tbosch** [comment]
We should just fix this as it is not hard. Please note that the issue regarding pug templates is different, i.e. the limitation only applies to interpolations in the same HTML text span.
