### ISSUE TITLE
NPM install cause  UNMET PEER DEPENDENCY and I get this error : TypeError: iterator1.next is not a function at Object.areIterablesEqual (collection.js:314)

### ISSUE THREAD

**Issue by samirthebti** [angular/angular#10298]
when try to install  the dependencies i get this error  
```
UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.4
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.4
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.4
├── UNMET PEER DEPENDENCY @angular/forms@0.2.0
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0-rc.4
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.0.0-rc.4
Linux 3.19.0-65-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path /home/thesam/Desktop/Evey/Evey/node_modules/.staging/abbrev-edbf2ddf
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/home/thesam/Desktop/Evey/Evey/node_modules/.staging/abbrev-edbf2ddf' -> '/home/thesam/Desktop/Evey/Evey/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/home/thesam/Desktop/Evey/Evey/node_modules/.staging/abbrev-edbf2ddf' -> '/home/thesam/Desktop/Evey/Evey/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

```
and as a result a get this error in console screen in google chrome : 

browser_adapter.js:84 EXCEPTION: Error in http://localhost:4200/vendor/@angular2-material/sidenav/sidenav.js class MdSidenavLayout - inline template:0:177BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 ORIGINAL EXCEPTION: TypeError: iterator1.next is not a functionBrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 TypeError: iterator1.next is not a function
    at Object.areIterablesEqual (collection.js:321)
    at Object.devModeEqual (change_detection_util.js:16)
    at checkBinding (view_utils.js:132)
    at DebugAppView._View_MdSidenavLayout0.detectChangesInternal (MdSidenavLayout.template.js:64)
    at DebugAppView.AppView.detectChanges (view.js:243)
    at DebugAppView.detectChanges (view.js:348)
    at DebugAppView.AppView.detectViewChildrenChanges (view.js:269)
    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:678)
    at DebugAppView.AppView.detectChanges (view.js:243)
    at DebugAppView.detectChanges (view.js:348)BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 DebugContextBrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:93 EXCEPTION: Error in http://localhost:4200/vendor/@angular2-material/sidenav/sidenav.js class MdSidenavLayout - inline template:0:177
browser_adapter.js:84 EXCEPTION: Error in http://localhost:4200/vendor/@angular2-material/sidenav/sidenav.js class MdSidenavLayout - inline template:0:177BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 ORIGINAL EXCEPTION: TypeError: iterator1.next is not a functionBrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 TypeError: iterator1.next is not a function
    at Object.areIterablesEqual (collection.js:321)
    at Object.devModeEqual (change_detection_util.js:16)
    at checkBinding (view_utils.js:132)
    at DebugAppView._View_MdSidenavLayout0.detectChangesInternal (MdSidenavLayout.template.js:64)
    at DebugAppView.AppView.detectChanges (view.js:243)
    at DebugAppView.detectChanges (view.js:348)
    at DebugAppView.AppView.detectViewChildrenChanges (view.js:269)
    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:678)
    at DebugAppView.AppView.detectChanges (view.js:243)
    at DebugAppView.detectChanges (view.js:348)BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 DebugContextBrowserDomAdapter.logError @ browser_adapter.js:84
main.js:30 ViewWrappedException(anonymous function) @ main.js:30
browser_adapter.js:93 EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in http://localhost:4200/vendor/@angular2-material/sidenav/sidenav.js class MdSidenavLayout - inline template:0:177
ORIGINAL EXCEPTION: TypeError: iterator1.next is not a function
ORIGINAL STACKTRACE:
TypeError: iterator1.next is not a function
    at Object.areIterablesEqual (http://localhost:4200/vendor/@angular/core/src/facade/collection.js:321:31)
    at Object.devModeEqual (http://localhost:4200/vendor/@angular/core/src/change_detection/change_detection_util.js:16:29)
    at checkBinding (http://localhost:4200/vendor/@angular/core/src/linker/view_utils.js:132:33)
    at DebugAppView._View_MdSidenavLayout0.detectChangesInternal (MdSidenavLayout.template.js:64:7)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:269:19)
    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:678:8)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
ERROR CONTEXT:
[object Object]
browser_adapter.js:84 EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in http://localhost:4200/vendor/@angular2-material/sidenav/sidenav.js class MdSidenavLayout - inline template:0:177
ORIGINAL EXCEPTION: TypeError: iterator1.next is not a function
ORIGINAL STACKTRACE:
TypeError: iterator1.next is not a function
    at Object.areIterablesEqual (http://localhost:4200/vendor/@angular/core/src/facade/collection.js:321:31)
    at Object.devModeEqual (http://localhost:4200/vendor/@angular/core/src/change_detection/change_detection_util.js:16:29)
    at checkBinding (http://localhost:4200/vendor/@angular/core/src/linker/view_utils.js:132:33)
    at DebugAppView._View_MdSidenavLayout0.detectChangesInternal (MdSidenavLayout.template.js:64:7)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:269:19)
    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:678:8)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
ERROR CONTEXT:
[object Object]BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:84
browser_adapter.js:84 Error: Uncaught (in promise): EXCEPTION: Error in http://localhost:4200/vendor/@angular2-material/sidenav/sidenav.js class MdSidenavLayout - inline template:0:177
ORIGINAL EXCEPTION: TypeError: iterator1.next is not a function
ORIGINAL STACKTRACE:
TypeError: iterator1.next is not a function
    at Object.areIterablesEqual (http://localhost:4200/vendor/@angular/core/src/facade/collection.js:321:31)
    at Object.devModeEqual (http://localhost:4200/vendor/@angular/core/src/change_detection/change_detection_util.js:16:29)
    at checkBinding (http://localhost:4200/vendor/@angular/core/src/linker/view_utils.js:132:33)
    at DebugAppView._View_MdSidenavLayout0.detectChangesInternal (MdSidenavLayout.template.js:64:7)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:269:19)
    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:678:8)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
ERROR CONTEXT:
[object Object]
    at resolvePromise (http://localhost:4200/vendor/zone.js/dist/zone.js:538:32)
    at http://localhost:4200/vendor/zone.js/dist/zone.js:574:18
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
    at Object.onInvokeTask (http://localhost:4200/vendor/@angular/core/src/zone/ng_zone_impl.js:44:41)
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:355:43)
    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
    at drainMicroTaskQueue (http://localhost:4200/vendor/zone.js/dist/zone.js:474:36)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:426:22)BrowserDomAdapter.logError @ browser_adapter.js:84
zone.js:461 Unhandled Promise rejection: EXCEPTION: Error in http://localhost:4200/vendor/@angular2-material/sidenav/sidenav.js class MdSidenavLayout - inline template:0:177
ORIGINAL EXCEPTION: TypeError: iterator1.next is not a function
ORIGINAL STACKTRACE:
TypeError: iterator1.next is not a function
    at Object.areIterablesEqual (http://localhost:4200/vendor/@angular/core/src/facade/collection.js:321:31)
    at Object.devModeEqual (http://localhost:4200/vendor/@angular/core/src/change_detection/change_detection_util.js:16:29)
    at checkBinding (http://localhost:4200/vendor/@angular/core/src/linker/view_utils.js:132:33)
    at DebugAppView._View_MdSidenavLayout0.detectChangesInternal (MdSidenavLayout.template.js:64:7)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:269:19)
    at DebugAppView._View_EveyWebAppComponent0.detectChangesInternal (EveyWebAppComponent.template.js:678:8)
    at DebugAppView.AppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (http://localhost:4200/vendor/@angular/core/src/linker/view.js:348:44)
ERROR CONTEXT:
[object Object] ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedExceptionconsoleError @ zone.js:461
zone.js:463 Error: Uncaught (in promise): EXCEPTION: Error in http://localhost:4200/vendor/@angular2-material/sidenav/sidenav.js class MdSidenavLayout - inline template:0:177(…)consoleError @ zone.js:463
auth.service.js:21   Auth Service Constructor : 
auth.service.js:28  auth state ///// undefined
ng_form.js:38 
      *It looks like you're using the old forms module. This will be opt-in in the next RC, and
      will eventually be removed in favor of the new forms module. For more information, see:
      https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

**Comment by pkozlowski-opensource** [comment]
This sounds like a support question and as such should be taken to the appropriate support channel, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
