### ISSUE TITLE
Error: Cannot find control 'formArray -> 0'

### ISSUE THREAD

**Issue by AJLiu** [angular/angular#10335]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Attempting to bind an input to a FormControl within a FormArray results in the error: 
```
zone.js@0.6.12?main=browser:461 Unhandled Promise rejection: EXCEPTION: Error in ./AppComponent class AppComponent - inline template:5:17
ORIGINAL EXCEPTION: Cannot find control 'formArray -> 0'
ORIGINAL STACKTRACE:
Error: Cannot find control 'formArray -> 0'
    at new BaseException (https://npmcdn.com/@angular/forms@0.2.0/src/facade/exceptions.js:27:23)
    at _throwError (https://npmcdn.com/@angular/forms@0.2.0/src/directives/shared.js:55:11)
    at Object.setUpControl (https://npmcdn.com/@angular/forms@0.2.0/src/directives/shared.js:28:9)
    at FormGroupDirective.addControl (https://npmcdn.com/@angular/forms@0.2.0/src/directives/reactive_directives/form_group_directive.js:71:18)
    at FormControlName.ngOnChanges (https://npmcdn.com/@angular/forms@0.2.0/src/directives/reactive_directives/form_control_name.js:39:32)
    at DebugAppView._View_AppComponent1.detectChangesInternal (AppComponent.template.js:240:55)
    at DebugAppView.AppView.detectChanges (https://npmcdn.com/@angular/core@2.0.0-rc.4//bundles/core.umd.js:12143:18)
    at DebugAppView.detectChanges (https://npmcdn.com/@angular/core@2.0.0-rc.4//bundles/core.umd.js:12247:48)
    at DebugAppView.AppView.detectContentChildrenChanges (https://npmcdn.com/@angular/core@2.0.0-rc.4//bundles/core.umd.js:12161:23)
    at DebugAppView._View_AppComponent0.detectChangesInternal (AppComponent.template.js:143:8)
ERROR CONTEXT:
[object Object] ; Zone: angular ; Task: Promise.then ; Value:
```

**Expected/desired behavior**
Inputs should be able to be bound to FormControls within a FormArray. 

**Reproduction of the problem**
http://plnkr.co/edit/EuII2sjFJw8qvvU3dzhu?p=preview

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** all
 
* **Language:**TypeScript 2.0.0-beta

**Comment by kara** [comment]
@AJLiu   It looks like there are a few issues with the code :)   

1)  If you want to use `formArrayName`, you need to provide the new forms bundle. You can do so like this in your bootstrap file:

```ts
import { disableDeprecatedForms, provideForms } from '@angular/forms';

bootstrap(App, [
  disableDeprecatedForms(),
  provideForms()
]);

```

2)  It looks like you are referencing a property that doesn't exist when you instantiate the FormGroup.  `this.emailArray` doesn't exist, but `this.arr` does (and refers to the FormArray you created). If you switch to use `this.arr`, everything works.

See updated code: http://plnkr.co/edit/8X4xWgHt0iv3e5XCeW26?p=preview

I'm closing, as this doesn't seem to be a bug.
