### ISSUE TITLE
 No provider for NewFormBuilder

### ISSUE THREAD

**Issue by factoryberlin** [angular/angular#10347]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
I'm trying to implement a form and get the error  `No provider for NewFormBuilder` in my browser (Chrome).

```
// main.ts

import { APP_BASE_HREF } from '@angular/common';
import { disableDeprecatedForms, provideForms } from '@angular/forms/index';
import { enableProdMode, provide } from '@angular/core';
import { bootstrap } from '@angular/platform-browser-dynamic';

import { APP_ROUTER_PROVIDERS } from './app.routes';
import { AppComponent } from './app.component';

if ('<%= ENV %>' === 'prod') { enableProdMode(); }

bootstrap(AppComponent, [
  APP_ROUTER_PROVIDERS,
  {
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  },
  disableDeprecatedForms(),
  provideForms()
]);
```

```
// app.component.ts

import { Component } from '@angular/core';
import { ROUTER_DIRECTIVES } from '@angular/router';
import { HTTP_PROVIDERS } from '@angular/http';

import { HomeComponent } from './+home/home.component';

@Component({
  moduleId: module.id,
  selector: 'fac-app',
  viewProviders: [HTTP_PROVIDERS],
  templateUrl: 'app.component.html',
  directives: [ROUTER_DIRECTIVES, HomeComponent]
})
export class AppComponent {}
```

```
// +home/home.component.ts

import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, FormBuilder, REACTIVE_FORM_DIRECTIVES, Validators } from '@angular/forms';

@Component({
  moduleId: module.id,
  selector: 'fac-home',
  template: `
    <form [formGroup]="applicationForm" (ngSubmit)="onSubmit()"></form>
    `,
  directives: [REACTIVE_FORM_DIRECTIVES]
})
export class HomeComponent implements OnInit {

  // Setup Form
  private email_regex = '[a-z0-9\\.\\-\\_]+@[a-z0-9\\.\\-\\_]+\\.[a-z0-9\\.\\-\\_]+';
  applicationForm: FormGroup;
  validation_errors: Array<string> = [];

  constructor(private formBuilder: FormBuilder) {}

  onSubmit() {}

  ngOnInit(): any {
    this.applicationForm = this.formBuilder.group({
      first_name: ['', Validators.required],
      last_name: ['', [Validators.required]],
      email: ['', [Validators.required, Validators.pattern(this.email_regex)]]
    });
  }

}

```

Full error message:

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in http://localhost:5555/app/+home/home.component.js class HomeComponent_Host - inline template:0:0
ORIGINAL EXCEPTION: No provider for NewFormBuilder!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:4412:27)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:4529:20)
    at new NoProviderError (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:4565:20)
    at ReflectiveInjector_._throwOrNull (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:6461:23)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:6489:29)
    at ReflectiveInjector_._getByKey (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:6452:29)
    at ReflectiveInjector_.get (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:6261:25)
    at ElementInjector.get (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:11873:52)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:6486:28)
    at ReflectiveInjector_._getByKey (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:6452:29)
ERROR CONTEXT:
[object Object]
```

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by factoryberlin** [comment]
Btw: The name `NewFormProvider` doesn't appear anywhere in my code. I have no idea where it comes from.

**Comment by sod** [comment]
Try to change in your `main.ts`

`import { disableDeprecatedForms, provideForms } from '@angular/forms/index';`
to
`import { disableDeprecatedForms, provideForms } from '@angular/forms';`

**Comment by factoryberlin** [comment]
That did the trick. Thank you.

Still wondering: Where is `NewFormProvider` coming from?
