### ISSUE TITLE
Improve errors for not exported factories in modules

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#10436]
**I'm submitting a feature request**

Given the following configuration:

```
{
          provide: LocationStrategy,
          useFactory: provideLocationStrategy,
          deps: [
            PlatformLocation, [new Inject(APP_BASE_HREF), new Optional()], ROUTER_CONFIGURATION
          ]
        }
```

and

```
function provideLocationStrategy(
    platformLocationStrategy: PlatformLocation, baseHref: string, options: ExtraOptions = {}) {
  return options.useHash ? new HashLocationStrategy(platformLocationStrategy, baseHref) :
                           new PathLocationStrategy(platformLocationStrategy, baseHref);
}
```

we see the following error: 

```
Error at /usr/local/google/home/stephenfluin/workspace/cms/app/app.module.ngfactory.ts:255:88: Property 'provideLocationStrategy' does not exist on type 'typeof "/usr/local/google/home/stephenfluin/workspace/cms/node_modules/@angular/router/src/router...'.
    at check (/usr/local/google/home/stephenfluin/workspace/cms/node_modules/@angular/tsc-wrapped/src/tsc.js:30:15)
    at Tsc.typeCheck (/usr/local/google/home/stephenfluin/workspace/cms/node_modules/@angular/tsc-wrapped/src/tsc.js:76:9)
    at /usr/local/google/home/stephenfluin/workspace/cms/node_modules/@angular/tsc-wrapped/src/main.js:28:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
Compilation failed
```

The error is due to the fact that the function is not exported. Can we identify this mistake and provide a useful error message so that it is more actionable for the module developer?

cc @vsavkin

**Comment by laco0416** [comment]
Fixed in latest router-builds. 

https://github.com/angular/angular/commit/8dc82a00806d262c7b851cb68403ba3262645f10

**Comment by JoostK** [comment]
This was added in #10951 back in 2016
