### ISSUE TITLE
Using the latest builds of Angular 2 gives me the following error: “No provider for NgControl: in NgModule DynamicModule”

### ISSUE THREAD

**Issue by balteo** [angular/angular#10476]
**I'm submitting a** :
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I get the following error message upon application startup (since switching to using latest dependencies from master from Github):

```
zone.js:463 Error: Uncaught (in promise): Error: Error: Provider parse errors:
    No provider for NgControl: in NgModule DynamicModule
        at new BaseException (http://localhost:8080/vendor/@angular/compiler/src/facade/exceptions.js:27:23)
        at NgModuleProviderAnalyzer.parse (http://localhost:8080/vendor/@angular/compiler/src/provider_analyzer.js:291:19)
        at NgModuleCompiler.compile (http://localhost:8080/vendor/@angular/compiler/src/ng_module_compiler.js:57:24)
        at RuntimeCompiler._compileModule (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:121:56)
        at RuntimeCompiler._compileModuleAndComponents (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:74:36)
        at RuntimeCompiler.compileModuleAsync (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:50:21)
        at PlatformRef_.bootstrapModule (http://localhost:8080/vendor/@angular/core/src/application_ref.js:361:25)
        at Object.bootstrap (http://localhost:8080/vendor/@angular/platform-browser-dynamic/index.js:73:10)
        at Object.eval (http://localhost:8080/main.js:23:28)
        at eval (http://localhost:8080/main.js:46:4)
    Evaluating http://localhost:8080/main.js
    Error loading http://localhost:8080/main.js
        at new BaseException (http://localhost:8080/vendor/@angular/compiler/src/facade/exceptions.js:27:23)
        at NgModuleProviderAnalyzer.parse (http://localhost:8080/vendor/@angular/compiler/src/provider_analyzer.js:291:19)
        at NgModuleCompiler.compile (http://localhost:8080/vendor/@angular/compiler/src/ng_module_compiler.js:57:24)
        at RuntimeCompiler._compileModule (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:121:56)
        at RuntimeCompiler._compileModuleAndComponents (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:74:36)
        at RuntimeCompiler.compileModuleAsync (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:50:21)
        at PlatformRef_.bootstrapModule (http://localhost:8080/vendor/@angular/core/src/application_ref.js:361:25)
        at Object.bootstrap (http://localhost:8080/vendor/@angular/platform-browser-dynamic/index.js:73:10)
        at Object.eval (http://localhost:8080/main.js:23:28)
        at eval (http://localhost:8080/main.js:46:4)
    Evaluating http://localhost:8080/main.js
    Error loading http://localhost:8080/main.js
    at resolvePromise (http://localhost:8080/vendor/zone.js/dist/zone.js:538:32)
    at resolvePromise (http://localhost:8080/vendor/zone.js/dist/zone.js:523:18)
    at http://localhost:8080/vendor/zone.js/dist/zone.js:571:18
    at ZoneDelegate.invokeTask (http://localhost:8080/vendor/zone.js/dist/zone.js:356:38)
    at Zone.runTask (http://localhost:8080/vendor/zone.js/dist/zone.js:256:48)
    at drainMicroTaskQueue (http://localhost:8080/vendor/zone.js/dist/zone.js:474:36)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:8080/vendor/zone.js/dist/zone.js:426:22)
```
Here is the dependencies section of my `package.json`:

```
"dependencies": {
    "@angular/common": "git+https://github.com/angular/common-builds.git#master",
    "@angular/compiler": "git+https://github.com/angular/compiler-builds.git#master",
    "@angular/core": "git+https://github.com/angular/core-builds.git#master",
    "@angular/forms": "git+https://github.com/angular/forms-builds.git#master",
    "@angular/http": "git+https://github.com/angular/http-builds.git#master",
    "@angular/platform-browser": "git+https://github.com/angular/platform-browser-builds.git#master",
    "@angular/platform-browser-dynamic": "git+https://github.com/angular/platform-browser-dynamic-builds.git#master",
    "@angular/router": "git+https://github.com/angular/router-builds.git#master",
    "angular2-moment": "^0.8.1",
    "bootstrap": "3.3.6",
    "es6-shim": "0.35.1",
    "moment": "^2.13.0",
    "ng2-bootstrap": "^1.0.23",
    "ng2-translate": "^2.2.2",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "0.6.12"
  },
```

**Expected/desired behavior**

The application used to load properly before I switched to latest versions of angular 2 (master from github). 

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X (latest from github master as of August 3rd 2016)
 
* **Browser:** [Chrome ] 
 
* **Language:** [TypeScript X.X] 

I have opened a SO question here: http://stackoverflow.com/questions/38749343

**Comment by qdouble** [comment]
Are you bootstrapping with ngModules? Currently, you have to declare your directives in ngModules if you're using latest builds. You may want to use angular-builds sha from before ngModules was merged unless you are using it.

**Comment by balteo** [comment]
@qdouble 

Here is how I bootstrap the application:
```
import {bootstrap} from "@angular/platform-browser-dynamic";
import {enableProdMode} from "@angular/core";
import {Title} from "@angular/platform-browser";
import {provideRouter} from "@angular/router";
import {LocationStrategy, HashLocationStrategy} from "@angular/common";
import {HTTP_PROVIDERS, Http, RequestOptions} from "@angular/http";
import {
  TRANSLATE_PROVIDERS,
  TranslateService,
  TranslateLoader,
  TranslateStaticLoader
} from "ng2-translate/ng2-translate";
import {AppComponent} from "./app/app.component";
import {SessionService} from "./app/session/session.service";
import {UserAccountService} from "./app/useraccount/useraccount.service";
import {ApplicationRequestOptions} from "./app/session/session.utils";
import {StylingService} from "./app/shared/services/styling.service";
import {AppRoutes} from "./app/routes/app.routes";
import {environment} from "./app/environment";
import {FormBuilder, REACTIVE_FORM_DIRECTIVES/*, provideForms, disableDeprecatedForms*/} from "@angular/forms";
import {PasswordValidationService} from "./app/shared/services/password-validation.service";
import {validatePassword} from "./app/shared/validators/password.validator";
import 'rxjs/add/operator/do';
import {AuthenticatedHttpClient} from "./app/shared/services/authenticated-http-client.service";

if (environment.production) {
  enableProdMode();
}

bootstrap(AppComponent, [
  provideRouter(AppRoutes),
  HTTP_PROVIDERS,
  TRANSLATE_PROVIDERS,
  Title,
  FormBuilder,
  REACTIVE_FORM_DIRECTIVES,
  SessionService,
  UserAccountService,
  AuthenticatedHttpClient,
  StylingService,
  TranslateService,
  PasswordValidationService,
  {provide: RequestOptions, useClass: ApplicationRequestOptions},
  {provide: LocationStrategy, useClass: HashLocationStrategy},
  {
    provide: TranslateLoader,
    useFactory: (http:Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'), deps: [Http]
  }
]);
```

What do you mean by **ngModules**?

This: `@AppModule(...`?

**Comment by qdouble** [comment]
@balteo an example of bootstrapping with ngModules is here: https://plnkr.co/edit/wmgFGqy36srcRCA5F5hY?p=info

Although, as of yesterday's commits, you also have to use ngDoBootstrap, an example of that is here: https://github.com/angular/angular/blob/7e4fd7d7da5795f09164ff3b16c5e45eab05f85a/modules/%40angular/compiler-cli/integrationtest/src/module.ts and another example of modifying an app to use ngModules and lazy loading here: https://github.com/brandonroberts/angular2-webpack/commit/6eca5a3e71dfd517551be14453eba611eef0e5df

If it's a bit confusing, you may want to wait until they release docs for it or go back to a build before ngModules was introduced.

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that got resolved.
