### ISSUE TITLE
Issue with metadata_resolver.ts's getTransitiveModules function

### ISSUE THREAD

**Issue by balteo** [angular/angular#10497]
**I'm submitting a:**
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

from **metadata_resolver.ts**:

```
function getTransitiveModules(
    modules: cpl.CompileNgModuleMetadata[], includeImports: boolean,
    targetModules: cpl.CompileNgModuleMetadata[] = [],
    visitedModules = new Set<Type>()): cpl.CompileNgModuleMetadata[] {
  modules.forEach((ngModule) => {
    if (!visitedModules.has(ngModule.type.runtime)) {
      visitedModules.add(ngModule.type.runtime);
      const nestedModules = includeImports ?
          ngModule.importedModules.concat(ngModule.exportedModules) :
          ngModule.exportedModules;
      getTransitiveModules(nestedModules, includeImports, targetModules, visitedModules);
      // Add after recursing so imported/exported modules are before the module itself.
      // This is important for overwriting providers of imported modules!
      targetModules.push(ngModule);
    }
  });
  return targetModules;
}
```
Debug stack trace shows that a null object is included in the array:

`modules = [CompileNgModuleMetadata, CompileNgModuleMetadata, CompileNgModuleMetadata, null]
`

Causing the following error:

```
zone.js:461 Unhandled Promise rejection: TypeError: Cannot read property 'type' of null
	    at eval (http://localhost:8080/vendor/@angular/compiler/src/metadata_resolver.js:698:41)
	    at Array.forEach (native)
	    at getTransitiveModules (http://localhost:8080/vendor/@angular/compiler/src/metadata_resolver.js:697:13)
	    at CompileMetadataResolver._getTransitiveNgModuleMetadata (http://localhost:8080/vendor/@angular/compiler/src/metadata_resolver.js:411:33)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8080/vendor/@angular/compiler/src/metadata_resolver.js:283:43)
	    at RuntimeCompiler._compileComponents (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:151:47)
	    at RuntimeCompiler._compileModuleAndComponents (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:73:37)
	    at RuntimeCompiler.compileModuleAsync (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:50:21)
	    at PlatformRef_.bootstrapModule (http://localhost:8080/vendor/@angular/core/src/application_ref.js:361:25)
	    at Object.eval (http://localhost:8080/main.js:10:47)
	Evaluating http://localhost:8080/main.js
	Error loading http://localhost:8080/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: TypeError: Cannot read property 'type' of null
	    at eval (http://localhost:8080/vendor/@angular/compiler/src/metadata_resolver.js:698:41)
	    at Array.forEach (native)
	    at getTransitiveModules (http://localhost:8080/vendor/@angular/compiler/src/metadata_resolver.js:697:13)
	    at CompileMetadataResolver._getTransitiveNgModuleMetadata (http://localhost:8080/vendor/@angular/compiler/src/metadata_resolver.js:411:33)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8080/vendor/@angular/compiler/src/metadata_resolver.js:283:43)
	    at RuntimeCompiler._compileComponents (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:151:47)
	    at RuntimeCompiler._compileModuleAndComponents (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:73:37)
	    at RuntimeCompiler.compileModuleAsync (http://localhost:8080/vendor/@angular/compiler/src/runtime_compiler.js:50:21)
	    at PlatformRef_.bootstrapModule (http://localhost:8080/vendor/@angular/core/src/application_ref.js:361:25)
	    at Object.eval (http://localhost:8080/main.js:10:47)
	Evaluating http://localhost:8080/main.js
	Error loading http://localhost:8080/main.js
```

**Reproduction of the problem**

Here is my **main.ts**

```
import {enableProdMode} from "@angular/core";
import * as platform from "@angular/platform-browser-dynamic";
import {environment} from "./app/environment";
import "rxjs/add/operator/do";
import {AppModule} from "./app/app.component";

if (environment.production) {
  enableProdMode();
}

console.log(platform.platformBrowserDynamic().bootstrapModule(AppModule));
```

and my **app.component.ts**:

```
import {Component, OnInit, ApplicationRef, NgModule} from "@angular/core";
import {FormsModule} from "@angular/forms";
import {Title, BrowserModule} from "@angular/platform-browser";
import {ROUTER_DIRECTIVES, ActivatedRoute, RouterModule} from "@angular/router";
import {
  TranslateService,
  TranslateLoader,
  TranslateStaticLoader
} from "ng2-translate/ng2-translate";
import {NavbarComponent} from "./shared/components/navbar.component";
import {FooterComponent} from "./shared/components/footer.component";
import {SigninComponent} from "./session/session.signin.component";
import {HomeComponent} from "./home/components/home.component";
import {SessionService} from "./session/session.service";
import {UserAccountService} from "./useraccount/useraccount.service";
import {LocationStrategy, HashLocationStrategy} from "@angular/common";
import {StylingService} from "./shared/services/styling.service";
import {PasswordValidationService} from "./shared/services/password-validation.service";
import {AppRoutes} from "./routes/app.routes";
import {AuthenticatedHttpClient} from "./shared/services/authenticated-http-client.service";
import {Http} from "@angular/http";
import "moment/locale/fr";
import * as moment from "moment";

@Component({
  selector: 'app',
  template: `
              <section class="container-fluid row Conteneur">
                 <navbar></navbar>
                 <section class="container">
                    <router-outlet (onActivate)="setTitle($event)"></router-outlet>
                 </section>
              </section>
              <section class="container-fluid">  
                <footer></footer>
              </section>
              `,
  directives: [NavbarComponent, FooterComponent, SigninComponent, HomeComponent, ROUTER_DIRECTIVES]
})
export class AppComponent implements OnInit {

  constructor(private translate:TranslateService,
              private sessionService:SessionService,
              private titleService:Title,
              private activatedRoute:ActivatedRoute) {
    let userLang = 'fr';
    translate.use(userLang);
    moment.locale(userLang);
  }

  ngOnInit() {
    this.sessionService.reloadPersonalInfo();
  }

  setTitle($event) {
    //FIXME: remove console.log below later on:
    console.log($event);

    this.translate.get(this.activatedRoute.snapshot.data['titleKey'])
      .subscribe(translation=>this.titleService.setTitle(translation));
  }
}

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot(AppRoutes),
    FormsModule,
    HomeComponent
  ],
  providers: [
    SessionService,
    UserAccountService,
    AuthenticatedHttpClient,
    StylingService,
    TranslateService,
    PasswordValidationService,
    {provide: LocationStrategy, useClass: HashLocationStrategy},
    {
      provide: TranslateLoader,
      useFactory: (http:Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'), deps: [Http]
    }],
  entryComponents: [
    AppComponent,
    HomeComponent
  ]
})
export class AppModule {

  ngDoBootstrap(appRef:ApplicationRef) {
    appRef.bootstrap(AppComponent);
  }
}
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X (latest from github master as of August 4th)
 
* **Browser:** [Chrome] 
 
* **Language:** [TypeScript] 

Can anyone please tell me what could cause this issue? Is this a bug or a problem in my configuration? Couldn't the error message be more explicit?

**Comment by balteo** [comment]
@tbosch 

I have pinpointed where the `TypeError` is raised. See problematic line from `getTransitiveModules()` [here](https://github.com/angular/angular/blob/46b212706b9162c22fb1523032d7e37c9155015a/modules/@angular/compiler/src/metadata_resolver.ts#L690).

The trouble is that if and when the `ngModule` variable is **null**, it causes the application not to bootstrap and a `TypeError` is raised with the following message:

`TypeError: Cannot read property 'type' of null`

The error message should be more explicit. By the way is it a bug?

**Comment by vthinkxie** [comment]
+1

**Comment by balteo** [comment]
I can confirm it does also affect **2.0.0-rc.5**.

**Comment by balteo** [comment]
Here is the updated **`NgModule`** class with `bootstrap` instead of `entryComponents`:

```
import {Component, OnInit, ApplicationRef, NgModule} from "@angular/core";
import {FormsModule} from "@angular/forms";
import {Title, BrowserModule} from "@angular/platform-browser";
import {ROUTER_DIRECTIVES, ActivatedRoute, RouterModule} from "@angular/router";
import {
  TranslateService,
  TranslateLoader,
  TranslateStaticLoader
} from "ng2-translate/ng2-translate";
import {NavbarComponent} from "./shared/components/navbar.component";
import {FooterComponent} from "./shared/components/footer.component";
import {SigninComponent} from "./session/session.signin.component";
import {HomeComponent} from "./home/components/home.component";
import {SessionService} from "./session/session.service";
import {UserAccountService} from "./useraccount/useraccount.service";
import {LocationStrategy, HashLocationStrategy} from "@angular/common";
import {StylingService} from "./shared/services/styling.service";
import {PasswordValidationService} from "./shared/services/password-validation.service";
import {AppRoutes} from "./routes/app.routes";
import {AuthenticatedHttpClient} from "./shared/services/authenticated-http-client.service";
import {Http} from "@angular/http";
import "moment/locale/fr";
import * as moment from "moment";
import {PrivateNavbarComponent} from "./shared/components/private-navbar.component";
import {PublicNavbarComponent} from "./shared/components/public-navbar.component";
import {SignupComponent} from "./signup/signup.component";
import {SendPasswordResetInformationComponent} from "./useraccount/password/send-password-reset-information.component";
import {PasswordResetComponent} from "./useraccount/password/password-reset.component";
import {DashboardComponent} from "./dashboard/dashboard.component";
import {DashboardSummaryComponent} from "./dashboard/dashboard-summary.component";
import {MessageSummaryComponent} from "./message/summary/message-summary.component";
import {MessageConversationComponent} from "./message/conversation/message-conversation.component";
import {UserAccountComponent} from "./useraccount/useraccount.component";
import {UserAccountSummaryComponent} from "./useraccount/summary/useraccount-summary.component";
import {UserAccountAddressComponent} from "./useraccount/address/useraccount-address.component";
import {UserAccountEmailComponent} from "./useraccount/email/useraccount-email.component";
import {UserAccountEmailNotificationComponent} from "./useraccount/emailnotification/useraccount-emailnotification.component";
import {UserAccountFirstNameComponent} from "./useraccount/firstname/useraccount-firstname.component";
import {UserAccountPasswordComponent} from "./useraccount/password/useraccount-password.component";

@Component({
  selector: 'app',
  template: `
              <section class="container-fluid row Conteneur">
                 <navbar></navbar>
                 <section class="container">
                    <router-outlet (onActivate)="setTitle($event)"></router-outlet>
                 </section>
              </section>
              <section class="container-fluid">  
                <footer></footer>
              </section>
              `,
  directives: [NavbarComponent, FooterComponent, SigninComponent, HomeComponent, ROUTER_DIRECTIVES]
})
export class AppComponent implements OnInit {

  constructor(private translate:TranslateService,
              private sessionService:SessionService,
              private titleService:Title,
              private activatedRoute:ActivatedRoute) {
    let userLang = 'fr';
    translate.use(userLang);
    moment.locale(userLang);
  }

  ngOnInit() {
    this.sessionService.reloadPersonalInfo();
  }

  setTitle($event) {
    //FIXME: remove console.log below later on:
    console.log($event);

    this.translate.get(this.activatedRoute.snapshot.data['titleKey'])
      .subscribe(translation=>this.titleService.setTitle(translation));
  }
}

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    SignupComponent,
    SigninComponent,
    SendPasswordResetInformationComponent,
    PasswordResetComponent,
    DashboardComponent,
    DashboardSummaryComponent,
    MessageSummaryComponent,
    MessageConversationComponent,
    UserAccountComponent,
    UserAccountSummaryComponent,
    UserAccountAddressComponent,
    UserAccountEmailComponent,
    UserAccountEmailNotificationComponent,
    UserAccountFirstNameComponent,
    UserAccountPasswordComponent,
    FooterComponent,
    NavbarComponent,
    PrivateNavbarComponent,
    PublicNavbarComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot(AppRoutes),
    FormsModule,
    HomeComponent,
    SignupComponent,
    SigninComponent,
    SendPasswordResetInformationComponent,
    PasswordResetComponent,
    DashboardComponent,
    DashboardSummaryComponent,
    MessageSummaryComponent,
    MessageConversationComponent,
    UserAccountComponent,
    UserAccountSummaryComponent,
    UserAccountAddressComponent,
    UserAccountEmailComponent,
    UserAccountEmailNotificationComponent,
    UserAccountFirstNameComponent,
    UserAccountPasswordComponent,
    FooterComponent,
    NavbarComponent,
    PrivateNavbarComponent,
    PublicNavbarComponent
  ],
  providers: [
    SessionService,
    UserAccountService,
    AuthenticatedHttpClient,
    StylingService,
    TranslateService,
    PasswordValidationService,
    {provide: LocationStrategy, useClass: HashLocationStrategy},
    {
      provide: TranslateLoader,
      useFactory: (http:Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'), deps: [Http]
    }],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule {

  ngDoBootstrap(appRef:ApplicationRef) {
    appRef.bootstrap(AppComponent);
  }
}

```

**Comment by pkozlowski-opensource** [comment]
@balteo please provide a minimal reproduce scenario using plunker - it is impossible to see what is going on otherwise. As such it is not actionable without a reproduce scenario and will be closed.

**Comment by bennyp123** [comment]
Are you using angular-cli?

**Comment by balteo** [comment]
@pkozlowski-opensource I will be updating the issue with relevant information. I got the `@NgModule` wrong but still the error message could be improved.

@bennyp123 Yes I am indeed.

**Comment by balteo** [comment]
Using the following `@NgModule` configuration sorted the issue:

```
@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    SignupComponent,
    SigninComponent,
    SendPasswordResetInformationComponent,
    PasswordResetComponent,
    DashboardComponent,
    DashboardSummaryComponent,
    MessageSummaryComponent,
    MessageConversationComponent,
    UserAccountComponent,
    UserAccountSummaryComponent,
    UserAccountAddressComponent,
    UserAccountEmailComponent,
    UserAccountEmailNotificationComponent,
    UserAccountFirstNameComponent,
    UserAccountPasswordComponent,
    TextCounterComponent,
    FooterComponent,
    NavbarComponent,
    PrivateNavbarComponent,
    PublicNavbarComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot(AppRoutes, {useHash: true}),
    FormsModule
  ],
  providers: [
    HTTP_PROVIDERS,
    FormBuilder,
    Title,
    SessionService,
    UserAccountService,
    AuthenticatedHttpClient,
    StylingService,
    TranslateService,
    PasswordValidationService,
    {
      provide: TranslateLoader,
      useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'), deps: [Http]
    }],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule {

  ngDoBootstrap(appRef: ApplicationRef) {
    appRef.bootstrap(AppComponent);
  }
}
```

Following the guide here [NgModule](https://angular.io/docs/ts/latest/guide/ngmodule.html) helped.

However, the error message in case of a misconfiguration should be more explicit.

**Comment by sqlsolver** [comment]
#https://github.com/angular/angular/issues/10671 seems identical. I am experiencing this also with RC5 and am reading through the same documentation of NgModule. Thanks for posting your resolution. This should perhaps be an issue so that at least the line/module where it fails is included in the error.
