### ISSUE TITLE
DI bug?

### ISSUE THREAD

**Issue by davidgfolch** [angular/angular#10525]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using this in an injected service makes DI fail with the following error:

Error: Error: Invalid provider - only instances of Provider and Type are allowed, got: undefined
	    at InvalidProviderError.BaseException [as constructor] (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:4412:27)
	    at new InvalidProviderError (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:4670:20)
	    at eval (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:5622:23)
	    at Array.forEach (native)
	    at _normalizeProviders (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:5605:19)
	    at eval (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:5616:17)
	    at Array.forEach (native)
	    at _normalizeProviders (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:5605:19)
	    at resolveReflectiveProviders (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:5565:26)
	    at Function.ReflectiveInjector.resolve (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:6042:20)
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ (index):142ZoneDelegate.invoke @ zone.js?1470401390504:323Zone.run @ zone.js?1470401390504:216(anonymous function) @ zone.js?1470401390504:571ZoneDelegate.invokeTask @ zone.js?1470401390504:356Zone.runTask @ zone.js?1470401390504:256drainMicroTaskQueue @ zone.js?1470401390504:474ZoneTask.invoke @ zone.js?1470401390504:426

  ```
AUTHORITY_ADMIN:string='ADMIN_AUTHORITY'; // if you use this on COMPONENT_AUTHORITIES breaks DI
  COMPONENT_AUTHORITIES:{ [key:string]: Array<string> } = {
    'UserListComponent':[AUTHORITY_ADMIN]
  };
```

but this works:
  ```
AUTHORITY_ADMIN:string='ADMIN_AUTHORITY'; // if you use this on COMPONENT_AUTHORITIES breaks DI
  COMPONENT_AUTHORITIES:{ [key:string]: Array<string> } = {
    'UserListComponent':['ADMIN_AUTHORITY']
  };
```

**Expected/desired behavior**

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript]

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by davidgfolch** [comment]
This is not a support request, DI fails when I use a constant inside the array in COMPONENT_AUTHORITIES object.  Otherwise works!
