### ISSUE TITLE
Importing HTTP_PROVIDERS causes ngc to blow up

### ISSUE THREAD

**Issue by mertdeg** [angular/angular#10550]
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
1. Create an app that uses import {HTTP_PROVIDERS} from "@angular/http";
2. Compile this app with "ngc -p ."
3. You will see following error:

__symbolic=reference
module=./src/backends/xhr_backend
name=CookieXSRFStrategy
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol HTTP_PROVIDERS in /var/www/common/lib/ts/common/tscomp/node_modules/@angular/http/http.d.ts, resolving symbol EqsiftIndexMain in /var/www/common/lib/ts/common/tscomp/app/eqsift/lib/ts/index/EqsiftIndexMain.ts, resolving symbol EqsiftIndexMain in /var/www/common/lib/ts/common/tscomp/app/eqsift/lib/ts/index/EqsiftIndexMain.ts
    at simplifyInContext (/var/www/common/lib/ts/common/tscomp/node_modules/@angular/compiler-cli/src/static_reflector.js:431:23)
    at StaticReflector.simplify (/var/www/common/lib/ts/common/tscomp/node_modules/@angular/compiler-cli/src/static_reflector.js:434:22)
    at StaticReflector.annotations (/var/www/common/lib/ts/common/tscomp/node_modules/@angular/compiler-cli/src/static_reflector.js:52:36)
    at DirectiveResolver.resolve (/var/www/common/lib/ts/common/tscomp/node_modules/@angular/compiler/src/directive_resolver.js:26:44)
    at CompileMetadataResolver.getDirectiveMetadata (/var/www/common/lib/ts/common/tscomp/node_modules/@angular/compiler/src/metadata_resolver.js:108:51)
    at CompileMetadataResolver.maybeGetDirectiveMetadata (/var/www/common/lib/ts/common/tscomp/node_modules/@angular/compiler/src/metadata_resolver.js:180:25)
    at CodeGenerator.readComponents (/var/www/common/lib/ts/common/tscomp/node_modules/@angular/compiler-cli/src/codegen.js:69:39)
    at generateOneFile (/var/www/common/lib/ts/common/tscomp/node_modules/@angular/compiler-cli/src/codegen.js:94:38)
    at Array.map (native)
    at CodeGenerator.codegen (/var/www/common/lib/ts/common/tscomp/node_modules/@angular/compiler-cli/src/codegen.js:115:14)


**Expected/desired behavior**


**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).



**What is the expected behavior?**
If you use "import {Http} from "@angular/http";" everything works fine. The error message is cryptic.


**What is the motivation / use case for changing the behavior?**



**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by IgorMinar** [comment]
please us rc5 and import http via the new HttpModule
