### ISSUE TITLE
Angular 2.0.0-rc.5 - Regression with Forms / ControlValueAccessor

### ISSUE THREAD

**Issue by danieleds** [angular/angular#10897]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We cannot provide a custom value accessors without specifying the `ngDefaultControl` attribute.
If you try, you get this fatal error:
```
Error: No value accessor for form control with unspecified name attribute
    at new BaseException (https://npmcdn.com/@angular/forms/src/facade/exceptions.js:27:23)
    at _throwError (https://npmcdn.com/@angular/forms/src/directives/shared.js:69:11)
    at Object.setUpControl (https://npmcdn.com/@angular/forms/src/directives/shared.js:30:9)
    at NgModel._setUpStandalone (https://npmcdn.com/@angular/forms/src/directives/ng_model.js:97:18)
    at NgModel._setUpControl (https://npmcdn.com/@angular/forms/src/directives/ng_model.js:89:37)
    at NgModel.ngOnChanges (https://npmcdn.com/@angular/forms/src/directives/ng_model.js:48:18)
    at DebugAppView._View_App0.detectChangesInternal (App.ngfactory.js:93:47)
    at DebugAppView.AppView.detectChanges (https://npmcdn.com/@angular/core/bundles/core.umd.js:12586:18)
    at DebugAppView.detectChanges (https://npmcdn.com/@angular/core/bundles/core.umd.js:12691:48)
    at DebugAppView.AppView.detectViewChildrenChanges (https://npmcdn.com/@angular/core/bundles/core.umd.js:12612:23)
```

**Expected/desired behavior**
We should be able to define custom value accessors without the need to add `ngDefaultControl`, which is what happened in rc4 and previous versions.

**Reproduction of the problem**
http://plnkr.co/edit/EtjbSQ0U7jlM9PvmLaPy?p=preview

Go to `src/app.ts` and remove the `ngDefaultControl` attribute: the app will fail, even if an appropriate ControlValueAccessor is provided.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** all 
 
* **Language:** TypeScript 1.8.10

**Comment by kara** [comment]
@danieleds When you create a custom value accessor, you have to declare it in your module declarations or it won't be found.  Also, it looks like you're using symbols from the deprecated forms API in `@angular/common`. When you fix these two things, the form works as expected: http://plnkr.co/edit/8FduduZp2VJuz3zc6XcS?p=preview.
