### ISSUE TITLE
bug(compiler) DI token for third-party-library crashes the AOT compiler

### ISSUE THREAD

**Issue by choeller** [angular/angular#11034]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Trying to provide a token for a a third-party-library object lets the AOT compiler crash. Having a Module like this:

``` ts
import * as io from 'socket.io-client';

@NgModule({
  providers: [
    ...
    {provide: "SocketIO", useValue: io},
  ],
  ...
})
export class AppModule {
}
```

calling

```
./node_modules/.bin/ngc -p ./src
```

throws the following exception:

```
Error: Internal error: unknown identifier [object Object]
    at new BaseException (/home/christoph/buch/sources/project-manager-reactive-2/node_modules/@angular/core/src/facade/exceptions.js:27:23)
    at _TsEmitterVisitor._visitIdentifier (/home/christoph/buch/sources/project-manager-reactive-2/node_modules/@angular/compiler/src/output/ts_emitter.js:293:19)
    at _TsEmitterVisitor.visitExternalExpr (/home/christoph/buch/sources/project-manager-reactive-2/node_modules/@angular/compiler/src/output/ts_emitter.js:84:14)
    at ExternalExpr.visitExpression (/home/christoph/buch/sources/project-manager-reactive-2/node_modules/@angular/compiler/src/output/output_ast.js:348:24)
    at _TsEmitterVisitor.AbstractEmitterVisitor.visitWritePropExpr (/home/christoph/buch/sources/project-manager-reactive-2/node_modules/@angular/compiler/src/output/abstract_emitter.js:185:20)
    at WritePropExpr.visitExpression (/home/christoph/buch/sources/project-manager-reactive-2/node_modules/@angular/compiler/src/output/output_ast.js:265:24)
    at _TsEmitterVisitor.AbstractEmitterVisitor.visitExpressionStmt (/home/christoph/buch/sources/project-manager-reactive-2/node_modules/@angular/compiler/src/output/abstract_emitter.js:104:19)
    at ExpressionStatement.visitStatement (/home/christoph/buch/sources/project-manager-reactive-2/node_modules/@angular/compiler/src/output/output_ast.js:562:24)
    at /home/christoph/buch/sources/project-manager-reactive-2/node_modules/@angular/compiler/src/output/abstract_emitter.js:384:58
    at Array.forEach (native)
c
```

after some research it looks like the aot compiler is iterating over all tokens and tries to precompile them, but that doesn't work for the provided function

**Expected/desired behavior**

it should be possible to provide functions from third-party-libraries when using the AOT compiler

**Please tell us about your environment:**
- **Angular version:** commit 9883e19e2e2839043557ae89740a8f6b299680d2
- **Browser:** [all  ] 
- **Language:** [all ]

**Comment by sod** [comment]
If the token is not available on compile time you have to provide it as an exported factory:

```typescript
import * as io from 'socket.io-client';

export function socketIoFactory {
    return io;
}

@NgModule({
  providers: [
    ...
    {provide: "SocketIO", useFactory: socketIoFactory},
  ],
  ...
})
export class AppModule {
}
```

**Comment by choeller** [comment]
Cool, that seems to work as a workaround. Nevertheless the other Implementation should at least provide another error message. So it works on dynamic-platform and there is no way to know, why this crashes the compiler in case of AOT

**Comment by sod** [comment]
Maybe https://github.com/angular/angular/pull/10947 already addresses this for rc.6. But haven't tested it yet.

**Comment by DzmitryShylovich** [comment]
@choeller @sod It should be fixed. Can you pls test and close the issue? thx

**Comment by JoostK** [comment]
This issue has been resolved in the Ivy compiler.
