### ISSUE TITLE
Error Cannot read property 'injector' of null when injecting a @Injectable() component

### ISSUE THREAD

**Issue by StefH** [angular/angular#11165]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Angular2 component is defined as:
```js
@Injectable()
export class ODataServiceFactory {

    constructor(private http: Http, private config: ODataConfiguration) {
    }

    . . .
}
```

The test is defined as:
```js
describe('ODataService - ', function () {
    TestBed.resetTestEnvironment();

    beforeEach(() => {
        TestBed.configureTestingModule({
            providers: [
                BaseRequestOptions,
                MockBackend,
                {
                    provide: Http, useFactory: (backend: ConnectionBackend, defaultOptions: BaseRequestOptions) => {
                        return new Http(backend, defaultOptions);
                    },
                    deps: [MockBackend, BaseRequestOptions]
                },
                {
                    provide: ODataConfiguration, useFactory: () => {
                        return new ODataConfiguration();
                    }
                },
                ODataServiceFactory
            ],
            imports: [
                HttpModule
            ]
        });
    });

    it('Construct via injected factory', inject([ ODataServiceFactory ], (factory: ODataServiceFactory) => {
        // Act
        let service = factory.CreateService<IEmployee>('Employees');

        // Assert
        assert.isNotNull(service);
    }));
});
```

**testbed error**
```
2) ODataService -  Construct via injected factory:
     TypeError: Cannot read property 'injector' of null
      at TestBed._createCompilerAndModule (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\@angular\core\testing\test_bed.js:246:44)
      at TestBed._initIfNeeded (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\@angular\core\testing\test_bed.js:213:39)
      at TestBed.execute (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\@angular\core\testing\test_bed.js:274:14)
      at Context.<anonymous> (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\@angular\core\testing\test_bed.js:404:45)
      at callFn (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runnable.js:334:21)
      at Test.Runnable.run (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runnable.js:327:7)
      at Runner.runTest (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:429:10)
      at C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:535:12
      at next (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:349:14)
      at C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:359:7
      at next (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:285:14)
      at C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:322:7
      at done (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runnable.js:291:5)
      at callFn (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runnable.js:352:7)
      at Hook.Runnable.run (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runnable.js:327:7)
      at next (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:299:10)
      at Immediate.<anonymous> (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:327:5)
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5

* **Unit test environment:** [Mocha]
 
* **Language:** [TypeScript]

**Comment by vicb** [comment]
This sounds like a support request but we should do a better job with error messages.
/cc @juliemr

**Comment by StefH** [comment]
So is this an error in Angular2 related to Mocha testing ? Or am I using the code in wrong way ?

**Comment by sgrinich** [comment]
My project does not include Mocha but I have this same problem. Is this confirmed as a bug in RC5?

**Comment by juliemr** [comment]
Agreed that we should have a better error message - @StefH why are you calling `TestBed.resetTestEnvironment`? I'm pretty sure that's why you're getting this error.

**Comment by sgrinich** [comment]
@juliemr I'm not including that call but still facing the same problem.

**Comment by StefH** [comment]
Indeed. With or without reset call gives same problem.

**Comment by sgrinich** [comment]
I've solved my issue (at least for the time being!). I simply needed to init the TestBed, like so: 

`  beforeEach(() => {
        TestBed.initTestEnvironment(
            BrowserDynamicTestingModule,
            platformBrowserDynamicTesting()
        ).configureTestingModule({
           ...
            ]});
    });`

Don't forget to include the import: 
`import {BrowserDynamicTestingModule, platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';
`

**Comment by StefH** [comment]
Now I get this error: **ReferenceError: window is not defined**

My code from **test spec file** is like:
```ts
describe('ODataService - ', function () {
    before(() => TestBedHelper.Init());

    beforeEach(() => {

        TestBed.configureTestingModule({
            providers: [
```

And my **TestBedHelper.ts** is like:
```ts
import { TestBed } from '@angular/core/testing/test_bed';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

export class TestBedHelper {

  public static Init() {
    TestBed.initTestEnvironment(
      BrowserDynamicTestingModule,
      platformBrowserDynamicTesting()
    );
  }
}

```

Any clue what I'm missing ?

**Comment by sgrinich** [comment]
I've never received this error so I'm afraid I can't be of too great help. I've never seen someone wrap the TestBed in a helper class like that. What was the reasoning behind moving it to another class if I may ask?

**Comment by StefH** [comment]
I moved to other class so that I can reuse it in other spec files.

**Comment by StefH** [comment]
@sgrinich if possible, can you post somewhere your project ?

**Comment by StefH** [comment]
OK, found the issue. Another injectable class uses this code:
```ts
@Injectable()
export class ODataConfiguration {
    baseUrl: string = window.location.origin + '/odata';
```

Which is not going to work because the **window** object is not available when running inside unit-test. Now I've to see how to solve this...

**Comment by StefH** [comment]
Thanks for all support.
Closing this issue now...
