### ISSUE TITLE
Error: Unexpected value 'undefined' imported by the module 'DynamicTestModule' after upgrading to RC.6

### ISSUE THREAD

**Issue by DcsMarcRemolt** [angular/angular#11238]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

All karma tests that utilize TestBed.compileComponents() die with the error

Error: Unexpected value 'undefined' imported by the module 'DynamicTestModule'

Stack:
Failed: Unexpected value 'undefined' imported by the module 'DynamicTestModule'
      Error: Unexpected value 'undefined' imported by the module 'DynamicTestModule'
          at webpack:///~/@angular/compiler/src/metadata_resolver.js:235:0 <- config/spec-bundle.js:29140:31
          at Array.forEach (native)
          at CompileMetadataResolver.getNgModuleMetadata (webpack:///~/@angular/compiler/src/metadata_resolver.js:215:0 <- config/spec-bundle.js:29120:44)
          at RuntimeCompiler._compileComponents (webpack:///~/@angular/compiler/src/runtime_compiler.js:126:0 <- config/spec-bundle.js:41002:47)
          at RuntimeCompiler._compileModuleAndAllComponents (webpack:///~/@angular/compiler/src/runtime_compiler.js:70:0 <- config/spec-bundle.js:40946:37)
          at RuntimeCompiler.compileModuleAndAllComponentsAsync (webpack:///~/@angular/compiler/src/runtime_compiler.js:61:0 <- config/spec-bundle.js:40937:21)
          at TestingCompilerImpl.compileModuleAndAllComponentsAsync (webpack:///~/@angular/compiler/bundles/compiler-testing.umd.js:763:0 <- config/spec-bundle.js:62423:35)
          at TestBed.compileComponents (webpack:///~/@angular/core/bundles/core-testing.umd.js:1046:0 <- config/spec-bundle.js:16892:35)
          at Function.TestBed.compileComponents (webpack:///~/@angular/core/bundles/core-testing.umd.js:950:49 <- config/spec-bundle.js:16796:71)
...

**Expected/desired behavior**

They should not. 

**Reproduction of the problem**

After I updated my angular2 teaching blueprint project

https://github.com/DcsMarcRemolt/dcs-angular2-blueprint/commit/71a486f62837e8eb07d76dd680630684e2ba5e72

to RC.6 the problem appeared (among other breaks that I could fix though). 

To reproduce, checkout, npm install && npm test

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [Chrome 52] 
 
* **Language:** [TypeScript 2.0.2 ]

**Comment by DcsMarcRemolt** [comment]
Found the problem.

For everyone else banging their heads against the wall, 

BrowserDynamicTestModule

is now 

BrowserDynamicTestingModule

**Comment by mhawila** [comment]
I am actually having `BrowserDynamicTestingModule` but I still see the same error!
