### ISSUE TITLE
AoT fails with NgModules & UpgradeAdapter.upgradeNg1Component

### ISSUE THREAD

**Issue by guojenman** [angular/angular#11307]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When adding the value returned from UpgradeAdapter.upgradeNg1Component into the declarations array of NgModule, AoT fails with the error below

```
export const Ng1Component = adapter.upgradeNg1Component('ng1Component');
@NgModule({
  imports: [BrowserModule],
  declarations: [TestApp, Ng1Component],
  bootstrap: [TestApp]
})
export class TestModule {}
```

```
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Ng1Component in /Users/guojian.wu/Downloads/ng2bad-build/src/app/main.ts, resolving symbol TestModule in /Users/guojian.wu/Downloads/ng2bad-build/src/app/main.ts, resolving symbol TestModule in /Users/guojian.wu/Downloads/ng2bad-build/src/app/main.ts
    at simplifyInContext (/Users/guojian.wu/Downloads/ng2bad-build/node_modules/@angular/compiler-cli/src/static_reflector.js:473:23)
    at StaticReflector.simplify (/Users/guojian.wu/Downloads/ng2bad-build/node_modules/@angular/compiler-cli/src/static_reflector.js:476:22)
    at StaticReflector.annotations (/Users/guojian.wu/Downloads/ng2bad-build/node_modules/@angular/compiler-cli/src/static_reflector.js:61:36)
    at _loop_1 (/Users/guojian.wu/Downloads/ng2bad-build/node_modules/@angular/compiler-cli/src/codegen.js:53:54)
    at CodeGenerator.readFileMetadata (/Users/guojian.wu/Downloads/ng2bad-build/node_modules/@angular/compiler-cli/src/codegen.js:66:13)
    at /Users/guojian.wu/Downloads/ng2bad-build/node_modules/@angular/compiler-cli/src/codegen.js:100:74
    at Array.map (native)
    at CodeGenerator.codegen (/Users/guojian.wu/Downloads/ng2bad-build/node_modules/@angular/compiler-cli/src/codegen.js:100:35)
    at codegen (/Users/guojian.wu/Downloads/ng2bad-build/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/Users/guojian.wu/Downloads/ng2bad-build/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
```

**Expected/desired behavior**
It should compile without error

**Reproduction of the problem**
[ng2bad-build.zip](https://github.com/angular/angular/files/453392/ng2bad-build.zip)

See attached project for error reproduction

npm run tsc (works)
npm run ngc (does not work - throws error from above)

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **OS:** OSX 10.10.5 
- **Language:** [TypeScript 2.0.2] 

Originally reported to a different issue https://github.com/angular/angular/issues/10789#issuecomment-244421950
But according to @chuckjaz, the issue is different enough to warrant a new bug report

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/11262, https://github.com/angular/angular/issues/11133, https://github.com/angular/angular/issues/11069, https://github.com/angular/angular/issues/10789

**Comment by guojenman** [comment]
switched to UpgradeComponent
