### ISSUE TITLE
router 3.0.0.rc2, ES5: Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by albertosantini** [angular/angular#11300]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The app throws the followng exception:

```
core.umd.min.js:21 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'call' of undefinedErrorHandler.handleError @ core.umd.min.js:21next @ core.umd.min.js:28generatorOrNext.object.schedulerFn @ core.umd.min.js:28SafeSubscriber.__tryOrUnsub @ Rx.umd.js:1433SafeSubscriber.next @ Rx.umd.js:1382Subscriber._next @ Rx.umd.js:1335Subscriber.next @ Rx.umd.js:1299Subject.next @ Rx.umd.js:1063EventEmitter.emit @ core.umd.min.js:28onError @ core.umd.min.js:28onHandleError @ core.umd.min.js:28ZoneDelegate.handleError @ zone.js:336Zone.runGuarded @ zone.js:242_loop_1 @ zone.js:508drainMicroTaskQueue @ zone.js:515ZoneTask.invoke @ zone.js:437
core.umd.min.js:21 ORIGINAL STACKTRACE:ErrorHandler.handleError @ core.umd.min.js:21next @ core.umd.min.js:28generatorOrNext.object.schedulerFn @ core.umd.min.js:28SafeSubscriber.__tryOrUnsub @ Rx.umd.js:1433SafeSubscriber.next @ Rx.umd.js:1382Subscriber._next @ Rx.umd.js:1335Subscriber.next @ Rx.umd.js:1299Subject.next @ Rx.umd.js:1063EventEmitter.emit @ core.umd.min.js:28onError @ core.umd.min.js:28onHandleError @ core.umd.min.js:28ZoneDelegate.handleError @ zone.js:336Zone.runGuarded @ zone.js:242_loop_1 @ zone.js:508drainMicroTaskQueue @ zone.js:515ZoneTask.invoke @ zone.js:437
core.umd.min.js:21 Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
    at resolvePromise (zone.js:558)
    at resolvePromise (zone.js:543)
    at zone.js:591
    at ZoneDelegate.invokeTask (zone.js:365)
    at Object.onInvokeTask (core.umd.min.js:28)
    at ZoneDelegate.invokeTask (zone.js:364)
    at Zone.runTask (zone.js:265)
    at drainMicroTaskQueue (zone.js:497)
    at HTMLDocument.ZoneTask.invoke (zone.js:437)ErrorHandler.handleError @ core.umd.min.js:21next @ core.umd.min.js:28generatorOrNext.object.schedulerFn @ core.umd.min.js:28SafeSubscriber.__tryOrUnsub @ Rx.umd.js:1433SafeSubscriber.next @ Rx.umd.js:1382Subscriber._next @ Rx.umd.js:1335Subscriber.next @ Rx.umd.js:1299Subject.next @ Rx.umd.js:1063EventEmitter.emit @ core.umd.min.js:28onError @ core.umd.min.js:28onHandleError @ core.umd.min.js:28ZoneDelegate.handleError @ zone.js:336Zone.runGuarded @ zone.js:242_loop_1 @ zone.js:508drainMicroTaskQueue @ zone.js:515ZoneTask.invoke @ zone.js:437
zone.js:484 Unhandled Promise rejection: Cannot read property 'call' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'call' of undefined(…) TypeError: Cannot read property 'call' of undefined
    at ApplyRedirects.expandSegment (https://unpkg.com/@angular/router@3.0.0-rc.2/bundles/router.umd.min.js:20:10071)
    at ApplyRedirects.expandSegmentGroup (https://unpkg.com/@angular/router@3.0.0-rc.2/bundles/router.umd.min.js:20:9078)
    at ApplyRedirects.apply (https://unpkg.com/@angular/router@3.0.0-rc.2/bundles/router.umd.min.js:20:7499)
    at applyRedirects (https://unpkg.com/@angular/router@3.0.0-rc.2/bundles/router.umd.min.js:6:7976)
    at https://unpkg.com/@angular/router@3.0.0-rc.2/bundles/router.umd.min.js:20:29638
    at new ZoneAwarePromise (https://unpkg.com/zone.js@0.6.17/dist/zone.js:607:30)
    at Router.runNavigate (https://unpkg.com/@angular/router@3.0.0-rc.2/bundles/router.umd.min.js:20:29443)
    at https://unpkg.com/@angular/router@3.0.0-rc.2/bundles/router.umd.min.js:20:28999
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.6.17/dist/zone.js:332:29)
    at Object.onInvoke (https://unpkg.com/@angular/core@2.0.0-rc.6/bundles/core.umd.min.js:28:16568)consoleError @ zone.js:484_loop_1 @ zone.js:511drainMicroTaskQueue @ zone.js:515ZoneTask.invoke @ zone.js:437
zone.js:486 Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined(…)
```

**Expected/desired behavior**

View1 should be rendered displaying `View View1 loaded with the router`

**Reproduction of the problem**

With angular2 2.0.0-rc.6, router 3.0.0-rc.2, rxjs 5.0.0-beta.11, it doesn't work:
http://plnkr.co/edit/3fCbGewE6ZHwRIZfhZVe?p=preview

With angular2 2.0.0-rc.5, router 3.0.0-rc.1, rxjs 5.0.0-beta.6, it works correctly:
http://plnkr.co/edit/WXRv9zwnU9f3lKseJxKP?p=preview

**What is the expected behavior?**

No exceptions

**What is the motivation / use case for changing the behavior?**

Upgrade from angular 2.0.0-rc.5 (router 3.0.0-rc.1, rxjs 5.0.0-beta.6) to angular 2.0.0-rc.6 (router 3.0.0-rc.2, rxjs 5.0.0-beta.11)

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all] 
 
* **Language:** [ES5]

**Comment by sonicblis** [comment]
Just found the same issue on my development environment.  Works fine with RC.5.

**Comment by IgorMinar** [comment]
This is an RxJS bug. The `_catch` operator at `rxjs/add/operator/is exported on the Rx.Observable.prototype as `catch` rather than `_catch`. 

<img width="597" alt="screen shot 2016-09-06 at 9 58 11 am" src="https://cloud.githubusercontent.com/assets/216296/18283019/4ca1cb5e-7418-11e6-809b-632e6abf3487.png">

**Comment by adamfoley** [comment]
Here's a temporary fix that works for me:

	(function () {
		var g;
		if (typeof (window) != null) g = window;
		else if (typeof (global) != null) g = global;
			// couldn't locate global
		else return;

		var obsProto = g.Rx.Observable.prototype;

		obsProto._catch = obsProto.catch;
	})();

**Comment by albertosantini** [comment]
@adamdbradley Thanks. 
Tested and it works nice.

**Comment by albertosantini** [comment]
Tested with rxjs `5.0.0-beta.12` and it works ok.

Be aware loading, in my use case, `Rx.min.js`, `Rx.umd.min.js` doesn't exist, from `node_modules/rxjs/bundles`.
The message `unmeet peer dep...` is displayed.

@IgorMinar Closing the issue? Leaving opened until the peer dep is met?

**Comment by IgorMinar** [comment]
@albertosantini peer dep is now resolved in master. the fix will be in rc.7

**Comment by Huck** [comment]
Hello,

I'm on RC7 with rxjs 5.0.0-beta.12 and router 3.0.0-rc.3 and am getting this same error. I brought the application to the bare bones, with simply a basic module and component, and one router path that loads a component that simply displays ""Hi" in the template.  the error I get is:

> core.umd.min.js:21 Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
    at l (zone.min.js:1)
    at l (zone.min.js:1)
    at eval (zone.min.js:1)
    at e.invokeTask (zone.min.js:1)
    at Object.onInvokeTask (core.umd.min.js:29)
    at e.invokeTask (zone.min.js:1)
    at n.runTask (zone.min.js:1)
    at a (zone.min.js:1)
    at XMLHttpRequest.invoke (zone.min.js:1)ErrorHandler.handleError @ core.umd.min.js:21next @ core.umd.min.js:29generatorOrNext.object.schedulerFn @ core.umd.min.js:29d.__tryOrUnsub @ Rx.min.js:50d.next @ Rx.min.js:49d._next @ Rx.min.js:48d.next @ Rx.min.js:47b.next @ Rx.min.js:41EventEmitter.emit @ core.umd.min.js:29onError @ core.umd.min.js:29onHandleError @ core.umd.min.js:29e.handleError @ zone.min.js:1n.runGuarded @ zone.min.js:1a @ zone.min.js:1a @ zone.min.js:1invoke @ zone.min.js:1XMLHttpRequest.send (async)n @ zone.min.js:1e.scheduleTask @ zone.min.js:1n.scheduleMacroTask @ zone.min.js:1(anonymous function) @ zone.min.js:1send @ VM10635:3ResourceLoaderImpl.get @ platform-browser-dynamic.umd.min.js:6DirectiveNormalizer._fetch @ compiler.umd.min.js:39DirectiveNormalizer.normalizeTemplateAsync @ compiler.umd.min.js:39DirectiveNormalizer.normalizeDirective @ compiler.umd.min.js:39RuntimeCompiler._createCompiledTemplate @ compiler.umd.min.js:41(anonymous function) @ compiler.umd.min.js:41(anonymous function) @ compiler.umd.min.js:41RuntimeCompiler._compileComponents @ compiler.umd.min.js:41RuntimeCompiler._compileModuleAndComponents @ compiler.umd.min.js:41RuntimeCompiler.compileModuleAsync @ compiler.umd.min.js:41PlatformRef_._bootstrapModuleWithZone @ core.umd.min.js:29PlatformRef_.bootstrapModule @ core.umd.min.js:29execute @ main.ts:10p @ system.js:5execute @ system.js:5y @ system.js:4w @ system.js:4p @ system.js:4h @ system.js:4(anonymous function) @ system.js:4F @ system-polyfills.js:4H @ system-polyfills.js:4q.when @ system-polyfills.js:4b.run @ system-polyfills.js:4t._drain @ system-polyfills.js:4drain @ system-polyfills.js:4e @ system-polyfills.js:4characterData (async)(anonymous function) @ system-polyfills.js:4t.run @ system-polyfills.js:4t.enqueue @ system-polyfills.js:4b.become @ system-polyfills.js:4b.resolve @ system-polyfills.js:4e @ system-polyfills.js:4a @ system.js:4Z.i.onreadystatechange @ system.js:4XMLHttpRequest.send (async)Z @ system.js:4(anonymous function) @ system.js:4n @ system-polyfills.js:4e @ system-polyfills.js:4(anonymous function) @ system.js:4(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4F @ system-polyfills.js:4H @ system-polyfills.js:4q.when @ system-polyfills.js:4b.run @ system-polyfills.js:4t._drain @ system-polyfills.js:4drain @ system-polyfills.js:4e @ system-polyfills.js:4characterData (async)(anonymous function) @ system-polyfills.js:4t.run @ system-polyfills.js:4t.enqueue @ system-polyfills.js:4b.become @ system-polyfills.js:4b.resolve @ system-polyfills.js:4e @ system-polyfills.js:4a @ system.js:4Z.i.onreadystatechange @ system.js:4
zone.min.js:1 

> Unhandled Promise rejection: Cannot read property 'call' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'call' of undefined(…) TypeError: Cannot read property 'call' of undefined
    at ApplyRedirects.expandSegmentGroup (http://localhost:5000/node/angular2/router/router.umd.min.js:20:8956)
    at ApplyRedirects.apply (http://localhost:5000/node/angular2/router/router.umd.min.js:20:7499)
    at applyRedirects (http://localhost:5000/node/angular2/router/router.umd.min.js:6:7976)
    at eval (http://localhost:5000/node/angular2/router/router.umd.min.js:20:29638)
    at new e (http://localhost:5000/node/zone/zone.min.js:1:18150)
    at Router.runNavigate (http://localhost:5000/node/angular2/router/router.umd.min.js:20:29443)
    at eval (http://localhost:5000/node/angular2/router/router.umd.min.js:20:28999)
    at e.invoke (http://localhost:5000/node/zone/zone.min.js:1:15936)
    at Object.onInvoke (http://localhost:5000/node/angular2/core/core.umd.min.js:29:16609)
    at e.invoke (http://localhost:5000/node/zone/zone.min.js:1:15887)

its the same error as above but with the latest code...  any idea how to fix it?

**Comment by adamfoley** [comment]
@Huck 

Have you verified your **package.json** dependencies are at the proper versions?  I just updated a project to RC7 with no issue.  Here are my versions:

```
   "@angular/common": "2.0.0-rc.7",
    "@angular/compiler": "2.0.0-rc.7",
    "@angular/core": "2.0.0-rc.7",
    "@angular/forms": "2.0.0-rc.7",
	"@angular/http": "2.0.0-rc.7",
    "@angular/platform-browser": "2.0.0-rc.7",
    "@angular/platform-browser-dynamic": "2.0.0-rc.7",
	"@angular/router": "3.0.0-rc.3",
    "core-js": "2.4.1",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.38",
    "zone.js": "0.6.21"
```

**Comment by Huck** [comment]
@adamfoley 

Thanks for the answer. Yup, I have exactly these versions in my package.json.  the app is really brought down to barebones. The error seems to be in the router component.

**Comment by adamfoley** [comment]
@Huck 

The best advice I can give is to either clone or reference the routing and nav [plunkr](https://angular.io/resources/live-examples/router/ts/plnkr.html) provided in angular documentation and move from there to determine what has gone wrong in your project.

Additionally, check each dependency's `package.json` to verify you are really using the version you've specified.  I've had scenarios where I _thought_ all the packages were updated when in reality they were not due to some unnoticed npm error.

**Comment by Huck** [comment]
thanks adamfoley.  I'm pretty sure my references are fine, but I'm starting to suspect it may be related to rxjs.  What used to work in the previous RCs doesn't seem to work anymore. I just wish angular would just work though, so I could do actual work... :(

[https://github.com/angular/angular/issues/9359](url)
