### ISSUE TITLE
Issue with mocha, TestBed : TypeError: Cannot read property 'assertPresent' of undefined

### ISSUE THREAD

**Issue by StefH** [angular/angular#11317]
**I'm submitting a ...** 

```
[x] bug report
```

**Current behavior**
When running tests, I get the error:

```
> mocha build/test
  ODataService -
    1) "before each" hook for "Construct via injection"

  0 passing (41ms)
  1 failing

  1)  "before each" hook for "Construct via injection":
     TypeError: Cannot read property 'assertPresent' of undefined
      at resetFakeAsyncZone (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\@angular\core\bundles\core-testing.umd.js:385:22)
      at Context.<anonymous> (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\@angular\core\bundles\core-testing.umd.js:1255:13)
      at callFn (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runnable.js:334:21)
      at Hook.Runnable.run (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runnable.js:327:7)
      at next (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:299:10)
      at Immediate.<anonymous> (C:\Users\azureuser\Documents\GitHub\_forks\angular2-odata\node_modules\mocha\lib\runner.js:327:5)
```

My test looks like:

``` ts
require('zone.js');
import 'reflect-metadata';
import { assert } from 'chai';
import { Observable, Operator } from 'rxjs/rx';
import { Location } from '@angular/common';
import { inject, TestBed } from '@angular/core/testing';
// import { TestBedHelper } from './testbedHelper';
import { MockBackend } from '@angular/http/testing';
import { BaseRequestOptions, Http, ConnectionBackend, HttpModule } from '@angular/http';
import { IEmployee } from './employee';
import { ODataOperation } from '../operation';
import { ODataServiceFactory } from '../odataservicefactory';
import { ODataConfiguration } from '../config';

describe('ODataService - ', () => {
    beforeEach(() => {
        TestBed.configureTestingModule({
            providers: [
                BaseRequestOptions,
                MockBackend,
                {
                    provide: Http, useFactory: (backend: ConnectionBackend, defaultOptions: BaseRequestOptions) => {
                        return new Http(backend, defaultOptions);
                    },
                    deps: [MockBackend, BaseRequestOptions]
                },
                ODataConfiguration,
                ODataServiceFactory
            ],
            imports: [
                HttpModule
            ]
        });
    });

    it('Construct via injection', inject([ ODataServiceFactory ], (factory: ODataServiceFactory) => {
        // Act
        let service = factory.CreateService<IEmployee>('Employees');

        // Assert
        assert.isNotNull(service);
    }));
});
```

**Please tell us about your environment:**
- **Mocha version:** 3.0.2
- **Angular version:** 2.0.0-rc.6
- **Language:** [all | TypeScript | ES6/7 | ES5]

**Comment by mszacun** [comment]
Hi! I had exactly the same TypeError using Karma test runner with Angular2. What helped me was to include all zone.js files listed here: https://github.com/angular/quickstart/blob/master/karma.conf.js#L37 in my karma.conf.js file. I see you use require to load zone.js, maybe you nedd to require all of this files?

**Comment by armno** [comment]
I solved the problem by importing `zone.js/dist/proxy` into `src/test.ts` file. Also had to change the order of imports a bit like so - import `proxy` and `jasmine` **after** `sync-test`.

```diff
import 'zone.js/dist/long-stack-trace-zone';
-import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import 'zone.js/dist/sync-test';
+import 'zone.js/dist/proxy';
+import 'zone.js/dist/jasmine-patch';
```

The error `TypeError: Cannot read property 'assertPresent' of undefined` now disappears.

**Test Environment**

- angular 2.0.0-rc.6
- zone.js 0.6.17

**Comment by StefH** [comment]
@armno 
Currently I've changed by test.spec.ts file to include zone like this:
```ts
require('zone.js');
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/proxy';
import 'reflect-metadata';
// more imports follow here . . .
```

Now I get a new error message:
```bash
"before each" hook for "Expand(string) via injection":
     Error: Expected to be running in 'ProxyZone', but it was not found.
      at Function.ProxyZoneSpec.assertPresent (C:\Github\_forks\angular2-odata\node_modules\zone.js\dist\proxy.js:65:24)
      at resetFakeAsyncZone (C:\Github\_forks\angular2-odata\node_modules\@angular\core\bundles\core-testing.umd.js:385:23)
      at Context.<anonymous> (C:\Github\_forks\angular2-odata\node_modules\@angular\core\bundles\core-testing.umd.js:1255:13)
      at callFn (C:\Github\_forks\angular2-odata\node_modules\mocha\lib\runnable.js:334:21)
      at Hook.Runnable.run (C:\Github\_forks\angular2-odata\node_modules\mocha\lib\runnable.js:327:7)
      at next (C:\Github\_forks\angular2-odata\node_modules\mocha\lib\runner.js:299:10)
      at Immediate.<anonymous> (C:\Github\_forks\angular2-odata\node_modules\mocha\lib\runner.js:327:5)
```

**Comment by armno** [comment]
@StefH Could you try importing `import 'zone.js/dist/jasmine-patch';` **after** `import 'zone.js/dist/proxy';`? I think the error should be gone.

**Comment by StefH** [comment]
@armno that gives an error related to jasmine, because I'm not using **jasmine** but **mocha**:

```
C:\Github\_forks\angular2-odata\node_modules\zone.js\dist\jasmine-patch.js:59
                throw new Error("Missing: jasmine.js");
```

**Comment by StefH** [comment]
See also same issue here: https://github.com/angular/angular/issues/11230

**Comment by armno** [comment]
@StefH oops! I didn't realize that you are using Mocha. Sorry! 🙏

**Comment by Davy-F** [comment]
Also experiencing this issue using Jasmine + Karma + Webpack.

When I add the suggested imports I get the following error "originalErr":

![image](https://cloud.githubusercontent.com/assets/19592376/19961364/30188fda-a1aa-11e6-881b-34c913f56520.png)

I am using commonJS if this affects the imports somehow?

**Comment by thescientist13** [comment]
thanks @armno , I had the same issue and importing all the `zone` libs in the order you provided worked for me!

**Comment by applecool** [comment]
@armno TypeError: Cannot read property 'assertPresent' of undefined doesn't disappear but with the correct order of imports, "Expected to be running in 'proxy zone'" error disappears. To make the assertPresent disappear, we need to tweak the core-testing.umd.js file. Add a check like this:
```
if(ProxyZoneSpec){
        ProxyZoneSpec.assertPresent().resetDelegate();
    }
```
instead of `ProxyZoneSpec.assertPresent().resetDelegate();`
ProxyZoneSpec inside the resetFakeAsyncZone() method is undefined. Hence the error.

**Comment by KSuttle-cng** [comment]
```js
// tslint:disable:ordered-imports
import 'zone.js/dist/long-stack-trace-zone'
import 'zone.js/dist/proxy.js'
import 'zone.js/dist/sync-test'
import 'zone.js/dist/jasmine-patch'
import 'zone.js/dist/async-test'
import 'zone.js/dist/fake-async-test'
```

Fixed it for me

**Comment by vikerman** [comment]
Needs proper Zone imports.

**Comment by vunder** [comment]
The most important thing is to keep import section like it was right after "ng new myproject".
For me import 'zone.js/dist/zone-testing' should be at the top of all imports:

```
import 'zone.js/dist/zone-testing';
// tslint:disable-next-line:ordered-imports
import { getTestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

declare const require: any;

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
```
