### ISSUE TITLE
AoT Compiler still failing on Win 7 with "undefined is not a function"

### ISSUE THREAD

**Issue by RoxKilly** [angular/angular#11367]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
I'm on `Windows 7 x64`, trying to follow instructions for [Ahead-of-Time compilation](https://github.com/angular/angular/tree/master/modules/%40angular/compiler-cli) of my Angular 2 application. The app compiles and runs fine with Just-in-Time compilation.

I've NPM installed `@angular/compiler-cli@0.6.0` `typescript@2.0.2` `@angular/platform-server@2.0.0-rc.6` and `@angular/compiler@2.0.0-rc.6`

I get the following error when running `ngc`:
```
C:\websites\learn\angular2>"node_modules/.bin/ngc" -p dev
can't resolve module @angular/core/src/di/opaque_token from C:\...\dev\index.ts
TypeError: undefined is not a function
    at ReflectorHost.findDeclaration (C:\...\node_modules\@angular\compiler-cli\src\reflector_host.js:171:59)
    at StaticReflector.initializeConversionMap (C:\...\node_modules\@angular\compiler-cli\src\static_reflector.js:150:38)
    at new StaticReflector (C:\...\node_modules\@angular\compiler-cli\src\static_reflector.js:42:14)
    at Function.CodeGenerator.create (C:\...\node_modules\@angular\compiler-cli\src\codegen.js:142:31)
    at codegen (C:\...\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (C:\...\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (C:\...\node_modules\@angular\compiler-cli\src\main.js:14:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
Compilation failed
```
Here is the line that throws the error, in *reflecter_host.js*:
```
var symbol = tc.getExportsOfModule(sf.symbol).find(function (m) { return m.name === symbolName; });
```
Here is my folder structure (`tsconfig.json` is in `angular2` at the top-level):

![1](https://cloud.githubusercontent.com/assets/12346501/18263071/089db5dc-73d5-11e6-8a7d-734c005916fc.png)

At first glance, the error seems [similar to this one](https://github.com/angular/angular/issues/9663), but a closer look shows that mine ("*undefined is not a function*") is different.

**Expected/desired behavior**
AoT compilation to work as [outlined in the guides](https://github.com/angular/angular/tree/master/modules/%40angular/compiler-cli).

**Reproduction of the problem**
Don't think I can reproduce AoT compilation errors in a fiddle.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 2.0.2] 

* **OS:** [Windows 7 x64]

**Comment by RoxKilly** [comment]
This had to do with the version of node I had installed.
```
$ node --version
v0.12.7

$ npm --version
3.7.5
```

After I downloaded and installed the latest 64-bit `.msi` installer from https://nodejs.org/en/download/:
```
$ node --version
v4.5.0

$ npm --version
2.15.9
```

The error no longer occurs
