### ISSUE TITLE
[Emergency!!] i18n extract

### ISSUE THREAD

**Issue by n-sviridenko** [angular/angular#11368]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
$ ng-xi18n
```

```
Error: Unexpected value 'TypeaheadModule' imported by the module 'LocationModule'
    at /srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:14118:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:14103:46)
    at /srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:12947:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/srv/app/node_modules/@angular/compiler/bundles/compiler.umd.js:12946:21)
    at Extractor.extract (/srv/app/node_modules/@angular/compiler-cli/src/extract_i18n.js:92:47)
    at extract (/srv/app/node_modules/@angular/compiler-cli/src/extract_i18n.js:16:35)
    at Object.main (/srv/app/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/srv/app/node_modules/@angular/compiler-cli/src/extract_i18n.js:161:9)
Extraction failed
```

**Expected/desired behavior**
Normal extract

**Reproduction of the problem**
It works with each module that was imported from `/node_modules` (but not `@angular/*` module). For me, it works with:
- https://github.com/valor-software/ng2-bootstrap
- https://github.com/urish/angular2-moment

**What is the expected behavior?**
`messages.xlf`

**What is the motivation / use case for changing the behavior?**
..

**Please tell us about your environment:**
VM on Debian GNU/Linux 8 (jessie) launched on Mac OSX El Capitan.
I'm using webpack 1.7.0.

Also, the code of the 'LocationModule':

```
...
import { TypeaheadModule } from 'ng2-bootstrap';

@NgModule({
  imports: [
    ...,
    TypeaheadModule,
  ],
  ...
})
export class LocationModule {}
```

* **Angular version:** 2.0.0-rc.X
2.0.0-rc.6
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
(error in console) 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
TypeScript 2.0.2

**Comment by christiandreher** [comment]
You say:

> For me, it works with:
>
> * [...]
> * https://github.com/urish/angular2-moment


Are you sure it works for you with angular2-moment? Because I have the following issue: https://github.com/urish/angular2-moment/issues/68

**Comment by n-sviridenko** [comment]
@christiandreher I wanted to say happens*

**Comment by christiandreher** [comment]
I think that this issue is **not** related to angular, but the vendors of those libraries. It seems that they are missing files that `angular-cli` needs to process.

Please go to my issue for `angular2-moment` above and leave a command that this also happens to you. The more people ask for a fix, the better. Also search for an open a issue at `ng2-bootstrap` mentioning this and comment there. If there is none, create one and link to my issue at `angular2-moment`, since the fix for this error message is similar.

**Comment by vicb** [comment]
`TypeaheadModule` is definitely not something angular.

**Comment by n-sviridenko** [comment]
Maybe you can add an `exclude` option to prevent vendor parsing?

**Comment by cladera** [comment]
I'm getting the same error but with angular/common:

```
Error: parameters received {"filePath":"/Users/foo/my-project/node_modules/@angular/common/src/location/location.d.ts","name":"Location"} which is not a StaticSymbol
    at StaticReflector.parameters (/Users/foo/my-project/node_modules/@angular/compiler-cli/src/static_reflector.js:92:19)
    at CompileMetadataResolver.getDependenciesMetadata (/Users/foo/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:14190:56)
    at CompileMetadataResolver.getTypeMetadata (/Users/foo/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:14155:28)
    at /Users/foo/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:14298:43
    at Array.forEach (native)
    at CompileMetadataResolver.getProvidersMetadata (/Users/foo/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:14278:21)
    at /Users/foo/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:14285:43
    at Array.forEach (native)
    at CompileMetadataResolver.getProvidersMetadata (/Users/foo/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:14278:21)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/foo/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:14037:60)
Extraction failed

```
I guess @angular/common is related with angular. 

Using @angular 2.0.2 and @angular/compiler-cli 0.6.4

**Comment by christiandreher** [comment]
Better you open a new issue referencing this one in that case, since this will not get any attention.
