### ISSUE TITLE
TestBed does not support deps in providers declarations

### ISSUE THREAD

**Issue by cartant** [angular/angular#11430]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

If the `providers` array passed to `TestBed.configureTestingModule` contains declarations that include `deps`, a `No provider` error is thrown.

**Expected behavior**

The provider's dependencies should be injected and the factory method should be called.

**Reproduction of the problem**

The following test exhibits the problem:

```js
import "core-js";
import "reflect-metadata";
import "zone.js/dist/zone";
import "zone.js/dist/long-stack-trace-zone";
import "zone.js/dist/proxy";
import "zone.js/dist/sync-test";
import "zone.js/dist/jasmine-patch";
import "zone.js/dist/async-test";
import "zone.js/dist/fake-async-test";

import { Inject, OpaqueToken } from "@angular/core";
import { inject, TestBed } from "@angular/core/testing";
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from "@angular/platform-browser-dynamic/testing";

TestBed.initTestEnvironment(
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting()
);

describe("test", () => {

    const FOO = new OpaqueToken("foo");
    const BAR = new OpaqueToken("bar");

    beforeEach(() => {

        TestBed.configureTestingModule({
            providers: [
                {
                    provide: FOO,
                    useFactory: (): any => "f"
                },
                {
                    deps: [new Inject(FOO)],
                    provide: BAR,
                    useFactory: (foo: any): any => "b" + foo
                }
            ]
        });
    });

    it("should inject foo", inject([FOO], (foo: any) => {

        expect(foo).toEqual("f");
    }));

    it("should inject bar", inject([BAR], (bar: any) => {

        expect(bar).toEqual("bf");
    }));
});
```

The above code is in [this GitHub repo](https://github.com/cartant/ng-testbed-di-bug). To reproduce the problem, clone the repo and run the following commands:

```sh
npm install
npm run build
```

Once built, open `index.html` to run the test in the browser. The following error will occur:

```
Error: No provider for @Inject(Token foo)!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (file:///C:/Users/Nicholas/git/temp/ng-testbed-di-bug/bundle.js:24890:38)
    at NoProviderError.AbstractProviderError [as constructor] (file:///C:/Users/Nicholas/git/temp/ng-testbed-di-bug/bundle.js:25374:20)
    at new NoProviderError (file:///C:/Users/Nicholas/git/temp/ng-testbed-di-bug/bundle.js:25405:20)
    at ReflectiveInjector_._throwOrNull (file:///C:/Users/Nicholas/git/temp/ng-testbed-di-bug/bundle.js:27007:23)
    at ReflectiveInjector_._getByKeyDefault (file:///C:/Users/Nicholas/git/temp/ng-testbed-di-bug/bundle.js:27035:29)
    at ReflectiveInjector_._getByKey (file:///C:/Users/Nicholas/git/temp/ng-testbed-di-bug/bundle.js:26998:29)
    at ReflectiveInjector_.get (file:///C:/Users/Nicholas/git/temp/ng-testbed-di-bug/bundle.js:26807:25)
    at NgModuleInjector.get (DynamicTestModule.ngfactory.js:120:92)
    at NgModuleInjector.DynamicTestModuleInjector.getInternal (DynamicTestModule.ngfactory.js:177:49)
```

**What is the motivation / use case for changing the behavior?** 

It appears to be a bug and it prevents the writing of tests that mock libraries - like [AngularFire2](https://github.com/angular/angularfire2) - that [make use of `deps`](https://github.com/angular/angularfire2/blob/master/src/angularfire2.ts#L85-L96) in their `NgModules`.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5 and 2.0.0-rc.6 
 
* **Browser:** Chrome 52 
 
* **Language:** TypeScript 2.0.2

**Comment by cartant** [comment]
This appears to be an error on my part. It seems that `new Inject(...)` is not used in `deps` - as mentioned in [this issue](https://github.com/angular/angular/issues/8623).
