### ISSUE TITLE
Animation filter blur bug in chrome

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#11460]
**I'm submitting a ...**  (check one with "x")
[x ] bug report => search github for a similar issue or PR before submitting
- **Angular version:** 2.0.0-rc.6
- **Language:** [TypeScript 2]

When using animation:

```
@Component({
  /*changeDetection: ChangeDetectionStrategy.OnPush,*/
  selector: 'background',
  styleUrls: [
    '/background.style.scss'
  ],
  template: `
    <div class="full-flex-row" style="justify-content: center">
      <img [@fadeInOut]="showFirst" [src]="'/assets/' + firstImage + '.svg'" class="full-flex-row" style="position:absolute;align-self:center;justify-content:center;object-fit: contain;width:auto;height:100%;padding:100px;">
      <img [@fadeInOut]="showSecond" [src]="'/assets/' + secondImage + '.svg'" class="full-flex-row" style="position:absolute;align-self:center;justify-content:center;object-fit: contain;width:auto;height:150%;padding:100px;">
    </div>
  `,
  animations: [
    trigger('fadeInOut', [
      state('false', style({
        opacity: 0,
        transform: 'scale(.9)',
        //transform: 'rotateY(180deg)',
        //filter: 'blur(15px)',
      })),
      state('true', style({
        opacity: .1,
        //transform: 'scale(1)',
      })),
      transition('false => true', [
        group([
          animate('10000ms ease', style({
            opacity: .1,
          })),
          animate('20000ms ease', style({
            transform: 'scale(1)',
          }))
        ])
      ]),
      transition('true => false', [
        group([
          animate('10000ms ease', style({
            opacity: 0,
            filter: 'blur(20px)',
          })),
          animate('20000ms ease', style({
            transform: 'scale(1.3)',
          }))
        ])
      ]),
    ])
  ]
```

The filter element works in Edge, and when it works, it looks great.
However, in chrome I get:

```
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
EXCEPTION: Error in ./Background class Background - inline template:3:11 caused by: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
ORIGINAL EXCEPTION: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
ORIGINAL STACKTRACE:
Error: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at Error (native)
    at WebAnimationsPlayer._triggerWebAnimation (http://localhost:3000/vendor.bundle.js:50175:24)
    at WebAnimationsPlayer.init (http://localhost:3000/vendor.bundle.js:50168:29)
    at http://localhost:3000/vendor.bundle.js:24676:113
    at Array.forEach (native)
    at AnimationGroupPlayer.init (http://localhost:3000/vendor.bundle.js:24676:71)
    at http://localhost:3000/vendor.bundle.js:24893:116
    at Array.forEach (native)
    at AnimationSequencePlayer.init (http://localhost:3000/vendor.bundle.js:24893:74)
    at AnimationSequencePlayer.play (http://localhost:3000/vendor.bundle.js:24899:18)
    at http://localhost:3000/vendor.bundle.js:33288:24
    at Array.forEach (native)
    at DebugAppView.AppView.triggerQueuedAnimations (http://localhost:3000/vendor.bundle.js:33286:47)
    at DebugAppView._View_Background0.detectChangesInternal (Background.ngfactory.js:170:30)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:33479:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:33584:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/vendor.bundle.js:33505:19)
    at DebugAppView._View_App0.detectChangesInternal (App.ngfactory.js:350:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:33479:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:33584:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/vendor.bundle.js:33505:19)
    at DebugAppView._View_App_Host0.detectChangesInternal (App_Host.ngfactory.js:31:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:33479:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:33584:44)
    at ViewRef_.detectChanges (http://localhost:3000/vendor.bundle.js:33967:65)
    at http://localhost:3000/vendor.bundle.js:26458:84
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:3000/vendor.bundle.js:26458:38)
    at http://localhost:3000/vendor.bundle.js:26399:105
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15092:29)
    at Object.onInvoke (http://localhost:3000/vendor.bundle.js:38898:41)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15091:35)
    at Zone.run (http://localhost:3000/polyfills.bundle.js:14985:44)
    at NgZoneImpl.runInner (http://localhost:3000/vendor.bundle.js:38929:71)
    at NgZone.run (http://localhost:3000/vendor.bundle.js:38829:66)
    at Object.next (http://localhost:3000/vendor.bundle.js:26399:81)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:3000/vendor.bundle.js:30973:70)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3000/vendor.bundle.js:59167:16)
    at SafeSubscriber.next (http://localhost:3000/vendor.bundle.js:59116:22)
    at Subscriber._next (http://localhost:3000/vendor.bundle.js:59069:26)
    at Subscriber.next (http://localhost:3000/vendor.bundle.js:59033:18)
    at EventEmitter.Subject.next (http://localhost:3000/vendor.bundle.js:58785:25)
    at EventEmitter.emit (http://localhost:3000/vendor.bundle.js:30965:76)
    at NgZone._checkStable (http://localhost:3000/vendor.bundle.js:38739:44)
    at NgZoneImpl.onLeave (http://localhost:3000/vendor.bundle.js:38711:23)
    at Object.onInvokeTask (http://localhost:3000/vendor.bundle.js:38892:31)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:15124:43)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:15025:48)
    at ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:15193:34)
ERROR CONTEXT:
DebugContext {_view: _View_Background0, _nodeIndex: 5, _tplRow: 3, _tplCol: 11}
logging error to firebase
```

When i comment out the filter: 'blur(20px)', the error does not happen.

**Comment by matsko** [comment]
Looking into it. Thank you for posting this.

**Comment by matsko** [comment]
@LanderBeeuwsaert could you please put together a plnkr of this issue? I'm having trouble producing it locally.

**Comment by LanderBeeuwsaert** [comment]
Hey,

I've created a beginning of a plunr,
As I'm not familiar with it, I didn't know how to do two things:

1. how to get: import {Observable} from "rxjs"; working.
2. how to not use the text in the template but img tags pointing to svg images.

My guess is that if you resolve 1. it will work, however, I think the problem lies with ng2 animations + blur + svg combined.

Does that point you in the right direction?

**Comment by LanderBeeuwsaert** [comment]
Whoops, plunkr link: https://plnkr.co/edit/X2RL19nXktd7WWFCcurW

**Comment by matsko** [comment]
Sorry this has taken so long for a reply.

Looking at your PR (I updated it to remove Rx) https://plnkr.co/edit/6gnYe7A4qgkPDpzRaHTA?p=preview it looks like it works fine.

Let me know if I'm missing something.

**Comment by LanderBeeuwsaert** [comment]
Hello Matsko,

cool, thanks for completing.
As I said in my 14/9 post:

'how to get: import {Observable} from "rxjs"; working.
how to not use the text in the template but img tags pointing to svg images.
My guess is that if you resolve 1. it will work, however, I think the problem lies with ng2 animations + blur + svg combined'

meaning that it works for the moment, yes, because you are blurring the <h2> tags. When you remove those tags and use the <svg> tags instead + add a valid svg-url to the image (which, again, I don't know how to do; see: https://plnkr.co/edit/d1OkETQxNq6TawcT0RN4?p=preview ), normally it will not work. (I think ;-))

**Comment by matsko** [comment]
Closing this for since animations have been rebuilt for 4.0.0. Please reopen if it shows up again.
