### ISSUE TITLE
[build] `gulp public-api:update` fails (should rm dist)

### ISSUE THREAD

**Issue by vicb** [angular/angular#11468]
```
$ gulp public-api:update
[17:50:42] Using gulpfile ~/Code/angular/gulpfile.js
[17:50:42] Starting 'build.sh'...
[17:50:42] 'build.sh' errored after 198 ms
[17:50:42] Error: Command failed: /Users/berchet/Code/angular/build.sh
rm: ./dist/all//@angular/router/src: Directory not empty
rm: ./dist/all//@angular/router: Directory not empty
rm: ./dist/all//@angular: Directory not empty
rm: ./dist/all/: Directory not empty

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by vicb** [comment]
/cc @IgorMinar 

@mhevery should we add a "comp: build" label ?

**Comment by IgorMinar** [comment]
this was caused by test.sh running in the background. build.sh does cleanup the target directory before building.
