### ISSUE TITLE
RC7: My Webpack build breaks

### ISSUE THREAD

**Issue by spock123** [angular/angular#11567]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I have 3 different projects, all running fine with RC6.
After upgrading to RC7 (and also upgrading dependencies RxJS/Zone), Webpack stops with lots of nasty error messages like:

```
Error: Debug Failure. False expression: Output generation failed Error: Debug Failure. False expression: Output generation failed
    at Object.assert (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/typescript/lib/typescript.js:2406:23)
    at Object.transpileModule (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/typescript/lib/typescript.js:54350:18)
    at State.fastEmit (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/awesome-typescript-loader/src/host.ts:264:39)
    at transform (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/awesome-typescript-loader/src/index.ts:164:28)
    at transformationFunction (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/awesome-typescript-loader/src/index.ts:89:48)
    at compiler (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/awesome-typescript-loader/src/index.ts:105:34)
    at Object.loader (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/awesome-typescript-loader/src/index.ts:18:18)
    at LOADER_EXECUTION (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/loader-runner/lib/LoaderRunner.js:95:14)
    at runSyncOrAsync (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/loader-runner/lib/LoaderRunner.js:96:4)
    at iterateNormalLoaders (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
    at iterateNormalLoaders (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/loader-runner/lib/LoaderRunner.js:189:10)
    at /home/lrj/workspace/angular2-webpack2-typescript2/node_modules/loader-runner/lib/LoaderRunner.js:204:3
    at runSyncOrAsync (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/loader-runner/lib/LoaderRunner.js:101:11)
    at iterateNormalLoaders (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
    at /home/lrj/workspace/angular2-webpack2-typescript2/node_modules/loader-runner/lib/LoaderRunner.js:173:4
    at Storage.finished (/home/lrj/workspace/angular2-webpack2-typescript2/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
    at /home/lrj/workspace/angular2-webpack2-typescript2/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

 
* **Language:** 
Typescript 2.0.2
Awesome-Typescript-Loader

Webpack: 
2.1.0-beta.21

**Comment by spock123** [comment]
Please disregard for now - I'm trying to figure out what the issue is... very strange...
It's probably not RC7 related, so I'll close this

**Comment by spock123** [comment]
So for anyone passing by - maybe Googled it.. the issue is probably with Typescript2 and Awesome-Typescript-Loader... I'm still investigating...

**Comment by spock123** [comment]
Update: Upgrade Awesome-Typescript-Loader to 2.2.4

**Comment by waratah** [comment]
I get the following error on:
Module build failed: Error: Debug Failure. False expression: Output generation failed
I put the following in the package.json under devDependencies "awesome-typescript-loader": "2.2.4"

I uninstalled and reinstalled the type loader and I still receive the error.

I am importing the definition with:

import { WidgetData } from '../interfaces/WidgetData.d';

The file it is complaining about is simply:

export class WidgetData {
    Title: string;
    Widget: string;
}
