### ISSUE TITLE
Can't inject service in custom "Errorhandler"

### ISSUE THREAD

**Issue by Skuriles** [angular/angular#11596]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
If I use a custom Errorhandler similar to this one (which has to be updated to RC6 changes): https://angular.io/docs/ts/latest/api/core/index/ErrorHandler-class.html 

and use this custom error handler like this:
```
import { ErrorHandler} from '@angular/core';
import {GrowlOpt} from "../dtos/growl";
import {GrowlTypes} from "../constants/Enums";
import { ToolService} from "./tool.service"

export class MyErrorHandler implements ErrorHandler {

        constructor(private toolService: ToolService) { }

    handleError(error): void {
        const opt = new GrowlOpt("Error", error.message, GrowlTypes.Error);
        this.toolService.doLog(error)
    }

}

```
there occurs an error on runtime: 
```
vendors.js:1 Potentially unhandled rejection [2] (SystemJS) Can't resolve all parameters for MyErrorHandler : (?).
	Error: Can't resolve all parameters for MyErrorHandler : (?).
	    at CompileMetadataResolver.getDependenciesMetadata (http://192.168.13.177:9080/node_modules/@angular/compiler/bundles/compiler.umd.js:14404:21)
	    at CompileMetadataResolver.getTypeMetadata (http://192.168.13.177:9080/node_modules/@angular/compiler/bundles/compiler.umd.js:14301:28)
	    at eval (http://192.168.13.177:9080/node_modules/@angular/compiler/bundles/compiler.umd.js:14448:43)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getProvidersMetadata (http://192.168.13.177:9080/node_modules/@angular/compiler/bundles/compiler.umd.js:14428:21)
	    at CompileMetadataResolver.getNgModuleMetadata (http://192.168.13.177:9080/node_modules/@angular/compiler/bundles/compiler.umd.js:14181:60)
	    at RuntimeCompiler._compileComponents (http://192.168.13.177:9080/node_modules/@angular/compiler/bundles/compiler.umd.js:16803:49)
	    at RuntimeCompiler._compileModuleAndComponents (http://192.168.13.177:9080/node_modules/@angular/compiler/bundles/compiler.umd.js:16741:39)
	    at RuntimeCompiler.compileModuleAsync (http://192.168.13.177:9080/node_modules/@angular/compiler/bundles/compiler.umd.js:16732:23)
	    at PlatformRef_._bootstrapModuleWithZone (http://192.168.13.177:9080/node_modules/@angular/core/bundles/core.umd.js:7225:29)
	Error loading http://192.168.13.177:9080/app/main.js
```

I can inject toolService in all other components/services without problems

**Expected behavior**
This should work without errors to use a service in MyErrorHandler (show toastr or whatever)

**Reproduction of the problem**
add a service to a custom Errorhandler

**What is the motivation / use case for changing the behavior?**
Update docs to RC7, work without errors

* **Angular version:** 2.0.0-rc.7

* **Language:** [all | TypeScript 2.0]

**Comment by pkozlowski-opensource** [comment]
You are, most probably, missing `@Injectable()` on the `MyErrorHandler` class. Please provide a plunker, as requested in the issue template, if you need more info / help.

**Comment by Skuriles** [comment]
Thought I tried this already. 
I moved the MyErrorHandler Class to an own module and readded @Injectable()...

Now it works...

Just to give other people info:
```
import {NgModule, ErrorHandler, Injectable } from '@angular/core';
import {GrowlOpt} from "../dtos/growl";
import {GrowlTypes} from "../constants/Enums";
import {ToolService} from "../services/tools.service";

@Injectable()
export class MyErrorHandler implements ErrorHandler {

    constructor(private toolService: ToolService) { }

    handleError(error): void {
        const opt = new GrowlOpt("Error", error.message, GrowlTypes.Error);
        this.toolService.showGrowl(opt);
        console.log(error.message);
    }

}

@NgModule({
    providers: [
        {
            provide: ErrorHandler,
            useClass: MyErrorHandler
        }
    ]
})
export class MyErrorModule { }
```


app.module.ts

```
@NgModule({    
    imports: [MyErrorModule],      
    providers: [       
        MyErrorHandler
    ],
    bootstrap: [AppComponent]
})

```
Closed and big thanks!!

**Comment by cgatian** [comment]
@Skuriles Does this still work for you in Angular 4?

**Comment by maximusk** [comment]
It doesn't seem to be working anymore, check [this answer](http://stackoverflow.com/a/44086775/2545680)
