### ISSUE TITLE
can't run build at webpack introduction example

### ISSUE THREAD

**Issue by feniixx** [angular/angular#11657]
I followed [this example](https://angular.io/docs/ts/latest/guide/webpack.html), but I can't run `npm run build`, I'm getting the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node4-lts/4.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.7
3 info using node@v4.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle angular2-webpack@1.0.0~prebuild: angular2-webpack@1.0.0
6 silly lifecycle angular2-webpack@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle angular2-webpack@1.0.0~build: angular2-webpack@1.0.0
8 verbose lifecycle angular2-webpack@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/jonathan/Projects/WebStormProjects/ng2-quickstart/node_modules/.bin:/usr/local/Cellar/node4-lts/4.5.0/bin:~/.composer/vendor/bin:/usr/local/lib/dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/jonathan/.dnx/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/.composer/vendor/bin:/usr/local/share/dotnet
10 verbose lifecycle angular2-webpack@1.0.0~build: CWD: /Users/jonathan/Projects/WebStormProjects/ng2-quickstart
11 silly lifecycle angular2-webpack@1.0.0~build: Args: [ '-c',
11 silly lifecycle   'rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail' ]
12 silly lifecycle angular2-webpack@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack@1.0.0~build: Failed to exec build script
14 verbose stack Error: angular2-webpack@1.0.0 build: `rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-webpack@1.0.0
16 verbose cwd /Users/jonathan/Projects/WebStormProjects/ng2-quickstart
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node4-lts/4.5.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v4.5.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error angular2-webpack@1.0.0 build: `rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail`
22 error Exit status 1
23 error Failed at the angular2-webpack@1.0.0 build script 'rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-webpack package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-webpack
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-webpack
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by DzmitryShylovich** [comment]
Docs repo is here https://github.com/angular/angular.io

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich

**Comment by wonbyte** [comment]
What was the resolution to this? I am seeing the same error.

**Comment by mohan1304** [comment]
what is the fix here? I am still seeing the issue with webpack example
