### ISSUE TITLE
AoT Compile issue with imported object properties in angular expression

### ISSUE THREAD

**Issue by venkataraghu** [angular/angular#11781]
When I try to compile my project with ngc, it throws the below error:
$ node_modules/.bin/ngc -p tsconfig-aot.json
Error: Error at E:/my-app/aot/app/home.component.ngfactory.ts:191:70: Property 'addr' does not exist on type '{ bpName: string; }'.
    at check (E:\my-app\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Tsc.typeCheck (E:\my-app\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)

I have a component and a service  as mentioned below. I see that the property access for 'bpName' has no issue. where as the dynamic property 'addr' insert at the time of home component constructor has some issue. My code seems working while using JIT compiling. Can someone guide me, where i am going wrong?
  

I18Service.ts
---------------------
import { Injectable } from '@angular/core';
export const lang  = {
        bpName : "Ciaz D"
};
@Injectable()
export class I18NService {   
   updateData(key: string, value: string) { 
        lang[key] = value;
    }
    getString(key: string): string {
        return lang[key];
    }
    getErrorString(errorObj: any): string {
        if (lang[errorObj.errorCode]) {
            return lang[errorObj.errorCode];
        } else {
            return errorObj.errorDescription;
        }
    }  
}

home.component.ts
---------------------
import { Component, Input } from '@angular/core';
import { I18NService, lang as LangPack } from './services/I18NService';

@Component({
    selector: 'bp-home',
    template: `
    <bp-header></bp-header>
    <div class="container2">
        <h1>Welcome {{lang.bpName}} </h1>
        <span>{{lang.addr}}</span>
    <div><a routerLink="/register">Register</a> </div> 
    <router-outlet></router-outlet>
	</div>
	<bp-footer></bp-footer>
    `
})
export class HomeComponent {
    lang = LangPack;

    constructor(private i18nService: I18NService) {
	   i18nService.updateData("addr", "2233 PEACHTREEE PLACE");
   }
}

**Comment by venkataraghu** [comment]
changing angular expression in my template code as shown below solved my issue.
**from** 
{{lang.addr]}}
**to**
{{lang['addr']}}
