### ISSUE TITLE
Adding in-memory-web-api to AoT application

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#11908]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
In the ng-doc project we are trying to add more substantial samples to our AoT documentation, but we are running into an issue when trying to add in-memory-web-api to the mix. 

In-memory-web-api exposes an NgModule that we are integrating with our application using an NgModule import in combination with a `forRoot` call

```
import { NgModule } from '@angular/core';
import { InMemoryWebApiModule } from 'angular-in-memory-web-api/in-memory-web-api';
import { InMemoryDataService } from './in-memory-db.service';

@NgModule({
  imports: [InMemoryWebApiModule.forRoot(InMemoryDataService)]    
})
export class AppModule {
}
``` 
When trying to AoT compile our application with the forRoot import we get the following error:
```
Error: Unexpected value '[object Object]' imported by the module 'AppModule'
    at /Users/tor/Development/in-mem-web-api-aot/node_modules/@angular/compiler/bundles/compiler.umd.js:14109:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/tor/Development/in-mem-web-api-aot/node_modules/@angular/compiler/bundles/compiler.umd.js:14094:46)
    at /Users/tor/Development/in-mem-web-api-aot/node_modules/@angular/compiler/bundles/compiler.umd.js:12936:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/Users/tor/Development/in-mem-web-api-aot/node_modules/@angular/compiler/bundles/compiler.umd.js:12935:21)
    at CodeGenerator.codegen (/Users/tor/Development/in-mem-web-api-aot/node_modules/@angular/compiler-cli/src/codegen.js:105:47)
    at codegen (/Users/tor/Development/in-mem-web-api-aot/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/Users/tor/Development/in-mem-web-api-aot/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/Users/tor/Development/in-mem-web-api-aot/node_modules/@angular/compiler-cli/src/main.js:14:9)
Compilation failed
```

AoT gave us a few challenges when trying to create a drop-in replacement for `XHRBackend`, but we are currently using the following code to swap out  `XHRBackend`.

```
import { Injector, NgModule, ModuleWithProviders, Type } from '@angular/core';
import { HttpModule, XHRBackend }              from '@angular/http';

import {
  InMemoryBackendConfigArgs,
  InMemoryBackendConfig,
  InMemoryBackendService,
  InMemoryDbService
} from './in-memory-backend.service';

// AoT requires factory to be exported
export function inMemoryBackendServiceFactory(injector: Injector, dbService: InMemoryDbService, options: InMemoryBackendConfig) : XHRBackend {
  let backend: any = new InMemoryBackendService(injector, dbService, options);
  return (<XHRBackend>backend);
}

@NgModule({
  // Must useFactory for AoT
  // https://github.com/angular/angular/issues/11178
  providers: [ { provide: XHRBackend,
                 useFactory: inMemoryBackendServiceFactory,
                 deps: [Injector, InMemoryDbService, InMemoryBackendConfig]} ]
})
export class InMemoryWebApiModule {
  /**
  *  Prepare in-memory-web-api in the root/boot application module
  *  with class that implements InMemoryDbService and creates an in-memory database.
  *
  * @param {Type} dbCreator - Class that creates seed data for in-memory database. Must implement InMemoryDbService.
  * @param {InMemoryBackendConfigArgs} [options]
  *
  * @example
  * InMemoryWebApiModule.forRoot(dbCreator);
  * InMemoryWebApiModule.forRoot(dbCreator, {useValue: {delay:600}});
  */
  static forRoot(dbCreator: Type<InMemoryDbService>, options?: InMemoryBackendConfigArgs): ModuleWithProviders {
    return {
      ngModule: InMemoryWebApiModule,
      providers: [
        { provide: InMemoryDbService,  useClass: dbCreator },
        { provide: InMemoryBackendConfig, useValue: options },
      ]
    };
  }
}

```

My initial suspicion is that this is perhaps a metadata related issue. Looks like the following condition is triggered in our case: https://github.com/angular/angular/blob/bd4045b6e753cc279aec861776221219030298b2/modules/%40angular/compiler/src/metadata_resolver.ts#L250

Here are a few of the assumptions we've made when integrating third party NgModule based projects with AoT projects.

1) The third party library has to be AoT compiled itself
2) The third party library has to export the JS source, the d.ts files and all generated metadata.json files

I have created a simple repo project showing our current setup. No need to download the project since I have checked in the in-memory-web-api dependency from node_modules.

Here is the url to the repo: https://github.com/thelgevold/aot-in-mem-web-api

* **Angular version:** 2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
 
* **Node (for AoT issues):** `node --version` =  5.11.1

**Comment by thelgevold** [comment]
Our setup is using symlinked node_modules, so that could perhaps contribute to this if the setup is otherwise correct.

**Comment by thelgevold** [comment]
I was able to get it to work if I ran it against physical files instead of symlinked node_modules. 
@alexeagle I remember earlier that you had the idea for the fix that enabled us to work with symlinked node_modules when doing AoT against local TS source. Is there perhaps a similar fix that will work when bringing in external AoT projects with meta data?

**Comment by thelgevold** [comment]
Looks like this might be related to npm link, so I am closing. Sorry for the noise
