### ISSUE TITLE
SelectMultipleControlValueAccessor is a string and fails with values.map does not exist

### ISSUE THREAD

**Issue by mcgear** [angular/angular#11926]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When using the basic example of the Dynamic Form, i try to add [multiple]="true" to the select:

```
            <select [id]="question.key" *ngSwitchCase="'dropdown'" [formControlName]="question.key" [multiple]="true">
                <option *ngFor="let opt of question.options" [value]="opt.key">{{opt.value}}</option>
            </select>
```

ANd i get a values.map does not exist error:
TypeError: values.map is not a function
    at SelectMultipleControlValueAccessor.writeValue (forms.umd.js:1317)
 at setUpControl (forms.umd.js:1470)
    at FormGroupDirective.addControl (forms.umd.js:3889)
    at FormControlName._setUpControl (forms.umd.js:4318)
    at FormControlName.ngOnChanges (forms.umd.js:4264)
    at DebugAppView._View_DynamicFormQuestionComponent22.detectChangesInternal (DynamicFormQuestionComponent2.ngfactory.js:514)
    at DebugAppView.AppView.detectChanges (core.umd.js:9566)
    at DebugAppView.detectChanges (core.umd.js:9671)
    at DebugAppView.AppView.detectContentChildrenChanges (core.umd.js:9584)
    at DebugAppView._View_DynamicFormQuestionComponent20.detectChangesInternal (DynamicFormQuestionComponent2.ngfactory.js:200)

**Expected behavior**
No error should be thrown when using [multiple]="true"

**Reproduction of the problem**
Run through the Dynamic Form documentation and just add [multiple]="true" to the select

**What is the motivation / use case for changing the behavior?**
Broken

**Please tell us about your environment:**
Surface Book w/ Win10 in visual studio using npm/gulp with SystemJS
- **Angular version:** 2.0.X 
  2.0.0
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
  Everything tried...  Chrome, edge, firefox
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  Typescript
- **Node (for AoT issues):** `node --version` =

**Comment by mcgear** [comment]
Just a little extra info, work around was pretty simple:

			new DropdownQuestion({
				key: 'brave',
				label: 'Bravery Rating',
				options: [
					{ key: 'solid', value: 'Solid' },
					{ key: 'great', value: 'Great' },
					{ key: 'good', value: 'Good' },
					{ key: 'unproven', value: 'Unproven' }
				],
				value: [],
				order: 3
			}),


Just added the value: [] definition to the DropdownQuestion definition and all was good.  Would be nice if it handled it default still

**Comment by mbjaishankar** [comment]
This issue comes for me also while using multiple select drop-down have used the same syntax recommended by "@angular\forms\src\directives\select_multiple_control_value_accessor.d.ts" but i am getting the below error 

can you please tell me when this issue will be solved or any alternative to use the multiple select drop-down 


Code snippet 
```
<select multiple name="city" ngModel>
  <option *ngFor="let c of cities" [value]="c"></option>
 </select> 
```

error :
 EXCEPTION: Uncaught (in promise): TypeError: values.map is not a function

zone.js:344 Unhandled Promise rejection: values.map is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: values.map is not a function(…) TypeError: values.map is not a function
    at SelectMultipleControlValueAccessor.writeValue (http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js:1317:30)
    at eval (http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js:1481:31)
    at eval (http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js:2511:69)
    at Array.forEach (native)
    at FormControl.setValue (http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js:2511:32)
    at eval (http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js:3607:64)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:28)
    at Object.onInvoke (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:6242:41)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:191:34)
    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:85:43)

**Comment by vicb** [comment]
please add a plunker

**Comment by Fank** [comment]
Looks like the error came from https://github.com/angular/angular/blob/2b313e49791b932634cc58cf913a8cf867671d37/modules/%40angular/forms/src/directives/select_multiple_control_value_accessor.ts#L70 and a fix maybe is to check that `value` is an `Array`

**Comment by AlmogShaul** [comment]
https://plnkr.co/edit/C1lu83?p=preview
