### ISSUE TITLE
Using async in one test and not in other will cause weird behaviour

### ISSUE THREAD

**Issue by Pouja** [angular/angular#12115]
**I'm submitting a ...**  (check one with "x")

```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

``` js
/* tslint:disable:no-use-before-declare */

import { CommonModule} from '@angular/common';
import { TestBed, ComponentFixture, fakeAsync, async} from '@angular/core/testing';
import { advance} from '../../testing';
import { ActivatedRoute } from '@angular/router';
import { Component, Input, OnDestroy, OnInit } from '@angular/core';

describe('Component: Async weird issue', () => {
  let fixture: ComponentFixture<HostComponent>;
  let component;
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [CommonModule],
      declarations: [AppPageComponent, HostComponent],
      providers: [{
        provide: ActivatedRoute, useValue: ActivatedRouteStub
      }]
    });
    fixture = TestBed.createComponent(HostComponent);
    component = fixture.debugElement.children[0].componentInstance;
  }));
  it('this will succeed', () => {
    expect(component).not.toBeNull();
  });
  it('\'this\' in this case will be empty as if ngInit never happened',
    fakeAsync(() => {
      advance(fixture);
      expect(component).not.toBeNull();
    }));
});

@Component({
  template: '<app-page [entities]="entities"></app-page>'
})
class HostComponent {
  public entities = {
    randomValue: 1
  };
}

const ActivatedRouteStub = {
  queryParams: {
    subscribe: function(){
      return {
        unsubscribe: function(){ }
      };
    }
  }
};

@Component({
  template: '<div></div>',
  selector: 'app-page'
})
class AppPageComponent implements OnInit, OnDestroy {
  @Input() entities: any;
  private queryParam$;
  constructor(private route: ActivatedRoute) {  }
  ngOnInit() {
    this.queryParam$ = this.route.queryParams.subscribe();
  }
  ngOnDestroy() {
    this.queryParam$.unsubscribe();
  }
}
```

Will crash when use `ng test`.
You will get

```
Chrome 53.0.2785 (Linux 0.0.0) Component: Async weird issue 'this' in this case will be empty as if ngInit never happened FAILED
    Error: Error in ./HostComponent class HostComponent - inline template:0:0 caused by: Cannot read property 'unsubscribe' of undefined
    TypeError: Cannot read property 'unsubscribe' of undefined
        at AppPageComponent.ngOnDestroy (webpack:///home/user/project/src/app/data-table/test.spec.ts:64:21 <- src/test.ts:84495:25)
        at DebugAppView._View_HostComponent0.destroyInternal (HostComponent.ngfactory.js:50:30)
        at DebugAppView.AppView.destroyLocal (webpack:///home/user/project/~/@angular/core/src/linker/view.js:204:0 <- src/test.ts:43989:14)
        at DebugAppView.destroyLocal (webpack:///home/user/project/~/@angular/core/src/linker/view.js:367:0 <- src/test.ts:44152:43)
        at DebugAppView.AppView._destroyRecurse (webpack:///home/user/project/~/@angular/core/src/linker/view.js:192:0 <- src/test.ts:43977:14)
        at DebugAppView.AppView._destroyRecurse (webpack:///home/user/project/~/@angular/core/src/linker/view.js:190:0 <- src/test.ts:43975:25)
        at DebugAppView.AppView.destroy (webpack:///home/user/project/~/@angular/core/src/linker/view.js:178:0 <- src/test.ts:43963:14)
        at ComponentRef_.destroy (webpack:///home/user/project/~/@angular/core/src/linker/component_factory.js:119:51 <- src/test.ts:27989:82)
        at ComponentFixture.destroy (webpack:///home/user/project/~/@angular/core/bundles/core-testing.umd.js:344:0 <- src/test.ts:5059:35)
```

**Expected behavior**
Not fail

**Minimal reproduction of the problem with instructions**
Use the code above with:
- angular 2.0.0
- angular-cli 1.0.0-beta.16

with `ng test`

**What is the motivation / use case for changing the behavior?**
You should not be forced to use async when async is not necessary imho.

**Please tell us about your environment:**
Stated above
- **Angular version:** 2.0.X
  Did not find any similar issue
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  Local
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  all
- **Node (for AoT issues):** `node --version` =   6.4.0

**Comment by SoldierCorp** [comment]
Is there any solution for this?

**Comment by vicb** [comment]
/cc @juliemr @vikerman I seem to remember having seen such an issue when `async` is used in `beforeEach`, do you know more ?

@Pouja @SoldierCorp please search the issue tracker and report what you can find. Thanks.

**Comment by Pouja** [comment]
@SoldierCorp The work around is that every `it` should use the `fakeAsync` **if** in the `beforeEach` `async` is used.

**Comment by willwsharp** [comment]
Is there any update on when this issue will be fixed?

**Comment by vikerman** [comment]
The ProxyZone should have fixed this. Material has tests where the beforeEach is async but the it() itself is not.

Ex.
https://github.com/angular/material2/blob/1bcd8ca12c28a60ad43b5d583c3e1815b1b40f28/src/lib/chips/chip-remove.spec.ts#L39
