### ISSUE TITLE
[BUG] tslint compiler.umd.js:8766

### ISSUE THREAD

**Issue by lifaon74** [angular/angular#12120]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
After updating to angular 2.0.2, I did a tslint and get this error (not present before) : 
```
node_modules\@angular\compiler\bundles\compiler.umd.js:8766
          template.animations.forEach(function (entry) { triggerLookup.add(entry.name); });
TypeError: Cannot read property 'animations' of undefined
    at TemplateParseVisitor._validateElementAnimationInputOutputs (node_modules\@angular\compiler\bundles\compiler.umd.js:8766:19)
    at TemplateParseVisitor.visitElement (node_modules\@angular\compiler\bundles\compiler.umd.js:8749:20)
    at Element.visit (node_modules\@angular\compiler\bundles\compiler.umd.js:4688:78)
    at node_modules\@angular\compiler\bundles\compiler.umd.js:4703:31
    at Array.forEach (native)
    at visitAll (node_modules\@angular\compiler\bundles\compiler.umd.js:4702:13)
    at TemplateParser.tryParse (node_modules\@angular\compiler\bundles\compiler.umd.js:8492:24)
    at Object.exports.parseTemplate (node_modules\codelyzer\angular\templateParser.js:14:23)
    at InputMetadataWalker.Ng2Walker.visitClassDecorator (\node_modules\codelyzer\angular\ng2Walker.js:115:62)
    at Array.forEach (native)

```

**Expected behavior**
Works as it worked in 2.0.1 

**Minimal reproduction of the problem with instructions**
1) Install angular 2.0.2 (common, compiler, core, forms, htpp, ...)
2) Do a tslint

**Please tell us about your environment:**
* Windows 10, angular2-seed
* **Angular version:** 2.0.2

**Comment by IgorMinar** [comment]
Can you clarify how the tslint is run? Why is it linting the umd bundle file?

**Comment by IgorMinar** [comment]
Oh. I see. The Codelyzer uses Angular's private APIs which have changed in 2.0.2.

I'm sorry but there is not much we can do about this. Can you please file an issue against codelyzer? //cc @mgechev

**Comment by lifaon74** [comment]
Thanks for your help

**Comment by mgechev** [comment]
@lifaon74 I already opened an issue for this. As workaround until it's fixed you can remove all template related rules from `tslint.json`.

**Comment by mgechev** [comment]
@lifaon74 if you pull the latest changes of the seed, everything should work as expected.

**Comment by lifaon74** [comment]
@mgechev yes, everything working now, thanks

**Comment by ganesansays** [comment]
@mgechev, what was changed in the seed to fix this. I took a fork sometime back and I dont want to pull the rest of the changes in.

**Comment by mgechev** [comment]
Remove the Angular specific rules. Take a look here https://github.com/mgechev/angular2-seed/commit/0a36abf44b72716d23d59be9834ea853537ff3f3.
