### ISSUE TITLE
Upgrading from 2.0.1 to 2.0.2 throws `Cannot read property 'animations' of undefined`

### ISSUE THREAD

**Issue by mattlewis92** [angular/angular#12126]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
After upgrading my app from 2.0.1 to 2.0.2 this error is thrown for all components:
```
Module build failed: TypeError: Cannot read property 'animations' of undefined
    at TemplateParseVisitor._validateElementAnimationInputOutputs (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:8766:19)
    at TemplateParseVisitor.visitElement (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:8749:20)
    at Element.visit (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:4688:78)
    at /Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:4703:31
    at Array.forEach (native)
    at visitAll (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:4702:13)
    at TemplateParseVisitor.visitElement (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:8722:26)
    at Element.visit (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:4688:78)
    at /Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:4703:31
    at Array.forEach (native)
    at visitAll (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:4702:13)
    at TemplateParser.tryParse (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/@angular/compiler/bundles/compiler.umd.js:8492:24)
    at Object.exports.parseTemplate (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/codelyzer/angular/templateParser.js:14:23)
    at InputMetadataWalker.Ng2Walker.visitClassDecorator (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/codelyzer/angular/ng2Walker.js:115:62)
    at Array.forEach (native)
    at InputMetadataWalker.Ng2Walker.visitClassDeclaration (/Users/mattlewis/Code/open-source/angular2-calendar/node_modules/codelyzer/angular/ng2Walker.js:72:40)
 @ ./src/index.ts 9:4154-4212
 @ ./test/calendarDate.pipe.spec.ts
 @ ./test \.spec
 @ ./test/entry.ts
```

**Expected behavior**
For everything to compile without errors

**Minimal reproduction of the problem with instructions**
Checkout this repo: https://github.com/mattlewis92/angular2-calendar
```
npm install
npm start
```

You'll see the error thrown in the console.

* **Angular version:** 2.0.X

2.0.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
6.7.0

**Comment by vicb** [comment]
Could you please add a simple plunker ?

**Comment by ericmartinezr** [comment]
Isn't this issue the same as this one https://github.com/angular/angular/issues/12120 ? At least is the same error message

**Comment by mattlewis92** [comment]
Oh yeah it's codelyzer causing it, thanks for the pointer!
