### ISSUE TITLE
AoT Compilation Failed: unexpected value imported by AppModule

### ISSUE THREAD

**Issue by rkrayovskyy** [angular/angular#12164]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I am using [ng-semantic](https://github.com/vladotesanovic/ngSemantic) module. It works well so far, however AoT compilation fails with it:

```
Error: Unexpected value 'NgSemanticModule' imported by the module 'AppModule'
    at /Users/***/node_modules/@angular/compiler/bundles/compiler.umd.js:13982:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/***/node_modules/@angular/compiler/bundles/compiler.umd.js:13967:46)
    at /Users/***/node_modules/@angular/compiler/bundles/compiler.umd.js:12812:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/Users/***/node_modules/@angular/compiler/bundles/compiler.umd.js:12811:21)
    at CodeGenerator.codegen (/Users/***/node_modules/@angular/compiler-cli/src/codegen.js:105:47)
    at codegen (/Users/***/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/Users/***/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/Users/***/node_modules/@angular/compiler-cli/src/main.js:14:9)
Compilation failed
```

**Expected behavior**
AoT should be successful.

**Minimal reproduction of the problem with instructions**
It works well in JiT, module itself has exported class being imported in AppModule.
So, it looks like all is good on their side. I have reported similar issue on their github, though.

**What is the motivation / use case for changing the behavior?**
Use ng-semantic and do AoT

**Please tell us about your environment:**

* **Angular version:** 2.0.2

* **Browser:** All
 
* **Language:** 2.0.3

* **Node (for AoT issues):** `node --version` =   6.2.2

**Comment by DzmitryShylovich** [comment]
It's a lib issue. You've already opened an issue https://github.com/vladotesanovic/ngSemantic/issues/86
Angular can't do anything about that.

**Comment by rkrayovskyy** [comment]
thanks for a quick response!
I'll close this one then and see if Vlado fixes it.
