### ISSUE TITLE
Page not loaded when trying to navigate using constant as route path

### ISSUE THREAD

**Issue by Iojjj** [angular/angular#12192]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Page not loaded. An error thrown:

```
Error: Uncaught (in promise): Error: Token must be defined!
    at resolvePromise (http://localhost:3000/polyfills.bundle.js:15069:32)
    at http://localhost:3000/polyfills.bundle.js:15046:14
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:14843:29)
    at Object.onInvoke (http://localhost:3000/vendor.bundle.js:6773:42)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:14842:35)
    at Zone.run (http://localhost:3000/polyfills.bundle.js:14736:44)
    at http://localhost:3000/polyfills.bundle.js:15102:58
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:14876:38)
    at Object.onInvokeTask (http://localhost:3000/vendor.bundle.js:6764:42)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:14875:43)
```

**Expected behavior**
Router navigates to proper page.

**Minimal reproduction of the problem with instructions**

1. Define and export a constant string with route url (or export class with `public static readonly` variable).
2. Import the constant route url into any class that contains a `Router` instance.
3. Call router's `navigate` method with imported constant.

[Plunker Sample](http://plnkr.co/edit/yhBgXxj7rJnsI7xnMJLH). Here `auth.guard` checks if user is not signed in and navigates to error page.

**What is the motivation / use case for changing the behavior?**
Bug fix.

**Please tell us about your environment:**

- **OS**: Windows 10, x64
- **IDE**: WebStorm 2016.2.3
- **npm**: 3.10.3
- **Angular version:** 2.0.2
- **Browser:** Chrome 53.0.2785.143 m, Microsoft Edge 38.14393.0.0
- **Language:** TypeScript 2.0.3
- **Node (for AoT issues):** `node --version` =  v6.3.1

**Comment by DzmitryShylovich** [comment]
Pls provide **working** reproduction.

**Comment by Iojjj** [comment]
moving constants to separate file fixes the problem.
