### ISSUE TITLE
SyntaxError: Unexpected token import; import { ChangeDetectionStrategy }

### ISSUE THREAD

**Issue by esakkikrishnan** [angular/angular#12229]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
node_modules\@angular\core\src\metadata\directives.js:8
import { ChangeDetectionStrategy } from '../change_detection/constants';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Use of @input in the nested component

**Please tell us about your environment:**
VsCode, Nodejs, Angular-Universal, Angular starter Kit from AngularClass

* **Angular version:** 2.0.X
2.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

It does not compile
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.0
* **Node (for AoT issues):** `node --version` =   
Node version 6.6.0

**ISSUE**
\node_modules\@angular\core\src\metadata\directives.js:8
import { ChangeDetectionStrategy } from '../change_detection/constants';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (\dist\server\index.js:1799:18)
    at __webpack_require__ (\dist\server\index.js:21:30)

**Comment by esakkikrishnan** [comment]
The issue was that I import a wrong module.
I apologize for the mistake
