### ISSUE TITLE
TypeError: Cannot read property 'animations' of undefined after upgrade to Angular 2.1.0

### ISSUE THREAD

**Issue by karlhaas** [angular/angular#12267]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8751
          template.animations.forEach(function (entry) { triggerLookup.add(entry.name); });
                  ^
TypeError: Cannot read property 'animations' of undefined
    at TemplateParseVisitor._validateElementAnimationInputOutputs (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8751:19)
    at TemplateParseVisitor.visitElement (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8734:20)
    at Element.visit (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:4656:78)
    at visit (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:4672:39)
    at /home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:4674:27
    at Array.forEach (native)
    at visitAll (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:4673:13)
    at TemplateParser.tryParseHtml (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8461:24)
    at TemplateParser.tryParse (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8451:23)
    at Object.exports.parseTemplate (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/codelyzer/angular/templateParser.js:14:23)
```

* **Angular version:** 2.1.0
 
* **Language:** Typescript 2.0.3

* **Node (for AoT issues):** `node --version` =   v6.8.0

**Comment by pkozlowski-opensource** [comment]
Looks like a duplicate of #12120. Aren't you using Codelyzer by chance?

**Comment by karlhaas** [comment]
Thx @pkozlowski-opensource . We use Codelyzer. I added a comment to https://github.com/mgechev/codelyzer/issues/115
