### ISSUE TITLE
Cannot read property 'injector' of null in TestBed.createComponent

### ISSUE THREAD

**Issue by jordins** [angular/angular#12304]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
TestBed.createComponent(); crashes when running tests with karma and browserify.
Here is the beforeEach which is crashing:
```
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By }              from '@angular/platform-browser';
import { DebugElement }    from '@angular/core';
import { AboutPage } from './about'


beforeEach(() => {

    // refine the test module by declaring the test component
    TestBed.configureTestingModule({
      declarations: [ AboutPage ],
    });

    // create component and test fixture
    fixture = TestBed.createComponent(AboutPage);

    // get test component from the fixture
    comp = fixture.componentInstance;
  });

```

And the error received:

```
Chrome 53.0.2785 (Mac OS X 10.11.6) About component should display original title FAILED
	TypeError: Cannot read property 'injector' of null
	    at TestBed._createCompilerAndModule (/var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/node_modules/@angular/core/bundles/core-testing.umd.js:834:0 <- /var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/57bca79162ed1bcbdc3d746a5d9211d7.browserify:3968:48)
	    at TestBed._initIfNeeded (/var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/node_modules/@angular/core/bundles/core-testing.umd.js:800:0 <- /var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/57bca79162ed1bcbdc3d746a5d9211d7.browserify:3934:43)
	    at TestBed.createComponent (/var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/node_modules/@angular/core/bundles/core-testing.umd.js:884:0 <- /var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/57bca79162ed1bcbdc3d746a5d9211d7.browserify:4018:18)
	    at Function.TestBed.createComponent (/var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/node_modules/@angular/core/bundles/core-testing.umd.js:714:0 <- /var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/57bca79162ed1bcbdc3d746a5d9211d7.browserify:3848:33)
	    at Object.<anonymous> (/var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/src/pages/about/about.spec.ts:24:22 <- /var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/57bca79162ed1bcbdc3d746a5d9211d7.browserify:50004:37)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:203:28)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:72:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:202:34)
	    at Zone.run (node_modules/zone.js/dist/zone.js:96:43)
	    at Object.<anonymous> (node_modules/zone.js/dist/jasmine-patch.js:91:50)
	TypeError: Cannot read property 'detectChanges' of undefined
	    at Object.<anonymous> (/var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/src/pages/about/about.spec.ts:33:12 <- /var/folders/by/05whlcq9247dyx85bd0l183w0000gn/T/57bca79162ed1bcbdc3d746a5d9211d7.browserify:50010:16)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:203:28)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:72:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:202:34)
	    at Zone.run (node_modules/zone.js/dist/zone.js:96:43)
	    at Object.<anonymous> (node_modules/zone.js/dist/jasmine-patch.js:91:50)
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (node_modules/zone.js/dist/jasmine-patch.js:119:42)
```

Any help will be appreciated.

**Please tell us about your environment:**
Operating system: osx 10.11.6

* **Angular version:** 2.0.X
Angular version: 2.0.1
"zone.js": "^0.6.21"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   v6.7.0

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
