### ISSUE TITLE
The hierarchic Json data cannot displayed correctly. Need help!

### ISSUE THREAD

**Issue by PiPiNaN** [angular/angular#12843]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I test the angular2-seed for displaying the repo-detail, which is a pure json string, in a table.  so appending the following code in repo-detail.component.html:
"\<table>
    \<tr>
        \<td>{{repoDetails.id}}\</td>
        \<td>{{repoDetails.owner.login}}\</td> 
    \</tr>
\</table>"
Now the data is not correctly displayed. In the console, i got:
zone.js:388 Unhandled Promise rejection: Error in ./RepoDetailComponent class RepoDetailComponent - inline template:7:12 caused by: Cannot read property 'login' of undefined ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedError {_nativeError: Error: Error in ./RepoDetailComponent class RepoDetailComponent - inline template:7:12 caused by: Ca…, originalError: TypeError: Cannot read property 'login' of undefined
    at DebugAppView._View_RepoDetailComponent0.…, context: DebugContext} TypeError: Cannot read property 'login' of undefined
    at DebugAppView._View_RepoDetailComponent0.detectChangesInternal (/AppModule/RepoDetailComponent/component.ngfactory.js:108:72)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:9319:19)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:9424:49)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/vendor.bundle.js:9345:24)
    at DebugAppView._View_RepoDetailComponent_Host0.detectChangesInternal (/AppModule/RepoDetailComponent/host.ngfactory.js:33:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:9319:19)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:9424:49)
    at ViewRef_.detectChanges (http://localhost:3000/vendor.bundle.js:7412:25)
    at RouterOutlet.activate (http://localhost:3000/vendor.bundle.js:13550:47)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:3000/vendor.bundle.js:13047:21)

**Expected behavior**

It will display the data in the page as the way with angular 1.x.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

2.1.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 
* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
`<td>{{repoDetails.owner?.login}}</td> `

This issue tracker is not suitable for support requests, please use [StackOverflow](http://stackoverflow.com/) with tag `angular`.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
