### ISSUE TITLE
Dynamic CSS loading throws error for child components @ BrowserDomAdapter.appendChild

### ISSUE THREAD

**Issue by nth-commit** [angular/angular#12853]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When rendering a **child** component after routing, dynamically appending CSS throws an error. Works in production builds where CSS is pre-bundled.

This is a really strange issue and I'm totally lost.

Message: 
Error: Uncaught (in promise): Error: Error in ./SearchDetails class SearchDetails - inline template:2:4 caused by: this.appendChild is not a function

NOTE:
The template location is the location where my child component starts. If, in that child component, I remove the styleUrls attribute (so styles are not loaded), I will get the same error at the next component to be rendered that requires a style element to be appended to the head of the document.

Stack:
```TypeError: this.appendChild is not a function
    at BrowserDomAdapter.createStyleElement (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:656:18)
    at DomSharedStylesHost._addStylesToHost (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1271:53)
    at eval (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1281:65)
    at Set.forEach (native)
    at DomSharedStylesHost.onStylesAdded (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1281:29)
    at DomSharedStylesHost.SharedStylesHost.addStyles (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1249:18)
    at new DomRenderer (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1354:53)
    at DomRootRenderer_.DomRootRenderer.renderComponent (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1323:28)
    at DebugDomRootRenderer.renderComponent (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:8758:56)
    at _View_FileListComponent0.AppView (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:9131:43)
    at new DebugAppView (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:9363:20)
    at _View_FileListComponent0 [as clazz] (/AppModule/FileListComponent/component.ngfactory.js:95:22)
    at viewFactory_FileListComponent0 (/AppModule/FileListComponent/component.ngfactory.js:429:10)
    at _View_SearchDetails0.createInternal (/AppModule/SearchDetails/component.ngfactory.js:31:20)
    at _View_SearchDetails0.DebugAppView.create (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:9370:48)
    at _View_SearchDetails_Host0.createInternal (/AppModule/SearchDetails/host.ngfactory.js:18:14)
    at _View_SearchDetails_Host0.DebugAppView.create (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:9370:48)
    at ComponentFactory.create (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:5809:40)
    at ViewContainerRef_.createComponent (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:4857:49)
    at RouterOutlet.activate (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:3457:44)
    at ActivateRoutes.placeComponentIntoOutlet (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2955:20)
    at ActivateRoutes.activateRoutes (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2933:26)
    at eval (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2902:23)
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2901:33)
    at ActivateRoutes.activate (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2896:18)
    at eval (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2646:60)
    at SafeSubscriber.eval [as _next] (eval at <anonymous> (http://localhost:8080/vendor.js:112:2), <anonymous>:94:25)
    at SafeSubscriber.__tryOrUnsub (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:223:16)
    at SafeSubscriber.next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:172:22)
    at Subscriber._next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:125:26)
    at Subscriber.next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:89:18)
    at MergeMapSubscriber.notifyNext (eval at <anonymous> (http://localhost:8080/vendor.js:498:2), <anonymous>:133:30)
    at InnerSubscriber._next (eval at <anonymous> (http://localhost:8080/vendor.js:300:2), <anonymous>:23:21)
    at InnerSubscriber.Subscriber.next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:89:18)
    at MapSubscriber._next (eval at <anonymous> (http://localhost:8080/vendor.js:348:2), <anonymous>:83:26)
    at MapSubscriber.Subscriber.next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:89:18)
    at ReduceSubscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:516:2), <anonymous>:105:30)
    at ReduceSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MergeMapSubscriber.notifyComplete (eval at <anonymous> (http://localhost:8080/vendor.js:498:2), <anonymous>:155:30)
    at InnerSubscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:300:2), <anonymous>:30:21)
    at InnerSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MapSubscriber.Subscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:132:26)
    at MapSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MapSubscriber.Subscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:132:26)
    at MapSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at LastSubscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:528:2), <anonymous>:110:25)
    at LastSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MergeAllSubscriber.notifyComplete (eval at <anonymous> (http://localhost:8080/vendor.js:510:2), <anonymous>:105:30)
    at InnerSubscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:300:2), <anonymous>:30:21)
    at InnerSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MapSubscriber.Subscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:132:26)
    at MapSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at eval (eval at <anonymous> (http://localhost:8080/vendor.js:240:2), <anonymous>:67:36)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:6206:41)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:114:43)
    at eval (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:502:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:265:35)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:6197:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:264:40)
    at Zone.runTask (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:154:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:401:35)
    at HTMLDivElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:339:25)
    at BrowserDomAdapter.createStyleElement (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:656:18)
    at DomSharedStylesHost._addStylesToHost (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1271:53)
    at eval (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1281:65)
    at Set.forEach (native)
    at DomSharedStylesHost.onStylesAdded (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1281:29)
    at DomSharedStylesHost.SharedStylesHost.addStyles (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1249:18)
    at new DomRenderer (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1354:53)
    at DomRootRenderer_.DomRootRenderer.renderComponent (eval at <anonymous> (http://localhost:8080/vendor.js:208:2), <anonymous>:1323:28)
    at DebugDomRootRenderer.renderComponent (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:8758:56)
    at _View_FileListComponent0.AppView (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:9131:43)
    at new DebugAppView (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:9363:20)
    at _View_FileListComponent0 [as clazz] (/AppModule/FileListComponent/component.ngfactory.js:95:22)
    at viewFactory_FileListComponent0 (/AppModule/FileListComponent/component.ngfactory.js:429:10)
    at _View_SearchDetails0.createInternal (/AppModule/SearchDetails/component.ngfactory.js:31:20)
    at _View_SearchDetails0.DebugAppView.create (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:9370:48)
    at _View_SearchDetails_Host0.createInternal (/AppModule/SearchDetails/host.ngfactory.js:18:14)
    at _View_SearchDetails_Host0.DebugAppView.create (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:9370:48)
    at ComponentFactory.create (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:5809:40)
    at ViewContainerRef_.createComponent (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:4857:49)
    at RouterOutlet.activate (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:3457:44)
    at ActivateRoutes.placeComponentIntoOutlet (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2955:20)
    at ActivateRoutes.activateRoutes (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2933:26)
    at eval (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2902:23)
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2901:33)
    at ActivateRoutes.activate (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2896:18)
    at eval (eval at <anonymous> (http://localhost:8080/vendor.js:450:2), <anonymous>:2646:60)
    at SafeSubscriber.eval [as _next] (eval at <anonymous> (http://localhost:8080/vendor.js:112:2), <anonymous>:94:25)
    at SafeSubscriber.__tryOrUnsub (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:223:16)
    at SafeSubscriber.next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:172:22)
    at Subscriber._next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:125:26)
    at Subscriber.next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:89:18)
    at MergeMapSubscriber.notifyNext (eval at <anonymous> (http://localhost:8080/vendor.js:498:2), <anonymous>:133:30)
    at InnerSubscriber._next (eval at <anonymous> (http://localhost:8080/vendor.js:300:2), <anonymous>:23:21)
    at InnerSubscriber.Subscriber.next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:89:18)
    at MapSubscriber._next (eval at <anonymous> (http://localhost:8080/vendor.js:348:2), <anonymous>:83:26)
    at MapSubscriber.Subscriber.next (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:89:18)
    at ReduceSubscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:516:2), <anonymous>:105:30)
    at ReduceSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MergeMapSubscriber.notifyComplete (eval at <anonymous> (http://localhost:8080/vendor.js:498:2), <anonymous>:155:30)
    at InnerSubscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:300:2), <anonymous>:30:21)
    at InnerSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MapSubscriber.Subscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:132:26)
    at MapSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MapSubscriber.Subscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:132:26)
    at MapSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at LastSubscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:528:2), <anonymous>:110:25)
    at LastSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MergeAllSubscriber.notifyComplete (eval at <anonymous> (http://localhost:8080/vendor.js:510:2), <anonymous>:105:30)
    at InnerSubscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:300:2), <anonymous>:30:21)
    at InnerSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at MapSubscriber.Subscriber._complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:132:26)
    at MapSubscriber.Subscriber.complete (eval at <anonymous> (http://localhost:8080/vendor.js:130:2), <anonymous>:114:18)
    at eval (eval at <anonymous> (http://localhost:8080/vendor.js:240:2), <anonymous>:67:36)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:6206:41)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:114:43)
    at eval (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:502:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:265:35)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:6197:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:264:40)
    at Zone.runTask (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:154:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:401:35)
    at HTMLDivElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:339:25)
    at resolvePromise (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:468:31)
    at eval (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:445:13)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:6206:41)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:114:43)
    at eval (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:502:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:265:35)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8080/vendor.js:100:2), <anonymous>:6197:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:264:40)
    at Zone.runTask (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:154:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:401:35)
    at HTMLDivElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8080/polyfills.js:2492:2), <anonymous>:339:25)
```

Patching BrowserDomAdapter.prototype.appendChild with the below helps to demonstrate how weird this is:
```
BrowserDomAdapter.prototype.appendChild = function (el, node) {
  console.log('started BrowserDomAdapter.appendChild');
  el.appendChild(node);
  console.log('finished BrowserDomAdapter.appendChild');
};
```

The error is thrown at the line ```this.appendChild(style, this.createTextNode(css));``` in BrowserDomAdapter.createStyleElement. If I pause on that exception and use the console to invoke some functions:

```this.appendChild(style, this.createTextNode(css));``` 
1) Throws error just like in this stack trace, this.appendChild not a function (JS PLS, I CAN SEE IT IS A FUNCTION!!!)

```this.appendChild(style);```
1) Logs 'started BrowserDomAdapter.appendChild' (INSIDE THE FUNCTION THAT IS NOT A FUNCTION)
2) Throws ```TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'``` - the native error for calling element.appendChild with missing second arg.

```this.appendChild(style, doc.createTextNode(css))```
1) Logs 'started BrowserDomAdapter.appendChild'
2) Logs 'finished BrowserDomAdapter.appendChild'
WORKS!!!!???

This makes no sense! I can see the difference between calls are just thin wrappers around the same code. I don't understand how/why the function just "disappears".

**Expected behavior**
Should append CSS to head without throwing.

**Minimal reproduction of the problem with instructions**
I don't have a minimal demo. I can provide one if needed, or I can provide a small app that I have been working on that exhibits this behaviour if necessary. Hoping this sticks out at someone as something obvious but to me, it's magic (the black kind).

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Using Webpack with ExtractTextPlugin to get CSS (as shown in Angular 2 quick start demo on official site). Using webpack webdev server.

* **Angular version:** 2.1.1

* **Browser:** Chrome latest
 
* **Language:** Typescript 2.0.6

Feel free to ask any questions. I've been working on this for hours trying to understand why this happens, so I've covered quite a lot of ground (but got nowhere).

Workaround is patching BrowserDomAdapter on start up:
```
import { __platform_browser_private__ } from '@angular/platform-browser';

const BrowserDomAdapter = __platform_browser_private__.BrowserDomAdapter;
BrowserDomAdapter.prototype.createStyleElement = function (css: string, doc = document) {
    const style = <HTMLStyleElement>doc.createElement('style');
    this.appendChild(style, doc.createTextNode(css));
    return style;
};
```

**Comment by DzmitryShylovich** [comment]
Should be fixed https://github.com/angular/angular/commit/8b2dfb2eca83b571f7c87db20297169eb5657773

**Comment by DzmitryShylovich** [comment]
@nth-commit can u close it pls if it was fixed?

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource can be closed
