### ISSUE TITLE
Trying to compile Angular AOT, running into TypeError with compiler-cli

### ISSUE THREAD

**Issue by quiringk** [angular/angular#12872]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After following all the AOT tutorials and configuring, I run 

`"node_modules/.bin/ngc" -p tsconfig-aot.json`

and get the following error:

`
TypeError: compiler.AnimationParser is not a constructor
    at Function.CodeGenerator.create (C:\Projects\NeilKellyClient4\node_modules\@angular\compiler-cli\src\codegen.js:108:400)
    at codegen (C:\Projects\NeilKellyClient4\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (C:\Projects\NeilKellyClient4\node_modules\@angular\tsc-wrapped\src\main.js:37:16)
    at Object.<anonymous> (C:\Projects\NeilKellyClient4\node_modules\@angular\compiler-cli\src\main.js:16:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Compilation failed
`

**Expected behavior**

AOT compiles

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10
node: 6.9.1
os: win32 x64
npm: 3.10.6

* **Angular version:** 2.0.X

2.1.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

command line running ^ command
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

typescript 2.0.3

* **Node (for AoT issues):** `node --version` =

**Comment by quiringk** [comment]
Downgraded to 2.1.0 with same as everything above, and now instead of the "compiler.AnimationParser" error I am getting this error:

`
TypeError: Cannot read property 'AssetUrl' of undefined
    at Object.<anonymous> (C:\Projects\NeilKellyClient4\node_modules\@angular\compiler-cli\src\private_import_compiler.js:10:51)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Projects\NeilKellyClient4\node_modules\@angular\compiler-cli\src\reflector_host.js:13:33)
    at Module._compile (module.js:570:32)
`

**Comment by vicb** [comment]
Please add a quick repro (leave just the code necessary to reproduce the issue). Otherwise we will have to close the issue. Thanks

**Comment by quiringk** [comment]
OK but this is a large project that I have been working on since April. What would be the relevant code you are looking for?

**Comment by reblace** [comment]
fwiw, I just got the same issue in my project. Trying to downgrade to 2.1.1 for everything and I'll see if I can dig up any info on what's going on.

**Comment by quiringk** [comment]
I actually think I just got passed this issue. I cloned angular quickstart and tried building AOT with all the latest versions of angular and cli (2.2.0 for everything.) It worked so I went back into my code, removed node_modules, and reinstalled everyting with latest angular versions and I got passed this issue. I think at some point some of my versions were off with different angular versions and compiler-cli versions etc.

**Comment by chrisnicola** [comment]
Currently seeing this issue with 2.2.4 for everything. Cleaned and re-installed node_modules as well.

**Comment by DzmitryShylovich** [comment]
it's not actionable without a repro

**Comment by mishudark** [comment]
I have the same issue with 2.2.4

**Comment by e-nouri** [comment]
I have the same problem my configuration is like so:

root@70aa2c4099c0:/data# node -v
v6.9.1
root@70aa2c4099c0:/data# npm -v
3.8.9
root@70aa2c4099c0:/data# ng --version
angular-cli: 1.0.0-beta.22
node: 6.9.1
os: linux x64

angular-cli@1.0.0-beta.21

**Comment by DzmitryShylovich** [comment]
@quiringk can you pls add s small repro?

**Comment by quiringk** [comment]
@DzmitryShylovich I got passed the issue and explained above

**Comment by DzmitryShylovich** [comment]
@quiringk so can you close the issue pls? thx
