### ISSUE TITLE
running ng-xi18n throws TypeError: this._directiveNormalizer.normalizeTemplate is not a function

### ISSUE THREAD

**Issue by tdesmet** [angular/angular#12887]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When running ./node_modules/.bin/ng-xi18n the following error is thrown

> TypeError: this._directiveNormalizer.normalizeTemplate is not a function
    at CompileMetadataResolver._loadDirectiveMetadata (C:\Workspace\i18n-test\node_modules\@angular\compiler\bundles\compiler.umd.js:14493:60)
    at C:\Workspace\i18n-test\node_modules\@angular\compiler\bundles\compiler.umd.js:14644:50
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (C:\Workspace\i18n-test\node_modules\@angular\compiler\bundles\compiler.umd.js:14634:56)
    at CompileMetadataResolver.loadNgModuleMetadata (C:\Workspace\i18n-test\node_modules\@angular\compiler\bundles\compiler.umd.js:14566:31)
    at addNgModule (C:\Workspace\i18n-test\node_modules\@angular\compiler\bundles\compiler.umd.js:12915:37)
    at C:\Workspace\i18n-test\node_modules\@angular\compiler\bundles\compiler.umd.js:12929:16
    at Array.forEach (native)
    at _loadNgModules (C:\Workspace\i18n-test\node_modules\@angular\compiler\bundles\compiler.umd.js:12928:28)
    at Object.analyzeNgModules (C:\Workspace\i18n-test\node_modules\@angular\compiler\bundles\compiler.umd.js:12685:14)
Extraction failed

**Expected behavior**

running ng-xi18n should work and not throw errors.

**Minimal reproduction of the problem with instructions**
checkout https://github.com/tdesmet/i18n-test
run `npm install`
run `./node_modules/.bin/ng-xi18n -p src/tsconfig.json`

If your downgrade to version 2.1.x then it works.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10
angular-cli

* **Angular version:** 2.2.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by benjamincombes** [comment]
Same issue for me for Angular 2.2.0 only, on macOS 10.12.1, with node v6.9.1.
But I have the problem when running :
`node_modules/.bin/ngc -p .`

**Comment by sondreb** [comment]
Same problem here, works fine with 2.1.2 but not 2.2.0.

**Comment by vicb** [comment]
Seems like a dep issue, `npm i @angular/compiler-cli@2.2.0` will help. (`npm i` would install 2.1.2).

**Comment by IgorMinar** [comment]
this is a problem with angular-cli's package.json. I spoke with @hansl he's fixing it. we'll need a new cli release to resolve this issue

**Comment by DzmitryShylovich** [comment]
@tdesmet is this still valid with the latest cli and angular 4?

**Comment by tdesmet** [comment]
Sorry, haven't had time to upgrade yet.
