### ISSUE TITLE
Unhandled Promise rejection: Cannot set property 'customProperty' of undefined ;

### ISSUE THREAD

**Issue by AbinayaSubbiah** [angular/angular#12880]
When i upgrade angular 2 application to **2.2.0** from **2.0.1** getting console error in custom component.

```
zone.js:388 Unhandled Promise rejection: Cannot set property 'customProperty' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'customProperty' of undefined(…) TypeError: Cannot set property 'customProperty' of undefined
    at eval (/AppModule/class13/wrapper.ngfactory.js:190:56)
    at evalExpression (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16566:96)
    at jitStatements (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:16572:14)
    at RuntimeCompiler._compileDirectiveWrapper (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17486:39)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17396:25)
    at Array.forEach (native)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17393:50)
    at Array.forEach (native)
    at RuntimeCompiler._compileComponents (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17391:45)
    at createResult (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:17319:21)
```

**Comment by teddywest32** [comment]
@AbinayaSubbiah have you added `zone.js` to your rendering file?? Could you post your codes here??

**Comment by AbinayaSubbiah** [comment]
@teddywest32  yes i have added zone.js file . And my app.module.ts code is

```
import { NgModule, enableProdMode, ErrorHandler } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { Custom_component } from './customComponent.component';

import { AppComponent } from './app.component';

@NgModule({
  imports: [BrowserModule, FormsModule, HttpModule],
  declarations: [AppComponent, Custom_component],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by teddywest32** [comment]
@AbinayaSubbiah  This doesn't provides more details.
Could you post your `index.html`, `main.ts`, `systemjs.config.js` too.

**Comment by AbinayaSubbiah** [comment]
@teddywest32  index.html as below

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Essential JavaScript for Angular 2 | SystemJS seed</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="node_modules/bootstrap/dist/css//bootstrap.min.css">

	<!-- Polyfill(s) for older browsers -->
	<script src="node_modules/core-js/client/shim.min.js"></script>
	<script src="node_modules/zone.js/dist/zone.js"></script>
	<script src="node_modules/reflect-metadata/Reflect.js"></script>
	<script src="node_modules/systemjs/dist/system.src.js"></script>

	<!-- 2. Configure SystemJS -->
	<script src="systemjs.config.js"></script>

	<script>       
      System.import('app')
            .then(null, console.error.bind(console));
    </script>

</head>

<!-- 3. Display the application -->

<body>
	<my-app>
		
	</my-app>
</body>

</html>
```

main.ts

```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule);
```
systemjs.config.js

```
/**
* System configuration for Angular 2 samples
* Adjust as necessary for your application needs.
*/
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'src',
      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      // other libraries
      'rxjs': 'npm:rxjs',
      'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api',
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
      }
    }
  });
})(this);

```

**Comment by teddywest32** [comment]
@AbinayaSubbiah  
I didn't find the codes posted from your `app.component.ts` and `customComponent.component.ts`

For now just use a simpler implementation by removing `customComponent.component.ts` from `app.module.ts` and adding these codes to check is there issue with your `selector` on `app.component.ts`.

```
import { Component } from '@angular/core';

@Component({
	selector: 'my-app',
	template: `<p>Hello World! </p>`
})

export class AppComponent {}
```

Hopefully it should work if there is no any issue with your dependencies.

**Comment by vicb** [comment]
Please provide a minimal repo in a plunker

**Comment by AbinayaSubbiah** [comment]
@vicb    find plnkr link below

  http://plnkr.co/edit/H8JdEJPEQ5e1l3xJEqg0?p=preview

**Comment by vicb** [comment]
The pb is `Utils.AngularizeInputs()` which returns `model.xxx`

Inpputs can rename a property binding name to class field name, they can not be used to traverse a path.

**Comment by AbinayaSubbiah** [comment]
@vicb How its worked in previous versions of Angular 2 ?

**Comment by vicb** [comment]
@AbinayaSubbiah that was a coincidence, it was never intended to work.
