### ISSUE TITLE
Aot runtime error thrown on navigation with queryParams

### ISSUE THREAD

**Issue by spock123** [angular/angular#12890]
After upgrading to 2.2.0 ( and router 3.2.0) I am getting a runtime error on navigation with queryParams.

`EXCEPTION: Cannot read property 'appendChild' of null`

The weird thing is that the error does not occur while in development mode, nor does the AoT compiler throw any error. 

Angular: 2.2.0
Angular router: 3.2.0

Example: 

router.navigate( [ 'home'], { queryParams: { test: 'test' }})

Anyone got this error as well?

Angular 2.1.2 works fine with precisely the same code.

// Update
So I tried only to update Angular to 2.2.0 and keep Angular-Router on 3.1.2, and the issue remains.

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by spock123** [comment]
@DzmitryShylovich  working on it - just wanted to know if other had the same issue already :)

thanks

**Comment by DzmitryShylovich** [comment]
> EXCEPTION: Cannot read property 'appendChild' of null

sounds similar to https://github.com/angular/angular/issues/12853

**Comment by spock123** [comment]
@DzmitryShylovich  

I am not using dynamic styles, styleUrls or anything.
But I am using Material2 (alpha 10), so could be in the components of course..

**Comment by DzmitryShylovich** [comment]
And the reason I guess https://github.com/angular/angular/commit/d708a8859ca3078a98e371b33ad560096070ad00

**Comment by michalstepien** [comment]
I have the same error. Not with AOT.

TypeError: Cannot read property 'appendChild' of null
    at appendChild (webpack:///./~/@angular/platform-browser/bundles/platform-browser.umd.js?:1200:54)
    at AppView.View_OfertyDetail29.visitRootNodesInternal (/OfertyDetailModule/OfertyDetail/component.ngfactory.js:4900:3)
    at AppView._renderAttach (webpack:///./~/@angular/core/bundles/core.umd.js?:9256:26)
    at AppView.attachAfter (webpack:///./~/@angular/core/bundles/core.umd.js?:9234:18)
    at ViewContainer.attachView (webpack:///./~/@angular/core/bundles/core.umd.js?:9561:18)
    at ViewContainerRef_.insert (webpack:///./~/@angular/core/bundles/core.umd.js?:7137:27)
    at ViewContainerRef_.createEmbeddedView (webpack:///./~/@angular/core/bundles/core.umd.js?:7117:18)
    at NgIf.set [as ngIf] (webpack:///./~/@angular/common/bundles/common.umd.js?:1427:41)
    at Wrapper_NgIf.check_ngIf (/CommonModule/NgIf/wrapper.ngfactory.js:17:23)

**Comment by michalstepien** [comment]
I use AlertComponent from this: https://github.com/valor-software/ng2-bootstrap/blob/development/components/alert/alert.component.ts
When I do *ngFor it fails:
`<alert type="danger">
            <span *ngFor="let ddd of ppp"></span>
 </alert>`

**Comment by michalstepien** [comment]
I will create plnkr.

**Comment by michalstepien** [comment]
In prod mode:

http://plnkr.co/edit/cZyFnzWTTvy8gFe5iNLL?p=preview

**Comment by tbosch** [comment]
This has the same root error as https://github.com/angular/angular/issues/12911. Closing as duplicate.

**Comment by naveedahmed1** [comment]
Does anyone have this issue when using changeDetection: ChangeDetectionStrategy.OnPush or  ChangeDetectorRef.detach(); /.detectChanges(); ?
