### ISSUE TITLE
valid CSS selector results in parsing error

### ISSUE THREAD

**Issue by aafische** [angular/angular#12949]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Template:
&lt;ng-content select="[my-attribute]"&gt;&lt;/ng-content&gt;
&lt;ng-content select=":not([my-attribute])"&gt;&lt;/ng-content&gt;

Calling template:
&lt;my-template>
    &lt;div id="div1"&gt;&lt;/div&gt;
    &lt;div id="div2" my-attribute>&lt;/div&gt;
    &lt;div id="div3"&gt;&lt;/div&gt;
    &lt;div id="div4" my-attribute>&lt;/div&gt;
&lt;/my-template&gt;

**Expected behavior**

Template should render as:
    &lt;div id="div2" my-attribute&gt;&lt;/div&gt;
    &lt;div id="div4" my-attribute&gt;&lt;/div&gt;
    &lt;div id="div1"&gt;&lt;/div&gt;
    &lt;div id="div3"&gt;&lt;/div&gt;

Instead, this line throws, because `selectables` is undefined:
https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/selector.ts#L303

Unhandled Promise rejection: Cannot read property 'concat' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'concat' of undefined(…) TypeError: Cannot read property 'concat' of undefined
    at SelectorMatcher._matchTerminal (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1395:40)
    at SelectorMatcher.match (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1353:25)
    at ElementContext.findNgContentIndex (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:9300:39)
    at TemplateParseVisitor.visitElement (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:8728:39)
    at Element.visit (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:4688:78)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:4703:31)
    at Array.forEach (native)
    at visitAll (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:4702:13)
    at TemplateParseVisitor.visitElement (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:8722:26)
    at Element.visit (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:4688:78)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:4703:31)

**Minimal reproduction of the problem with instructions**

Plunker added:  http://plnkr.co/edit/SHiwpgUOUenxyixcYCrL

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Pls add a repro in plunkr.

**Comment by aafische** [comment]
Sure.  Here you go:  http://plnkr.co/edit/SHiwpgUOUenxyixcYCrL
