### ISSUE TITLE
Unable to use lazy loading for wildcard route

### ISSUE THREAD

**Issue by slubowsky** [angular/angular#12955]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Add a wildcard route for handling 404's as described in documentation - https://angular.io/docs/ts/latest/guide/router.html. It works. Change the PageNotFoundComponent to be lazy loaded (exactly as any other lazy loaded component - which are working in same application) and instead of navigation you get an error on an unmatched route:
```
error_handler.js:47 EXCEPTION: Uncaught (in promise): TypeError: segment.hasChildren is not a function
TypeError: segment.hasChildren is not a function
    at serializeSegment (http://localhost:4200/main.bundle.js:8576:17)
    at serializeSegment (http://localhost:4200/main.bundle.js:8578:13)
    at DefaultUrlSerializer.serialize (http://localhost:4200/main.bundle.js:8565:29)
    at Router.serializeUrl (http://localhost:4200/main.bundle.js:14731:80)
    at MergeMapSubscriber.project (http://localhost:4200/main.bundle.js:14827:231)
    at MergeMapSubscriber._tryNext (http://localhost:4200/main.bundle.js:11011:27)
    at MergeMapSubscriber._next (http://localhost:4200/main.bundle.js:11001:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:4200/main.bundle.js:2737:18)
    at CatchSubscriber.Subscriber._next (http://localhost:4200/main.bundle.js:2773:26)
    at CatchSubscriber.Subscriber.next (http://localhost:4200/main.bundle.js:2737:18)
```

Making no changes other then hanging the route path from '**' to 'foo' and navigating to 'foo', the component lazy loads as expected, so it only the wildcard path that's causing the issue.

**Expected behavior**

Page should navigate to the correct lazy loaded component.

**Minimal reproduction of the problem with instructions**

Will try to add at a later date but should be simple to reproduce.

**What is the motivation / use case for changing the behavior?**

Want to keep app as small as possible. Don't expect any 404's but want the component available to be lazy loaded  just in case

**Please tell us about your environment:**

Windows 10, Visual StudiCode, node 7.0.0, Angular-cli 1.0.0-beta.20-4 ng serve

* **Angular version:** 2.0.X

2.0.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Only tried in Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =

**Comment by Lyoko-Jeremie** [comment]
I have the same bug.
when lazy load 404 page module use wildcard route, it say<code>Uncaught (in promise): TypeError: segment.hasChildren is not a function</code>.
  
happen in firefox, 
WebStorm 2016.3,
angular-cli: 1.0.0-beta.20-4,
node: 6.9.1,
os: win32 x64,
@angular/router@3.2.3,
typescript 2.1.1

**Comment by diestrin** [comment]
Nothing yet? Here's a plunkr reproducing the issue http://plnkr.co/edit/zNMFIieWukKQYYaGXiDo?p=preview

**Comment by felipedrumond** [comment]
I'm facing the same problem. Did you do any improvement on this, or created a workaround?

**Comment by slubowsky** [comment]
@felipedrumond I didn't. Doesn't break anything for me to make it eagerly loaded for now, and will be simple for me to switch to lazy whenever this bug is fixed, just change component back to loadChildren and remove the import

**Comment by slubowsky** [comment]
@DzmitryShylovich  No more error, but doesn't actually work either. The component does not appear. This happened when I updated my app and I see the same with the plunkr linked above, its now using 2.4.2, router 3.4.2 and lazy loaded 404 page still never appears

**Comment by DzmitryShylovich** [comment]
@slubowsky yeah https://github.com/angular/angular/issues/13848 working on it
