### ISSUE TITLE
Muliline comment

### ISSUE THREAD

**Issue by zapping** [angular/angular#12967]
I was trying out the routing feature from your guide when this issue propped up. The app-routing.module.ts file from your [guide](https://angular.io/docs/ts/latest/guide/router.html) was changed as follows:

```
import { NgModule }             from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { CrisisListComponent1 }  from './crisis-list1.component';
import { HeroListComponent1 }    from './hero-list1.component';
/*  import { CrisisListComponent }  from './crisis-list.component';
    import { HeroListComponent }    from './hero-list.component';    */

 const appRoutes: Routes = [
      { path: 'crisis-center', component: CrisisListComponent1 },
      { path: 'heroes', component: HeroListComponent1 }
];

@NgModule({
  imports: [
    RouterModule.forRoot(appRoutes)
  ],
  exports: [
    RouterModule
  ]
})
export class AppRoutingModule {}
```
This threw the following error
```
localhost/:17 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:56301/traceur
    Error: XHR error (404 Not Found) loading http://localhost:56301/traceur
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:56301/node_modules/zone.js/dist/zone.js:698:29)
        at ZoneDelegate.invokeTask (http://localhost:56301/node_modules/zone.js/dist/zone.js:265:35)
        at Zone.runTask (http://localhost:56301/node_modules/zone.js/dist/zone.js:154:47)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:56301/node_modules/zone.js/dist/zone.js:335:33)
    Error loading http://localhost:56301/traceur
    Unable to load transpiler to transpile http://localhost:56301/app/app-routing.module.js
    Error loading http://localhost:56301/app/app-routing.module.js as "./app-routing.module" from http://localhost:56301/app/app.module.js
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:56301/node_modules/zone.js/dist/zone.js:698:29)
        at ZoneDelegate.invokeTask (http://localhost:56301/node_modules/zone.js/dist/zone.js:265:35)
        at Zone.runTask (http://localhost:56301/node_modules/zone.js/dist/zone.js:154:47)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:56301/node_modules/zone.js/dist/zone.js:335:33)
    Error loading http://localhost:56301/traceur
    Unable to load transpiler to transpile http://localhost:56301/app/app-routing.module.js
    Error loading http://localhost:56301/app/app-routing.module.js as "./app-routing.module" from http://localhost:56301/app/app.module.js
```

But after changing the multiline comment to single line comment it worked. I asked the same question on [stackoverflow](http://stackoverflow.com/questions/40677324/comments-in-angular2) and one of the experts there said it seems like a bug with systemjs. Can you please check. Thanks.

My development environments are as follow:
OS: Windows
IDE: Visual studio 2015 update 3
http server: Visual studio builtin one
Angular version: 2.2.0
Browser: chrome
Language: Typescript. Infact its was setup using your [quickstart guide](https://angular.io/docs/ts/latest/quickstart.html)

**Comment by DzmitryShylovich** [comment]
> a bug with systemjs

file an issue in systemjs repo

**Comment by zapping** [comment]
Oh ok.
