### ISSUE TITLE
[BUG] Loading router on condition fails

### ISSUE THREAD

**Issue by AmitMY** [angular/angular#12988]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When having `ngIf` on a router view, it an error.
When changing the route (using routerLink), it shows the right component.
The error:
> error_handler.js:47EXCEPTION: Uncaught (in promise): Error: Cannot find primary outlet to load 'ProfileComponent'
Error: Cannot find primary outlet to load 'ProfileComponent'
    at getOutlet (http://localhost:4200/main.bundle.js:15707:19)
    at ActivateRoutes.activateRoutes (http://localhost:4200/main.bundle.js:15615:30)
    at http://localhost:4200/main.bundle.js:15572:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/main.bundle.js:15572:29)
    at ActivateRoutes.activate (http://localhost:4200/main.bundle.js:15558:14)
    at http://localhost:4200/main.bundle.js:15283:56
    at SafeSubscriber._next (http://localhost:4200/main.bundle.js:498:21)
    at SafeSubscriber.__tryOrSetError (http://localhost:4200/main.bundle.js:3846:16)
    at SafeSubscriber.next (http://localhost:4200/main.bundle.js:3788:27)ErrorHandler.handleError @ error_handler.js:47next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74NgZone.triggerError @ ng_zone.js:278onHandleError @ ng_zone.js:257ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131_loop_1 @ zone.js:412drainMicroTaskQueue @ zone.js:421
error_handler.js:52ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:52next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74NgZone.triggerError @ ng_zone.js:278onHandleError @ ng_zone.js:257ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131_loop_1 @ zone.js:412drainMicroTaskQueue @ zone.js:421
error_handler.js:53Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'ProfileComponent'
Error: Cannot find primary outlet to load 'ProfileComponent'
    at getOutlet (http://localhost:4200/main.bundle.js:15707:19)
    at ActivateRoutes.activateRoutes (http://localhost:4200/main.bundle.js:15615:30)
    at http://localhost:4200/main.bundle.js:15572:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/main.bundle.js:15572:29)
    at ActivateRoutes.activate (http://localhost:4200/main.bundle.js:15558:14)
    at http://localhost:4200/main.bundle.js:15283:56
    at SafeSubscriber._next (http://localhost:4200/main.bundle.js:498:21)
    at SafeSubscriber.__tryOrSetError (http://localhost:4200/main.bundle.js:3846:16)
    at SafeSubscriber.next (http://localhost:4200/main.bundle.js:3788:27)
    at resolvePromise (http://localhost:4200/main.bundle.js:99097:31)
    at resolvePromise (http://localhost:4200/main.bundle.js:99082:17)
    at http://localhost:4200/main.bundle.js:99131:17
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:98894:35)
    at Object.onInvokeTask (http://localhost:4200/main.bundle.js:30277:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:98893:40)
    at Zone.runTask (http://localhost:4200/main.bundle.js:98783:47)
    at drainMicroTaskQueue (http://localhost:4200/main.bundle.js:99030:35)ErrorHandler.handleError @ error_handler.js:53next @ application_ref.js:272schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74NgZone.triggerError @ ng_zone.js:278onHandleError @ ng_zone.js:257ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131_loop_1 @ zone.js:412drainMicroTaskQueue @ zone.js:421
zone.js:388Unhandled Promise rejection: Cannot find primary outlet to load 'ProfileComponent' ; Zone: angular ; Task: Promise.then ; Value: Error: Cannot find primary outlet to load 'ProfileComponent'(…) Error: Cannot find primary outlet to load 'ProfileComponent'
    at getOutlet (http://localhost:4200/main.bundle.js:15707:19)
    at ActivateRoutes.activateRoutes (http://localhost:4200/main.bundle.js:15615:30)
    at http://localhost:4200/main.bundle.js:15572:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/main.bundle.js:15572:29)
    at ActivateRoutes.activate (http://localhost:4200/main.bundle.js:15558:14)
    at http://localhost:4200/main.bundle.js:15283:56
    at SafeSubscriber._next (http://localhost:4200/main.bundle.js:498:21)
    at SafeSubscriber.__tryOrSetError (http://localhost:4200/main.bundle.js:3846:16)
    at SafeSubscriber.next (http://localhost:4200/main.bundle.js:3788:27)consoleError @ zone.js:388_loop_1 @ zone.js:417drainMicroTaskQueue @ zone.js:421
zone.js:390Error: Uncaught (in promise): Error: Cannot find primary outlet to load 'ProfileComponent'(…)

**Expected behavior**
It to work with a condition

**Minimal reproduction of the problem with instructions**
Super simple:
```
<div *ngIf="isLoggedIn">
    <router-outlet></router-outlet>
</div>
```

**What is the motivation / use case for changing the behavior?**
For example, loading the router module only when logged in, because some behaviours depend on the user being logged in.

**Please tell us about your environment:**

Windows 10, PHPStorm 2016, npm, nodejs-http

* **Angular version:** 2.3.0-beta.0

* **Browser:** All
 
* **Language:** HTML bug

* **Node (for AoT issues):** `node --version` = v6.9.1

**Comment by DzmitryShylovich** [comment]
It's intentional behavior.

**Comment by AmitMY** [comment]
@DzmitryShylovich Thanks. But why? Is there a post on this? I couldn't find one

**Comment by ericmartinezr** [comment]
https://github.com/angular/angular/issues/11100#issuecomment-242827341

**Comment by AmitMY** [comment]
@ericmartinezr Thanks!
Closed
