### ISSUE TITLE
Angular 2 Unit testing Component having dependent component gives error saying Can't resolve all parameters for componentName: (?, ?)

### ISSUE THREAD

**Issue by snehasis** [angular/angular#13087]
I am getting an error while doing unit test case for a Particular Component which depends upon another 2 components , so in the constructor we have those 2 components

   Node : v6.9.1 (AoT)
   "ionic-angular": "2.0.0-rc.2",
   "@angular/common": "2.2.0",
    "@angular/compiler": "2.2.0",
    "@angular/core": "2.2.0",
    "@angular/forms": "2.2.0",
    "@angular/http": "2.2.0",
    "@angular/platform-browser": "2.2.0",
    "@angular/platform-browser-dynamic": "2.2.0",
    "@angular/compiler-cli": "2.2.0",
    "@angular/platform-server": "2.2.0",

    "@types/jasmine": "^2.5.35",
    "jasmine-core": "2.5.2",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",

Below is the error which I am getting

Error: Can't resolve all parameters for NavParams: (?).

Below is the 2 file contents:
xyz.ts

import {Component, Input, Output, EventEmitter, Inject} from '@angular/core';
import { NavParams } from 'ionic-angular';
import {ViewController} from 'ionic-angular';

@Component({
  templateUrl: 'xyz.html'
})
export class XYZClass implements OnInit {
  constructor(
    @Inject(NavParams) protected navParams: NavParams
  ) {
       this.xyz = navParams.data.xyz;
  }
}

xyz-spec.ts

import {inject, TestBed} from '@angular/core/testing';
import {Http,BaseRequestOptions,Response,ResponseOptions} from "@angular/http";

import { Component, OnInit, Inject, Input, NgZone, Output, EventEmitter } from '@angular/core';
import { NavController, NavParams, ActionSheetController, AlertController, Platform, ViewController } from 'ionic-angular';

import {XYZClass} from './xyz.ts';

beforeEach(() => {
    TestBed.configureTestingModule({
        providers: [
            XYZClass,
            NavParams
        ]
    })
});

describe('XYZClass', () => {

    it('is XYZClass',
        inject([XYZClass], (comp: XYZClass) => {
            
            expect(comp).toBeTruthy();
        }));
        
});

Expected Result :
As described on Angular 2 Docs for Unit testing if anything Is dependent  for the the component it needs to be provided in the Providers list in TestBed.configureTestingModule. So the unit test spec should work and should not show error like "Can't resolve all parameters for NavParams: (?)."

**Comment by DzmitryShylovich** [comment]
Pls add a repro. You can use http://plnkr.co/edit/Ph8CxhfUm0vHhTq3UBdo?p=preview as a starting point

**Comment by readme42** [comment]
Same Problem here. All normal webpack build runs fine, but a test run (karma/jasmine) exits with

`Uncaught Error: Can't resolve all parameters for HelpPopoverDirective: (?, ?).`

Thats the directive. If i remove it completly, everything runs fine. (Its the only directive created with the new UpgradeComponent) 

````
@Directive({
    selector: "red-help-popover"
})
export class HelpPopoverDirective extends UpgradeComponent {
    @Input() redHelpPopoverPageId: string;
    constructor(elementRef: ElementRef, injector: Injector) {
        super("redHelpPopover", elementRef, injector);
    }
}
```

**Comment by readme42** [comment]
Okay - got it at least running. 

Changed
` constructor(elementRef: ElementRef, injector: Injector)`
to 
`constructor(@Inject(ElementRef) elementRef: ElementRef, @Inject(Injector) injector: Injector)`

Not all specs are green - but another exception is thrown during test run (i will ignore it for the moment):

```
'Unhandled Promise rejection:', 'Could not compile 'HelpPopoverDirective' because it is not a component.', '; Zone:', '<root>', '; Task:', 'Promise.then', '; Value:', Error{}, 'Error: Could not compile 'HelpPopoverDirective' because it is not a component.
    at assertComponent (http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:40520:15)
    at RuntimeCompiler._createCompiledHostTemplate (http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:40366:13)
    at http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:40339:37
    at Array.forEach (native)
    at http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:40337:45
    at Array.forEach (native)
    at RuntimeCompiler._compileComponents (http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:40326:43)
    at createResult (http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:40238:19)
    at ZoneDelegate.invoke (http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:35446:26)
    at Zone.run (http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:35328:43)
    at http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:35716:57
    at ZoneDelegate.invokeTask (http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:35479:35)
    at Zone.runTask (http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:35368:47)
    at drainMicroTaskQueue (http://localhost:8080/base/spec.bundle.js?6e2ccef7919c83b33d70f56d9fc899dce599e33d:35615:35)'
Error{rejection: Error{}, promise: ZoneAwarePromise{__zone_symbol__state: 0, __zone_symbol__value: Error{}}, zone: Zone{_properties: Object{}, _parent: null, _name: '<root>', _zoneDelegate: ZoneDelegate{_taskCounts: ..., zone: ..., _parentDelegate: ..., _forkZS: ..., _forkDlgt: ..., _interceptZS: ..., _interceptDlgt: ..., _invokeZS: ..., _invokeDlgt: ..., _handleErrorZS: ..., _handleErrorDlgt: ..., _scheduleTaskZS: ..., _scheduleTaskDlgt: ..., _invokeTaskZS: ..., _invokeTaskDlgt: ..., _cancelTaskZS: ..., _cancelTaskDlgt: ..., _hasTaskZS: ..., _hasTaskDlgt: ...}}, task: ZoneTask{runCount: 1, type: 'microTask', zone: Zone{_properties: ..., _parent: ..., _name: ..., _zoneDelegate: ...}, source: 'Promise.then', data: undefined, scheduleFn: undefined, cancelFn: null, callback: function () { ... }, invoke: function () { ... }}}
'newTerminal', Object{headId: 'newHeadId', detailsHeadId: 'newDetailsHeadId'}
'result is', Contact{patientId: undefined, type: undefined, id: '222'}
'could not save item!', Location{isMainLocation: undefined, abbr: undefined, name: undefined, desc: undefined, customKvdt: false, episodeTypes: Object{type0101: false, type0102: false, type0103: false, type0104: false}, kvSection: undefined, id: 'test'}


```

**Comment by juliemr** [comment]
Can you please provide a smaller reproducible case? Thanks.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource no repro, no feedback. can be closed

**Comment by readme42** [comment]
Sorry, i just forgot the feedback :(

I can't speak for the original author, but my problem described above was solved by fixing my webpack config. Somehow my webpack test config (and only that one) didnt recognize my tsconfig.json. So it used default settings without "emitDecoratorMetadata" and voila - all broken. Ironically this happened only on windows machines, never on macs.

**Comment by dherges** [comment]
Let me sum this up for people who stumble across similar issues:

#### Problem

Test run produces `Error: Can't resolve all parameters for MyComponent: (?, ?).`. The stacktrace may look like this:

```
at SyntaxError.ZoneAwareError (webpack:///~/zone.js/dist/zone.js:992:0 <- test.js:59216:33)
at SyntaxError.BaseError [as constructor] (webpack:///modules/@angular/compiler/src/facade/errors.ts:19:4 <- test.js:64292:16)
at new SyntaxError (webpack:///modules/@angular/compiler/src/util.ts:136:33 <- test.js:6450:16)
at CompileMetadataResolver._getDependenciesMetadata (webpack:///modules/@angular/compiler/src/metadata_resolver.ts:848:10 <- test.js:17977:31)

at CompileMetadataResolver._getTypeMetadata (webpack:///modules/@angular/compiler/src/metadata_resolver.ts:715:19 <- test.js:17852:26)
at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (webpack:///modules/@angular/compiler/src/metadata_resolver.ts:311:17 <- test.js:17492:24)
at CompileMetadataResolver._loadDirectiveMetadata (webpack:///modules/@angular/compiler/src/metadata_resolver.ts:174:4 <- test.js:17368:23)
at webpack:///modules/@angular/compiler/src/metadata_resolver.ts:395:46 <- test.js:17569:54
at Array.forEach (native)
at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (webpack:///modules/@angular/compiler/src/metadata_resolver.ts:394:34 <- test.js:17568:41)
at webpack:///modules/@angular/compiler/src/jit/compiler.ts:159:50 <- test.js:43103:58
at Array.forEach (native)
at JitCompiler._loadModules (webpack:///modules/@angular/compiler/src/jit/compiler.ts:158:38 <- test.js:43102:43)
at JitCompiler._compileModuleAndAllComponents (webpack:///modules/@angular/compiler/src/jit/compiler.ts:134:49 <- test.js:43076:52)
at JitCompiler.compileModuleAndAllComponentsAsync (webpack:///modules/@angular/compiler/src/jit/compiler.ts:96:16 <- test.js:43037:21)
at TestingCompilerImpl.compileModuleAndAllComponentsAsync (webpack:///~/@angular/compiler/bundles/compiler-testing.umd.js:485:0 <- test.js:63966:35)
at TestBed.compileComponents (webpack:///~/@angular/core/bundles/core-testing.umd.js:757:0 <- test.js:14489:35)
at Function.TestBed.compileComponents (webpack:///~/@angular/core/bundles/core-testing.umd.js:660:49 <- test.js:14392:71)
at Object.<anonymous> (webpack:///src/my.component.spec.ts:19:9 <- test.js:60408:12)
```

The error is propagated by the Angular compiler, e.g. thru `TestBed.compileComponents()`. Example:

```ts
TestBed.configureTestingModule({ declarations: [ MyComponent ] }).compileComponents()
``` 

The component's class being tested relies on constructor injection WITHOUT explicit `@Inject()` decorators. It may look like:

```ts
@Component({ /* .. */ })
export class MyComponent {

  constructor(
    private _elementRef: ElementRef,
    private _renderer: Renderer
  ) { }

}
```

#### Solution

Make sure `emitDecoratorMetadata` is enabled by testing configuration. Add the following options to `tsconfig.spec.json`. Take care that ***THIS*** is the one tsconfig file that is used for testing!

```json
  "compilerOptions": {
    ..
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    ..
  }
```

**Comment by MiroKov** [comment]
I needed to use 
`constructor(@Inject(ElementRef) private el: ElementRef, @Inject(Renderer2) private renderer: Renderer2)`
Solution from @dherges  didn't work for me.
