### ISSUE TITLE
Aot throwing compile error relating to 'getAnimationEntryMetadata'

### ISSUE THREAD

**Issue by mip1983** [angular/angular#13157]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I've followed the cookbook guide on aot for my app (after ripping out lazy loaded modules as they don't work with rollup), and now I'm getting different error when running:

"node_modules/.bin/ngc" -p tsconfig-aot.json

The stack trace is:

```
> λ "node_modules/.bin/ngc" -p tsconfig-aot.json
> TypeError: Cannot read property 'map' of undefined
>     at CompileMetadataResolver.**getAnimationEntryMetadata** (C:\Users\q799755\Documents\Home\Ed Project\SiteLatest\WhitePondFarm\node_modules\@angular\compiler\bundles\compiler.umd.js:14402:39)
>     at C:\Users\q799755\Documents\Home\Ed Project\SiteLatest\WhitePondFarm\node_modules\@angular\compiler\bundles\compiler.umd.js:14515:70
>     at Array.map (native)
>     at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (C:\Users\q799755\Documents\Home\Ed Project\SiteLatest\WhitePondFarm\node_modules\@angular\compiler\bundles\compiler.umd.js:14515:38)
>     at CompileMetadataResolver._loadDirectiveMetadata (C:\Users\q799755\Documents\Home\Ed Project\SiteLatest\WhitePondFarm\node_modules\@angular\compiler\bundles\compiler.umd.js:14446:44)
>     at C:\Users\q799755\Documents\Home\Ed Project\SiteLatest\WhitePondFarm\node_modules\@angular\compiler\bundles\compiler.umd.js:14712:89
>     at C:\Users\q799755\Documents\Home\Ed Project\SiteLatest\WhitePondFarm\node_modules\@angular\compiler\bundles\compiler.umd.js:12714:153
>     at Array.map (native)
>     at C:\Users\q799755\Documents\Home\Ed Project\SiteLatest\WhitePondFarm\node_modules\@angular\compiler\bundles\compiler.umd.js:12714:122
>     at Array.map (native)
> Compilation failed
```

Having noticed the error is referring to 'getAnimationEntryMetadata', the only animation code I have is route change animations:

Component:

```ts
import { Component, HostBinding, trigger, transition, animate, style, state } from '@angular/core';

import { RouteAnimationComponent } from '../shared/route-animation.component';
import { RouteAnimations } from '../shared/route.animation';

@Component({
  moduleId: module.id,
  selector: 'home',
  templateUrl: "home.component.html",
  animations: [
    RouteAnimations.FadeAnimation
  ]
})
export class HomeComponent extends RouteAnimationComponent { 
}
```

Extends:
```ts
import { HostBinding } from '@angular/core';

export class RouteAnimationComponent { 
  @HostBinding('@routeAnimation') get routeAnimation() {
      return true;
  }

  @HostBinding('style.display') get display() {
    return 'block';
  }
}
```

RouteAnimations:

```ts
import { trigger, transition, animate, style, state } from '@angular/core';

export class RouteAnimations {

    public static FadeAnimation = trigger('routeAnimation', [
      state('*',
        style({
          opacity: 1
        }),
      ),
      transition('void => *', [
        style({
          opacity: 0
        }),
        animate('0.5s ease-in')
      ]),
      transition('* => void', [
        animate('0.5s ease-out', style({
          opacity: 0
        }))
      ])
    ]);

}
```

**Expected behavior**
I'm not sure why the app isn't compiling. Works fine with JIT.

**Minimal reproduction of the problem with instructions**
I can't really demo aot with plunker, but you can take the above component code and compile with a basic AoT app from the cookbook: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

**What is the motivation / use case for changing the behavior?**
Cannot compile.

**Please tell us about your environment:**
Windows 7, npm 3.10.3

* **Angular version:** 2.2.3

* **Browser:** N/A
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =  3.10.3

**Comment by matsko** [comment]
@chuckjaz does everything in here look correct for AOT?

**Comment by matsko** [comment]
@mip1983 is this still an issue with 2.4.1/4.0.0-beta.1? We made a variety of updates to AOT and animations with the recent wave of commits.

**Comment by mip1983** [comment]
@matsko I've recently re-tested this and it's no longer an issue, I'll close, thanks.
