### ISSUE TITLE
Upgraded components with ng-transclude error if there is no transcluded content

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#13271]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

When an upgraded ng1 component contains an ng-transclude directive, but the element is not supplied with content to transclude — e.g. it is empty, or should use fallback content — then the following error is thrown:

```
VM3034 angular.js:14110TypeError: Cannot read property '$destroy' of undefined
    at ngTranscludeCloneAttachFn (https://unpkg.com/angular/angular.js:31320:29)
    at attachChildNodes (https://unpkg.com/@angular/upgrade@2.3.0-rc.0/bundles/upgrade-static.umd.js:568:92)
    at controllersBoundTransclude (https://unpkg.com/angular/angular.js:9542:20)
    at Object.ngTranscludePostLink (https://unpkg.com/angular/angular.js:31306:9)
    at eval (https://unpkg.com/angular/angular.js:1259:18)
    at invokeLinkFn (https://unpkg.com/angular/angular.js:10095:9)
    at nodeLinkFn (https://unpkg.com/angular/angular.js:9492:11)
    at compositeLinkFn (https://unpkg.com/angular/angular.js:8757:13)
    at MyUpgradedComponent.publicLinkFn [as linkFn] (https://unpkg.com/angular/angular.js:8637:30)
    at MyUpgradedComponent.UpgradeComponent.ngOnInit (https://unpkg.com/@angular/upgrade@2.3.0-rc.0/bundles/upgrade-static.umd.js:569:18)
    at Wrapper_MyUpgradedComponent.ngDoCheck (/AppModule/MyUpgradedComponent/wrapper.ngfactory.js:25:53)
    at CompiledTemplate.proxyViewClass.View_App0.detectChangesInternal (/AppModule/App/component.ngfactory.js:27:33)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (https://unpkg.com/@angular/core@2.3.0-rc.0/bundles/core.umd.js:12522:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (https://unpkg.com/@angular/core@2.3.0-rc.0/bundles/core.umd.js:12669:48)
    at CompiledTemplate.proxyViewClass.View_App_Host0.detectChangesInternal (/AppModule/App/host.ngfactory.js:29:19) <ng-transclude class="ng-scope">
```

It seems the ng1 transclusion directive tries to destroy the transcluded scope if the transcluded content is empty, but UpgradeComponent doesn't actually supply a scope in this case.

**Expected behavior**

It should work without errors.

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/iluIot4jXRbot4Rk3O9t?p=preview

**What is the motivation / use case for changing the behavior?**

Correctness, ease of upgrade.

**Please tell us about your environment:**

macOS Sierra

* **Angular version:** 2.3.0-rc.0, 1.6.0-rc.2

* **Browser:** all
 
* **Language:** all

**Comment by jonrimmer** [comment]
Shouldn't the label be upgrade/static?

**Comment by qmOnArq** [comment]
If you need workaround for now, you can use `ng-if` to remove the transclude when it's empty

**Comment by petebacondarwin** [comment]
One problem that this bug has highlighted to me is that we are currently testing ngUpgrade against 1.5.x (which doesn't expose this problem) rather than 1.6.0.

**Comment by petebacondarwin** [comment]
I think we need to do a better job of creating our bound transclusion function, so that it has a suitable transclusion scope passed through.

**Comment by petebacondarwin** [comment]
Working on a fix for this.

**Comment by petebacondarwin** [comment]
Maybe this helps: https://github.com/angular/angular/pull/16627

**Comment by gkalpak** [comment]
There are some issues with your plnkr. Here is an [updated version][1]. This still doesn't work (because of an ngUpgrade bug), but should by fixed by #16627.

[1]: https://plnkr.co/edit/fFncmfxKiKgS1IUu01H6?p=preview

**Comment by gkalpak** [comment]
Actually, you can see that simple transclusion works already: [updated plnkr][1]
What doesn't work (and will be fixed by #16627) is:
- Fallback content.
- Multi-slot transclusion.

[1]: https://plnkr.co/edit/e6LtTIvMzKxLFZ4PuruA?p=preview

**Comment by FDIM** [comment]
I know that this is an old issue, but this seems to be still happening with angular 5.2.4 and angularjs 1.6.9:
https://stackblitz.com/edit/ngupgradestatic-playground-hh5hru

**Comment by gkalpak** [comment]
@FDIM, this issue is closed as fixed. Can you please open a new issue to track the bug you are reporting?

**Comment by FDIM** [comment]
@gkalpak done
