### ISSUE TITLE
Angular 2.3 Animation Creating Cannot read property 'cancel' of undefined error

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#13293]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After upgrading to 2.3.0 from 2.2.4, I receive the following error:

```
libs.js:46362 TypeError: Cannot read property 'cancel' of undefined
    at WebAnimationsPlayer._resetDomPlayerState (http://localhost:9999/libs.js:59060:84)
    at WebAnimationsPlayer.destroy (http://localhost:9999/libs.js:59077:18)
    at http://localhost:9999/libs.js:38813:69
    at Array.forEach (native)
    at AnimationSequencePlayer.destroy (http://localhost:9999/libs.js:38813:27)
    at Object.TooltipContentComponent_visibilityChanged_factory [as visibilityChanged] (/TooltipModule/TooltipContentComponent/component.ngfactory.js:58:53)
    at Wrapper_TooltipContentComponent.ngOnDetach (/TooltipModule/TooltipContentComponent/wrapper.ngfactory.js:22:106)
    at CompiledTemplate.proxyViewClass.View_TooltipContentComponent_Host0.detachInternal (/TooltipModule/TooltipContentComponent/host.ngfactory.js:44:37)
    at CompiledTemplate.proxyViewClass.AppView.detach (http://localhost:9999/libs.js:49139:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detach (http://localhost:9999/libs.js:49495:37)
    at ApplicationRef_.detachView (http://localhost:9999/libs.js:40807:14)
    at Array.<anonymous> (http://localhost:9999/app.js:37489:24)
    at CompiledTemplate.proxyViewClass.AppView.destroy (http://localhost:9999/libs.js:49111:36)
    at CompiledTemplate.proxyViewClass.DebugAppView.destroy (http://localhost:9999/libs.js:49508:38)
    at CompiledTemplate.proxyViewClass.AppView.detachAndDestroy (http://localhost:9999/libs.js:49098:14)
```

which is a result of the following animation code:

```
  animations: [
    trigger('visibilityChanged', [
      state('active', style({ opacity: 1, 'pointer-events': 'auto' })),
      transition('void => *', [
        style({
          opacity: 0,
          'pointer-events': 'none',
          transform: 'translate3d(0, 0, 0)'
        }),
        animate('0.3s ease-out')
      ]),
      transition('* => void', [
        style({ opacity: 1 }),
        animate('0.2s ease-out')
      ])
    ])
  ]
```

when I remove the out transition:

```
      transition('* => void', [
        style({ opacity: 1 }),
        animate('0.2s ease-out')
      ])
```

it seems to work fine but loses that transition. This occurs when the tooltip is killed using `component.destroy();` function.

When debugging you can see the player is trying to kill is undefined: 

![img](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/c710526f-dffa-4738-bf65-3b0b0531bad6/2016-12-07_17-29-10.png)

**Expected behavior**

No errors.

**Minimal reproduction of the problem with instructions**

Upgrade [ng2d3](https://github.com/swimlane/ng2d3) to 2.3 and launch demo page and note error. see branch: https://github.com/swimlane/ng2d3/tree/ng-230-upgrade

**What is the motivation / use case for changing the behavior?**

NA

**Please tell us about your environment:**

Mac, NPM, Webpack, Node 7.x

* **Angular version:** 2.0.X

2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TS 2.10.0

* **Node (for AoT issues):** `node --version` =

**Comment by amcdnl** [comment]
@matsko - IS this closed now w/ your above change?
