### ISSUE TITLE
Since Angurlar 2.3.0 ng-xi18n does not work anymore: Error: Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular#13306]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Since Angurlar 2.3.0 ng-xi18n does not work anymore:

```
Error: Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 7:12 in the original .ts file), resolving symbol Ng2BootstrapConfig in /work/client/node_modules/ng2-bootstrap/components/ng2-bootstrap-config.d.ts, resolving symbol TypeaheadContainerComponent in /work/client/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts, resolving symbol TypeaheadContainerComponent in /work/client/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts
    at positionalError (/work/client/node_modules/@angular/compiler/bundles/compiler.umd.js:25370:37)
    at simplifyInContext (/work/client/node_modules/@angular/compiler/bundles/compiler.umd.js:25177:29)
    at StaticReflector.simplify (/work/client/node_modules/@angular/compiler/bundles/compiler.umd.js:25191:15)
    at StaticReflector.annotations (/work/client/node_modules/@angular/compiler/bundles/compiler.umd.js:24533:62)
    at NgModuleResolver.resolve (/work/client/node_modules/@angular/compiler/bundles/compiler.umd.js:17207:84)
    at CompileMetadataResolver.getNgModuleMetadata (/work/client/node_modules/@angular/compiler/bundles/compiler.umd.js:17681:62)
    at addNgModule (/work/client/node_modules/@angular/compiler/bundles/compiler.umd.js:24285:60)
    at /work/client/node_modules/@angular/compiler/bundles/compiler.umd.js:24296:16
    at Array.forEach (native)
    at _createNgModules (/work/client/node_modules/@angular/compiler/bundles/compiler.umd.js:24295:28)
Extraction failed
```

**Expected behavior**
`ng-xi18n` works with Angular 2.2.4.

**Minimal reproduction of the problem with instructions**
`./node_modules/.bin/ng-xi18n`

**What is the motivation / use case for changing the behavior?**
I want to use `ng-xi18n` with the latest Angular version.

**Please tell us about your environment:**
Linux: Xubuntu 16.04

* **Angular version:** 2.3.0
 
* **Language:** TypeScript 2.0.10

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by vicb** [comment]
Actually the solution is in the error message: "Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler "

**Comment by Martin-Wegner** [comment]
@vicb but it works with Angular 2.2.4! So what changed from 2.2.4 to 2.3.0?

**Comment by Martin-Wegner** [comment]
OK with ng2-bootstrap 1.1.6-7 it works :)
