### ISSUE TITLE
Since TypeScript 2.1.4 ng-xi18n does not work anymore: TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular#13305]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Since TypeScript 2.1.4 `ng-xi18n` does not work anymore:

```
TypeError: Cannot read property 'text' of undefined
    at NodeObject.getText (/work/client/node_modules/typescript/lib/typescript.js:78080:30)
    at Evaluator.evaluateNode (/work/client/node_modules/@angular/tsc-wrapped/src/evaluator.js:495:66)
    at _loop_1 (/work/client/node_modules/@angular/tsc-wrapped/src/collector.js:306:54)
    at /work/client/node_modules/@angular/tsc-wrapped/src/collector.js:365:25
    at visitEachNode (/work/client/node_modules/typescript/lib/typescript.js:13907:30)
    at Object.forEachChild (/work/client/node_modules/typescript/lib/typescript.js:14078:24)
    at MetadataCollector.getMetadata (/work/client/node_modules/@angular/tsc-wrapped/src/collector.js:204:12)
    at MetadataWriterHost.writeMetadata (/work/client/node_modules/@angular/tsc-wrapped/src/compiler_host.js:111:51)
    at MetadataWriterHost.writeFile (/work/client/node_modules/@angular/tsc-wrapped/src/compiler_host.js:103:19)
    at Object.writeFile (/work/client/node_modules/typescript/lib/typescript.js:62522:132)
Extraction failed
```

**Expected behavior**
`ng-xi18n` works with TypeScript 2.0.10.

**Minimal reproduction of the problem with instructions**
`./node_modules/.bin/ng-xi18n`

**What is the motivation / use case for changing the behavior?**
I want to use `ng-xi18n` with the latest TypeScript version.

**Please tell us about your environment:**
Linux: Xubuntu 16.04

* **Angular version:** 2.2.4 and 2.3.0
 
* **Language:** TypeScript 2.1.4

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by seanlandsman** [comment]
I think this might be a typescript issue, not an angular one - try rolling back to 2.0.3 and it should work

**Comment by Martin-Wegner** [comment]
As I wrote with 2.0.10 it works. I will also create an Issue for TypeScript...

**Comment by DzmitryShylovich** [comment]
I think angular is not compatible with ts 2.1 yet https://github.com/angular/angular/pull/13294

**Comment by Delagen** [comment]
AOT also not work with the last 2.3.0 build
NGC+Webpack build works fine on 2.2.4
but on 2.3.0 fall in No provider for type

**Comment by vicb** [comment]
closing until we add support for TS 2.1
