### ISSUE TITLE
Cannot create property '__anonymousType' on symbol

### ISSUE THREAD

**Issue by JimmyBoh** [angular/angular#13314]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Within a TS file I create a very simple `symbol` and an injectable class. When this symbol is used as an injection reference it breaks:

```ts
  const MyGlobalService = Symbol('MyGlobalService');

  // ...
  constructor(
    @Inject(MyGlobalService) private _service: any
  ){}
  //...
```

Error Thrown:
```
Unhandled Promise rejection: Cannot create property '__anonymousType' on symbol 'Symbol(MyGlobalService)' ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot create property '__anonymousType' on symbol 'Symbol(MyGlobalService)'(…) TypeError: Cannot create property '__anonymousType' on symbol 'Symbol(MyGlobalService)'
    at identifierName (https://localhost:8080/lib/@angular/compiler/bundles/compiler.umd.min.js:6:3240)
    at tokenName (https://localhost:8080/lib/@angular/compiler/bundles/compiler.umd.min.js:6:3553)
    at _InjectorBuilder.addProvider (https://localhost:8080/lib/@angular/compiler/bundles/compiler.umd.min.js:34:21529)
    at eval (https://localhost:8080/lib/@angular/compiler/bundles/compiler.umd.min.js:34:19932)
    at Array.forEach (native)
    at NgModuleCompiler.compile (https://localhost:8080/lib/@angular/compiler/bundles/compiler.umd.min.js:34:19890)
    at JitCompiler._compileModule (https://localhost:8080/lib/@angular/compiler/bundles/compiler.umd.min.js:45:25933)
    at createResult (https://localhost:8080/lib/@angular/compiler/bundles/compiler.umd.min.js:45:24480)
    at ZoneDelegate.invoke (https://localhost:8080/lib/zone.js/dist/zone.js:232:26)
    at Zone.run (https://localhost:8080/lib/zone.js/dist/zone.js:114:43)
```

I'm pretty sure the [`identifierName method in compile_metadata.ts`](https://github.com/angular/angular/blob/5614c4ff0fbfc7e856849d1f539934f46b4bca4b/modules/%40angular/compiler/src/compile_metadata.ts#L85-L105) does not handle symbols.

**Expected behavior**
Previously this was working in 2.1. I did try changing the `Symbol` to an `OpaqueToken`, which did fix the issue. Regardless, this is a breaking change that should be noted.

**Minimal reproduction of the problem with instructions**

*MINIMAL DEMO:* http://plnkr.co/edit/6J3klFpWH4Fn1hHna8zo?p=preview

*STEPS TO REPRODUCE:*
 1. Create a `Symbol`.
 1. Create a factory provider using the `Symbol` that returns any object.
 1. Create a component with a constructor that `@Inject`'s using the `Symbol`.
 1. Load the app in Chrome.

**What is the motivation / use case for changing the behavior?**
I am using a `Symbol` to inject a non-angular object. I understand now that an `OpaqueToken` is the recommended approach, but this has broken since an update.

**Please tell us about your environment:**

Windows 8.1, VS Code, NPM, dotnet core (Kestrel)

* **Angular version:** 2.3.0

* **Browser:** [ Chrome 54 ] (works fine in IE 11)

 
* **Language:** [ TypeScript 2.1 ]

* **Node (for AoT issues):** `node --version` =   v6.3.0

**Comment by DzmitryShylovich** [comment]
Why do u think angular supports injection by `Symbol`?

**Comment by vicb** [comment]
It is indeed a bug (you should be able to use anything as a DI token).

The fix is probably to use a `WeakMap` instead of adding hidden properties.

**Comment by Yogu** [comment]
For anyone else reading this in the future - this has been reverted in #15319, so Symbols again can't be used. Note that you can use an `InjectionToken` instead (which even accepts a type parameter).
