### ISSUE TITLE
ngCompiler.ReflectorHost is not a constructor Exception launching app

### ISSUE THREAD

**Issue by jtsom** [angular/angular#13310]
**I'm submitting a ...**  (check one with "x")
```
[ *] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Create new app with ng new newapp. Try to start app with ng serve
Exception when trying to start

This is with a brand new project, with the Angular dependencies updated:

```
➜  testing git:(master) ✗ ng serve
ngCompiler.ReflectorHost is not a constructor
TypeError: ngCompiler.ReflectorHost is not a constructor
    at AotPlugin._setupOptions (/Users/John/Dev/Javascript/Angular/testing/node_modules/@ngtools/webpack/src/plugin.js:136:31)
    at new AotPlugin (/Users/John/Dev/Javascript/Angular/testing/node_modules/@ngtools/webpack/src/plugin.js:37:14)
    at Object.exports.getWebpackNonAotConfigPartial (/Users/John/Dev/Javascript/Angular/testing/node_modules/angular-cli/models/webpack-bu
ild-typescript.js:20:13)
    at new NgCliWebpackConfig (/Users/John/Dev/Javascript/Angular/testing/node_modules/angular-cli/models/webpack-config.js:23:42)
    at Class.run (/Users/John/Dev/Javascript/Angular/testing/node_modules/angular-cli/tasks/serve-webpack.js:20:22)
    at /Users/John/Dev/Javascript/Angular/testing/node_modules/angular-cli/commands/serve.js:102:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
➜  testing git:(master) ✗
```

FWIW, My package.json dependencies are:

```"dependencies": {
    "@angular/common": "2.3.0",
    "@angular/compiler": "2.3.0",
    "@angular/core": "2.3.0",
    "@angular/forms": "2.3.0",
    "@angular/http": "2.3.0",
    "@angular/platform-browser": "2.3.0",
    "@angular/platform-browser-dynamic": "2.3.0",
    "@angular/router": "3.3.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-rc.4",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.3.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.22-1",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.7.0",
    "tslint": "^4.0.2",
    "typescript": "~2.0.10",
    "webdriver-manager": "10.2.5"
  }
```

**Expected behavior**
App launches

**Minimal reproduction of the problem with instructions**
ng new newapp
(update package. json to latest angular - 2.3.0)
ng serve

**Please tell us about your environment:**
OS X 10.12.1

* **Angular version:** 2.0.X
2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
N/A - 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.10

* **Node (for AoT issues):** `node --version` =   
v7.2.1

**Comment by wulfsberg** [comment]
I am getting a suspiciously similar
````
TypeError: Cannot read property 'parse' of undefined
    at ReflectorHost.normalizeAssetUrl ...
````
when trying to AoT compile a project with Angular-CLI after upgrading to 2.3.0, so either Angular-CLI was (ab)using some internal functionality which has changed, or something broke in the backwards compatibility between 2.2.4 and 2.3.0

**Comment by vicb** [comment]
@chuckjaz @hansl do you know what is going on here ?

**Comment by wulfsberg** [comment]
It seems the Angular-CLI team is on it: angular/angular-cli/issues/3467

**Comment by tbosch** [comment]
This is solved now, see the angular-cli issue which was closed.

**Comment by tbosch** [comment]
I.e. Angular-Cli beta 24 works with Angular 2.3.1 and above (2.3.0 won't work...)
