### ISSUE TITLE
Unit test for lazy module

### ISSUE THREAD

**Issue by suplch** [angular/angular#13418]
**Current behavior**
lazy module path can run successfully in real browser by http://localhost:4200/lazy
I can see browser download http://localhost:4200/0.chunk.js asynchronously.
but it throw error in Unit test with 'Cannot find module 'app/t4/lazy.module'
**Expected behavior**
Be able to test asynchronously lazy module path in Unit test environment as normal synchronously path.

**Minimal reproduction of the problem with instructions**
Make a Lazy Module, run it in browser successfully, and then write a Unit test to test this lazy path, it don't work.
```typescript
....
describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        BrowserModule,
        RouterModule.forRoot([
          { path: 'search',       component: SearchComponent },
          { path: 'lazy',         loadChildren: 'app/t4/lazy.module#LazyModule'}
        ])
      ],
...
  // this test run with error 'Cannot find module 'app/t4/lazy.module'
  it('test lazy path', inject([Router], fakeAsync((router: Router) => {
    const fixture = createRoot(router, AppComponent);
    let app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
    // this line throw error with 'Cannot find module 'app/t4/lazy.module'.'
    router.navigateByUrl('/lazy'); 
    // advance(fixture);
    // expect(location.pathname).toBe('/lazy');
    // const compiled = fixture.debugElement.nativeElement;
    // expect(compiled.querySelector('div').textContent).toContain('this is lazy component');
  })));
...
  // this test can run successfully.
  it('test search', inject([Router], fakeAsync((router: Router) => {
    const fixture = createRoot(router, AppComponent);
    let app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
    router.navigateByUrl('/search');
    advance(fixture);
    expect(location.pathname).toBe('/search');
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('div').textContent).toContain('this is search component');
  })));
....
export function createRoot(router: Router, componentType: any): ComponentFixture<any> {
  const f = TestBed.createComponent(componentType);
  advance(f);
  router.initialNavigation();
  return f;
}
export function advance<T>(fixture: ComponentFixture<T>): void {
  tick();
  fixture.detectChanges();
}
```

**What is the motivation / use case for changing the behavior?**
I hope test lazy module path easily as normal sync path.

** environment:**
OS:  macOS Sierra
IDE: WebStorm 2016 2.3
angular-cli tools

* **Angular version:** 2.1.0

* **Browser:** [all | Chrome 54.0.2840.98 (64-bit)  ]
 
* **Language:** [TypeScript 2.0.3 ]

* **Node (for AoT issues):** `node --version` =   v7.0.0

**Comment by Toxicable** [comment]
Can you please make a minimal reproduction aswell as fill out the other fields required by the issue template

**Comment by suplch** [comment]
this is whole code
```typescript
import {TestBed, async, fakeAsync, inject, ComponentFixture, tick} from '@angular/core/testing';
import { AppComponent } from './app.component';
import { Calculator } from "./t1/calculator";
import {RouterModule, Router} from "@angular/router";
import { SearchComponent} from "./t3/music-test-helpers";
import {BrowserModule} from "@angular/platform-browser";
import {LocationStrategy, APP_BASE_HREF, PathLocationStrategy} from "@angular/common";
import {BaseRequestOptions, Http, ConnectionBackend, ResponseOptions, Response} from "@angular/http";
import {MockBackend} from "@angular/http/testing";
import {SpotifyService} from "./t2/spotify.service";

export function advance<T>(fixture: ComponentFixture<T>): void {
  tick();
  fixture.detectChanges();
}

export function createRoot(router: Router, componentType: any): ComponentFixture<any> {
  const f = TestBed.createComponent(componentType);
  advance(f);
  router.initialNavigation();
  return f;
}

describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        BrowserModule,
        RouterModule.forRoot([
          { path: 'search',       component: SearchComponent },
          { path: 'lazy',         loadChildren: 'app/t4/lazy.module#LazyModule'}
        ])
      ],
      declarations: [
        AppComponent,
        SearchComponent,
      ],
      providers: [
        { provide: LocationStrategy, useClass: PathLocationStrategy},
        { provide: APP_BASE_HREF, useValue: '/'},
        BaseRequestOptions,
        MockBackend,
        SpotifyService,
        {
          provide: Http,
          useFactory: (backend: ConnectionBackend, defaultOptions: BaseRequestOptions) => {
            return new Http(backend, defaultOptions);
          },
          deps: [
            MockBackend,
            BaseRequestOptions
          ]
        }
      ]
    });
  });

  it('test search', inject([Router], fakeAsync((router: Router) => {
    const fixture = createRoot(router, AppComponent);
    let app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
    router.navigateByUrl('/search');
    advance(fixture);
    expect(location.pathname).toBe('/search');
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('div').textContent).toContain('this is search component');
  })));

  it('test lazy path', inject([Router], fakeAsync((router: Router) => {
    const fixture = createRoot(router, AppComponent);
    let app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
    router.navigateByUrl('/lazy');
    // advance(fixture);
    // expect(location.pathname).toBe('/lazy');
    // const compiled = fixture.debugElement.nativeElement;
    // expect(compiled.querySelector('div').textContent).toContain('this is lazy component');
  })));
});

```

**Comment by suplch** [comment]
these are error output
```
Chrome 54.0.2840 (Mac OS X 10.12.1) AppComponent test lazy path FAILED
        Error: Uncaught (in promise): Error: Cannot find module 'app/t4/lazy.module'.
        Error: Cannot find module 'app/t4/lazy.module'.
            at webpackEmptyContext (webpack:/Users/chunhua/WebstormProjects/test-app/src%20async:2:0 <- src/test.ts:59572:8)
            at SystemJsNgModuleLoader.loadAndCompile (webpack:///Users/chunhua/WebstormProjects/test-app/~/@angular/core/src/linker/system_js_ng_module_factory_loader.js:69:0 <- src/test.ts:72153:40)
            at SystemJsNgModuleLoader.load (webpack:///Users/chunhua/WebstormProjects/test-app/~/@angular/core/src/linker/system_js_ng_module_factory_loader.js:57:0 <- src/test.ts:72141:60)
            at RouterConfigLoader.loadModuleFactory (webpack:///Users/chunhua/WebstormProjects/test-app/~/@angular/router/src/router_config_loader.js:71:0 <- src/test.ts:22264:128)
            at RouterConfigLoader.load (webpack:///Users/chunhua/WebstormProjects/test-app/~/@angular/router/src/router_config_loader.js:58:0 <- src/test.ts:22251:81)
            at MergeMapSubscriber.project (webpack:///Users/chunhua/WebstormProjects/test-app/~/@angular/router/src/apply_redirects.js:379:0 <- src/test.ts:76197:111)
            at MergeMapSubscriber._tryNext (webpack:///Users/chunhua/WebstormProjects/test-app/~/rxjs/operator/mergeMap.js:110:0 <- src/test.ts:22550:27)
            at MergeMapSubscriber._next (webpack:///Users/chunhua/WebstormProjects/test-app/~/rxjs/operator/mergeMap.js:100:0 <- src/test.ts:22540:18)
            at MergeMapSubscriber.Subscriber.next (webpack:///Users/chunhua/WebstormProjects/test-app/~/rxjs/Subscriber.js:89:0 <- src/test.ts:5895:18)
            at ScalarObservable._subscribe (webpack:///Users/chunhua/WebstormProjects/test-app/~/rxjs/observable/ScalarObservable.js:49:0 <- src/test.ts:58975:24)
            at resolvePromise (webpack:///Users/chunhua/WebstormProjects/test-app/~/zone.js/dist/zone.js:468:0 <- src/test.ts:83107:31)
            at resolvePromise (webpack:///Users/chunhua/WebstormProjects/test-app/~/zone.js/dist/zone.js:453:0 <- src/test.ts:83092:17)
            at webpack:///Users/chunhua/WebstormProjects/test-app/~/zone.js/dist/zone.js:502:0 <- src/test.ts:83141:17
            at ZoneDelegate.invokeTask (webpack:///Users/chunhua/WebstormProjects/test-app/~/zone.js/dist/zone.js:265:0 <- src/test.ts:82904:35)
            at ProxyZoneSpec.onInvokeTask (webpack:///Users/chunhua/WebstormProjects/test-app/~/zone.js/dist/proxy.js:103:0 <- src/test.ts:60471:39)
            at ZoneDelegate.invokeTask (webpack:///Users/chunhua/WebstormProjects/test-app/~/zone.js/dist/zone.js:264:0 <- src/test.ts:82903:40)
            at Zone.runTask (webpack:///Users/chunhua/WebstormProjects/test-app/~/zone.js/dist/zone.js:154:0 <- src/test.ts:82793:47)
            at ZoneTask.invoke (webpack:///Users/chunhua/WebstormProjects/test-app/~/zone.js/dist/zone.js:335:0 <- src/test.ts:82974:33)
            at FakeAsyncTestZoneSpec.flushMicrotasks (webpack:///Users/chunhua/WebstormProjects/test-app/~/zone.js/dist/fake-async-test.js:204:0 <- src/test.ts:60001:17)
            at flushMicrotasks (webpack:///Users/chunhua/WebstormProjects/test-app/~/@angular/core/bundles/core-testing.umd.js:401:0 <- src/test.ts:11513:33)
Chrome 54.0.2840 (Mac OS X 10.12.1): Executed 9 of 9 (1 FAILED) (0.973 secs / 0.791 secs)

```

**Comment by Toxicable** [comment]
I think you misunderstand, when you click on New Issue you are provided with a template, like the one below, you are expected to fill it out. I have included it below incase you cant find it in the New Issue box

```
<!--
IF YOU DON'T FILL OUT THE FOLLOWING INFORMATION WE MIGHT CLOSE YOUR ISSUE WITHOUT INVESTIGATING
-->

**I'm submitting a ...**  (check one with "x")

[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question


**Current behavior**
<!-- Describe how the bug manifests. -->

**Expected behavior**
<!-- Describe what the behavior would be without the bug. -->

**Minimal reproduction of the problem with instructions**
<!--
If the current behavior is a bug or you can illustrate your feature request better with an example, 
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
-->

**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->

**Please tell us about your environment:**
<!-- Operating system, IDE, package manager, HTTP server, ... -->

* **Angular version:** 2.0.X
<!-- Check whether this is still an issue in the most recent Angular version -->

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
<!-- All browsers where this could be reproduced -->
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   
```

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
