### ISSUE TITLE
downgradeNg2Component doesn't work with multiple element selectors(@angular/materail sidenav)

### ISSUE THREAD

**Issue by epelc** [angular/angular#13427]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

You get an error when downgrading an ng2 component that selects multiple element names.

**Expected behavior**

The following should work.
```
// Notice we add a `t` after `md` since angular-material and @angular/material do not play well together.
    angular.module('ng2').directive('mdtSidenavLayout', <angular.IDirectiveFactory>upgradeAdapter.downgradeNg2Component(MdSidenavLayout))
    .directive('mdtSidenav', <angular.IDirectiveFactory>upgradeAdapter.downgradeNg2Component(MdSidenav))
```

You receive the following error because @angular/material now uses multiple element selectors. I don't see why this can't work when selecting multiple element names.
```
app.js:717Uncaught Error: Only selectors matching element names are supported, got: md-sidenav-layout, mat-sidenav-layout
    at d (https://app.com/app/vendor.js:93815:10312)
    at getComponentInfo (https://app.com/app/app.js:717:18)
    at UpgradeAdapter.downgradeNg2Component (https://app.com/app/app.js:1314:40)
    at Object.<anonymous> (https://app.com/app/app.js:132:635)
    at __webpack_require__ (https://app.com/app/vendor.js:51:30)
    at Object.<anonymous> (https://app.com/app/app.js:7:13)
    at __webpack_require__ (https://app.com/app/vendor.js:51:30)
    at webpackJsonpCallback (https://app.com/app/vendor.js:22:20)
    at https://app.com/app/app.js:1:1d @ vendor.js:93815getComponentInfo @ app.js:717UpgradeAdapter.downgradeNg2Component @ app.js:1314(anonymous function) @ app.js:132__webpack_require__ @ vendor.js:51(anonymous function) @ app.js:7__webpack_require__ @ vendor.js:51webpackJsonpCallback @ vendor.js:22(anonymous function) @ app.js:1
```
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

Using @angular/material(2) sidenav in mixed ng1/ng2 app while in the process of upgrading to ng2.

In beta 11 @angular/material changed their selector for the sidenav from 

`selector: 'md-sidenav-layout'`

to 

`selector: 'md-sidenav-layout, mat-sidenav-layout`

**Please tell us about your environment:**

macOS 10.12.1, npm

* **Angular version:** 2.0.X

2.3.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome latest macOS 10.12.1
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.1 => ES5
* **Node (for AoT issues):** `node --version` =   
v6.9.2

**Comment by petebacondarwin** [comment]
Is this now fixed? Perhaps by ttps://github.com/angular/angular/pull/11808 ?

**Comment by petebacondarwin** [comment]
It is definitely working in `upgrade/static`.
