### ISSUE TITLE
ngc fails to compile with TypeScript 2.1.4

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#13450]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If I run `ngc` with TS `2.1.4` installed, I get the following error:
```bash
TypeError: Cannot read property 'text' of undefined
    at NodeObject.getText (/Users/rolandjitsu/Projects/infarm/core/node_modules/typescript/lib/typescript.js:78080:30)
    at Evaluator.evaluateNode (/Users/rolandjitsu/Projects/infarm/core/node_modules/@angular/tsc-wrapped/src/evaluator.js:495:66)
    at _loop_1 (/Users/rolandjitsu/Projects/infarm/core/node_modules/@angular/tsc-wrapped/src/collector.js:306:54)
    at /Users/rolandjitsu/Projects/infarm/core/node_modules/@angular/tsc-wrapped/src/collector.js:365:25
    at visitEachNode (/Users/rolandjitsu/Projects/infarm/core/node_modules/typescript/lib/typescript.js:13907:30)
    at Object.forEachChild (/Users/rolandjitsu/Projects/infarm/core/node_modules/typescript/lib/typescript.js:14078:24)
    at MetadataCollector.getMetadata (/Users/rolandjitsu/Projects/infarm/core/node_modules/@angular/tsc-wrapped/src/collector.js:204:12)
    at MetadataWriterHost.writeMetadata (/Users/rolandjitsu/Projects/infarm/core/node_modules/@angular/tsc-wrapped/src/compiler_host.js:111:51)
    at MetadataWriterHost.writeFile (/Users/rolandjitsu/Projects/infarm/core/node_modules/@angular/tsc-wrapped/src/compiler_host.js:103:19)
    at Object.writeFile (/Users/rolandjitsu/Projects/infarm/core/node_modules/typescript/lib/typescript.js:62522:132)
Compilation failed
```

**Expected behavior**

It should compile and not throw an error.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** TypeScript 2.1

* **Node (for AoT issues):** `node --version` = 6.7.0

**Comment by DzmitryShylovich** [comment]
See https://github.com/angular/angular/pull/13294

**Comment by rolandjitsu** [comment]
Ooops. Thanks @DzmitryShylovich
