### ISSUE TITLE
Reference to a non-exported class _NoOpAnimationDriver

### ISSUE THREAD

**Issue by hansl** [angular/angular#13479]
@IgorMinar @vicb **This should block the release today.**

The metadata built in master (see [here](https://github.com/angular/platform-browser-builds/blob/2.0.0-a0a0504/src/dom/animation_driver.metadata.json)) right now display an error detected when building AnimationDriver.

The _NoOpAnimationDriver should be exported in the file, even if it's not exported in the barrel.

Also, a manual checkup on [these errors](https://github.com/angular/platform-browser-builds/search?utf8=%E2%9C%93&q=__symbolic%22%3A%22error%22%2C%22message) should be performed to make sure our metadata is clean.

**Comment by xavierbriand** [comment]
Might be related, I get this AoT compilation error since I updated my project to `^v2.3`:
```
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AnimationDriver in node_modules/@angular/platform-browser/src/dom/animation_driver.d.ts, resolving symbol BrowserTestingModule in node_modules/@angular/platform-browser/testing/browser.d.ts, resolving symbol BrowserTestingModule in node_modules/@angular/platform-browser/testing/browser.d.ts
    at simplifyInContext (node_modules/@angular/compiler/bundles/compiler.umd.js:25247:25)
    at StaticReflector.simplify (node_modules/@angular/compiler/bundles/compiler.umd.js:25259:15)
    at StaticReflector.annotations (node_modules/@angular/compiler/bundles/compiler.umd.js:24598:62)
    at NgModuleResolver.resolve (node_modules/@angular/compiler/bundles/compiler.umd.js:17265:84)
    at CompileMetadataResolver.getNgModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:17739:62)
    at CompileMetadataResolver.getNgModuleSummary (node_modules/@angular/compiler/bundles/compiler.umd.js:17695:54)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:17785:70
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:17780:51)
    at addNgModule (node_modules/@angular/compiler/bundles/compiler.umd.js:24349:60)
Compilation failed
```

on `@angular#2.3.1` with node `v5.2.0`

**Comment by matsko** [comment]
@chuckjaz can you please have a look

**Comment by hansl** [comment]
After discussion with Chuck and Tobias it seems like this error is an inconvenience, although we should still fix it WRT `AnimationDriver` (basically exporting `_NoOpAnimationDriver`). `ngc` is doing the right thing here; a static member with a value that's not exported would create an invalid factory.

Users right now encountering this either use a NOOP AnimationDriver themselves (they should stop doing that) or try to `ngc` on a TestBrowser (they should stop doing that). Normally this is a symptom for `tsconfig.json` including too many files or not excluding test code.

**Comment by xavierbriand** [comment]
@hansl, probably the later in my case. Thanks for the quick feedback.

**Comment by matsko** [comment]
I'm closing this issue for now since https://github.com/angular/angular/commit/842f52e841b61ab1389a316b3d0d0f02f34ec5e3 fixed it. If there is a bizarre failure that shows up then reopen and let us know :)
