### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined in angular 2.2.3

### ISSUE THREAD

**Issue by colombia9503** [angular/angular#13595]
NODE VERSION 4.6.0
ANGULAR 2.2.3
ROUTER  3.2.3
OS: Ubuntu 14.04 LTS
the project was instanced with angular-cli@1.0.0-beta.22-1
this is my app.module.ts
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { RouterModule } from '@angular/router';

import { AppComponent } from './app.component';

//Materialize Module
import { MaterializeModule } from 'angular2-materialize';

//App Modules
import { LoginModule } from './login/index';
import { HomeModule } from './home/index';
import { SharedModule } from './shared/index';

//Routes
import { routedModules } from './index';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    /**
     * Materialize Module
     */
    MaterializeModule,
    /**
     * Router Module
     */
    RouterModule.forRoot(routedModules),
    /**
     * App Modules
     */
    LoginModule,
    HomeModule,
    /**
     * Shared Module
     */
    SharedModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { 
}
```

My login.module.ts
```typescript
import { NgModule } from '@angular/core';
import { MaterializeModule } from 'angular2-materialize';
import { CommonModule } from '@angular/common';


import { LoginComponent } from './login.component';

@NgModule({
  imports: [MaterializeModule, CommonModule],
  exports: [],
  declarations: [LoginComponent],
  bootstrap: [LoginComponent],
  providers: [],
})
export class LoginModule { }
```

my app.routes.ts
```typescript
import { Routes } from '@angular/router';

//Routes
import { LoginRoute } from './login/index';

export const routedModules: Routes = [
    ...LoginRoute
];
```

and my login.routes.ts
```typescript
import { Route } from '@angular/router';

import { LoginComponent } from './login.component';

export const LoginRoute: Route[] = [
  { path: 'login', component: LoginComponent },
];
```
why doesn't work the routing?
i got this, i don't know what's wrong in my code, this works on the angular v2.1.0 with router 3.1.0
[localhost-1482263759959.txt](https://github.com/angular/angular/files/664618/localhost-1482263759959.txt)
```console
zone.js:388Unhandled Promise rejection: Cannot read property 'length' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'length' of undefined
    at flatten (http://localhost:4200/vendor.bundle.js:5221:33)
    at setupRouter (http://localhost:4200/vendor.bundle.js:44828:233)
    at NgModuleInjector.get (/AppModule/module.ngfactory.js:190:57)
    at NgModuleInjector.AppModuleInjector.createInternal (/AppModule/module.ngfactory.js:229:60)
    at NgModuleInjector.create (http://localhost:4200/vendor.bundle.js:40610:76)
    at NgModuleFactory.create (http://localhost:4200/vendor.bundle.js:40595:18)
    at http://localhost:4200/vendor.bundle.js:26264:43
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:69721:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:28580:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:69720:32) TypeError: Cannot read property 'length' of undefined
    at flatten (http://localhost:4200/vendor.bundle.js:5221:33)
    at setupRouter (http://localhost:4200/vendor.bundle.js:44828:233)
    at NgModuleInjector.get (/AppModule/module.ngfactory.js:190:57)
    at NgModuleInjector.AppModuleInjector.createInternal (/AppModule/module.ngfactory.js:229:60)
    at NgModuleInjector.create (http://localhost:4200/vendor.bundle.js:40610:76)
    at NgModuleFactory.create (http://localhost:4200/vendor.bundle.js:40595:18)
    at http://localhost:4200/vendor.bundle.js:26264:43
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:69721:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:28580:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:69720:32)consoleError @ zone.js:388_loop_1 @ zone.js:417drainMicroTaskQueue @ zone.js:421
zone.js:390Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at flatten (http://localhost:4200/vendor.bundle.js:5221:33)
    at setupRouter (http://localhost:4200/vendor.bundle.js:44828:233)
    at NgModuleInjector.get (/AppModule/module.ngfactory.js:190:57)
    at NgModuleInjector.AppModuleInjector.createInternal (/AppModule/module.ngfactory.js:229:60)
    at NgModuleInjector.create (http://localhost:4200/vendor.bundle.js:40610:76)
    at NgModuleFactory.create (http://localhost:4200/vendor.bundle.js:40595:18)
    at http://localhost:4200/vendor.bundle.js:26264:43
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:69721:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:28580:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:69720:32)
    at flatten (http://localhost:4200/vendor.bundle.js:5221:33)
    at setupRouter (http://localhost:4200/vendor.bundle.js:44828:233)
    at NgModuleInjector.get (/AppModule/module.ngfactory.js:190:57)
    at NgModuleInjector.AppModuleInjector.createInternal (/AppModule/module.ngfactory.js:229:60)
    at NgModuleInjector.create (http://localhost:4200/vendor.bundle.js:40610:76)
    at NgModuleFactory.create (http://localhost:4200/vendor.bundle.js:40595:18)
    at http://localhost:4200/vendor.bundle.js:26264:43
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:69721:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:28580:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:69720:32)
    at resolvePromise (http://localhost:4200/vendor.bundle.js:69957:31)
    at http://localhost:4200/vendor.bundle.js:69994:17
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:69754:35)
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:69643:47)
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:69890:35)consoleError @ zone.js:390_loop_1 @ zone.js:417drainMicroTaskQueue @ zone.js:421
```

**Comment by DzmitryShylovich** [comment]
Pls add:
1. small repro in plunkr
2. steps to reproduce
3. expected behavior.
And format your code.
