### ISSUE TITLE
Better Error Message Needed

### ISSUE THREAD

**Issue by mwarton** [angular/angular#13756]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I had an incorrect templateUrl in my component (started with / instead of ./).  It would be nice if there was a better error message for this case, rather than for people needing to find it by trial and error.

Error message received is:
```
TypeError: Cannot read property 'length' of null
    at new _Tokenizer (/usr/local/google/_blaze_mwarton/7d2ae3606dd43aefe08f968f630c67e2/execroot/google3/blaze-out/host/bin/javascript/angular2/tools/ngc/ngc.runfiles/google3/third_party/javascript/angular2/rc/modules/@angular/compiler/src/ml_parser/lexer.es5.js:108:37)
    at Object.tokenize (/usr/local/google/_blaze_mwarton/7d2ae3606dd43aefe08f968f630c67e2/execroot/google3/blaze-out/host/bin/javascript/angular2/tools/ngc/ngc.runfiles/google3/third_party/javascript/angular2/rc/modules/@angular/compiler/src/ml_parser/lexer.es5.js:65:12)
    at HtmlParser.Parser.parse (/usr/local/google/_blaze_mwarton/7d2ae3606dd43aefe08f968f630c67e2/execroot/google3/blaze-out/host/bin/javascript/angular2/tools/ngc/ngc.runfiles/google3/third_party/javascript/angular2/rc/modules/@angular/compiler/src/ml_parser/parser.es5.js:42:35)
    at HtmlParser.parse (/usr/local/google/_blaze_mwarton/7d2ae3606dd43aefe08f968f630c67e2/execroot/google3/blaze-out/host/bin/javascript/angular2/tools/ngc/ngc.runfiles/google3/third_party/javascript/angular2/rc/modules/@angular/compiler/src/ml_parser/html_parser.es5.js:24:39)
    at I18NHtmlParser.parse (/usr/local/google/_blaze_mwarton/7d2ae3606dd43aefe08f968f630c67e2/execroot/google3/blaze-out/host/bin/javascript/angular2/tools/ngc/ngc.runfiles/google3/third_party/javascript/angular2/rc/modules/@angular/compiler/src/i18n/i18n_html_parser.es5.js:28:44)
    at DirectiveNormalizer.normalizeLoadedTemplate (/usr/local/google/_blaze_mwarton/7d2ae3606dd43aefe08f968f630c67e2/execroot/google3/blaze-out/host/bin/javascript/angular2/tools/ngc/ngc.runfiles/google3/third_party/javascript/angular2/rc/modules/@angular/compiler/src/directive_normalizer.es5.js:81:51)
    at /usr/local/google/_blaze_mwarton/7d2ae3606dd43aefe08f968f630c67e2/execroot/google3/blaze-out/host/bin/javascript/angular2/tools/ngc/ngc.runfiles/google3/third_party/javascript/angular2/rc/modules/@angular/compiler/src/directive_normalizer.es5.js:77:51
    at process._tickCallback (internal/process/next_tick.js:103:7)
Codegen failed
```

**Expected behavior**
I would expect an error message similar to `Cannot find template ${PATH}`

**Minimal reproduction of the problem with instructions**
```
@Component({
  ...
  templateUrl: '/component.html',
  ...
})
```

**What is the motivation / use case for changing the behavior?**
Better developer experience for a common error.

**Please tell us about your environment:**
Linux, Visual Studio Code

* **Angular version:** 6b02b80a034491c7f6ebc4eba9ed57140f629856

* **Browser:** Compile time problem.
 
* **Language:** TypeScript 2.0

* **Node (for AoT issues):** `node --version` =   6.9.1

**Comment by vicb** [comment]
What is your env ? angular version, build tools, ...

**Comment by mwarton** [comment]
Angular version is in the description, build tool is blaze.

**Comment by DzmitryShylovich** [comment]
> Angular version is in the description

there's only a commit reference in description :)

**Comment by mwarton** [comment]
I am using the Angular2 version in the internal Google code base, from what
I can see that is the latest version that was synced from the open source
repository and what is being used.  I'm not sure exactly which released
version this corresponds to.

On Tue, Jan 3, 2017 at 11:26 AM, Dzmitry Shylovich <notifications@github.com

**Comment by DzmitryShylovich** [comment]
Can't reproduce in plunkr https://plnkr.co/edit/mFoZ0s6y6SlN59Z2soPG?p=preview
> Unhandled Promise rejection: Failed to load /component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load /component.html

**Comment by tbosch** [comment]
This is with AoT

**Comment by kara** [comment]
FWIW, I also ran into this issue and it turned out the HTML file for the template wasn't included in my build.

**Comment by mateuszwitkowski** [comment]
I've similar error with AOT.

```
TypeError: Cannot read property 'length' of undefined
    at StaticSymbolResolver.resolveSymbol (C:\frontend-angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:25950:35)
    at StaticReflector.findSymbolDeclaration (C:\frontend-angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:25212:69)
    at StaticReflector.importUri (C:\frontend-angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:25187:52)
    at StaticAndDynamicReflectionCapabilities.importUri (C:\frontend-angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:25102:113)
    at Reflector.importUri (C:\frontend-angular-cli\node_modules\@angular\core\bundles\core.umd.js:2170:94)
    at identifierModuleUrl (C:\frontend-angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:1991:24)
    at _TsEmitterVisitor._visitIdentifier (C:\frontend-angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:20179:44)
    at _TsEmitterVisitor.visitExternalExpr (C:\frontend-angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:19878:16)
    at ExternalExpr.visitExpression (C:\frontend-angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:14603:26)
    at C:\frontend-angular-cli\node_modules\@angular\compiler\bundles\compiler.umd.js:19676:62
Compilation failed
```

I'm struggling with it for days now and keep failing. It would be nice if error message would point out sorce file / part of code which is causing failed compilation.

**Comment by tbosch** [comment]
It turns out that this was a bug in G3 only, because of an error in the custom `ResourceLoader` implementation that we use in G3. Internal reference: b/34282810
