### ISSUE TITLE
IE11 W8.1 Object doesn't support this action

### ISSUE THREAD

**Issue by papajuras** [angular/angular#13794]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When creating a component that emits value via EvenEmitter (    '(valueChanged)="val = $event"' syntax ) IE11 reports error 'Object doesn't support this action'

Works correctly in Chrome, Firefox and Safari.
**Expected behavior**
Component works properly in IE11. 

**Minimal reproduction of the problem with instructions**
This is slightly too big for a plunker, full reproduction is here:
https://github.com/papajuras/angular2IEproblem

(please note this is extracted from existing project, there might be some not necessary code)

**What is the motivation / use case for changing the behavior?**
Wrapping around jquery plugins.
**Please tell us about your environment:**
Windows 8.1
Angular startup project from https://angular.io/docs/ts/latest/guide/setup.html

* **Angular version:** 2.0.X
"@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0", 

from most recent https://angular.io/docs/ts/latest/guide/setup.html

* **Browser:** 
Internet explorer 11 (11.0.9600.16476) 
* **Language:**
    "typescript": "~2.0.10",

* **Stacktrace:** 
Error: Uncaught (in promise): Error: Error in ./AppComponent class AppComponent - inline template:3:76 caused by: Object doesn't support this action
Error: Error in ./AppComponent class AppComponent - inline template:3:76 caused by: Object doesn't support this action
  at _rethrowWithContext (eval code:12769:21)
  at detectChanges (eval code:12742:17)
  at internalDetectChanges (eval code:12577:17)
  at detectChangesInternal (Function code:27:3)
  at detectChanges (eval code:12592:13)
  at detectChanges (eval code:12739:17)
  at detectChanges (eval code:9819:13)
  at Anonymous function (eval code:8721:55)
  at tick (eval code:8721:17)
  at _loadComponent (eval code:8696:13)
  at bootstrap (eval code:8684:13)
  at Anonymous function (eval code:8506:79)
  at _moduleDoBootstrap (eval code:8506:17)
  at Anonymous function (eval code:8458:25)
  at invoke (http://192.168.1.56:3000/node_modules/zone.js/dist/zone.js:240:13)

* **Node (for AoT issues):** `node --version` =   v5.2.0

* **Site note:**
 plnkr https://embed.plnkr.co/?show=preview&show=app%2Fapp.component.ts from tutorial doesn't start in IE either, with error:
ReferenceError: 'Promise' is undefined
  at r (https://embed.plnkr.co/static/build/embed.js:71:29876)
  at y (https://embed.plnkr.co/static/build/embed.js:74:4437)
  at l (https://embed.plnkr.co/static/build/embed.js:74:2834)
  at Anonymous function (https://embed.plnkr.co/static/build/embed.js:7:2125)
  at i (https://embed.plnkr.co/static/build/embed.js:6:916)
  at d (https://embed.plnkr.co/static/build/embed.js:7:1992)
  at a (https://embed.plnkr.co/static/build/embed.js:6:30356)
  at d (https://embed.plnkr.co/static/build/embed.js:7:2445)
  at a (https://embed.plnkr.co/static/build/embed.js:6:30356)
  at a (https://embed.plnkr.co/static/build/embed.js:6:30373) 

I am probably missing some shims added, if thats the case Id appreciate guidance what i am missing

**Comment by DzmitryShylovich** [comment]
> plnkr https://embed.plnkr.co/?show=preview&show=app%2Fapp.component.ts from tutorial doesn't start in IE either, with error:

this one https://plnkr.co/edit/4FS2y3ibae8ZC2XvMN1d?p=preview works in ie

**Comment by papajuras** [comment]
@DzmitryShylovich this one works for me too.

**Comment by DzmitryShylovich** [comment]
Can't reproduce https://plnkr.co/edit/wiX2tFvNeiU0enEffkzA?p=preview
works fine in ie

**Comment by DzmitryShylovich** [comment]
So it's not an angular issue. You probably need some shim/polifyll
