### ISSUE TITLE
If a child module defines a service and uses loadChildren without using a component, it breaks

### ISSUE THREAD

**Issue by fbarbat** [angular/angular#13941]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Lets suppose a root module lazy loads module A which in turns lazy loads module B. Module A "forwards" to child without using a component itself (i.e. {path: 'b', loadChildren: 'app/b.module#BModule'}).
If a component in B uses a service defined in A, it breaks.

```
EXCEPTION: Uncaught (in promise): TypeError: Cannot set property 'stack' of undefined
TypeError: Cannot set property 'stack' of undefined
    at NoProviderError.set [as stack] (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:1203:65)
    at assignAll (https://unpkg.com/zone.js@0.7.5/dist/zone.js:704:29)
    at NoProviderError.ZoneAwareError (https://unpkg.com/zone.js@0.7.5/dist/zone.js:775:16)
    at NoProviderError.BaseError [as constructor] (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:1165:20)
    at NoProviderError.AbstractProviderError [as constructor] (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:1345:20)
    at new NoProviderError (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:1384:20)
    at ReflectiveInjector_._throwOrNull (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3342:23)
    at ReflectiveInjector_._getByKeyDefault (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3379:29)
    at ReflectiveInjector_._getByKey (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3329:29)
    at ReflectiveInjector_.get (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3091:25)
    at AppModuleInjector.NgModuleInjector.get (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:9014:56)
    at proxyClass.AppView.injectorGet (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:12444:49)
    at proxyClass.DebugAppView.injectorGet (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:12824:53)
    at ElementInjector.get (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:12298:31)
    at BModuleInjector.NgModuleInjector.get (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:9014:56)
```

**Expected behavior**
Service should be injected correctly in module B component without the need of using an enclosing component in module A.

**Minimal reproduction of the problem with instructions**
This [plnkr](http://plnkr.co/edit/0grohqIoPWxkYGesmoAb?p=preview) shows four options:

1. */with-enclosing/with-service* -> lazy loads module A, uses an enclosing component, lazy loads Component B which uses an A service from module B. It works and **could be considered a workaround for this problem**.
2. */with-enclosing/without-service* -> Same as 1 but component B does not need a dependency from module A. It also works.
3. */without-enclosing/without-service* -> Module A "forwards" to a component in module B. If that component has no dependencies to a service in module A, it works.
4. */without-enclosing/with-service (breaks)* -> Lazy loads module A which in turns lazy loads module B to load component B. Component in B has a dependency to a service in A. **It breaks.**

**What is the motivation / use case for changing the behavior?**
I have a webapp which consists of:
- A landing page (app module) which has two child modules which represent almost different webapps.
- Each child application (module A) has its own login service which store authenticated user data.
- After authenticated, each application download sources (module B). From module B, we need to access the login service.

**Please tell us about your environment:**
Windows 10, Intellij, Angular Cli 1.0.0-beta.25.5 , npm 4.0.3

* **Angular version:** 4.0.0-beta.3, 2.4.3

* **Browser:** all
 
* **Language:** TypeScript 2.0.2, 2.1.5

* **Node (for AoT issues):** `node --version` =  v6.9.1

**Comment by DzmitryShylovich** [comment]
What zone.js version do u use? https://github.com/angular/zone.js/issues/427#issuecomment-272599762

**Comment by fbarbat** [comment]
I updated the [plunkr](http://plnkr.co/edit/0grohqIoPWxkYGesmoAb?p=preview)

The stacktrace is now:

```
core.umd.js:3463 EXCEPTION: Uncaught (in promise): Error: No provider for HelloService!
Error: DI Error
    at NoProviderError.BaseError [as constructor] (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:1170:31) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:1345:20) [angular]
    at new NoProviderError (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:1384:20) [angular]
    at ReflectiveInjector_._throwOrNull (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3342:23) [angular]
    at ReflectiveInjector_._getByKeyDefault (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3379:29) [angular]
    at ReflectiveInjector_._getByKey (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3329:29) [angular]
    at ReflectiveInjector_.get (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3091:25) [angular]
    at AppModuleInjector.NgModuleInjector.get (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:9014:56) [angular]
    at proxyClass.AppView.injectorGet (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:12444:49) [angular]
    at proxyClass.DebugAppView.injectorGet (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:12824:53) [angular]
    at ElementInjector.get (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:12298:31) [angular]
    at BModuleInjector.NgModuleInjector.get (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:9014:56) [angular]
    at ReflectiveInjector_._getByKeyDefault (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3376:28) [angular]
    at ReflectiveInjector_._getByKey (https://unpkg.com/@angular/core@4.0.0-beta.3/bundles/core.umd.js:3329:29) [angular]
```

**Comment by DzmitryShylovich** [comment]
Lazy loaded modules have their own DI context. You need to provide your service in the `AppModule` if you want to use it in multiple lazy loaded modules http://plnkr.co/edit/jgwRdaZEjd9F7Bgxq3KX?p=preview

**Comment by fbarbat** [comment]
Ok, I understand it could work that way. But is that ok? It is really useful to have services that can be shared to lazy child modules from lazy loaded modules. That was my case, I needed to share a login service from a lazy loaded module to its child. If I had pulled the service all the way up, that would eagerly loaded code that would not always be used -i.e. others modules do not need that login service.

It is also strange that if you use a component from module A it works.

**Comment by DzmitryShylovich** [comment]
It's by design.

> It is also strange that if you use a component from module A it works.

Components are very different from providers

**Comment by fbarbat** [comment]
I'm sorry, I wanted to say that if you use a component from A, you can inject a service from A -which is not registered to component, but to the module. If you do not use the compoenent from A, then the service is not found. Is that by design too?

**Comment by DzmitryShylovich** [comment]
Yeap. Services are lazy instantiated. If you want to eager instantiate your service then you need to add `ngOnDestroy` hook

**Comment by fbarbat** [comment]
There are a couple of things I do not understand here.

First, you say they are on different DI contexts, so a service declared on A should not be visible in B. But a service declared in A is being injected in a component in B in "/with-enclosing/with-service". Why does that work?

Second, I changed that plunkr so it does not instantiate service A on module A. However, it also works injecting service A on a component on module B if a component from A is used. So it looks that eagerly loading a service is not what it is making it to work. It is just the use of a component from A. Why is that happening?

Thanks.

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by fbarbat** [comment]
Hi. I really think this is bug report. If you wanted to close it, at least you could have told me this works like that by -maybe a little currently flawed- design.  The questions above were not to get support but to make you think about the inconsistencies of this case. I took many hours of my time to isolate this case and to help you improve the framework. It is a shame we are loosing an opportunity to get a better tool. I am really sorry but I think I will not contribute again.
