### ISSUE TITLE
ngc compiler - Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by xcaliber-private** [angular/angular#13952]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

If you try to run `ngc` against a project containing code like:
```
const transactionRequest = {
  amount: 0,
  method: new Method
};
```

You receive a cryptic stack trace:
```
TypeError: Cannot read property 'map' of undefined
    at Evaluator.evaluateNode (/Users/dominic/Sites/stash/xcaf/r2d2/node_modules/@angular/tsc-wrapped/src/evaluator.js:302:38)
```

After debugging and console logging. I found the above to be the cause and it points to this code snippet inside evaluator.js:
```javascript
case ts.SyntaxKind.NewExpression:
    var newExpression = node;
    var newArgs = newExpression.arguments.map(function (arg) { return _this.evaluateNode(arg); });
```

**Expected behavior**

A nice pretty message like: `You can't instantiate a class inside of a JS object`

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

To compile projects with errors that allow you to resolve the problem.

**Please tell us about your environment:** OSX Sierra

* **Angular version:** 2.4.3
 
* **Language:** TypeScript

* **Node (for AoT issues):** 7.1.0

**Comment by DzmitryShylovich** [comment]
I think you should report it in typescript repo

**Comment by intellix** [comment]
The problem here is actually the missing parenthesis.

**Comment by trotyl** [comment]
@intellix The `new` statement without parenthesis is still valid JavaScript/TypeScript, just a matter of preference for using parenthesis or not.

**Comment by intellix** [comment]
yeah, that's true but ngc fails without them

**Comment by JayKan** [comment]
+1

**Comment by gtarun** [comment]
Hi, 
I am building my angular application with following params
`ng build --prod --env=production --aot`

Above command always generate all new chunks, vendor and bundled files with a new hash file file. I am serving dist folder through Apache2 on Ubuntu server. 

My problem is when I make a new build and serve new files from my server, all my users starts to get following errors 

**Unhandled Promise rejection: Loading chunk 2 failed. ; Zone: angular ; Task: Promise.then ; Value: Error: Loading chunk 2 failed**

After I refresh the page everything works fine, but untill then all the user see white screen. Is there any way I can handle this error and reload the page with the code automatically?

**Comment by gtarun** [comment]
For more insight on error 

Uncaught SyntaxError: Unexpected token <
error_handler.js:50 EXCEPTION: Uncaught (in promise): Error: Loading chunk 3 failed.
Error: Loading chunk 3 failed.
    at d (https://democo.outgrow.co/vendor.695f83f3660942c007b7.bundle.js:1422:1654)
    at HTMLScriptElement.n (https://democo.outgrow.co/inline.d1d43484501fd2ff0bce.bundle.js:1:554)
    at HTMLScriptElement.e (https://democo.outgrow.co/vendor.695f83f3660942c007b7.bundle.js:1394:766)
    at t.invokeTask (https://democo.outgrow.co/vendor.695f83f3660942c007b7.bundle.js:1422:7626)
    at Object.onInvokeTask (https://democo.outgrow.co/vendor.695f83f3660942c007b7.bundle.js:366:2559)
    at t.invokeTask (https://democo.outgrow.co/vendor.695f83f3660942c007b7.bundle.js:1422:7547)
    at e.runTask (https://democo.outgrow.co/vendor.695f83f3660942c007b7.bundle.js:1422:4428)
    at HTMLScriptElement.invoke (https://democo.outgrow.co/vendor.695f83f3660942c007b7.bundle.js:1422:8766)
t.handleError @ error_handler.js:50
next @ application_ref.js:346
e.object.o @ async.js:91
e.__tryOrUnsub @ Subscriber.js:223
e.next @ Subscriber.js:172
e._next @ Subscriber.js:125
e.next @ Subscriber.js:89
e.next @ Subject.js:55
e.emit @ async.js:77
t.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
t.handleError @ zone.js:246
e.runGuarded @ zone.js:129
r @ zone.js:429
i @ zone.js:438
invoke @ zone.js:349
error_handler.js:55 ORIGINAL STACKTRACE:
t.handleError @ error_handler.js:55
next @ application_ref.js:346
e.object.o @ async.js:91
e.__tryOrUnsub @ Subscriber.js:223
e.next @ Subscriber.js:172
e._next @ Subscriber.js:125
e.next @ Subscriber.js:89
e.next @ Subject.js:55
e.emit @ async.js:77
t.triggerError @ ng_zone.js:329
onHandleError @ ng_zone.js:290
t.handleError @ zone.js:246
e.runGuarded @ zone.js:129
r @ zone.js:429
i @ zone.js:438
invoke @ zone.js:349
error_handler.js:56 Error: Uncaught (in promise): Error: Loading chunk 3 failed.
Error: Loading chunk 3 failed.
    at d (zone.js:682)
    at HTMLScriptElement.n (inline.d1d4348….bundle.js:1)
    at HTMLScriptElement.e (zone.js:889)
    at t.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:260)
    at t.invokeTask (zone.js:274)
    at e.runTask (zone.js:151)
    at HTMLScriptElement.invoke (zone.js:345)
    at d (zone.js:682)
    at f (zone.js:486)
    at f (zone.js:471)
    at zone.js:520
    at t.invokeTask (zone.js:275)
    at Object.onInvokeTask (ng_zone.js:260)
    at t.invokeTask (zone.js:274)
    at e.runTask (zone.js:151)
    at i (zone.js:418)
    at HTMLScriptElement.invoke (zone.js:349)

**Comment by DzmitryShylovich** [comment]
@intellix is this still valid in ng4?

**Comment by intellix** [comment]
I don't seem to be getting it anymore :) Thanks
