### ISSUE TITLE
Using perspective in animations results in partial keyframes exception

### ISSUE THREAD

**Issue by jinder** [angular/angular#14007]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When animating an ngIf with perspective values that don't change, Angular throws a "Partial keyframes are not supported" exception.  This only seems to occur in Chrome, and if an existing animation is interrupted (for example if ngIf gets changed before the animation is complete).  Doesn't seem to occur if perspective is not specified.

```
unpkg.com/zone.js@0.7.6/dist/zone.js:420 Unhandled Promise rejection: Failed to execute 'animate' on 'Element': Partial keyframes are not supported. ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer._triggerWebAnimation (https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:1040:39)
    at WebAnimationsPlayer.init (https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:1024:33)
    at WebAnimationsPlayer.play (https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:1064:18)
    at AnimationSequencePlayer.play (https://unpkg.com/@angular/core/bundles/core.umd.js:10715:32)
    at AnimationQueue._triggerAnimations (https://unpkg.com/@angular/core/bundles/core.umd.js:4544:28)
    at eval (https://unpkg.com/@angular/core/bundles/core.umd.js:4529:75)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.6/dist/zone.js:242:26)
    at Zone.run (https://unpkg.com/zone.js@0.7.6/dist/zone.js:113:43)
    at https://unpkg.com/zone.js@0.7.6/dist/zone.js:535:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.6/dist/zone.js:275:35)
    at Zone.runTask (https://unpkg.com/zone.js@0.7.6/dist/zone.js:151:47)
    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.6/dist/zone.js:433:35)
    at ZoneTask.invoke (https://unpkg.com/zone.js@0.7.6/dist/zone.js:349:25)
    at data.args.(anonymous function) (https://unpkg.com/zone.js@0.7.6/dist/zone.js:1376:25) Error: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer._triggerWebAnimation (https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:1040:39)
    at WebAnimationsPlayer.init (https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:1024:33)
    at WebAnimationsPlayer.play (https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:1064:18)
    at AnimationSequencePlayer.play (https://unpkg.com/@angular/core/bundles/core.umd.js:10715:32)
    at AnimationQueue._triggerAnimations (https://unpkg.com/@angular/core/bundles/core.umd.js:4544:28)
    at eval (https://unpkg.com/@angular/core/bundles/core.umd.js:4529:75)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.6/dist/zone.js:242:26)
    at Zone.run (https://unpkg.com/zone.js@0.7.6/dist/zone.js:113:43)
    at https://unpkg.com/zone.js@0.7.6/dist/zone.js:535:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.6/dist/zone.js:275:35)
    at Zone.runTask (https://unpkg.com/zone.js@0.7.6/dist/zone.js:151:47)
    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.6/dist/zone.js:433:35)
    at ZoneTask.invoke (https://unpkg.com/zone.js@0.7.6/dist/zone.js:349:25)
``` 

**Expected behavior**
Should animate without exception.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/7TMOx571Eurk74yIVtVX?p=preview

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Only seems to occur on Chrome.  Use Chrome 55 on Mac to repro.

* **Angular version:** 2.4.3

* **Browser:** Chrome 55

 
* **Language:** all

**Comment by DennisSmolek** [comment]
I wanted to add a +1 to this. We use Material2 tabs and when inside our component that uses `<ng-content>` we get the same `partial keyframes` error when we wrapped the element in a `*ngIf="show"`. 

I think it's something with animations inside the tabs module attempting to fire but the item is hidden with the ngIf.. I can't for the life of me figure out how to get it to work correctly..

**Comment by DzmitryShylovich** [comment]
@jinder is this still valid in angular 4? can you please update the plunkr? thanks

**Comment by jinder** [comment]
@DzmitryShylovich Seems to have been fixed in 4.0.0-rc2:  http://plnkr.co/edit/KohCoFzDBywBy8Ez7m5X

@DennisSmolek is it now fixed for you too?

**Comment by DzmitryShylovich** [comment]
@jinder close the issue if it was fixed please.

**Comment by jinder** [comment]
@DzmitryShylovich Actually, it appears that the animations were disabled in the updated plunkr due to the new animations module.

```
Unhandled Promise rejection: Failed to execute 'animate' on 'Element': 'undefined' is not a valid value for easing ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Failed to execute 'animate' on 'Element': 'undefined' is not a valid value for easing
    at WebAnimationsPlayer._triggerWebAnimation (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:2439:42)
    at WebAnimationsPlayer.init (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:2426:37)
    at InjectableAnimationEngine._queuePlayer (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1878:24)
    at InjectableAnimationEngine.animateTransition (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1814:22)
    at eval (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1975:58)
    at Array.forEach (native)
    at eval (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1971:55)
    at Map.forEach (native)
    at InjectableAnimationEngine.flush (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1944:38)
    at eval (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:504:44)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.8/dist/zone.js:334:26)
    at Zone.run (https://unpkg.com/zone.js@0.7.8/dist/zone.js:126:43)
    at https://unpkg.com/zone.js@0.7.8/dist/zone.js:713:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.8/dist/zone.js:367:31)
    at Zone.runTask (https://unpkg.com/zone.js@0.7.8/dist/zone.js:166:47)
    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.8/dist/zone.js:546:35) TypeError: Failed to execute 'animate' on 'Element': 'undefined' is not a valid value for easing
    at WebAnimationsPlayer._triggerWebAnimation (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:2439:42)
    at WebAnimationsPlayer.init (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:2426:37)
    at InjectableAnimationEngine._queuePlayer (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1878:24)
    at InjectableAnimationEngine.animateTransition (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1814:22)
    at eval (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1975:58)
    at Array.forEach (native)
    at eval (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1971:55)
    at Map.forEach (native)
    at InjectableAnimationEngine.flush (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:1944:38)
    at eval (https://unpkg.com/@angular/platform-browser@4.0.0-rc.2/bundles/platform-browser-animations.umd.js:504:44)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.8/dist/zone.js:334:26)
    at Zone.run (https://unpkg.com/zone.js@0.7.8/dist/zone.js:126:43)
    at https://unpkg.com/zone.js@0.7.8/dist/zone.js:713:57
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.8/dist/zone.js:367:31)
    at Zone.runTask (https://unpkg.com/zone.js@0.7.8/dist/zone.js:166:47)
    at drainMicroTaskQueue (https://unpkg.com/zone.js@0.7.8/dist/zone.js:546:35)
```

**Comment by DzmitryShylovich** [comment]
@jinder can you update the plunkr?

**Comment by jinder** [comment]
@DzmitryShylovich already have:  http://plnkr.co/edit/KohCoFzDBywBy8Ez7m5X

**Comment by lukefarran** [comment]
I'm seeing this in Angular 4.0.0

**Comment by GuerrillaCoder** [comment]
I am getting this also using translateX() - https://plnkr.co/edit/qEXLKKMO2KjuVKlC2NsI?p=preview

**Comment by ciesielskico** [comment]
Gettings this with material2.beta3 md-tabs and Angular 4.0.1 on latest Chrome as well.

**Comment by jinder** [comment]
@matsko @DzmitryShylovich Is anyone looking into this?  I'm now also seeing this in Safari in some scenarios.

**Comment by jinder** [comment]
I've updated the plunkr and it's still a problem in 4.2.0-rc2: http://plnkr.co/edit/Tox3xoAm20l2DPV8JwJ2

This wouldn't be such a problem if the animation just failed.  But the DOM elements are left in an inconsistent state.

```
ERROR DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at WebAnimationsPlayer._triggerWebAnimation (https://unpkg.com/@angular/animations@4.2.0-rc.2/bundles/animations-browser.umd.js:4662:35)
    at WebAnimationsPlayer._buildPlayer (https://unpkg.com/@angular/animations@4.2.0-rc.2/bundles/animations-browser.umd.js:4636:29)
    at WebAnimationsPlayer.play (https://unpkg.com/@angular/animations@4.2.0-rc.2/bundles/animations-browser.umd.js:4691:14)
    at TransitionAnimationPlayer.play (https://unpkg.com/@angular/animations@4.2.0-rc.2/bundles/animations-browser.umd.js:4161:91)
    at eval (https://unpkg.com/@angular/animations@4.2.0-rc.2/bundles/animations-browser.umd.js:3879:20)
    at Array.forEach (native)
    at TransitionAnimationEngine._flushAnimations (https://unpkg.com/@angular/animations@4.2.0-rc.2/bundles/animations-browser.umd.js:3872:21)
    at TransitionAnimationEngine.flush (https://unpkg.com/@angular/animations@4.2.0-rc.2/bundles/animations-browser.umd.js:3689:28)
    at InjectableAnimationEngine.AnimationEngine.flush (https://unpkg.com/@angular/animations@4.2.0-rc.2/bundles/animations-browser.umd.js:4527:32)
    at eval (https://unpkg.com/@angular/platform-browser@4.2.0-rc.2/bundles/platform-browser-animations.umd.js:325:26)
```
