### ISSUE TITLE
Error was occurred when angular application embed to webcomponent. 

### ISSUE THREAD

**Issue by gorshkov-leonid** [angular/angular#14011]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Error was occurred when angular application embed to webcomponent. 
I try to embed angular inside web component (adapted example from https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5)
```
The selector "my-app" did not match any elements
    at DomRenderer.selectRootElement (https://unpkg.com/@angular/platform-browser/bundles/platform-browser.umd.js:2923:27) [angular]
    at DebugDomRenderer.selectRootElement (https://unpkg.com/@angular/core/bundles/core.umd.js:11769:60) [angular]
    at selectOrCreateRenderHostElement (https://unpkg.com/@angular/core/bundles/core.umd.js:7093:36) [angular]
    at CompiledTemplate.proxyViewClass.View_App_Host0.createInternal (/AppModule/App/host.ngfactory.js:13:16) [angular]
    at CompiledTemplate.proxyViewClass.AppView.createHostView (https://unpkg.com/@angular/core/bundles/core.umd.js:12409:25) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (https://unpkg.com/@angular/core/bundles/core.umd.js:12817:56) [angular]
    at ComponentFactory.create (https://unpkg.com/@angular/core/bundles/core.umd.js:7774:29) [angular]
    at ApplicationRef_.bootstrap (https://unpkg.com/@angular/core/bundles/core.umd.js:8761:61) [angular]
    at eval (https://unpkg.com/@angular/core/bundles/core.umd.js:8589:93) [angular]
    at Array.forEach (native) [angular]
    at PlatformRef_._moduleDoBootstrap (https://unpkg.com/@angular/core/bundles/core.umd.js:8589:46) [angular]
    at eval (https://unpkg.com/@angular/core/bundles/core.umd.js:8541:31) [angular]
    at Object.onInvoke (https://unpkg.com/@angular/core/bundles/core.umd.js:4435:41) [angular]
```
Error in 
```
   DomRenderer.prototype.selectRootElement = function (selectorOrNode, debugInfo) {
            var /** @type {?} */ el;
            if (typeof selectorOrNode === 'string') {
                el = this._rootRenderer.document.querySelector(selectorOrNode);
                if (!el) {
                    throw new Error("The selector \"" + selectorOrNode + "\" did not match any elements");
                }
            }
```
`this._rootRenderer.document` is root document - it is not webcomponent's document (can be obtained with document.currentScript.ownerDocument in webcomponent)

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
* **Angular version:** 2.4.4
* **Browser:** Chrome 55.0.2883.87
* **Language:**  TypeScript

**Comment by DzmitryShylovich** [comment]
> https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

is empty. did you save your changes?

**Comment by gorshkov-leonid** [comment]
I tried to explain problem without code. Ok I will prepare  code tomorrow for the morning

**Comment by DzmitryShylovich** [comment]
I got the issue, but `document.currentScript` returns `null` so I need a working example :)

**Comment by gorshkov-leonid** [comment]
example is ready
https://plnkr.co/edit/3c2FRdI2ZHKID5ZOUOje?p=preview

**Comment by DzmitryShylovich** [comment]
> how to inject 'parentDocument' instead 'rootDocument'?

but `parentDocument.querySelector('my-app')` returns `null` as well

**Comment by DzmitryShylovich** [comment]
need something like `parentDocument.querySelector('#mycmp-template').content.querySelector('my-app');`...

**Comment by gorshkov-leonid** [comment]
I was terribly wrong. To search embedding container querySelector should be called on shadowRoot.... 
I want to angular work in context of shadowRoot of webcomponent - not document.

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/5qGClUiYzDBj1SgeIRQt?p=preview

**Comment by gorshkov-leonid** [comment]
Wow, 
```
 providers: [{provide: DOCUMENT, useValue: shadowRoot}]
```
Thanks, but I concerned. shadowRoot does not implement Document's contract. In future may be  problem.

**Comment by gorshkov-leonid** [comment]
https://www.w3.org/TR/2012/WD-shadow-dom-20120522/#shadow-root-object
I would like to be sure that angular uses DOCUMENT as DocumentFragment (I think DocumentFragment is lightweight Document, it have subset of methods of Document)
