### ISSUE TITLE
ng-xi18n error: ENOENT: no such file or directory, open '...utils.metadata.json'

### ISSUE THREAD

**Issue by born2net** [angular/angular#14138]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
angular-cli: 1.0.0-beta.26
node: 6.5.0
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/language-service: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.2.1
@angular/compiler-cli: 2.4.5
```
**Current behavior**
expect to generate translation file

**Expected behavior**
getting error:

```
$ ./node_modules/.bin/ng-xi18n  --i18nFormat=xmb -p src/tsconfig.json
Error: ENOENT: no such file or directory, open 'C:\msweb\studioweb\dist\out-tsc\node_modules\angular-pipes\src\utils\utils.metadata.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at MetadataWriterHost.writeMetadata (C:\msweb\studioweb\node_modules\@angular\tsc-wrapped\src\compiler_host.js:164:22)
    at MetadataWriterHost.writeFile (C:\msweb\studioweb\node_modules\@angular\tsc-wrapped\src\compiler_host.js:143:19)
    at Object.writeFile (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:45369:132)
    at Object.writeFile (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:7602:14)
    at writeEmittedFiles (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:37859:20)
    at doEmit (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:37719:17)
    at emitFile (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:44665:21)
Extraction failed
```

**Minimal reproduction of the problem with instructions**
repo: https://github.com/born2net/studioweb

**What is the motivation / use case for changing the behavior?**
expect it to work

**Comment by born2net** [comment]
let me add that it is looking for node_modules that does not exist in dist
```
/cygdrive/c/msweb/studioweb/dist/out-tsc

root@DESKTOP-VEUHFOL /cygdrive/c/msweb/studioweb/dist/out-tsc
$ ls
src

```

**Comment by born2net** [comment]
also tried in windows command instead of cygwin:

```
C:\msweb\studioweb>
C:\msweb\studioweb>"./node_modules/.bin/ng-xi18n" -p "src/tsconfig.json"
Error: ENOENT: no such file or directory, open 'C:\msweb\studioweb\dist\out-tsc\node_modules\angular-pipes\src\utils\utils.metadata.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at MetadataWriterHost.writeMetadata (C:\msweb\studioweb\node_modules\@angular\tsc-wrapped\src\compiler_host.js:164:22)
    at MetadataWriterHost.writeFile (C:\msweb\studioweb\node_modules\@angular\tsc-wrapped\src\compiler_host.js:143:19)
    at Object.writeFile (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:45369:132)
    at Object.writeFile (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:7602:14)
    at writeEmittedFiles (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:37859:20)
    at doEmit (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:37719:17)
    at emitFile (C:\msweb\studioweb\node_modules\typescript\lib\typescript.js:44665:21)
Extraction failed

C:\msweb\studioweb>
```

**Comment by born2net** [comment]
I was able to solve the issue via:
```
cp -r -f node_modules/ ./dist/out-tsc/
```
but I believe this is still a bug, unless someone can recommend some env setting that needs to be set?
to have i18n look at the proper dir in Windows for node_modules?

regards

**Comment by tbosch** [comment]
Hello,
we need a way of reproducing this. Could you create a small example that shows the error?

**Comment by born2net** [comment]
I believe its ok now.. I will close for now and open if I face issue again,
tx!

**Comment by cburgmer** [comment]
I have the same issue. I'd happily debug, but I don't know who's trying what here. Any pointers where to look?

My only guess so far is that ng-xi18n fails on node-dependencies which themselves are written in TypeScript.

**Comment by cburgmer** [comment]
To clarify, my dependency is an Angular2 component, without AOT compilation. Is AOT required on dependencies to make i18n work for the app? I spent an hour or so trying getting AOT up and running, to now avail.
