### ISSUE TITLE
Language service error Warning:(1, 1) Angular Language Service internal globalError: Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by born2net** [angular/angular#14366]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
Warning:(1, 1) Angular Language Service internal globalError: Cannot read property 'charCodeAt' of undefined
```

when configured template with templateRef:
```
  <Slideritem [templateRef]="g">
                <template #g>
                </template>
            </Slideritem>
```
**Expected behavior**
no error

```
@angular/cli: 1.0.0-beta.30
node: 6.9.5
os: win32 x64
@angular/cli: 1.0.0-beta.30
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/language-service: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.6
@ngtools/webpack: 1.2.8
```

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by dahaupt** [comment]
In my project I've got a similar warning:
`Warning:(1, 1) Angular Language Service internal globalError: Cannot read property 'has' of undefined`

**Comment by born2net** [comment]
same here...

**Comment by elmccd** [comment]
@dahaupt I had the same problem while using angular `2.4.8` and language service `2.4.10`. 
Changing service version to `2.4.8` to match angular solved the issue.

**Comment by anstarovoyt** [comment]
error:
Process: Error processing message: Cannot read property 'has' of undefined TypeError: Cannot read property 'has' of undefined
    at ExpressionDiagnosticsVisitor.visitVariable (/Users/anstarovoyt/git/ngcli-devoxx/node_modules/@angular/language-service/bundles/language-service.umd.js:45706:26)
    at VariableAst.visit (/Users/anstarovoyt/git/ngcli-devoxx/node_modules/@angular/language-service/bundles/language-service.umd.js:15747:25)
    at visit (/Users/anstarovoyt/git/ngcli-devoxx/node_modules/@angular/language-service/bundles/language-service.umd.js:15982:38)
    at /Users/anstarovoyt/git/ngcli-devoxx/node_modules/@angular/language-service/bundles/language-service.umd.js:15984:43
    at Array.forEach (native)
    at templateVisitAll (/Users/anstarovoyt/git/ngcli-devoxx/node_modules/@angular/language-service/bundles/language-service.umd.js:15983:11)
    at visit (/Users/anstarovoyt/git/ngcli-devoxx/node_modules/@angular/language-service/bundles/language-service.umd.js:43556:31)
    at /Users/anstarovoyt/git/ngcli-devoxx/node_modules/@angular/language-service/bundles/language-service.umd.js:43517:14
    at ExpressionDiagnosticsVisitor.TemplateAstChildVisitor.visitChildren (/Users/anstarovoyt/git/ngcli-devoxx/node_modules/@angular/language-service/bundles/language-service.umd.js:43558:10)
    at ExpressionDiagnosticsVisitor.TemplateAstChildVisitor.visitEmbeddedTemplate (/Users/anstarovoyt/git/ngcli-devoxx/node_modules/@angular/language-service/bundles/language-service.umd.js:43514:22)

**Comment by marcoturi** [comment]
Same here with 2.4.9 (both angular core and language service)

**Comment by Ionaru** [comment]
I'm getting the same kind of warnings with Angular 4.0.0

**Comment by born2net** [comment]
really? :( I was really hoping it will be fixed in angular4

**Comment by anstarovoyt** [comment]
@Ionaru I don't see Angular LS 4.0 ( [Link](https://www.npmjs.com/package/@angular/language-service) )
 Angular LS 2.4.* can be incompatible with Angular 4.0

**Comment by Ionaru** [comment]
That might be possible, yes.

**Comment by anstarovoyt** [comment]
released https://www.npmjs.com/package/@angular/language-service

**Comment by Ionaru** [comment]
Seems an upgrade to LS 4.0.0 did not fix the issue

Node 7.5.0
Typescript 2.2.1
Angular 4.0.0
Angular LS 4.0.0

![screenshot_3](https://cloud.githubusercontent.com/assets/3472373/24316450/5390f930-10ee-11e7-9820-2ce57b7d526f.png)

```
Process: Error processing message: Cannot read property 'hasOwnProperty' of undefined TypeError: Cannot read property 'hasOwnProperty' of undefined
    at toSymbols (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:48013:33)
    at new SymbolTableWrapper (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:48248:28)
    at SymbolWrapper.members (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:48132:60)
    at AstType.resolvePropertyRead (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:45467:35)
    at AstType.visitPropertyRead (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:45408:21)
    at PropertyRead.visit (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:18690:24)
    at AstType.getType (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:45167:61)
    at C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:45457:96
    at Array.map (native)
    at AstType.resolveMethodCall (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:45457:62)
Process: Error processing message: Cannot read property '__constructor' of undefined TypeError: Cannot read property '__constructor' of undefined
    at TypeScriptSymbolQuery.getTemplateRefContextType (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:47960:39)
    at TypeScriptSymbolQuery.getTemplateContext (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:47935:36)
    at ExpressionDiagnosticsVisitor.visitVariable (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:47029:52)
    at VariableAst.visit (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:16446:24)
    at visit (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:16681:37)
    at C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:16683:42
    at Array.forEach (native)
    at templateVisitAll (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:16682:10)
    at visit (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:44866:30)
    at C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:44827:13
Process: Error processing message: Cannot read property '__constructor' of undefined TypeError: Cannot read property '__constructor' of undefined
    at TypeScriptSymbolQuery.getTemplateRefContextType (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:47960:39)
    at TypeScriptSymbolQuery.getTemplateContext (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:47935:36)
    at ExpressionDiagnosticsVisitor.visitVariable (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:47029:52)
    at VariableAst.visit (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:16446:24)
    at visit (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:16681:37)
    at C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:16683:42
    at Array.forEach (native)
    at templateVisitAll (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:16682:10)
    at visit (C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:44866:30)
    at C:\Users\Jeroen\IdeaProjects\EVE Track\client\node_modules\@angular\language-service\bundles\language-service.umd.js:44827:13
```

**Comment by kevincam3** [comment]
Same problem

**Comment by chuckjaz** [comment]
Can you try changing the TypeScript to version `2.1.5`. TypeScript has made internal changes in `2.2.1` that the language service is not resilient to.

**Comment by kevincam3** [comment]
I changed it to 2.1.5 but still get globalErrors

**Comment by chuckjaz** [comment]
I tried this in: 
```
WebStorm 2017.1
Build #WS-171.3780.79, built on March 17, 2017
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.3
 ```

with TypeScript 2.2.1 and `@angular/language-service` 4.0.0 and could reproduce this with the https://github.com/angular/quickstart application.  

Is there a project I can clone to see this?

**Comment by born2net** [comment]
seems issue persists with latest  ```"@angular/language-service": "^4.1.0-beta",```

**Comment by born2net** [comment]
You can use this project:
https://github.com/born2net/studioweb

**Comment by tonimitrevski** [comment]
Same problem

**Comment by jakeNiemiec** [comment]
Same issue for me after upgrading to 4.0.0

**Comment by dojchek** [comment]
Same issue for me, running on:
```
@angular/language-service: 4.0.1
typescript 2.2.2
node: 7.4.0
os: win32 x64
WebStorm 2017.1
```

**Comment by duydao** [comment]
Updating to angular & language service from 4.0.1 to 4.0.2 solved it for me:

`@angular/language-service: 4.0.2
typescript 2.2.2
node: 6.10.0
os: mac os
IntelliJ 2017.1`

**Comment by dojchek** [comment]
Updating to 4.0.2 also did the trick for me.

**Comment by born2net** [comment]
same!
closing!
tx!
