### ISSUE TITLE
Error: Error in :0:0 caused by: $parentScope.$new is not a function

### ISSUE THREAD

**Issue by TitanNano** [angular/angular#14502]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm upgrading a AngularJS component but the following error is thrown when it gets instantiated.
The exception occurs in the UpgradeComponent constructor.

```
Error: Error in :0:0 caused by: $parentScope.$new is not a function
    at ViewWrappedError.ZoneAwareError (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:120131:33)
    at ViewWrappedError.BaseError [as constructor] (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:45764:16)
    at ViewWrappedError.WrappedError [as constructor] (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:45829:16)
    at new ViewWrappedError (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:72860:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:133048:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:132965:18)
    at ViewContainerRef_.createComponent (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:73527:62)
    at UIView.applyUpdatedConfig (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:41447:50)
    at UIView.viewConfigUpdated (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:41435:14)
    at configureUIView (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:117317:24)
    at Array.forEach (native)
    at ViewService.sync (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:117319:82)
    at activateViews (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:255980:11)
    at TransitionHook.invokeHook (http://jovandemo.modulentwicklung.de/dist/vendor_f75ba111f481cdcf5ec6.js:41108:37)
    at Array.forEach (native)
```

**Expected behavior**
No error.

**Minimal reproduction of the problem with instructions**
Nothing fancy.
```TypeScript
@Directive({
	selector: 'zmb-articles-overview',
})
export class ZmbArticlesOverview extends UpgradeComponent {
	constructor(elementRef: ElementRef, injector: Injector) {
		super('zmbArticlesOverview', elementRef, injector);
	}
}
```
**Please tell us about your environment:**
Firefox and Google Chrome, macOS 10.12.3

* **Angular version:** 2.0.X
```
    "@angular/core": "^2.4.6",
    "@angular/upgrade": "^2.4.6",
```

* **Browser:**
Google Chrome, Firefox
 
* **Language:**
TypeScript 2.1.5

* **Node (for AoT issues):** `node --version` =   
Node v7.4

**Comment by gkalpak** [comment]
There is not enough info to investigate the problem. Can you create a reproduction (you can use [this plnkr][1] as a base)?

[1]: http://plnkr.co/edit/785vvBBviXfwDNVCysZg?p=preview

**Comment by TitanNano** [comment]
I don't really have time to create the plnkr, but I can say that the issue appears if someone tries to instantiate components like this: `bootstrap ng2 component` -> `ng1 component`. I understand that this might be something that shouldn't be done, but it would be useful if an explanation could be given when this error appears.

**Comment by tbosch** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by RaphyLi** [comment]
@TitanNano did you use ui-router-ng2? 
Because I have the same error, when I changed angular-ui-router to ui-router-ng2, this error appear.

**Comment by TitanNano** [comment]
@RaphyLi  yes I was using ui router 2. You shouldn't bootstrap with an ng2 component. you need to bootstrap a ng1 component and load a downgraded ng2 component in there.
