### ISSUE TITLE
Better error message when lazy loading a module with no root route

### ISSUE THREAD

**Issue by shairez** [angular/angular#14596]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When not setting a root route for a lazy loaded module, I'm getting the following error - 

```
error_handler.js:54 EXCEPTION: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65880:56)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
error_handler.js:60 Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at RouterPreloader.processRoutes (router_preloader.js:128)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at resolvePromise (zone.js:643) [angular]
    at polyfills.bundle.js:6620:17 [angular]
    at Object.onInvokeTask (ng_zone.js:264) [angular]
    at ZoneDelegate.invokeTask (zone.js:362) [angular]
    at Zone.runTask (zone.js:166) [<root> => angular]
    at drainMicroTaskQueue (zone.js:529) [<root>]
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
ZoneDelegate.handleError @ zone.js:334
Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
zone.js:516 Unhandled Promise rejection: Maximum call stack size exceeded ; Zone: angular ; Task: Promise.then ; Value: RangeError: Maximum call stack size exceeded
    at RouterPreloader.processRoutes (router_preloader.js:128)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135)
    at RouterPreloader.processRoutes (router_preloader.js:135) RangeError: Maximum call stack size exceeded
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65880:56)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
    at RouterPreloader.processRoutes (http://localhost:4200/vendor.bundle.js:65887:31)
consoleError @ zone.js:516
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
zone.js:518 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call …, rejection: RangeError: Maximum call stack size exceeded
    at RouterPreloader.processRoutes (http://localhost:…, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask…}
consoleError @ zone.js:518
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
```

**Expected behavior**
I think a clearer bug message could be helpful for first time users, something like: 

```
There isn't a root route defined on your lazy loaded module
```
Or something along this line

**Minimal reproduction of the problem with instructions**

[Checkout this plunker](https://plnkr.co/edit/53pRiIs7kfiF3r1SaIOy?p=preview)

Click on `Lazy loaded module with no routes` and check the console

**OR**

1. Generate an app with Angular cli
2. Generate a module with a component, let's say a `SettingsModule`
3. Add the following line to the AppModule routes array -
`{ path: 'settings', loadChildren: 'app/settings/settings.module#SettingsModule' }`
4. Add this to the `app.component.html` - 
``` 
 <a routerLink="/settings">settings</a>

  <router-outlet></router-outlet>
```

5. Load the app and click on the settings link

**What is the motivation / use case for changing the behavior?**
Could save the confusion and debugging time

**Please tell us about your environment:**
Windows 10, vs code, npm 3.10.9
angular/cli 1.0.0-beta.32.3

* **Angular version:** 2.0.X
2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 56.0.2924.87 (64-bit)
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript@2.0.10

* **Node (for AoT issues):** `node --version` =   
v7.2.0

**Comment by Toxicable** [comment]
What about the situation where you don't want to have a default route?

**Comment by shairez** [comment]
I will edit and rephrase my issue - I've meant a root route, not a redirect default route.

meaning: 
`{ path: "" }`

**Comment by DzmitryShylovich** [comment]
@shairez pls provide a plunkr

**Comment by shairez** [comment]
@DzmitryShylovich here you go - 

https://plnkr.co/edit/53pRiIs7kfiF3r1SaIOy?p=preview

Click on `Lazy loaded module with no routes` and check the console
