### ISSUE TITLE
angular 4.0.0-beta.8 - Unhandled Promise rejection: Cannot read property 'merge' of undefined

### ISSUE THREAD

**Issue by albertosantini** [angular/angular#14603]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The app throws the following exception:
```
Unhandled Promise rejection: Cannot read property 'merge' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'merge' of undefined
    at new ApplicationRef_ (VM797 core.umd.js:8410)
    at class1Injector.createInternal (/class1/module.ngfactory.js:133)
    at class1Injector.NgModuleInjector.create (VM797 core.umd.js:8673)
    at NgModuleFactory.create (VM797 core.umd.js:8646)
    at VM797 core.umd.js:8192
    at ZoneDelegate.invoke (zone.js:330)
    at Object.onInvoke (VM797 core.umd.js:3891)
    at ZoneDelegate.invoke (zone.js:329)
    at Zone.run (zone.js:126)
    at NgZone.run (VM797 core.umd.js:3760)
    at PlatformRef_._bootstrapModuleFactoryWithZone (VM797 core.umd.js:8190)
    at VM797 core.umd.js:8230
    at ZoneDelegate.invoke (zone.js:330)
    at Zone.run (zone.js:126)
    at zone.js:679 TypeError: Cannot read property 'merge' of undefined
    at new ApplicationRef_ (https://unpkg.com/@angular/core@4.0.0-beta.8/bundles/core.umd.js:8410:52)
    at class1Injector.createInternal (/class1/module.ngfactory.js:133:30)
    at class1Injector.NgModuleInjector.create (https://unpkg.com/@angular/core@4.0.0-beta.8/bundles/core.umd.js:8673:80)
    at NgModuleFactory.create (https://unpkg.com/@angular/core@4.0.0-beta.8/bundles/core.umd.js:8646:22)
    at https://unpkg.com/@angular/core@4.0.0-beta.8/bundles/core.umd.js:8192:65
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.7/dist/zone.js:330:26)
    at Object.onInvoke (https://unpkg.com/@angular/core@4.0.0-beta.8/bundles/core.umd.js:3891:41)
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.7/dist/zone.js:329:32)
    at Zone.run (https://unpkg.com/zone.js@0.7.7/dist/zone.js:126:43)
    at NgZone.run (https://unpkg.com/@angular/core@4.0.0-beta.8/bundles/core.umd.js:3760:66)
    at PlatformRef_._bootstrapModuleFactoryWithZone (https://unpkg.com/@angular/core@4.0.0-beta.8/bundles/core.umd.js:8190:27)
    at https://unpkg.com/@angular/core@4.0.0-beta.8/bundles/core.umd.js:8230:63
    at ZoneDelegate.invoke (https://unpkg.com/zone.js@0.7.7/dist/zone.js:330:26)
    at Zone.run (https://unpkg.com/zone.js@0.7.7/dist/zone.js:126:43)
    at https://unpkg.com/zone.js@0.7.7/dist/zone.js:679:57
consoleError @ zone.js:516
_loop_1 @ zone.js:545
drainMicroTaskQueue @ zone.js:549
ZoneTask.invoke @ zone.js:420
zone.js:518 
```

**Expected behavior**
No exception raised (with 4.0.0-beta.7 it is ok).

**Minimal reproduction of the problem with instructions**

With 4.0.0-beta.8 it raises the exception:
http://plnkr.co/edit/bLymPemonIFk52fB8JfK?p=preview

With 4.0.0-beta.7 it works ok:
http://plnkr.co/edit/fcVTRysHUdmHfWpcyYOs?p=preview

**What is the motivation / use case for changing the behavior?**
Using Angular with ES5.

**Please tell us about your environment:**

* **Angular version:** 4.0.0-beta.8

* **Browser:** [all]

 
* **Language:** [ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by albertosantini** [comment]
It seems `rxjs_observable_merge` is undefined.

(core.umd.js:8410)
 _this._isStable = rxjs_observable_merge.merge(isCurrentlyStable, rxjs_operator_share.share.call(isStable));

Maybe there is an error in the [rollup config](https://github.com/angular/angular/blob/e25baa08b33c7679165f94e54f438328db506bf8/modules/%40angular/core/rollup.config.js).

**Comment by albertosantini** [comment]
@robwormald It seems fixing rollup should be the way to go, giving a look at the similar past issues, but it seems something it is changed and I don't find the configs.

I would prepare the PR. Any hint? Thanks in advance.

**Comment by albertosantini** [comment]
@DzmitryShylovich thanks.

rc.1 has the same issue as stated in `Known Issues`.

Workaround waiting for the merge:

```
        <script src="node_modules/rxjs/bundles/Rx.min.js"></script>
...
        <script>
            // workaround for https://github.com/angular/angular/issues/14626
            Rx.Symbol.$$observable = Rx.Symbol.observable;
            window.rxjsObservable = Rx;
            window.rxjsSymbolObservable = Rx.Symbol;
            window.rxjsObservableMerge = Rx.Observable;
            window.rxjsOperatorShare = Rx.Observable.prototype;
        </script>
        <script src="node_modules/@angular/core/bundles/core.umd.min.js"></script>
...
```

**Comment by DzmitryShylovich** [comment]
@albertosantini fixed by https://github.com/angular/angular/pull/14820

**Comment by albertosantini** [comment]
Tested my use case with 4.0.0-rc.2. 
It is ok.

Thanks for the efforts.
