### ISSUE TITLE
Could not resolve [moduleName] relative to [path] for modules ending with "*.js"

### ISSUE THREAD

**Issue by mgechev** [angular/angular#14663]
PR here https://github.com/angular/angular/pull/14664

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The issue is in `@angular/compiler-cli` when using AoT and referencing modules which end with `.js`. For instance:

```ts
// ...
import { Wove } from 'aspect.js';

@Wove()
export class NameListService {

  constructor(private http: Http) {}

  get(): Observable<string[]> {
    return this.http.get('assets/data.json')
                    .map((res: Response) => res.json())
                    .catch(this.handleError);
  }
}
```

Fails with error:

```
Error: Error encountered resolving symbol values statically. Could not resolve aspect.js relative to .../shared/name-list/name-list.service.ts., resolving symbol NameListService in .../shared/name-list/name-list.service.ts, resolving symbol NameListService in .../app/shared/name-list/name-list.service.ts
```

The issue is in:

`CompilerHost.getCanonicalFileName` where the `.js` from `aspect.js` is being stripped by the line
`m = m.replace(EXT, '');`, since it's considered as a relative path.

**Expected behavior**

There should not be an error.

**Minimal reproduction of the problem with instructions**

Try to use the `@Wove` decorator from [`aspect.js`](https://github.com/mgechev/aspect.js).

* **Angular version:** 2.0.X

Angular 2.4 - 4.0.
 
* **Language:** TypeScript

According to https://github.com/Microsoft/TypeScript/issues/4595, stripping the file extension is not required because the TypeScript compiler accepts imports with which include extension.

**Comment by cyrilletuzi** [comment]
Do we agree that in this case, the compiler will first search for `aspect.ts` and then, if it does not exist, `aspect.js`, as TypeScript does since 2.0 ? It's important for compatibility with upcoming `<script type="module"></script>`, which requires the `.js` extension.

**Comment by fahdsaeed** [comment]
i'm getting this error

ERROR in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts (5,30): Cannot find module 'angular2-select'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve angular2-select relative to /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts., resolving symbol DashboardModule in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts, resolving symbol DashboardModule in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts
    at Error (native)
    at syntaxError (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

webpack: Failed to compile.

**Comment by pkozlowski-opensource** [comment]
Sounds like this one can be closed based on https://github.com/angular/angular/pull/14664#issuecomment-366098086
