### ISSUE TITLE
angular 4.0.0-rc.1 unable to start with ng serve command

### ISSUE THREAD

**Issue by aniruddhadas9** [angular/angular#14735]
**I'm submitting a ...**  (check one with "4.0.0-rc.1")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

`ng serve` or `ng build` showing the below described error.

**Expected behavior**

`ng serve` should start the application at localhost:4200

**Minimal reproduction of the problem with instructions**

I created one application `using ng new appname` and then in my package.json I changed ^2.4.0 to 4.0.0-rc1 to upgrade from angular2 to angular4. Then I deleted the node_modules and did `npm i` to get dependencies. everything goes well.

Now when I did `ng serve` ot `ng build` I got below error.

**angular cli version**
@angular/cli: 1.0.0-rc.0
node: 6.9.1
os: darwin x64

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.9.1

**detail error message**

C02NM7DYG3QD:feb25 k26686$ npm start

> feb25@0.0.0 start /Users/k26686/aniruddh/develop/ng2cli/feb25
> ng serve

Cannot read property 'Private' of undefined
TypeError: Cannot read property 'Private' of undefined
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/tsickle/build/src/tsickle.js:111:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/src/main.js:11:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/index.js:14:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/src/compiler_host.js:14:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/src/codegen.js:15:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/index.js:15:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@ngtools/webpack/src/plugin.js:6:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@ngtools/webpack/src/index.js:6:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/models/webpack-configs/styles.js:7:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/models/webpack-configs/index.js:10:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/models/webpack-config.js:5:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/tasks/serve.js:11:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.run (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/commands/serve.js:94:52)
    at Class.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/Users/k26686/.npm-packages/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! feb25@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feb25@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the feb25 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs feb25
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls feb25
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/k26686/aniruddh/develop/ng2cli/feb25/npm-debug.log
C02NM7DYG3QD:feb25 k26686$ ng serve
Cannot read property 'Private' of undefined
TypeError: Cannot read property 'Private' of undefined
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/tsickle/build/src/tsickle.js:111:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/src/main.js:11:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/node_modules/@angular/tsc-wrapped/index.js:14:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/src/compiler_host.js:14:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/src/codegen.js:15:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/compiler-cli/index.js:15:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@ngtools/webpack/src/plugin.js:6:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@ngtools/webpack/src/index.js:6:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/models/webpack-configs/styles.js:7:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/models/webpack-configs/index.js:10:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/models/webpack-config.js:5:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/tasks/serve.js:11:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.run (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/commands/serve.js:94:52)
    at Class.<anonymous> (/Users/k26686/aniruddh/develop/ng2cli/feb25/node_modules/@angular/cli/ember-cli/lib/models/command.js:134:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
C02NM7DYG3QD:feb25 k26686$

**Comment by DzmitryShylovich** [comment]
You need to generate new project using `--ng4` flag:
```
using ng new appname --ng4
```

**Comment by naveedahmed1** [comment]
@DzmitryShylovich solution should fix the issue. I would also suggest updating to the latest release of angular-cli.

**Comment by Toxicable** [comment]
While that flag should fix it, the reason for this issue is that you havn't upgraded your TypeScript to version 2.1.x

**Comment by robwormald** [comment]
upgrade your version of Typescript. Closing.

**Comment by aniruddhadas9** [comment]
@Toxicable @robwormald By upgrading from Typescript `~2.0.0` to `~2.1.0` resolved my issue. thanks :)
@DzmitryShylovich actually I was upgrading my existing app from `2.x.x.` to `4.0.0-rc1` but did not try a new project creation with `--ng4`. @naveedahmed1 I am using the latest version of cli `1.0.0-rc0` and upgraded `angular 2.x.x to 4.0.0-rc1` directly changing the version in package.json.

**Comment by naveedahmed1** [comment]
@aniruddhadas9 I believe with --ng4 you dont need to update package.json manually.

**Comment by aniruddhadas9** [comment]
@naveedahmed1 true. I am upgrading my developed application. Its not a new application I am creating.
