### ISSUE TITLE
Ungular Universal Cli / Error: Zone.js has detected that ZoneAwarePromise

### ISSUE THREAD

**Issue by kamalkech** [angular/angular#14746]
** I use Ungular Universal Cli

**OS
Windows 10

**What is the motivation / use case for changing the behavior?**
After Use Http service to get data from API (express)

**Angular version:** 2.0.X
universal-cli: 1.0.0-alpha.universal.3
angular-cli: 1.0.0-beta.23
node: 6.10.0
os: win32 x64

** Error Message : 
`
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.Zone.assertZonePatched (C:\Projets\Angular\ung-universal\node_modules\zone.js\dist\zone-node.js:38:23)
    at new NgZone (C:\Projets\Angular\ung-universal\node_modules\@angular\core\bundles\core.umd.js:5832:18)
    at PlatformRef_._bootstrapModuleFactoryWithZone (C:\Projets\Angular\ung-universal\node_modules\@angular\core\bundles\core.umd.js:6412:26)
    at PlatformRef_.bootstrapModuleFactory (C:\Projets\Angular\ung-universal\node_modules\@angular\core\bundles\core.umd.js:6403:25)
    at C:\Projets\Angular\ung-universal\node_modules\angular2-platform-node\node-platform.js:440:38
    at tryCatcher (C:\Projets\Angular\ung-universal\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Projets\Angular\ung-universal\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Projets\Angular\ung-universal\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Projets\Angular\ung-universal\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Projets\Angular\ung-universal\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Projets\Angular\ung-universal\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Projets\Angular\ung-universal\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Projets\Angular\ung-universal\node_modules\bluebird\js\release\async.js:17:14)
    at ZoneDelegate.invokeTask (C:\Projets\Angular\ung-universal\node_modules\zone.js\dist\zone-node.js:265:35)
    at Zone.runTask (C:\Projets\Angular\ung-universal\node_modules\zone.js\dist\zone-node.js:154:47)
    at Immediate.ZoneTask.invoke (C:\Projets\Angular\ung-universal\node_modules\zone.js\dist\zone-node.js:335:33)
    at Immediate.data.args.(anonymous function) (C:\Projets\Angular\ung-universal\node_modules\zone.js\dist\zone-node.js:954:25)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
`

I am tired to found solution, any idea plz ?

**Comment by DzmitryShylovich** [comment]
some 3rd party lib overrides native `Promise` impl

**Comment by IgorMinar** [comment]
yeah. please check what is overriding the window.Promise or global.Promise. There is not much we can do about this. sorry.
