### ISSUE TITLE
[ng2] Get all components in the ComponentFactory

### ISSUE THREAD

**Issue by DenisValcke** [angular/angular#14758]
Hi

So I was trying to create a module which would take a bunch of components and load them dynamically but without messing with AoT. This has proven a challenge but I'm getting really close except for one thing. How do I retrieve all the components which are stored in the ComponentFactory?

In mij `app.module.ts` I pass an array of components to the forRoot() of my dynamic-load module:
```javascript
imports: [
  DynamicLoadModule.forRoot(dynamicComponents),
]
```

In my `dynamic-load.module.ts` I add all of them to the Angular2 ComponentFactory:
```javascript
static forRoot(components: any[]) {
        return {
            ngModule: DynamicLoadModule,
            providers: [{
                provide: ANALYZE_FOR_ENTRY_COMPONENTS,
                useValue: components,
                multi: true,
            }, {
                provide: DynamicLoadService,
                useValue: new DynamicLoadService(components)
            }]
        };
    }
```

Now the problem lies in the `DynamicLoadService`, which is messing with AoT. I've tried the documented export-a-function way but this doesn't solve the problem because this way I'm unable to pass the `components` as parameters to the service. So the following found in [the Angular documentation](https://angular.io/docs/ts/latest/guide/dependency-injection.html) is not providing a solution for my problem: 
```javascript
let heroServiceFactory = (logger: Logger, userService: UserService) => {
  return new HeroService(logger, userService.user.isAuthorized);
};

export let heroServiceProvider =
  { provide: HeroService,
    useFactory: heroServiceFactory,
    deps: [Logger, UserService]
  };
```

So then I tried passing the components to my `dynamic-load.module` by the use of `OpaqueToken`, which was also of no help because I then had uncompiled components at best and my module lost a lot of flexibilty.

So I came to the conclusion that, if I needed an array of all the components in the `ComponentFactory`, I just need a way to retrieve them all.  
So, where I now use the `ComponentFactoryResolver` to get one template based on the name I need to get them all, or at least get all the names of the components in the factory.

```javascript
if (selectedComponent !== '') {
  if (typeof this.currentComponent !== 'undefined') { this.currentComponent.destroy(); }

  const   components = this.dynamicLoadService.getComponents(), // --> instead of getting a list of available components through this service which needs the factory that blocks AoT, I should just be able to retrieve all available components from the ComponentFactory
          component: any = components.find((x) => x.name.toLowerCase().indexOf(selectedComponent) > -1),
          compFactory = this.cfr.resolveComponentFactory(component);

  this.currentComponent = this.vcr.createComponent(compFactory);
  this.currentComponent.instance.data = this.componentData;
}
```

**Comment by DzmitryShylovich** [comment]
```
export function heroServiceFactory(logger: Logger, userService: UserService) {
  return new HeroService(logger, userService.user.isAuthorized);
};

export let heroServiceProvider =
  { provide: HeroService,
    useFactory: heroServiceFactory,
    deps: [Logger, UserService]
  };
```

**Comment by DenisValcke** [comment]
@DzmitryShylovich I don't really understand what you're trying to explain by this?

**Comment by DzmitryShylovich** [comment]
this is what is called `exported function` in documentation

**Comment by DenisValcke** [comment]
Yes I know but, as I mentioned, I wasn't able to use that as an option since I'm not able to pass my components as arguments to the service. I only seem to be able to do that in the following ways (which don't work well with AoT):
```javascript
  provide: DynamicLoadService,
  useValue: new DynamicLoadService(components)
```

```javascript
  provide: DynamicLoadService,
  useFactory: ()=> new DynamicLoadService(components)
```

This is how it currently looks like:
```javascript
    static forRoot(components: any[]) {
        return {
            ngModule: DynamicLoadModule,
            providers: [{
                provide: ANALYZE_FOR_ENTRY_COMPONENTS,
                useValue: components,
                multi: true,
            }, {
                provide: DynamicLoadService,
                useFactory: ()=> new DynamicLoadService(components)
            }]
        };
    }
```

**Comment by DzmitryShylovich** [comment]
Just inject `ANALYZE_FOR_ENTRY_COMPONENTS` into `DynamicLoadService`
or
```
{ provide: DynamicLoadService, useFactory: factory, deps: [new Inject(ANALYZE_FOR_ENTRY_COMPONENTS)] }

export function factory(cmps) {
    return new DynamicLoadService(cmps);
}
```

**Comment by DenisValcke** [comment]
@DzmitryShylovich That actually solved it for me, such a simple solution. Thanks a lot for the input!

**Comment by DenisValcke** [comment]
Ok, I might have cheered a little to soon. I now have the following, based on your suggestion @DzmitryShylovich:

```javascript
import {NgModule, ANALYZE_FOR_ENTRY_COMPONENTS, Inject} from '@angular/core';
import { DynamicLoadService } from './dynamic-load.service';

import { DynamicLoadComponent } from './dynamic-load.component';

export function DynamicLoadFactory(cmps) {
    return new DynamicLoadService(cmps);
}

@NgModule({
    declarations: [
        DynamicLoadComponent
    ],
    exports: [
        DynamicLoadComponent
    ]
})
export class DynamicLoadModule {
    static forRoot(components: any[]) {
        const test = {
            ngModule: DynamicLoadModule,
            providers: [{
                provide: ANALYZE_FOR_ENTRY_COMPONENTS,
                useValue: components,
                multi: true,
            },
            {
                provide: DynamicLoadService,
                useFactory: DynamicLoadFactory,
                deps: [[new Inject(ANALYZE_FOR_ENTRY_COMPONENTS)]]
            }]
        };
        return test;
    }
}
```

But I get the following error in my console:
```
EXCEPTION: Uncaught (in promise): Error: Error in ./DataComponent class DataComponent - inline template:0:0 caused by: No provider for Token AnalyzeForEntryComponents!
Error: Error in ./DataComponent class DataComponent - inline template:0:0 caused by: No provider for Token AnalyzeForEntryComponents!
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3340:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:30581:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:30646:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:63825:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:90126:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.create (http://localhost:4200/vendor.bundle.js:90026:18)
    at CompiledTemplate.proxyViewClass.View_DataComponent_Host0.createInternal (/AppModule/DataComponent/host.ngfactory.js:16:19)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:89584:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:90040:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:45201:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:64472:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:76063:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:25313:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:25280:26)
    at http://localhost:4200/vendor.bundle.js:25216:58
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.797.ZoneDelegate.handleError @ zone.js:334
webpackJsonp.797.Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
ZoneTask.invoke @ zone.js:420
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.797.ZoneDelegate.handleError @ zone.js:334
webpackJsonp.797.Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
ZoneTask.invoke @ zone.js:420
error_handler.js:60 Error: Uncaught (in promise): Error: Error in ./DataComponent class DataComponent - inline template:0:0 caused by: No provider for Token AnalyzeForEntryComponents!
Error: Error in ./DataComponent class DataComponent - inline template:0:0 caused by: No provider for Token AnalyzeForEntryComponents!
    at ViewWrappedError.ZoneAwareError (zone.js:958)
    at ViewWrappedError.BaseError [as constructor] (errors.js:22)
    at ViewWrappedError.WrappedError [as constructor] (errors.js:87)
    at new ViewWrappedError (errors.js:77)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (view.js:650)
    at CompiledTemplate.proxyViewClass.DebugAppView.create (view.js:550)
    at CompiledTemplate.proxyViewClass.View_DataComponent_Host0.createInternal (/AppModule/DataComponent/host.ngfactory.js:16)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (view.js:108)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (view.js:564)
    at ComponentFactory.create (component_factory.js:202)
    at ViewContainerRef_.createComponent (view_container_ref.js:233)
    at RouterOutlet.activate (router_outlet.js:155)
    at ActivateRoutes.placeComponentIntoOutlet (router.js:1348)
    at ActivateRoutes.activateRoutes (router.js:1315)
    at router.js:1251
    at resolvePromise (zone.js:643) [angular]
    at resolvePromise (zone.js:619) [angular]
    at polyfills.bundle.js:3061:17 [angular]
    at Object.onInvokeTask (ng_zone.js:264) [angular]
    at ZoneDelegate.webpackJsonp.797.ZoneDelegate.invokeTask (zone.js:362) [angular]
    at Zone.webpackJsonp.797.Zone.runTask (zone.js:166) [<root> => angular]
    at drainMicroTaskQueue (zone.js:529) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (zone.js:420) [<root>]
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.797.ZoneDelegate.handleError @ zone.js:334
webpackJsonp.797.Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
ZoneTask.invoke @ zone.js:420
zone.js:516 Unhandled Promise rejection: Error in ./DataComponent class DataComponent - inline template:0:0 caused by: No provider for Token AnalyzeForEntryComponents! ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedError {__zone_symbol__error: Error: Error in ./DataComponent class DataComponent - inline template:0:0 caused by: No provider for…, _nativeError: ZoneAwareError, originalError: NoProviderError, context: DebugContext, __zone_symbol__stack: "Error: Error in ./DataComponent class DataComponen…t http://localhost:4200/vendor.bundle.js:25216:58"…} Error: Error in ./DataComponent class DataComponent - inline template:0:0 caused by: No provider for Token AnalyzeForEntryComponents!
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3340:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:30581:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:30646:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:63825:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:90126:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.create (http://localhost:4200/vendor.bundle.js:90026:18)
    at CompiledTemplate.proxyViewClass.View_DataComponent_Host0.createInternal (/AppModule/DataComponent/host.ngfactory.js:16:19)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:89584:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:90040:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:45201:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:64472:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:76063:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:25313:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:25280:26)
    at http://localhost:4200/vendor.bundle.js:25216:58
```

**Comment by alexzuza** [comment]
`ANALYZE_FOR_ENTRY_COMPONENTS` is not part of dependency injection tree
```
if (providerMeta.token === resolveIdentifier(Identifiers.ANALYZE_FOR_ENTRY_COMPONENTS)) {
   targetEntryComponents.push(...this._getEntryComponentsFromProvider(providerMeta, type));
} else {
   compileProviders.push(this.getProviderMetadata(providerMeta));
}
```
https://github.com/angular/angular/blob/2.4.8/modules/%40angular/compiler/src/metadata_resolver.ts#L805-L809
You can try to use the following configuration

```
export class DynamicLoadModule {
    static forRoot(components: any[]) {
        const test = {
            ngModule: DynamicLoadModule,
            providers: [{
                provide: ANALYZE_FOR_ENTRY_COMPONENTS,
                useValue: components,
                multi: true,
            },
            {
                provide: DynamicLoadService,
                useValue: new DynamicLoadService(components)
            }]
        };
        return test;
    }
}
```

**Comment by DenisValcke** [comment]
@alexzuza This works, thanks, but again seems to screw up AoT according to angular-cli (which again is throwing the "Calling function 'DynamicLoadModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function" error)

**Comment by gustavoq-infocorp** [comment]
@DenisValcke could you share the full working code ?
