### ISSUE TITLE
Compiler Error in 2.4.3

### ISSUE THREAD

**Issue by lcurrens** [angular/angular#14875]
**I'm submitting a ...**  (check one with "x")
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Current behavior**
Using the following HTML an error occurs:

 ` <h1>Angular 2.4.3 compiler error </h1>
    <div *ngIf="test">
       <div *ngIf(!isTest2())>  <!-- THIS DIV IS CAUSING AN ERROR -->
          <div>
              <h2>HELLO </h2>
          </div>
      </div>
      </div>`

Here is the error:
Unhandled Promise rejection: Template parse errors:
TypeError: Cannot read property 'toUpperCase' of undefined 
`("
  <h1>Angular 2.4.3 compiler error </h1>
    <div *ngIf="test">
       <div [ERROR ->]*ngIf(!isTest2())>  <!-- THIS DIV IS CAUSING AN ERROR-->
          <div>
         "): AppComponent@4:12 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError Error: Template parse errors:

TypeError: Cannot read property 'toUpperCase' of undefined ("
  <h1>Angular 2.4.3 compiler error </h1>
    <div *ngIf="test">
       <div [ERROR ->]*ngIf(!isTest2())>  <!-- THIS DIV IS CAUSING AN ERROR, because of *ngIf -->
          <div>
         "): AppComponent@4:12
    at SyntaxError.ZoneAwareError (http://localhost:3000/node_modules/zone.js/dist/zone.js:958:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1590:18)
    at new SyntaxError (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:1793:18)
    at TemplateParser.parse (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:11210:21)
    at JitCompiler._compileTemplate (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27480:70)
    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27363:64)
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27363:21)
    at createResult (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:27246:21)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:330:26)
    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:126:43)
    at http://localhost:3000/node_modules/zone.js/dist/zone.js:679:57
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:363:31)
    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:166:47)
    at drainMicroTaskQueue (http://localhost:3000/node_modules/zone.js/dist/zone.js:529:35)
`
**Expected behavior**
The HTML would should work with no error, as it does in 2.4.2.  This error begins in 2.4.3.  I do see information on BREAKING CHANGES (not mentioned until 2.0.0-rc.4 - but this happens starting in 2.4.3): 
"BREAKING CHANGES: Previously multiple template bindings on one element (ex.` <div *ngIf='..' *ngFor='...'>`) were allowed but most of the time were leading to undesired result. It is possible that a small number of applications will see template parse errors that should be fixed by nesting elements or using <template> tags explicitly."

HOWEVER- I am not using multiple template bindings in one element, I am using nested elements with template bindings, and it is still breaking.

**Minimal reproduction of the problem with instructions**
app.component.ts:
----------------------------------------------------------------------------
`import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app/app.component.html',
  styleUrls: ['./app/app.component.css']
})
export class AppComponent {
   test: boolean;
   test2: boolean;

   isTest2(): boolean {
     return this.test2;
   }
}`
----------------------------------------------------------------------------
app.component.html:
`  <h1>Angular 2.4.3 compiler error </h1>
  <div *ngIf="test">
       <div *ngIf(!isTest2())>  <!-- THIS DIV IS CAUSING AN ERROR -->
           <div>
               <h2>HELLO </h2>
           </div>
       </div>
   </div>`
------------------------------------------------------------------------------
**What is the motivation / use case for changing the behavior?**
This was working up until 2.4.2.  I have a need to test for multiple different conditions within an initial condition test, using *ngIf
For example:
if A
   if B <some html>
   if C <some html>
   if !C <some other html>
end if A

**Please tell us about your environment:**
<!-- Operating system, IDE, package manager, HTTP server, ... -->
Windows 7 64 bit, Atom, TSC, NPM, lite-server

* **Angular version:** 2.4.3, and up to latest version of 2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Only tested on Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
`

**Comment by DzmitryShylovich** [comment]
please add a plunkr

**Comment by lcurrens** [comment]
I will try to add a plunker - how do I get the text in this to be plaintext, I can't get rid of the html formatting...?

**Comment by DzmitryShylovich** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by lcurrens** [comment]
http://plnkr.co/edit/QIm3KxVdNGS9r7jsyjq3?p=preview

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/3iT2zZ8Zr3VtUsEa7cSo?p=preview

**Comment by lcurrens** [comment]
Thanks DzmitryShylovich, can you please explain?

**Comment by lcurrens** [comment]
OK please take a look again, I fixed my plunker and I am now getting the error that I mention in this issue:
http://plnkr.co/edit/QIm3KxVdNGS9r7jsyjq3?p=preview

**Comment by DzmitryShylovich** [comment]
> *ngIf(!isTest2())

this is incorrect syntax. did you read documentation? https://angular.io/docs/ts/latest/guide/template-syntax.html#!#ngIf

**Comment by lcurrens** [comment]
Ah, thank you - I did not see that.  It was working up until 2.4.3, so I did not expect that this would have stopped working, I wasn't looking for that.  Thanks for your help.

   `<div *ngIf(!isTest2())>     vs    <div *ngIf="!isTest2()"> `
