### ISSUE TITLE
bug(platform-server): @HostListener('window') doesn't work

### ISSUE THREAD

**Issue by FrozenPandaz** [angular/angular#15000]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Adding
```ts
  @HostListener('window:scroll')
  track() {
    console.log('scroll');
  }
```

will give this error
```sh
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property '_eventListenersMap' of undefined
TypeError: Cannot read property '_eventListenersMap' of undefined
    at Parse5DomAdapter.on (/Users/jjean/projects/ng-universal-demo/dist/server.js:35214:50)
    at Parse5DomAdapter.onAndCancel (/Users/jjean/projects/ng-universal-demo/dist/server.js:35232:18)
    at /Users/jjean/projects/ng-universal-demo/dist/server.js:36952:124
    at ZoneDelegate.invoke (/Users/jjean/projects/ng-universal-demo/dist/server.js:52558:26)
    at Zone.run (/Users/jjean/projects/ng-universal-demo/dist/server.js:52354:43)
    at NgZone.runOutsideAngular (/Users/jjean/projects/ng-universal-demo/dist/server.js:5339:31)
    at DefaultServerRendererV2.listen (/Users/jjean/projects/ng-universal-demo/dist/server.js:36951:32)
    at listenToElementOutputs (/Users/jjean/projects/ng-universal-demo/dist/server.js:11517:64)
    at createViewNodes (/Users/jjean/projects/ng-universal-demo/dist/server.js:14122:17)
    at createRootView (/Users/jjean/projects/ng-universal-demo/dist/server.js:14057:5)
    at Object.createProdRootView [as createRootView] (/Users/jjean/projects/ng-universal-demo/dist/server.js:14613:12)
    at ComponentFactory_.create (/Users/jjean/projects/ng-universal-demo/dist/server.js:11906:49)
    at ViewContainerRef_.createComponent (/Users/jjean/projects/ng-universal-demo/dist/server.js:12100:65)
    at RouterOutlet.activate (/Users/jjean/projects/ng-universal-demo/dist/server.js:60073:44)
    at ActivateRoutes.placeComponentIntoOutlet (/Users/jjean/projects/ng-universal-demo/dist/server.js:59266:20)
ORIGINAL STACKTRACE:
Error: Uncaught (in promise): TypeError: Cannot read property '_eventListenersMap' of undefined
TypeError: Cannot read property '_eventListenersMap' of undefined
    at Parse5DomAdapter.on (/Users/jjean/projects/ng-universal-demo/dist/server.js:35214:50)
    at Parse5DomAdapter.onAndCancel (/Users/jjean/projects/ng-universal-demo/dist/server.js:35232:18)
    at /Users/jjean/projects/ng-universal-demo/dist/server.js:36952:124
    at ZoneDelegate.invoke (/Users/jjean/projects/ng-universal-demo/dist/server.js:52558:26)
    at Zone.run (/Users/jjean/projects/ng-universal-demo/dist/server.js:52354:43)
    at NgZone.runOutsideAngular (/Users/jjean/projects/ng-universal-demo/dist/server.js:5339:31)
    at DefaultServerRendererV2.listen (/Users/jjean/projects/ng-universal-demo/dist/server.js:36951:32)
    at listenToElementOutputs (/Users/jjean/projects/ng-universal-demo/dist/server.js:11517:64)
    at createViewNodes (/Users/jjean/projects/ng-universal-demo/dist/server.js:14122:17)
    at createRootView (/Users/jjean/projects/ng-universal-demo/dist/server.js:14057:5)
    at Object.createProdRootView [as createRootView] (/Users/jjean/projects/ng-universal-demo/dist/server.js:14613:12)
    at ComponentFactory_.create (/Users/jjean/projects/ng-universal-demo/dist/server.js:11906:49)
    at ViewContainerRef_.createComponent (/Users/jjean/projects/ng-universal-demo/dist/server.js:12100:65)
    at RouterOutlet.activate (/Users/jjean/projects/ng-universal-demo/dist/server.js:60073:44)
    at ActivateRoutes.placeComponentIntoOutlet (/Users/jjean/projects/ng-universal-demo/dist/server.js:59266:20)
    at new Error (native)
    at resolvePromise (/Users/jjean/projects/ng-universal-demo/dist/server.js:52871:31) [angular]
    at resolvePromise (/Users/jjean/projects/ng-universal-demo/dist/server.js:52847:17) [angular]
    at /Users/jjean/projects/ng-universal-demo/dist/server.js:52907:17 [angular]
    at Object.onInvokeTask (/Users/jjean/projects/ng-universal-demo/dist/server.js:5388:41) [angular]
    at ZoneDelegate.invokeTask (/Users/jjean/projects/ng-universal-demo/dist/server.js:52590:36) [angular]
    at Zone.runTask (/Users/jjean/projects/ng-universal-demo/dist/server.js:52394:47) [<root> => angular]
    at drainMicroTaskQueue (/Users/jjean/projects/ng-universal-demo/dist/server.js:52757:35) [<root>]
    at ZoneTask.invoke (/Users/jjean/projects/ng-universal-demo/dist/server.js:52648:25) [<root>]
    at data.args.(anonymous function) (/Users/jjean/projects/ng-universal-demo/dist/server.js:53676:25) [<root>]
    at FSReqWrap.oncomplete (fs.js:123:15) [<root>]
```

**Expected behavior**
It should fail gracefully by doing nothing

**Minimal reproduction of the problem with instructions**
https://github.com/FrozenPandaz/ng-universal-demo/tree/host
```sh
npm install && npm start
```

**What is the motivation / use case for changing the behavior?**
Server should gracefully fail for things that it does not support

**Please tell us about your environment:**
Node 6.9+

* **Angular version:** 2.0.X
4.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Node
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by FrozenPandaz** [comment]
https://github.com/angular/angular/blob/master/modules/%40angular/platform-server/src/parse5_adapter.ts#L554

Will try to get the _window but that does not exist when one is being parsed in

https://github.com/angular/angular/blob/master/modules/%40angular/platform-server/src/parse5_adapter.ts#L33

I think the way parsed documents are brought in is not as complete as we think it is.

We should either make it more complete upon parsing or not make the assumptions we are making.

I can take a look at this
