### ISSUE TITLE
QueryList fails to look up Directives where a PreBuiltObjets is injected

### ISSUE THREAD

**Issue by mlaval** [angular/angular#1507]
To reproduce this issue, just modify the last sample from `query_integration_spec.js` by injecting a prebuilt object in the constructor of the `TextDirective` decorator. For example:
```
class TextDirective {
  text: string;
  constructor(el: NgElement) {}
}
```

As a result, running the unit tests raises the following error:
```
Uncaught (in promise) TypeError: Cannot read property 'element' of null
    at ElementInjector.execute.$__export._getPreBuiltObjectByKeyId (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:1048:43)
    at ElementInjector.execute.$__export._getByKey (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:1011:36)
    at ElementInjector.execute.$__export._getByDependency (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:809:25)
    at ElementInjector.execute.$__export._new (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:742:38)
    at ElementInjector.execute.$__export._getDirectiveByKeyId (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:1060:35)
    at ElementInjector.execute.$__export.hasDirective (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:688:44)
    at QueryRef.execute.QueryRef.visit (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:1271:21)
    at QueryRef.execute.QueryRef.visit (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:1276:20)
    at QueryRef.execute.QueryRef.visit (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:1276:20)
    at QueryRef.execute.QueryRef.update (http://localhost:9876/base/modules/angular2/src/core/compiler/element_injector.js:1264:18)
```

In `ViewContainer.create()`, it is said that:
> insertion must come before hydration so that element injector trees are attached  

As a consequence, the injector's prebuilt objects are not yet created, hence the error.

**Comment by naomiblack** [comment]
@mlaval are you blocked by this? Should fix, but moving to M9 as less urgent, unless it is blocking....

**Comment by mlaval** [comment]
I'm not blocked, it is not urgent for me.

**Comment by mlaval** [comment]
I can't reproduce it anymore.
