### ISSUE TITLE
Upgrading to rc.4 Cannot convert undefined or null to object at Function.keys (<anonymous>)

### ISSUE THREAD

**Issue by gregbown** [angular/angular#15250]
I'm submitting a bug as I am unable to track it down or isolate the cause.
I can't update from 4.0.0 rc3 to rc4 without getting a runtime Error-> Uncaught TypeError: Cannot convert undefined or null to object. at Function.keys (<anonymous>)

Starts at the following function...
```
function(t, e, n) {
	"use strict";
	function r(t) {
		for (var e = Object.keys(t), n = {}, r = 0; r < e.length; r++) {
			var o = e[r];
			"function" == typeof t[o] && (n[o] = t[o])
		}
		var i = Object.keys(n);
		return function(t, e) {
			void 0 === t && (t = {});
			for (var r = !1, o = {}, s = 0; s < i.length; s++) {
				var a = i[s]
				  , u = n[a]
				  , c = t[a]
				  , l = u(c, e);
				o[a] = l,
				r = r || l !== c
			}
			return r ? o : t
		}
	}
	e.a = r
}
```
The last line before it throws is t.state !== b && t.state !== E && (t.type == P || t.data && t.data.isPeriodic ? It appears t.data.isPeriodic is undefined in this method.
```
finally {
	t.state !== b && t.state !== E && (t.type == P || t.data && t.data.isPeriodic ? r && t._transitionTo(w, _) : (t.runCount = 0,
	this._updateTaskCount(t, -1),
	r && t._transitionTo(b, _, b))),
	N = N.parent,
	z = i
}
```
STEPS TO REPRODUCE
If I had something more meaningful to track it down other than changing 3 to 4

**Please tell us about your environment:**
Windows 10, Typescript 2.2.1, Webpack 2.2.1, Angular 4.0.0-rc.3 attempting change to rc.4
Also using ngrx store 2.2.1 w effects 2.0.0
Occurs in all browsers, developing in chrome

Thank you,  Any advice, hunches or direction appreciated.
Greg

**Comment by DzmitryShylovich** [comment]
Please add reproduction

**Comment by gregbown** [comment]
@DzmitryShylovich I don't work with plnkr much.  Would you have a link to one set up to rc3 or rc4

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/lU32vBJY9KYXZUTW7GQQ?p=preview

**Comment by fulls1z3** [comment]
Having more or less a fatal error using ngrx 2.2.1. Gonna work on a repro early next week, but hereby sharing the error message if it helps.

Environment:

- Windows 10
- Typescript 2.2.1
- Webpack 2.2.1
- Angular 4.0.0-rc.3 attempting change to rc.5

- ngrx store 2.2.1
- ngrx effects 2.0.0

- all browsers


```
Unhandled Promise rejection: Cannot convert undefined or null to object ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at combineReducers (utils.js:4)
    at _initialReducerFactory (ng2.js:33)
    at AppModuleInjector.get (module.ngfactory.js:1)
    at AppModuleInjector.getInternal (module.ngfactory.js:1)
    at AppModuleInjector.NgModuleInjector.get (core.es5.js:3538)
    at _createReducerIfExtension (instrument.js:58)
    at AppModuleInjector.createInternal (module.ngfactory.js:1)
    at AppModuleInjector.NgModuleInjector.create (core.es5.js:3519)
    at NgModuleFactory.create (core.es5.js:3492)
    at core.es5.js:4688
    at ZoneDelegate.invoke (zone.js:365)
    at Object.onInvoke (core.es5.js:4079)
    at ZoneDelegate.invoke (zone.js:364)
    at Zone.run (zone.js:125)
    at NgZone.run (core.es5.js:3948)
    at PlatformRef_._bootstrapModuleFactoryWithZone (core.es5.js:4686)
    at core.es5.js:4728
    at ZoneDelegate.invoke (zone.js:365)
    at Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.invokeTask (zone.js:398)
    at Zone.runTask (zone.js:165)
    at drainMicroTaskQueue (zone.js:593) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at combineReducers (http://localhost:1337/assets/vendor.dll.js:63011:30)
    at _initialReducerFactory (http://localhost:1337/assets/vendor.dll.js:111202:90)
    at AppModuleInjector.get (ng:///AppModule/module.ngfactory.js:144:105)
    at AppModuleInjector.getInternal (ng:///AppModule/module.ngfactory.js:447:71)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:1337/assets/vendor.dll.js:3758:44)
    at _createReducerIfExtension (http://localhost:1337/assets/vendor.bundle.js:485:32)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:323:22)
    at AppModuleInjector.NgModuleInjector.create (http://localhost:1337/assets/vendor.dll.js:3739:76)
    at NgModuleFactory.create (http://localhost:1337/assets/vendor.dll.js:3712:18)
    at http://localhost:1337/assets/vendor.dll.js:4908:61
    at ZoneDelegate.invoke (http://localhost:1337/assets/polyfills.dll.js:4298:26)
    at Object.onInvoke (http://localhost:1337/assets/vendor.dll.js:4299:37)
    at ZoneDelegate.invoke (http://localhost:1337/assets/polyfills.dll.js:4297:32)
    at Zone.run (http://localhost:1337/assets/polyfills.dll.js:4058:43)
    at NgZone.run (http://localhost:1337/assets/vendor.dll.js:4168:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:1337/assets/vendor.dll.js:4906:23)
    at http://localhost:1337/assets/vendor.dll.js:4948:59
    at ZoneDelegate.invoke (http://localhost:1337/assets/polyfills.dll.js:4298:26)
    at Zone.run (http://localhost:1337/assets/polyfills.dll.js:4058:43)
    at http://localhost:1337/assets/polyfills.dll.js:4693:57
    at ZoneDelegate.invokeTask (http://localhost:1337/assets/polyfills.dll.js:4331:31)
    at Zone.runTask (http://localhost:1337/assets/polyfills.dll.js:4098:47)
    at drainMicroTaskQueue (http://localhost:1337/assets/polyfills.dll.js:4526:35)
```

**Comment by zygimantas** [comment]
You can temporary remove StoreDevtoolsModule

**Comment by fulls1z3** [comment]
Thanks dude, it worked like a charm 👍

**Comment by gregbown** [comment]
Thank you!!! @zygimantas Yes, that is the culprit.  Also thank you @DzmitryShylovich, going through the process of trying to reproduce the issue with plnkr is excellent practice, or should I say best practice.

I am closing this issue as I am able to build jit and aot with 4 rc5. Maybe it is just an issue with the ngrx StoreDevToolsModule
