### ISSUE TITLE
Angular RC3: window object is not defined in universal when external libraries are imported.

### ISSUE THREAD

**Issue by robertdumitrescu** [angular/angular#15261]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I tried to include angular2-chartjs plugin in an angular universal application in an lazy component. The thing is that the plugin requires the window object to be defined in order to work. Because on server is not defined I'm getting a lot of errors. Also I saw that the error occures not when I try to render the components, but when I am trying to attach the ChartComponent with @ViewChild.

Is there any way in which I can declare  @ViewChild just when I am in the browser? I tried several approaches with 

`  constructor(
    @Inject(PLATFORM_ID) platformId: string
  ) {
    this.isBrowser = isPlatformBrowser(platformId);

  }`

but with no result. 

P.S. The errors that I am receiving

`EXCEPTION: Uncaught (in promise): ReferenceError: window is not defined
ReferenceError: window is not defined
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18965:10
    at exports.modules.Array.concat.module.exports (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18973:3)
    at Object.exports.modules.Array.concat.module.exports.Chart.Bar.config.type (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14882:25)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14842:1)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14870:10)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:12:75)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:50873:10
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52783:26)
    at Object.onInvoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:4501:37)
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52782:32)
    at Zone.run (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52576:43)
ORIGINAL STACKTRACE:
Error: Uncaught (in promise): ReferenceError: window is not defined
ReferenceError: window is not defined
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18965:10
    at exports.modules.Array.concat.module.exports (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18973:3)
    at Object.exports.modules.Array.concat.module.exports.Chart.Bar.config.type (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14882:25)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14842:1)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14870:10)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:12:75)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:50873:10
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52783:26)
    at Object.onInvoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:4501:37)
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52782:32)
    at Zone.run (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52576:43)
    at resolvePromise (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:53114:31) [angular]
    at resolvePromise (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:53085:17) [angular]
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:53162:17 [angular]
    at Object.onInvokeTask (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:4492:37) [angular]
    at ZoneDelegate.invokeTask (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52815:36) [angular]
    at Zone.runTask (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52616:47) [<root> => angular]
    at drainMicroTaskQueue (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52995:35) [<root>]
    at ZoneTask.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52873:25) [<root>]
    at data.args.(anonymous function) (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:53968:25) [<root>]
    at FSReqWrap.oncomplete (fs.js:114:15) [<root>]
Unhandled Promise rejection: window is not defined ; Zone: angular ; Task: Promise.then ; Value: { ReferenceError: window is not defined
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18965:10
    at exports.modules.Array.concat.module.exports (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18973:3)
    at Object.exports.modules.Array.concat.module.exports.Chart.Bar.config.type (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14882:25)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14842:1)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14870:10)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:12:75)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:50873:10
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52783:26)
    at Object.onInvoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:4501:37)
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52782:32)
    at Zone.run (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52576:43)
  __zone_symbol__currentTask: 
   ZoneTask {
     zone: 
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } } ReferenceError: window is not defined
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18965:10
    at exports.modules.Array.concat.module.exports (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18973:3)
    at Object.exports.modules.Array.concat.module.exports.Chart.Bar.config.type (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14882:25)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14842:1)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14870:10)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:12:75)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:50873:10
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52783:26)
    at Object.onInvoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:4501:37)
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52782:32)
    at Zone.run (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52576:43)
{ Error: Uncaught (in promise): ReferenceError: window is not defined
ReferenceError: window is not defined
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18965:10
    at exports.modules.Array.concat.module.exports (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18973:3)
    at Object.exports.modules.Array.concat.module.exports.Chart.Bar.config.type (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14882:25)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14842:1)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14870:10)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at Object.<anonymous> (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:12:75)
    at __webpack_require__ (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:26:30)
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:50873:10
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52783:26)
    at Object.onInvoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:4501:37)
    at ZoneDelegate.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52782:32)
    at Zone.run (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52576:43)
    at resolvePromise (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:53114:31) [angular]
    at resolvePromise (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:53085:17) [angular]
    at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:53162:17 [angular]
    at Object.onInvokeTask (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:4492:37) [angular]
    at ZoneDelegate.invokeTask (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52815:36) [angular]
    at Zone.runTask (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52616:47) [<root> => angular]
    at drainMicroTaskQueue (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52995:35) [<root>]
    at ZoneTask.invoke (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:52873:25) [<root>]
    at data.args.(anonymous function) (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/server.js:53968:25) [<root>]
    at FSReqWrap.oncomplete (fs.js:114:15) [<root>]
  __zone_symbol__error: 
   { Error: Uncaught (in promise): ReferenceError: window is not defined
   ReferenceError: window is not defined
       at /home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18965:10
       at exports.modules.Array.concat.module.exports (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:18973:3)
       at Object.exports.modules.Array.concat.module.exports.Chart.Bar.config.type (/home/idz/gitRepos/PUBLIC-TOOL-SITE/dist/0.server.js:14882:25)
` 

**Expected behavior**
The external components that are loaded as modules should not break the entire universal applications.

**Minimal reproduction of the problem with instructions**
I think the instructions are clear enough.

**Please tell us about your environment:**

* **Angular version:** 4.0.0 r.c.3

* **Browser:** [all ]
It doesn't fit because is a server problem
 
* **Language:** 

Here is my package.json dependecies

  "dependencies": {
    "@angular/common": "4.0.0-rc.3",
    "@angular/compiler": "4.0.0-rc.3",
    "@angular/core": "4.0.0-rc.3",
    "@angular/forms": "4.0.0-rc.3",
    "@angular/http": "4.0.0-rc.3",
    "@angular/platform-browser": "4.0.0-rc.3",
    "@angular/platform-browser-dynamic": "4.0.0-rc.3",
    "@angular/platform-server": "4.0.0-rc.3",
    "@angular/router": "4.0.0-rc.3",
    "angular2-chartjs": "^0.1.6",
    "express": "^4.15.2",
    "rxjs": "5.2.0",
    "xhr2": "^0.1.4",
    "zone.js": "0.8.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.0.0-rc.3",
    "@ngtools/webpack": "^1.2.12",
    "@types/express": "^4.0.35",
    "html-webpack-plugin": "^2.28.0",
    "@types/node": "7.0.8",
    "script-ext-html-webpack-plugin": "^1.7.1",
    "del": "^2.2.2",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-sync": "^0.1.4",
    "nodemon": "^1.11.0",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.1",
    "typescript": "^2.2.1",
    "webpack": "^2.2.1",
    "webpack-merge": "4.0.0"
  }

* **Node (for AoT issues):** `node --version` = 
Node 7.7.0

**Comment by DzmitryShylovich** [comment]
See https://github.com/angular/angular/issues/15150#issuecomment-286887083

**Comment by robertdumitrescu** [comment]
The problem is that the @ViewChild needs to be at the constructor level or directly as a child of the class, so isPlatformBrowser become useless because I can't use it since the @ViewChild is executed before. 

Is there any other solution?

**Comment by DzmitryShylovich** [comment]
I think it's a lib responsibility to handle this.

**Comment by robertdumitrescu** [comment]
It might be but we need to consider that we are not including just angular components. A lot of projects will include old libraries that are heavy dependent on browser-based objects like "window". Think just about grids(that are most of them based on Jquery), calendars, WysIwYg editors and so on... Angular should provide a mechanism for developers to avoid those kind of problems in univeral rendering case.

**Comment by DzmitryShylovich** [comment]
https://github.com/angular/angular/issues/15150#issuecomment-286887083 :
> We are considering a better solution for this post 4.0.

**Comment by robertdumitrescu** [comment]
Ok, fair point. I will try to hack my way through till then. Thanks!

**Comment by vikerman** [comment]
BTW - Even when we have a full solution we can never support global variables like 'window'. Remember that the server could be handling multiple requests at the same time and you cannot use global variables like document, window. You would have to wrap your legacy code with a wrapper that can be initialized with document/window.
