### ISSUE TITLE
Small router question - extend router

### ISSUE THREAD

**Issue by patrikx3** [angular/angular#15297]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Extend router. Just a small question if it is simple to extend the router? Or do I need a factory in the provider or how?

**Expected behavior**

```ts
import { Compiler, Injector, NgModuleFactoryLoader, Type } from '@angular/core';
import {
    Router as AngularRouter,
    NavigationExtras, UrlSerializer, RouterOutletMap, Routes
} from '@angular/router';

import { Injectable } from '@angular/core';
@Injectable()
export class Router extends AngularRouter  {

    navigateTop(commands: any[], extras?: NavigationExtras): Promise<boolean> {
        window.scrollTo(0, 0);
        return this.navigate(commands, extras);
    }
}

```

Provider is there. With Webpack it compiles.

**Minimal reproduction of the problem with instructions**

It breaks when I load the page.

```bash
Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at validateConfig (eval at <anonymous> (http://localhost:8080/vendor.js:5031:1), <anonymous>:19:48)
    at Router.resetConfig (eval at <anonymous> (http://localhost:8080/vendor.js:775:1), <anonymous>:474:96)
    at Router (eval at <anonymous> (http://localhost:8080/vendor.js:775:1), <anonymous>:385:14)
```

**What is the motivation / use case for changing the behavior?**

Simple extend the router with a ```navigateTop``` function.

**Please tell us about your environment:**

Debian 9, Yarn, all latest.

* **Angular version:** 2.0.X

Current stable.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers. 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =   
Not AOT.

**Comment by patrikx3** [comment]
i can do it besides, but i would need 2 objects, trying to do it with 1 objects (instead of compose, use extends)

**Comment by Toxicable** [comment]
Why are you extending to the router to do this? Why not just scroll to the top on every navigation instead?

**Comment by patrikx3** [comment]
So that i do not have to add every time, just extend the router and use my own router that is build in ```navigateTop```.

**Comment by Toxicable** [comment]
`this.route.events.filter(e => e instanceof NavigationEnd).subscribe(e => //scroll to top)` how is this having to add anything every time?

**Comment by patrikx3** [comment]
So it is not possible to extend?
I am able to extend Http, but I cannot do it with the Router. :(

**Comment by patrikx3** [comment]
just trying to use this:
```ts
 this.router.navigateTop(path);
```

**Comment by DzmitryShylovich** [comment]
@patrikx3 it's not recommended to use inheritance because router constructor can change any time and it will break your code. Better create a wrapper around router:
```
export class MyRouter {
   constroctor(private ngRouter: Router) {}

  navigateTop(commands: any[], extras?: NavigationExtras): Promise<boolean> {
        window.scrollTo(0, 0);
        return this.ngRouter.navigate(commands, extras);
    }
  ...
}
```

**Comment by patrikx3** [comment]
thanks, do you think i should compose instead of extend the http as well?

**Comment by patrikx3** [comment]
same logic, as an interceptor.

**Comment by patrikx3** [comment]
i guess extend is bad idea, composing is better idea.

**Comment by DzmitryShylovich** [comment]
yeap, composition over inheritance

**Comment by patrikx3** [comment]
what do you think using a proxy? it is still more code with  composing, sometimes composing is good, but  not always.

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource support request

**Comment by jasonaden** [comment]
Closing due to inactivity on this issue.
