### ISSUE TITLE
TypeError: Cannot read property 'toJSON' of undefined when sourceMaps set to true

### ISSUE THREAD

**Issue by pderks** [angular/angular#15527]
I'm submitting a:

[x ] bug report
[ ] feature request
[ ] support request

**Current behavior**
Currently when I set sourceMaps to true and mapRoot to "./" in tsconfig.json I receive an error. This does not occur when sourceMaps is set to false and mapRoot is removed.  I receive the following error when running the aot compiler (ngc -p ./src/):

TypeError: Cannot read property 'toJSON' of undefined
at Object.sourceMapGeneratorToConsumer (C:.....\node_modules\tsickle\build\src\source_map_utils.js:65:42)
at TsickleCompilerHost.combineSourceMaps (C:.....\node_modules\tsickle\build\src\tsickle_compiler_host.js:167:74)
at TsickleCompilerHost.writeFile (C:.....\node_modules\tsickle\build\src\tsickle_compiler_host.js:111:28)
at Object.writeFile (C:.....\node_modules\typescript\lib\typescript.js:64240:132)
at Object.writeFile (C:.....\node_modules\typescript\lib\typescript.js:9020:14)
at printSourceFileOrBundle (C:.....\node_modules\typescript\lib\typescript.js:61197:20)
at emitSourceFileOrBundle (C:.....\node_modules\typescript\lib\typescript.js:61155:21)
at Object.forEachEmittedFile (C:.....\node_modules\typescript\lib\typescript.js:8986:17)
at Object.emitFiles (C:.....\node_modules\typescript\lib\typescript.js:61137:12)
at emitWorker (C:.....\node_modules\typescript\lib\typescript.js:64294:33)

Here is my tsconfig.json file for reference:

{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "mapRoot": "./",
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "files": [
    "./app/app.module.ts",
    "./app/shared_modules/shared-components.module.ts",
    "./main.ts"
  ],

  "angularCompilerOptions": {
   "genDir": "aot",
   "entryModule": "app/app.module#AppModule",
   "skipMetadataEmit" : true
 }
}

**Please tell us about your environment:**
@angular/cli: 1.0.0-rc.2
node: 6.10.0
os: win32 x64
@angular/animations: 4.0.0
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/compiler-cli: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/platform-server: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0-rc.2

**Comment by MrTimms** [comment]
I'm seeing this too.

**Comment by angusoid** [comment]
+1

**Comment by alan-agius4** [comment]
any updates regarding this?

**Comment by JoostK** [comment]
Closing this issue as obsolete. From the issue description I don't think this is still an issue today, and without an up-to-date reproduction I can't investigate more. Sorry this was never addressed!
