### ISSUE TITLE
ngc Error when using "new this" inside static method

### ISSUE THREAD

**Issue by colinkahn** [angular/angular#15537]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Upgrading to 4.0.0 ngc now throws the following error when call `new this` inside of a static method of a class:

```
Error: /Users/user/code/ngc-test/src/index.ts:1:1: Error encountered in metadata generated for exported symbol 'Foo':
 /Users/user/code/ngc-test/src/index.ts:3:20: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":2,"character":19}
    at /Users/user/code/ngc-test/node_modules/@angular/tsc-wrapped/src/collector.js:629:27
    at Array.forEach (native)
    at validateMetadata (/Users/user/code/ngc-test/node_modules/@angular/tsc-wrapped/src/collector.js:617:42)
    at MetadataCollector.getMetadata (/Users/user/code/ngc-test/node_modules/@angular/tsc-wrapped/src/collector.js:474:17)
    at MetadataWriterHost.writeMetadata (/Users/user/code/ngc-test/node_modules/@angular/tsc-wrapped/src/compiler_host.js:110:51)
    at MetadataWriterHost._this.writeFile (/Users/user/code/ngc-test/node_modules/@angular/tsc-wrapped/src/compiler_host.js:92:23)
    at Object.
```

**Expected behavior**
This should not throw an error.

**Minimal reproduction of the problem with instructions**
See https://github.com/colinkahn/ngc-test

**What is the motivation / use case for changing the behavior?**
This bug essentially removes this feature from TypeScript.

**Please tell us about your environment:**

* **Angular version:** 4.0.0

* **Browser:** Not browser specific
 
* **Language:** TypeScript 2.2.2

* **Node (for AoT issues):** `node --version` =   7.7.4

**Comment by DzmitryShylovich** [comment]
have you tried it with ts 2.1.1?

**Comment by colinkahn** [comment]
@DzmitryShylovich I get a different error:

```
Error: Metadata emit requires the sourceFiles are passed to WriteFileCallback. Update to TypeScript ^1.9.0-dev
    at MetadataWriterHost._this.writeFile (/Users/user/code/ngc-test/node_modules/@angular/tsc-wrapped/src/compiler_host.js:85:23)
    at Object.writeFile (/Users/user/code/ngc-test/node_modules/typescript/lib/typescript.js:59396:132)
    at Object.writeFile (/Users/user/code/ngc-test/node_modules/typescript/lib/typescript.js:8619:14)
    at printFile (/Users/user/code/ngc-test/node_modules/typescript/lib/typescript.js:56633:20)
    at emitFile (/Users/user/code/ngc-test/node_modules/typescript/lib/typescript.js:56590:21)
    at onSingleFileEmit (/Users/user/code/ngc-test/node_modules/typescript/lib/typescript.js:8526:13)
    at Object.forEachTransformedEmitFile (/Users/user/code/ngc-test/node_modules/typescript/lib/typescript.js:8503:21)
    at Object.emitFiles (/Users/user/code/ngc-test/node_modules/typescript/lib/typescript.js:56573:12)
    at emitWorker (/Users/user/code/ngc-test/node_modules/typescript/lib/typescript.js:59447:33)
    at /Users/user/code/ngc-test/node_modules/typescript/lib/typescript.js:59410:66
Compilation failed
```

**Comment by colinkahn** [comment]
@DzmitryShylovich above comment used 2.1.1, 2.1.6 gives me the same error as 2.2.2.

**Comment by DzmitryShylovich** [comment]
@colinkahn thanks

@chuckjaz looks like ts 2.1-2.2 support is broken. this issue + https://github.com/angular/angular/issues/15502 can you take a look please?

**Comment by chuckjaz** [comment]
@colinkahn The original issue is an intentional change and we consider this expected behavior.

With `strictMetadataEmit` true it will report whenever you generate metadata that will produce an error if used inside decorations. We extended that to report error for macro functions in `4.0.0`.

To work around this, you have a couple  options.
1) Turn off `strictMetadataEmit`. This is not necessary for correct behavior, only for early errors that might only be caught by a library user.
2) Change `create()` to not qualify as a macro function. For example, if you rewrote this to
```ts
export class Foo {
    static create() {
        let result = new this();
        return result;
    }
}
```
it would not produce an early error.

@DzmitryShylovich can you report a separate error for the error you are encountering?
