### ISSUE TITLE
Angular2 project not working after installing @angular/animation

### ISSUE THREAD

**Issue by marianharbist** [angular/angular#15773]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The app doesnt work and in browser its showing a lot of errors with 'stateChangeExpr' of null.

> Unhandled Promise rejection: Cannot read property 'stateChangeExpr' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'stateChangeExpr' of null
    at _parseAnimationStateTransition (http://localhost:4200/vendor.bundle.js:31226:68)
    at http://localhost:4200/vendor.bundle.js:31190:97
    at Array.map (native)
    at AnimationParser.parseEntry (http://localhost:4200/vendor.bundle.js:31190:64)
    at http://localhost:4200/vendor.bundle.js:31147:49
    at Array.map (native)
    at AnimationParser.parseComponent (http://localhost:4200/vendor.bundle.js:31146:67)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:65022:71)
    at http://localhost:4200/vendor.bundle.js:64908:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:64908:19)
    at createResult (http://localhost:4200/vendor.bundle.js:64790:19)
    at ZoneDelegate.webpackJsonp.1213.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:378:26)
    at Zone.webpackJsonp.1213.Zone.run (http://localhost:4200/polyfills.bundle.js:170:43)
    at http://localhost:4200/polyfills.bundle.js:757:57 TypeError: Cannot read property 'stateChangeExpr' of null
    at _parseAnimationStateTransition (http://localhost:4200/vendor.bundle.js:31226:68)
    at http://localhost:4200/vendor.bundle.js:31190:97
    at Array.map (native)
    at AnimationParser.parseEntry (http://localhost:4200/vendor.bundle.js:31190:64)
    at http://localhost:4200/vendor.bundle.js:31147:49
    at Array.map (native)
    at AnimationParser.parseComponent (http://localhost:4200/vendor.bundle.js:31146:67)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:65022:71)
    at http://localhost:4200/vendor.bundle.js:64908:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:64908:19)
    at createResult (http://localhost:4200/vendor.bundle.js:64790:19)
    at ZoneDelegate.webpackJsonp.1213.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:378:26)
    at Zone.webpackJsonp.1213.Zone.run (http://localhost:4200/polyfills.bundle.js:170:43)
    at http://localhost:4200/polyfills.bundle.js:757:57
consoleError @ zone.js:522
handleUnhandledRejection @ zone.js:527
_loop_1 @ zone.js:562
drainMicroTaskQueue @ zone.js:566
zone.js:524 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): TypeError: Cannot read property 'stateChangeExpr' of null
TypeError: C…, rejection: TypeError: Cannot read property 'stateChangeExpr' of null
    at _parseAnimationStateTransition (htt…, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask}

**Minimal reproduction of the problem with instructions**
The app doesnt work. It was working well but I needed to install project from my GIT repository and after that when I tried to ng build it showed some errors with @angular/animation missing. So I installed that package and after that it is not working and showing a lot of errors in browser. Please, I need really help because I really dont know what to do now and it is my bachelors thesis...thanks

**Please tell us about your environment:**
Mac OSX,
IDE Webstorm

* **Angular version:** 
"@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "angular2-csv": "^0.1.1",
    "core-js": "^2.4.1",
    "md2": "0.0.18",
    "ng2-pagination": "^2.0.1",
    "primeng": "^2.0.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
[ES6/7]

* **Node (for AoT issues):** `node --version` =   7.2.0

**Comment by DzmitryShylovich** [comment]
Please provide a small plunkr that reproduces the error

**Comment by marianharbist** [comment]
Thank you for your reply but the project is so huge and I have never created any plunkr...

**Comment by ericmartinezr** [comment]
Have you tried updating all your libs to their latest version? This issue in cli's https://github.com/angular/angular-cli/issues/5503#issuecomment-291422904 doesn't give any solution, but the user solved it by updating his dependencies.

**Comment by tbosch** [comment]
Unless we have a reproduction, we can't help, sorry.
A good way to extract a reproduction is bisecting...

**Comment by wuyanxin** [comment]
update the @angular/* packages can solve the problem
because @angular/animations is depend on @angular/core@4.0+

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
