### ISSUE TITLE
[Animation] Height not captured after web animation in Chromium 39

### ISSUE THREAD

**Issue by mlaval** [angular/angular#15793]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
One animation test is failing in Chromium 39, which is the default browser in Android 5.1.1:
```
Chrome Mobile 39.0.0 (Android 5.1.1) animation integration tests using web animations should animate a component that captures height during an animation FAILED
	Expected 0 to be greater than 15.
	    at new Error (native)
	    at assertStyleBetween (/home/travis/build/angular/angular/modules/../../../../../../packages/core/test/animation/animations_with_web_animations_integration_spec.ts:91:18) [ProxyZone]
	    at Object.<anonymous> (/home/travis/build/angular/angular/modules/../../../../../../packages/core/test/animation/animations_with_web_animations_integration_spec.ts:81:6) [ProxyZone]
	    at ProxyZoneSpec.onInvoke (/home/travis/build/angular/angular/node_modules/zone.js/dist/proxy.js:79:39) [ProxyZone]
	    at Zone.run (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:125:43) [<root> => ProxyZone]
	    at Object.<anonymous> (/home/travis/build/angular/angular/node_modules/zone.js/dist/jasmine-patch.js:104:34) [<root>]
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (/home/travis/build/angular/angular/node_modules/zone.js/dist/jasmine-patch.js:132:42) [<root>]
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (/home/travis/build/angular/angular/node_modules/zone.js/dist/jasmine-patch.js:132:42) [<root>]
	    at Zone.runTask (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:165:47) [<root> => <root>]
	    at drainMicroTaskQueue (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:593:35) [<root>]
	    at run (/home/travis/build/angular/angular/node_modules/core-js/client/core.js:4019:23) [<root>]
	    at /home/travis/build/angular/angular/node_modules/core-js/client/core.js:4032:29 [<root>]
	    at MutationObserver.flush (/home/travis/build/angular/angular/node_modules/core-js/client/core.js:4387:10) [<root>]
	Expected 0 to be greater than 35.
	    at new Error (native)
	    at assertStyleBetween (/home/travis/build/angular/angular/modules/../../../../../../packages/core/test/animation/animations_with_web_animations_integration_spec.ts:91:18) [ProxyZone]
	    at Object.<anonymous> (/home/travis/build/angular/angular/modules/../../../../../../packages/core/test/animation/animations_with_web_animations_integration_spec.ts:90:6) [ProxyZone]
	    at ProxyZoneSpec.onInvoke (/home/travis/build/angular/angular/node_modules/zone.js/dist/proxy.js:79:39) [ProxyZone]
	    at Zone.run (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:125:43) [<root> => ProxyZone]
	    at Object.<anonymous> (/home/travis/build/angular/angular/node_modules/zone.js/dist/jasmine-patch.js:104:34) [<root>]
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (/home/travis/build/angular/angular/node_modules/zone.js/dist/jasmine-patch.js:132:42) [<root>]
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (/home/travis/build/angular/angular/node_modules/zone.js/dist/jasmine-patch.js:132:42) [<root>]
	    at Zone.runTask (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:165:47) [<root> => <root>]
	    at drainMicroTaskQueue (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:593:35) [<root>]
	    at run (/home/travis/build/angular/angular/node_modules/core-js/client/core.js:4019:23) [<root>]
	    at /home/travis/build/angular/angular/node_modules/core-js/client/core.js:4032:29 [<root>]
	    at MutationObserver.flush (/home/travis/build/angular/angular/node_modules/core-js/client/core.js:4387:10) [<root>]
```

**Expected behavior**
Test should pass

**Minimal reproduction of the problem with instructions**
See full logs: https://travis-ci.org/angular/angular/jobs/218405097

After investigation, it seems that this browser is no longer calculating the height correctly after a web animation, i.e. `getComputedStyle` is always returning the same value even the element is changing visually size.

**Comment by mlaval** [comment]
Obsolete, issue does not happen anymore

**Comment by mlaval** [comment]
Still occurring:
```
Chrome Mobile 39.0.0 (Android 5.1.1) animation integration tests using web animations should compute (*) animation styles for a container that is being removed FAILED
	Expected [ Object({ height: '0px', offset: 0 }), Object({ height: '0px', offset: 1 }) ] to equal [ Object({ height: '100px', offset: 0 }), Object({ height: '0px', offset: 1 }) ].
	    at Object.<anonymous> (/home/travis/build/angular/angular/modules/../../../../../../packages/core/test/animation/animations_with_web_animations_integration_spec.ts:76:34)
	    at ZoneDelegate.invoke (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:391:26)
	    at ProxyZoneSpec.onInvoke (/home/travis/build/angular/angular/node_modules/zone.js/dist/proxy.js:79:39)
	    at ZoneDelegate.invoke (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:390:63)
	    at Zone.run (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:141:43)
	    at Object.<anonymous> (/home/travis/build/angular/angular/node_modules/zone.js/dist/jasmine-patch.js:104:34)
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (/home/travis/build/angular/angular/node_modules/zone.js/dist/jasmine-patch.js:132:42)
	    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (/home/travis/build/angular/angular/node_modules/zone.js/dist/jasmine-patch.js:132:42)
	    at ZoneDelegate.invokeTask (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:191:47)
	    at drainMicroTaskQueue (/home/travis/build/angular/angular/node_modules/zone.js/dist/zone.js:584:35)
	    at run (/home/travis/build/angular/angular/node_modules/core-js/client/core.js:4019:23)
	    at /home/travis/build/angular/angular/node_modules/core-js/client/core.js:4032:29
	    at MutationObserver.flush (/home/travis/build/angular/angular/node_modules/core-js/client/core.js:4387:10)
```
