### ISSUE TITLE
Cannot read property 'exclude' of undefined at applyDefaults

### ISSUE THREAD

**Issue by saurabhschauhan** [angular/angular#15865]
![screenshot from 2017-04-10 16-59-27](https://cloud.githubusercontent.com/assets/25522343/24859918/fc42bb76-1e0f-11e7-97d5-b454d54750fc.png)

**Hello,
I updated my app to angular4 using "npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save "
**  
```
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/home/daffodil-201/Desktop/backup/beverage-ecommerce-maintenance/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/home/daffodil-201/Desktop/backup/beverage-ecommerce-maintenance/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/home/daffodil-201/Desktop/backup/beverage-ecommerce-maintenance/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/home/daffodil-201/Desktop/backup/beverage-ecommerce-maintenance/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main

```

**Current behavior**

webpack: Failed to compile.

**Expected behavior**

Running app
**Minimal reproduction of the problem with instructions**

when I run my app after updation I'm getting the following problem. I run my app using npm start and ng serve both.

**What is the motivation / use case for changing the behavior?**

I'm updating my project to latest angular version

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:**Chrome 

 
* **Language:**TypeScript

* **Node (for AoT issues):** `node --version` =   6.10.1

**Comment by hansl** [comment]
You seem to be using `@angular/cli`, but also a custom (or very old version of) webpack configuration using `awesome-typescript-loader`. Try to upgrade to the latest version of the Angular CLI, and if this issue still occurs, file an issue on the CLI repo: github.com/angular/angular-cli. Thanks.
