### ISSUE TITLE
Dynamic updates to hierarchical structures throwing exception

### ISSUE THREAD

**Issue by dylanb** [angular/angular#1607]
The use case is the ability to create and update hierarchical structures from data fetched from a server

The code is in this plunk http://plnkr.co/edit/F2gNplix1tBSg3iZmkd0?p=preview

You have to click on the ***Click Me*** element and then you'll see the following stack trace

```
STACKTRACE:
TypeError: Cannot read property 'insert' of null
    at Content.execute.$__export.insert (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:14193:27)
    at redistributeNodes (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:20450:17)
    at LightDom.execute.$__export.redistribute (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:20508:13)
    at ViewContainer.execute.$__export.detach (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:13912:47)
    at ViewContainer.execute.$__export.clear (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:13882:20)
    at RenderViewHydrator.execute.$__export._viewContainerDehydrateRecurse (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:14558:27)
    at RenderViewHydrator.execute.$__export._viewDehydrateRecurse (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:14538:24)
    at RenderViewHydrator.execute.$__export.dehydrateViewInViewContainer (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:14468:18)
    at DirectDomRenderer.execute.$__export.destroyViewInContainer (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:25707:32)
    at AppViewHydrator.execute.$__export.dehydrateViewInViewContainer (https://code.angularjs.org/2.0.0-alpha.20/angular2.dev.js:16126:28)
```

**Comment by mhevery** [comment]
Obsolete, closing.
