### ISSUE TITLE
Whan app loads in browser tab that is not in focus, we get 'Unhandled Promise rejection: Cannot read property 'hasOwnProperty' of undefined' error

### ISSUE THREAD

**Issue by born2net** [angular/angular#16086]
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If I load our application in a browser tab that is not in focus, meaning I am browsing another web site while the application is loading in the background in another chrome browser tab, the application will error out with:
```
Unhandled Promise rejection: Cannot read property 'hasOwnProperty' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'hasOwnProperty' of undefined TypeError: Cannot read property 'hasOwnProperty' of undefined at http://localhost:4208/vendor.bundle.js:124647:40 at Array.forEach (native) at WebAnimationsPlayer.init (http://localhost:4208/vendor.bundle.js:124646:32) at InjectableAnimationEngine.DomAnimationEngine._queuePlayer (http://localhost:4208/vendor.bundle.js:123957:16) at InjectableAnimationEngine.DomAnimationEngine.animateTransition (http://localhost:4208/vendor.bundle.js:123872:14) at http://localhost:4208/vendor.bundle.js:124056:48 at Array.forEach (native) at http://localhost:4208/vendor.bundle.js:124051:49 at Map.forEach (native) at InjectableAnimationEngine.DomAnimationEngine.flush (http://localhost:4208/vendor.bundle.js:124023:30) at http://localhost:4208/vendor.bundle.js:151459:35 at ZoneDelegate.invoke (http://localhost:4208/vendor.bundle.js:218836:26) at Zone.run (http://localhost:4208/vendor.bundle.js:218596:43) at http://localhost:4208/vendor.bundle.js:219231:57 at ZoneDelegate.invokeTask (http://localhost:4208/vendor.bundle.js:218869:31)
 http://localhost:4208/vendor.bundle.js:219040:21 consoleError()
 http://localhost:4208/vendor.bundle.js:219045:9 handleUnhandledRejection()
 http://localhost:4208/vendor.bundle.js:219080:25 _loop_1()
 http://localhost:4208/vendor.bundle.js:219084:21 drainMicroTaskQueue()
 http://localhost:4208/vendor.bundle.js:218935:25 ZoneTask.invoke()
 http://localhost:4208/vendor.bundle.js:220011:29 timer()
```

which comes from the code spot:

```
  WebAnimationsPlayer.prototype.init = function () {
        var _this = this;
        if (this._initialized)
            return;
        this._initialized = true;
        var /** @type {?} */ keyframes = this.keyframes.map(function (styles) {
            var /** @type {?} */ formattedKeyframe = {};
            Object.keys(styles).forEach(function (prop, index) {
                var /** @type {?} */ value = styles[prop];
                if (value == __WEBPACK_IMPORTED_MODULE_0__angular_animations__["AUTO_STYLE"]) {
                    value = _computeStyle(_this.element, prop);
                }
                if (value != undefined) {
                    formattedKeyframe[prop] = value;
                }
            });
            return formattedKeyframe;
        });
        var /** @type {?} */ previousStyleProps = Object.keys(this.previousStyles);
        if (previousStyleProps.length) {
            var /** @type {?} */ startingKeyframe_1 = keyframes[0];
            var /** @type {?} */ missingStyleProps_1 = [];
            previousStyleProps.forEach(function (prop) {
                if (!startingKeyframe_1.hasOwnProperty(prop)) { <<<<<<<<<<<<<<<<<<<<<<<<<
                    missingStyleProps_1.push(prop);
                }
```

**Expected behavior**
This does not happen if application loads while tab is in focus, the was fine in ng2, started in ng4

**Minimal reproduction of the problem with instructions**
you can use this project to reproduce:
https://github.com/born2net/studio-lite

you can even see the issue in our production release, just navigate to:
https://secure.digitalsignage.com/studioweb/index.html?param=dXNlcj1kZW1vX2xpdGVAbXMuY29tLHBhc3M9cGFzc3dvcmQ=

and make sure you tab away as soon as you click the link and wait 15 seconds before switching back to open console and see the error.

```
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2
@angular/language-service: 4.0.2
@ngtools/webpack: 1.3.0
````

**Comment by Toxicable** [comment]
Can you please make a *minimal* reproduction, a plunkr would be best, it takes too much of our time to debug your entire application

**Comment by born2net** [comment]
I don't believe I will be able to reproduce in Plunkr.
I am using cli which I believe is related but I will try and narrow down
tx!

**Comment by Toxicable** [comment]
The only time the CLI should make a difference over reproducing an issue is when the issue is only reproducible in AOT, otherwise if there is a difference then it's a CLI issue not Angular. But either way even a minimal reproduction in repo is better.

**Comment by born2net** [comment]
ok, I will close until I can provide a cleaner project.
tx
