### ISSUE TITLE
Angular 4 and Universal

### ISSUE THREAD

**Issue by lukaszkukawski** [angular/angular#16135]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I try to do tutorial from https://angular.io/docs/ts/latest/guide/universal.html
And i stopped on the subject "Build and Serve - Universal", all code was copied and pasted from tutorial

In console i have info:

```
Air-Angular2Universal lukas$ npm run build:uni

> Angular2Universal@1.0.0 build:uni /Users/lukas/GIT/Angular2Universal
> webpack --config webpack.config.uni.js

Hash: ef2953ae4379901feff9
Version: webpack 2.4.1
Time: 25503ms
        Asset     Size  Chunks                    Chunk Names
    server.js  1.15 MB       0  [emitted]  [big]  main
server.js.map  7.62 MB       0  [emitted]         main
   [2] ./~/rxjs/Observable.js 5.17 kB {0} [built]
   [6] ./~/@angular/core/@angular/core.es5.js 461 kB {0} [built]
   [8] ./~/rxjs/Subscriber.js 8.87 kB {0} [built]
  [19] ./~/rxjs/Subject.js 5.33 kB {0} [built]
  [38] ./aot async 160 bytes {0} [built]
  [70] ./src/uni/app.server.ts 176 bytes {0} [built]
  [71] ./src/uni/server-aot.ts 1.2 kB {0} [built]
  [76] ./~/@angular/platform-server/@angular/platform-server.es5.js 73.7 kB {0} [built]
  [77] ./src/uni/universal-engine.ts 1.17 kB {0} [built]
  [89] ./~/express/index.js 224 bytes {0} [built]
  [92] ./~/express/lib/express.js 2.22 kB {0} [built]
 [138] ./~/rxjs/observable/merge.js 128 bytes {0} [built]
 [144] ./~/rxjs/operator/share.js 922 bytes {0} [built]
 [161] ./~/zone.js/dist/zone-node.js 75.2 kB {0} [built]
 [167] multi ./src/uni/app.server.ts ./src/uni/server-aot.ts 40 bytes {0} [built]
    + 153 hidden modules

WARNING in ./~/express/lib/view.js
80:29-41 Critical dependency: the request of a dependency is an expression

ERROR in ./src/uni/server-aot.ts
Module not found: Error: Can't resolve '../../aot/src/uni/app.server.ngfactory' in '/Users/lukas/GIT/Angular2Universal/src/uni'
 @ ./src/uni/server-aot.ts 3:0-82
 @ multi ./src/uni/app.server.ts ./src/uni/server-aot.ts

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:uni"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Angular2Universal@1.0.0 build:uni: `webpack --config webpack.config.uni.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the Angular2Universal@1.0.0 build:uni script 'webpack --config webpack.config.uni.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Angular2Universal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack.config.uni.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Angular2Universal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Angular2Universal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lukas/GIT/Angular2Universal/npm-debug.log
```

And info from npm-debug.log file

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:uni' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prebuild:uni', 'build:uni', 'postbuild:uni' ]
5 info lifecycle Angular2Universal@1.0.0~prebuild:uni: Angular2Universal@1.0.0
6 silly lifecycle Angular2Universal@1.0.0~prebuild:uni: no script for prebuild:uni, continuing
7 info lifecycle Angular2Universal@1.0.0~build:uni: Angular2Universal@1.0.0
8 verbose lifecycle Angular2Universal@1.0.0~build:uni: unsafe-perm in lifecycle true
9 verbose lifecycle Angular2Universal@1.0.0~build:uni: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/lukas/GIT/Angular2Universal/node_modules/.bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle Angular2Universal@1.0.0~build:uni: CWD: /Users/lukas/GIT/Angular2Universal
11 silly lifecycle Angular2Universal@1.0.0~build:uni: Args: [ '-c', 'webpack --config webpack.config.uni.js' ]
12 silly lifecycle Angular2Universal@1.0.0~build:uni: Returned: code: 2  signal: null
13 info lifecycle Angular2Universal@1.0.0~build:uni: Failed to exec build:uni script
14 verbose stack Error: Angular2Universal@1.0.0 build:uni: `webpack --config webpack.config.uni.js`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Angular2Universal@1.0.0
16 verbose cwd /Users/lukas/GIT/Angular2Universal
17 error Darwin 16.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:uni"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error Angular2Universal@1.0.0 build:uni: `webpack --config webpack.config.uni.js`
22 error Exit status 2
23 error Failed at the Angular2Universal@1.0.0 build:uni script 'webpack --config webpack.config.uni.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Angular2Universal package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --config webpack.config.uni.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Angular2Universal
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Angular2Universal
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Expected behavior**

I want to use angular universal, nothing more.

**Please tell us about your environment:**

macOS Sierra 10.12.4

* **Angular version:** 2.0.X
My packege.json:

```
{
  "name": "Angular2Universal",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "build:uni": "webpack --config webpack.config.uni.js",
    "serve:uni": "node src/dist/server.js",
    "build:aot": "webpack --config webpack.config.aot.js",
    "serve:aot": "lite-server -c=bs-config.aot.js",
    "build": "tsc -p src/",
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "start": "concurrently \"npm run build:watch\" \"npm run serve\"",
    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "angular-in-memory-web-api": "~0.3.0",
    "systemjs": "0.19.40",
    "core-js": "^2.4.1",
    "rxjs": "5.0.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/animations": "^4.0.2",
    "@angular/compiler-cli": "^4.0.2",
    "@angular/platform-server": "^4.0.2",
    "@ngtools/webpack": "^1.3.0",
    "@types/jasmine": "2.5.36",
    "@types/node": "^6.0.46",
    "canonical-path": "0.0.2",
    "concurrently": "^3.2.0",
    "express": "^4.15.2",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.4",
    "protractor": "~4.0.14",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.4",
    "tslint": "^3.15.1",
    "typescript": "~2.1.0",
    "webpack": "^2.4.1"
  },
  "repository": {}
}
```

When i try to Serve - AOT, using command: build:aot and serve:aot it works

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Look at package.json

* **Node (for AoT issues):** `node --version` =   v6.10.2

**Comment by lukaszkukawski** [comment]
I solved this problem using this description: https://github.com/angular/angular/issues/16038

Please update update docs, i spend 2 days for this.
