### ISSUE TITLE
Animation not working angular SSR   (Angular  4.0.3) 

### ISSUE THREAD

**Issue by ysus** [angular/angular#16245]
@vikerman 

**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

when i try to run angular ssr in production  with animation ( ng build --prod) the app run but send me an error after compiling 

when i run with ng serve work fine

**Expected behavior**

the app can be rendering in the browser, but not show me nothing, just loading 

**Minimal reproduction of the problem with instructions**

based on : https://github.com/evertonrobertoauler/cli-universal-demo

`> cli-universal-demo@0.0.0 start C:\src2\evertonrobertoauler\cli-universal-demo-master
> node dist/server.js

listening on http://localhost:4000!
ERROR { ReferenceError: document is not defined
    at DefaultDomRenderer2.selectRootElement (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2821:72)
    at createElement (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:9339:23)
    at createViewNodes (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:11942:44)
    at createRootView (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:11889:5)
    at Object.createProdRootView [as createRootView] (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:12467:12)
    at ComponentFactory_.create (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:9825:46)
    at ComponentFactoryBoundToModule.create (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:3434:29)
    at ApplicationRef_.bootstrap (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:5016:57)
    at C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:4803:79
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:4803:42)
    at C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:4765:27
    at ZoneDelegate.invoke (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\zone.js\dist\zone-node.js:365:26)
    at Object.onInvoke (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:4132:37)
    at ZoneDelegate.invoke (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\zone.js\dist\zone-node.js:364:32)
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
Unhandled Promise rejection: document is not defined ; Zone: <root> ; Task: Promise.then ; Value: { ReferenceError: document is not defined
    at DefaultDomRenderer2.selectRootElement (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2821:72)
    at createElement (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:9339:23)
    at createViewNodes (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:11942:44)
    at createRootView (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:11889:5)
    at Object.createProdRootView [as createRootView] (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:12467:12)
    at ComponentFactory_.create (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:9825:46)
    at ComponentFactoryBoundToModule.create (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:3434:29)
    at ApplicationRef_.bootstrap (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:5016:57)
    at C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:4803:79
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:4803:42)
    at C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:4765:27
    at ZoneDelegate.invoke (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\zone.js\dist\zone-node.js:365:26)
    at Object.onInvoke (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:4132:37)
    at ZoneDelegate.invoke (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\zone.js\dist\zone-node.js:364:32)
  __zone_symbol__currentTask:
   ZoneTask {
     _zone:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } } ReferenceError: document is not defined
    at DefaultDomRenderer2.selectRootElement (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2821:72)
    at createElement (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:9339:23)
    at createViewNodes (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:11942:44)
    at createRootView (C:\src2\evertonrobertoauler\cli-universal-demo-master\node_modules\@angular\core\bundles\core.umd.js:11889:5)`

**Please tell us about your environment:**

@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/animations: 4.0.3
@angular/common: 4.0.3
@angular/compiler: 4.0.3
@angular/core: 4.0.3
@angular/forms: 4.0.3
@angular/http: 4.0.3
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.3
@angular/platform-browser-dynamic: 4.0.3
@angular/platform-server: 4.0.3
@angular/router: 4.0.3
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.3

* **Angular version:**  4.0.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.10.0

**Comment by ysus** [comment]
fixed.
https://github.com/pquarme/cli-universal-demo

**Comment by AnthonyNahas** [comment]
amazing!! it works now !
