### ISSUE TITLE
ngx-bootstrap/dropdown not working with angular2-universal 

### ISSUE THREAD

**Issue by shijilesh** [angular/angular#16263]
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';

@NgModule({
  imports: [BsDropdownModule.forRoot(),...]
})

is not working for me, throws error .

Exception: Call to Node module failed with error: Error: DI Error
at NoProviderError.Error (native)
at NoProviderError.ZoneAwareError (E:\Project\myapp\ClientApp\dist\vendor.js:74873:33)
at NoProviderError.BaseError [as constructor] (E:\Project\myapp\ClientApp\dist\vendor.js:1312:20)
at NoProviderError.AbstractProviderError [as constructor] (E:\Project\myapp\ClientApp\dist\vendor.js:1438:20)
at new NoProviderError (E:\Project\myapp\ClientApp\dist\vendor.js:1478:20)
at ReflectiveInjector_._throwOrNull (E:\Project\myapp\ClientApp\dist\vendor.js:3010:23)
at ReflectiveInjector_._getByKeyDefault (E:\Project\myapp\ClientApp\dist\vendor.js:3049:29)
at ReflectiveInjector_._getByKey (E:\Project\myapp\ClientApp\dist\vendor.js:2981:29)
at ReflectiveInjector_.get (E:\Project\myapp\ClientApp\dist\vendor.js:2850:25)
at NgModuleInjector.get (E:\Project\myapp\ClientApp\dist\vendor.js:8564:56)
at AppView.injectorGet (E:\Project\myapp\ClientApp\dist\vendor.js:12008:49)
at AppView.View_AppComponentx0.createInternal (/AppModule/AppComponentx/component.ngfactory.js:50:156)
at AppView.create (E:\Project\myapp\ClientApp\dist\vendor.js:11951:25)
at AppView.View_AppComponentx_Host0.createInternal (/AppModule/AppComponentx/host.ngfactory.js:15:19)
at AppView.createHostView (E:\Project\myapp\ClientApp\dist\vendor.js:11964:25)

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
