### ISSUE TITLE
SiganalR Error during negotiation request

### ISSUE THREAD

**Issue by MR62** [angular/angular#16371]
Hi,

I use SignalR in my angular app and it works fine. Some days ago I upgrade my angular app from 2.4.5 to 4.0.0. After upgrade SignalR could not starts and fail occurs. Error message is :

`
"Error: Error during negotiation request.
    at Object.error (http://localhost:21755/Scripts/libs/signalr/jquery.signalR.min.js:9:4515) [<root>]
    at g (http://localhost:21755/Scripts/libs/signalr/jquery.signalR.min.js:9:9724) [<root>]
    at Object.error (http://localhost:21755/Scripts/libs/signalr/jquery.signalR.min.js:9:10024) [<root>]
    at i (http://localhost:21755/Scripts/jquery-3.2.1.min.js:2:28017) [<root>]
    at Object.fireWith [as rejectWith] (http://localhost:21755/Scripts/jquery-3.2.1.min.js:2:28783) [<root>]
    at A (http://localhost:21755/Scripts/jquery-3.2.1.min.js:4:14060) [<root>]
    at Function.ajax (http://localhost:21755/Scripts/jquery-3.2.1.min.js:4:13534) [<root>]
    at Object.ajax (http://localhost:21755/Scripts/libs/signalr/jquery.signalR.min.js:9:16132) [<root>]
    at t.fn.init.start (http://localhost:21755/Scripts/libs/signalr/jquery.signalR.min.js:9:9984) [<root>]
    at a._.deferredStartHandler (http://localhost:21755/Scripts/libs/signalr/jquery.signalR.min.js:9:7271) [<root>]
    at dispatch (http://localhost:21755/Scripts/jquery-3.2.1.min.js:3:10316) [<root>]
    at q.handle (http://localhost:21755/Scripts/jquery-3.2.1.min.js:3:8343) [<root>]"
`

What is problem and how can I fix it?
Thank in advance.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
