### ISSUE TITLE
Error thrown when using input[type="date"] on IE11

### ISSUE THREAD

**Issue by markheron91** [angular/angular#16575]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Using a dynamic form for part of my app - data is retrieved from an api and used to show different types of fields on the screen. This error occurs when the type of the field is specified as "date", and only happens on IE11. My other supported browsers (Chrome, Firefox, Edge) handle this type ok (Edge doesn't show the field but it doesn't error).

The error that is thrown is pretty cryptic and it has taken a while of trial and error with different form data structures to work out that it was the date field causing the problem. The error can be seen below (server urls and names omitted):

Error: Invalid argument.
    at e.prototype.setProperty (https://<url>/vendor.5d8acaa85e31b2fd098e.bundle.js:697:2668)
    at 0t (https://<url>/vendor.5d8acaa85e31b2fd098e.bundle.js:697:3613)
    at Tt (https://<url>/vendor.5d8acaa85e31b2fd098e.bundle.js:697:2999)
    at kt (https://<url>/vendor.5d8acaa85e31b2fd098e.bundle.js:697:2438)
    at Wn (https://<url>/vendor.5d8acaa85e31b2fd098e.bundle.js:697:4773)
    at Vn (https://<url>/vendor.5d8acaa85e31b2fd098e.bundle.js:697:4643)
    at ar (https://<url>/vendor.5d8acaa85e31b2fd098e.bundle.js:697:8648)
    at Anonymous function (https://<url>/main.09bc3955f9436e5aafc5.bundle.js:1:178462)
    at updateRenderer

**Expected behavior**

There should be no app breaking error returned if code like this is included, especially as IE11 is listed as one of the supported browsers.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/7IuISDwu0q7BL1xynFZn?p=preview

Compare the behaviour in other browsers to the behaviour experienced when this plunkr is run in IE11.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.1

* **Browser:** IE 11

 
* **Language:** Typescript 2.3.1

* **Node (for AoT issues):** `node --version` = 

Cheers

**Comment by CyoClound** [comment]
I ran into a similar problem in **IE11** ，but no such problems in chrome and firefox in

Error: 参数无效。
at DefaultDomRenderer2.prototype.setValue (http://localhost:4200/vendor.bundle.js:205435:71)
at BaseAnimationRenderer.prototype.setValue (http://localhost:4200/vendor.bundle.js:207473:73)
at DebugRenderer2.prototype.setValue (http://localhost:4200/vendor.bundle.js:192824:66)
at checkAndUpdateTextInline (http://localhost:4200/vendor.bundle.js:190889:9)
at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:191391:13)
at checkAndUpdateNode (http://localhost:4200/vendor.bundle.js:191336:9)
at debugCheckAndUpdateNode (http://localhost:4200/vendor.bundle.js:192193:5)
at debugCheckRenderNodeFn (http://localhost:4200/vendor.bundle.js:192172:13)
at Anonymous function (Function code:14:5)
at debugUpdateRenderer (http://localhost:4200/vendor.bundle.js:192157:5)"

**Comment by gkalpak** [comment]
This is error is not related to forms actually. It is that IE11 will throw an error if you try to set an `input`'s `type` property (not attribute) to a value that it does not support (e.g. `date`).

So, the part that is causing the error is `<input [type]="fieldType"`. Note that this is not Angular-specific; you would get the same error if you manually did `document.getElementById(fieldId).type = 'date'`.

**Comment by kara** [comment]
Yep, IE11 doesn't seem to support the date type, so not much we can do here.
