### ISSUE TITLE
ViewChild can't construct a query on 4.1.1 

### ISSUE THREAD

**Issue by matheo** [angular/angular#16614]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
```

**Current behavior**
`@ViewChild(MyComponent)` doesn't work anymore as shown in [the Component Communication docs](https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#parent-calls-an-_-viewchild-_)

**Expected behavior**
Be able to select some child components.

**Minimal reproduction of the problem with instructions**
I have a `BuilderComponent` with three subcomponents: `Toolbar`, `Markers` and `Canvas`, I cannot select the childs anymore in `4.1.1`. My template looks like:
```
<div class="builder-sidenav">
  <app-toolbar></app-toolbar>
</div>
<div class="builder-maincontent">
  <app-canvas></app-canvas>
  <app-markers></app-markers>
</div>
```
and I try to do the usual query on my parent component:
```
  @ViewChild(CanvasComponent)
  private canvas: CanvasComponent;

  @ViewChild(MarkersComponent)
  private markers: MarkersComponent;
```
when I try to select the child AfterViewInit:
```
  ngAfterViewInit() {
    // not even waiting a tick to select the child
    setTimeout(() => {
      console.log(this.canvas)
    }, 0);
  }
```
I get:
```
Error: Can't construct a query for the property "canvas" of "BuilderComponent" since the query selector wasn't defined.
    at syntaxError (http://localhost:4200/vendor.bundle.js:50691:34)
    at CompileMetadataResolver._getQueryMetadata (http://localhost:4200/vendor.bundle.js:64230:35)
    at http://localhost:4200/vendor.bundle.js:64205:32
    at Array.forEach (native)
    at CompileMetadataResolver._getQueriesMetadata (http://localhost:4200/vendor.bundle.js:64202:30)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:4200/vendor.bundle.js:63498:32)
    at CompileMetadataResolver._getEntryComponentMetadata (http://localhost:4200/vendor.bundle.js:64149:45)
    at http://localhost:4200/vendor.bundle.js:64135:48
    at Array.forEach (native)
    at CompileMetadataResolver._getEntryComponentsFromProvider (http://localhost:4200/vendor.bundle.js:64134:30)
    at syntaxError (http://localhost:4200/vendor.bundle.js:50691:34)
    at CompileMetadataResolver._getQueryMetadata (http://localhost:4200/vendor.bundle.js:64230:35)
    at http://localhost:4200/vendor.bundle.js:64205:32
    at Array.forEach (native)
    at CompileMetadataResolver._getQueriesMetadata (http://localhost:4200/vendor.bundle.js:64202:30)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:4200/vendor.bundle.js:63498:32)
    at CompileMetadataResolver._getEntryComponentMetadata (http://localhost:4200/vendor.bundle.js:64149:45)
    at http://localhost:4200/vendor.bundle.js:64135:48
    at Array.forEach (native)
    at CompileMetadataResolver._getEntryComponentsFromProvider (http://localhost:4200/vendor.bundle.js:64134:30)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3465:31)
    at resolvePromise (http://localhost:4200/polyfills.bundle.js:3436:17)
    at http://localhost:4200/polyfills.bundle.js:3513:17
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:3122:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:4914:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:3121:36)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:2889:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3282:35)
    at <anonymous>
```

**Please tell us about your environment:**
```
ubuntu 16.04
Typescript 2.3.2
@angular/cli: 1.0.2
http_parser: 2.7.0
node: 7.6.0
v8: 5.5.372.40
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: linux x64
@angular/animations: 4.1.1
@angular/common: 4.1.1
@angular/compiler: 4.1.1
@angular/core: 4.1.1
@angular/forms: 4.1.1
@angular/http: 4.1.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.1.1
@angular/platform-browser-dynamic: 4.1.1
@angular/router: 4.1.1
@angular/cli: 1.0.2
@angular/compiler-cli: 4.1.1
```

**Comment by ericmartinezr** [comment]
It's working fine for me http://plnkr.co/edit/Ej4DoJRtSUxPqVCcnFum?p=preview. Please add a reproduction of your issue.

**Comment by matheo** [comment]
Thanks @ericmartinezr 
Indeed something is happening in my upgraded 4.0.1 app then.

For the record, I've printed the angular version to see it in the plunker:
http://plnkr.co/edit/y8Jm7d?p=preview
