### ISSUE TITLE
gulp lint silently fails

### ISSUE THREAD

**Issue by bisubus** [angular/angular#16829]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

```
**Current behavior**

`gulp lint` silently fails with an error that doesn't look like an error, except code 1:

```
[00:28:11] Using gulpfile <...>\gulpfile.js
[00:28:11] Starting 'format:enforce'...
[00:28:11] Starting 'validate-commit-messages'...
[00:28:11] Finished 'validate-commit-messages' after 20 ms
[00:28:11] Starting 'tools:build'...

From https://github.com/bisubus/angular
 * branch            master     -> FETCH_HEAD
```

On a closer look there are no 'Finished' messages for `format:enforce` and `tools:build` tasks but there is obscure `From ...` in the end.

The problem was debugged to `validate-commit-messages` task which [logs the first 2 strings from `git` output instead of the error](https://github.com/angular/angular/blob/b1a79fd2ec188e7d75a5e8064f588b4d022bee7b/tools/gulp-tasks/validate-commit-message.js#L11-L12). 

And actual error that fails the task is

```
{ Error: stdout maxBuffer exceeded                                                     
    at Socket.<anonymous> (child_process.js:257:14)                                    
    at emitOne (events.js:96:13)                                                       
    at Socket.emit (events.js:188:7)                                                   
    at readableAddChunk (_stream_readable.js:176:18)                                   
    at Socket.Readable.push (_stream_readable.js:134:10)                               
    at Pipe.onread (net.js:547:20)                                                     
  cmd: 'git fetch origin master && git log --reverse --format=%s HEAD ^origin/master' }
```

The primary cause of buffer excess is #16830 .

**Expected behavior**

`gulp lint` should work as expected or provide meaningful error output.

**Minimal reproduction of the problem with instructions**

```
git clone https://github.com/angular/angular
cd ./angular
npm i
gulp validate-commit-messages
```

**Please tell us about your environment:**

Windows 7 x64
Node 6.10.3
NPM 3.10.10
git 2.9.0.windows.1

* **Angular version:** 4.2.0-beta.1

**Comment by gkalpak** [comment]
Thx for reporting this!
The situation has been improved in #19685, but I will submit a PR to make errors more explicit and also stop execution.
