### ISSUE TITLE
Angular Universal: ng-express-engine goes into an infinite loop if res.render() throws an error

### ISSUE THREAD

**Issue by simonxca** [angular/angular#17073]
Copy of https://github.com/angular/universal/issues/730#issuecomment-304540378. I was suggested to post this issue here.

* **I'm submitting a ...**
```
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [X] express-engine
- [ ] hapi-engine
```
Apparently [the source of the problem](https://github.com/angular/universal/issues/730#issuecomment-304540378) is `RenderModule` in [angular/packages/platform-server](https://github.com/angular/angular/tree/master/packages/platform-server/src)

* **What is the current behavior?**
Using ng-express-engine, if `res.render()` encounters an error, it goes into an infinite loop.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Steps to reproduce:
1. `git clone https://github.com/simonxca/ng-universal-demo`
2. `cd ng-universal-demo`
3. `npm run watch`
4. `npm run server`
5. Try opening `localhost:8000` in browser.

The repo above is a fork of https://github.com/FrozenPandaz/ng-universal-demo. I only added [one line](https://github.com/simonxca/ng-universal-demo/commit/62d6492e4a2e4fbfdadd9ed146c21c51a948b746).

* **What is the expected behavior?**
There should be a way to catch the error thrown by `res.render()` and send back a 500 response to the browser instead of going into an infinite loop.

* **What is the motivation / use case for changing the behavior?**
If something goes wrong during the `res.render()`, the infinite loop will eat up the CPU and the app will no longer be functional.

* **Please tell us about your environment:**

- Angular version: 4.1.3
- Browser: all
- Language: all
- OS:  Mac OSX Sierra
- Platform: NodeJS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Here's a stack trace:
```
ERROR TypeError: Cannot read property 'bar' of undefined
    at Object.eval [as updateRenderer] (ng:///AppModule/HomeView.ngfactory.js:24:27)
    at Object.updateRenderer (/Users/simonxca/source/ng-universal-demo/dist/server.js:13465:70)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12994:14)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
    at execComponentViewsAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13284:13)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12995:5)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
    at execEmbeddedViewsAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13310:17)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12990:5)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
ERROR TypeError: Cannot read property 'bar' of undefined
    at Object.eval [as updateRenderer] (ng:///AppModule/HomeView.ngfactory.js:24:27)
    at Object.updateRenderer (/Users/simonxca/source/ng-universal-demo/dist/server.js:13465:70)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12994:14)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
    at execComponentViewsAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13284:13)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12995:5)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
    at execEmbeddedViewsAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13310:17)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12990:5)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
ERROR TypeError: Cannot read property 'bar' of undefined
    at Object.eval [as updateRenderer] (ng:///AppModule/HomeView.ngfactory.js:24:27)
    at Object.updateRenderer (/Users/simonxca/source/ng-universal-demo/dist/server.js:13465:70)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12994:14)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
    at execComponentViewsAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13284:13)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12995:5)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
    at execEmbeddedViewsAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13310:17)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12990:5)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
ERROR TypeError: Cannot read property 'bar' of undefined
    at Object.eval [as updateRenderer] (ng:///AppModule/HomeView.ngfactory.js:24:27)
    at Object.updateRenderer (/Users/simonxca/source/ng-universal-demo/dist/server.js:13465:70)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12994:14)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
    at execComponentViewsAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13284:13)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12995:5)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
    at execEmbeddedViewsAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13310:17)
    at checkAndUpdateView (/Users/simonxca/source/ng-universal-demo/dist/server.js:12990:5)
    at callViewAction (/Users/simonxca/source/ng-universal-demo/dist/server.js:13352:21)
... loops infinitely.
```

**Comment by vikerman** [comment]
Will look into it

**Comment by paulogr** [comment]
Any workaround for this?

**Comment by adrienboulle** [comment]
I've (I think) found the issue.
It's juste that the custom error handler from angular do not run outside angular.

a workaround I used:

```
export class CustomErrorHandler extends ErrorHandler {
  constructor(private _zone: NgZone) {
    super();
  }

  public handleError(err: any): void {
    Logger.configure();
    this._zone.runOutsideAngular(() => {
      super.handleError(err);
    });
  }
}

export function loggerFactory(ngZone: NgZone) {
  return new CustomErrorHandler(ngZone);
}

@NgModule({
  providers: [
    { provide: ErrorHandler, useFactory: loggerFactory, deps: [NgZone] },
  ],
})
...
```

**Comment by adrienboulle** [comment]
@vikerman Are you guys working on it? We have migrated quite a big app in my company to universal last week and we had to rollback several times due to this issue.

The fact is that the infinite loop just won't stop until the server is down, meaning that without the workaround, it's just not possible to have an app on production with universal (assuming the app is big enough and bugs do exist)

**Comment by vikerman** [comment]
Sorry for the delay. I started investigating the root cause but got pulled into other things.

The root cause as to why this happens only on platform-server and not on platform-browser is that the console.warn on Node.JS actually results in a Zone.JS task invocation again which causes the NgZone to emit microTaskEmpty again which triggers the change detection which in turn throws an exception again. Trying to figure out the right place to fix this now.
