### ISSUE TITLE
`Error: Compilation failed. Resource file not found` for fuzzy scss import

### ISSUE THREAD

**Issue by cburgmer** [angular/angular#17108]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

My project includes the following statement:

```
@import "./../node_modules/some_module/src/index.scss";
```

although the actual file is found in `./../node_modules/some_module/src/_index.scss`.

Now running ng-xi18n yields the following:

```
$ ./node_modules/.bin/ng-xi18n -p src/tsconfig.app.json --i18nFormat=xlf
Error: Compilation failed. Resource file not found: /Users/me/my_project/node_modules/some_module/src/index.scss
    at ModuleResolutionHostAdapter.readResource (/Users/me/my_project/node_modules/@angular/compiler-cli/src/compiler_host.js:370:19)
    at CompilerHost.loadResource (/Users/me/my_project/node_modules/@angular/compiler-cli/src/compiler_host.js:243:85)
    at Object.get (/Users/me/my_project/node_modules/@angular/compiler/bundles/compiler.umd.js:26163:103)
    at DirectiveNormalizer._fetch (/Users/me/my_project/node_modules/@angular/compiler/bundles/compiler.umd.js:13297:45)
    at /Users/me/my_project/node_modules/@angular/compiler/bundles/compiler.umd.js:13426:53
    at Array.map (native)
    at DirectiveNormalizer._loadMissingExternalStylesheets (/Users/me/my_project/node_modules/@angular/compiler/bundles/compiler.umd.js:13426:14)
    at /Users/me/my_project/node_modules/@angular/compiler/bundles/compiler.umd.js:13429:26
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
Extraction failed
```

**Expected behavior**
Any syntax that scss allows, should be supported in Angular. Alternatively the documentation should point out how to make Angular happy by finding those fuzzy imports upfront. 

I tried both sass-lint and stylelint, neither seem to give me an option to flag such imports early on. So any package I consume is able to break my translation process.

**Minimal reproduction of the problem with instructions**
See above.

**What is the motivation / use case for changing the behavior?**
See above.

**Please tell us about your environment:**
$ uname -v
Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
$ node --version
v7.9.0
$ cat package.json | grep '"@angular/compiler-cli"'
    "@angular/compiler-cli": "^4.1.3",

**Comment by vicb** [comment]
We can not help without knownig about your setup. However this works - you can try with the CLI
