### ISSUE TITLE
Getting DI Error on using custom provider in a lazy loaded module

### ISSUE THREAD

**Issue by sanbornsen** [angular/angular#17117]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

<img width="1096" alt="screen shot 2017-05-30 at 9 48 34 pm" src="https://cloud.githubusercontent.com/assets/2410474/26593475/cbaf101a-4581-11e7-8197-5a69b1f18ce3.png">
Getting this error when trying to use a lazy loaded module with custom provider. Something like this

```
providers: [
    // TestService,
    OverrideService,
    {
      provide: OverrideService,
      useExisting: TestService
    }
  ]
```

**Expected behavior**

above should work, just like the following works.

```
providers: [
    TestService
]
```

**Minimal reproduction of the problem with instructions**

I have created a sample application with angular CLI which will show you the problem.
https://github.com/sanbornsen/nglazyloadtest
```After running the application, go to localhost:4200/lazy```

**What is the motivation / use case for changing the behavior?**

To be able to use lazy loaded module with custom providers.

**Please tell us about your environment:** Generic env

* **Angular version:** 2.4.0 and `Router 3.4.0`.

* **Browser:** all

* **Language:** TypeScript 2.0.0 (Not specific, I am using this. Shouldn't be a problem)

* **Node (for AoT issues):** Node 6.9.5

**Edit**
I just tried with angular 4 (Updated the above repo) and the error still exists but in a different form. Something like the following - 

```
Error: Uncaught (in promise): Error Error at Error.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3645:33) at ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3642:35) at injectionError (http://localhost:4200/vendor.bundle.js:2419:86) at noProviderError (http://localhost:4200/vendor.bundle.js:2457:12) at ReflectiveInjector_.throwOrNull (http://localhost:4200/vendor.bundle.js:3958:19) at ReflectiveInjector.getByKeyDefault (http://localhost:4200/vendor.bundle.js:3997:25) at ReflectiveInjector.getByKey (http://localhost:4200/vendor.bundle.js:3929:25) at ReflectiveInjector.get (http://localhost:4200/vendor.bundle.js:3798:21) at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:4766:52) at TestModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:4766:52) at resolveDep (http://localhost:4200/vendor.bundle.js:12227:45) at createClass (http://localhost:4200/vendor.bundle.js:12080:35) at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:11911:37) at createViewNodes (http://localhost:4200/vendor.bundle.js:13274:49) at createRootView (http://localhost:4200/vendor.bundle.js:13179:5) at Error.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3645:33) at ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3642:35) at injectionError (http://localhost:4200/vendor.bundle.js:2419:86) at noProviderError (http://localhost:4200/vendor.bundle.js:2457:12) at ReflectiveInjector_.throwOrNull (http://localhost:4200/vendor.bundle.js:3958:19) at ReflectiveInjector.getByKeyDefault (http://localhost:4200/vendor.bundle.js:3997:25) at ReflectiveInjector.getByKey (http://localhost:4200/vendor.bundle.js:3929:25) at ReflectiveInjector.get (http://localhost:4200/vendor.bundle.js:3798:21) at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:4766:52) at TestModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:4766:52) at resolveDep (http://localhost:4200/vendor.bundle.js:12227:45) at createClass (http://localhost:4200/vendor.bundle.js:12080:35) at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:11911:37) at createViewNodes (http://localhost:4200/vendor.bundle.js:13274:49) at createRootView (http://localhost:4200/vendor.bundle.js:13179:5) at resolvePromise (http://localhost:4200/polyfills.bundle.js:3318:31) [angular] at resolvePromise (http://localhost:4200/polyfills.bundle.js:3289:17) [angular] at http://localhost:4200/polyfills.bundle.js:3366:17 [angular] at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:5328:37) [angular] at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:3019:36) [angular] at Zone.runTask (http://localhost:4200/polyfills.bundle.js:2819:47) [<root> => angular] at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:3199:35) [<root>] at <anonymous> [<root>]
```

**Comment by vicb** [comment]
@sanbornsen is the bug still present on the 4.x branch ?

**Comment by sanbornsen** [comment]
@vicb I updated the description. Yes, it exists with 4.x

**Comment by tytskyi** [comment]
shouldn't be?

```
providers: [
    // TestService,
    OverrideService,
    {
      provide: TestService ,
      useExisting: OverrideService
    }
  ]
```

**Comment by sanbornsen** [comment]
@tytskyi exactly. Sorry !! My bad. Now it's working fine. I'll just close the issue.
