### ISSUE TITLE
Error messages rearly direct to either cause or way to solve the problem

### ISSUE THREAD

**Issue by ido-ran** [angular/angular#17197]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I'm following the [AngularJS to Angular Upgrade tutorial](https://angular.io/docs/ts/latest/guide/upgrade.html) and I run into mistakes I made (which is what I expect while learning new technology) but the error messages I see in the DevTools Console are far from clearly explaining the possible cause of the error nor how I might go about solving the error.

## Example 1 - forget to declare Angular component which will be used in AngularJS in `declarations` section of my NgModule:

```
zone.js:642 Unhandled Promise rejection: Component PhoneListComponent is not part of any NgModule or the module has not been imported into your module. ; Zone: <root> ; Task: Promise.then ; Value: Error: Component PhoneListComponent is not part of any NgModule or the module has not been imported into your module.
    at JitCompiler._createCompiledHostTemplate (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25678:19)
    at eval (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25644:37)
    at Array.forEach (native)
    at eval (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25642:45)
    at Array.forEach (native)
    at JitCompiler._compileComponents (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25631:43)
    at createResult (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25532:19)
    at ZoneDelegate.invoke (http://localhost:8000/node_modules/zone.js/dist/zone.js:391:26)
    at Zone.run (http://localhost:8000/node_modules/zone.js/dist/zone.js:141:43)
    at http://localhost:8000/node_modules/zone.js/dist/zone.js:817:57 Error: Component PhoneListComponent is not part of any NgModule or the module has not been imported into your module.
    at JitCompiler._createCompiledHostTemplate (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25678:19)
    at eval (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25644:37)
    at Array.forEach (native)
    at eval (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25642:45)
    at Array.forEach (native)
    at JitCompiler._compileComponents (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25631:43)
    at createResult (http://localhost:8000/node_modules/@angular/compiler/bundles/compiler.umd.js:25532:19)
    at ZoneDelegate.invoke (http://localhost:8000/node_modules/zone.js/dist/zone.js:391:26)
    at Zone.run (http://localhost:8000/node_modules/zone.js/dist/zone.js:141:43)
    at http://localhost:8000/node_modules/zone.js/dist/zone.js:817:57
api.onUnhandledError @ zone.js:642
handleUnhandledRejection @ zone.js:666
_loop_1 @ zone.js:657
api.microtaskDrainDone @ zone.js:661
drainMicroTaskQueue @ zone.js:592
ZoneTask.invoke @ zone.js:490

```

Example ## 2 - Replace $ngResource with Angular Http and covert the Observable return from Http.get to Promise with rxjs `toPromise()`

This is a naive upgrade while leaving the controller and template the same as it was used with `$ngResource`

```
angular.js:14199 Error: [filter:notarray] Expected array but received: {"__zone_symbol__state":null,"__zone_symbol__value":[]}
http://errors.angularjs.org/1.5.11/filter/notarray?p0=%7B%22__zone_symbol__state%22%3Anull%2C%22__zone_symbol__value%22%3A%5B%5D%7D
    at angular.js:68
    at angular.js:20500
    at fn (eval at compile (angular.js:15126), <anonymous>:4:378)
    at regularInterceptedExpression (angular.js:16354)
    at Scope.$digest (angular.js:17828)
    at Scope.$apply (angular.js:18102)
    at done (angular.js:12082)
    at completeRequest (angular.js:12291)
    at XMLHttpRequest.requestLoaded (angular.js:12219)
    at XMLHttpRequest.wrapFn [as __zone_symbol___onload] (zone.js:1055)
```

## Example 3 - Replace $ngResource with Angular Http and replace method result from Promise to Observable

```
angular.js:14199 Error: [filter:notarray] Expected array but received: {"_isScalar":false,"source":{"_isScalar":false},"operator":{}}
http://errors.angularjs.org/1.5.11/filter/notarray?p0=%7B%22_isScalar%22%3A…C%22source%22%3A%7B%22_isScalar%22%3Afalse%7D%2C%22operator%22%3A%7B%7D%7D
    at angular.js:68
    at angular.js:20500
    at fn (eval at compile (angular.js:15126), <anonymous>:4:378)
    at regularInterceptedExpression (angular.js:16354)
    at Scope.$digest (angular.js:17828)
    at Scope.$apply (angular.js:18102)
    at done (angular.js:12082)
    at completeRequest (angular.js:12291)
    at XMLHttpRequest.requestLoaded (angular.js:12219)
    at XMLHttpRequest.wrapFn [as __zone_symbol___onload] (zone.js:1055)
```

There are lots of other examples, and there are also unclear messages from TypeScript Compiler but that's belong to a different issues in different repository.

**Expected behavior**

I would be great if the error messages will be more informative about the possible cause of the problem and possible ways to solve them. In Example 1 for instance it does direct me to a possible issue with NgModule but it doesn't say anything about `declarations`. 

Adding link to more details online might be good way to help find possible solutions.

I think looking at Elm error messages is a good direction to work toward.

**Minimal reproduction of the problem with instructions**

I've written several examples, I'll be glad to push complete repos if required.

**What is the motivation / use case for changing the behavior?**

Developers run into errors all the time and it's one of the hardest barrires for entry to any framework.
As I'm working to learn how to upgrade AngularJS to Angular I find myself having to develop strong intuition of what error messages actually means. Even when I get things working I start to try remove and change things in way I assume will happen to me to see what kind of errors are produces.

Having clear error messages can help focus on the development instead of the guess-work around the cause and solution of the error.

* **Angular version:** 2.0.X

    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "@angular/upgrade": "^4.1.3",

**Comment by tbosch** [comment]
Link to the tracking bug: https://github.com/angular/angular/issues/19700

**Comment by gkalpak** [comment]
For the first example, the error now is:

> Cannot determine the module for class TestComponent in /path/to/project/src/app/test.component.ts! Add TestComponent to the NgModule to fix it.

This is better, but could still be improved, I guess (e.g. by mentioning `declarations` or linking to some docs).

##
For the other two examples, I am afraid there is not much we can do. If an AngularJS filter expects an array and instead gets a promise or an observable is a very generic error to provide a useful suggestion. Also, AngularJS lacks the static evaluation capabilities of Angular, so it can't really offer more context.

Angular's template type-checking has been improved significantly in recent versions, so it can check the types of values used in your templates (e.g. passed to filters) and complain if their type is not appropriate. But this is not something we can fix in AngularJS at this point :grin:

##
Leaving this issue open to track improving the error for the first example (component missing from `declarations`).

**Comment by atscott** [comment]
Closing since AngularJS and the upgrade module are nearing end of life. Realistically, we won't be prioritizing work in these areas.
