### ISSUE TITLE
Exception message does not help to find error: EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: Cannot read property 'operation' of undefined

### ISSUE THREAD

**Issue by thomas-mindruptive** [angular/angular#17224]
Bug-Report

Environment:

- Angular 2.3.1 - installed through the seed-sample
- Build time: Node 7.8.0, NPM 4.2.0
-  Browsers: Edge, Chrome 58
- TypeScript: Just using that of the seed-sample: ~2.0.3, generate ES6
- OS: Windows 10

I simply re-deployed the app today and got following message

EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: Cannot read property 'operation' of undefined
`
EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: Cannot read property 'operation' of undefined
Error: Error in :0:0 caused by: Cannot read property 'operation' of undefined
    at ViewWrappedError.ZoneAwareError (http://ng-ai-01.azurewebsites.net/polyfills.bundle.js:6883:33)
    at ViewWrappedError.BaseError [as constructor] (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:27195:16)
    at ViewWrappedError.WrappedError [as constructor] (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:27260:16)
    at new ViewWrappedError (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:56256:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:76003:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:75976:18)
    at ViewRef_.detectChanges (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:57183:20)
    at RouterOutlet.activate (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:62691:42)
    at ActivateRoutes.placeComponentIntoOutlet (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:22538:16)
    at ActivateRoutes.activateRoutes (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:22505:26)
    at http://ng-ai-01.azurewebsites.net/vendor.bundle.js:22441:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:22441:29)
    at ActivateRoutes.activate (http://ng-ai-01.azurewebsites.net/vendor.bundle.js:22415:14)
    at http://ng-ai-01.azurewebsites.net/vendor.bundle.js:21975:22
`

Any idea is appreciated
Thanks

**Comment by pkozlowski-opensource** [comment]
Could you please provide a minimal reproduce scenario? We can't help based on just the information provided... Ideally you should also updated to the latest released Angular 4.x version and check if the error is still there.

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
