### ISSUE TITLE
Navigating to the same component with different params not working

### ISSUE THREAD

**Issue by lansana** [angular/angular#17538]
## I'm submitting a ...
<pre><code>[x] Bug report </code></pre>

## Current behavior
When I first navigate to the component, everything works. When I navigate to the same component with a different parameter, I get an error.

I can confirm the URL's are valid, and the params I'm passing to the routerLink is not null or undefined. 

When I click the link, the route changes the id parameter for a split second and then it goes back to what it was before, then the error below is thrown (the app also breaks and I can't navigate anywhere else once the error happens):

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'next' of null
TypeError: Cannot read property 'next' of null
    at advanceActivatedRoute (http://localhost:8080/vendor.bundle.js:60552:31)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:8080/vendor.bundle.js:62623:13)
    at http://localhost:8080/vendor.bundle.js:62583:58
    at Array.forEach (native)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateChildRoutes (http://localhost:8080/vendor.bundle.js:62583:29)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:8080/vendor.bundle.js:62627:22)
    at http://localhost:8080/vendor.bundle.js:62583:58
    at Array.forEach (native)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateChildRoutes (http://localhost:8080/vendor.bundle.js:62583:29)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:8080/vendor.bundle.js:62630:22)
    at advanceActivatedRoute (http://localhost:8080/vendor.bundle.js:60552:31)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:8080/vendor.bundle.js:62623:13)
    at http://localhost:8080/vendor.bundle.js:62583:58
    at Array.forEach (native)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateChildRoutes (http://localhost:8080/vendor.bundle.js:62583:29)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:8080/vendor.bundle.js:62627:22)
    at http://localhost:8080/vendor.bundle.js:62583:58
    at Array.forEach (native)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateChildRoutes (http://localhost:8080/vendor.bundle.js:62583:29)
    at ActivateRoutes.webpackJsonp../node_modules/@angular/router/@angular/router.es5.js.ActivateRoutes.activateRoutes (http://localhost:8080/vendor.bundle.js:62630:22)
    at resolvePromise (http://localhost:8080/polyfills.bundle.js:3110:31)
    at resolvePromise (http://localhost:8080/polyfills.bundle.js:3081:17)
    at http://localhost:8080/polyfills.bundle.js:3158:17
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8080/polyfills.bundle.js:2765:31)
    at Object.onInvokeTask (http://localhost:8080/vendor.bundle.js:34992:37)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8080/polyfills.bundle.js:2764:36)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:8080/polyfills.bundle.js:2532:47)
    at drainMicroTaskQueue (http://localhost:8080/polyfills.bundle.js:2925:35)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:8080/polyfills.bundle.js:2831:25)
defaultErrorLogger @ core.es5.js:1084
webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1144
next @ core.es5.js:4778
schedulerFn @ core.es5.js:3851
webpackJsonp../node_modules/rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp../node_modules/rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp../node_modules/rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp../node_modules/rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp../node_modules/rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3837
webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.NgZone.triggerError @ core.es5.js:4209
onHandleError @ core.es5.js:4170
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:157
_loop_1 @ zone.js:652
api.microtaskDrainDone @ zone.js:661
drainMicroTaskQueue @ zone.js:592
ZoneTask.invoke @ zone.js:490
```

## Expected behavior
I should be able to get the new ID passed into the route params observable, with no error, so that I can use the ID to fetch more data and update my component values accordingly.

## Minimal reproduction of the problem with instructions
This is my component:
```typescript
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { Subscription } from 'rxjs/Subscription';

@Component({
    // ...
    template: `
    <a [routerLink]="['../', myData.id]">Go to same component with different ID</a>
`
})
export class OUDetailComponent implements OnInit, OnDestroy {
    private dataSub: Subscription;

    myData: any;

    constructor(private route: ActivatedRoute) {
        this.paramsSub = route.params.subscribe(params => {
            // do stuff with params['id']...
            // this.myData = someDataWithNewId;
        });
    }

    ngOnInit() {
        // The code is currently in the constructor, but even if I put it here in ngOnInit I still get the same error.
    }

    ngOnDestroy() {
        this.paramsSub.unsubscribe();
    }

    initializeView(id: number) {
        // Make HTTP call and reset this.myData
    }
}
```

## Please tell us about your environment

<pre><code>
Angular version: 4.0.3

Browser:
- [x] Chrome (desktop) latest version
 
For Tooling issues:
- Node version: 8.1.1
- Platform: Mac
</code></pre>

**Comment by jasonaden** [comment]
@lansana I think you're attempting to go one route up. Shouldn't your link be: 

`<a [routerLink]="['./', myData.id]">Go to same component with different ID</a>`

Specifically, `./` rather than `../`?

**Comment by rafa-as** [comment]
Same here! I've tried all the options, any solution/workaround?

**Comment by tornodo** [comment]
@rafa-as  here is the answer
https://stackoverflow.com/questions/41678356/router-navigate-does-not-call-ngoninit-when-same-page
