### ISSUE TITLE
AOT does not add Annotations from metadata

### ISSUE THREAD

**Issue by Alekcei** [angular/angular#17595]
Please help me
How to use "MyModule" Compiled by AOT in JitCompiler?

## I'm submitting a ...
`ERROR Error: Unexpected value '[object Object]' imported by the module 'DynamicHtmlModule'. Please add a @NgModule annotation.`
MyModule contains controls component. But he does not have metadata

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0

Browser:
- any

For Tooling issues:
- Node version: v6.10.0
- Platform:  Linux, Windows

Others:
angular cli
</code></pre>

**Comment by alexzuza** [comment]
Can you add reproduction?

**Comment by Alekcei** [comment]
Reproduce in my [MyRepositary AotAndJitl](https://github.com/Alekcei/AotAndJitl)
Failure
ng serve --aot=true  

Complete success
ng serve --aot=false  

[The main code file](https://github.com/Alekcei/AotAndJit/blob/master/src/app/app.component.ts)
```
import { Component, OnInit, ViewContainerRef, ViewChild, ComponentRef, ElementRef, ComponentFactoryResolver, NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { CommonModule } from '@angular/common';
import { ControlsModule } from './controls/controls.module';
import { ReflectiveInjector, ComponentFactory, Compiler } from '@angular/core';
import { JitCompilerFactory } from '@angular/compiler';

export function CustomComponent(annotation: any) {
  return function (target: Function) {
    //var parentTarget = annotation.parent;
    let metaData = new Component(annotation)
    Component(metaData)(target)
  }
}

export function CustomNgModule(annotation: any) {
  return function (target: Function) {
    //var parentTarget = annotation.parent;
    let metaData = new NgModule(annotation)
    NgModule(metaData)(target)
  }
}

export function appendMetaData(obj:any, metadata:any){
        obj.annotations = [ metadata ];
    }

export function createJitCompiler() {
    console.log("create jit compiller")
   return new JitCompilerFactory([{ useDebug: false, useJit: true}]).createCompiler();
}
class PetitionEdit{
    itIsMaySuperPetitionComponent = true
    selectFrom = {1:'value1 in dinmic petition', 2:'value2 in dinamic petition'}
}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [{ provide: Compiler, useFactory: createJitCompiler, deps: [] }]
})
export class AppComponent implements OnInit {

    selectFrom = {1:'value1',2:'value2'}
    title = 'app';

    @ViewChild('petitionContent',  { read: ViewContainerRef })
    containerRef: ViewContainerRef;
    private innerRef: ComponentRef<any>;

    @ViewChild('petitionContentTwo',  { read: ViewContainerRef })
    containerRef2: ViewContainerRef;
    private innerRef2: ComponentRef<any>;

    @ViewChild('petitionContentThree',  { read: ViewContainerRef })
    containerRef3: ViewContainerRef;
    private innerRef3: ComponentRef<any>;

    constructor(private elementRef: ElementRef,
                private resolver: ComponentFactoryResolver,
                private compiler: Compiler){
    }
    ngOnInit() {

        try{
            let petitionhtmlForm = `
                <div style="text-align:center">
                  <h1>
                    Thih is my dinamic component
                  </h1>
                <br/>
                <ui-button>My button in dinamic component does not work !</ui-button>
                <br/><br/>
                <ui-select style="width:300px" [from]="selectFrom"></ui-select>
                <br/><br/>
            `
            this.createDinamicPetitionComponent1 (petitionhtmlForm, this.innerRef, this.containerRef, this.resolver, this.compiler)

        } catch(e){
            console.error(e)
        }
        try {

            let petitionhtmlForm = `
                <div style="text-align:center">
                  <h1>
                    Thih is my dinamic component WORKING. Without  ControlsModule, because ControlsModule does not contain MetaData
                  </h1>
                <br/>
                <br/><br/>
            `
            this.createDinamicPetitionComponent2 (petitionhtmlForm, this.innerRef2, this.containerRef2, this.resolver, this.compiler)

        } catch(e){
            console.error(e)
        }


        try {

            let petitionhtmlForm = `
                <div style="text-align:center">
                  <h1>
                    Thih is my dinamic component does not work. Without  ControlsModule,
                  </h1>
                <br/>
                <br/><br/>
                 <ui-button>My button in dinamic component not working !</ui-button>
                <br/><br/>
                <ui-select style="width:300px" [from]="selectFrom"></ui-select>
                <br/><br/>
            `
            this.createDinamicPetitionComponent3 (petitionhtmlForm, this.innerRef3, this.containerRef3, this.resolver, this.compiler)

        } catch(e){
            console.error(e)
        }

    }

    createDinamicPetitionComponent1(htmlForm, innerRef, containerRef, resolver, compiler ){
        console.log("createDinamicPetitionComponent1")
        if (innerRef) {
            innerRef.destroy();
        }

        @Component({
            selector: 'dinamic-petition-edit',
            template: htmlForm
        })
        class DynamicPetitionEditComponent extends PetitionEdit {}

        @NgModule({
            declarations:[DynamicPetitionEditComponent],
            imports: [    BrowserModule,
                          CommonModule,
                          ControlsModule
                     ]
        })
        class DynamicHtmlModule {}
        compiler.compileModuleAndAllComponentsAsync(DynamicHtmlModule) // if Aot no contains metadata
        .then(factory => {
            const compFactory = factory.componentFactories.find(x => x.componentType === DynamicPetitionEditComponent);
            const injector = ReflectiveInjector.fromResolvedProviders([], containerRef.parentInjector);
            innerRef = containerRef.createComponent(compFactory, 0, injector, []);
         });

    }

    createDinamicPetitionComponent2(htmlForm, innerRef, containerRef, resolver, compiler ){
        console.log("createDinamicPetitionComponent2")
        if (innerRef) {
            innerRef.destroy();
        }

        @CustomComponent({   //  custom append metaData
            selector: 'dinamic-petition-edit',
            template: htmlForm
        })
        class DynamicPetitionEditComponent extends PetitionEdit {}

        @CustomNgModule({
            declarations:[DynamicPetitionEditComponent],
            imports: [    BrowserModule,  // <-- succes
                          CommonModule,   // <-- succes
                        //  ControlsModule  // <-- HAS ERRORS
                     ]
        })
        class DynamicHtmlModule {}

        compiler.compileModuleAndAllComponentsAsync(DynamicHtmlModule)
        .then(factory => {
            const compFactory = factory.componentFactories.find(x => x.componentType === DynamicPetitionEditComponent);
            const injector = ReflectiveInjector.fromResolvedProviders([], containerRef.parentInjector);
            innerRef = containerRef.createComponent(compFactory, 0, injector, []);
         });

    }


    createDinamicPetitionComponent3(htmlForm, innerRef, containerRef, resolver, compiler ){
        console.log("createDinamicPetitionComponent3")
        if (innerRef) {
            innerRef.destroy();
        }

        @CustomComponent({   //  custom append metaData
            selector: 'dinamic-petition-edit',
            template: htmlForm
        })
        class DynamicPetitionEditComponent extends PetitionEdit {}

        @CustomNgModule({
            declarations:[DynamicPetitionEditComponent],
            imports: [    BrowserModule,  // <-- succes
                          CommonModule,   // <-- succes
                          ControlsModule  // <-- HAS ERRORS
                     ]
        })
        class DynamicHtmlModule {}

        compiler.compileModuleAndAllComponentsAsync(DynamicHtmlModule)
        .then(factory => {
            const compFactory = factory.componentFactories.find(x => x.componentType === DynamicPetitionEditComponent);
            const injector = ReflectiveInjector.fromResolvedProviders([], containerRef.parentInjector);
            innerRef = containerRef.createComponent(compFactory, 0, injector, []);
         });

    }
}

```

**Comment by alexzuza** [comment]
angular-cli removes all angular decorators in aot mode. If you want to keep decorator then use custom decorator like `@CustomComponent` or `@CustomNgModule`

**Comment by Alekcei** [comment]
**Custom decorator not working for AOT**
@CustomComponent or @CustomNgModule working is only Jit. If use custom decorator like @CustomComponent or @CustomNgModule for ControlsModule
```
let  declarations = [
      UiButtonComponent,
      UiSelectComponent,
      UiRadioComponent
]
@CustomNgModule({
  declarations: declarations,
  imports: [CommonModule],
  exports:  declarations,
  providers: []
})
export class ControlsModule {}
```
Has errors
```
ERROR in Unexpected value 'ControlsModule in /home/sosnovskikh/workspaces/AotAndJit/src/app/controls/controls.module.ts' imported by the module 'AppModule in /home/sosnovskikh/workspaces/AotAndJit/src/app/app.module.ts'. Please add a @NgModule annotation.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/sosnovskikh/workspaces/AotAndJit/src'
 @ ./src/main.ts 4:0-74
 @ multi webpack-dev-server/client?http://172.30.0.38:4200 ./src/main.ts
```
Is there a way to make the decorator work under AOTandJit with @angular/cli?

**Comment by alexzuza** [comment]
```
const metadata = {
  declarations: declarations,
  imports: [CommonModule],
  exports:  declarations,
  providers: []
};

@NgModule(metadata)
@CustomNgModule(metadata)
export class ControlsModule {}
```

**Comment by Alekcei** [comment]
So does not work
Has Error in browser console
```
Uncaught TypeError: __webpack_require__.i(...) is not a function
    at Object.../../../../../src/app/controls/controls.module.ts (main.bundle.js:649)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.../../../../../src/app/app.component.ts (main.bundle.js:379)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.../../../../../src/$$_gendir/app/app.module.ngfactory.ts (main.bundle.js:121)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.../../../../../src/main.ts (main.bundle.js:927)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.2 (main.bundle.js:944)
    at __webpack_require__ (inline.bundle.js:55)
```

**Comment by alexzuza** [comment]
You have circular reference. Move custom decorator from app.component.ts to separated file

**Comment by Alekcei** [comment]
Oh yes! It works! 
The solution is, but very complex! I hope it will be easier. I will rewrite my project
Thank you very much!

**Comment by Alekcei** [comment]
Helo, I  have an error, after update
`Error: No ResourceLoader implementation has been provided. Can't read the url "button.component.less"
    at Object.get (http://localhost:4201/vendor.bundle.js:43611:15)
    at DirectiveNormalizer.webpackJsonp.../../../compiler/@angular/compiler.es5.js.DirectiveNormalizer._fetch (http://localhost:4201/vendor.bundle.js:30339:43)
    at http://localhost:4201/vendor.bundle.js:30455:68
    at Array.map (native)
    at DirectiveNormalizer.webpackJsonp.../../../compiler/@angular/compiler.es5.js.DirectiveNormalizer._loadMissingExternalStylesheets (http://localhost:4201/vendor.bundle.js:30455:14)
    at DirectiveNormalizer.webpackJsonp.../../../compiler/@angular/compiler.es5.js.DirectiveNormalizer.normalizeExternalStylesheets (http://localhost:4201/vendor.bundle.js:30433:36)
    at http://localhost:4201/vendor.bundle.js:30366:105
    at Object.then (http://localhost:4201/vendor.bundle.js:17958:156)
    at DirectiveNormalizer.webpackJsonp.../../../compiler/@angular/compiler.es5.js.DirectiveNormalizer.normalizeTemplate (http://localhost:4201/vendor.bundle.js:30366:26)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.loadDirectiveMetadata (http://localhost:4201/vendor.bundle.js:31395:75)`

Reproduce in my [MyRepositary AotAndJitl](https://github.com/Alekcei/AotAndJitl)
Failure
ng serve --aot=true  

Complete success
ng serve --aot=false

**Comment by Alekcei** [comment]
This is problem https://github.com/angular/angular/issues/15343

**Comment by Alekcei** [comment]
Jit and Aot not working do not work in a place,
I append CustomDecorator, but property comoponet not binds

```
Error: Template parse errors:
Can't bind to 'from' since it isn't a known property of 'ui-select'.
1. If 'ui-select' is an Angular component and it has 'from' input, then verify that it is part of this module.
2. If 'ui-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("king !!!!!!!!</ui-button>
                <br/><br/>
                <ui-select style="width:300px" [ERROR ->][from]="selectFrom"></ui-select>

                <br/><br/>
"): ng:///DynamicHtmlModule/DynamicPetitionEditComponent.html@9:47
```

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Alekcei** [comment]
Please add cook
I @Input, but has error
