### ISSUE TITLE
Language service. Do not fail hard when component cannot be used as an entry component

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#17767]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When Language service meets component with custom decorator it fails with `cannot be used as an entry component` and stack:

```
Process: Error processing message: AppComponent cannot be used as an entry component. Error: AppComponent cannot be used as an entry component.
    at Error (native)
    at syntaxError (/home/sergey/projects/angularLsIssue/node_modules/@angular/language-service/bundles/language-service.umd.js:18667:34)
    at CompileMetadataResolver._getEntryComponentMetadata (/home/sergey/projects/angularLsIssue/node_modules/@angular/language-service/bundles/language-service.umd.js:32865:19)
    at /home/sergey/projects/angularLsIssue/node_modules/@angular/language-service/bundles/language-service.umd.js:32438:110
    at Array.map (native)
    at CompileMetadataResolver.getNgModuleMetadata (/home/sergey/projects/angularLsIssue/node_modules/@angular/language-service/bundles/language-service.umd.js:32438:73)
    at addNgModule (/home/sergey/projects/angularLsIssue/node_modules/@angular/language-service/bundles/language-service.umd.js:41114:58)
    at /home/sergey/projects/angularLsIssue/node_modules/@angular/language-service/bundles/language-service.umd.js:41125:14
    at Array.forEach (native)
    at _createNgModules (/home/sergey/projects/angularLsIssue/node_modules/@angular/language-service/bundles/language-service.umd.js:41124:26)
```

## Expected behavior

LS should report warning but do not fail

## Minimal reproduction of the problem with instructions

Check the repo: https://github.com/WiseBird/angular_ls_issue
Decorator:

```
export function WindowComponent(annotation: any) {
  return function (target: Function) {
    const metadata = new Component(annotation);
    Reflect.defineMetadata('annotations', [metadata], target);
  };
}
```

## What is the motivation / use case for changing the behavior?

Ability to use LS with custom component decorators

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

 
For Tooling issues:
- Node version: 7.6.0
- Platform: Mint - Linux computer 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Others:
IDE: WebShtorm 2017.2 EAP
</code></pre>

**Comment by danger89** [comment]
I have something simular. I'm new but I don't know what I did wrong here:
```
ERROR in Error: AppComponent cannot be used as an entry component.
    at syntaxError (/mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:528:34)
    at CompileMetadataResolver._getEntryComponentMetadata (/mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:15899:19)
    at /mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:15371:110
    at Array.map (native)
    at CompileMetadataResolver.getNgModuleMetadata (/mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:15371:73)
    at visitLazyRoute (/mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:31175:104)
    at AotCompiler.listLazyRoutes (/mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:31143:20)
    at AngularCompilerProgram.listLazyRoutes (/mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@angular/compiler-cli/src/transformers/program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (/mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:248:66)
    at Promise.resolve.then.then (/mnt/c910940f-f82f-47a8-8a73-b93a7a23a069/Projects/tmp/erp-frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:565:50)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
```ts
....
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by lentschi** [comment]
Just in case anyone else stumbles across in conjunction with the VsCode plugin ["Angular Language Service"](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template): There's this ["Cannot read property 'length' of undefined" bug](https://github.com/angular/vscode-ng-language-service/issues/90), that has been marked as resolved long ago, but still happened to me with angular 8.0.2 and VsCode "Angular Language Service" 0.801.1. (`ng serve` works fine for me, this is just about VsCode)
I did a local workaround for it by changing this line in the file `node_modules/@angular/language-service/bundles/language-service.umd.js`):

```js
entryComponents.push.apply(entryComponents, __spread(bootstrapComponents.map(function (type) { return _this._getEntryComponentMetadata(type.reference, false); })));
```

...to this:

```js
entryComponents.push.apply(entryComponents, __spread(bootstrapComponents.map(function (type) { return _this._getEntryComponentMetadata(type.reference, false); }).filter(function (comp) {return comp !== null;})));
```

This'll fix until the next angular upgrade and who knows - Maybe then the problem's resolved :smile:

**Comment by JoostK** [comment]
With the Ivy language service the erroring code is no longer used, and I've not been able to reproduce even with the View Engine based language service enabled.
