### ISSUE TITLE
AOT and Jit not compiled with external files

### ISSUE THREAD

**Issue by Alekcei** [angular/angular#17764]
Please help me
How to use "MyModule" Compiled by AOT in JitCompiler?

## I'm submitting a ...
`ERROR Error: Unexpected value '[object Object]' imported by the module 'DynamicHtmlModule'. Please add a @NgModule annotation.`
MyModule contains controls component. But he does not have metadata

## Please tell us about your environment

<pre><code>
Angular version: 4.0.0

Browser:
- any

For Tooling issues:
- Node version: v6.10.0
- Platform:  Linux, Windows

Others:
angular cli
</code></pre>

From https://github.com/angular/angular/issues/17595
I added CustomDecorators
MyComponents not compiled with external files

`Error: No ResourceLoader implementation has been provided. Can't read the url "button.component.less"
    at Object.get (http://localhost:4201/vendor.bundle.js:43611:15)
    at DirectiveNormalizer.webpackJsonp.../../../compiler/@angular/compiler.es5.js.DirectiveNormalizer._fetch (http://localhost:4201/vendor.bundle.js:30339:43)
    at http://localhost:4201/vendor.bundle.js:30455:68
    at Array.map (native)
    at DirectiveNormalizer.webpackJsonp.../../../compiler/@angular/compiler.es5.js.DirectiveNormalizer._loadMissingExternalStylesheets (http://localhost:4201/vendor.bundle.js:30455:14)
    at DirectiveNormalizer.webpackJsonp.../../../compiler/@angular/compiler.es5.js.DirectiveNormalizer.normalizeExternalStylesheets (http://localhost:4201/vendor.bundle.js:30433:36)
    at http://localhost:4201/vendor.bundle.js:30366:105
    at Object.then (http://localhost:4201/vendor.bundle.js:17958:156)
    at DirectiveNormalizer.webpackJsonp.../../../compiler/@angular/compiler.es5.js.DirectiveNormalizer.normalizeTemplate (http://localhost:4201/vendor.bundle.js:30366:26)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.loadDirectiveMetadata (http://localhost:4201/vendor.bundle.js:31395:75)`

Reproduce in my [MyRepositary AotAndJitl](https://github.com/Alekcei/AotAndJit)
Failure
ng serve --aot=true  

Complete success
ng serve --aot=false  

How use AOT and Jit and @angular/cli

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by Alekcei** [comment]
Sory but this problem has already been encountered https://github.com/angular/angular/issues/15343,
Please add possible using custom component compile for AOT in Jit compiller
```
var _NO_RESOURCE_LOADER = {
    /**
     * @param {?} url
     * @return {?}
     */
    get: function (url) {
        throw new Error("No ResourceLoader implementation has been provided. Can't read the url \"" + url + "\"");
    }
};
```
