### ISSUE TITLE
Please guide me to Debug Angular 4 app 

### ISSUE THREAD

**Issue by atlabiz** [angular/angular#17786]
I use Vscode and I want to fix one big problem I have in my app. the only reason to fix that is to debug my  code

I find this random code from the StackOverflow how to debug angular 4 in vscode but is not working is don't debug anything

## launch.json
```
    {
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome against localhost, with sourcemaps",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:4200/all-products",
      "sourceMaps": true,
      "diagnosticLogging": true,
      "webRoot": "${workspaceRoot}",
      "userDataDir": "${workspaceRoot}/.vscode/chrome"
    },
    {
      "name": "Attach to Chrome, with sourcemaps",
      "type": "chrome",
      "request": "attach",
      "port": 9222,
      "sourceMaps": true,
      "diagnosticLogging": true,
      "webRoot": "${workspaceRoot}"
    }
  ]
}

```

## DEBUG CONSOLE

Error processing "restart": TypeError: Cannot read property 'Page' of undefined
    at ChromeDebugAdapter.restart (C:\Users\Developer\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.5\out\bundle.js:304:27)
    at Object.dispatchRequest (C:\Users\Developer\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.5\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugSession.js:75:82)
    at Object.ProtocolServer._handleData (C:\Users\Developer\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.5\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:104:38)
    at Socket.<anonymous> (C:\Users\Developer\.vscode\extensions\msjsdiag.debugger-for-chrome-3.1.5\node_modules\vscode-chrome-debug-core\node_modules\vscode-debugadapter\lib\protocol.js:24:60)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
Terminated: Got disconnect request
Killing Chrome process by pid: taskkill /F /T /PID 3188

**Comment by pkozlowski-opensource** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
