### ISSUE TITLE
Strange behavior of Ahead-of-Time Compilation with configure rootDirs

### ISSUE THREAD

**Issue by mgtsai** [angular/angular#17803]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Error occurs while compiling a project with AoT with tsconfig.json contains "rootDirs":

<pre><code>
Error: Unable to find any resolvable import for @angular/core relative to /module.ngfactory.ts
at PathMappedCompilerHost.fileNameToModuleName (/project/node_modules/@angular/compiler-cli/src/path_mapped_compiler_host.js:115:15)
at StaticSymbolResolver.fileNameToModuleName (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:25151:23)
at Object.importExpr$$1 [as importExpr] (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:23990:69)
at singleProviderDef (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:18377:32)
at componentFactoryResolverProviderDef (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:18483:14)
at NgModuleCompiler.compile (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:18525:46)
at AotCompiler._compileModule (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:23920:32)
at /project/node_modules/@angular/compiler/bundles/compiler.umd.js:23833:66
at Array.forEach (native)
at AotCompiler._compileImplFile (/project/node_modules/@angular/compiler/bundles/compiler.umd.js:23833:19)
Compilation failed
</code></pre>

## Expected behavior
Compilation error should not occur, especially compiling Angular's internal modules (@angular/core)

## Minimal reproduction of the problem with instructions
I have simplified the while project containing only 3 files to demonstrate this

tsconfig.json
<pre><code>
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "lib": ["dom", "es7"],
    "rootDirs": [
      "generated",
      "app"
    ]
  },
  "include": [
    "app/**/*.ts"
  ],
  "angularCompilerOptions": {
    "genDir": "generated",
    "skipMetadataEmit": true
  }
}
</code></pre>

app/main.ts
<pre><code>
import { platformBrowser }   from '@angular/platform-browser';
import { AppModuleNgFactory} from './module.ngfactory';
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
</code></pre>

app/module.ts
<pre><code>
import {NgModule} from '@angular/core';

@NgModule({
    imports: [],
    declarations: []
})
export class AppModule { }
</code></pre>

Then, use <code>ngc</code> to compile this project

Otherwise, by removing "rootDirs" in tsconfig.js, the compilation is all fine

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.3
- Platform: Linux

Others:

</code></pre>

**Comment by JoostK** [comment]
This issue concerns the legacy compiler pipeline and is now obsolete. Having `rootDirs` configured in Ivy is not a problem.
