### ISSUE TITLE
Angular animation issue in IE11

### ISSUE THREAD

**Issue by jclancy93** [angular/angular#17822]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

On IE11 (only on pages with animations), I get the error "TypeError: Object doesn't support property or method 'contains'

Here is the stack trace:
   at _contains (http://192.168.1.92:4200/vendor.bundle.js:111033:41)
   at NoopAnimationDriver.prototype.containsElement (http://192.168.1.92:4200/vendor.bundle.js:111078:77)
   at TransitionAnimationEngine.prototype._balanceNamespaceList (http://192.168.1.92:4200/vendor.bundle.js:114345:17)
   at TransitionAnimationEngine.prototype.createNamespace (http://192.168.1.92:4200/vendor.bundle.js:114318:13)
   at TransitionAnimationEngine.prototype.register (http://192.168.1.92:4200/vendor.bundle.js:114369:13)
   at AnimationEngine.prototype.register (http://192.168.1.92:4200/vendor.bundle.js:115419:9)
   at AnimationRendererFactory.prototype.createRenderer (http://192.168.1.92:4200/vendor.bundle.js:181176:9)
   at DebugRendererFactory2.prototype.createRenderer (http://192.168.1.92:4200/vendor.bundle.js:161361:9)
   at createComponentView (http://192.168.1.92:4200/vendor.bundle.js:159965:9)
   at callWithDebugContext (http://192.168.1.92:4200/vendor.b"

## Expected behavior

To be able to animate without throwing errors

## Minimal reproduction of the problem with instructions
http://sheltered-eyrie-91513.herokuapp.com/#/report/619/leasing

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x ] IE version 11
- [ ] Edge version XX
 

Others:
This seems to also have something to do with the library @swimlane/ngx-charts. Any help would be greatly appreciated! 

</code></pre>

**Comment by ericmartinezr** [comment]
https://angular.io/guide/browser-support#mandatory-polyfills

**Comment by jclancy93** [comment]
@ericmartinezr Definitely have all the necessary polyfills installed. You can close this issue though, as I have found that the problem is caused by ngx-charts. 

You can find the issue in the ngx-charts github here: https://github.com/swimlane/ngx-charts/issues/459

**Comment by TahaDiNero** [comment]
Have the same issue with line chart(ngx-chart).
Any news for possible fix??

**Comment by matsko** [comment]
Unfortunately this can't be changed inside of the angular animation code because `element.contains` is used heavily. The problem looks like SVG elements do not contain this method (maybe in just IE).

@Taha-Di-Nero @jclancy93 did you guys have any progress getting this to function using polyfills?

**Comment by gkalpak** [comment]
FWIW, in AngularJS we work around this IE9-11 issue [like this][1]:


```
var contains = window.Node.prototype.contains || function(arg) {
  // eslint-disable-next-line no-bitwise
  return this === arg || !!(this.compareDocumentPosition(arg) & 16);
};
```

[1]: https://github.com/angular/angular.js/blob/8f563e2ecf7a882f8306225e8c781fafad42ecb5/src/ngAnimate/animateQueue.js#L181-L185

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
