### ISSUE TITLE
Not working export member AnimationBuilder

### ISSUE THREAD

**Issue by splincode** [angular/angular#17935]
```
[AOT-PRE-COMPILE ngc]
Error at /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts:8:10: Module '"/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"' has no exported member 'AnimationBuilder'.
Error at /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts:8:28: Module '"/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"' has no exported member 'AnimationFactory'.
Error at /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts:8:65: Module '"/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"' has no exported member 'AnimationOptions'.
Error at /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22: Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'flush' from class 'AnimationEngine'.
Error at /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22: Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'listen' from class 'AnimationEngine'.
Error at /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22: Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'onInsert' from class 'AnimationEngine'.
Error at /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22: Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'onRemove' from class 'AnimationEngine'.
Error at /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22: Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'registerTrigger' from class 'AnimationEngine'.
Error at /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22: Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'setProperty' from class 'AnimationEngine'.
Error at /home/splincode/Develop/blackbox/ui-util/source/app/app.module.ngfactory.ts:49:27: Property 'AnimationBuilder' does not exist on type 'typeof "/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"'.



```

```
ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/index.ngfactory.ts (40,27): Property 'AnimationBuilder' does not exist on type 'typeof "/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/index.ngfactory.ts (77,27): Property 'AnimationBuilder' does not exist on type 'typeof "/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"'.

ERROR in /home/splincode/Develop/blackbox/ui-util/source/app/app.module.ngfactory.ts (49,27): Property 'AnimationBuilder' does not exist on type 'typeof "/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"'.

ERROR in /home/splincode/Develop/blackbox/ui-util/webapp/source/app/app.module.ngfactory.ts (49,27): Property 'AnimationBuilder' does not exist on type 'typeof "/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts (8,10): Module '"/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"' has no exported member 'AnimationBuilder'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts (8,28): Module '"/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"' has no exported member 'AnimationFactory'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts (8,65): Module '"/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"' has no exported member 'AnimationOptions'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts (5,22): Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'flush' from class 'AnimationEngine'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts (5,22): Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'listen' from class 'AnimationEngine'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts (5,22): Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'onInsert' from class 'AnimationEngine'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts (5,22): Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'onRemove' from class 'AnimationEngine'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts (5,22): Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'registerTrigger' from class 'AnimationEngine'.

ERROR in /home/splincode/Develop/blackbox/ui-util/node_modules/@angular/platform-browser/animations/src/providers.d.ts (5,22): Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'setProperty' from class 'AnimationEngine'.

ERROR in [at-loader] node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts:8:10 
    Module '"/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"' has no exported member 'AnimationBuilder'.

ERROR in [at-loader] node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts:8:28 
    Module '"/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"' has no exported member 'AnimationFactory'.

ERROR in [at-loader] node_modules/@angular/platform-browser/animations/src/animation_builder.d.ts:8:65 
    Module '"/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"' has no exported member 'AnimationOptions'.

ERROR in [at-loader] node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22 
    Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'flush' from class 'AnimationEngine'.

ERROR in [at-loader] node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22 
    Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'listen' from class 'AnimationEngine'.

ERROR in [at-loader] node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22 
    Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'onInsert' from class 'AnimationEngine'.

ERROR in [at-loader] node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22 
    Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'onRemove' from class 'AnimationEngine'.

ERROR in [at-loader] node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22 
    Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'registerTrigger' from class 'AnimationEngine'.

ERROR in [at-loader] node_modules/@angular/platform-browser/animations/src/providers.d.ts:5:22 
    Non-abstract class 'InjectableAnimationEngine' does not implement inherited abstract member 'setProperty' from class 'AnimationEngine'.

ERROR in [at-loader] source/app/app.module.ngfactory.ts:49:27 
    Property 'AnimationBuilder' does not exist on type 'typeof "/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"'.

ERROR in [at-loader] webapp/source/app/app.module.ngfactory.ts:49:27 
    Property 'AnimationBuilder' does not exist on type 'typeof "/home/splincode/Develop/blackbox/ui-util/node_modules/@angular/animations/animations"'.


```

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by jdrake3** [comment]
I know it isn't all the guidelines, but if it helps:

@angular/cli@1.2.1
@angular/common@4.2.6
@angular/compiler@4.2.6
@angular/animations@4.1.1
