### ISSUE TITLE
error      use   ionic cordova build ios --prod

### ISSUE THREAD

**Issue by chd999** [angular/angular#17990]
use   ionic cordova build ios --prod
     
ionic_app-scripts1.3.4    no error  ,   but   ios app  Can't use
ionic_app-scripts1.3.4----ionic_app-scripts1.3.12  error

C:\zzvc\app\icomi_mobile_app>ionic cordova build ios --prod
> cordova platform add --save ios
✔ Running command - done!
Running app-scripts build: --prod --iscordovaserve --externalIpRequired --nobrowser

[00:11:25]  build prod started ...
[00:11:25]  clean started ...
[00:11:25]  clean finished in 12 ms
[00:11:25]  copy started ...
[00:11:25]  ngc started ...
[00:11:33]  ngc finished in 8.12 s
[00:11:33]  preprocess started ...
[00:11:33]  deeplinks started ...
[00:11:33]  deeplinks finished in 379 ms
[00:11:33]  optimization started ...
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of
       date.
Error: ./~/_ionic2-calendar@0.3.7@ionic2-calendar/calendar.ngfactory.ts
Module build failed: TypeError: Cannot read property 'content' of undefined
    at Object.optimizationLoader (C:\zzvc\app\icomi_mobile_app\node_modules\_@ionic_app-scripts@1.3.7@@ionic\app-scripts\dist\webpack\optimization-loader-impl.js:14:24)
    at Object.loader (C:\zzvc\app\icomi_mobile_app\node_modules\_@ionic_app-scripts@1.3.7@@ionic\app-scripts\dist\webpack\optimization-loader.js:5:32)
 @ ./src/app/app.module.ngfactory.js 57:0-82
 @ ./src/app/main.ts

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
