### ISSUE TITLE
Using type alias and dependency injection throws error

### ISSUE THREAD

**Issue by mpk** [angular/angular#18035]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have an Angular service that contains some generic parameters - `class Store<A, B, C>` - and I injected the service into components like this:
```
constructor( private store: Store<string, number, boolean> ) {}
```

Since I don't want to repeat the generic parameters in every single component, I decided to create an alias (using TypeScript type aliases feature) - `type StoreAlias = Store<string, number, boolean>;` - so I can inject the service like this:
```
constructor( private store: StoreAlias ) {}
```

Since type aliases just assign a new name for a type, I would expect this to work. However, Angular dependency injection cannot resolve it and throws an error:
```
Uncaught Error: Can't resolve all parameters for AppComponent: (?).
    at syntaxError (http://localhost:4200/vendor.bundle.js:17706:34)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:31774:35)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.bundle.js:31642:26)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:4200/vendor.bundle.js:31237:24)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getEntryComponentMetadata (http://localhost:4200/vendor.bundle.js:31896:45)
    at http://localhost:4200/vendor.bundle.js:31478:110
    at Array.map (native)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:31478:73)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:42702:70)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:42675:36)
```

## Expected behavior
Should not throw a dependency resolution error.

## Minimal reproduction of the problem with instructions
`app.module.ts`
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { Store } from './store';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule],
  providers: [Store],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

`app.component.ts`
```
import { Component } from '@angular/core';
import { StoreAlias } from './store-alias';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    constructor(
        private store: StoreAlias
    ) {}
}
```

`store.ts`
```
import { Injectable } from '@angular/core';

@Injectable()
export class Store<A, B, C> {

}
```

`store-alias.ts`
```
import { Store } from './store';

export type StoreAlias = Store<string, number, boolean>;
```

## Please tell us about your environment
<pre><code>
Angular version: 4.2.6

Browser:
- [x] Chrome (desktop) version 59
</code></pre>

**Comment by chuckjaz** [comment]
There are several things at work here.

First, we do not resolve types during the collection and code generating phase. This intentional to avoid multiple type-checking passes and we have to generate code before type-checking since the generated code is, itself, type-checked. This means we do not know that `StoreAlias` is an alias and treat it as a type and, therefore, as a metadata token. Since no provider is found for the token `StoreAlias` we report an error. You can work around this by using an `@Inject`. Even more laborious than supplying type parameters I know but you need it anyway as noted below.

Second, we don't support generics as a metadata token. This is because generics do not result in a unique token for each combination of type parameters (that is, the type is not reified). You need to supply a token that represents this combination yourself. This is why `InjectionToken` has a generic type parameter which represents the instance type the token will inject. 

Therefore, you need to use `@Ineject` in these circumstances to specify the correct token to inject. The error needs to be improved, and we are working on that for v5, but that is essentially what the error is trying to tell you.
