### ISSUE TITLE
I can't install aio

### ISSUE THREAD

**Issue by baihech** [angular/angular#18069]
## I'm submitting a...
<pre><code>
[ x] Support request 
</code></pre>

## Current behavior
I can't install aio,when I run `yarn install`,it can't install node-sass,and the ‘node_modules/node-sass’ folder does not exist.But I can add global node-sass.
## Environment
<pre><code>
- Node version: v8.1.3
- Yarn version:0.24.5
- Platform:  Windows10
</code></pre>
##Log 
```
[4/4] Building fresh packages...
[1/1] ⡀ node-sass: command clean []
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
warning Error running install script for optional dependency: "C:\\git\\angular\\aio\\node_modules\\node-sass: Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
Arguments: /d /s /c node scripts/build.js
Directory: C:\\git\\angular\\aio\\node_modules\\node-sass
Output:
Building: C:\\Program Files\\nodejs\\node.exe C:\\git\\angular\\aio\\node_modules\\node-gyp\\bin\\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\\\Program Files\\\\nodejs\\\\node.exe',\ngyp verb cli   'C:\\\\git\\\\angular\\\\aio\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.1
gyp info using node@8.1.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing \"build\" directory
gyp verb command configure []
gyp verb check python checking for Python executable \"python2\" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\\git\\angular\\aio\\node_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (C:\\git\\angular\\aio\\node_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (C:\\git\\angular\\aio\\node_modules\\which\\which.js:80:29)
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\which\\which.js:89:16
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\\git\\angular\\aio\\node_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (C:\\git\\angular\\aio\\node_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (C:\\git\\angular\\aio\\node_modules\\which\\which.js:80:29)
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\which\\which.js:89:16
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable \"python\" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\\git\\angular\\aio\\node_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (C:\\git\\angular\\aio\\node_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (C:\\git\\angular\\aio\\node_modules\\which\\which.js:80:29)
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\which\\which.js:89:16
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\\git\\angular\\aio\\node_modules\\which\\which.js:13:12)
gyp verb `which` failed     at F (C:\\git\\angular\\aio\\node_modules\\which\\which.js:68:19)
gyp verb `which` failed     at E (C:\\git\\angular\\aio\\node_modules\\which\\which.js:80:29)
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\which\\which.js:89:16
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\isexe\\index.js:42:5
gyp verb `which` failed     at C:\\git\\angular\\aio\\node_modules\\isexe\\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb could not find \"python\". checking python launcher 
gyp verb could not find \"python\". guessing location 
gyp verb ensuring that file exists: C:\\Python27\\python.exe
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\\git\\angular\\aio\\node_modules\\node-gyp\\lib\\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\\git\\angular\\aio\\node_modules\\node-gyp\\lib\\configure.js:508:16)
gyp ERR! stack     at C:\\git\\angular\\aio\\node_modules\\graceful-fs\\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\git\\\\angular\\\\aio\\\\node$ node tools/cli-patches/patch.js && uglifyjs node_modules/lunr/lunr.js -c -m -o src/assets/js/lunr.min.js --source-map
'patch' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'patch' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'patch' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'patch' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

**Comment by gkalpak** [comment]
I haven't tried with these versions, but this usually means you need to rebuild node-sass.
Try running `npm rebuild node-sass` first.

**Comment by baihech** [comment]
@gkalpak The ‘node_modules/node-sass’ folder **does not exist**，so invalid running `npm rebuild node-sass`

**Comment by baihech** [comment]
How to avoid this situation？

**Comment by gkalpak** [comment]
I run `yarn install` with the same versions and it worked.
From the log, it seems that it can't find python. Try adding it to your PATH (or setting the PYTHON env variable).

**Comment by IgorMinar** [comment]
Hello, I'm confident that this is an issue with your local environment. I recommend you try to reinstall yarn (use version 0.24.6 or newer) and verify that python is available on your machine.
