### ISSUE TITLE
Unit test of ngModel fails with latest zone.js dependency

### ISSUE THREAD

**Issue by shekhargulati** [angular/angular#18091]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I created a simple unit test for ngModel behavior as shown below.

app.componenent.ts

```ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  title = 'hello';

  constructor() {
  }

}
```
app.component.html

```ts
<div>
    <input type="text" [(ngModel)]="title">
    <h2>{{title}}</h2>
</div>
```

app.component.spec.ts

```ts
import { FormsModule } from '@angular/forms';
import { TestBed, async } from '@angular/core/testing';

import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [FormsModule],
      declarations: [
        AppComponent
      ],
    }).compileComponents();
  }));

  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));
});

```

When running the test `ng test` with latest ng-cli, it fails with following error. Please note application works but only test fails.

```
	TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
	    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/vendor.bundle.js:3636:38)
	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2814:51)
	    at Object.onScheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2710:29)
	    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2814:51)
	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2645:43)
	    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleEventTask (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:2671:25)
	    at HTMLInputElement.addEventListener (http://localhost:9876/_karma_webpack_/polyfills.bundle.js:3971:29)
	    at DomEventsPlugin.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DomEventsPlugin.addEventListener (http://localhost:9876/_karma_webpack_/vendor.bundle.js:61779:17)
	    at EventManager.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.EventManager.addEventListener (http://localhost:9876/_karma_webpack_/vendor.bundle.js:61117:23)
	    at EmulatedEncapsulationDomRenderer2.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DefaultDomRenderer2.listen (http://localhost:9876/_karma_webpack_/vendor.bundle.
```

## Expected behavior
The test should pass. I tested the same with older version of Angular and it worked.

On debugging I could find that latest version of zone.js i.e. `0.8.13` is responsible for it. I downgraded the version to 0.8.11 and test started passing.

## Minimal reproduction of the problem with instructions

Create a new project using latest ng-cli and replace the app.component.ts, app.component.html, and app.component.spec.ts with the ones mentioned above.

The version of ng-cli 

```
@angular/cli: 1.2.1
node: 7.4.0
os: darwin x64
@angular/animations: 4.2.6
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.1
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6
```

**Comment by pkozlowski-opensource** [comment]
This is tracked in https://github.com/angular/zone.js/issues/832
