### ISSUE TITLE
Node-modules automatically not installed in the new app

### ISSUE THREAD

**Issue by Shayanch** [angular/angular#18262]
## Current behavior

C:\Users\W10\Desktop>ng serve
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (C:\Users\W10\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\W10\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

When i install the node-modules it will run successfully . 
So it is irritating , install it manually again and again for new app.
help me out

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular-cli/issues/7043

**Comment by Shayanch** [comment]
nothing happen having same issue
