### ISSUE TITLE
Moving from Angular 2 to 4, I can compile, but errors out on page load

### ISSUE THREAD

**Issue by darrenbrett** [angular/angular#18437]
My dev environment:
MacBook Air
OS X El Capitan 10.11.6
@angular/cli: 1.2.0
node: 7.4.0
os: darwin x64
IDE: VSCode

After upgrading from Angular 2.3 to 4, and making numerous tweaks, I'm able to get the app to compile. 

However, the app errors out on page load, with this error:

> zone.js:654 Unhandled Promise rejection: Cannot set property '__listeners' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property '__listeners' of undefined

The full error info I see in the console is:

> Unhandled Promise rejection: Cannot set property '__listeners' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property '__listeners' of undefined
>     at Function.bind (app.event-handler.ts:737)
>     at createClass (core.es5.js:10851)
>     at createDirectiveInstance (core.es5.js:10675)
>     at createViewNodes (core.es5.js:12024)
>     at createRootView (core.es5.js:11929)
>     at callWithDebugContext (core.es5.js:13060)
>     at Object.debugCreateRootView [as createRootView] (core.es5.js:12521)
>     at ComponentFactory_.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactory_.create (core.es5.js:9866)
>     at ComponentFactoryBoundToModule.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactoryBoundToModule.create (core.es5.js:3447)
>     at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap (core.es5.js:5030) TypeError: Cannot set property '__listeners' of undefined
>     at Function.bind (http://localhost:4200/main.bundle.js:858:27)
>     at createClass (http://localhost:4200/vendor.bundle.js:105239:41)
>     at createDirectiveInstance (http://localhost:4200/vendor.bundle.js:105063:37)
>     at createViewNodes (http://localhost:4200/vendor.bundle.js:106412:49)
>     at createRootView (http://localhost:4200/vendor.bundle.js:106317:5)
>     at callWithDebugContext (http://localhost:4200/vendor.bundle.js:107448:42)
>     at Object.debugCreateRootView [as createRootView] (http://localhost:4200/vendor.bundle.js:106909:12)
>     at ComponentFactory_.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactory_.create (http://localhost:4200/vendor.bundle.js:104254:46)
>     at ComponentFactoryBoundToModule.webpackJsonp.../../../core/@angular/core.es5.js.ComponentFactoryBoundToModule.create (http://localhost:4200/vendor.bundle.js:97835:29)
>     at ApplicationRef_.webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:99418:57)

Since this error doesn't point me to any particular file, I'm not sure how to go about troubleshooting it. Is this a Zone.js issue? Something else?

**Comment by robwormald** [comment]
This looks Zone related - be sure you have the latest version and that's it's *correctly* installed

**Comment by darrenbrett** [comment]
Thanks for the feedback. How would I go about ensuring the latest version is "correctly" installed?

**Comment by JiaLiPassion** [comment]
@darrenbrett , could you provide a reproduce repo?
