### ISSUE TITLE
confusing error while running test.unit.cjs

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1881]
If you have a test which is failing then you get this error.

```
/Users/misko/.nvm/versions/node/v0.12.2/bin/node /Users/misko/work/angular/node_modules/gulp/bin/gulp.js --color --gulpfile /Users/misko/work/angular/gulpfile.js test.unit.cjs
[13:31:41] Working directory changed to ~/work/angular
Dart SDK detected
[13:31:43] Using gulpfile ~/work/angular/gulpfile.js
[13:31:43] Starting 'build/clean.js'...
[13:31:43] Starting 'build/clean.tools'...
[13:31:43] Finished 'build/clean.tools' after 738 μs
[13:31:43] Starting 'build.tools'...
[13:31:43] Starting '!build.tools'...
[13:31:43] Finished 'build/clean.js' after 309 ms
[13:31:45] Finished '!build.tools' after 2.41 s
[13:31:45] Finished 'build.tools' after 2.41 s
[13:31:45] Starting 'test.unit.cjs'...
[13:31:45] Starting '!build.js.cjs'...
Tree diff:          funnel-output_path-2kDwRVsn.tmp, duration:    19ms,   273 changes detected (files:   273, directories:  166)
Tree diff:          funnel-output_path-2kDwRVsn.tmp, duration:    16ms,    50 changes detected (files:    50, directories:  166)
Tree diff:                   funnel-dest_EFW5yV.tmp, duration:    34ms,   729 changes detected (files:   729, directories:   87)

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
DiffingTSCompiler                             | 23227ms             
DiffingTraceurCompiler                        | 3856ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
DiffingTSCompiler (1)                         | 23227ms             
DiffingTraceurCompiler (1)                    | 3856ms              

creating node_modules symlink hack
creating link dist/js/cjs/node_modules/angular2 ../angular2
creating link dist/js/cjs/node_modules/benchmarks ../benchmarks
creating link dist/js/cjs/node_modules/benchmarks_external ../benchmarks_external
creating link dist/js/cjs/node_modules/benchpress ../benchpress
creating link dist/js/cjs/node_modules/examples ../examples
creating link dist/js/cjs/node_modules/rtts_assert ../rtts_assert
[13:32:13] Finished '!build.js.cjs' after 28 s
[13:32:13] Starting 'test.unit.cjs/ci'...
F

Failures: 
1) injector resolve should resolve forward references
1.1) TypeError: undefined is not a function
    TypeError: undefined is not a function
        at /Users/misko/Dropbox/work/angular/dist/js/cjs/angular2/test/di/injector_spec.js:330:13
        at FunctionWrapper.apply (/Users/misko/Dropbox/work/angular/dist/js/cjs/angular2/src/facade/lang.js:228:64)
        at FunctionWithParamTokens.execute (/Users/misko/Dropbox/work/angular/dist/js/cjs/angular2/src/test_lib/test_injector.js:138:21)
        at Object.<anonymous> (/Users/misko/Dropbox/work/angular/dist/js/cjs/angular2/src/test_lib/test_lib.js:183:8)

1 spec, 1 failure
Finished in 0.012 seconds
[13:32:14] 'test.unit.cjs/ci' errored after 884 ms
[13:32:14] Error: 1
    at formatError (/Users/misko/Dropbox/work/angular/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/misko/Dropbox/work/angular/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/misko/Dropbox/work/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/misko/Dropbox/work/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/misko/Dropbox/work/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/misko/Dropbox/work/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at ChildProcess.<anonymous> (/Users/misko/Dropbox/work/angular/gulpfile.js:451:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
Error running task sequence: { task: 'test.unit.cjs/ci',
  message: 'test.unit.cjs/ci callback',
  duration: 0.884107958,
  hrDuration: [ 0, 884107958 ],
  err: 1 }
```

**Comment by vicb** [comment]
sounds like an issue with `inject()`. Is it possible to see the test source ?

**Comment by mhevery** [comment]
@vicb the issues is that when the test fails, it than causes gulp to generate stack trace which is confusing and not relevant.

**Comment by IgorMinar** [comment]
this is an unwanted side-effect of @mhevery's 4f2b9a4c283225e4a1e85eea3e95bc4cbc1349b5

I have a fix in progress...

**Comment by caitp** [comment]
Igor, the simplest fix is to just bind the done callback with a null first argument, or else wrap calling done in a closure. (Right now, the done callback is just used as the close event handler, and gulp eats the non-0 exit code)

**Comment by caitp** [comment]
I do this in my follow-up PR sing tests for the chokidar thing, so there is a fix available already

**Comment by caitp** [comment]
I guess there are a few cases in the gulpfile where calling the done function is already wrapped in a closure, and the exit code is explicitly passed... so all that's needed is to not pass it =)

**Comment by IgorMinar** [comment]
@caitp I just came across your bind(null, null) approach. it breaks the ci. my proposed fix is in #1892

**Comment by caitp** [comment]
yes, I just tried your Error fix locally and it works well enough (I think the stack trace is kind of pointless in this case, but what can you do).

**Comment by IgorMinar** [comment]
I don't have a way to stop gulp from printing the stack trace, while having
it exit with non-zero error code and also executing cleanup. So while the
extra stack trace is not great, it's a  trade off.
