### ISSUE TITLE
How can this issue be solved please

### ISSUE THREAD

**Issue by clementcrownrise** [angular/angular#18911]
$ npm serve
module.js:471
    throw err;
    ^

Error: Cannot find module 'buffer-shims'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Double Edge\AppData\Roaming\npm\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:36:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Double Edge@DoubleEdge MINGW64 ~/angular

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by robwormald** [comment]
See: https://github.com/angular/angular-cli/issues/3131

You likely have a stale dependency in your node modules. Try removing the folder and reinstalling.

In the future, please don't post support requests on GitHub.
