### ISSUE TITLE
build error: "SyntaxError: Unexpected token �"

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#1901]
If one of our build plugins throw an error, the error gets mangled by `source-map-support` installed by `ts2dart`.

```
08:41:28:angular (speedup-broccoli-typescript)$ gulp build.js.dev
Dart SDK detected
[08:47:52] Using gulpfile ~/Dev/angular/gulpfile.js
[08:47:52] Starting 'build/clean.js'...
[08:47:52] Finished 'build/clean.js' after 3.31 ms
[08:47:52] Starting 'build.js.dev'...
[08:47:52] Starting 'build/clean.tools'...
[08:47:52] Finished 'build/clean.tools' after 739 μs
[08:47:52] Starting 'build.tools'...
[08:47:52] Starting '!build.tools'...
[08:47:54] Finished '!build.tools' after 2.83 s
[08:47:54] Finished 'build.tools' after 2.83 s
[08:47:54] Starting 'broccoli.js.dev'...
[08:47:54] Starting '!broccoli.js.dev'...
Tree diff:          funnel-output_path-r5hCLPbt.tmp, duration:    21ms,   312 changes detected (files:   312, directories:  217)
Tree diff:          funnel-output_path-r5hCLPbt.tmp, duration:    17ms,    50 changes detected (files:    50, directories:  217)
TypeError: [DiffingTSCompiler]: Cannot read property 'snapshot' of undefined
[08:47:58] '!broccoli.js.dev' errored after 3.08 s
[08:47:58] SyntaxError: Unexpected token �
    at Object.parse (native)
    at new SourceMapConsumer (/Users/iminar/Dev/angular/node_modules/ts2dart/node_modules/source-map-support/node_modules/source-map/lib/source-map/source-map-consumer.js:50:24)
    at mapSourcePosition (/Users/iminar/Dev/angular/node_modules/ts2dart/node_modules/source-map-support/source-map-support.js:120:14)
    at wrapCallSite (/Users/iminar/Dev/angular/node_modules/ts2dart/node_modules/source-map-support/source-map-support.js:270:20)
    at /Users/iminar/Dev/angular/node_modules/ts2dart/node_modules/source-map-support/source-map-support.js:304:26
    at Array.map (native)
    at Function.prepareStackTrace (/Users/iminar/Dev/angular/node_modules/ts2dart/node_modules/source-map-support/source-map-support.js:303:24)
    at /Users/iminar/Dev/angular/angular_builder.ts:92:18
    at lib$rsvp$$internal$$tryCatch (/Users/iminar/Dev/angular/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/iminar/Dev/angular/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/iminar/Dev/angular/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$$internal$$publishRejection (/Users/iminar/Dev/angular/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:415:7)
    at lib$rsvp$asap$$flush (/Users/iminar/Dev/angular/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
[08:47:58] 'build.js.dev' errored after 5.91 s
```

I'm not sure if this is an issue with `source-map-support`, `ts2dart` or something else, but it's quite concerning that `ts2dart` can cause this issue in our build process.

**Comment by IgorMinar** [comment]
@mprobst do you have any insight into this? or did alex setup the source-map-support?

**Comment by mprobst** [comment]
@IgorMinar I sent [a pull request](https://github.com/evanw/node-source-map-support/pull/48) for `node-source-map-support` to fix the issue. [My fork of the repo](http://github.com/mprobst/node-source-map-support) has the correct fix, but I hope the pull request closing the issue should go in soon. Let's wait a couple of days and see if it's accepted, otherwise switch to the fork.

**Comment by IgorMinar** [comment]
the PR was merged in

**Comment by mprobst** [comment]
It was. However even before that, we had depended on a fixed, forked
version of the library. Is it possible that there's an outdated library in
your installation?

Igor Minar <notifications@github.com> schrieb am Mi., 20. Mai 2015 07:04:

**Comment by IgorMinar** [comment]
nevermind! I didn't notice that we were depending on your fork already. all
good

**Comment by mprobst** [comment]
OK, closing the issue.
