### ISSUE TITLE
5.0.0-beta.6 cannot be bundled with Rollup & ClosureCompiler

### ISSUE THREAD

**Issue by steveblue** [angular/angular#19057]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Rollup and ClosureCompiler bundle and then optimize the build without warnings, but an error happens in the browser console from within the build. (Chrome Version 60.0.3112.113 (Official Build) (64-bit))

```
Unhandled Promise rejection: No NgModule metadata found for 'function (){}'.
  Evaluating http://localhost:4200/bundle.js
  Loading bundle ; Zone: <root> ; Task: Promise.then ; Value: Error: No NgModule metadata found for 'function (){}'.
  Evaluating http://localhost:4200/bundle.js
```

## Expected behavior

Rollup and ClosureCompiler should be able to interpret the output of `ngc`

## Minimal reproduction of the problem with instructions

```
$ git clone https://github.com/steveblue/angular2-rollup.git
$ git checkout feature/5.0.0
$ cd angular2-rollup && npm install
$ npm link
$ cd ../
$ mkdir test-app && cd test-app
$ ngr scaffold --angularVersion 5.0.0-beta.6 && npm install
$ ngr build prod --serve
```

## What is the motivation / use case for changing the behavior?

Angular should be able to be built and bundled with Rollup and ClosureCompiler similar to 4.0.0.

## Environment

<pre><code>
Angular version: 5.0.0-beta.6

Browser: Chrome Version 60.0.3112.113 (Official Build) (64-bit)

For Tooling issues:
- Node version: 6.9.0
- Platform:  MacOS

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Related https://github.com/angular/angular/issues/19022 ?

**Comment by steveblue** [comment]
Possibly @ericmartinezr it sounds like it may be a dupe or related. I am confused as to why the changes to `ngc` have not been outlined in the CHANGELOG for `beta` releases. My team has a custom build that relies on AOT and we cannot wait until GA to test if it works or not. What if there are changes that make it not compatible with Rollup? This happened before leading up to `4.0.0` when Angular team left circular imports in the AOT compiled code. We need to be able to test AOT during beta. This seems to be a recurring theme with `ngc`. Leading up to 2.0.0, even in RC it was near impossible to find documentation about how `ngc` worked.

**Comment by steveblue** [comment]
I did some further tests and was able to get `ngc` to compile, edited the bug because now there is a console error in the browser after the bundle is compiled.

**Comment by steveblue** [comment]
This bug is replicated in both the bundle Rollup creates and after the bundle is transpired and optimized by ClosureCompiler.

**Comment by steveblue** [comment]
I tried `angularCompilerOptions.skipMetadataEmit: false` and no change.

**Comment by steveblue** [comment]
I see metadata.json files in the compiled code like `app.module.metadata.json`, but I do not see the contents of the metadata in the bundle. I am looking for the metadata because it seems thats where the bundle fails at `getNgModuleMetadata`. 

Here is the full Stacktrace of the error. I am confused because the JitCompiler is being called, when I am expecting AOT. 
```
Unhandled Promise rejection: No NgModule metadata found for 'AppModule'.
  Evaluating http://localhost:4200/bundle.es2015.js
  Loading bundle ; Zone: <root> ; Task: Promise.then ; Value: Error: No NgModule metadata found for 'AppModule'.
  Evaluating http://localhost:4200/bundle.es2015.js
  Loading bundle
    at NgModuleResolver.resolve (bundle.es2015.js:9476)
    at CompileMetadataResolver.getNgModuleMetadata (bundle.es2015.js:7329)
    at JitCompiler._loadModules (bundle.es2015.js:14183)
    at JitCompiler._compileModuleAndComponents (bundle.es2015.js:14166)
    at JitCompiler.compileModuleAsync (bundle.es2015.js:14135)
    at CompilerImpl.compileModuleAsync (bundle.es2015.js:24294)
    at PlatformRef_._bootstrapModuleWithZone (bundle.es2015.js:17834)
    at PlatformRef_.bootstrapModule (bundle.es2015.js:17829)
    at eval (bundle.es2015.js:32775)
    at Object.eval (bundle.es2015.js:32777) Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (http://localhost:4200/bundle.es2015.js:9476:23)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/bundle.es2015.js:7329:45)
    at JitCompiler._loadModules (http://localhost:4200/bundle.es2015.js:14183:53)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/bundle.es2015.js:14166:36)
    at JitCompiler.compileModuleAsync (http://localhost:4200/bundle.es2015.js:14135:37)
    at CompilerImpl.compileModuleAsync (http://localhost:4200/bundle.es2015.js:24294:32)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/bundle.es2015.js:17834:25)
    at PlatformRef_.bootstrapModule (http://localhost:4200/bundle.es2015.js:17829:21)
    at eval (http://localhost:4200/bundle.es2015.js:32775:26)
    at Object.eval (http://localhost:4200/bundle.es2015.js:32777:2)
```

**Comment by steveblue** [comment]
OK, this is my mistake. I should be using `platformBrowser().bootstrapModuleFactory` still it seems.

**Comment by kirakishin** [comment]
Hello, 
my issue was apparently related to the angular compiler 1.5, it doesn't works if i manualy bootstrap with 2 statements : 
```typescript
const platform = platformBrowserDynamic();
platform.bootstrapModule(AppModule);
```

i must use : 
```typescript
platformBrowserDynamic().bootstrapModule(AppModule);
```

sorry about time
