### ISSUE TITLE
build(aio) Running yarn docs in aio directory fails 

### ISSUE THREAD

**Issue by kirtangajjar** [angular/angular#19130]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Here is the complete output of `yarn docs`

```
yarn docs v0.27.5
$ rimraf src/generated/{docs,*.json}
$ dgeni ./tools/transforms/angular.io-package
info:    running processor: readFilesProcessor
info:    running processor: extractJSDocCommentsProcessor
info:    running processor: collectExamples
info:    running processor: readTypeScriptModules
info:    running processor: linkInheritedDocs
info:    running processor: parseTagsProcessor
info:    running processor: extractTagsProcessor
info:    running processor: codeNameProcessor
info:    running processor: createOverviewDump
info:    running processor: convertPrivateClassesToInterfacesProcessor
info:    running processor: mergeDecoratorDocs
info:    running processor: extractDecoratedClassesProcessor
info:    running processor: markBarredODocsAsPrivate
info:    running processor: computeIdsProcessor
info:    running processor: filterContainedDocs
info:    running processor: filterPrivateDocs
info:    running processor: simplifyMemberAnchors
info:    running processor: computePathsProcessor
info:    running processor: generateApiListDoc
info:    running processor: addNotYetDocumentedProperty
info:    running processor: matchUpDirectiveDecorators
info:    running processor: processNavigationMap
info:    running processor: renderDocsProcessor
info:    running processor: unescapeCommentsProcessor
info:    running processor: inlineTagProcessor
info:    running processor: renderExamples
info:    running processor: copyContentAssetsProcessor
info:    running processor: postProcessHtml
info:    running processor: computeSearchTitleProcessor
info:    running processor: generateKeywordsProcessor
info:    running processor: checkUnbalancedBackTicks
info:    running processor: fixInternalDocumentLinks
info:    running processor: checkAnchorLinksProcessor
warn:    Dangling Links Found in "guide/aot-compiler.json":
 - generated/zips/toh-pt6/toh-pt6.zip
warn:    Dangling Links Found in "guide/quickstart.json":
 - generated/zips/cli-quickstart/cli-quickstart.zip
warn:    Dangling Links Found in "guide/webpack.json":
 - generated/zips/webpack/webpack.zip
warn:    Dangling Links Found in "docs.json":
 - generated/live-examples/quickstart/eplnkr.html
error:   Error: 4 unmatched links
    at Object.$process (/Users/apple/code/angular/aio/node_modules/dgeni-packages/base/processors/checkAnchorLinks.js:106:17)
    at /Users/apple/code/angular/aio/node_modules/dgeni/lib/Dgeni.js:179:54
    at _fulfilled (/Users/apple/code/angular/aio/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/apple/code/angular/aio/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/apple/code/angular/aio/node_modules/q/q.js:796:13)
    at /Users/apple/code/angular/aio/node_modules/q/q.js:604:44
    at runSingle (/Users/apple/code/angular/aio/node_modules/q/q.js:137:13)
    at flush (/Users/apple/code/angular/aio/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error:   Error processing docs:  Error: 4 unmatched links
    at Object.$process (/Users/apple/code/angular/aio/node_modules/dgeni-packages/base/processors/checkAnchorLinks.js:106:17)
    at /Users/apple/code/angular/aio/node_modules/dgeni/lib/Dgeni.js:179:54
    at _fulfilled (/Users/apple/code/angular/aio/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/apple/code/angular/aio/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/apple/code/angular/aio/node_modules/q/q.js:796:13)
    at /Users/apple/code/angular/aio/node_modules/q/q.js:604:44
    at runSingle (/Users/apple/code/angular/aio/node_modules/q/q.js:137:13)
    at flush (/Users/apple/code/angular/aio/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/Users/apple/code/angular/aio/node_modules/q/q.js:155
                throw e;
                ^

Error: 4 unmatched links
    at Object.$process (/Users/apple/code/angular/aio/node_modules/dgeni-packages/base/processors/checkAnchorLinks.js:106:17)
    at /Users/apple/code/angular/aio/node_modules/dgeni/lib/Dgeni.js:179:54
    at _fulfilled (/Users/apple/code/angular/aio/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/apple/code/angular/aio/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/apple/code/angular/aio/node_modules/q/q.js:796:13)
    at /Users/apple/code/angular/aio/node_modules/q/q.js:604:44
    at runSingle (/Users/apple/code/angular/aio/node_modules/q/q.js:137:13)
    at flush (/Users/apple/code/angular/aio/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error Command failed with exit code 1.
```

## Expected behavior
Generate docs successfully :/

## Minimal reproduction of the problem with instructions
1. Clone the repo. 
2. cd into the `aio` folder.
3. run `yarn docs`

## Environment

<pre><code>
Angular version: 4.4.x/master

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 7.5.0
- Platform: Mac

</code></pre>

**Comment by gkalpak** [comment]
You should run `yarn setup` first (`yarn setup` also run `yarn docs` at the end).
Take a look in [aio/README.md][1] for a list of available commands.

BTW, yarn@0.27.5 has a bug that will bite you down the road. See #18488 for more details.

[1]: https://github.com/angular/angular/blob/master/aio/README.md

**Comment by kirtangajjar** [comment]
@gkalpak Thanks. Can you add to documentation? I didn't know you had to run it before running `npm docs`. Maybe it'll help somebody in future

**Comment by gkalpak** [comment]
@kirtangajjar, what do you have in mind. What documentation should this be added to? This is only needed for people that try to build the aio project themselves (and that is why we have it in `aio/README.md`).
