### ISSUE TITLE
Exception in language-service in getExternalFiles

### ISSUE THREAD

**Issue by RyanCavanaugh** [angular/angular#19325]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
```
Info 25   [15:6:34.171] A plugin threw an exception in getExternalFiles: TypeError: Cannot read property 'replace' of undefined
Info 26   [15:6:34.202] TypeError: Cannot read property 'replace' of undefined
    at normalizeSlashes (C:\github\TypeScript\built\local\tsserver.js:2699:20)
    at getNormalizedPathComponents (C:\github\TypeScript\built\local\tsserver.js:2853:16)
    at getNormalizedAbsolutePath (C:\github\TypeScript\built\local\tsserver.js:2864:52)
    at Object.toPath (C:\github\TypeScript\built\local\tsserver.js:1471:15)
    at toPath (C:\github\TypeScript\built\local\tsserver.js:70380:23)
    at Object.getSourceFile (C:\github\TypeScript\built\local\tsserver.js:70801:40)
    at TypeScriptServiceHost.get [as reflectorHost] (c:\github\angular2-seed\node_modules\@angular\language-service\bundles\language-service.umd.js:52990:58)
    at TypeScriptServiceHost.get [as staticSymbolResolver] (c:\github\angular2-seed\node_modules\@angular\language-service\bundles\language-service.umd.js:53033:84)
    at TypeScriptServiceHost.ensureAnalyzedModules (c:\github\angular2-seed\node_modules\@angular\language-service\bundles\language-service.umd.js:52786:60)
    at TypeScriptServiceHost.getAnalyzedModules (c:\github\angular2-seed\node_modules\@angular\language-service\bundles\language-service.umd.js:52780:21)
    at TypeScriptServiceHost.ensureTemplateMap (c:\github\angular2-seed\node_modules\@angular\language-service\bundles\language-service.umd.js:52910:40)
    at TypeScriptServiceHost.getTemplateReferences (c:\github\angular2-seed\node_modules\@angular\language-service\bundles\language-service.umd.js:52756:14)
    at Object.getExternalFiles (c:\github\angular2-seed\node_modules\@angular\language-service\bundles\language-service.umd.js:53221:21)
```

## Expected behavior

* No crash

## Minimal reproduction of the problem with instructions

Occurs when loading the language-service plugin with the angular2-seed project in Visual Studio

@chuckjaz I'm out of town this weekend but will put together a way to run this scenario from a commandline or something next week

**Comment by kyliau** [comment]
I ran into the same issue and took a quick look at the code. It looks like when `ReflectorHost` is first initialized, it is trying to create a context by calling `getScriptFileNames()`, but the result is an empty array.

https://github.com/angular/angular/blob/master/packages/language-service/src/typescript_host.ts#L360
