### ISSUE TITLE
AOT compilation on Windows searches for file in the wrong directory

### ISSUE THREAD

**Issue by navrudh** [angular/angular#19370]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

<pre><code>
"node_modules/.bin/ngc" -p tsconfig.aot.json

Error: Compilation failed. Resource file not found: d:/connectors-page.component.html
    at ModuleResolutionHostAdapter.readResource (d:\Workspaces\request-service\request-frontend\node_modules\@angular\compiler-cli\src\compiler_host.js:387:19)
    at CompilerHost.loadResource (d:\Workspaces\request-service\request-frontend\node_modules\@angular\compiler-cli\src\compiler_host.js:250:33)
    at Object.get (d:\Workspaces\request-service\request-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:25920:107)
    at DirectiveNormalizer._fetch (d:\Workspaces\request-service\request-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14255:43)
    at DirectiveNormalizer.normalizeTemplateOnly (d:\Workspaces\request-service\request-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14302:29)
    at DirectiveNormalizer.normalizeTemplate (d:\Workspaces\request-service\request-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:14286:36)
    at CompileMetadataResolver.loadDirectiveMetadata (d:\Workspaces\request-service\request-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:15318:75)
    at d:\Workspaces\request-service\request-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:15524:54
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (d:\Workspaces\request-service\request-frontend\node_modules\@angular\compiler\bundles\compiler.umd.js:15523:41)
Compilation failed
</code></pre>

## Expected behavior

AOT Compilation Successful

## Environment

<pre><code>
Angular version: 4.4.3

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.5.0
- Platform: Windows 7

Others:

</code></pre>

**Comment by Toxicable** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
