### ISSUE TITLE
Service Worker: Can't display push notification

### ISSUE THREAD

**Issue by webmaxru** [angular/angular#19488]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Client': PushMessageData object could not be cloned.
    at clients.forEach.client (https://ngsw.surge.sh/ngsw-worker.js:2199:44)
    at Array.forEach (<anonymous>)
    at Driver.broadcast (https://ngsw.surge.sh/ngsw-worker.js:2199:17)
    at <anonymous>
```

## Expected behavior
Show web push notification

## Minimal reproduction of the problem with instructions
Click "Subscribe to push" and wait some seconds. Or use "Push" on "Application" tab of DevTools.
Most likely this is because the object passed to `postMessage`has methods, not only the properties. Methods have to be removed:
https://stackoverflow.com/a/42376465

CC: @alxhub 

## What is the motivation / use case for changing the behavior?
Fix the bug

## Environment

<pre><code>
Angular version: 5.0.0.rc.0

Browser:
- [x] Chrome (desktop) version 61
 

</code></pre>

**Comment by webmaxru** [comment]
Fixed by https://github.com/angular/angular/pull/19764/
