### ISSUE TITLE
5.0.0-rc.0, ngc throws Could not resolve module @angular/core on windows

### ISSUE THREAD

**Issue by kemsky** [angular/angular#19492]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
ngc throws exception:
```
[01:57:35] Error: Error: Could not resolve module @angular/core
[01:57:35]     at StaticSymbolResolver.getSymbolByModule (D:\Dev\Project\node_modules\@angular\compiler\bundles\compiler.umd.js:31256:30)
[01:57:35]     at StaticReflector.findDeclaration (D:\Dev\Project\node_modules\@angular\compiler\bundles\compiler.umd.js:29723:63)
[01:57:35]     at StaticReflector.initializeConversionMap (D:\Dev\Project\node_modules\@angular\compiler\bundles\compiler.umd.js:29988:36)
[01:57:35]     at new StaticReflector (D:\Dev\Project\node_modules\@angular\compiler\bundles\compiler.umd.js:29673:14)
[01:57:35]     at Object.createAotCompiler (D:\Dev\Project\node_modules\@angular\compiler\bundles\compiler.umd.js:31496:44)
[01:57:35]     at AngularCompilerProgram._createProgramWithBasicStubs (D:\Dev\Project\node_modules\@angular\compiler-cli\src\transformers\program.js:304:37)
[01:57:35]     at AngularCompilerProgram.initSync (D:\Dev\Project\node_modules\@angular\compiler-cli\src\transformers\program.js:278:23)
[01:57:35]     at AngularCompilerProgram.get [as tsProgram] (D:\Dev\Project\node_modules\@angular\compiler-cli\src\transformers\program.js:237:22)
[01:57:35]     at AngularCompilerProgram.getTsOptionDiagnostics (D:\Dev\Project\node_modules\@angular\compiler-cli\src\transformers\program.js:75:20)
[01:57:35]     at defaultGatherDiagnostics (D:\Dev\Project\node_modules\@angular\compiler-cli\src\perform_compile.js:170:34)
```
5.0.0-beta7 works fine on the same project.

## Expected behavior
no error

## Environment

<pre><code>
Angular version: 5.0.0-rc.0

For Tooling issues:
- Node version: 8.4.0
- Platform:  Windows

**Comment by alexzuza** [comment]
@tbosch I think the problem here is that new `TsCompilerAotCompilerTypeCheckHostAdapter`  [doesn't replace](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/compiler_host.ts#L112-L113) `\` to `/` for `containingFile` variable as [it was](https://github.com/angular/angular/blob/master/packages/compiler-cli/src/compiler_host.ts#L344-L346) in old CompilerHost so typescript can't find module because it uses `ts.directorySeparator` equals `/` to find `containingFolder`.

Possible workaround is using `paths` options in tsconfig:

```
{
  "compilerOptions": {
    ...
    "baseUrl": ".",
    "paths": {
      "@angular/core": ["node_modules/@angular/core"]
    }
  },
```

**Comment by petebacondarwin** [comment]
You want to be using the vital [`canonical-path`](https://www.npmjs.com/package/canonical-path) library :-)

**Comment by tbosch** [comment]
See this [commit](https://github.com/angular/angular/commit/6c77d7182ad86ae3b4fc6c60cf4737533b84ac4c) that originally introduced the windows compatibility.

**Comment by petebacondarwin** [comment]
It is much better to stick with alway using forward slashes in node if you can. A forward slash will be converted to a back slash for the OS on Windows but the reverse does not happen. So you end up with crazy situation where:  `path.join('a','b/c')` will end up being `a/b/c` on unix and `a\b\c` on Windows. The `canonical-path` library means that in your code you can just assume that all paths are always forward slash separated and then go to the pub early.
