### ISSUE TITLE
Angular 5 compiler can't find the `.css` files next to source `.ts` files 

### ISSUE THREAD

**Issue by tinayuangao** [angular/angular#19765]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
</code></pre>

## Current behavior
The build doesn't work with Angular 5. It was working with Angular4.
The issue is that we compile our TS files with the `@angular/compiler-cli`, but it ends up throwing an error that it can’t find the `.css` files next to the source `.ts` files. 

One example of failures:
```
Failed to compile select
Error: Error: Couldn't resolve resource chips.css relative to /usr/local/google/home/tinagao/WebstormProjects/caretaker/material2/src/lib/chips/chip-list.ts
    at /usr/local/google/home/tinagao/WebstormProjects/caretaker/material2/node_modules/@angular/compiler/bundles/compiler.umd.js:29163:27
    at Array.forEach (native)
    at /usr/local/google/home/tinagao/WebstormProjects/caretaker/material2/node_modules/@angular/compiler/bundles/compiler.umd.js:29160:43
    at Array.forEach (native)
    at AotCompiler.findGeneratedFileNames (/usr/local/google/home/tinagao/WebstormProjects/caretaker/material2/node_modules/@angular/compiler/bundles/compiler.umd.js:29153:25)
    at Object.findGeneratedFileNames (/usr/local/google/home/tinagao/WebstormProjects/caretaker/material2/node_modules/@angular/compiler-cli/src/transformers/program.js:496:82)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (/usr/local/google/home/tinagao/WebstormProjects/caretaker/material2/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:327:55)
    at findSourceFile (/usr/local/google/home/tinagao/WebstormProjects/caretaker/material2/node_modules/typescript/lib/typescript.js:70246:29)
    at processImportedModules (/usr/local/google/home/tinagao/WebstormProjects/caretaker/material2/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile (/usr/local/google/home/tinagao/WebstormProjects/caretaker/material2/node_modules/typescript/lib/typescript.js:70274:17)
```

## Expected behavior
The build should work

## Minimal reproduction of the problem with instructions
1. Patch PR: https://github.com/angular/material2/pull/6018
2. run `npm install`
3. run `npm run demo-app`

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.5
- Platform:  Linux

Others:

</code></pre>

**Comment by chuckjaz** [comment]
The following changes need to be added https://github.com/chuckjaz/material2/commit/dea835046e22fc64e7267c533d61e6c2e90fc89e.

The compiler now validates the modules in compile by generating and type-checking the implied factory files. However, this means that we need to be able to find the referenced '.css' files. Since the '.css' files are generated into `dist` it means we need to know where that is. This is what the addition of `rootDirs` does.

We improved the metadata validation as well but it now reports that `styleTag` is invalid. Since `styleTag` is not intended to be used in a decorator, adding `@dynamic` to its comment silences this error.

Making these changes is not a complete fix as this uncovered a bug in `ngc` that #19770  fixes.
