### ISSUE TITLE
Component ngfactory sourcemap sources include links to root directory

### ISSUE THREAD

**Issue by igmdvc** [angular/angular#19861]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After AOT compilation, generated ngfactory component sourcemap sources property contain a directory entry (root directory):

AppComponent.ngfactory.js

`{"version":3,"file":"AppComponent.ngfactory.js","sourceRoot":"","sources":["AppComponent.ngfactory.ts","AppComponent.html","../../../"],"names":[],"mappings":";;;;;;;;;;;;;8DCAA,2EAAI,KAAA,wCAAW,MAAK,+BACpB,MAAA,6SAAe;mECDf,4KAAK","sourcesContent":["import * as i0 from '@angular/core';\ni0.ComponentFactory;\n","<h1>Hello BEDCA</h1>\n<router-outlet></router-outlet>","<app></app>"]}`

LoginComponent.ngfactory.js

`{"version":3,"file":"LoginComponent.ngfactory.js","sourceRoot":"","sources":["LoginComponent.ngfactory.ts","LoginComponent.html","../../../../"],"names":[],"mappings":";;;;;;;;;;;gECAA,oCACA;qECDA,2LAAc","sourcesContent":["import * as i0 from '@angular/core';\ni0.ComponentFactory;\n","WORLD\n","<ng-component></ng-component>"]}`

This provokes rollup to fail when bundling with enabled sourcemap, as it is comparing for the same source (root folder) different content The following error is shown:

`[!] Error: Multiple conflicting contents for sourcemap source undefined
Error: Multiple conflicting contents for sourcemap source undefined
    at error (/src/node_modules/rollup/dist/rollup.js:185:14)
    at line.forEach.segment (/src/node_modules/rollup/dist/rollup.js:9546:7)
    at Array.forEach (<anonymous>)
    at mappings.mappings.map.line (/src/node_modules/rollup/dist/rollup.js:9520:9)
    at Array.map (<anonymous>)
    at Link.traceMappings (/src/node_modules/rollup/dist/rollup.js:9517:34)
    at collapseSourcemaps (/src/node_modules/rollup/dist/rollup.js:9649:19)
    at transformBundle.then.code (/src/node_modules/rollup/dist/rollup.js:10232:13)
    at <anonymous>`

## Expected behavior
Sourcemap contains references to valid sources (ngfactory.ts and HTML template)

## Environment

<pre><code>
Angular version: 5.0.0-rc.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.7
- Platform:  Linux

Others:

</code></pre>

**Comment by igmdvc** [comment]
It seems the problem will be solved by this fix https://github.com/angular/angular/pull/19965
