### ISSUE TITLE
`ngc` will not report/recover from some errors

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#19951]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`ngc` will not report some errors correctly and recover from them.

## Expected behavior

`ngc` would report all errors correctly and recover from them.

## Minimal reproduction of the problem with instructions

- `git clone https://github.com/filipesilva/ngc-tsc-rebuild`
- `cd ngc-tsc-rebuild && npm i`
- `npm run ngc` or `npm run tsc`
- wait for the compilation to be complete
- comment out the whole contents of `./src/app.app.component.ts`
- hit save
- `ngc` will show `Message: Compilation complete. Watching for file changes.`, but `tsc` will show `src/app/app.module.ts(4,30): error TS2306: File 'D:/sandbox/ng-master-project/src/app/app.component.ts' is not a module.`
- uncomment out the whole contents of `./src/app.app.component.ts`
- `ngc` will show `Message: Emitted no files.`, `tsc` will show a successful compilation.
- add `console.log(1);` to `./src/app.app.component.ts` hit save again
- `ngc` will show `Message: Emitted no files.`, `tsc` will show a successful compilation.
- doing the same with `npm run ng -- serve --aot` will show the following error being thrown on program creation:
```
ERROR in Error: Unexpected value 'AppComponent in D:/sandbox/ng-master-project/src/app/app.component.ts' declared by the module 'AppModule in D:/sandbox/ng-master-project/src/app/app.module.ts'. Pl
ease add a @Pipe/@Directive/@Component annotation.
    at Error (native)
    at syntaxError (D:\work\cli\node_modules\@angular\compiler\bundles\compiler.umd.js:509:34)
    at D:\work\cli\node_modules\@angular\compiler\bundles\compiler.umd.js:15164:40
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (D:\work\cli\node_modules\@angular\compiler\bundles\compiler.umd.js:15146:54)
    at D:\work\cli\node_modules\@angular\compiler\bundles\compiler.umd.js:29999:70
    at Array.forEach (native)
    at analyzeFile (D:\work\cli\node_modules\@angular\compiler\bundles\compiler.umd.js:29978:53)
    at AotCompiler._analyzeFile (D:\work\cli\node_modules\@angular\compiler\bundles\compiler.umd.js:29202:17)
    at AotCompiler.findGeneratedFileNames (D:\work\cli\node_modules\@angular\compiler\bundles\compiler.umd.js:29218:42)
    at Object.findGeneratedFileNames (D:\work\cli\node_modules\@angular\compiler-cli\src\transformers\program.js:385:82)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (D:\work\cli\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:324:55)
    at findSourceFile (D:\work\cli\node_modules\typescript\lib\typescript.js:70782:29)
    at processImportedModules (D:\work\cli\node_modules\typescript\lib\typescript.js:70949:25)
    at findSourceFile (D:\work\cli\node_modules\typescript\lib\typescript.js:70830:17)
    at args (D:\work\cli\node_modules\typescript\lib\typescript.js:70719:85)
    at getSourceFileFromReferenceWorker (D:\work\cli\node_modules\typescript\lib\typescript.js:70692:34)
    at processSourceFile (D:\work\cli\node_modules\typescript\lib\typescript.js:70719:13)
    at processRootFile (D:\work\cli\node_modules\typescript\lib\typescript.js:70573:13)
    at D:\work\cli\node_modules\typescript\lib\typescript.js:69765:60
    at Object.forEach (D:\work\cli\node_modules\typescript\lib\typescript.js:1500:30)
    at Object.createProgram (D:\work\cli\node_modules\typescript\lib\typescript.js:69765:16)
    at AngularCompilerProgram._createProgramWithBasicStubs (D:\work\cli\node_modules\@angular\compiler-cli\src\transformers\program.js:429:29)
    at AngularCompilerProgram.loadNgStructureAsync (D:\work\cli\node_modules\@angular\compiler-cli\src\transformers\program.js:144:23)
    at AngularCompilerPlugin._createOrUpdateProgram (D:\work\cli\packages\@ngtools\webpack\src\angular_compiler_plugin.ts:254:34)
    at Promise.resolve.then (D:\work\cli\packages\@ngtools\webpack\src\angular_compiler_plugin.ts:542:29)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

## Environment

<pre><code>
Angular version: 5.0.0-rc.6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX   6.11.1
- Platform:   Windows

Others:

</code></pre>

/cc @tbosch

**Comment by tbosch** [comment]
I am seeing the following:

1. start `ngc` as above
2. touch `app.component.ts`, and wait for compilation to complete
3. comment it out and wait for compilation to complete
4. uncomment it and wait for compilation to complete

Error is shown: 
```
Error: Error: Debug Failure.
    at tryReuseStructureFromOldProgram (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/typescript/lib/typescript.js:69547:22)
    at Object.createProgram (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/typescript/lib/typescript.js:69310:34)
    at AngularCompilerProgram._createProgramWithBasicStubs (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/@angular/compiler-cli/src/transformers/program.js:429:29)
    at AngularCompilerProgram.initSync (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/@angular/compiler-cli/src/transformers/program.js:369:23)
    at AngularCompilerProgram.get [as tsProgram] (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/@angular/compiler-cli/src/transformers/program.js:346:22)
    at AngularCompilerProgram.getTsOptionDiagnostics (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/@angular/compiler-cli/src/transformers/program.js:104:20)
    at defaultGatherDiagnostics (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/@angular/compiler-cli/src/perform_compile.js:181:34)
    at Object.performCompilation (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/@angular/compiler-cli/src/perform_compile.js:138:51)
    at doCompilation (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/@angular/compiler-cli/src/perform_watch.js:160:47)
    at Timeout.recompile [as _onTimeout] (/Users/tbosch/projects/repro/issue-19951/ngc-tsc-rebuild/node_modules/@angular/compiler-cli/src/perform_watch.js:227:9)
```

**Comment by alexzuza** [comment]
The same as @filipesilva described. Windows 10
![ngc](https://user-images.githubusercontent.com/4223314/32071121-5e8547fa-ba9f-11e7-9446-ac32fb2739b0.png)

**Comment by tbosch** [comment]
Thanks @alexzuza. The fact that we show "Message: Emitted no files." seems to be windows as we incorrectly calculate the changes files (i.e. we think no file changed).

The problem with watching in the cli is because the cli is reusing a program that had errors, instead of discarding it.

The remaining problem with `Error: Error: Debug Failure.` still needs to be investigated.
