### ISSUE TITLE
[5.0.0-rc.9] provide a better message error when module doesn't exist

### ISSUE THREAD

**Issue by aitboudad** [angular/angular#20049]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`NoConflictStyleCompatibilityMode` has been removed in material2 and after upgrading my app I get the following error with `ng serve`
**Note**: The issue only raised when importing module with 
```ts
{ ngModule: NoConflictStyleCompatibilityMode }
```

```console
ERROR in TypeError: staticSymbol.assertNoMembers is not a function
    at AotSummaryResolver.resolveSummary (node_modules/@angular/compiler/bundles/compiler.umd.js:31928:22)
    at CompileMetadataResolver._loadSummary (node_modules/@angular/compiler/bundles/compiler.umd.js:14709:66)
    at CompileMetadataResolver.isDirective (node_modules/@angular/compiler/bundles/compiler.umd.js:15003:23)
    at CompileMetadataResolver._getTypeDescriptor (node_modules/@angular/compiler/bundles/compiler.umd.js:15269:18)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:15131:78
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (node_modules/@angular/compiler/bundles/compiler.umd.js:15114:49)
    at node_modules/@angular/compiler/bundles/compiler.umd.js:30090:70
    at Array.forEach (<anonymous>)
    at analyzeFile (node_modules/@angular/compiler/bundles/compiler.umd.js:30069:53)
    at AotCompiler._analyzeFile (node_modules/@angular/compiler/bundles/compiler.umd.js:29289:17)
    at AotCompiler.findGeneratedFileNames (node_modules/@angular/compiler/bundles/compiler.umd.js:29305:42)
    at Object.findGeneratedFileNames (node_modules/@angular/compiler-cli/src/transformers/program.js:387:82)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:325:55)
    at tryReuseStructureFromOldProgram (node_modules/typescript/lib/typescript.js:70032:28)
    at Object.createProgram (node_modules/typescript/lib/typescript.js:69763:34)
```

## Expected behavior

```console
ERROR in Error: Unexpected value 'NoConflictStyleCompatibilityMode in node_modules/@angular/material/core.d.ts' imported by the module 'AppModule in src/app/app.module.ts'. Please add a @NgModule annotation.
```

## Minimal reproduction of the problem with instructions

see https://github.com/aitboudad/ng-cli-19994

```ts
import { NoConflictStyleCompatibilityMode } from '@angular/material/core';
@NgModule({
  declarations: [],
  imports: [
    ...
    { ngModule: NoConflictStyleCompatibilityMode },
  ],
})
export class AppModule { }
```

## Environment

<pre><code>
Angular version: X.Y.Z

Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 61
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.6.0  
- Platform: Linux

- @angular/cli: 1.5.0-rc.8

**Comment by musasesay** [comment]
I have the same Issue

**Comment by musasesay** [comment]
ERROR in TypeError: staticSymbol.assertNoMembers is not a function
    at AotSummaryResolver.resolveSummary (C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler\bundles\compiler.umd.js:31928:22)
    at CompileMetadataResolver._loadSummary (C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler\bundles\compiler.umd.js:14709:66)
    at CompileMetadataResolver.isDirective (C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler\bundles\compiler.umd.js:15003:23)
    at CompileMetadataResolver._getTypeDescriptor (C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler\bundles\compiler.umd.js:15269:18)
    at C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler\bundles\compiler.umd.js:15131:78
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler\bundles\compiler.umd.js:15114:49)
    at visitLazyRoute (C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler\bundles\compiler.umd.js:29937:104)
    at AotCompiler.listLazyRoutes (C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler\bundles\compiler.umd.js:29905:20)
    at AngularCompilerProgram.listLazyRoutes (C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler-cli\src\transformers\program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\angularproject\basics-assignment-1-start\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (C:\angularproject\basics-assignment-1-start\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:246:66)
    at Promise.resolve.then.then (C:\angularproject\basics-assignment-1-start\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:542:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

webpack: Failed to compile.
