### ISSUE TITLE
Angular 5 production build issue

### ISSUE THREAD

**Issue by aishanu** [angular/angular#20095]
ERROR in ./node_modules/rxjs/_esm5/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined  at Object.getEffectiveTypeAnnotationNode (node_modules/typescript/lib/typescript.js:9341:17).

 at Object.forEach (/home/arpitha/Desktop/itrack-new/itrack-app/node_modules/typescript/lib/typescript.js:1506:30)
 @ ./node_modules/rxjs/_esm5/observable/bindCallback.js 2:0-68
 @ ./node_modules/rxjs/_esm5/add/observable/bindCallback.js
 @ ./node_modules/rxjs/_esm5/Rx.js
 @ ./src/app/service/interceptor.service.ts
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by aishanu** [comment]
I am getting prodction build issue after upgrading to Angular v5

**Comment by BartBurger** [comment]
Look for `import { Observable } from 'rxjs/Rx'` in your project and replace it with `import { Observable } from 'rxjs/Observable'`

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by rsaenen** [comment]
I had the same issue and I looked for all import from rxjs.

- Observable
- Subject
- Subscription
- ...

<kbd>Ctrl+F</kbd> for `import { x } from 'rxjs/'` or `import { x } from 'rxjs/Rx'`

**Comment by Anoop-Goudar** [comment]
Updating typescript to 2.6.1 will fix this issue, but we will have warning message as below

```
@angular/compiler-cli@5.0.0 requires typescript@'>=2.4.2 <2.5.0' but 2.6.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.5.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```

**Comment by maxguzeng** [comment]
this solve my issue~~!!

**Comment by vesrah** [comment]
Upgrading typescript didn't solve the issue for me, nor did updating the rxjs imports.

**Comment by sondreb** [comment]
I can also confirm that using the bindCallback operator on Observable will cause production build errors, unless TypeScript is upgraded above the "supported" version. It is not enough to simply upgrade global TypeScript to 2.6.1, also make sure you upgrade package.json or it won't work.

```
// Import example
import 'rxjs/add/observable/bindCallback';
```

```
// TypeScript example
Observable.bindCallback()
```

**Comment by klochko7** [comment]
I have the same error ..  I am using ..   Should I import  import "rxjs" ?

```
import { timeout } from 'rxjs/operator/timeout';
import { map } from 'rxjs/operator/map';

```

```
Error: ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (D:\tmp\ionic2\ezpart-mobile-svn\no
de_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (D:\tmp\ionic2\ezpart-mobile-svn\node_modu
les\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (D:\tmp\ionic2\ezpart-mobile
-svn\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\types
cript\lib\typescript.js:42959:28)
    at checkExpression (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typescript\
lib\typescript.js:42898:42)
    at checkExpressionCached (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\types
cript\lib\typescript.js:42779:38)
    at checkReturnStatement (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typesc
ript\lib\typescript.js:45418:54)
    at checkSourceElement (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typescri
pt\lib\typescript.js:46763:28)
    at Object.forEach (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typescript\l
ib\typescript.js:1506:30)
    at checkBlock (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typescript\lib\t
ypescript.js:44563:16)
 @ ./node_modules/rxjs/observable/bindNodeCallback.js 2:36-76
 @ ./node_modules/rxjs/add/observable/bindNodeCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./src/providers/loginProvider.ts
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (D:\tmp\ionic2\ezpart-mobile-svn\no
de_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (D:\tmp\ionic2\ezpart-mobile-svn\node_modu
les\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (D:\tmp\ionic2\ezpart-mobile
-svn\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\types
cript\lib\typescript.js:42959:28)
    at checkExpression (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typescript\
lib\typescript.js:42898:42)
    at checkExpressionCached (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\types
cript\lib\typescript.js:42779:38)
    at checkReturnStatement (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typesc
ript\lib\typescript.js:45418:54)
    at checkSourceElement (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typescri
pt\lib\typescript.js:46763:28)
    at Object.forEach (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typescript\l
ib\typescript.js:1506:30)
    at checkBlock (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\typescript\lib\t
ypescript.js:44563:16)
 @ ./node_modules/rxjs/observable/bindCallback.js 2:32-68
 @ ./node_modules/rxjs/add/observable/bindCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./src/providers/loginProvider.ts
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\@ionic\app-s
cripts\dist\util\errors.js:16:28)
    at callback (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\@ionic\app-scripts
\dist\webpack.js:121:28)
    at emitRecords.err (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\webpack\lib
\Compiler.js:269:13)
    at Compiler.emitRecords (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\webpac
k\lib\Compiler.js:375:38)
    at emitAssets.err (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\webpack\lib\
Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (D:\tmp\ionic2\ezpart-mobile-svn\node_module
s\webpack\lib\Compiler.js:368:12)
    at next (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\tapable\lib\Tapable.js
:218:11)
    at Compiler.compiler.plugin (D:\tmp\ionic2\ezpart-mobile-svn\node_modules\we
bpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (D:\tmp\ionic2\ezpart-mobile-svn\node_m
odules\tapable\lib\Tapable.js:222:13)
```

**Comment by lincolnthree** [comment]
@Anoop-Goudar Upgrading to TypeScript 2.6.1 also solved my issue. Thank you.

**Comment by subatomicglue** [comment]
When using `typescript 2.6.1` with `ng serve --aot`, I get this error when incrementally saving a `.html` or `.ts` file
```
ERROR in Error: Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
    at tryReuseStructureFromOldProgram (.../node_modules/typescript/lib/typescript.js:72100:26)
    at Object.createProgram (.../node_modules/typescript/lib/typescript.js:71808:34)
    at AngularCompilerProgram._updateProgramWithTypeCheckStubs (.../node_modules/@angular/compiler-cli/src/transformers/program.js:461:30)
    at .../node_modules/@angular/compiler-cli/src/transformers/program.js:149:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
Which the fix [here](https://github.com/angular/angular-cli/issues/8332#issuecomment-343574507) says to downgrade to `typescript 2.4.2`...

When using `typescript 2.4.2` with `ng build -prod`, I get  the error described above, which is of course:
```
ERROR in ./node_modules/rxjs/_esm5/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined at Object.getEffectiveTypeAnnotationNode (node_modules/typescript/lib/typescript.js:9341:17).
```
Which the fix [here](https://github.com/angular/angular/issues/20095#issuecomment-343062427) says to upgrade `typescript` to `2.6.1`.


So I am in a catch 22, where I need `typescript 2.4.2` for `ng serve --aot` and  `typescript 2.6.1` for `ng build --prod`.

**Comment by finalxcode** [comment]
my problem  is ngx-datatable,  after upgrade ngx-datatable to 11.0.4, i works

**Comment by bastienlemaitre** [comment]
Works with Typescript 2.4.2, i have replaced
```ts
import { Observable } from 'rxjs/Rx';
```
by
```ts
import { Observable } from 'rxjs/Observable';
```

**Comment by maiziheimei** [comment]
Yes, it solved by updating typescript's version

**For Exact version
npm install typescript@2.0.10 --save
**For latest release
npm install typescript@latest --save

**Comment by sburnicki** [comment]
I had this error when using
```typescript
import {pipe} from "rxjs/Rx";`
```
and needed to change it to 
```typescript
import {pipe} from "rxjs/util/pipe";
```

**Comment by iursevla** [comment]
I'm using only a single **BehaviorSubject** and the `first` method. 
How to replace it like:
`import { Observable } from 'rxjs/Rx';`
to
`import { Observable } from 'rxjs/Observable';`

If i try to replace
`import { BehaviorSubject } from 'rxjs/Rx';`
to
`import { BehaviorSubject } from 'rxjs/BehaviorSubject';`

it gives an error in the `.first` method  
![See image](https://image.prntscr.com/image/luhu9eKwRYO4z8LKSxeGuA.png)

**Comment by bastienlemaitre** [comment]
Yo need to import operators.

**Comment by iursevla** [comment]
@bastienlemaitre 
how so? (Sorry if it's a noob question)

`import { Operator } from 'rxjs/Operator';` ?? and then?

**Comment by bastienlemaitre** [comment]
Try this.
```ts
import 'rxjs/add/observable/first';
```

**Comment by iursevla** [comment]
I solved it by importing the operator as @bastienlemaitre said.
Like so:
```ts
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import 'rxjs/add/operator/first';
```

**Comment by giscafer** [comment]
I solved it by updating latest vesion

```ts
"@ionic/app-scripts": "^3.1.4",
"typescript": "^2.6.2",
```
and `import { x } from 'rxjs' replace width import { x } from 'rxjs/Rx'`

**Comment by subatomicglue** [comment]
With `typescript 2.6.2`, I still get the error when using `ng serve --aot`

```
ERROR in Error: Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
    at tryReuseStructureFromOldProgram (.../node_modules/typescript/lib/typescript.js:72296:26)
    at Object.createProgram (.../node_modules/typescript/lib/typescript.js:72004:34)
    at AngularCompilerProgram._updateProgramWithTypeCheckStubs (.../node_modules/@angular/compiler-cli/src/transformers/program.js:461:30)
    at .../node_modules/@angular/compiler-cli/src/transformers/program.js:149:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by PixeliGer** [comment]
This is my project config:

```
❯ ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.4
Node: 6.11.4
OS: darwin x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1 
```

I just removed or replaced every unnecesary or unnused `'rxjs'` import in my project but the error persist:

```ERROR in ./node_modules/rxjs/_esm5/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:9341:17)
    at assignContextualParameterTypes (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:41948:29)
    at checkExpressionWorker (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:42959:28)
    at checkExpression (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:42898:42)
    at checkExpressionCached (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:42779:38)
    at checkReturnStatement (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:45418:54)
    at checkSourceElement (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46763:28)
    at Object.forEach (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:1506:30)
    at checkBlock (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:44563:16)
    at checkSourceElement (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:41990:21)
    at checkDeferredNodes (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46828:25)
    at checkSourceFileWorker (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46863:17)
    at checkSourceFile (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46842:13)
    at Object.forEach (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:1506:30)
 @ ./node_modules/rxjs/_esm5/observable/bindNodeCallback.js 2:0-76
 @ ./node_modules/rxjs/_esm5/add/observable/bindNodeCallback.js
 @ ./node_modules/rxjs/_esm5/Rx.js
 @ ./node_modules/angular2-datatable/lib/DataTable.js
 @ ./src/app/shared/tables/staff-table/staff-table.component.ngfactory.js
 @ ./src/app/components/staff/staff-list.component.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/rxjs/_esm5/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:9341:17)
    at assignContextualParameterTypes (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:41948:29)
    at checkExpressionWorker (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:42959:28)
    at checkExpression (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:42898:42)
    at checkExpressionCached (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:42779:38)
    at checkReturnStatement (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:45418:54)
    at checkSourceElement (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46763:28)
    at Object.forEach (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:1506:30)
    at checkBlock (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:44563:16)
    at checkSourceElement (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:41990:21)
    at checkDeferredNodes (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46828:25)
    at checkSourceFileWorker (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46863:17)
    at checkSourceFile (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:46842:13)
    at Object.forEach (/Users/german/github/angular-cms/node_modules/typescript/lib/typescript.js:1506:30)
 @ ./node_modules/rxjs/_esm5/observable/bindCallback.js 2:0-68
 @ ./node_modules/rxjs/_esm5/add/observable/bindCallback.js
 @ ./node_modules/rxjs/_esm5/Rx.js
 @ ./node_modules/angular2-datatable/lib/DataTable.js
 @ ./src/app/shared/tables/staff-table/staff-table.component.ngfactory.js
 @ ./src/app/components/staff/staff-list.component.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts```

**Comment by Bulan** [comment]
Thx, suggestion by BartBurger (3rd post) worked like a charm.

This should really make it into the upgrade guide, or an FAQ for upgrading

**Comment by sanjaynegi** [comment]
Upgrading typescript to latest solved the issue

**Comment by arttuTuomi** [comment]
Changing
`import { Observable } from 'rxjs/Rx';`
to
`import { Observable } from 'rxjs/Observable';`
solves the issue.

**Comment by yanxiaojun617** [comment]
npm i typescript@2.6.1 --save-dev

**Comment by sushmit-oodles** [comment]
> Works with Typescript 2.4.2, i have replaced
> 
> ```ts
> import { Observable } from 'rxjs/Rx';
> ```
> 
> by
> 
> ```ts
> import { Observable } from 'rxjs/Observable';
> ```

worked for me!
