### ISSUE TITLE
Minimist reference throwing error on NGC build

### ISSUE THREAD

**Issue by eestein** [angular/angular#20342]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I use NGC the following error is thrown:

```
[10:18:41] TypeError: args.indexOf is not a function
    at module.exports (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/minimist/index.js:44:14)
    at readNgcCommandLineAndConfiguration (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/@angular/compiler-cli/src/main.js:66:41)
    at main (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/@angular/compiler-cli/src/main.js:21:24)
    at Gulp.<anonymous> (/Users/eestein/Documents/dev/dacasa/sdk-front/gulpfile.js:47:12)
    at module.exports (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/run-sequence/index.js:86:16)
    at Gulp.onTaskEnd (/Users/eestein/Documents/dev/dacasa/sdk-front/node_modules/run-sequence/index.js:75:5)
ERROR: args.indexOf is not a function
```

## Expected behavior
Build with no error

## Minimal reproduction of the problem with instructions
Create a lib project and run ngc

## Environment

<pre><code>
eestein@SteinMac sdk-front (master) $ ng --version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.5.0
Node: 7.7.3
OS: darwin x64
Angular: 5.0.1
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.2
typescript: 2.4.2
webpack: 3.8.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  Mac

Others:

gulp ngc task:

gulp.task('ngc', function () {
    return ngc({
        project: `${tmpFolder}/tsconfig.es5.json`
    })
        .then((exitCode) => {
            if (exitCode === 1) {
                throw new Error('Compiler error');
            }
        });
});
</code></pre>

minimist code:
```
    var notFlags = [];

    if (args.indexOf('--') !== -1) {                   // line throwing error
        notFlags = args.slice(args.indexOf('--')+1);
        args = args.slice(0, args.indexOf('--'));
    }
```
compiler-cli code:

```
function readNgcCommandLineAndConfiguration(args) {
    var options = {};
    var parsedArgs = require('minimist')(args);                  // line throwing error
```

I opened this issue at angular-cli's repository, but they directed me to this one.

https://github.com/angular/angular-cli/issues/8436

**Comment by Toxicable** [comment]
Can you make a minimal repro where that we can clone to see the issue

**Comment by Zaljin** [comment]
@eestein The API for ngc has changed slightly -- try using something like this instead.

```javascript
gulp.task('ngc', function () {
  return ngc(['-p', `${tmpFolder}/tsconfig.es5.json`], (error) => {
    if (error) {
      throw new Error('ngc compilation failed: ' + error);
    }
  });
});
```

Notice how we are passing in the args as an array of strings, and not an object.

**Comment by eestein** [comment]
@Zaljin thank you, that was it! Now I'm receiving other ngc errors, I'll dig into those now. Thanks!
