### ISSUE TITLE
After 5.0 upgrade, ngc generates invalid(?) metadata.json files for files that do not export anything

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular#20479]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I run ngc on my library, it generates `.metadata.json` files even for files that have no exports (previously with 4.x no metadata files were generated for such files). The content of the metadata file is just `[null]`. This causes AoT compilation (with `@ngtools/webpack`/`@angular/cli`) to throw an error: 

```
ERROR in TypeError: Cannot read property 'version' of null
    at readMetadataFile (C:\Devel\cli-app\node_modules\@angular\compiler-cli\src\transformers\metadata_reader.js:66:28)
    at Object.readMetadata (C:\Devel\cli-app\node_modules\@angular\compiler-cli\src\transformers\metadata_reader.js:35:25)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (C:\Devel\cli-app\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:413:34)
    at StaticSymbolResolver.getModuleMetadata (C:\Devel\cli-app\node_modules\@angular\compiler\bundles\compiler.umd.js:31787:62)
    at StaticSymbolResolver.hasDecorators (C:\Devel\cli-app\node_modules\@angular\compiler\bundles\compiler.umd.js:31514:46)
    at analyzeFile (C:\Devel\cli-app\node_modules\@angular\compiler\bundles\compiler.umd.js:30061:63)
    at AotCompiler._analyzeFile (C:\Devel\cli-app\node_modules\@angular\compiler\bundles\compiler.umd.js:29289:17)
    at AotCompiler.findGeneratedFileNames (C:\Devel\cli-app\node_modules\@angular\compiler\bundles\compiler.umd.js:29305:42)
    at Object.findGeneratedFileNames (C:\Devel\cli-app\node_modules\@angular\compiler-cli\src\transformers\program.js:387:82)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile (C:\Devel\cli-app\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:325:55)
    at findSourceFile (C:\Devel\cli-app\node_modules\typescript\lib\typescript.js:70246:29)
    at processImportedModules (C:\Devel\cli-app\node_modules\typescript\lib\typescript.js:70393:25)
    at findSourceFile (C:\Devel\cli-app\node_modules\typescript\lib\typescript.js:70274:17)
    at processImportedModules (C:\Devel\cli-app\node_modules\typescript\lib\typescript.js:70393:25)
    at findSourceFile (C:\Devel\cli-app\node_modules\typescript\lib\typescript.js:70274:17)
    at processImportedModules (C:\Devel\cli-app\node_modules\typescript\lib\typescript.js:70393:25)
```

An example of file with no exports - downgrade of a service separately, because I support both hybrid and Angular 4+ only apps:
```
import { downgradeInjectable } from '@angular/upgrade/static';
import { AuthService } from '@xx/core';

declare var angular: angular.IAngularStatic;

angular
    .module('xx.upgrade')
    .factory('xxAuth', downgradeInjectable(AuthService));
```

## Expected behavior

No metadata files should be generated for these files? Not sure if this is an intended change.

For now I have this workaround:
```
    ngc(['-p', tsConfigPath]);

    const metadata = globby.sync(['dist/'**/*.metadata.json')]);
    for (const metadataFile of metadata) {
        const content = fs.readFileSync(metadataFile, { encoding: 'utf8' });
        if (content === '[null]') {
            gutil.log('Detected invalid metadata.json files. Purging...');
            fs.unlinkSync(metadataFile);
        }
    }
```

## Environment

<pre><code>
Angular version: 5.0.1

**Comment by sandangel** [comment]
I face the same issue but I thought that was the library issue. 

https://github.com/swimlane/ngx-charts/issues/641

**Comment by sandangel** [comment]
Wow I can not compile my app anymore with aot, angular 5.0.2. Is this a critical issue? Please release a quick fix.

**Comment by ashishmulaye** [comment]
I am facing the same issue. When I compile my library with ngc it generates the .metadata.json files (having [null] value) for some of the files. With Angular >5.0.0, it does not generate these metadata.json files for those files.

**Comment by migglu** [comment]
I'm facing the same issue, and I'm not really sure how to use the given workaround. Any estimate on when this will be fixed and released?
