### ISSUE TITLE
Language Server errors when including locale file

### ISSUE THREAD

**Issue by Kamshak** [angular/angular#20502]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The following error occurs:
```
Error for getTemplateRefrences:
    TypeError: Cannot read property 'version' of null
    at readMetadataFile (/home/valentin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:38664:28)
    at readMetadata (/home/valentin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:38630:25)
    at ReflectorHost.getMetadataFor (/home/valentin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:56544:16)
    at StaticSymbolResolver.getModuleMetadata (/home/valentin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:31819:62)
    at StaticSymbolResolver.hasDecorators (/home/valentin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:31546:46)
    at analyzeFile (/home/valentin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30093:63)
    at visitFile (/home/valentin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30072:45)
    at /home/valentin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30078:52
    at Array.forEach (native)
    at _analyzeFilesIncludingNonProgramFiles (/home/valentin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30078:15)
```

logging at that location yields:
```
metadatas = '[ null ]'
metadataPath = '/home/valentin/frantz2/node_modules/@angular/common/locales/de.metadata.json'
```

Likely related to #20479 

## Expected behavior
No error.

## Minimal reproduction of the problem with instructions

**STEPS TO REPRODUCE**
in main.ts:
```
import localeDe from '@angular/common/locales/de';
registerLocaleData(localeDe);
``` 

## What is the motivation / use case for changing the behavior?
Building without CLI.

## Environment

<pre><code>
Angular version: 5.0.2

Browser:
- Not relevant - language server

For Tooling issues:
- Node version: 7.10.1
- Platform:
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=16.04
  DISTRIB_CODENAME=xenial
  DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
  NAME="Ubuntu"
  VERSION="16.04.3 LTS (Xenial Xerus)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 16.04.3 LTS"
  VERSION_ID="16.04"
  HOME_URL="http://www.ubuntu.com/"
  SUPPORT_URL="http://help.ubuntu.com/"
  BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
  VERSION_CODENAME=xenial
  UBUNTU_CODENAME=xenial

Others:
Using VSCode:
  Version 1.17.2
  Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
  Date 2017-10-16T13:57:00.652Z
  Shell 1.7.7
  Renderer 58.0.3029.110
  Node 7.9.0
  Architecture x64
</code></pre>

**Comment by ocombe** [comment]
Fixed with #20938
