### ISSUE TITLE
Language service plugin crashes on startup

### ISSUE THREAD

**Issue by kyliau** [angular/angular#20552]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The following exception occurs when the angular language service plugin is first loaded.

```
Info 17   [18:17:59.459] A plugin threw an exception in getExternalFiles: TypeError: Cannot read property 'enable' of undefined
Info 18   [18:17:59.464] TypeError: Cannot read property 'enable' of undefined
    at ConfiguredProject.Project.getGlobalCache (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82706:49)
    at resolveModuleName (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82006:46)
    at resolveNamesWithLocalCache (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82038:38)
    at Object.resolveModuleNames (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82091:20)
    at ConfiguredProject.Project.resolveModuleNames (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:82678:45)
    at Object.compilerHost.resolveModuleNames (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79713:117)
    at resolveModuleNamesWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:58912:106)
    at resolveModuleNamesReusingOldState (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:59043:24)
    at processImportedModules (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:59954:35)
    at findSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:59875:17)
    at args (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:59775:85)
    at getSourceFileFromReferenceWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:59749:34)
    at processSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:59775:13)
    at processTypeReferenceDirective (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:59910:21)
    at Object.createProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:58950:21)
    at synchronizeHostData (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79721:26)
    at Object.getProgram (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:79756:13)
    at TypeScriptServiceHost.get [as program] (/Users/kyliau/.vscode/extensions/nglangsvc/node_modules/angular_language_service/index.js:56823:50)
    at TypeScriptServiceHost.validate (/Users/kyliau/.vscode/extensions/nglangsvc/node_modules/angular_language_service/index.js:56840:27)
    at TypeScriptServiceHost.getAnalyzedModules (/Users/kyliau/.vscode/extensions/nglangsvc/node_modules/angular_language_service/index.js:56721:14)
    at TypeScriptServiceHost.ensureTemplateMap (/Users/kyliau/.vscode/extensions/nglangsvc/node_modules/angular_language_service/index.js:56877:40)
    at TypeScriptServiceHost.getTemplateReferences (/Users/kyliau/.vscode/extensions/nglangsvc/node_modules/angular_language_service/index.js:56698:14)
    at Object.getExternalFiles (/Users/kyliau/.vscode/extensions/nglangsvc/node_modules/angular_language_service/index.js:57207:27)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83386:39
    at Object.flatMap (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:1561:25)
    at ConfiguredProject.getExternalFiles (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:83382:48)
    at ProjectService.createConfiguredProject (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:84417:70)
    at ProjectService.openClientFileWithNormalizedPath (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:84740:44)
    at IOSession.Session.openClientFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86071:37)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:85303:31)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86710:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86701:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86710:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:86730:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:87922:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

## Expected behavior

Plugin should not crash

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Mac

Others:

Typescript version 2.6.1
VS Code 1.18.1
</code></pre>

**Comment by kyliau** [comment]
This is because `typeAcquisition` is not set **before** `getExternalFiles()` is called

**Comment by kyliau** [comment]
Closing this as it's no longer relevant
