### ISSUE TITLE
Aot can't compile module when declarations was created by Object.values

### ISSUE THREAD

**Issue by mxyzzhong** [angular/angular#20604]
I have so much components,it's ugly to set one by one to declarations.So I export all components in an common file and use `Object.values( )` to do this. 

## I'm submitting a...

<pre><code>
[] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

well,when I execute `ng serve`,it's all well.
But,when I execute `ng build --prod`,it throws error

<pre>
ERROR in Error: Unexpected value 'null' declared by the module 'AppModule in G:/gitlab/sudiyi-bms/src/app/app.module.ts'
    at syntaxError (G:\gitlab\sudiyi-bms\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at G:\gitlab\sudiyi-bms\node_modules\@angular\compiler\bundles\compiler.umd.js:15466:40
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (G:\gitlab\sudiyi-bms\node_modules\@angular\compiler\bundles\compiler.umd.js:15464:54)
    at addNgModule (G:\gitlab\sudiyi-bms\node_modules\@angular\compiler\bundles\compiler.umd.js:24269:58)
    at G:\gitlab\sudiyi-bms\node_modules\@angular\compiler\bundles\compiler.umd.js:24280:14
    at Array.forEach (<anonymous>)
    at _createNgModules (G:\gitlab\sudiyi-bms\node_modules\@angular\compiler\bundles\compiler.umd.js:24279:26)
    at analyzeNgModules (G:\gitlab\sudiyi-bms\node_modules\@angular\compiler\bundles\compiler.umd.js:24154:14)
    at analyzeAndValidateNgModules (G:\gitlab\sudiyi-bms\node_modules\@angular\compiler\bundles\compiler.umd.js:24164:35)
    at AotCompiler.analyzeModulesAsync (G:\gitlab\sudiyi-bms\node_modules\@angular\compiler\bundles\compiler.umd.js:23798:46)
    at CodeGenerator.codegen (G:\gitlab\sudiyi-bms\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (G:\gitlab\sudiyi-bms\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (G:\gitlab\sudiyi-bms\node_modules\@ngtools\webpack\src\plugin.js:386:44)
    at <anonymous>
</pre>

## Minimal reproduction of the problem with instructions

<pre>
import { NgModule} from '@angular/core';  

import * as components from './components';  

@NgModule({
    declarations: [
        ...Object.values(components)
    ],
    imports: [],
    providers: [],
    bootstrap: [components.LayoutComponent]
})
export class AppModule {}
</pre>
## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [ ] Chrome (desktop) version 62.0.3202.94
 
For Tooling issues:
- Node version: 8.4.0  
- Platform: Windows   

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@mxyzzhong ... your idea has no sense. Btw, how many minutes do you save? It is absolutely irrelevant ... + tree shaking nonsense.

**Comment by mxyzzhong** [comment]
@mlc-mlapis In fact,each of components has been used,so tree shaking is not needed there.
 why I used it is not saving time but making code prettier.
I just wonder why it throws error,caused by webpack or angular itself?

**Comment by mlc-mlapis** [comment]
@mxyzzhong ... just save your time ... it's not the way forward. Forget about it.

**Comment by mhevery** [comment]
yes this is not supported by our metadata collector, and we don't plan to support that.
