### ISSUE TITLE
why the new angular project run ‘ng build --prod‘ error 

### ISSUE THREAD

**Issue by xiaohuoni** [angular/angular#20601]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[1] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

<pre><code>

For Tooling issues:
-Angular CLI:1.5.3
-Node:8.9.1
-OS:win32 x64
-Angular:5.0.3
-npm install:cnpm
Others:

ng new buildt
buildt>ng build --prod
 10% building modules 3/4 modules 1 active ....js??postcss!D:\buildt\src\styles.
 ...
 27% building modules 142/143 modules 1 active ....js??postcss!D:\buildt\src\sty
 95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open
'D:\buildt\node_modules\_@angular_core@5.0.3@@angular\package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at LicenseExtractor.readPackageJson (D:\buildt\node_modules\_license-webpack
-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:124:23)
    at LicenseExtractor.parsePackage (D:\buildt\node_modules\_license-webpack-pl
ugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (D:\buildt\node_modules\_license-webpack-p
lugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (D:\buildt\node_modules\_license-webpack-plug
in@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:21:21)
    at moduleCallback (D:\buildt\node_modules\_license-webpack-plugin@1.1.1@lice
nse-webpack-plugin\dist\LicenseWebpackPlugin.js:80:61)
    at Set.forEach (<anonymous>)
    at Chunk.forEachModule (D:\buildt\node_modules\_webpack@3.8.1@webpack\lib\Ch
unk.js:159:17)
    at D:\buildt\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plug
in\dist\LicenseWebpackPlugin.js:89:27
    at Array.forEach (<anonymous>)
    at Compiler.<anonymous> (D:\buildt\node_modules\_license-webpack-plugin@1.1.
1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:65:32)
    at next (D:\buildt\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:204:14
)
    at D:\buildt\node_modules\_html-webpack-plugin@2.30.1@html-webpack-plugin\in
dex.js:204:9
    at PassThroughHandlerContext.finallyHandler (D:\buildt\node_modules\_bluebir
d@3.5.1@bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (D:\buildt\node_modules\_bluebird@3.
5.1@bluebird\js\release\util.js:16:23)

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Please report angular-cli's issues on its repo https://github.com/angular/angular-cli
