### ISSUE TITLE
Injection errors from unit tests are not very useful

### ISSUE THREAD

**Issue by juliemr** [angular/angular#2091]
When an error is thrown from say, the injector, the message doesn't get passed along:

```
Chrome 45.0.2408 (Mac OS X 10.9.5) binding to CSS class list should add classes specified in an object literal FAILED
	Error
	    at NoAnnotationError.BaseException (/Users/ralphj/angular/dist/js/dev/es5/angular2/src/facade/lang.js:102:25)
	    at new NoAnnotationError (/Users/ralphj/angular/dist/js/dev/es5/angular2/src/di/exceptions.js:109:63)
	    at _dependenciesFor (/Users/ralphj/angular/dist/js/dev/es5/angular2/src/di/binding.js:39:13)
	    at $__export.resolve (/Users/ralphj/angular/dist/js/dev/es5/angular2/src/di/binding.js:168:28)
	    at resolveBindings (/Users/ralphj/angular/dist/js/dev/es5/angular2/src/di/injector.js:40:57)
	    at Function.$__export.resolve (/Users/ralphj/angular/dist/js/dev/es5/angular2/src/di/injector.js:211:36)
	    at Injector.$__export.resolveAndCreateChild (/Users/ralphj/angular/dist/js/dev/es5/angular2/src/di/injector.js:141:42)
	    at createTestInjector (/Users/ralphj/angular/dist/js/dev/es5/angular2/src/test_lib/test_injector.js:68:25)
	    at Object.<anonymous> (/Users/ralphj/angular/dist/js/dev/es5/angular2/src/test_lib/test_lib.js:86:22)
```

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
