### ISSUE TITLE
ngmodules examples for final is not building

### ISSUE THREAD

**Issue by drlukeangel** [angular/angular#20928]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

download The final version / download example on the page https://angular.io/guide/ngmodule#ngmodules and it will not build 

## Expected behavior

the project runs after you npm i > npm serve 

## Minimal reproduction of the problem with instructions

download the code and run it
## What is the motivation / use case for changing the behavior?

want people to get working code 

## Environment
prod
<pre><code>
Angular version: 5.0.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
windows 10 pro - node newest - npm newest - angular/cli newest
Others:

</code></pre>
**first error**

ENOENT: no such file or directory, stat 'C:\dev\source\googleAngular\ngmodule\src\tsconfig.app.json'
Error: ENOENT: no such file or directory, stat 'C:\dev\source\googleAngular\ngmodule\src\tsconfig.app.json'
    at Object.fs.statSync (fs.js:948:11)
    at AngularCompilerPlugin._setupOptions (C:\dev\source\googleAngular\ngmodule\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:78:16)
    at new AngularCompilerPlugin (C:\dev\source\googleAngular\ngmodule\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:43:14)
    at _createAotPlugin (C:\dev\source\googleAngular\ngmodule\node_modules\@angular\cli\models\webpack-configs\typescript.js:77:16)
    at Object.getNonAotConfig (C:\dev\source\googleAngular\ngmodule\node_modules\@angular\cli\models\webpack-configs\typescript.js:100:19)
    at NgCliWebpackConfig.buildConfig (C:\dev\source\googleAngular\ngmodule\node_modules\@angular\cli\models\webpack-config.js:33:37)
    at Class.run (C:\dev\source\googleAngular\ngmodule\node_modules\@angular\cli\tasks\serve.js:71:98)
    at check_port_1.checkPort.then.port (C:\dev\source\googleAngular\ngmodule\node_modules\@angular\cli\commands\serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
PS C:\dev\source\googleAngular\ngmodule> ng serve --port 4100

added a basic version 
`{
    "extends": "../tsconfig.json",
    "compilerOptions": {
      "outDir": "../out-tsc/app",
      "module": "es2015",
      "baseUrl": "",
      "types": []
    },
    "exclude": [
      "test.ts",
      "**/*.spec.ts"
    ]
  }
  `

it then fails
`
ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve 'C:\dev\source\googleAngular\ngmodule\src\polyfills.ts' in 'C:\dev\source\googleAngular\ngmodule\node_modules\@angular\cli\models\webpack-configs'
resolve 'C:\dev\source\googleAngular\ngmodule\src\polyfills.ts' in 'C:\dev\source\googleAngular\ngmodule\node_modules\@angular\cli\models\webpack-configs'
  using description file: C:\dev\source\googleAngular\ngmodule\node_modules\@angular\cli\package.json (relative path: ./models/webpack-configs)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\dev\source\googleAngular\ngmodule\node_modules\@angular\cli\package.json (relative path: ./models/webpack-configs)
    using description file: C:\dev\source\googleAngular\ngmodule\package.json (relative path: ./src/polyfills.ts)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\dev\source\googleAngular\ngmodule\src\polyfills.ts doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\dev\source\googleAngular\ngmodule\src\polyfills.ts.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\dev\source\googleAngular\ngmodule\src\polyfills.ts.js doesn't exist
      as directory
        C:\dev\source\googleAngular\ngmodule\src\polyfills.ts doesn't exist
[C:\dev\source\googleAngular\ngmodule\src\polyfills.ts]
[C:\dev\source\googleAngular\ngmodule\src\polyfills.ts.ts]
[C:\dev\source\googleAngular\ngmodule\src\polyfills.ts.js]
[C:\dev\source\googleAngular\ngmodule\src\polyfills.ts]
 @ multi ./src/polyfills.ts
ERROR in TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:16640:110)
    at parseSourceFileWorker (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:16572:26)
    at Object.parseSourceFile (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:16521:26)
    at Object.createSourceFile (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:16371:29)
    at VirtualFileStats.getSourceFile (C:\dev\source\googleAngular\ngmodule\node_modules\@ngtools\webpack\src\compiler_host.js:67:35)
    at WebpackCompilerHost.getSourceFile (C:\dev\source\googleAngular\ngmodule\node_modules\@ngtools\webpack\src\compiler_host.js:207:38)
    at findSourceFile (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:70246:29)
    at processImportedModules (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:70393:25)
    at findSourceFile (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:70274:17)
    at args (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:70200:85)
    at getSourceFileFromReferenceWorker (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:70173:34)
    at processSourceFile (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:70200:13)
    at processRootFile (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:70055:13)
    at C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:69312:60
    at Object.forEach (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:1506:30)
    at Object.createProgram (C:\dev\source\googleAngular\ngmodule\node_modules\typescript\lib\typescript.js:69312:16)

**Comment by gkalpak** [comment]
Thx for reporting this. That particular guide is being re-worked and the new version will land soon: #20306
The downloadable example is already fixed there. I'll have to look into why the files to be missing in the current version 😕

**Comment by gkalpak** [comment]
The issue is related to how our `ExampleZipper` utility determines the [files to include/exclude][1]. From a quick look, this may also affect (one way or another) other zips (`dependency-injection`, `i18n`, `reactive-forms`, `testing`).

@Foxandxss, who is most familiar with `ExampleZipper`, will take a look later this week.

[1]: https://github.com/angular/angular/blob/add3589451d8efdce65aa2c268070bbfab271cde/aio/tools/example-zipper/exampleZipper.js#L72-L135

**Comment by drlukeangel** [comment]
I can confirm multiple other example downloads were broken. I listed only one in the reported issue.

**Comment by Foxandxss** [comment]
Yes, I am going to fix it now.

**Comment by drlukeangel** [comment]
quick turn around. good job.
