### ISSUE TITLE
Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by lcasassa** [angular/angular#20960]
When I connect to kong, I'm getting this error:

[centos@manager-0-kong deploy]$ sudo docker service logs kong_konga -f
kong_konga.1.xi0x55l18mnh@manager-2-kong    | /app/api/controllers/UserController.js:48
kong_konga.1.xi0x55l18mnh@manager-2-kong    |                 if(user.node) {
kong_konga.1.xi0x55l18mnh@manager-2-kong    |                        ^
kong_konga.1.xi0x55l18mnh@manager-2-kong    | 
kong_konga.1.xi0x55l18mnh@manager-2-kong    | TypeError: Cannot read property 'node' of undefined
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at /app/api/controllers/UserController.js:48:24
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at wrapper (/app/node_modules/sails-hook-validation/node_modules/lodash/index.js:3602:19)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at applyInOriginalCtx (/app/node_modules/sails-hook-validation/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at wrappedCallback (/app/node_modules/sails-hook-validation/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at success (/app/node_modules/sails-hook-validation/node_modules/switchback/lib/normalize.js:33:31)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at _switch (/app/node_modules/sails-hook-validation/node_modules/switchback/lib/factory.js:58:28)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at /app/node_modules/sails-hook-validation/lib/update.js:61:21
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at /app/node_modules/waterline/lib/waterline/query/dql/update.js:235:9
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at Object.async.forEachOf.async.eachOf (/app/node_modules/waterline/node_modules/async/lib/async.js:236:30)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at Object.async.forEach.async.each (/app/node_modules/waterline/node_modules/async/lib/async.js:209:22)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at /app/node_modules/waterline/lib/waterline/query/dql/update.js:226:13
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at /app/node_modules/waterline/node_modules/async/lib/async.js:52:16
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at /app/node_modules/waterline/node_modules/async/lib/async.js:550:17
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at /app/node_modules/waterline/node_modules/async/lib/async.js:544:17
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at _arrayEach (/app/node_modules/waterline/node_modules/async/lib/async.js:85:13)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at Immediate.taskComplete (/app/node_modules/waterline/node_modules/async/lib/async.js:543:13)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at tryOnImmediate (timers.js:645:5)
kong_konga.1.xi0x55l18mnh@manager-2-kong    |     at processImmediate [as _immediateCallback] (timers.js:617:5)

Let me know what else you need to reproduce.

**Comment by lcasassa** [comment]
sorry, please close.
