### ISSUE TITLE
ng build -prod error 

### ISSUE THREAD

**Issue by xiaohuoni** [angular/angular#20977]
Angular CLI: 1.5.3
Node: 8.9.1
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0
@angular/cli: 1.5.3
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack: 3.8.1

npm use cnpm

run `ng build -prod error `

error ：
95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open 'D:\td-share-ng\node_modules\_@angular_core@5.1.0@@angular\package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at LicenseExtractor.readPackageJson (D:\td-share-ng\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:124:23)
    at LicenseExtractor.parsePackage (D:\td-share-ng\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (D:\td-share-ng\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (D:\td-share-ng\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:21:21)
    at moduleCallback (D:\td-share-ng\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:80:61)
    at Set.forEach (<anonymous>)
    at Chunk.forEachModule (D:\td-share-ng\node_modules\_webpack@3.8.1@webpack\lib\Chunk.js:159:17)
    at D:\td-share-ng\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:89:27
    at Array.forEach (<anonymous>)
    at Compiler.<anonymous> (D:\td-share-ng\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:65:32)
    at next (D:\td-share-ng\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:204:14)
    at D:\td-share-ng\node_modules\_html-webpack-plugin@2.30.1@html-webpack-plugin\index.js:204:9
    at PassThroughHandlerContext.finallyHandler (D:\td-share-ng\node_modules\_bluebird@3.5.1@bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (D:\td-share-ng\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)

Can't visit stackoverflow in China ，Thanks！

**Comment by ericmartinezr** [comment]
Please report angular-cli's issues in its repo -> https://github.com/angular/angular-cli

**Comment by xiaohuoni** [comment]
thank you!
