### ISSUE TITLE
ng serve failed after updating CLI

### ISSUE THREAD

**Issue by SlimenTN** [angular/angular#20984]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

ng serve failed and  I get this error :
<code>
ERROR in Error: AppModule is not an NgModule
    at _getNgModuleMetadata (/Applications/MAMP/htdocs/VSCodeProjects/Webcard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (/Applications/MAMP/htdocs/VSCodeProjects/Webcard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Applications/MAMP/htdocs/VSCodeProjects/Webcard/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Applications/MAMP/htdocs/VSCodeProjects/Webcard/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Applications/MAMP/htdocs/VSCodeProjects/Webcard/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Applications/MAMP/htdocs/VSCodeProjects/Webcard/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/plugin.js:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
</code>

## Expected behavior

ng serve should work fine.

## What is the motivation / use case for changing the behavior?

The only thing I did before this happens is updating the angular CLI to the version 1.6.0 (globally and locally) and I have followed these steps here: https://github.com/angular/angular-cli#updating-angular-cli

## Environment

<pre><code>
Angular version: 4.4.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.6.0  
- Platform:  Mac 

Others:

This is my package.json file
</code>
{
  "name": "my-project",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.1",
    "@angular/animations": "^4.4.1",
    "@angular/common": "^4.4.1",
    "@angular/compiler": "^4.4.1",
    "@angular/core": "^4.4.1",
    "@angular/forms": "^4.4.1",
    "@angular/http": "^4.4.1",
    "@angular/platform-browser": "^4.4.1",
    "@angular/platform-browser-dynamic": "^4.4.1",
    "@angular/router": "^4.4.1",
    "core-js": "^2.5.1",
    "ngx-color-picker": "^4.5.0",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.17"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.0",
    "@angular/compiler-cli": "^4.4.1",
    "@angular/language-service": "^4.4.1",
    "@types/jasmine": "^2.6.0",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^6.0.88",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3",
    "webpack": "^3.10.0"
  }
}

</pre>

**Comment by SlimenTN** [comment]
Ok, the supported typescript version for CLI 1.6 is 2.5.3
and after updating it now it works fine.
