### ISSUE TITLE
Issue with ngc/Angular 5/ambient modules

### ISSUE THREAD

**Issue by staeke** [angular/angular#21039]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I seem not to be able to use ambient modules with Angular 5.1.0. This was working in Angular 4.4.6. 

For code such as 
```ts
declare module 'rxjs/Observable' {
    export interface Observable<T> {
        fooBar();
    }
}
```

I get the error 

> : Error: Debug Failure. False expression: Unexpected node.
Verbose Debug Information: Node StringLiteral did not pass test 'isIdentifier'.
    at visitNode (/Users/staffan/dev/repro-angular2/node_modules/typescript/lib/typescript.js:51067:18)
    at Object.visitEachChild (/Users/staffan/dev/repro-angular2/node_modules/typescript/lib/typescript.js:51361:167)
    at visitNodeImpl (/Users/staffan/dev/repro-angular2/node_modules/tsickle/src/transformer_sourcemap.js:51:27)
    at Object.visitNodeWithSynthesizedComments (/Users/staffan/dev/repro-angular2/node_modules/tsickle/src/transformer_util.js:281:20)
    at visitNode (/Users/staffan/dev/repro-angular2/node_modules/tsickle/src/transformer_sourcemap.js:33:43)
    at visitNodes (/Users/staffan/dev/repro-angular2/node_modules/typescript/lib/typescript.js:51104:48)
    at visitLexicalEnvironment (/Users/staffan/dev/repro-angular2/node_modules/typescript/lib/typescript.js:51137:22)
    at Object.visitEachChild (/Users/staffan/dev/repro-angular2/node_modules/typescript/lib/typescript.js:51431:54)
    at visitNodeImpl (/Users/staffan/dev/repro-angular2/node_modules/tsickle/src/transformer_sourcemap.js:51:27)
    at /Users/staffan/dev/repro-angular2/node_modules/tsickle/src/transformer_util.js:272:145

## Expected behavior
For it to work

## Minimal reproduction of the problem with instructions
```bash
git clone git@github.com:staeke/repro-angular.git
cd repro-angular
git checkout angular5-ambient-modules-ngc
npm install
# EDIT: Earlier version didn't have NODE_ENV=development
NODE_ENV=development ./node_modules/.bin/ngc -p tsconfig.json 
```

## Environment

Angular version: 5.1.0

For Tooling issues:
- Node version: 8.9.3
- Platform: Mac
- Typescript: 2.5.2

**Comment by chuckjaz** [comment]
@staeke This looks like might be a bug in Tsickle. However, I cannot reproduce the issue with the steps you provide.

Can push a change to the `angular5-ambient-modules-ngc` branch that reproduces the issue? Once that is done I will use these steps to open a bug against Tsickle.

**Comment by staeke** [comment]
@chuckjaz weird...I've reproduced this error on new checkouts for this branch. Verified again now. Are you using the same Node version? Should I push `node_modules` too maybe?

**Comment by chuckjaz** [comment]
@staeke I was using `8.9.2`. Switched to `8.9.3` and still no error.

The `package-lock.json` should have been sufficient. On Monday I will have someone else see if they can reproduce it on their machine.

**Comment by staeke** [comment]
My colleagues didn't get it so I dug a little more. I finally narrowed it down to me having `NODE_ENV=development` defined as an environment variable. Thus, the line should read

```
NODE_ENV=development ./node_modules/.bin/ngc -p tsconfig.json
```

Updated above

**Comment by chuckjaz** [comment]
As a work-around I would recommend not setting `NODE_ENV=development` when executing `ngc`.

**Comment by JoostK** [comment]
I can reproduce the issue with the reproduction repo in Angular 5, but it works in Angular 9 both using ViewEngine and Ivy.
