### ISSUE TITLE
Unexpected directive value 'undefined' on the View of component 'DisplayComponent'

### ISSUE THREAD

**Issue by RinatMullayanov** [angular/angular#2104]
I watched step by step guide https://angular.io/docs/js/latest/guide/ and created my repo https://github.com/RinatMullayanov/step-by-step-guide-with-angular2
with 2.0.0-alpha.23 everything works, but  when I wanted to update to 2.0.0-alpha.25, I got an error:

```
Unexpected directive value 'undefined' on the View of component 'DisplayComponent'
Error
    at new BaseException (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:7159:25)
    at execute.Compiler._compile (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:24579:21)
    at https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:24607:35
    at Function.execute.ListWrapper.forEach (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:7593:15)
    at execute.Compiler._compileNestedProtoViews (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:24602:23)
    at https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:24587:25
    at Zone.run (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:115:17)
    at Zone.execute.NgZone._createInnerZone.zone.fork.fork.$run [as run] (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:12418:38)
    at zoneBoundFn (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:88:19)
    at lib$es6$promise$$internal$$tryCatch (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:479:16)
```
![2015-05-22 20 05 03](https://cloud.githubusercontent.com/assets/7579698/7773427/dec5aea8-00bd-11e5-9465-e031d89d3045.png)

**Comment by Braincompiler** [comment]
I got the same with `v2.0.0-alpha.22`.

How can I workaround it? Can I choose a specific Version? Maybe .23 where it seems to be working?

**Comment by RinatMullayanov** [comment]
> I got the same with v2.0.0-alpha.22 (The version I got using tsd).

> How can I workaround it? Can I choose a specific Version? Maybe .23 where it seems to be working?

Oh, and update tsd I forgot.
Perhaps this is the reason of my problem - different versions of the tsd and angular2.
Now there are only tsd v2.0.0-alpha.22, well I will wait for the update to tsd v2.0.0-alpha.25.

**Comment by mdausmann** [comment]
Last time I got this error was the name change from For to NgFor.  Nobody is doing a good job of updating the tsd along with the builds so you need to self-maintain for now.

**Comment by gdi2290** [comment]
I have a PR open with latest definitions that I made while workingon Angular 2

**Comment by RinatMullayanov** [comment]
> I have a PR open with latest definitions that I made while workingon Angular 2

> borisyankov/DefinitelyTyped#4432

Thanks

**Comment by mhevery** [comment]
No action for us closing.
