### ISSUE TITLE
Angular 4 safesubscriber.next this._parentSubscriber causing reloads

### ISSUE THREAD

**Issue by JohnYoussef** [angular/angular#21100]
Safesubscriber is being called after subscriptions and unsubscribe and reloads history components and actions, when I debug it sometimes goes to this functions in Subscriber.js

<pre><code>
SafeSubscriber.prototype.complete = function ()
var _this = this;
    if (!this.isStopped) { //false
       var _parentSubscriber = this._parentSubscriber; //isclosed false also
</code></pre>

<pre><code>
SafeSubscriber.prototype.__tryOrUnsub = function (fn, value) {
    try {
        fn.call(this._context, value); //fn = ƒ (), value = undefined
    }
</code></pre>

this happens after certain subscriptions to DB Apollo mutations
<pre><code>
this.jobService.mutateEditOffer(allMutations).subscribe(data => {
            console.log(data);
        }, (error) => { console.log(error); },
            () => {
                console.log('unsubscribe');
            });
</code></pre>

## Expected behavior
It shouldn't reload history actions and other components

Browser:
- [x] Chrome (desktop) version XX
 
For Tooling issues:
- Node version ts-node: 3.2.0
- Platform:  Windows 10, Firebase

**Comment by JohnYoussef** [comment]
Another error appears before reloading back history actions
`"ReferenceError: error is not defined
    at eval (eval at <anonymous> (http://localhost:4200/main.bundle.js:6377:9), <anonymous>:1:1)
    at SafeSubscriber._next (http://localhost:4200/main.bundle.js:6377:9)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.bundle.js:22701:16)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next (http://localhost:4200/vendor.bundle.js:22648:22)
    at Subscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next (http://localhost:4200/vendor.bundle.js:22589:26)
    at Subscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.bundle.js:22553:18)
    at MapSubscriber.webpackJsonp.../../../../rxjs/_esm5/operators/map.js.MapSubscriber._next (http://localhost:4200/vendor.bundle.js:39716:26)
    at MapSubscriber.webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.bundle.js:22553:18)
    at http://localhost:4200/vendor.bundle.js:7160:28
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2937:26)"`

**Comment by chuckjaz** [comment]
Can you please create a project on [stackblitz](stackblitz.com) or [plunker](https://plnkr.co/) that duplicates this issue?
