### ISSUE TITLE
[service-worker] 'navigator is not defined' in server side rendering.

### ISSUE THREAD

**Issue by leo6104** [angular/angular#21230]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```
ReferenceError: navigator is not defined
    at ngswCommChannelFactory (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:198693:57)
    at _callFactory (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:11213:20)
    at _createProviderInstance$1 (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:11163:26)
    at resolveNgModuleDep (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:11145:17)
    at _createClass (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:11186:29)
    at _createProviderInstance$1 (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:11160:26)
    at resolveNgModuleDep (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:11145:17)
    at NgModuleRef_.get (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:12381:16)
    at resolveDep (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:12879:45)
    at createClass (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:12749:32)
    at createDirectiveInstance (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:12586:37)
    at createViewNodes (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:14047:53)
    at createRootView (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:13936:5)
    at Object.createProdRootView [as createRootView] (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:14629:12)
    at ComponentFactory_.create (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:11531:46)
    at ComponentFactoryBoundToModule.create (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:4302:29)
    at ApplicationRef.bootstrap (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:6126:57)
    at /Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:5853:81
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:5853:44)
    at /Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:5774:27
    at ZoneDelegate.invoke (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157481:26)
    at Object.onInvoke (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:5024:33)
    at ZoneDelegate.invoke (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157480:32)
    at Zone.run (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157231:43)
    at /Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157962:57
    at ZoneDelegate.invokeTask (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157514:31)
    at Object.onInvokeTask (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:5015:33)
    at ZoneDelegate.invokeTask (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157513:36)
    at Zone.runTask (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157281:47)
    at drainMicroTaskQueue (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157691:35)
    at ZoneTask.invokeTask (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157592:21)
    at ZoneTask.invoke (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:157577:48)
    at data.args.(anonymous function) (/Users/sangmin/WebstormProjects/mapia_ng2/dist/server.js:158248:25)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

## Expected behavior

only access navigator in platformBrowser

## Minimal reproduction of the problem with instructions

https://github.com/angular/angular/blob/master/packages/service-worker/src/module.ts#L60

## What is the motivation / use case for changing the behavior?

In AppModule
```
ServiceWorkerModule.register('/ngsw-worker.js', { enabled: environment.env === 'prod' })
```

## Environment

<pre><code>
Angular version: 5.1.2

Browser: All

For Tooling issues:
- Node version: 8.9.1  
- Platform:  Mac

Others:

</code></pre>

**Comment by gkalpak** [comment]
Fixed in #21231.
