### ISSUE TITLE
angular.io translation issue : dgeni build failed

### ISSUE THREAD

**Issue by han41858** [angular/angular#21306]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Hi, I'm a Angular developer in South Korea.
I'm translating angular.io project to Korean, and I have some issue.

For example, in Architecture page, I want translate 'Modules' section name to Korean.
So I changed it to Korean and tried to build, but it failed.
This is error log.

```
λ yarn docs
yarn run v1.3.2
$ rimraf src/generated/{docs,*.json}
$ dgeni ./tools/transforms/angular.io-package
info:    running processor: readFilesProcessor
info:    running processor: extractJSDocCommentsProcessor
info:    running processor: collectExamples
info:    running processor: readTypeScriptModules
info:    Export has no declarations: unknown
info:    Export has no declarations: unknown
info:    Export has no declarations: unknown
info:    Export has no declarations: unknown
info:    Export has no declarations: unknown
info:    Export has no declarations: unknown
info:    Export has no declarations: unknown
info:    Export has no declarations: unknown
info:    Export has no declarations: unknown
info:    running processor: linkInheritedDocs
warn:    Unresolved TypeScript symbol(s): Subject<T> - doc "core/EventEmitter" (class)  - from file "core/src/event_emitter.ts" - starting at line 9, ending at line 115
info:    running processor: parseTagsProcessor
info:    running processor: extractTagsProcessor
info:    running processor: codeNameProcessor
info:    running processor: createOverviewDump
info:    running processor: convertPrivateClassesToInterfacesProcessor
info:    running processor: mergeDecoratorDocs
info:    running processor: extractDecoratedClassesProcessor
info:    running processor: markBarredODocsAsPrivate
info:    running processor: addMetadataAliasesProcessor
info:    running processor: computeIdsProcessor
info:    running processor: filterContainedDocs
info:    running processor: filterPrivateDocs
info:    running processor: simplifyMemberAnchors
info:    running processor: computePathsProcessor
info:    running processor: generateApiListDoc
info:    running processor: addNotYetDocumentedProperty
info:    running processor: matchUpDirectiveDecorators
info:    running processor: processNavigationMap
info:    running processor: renderDocsProcessor
info:    running processor: unescapeCommentsProcessor
info:    running processor: inlineTagProcessor
info:    running processor: renderExamples
info:    running processor: copyContentAssetsProcessor
info:    running processor: postProcessHtml
info:    running processor: computeSearchTitleProcessor
info:    running processor: generateKeywordsProcessor
info:    running processor: checkUnbalancedBackTicks
info:    running processor: fixInternalDocumentLinks
info:    running processor: checkAnchorLinksProcessor
warn:    Dangling Links Found in "guide/ajs-quick-reference.json":
 - guide/architecture#%EB%AA%A8%EB%93%88
warn:    Dangling Links Found in "guide/architecture.json":
 - guide/architecture#%EB%AA%A8%EB%93%88,
 - guide/architecture#%EB%AA%A8%EB%93%88
error:   Error: 3 unmatched links
    at Object.$process (D:\Workspace\angular-ko\aio\node_modules\dgeni-packages\base\processors\checkAnchorLinks.js:106:17)
    at D:\Workspace\angular-ko\aio\node_modules\dgeni\lib\Dgeni.js:179:54
    at _fulfilled (D:\Workspace\angular-ko\aio\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\Workspace\angular-ko\aio\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\Workspace\angular-ko\aio\node_modules\q\q.js:796:13)
    at D:\Workspace\angular-ko\aio\node_modules\q\q.js:604:44
    at runSingle (D:\Workspace\angular-ko\aio\node_modules\q\q.js:137:13)
    at flush (D:\Workspace\angular-ko\aio\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error:   Error processing docs:  Error: 3 unmatched links
    at Object.$process (D:\Workspace\angular-ko\aio\node_modules\dgeni-packages\base\processors\checkAnchorLinks.js:106:17)
    at D:\Workspace\angular-ko\aio\node_modules\dgeni\lib\Dgeni.js:179:54
    at _fulfilled (D:\Workspace\angular-ko\aio\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\Workspace\angular-ko\aio\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\Workspace\angular-ko\aio\node_modules\q\q.js:796:13)
    at D:\Workspace\angular-ko\aio\node_modules\q\q.js:604:44
    at runSingle (D:\Workspace\angular-ko\aio\node_modules\q\q.js:137:13)
    at flush (D:\Workspace\angular-ko\aio\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
D:\Workspace\angular-ko\aio\node_modules\q\q.js:155
                throw e;
                ^

Error: 3 unmatched links
    at Object.$process (D:\Workspace\angular-ko\aio\node_modules\dgeni-packages\base\processors\checkAnchorLinks.js:106:17)
    at D:\Workspace\angular-ko\aio\node_modules\dgeni\lib\Dgeni.js:179:54
    at _fulfilled (D:\Workspace\angular-ko\aio\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\Workspace\angular-ko\aio\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\Workspace\angular-ko\aio\node_modules\q\q.js:796:13)
    at D:\Workspace\angular-ko\aio\node_modules\q\q.js:604:44
    at runSingle (D:\Workspace\angular-ko\aio\node_modules\q\q.js:137:13)
    at flush (D:\Workspace\angular-ko\aio\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The section name 'Module' is '모듈' in Korean word and it converted successfully to '%EB%AA%A8%EB%93%88'.
But dgeni build failed for this errors.

I tested another test code for HTML fragment identifier.
```xml
<html>
	<body>
		<h2 id="테스트">테스트</h2>
		<p>1</p>
		<p>2</p>
		<p>3</p>
		<p>4</p>
		<p>5</p>
		<p>6</p>
		<p>7</p>
		<p>8</p>
		<p>9</p>
		<p>10</p>
		<p>1</p>
		<p>2</p>
		<p>3</p>
		<p>4</p>
		<p>5</p>
		<p>6</p>
		<p>7</p>
		<p>8</p>
		<p>9</p>
		<p>10</p>
		<p>1</p>
		<p>2</p>
		<p>3</p>
		<p>4</p>
		<p>5</p>
		<p>6</p>
		<p>7</p>
		<p>8</p>
		<p>9</p>
		<p>10</p>
		<p>1</p>
		<p>2</p>
		<p>3</p>
		<p>4</p>
		<p>5</p>
		<p>6</p>
		<p>7</p>
		<p>8</p>
		<p>9</p>
		<p>10</p>
		<p>1</p>
		<p>2</p>
		<p>3</p>
		<p>4</p>
		<p>5</p>
		<p>6</p>
		<p>7</p>
		<p>8</p>
		<p>9</p>
		<p>10</p>
		<p>1</p>
		<p>2</p>
		<p>3</p>
		<p>4</p>
		<p>5</p>
		<p>6</p>
		<p>7</p>
		<p>8</p>
		<p>9</p>
		<p>10</p>
		<p>1</p>
		<p>2</p>
		<p>3</p>
		<p>4</p>
		<p>5</p>
		<p>6</p>
		<p>7</p>
		<p>8</p>
		<p>9</p>
		<p>10</p>
		<a href="#테스트">link</a>
	</body>
</html>
```

If you make this code to html file and click the anchor tag, works fine and there is no invalid code for HTML specs.
There is no issue with simple fragment identifier.

There are too many of this case to leave texts in English as it is.

How can I solve this problem?

I'll waiting your reply.
Have a good day! :)

## Expected behavior

dgeni build success

## Minimal reproduction of the problem with instructions

change link section name to another language and build with `yarn docs`

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by petebacondarwin** [comment]
Thanks for this info. I will take a look next week.

**Comment by han41858** [comment]
Hey~ Is there any in progress?

**Comment by petebacondarwin** [comment]
Sorry it got lost in my list of things to do. I will try to find time tomorrow

**Comment by petebacondarwin** [comment]
Well I spent considerable time on this today and it is significantly more complicated than I had hoped. It seems that we need to decode the anchor before matching in the `checkAnchorLinksProcessor` processor but this then causes problems with anchors that were encoded for API docs in angular.io...

Still working on it.

**Comment by petebacondarwin** [comment]
OK, I have worked this out. It required a new release of [dgeni-package v0.24.0](https://github.com/angular/dgeni-packages/blob/master/CHANGELOG.md#0240-26-january-2018); and then we need to land changes to the angular.io project, to deal with the breaking changes in that version.

**Comment by han41858** [comment]
wow.. It requires something more I thought... Thanks for your GREAT solution :)

**Comment by han41858** [comment]
ok, I checked it working. Thanks a lot!!
