### ISSUE TITLE
Language service: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#21459]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior
In Visual Studio code, the editor occasionally popups up the "OUTPUT" tab with the following in the output
```SERVER ERROR: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at Project.updateFileMap (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:797:94)
    at Project.updateGraph (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:815:14)
    at Project.finishGraph (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:807:14)
    at ProjectService.updateConfiguredProject (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1717:25)
    at ProjectService.openOrUpdateConfiguredProjectForFile (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1501:22)
    at ProjectService.openClientFile (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1404:23)
    at /usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:180:38
    at TextDocuments.logErrors (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:235:13)
    at /usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:173:74
    at handleNotification (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:353:21)
[Error - 4:08:11 PM] Notification handler 'textDocument/didSave' failed with message: Cannot read property 'length' of null
```

## Expected behavior
The language service should not error.

## Minimal reproduction of the problem with instructions
I have not been able to deterministically reproduce this issue, but it seems to happen with all of my CLI-based projects at some point after editing or moving components & modules.

I think @robwormald has seen this too.

## Environment
Visual Studio Code: 1.19.2-1515599945

<pre><code>
```
Angular CLI: 1.6.3
Node: 8.4.0
OS: linux x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core
... language-service, platform-browser, platform-browser-dynamic

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

Others:

</code></pre>

**Comment by chuckjaz** [comment]
This can no longer be reproduced in 0.1.9 of the plugin.
