### ISSUE TITLE
Angular bazel build broken with latest rules_typescript

### ISSUE THREAD

**Issue by gregmagolan** [angular/angular#21481]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior
Bazel build fails when using the latest rules_typescript. The build was broken in the following commit: https://github.com/bazelbuild/rules_typescript/commit/983a2ebf6dead0ccfbe0a3d6c7c5046a827e6c7b

The compiler error is as follows:

```
ERROR: /Users/greg/google/gregmagolan/angular-bazel-example/src/BUILD.bazel:5:1: Compiling Angular templates (ngc) //src:src failed (Exit 1)
: Error: Could not resolve src/hello-world/hello-world.module from /private/var/tmp/_bazel_greg/2c2a834fcea131eff2d962ffe20e1c87/bazel-sandbox/8397443511502024963/execroot/angular_bazel_example/bazel-out/darwin-fastbuild/bin/src/hello-world/hello-world.module.d.ts
    at TsCompilerAotCompilerTypeCheckHostAdapter.fromSummaryFileName (/Users/greg/google/gregmagolan/angular-bazel-example/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:210:19)
    at AotSummaryResolver.fromSummaryFileName (/Users/greg/google/gregmagolan/angular-bazel-example/node_modules/@angular/compiler/bundles/compiler.umd.js:32786:26)
    at /Users/greg/google/gregmagolan/angular-bazel-example/node_modules/@angular/compiler/bundles/compiler.umd.js:30350:64
    at Array.map (<anonymous>)
    at FromJsonDeserializer.deserialize (/Users/greg/google/gregmagolan/angular-bazel-example/node_modules/@angular/compiler/bundles/compiler.umd.js:30349:37)
    at deserializeSummaries (/Users/greg/google/gregmagolan/angular-bazel-example/node_modules/@angular/compiler/bundles/compiler.umd.js:29854:25)
    at AotSummaryResolver._loadSummaryFile (/Users/greg/google/gregmagolan/angular-bazel-example/node_modules/@angular/compiler/bundles/compiler.umd.js:32886:22)
    at AotSummaryResolver.resolveSummary (/Users/greg/google/gregmagolan/angular-bazel-example/node_modules/@angular/compiler/bundles/compiler.umd.js:32802:18)
    at StaticSymbolResolver._resolveSymbolFromSummary (/Users/greg/google/gregmagolan/angular-bazel-example/node_modules/@angular/compiler/bundles/compiler.umd.js:29366:61)
    at StaticSymbolResolver.resolveSymbol (/Users/greg/google/gregmagolan/angular-bazel-example/node_modules/@angular/compiler/bundles/compiler.umd.js:29113:74)
```

@alexeagle is aware of this regression.

## Expected behavior
The build works

## Minimal reproduction of the problem with instructions
Can reproduced by updating https://github.com/alexeagle/angular-bazel-example to the following rules_typescript:

```
git_repository(
    name = "build_bazel_rules_typescript",
    remote = "https://github.com/bazelbuild/rules_typescript.git",
    commit = "983a2ebf6dead0ccfbe0a3d6c7c5046a827e6c7b",
)
```

## Environment
Angular version: 5.2.0

**Comment by alexeagle** [comment]
I believe the problem is that eg. `core/index.ngsummary.json` has `{"__symbol":1,"name":"ANALYZE_FOR_ENTRY_COMPONENTS","filePath":"packages/core/public_api"}` and then we try to do TS module resolution on the `filePath` - so it should be written as `angular/packages/core/public_api`
