### ISSUE TITLE
gulp build.dart, resolving dependencies is not Ctrl+C-able

### ISSUE THREAD

**Issue by vicb** [angular/angular#2158]
It is not possible to cancel the step "resolving dependencies"

**Comment by IgorMinar** [comment]
this is most likely because we are running dart's pub command synchronously. Cait, can you please take a look at switch it to async? unlike other commands, this one can take a while so it is desirable to be be able to kill it with ctrl+c

**Comment by IgorMinar** [comment]
I can't repro this.

**Comment by pkozlowski-opensource** [comment]
I can see it from time to time locally but can't pin-point the exact command / root cause... But there is definitively sth fishy going on in one of the tasks.

**Comment by caitp** [comment]
I had meant to comment on this a few weeks ago, but never did. In my repro attempts, I wasn't able to reproduce this. I gave it another go today, and still no luck reproing --- however the results are slightly different and we do get an abrupt stack trace, which is sort of interesting.

```
EchoBeach:angular caitp$ gulp build.dart
[12:49:00] Warning: gulp version mismatch:
[12:49:00] Global gulp is 3.9.0
[12:49:00] Local gulp is 3.8.11
Dart SDK detected
[12:49:02] Using gulpfile ~/git/angular/gulpfile.js
[12:49:02] Starting 'build.dart'...
[12:49:02] Starting 'build/packages.dart'...
[12:49:02] Starting 'build/clean.dart'...
[12:49:02] Starting 'build/clean.tools'...
[12:49:02] Finished 'build/clean.tools' after 852 μs
[12:49:02] Starting 'build.tools'...
[12:49:02] Starting '!build.tools'...
[12:49:02] Finished 'build/clean.dart' after 257 ms
[12:49:04] Finished '!build.tools' after 2.56 s
[12:49:04] Finished 'build.tools' after 2.56 s
[12:49:04] Starting 'build/tree.dart'...
[12:49:04] Starting '!build/tree.dart'...

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
TSToDartTranspiler                            | 2645ms              
DartFormatter                                 | 1808ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
TSToDartTranspiler (1)                        | 2645ms              
DartFormatter (1)                             | 1808ms              
MergeTrees (5)                                | 676ms (135 ms)      
Funnel (10)                                   | 463ms (46 ms)       

[12:49:10] Finished '!build/tree.dart' after 5.91 s
[12:49:10] Finished 'build/tree.dart' after 5.91 s
[12:49:10] Starting '!build/pubget.angular2.dart'...
Resolving dependencies... (1.2s) ^C[12:49:12] Starting 'cleanup.builder'...
[12:49:12] Finished '!build/pubget.angular2.dart' after 1.5 s
[12:49:12] Starting '!build/change_detect.dart'...
Unhandled exception:
Uncaught Error: Load Error: FileSystemException: Cannot open file, path = '/Users/caitp/git/angular/dist/dart/angular2/test/change_detection/generator/packages/dart_style/dart_style.dart' (OS Error: No such file or directory, errno = 2)
Stack Trace:
#0      _asyncLoadErrorCallback (dart:_builtin:268)
#1      _asyncLoadError (dart:_builtin:287)
#2      _loadDataAsyncLoadPort.<anonymous closure> (dart:_builtin:304)
#3      _RootZone.runUnary (dart:async/zone.dart:1155)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#6      _Future._complete (dart:async/future_impl.dart:358)
#7      _cancelAndValue (dart:async/stream_pipe.dart:62)
#8      Stream.first.<anonymous closure> (dart:async/stream.dart:911)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1093)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:698)
#13     _StreamController._add (dart:async/stream_controller.dart:570)
#14     _StreamController.add (dart:async/stream_controller.dart:516)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:143)
[12:49:12] Finished '!build/change_detect.dart' after 108 ms
[12:49:12] Starting 'build/pure-packages.dart'...
[12:49:13] Finished 'cleanup.builder' after 744 ms
```

**Comment by naomiblack** [comment]
cannot repro.
