### ISSUE TITLE
Maximum call stack size exceeded when build --prod at StaticSymbolResolver.resolveSymbol

### ISSUE THREAD

**Issue by HeDo88TH** [angular/angular#21693]
## I'm submitting a...

<pre><code>
[ ] Regression
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I have 1 module 3 components and 1 directive. There are no circular dependencies between them. I'm using angular material. 

When I run ng build --prod this is the error that pops out (using --verbose)

<pre><code>
ng build --prod --verbose

6451ms building modules
0ms sealing
0ms optimizing
0ms basic module optimization
0ms module optimization
0ms advanced module optimization
15ms basic chunk optimization
0ms chunk optimization
0ms advanced chunk optimization
1075ms building modules
4ms module and chunk tree optimization
0ms chunk modules optimization
0ms advanced chunk modules optimization
0ms module reviving
5ms module order optimization
0ms module id optimization
0ms chunk reviving
4ms chunk order optimization
0ms chunk id optimization
4ms hashing
0ms module assets processing
8ms chunk assets processing
16ms additional chunk assets processing
0ms additional asset processing
309ms chunk asset optimization
0ms asset optimization
Hash: 1b29ef7f5e3a9970305f
Version: webpack 3.10.0
Time: 7940ms
                                   Asset      Size  Chunks  Chunk Names
polyfills.3bc34265385d52184eab.bundle.js  86 bytes       1  polyfills
     main.e402deade8b026b7d50e.bundle.js  84 bytes       2  main
   inline.92ef6709b02058cd9af2.bundle.js   1.45 kB       3  inline
  styles.9bf67ccb2b89c7f441c0.bundle.css   49.3 kB       0  styles
chunk    {0} styles.9bf67ccb2b89c7f441c0.bundle.css (styles) 122 bytes {3} [initial] [rendered]
chunk    {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 28 bytes {3} [initial] [rendered]
chunk    {2} main.e402deade8b026b7d50e.bundle.js (main) 28 bytes {3} [initial] [rendered]
chunk    {3} inline.92ef6709b02058cd9af2.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveSymbol (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:29106:14)
    at resolveReferenceValue (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32053:75)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32216:65)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  3.33 kB       0
    chunk    {0} index.html 813 bytes [entry] [rendered]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--8-1!node_modules/postcss-loader/lib/index.js??postcss!src/style.css:
    chunk    {0} extract-text-webpack-plugin-output-filename 2.68 kB [entry] [rendered]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--9-1!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--9-3!src/orange-indigo.scss:
    chunk    {0} extract-text-webpack-plugin-output-filename 51.5 kB [entry] [rendered]

ERROR in RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveSymbol (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:29106:14)
    at resolveReferenceValue (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32053:75)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32216:65)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
    at simplifyNested (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32078:28)
    at simplify (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32218:36)
    at simplifyInContext (C:\Users\HeDo\source\repos\ProductRegistrationClient\node_modules\@angular\compiler\bundles\compiler.umd.js:32421:20)
</pre></code>

Using --dev or removing --aot It works. The command serve works like a charm.

## Environment

This is my environment:

<pre><code>
Angular CLI: 1.6.4
Node: 9.4.0
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.1.0
@angular/cli: 1.6.4
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.46
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.5.3
webpack: 3.10.0

</code></pre>

I can provide the source code if needed to solve this issue, thanks

**Comment by HeDo88TH** [comment]
YesIl 23 Gen 2018 01:25, Ádám Lippai <notifications@github.com> ha scritto:Did you get this on Chrome 63 on Windows?

**Comment by mhevery** [comment]
Please file the issue with https://github.com/angular/angular-cli
