### ISSUE TITLE
Language Service Doesn't Support non-spec tsconfig.json - Unexpected token }

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#21729]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

#Steps to reproduce
* Use VSCode (version shouldn't matter)
* Open an angular application
* Have a `tsconfig.json` file that conforms to TypeScript's spec, but is not valid JSON (with an extra `,`  before a closing `}` for example)

## Current behavior
```
Search path: /usr/local/google/home/stephenfluin/workspace/devfest/src/environments
Config file name: /usr/local/google/home/stephenfluin/workspace/devfest/src/tsconfig.json
SERVER ERROR: Unexpected token } in JSON at position 449
SyntaxError: Unexpected token } in JSON at position 449
    at JSON.parse (<anonymous>)
    at parseAndReEmitConfigJSONFile (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:257:33)
    at ProjectService.configFileToProjectOptions (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1598:18)
    at ProjectService.openConfigFile (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1620:42)
    at ProjectService.openOrUpdateConfiguredProjectForFile (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1486:41)
    at ProjectService.openClientFile (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1404:23)
    at /usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:135:47
    at TextDocuments.logErrors (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:235:13)
    at /usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:131:74
    at handleNotification (/usr/local/google/home/stephenfluin/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:353:21)
[Error - 9:09:43 AM] Notification handler 'textDocument/didOpen' failed with message: Unexpected token } in JSON at position 449
```

## Expected behavior
Because TypeScript allows this file, the language service should allow it as well

## Environment

<pre><code>
Angular CLI: 1.6.2
Node: 8.4.0
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.0.2
@angular/cli: 1.6.2
@angular/material: 5.0.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0

For Tooling issues:
VS Code: Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80

>
</code></pre>

**Comment by rodmax** [comment]
Any updates? as i see in vscode-extension github repository
too many issues regarding broken extension

and i believe that folk put forward a bunch of false ideas (reinstall extension an so on) 

whereas in many cases the problem lies in this issue

it seems if typescript supports json5-like format this package should too
