### ISSUE TITLE
Error during runtime (possible Typescript issue)

### ISSUE THREAD

**Issue by DooMMasteR** [angular/angular#21776]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I get an error, when the page is loaded, as overlay, compile works fine:
<pre><code>Failed to compile.

TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/home/user/build/webclient-ng/node_modules/typescript/lib/typescript.js:15457:109)
    at parseSourceFileWorker (/home/user/build/webclient-ng/node_modules/typescript/lib/typescript.js:15389:26)
    at Object.parseSourceFile (/home/user/build/webclient-ng/node_modules/typescript/lib/typescript.js:15338:26)
    at Object.createSourceFile (/home/user/build/webclient-ng/node_modules/typescript/lib/typescript.js:15192:29)
    at new TypeScriptFileRefactor (/home/user/build/webclient-ng/node_modules/@ngtools/webpack/src/refactor.js:79:35)
    at Object.findLazyRoutes (/home/user/build/webclient-ng/node_modules/@ngtools/webpack/src/lazy_routes.js:18:22)
    at AotPlugin._findLazyRoutesInAst (/home/user/build/webclient-ng/node_modules/@ngtools/webpack/src/plugin.js:217:50)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/user/build/webclient-ng/node_modules/@ngtools/webpack/src/plugin.js:496:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)</code></pre>

## Expected behavior
I should not get the error.

## Minimal reproduction of the problem with instructions
I cannot really provide a way to reproduce

## What is the motivation / use case for changing the behavior?
Get it working.

## Environment

<pre><code>
Angular CLI: 1.6.5
Node: 6.11.1
OS: linux x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.6.5
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.3.4
webpack: 3.10.0

Browser:
- [x ] Chrome (desktop) version 65
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 57
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.1
- Platform:  Linux

Others:
This issue suddenly appeared, the application has multiple thousand lines of code and worked fine so far.</code></pre>

**Comment by vicb** [comment]
> I cannot really provide a way to reproduce

Closing as no repro.

**Comment by DooMMasteR** [comment]
It is weird, that augmenting the mentioned lines with: 
`            if(typeof sourceText === 'undefined'){
                console.log(fileName);
            }
`
does not result in any output OR change of the error, the error stays the same, which points me at it being the result of a already compiled, typescript based package.

**Comment by zerostatic** [comment]
Did you ever figure this out? I'm having the same errors when testing
