### ISSUE TITLE
Cannot find module 'uglifyjs-webpack-plugin'

### ISSUE THREAD

**Issue by jferrer21** [angular/angular#21869]
Angular CLI: 1.6.6
Node: 8.9.4
OSX
Angular: 5.2.2

Created a new project and then ran npm start.  

Thanks for any help with this issue.

Cannot find module 'uglifyjs-webpack-plugin'
Error: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/julioferrer/test-app/node_modules/@angular/cli/models/webpack-configs/production.js:13:24)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/julioferrer/test-app/node_modules/@angular/cli/models/webpack-configs/index.js:9:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-app@0.0.0 start: `ng serve -o`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-app@0.0.0 start script.

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular-cli/issues/9427

**Comment by pkozlowski-opensource** [comment]
> dup of angular/angular-cli#9427

Yep...
