### ISSUE TITLE
Error "instance[output.propName].subscribe is not a function" resulting from polyfill

### ISSUE THREAD

**Issue by supdegrave** [angular/angular#22065]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

I'm running into a strange issue. I've researched the error, and it generally seems to be related to the use of @Output or EventEmitter, but that's not the case here.

I get the following error in a component karma test, with a particular polyfill in place:

```
TypeError: instance[output.propName].subscribe is not a function
    at createDirectiveInstance (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/core.js:12319:71)
    at createViewNodes (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/core.js:13776:38)
    at callViewAction (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/core.js:14210:1)
    at execComponentViewsAction (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/core.js:14119:1)
    at createViewNodes (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/core.js:13804:1)
    at createRootView (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/core.js:13665:1)
    at callWithDebugContext (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/core.js:15090:26)
    at Object.debugCreateRootView [as createRootView] (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/core.js:14373:1)
    at ComponentFactory_.webpackJsonp.../../../core/esm5/core.js.ComponentFactory_.create (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/core.js:11260:26)
    at initComponent (http://localhost:9876/_karma_webpack_/webpack:/Users/stuart/localhost/projects/tt-new/work-group/node_modules/@angular/core/esm5/testing.js:1137:1)
```

The polyfill is as follows:

```
Object.prototype.clone = function(deep = false) {
    return (deep)
        ? JSON.parse(JSON.stringify(this)) // Deep clone - copies object property values in full.
        : Object.assign({}, this);         // Shallow clone - copies property values (including object references rather than object).
};
```

This issue does not appear to affect the application, only one specific test spec. 

Can anyone help me understand why this might cause an error inside createDirectiveInstance? If I comment this code out, the error goes away. It's not simply having a polyfill that causes problems - there's another, which adds Array.prototype.upsert, which doesn't cause problems.

## Expected behavior

Adding a polyfill should not result in a failure to create a directive. 

## Minimal reproduction of the problem with instructions

I haven't been able to figure out how to create a Plunker for karma tests. 

## Environment

<pre><code>
Angular version: 5.1.3

Browser:
- [x] Chrome (desktop) version 63.0.3239.132
</code></pre>

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by supdegrave** [comment]
@mhevery I'd love to have a better understanding of how a getting an obscure error from one polyfill and not another is considered a support issue rather than a bug. There's no clear relation between adding the polyfill and the test error. 

FYI, I posted the same question on SO a couple of days prior to posting here, with no response. https://stackoverflow.com/questions/48596826/instanceoutput-propname-subscribe-is-not-a-function-resulting-from-polyfill
