### ISSUE TITLE
Including an implied end tag for p a template should still work

### ISSUE THREAD

**Issue by NRauh** [angular/angular#22099]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When including a tag (like address) inside open and closing p tags, this error is thrown when parsing the template.

```
unpkg.com/zone.js@0.8.20/dist/zone.js:388 Error: (SystemJS) Error: Template parse errors:
	Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("
	          Townsvill, MA
	        </address>
	      [ERROR ->]</p>
	    </div>
	  "): ng:///AppModule/App.html@9:6
	    at syntaxError (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:528:34)
	    at DirectiveNormalizer._preparseLoadedTemplate (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:3263:19)
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:3243:76)
	    at Object.then (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:517:77)
	    at DirectiveNormalizer._preParseTemplate (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:3243:26)
	    at DirectiveNormalizer.normalizeTemplate (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:3221:36)
	    at CompileMetadataResolver.loadDirectiveMetadata (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:14950:75)
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:34454:72)
	    at Array.forEach (<anonymous>)
	    at eval (https://unpkg.com/@angular/compiler/bundles/compiler.umd.js:34453:72)
	Error loading https://run.plnkr.co/RVDABcX4pj5LoFyi/src/main.ts
```
I tried with a couple other tags instead of address (h2 and ul [with li]), and still had the same problem.

I checked the transpiled source, and it isn't incorrectly modifying the source, so it seems to be an issue with the parser.

## Expected behavior

Including the optional closing tag is still valid, and should be able to be parsed.

## Minimal reproduction of the problem with instructions

Add this HTML to a template. 

```html
<p>
  Some text with contact information
  <address>
    123 Somedrive
    Townsvill, MA
  </address>
</p>
```
[Here's a plnkr](https://plnkr.co/edit/NqovZvXSMEePOVif5bPv?p=preview)

## What is the motivation / use case for changing the behavior?

The w3 section for p implies that it should be optional to omit the closing tag, not that it should be required.

It should also be allowed for formatting consistency, and error prevention when optional end tags aren't known.

## Environment

<pre><code>
Angular version: 5.2.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Linux

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@NRauh ... due to HTML spec ... `The HTML <p> element represents a paragraph of text.` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p

**Comment by NRauh** [comment]
I'd look at MDN before creating this issue to double check myself, but I had misread the category for content.

I'll close the issue.
