### ISSUE TITLE
templateUrl usage with local files (file:///)  not working because of (XMLHttpRequest)  xhr.status checks

### ISSUE THREAD

**Issue by chrisber** [angular/angular#2219]
- Overview of the Issue    
  templateUrl is not able to load local files (file:///) do to xhr.status (XMLHttpRequest) checks. This prevents the usage of `templateUrl` within `@Views`   
 **stack trace:**
```
Failed to load the template "MyAppComponent"

Error
    at new BaseException (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:7159:25)
    at https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:22973:21
    at Zone.run (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:115:17)
    at Zone.execute.NgZone._createInnerZone.zone.fork.fork.$run [as run] (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:12418:38)
    at zoneBoundFn (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:88:19)
    at lib$es6$promise$$internal$$tryCatch (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:479:16)
    at lib$es6$promise$$internal$$invokeCallback (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:491:17)
    at lib$es6$promise$$internal$$publish (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:462:11)
    at lib$es6$promise$$internal$$publishRejection (https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:412:7)
    at https://code.angularjs.org/2.0.0-alpha.25/angular2.dev.js:195:9

```    

- Motivation for or Use Case      
Angular in combination with Electron must be able to load local files (file:///) like `"file:///path/to/myAppComponent.html"`. The issue appears when using `templateUrl` instead of `template` within a view. The xhr implementation expects a status response `(200 <= status && status <= 300)`, but for local files, browsers do not respond with a status code (0). Have a look at [xhr_impl.ts L15](https://github.com/angular/angular/blob/91ccc9af9846b2ce54abe2ca8fff149438c57798/modules/angular2/src/services/xhr_impl.ts#L15). This issue makes the usage of template files impossible when developing inside electron applications.    
- Angular Version(s)    
 Tested with 2.0.0-alpha.25
- Browsers and Operating System     
 all
- Reproduce the Error     
  - http://plnkr.co/edit/1P2LpY?p=info
  - Fork the repository
  - Run electron `./electron bug/`

**Comment by C4Grey** [comment]
I proposed the [solution](https://github.com/angular/angular/issues/1954) of this issue earlier...

**Comment by tlancina** [comment]
We're having this issue with Ionic as well, since Cordova uses `file://`.

https://github.com/tlancina/ng2-play

**Comment by mhevery** [comment]
Should be a trivial fix, can you submit a PR?

**Comment by mhevery** [comment]
dup of #1954 closing

**Comment by vicb** [comment]
There is already a PR (#2238), blocked on adding tests.

**Comment by mhevery** [comment]
Reopen since #2238 will close this one on merge.

**Comment by vicb** [comment]
2238 has landed as cd735c483747c66d378ae34f4755178dd0a54d70

**Comment by aro1976** [comment]
the same problem occurs on 1.4.7.

**Comment by erunge** [comment]
Hi there,
I found a workaround, i use ``__dirname`` to construct correct path to template files. It seems to work.
