### ISSUE TITLE
ngc attempts to generate metadata for rxjs Subscription in 6.0.0

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#22210]
### Steps to reproduce
1. Clone https://github.com/jelbourn/material2/tree/angular6-dep
2. `npm i`
3. `./node_modules/.bin/ngc -p ./src/cdk/collections/tsconfig-build.json`

[Relevant tsconfig](https://github.com/jelbourn/material2/blob/angular6-dep/src/cdk/collections/tsconfig-build.json)

It's also worth mentioning that the bazel build / tests for this are fine.

### Error
```
: Error: /usr/local/google/home/jelbourn/material2/node_modules/rxjs/Subscription.d.ts:21:1: Error encountered in metadata generated for exported symbol 'Subscription': 
 /usr/local/google/home/jelbourn/material2/node_modules/rxjs/Subscription.d.ts:22:12: Metadata collected contains an error that will be reported at runtime: Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler.
  {"__symbolic":"error","message":"Variable not initialized","line":21,"character":11}
    at /usr/local/google/home/jelbourn/material2/node_modules/@angular/compiler-cli/src/metadata/collector.js:667:27
    at Array.forEach (<anonymous>)
    at validateMetadata (/usr/local/google/home/jelbourn/material2/node_modules/@angular/compiler-cli/src/metadata/collector.js:655:42)
    at MetadataCollector.getMetadata (/usr/local/google/home/jelbourn/material2/node_modules/@angular/compiler-cli/src/metadata/collector.js:510:17)
    at MetadataCache.getMetadata (/usr/local/google/home/jelbourn/material2/node_modules/@angular/compiler-cli/src/transformers/metadata_cache.js:55:37)
    at Object.getSourceFileMetadata (/usr/local/google/home/jelbourn/material2/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:101:52)
    at upgradeMetadataWithDtsData (/usr/local/google/home/jelbourn/material2/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:94:28)
    at Object.readMetadata (/usr/local/google/home/jelbourn/material2/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:40:30)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (/usr/local/google/home/jelbourn/material2/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:425:34)
    at StaticSymbolResolver.getModuleMetadata (/usr/local/google/home/jelbourn/material2/node_modules/@angular/compiler/bundles/compiler.umd.js:30908:62)
```

**Comment by mlc-mlapis** [comment]
The same problem with `Observable`.

Error encountered in metadata generated for exported symbol 'Observable':
... Metadata collected contains an error that will be reported at runtime: Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler.
