### ISSUE TITLE
Error after ng eject then npm start

### ISSUE THREAD

**Issue by ahmedhassanahmedwasfy** [angular/angular#22259]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[x] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have used ng eject to get the webpack.config then i used npm start but it says : 
> webpack-dev-server --port=4200

path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:221:7)
    at module.exports (D:\Poject Extentions\wasfy\ngx-admin\node_modules\rxjs\_esm5\path-mapping.js:8:31)
    at Object.<anonymous> (D:\Poject Extentions\wasfy\ngx-admin\webpack.config.js:123:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at requireConfig (D:\Poject Extentions\wasfy\ngx-admin\node_modules\webpack\bin\convert-argv.js:97:18)
    at D:\Poject Extentions\wasfy\ngx-admin\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\Poject Extentions\wasfy\ngx-admin\node_modules\webpack\bin\convert-argv.js:102:15)
    at Object.<anonymous> (D:\Poject Extentions\wasfy\ngx-admin\node_modules\webpack-dev-server\bin\webpack-dev-server.js:223:50)

## Expected behavior
i was expecting like ng serve to run the aplication n 4200

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.1
- Platform: Windows 

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Please report angular-cli issues in its repo https://github.com/angular/angular-cli 👍

**Comment by ahmedhassanahmedwasfy** [comment]
Thanks
