### ISSUE TITLE
Change the location of tsconfig.app.json

### ISSUE THREAD

**Issue by dulcetti** [angular/angular#22421]
My file `tsconfig.app.json`:
```js
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": "../../out-tsc/app",
        "baseUrl": "../",
        "module": "es2015",
        "types": []
    },
    "exclude": [
        "test.ts",
        "../**/*.spec.ts"
    ]
}
```

### Desired behavior
I don't use the CLI.

Regards.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Hello guys. I can change the location of files tsconfig.app.json and tsconfig.spec.json? I want to put these files inside `src/config` folder. But when i try, the Terminal show me an error.

* Put the file `tsconfig.app.json` inside config folder
* Change the location of `tsconfig.json` inside `extends` into tsconfig.app.json
* Run the start of project

Return the error:
```
ERROR in TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\typescript\lib\typescript.js:12619:109)
    at parseSourceFileWorker (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\typescript\lib\typescript.js:12551:26)
    at Object.parseSourceFile (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\typescript\lib\typescript.js:12477:26)
    at Object.createSourceFile (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\typescript\lib\typescript.js:12318:29)
    at new TypeScriptFileRefactor (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\@ngtools\webpack\src\refactor.js:79:35)
    at Object.resolveEntryModuleFromMain (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\@ngtools\webpack\src\entry_resolver.js:108:20)
    at Promise.resolve.then.then (C:\Users\bruno.dulcetti\Repositorios\tfs\_componentes\Base.Template.Angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:255:54)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

## What is the motivation / use case for changing the behavior?
Organizate the project, moving the root files of `src/` to config `folder`

## Environment

<pre><code>
Angular version: 5.2.0

Browser:
- [x ] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.11.4
- Platform: Windows 10

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dulcetti** [comment]
@ericmartinezr ok, thanks

**Comment by quetzalcoatl** [comment]
@dulcetti I suppose you could try changing the path/name to tsconfig.app.json in the app definition in .angular-cli.json in the root folder of your project

**Comment by dulcetti** [comment]
@quetzalcoatl yeah. But i needed more things. Looking the links sended to me I saw how to implement :)

Thanks
