### ISSUE TITLE
SnackBar.openComponent fails in Karma after upgrading angular to 5.2.7

### ISSUE THREAD

**Issue by davidkarlsen** [angular/angular#22523]
## I'm submitting a...
<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I have a service, which has a MatSnackBar injected, which in turn does
```
return this.snackBar.openFromComponent(MessageComponent, {
        data: {
          messageKey: messageKey,
          messageType: messageType,
        },
        duration: 10000
      });
    }
```
injecting and calling the service used to work with ng 5.2.6 but fails after upgrading to 5.2.7

I get:
```
/usr/local/bin/node "/Users/et2448/Library/Application Support/IntelliJIdea2017.3/js-karma/js_reporter/karma-intellij/lib/intellijRunner.js" --karmaPackageDir=/Users/et2448/projects/tac/jfr/tac-jfr-js-client/node_modules/karma --serverPort=9876 --protocol=http: --urlRoot=/ --debug=true
'Unhandled Promise rejection:', 'Found the synthetic listener @state.done. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.', '; Zone:', 'ProxyZone', '; Task:', 'Promise.then', '; Value:', Error{ngDebugContext: DebugContext_{view: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}, nodeIndex: 0, nodeDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elDef: Object{nodeIndex: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., checkIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elView: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ..., initIndex: ...}}, ngErrorLogger: function () { ... }}, 'Error: Found the synthetic listener @state.done. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/esm5/platform-browser.js:3005:1)
    at DefaultDomRenderer2.webpackJsonp../node_modules/@angular/platform-browser/esm5/platform-browser.js.DefaultDomRenderer2.listen (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/esm5/platform-browser.js:2989:1)
    at DebugRenderer2.webpackJsonp../node_modules/@angular/core/esm5/core.js.DebugRenderer2.listen (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:15433:1)
    at listenToElementOutputs (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:10576:56)
    at createViewNodes (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:13709:1)
    at createRootView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:13631:1)
    at callWithDebugContext (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:15056:26)
    at Object.debugCreateRootView [as createRootView] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:14339:1)
    at ComponentFactory_.webpackJsonp../node_modules/@angular/core/esm5/core.js.ComponentFactory_.create (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:11236:26)
    at ComponentFactoryBoundToModule.webpackJsonp../node_modules/@angular/core/esm5/core.js.ComponentFactoryBoundToModule.create (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/esm5/core.js:4023:1)
    at DomPortalOutlet.webpackJsonp../node_modules/@angular/cdk/esm5/portal.es5.js.DomPortalOutlet.attachComponentPortal (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/cdk/esm5/portal.es5.js:402:1)
    at DomPortalOutlet.webpackJsonp../node_modules/@angular/cdk/esm5/portal.es5.js.BasePortalOutlet.attach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/cdk/esm5/portal.es5.js:284:1)
    at OverlayRef.webpackJsonp../node_modules/@angular/cdk/esm5/overlay.es5.js.OverlayRef.attach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/cdk/esm5/overlay.es5.js:655:26)
    at MatSnackBar.webpackJsonp../node_modules/@angular/material/esm5/snack-bar.es5.js.MatSnackBar._attachSnackBarContainer (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/material/esm5/snack-bar.es5.js:709:26)
    at MatSnackBar.webpackJsonp../node_modules/@angular/material/esm5/snack-bar.es5.js.MatSnackBar._attach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/material/esm5/snack-bar.es5.js:729:26)
    at MatSnackBar.webpackJsonp../node_modules/@angular/material/esm5/snack-bar.es5.js.MatSnackBar.openFromComponent (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/material/esm5/snack-bar.es5.js:620:26)
    at MessageService.webpackJsonp../src/app/services/message.service.ts.MessageService.submit (http://localhost:9876/_karma_webpack_/webpack:/src/app/services/message.service.ts:12:28)
    at http://localhost:9876/_karma_webpack_/webpack:/src/app/customer/add/add-customer.component.ts:58:31
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:388:1)
    at ProxyZoneSpec.webpackJsonp../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:79:1)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:387:1)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:138:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:858:1
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:421:1)
    at ProxyZoneSpec.webpackJsonp../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/proxy.js:103:1)
    at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:420:1)
    at Zone.webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:188:1)
    at drainMicroTaskQueue (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:595:1)
    at <anonymous>'
'Http failure response for http://localhost:9876/assets/countries.json: 404 Not Found'

Process finished with exit code 0

```

## Expected behavior
Should pass as before

## Minimal reproduction of the problem with instructions
Have a service use MatSnackBar and open a Component from a karma test, configuring the testmodule to define the Component and Service.

## What is the motivation / use case for changing the behavior?
Make it work as before.

## Environment

<pre><code>
Angular version: 5.2.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version 58.0.2 (64-bit)
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.6.1
- Platform:  Mac/Linux

**Comment by davidkarlsen** [comment]
hang on - something else must have changed breaking this - don't waste time on this quite yet

**Comment by alexeagle** [comment]
okay, please open another issue if you can confirm the problem is on our side. Thanks!

**Comment by davidkarlsen** [comment]
It seems to be tied to cli v 1.7.2

**Comment by davidkarlsen** [comment]
@alexeagle Can you reopen it?

**Comment by trotyl** [comment]
Please report to [Angular CLI](https://github.com/angular/angular-cli) if you cannot repro it with pure Angular (without Angular CLI).
