### ISSUE TITLE
Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "5.2.7"

### ISSUE THREAD

**Issue by FullStackTiger** [angular/angular#22589]
I can't fix these errors.
How can i fix these errors?

Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "5.2.7".
    at Object.<anonymous> (/Volumes/MacWork/upworkproject/aa/node_modules/@ngtools/webpack/src/index.js:27:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/MacWork/upworkproject/aa/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! washington-tractor-tr-webapp@0.0.1 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the washington-tractor-tr-webapp@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macdev/.npm/_logs/2018-03-05T12_05_09_899Z-debug.log
macdevs-iMac-2:aa macdev$ sh build-application.sh
build-application.sh: line 3: docker: command not found
build-application.sh: line 4: docker: command not found
macdevs-iMac-2:aa macdev$ npm run build

**Comment by alexeagle** [comment]
This doesn't look like a problem in Angular, it looks like a support request, which we don't handle through the issue tracker. Also this is for angular/angular-cli, not angular/angular.
Sorry!

**Comment by FullStackTiger** [comment]
Yes, I resolved these issues yesterday.
This is not a problem in Angular, Angular-cli.
I installed node and angular-cli.
