### ISSUE TITLE
I'm submitting Bug report: NullInjectorError: No provider for Router!

### ISSUE THREAD

**Issue by Jetxiaoli** [angular/angular#22586]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
 **similiar with #20389, I met an issue the provider of router**
Unhandled Promise rejection: StaticInjectorError(AppModule)[Auth0Service -> Router]: 
  StaticInjectorError(Platform: core)[Auth0Service -> Router]: 
    NullInjectorError: No provider for Router! ; Zone: <root> ; Task: Promise.then ; Value: Error: StaticInjectorError(AppModule)[Auth0Service -> Router]: 
  StaticInjectorError(Platform: core)[Auth0Service -> Router]: 
    NullInjectorError: No provider for Router!
    at _NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10854)
    at _createClass (core.js:10893)
    at _createProviderInstance$1 (core.js:10865) Error: StaticInjectorError(AppModule)[Auth0Service -> Router]: 
  StaticInjectorError(Platform: core)[Auth0Service -> Router]: 
    NullInjectorError: No provider for Router!
    at _NullInjector.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1218:19)
    at resolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1516:24)
    at tryResolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1458:16)
    at StaticInjector.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1326:20)
    at resolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1516:24)
    at tryResolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1458:16)
    at StaticInjector.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1326:20)
    at resolveNgModuleDep (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11070:25)
    at _createClass (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11109:29)
    at _createProviderInstance$1 (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11081:26)

the package version
"dependencies": {
    "@angular/animations": "5.2.6",
    "@angular/common": "5.2.6",
    "@angular/compiler": "5.2.6",
    "@angular/core": "5.2.6",
    "@angular/forms": "5.2.6",
    "@angular/http": "5.2.6",
    "@angular/platform-browser": "5.2.6",
    "@angular/platform-browser-dynamic": "5.2.6",
    "@angular/router": "5.2.6",
    "@mcs/mcs-angular": "file:../Mcs.Angular/mcs-mcs-angular-0.3.0.tgz",
    "angular2-collapsible": "0.0.41",
    "angular2-markdown": "^1.6.0",
    "angular2-jwt": "^0.2.3",
    "core-js": "^2.4.1",
    "materialize-css": "^0.98.2",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.7.1",
    "@angular/compiler-cli": "5.2.6",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.6.0"
  }

I have imported the routemodule
@NgModule({
  imports: [
    AppRoutingModule,
    BrowserModule,
    BrowserAnimationsModule,
    FormsModule,
    HttpModule,
    CollapsibleModule,
    HttpClientModule
  ],

this error happend on one site, but for another one, there is no such issue. I compared the package version and other things, there seems to be no difference.

**Comment by deepakshrma** [comment]
Please Check Auth0Service Service. Seems like you created a separate mdoule(Sub module) and forget to add something like below snippet.
```js
@NgModule ({
  imports: [RouterModule.forRoot (routes)],
  exports: [RouterModule]
})
```

**Comment by alexeagle** [comment]
We don't handle support requests on the issue tracker, but it looks like maybe @deepakshrma helped you anyway (thanks!)

Please re-open if you think there is a bug in Angular.
