### ISSUE TITLE
Error: Illegal State: external references changed when splitting Bazel build in smaller units

### ISSUE THREAD

**Issue by divdavem** [angular/angular#22820]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

While trying to use [bazel](https://bazel.build/) to build [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) (cf my bazel branch of ng-bootstrap [here](https://github.com/divdavem/ng-bootstrap/tree/bazel)), I came across an issue that I reproduced in the following minimal repository: https://github.com/divdavem/angular-bazel-bug-illegal-state

I first had a single `ng_module` rule for all modules of the demo (and the build was working fine), but I then tried to have [multiple `ng_module` rules](https://github.com/divdavem/angular-bazel-bug-illegal-state/commit/79911261b56542298d93e8dd5e1d7019d5e31086) (about one for each `@NgModule`), but then the build failed with the `Error: Illegal State: external references changed` error.

Here is the stacktrace of the error in my minimal repository:

```
ERROR: /home/user/Documents/angular-bazel-bug-illegal-state/src/mymodule/BUILD.bazel:5:1: Compiling Angular templates (ngc) //src/mymodule:mymodule failed (Exit 1)
: Error: Illegal State: external references changed in /home/user/.cache/bazel/_bazel_user/ac826a7d56e25950b7301fbe118ebd0e/bazel-sandbox/4296127360030547510/execroot/angular_bazel_bug_illegal_state/src/mymodule/index.ngfactory.ts.
Old: @angular/core,angular_bazel_bug_illegal_state/src/mymodule/index,,@angular/router,angular_bazel_bug_illegal_state/src/mymodule/mycomponent,angular_bazel_bug_illegal_state/src/shared/index.
New: @angular/core,angular_bazel_bug_illegal_state/src/mymodule/index,,@angular/router,@angular/forms,angular_bazel_bug_illegal_state/src/mymodule/mycomponent,angular_bazel_bug_illegal_state/src/shared/index
    at TsCompilerAotCompilerTypeCheckHostAdapter.updateGeneratedFile (/home/user/Documents/angular-bazel-bug-illegal-state/packages/compiler-cli/src/transformers/compiler_host.ts:296:13)
    at /home/user/Documents/angular-bazel-bug-illegal-state/packages/compiler-cli/src/transformers/program.ts:503:30
    at Array.forEach (<anonymous>)
    at AngularCompilerProgram._updateProgramWithTypeCheckStubs (/home/user/Documents/angular-bazel-bug-illegal-state/packages/compiler-cli/src/transformers/program.ts:495:33)
    at AngularCompilerProgram.initSync (/home/user/Documents/angular-bazel-bug-illegal-state/packages/compiler-cli/src/transformers/program.ts:424:12)
    at AngularCompilerProgram.get [as tsProgram] (/home/user/Documents/angular-bazel-bug-illegal-state/packages/compiler-cli/src/transformers/program.ts:397:12)
    at AngularCompilerProgram.getTsProgram (/home/user/Documents/angular-bazel-bug-illegal-state/packages/compiler-cli/src/transformers/program.ts:133:44)
    at gatherDiagnosticsForInputsOnly (/home/user/.cache/bazel/_bazel_user/ac826a7d56e25950b7301fbe118ebd0e/execroot/angular_bazel_bug_illegal_state/external/angular/src/ngc-wrapped/index.ts:277:31)
    at gatherDiagnostics (/home/user/.cache/bazel/_bazel_user/ac826a7d56e25950b7301fbe118ebd0e/execroot/angular_bazel_bug_illegal_state/external/angular/src/ngc-wrapped/index.ts:239:9)
    at Object.performCompilation (/home/user/Documents/angular-bazel-bug-illegal-state/packages/compiler-cli/src/perform_compile.ts:211:28)

Target //src:src failed to build
```

One [`SharedModule` module](https://github.com/divdavem/angular-bazel-bug-illegal-state/blob/master/src/shared/index.ts) exports `ReactiveFormsModule`, and the [other module](https://github.com/divdavem/angular-bazel-bug-illegal-state/blob/master/src/mymodule/index.ts) imports the `SharedModule` and uses reactive forms. When both are compiled together, it works fine, but when there are two separate `ng_module` rules, the build fails. A [workaround](https://github.com/divdavem/angular-bazel-bug-illegal-state/commit/af5a009619a9ef612eec50c6ac69060ad3216363) is to explicitly import directly `ReactiveFormsModule` in the module that depends on `SharedModule`.

## Expected behavior

The build runs successfully with multiple `ng_module` rules with the same code as with a single `ng_module` rule.

## Minimal reproduction of the problem with instructions

```bash
git clone https://github.com/divdavem/angular-bazel-bug-illegal-state.git
cd angular-bazel-bug-illegal-state
bazel run @yarn//:yarn
bazel build //src
```

## What is the motivation / use case for changing the behavior?

Having a modular build is a recommendation when using bazel, so that only modified parts are rebuilt.

## Environment

<pre><code>
- Angular version: 5.2.9
- Bazel version: 0.11.1
- Node version: 8.9.4
- Platform: Linux (Ubuntu 16.04.4 LTS)
</code></pre>

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
