### ISSUE TITLE
Using ts-loader and per docs causes Zone is not defined error

### ISSUE THREAD

**Issue by dottodot** [angular/angular#22891]
I have the following webpack config which is pretty much the same as the docs for my Universal server.ts

```
module.exports = {
  entry: {
    server: './server.ts'
  },
  resolve: { extensions: ['.js', '.ts'] },
  target: 'node',
  externals: [/(node_modules|main\..*\.js)/, 'ws'],
  output: {
    path: path.join(__dirname),
    filename: '[name].js'
  },

  module: {
    rules: [{ test: /\.ts$/, loader: 'ts-loader' }]
  },

  plugins: [
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      /(.+)?angular(\\|\/)core(.+)?/,
      path.join(__dirname, 'src', 'client'), // location of your src
      {} // a map of your routes
    ),
    new webpack.ContextReplacementPlugin(
      // fixes WARNING Critical dependency: the request of a dependency is an expression
      /(.+)?express(\\|\/)(.+)?/,
      path.join(__dirname, 'src', 'client'),
      {}
    )
  ],

    node: {
    __dirname: false
  }
};
```
but this gives an error of 

```
Zone.__load_patch('ZoneAwarePromise', function (global, Zone, api) {
^

ReferenceError: Zone is not defined
    at /server.js:222620:1
    at FUNCTION (/server.js:221976:10)
    at Object.<anonymous> (/server.js:221979:2)
    at __webpack_require__ (/server.js:20:30)
    at Object.<anonymous> (/server.js:214318:1)
    at __webpack_require__ (/server.js:20:30)
    at /server.js:63:18
    at Object.<anonymous> (/server.js:66:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10
```
However if I just remove the ts-loader from the webpack config it builds fine and works. So not entirely sure what it's purpose is.

```
Angular CLI: 1.7.3
Node: 8.9.4
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/material-moment-adapter: 5.2.4
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack-bundle-analyzer: 2.11.1
webpack: 3.11.0
```

**Comment by benneq** [comment]
Please just fill out the Form that appears when you click on "New Issue" or close this issue.

I'm **no** Angular developer. But I'd still like to give my opinion on Bug Reports like this.

I'm myself a developer. And it's really annoying and time consuming when users/customers report bugs like this. Now someone has to invest a lot of time to ask question about which versions are you using, which part of your code triggers the error, why you are using ContextReplacementPlugins, why you aren't using angular-cli, etc.

**Developer's time is precious!** As I said: I'm no angular dev. But from my work I can tell you, that bug reports like yours cost about 4x time (and nerves) of a "normal" bug report which provides (almost) all necessary information. And two weeks later the very same "users" / "customers" ask you "why isn't feature XYZ ready yet?" and all I can say is: "Because I spent 20 hours writing emails to you, asking questions over and over again, because of your shitty bug reports."

**Sorry for the harsh words, but I want to people to actually see and understand what they are doing.**

**Comment by dottodot** [comment]
@benneq Glad you have so much spare time on you hands to inform me of my errors. Must be nice.

**Comment by benneq** [comment]
That looks better. Thank you!

Why are you using a custom webpack config with angular-cli?
angular-cli already does all the webpack configuration for you.

Please also provide your package.json and tell us which command you use to start your application.

**Comment by dottodot** [comment]
angular cli doesn't build your express server.ts, my setup is very similar to https://github.com/angular/universal-starter

**Comment by benneq** [comment]
Still no `package.json`. You really want to make it extra hard to get help, don't you?

I now downloaded the code from angular/universal-starter master branch, and updated all dependencies in package.json to their most recent version (except webpack, because it causes trouble with `NodeTemplatePlugin.js`). It's starting fine. No errors at all.

```
{
  "name": "ng-universal-demo",
  "version": "0.0.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/angular/universal-starter.git"
  },
  "contributors": [
    "AngularClass <hello@angularclass.com>",
    "PatrickJS <patrick@angularclass.com>",
    "Jeff Whelpley <jeff@gethuman.com>",
    "Jeff Cross <crossj@google.com>",
    "Mark Pieszak <mpieszak84@gmail.com>",
    "Jason Jean <jasonjean1993@gmail.com>",
    "Fabian Wiles <fabian.wiles@gmail.com>"
  ],
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "lint": "ng lint --fix",
    "build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-hashing=false",
    "build:prerender": "npm run build:client-and-server-bundles && npm run webpack:server && npm run generate:prerender",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "generate:prerender": "cd dist && node prerender",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:prerender": "cd dist/browser && http-server",
    "serve:ssr": "node dist/server"
  },
  "pre-commit": [
    "lint"
  ],
  "private": true,
  "dependencies": {
    "@angular/animations": "5.2.9",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@angular/platform-server": "5.2.9",
    "@angular/router": "5.2.9",
    "@nguniversal/common": "5.0.0-beta.6",
    "@nguniversal/express-engine": "5.0.0-beta.6",
    "@nguniversal/module-map-ngfactory-loader": "5.0.0-beta.6",
    "core-js": "2.4.1",
    "rxjs": "5.5.7",
    "zone.js": "0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.7.3",
    "@angular/compiler-cli": "5.2.9",
    "@angular/language-service": "5.2.9",
    "@types/node": "^8.9.4",
    "codelyzer": "4.2.1",
    "cpy-cli": "^1.0.1",
    "express": "^4.16.3",
    "http-server": "^0.11.1",
    "pre-commit": "^1.2.2",
    "reflect-metadata": "^0.1.10",
    "ts-loader": "^3.5.0",
    "tslint": "^5.7.0",
    "typescript": "2.6.2",
    "webpack": "^3.11.0"
  }
}
```

**Comment by gamunax** [comment]
@dottodot 
Did you get to solve it?

**Comment by aks4it** [comment]
had same problem,
solved by making below import as the 1st line in server.ts (While editing this file i had moved this import )
import 'zone.js/dist/zone-node';

**Comment by dottodot** [comment]
Moving `import 'zone.js/dist/zone-node';` does resolve that issue but I then get a new error (see below)

What's the actual point of using the ts-loader as if I remove it, the app seems to build and run without any issues.

```
Unhandled Promise rejection: no Promise impl found ; Zone: angular ; Task: Promise.then ; Value: Error: no Promise impl found
    at Observable.forEach (/app/server.js:20315:19)
    at Router.activateRoutes (/app/server.js:204742:14)
    at /app/server.js:204703:19
    at new ZoneAwarePromise (/app/server.js:159854:29)
    at Router.runNavigate (/app/server.js:204634:16)
    at /app/server.js:204589:30
    at ZoneDelegate.invoke (/app/server.js:159351:26)
    at Object.onInvoke (/app/server.js:5051:33)
    at ZoneDelegate.invoke (/app/server.js:159350:32)
    at Zone.run (/app/server.js:159101:43) Error: no Promise impl found
    at Observable.forEach (/app/server.js:20315:19)
    at Router.activateRoutes (/app/server.js:204742:14)
    at /app/server.js:204703:19
    at new ZoneAwarePromise (/app/server.js:159854:29)
    at Router.runNavigate (/app/server.js:204634:16)
    at /app/server.js:204589:30
    at ZoneDelegate.invoke (/app/server.js:159351:26)
    at Object.onInvoke (/app/server.js:5051:33)
    at ZoneDelegate.invoke (/app/server.js:159350:32)
    at Zone.run (/app/server.js:159101:43)
```

**Comment by jenniferfell** [comment]
docsarea=universal
docsarea=webpack

**Comment by brandonroberts** [comment]
The current guide for universal provides a working example on getting started with server-side rendering.
