### ISSUE TITLE
Cyclic dependency in HTTP_INTERCEPTORS when using platform-server

### ISSUE THREAD

**Issue by marcin-j** [angular/angular#23023]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using platform-server and injecting service which uses HttpClient into HttpInterceptor the cyclic dependency error occurs.

## Expected behavior
There shouldn't be any cyclic dependency error.

For platform-browser it was fixed after https://github.com/angular/angular/issues/18224

## Minimal reproduction of the problem with instructions
Create service (DummyService) which uses HttpClient
Create HTTP_INTERCEPTORS interceptor and inject DummyService there

## Environment

<pre><code>
Angular version: 5.2.3

**Comment by MarkPieszak** [comment]
Try using the Injector to grab HttpClient, you shouldn't have any issues that way:

```ts
get http() {
    return this._injector.get(HttpClient);
  }

constructor(private injector: Injector) { }

// somewhere else
this.http.get();
```

Hope that helps!

**Comment by marcin-j** [comment]
Hey, thats what I'm doing for now and it works. I just thought that if it works for platform-browser (no cyclic dependencies) it should work for platform-server as well. Thanks for answer :)

**Comment by jaumard** [comment]
Still same error with angular 6.0.3, I'll try the injector solution

**Comment by Willovent** [comment]
I have this error as well on 6.0.3. But my interceptor is not using httpClient. 
Here is the code of the interceptor causing the issue on my project : 
```typescript
import { REQUEST } from '@nguniversal/express-engine/tokens';

@Injectable()
export class RefererInterceptor implements HttpInterceptor {
  constructor(@Optional() @Inject(REQUEST) private request) {}

  public intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    if (this.request) {
      const host = `${this.request.protocol}://${this.request.headers.host}`;
      req = req.clone({
        headers: req.headers.append('StSsrReferer', host)
      });
      return next.handle(req);
    }
  }
}

```

**Comment by vikerman** [comment]
@Willovent - what's the exact DI exception message. Want to make sure it's the same issue.

**Comment by Willovent** [comment]
@vikerman  here it is : 
```
ERROR in : Error: Provider parse errors:
Cannot instantiate cyclic dependency! HTTP_INTERCEPTORS ("[ERROR ->]"): in NgModule AppServerModule in C:/WS/SportyCustomerWeb/projects/customer/src/app/app.server.module.ts@-1:-1
    at NgModuleProviderAnalyzer.parse (C:\WS\SportyCustomerWeb\node_modules\@angular\compiler\bundles\compiler.umd.js:11448:19)
    at NgModuleCompiler.compile (C:\WS\SportyCustomerWeb\node_modules\@angular\compiler\bundles\compiler.umd.js:11817:36)
    at AotCompiler._compileModule (C:\WS\SportyCustomerWeb\node_modules\@angular\compiler\bundles\compiler.umd.js:20438:32)
    at C:\WS\SportyCustomerWeb\node_modules\@angular\compiler\bundles\compiler.umd.js:20357:66
    at Array.forEach (<anonymous>)
    at AotCompiler._compileImplFile (C:\WS\SportyCustomerWeb\node_modules\@angular\compiler\bundles\compiler.umd.js:20357:19)
    at C:\WS\SportyCustomerWeb\node_modules\@angular\compiler\bundles\compiler.umd.js:20347:70
    at Array.map (<anonymous>)
    at AotCompiler.emitAllImpls (C:\WS\SportyCustomerWeb\node_modules\@angular\compiler\bundles\compiler.umd.js:20347:35)
    at AngularCompilerProgram.generateFilesForEmit (C:\WS\SportyCustomerWeb\node_modules\@angular\compiler-cli\src\transformers\program.js:691:46)
    at AngularCompilerProgram._emitRender2 (C:\WS\SportyCustomerWeb\node_modules\@angular\compiler-cli\src\transformers\program.js:284:27)
    at AngularCompilerProgram.emit (C:\WS\SportyCustomerWeb\node_modules\@angular\compiler-cli\src\transformers\program.js:231:22)
    at AngularCompilerPlugin._emit (C:\WS\SportyCustomerWeb\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:805:49)
    at Promise.resolve.then.then.then (C:\WS\SportyCustomerWeb\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:630:54)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
