### ISSUE TITLE
ERROR in Could not resolve module @angular/core

### ISSUE THREAD

**Issue by stevermeister** [angular/angular#23160]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I've migrated from Angular4 to **Angular5** and also from webpack2 to **webapck4** and now I'm getting an error

     ERROR in Could not resolve module @angular/core

Error stack trace:
```
Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (.../node_modules/@angular/compiler/bundles/compiler.umd.js:29766:30)
    at StaticReflector.findDeclaration (.../node_modules/@angular/compiler/bundles/compiler.umd.js:31635:63)
    at StaticReflector.initializeConversionMap (.../node_modules/@angular/compiler/bundles/compiler.umd.js:31953:36)
    at new StaticReflector (.../node_modules/@angular/compiler/bundles/compiler.umd.js:31571:14)
    at Object.createAotCompiler (.../node_modules/@angular/compiler/bundles/compiler.umd.js:32957:44)
    at AngularCompilerProgram._createCompiler (.../node_modules/@angular/compiler-cli/src/transformers/program.js:404:37)
    at AngularCompilerProgram.get [as hostAdapter] (.../node_modules/@angular/compiler-cli/src/transformers/program.js:327:22)
    at AngularCompilerProgram._createProgramWithBasicStubs (.../node_modules/@angular/compiler-cli/src/transformers/program.js:435:73)
    at .../node_modules/@angular/compiler-cli/src/transformers/program.js:143:28
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:684:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

Also created question on SO - https://stackoverflow.com/questions/49647366/error-in-could-not-resolve-module-angular-core#comment86303771_49647405

## Environment

<pre><code>
Angular version: 5.2.9
 
For Tooling issues:
- Node version: 9.2.1
- Platform:  Mac
- Angular-cli: 1.7.3

**Comment by stevermeister** [comment]
I fact installing module `@angular-devkit/core` solved the problem

**Comment by shardulP** [comment]
Hi,
I am facing the same issue. I install @angular-devkit.core. Still I am getting the same error.
