### ISSUE TITLE
ReferenceError: httpParams is not defined at eval webpack-internal:

### ISSUE THREAD

**Issue by rajdharg** [angular/angular#23251]
I am trying to consume the Restful Webservice via Angular 5 component, but the parameters are not getting packaged in the Request, due to which I am getting the NULL response from the service.

And getting error while debugging as ReferenceError and SyntaxError as below:

> ReferenceError:

_"ReferenceError: httpParams is not defined at eval (eval at <anonymous> (webpack-internal:///./src/app/app.git.service.ts), <anonymous>:1:1)↵    at SafeSubscriber.eval [as _next] (webpack-internal:///./src/app/app.git.service.ts:40:13)↵    at SafeSubscriber.__tryOrUnsub (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:248:16)↵    at SafeSubscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:195:22)↵    at Subscriber._next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:136:26)↵    at Subscriber.next (webpack-internal:///./node_modules/rxjs/_esm5/Subscriber.js:100:18)↵    at XMLHttpRequest.onLoad (webpack-internal:///./node_modules/@angular/http/esm5/http.js:1628:38)↵    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421:31)↵    at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:33)↵    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:420:36)

> SyntaxError:

_SyntaxError: Unexpected end of input↵    at AppGitService.postGitUser (webpack-internal:///./src/app/app.git.service.ts:38:21)↵    at AppComponent.httpservice (webpack-internal:///./src/app/app.component.ts:34:27)↵    at Object.eval [as handleEvent] (ng:///AppModule/AppComponent.ngfactory.js:33:27)↵    at handleEvent (webpack-internal:///./node_modules/@angular/core/esm5/core.js:13763:155)↵    at callWithDebugContext (webpack-internal:///./node_modules/@angular/core/esm5/core.js:15272:42)↵    at Object.debugHandleEvent [as handleEvent] (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14859:12)↵    at dispatchEvent (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10178:25)↵    at eval (webpack-internal:///./node_modules/@angular/core/esm5/core.js:10803:38)↵    at HTMLButtonElement.eval (webpack-internal:///./node_modules/@angular/platform-browser/esm5/platform-browser.js:2680:53)↵    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421:31)_

> Service Call from Angular:

import { Injectable, Inject, ViewEncapsulation } from "@angular/core";
import { Http, Headers } from "@angular/http";
import { HttpParams, HttpHeaders } from "@angular/common/http"
import { HttpClient } from "selenium-webdriver/http";

```
@Injectable()
export class AppGitService {
    constructor(@Inject(Http) private proxy: Http){}
    
    url = "http://localhost:8081/loginangular/webapi/AngularUser/login";
    postGitUser(){
        let httpParams = {"uname":"rajdharg","paswd":"gourav"}
    
        let headers = new Headers()
        headers.append('Content-Type','application/x-www-form-urlencoded');

        return this.proxy.post(this.url,httpParams,{headers:headers}).subscribe(resp => {
            console.log("response %o , ", resp);
        });
    }
}
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
