### ISSUE TITLE
bazel test  //packages/core/test:test errors on windows

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#23281]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
```
 bazel test  //packages/core/test:test
```

will throw an error
```sh
bazel test  //packages/core/test:test
INFO: Analysed target //packages/core/test:test (0 packages loaded).
INFO: Found 1 test target...
ERROR: C:/git/angular/packages/upgrade/static/BUILD.bazel:7:1: Compiling Angular templates (ngc) //packages/upgrade/static:static failed (Exit 1)
packages/upgrade/static/public_api.ts(15,84): error TS2307: Cannot find module './src/common/angular1'.
packages/upgrade/static/public_api.ts(16,34): error TS2307: Cannot find module './src/common/downgrade_component'.
packages/upgrade/static/public_api.ts(17,35): error TS2307: Cannot find module './src/common/downgrade_injectable'.
packages/upgrade/static/public_api.ts(18,23): error TS2307: Cannot find module './src/common/version'.
packages/upgrade/static/public_api.ts(19,31): error TS2307: Cannot find module './src/static/downgrade_module'.
packages/upgrade/static/public_api.ts(20,32): error TS2307: Cannot find module './src/static/upgrade_component'.
packages/upgrade/static/public_api.ts(21,29): error TS2307: Cannot find module './src/static/upgrade_module'.

Target //packages/core/test:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 47.176s, Critical Path: 44.90s
FAILED: Build did NOT complete successfully

Executed 0 out of 1 test: 1 fails to build.

```

it looks like https://github.com/angular/angular/blob/master/packages/upgrade/static/src is being  ignored

After fixing this error (by copying the files) I get another error

```sh
bazel test  //packages/core/test:test
INFO: Analysed target //packages/core/test:test (1 packages loaded).
INFO: Found 1 test target...
FAIL: //packages/core/test:test (see C:/users/alag/appdata/local/temp/_bazel_alag/btbwur4a/execroot/angular/bazel-out/x64_windows-fastbuild/testlogs/packages/core/test/test/test.log)
INFO: From Testing //packages/core/test:test:
==================== Test output for //packages/core/test:test:
Failed to findPath for C:\users\alag\appdata\local\temp\_bazel_alag\btbwur4a\execroot\angular\bazel-out\x64_windows-fastbuild\bin\packages\core\test\test.runfiles\rxjs\index\external\rxjs\index
bootstrap failure Error: No file rxjs/external\rxjs\index found in module root rxjs//index/external\rxjs\index
    at Function.module.constructor._resolveFilename (C:\users\alag\appdata\local\temp\_bazel_alag\btbwur4a\execroot\angular\bazel-out\x64_windows-fastbuild\bin\packages\core\test\test_loader.js:354:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\users\alag\appdata\local\temp\_bazel_alag\btbwur4a\execroot\angular\packages\core\src\application_ref.ts:9:1
    at Object.defineProperty.value (C:\users\alag\appdata\local\temp\_bazel_alag\btbwur4a\execroot\angular\bazel-out\x64_windows-fastbuild\bin\packages\core\src\application_ref.js:10:17)
    at Object.<anonymous> (C:\users\alag\appdata\local\temp\_bazel_alag\btbwur4a\execroot\angular\bazel-out\x64_windows-fastbuild\bin\packages\core\src\application_ref.js:16:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

## Expected behavior
It works

For Tooling issues:
- Node version: 8.9.1
- Platform:  Windows 10

//cc @alexeagle as I know he is interested in this.

**Comment by alexeagle** [comment]
I have never tried running Angular's bazel tests on windows, so this isn't
a regression. But I'm starting to pick up Windows development again so I'll
get to this one in due time...

**Comment by jelbourn** [comment]
@alan-agius4 is this issue obsolete? Feel free to close if so.

**Comment by alan-agius4** [comment]
I reckon it is, since we now also have Windows CI.
