### ISSUE TITLE
ng test fails with an "Cannot read property 'options' of undefined" error

### ISSUE THREAD

**Issue by kblicharski** [angular/angular#23593]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When running `ng test`, I get a "Cannot read property 'options' of undefined" error.

## Expected behavior

I want to be able to run `ng test`.

### package.json
```json
{
  "dependencies": {
    "@angular-devkit/architect": "0.0.7",
    "@angular-devkit/core": "^0.4.6",
    "@angular/animations": "^6.0.0-rc.6",
    "@angular/cdk": "^6.0.0-rc.13",
    "@angular/common": "6.0.0-rc.6",
    "@angular/compiler": "6.0.0-rc.6",
    "@angular/core": "^6.0.0-rc.6",
    "@angular/forms": "6.0.0-rc.6",
    "@angular/http": "6.0.0-rc.6",
    "@angular/material": "^6.0.0-rc.13",
    "@angular/platform-browser": "6.0.0-rc.6",
    "@angular/platform-browser-dynamic": "6.0.0-rc.6",
    "@angular/router": "6.0.0-rc.6",
    "bootstrap": "^4.1.0",
    "core-js": "^2.5.5",
    "cors": "^2.8.4",
    "hammerjs": "^2.0.8",
    "helmet": "^3.12.0",
    "jasmine": "^3.1.0",
    "jquery": "^3.3.1",
    "loopback": "^3.19.0",
    "loopback-boot": "^2.27.1",
    "loopback-component-explorer": "^6.0.0",
    "loopback-connector-mysql": "^5.2.0",
    "popper.js": "^1.14.3",
    "request": "^2.85.0",
    "rxjs": "^6.0.0",
    "webpack": "^4.6.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.5.8",
    "@angular-devkit/build-webpack": "0.0.7",
    "@angular/cli": "6.0.0-rc.6",
    "@angular/compiler-cli": "6.0.0-rc.6",
    "@angular/language-service": "6.0.0-rc.6",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.0.0",
    "codelyzer": "^4.3.0",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.0.0",
    "protractor": "~5.3.1",
    "ts-node": "~6.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}
```

### karma.conf.js
```javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-webpack'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-webpack/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    customLaunchers: {
      ChromeNoSandbox: {
        base: 'Chrome',
        flags: ['--no-sandbox']
      }
    },
    singleRun: false
  });
};
```

### Output after running ng test
```bash
Cannot read property 'options' of undefined
TypeError: Cannot read property 'options' of undefined
    at init (/Users/kblicharski/code/fswe-project/node_modules/@angular-devkit/build-webpack/src/angular-cli-files/plugins/packages/angular_devkit/build_webpack/src/angular-cli-files/plugins/karma.ts:52:50)
    at Array.invoke (/Users/kblicharski/code/fswe-project/node_modules/di/lib/injector.js:75:15)
    at Injector.get (/Users/kblicharski/code/fswe-project/node_modules/di/lib/injector.js:48:43)
    at /Users/kblicharski/code/fswe-project/node_modules/karma/lib/server.js:169:20
    at Array.forEach (<anonymous>)
    at Server._start (/Users/kblicharski/code/fswe-project/node_modules/karma/lib/server.js:168:21)
    at Injector.invoke (/Users/kblicharski/code/fswe-project/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/kblicharski/code/fswe-project/node_modules/karma/lib/server.js:129:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/kblicharski/code/fswe-project/node_modules/@angular-devkit/build-angular/src/karma/packages/angular_devkit/build_angular/src/karma/index.ts:91:21)
    at Observable.subscribe (/Users/kblicharski/code/fswe-project/node_modules/rxjs/src/internal/Observable.ts:198:63)
    at /Users/kblicharski/code/fswe-project/node_modules/rxjs/src/internal/util/subscribeTo.ts:22:23
    at Object.subscribeToResult (/Users/kblicharski/code/fswe-project/node_modules/rxjs/src/internal/util/subscribeToResult.ts:18:29)
    at MergeMapSubscriber._innerSub (/Users/kblicharski/code/fswe-project/node_modules/rxjs/src/internal/operators/mergeMap.ts:139:14)
    at MergeMapSubscriber._tryNext (/Users/kblicharski/code/fswe-project/node_modules/rxjs/src/internal/operators/mergeMap.ts:135:10)
    at MergeMapSubscriber._next (/Users/kblicharski/code/fswe-project/node_modules/rxjs/src/internal/operators/mergeMap.ts:119:12)
    at MergeMapSubscriber.Subscriber.next (/Users/kblicharski/code/fswe-project/node_modules/rxjs/src/internal/Subscriber.ts:102:12)
```

## Environment
<pre><code>
- Angular version: 6.0.0-rc.6
- Chrome (desktop) version 65.0.3325.181
- Node version: v9.10.1
- Platform:  Mac
</code></pre>

## Other
Followed instructions in https://github.com/angular/angular-cli/issues/10003

**Comment by IgorMinar** [comment]
@kblicharski yes, this belong to angular/angular-cli, please repos there.

**Comment by matsko** [comment]
Moved to https://github.com/angular/angular-cli/issues/10818
