### ISSUE TITLE
building angular project ( _this.host.getOutputName is not a function)

### ISSUE THREAD

**Issue by mutasemhidmi** [angular/angular#23699]
i'm getting the below error when i try to to build my angular project 
ERROR in TypeError: _this.host.getOutputName is not a function
    at getOriginalName (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:29595:32)
    at ReferenceTransformer.visitStringMap (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:29640:43)
    at visitValue (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:427:24)
    at E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:484:65
    at Array.forEach (<anonymous>)
    at ReferenceTransformer.ValueTransformer.visitStringMap (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:484:26)
    at ReferenceTransformer.visitStringMap (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:29667:60)
    at visitValue (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:427:24)
    at E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:484:65
    at Array.forEach (<anonymous>)
    at ReferenceTransformer.ValueTransformer.visitStringMap (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:484:26)
    at ReferenceTransformer.visitStringMap (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:29667:60)
    at visitValue (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:427:24)
    at E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:484:65
    at Array.forEach (<anonymous>)
    at ReferenceTransformer.ValueTransformer.visitStringMap (E:\visual studio code\angularJS\dentist-website\node_modules\@angular\compiler\bundles\compiler.umd.js:484:26)
and here is my json package file 
{
  "name": "dentist-website",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.5",
    "@angular/cdk": "^5.0.0-rc.2",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/material": "^5.0.0-rc.2",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@hallysonh/ngx-imageviewer": "^1.2.2",
    "@aspnet/signalr-client": "^1.0.0-alpha2-final",
    "@swimlane/ngx-datatable": "^11.3.2",
    "angular-calendar": "^0.23.3",
    "angular-font-awesome": "^3.1.2",
    "angular2-busy": "^2.0.4",
    "angular2-image-gallery": "^1.0.1",
    "angular5-toaster": "^1.0.2",
    "auth0-js": "^9.2.3",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "firebase-reporting": "0.0.15",
    "firebase-reporting-angular": "0.0.4",
    "font-awesome": "^4.7.0",
    "googleapis": "^23.0.0",
    "html2pdf.js": "^0.8.2",
    "jquery": "^3.2.1",
    "jspdf": "^1.3.5",
    "ng2-file-input": "^1.1.0",
    "ng2-image-viewer": "^1.1.1",
    "ng2-signalr": "^2.1.1",
    "ngx-image-viewer": "^1.0.0",
    "ngx-ssrs-reportviewer": "^1.0.2",
    "paypal-checkout": "^4.0.178",
    "rxjs": "^5.5.2",
    "signalr": "^2.2.2",
    "web-animations-js": "^2.3.1",
    "xcomponent": "^6.0.41",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.2",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
