### ISSUE TITLE
Guide – Angular Universal: server-side rendering – Not working or docs not updated

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular#23795]
I tried to setup the universal example provided on the angular.io guide page: https://angular.io/guide/universal

Unfortunately, it fails with that error:

```
......
chunk {3} main.5455f303c46ef36adeb1.js (main) 346 kB [initial] [rendered]
Target 'server' could not be found in project 'angular.io-example'.
Error: Target 'server' could not be found in project 'angular.io-example'.
    at Architect._getProjectTarget (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/@angular-devkit/architect/src/architect.js:90:19)
    at Architect.getBuilderConfiguration (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/@angular-devkit/architect/src/architect.js:97:29)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/@angular/cli/models/architect-command.js:77:55)
    at MergeMapSubscriber._tryNext (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/rxjs/internal/Subscriber.js:103:18)
    at TapSubscriber._next (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/rxjs/internal/operators/tap.js:109:26)
    at TapSubscriber.Subscriber.next (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/Users/marvinheilemann/Downloads/toh-pt6/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-io-example@1.0.0 build:client-and-server-bundles: `ng build --prod && ng run angular.io-example:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-io-example@1.0.0 build:client-and-server-bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marvinheilemann/.npm/_logs/2018-05-09T11_30_03_776Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-io-example@1.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run webpack:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-io-example@1.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marvinheilemann/.npm/_logs/2018-05-09T11_30_03_801Z-debug.log
```

It does not create any server or browser folder, just an `angular.io-example` folder. The download of the finished sample code is working… maybe someone just needs to update the page

**Comment by RomanYablonski** [comment]
the same problem...

**Comment by zaid4kspr** [comment]
same here !

**Comment by raghav141988** [comment]
Same problem

**Comment by BrendanHenryGithub** [comment]
I meet the same problem. Compare to the final code, the tutorial need to add 2 steps: modify the  "/angular.json" file and the create the file "/src/main.server.ts".

**Comment by vikerman** [comment]
@brandonroberts - Can you take a look?

**Comment by igorp1** [comment]
@BrendanHenryGithub is right, I was able to fix the build by:

1. creating a `/src/main.server.ts` file with:
```typescript
export { AppServerModule } from './app/app.server.module';
```

2. adding a server target to `/angular.json` right under lint:
```json
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          }
        }
```
Should end up looking kinda like this:
```json
...
       "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          }
        }
...
```

**Comment by brandonroberts** [comment]
That's correct. The example zip file has all the necessary changes, the files just need to be exposed in the guide. I'll get a fix in for this

**Comment by Maximaximum** [comment]
I get a similar error, `Project 'angular.io-example' could not be found in workspace.` when trying to follow the tutorial with all the latest package versions. :(

**Comment by ilwebdifabio** [comment]
I think it's a typo
`"build:client-and-server-bundles": "ng build --prod && ng run angular.io-example:server",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors"`

should be:

`"build:client-and-server-bundles": "ng build --prod && ng run webpack:server",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors"`

**Comment by tomfordweb** [comment]
For me, it was because I needed to replace `angular.io-example` in the `build:ssr` script to the name of my project as seen under `projects` in `/angular.json`.

Easy to see if you just search `angular.io-example` in the sample project they give you on the SSR docs.

/angular.json
```
  "projects": {
    "foobar": { // this is the name of the project
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
```

/package.json
`"build:client-and-server-bundles": "ng build --prod && ng run foobar:server",`

**Comment by github-mayur** [comment]
@tomfordweb I have tried the same way you mentioned here, but still it is showing the same error. 

My command are,

```
"build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
"serve:ssr": "node dist/server",
"build:client-and-server-bundles-old": "ng build --prod --extract-css && ng run frontend:server",
"webpack:server": "webpack --config webpack.server.config.js --progress --colors"
```

and I am facing error as below,

```
"C:\JetBrains\PhpStorm 2018.2\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run build:ssr --scripts-prepend-node-path=auto

> frontend@0.0.0 build:ssr C:\Users\mchampaneria\phpstormprojects\angular_win\frontend
> npm run build:client-and-server-bundles && npm run webpack:server


> frontend@0.0.0 build:client-and-server-bundles C:\Users\mchampaneria\phpstormprojects\angular_win\frontend
> ng run frontend:server

Target 'server' could not be found in project 'frontend'.
Error: Target 'server' could not be found in project 'frontend'.
    at Architect._getProjectTarget (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\@angular-devkit\architect\src\architect.js:90:19)
    at Architect.getBuilderConfiguration (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\@angular-devkit\architect\src\architect.js:97:29)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\@angular\cli\models\architect-command.js:72:55)
    at MergeMapSubscriber._tryNext (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\Subscriber.js:64:18)
    at TapSubscriber._next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\operators\tap.js:62:26)
    at TapSubscriber.Subscriber.next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\operators\mergeMap.js:84:26)
    at InnerSubscriber._next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\InnerSubscriber.js:25:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 build:client-and-server-bundles: `ng run frontend:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.0.0 build:client-and-server-bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mchampaneria\AppData\Roaming\npm-cache\_logs\2018-08-17T09_15_10_808Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run webpack:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mchampaneria\AppData\Roaming\npm-cache\_logs\2018-08-17T09_15_10_839Z-debug.log

Process finished with exit code 1

```

what should I do now?

**Comment by helmar81** [comment]
npm run build:ssr; npm run serve:ssr
same issue, get error message : missing script: build:ssr
