### ISSUE TITLE
Get rid of App Injector / improve Element Injector

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2379]
# Goals

- [ ] Get rid of app `Injector`
- [x] Allow `@Injectable` annotation to declare default visibility, default to `@Unbound(self: true)`
- [x] All Directive's default visibility is hidden.
- [x] Introduce `@Self` annotation to inject from current element.
- [x] Have consumer of injection be able to override the default visibility.
- [x] Root/platform injector on `HTML` element which has common instances (Location, Cookies, etc).

**Comment by mhevery** [comment]
cc: @matanlurey @vicb @tbosch @yjbanov @jbdeboer

**Comment by tbosch** [comment]
In the case of multiple ng apps we will have multiple injectors on the `html` element, but I think this is ok.

**Comment by tbosch** [comment]
So visibility can then be restricted by both sides, the place where a token is bound, and the place where a token is consumed? (and both via `@Self`, `@Unbound`, ...)?

**Comment by mdausmann** [comment]
So for the dummies does this mean that the intent is to drop this approach
```javascript
@Component({
    selector: 'my-canvas',
    appInjector:[NoteService]
})
//...etc
constructor(_noteService: NoteService) {
    this.noteService = _noteService;
}
```
in favour of this approach?
```javascript
constructor(@Inject(NoteService)_noteService:NoteService) {
    this.noteService = _noteService;
}
```

**Comment by mhevery** [comment]
@mdausmann you are confusing usage and declarations. We are changing `appInjector` to `hostInjectables`

**Comment by naomiblack** [comment]
This is also internal b/21721756

**Comment by matanlurey** [comment]
@mhevery is there a design document or anything I can follow along with? In theory this looks good, but I'd like to better understand the overall picture.

**Comment by vsavkin** [comment]
I am making some progress on the issue. See https://github.com/angular/angular/pull/2737 https://github.com/angular/angular/pull/2760.

There is one PR left that will remove the app injector tree.

**Comment by vsavkin** [comment]
Closed https://github.com/angular/angular/pull/2797

**Comment by bl-nero** [comment]
https://angular.io/docs/ts/latest/guide/displaying-data.html still refers to the outdated syntax.

**Comment by PascalPrecht** [comment]
@bl-nero docs are being rewritten, hold your horses :)

**Comment by miqmago** [comment]
To avoid someone else +4 hours looking for this, trying to inject a HeroService into AppComponent, (frustrating):
I'm using alpha.44

```javascript
class HeroService {
	heroes: Hero[];
	constructor() {
        this.heroes = HEROES;
	}
	getHeroes() {
        return this.heroes;
	}
}

@Component({
	selector: 'my-app',
	directives: [CORE_DIRECTIVES, FORM_DIRECTIVES],
	template: '<h1>Hello {{title}}</h1>',
	providers: [HeroService]
})
class AppComponent {
	public title = "World";
	public heroes;
	public selectedHero: Hero;
	
	constructor(@Inject(HeroService)heroService: HeroService) {
		this.heroes = heroService.getHeroes();
	}
```

**Comment by PascalPrecht** [comment]
@miqmago if you use Typescript, you should actually be able to just do 
```
constructor(heroService: HeroService) { }
```

In that particular case, since TS already emits metadata due to `@Component`.

**Comment by miqmago** [comment]
I've been trying this and many combinations of this for many hours always getting "Error: No Directive annotation found on AppComponent" or similar. The only combination that worked for me is the one I've posted.

**Comment by robwormald** [comment]
make sure that you have --emitDecoratorMetadata turned on in the TS compiler as well.

**Comment by miqmago** [comment]
Yes I have. This is the compiled file when using proposed solution by @PascalPrecht:

```javascript
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var angular2_1 = require('angular2/angular2');
/// <reference path="./templates/staticContent" />
var mock_heroes_1 = require('./mock-heroes');
var HeroService = (function () {
    function HeroService() {
        this.heroes = mock_heroes_1.HEROES;
    }
    HeroService.prototype.getHeroes = function () {
        return this.heroes;
    };
    return HeroService;
})();
exports.HeroService = HeroService;
var AppComponent = (function () {
    function AppComponent(heroService) {
        this.title = "Hello World";
        this.heroes = heroService.getHeroes();
    }
    AppComponent.prototype.onSelect = function (hero) {
        this.selectedHero = hero;
    };
    AppComponent.prototype.getSelectedClass = function (hero) {
        return {
            'selected': hero === this.selectedHero
        };
    };
    AppComponent = __decorate([
        angular2_1.Component({
            selector: 'my-app',
            directives: [angular2_1.CORE_DIRECTIVES, angular2_1.FORM_DIRECTIVES],
            template: staticContent.app_html,
            styles: [staticContent.app_css]
        })
    ], AppComponent);
    return AppComponent;
})();
angular2_1.bootstrap(AppComponent);
```

I'm using grunt-ts and this is the Gruntfile.js:

```javascript
module.exports = function(grunt) {
        //tsconfig: './src/tsconfig.json',
  grunt.initConfig({
    ts: {
      default : {
		src: ['src/app/**/*.ts'],
		html: ['src/app/templates/**/*.html', 'src/app/templates/**/*.css'],
		watch: 'src/.',
		outDir: 'public/app',
		options: {
			target: "ES5",
			module: "commonjs",
			sourceMap: false,
			emitDecorationMetadata: true,
			experimentalDecorators: true,
			removeComments: false,
			noImplicitAny: false,
			htmlModuleTemplate: 'staticContent',
			htmlVarTemplate: '<%= filename %>_<%= ext %>'
		}
      }
    }
  });
  grunt.loadNpmTasks("grunt-ts");
  grunt.registerTask("default", ["ts"]);
};
```

And I'm getting this error:

```
EXCEPTION: Cannot resolve all parameters for AppComponent(?). Make sure they all have valid type or annotations.
angular2.dev.js:21835 EXCEPTION: Cannot resolve all parameters for AppComponent(?). Make sure they all have valid type or annotations.BrowserDomAdapter.logError @ angular2.dev.js:21835BrowserDomAdapter.logGroup @ angular2.dev.js:21846ExceptionHandler.call @ angular2.dev.js:4431(anonymous function) @ angular2.dev.js:19543NgZone._onError @ angular2.dev.js:10711errorHandling.onError @ angular2.dev.js:10630run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10670run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21835 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:21835ExceptionHandler.call @ angular2.dev.js:4433(anonymous function) @ angular2.dev.js:19543NgZone._onError @ angular2.dev.js:10711errorHandling.onError @ angular2.dev.js:10630run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10670run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21835 Error: Cannot resolve all parameters for AppComponent(?). Make sure they all have valid type or annotations.
    at NoAnnotationError.BaseException [as constructor] (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:16034:21)
    at new NoAnnotationError (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:4983:14)
    at _dependenciesFor (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:20066:13)
    at resolveFactory (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:19964:22)
    at Object.resolveProvider (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:19983:66)
    at Function.DirectiveProvider.createFromProvider (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:23906:27)
    at Function.DirectiveProvider.createFromType (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:23915:32)
    at provideDirective (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:27209:49)
    at http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:27188:14
    at Array.map (native)BrowserDomAdapter.logError @ angular2.dev.js:21835ExceptionHandler.call @ angular2.dev.js:4434(anonymous function) @ angular2.dev.js:19543NgZone._onError @ angular2.dev.js:10711errorHandling.onError @ angular2.dev.js:10630run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10670run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21845 EXCEPTION: TypeError: Cannot read property 'location' of undefined
angular2.dev.js:21835 EXCEPTION: TypeError: Cannot read property 'location' of undefinedBrowserDomAdapter.logError @ angular2.dev.js:21835BrowserDomAdapter.logGroup @ angular2.dev.js:21846ExceptionHandler.call @ angular2.dev.js:4431(anonymous function) @ angular2.dev.js:19543NgZone._onError @ angular2.dev.js:10711errorHandling.onError @ angular2.dev.js:10630run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10670run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21835 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:21835ExceptionHandler.call @ angular2.dev.js:4433(anonymous function) @ angular2.dev.js:19543NgZone._onError @ angular2.dev.js:10711errorHandling.onError @ angular2.dev.js:10630run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10670run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21835 TypeError: Cannot read property 'location' of undefined
    at angular2.dev.js:19434
    at Zone.run (angular2.dev.js:138)
    at Zone.run (angular2.dev.js:10644)
    at zoneBoundFn (angular2.dev.js:111)
    at lib$es6$promise$$internal$$tryCatch (angular2.dev.js:1507)
    at lib$es6$promise$$internal$$invokeCallback (angular2.dev.js:1519)
    at lib$es6$promise$$internal$$publish (angular2.dev.js:1490)
    at angular2.dev.js:219
    at microtask (angular2.dev.js:10670)
    at Zone.run (angular2.dev.js:138)BrowserDomAdapter.logError @ angular2.dev.js:21835ExceptionHandler.call @ angular2.dev.js:4434(anonymous function) @ angular2.dev.js:19543NgZone._onError @ angular2.dev.js:10711errorHandling.onError @ angular2.dev.js:10630run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10670run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21845 EXCEPTION: TypeError: Cannot read property 'hostView' of undefined
angular2.dev.js:21835 EXCEPTION: TypeError: Cannot read property 'hostView' of undefinedBrowserDomAdapter.logError @ angular2.dev.js:21835BrowserDomAdapter.logGroup @ angular2.dev.js:21846ExceptionHandler.call @ angular2.dev.js:4431(anonymous function) @ angular2.dev.js:19543NgZone._onError @ angular2.dev.js:10711errorHandling.onError @ angular2.dev.js:10630run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10670run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21835 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:21835ExceptionHandler.call @ angular2.dev.js:4433(anonymous function) @ angular2.dev.js:19543NgZone._onError @ angular2.dev.js:10711errorHandling.onError @ angular2.dev.js:10630run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10670run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:21835 TypeError: Cannot read property 'hostView' of undefined
    at tick (angular2.dev.js:19626)
    at Zone.run (angular2.dev.js:138)
    at Zone.run (angular2.dev.js:10644)
    at zoneBoundFn (angular2.dev.js:111)
    at lib$es6$promise$$internal$$tryCatch (angular2.dev.js:1507)
    at lib$es6$promise$$internal$$invokeCallback (angular2.dev.js:1519)
    at lib$es6$promise$$internal$$publish (angular2.dev.js:1490)
    at angular2.dev.js:219
    at microtask (angular2.dev.js:10670)
    at Zone.run (angular2.dev.js:138)BrowserDomAdapter.logError @ angular2.dev.js:21835ExceptionHandler.call @ angular2.dev.js:4434(anonymous function) @ angular2.dev.js:19543NgZone._onError @ angular2.dev.js:10711errorHandling.onError @ angular2.dev.js:10630run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10670run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10644zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
```

Also
```
EXCEPTION: TypeError: Cannot read property 'location' of undefined
angular2.dev.js:21845
EXCEPTION: TypeError: Cannot read property 'hostView' of undefined
angular2.dev.js:21845
```

**Comment by robwormald** [comment]
your compiled code doesn't appear to reference `providers: [HeroService]` like your original post does... can you confirm it's there?

**Comment by miqmago** [comment]
@robwormald the compiled code is without providers, to show the error when not using @Inject.

Anyway, I've tried with providers and without inject and the result is the same error. Here it is the js code with providers:

```javascript
(function(require, exports, module, __filename, __dirname, global, GLOBAL) {var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var angular2_1 = require('angular2/angular2');
var heroes_service_1 = require('./heroes-service');
/// <reference path="./templates/staticContent" />
var AppComponent = (function () {
    function AppComponent(heroService) {
        this.title = "Hello World";
        this.heroes = heroService.getHeroes();
    }
    AppComponent.prototype.onSelect = function (hero) {
        this.selectedHero = hero;
    };
    AppComponent.prototype.getSelectedClass = function (hero) {
        return {
            'selected': hero === this.selectedHero
        };
    };
    AppComponent = __decorate([
        angular2_1.Component({
            selector: 'my-app',
            directives: [angular2_1.CORE_DIRECTIVES, angular2_1.FORM_DIRECTIVES],
            template: staticContent.app_html,
            styles: [staticContent.app_css],
            providers: [heroes_service_1.HeroService]
        })
    ], AppComponent);
    return AppComponent;
})();
angular2_1.bootstrap(AppComponent);

}).apply(__cjsWrapper.exports, __cjsWrapper.args);
```

**Comment by miqmago** [comment]
In fact here it is splitted in two files, but the result is the same if HeroService is in the same app.ts file...

**Comment by miqmago** [comment]
And here it is the compiled code with `@Inject`, wich in fact, it works:

```javascript
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __param = (this && this.__param) || function (paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
};
var angular2_1 = require('angular2/angular2');
var heroes_service_1 = require('./heroes-service');
/// <reference path="./templates/staticContent" />
var AppComponent = (function () {
    function AppComponent(heroService) {
        this.title = "Hello World";
        this.heroes = heroService.getHeroes();
    }
    AppComponent.prototype.onSelect = function (hero) {
        this.selectedHero = hero;
    };
    AppComponent.prototype.getSelectedClass = function (hero) {
        return {
            'selected': hero === this.selectedHero
        };
    };
    AppComponent = __decorate([
        angular2_1.Component({
            selector: 'my-app',
            directives: [angular2_1.CORE_DIRECTIVES, angular2_1.FORM_DIRECTIVES],
            template: staticContent.app_html,
            styles: [staticContent.app_css],
            providers: [heroes_service_1.HeroService]
        }),
        __param(0, angular2_1.Inject(heroes_service_1.HeroService))
    ], AppComponent);
    return AppComponent;
})();
angular2_1.bootstrap(AppComponent);

```

**Comment by PascalPrecht** [comment]
> Anyway, I've tried with providers and without inject and the result is the same error. Here it is the js code with providers

You always need to declare providers no matter how you inject services.

We can see that in your compiled version without `@Inject`, the `__decorate()` function is missing. This shouldn't be the case, because TS adds this function as soon as it sees your `@Component()` decorator.

Your grunt config says:

```
emitDecorationMetadata: true,
```

Shouldn't this be

```
emitDecoratorMetadata: true
```
?

**Comment by miqmago** [comment]
@PascalPrecht Thanks a lot, this was the issue, don't know from where I've taken `emitDecorationMetadata`...

**Comment by PascalPrecht** [comment]
You're very welcome! Let's hope that no one else spends 4 hours on this. :)

**Comment by shaohaolin** [comment]
I just noticed that appInjector got removed. What should I replace for the following code ( from ng-conf-2015 ToDoApp)

```
@Component({
  selector: 'todo-app',
  appInjector: [
    AngularFire,
    bind(Firebase).toValue(new Firebase('https://webapi.firebaseio-demo.com/test'))
]})
```

There is viewProviders according to Angular 2 Cheat Sheet. Should I replace appInjector to viewProviders?

Thank you.

**Comment by matanlurey** [comment]
@shaohaolin: You can use:

```js
@Component({
  selector: 'todo-app',
  providers: [
    AngularFire,
    provide(Firebase, useValue: new Firebase('https://webapi.firebaseio-demo.com/test'))
  ]
})
```
