### ISSUE TITLE
DynamicChangeDetector._check is truncating stack traces

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#2390]
My application is throwing an exception during change detection; however, DynamicChangeDetector is not reporting the complete stack trace.

It prints
```
STACKTRACE:
[#0      DynamicChangeDetector._check (package:angular2/src/change_detection/dynamic_change_detector.dart:165:7)
#1      DynamicChangeDetector.detectChangesInRecords (package:angular2/src/change_detection/dynamic_change_detector.dart:106:27)
#2      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:48:10)
#3      AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#4      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#5      AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#6      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#7      AbstractChangeDetector._detectChangesInLightDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:59:12)
#8      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:49:10)
#9      AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#10     AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#11     AbstractChangeDetector.detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:41:10)
#12     LifeCycle.tick (package:angular2/src/core/life_cycle/life_cycle.dart:77:26)
#13     LifeCycle.registerWith.<anonymous closure> (package:angular2/src/core/life_cycle/life_cycle.dart:59:68)
#14     _rootRun (dart:async/zone.dart:904)
#15     _ZoneDelegate.run (dart:async/zone.dart:503)
#16     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:150:20)
#17     _CustomZone.run (dart:async/zone.dart:803)
#18     _CustomZone.runGuarded (dart:async/zone.dart:709)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#21     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#22     _ScheduleImmediateHelper._handleMutation (dart:html:42503)
]
```

when it should print:
```
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _LocalInstanceMirror._invokeGetter (dart:mirrors-patch/mirrors_impl.dart:533)
#3      _LocalInstanceMirror._getFieldSlow (dart:mirrors-patch/mirrors_impl.dart:450)
#4      _LocalInstanceMirror.getField (dart:mirrors-patch/mirrors_impl.dart:464)
#5      ReflectionCapabilities.getter.<anonymous closure> (package:angular2/src/reflection/reflection_capabilities.dart:82:44)
#6      DynamicChangeDetector._calculateCurrValue (package:angular2/src/change_detection/dynamic_change_detector.dart:200:22)
#7      DynamicChangeDetector._referenceCheck (package:angular2/src/change_detection/dynamic_change_detector.dart:174:26)
#8      DynamicChangeDetector._check (package:angular2/src/change_detection/dynamic_change_detector.dart:162:21)
#9      DynamicChangeDetector.detectChangesInRecords (package:angular2/src/change_detection/dynamic_change_detector.dart:106:27)
#10     AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:48:10)
#11     AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#12     AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#13     AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#14     AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#15     AbstractChangeDetector._detectChangesInLightDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:59:12)
#16     AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:49:10)
#17     AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#18     AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#19     AbstractChangeDetector.detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:41:10)
#20     LifeCycle.tick (package:angular2/src/core/life_cycle/life_cycle.dart:77:26)
#21     LifeCycle.registerWith.<anonymous closure> (package:angular2/src/core/life_cycle/life_cycle.dart:59:68)
#22     _rootRun (dart:async/zone.dart:904)
#23     _ZoneDelegate.run (dart:async/zone.dart:503)
#24     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:150:20)
#25     _CustomZone.run (dart:async/zone.dart:803)
#26     _CustomZone.runGuarded (dart:async/zone.dart:709)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#29     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#30     _ScheduleImmediateHelper._handleMutation (dart:html:42503)
```

Notice the first stack trace is missing 7 frames.

**Comment by vicb** [comment]
@jbdeboer I think it is a feature of [stack_trace](https://pub.dartlang.org/packages/stack_trace) which filters out internal dart frames, are those valuables ?

**Comment by jbdeboer** [comment]
No, some of the missing frames are in Angular.

The issue is that Angular is catching exceptions and throwing new,
different, exceptions from the catch block.

**Comment by mhevery** [comment]
@vsavkin has reworked the error reporting quite a bit to make it a lot more useful. Closing as this issue is now stale.
