### ISSUE TITLE
Red herring error message: Class 'Object' has no instance getter 'value'.

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#2392]
For a demo, see https://github.com/jbdeboer/angular2_router_eating_stack_traces, ```pub serve``` the app and click on the "The same, with bindings" link.

When a component fails to be constructed, its template is still loaded, but Angular evaluates the template expressions against ```Object``` instead of the component instance.  These error messages are quite confusing and lead the developer down an incorrect debugging path.

e.g.
```
Class 'Object' has no instance getter 'value'.

NoSuchMethodError: method not found: 'value'
Receiver: Instance of 'Object'
Arguments: [] in [{{value}} in BindingsView]
STACKTRACE:
#0      DynamicChangeDetector._check (package:angular2/src/change_detection/dynamic_change_detector.dart:165:7)
#1      DynamicChangeDetector.detectChangesInRecords (package:angular2/src/change_detection/dynamic_change_detector.dart:106:27)
#2      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:48:10)
#3      AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#4      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#5      AbstractChangeDetector._detectChangesInLightDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:59:12)
#6      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:49:10)
#7      AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:65:12)
#8      AbstractChangeDetector._detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:51:10)
#9      AbstractChangeDetector.detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:41:10)
#10     LifeCycle.tick (package:angular2/src/core/life_cycle/life_cycle.dart:77:26)
#11     LifeCycle.registerWith.<anonymous closure> (package:angular2/src/core/life_cycle/life_cycle.dart:59:68)
#12     _rootRun (dart:async/zone.dart:904)
#13     _ZoneDelegate.run (dart:async/zone.dart:503)
#14     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:150:20)
#15     _CustomZone.run (dart:async/zone.dart:803)
#16     _CustomZone.runGuarded (dart:async/zone.dart:709)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#19     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#20     _ScheduleImmediateHelper._handleMutation (dart:html:42503)
```

**Comment by mhevery** [comment]
@vsavkin reworked the error massages. This is now stale, closing.
