### ISSUE TITLE
ng build "library" with a template containing ` (grave accent) in the templateUrl throws errors.

### ISSUE THREAD

**Issue by brianpilati** [angular/angular#23997]
## I'm submitting a...
<pre><code>
[ x ] Bug report  
</code></pre>

## Current behavior
When I have a ` (grave accent) in the html of a component loaded from a templateUrl in a library the compiler throws errors.

## Expected behavior
I would expect that I could have any alpha-numeric character in a templateUrl template.

## Minimal reproduction of the problem with instructions
Step 1- Unzip the project
[angular-grave-accent.zip](https://github.com/angular/angular/files/2017760/angular-grave-accent.zip)
Step 2- npm install
Step 3- ng build grave-accent

```
dev-homie:lib brianpilati$ ng build grave-accent
Building Angular Package
Building entry point 'grave-accent'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
BUILD ERROR
: Error: <{path-remove}>/angular-grace-accent/projects/grave-accent/src/lib/grave-accent-example/grave-accent-example.component.ts:3:1: Error encountered in metadata generated for exported symbol 'GraveAccentExampleComponent':
<{path-remove}>/angular-grace-accent/projects/grave-accent/src/lib/grave-accent-example/grave-accent-example.component.ts:6:12: Metadata collected contains an error that will be reported at runtime: Tagged template expressions are not supported in metadata.
{"__symbolic":"error","message":"Tagged template expressions are not supported in metadata","line":5,"character":11}
at <{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/metadata/collector.js:707:31
at Array.forEach (<anonymous>)
  at validateMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/metadata/collector.js:695:46)
  at MetadataCollector.getMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/metadata/collector.js:550:21)
  at MetadataCache.getMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/transformers/metadata_cache.js:86:41)
  at Object.getSourceFileMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:112:56)
  at Object.readMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:46:37)
  at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:464:38)
  at StaticSymbolResolver.getModuleMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler/bundles/compiler.umd.js:19516:45)
  at StaticSymbolResolver.hasDecorators (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler/bundles/compiler.umd.js:19272:29)

  Error: : Error: <{path-remove}>/angular-grace-accent/projects/grave-accent/src/lib/grave-accent-example/grave-accent-example.component.ts:3:1: Error encountered in metadata generated for exported symbol 'GraveAccentExampleComponent':
  <{path-remove}>/angular-grace-accent/projects/grave-accent/src/lib/grave-accent-example/grave-accent-example.component.ts:6:12: Metadata collected contains an error that will be reported at runtime: Tagged template expressions are not supported in metadata.
  {"__symbolic":"error","message":"Tagged template expressions are not supported in metadata","line":5,"character":11}
  at <{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/metadata/collector.js:707:31
  at Array.forEach (<anonymous>)
    at validateMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/metadata/collector.js:695:46)
    at MetadataCollector.getMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/metadata/collector.js:550:21)
    at MetadataCache.getMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/transformers/metadata_cache.js:86:41)
    at Object.getSourceFileMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:112:56)
    at Object.readMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:46:37)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:464:38)
    at StaticSymbolResolver.getModuleMetadata (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler/bundles/compiler.umd.js:19516:45)
    at StaticSymbolResolver.hasDecorators (<{path-remove}>/angular-grace-accent/node_modules/@angular/compiler/bundles/compiler.umd.js:19272:29)

    at Object.<anonymous> (<{path-remove}>/angular-grace-accent/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
      at Generator.next (<anonymous>)
        at <{path-remove}>/angular-grace-accent/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
        at new Promise (<anonymous>)
          at __awaiter (<{path-remove}>/angular-grace-accent/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
          at Object.compileSourceFiles (<{path-remove}>/angular-grace-accent/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
          at Object.<anonymous> (<{path-remove}>/angular-grace-accent/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:44:32)
            at Generator.next (<anonymous>)
              at <{path-remove}>/angular-grace-accent/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
              at new Promise (<anonymous>)
```

## What is the motivation / use case for changing the behavior?
I had a project in Angular 5 that had a few hundred of these characters when I upgrade to angular 6 and moved it to a project ... lots of errors.

<b>There is a work around ... change ` to be &#96. However, that doesn't seem to be the "angular way".</b>

## Environment

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.3
Node: 8.9.4
OS: darwin x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.1
@angular-devkit/build-angular      0.6.1
@angular-devkit/build-ng-packagr   0.6.3
@angular-devkit/build-optimizer    0.6.1
@angular-devkit/core               0.6.1
@angular-devkit/schematics         0.6.3
@angular/cdk                       6.0.0
@angular/cli                       6.0.3
@angular/flex-layout               6.0.0-beta.15
@angular/material                  6.0.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.1
@schematics/angular                0.6.3
@schematics/update                 0.6.3
ng-packagr                         3.0.0-rc.5
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
```
<pre><code>
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.4
- Platform:  Mac

Others:

</code></pre>

**Comment by alexzuza** [comment]
https://angular.io/guide/aot-compiler#tagged-template-expressions-not-supported

**Comment by trotyl** [comment]
Not related to Angular, it's a [ng-packagr](https://github.com/dherges/ng-packagr) issue, which doesn't escape the text content when inlining resources, resulting to:

```typescript
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'lib-grave-accent-example',
  template: `<p>
    `Hello World`
</p>
`,
  styles: [``]
})
export class GraveAccentExampleComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```

Which is invalid TypeScript syntax.

Ref: https://github.com/dherges/ng-packagr/blob/master/src/lib/ng-v5/entry-point/ts/transform-sources.transform.ts
CC: @dherges

**Comment by vicb** [comment]
Thanks for the analysis @trotyl.
Could you please create an issue on the ng-packagr project ?

**Comment by dherges** [comment]
Yes, can you make me an issue? What's the expected escape sequence? A `&#96;`?

**Comment by mhevery** [comment]
closing as no action for angular.
