### ISSUE TITLE
StaticInjectorError(AppModule)[NgIf -> TemplateRef]

### ISSUE THREAD

**Issue by livershi** [angular/angular#24091]
## I'm submitting a...[ ] Bug report  

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Code

`
<ng-template ngFor let-p [ngForOf]="dataservice._datajson.navjson">
          <li *ngIf="p.children.length>0" dropdown>
            <a dropdownToggle>{{p.name}}
              <span class="caret"></span>
            </a>
            <ul dropdownMenu class="dropdown-menu nav-{{selectvalue}}-dropdown" role="menu">
              <li *ngFor="let c of p.children;">
                <a class="dropdown-item" *ngIf="(c.isShow == 1 || c.isShow == undefined) && c.attr.type=='pageNavMenu'" [routerLink]="['/manage',dataservice.webId,c.attr.pageId]">{{c.name}}</a>
                <a class="dropdown-item" *ngIf="(c.isShow == 1 || c.isShow == undefined) && c.attr.type=='linkNavMenu'" [href]="c.attr.linkUrl"
                  target="_blank">{{c.name}}</a>
                <a class="dropdown-item" *ngIf="(c.isShow == 1 || c.isShow == undefined) && c.attr.type=='articleListNavMenu'" [routerLink]="['/manage/'+dataservice.webId+'/list/'+c.attr.articleType]">{{c.name}}</a>
                <a class="dropdown-item" *ngIf="(c.isShow == 1 || c.isShow == undefined) && c.attr.type=='gameListNavMenu'" [routerLink]="['/manage',dataservice.webId,c.attr.pageId]">{{c.name}}</a>
              </li>
            </ul>
          </li>
          <li *ngIf="p.children.length==0">
            <a *ngIf="p.attr.type=='pageNavMenu'" [routerLink]="['/manage',dataservice.webId,p.attr.pageId]">{{p.name}}</a>
            <a class="dropdown-item" *ngIf="p.attr.type=='linkNavMenu'" [href]="p.attr.linkUrl" target="_blank">{{p.name}}</a>
            <a class="dropdown-item" *ngIf="p.attr.type=='articleListNavMenu'" [routerLink]="['/manage/'+dataservice.webId+'/list/'+p.attr.articleType]">{{p.name}}</a>
            <a class="dropdown-item" *ngIf="p.attr.type=='gameListNavMenu'" [routerLink]="['/manage',dataservice.webId,p.attr.pageId]">{{p.name}}</a>
          </li>
        </ng-template>
`
## Error
 StaticInjectorError(Platform: core)[NgIf -> TemplateRef]: 
    NullInjectorError: No provider for TemplateRef!
    at NullInjector.get (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:1251:19)
    at resolveToken (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:1504:24)
    at tryResolveToken (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:1454:16)
    at StaticInjector.get (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:1349:20)
    at resolveToken (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:1504:24)
    at tryResolveToken (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:1454:16)
    at StaticInjector.get (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:1349:20)
    at resolveNgModuleDep (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:9510:29)
    at NgModuleRef_.get (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10191:16)
    at resolveDep (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10556:45)
    at createClass (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10432:141)
    at createDirectiveInstance (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:10313:20)
    at createViewNodes (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:11535:36)
    at callViewAction (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:11851:13)
    at execComponentViewsAction (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:11770:13)
    at createViewNodes (webpack-internal:///./node_modules/@angular/core/fesm5/core.js:11563:5)

## Environment

<pre><code>
Angular version: 6

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by abhishekgoenka** [comment]
@livershi Is this issue resolved? if yes, what was the solution?

**Comment by RamkiPannerselvam** [comment]
https://stackoverflow.com/questions/35932074/angular2-no-provider-for-templateref-ngif-templateref
