### ISSUE TITLE
Update guide does not work (5 -> 6)

### ISSUE THREAD

**Issue by tatsujb** [angular/angular#24175]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

https://update.angular.io/
Angular Update Guide | 5.2 -> 6.0 for Advanced Apps

## Current behavior

crashes on ng update : 

```
PS C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui> npm install -g @angular/cli
C:\Users\j_bard\AppData\Roaming\npm\ng -> C:\Users\j_bard\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng

> @angular/cli@6.0.5 postinstall C:\Users\j_bard\AppData\Roaming\npm\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@6.0.5
updated 1 package in 51.476s
PS C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui> npm install @angular/cli
npm WARN rollback Rolling back minimist@1.2.0 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui\node_modules\fsevents\node_modules\rc\node_modules'
npm WARN @angular/compiler-cli@5.2.11 requires a peer of typescript@>=2.4.2 <2.7 but none is installed. You must install peer dependencies yourself.
npm WARN parcel-plugin-angular@0.5.1-next.13 requires a peer of parcel-plugin-typescript@^0.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN parcel-plugin-angular@0.5.1-next.13 requires a peer of typescript@>=2.4.2 <2.6 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@1.7.3
updated 1 package in 69.554s
PS C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui> ng update @angular/cli
Your global Angular CLI version (6.0.5) is greater than your local
version (1.7.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 104.18.95.96:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
PS C:\Users\j_bard\WebstormProjects\AirConnect\web\web.ui>
```

## Expected behavior

would at least complete task

## Minimal reproduction of the problem with instructions

take a project, and follow the update steps from the website.

## What is the motivation / use case for changing the behavior?

people want to update

For Tooling issues:
- Node version: 8.9.4
- Platform:  Windows

**Comment by destus90** [comment]
@tatsujb  try this ```npm install @angular/cli@latest```

**Comment by tatsujb** [comment]
@destus90 that unclogged things. now ng update @angular/cli ran without issue.

**Comment by keyesone66** [comment]
@tatsujb The same error will be reported
