### ISSUE TITLE
Schema Validation Failed.

### ISSUE THREAD

**Issue by 13beseztariq** [angular/angular#24394]
I upgraded angular 5 to 6. But there are lots of errors.
```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(defaultProject).
Error: Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(defaultProject).
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (E:\xampp\GitHub\bb-customer-search-result\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\workspace\workspace.js:139:42)
    at MergeMapSubscriber._tryNext (E:\xampp\GitHub\bb-customer-search-result\node_modules\rxjs\internal\operators\mergeMap.js:122:27)
    at MergeMapSubscriber._next (E:\xampp\GitHub\bb-customer-search-result\node_modules\rxjs\internal\operators\mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (E:\xampp\GitHub\bb-customer-search-result\node_modules\rxjs\internal\Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (E:\xampp\GitHub\bb-customer-search-result\node_modules\rxjs\internal\operators\mergeMap.js:141:26)
    at InnerSubscriber._next (E:\xampp\GitHub\bb-customer-search-result\node_modules\rxjs\internal\InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (E:\xampp\GitHub\bb-customer-search-result\node_modules\rxjs\internal\Subscriber.js:103:18)
    at MapSubscriber._next (E:\xampp\GitHub\bb-customer-search-result\node_modules\rxjs\internal\operators\map.js:92:26)
    at MapSubscriber.Subscriber.next (E:\xampp\GitHub\bb-customer-search-result\node_modules\rxjs\internal\Subscriber.js:103:18)
    at SwitchMapSubscriber.notifyNext (E:\xampp\GitHub\bb-customer-search-result\node_modules\rxjs\internal\operators\switchMap.js:122:26)
```
I'm using
```
Angular CLI: 6.0.0-rc.4
Node: 8.11.2
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version

@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.5.6
@angular/cdk                      6.2.1
@angular/cli                      6.0.0-rc.4
@angular/material                 6.2.1
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.5.6
@schematics/update                0.5.6
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
