### ISSUE TITLE
Failed to compile when using JSON file in combination with raw-loader

### ISSUE THREAD

**Issue by Schaekels** [angular/angular#24586]
## I'm submitting a...

<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When i use require with raw-loader in a folder where a JSON file is present. The application won't compile it throws the following error.

<pre><code>
WARNING in ./src/app/package.json (./node_modules/raw-loader!./src/app/package.json)
Module parse failed: Unexpected token m in JSON at position 0
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
    at JsonParser.parse (D:\ProjectTemplateStart\nowhere6\node_modules\webpack\lib\JsonParser.js:15:21)
    at doBuild.err (D:\ProjectTemplateStart\nowhere6\node_modules\webpack\lib\NormalModule.js:398:32)
    at runLoaders (D:\ProjectTemplateStart\nowhere6\node_modules\webpack\lib\NormalModule.js:280:12)
    at D:\ProjectTemplateStart\nowhere6\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (D:\ProjectTemplateStart\nowhere6\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (D:\ProjectTemplateStart\nowhere6\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at D:\ProjectTemplateStart\nowhere6\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at runSyncOrAsync (D:\ProjectTemplateStart\nowhere6\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\ProjectTemplateStart\nowhere6\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (D:\ProjectTemplateStart\nowhere6\node_modules\loader-runner\lib\LoaderRunner.js:202:4).js:202:4)                                                                                            tFileSystem.js:43:16)
    at Storage.finished (D:\ProjectTemplateStart\nowhere6\node_modules\enhanced-resolve\lib\CachedInputem.js:79:9)tFileSystem.js:43:16)
    at provider (D:\ProjectTemplateStart\nowhere6\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)    at D:\ProjectTemplateStart\nowhere6\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

ERROR in chunk main [initial]
[name].js
D:\ProjectTemplateStart\nowhere6\node_modules\raw-loader\index.js!D:\ProjectTemplateStart\nowhere6\src\app\package.json
Cannot read property 'replace' of undefined
</pre></code>

## Expected behavior
It would compile like it did in version 5 of angular.

## Minimal reproduction of the problem with instructions
- First you make a new empty project angular project with ng new.
- Then you add a valid json file in the app folder 'package.json'
- Copy the following code in the app.component.ts
<pre><code>
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  public requireSomething(val: string){
    return require("!!raw-loader!../" + val);
  }
}
</pre></code>

- Do ng serve / ng build and it will not compile this time.

## What is the motivation / use case for changing the behavior?
I have to include a few Typescript/html files in a folder to generate some code examples. That's why i use the raw-loader with require to load all my typescript files in a certain folder. That particular folder is also a npm package so it includes a package.json. Which makes the application crash now.

## Environment
<pre><code>
Angular version: 6.0.5

For Tooling issues:
- Node version:  8.11.1 
- Npm version: 6.1.0
- Platform:  Windows 10
</pre></code>

## My solution
I found a temporary solution for my problem.
In the file "@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\common.js";
I replaced the following line:
<pre><code>
{ test: /\.html$/, loader: 'raw-loader' },
</pre></code>
With the following code:
<pre><code>
{ test: /\.(html|ts|js)$/, loader: 'raw-loader' }

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
