### ISSUE TITLE
ng serve - No browser version for node.js core module net available

### ISSUE THREAD

**Issue by kwiniarski97** [angular/angular#24605]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I recently updated from angular 6.0.3 to 6.0.6 i used `ng update` and `ng update @angular/core`.
But when I try to run `ng serve` it prints me this:
`ng serve
** Angular Live Development Server is listening on localhost:8080, open your browser on http://localhost:8080/ **
 10% building modules 0/1 modules 1 active …cuments\repos\mip\POU.WebUI\src\main.tsNo browser version for node.js core module net available
Error: No browser version for node.js core module net available
    at getPathToModule (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\node\NodeSourcePlugin.js:23:12)
    at compiler.resolverFactory.hooks.resolver.for.tap.resolver (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\node\NodeSourcePlugin.js:131:17)
    at SyncHook.eval [as call] (eval at create (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:35:1)
    at SyncHook.lazyCompileHook [as _call] (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\tapable\lib\Hook.js:35:21)
    at ResolverFactory._create (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\ResolverFactory.js:61:33)
    at ResolverFactory.get (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\ResolverFactory.js:50:28)
    at Compilation.buildModule (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\Compilation.js:365:25)
    at moduleFactory.create (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\Compilation.js:711:12)
    at MultiModuleFactory.create (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\MultiModuleFactory.js:18:3)
    at semaphore.acquire (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\Compilation.js:658:18)
    at Semaphore.acquire (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\util\Semaphore.js:17:4)
    at Compilation._addModuleChain (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\Compilation.js:657:18)
    at Compilation.addEntry (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\Compilation.js:741:8)
    at compiler.hooks.make.tapAsync (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\webpack\lib\MultiEntryPlugin.js:41:17)
    at AsyncParallelHook.eval [as callAsync] (eval at create (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:25:1)
    at AsyncParallelHook.lazyCompileHook [as _callAsync] (C:\Users\Karol\Documents\repos\mip\POU.WebUI\node_modules\tapable\lib\Hook.js:35:21)`

## Expected behavior
App should compile and ng serve should run app.

## Minimal reproduction of the problem with instructions
upgrade from 6.0.3 to 6.0.6 and run ng serve

## What is the motivation / use case for changing the behavior?
upgrade from 6.0.3 to 6.06

## Environment

<pre><code>
Angular version: 6.0.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.5.0 and 10.4.1  
- Platform:  Windows 10
</code></pre>

**Comment by jasonaden** [comment]
Thanks for the issue. Please head over to the [Angular CLI](https://github.com/angular/angular-cli) project and file it there as this appears to only be related to the CLI.
