### ISSUE TITLE
HttpClient - TypeError: Data must be a string or a buffer. When using http.post()...

### ISSUE THREAD

**Issue by html5ravi** [angular/angular#24650]
##HTTPClient Error

Am trying to implement Login stuffs with Angular 6. 
Below api is working well with AngularJS version, Am upgrading version manually. When trying to implement this login api am getting below error

<pre><code>
   POST http://xx.xxx.com:9000/web/new_login/ 500 (Internal Server Error).

 TypeError: Data must be a string or a buffer<br> &nbsp; &nbsp;at TypeError (native)<br> &nbsp; &nbsp;at Hash.update (crypto.js:74:16)<br> &nbsp; &nbsp;at login (/home/ubuntu/STTarter/models/api.js:2810:60)<br> &nbsp; &nbsp;at WebFrameworkShim.applySegment (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:1329:17)<br> &nbsp; &nbsp;at _applyRecorderSegment (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:940:20)<br> &nbsp; &nbsp;at _doRecord (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:919:17)<br> &nbsp; &nbsp;at login (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:904:24)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/ubuntu/STTarter/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at next (/home/ubuntu/STTarter/node_modules/express/lib/router/route.js:110:13)<br> &nbsp; &nbsp;at Route.dispatch (/home/ubuntu/STTarter/node_modules/express/lib/router/route.js:91:3)<br> &nbsp; &nbsp;at WebFrameworkShim.applySegment (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:1329:17)<br> &nbsp; &nbsp;at _applyRecorderSegment (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:940:20)<br> &nbsp; &nbsp;at _doRecord (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:919:17)<br> &nbsp; &nbsp;at bound &nbsp;(/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:904:24)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/ubuntu/STTarter/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at /home/ubuntu/STTarter/node_modules/express/lib/router/index.js:267:22<br> &nbsp; &nbsp;at Function.proto.process_params (/home/ubuntu/STTarter/node_modules/express/lib/router/index.js:321:12)<br> &nbsp; &nbsp;at next (/home/ubuntu/STTarter/node_modules/express/lib/router/index.js:261:10)<br> &nbsp; &nbsp;at boundNext (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/webframework-shim.js:961:27)<br> &nbsp; &nbsp;at WebFrameworkShim.applySegment (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:1329:17)<br> &nbsp; &nbsp;at wrapper (/home/ubuntu/STTarter/node_modules/newrelic/lib/shim/shim.js:1932:17)<br> &nbsp; &nbsp;at /home/ubuntu/STTarter/server.js:46:5

</code></pre>
 
#My code is: 
<pre><code>
   const httpOptions = {
      headers: new HttpHeaders({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
    };
    let payload ={ "email":"xxxxxx@xxxxxx.com","password":"xxxxxxxx"};
    let url = "http://xx.xxxx.com:9000/web/new_login/";
    this.http.post(url,payload,httpOptions).subscribe(data => console.log(data));
</code></pre>

#My App versions are: 
<pre><code>

Angular CLI: 6.0.3
Node: 8.11.2
OS: darwin x64
Angular: 6.0.2
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/.DS_Store                <error>
@angular/animations               6.0.4
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
</code></pre>

Please help me out, how to resolve this issue.

**Comment by html5ravi** [comment]
This issue solved myself,

After removing `providers:[Interceptors]` this error gone.
