### ISSUE TITLE
Cannot run protractor tests with root

### ISSUE THREAD

**Issue by huangw5** [angular/angular#24905]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When running  //packages/bazel/test/protractor:test_chromium-local with root in a docker container, the test failed with the following error:

```
[15:22:26] I/launcher - Running 1 instances of WebDriver
[15:22:26] I/direct - Using ChromeDriver directly...
[15:23:26] E/launcher - unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.0-6-amd64 x86_64)
[15:23:26] E/launcher - WebDriverError: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.9.0-6-amd64 x86_64)
    at Object.checkLegacyResponse (/src/github.com/huangw5/angular/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/src/github.com/huangw5/angular/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/src/github.com/huangw5/angular/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:440:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/src/github.com/huangw5/angular/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/src/github.com/huangw5/angular/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/src/github.com/huangw5/angular/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/src/github.com/huangw5/angular/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/src/github.com/huangw5/angular/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/src/github.com/huangw5/angular/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/src/github.com/huangw5/angular/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/src/github.com/huangw5/angular/node_modules/protractor/node_modules/q/q.js:796:13)
    at /src/github.com/huangw5/angular/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/src/github.com/huangw5/angular/node_modules/protractor/node_modules/q/q.js:137:13)
[15:23:26] E/launcher - Process exited with error code 199
================================================================================
```

## Expected behavior

The test should pass.

## Minimal reproduction of the problem with instructions

Just run the test with root user.

## What is the motivation / use case for changing the behavior?

This is needed to run protractor tests inside a docker container without setting up non-root users.

**Comment by jelbourn** [comment]
Closing as obsolete since out build and test pipeline has changed significantly since it was filed
