### ISSUE TITLE
(group.resources.urls || []).map is not a function

### ISSUE THREAD

**Issue by bleuscyther** [angular/angular#25197]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Throws error after building prod:
**group.resources.urls || []).map is not a function**
``` console
TypeError: (group.resources.urls || []).map is not a function
    at Generator.<anonymous> (C:\...\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:275:88)
    at step (C:\...\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:59:27)
    at Object.next (C:\...\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:40:57)
    at fulfilled (C:\...\node_modules\@angular\service-worker\bundles\service-worker-config.umd.js:30:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Minimal reproduction of the problem with instructions
run `npm build --prod`

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [*] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.3  
- Platform:   Windows
</code></pre>

Others:
dependenciese:

``` json
{
 "@angular/animations": "^6.1.0",
    "@angular/cdk": "^6.4.1",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/elements": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/material": "^6.4.1",
    "@angular/material-moment-adapter": "^6.4.1",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/pwa": "^0.7.1",
    "@angular/router": "^6.1.0",
    "@angular/service-worker": "^6.1.0",
    "@auth0/angular-jwt": "^2.0.0",
    "@fortawesome/angular-fontawesome": "^0.1.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.2",
    "@fortawesome/free-regular-svg-icons": "^5.2.0",
    "@fortawesome/free-solid-svg-icons": "^5.2.0",
    "@netbasal/content-loader": "^2.0.0",
    "@ng-bootstrap/ng-bootstrap": "^2.2.1",
    "@ng-bootstrap/schematics": "^2.0.0-alpha.1",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "@swimlane/ngx-charts": "^9.0.0",
    "@swimlane/ngx-datatable": "^13.0.1",
    "angular2-notifications": "^1.0.2",
    "angularx-qrcode": "^1.2.2",
    "animate.css": "^3.7.0",
    "bootstrap": "^4.1.3",
    "bootswatch": "^4.1.3",
    "compass-sass-mixins": "^0.12.7",
    "core-js": "^2.5.7",
    "document-register-element": "^1.11.0",
    "exceljs": "^1.5.1",
    "fuse.js": "^3.2.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "ng2-meta": "^5.0.0",
    "ngx-clipboard": "^11.1.1",
    "ngx-css-variables": "^1.0.1",
    "ngx-file-drop": "^4.0.6",
    "ngx-img-fallback": "^1.3.3",
    "ngx-spinner": "^6.0.0",
    "normalize-diacritics": "^0.4.4",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "webrtc-adapter": "^6.3.0",
    "xlsx": "^0.13.3",
}
```

**Comment by splincode** [comment]
Please add stackblitz example for reproduce

**Comment by gkalpak** [comment]
Sounds like you have a malformed `ngsw-config.json`. See [here][1] for more info on how to config `@angular/service-worker`.

[1]: https://angular.io/guide/service-worker-config

**Comment by bleuscyther** [comment]
it started after i updated to version 6.1 and only happens in with --aot

**Comment by bleuscyther** [comment]
@gkalpak  i see the error thx for the link.
 assetGroups.urls was {} instead of []. don' t know why it was working before.
