### ISSUE TITLE
Angular 6.1.0 index.html app-root and scripts order issue

### ISSUE THREAD

**Issue by debangob** [angular/angular#25207]
## I'm submitting a...
<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
After upgrading to Angular 6.1.0 from Angular 6.0.0 experiencing the following issue: 
We have a hybrid MVC + Angular model where we load the angular app in MVC(.Net) application by loading dist/index.html from server.
Because of this we only keep just the app-root element in the src > index.html and nothing else ( no html, body and head tags). Since the html loaded using MVC already has those tags.
In Angular 6.0.0 after building the app the dist>index.html had the src includes after the app-root element. as a result when the scripts ran it found the app-root element.
In angular 6.1.0 without declaring any html , head and body tag in the src > index.html the script includes (runtime.js, polyfills.js ,styles.js, vendor.js etc) in the dist>index.html are added before the app-root element.

contents of dist/index.html

<script type="text/javascript" src="./runtime.js"></script> 
<script type="text/javascript" src="./polyfills.js"></script> 
<script type="text/javascript" src="./styles.js">
</script> <script type="text/javascript" src="./vendor.js">
</script> <script type="text/javascript" src="./main.js"></script>

As a result when we load the index.html from server we are getting below error. 
main.408bb2530613e5599269.js:1 ERROR Error: The selector "app-root" did not match any elements at t.selectRootElement (main.408bb2530613e5599269.js:1) at t.selectRootElement (main.408bb2530613e5599269.js:1) at Or (main.408bb2530613e5599269.js:1) at Xa (main.408bb2530613e5599269.js:1) at Ua (main.408bb2530613e5599269.js:1) at Object.hs [as createRootView] (main.408bb2530613e5599269.js:1) at e.create (main.408bb2530613e5599269.js:1) at e.create (main.408bb2530613e5599269.js:1) at t.bootstrap (main.408bb2530613e5599269.js:1) at main.408bb2530613e5599269.js:1

## Expected behavior
Should work as it used in Angular 6.0.0

contents of dist/index.html

<script type="text/javascript" src="./runtime.js"></script> 
<script type="text/javascript" src="./polyfills.js"></script> 
<script type="text/javascript" src="./styles.js">
</script> <script type="text/javascript" src="./vendor.js">
</script> <script type="text/javascript" src="./main.js"></script>

## Minimal reproduction of the problem with instructions
1. Create new ng app
2. Remove the html, head and body elements from src>index.html
3. only keep <app-root> element
4. Build n run the app
5. App does not load and javascript error is logged in the console as mentioned above

## What is the motivation / use case for changing the behavior?
When trying to load angular in a hybrid app (MVC/.Net plus angular) the index.html under src folder cannot contain any of the `<html>`,`<head>` and `<body>` tag since the MVC pages will already have it.
`<base href>` is set as part of the MVC page. 

## Environment 
NA

<pre><code>
Angular version: 6.1.0

Browser:
- [x] Chrome (desktop)  version 67.0.3396.99
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version Any Version
- [x] Edge version XX
 
For Tooling issues:
- Node version: 8.9.0 
- Platform:  Windows 

Others:
None

**Comment by IgorMinar** [comment]
If you delete all those tags then you are working with an invalid html document that the browser tries to autocorrect which could result in weird behavior. If you want .Net to generate your main index.html then I suggest that you read in the listing of the dist directory and and render the index.html with correct file names.

**Comment by debangob** [comment]
@IgorMinar  What I am trying to do is load the index.html as a partial page. The main MVC app already has the required tags in the main loaded page. The index.html loads after the MVC Main page has already loaded. So cannot have the angular index.html tag containing the html/head/body tags for the second time.  It used to work in 6.0.0 as the app-root always generated first and then the rest of the script files even without declaring app-root in body tag. now without the body tag the app-root is rendered after the scripts. So when the index.html loads as partial view  the scripts do not find the app-root.

Attaching couple of pictures to explain better.
![angular 6 0 works fine html](https://user-images.githubusercontent.com/32641222/43530353-fc5d4f78-9572-11e8-9a6d-82f5be162667.png)
![angular 6 1 dist_index html](https://user-images.githubusercontent.com/32641222/43530354-fc90420c-9572-11e8-8c2c-af80bf19563d.png)
![src_index html](https://user-images.githubusercontent.com/32641222/43530355-fca3a482-9572-11e8-9c44-e55a0a379964.png)
![angular 6 0 dist_index html](https://user-images.githubusercontent.com/32641222/43530357-fcb83302-9572-11e8-9e58-b0ac0a97988e.png)

**Comment by codemonkey00** [comment]
I am having this same issue.  Did you every find a solution to this?

we have a MVC login page and once authenticated an index.cshtml loads the angular app (index.html). I just updated from 5.2 to 6.1 and now i get this in the console: 

zone.js:665 Unhandled Promise rejection: The selector "my-app" did not match any elements ; Zone: <root> ; Task: Promise.then ; Value: Error: The selector "my-app" did not match any elements
    at DefaultDomRenderer2.push../node_modules/@angular/platform-browser/fesm5/platform-browser.js.DefaultDomRenderer2.selectRootElement (platform-browser.js:1068)
    at BaseAnimationRenderer.push../node_modules/@angular/platform-browser/fesm5/animations.js.BaseAnimationRenderer.selectRootElement (animations.js:228)
    at DebugRenderer2.push../node_modules/@angular/core/fesm5/core.js.DebugRenderer2.selectRootElement (core.js:11449)
    at createElement (core.js:8129)
    at createViewNodes (core.js:10360)
    at createRootView (core.js:10313)
    at callWithDebugContext (core.js:11344)
    at Object.debugCreateRootView [as createRootView] (core.js:10831)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (core.js:8659)
    at ComponentFactoryBoundToModule.push../node_modules/@angular/core/fesm5/core.js.ComponentFactoryBoundToModule.create (core.js:3311) Error: The selector "my-app" did not match any elements
    at DefaultDomRenderer2.push../node_modules/@angular/platform-browser/fesm5/platform-browser.js.DefaultDomRenderer2.selectRootElement (http://localhost:81/MSS/vendor.js:129183:19)
    at BaseAnimationRenderer.push../node_modules/@angular/platform-browser/fesm5/animations.js.BaseAnimationRenderer.selectRootElement (http://localhost:81/MSS/vendor.js:127824:106)
    at DebugRenderer2.push../node_modules/@angular/core/fesm5/core.js.DebugRenderer2.selectRootElement (http://localhost:81/MSS/vendor.js:65865:32)
    at createElement (http://localhost:81/MSS/vendor.js:62545:23)
    at createViewNodes (http://localhost:81/MSS/vendor.js:64776:26)
    at createRootView (http://localhost:81/MSS/vendor.js:64729:5)
    at callWithDebugContext (http://localhost:81/MSS/vendor.js:65760:25)
    at Object.debugCreateRootView [as createRootView] (http://localhost:81/MSS/vendor.js:65247:12)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (http://localhost:81/MSS/vendor.js:63075:29)
    at ComponentFactoryBoundToModule.push../node_modules/@angular/core/fesm5/core.js.ComponentFactoryBoundToModule.create (http://localhost:81/MSS/vendor.js:57727:29)
