### ISSUE TITLE
5 min quick start for Dart does not work.

### ISSUE THREAD

**Issue by kzhdev** [angular/angular#2532]
When run the app, it throw an exception.

Cannot find reflection information on TestabilityRegistry

#0      NoReflectionCapabilities.factory (package:angular2/src/reflection/reflection.dart:10:5)
#1      Reflector.factory (package:angular2/src/reflection/reflector.dart:38:42)
#2      Binding.resolve (package:angular2/src/di/binding.dart:214:29)
#3      resolveBindings (package:angular2/src/di/injector.dart:358:55)
#4      Injector.resolve (package:angular2/src/di/injector.dart:95:28)
#5      Injector.resolveAndCreate (package:angular2/src/di/injector.dart:115:34)
#6      _createAppInjector (http://localhost:63343/traffic/packages/angular2/src/core/application.dart:350:16)
#7      bootstrap.<anonymous closure> (http://localhost:63343/traffic/packages/angular2/src/core/application.dart:305:9)
#8      _rootRun (dart:async/zone.dart:895)
#9      _ZoneDelegate.run (dart:async/zone.dart:501)
#10     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:142:21)
#11     _CustomZone.run (dart:async/zone.dart:796)
#12     _CustomZone.runGuarded (dart:async/zone.dart:704)
#13     NgZone.run (package:angular2/src/core/zone/ng_zone.dart:103:23)
#14     bootstrap (http://localhost:63343/traffic/packages/angular2/src/core/application.dart:300:8)
#15     main (http://localhost:63343/traffic/web/main.dart:18:3)

application.dart:156 Exception: Cannot find reflection information on TestabilityRegistryapplication.dart:156 <anonymous closure>package:angular2/src/core/zone/ng_zone.dart:190 NgZone._onErrorWithoutLongStackTrace@693253716package:angular2/src/core/zone/ng_zone.dart:61 NgZone.<anonymous closure>package:angular2/src/core/zone/ng_zone.dart:103 NgZone.runapplication.dart:300 bootstrapmain.dart:18 main

**Comment by kzhdev** [comment]
I might did something. After copy/paste the code. It works now.
