### ISSUE TITLE
Target 'server' could not be found in project 'frontend'

### ISSUE THREAD

**Issue by github-mayur** [angular/angular#25539]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Hello, I am working on Angular 6 and trying to build application Server Side Rendering from several days. I have list of commands as below,

```
"build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
"serve:ssr": "node dist/server",
"build:client-and-server-bundles-old": "ng build --prod --extract-css && ng run frontend:server",
"webpack:server": "webpack --config webpack.server.config.js --progress --colors"
```

I am continuously facing an error as below, when I run `build:ssr`

```
"C:\JetBrains\PhpStorm 2018.2\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run build:ssr --scripts-prepend-node-path=auto

> frontend@0.0.0 build:ssr C:\Users\mchampaneria\phpstormprojects\angular_win\frontend
> npm run build:client-and-server-bundles && npm run webpack:server


> frontend@0.0.0 build:client-and-server-bundles C:\Users\mchampaneria\phpstormprojects\angular_win\frontend
> ng run frontend:server

Target 'server' could not be found in project 'frontend'.
Error: Target 'server' could not be found in project 'frontend'.
    at Architect._getProjectTarget (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\@angular-devkit\architect\src\architect.js:90:19)
    at Architect.getBuilderConfiguration (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\@angular-devkit\architect\src\architect.js:97:29)
    at MergeMapSubscriber._loadWorkspaceAndArchitect.pipe.operators_1.concatMap [as project] (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\@angular\cli\models\architect-command.js:72:55)
    at MergeMapSubscriber._tryNext (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\Subscriber.js:64:18)
    at TapSubscriber._next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\operators\tap.js:62:26)
    at TapSubscriber.Subscriber.next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MergeMapSubscriber.notifyNext (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\operators\mergeMap.js:84:26)
    at InnerSubscriber._next (C:\Users\mchampaneria\phpstormprojects\angular_win\frontend\node_modules\rxjs\internal\InnerSubscriber.js:25:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 build:client-and-server-bundles: `ng run frontend:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.0.0 build:client-and-server-bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mchampaneria\AppData\Roaming\npm-cache\_logs\2018-08-17T09_15_10_808Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run webpack:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mchampaneria\AppData\Roaming\npm-cache\_logs\2018-08-17T09_15_10_839Z-debug.log

Process finished with exit code 1

```

## Expected behavior

Since, my project name is 'frontend' and I am executing commands like below, after following full document describe on [Angular Universal](https://angular.io/guide/universal) url

## What is the motivation / use case for changing the behavior?

Change the behaviors while releasing Angular 6

## Environment

<pre><code>
Angular version: 6.1.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1  
- Platform: Windows 

Others:

</code></pre>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Unfortunately this reads like a support request and doesn't provide info to reproduce the issue. However, if you can reproduce the problem, please submit a new issue and include the reproduction that shows this working in an earlier version, and now not working.
