### ISSUE TITLE
Can't build the project due to FormatException

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#2585]
After pulling the latest changes and running `npm i` I get this:

```
$ npm install

> angular@2.0.0-alpha.27 preinstall /Users/pp/projects/angular/angular
> node tools/npm/check-node-modules --purge

:-) npm dependencies are looking good!

> angular@2.0.0-alpha.27 postinstall /Users/pp/projects/angular/angular
> node tools/npm/copy-npm-shrinkwrap && node tools/chromedriverpatch.js && webdriver-manager update && bower install && gulp pubget.dart && tsd reinstall --config modules/angular2/tsd.json && tsd reinstall --config tools/tsd.json

selenium standalone is up to date.
chromedriver is up to date.
Dart SDK detected
[12:29:16] Using gulpfile ~/projects/angular/angular/gulpfile.js
[12:29:16] Starting 'pubget.dart'...
Unhandled exception:
FormatException: The Dart SDK's 'version' file was not in a format pub could recognize. Found: 1.10.1
#0      _getVersion (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/sdk/lib/_internal/pub/lib/src/sdk.dart:53)
#1      version (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/sdk/lib/_internal/pub/lib/src/sdk.dart:36)
#2      main (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/sdk/lib/_internal/pub/bin/pub.dart:74)
#3      _startIsolate.isolateStartHandler (dart:isolate-patch/isolate_patch.dart:188)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:93)
[12:29:17] 'pubget.dart' errored after 302 ms
[12:29:17] Error: 255
    at formatError (/Users/pp/projects/angular/angular/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/pp/projects/angular/angular/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
    at _rejected (/Users/pp/projects/angular/angular/node_modules/q/q.js:830:24)
    at /Users/pp/projects/angular/angular/node_modules/q/q.js:856:30
    at Promise.when (/Users/pp/projects/angular/angular/node_modules/q/q.js:1108:31)
```

I updated the dart-sdk to the latest version by downloading it from the website and configuring it accordingly. The version file just contains the version number `1.10.1`, but still, apparently this is in a wrong format.

Any idea why `pub` has a problem with that?

**Comment by vicb** [comment]
Are you 100% confident that gulp uses the last version of the SDk you've installed ?

**Comment by PascalPrecht** [comment]
Yes, here's my configuration:

```
...
DART_EDITOR_DIR=~/Applications/dart

export DART_SDK="$DART_EDITOR_DIR/dart-sdk"

PATH+=":$DART_SDK/bin"
```

And this is also where I put the package. The version file has `1.10.1` which is also what the build error says. I even manually changed the version number in that file to and then, that one was used.

So yea, I think I'm 100% sure.

**Comment by vicb** [comment]
What's the output of `pub --version`

**Comment by PascalPrecht** [comment]
This is not a joke, I can't even run `pub --version`. Getting the same error.
```
$ pub --version
Unhandled exception:
FormatException: The Dart SDK's 'version' file was not in a format pub could recognize. Found: 1.10.1
#0      _getVersion (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/sdk/lib/_internal/pub/lib/src/sdk.dart:53)
#1      version (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/sdk/lib/_internal/pub/lib/src/sdk.dart:36)
#2      main (file:///Volumes/data/b/build/slave/dart-editor-mac-stable/build/dart/sdk/lib/_internal/pub/bin/pub.dart:34)
#3      _startIsolate.isolateStartHandler (dart:isolate-patch/isolate_patch.dart:188)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:93)
```

**Comment by vicb** [comment]
`file:///Volumes/data/b/build/slave/dart-editor-mac-stable/` is that a link to `$DART_EDITOR_DIR/dart-sdk` ?

**Comment by PascalPrecht** [comment]
@vicb Okay, so I re-installed the dart-sdk once again and after a while I found out that there was a `pub` somewhere in `/usr/local/bin` which I didn't know about. It's working now, thank you so much for your help! <3

**Comment by vicb** [comment]
no problem
