### ISSUE TITLE
Angular 2 --> 6  Upgrade and Deployment issue 

### ISSUE THREAD

**Issue by gomteshhatgine** [angular/angular#25998]
I have just upgraded my Angular 2 app to Angular 6.
Is there any way we can make use of less rather than css by default or do we need to use a third party package for the same
The app builds and deploys properly when the ng serve command is used. The issue occurs when I build the app in prod mode
the issues and the details are mentioned as below : 

Angular CLI: 6.2.1
Node: 8.11.4
OS: linux x64
Angular: 6.1.7

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.1
@angular-devkit/build-angular     0.8.1
@angular-devkit/build-optimizer   0.8.1
@angular-devkit/build-webpack     0.8.1
@angular-devkit/core              0.8.1
@angular-devkit/schematics        0.8.1
@angular/cdk                      6.4.7
@angular/cli                      6.2.1
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@ngtools/webpack                  6.2.1
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.0.0
typescript                        2.9.2
webpack                           4.19.0

**!! ERROR !!**
The /home/gomtesh/demo/app1/src/undefined path in file replacements does not exist.
Error: The /home/gomtesh/demo/app1/src/undefined path in file replacements does not exist.
    at TapSubscriber.operators_1.tap [as _tapNext] (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/src/utils/normalize-file-replacements.js:26:19)
    at TapSubscriber._next (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/tap.js:56:27)
    at TapSubscriber.Subscriber.next (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/home/gomtesh/demo/app1/node_modules/@angular-devkit/core/node/host.js:241:21)
    at Observable._trySubscribe (/home/gomtesh/demo/app1/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/home/gomtesh/demo/app1/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:29:22)
    at DoOperator.call (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/tap.js:29:23)
    at Observable.subscribe (/home/gomtesh/demo/app1/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:24:22)
    at /home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToObservable.js:10:20
    at Object.subscribeToResult (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
    at MergeMapSubscriber._next (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:64:18)
    at Observable._subscribe (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/home/gomtesh/demo/app1/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Observable.js:43:25)

**Comment by gomteshhatgine** [comment]
Adding the package.json file for the above issue
{
  "name": "app1",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "postinstall": "typings install"
  },
  "dependencies": {
    "@angular/animations": "^6.1.7",
    "@angular/cdk": "^6.4.7",
    "@angular/cli": "^6.2.1",
    "angular2-datatable-pagination": "0.0.3",
    "core-js": "2.4.1",
    "intro.js": "^2.9.3",
    "ngx-bootstrap": "^3.0.1",
    "ngx-clipboard": "7.0.6",
    "rxjs-compat": "6.0.0",
    "save": "^2.3.2",
    "tippy.js": "^2.6.0",
    "update": "^0.7.4",
    "webpack": "^4.19.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/common": "^6.1.7",
    "@angular/compiler": "^6.1.7",
    "@angular/compiler-cli": "^6.1.7",
    "@angular/core": "^6.1.7",
    "@angular/flex-layout": "^6.0.0-beta.15",
    "@angular/forms": "^6.1.7",
    "@angular/http": "^6.1.7",
    "@angular/material": "^6.1.7",
    "@angular/platform-browser": "^6.1.7",
    "@angular/platform-browser-dynamic": "6.1.7",
    "@angular/router": "6.1.7",
    "@angular/upgrade": "6.1.7",
    "@ng-bootstrap/ng-bootstrap": "^3.2.0",
    "@types/core-js": "^0.9.34",
    "@types/jasmine": "2.5.41",
    "@types/node": "^7.0.7",
    "@types/selenium-webdriver": "2.44.26",
    "angular-in-memory-web-api": "^0.1.17",
    "angular2-cookie": "^1.2.6",
    "angular2-datatable": "^0.6.0",
    "angular2-router-loader": "0.3.4",
    "angular2-template-loader": "0.6.0",
    "codelyzer": "~2.0.0-beta.1",
    "concurrently": "3.2.0",
    "css-loader": "0.26.1",
    "cssify": "1.0.3",
    "file-loader": "0.8.5",
    "grunt": "^1.0.3",
    "grunt-browserify": "^5.3.0",
    "grunt-bump": "0.8.0",
    "grunt-contrib-clean": "1.0.0",
    "grunt-contrib-concat": "1.0.1",
    "grunt-contrib-copy": "1.0.0",
    "grunt-contrib-jshint": "1.1.0",
    "grunt-contrib-less": "^2.0.0",
    "grunt-contrib-uglify": "2.1.0",
    "grunt-contrib-watch": "^1.1.0",
    "grunt-express": "1.4.1",
    "grunt-html2js": "^0.5.1",
    "grunt-karma": "^3.0.0",
    "grunt-ng-annotate": "3.0.0",
    "grunt-parallel": "0.5.1",
    "grunt-systemjs-builder": "0.2.7",
    "grunt-ts": "6.0.0-beta.11",
    "grunt-update": "^0.2.3",
    "grunt-war": "0.5.1",
    "hammerjs": "2.0.8",
    "html-loader": "0.4.4",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-htmlfile-reporter": "^0.3.6",
    "karma-jasmine": "1.0.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-phantomjs-launcher": "1.0.2",
    "karma-remap-istanbul": "^0.6.0",
    "karma-sourcemap-loader": "0.3.7",
    "lessify": "1.0.1",
    "null-loader": "0.1.1",
    "phantomjs-prebuilt": "^2.1.16",
    "raw-loader": "0.5.1",
    "rimraf": "2.5.2",
    "rxjs": "6.0.0",
    "scssify": "2.2.1",
    "style-loader": "0.13.1",
    "ts-helpers": "1.1.2",
    "ts-loader": "2.0.0",
    "ts-node": "1.2.1",
    "tslint": "4.3.0",
    "typescript": "^2.9.2",
    "typescriptifier": "1.0.0",
    "typings": "2.1.0",
    "url-loader": "^1.1.1",
    "zone.js": "^0.8.26"
  }
}

**Comment by benlesh** [comment]
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a StackBlitz reproducing the problem and describing the difference between the expected and current behavior. You can use this StackBlitz template: https://stackblitz.com/fork/angular-gitter

**Comment by nicompte** [comment]
Hello, I had the same issue after updating an old project, running `ng update @angular/cli --migrate-only --from=1.7.4` (I think, I did some other things so I can't be 100% sure), I'll add my fix in case someone stumbles upon this issue like I did.

The issue is in `angular.json`:
```
 "fileReplacements": [
                {
                  "replace": "src/undefined",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
```
I just had to use `src/environments/environment.ts` and it worked well.
