### ISSUE TITLE
Bundle generated through bundleDependencies=all is incompatible with uglifyjs after 7.0.0-beta.2

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#26023]
## I'm submitting a...
<pre><code>
[x ] Bug report  
</code></pre>

## Current behavior

Generating a bundle with option bundleDependencies set to all and then minifying it using uglifyjs is broken after 7.0.0-beta.2 and throw below error:

Parse error at main.js:157164,23
module.exports = class NodeList extends Array {
                       ^
ERROR: Unexpected token: name (NodeList)
    at JS_Parse_Error.get (eval at <anonymous> (C:\Users\UserName\AppData\Roaming\npm\node_modules\uglify-js\tools\node.js:20:1), <anonymous>:71:23)
    at fatal (C:\Users\UserName\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:291:53)
    at run (C:\Users\UserName\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:235:9)
    at Object.<anonymous> (C:\Users\UserName\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:160:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

## Expected behavior
The generated bundle should be compatible with uglifyjs.

## Minimal reproduction of the problem with instructions

Generate a bundle with below options:

```
              "optimization": false,
              "bundleDependencies": "all",

```

Then use uglifyjs to minify the bundle.

`uglifyjs main.js --output main1.js`

And it will throw above error

## What is the motivation / use case for changing the behavior?

For .Net developers using Angular Universal/SSR, its necessary to have all dependencies bundled in one file before we could successful deploy it on server Windows Server.

generating a server bundle with optimization set to true and bundleDependencies set to all doesn't work
as a work around we generate bundle with optimizations set to false and then use uglifyjs to tree-shake and minify bundle.

## Environment

<pre><code>
Angular version: 7.0.0-beta.5

Browser:
- [x] All
 
For Tooling issues:
- Node version: v8.11.4
- Platform: Windows
</code></pre>

**Comment by naveedahmed1** [comment]
@trotyl any specific reason to down vote this issue? I think its very important issue for .Net developers using Angular Universal on Windows Servers/IIS.

**Comment by trotyl** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by naveedahmed1** [comment]
@trotyl this is **not a support request** its something broken after 7 beta, probably something related to the compiler in version 7.

**Comment by naveedahmed1** [comment]
If I compiled the project with

`"target": "es6",

And use https://www.npmjs.com/package/uglify-es its works

But with default config i.e.

`"target": "es5",

and https://www.npmjs.com/package/uglify-js it doesnt work.
