### ISSUE TITLE
ng build --prod doesn't work with npm i --prod

### ISSUE THREAD

**Issue by garyluu** [angular/angular#26546]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
`ng build --prod` doesn't work with prod-only dependencies

## Expected behavior
`ng build --prod` should work with prod-only dependencies

## Minimal reproduction of the problem with instructions

```
docker run -i -t node /bin/bash
npm i -g @angular/cli
ng new potato
cd potato
rm -rf node_modules/
npm i --prod
ng build --prod
```
fails with:
```
Could not find module "@angular-devkit/build-angular" from "/potato".
Error: Could not find module "@angular-devkit/build-angular" from "/potato".
    at Object.resolve (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable._trySubscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:29:22)
    at DoOperator.call (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:29:23)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:24:22)
    at /usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:72:14)

```
## What is the motivation / use case for changing the behavior?

Don't want to install all devDependencies when just building for prod

## Environment

<pre><code>
Angular version: 6.1.10

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v10.12.0  
- Platform:  Linux 

Others:

</code></pre>

**Comment by sarunint** [comment]
It's intended. Building the production version of the app is considered in the "development" phase.

Also, wrong repo.
