### ISSUE TITLE
angular compiler cannot find module 'tsickle'

### ISSUE THREAD

**Issue by 100cm** [angular/angular#26580]
when i run

$(npm bin)/ngc -p tsconfig-build.json -t es2015 --outDir publish-es2015/src

```
✗ $(npm bin)/ngc -p tsconfig-build.json -t es2015 --outDir publish-es2015/src
: Error: Cannot find module 'tsickle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/icepoint1999/code/at-ui-angular/node_modules/@angular/compiler-cli/src/main.js:72:24
    at AngularCompilerProgram._emitRender2 (/Users/icepoint1999/code/at-ui-angular/node_modules/@angular/compiler-cli/src/transformers/program.js:388:34)
    at AngularCompilerProgram.emit (/Users/icepoint1999/code/at-ui-angular/node_modules/@angular/compiler-cli/src/transformers/program.js:212:22)
    at Object.performCompilation (/Users/icepoint1999/code/at-ui-angular/node_modules/@angular/compiler-cli/src/perform_compile.js:216:29)
    at main (/Users/icepoint1999/code/at-ui-angular/node_modules/@angular/compiler-cli/src/main.js:31:46)
    at /Users/icepoint1999/code/at-ui-angular/node_modules/@angular/compiler-cli/src/main.js:168:28
```

angualr verision:

```
Angular CLI: 7.0.1
Node: 10.11.0
OS: darwin x64
Angular: 7.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.1
@angular-devkit/build-angular     0.10.1
@angular-devkit/build-optimizer   0.10.1
@angular-devkit/build-webpack     0.10.1
@angular-devkit/core              7.0.1
@angular-devkit/schematics        7.0.1
@angular/cli                      7.0.1
@ngtools/webpack                  7.0.1
@schematics/angular               7.0.1
@schematics/update                0.10.1
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

**Comment by 100cm** [comment]
online waiting...

**Comment by kemsky** [comment]
just install it manually

**Comment by 100cm** [comment]
@kemsky  why it doesn't been included in dependencies
