### ISSUE TITLE
Auto-watch doesn't work in `gulp test.unit.dart`

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#2662]
After fresh install from master / npm:
* run `gulp test.unit.dart`
* touch any file that triggers tests re-run. 

There is an error on the console and subsequent run is not triggered:

> [14:28:09] Starting '!build/tree.dart'...
[14:28:11] '!build/tree.dart' errored after 1.92 s
[14:28:11] TypeError: [MergeTrees]: Cannot read property 'forEach' of undefined
    at /Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/angular/broccoli-merge-trees.ts:76:30
    at Array.forEach (native)
    at MergeTrees.rebuild (/Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/angular/broccoli-merge-trees.ts:74:27)
    at DiffingPluginWrapper.rebuild (/Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/angular/diffing-broccoli-plugin.ts:106:39)
    at /Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/angular/node_modules/broccoli/lib/api_compat.js:42:21
    at lib$rsvp$$internal$$tryCatch (/Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/angular/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/angular/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/angular/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/Users/pawelkozlowski/work/gitrepos/pkozlowski-opensource/angular/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)

This makes working on Dart-related code quite challenging, atm...

**Comment by pkozlowski-opensource** [comment]
@caitp it might be related to d575915d7a504c155fbdfad5614a210268e5bea4 - are there any special cleanup steps that I should take after pulling this sha1?

**Comment by vicb** [comment]
same error here (Ubuntu)

**Comment by tbosch** [comment]
Just tried: reverting https://github.com/angular/angular/commit/d575915d7a504c155fbdfad5614a210268e5bea4 makes the incremental build work again...

**Comment by naomiblack** [comment]
@tbosch @IgorMinar @mhevery  can we find someone to own this in alpha-29? It would be great to resolve quickly if possible. Any suggestions since @caitp is out?

**Comment by caitp** [comment]
I can take some time to fix this today. For the time being, reverting d575915 should get it working again

**Comment by tbosch** [comment]
@pkozlowski-opensource @caitp I reverted the commit for now on master.
