### ISSUE TITLE
export 'constructor' (imported as 'o') was not found in '../../output/output_ast'

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#26743]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When consuming the ESM5 Angular bundles through Webpacks `mainFields` configuration, the following warning is displayed:
```
WARNING in ./node_modules/@angular/compiler/esm5/src/render3/view/util.js 52:93-106
"export 'constructor' (imported as 'o') was not found in '../../output/output_ast'
```

## Expected behavior
No missing export warning displayed.

## Minimal reproduction of the problem with instructions
This export can be seen in the source code for compiler:
https://github.com/angular/angular/blob/297dc2bc02ac7a576baefd0046863bfd2129a78f/packages/compiler/src/render3/view/util.ts#L58-L61

Where `o` is `import * as o from '../../output/output_ast';`.

It can also be seen in the generated esm5 bundle:
https://github.com/angular/compiler-builds/blob/49a4ec193bdcad7729fb794a1de8798a3ae00020/esm5/src/render3/view/util.js#L44-L46

But oddly enough it is not present in the [fesm5 bundle](https://github.com/angular/compiler-builds/blob/49a4ec193bdcad7729fb794a1de8798a3ae00020/esm5/src/render3/view/util.js#L44-L46):
```
function invalid(arg) {
    throw new Error("Invalid state: Visitor " + this.constructor.name + " doesn't handle " + arg.constructor.name);
}
```
In the fesm5, `o.output.name` is replaced with `arg.output.name`, which looks like the right variable.

@petebacondarwin had a look and figured out that `o.constructor` is not an error even though `output_ast` has no such export, because `o` is an object, and all object have constructors.

But it is puzzling why different generated bundles suddenly are using different variables.

## Environment

<pre><code>
Angular version: 7.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.10.0
- Platform:  Windows

Others:

</code></pre>

cc @alexeagle

**Comment by trotyl** [comment]
> because `o` is an object, and all object have constructors

Not true, `Object.create(null)` doesn't have a `constructor`, let alone exotic objects.

**Comment by filipesilva** [comment]
You're right, that part was added by me and was incorrect. I'll add a strikethrough 👍

**Comment by trotyl** [comment]
The point is **Module Namespace Exotic object** indeed has no constructor, although the right error should be `TypeError: Cannot read property 'name' of undefined`. 😃

**Comment by filipesilva** [comment]
Do you think that the missing error is a typescript bug in their typings of module namespace objects?

**Comment by petebacondarwin** [comment]
I think this probably is an error in the TS compiler.

**Comment by trotyl** [comment]
Likely relates to https://github.com/Microsoft/TypeScript/issues/1108.

**Comment by filipesilva** [comment]
Yeah that makes sense. Then the only question that remains regarding this repo is why `o.constructor` is transformed to `arg.constructor` in different bundles.

**Comment by filipesilva** [comment]
As far as I can tell, the transformation from `o.constructor` to `arg.constructor` in FESM bundles happens in our pipeline, at the rollup step.

By running `yarn bazel build //packages/compiler:npm_package --subcommands` we can see all subcommands that Bazel is running. 

The rollup for FESM uses this command:
```
SUBCOMMAND: # //packages/compiler:npm_package [action 'ng_package: Rollup fesm5 //packages/compiler:npm_package']
cd C:/users/kamik/_bazel_kamik/b3mwdre7/execroot/angular
bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/rollup/rollup.exe --config bazel-out/x64_windows-fastbuild/bin/packages/compiler/_npm_package.rollup_esm5.conf.js --input packages/compiler/index.js --output.file bazel-out/x64_windows-fastbuild/bin/packages/compiler/fesm5/compiler.js --output.format es --sourcemap --external @angular/upgrade,@angular/upgrade/static,@angular/forms,@angular/core/testing,@angular/core,@angular/platform-server/testing,@angular/platform-server,@angular/platform-webworker-dynamic,@angular/platform-webworker,@angular/common/testing,@angular/common,@angular/common/http/testing,@angular/common/http,@angular/elements,@angular/http/testing,@angular/http,@angular/platform-browser-dynamic/testing,@angular/platform-browser-dynamic,@angular/compiler/testing,@angular/compiler,@angular/animations,@angular/animations/browser/testing,@angular/animations/browser,@angular/service-worker/config,@angular/service-worker,@angular/platform-browser/testing,@angular/platform-browser,@angular/platform-browser/animations,@angular/router/upgrade,@angular/router/testing,@angular/router,rxjs,rxjs/operators,tslib --globals @angular/upgrade:ng.upgrade,@angular/upgrade/static:ng.upgrade.static,@angular/forms:ng.forms,@angular/core/testing:ng.core.testing,@angular/core:ng.core,@angular/platform-server/testing:ng.platformServer.testing,@angular/platform-server:ng.platformServer,@angular/platform-webworker-dynamic:ng.platformWebworkerDynamic,@angular/platform-webworker:ng.platformWebworker,@angular/common/testing:ng.common.testing,@angular/common:ng.common,@angular/common/http/testing:ng.common.http.testing,@angular/common/http:ng.common.http,@angular/elements:ng.elements,@angular/http/testing:ng.http.testing,@angular/http:ng.http,@angular/platform-browser-dynamic/testing:ng.platformBrowserDynamic.testing,@angular/platform-browser-dynamic:ng.platformBrowserDynamic,@angular/compiler/testing:ng.compiler.testing,@angular/compiler:ng.compiler,@angular/animations:ng.animations,@angular/animations/browser/testing:ng.animations.browser.testing,@angular/animations/browser:ng.animations.browser,@angular/service-worker/config:ng.serviceWorker.config,@angular/service-worker:ng.serviceWorker,@angular/platform-browser/testing:ng.platformBrowser.testing,@angular/platform-browser:ng.platformBrowser,@angular/platform-browser/animations:ng.platformBrowser.animations,@angular/router/upgrade:ng.router.upgrade,@angular/router/testing:ng.router.testing,@angular/router:ng.router,rxjs:rxjs,rxjs/operators:rxjs.operators --silent
```

I think this is the point it happens at because the rollup sources (`bazel-out/x64_windows-fastbuild/bin/packages/compiler/npm_package.esm5/packages/compiler/index.js`) at this point still show the function as below:
```
    function invalid(arg) {
        throw new Error("Invalid state: Visitor " + this.constructor.name + " doesn't handle " + o.constructor.name);
    }
```
Then in the output (`--output.file bazel-out/x64_windows-fastbuild/bin/packages/compiler/fesm5/compiler.js`) we instead see:
```
function invalid(arg) {
    throw new Error("Invalid state: Visitor " + this.constructor.name + " doesn't handle " + arg.constructor.name);
}
```

Something else that is interesting is how the rollup command has the `--silent` flag. 

If you delete the `bazel-out/x64_windows-fastbuild/bin/packages/compiler/fesm5` folder and run the command as is, you will see this folder is recreated with the appropriate bundles.

But if you remove the `--silent` flag, the `fesm5` folder isn't recreated and instead there's an error:
```
[!] Error: Unknown input option: resolveBazel. Allowed options: acorn, acornInjectPlugins, cache, chunkGroupingSize, context, experimentalCacheExpiry, experimentalOptimizeChunks, experimentalTopLevelAwait, external, inlineDynamicImports, input, manualChunks, moduleContext, onwarn, perf, plugins, preserveModules, preserveSymlinks, shimMissingExports, treeshake, watch
Error: Unknown input option: resolveBazel. Allowed options: acorn, acornInjectPlugins, cache, chunkGroupingSize, context, experimentalCacheExpiry, experimentalOptimizeChunks, experimentalTopLevelAwait, external, inlineDynamicImports, input, manualChunks, moduleContext, onwarn, perf, plugins, preserveModules, preserveSymlinks, shimMissingExports, treeshake, watch
    at Object.onwarn (C:\users\kamik\_bazel_kamik\b3mwdre7\execroot\angular\bazel-out\x64_windows-fastbuild\bin\packages\compiler\_npm_package.rollup_esm5.conf.js:164:11)
    at Object.onwarn (C:\users\kamik\_bazel_kamik\b3mwdre7\external\build_bazel_rules_nodejs_rollup_deps\node_modules\rollup\bin\rollup:319:50)
    at C:\users\kamik\_bazel_kamik\b3mwdre7\external\build_bazel_rules_nodejs_rollup_deps\node_modules\rollup\bin\rollup:1821:34
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

Unrecognized options in Rollup are actually warnings, but in https://github.com/bazelbuild/rules_nodejs/blob/efdc184540c0b2bd855dff26eb80842c0ce3f35e/internal/rollup/rollup.config.js#L158-L163 we make them into thrown errors instead:
```
  onwarn: (warning) => {
    // Always fail on warnings, assuming we don't know which are harmless.
    // We can add exclusions here based on warning.code, if we discover some
    // types of warning should always be ignored under bazel.
    throw new Error(warning.message);
  },
```

It looks like the rollup `--silent` flag somehow also ignores thrown errors. But that's not actually the case. The flag description reads `Don't print warnings`, so I think the `onwarn` hook is never actually called. Regardless, I opened an issue there: https://github.com/rollup/rollup/issues/2686

Knowing that our `onwarn` hook isn't working correctly, we can remove it and see the correct warnings when rollup is ran without the `--silent` flag:
```
(!) You have passed an unrecognized option
Unknown input option: resolveBazel. Allowed options: acorn, acornInjectPlugins, cache, chunkGroupingSize, context, experimentalCacheExpiry, experimentalOptimizeChunks, experimentalTopLevelAwait, external, inlineDynamicImports, input, manualChunks, moduleContext, onwarn, perf, plugins, preserveModules, preserveSymlinks, shimMissingExports, treeshake, watch

packages/compiler/index.js → bazel-out/x64_windows-fastbuild/bin/packages/compiler/fesm5/compiler.js...
(!) Missing exports
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
bazel-out\x64_windows-fastbuild\bin\packages\compiler\npm_package.esm5\packages\compiler\src\render3\view\util.js
constructor is not exported by bazel-out\x64_windows-fastbuild\bin\packages\compiler\npm_package.esm5\packages\compiler\src\output\output_ast.js
44: }
45: export function invalid(arg) {
46:     throw new Error("Invalid state: Visitor " + this.constructor.name + " doesn't handle " + o.constructor.name);
                                                                                                   ^
47: }
48: export function asLiteral(value) {
```

So a warning is actually shown for the missing export, we just never saw it. The fact these are warnings and not errors in rollup is discussed in https://github.com/rollup/rollup/issues/2582.

This doesn't really explain why `o.constructor.name` is altered to `arg.constructor.name`, but explains why we weren't seeing this error.

I tried reproducing in a simple example with rollup and indeed I can get it to alter the variable, but it's altered to `undefined` instead:
```
function invalid(arg) {
    throw new Error("Invalid state: Visitor " + this.constructor.name + " doesn't handle " + undefined);
}
```

I couldn't get the simple repro but submitted both simple and real reproductions to rollup in https://github.com/rollup/rollup/issues/2687.

**Comment by filipesilva** [comment]
This has also been identified in https://github.com/bazelbuild/rules_nodejs/pull/459
