### ISSUE TITLE
Issues with alpha 27

### ISSUE THREAD

**Issue by ctindel** [angular/angular#2723]
I am seeing the following logs show up in my console output.  These are with Google Chrome Version 43.0.2357.124 (64-bit)

Anything I can do?

```
TypeError: Cannot read property 'then' of undefined
    at RootRouter.commit (router.js:187)
    at router.js:110
    at Zone.run (core.js:91)
    at Zone.NgZone._createInnerZone.zone.fork.fork.$run [as run] (ng_zone.js:126)
    at zoneBoundFn (core.js:64)BrowserDomAdapter.logError @ browser_adapter.js:59defaultErrorReporter @ application.js:111NgZone._onError @ ng_zone.js:175NgZone._createInnerZone.errorHandling.onError @ ng_zone.js:112run @ core.js:94NgZone._createInnerZone.zone.fork.fork.$run @ ng_zone.js:126zoneBoundFn @ core.js:64
browser_adapter.js:59TypeError: Cannot read property 'replace' of undefined
STACKTRACE:
TypeError: Cannot read property 'replace' of undefined
    at module.exports (base64_url_decode.js:4)
    at module.exports (index.js:5)
    at new Home (home.ts:29)
    at ReflectionCapabilities.factory (reflection_capabilities.js:12)
    at ElementInjector._new (element_injector.js:759)
    at ElementInjectorInlineStrategy.getObjByKeyId (element_injector.js:1186)
    at ElementInjectorInlineStrategy.hydrate (element_injector.js:1124)
    at ElementInjector.hydrate (element_injector.js:669)
    at AppViewManagerUtils._hydrateView (view_manager_utils.js:185)
    at AppViewManagerUtils.hydrateViewInContainer (view_manager_utils.js:156)BrowserDomAdapter.logError @ browser_adapter.js:59ExceptionHandler.call @ exception_handler.js:54LifeCycle._errorHandler @ life_cycle.js:49NgZone._onError @ ng_zone.js:175NgZone._createInnerZone.errorHandling.onError @ ng_zone.js:112run @ core.js:94NgZone._createInnerZone.zone.fork.fork.$run @ ng_zone.js:126zoneBoundFn @ core.js:64
browser_adapter.js:59Attempt to detect changes on a dehydrated detector.
STACKTRACE:
Error: Attempt to detect changes on a dehydrated detector.
    at DehydratedException.BaseException (http://localhost:3000/build/angular2.js:42:24)
    at new DehydratedException (http://localhost:3000/build/angular2.js:16516:17)
    at Function.ChangeDetectionUtil.throwDehydrated (http://localhost:3000/build/angular2.js:15194:64)
    at DynamicChangeDetector.detectChangesInRecords (http://localhost:3000/build/angular2.js:22462:58)
    at DynamicChangeDetector.AbstractChangeDetector._detectChanges (http://localhost:3000/build/angular2.js:22208:15)
    at DynamicChangeDetector.AbstractChangeDetector._detectChangesInLightDomChildren (http://localhost:3000/build/angular2.js:22221:19)
    at DynamicChangeDetector.AbstractChangeDetector._detectChanges (http://localhost:3000/build/angular2.js:22209:15)
    at DynamicChangeDetector.AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:3000/build/angular2.js:22227:19)
    at DynamicChangeDetector.AbstractChangeDetector._detectChanges (http://localhost:3000/build/angular2.js:22212:15)
    at DynamicChangeDetector.AbstractChangeDetector.detectChanges (http://localhost:3000/build/angular2.js:22203:74)BrowserDomAdapter.logError @ browser_adapter.js:59ExceptionHandler.call @ exception_handler.js:54LifeCycle._errorHandler @ life_cycle.js:49NgZone._onError @ ng_zone.js:175NgZone._createInnerZone.errorHandling.onError @ ng_zone.js:112run @ core.js:94NgZone._createInnerZone.zone.fork.fork.$run @ ng_zone.js:140zoneBoundFn @ core.js:64
home:1 Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
    at RootRouter.commit (http://localhost:3000/build/angular2.js:16216:14)
    at http://localhost:3000/build/angular2.js:16139:33
    at Zone.run (http://localhost:3000/build/angular2.js:46334:18)
    at Zone.NgZone._createInnerZone.zone.fork.fork.$run [as run] (http://localhost:3000/build/angular2.js:25328:43)
    at zoneBoundFn (http://localhost:3000/build/angular2.js:46307:20)
home:1 Uncaught (in promise) DehydratedException {message: "Attempt to detect changes on a dehydrated detector.", stack: "Error: Attempt to detect changes on a dehydrated d…http://localhost:3000/build/angular2.js:22203:74)"}message: "Attempt to detect changes on a dehydrated detector."stack: "Error: Attempt to detect changes on a dehydrated detector.↵    at DehydratedException.BaseException (http://localhost:3000/build/angular2.js:42:24)↵    at new DehydratedException (http://localhost:3000/build/angular2.js:16516:17)↵    at Function.ChangeDetectionUtil.throwDehydrated (http://localhost:3000/build/angular2.js:15194:64)↵    at DynamicChangeDetector.detectChangesInRecords (http://localhost:3000/build/angular2.js:22462:58)↵    at DynamicChangeDetector.AbstractChangeDetector._detectChanges (http://localhost:3000/build/angular2.js:22208:15)↵    at DynamicChangeDetector.AbstractChangeDetector._detectChangesInLightDomChildren (http://localhost:3000/build/angular2.js:22221:19)↵    at DynamicChangeDetector.AbstractChangeDetector._detectChanges (http://localhost:3000/build/angular2.js:22209:15)↵    at DynamicChangeDetector.AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:3000/build/angular2.js:22227:19)↵    at DynamicChangeDetector.AbstractChangeDetector._detectChanges (http://localhost:3000/build/angular2.js:22212:15)↵    at DynamicChangeDetector.AbstractChangeDetector.detectChanges (http://localhost:3000/build/angular2.js:22203:74)"__proto__: DehydratedException
```

**Comment by ctindel** [comment]
I also see errors when I use Chrome Version 45.0.2439.0 canary (64-bit)

**Comment by tapas4java** [comment]
Any findings on this? I am seeing same issue in  `alpha-28` also:

```
TypeError: Cannot read property 'then' of undefined

TypeError: Cannot read property 'then' of undefined
    at RootRouter.commit (router.js:186)
    at router.js:110
    at Zone.run (core.js:91)
    at Zone.NgZone._createInnerZone.zone.fork.fork.$run [as run] (ng_zone.js:126)
    at zoneBoundFn (core.js:64)BrowserDomAdapter.logError @ browser_adapter.js:65defaultErrorReporter @ application.js:107NgZone._onError @ ng_zone.js:175NgZone._createInnerZone.errorHandling.onError @ ng_zone.js:112run @ core.js:94NgZone._createInnerZone.zone.fork.fork.$run @ ng_zone.js:126zoneBoundFn @ core.js:64
localhost/:1 Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
    at RootRouter.commit (http://localhost:3000/build/angular2.js:16104:14)
    at http://localhost:3000/build/angular2.js:16028:33
    at Zone.run (http://localhost:3000/build/angular2.js:46999:18)
    at Zone.NgZone._createInnerZone.zone.fork.fork.$run [as run] (http://localhost:3000/build/angular2.js:27304:43)
    at zoneBoundFn (http://localhost:3000/build/angular2.js:46972:20)
```

**Comment by naomiblack** [comment]
@btford assigning to you for triage -- can you assess whether this is really a router issue, and rough estimate on effort please?

**Comment by btford** [comment]
@tapas4java @ctindel could either of you please provide steps to reproduce the issue?

**Comment by tapas4java** [comment]
I got this error when I was trying to upgrade [angular2-authentication-sample ](https://github.com/auth0/angular2-authentication-sample) to alpha-29.

Steps:
1. Clone the repo
2. Change angular version to alpha-29
3. Change location strategy changes
4. Run the app

**Comment by gdi2290** [comment]
You can close this issue. This is a problem with the `LoggedInRouterOutlet` implementation not returning in `activate` not angular itself. I have the fix for the repo here https://github.com/auth0/angular2-authentication-sample/pull/24

**Comment by btford** [comment]
Thanks, @gdi2290!
