### ISSUE TITLE
Move remaining jobs from Travis to CircleCI & Travis being flaky

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#27242]
Move the reaming CI jobs from Travis to CircleCI.

In addition to being able to check all CI tests in one place, Travis is being flakey lately. About every other build (if not more) breaks for me. I've seen several different errors, mostly in the `CI_MODE=js` and `CI_MODE=saucelabs_required` jobs. (It remains to be seen whether Saucelabs is also part of the problem, in which case some of the flakes will continue on CircleCI and will need to be addressed there.)

Example failures:

**`CI_MODE=js`:**
- > Error ENOSPC - no space left on disk

**`CI_MODE=saucelabs_required`:**
- > The job exceeded the maximum time limit for jobs, and has been terminated.
- <blockquote>
    <details>
      <summary>Web Worker Renderer v2 should update any element property/attributes/class/style(s) independent of the compilation on the root element and other elements FAILED</summary>

      Chrome 67.0.3396 (Windows 7 0.0.0) Web Worker Renderer v2 should update any element property/attributes/class/style(s) independent of the compilation on the root element and other elements FAILED
          TypeError: Cannot read property 'element' of undefined
	      error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 999427, rootNodeFlags: 3, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: -1, flags: 2, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 0, bindings: [  ], bindingFlags: 8, outputs: [  ], element: null, provider: null, text: Object({ prefix: 'ng2A(' }), query: null, ngContent: null }), Object({ nodeIndex: 1, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 1, childFlags: 999424, directChildFlags: 999424, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'ng1A', attrs: [  ...
	          at <Jasmine>
	          at Function.exports.element.cleanData (packages/upgrade/static/src/common/angular1.ts:303:37 <- dist/all/@angular/upgrade/static/src/common/angular1.js:77:63)
	          at UpgradeHelper.onDestroy (packages/upgrade/static/src/common/upgrade_helper.ts:134:20 <- dist/all/@angular/upgrade/static/src/common/upgrade_helper.js:99:25)
	          at Ng1ComponentA.UpgradeComponent.ngOnDestroy (packages/upgrade/static/src/static/upgrade_component.ts:221:16 <- dist/all/@angular/upgrade/static/src/static/upgrade_component.js:176:21)
	          at callProviderLifecycles (packages/core/src/view/provider.ts:575:13 <- dist/all/@angular/core/src/view/provider.js:516:18)
	          at callElementProvidersLifecycles (packages/core/src/view/provider.ts:541:6 <- dist/all/@angular/core/src/view/provider.js:484:13)
	          at Object.callLifecycleHooksChildrenFirst (packages/core/src/view/provider.ts:529:20 <- dist/all/@angular/core/src/view/provider.js:473:29)
	          at destroyView (packages/core/src/view/view.ts:511:2 <- dist/all/@angular/core/src/view/view.js:470:16)
	          at callViewAction (packages/core/src/view/view.ts:633:6 <- dist/all/@angular/core/src/view/view.js:597:13)
	          at execComponentViewsAction (packages/core/src/view/view.ts:559:6 <- dist/all/@angular/core/src/view/view.js:519:13)
	          at destroyView (packages/core/src/view/view.ts:510:2 <- dist/all/@angular/core/src/view/view.js:469:5)
	          at callWithDebugContext (packages/core/src/view/services.ts:652:22 <- dist/all/@angular/core/src/view/services.js:615:25)
	          at Object.debugDestroyView [as destroyView] (packages/core/src/view/services.ts:356:9 <- dist/all/@angular/core/src/view/services.js:299:12)
	          at ViewRef_.destroy (packages/core/src/view/refs.ts:284:13 <- dist/all/@angular/core/src/view/refs.js:300:26)
	          at packages/core/src/application_ref.ts:559:47 <- dist/all/@angular/core/src/application_ref.js:521:67
	          at <Jasmine>
	          at ApplicationRef.ngOnDestroy (packages/core/src/application_ref.ts:559:24 <- dist/all/@angular/core/src/application_ref.js:521:29)
	          at Object.callNgModuleLifecycle (packages/core/src/view/ng_module.ts:222:20 <- dist/all/@angular/core/src/view/ng_module.js:207:31)
	          at NgModuleRef_.destroy (packages/core/src/view/refs.ts:521:4 <- dist/all/@angular/core/src/view/refs.js:519:21)
	          at packages/core/src/application_ref.ts:298:51 <- dist/all/@angular/core/src/application_ref.js:281:73
	          at <Jasmine>
	          at PlatformRef.destroy (packages/core/src/application_ref.ts:298:26 <- dist/all/@angular/core/src/application_ref.js:281:31)
	          at Module.destroyPlatform (packages/core/src/application_ref.ts:138:14 <- dist/all/@angular/core/src/application_ref.js:141:19)
	          at UserContext.<anonymous> (packages/platform-webworker/test/web_workers/worker/renderer_v2_integration_spec.ts:40:21 <- dist/all/@angular/platform-webworker/test/web_workers/worker/renderer_v2_integration_spec.js:57:48)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
	          at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:288:39)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
	          at Zone.run (node_modules/zone.js/dist/zone.js:138:43)
	          at runInTestZone (node_modules/zone.js/dist/zone-testing.js:509:34)
	          at UserContext.<anonymous> (node_modules/zone.js/dist/zone-testing.js:524:20)
	          at <Jasmine>
	          at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
	          at Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
	          at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)
	      Error: A platform with a different configuration has been created. Please destroy it first.
	          at assertPlatform (packages/core/src/application_ref.ts:124:10 <- dist/all/@angular/core/src/application_ref.js:129:15)
	          at Module.<anonymous> (packages/core/src/application_ref.ts:107:11 <- dist/all/@angular/core/src/application_ref.js:114:16)
	          at UserContext.<anonymous> (packages/platform-webworker/test/web_workers/worker/renderer_v2_integration_spec.ts:47:28 <- dist/all/@angular/platform-webworker/test/web_workers/worker/renderer_v2_integration_spec.js:63:45)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
	          at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:288:39)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
	          at Zone.run (node_modules/zone.js/dist/zone.js:138:43)
	          at runInTestZone (node_modules/zone.js/dist/zone-testing.js:509:34)
	          at UserContext.<anonymous> (node_modules/zone.js/dist/zone-testing.js:524:20)
	          at <Jasmine>
	          at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
	          at Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
	          at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)
	      Error: Illegal state: Could not load the summary for directive MyComp2.
	      error properties: Object({ ngSyntaxError: true })
	          at Object.syntaxError (packages/compiler/src/util.ts:100:16 <- dist/all/@angular/compiler/src/util.js:92:17)
	          at CompileMetadataResolver.getDirectiveSummary (packages/compiler/src/metadata_resolver.ts:423:10 <- dist/all/@angular/compiler/src/metadata_resolver.js:388:38)
	          at JitCompiler.getComponentFactory (packages/compiler/src/jit/compiler.ts:73:43 <- dist/all/@angular/compiler/src/jit/compiler.js:57:46)
	          at CompilerImpl.getComponentFactory (packages/platform-browser-dynamic/src/compiler_factory.ts:77:26 <- dist/all/@angular/platform-browser-dynamic/src/compiler_factory.js:59:31)
	          at TestingCompilerImpl.getComponentFactory (packages/platform-browser-dynamic/testing/src/compiler_factory.ts:61:26 <- dist/all/@angular/platform-browser-dynamic/testing/src/compiler_factory.js:60:31)
	          at TestBedViewEngine.createComponent (packages/core/testing/src/test_bed.ts:603:44 <- dist/all/@angular/core/testing/src/test_bed.js:439:47)
	          at Function.TestBedViewEngine.createComponent (packages/core/testing/src/test_bed.ts:251:35 <- dist/all/@angular/core/testing/src/test_bed.js:151:40)
	          at UserContext.<anonymous> (packages/platform-webworker/test/web_workers/worker/renderer_v2_integration_spec.ts:101:18 <- dist/all/@angular/platform-webworker/test/web_workers/worker/renderer_v2_integration_spec.js:105:18)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
	          at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:288:39)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
	          at Zone.run (node_modules/zone.js/dist/zone.js:138:43)
	          at runInTestZone (node_modules/zone.js/dist/zone-testing.js:509:34)
	          at UserContext.<anonymous> (node_modules/zone.js/dist/zone-testing.js:524:20)
	          at <Jasmine>
	          at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
	          at Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
	          at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)
	      Error: The ng module Ng2ModuleA has already been destroyed.
	          at NgModuleRef_.destroy (packages/core/src/view/refs.ts:517:12 <- dist/all/@angular/core/src/view/refs.js:516:19)
	          at packages/core/src/application_ref.ts:298:51 <- dist/all/@angular/core/src/application_ref.js:281:73
	          at <Jasmine>
	          at PlatformRef.destroy (packages/core/src/application_ref.ts:298:26 <- dist/all/@angular/core/src/application_ref.js:281:31)
	          at Module.destroyPlatform (packages/core/src/application_ref.ts:138:14 <- dist/all/@angular/core/src/application_ref.js:141:19)
	          at UserContext.<anonymous> (packages/platform-webworker/test/web_workers/worker/renderer_v2_integration_spec.ts:41:20 <- dist/all/@angular/platform-webworker/test/web_workers/worker/renderer_v2_integration_spec.js:58:47)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
	          at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:288:39)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
	          at Zone.run (node_modules/zone.js/dist/zone.js:138:43)
	          at runInTestZone (node_modules/zone.js/dist/zone-testing.js:509:34)
	          at UserContext.<anonymous> (node_modules/zone.js/dist/zone-testing.js:524:20)
	          at <Jasmine>
	          at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
	          at Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
	          at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)
    </details>
  </blockquote>
- <blockquote>
    <details>
      <summary>adapter: ng1 to ng2 scope/component change-detection should propagate changes to a downgraded component inside the ngZone FAILED</summary>

      Chrome Mobile 67.0.3396 (Android 6.0.0) [AngularJS v1.7] adapter: ng1 to ng2 scope/component change-detection should propagate changes to a downgraded component inside the ngZone FAILED
	      TypeError: Cannot read property 'element' of undefined
	      error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 999427, rootNodeFlags: 3, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: -1, flags: 2, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 0, bindings: [  ], bindingFlags: 8, outputs: [  ], element: null, provider: null, text: Object({ prefix: 'ng2A(' }), query: null, ngContent: null }), Object({ nodeIndex: 1, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 1, childFlags: 999424, directChildFlags: 999424, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'ng1A', attrs: [  ...
	          at <Jasmine>
	          at Function.exports.element.cleanData (packages/upgrade/static/src/common/angular1.ts:303:37 <- dist/all/@angular/upgrade/static/src/common/angular1.js:77:63)
	          at UpgradeHelper.onDestroy (packages/upgrade/static/src/common/upgrade_helper.ts:134:20 <- dist/all/@angular/upgrade/static/src/common/upgrade_helper.js:99:25)
	          at Ng1ComponentA.UpgradeComponent.ngOnDestroy (packages/upgrade/static/src/static/upgrade_component.ts:221:16 <- dist/all/@angular/upgrade/static/src/static/upgrade_component.js:176:21)
	          at callProviderLifecycles (packages/core/src/view/provider.ts:575:13 <- dist/all/@angular/core/src/view/provider.js:516:18)
	          at callElementProvidersLifecycles (packages/core/src/view/provider.ts:541:6 <- dist/all/@angular/core/src/view/provider.js:484:13)
	          at Object.callLifecycleHooksChildrenFirst (packages/core/src/view/provider.ts:529:20 <- dist/all/@angular/core/src/view/provider.js:473:29)
	          at destroyView (packages/core/src/view/view.ts:511:2 <- dist/all/@angular/core/src/view/view.js:470:16)
	          at callViewAction (packages/core/src/view/view.ts:633:6 <- dist/all/@angular/core/src/view/view.js:597:13)
	          at execComponentViewsAction (packages/core/src/view/view.ts:559:6 <- dist/all/@angular/core/src/view/view.js:519:13)
	          at destroyView (packages/core/src/view/view.ts:510:2 <- dist/all/@angular/core/src/view/view.js:469:5)
	          at callWithDebugContext (packages/core/src/view/services.ts:652:22 <- dist/all/@angular/core/src/view/services.js:615:25)
	          at Object.debugDestroyView [as destroyView] (packages/core/src/view/services.ts:356:9 <- dist/all/@angular/core/src/view/services.js:299:12)
	          at ViewRef_.destroy (packages/core/src/view/refs.ts:284:13 <- dist/all/@angular/core/src/view/refs.js:300:26)
	          at packages/core/src/application_ref.ts:559:47 <- dist/all/@angular/core/src/application_ref.js:521:67
	          at <Jasmine>
	          at ApplicationRef.ngOnDestroy (packages/core/src/application_ref.ts:559:24 <- dist/all/@angular/core/src/application_ref.js:521:29)
	          at Object.callNgModuleLifecycle (packages/core/src/view/ng_module.ts:222:20 <- dist/all/@angular/core/src/view/ng_module.js:207:31)
	          at NgModuleRef_.destroy (packages/core/src/view/refs.ts:521:4 <- dist/all/@angular/core/src/view/refs.js:519:21)
	          at packages/core/src/application_ref.ts:298:51 <- dist/all/@angular/core/src/application_ref.js:281:73
	          at <Jasmine>
	          at PlatformRef.destroy (packages/core/src/application_ref.ts:298:26 <- dist/all/@angular/core/src/application_ref.js:281:31)
	          at Module.destroyPlatform (packages/core/src/application_ref.ts:138:14 <- dist/all/@angular/core/src/application_ref.js:141:19)
	          at UserContext.<anonymous> (packages/upgrade/test/dynamic/upgrade_spec.ts:25:21 <- dist/all/@angular/upgrade/test/dynamic/upgrade_spec.js:29:48)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
	          at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:288:39)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
	          at Zone.run (node_modules/zone.js/dist/zone.js:138:43)
	          at runInTestZone (node_modules/zone.js/dist/zone-testing.js:509:34)
	          at UserContext.<anonymous> (node_modules/zone.js/dist/zone-testing.js:524:20)
	          at <Jasmine>
	          at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
	          at Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
	          at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:595:35)
	      Error: The ng module Ng2ModuleA has already been destroyed.
	          at NgModuleRef_.destroy (packages/core/src/view/refs.ts:517:12 <- dist/all/@angular/core/src/view/refs.js:516:19)
	          at packages/core/src/application_ref.ts:298:51 <- dist/all/@angular/core/src/application_ref.js:281:73
	          at <Jasmine>
	          at PlatformRef.destroy (packages/core/src/application_ref.ts:298:26 <- dist/all/@angular/core/src/application_ref.js:281:31)
	          at Module.destroyPlatform (packages/core/src/application_ref.ts:138:14 <- dist/all/@angular/core/src/application_ref.js:141:19)
	          at UserContext.<anonymous> (packages/upgrade/test/dynamic/upgrade_spec.ts:26:20 <- dist/all/@angular/upgrade/test/dynamic/upgrade_spec.js:30:47)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
	          at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:288:39)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
	          at Zone.run (node_modules/zone.js/dist/zone.js:138:43)
	          at runInTestZone (node_modules/zone.js/dist/zone-testing.js:509:34)
	          at UserContext.<anonymous> (node_modules/zone.js/dist/zone-testing.js:524:20)
	          at <Jasmine>
	          at node_modules/zone.js/dist/zone-testing.js:825:21
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
	          at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:288:39)
	          at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
	          at Zone.run (node_modules/zone.js/dist/zone.js:138:43)
	          at AsyncTestZoneSpec.finishCallback (node_modules/zone.js/dist/zone-testing.js:824:29)
	          at node_modules/zone.js/dist/zone-testing.js:656:31
	          at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:31)
	          at Zone.runTask (node_modules/zone.js/dist/zone.js:188:47)
	          at ZoneTask.invokeTask (node_modules/zone.js/dist/zone.js:496:34)
	          at ZoneTask.invoke (node_modules/zone.js/dist/zone.js:485:48)
	          at timer (node_modules/zone.js/dist/zone.js:2054:29)
    </details>
  </blockquote>

**Comment by gkalpak** [comment]
Assigned @IgorMinar, since he's already working on moving remaining Travis jobs over to CircleCI.

**Comment by gkalpak** [comment]
Obsolete (we have moved off of Travis).
