### ISSUE TITLE
I can't run item ,the error:Progress Plugin Invalid Options

### ISSUE THREAD

**Issue by CheeseZhao** [angular/angular#27259]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
I user the CLI: ng serve , then error:
`Your global Angular CLI version (6.1.5) is greater than your local
version (6.0.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

ValidationError: Progress Plugin Invalid Options

options['colors'] is an invalid additional property
options should pass "instanceof" keyword validation
options should match exactly one schema in oneOf

    at validateOptions (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/schema-utils/src/validateOptions.js:31:11)
    at new ProgressPlugin (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/webpack/lib/ProgressPlugin.js:90:3)
    at Object.getCommonConfig (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js:126:27)
    at BrowserBuilder.buildWebpackConfig (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/@angular-devkit/build-angular/src/browser/index.js:115:31)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:38:50)
    at Observable._trySubscribe (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/Observable.js:30:22)
    at /Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
    at MergeMapSubscriber._next (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/Subscriber.js:67:18)
    at TapSubscriber._next (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/operators/tap.js:65:26)
    at TapSubscriber.Subscriber.next (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/cheese/IdeaProjects/yueda_mall_4.5.0/deFangMallWeb/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
`

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jasonaden** [comment]
Closing based on above.
