### ISSUE TITLE
ngtsc/ngcc: unable to statically resolve UMD references

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#27452]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Description

In UMD packages we get directive declarations such as 

```
{selector: 'cdk-virtual-scroll-viewport',
    template: "...",
    styles: ["..."],
    host: { ... },
    encapsulation: core.ViewEncapsulation.None,
    changeDetection: core.ChangeDetectionStrategy.OnPush,
}
```

Note that there are expressions like `core.ViewEncapsulation.None`. The `core` identifier refers to the parameter on the factory function, which is effectively a namespace for an import. The wrapper and function declaration looks like:

```
"(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/core'), require('@angular/cdk/coercion'), require('rxjs'), require('rxjs/operators'), require('@angular/cdk/platform'), require('@angular/cdk/bidi'), require('@angular/cdk/collections')) :
	typeof define === 'function' && define.amd ? define('@angular/cdk/scrolling', ['exports', '@angular/core', '@angular/cdk/coercion', 'rxjs', 'rxjs/operators', '@angular/cdk/platform', '@angular/cdk/bidi', '@angular/cdk/collections'], factory) :
	(factory((global.ng = global.ng || {}, global.ng.cdk = global.ng.cdk || {}, global.ng.cdk.scrolling = {}),global.ng.core,global.ng.cdk.coercion,global.rxjs,global.rxjs.operators,global.ng.cdk.platform,global.ng.cdk.bidi,global.ng.cdk.collections));
}(this, (function (exports,core,coercion,rxjs,operators,platform,bidi,collections) { 'use strict';
```

where the factory function that declares `core` as a parameter is `function (exports,core,coercion,rxjs,operators,platform,bidi,collections) { ... }`.

When ngcc tries to compile this file, it tries to statically resolve `core.ViewEncapsulation.None` and then fails because it cannot resolve the `core` (`Parameter`) node.

## 🔬 Minimal Reproduction

The error can be seen in the integration test for the ngcc UMD support PR (https://github.com/angular/angular/pull/25445). See https://circleci.com/gh/angular/angular/119366.

## 🔥 Exception or Error

```
Compiling @angular/cdk/scrolling - umd
Error: Don't know how to refer to Parameter
    at StaticInterpreter.getReference (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:635:23)
    at StaticInterpreter.visitDeclaration (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:420:29)
    at StaticInterpreter.visitIdentifier (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:394:31)
    at StaticInterpreter.visitExpression (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:275:29)
    at StaticInterpreter.visitPropertyAccessExpression (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:465:28)
    at StaticInterpreter.visitExpression (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:278:29)
    at StaticInterpreter.visitPropertyAccessExpression (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:465:28)
    at StaticInterpreter.visitExpression (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:278:29)
    at StaticInterpreter.visit (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:250:25)
    at Object.staticallyResolve (angular/integration/ngcc/node_modules/@angular/compiler-cli/src/ngtsc/metadata/src/resolver.js:208:53)
```

**Comment by petebacondarwin** [comment]
Perhaps one approach would be to move the `identifierOfDeclaration()` function from `resolve.ts` to a member of the `ReflectionHost`, so that the `UmdReflectionHost` could provide something special in this case...

**Comment by 100cm** [comment]
so how to get umd angular reference after angular 7 ? most  umd libs set `global.ng.core` as reference now..

**Comment by petebacondarwin** [comment]
@100cm we are working on UMD support with ngcc, this is just one issue that we need to deal with. Moreover, ngcc and ngtsc are specific to the ivy build processes that are not even turned on in Angular 7 yet. There should be no issue with pre-ivy use of Angular; and by the time it is turned on we will have support in place.

**Comment by 100cm** [comment]
@petebacondarwin For Me, i want to run remote AOT compiled component code in browser, before Angular 6, You can get `ng.core ng.animation `in `window` object,

![image](https://user-images.githubusercontent.com/12691638/49840947-947d0600-fdf0-11e8-9d5f-a8d4cf5c087b.png)

and after Angular 6 +

![image](https://user-images.githubusercontent.com/12691638/49840963-a363b880-fdf0-11e8-9ca3-58b202c41bea.png)
So , i am so confused for this , and i want to load remote AOT compiled component that build in UMD format  like this 

https://trotyl.github.io/ng-component-loader-demo/

Could you give me some help?

**Comment by alan-agius4** [comment]
@100cm see 
https://github.com/angular/angular-cli/issues/13205#issuecomment-447745248

**Comment by JoostK** [comment]
@petebacondarwin I think you solved this now that UMD is supported?

**Comment by petebacondarwin** [comment]
Yes. Thanks @JoostK for noting it.
