### ISSUE TITLE
CircleCI error with bazel: "Error: EEXIST: file already exists"

### ISSUE THREAD

**Issue by ocombe** [angular/angular#27575]
I had this weird error on circleCI: https://circleci.com/gh/angular/angular/125463

```
ERROR: /home/circleci/ng/packages/bazel/BUILD.bazel:3:1: SkylarkAction packages/bazel/npm_package failed (Exit 1): packager failed: error executing command 
  (cd /home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular && \
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/npm_package/packager bazel-out/k8-fastbuild/bin/packages/bazel/npm_package-0.params)
Error: EEXIST: file already exists, mkdir 'bazel-out/k8-fastbuild/bin/packages/external/ngdeps/node_modules/rxjs/src/internal/observable/dom'
    at Object.mkdirSync (fs.js:729:3)
    at mkdirp (/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/npm_package/packager.runfiles/build_bazel_rules_nodejs/internal/npm_package/packager.js:23:8)
    at write (/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/npm_package/packager.runfiles/build_bazel_rules_nodejs/internal/npm_package/packager.js:28:3)
    at main (/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/npm_package/packager.runfiles/build_bazel_rules_nodejs/internal/npm_package/packager.js:101:5)
    at Object.<anonymous> (/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/npm_package/packager.runfiles/build_bazel_rules_nodejs/internal/npm_package/packager.js:132:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

I restarted the instance and it passed... not sure what caused it.

**Comment by jelbourn** [comment]
Closing since this is obsolete.
