### ISSUE TITLE
angular can not navigate to a new pag when deploy to nginx with ie11 and edge.

### ISSUE THREAD

**Issue by liujingsheng** [angular/angular#27598]
my angular web can not navigate to link when deploy to nginx by ie11 and edge. the chrome looks good. when i try the ng serve locally it works good on ie11 and edge. but deploy to ngix, it can not link to the dash page when i log in.

I have update to latest angular, but still failed.

the error like this:

ERROR Error: Uncaught (in promise): Error: SyntaxError
Error: SyntaxError
   at callWithDebugContext (http://192.168.1.196/vendor.js:83010:9)
   at debugCreateRootView (http://192.168.1.196/vendor.js:82486:5)
   at ComponentFactory_.prototype.create (http://192.168.1.196/vendor.js:80307:9)
   at ComponentFactoryBoundToModule.prototype.create (http://192.168.1.196/vendor.js:69950:9)
   at ViewContainerRef_.prototype.createComponent (http://192.168.1.196/vendor.js:80418:9)
   at RouterOutlet.prototype.activateWith (http://192.168.1.196/vendor.js:138165:9)
   at ActivateRoutes.prototype.activateRoutes (http://192.168.1.196/vendor.js:135491:25)
   at Anonymous function (http://192.168.1.196/vendor.js:135442:13)
   at Array.prototype.forEach (native code)
   at ActivateRoutes.prototype.activateChildRoutes (http://192.168.1.196/vendor.js:135441:9)

I checked the angular page https://angular.io/guide/browser-support try change the polyfills.ts and change the index.html still could not work on ie or edge.

could any experts help to check

**Comment by alxhub** [comment]
Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!
