### ISSUE TITLE
ngtsc problem with angular modules imort

### ISSUE THREAD

**Issue by klimentru1986** [angular/angular#27698]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cli

### Description
Problem with ivy renderer and ngtsc.
When i try to import any angular module into my application and run `ng serve --aot` or `ngc -p src/tsconfig.app.json` 
Build will fail with error: 
```Error: Module not found: CommonModule  at SelectorScopeRegistry.lookupScopesOrDie```

## 🔬 Minimal Reproduction
main.ts
```
import { AppComponent } from './app/app.component';
import { ɵrenderComponent as renderComponent } from '@angular/core';

renderComponent(AppComponent);
```
app.module.ts
```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';


@NgModule({
  declarations: [AppComponent],
  imports: [CommonModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```
app.component.ts
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: '<div *ngIf="title">{{title}}</div>'
})
export class AppComponent {
  title = 'ivy-cd';
}
```
tsconfig.app.json
```
  "angularCompilerOptions": {
    "enableIvy": "ngtsc"
  }
```
run script `ng serve --aot` or `ngc -p src/tsconfig.app.json` or `ng build --prod`
## 🔥 Exception or Error
<pre><code>
ERROR in : Error: Module not found: CommonModule
    at SelectorScopeRegistry.lookupScopesOrDie (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\selector_scope.js:142:23)
    at C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\selector_scope.js:172:121
    at Array.map (<anonymous>)
    at SelectorScopeRegistry.lookupScopes (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\selector_scope.js:172:87)
    at SelectorScopeRegistry.lookupScopesOrDie (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\selector_scope.js:140:31)
    at SelectorScopeRegistry.lookupCompilationScopeAsRefs (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\selector_scope.js:111:18)
    at SelectorScopeRegistry.lookupCompilationScope (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\selector_scope.js:136:30)
    at ComponentDecoratorHandler.compile (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:180:44)
    at IvyCompilation.compileIvyFieldFor (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:163:34)
    at IvyVisitor.visitClassDeclaration (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\transform.js:48:40)
    at C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\util\src\visitor.js:77:93
    at IvyVisitor.Visitor._visitListEntryNode (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\util\src\visitor.js:51:26)
    at IvyVisitor.Visitor._visit (C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\util\src\visitor.js:77:36)
    at C:\tmp\ivy-cd\node_modules\@angular\compiler-cli\src\ngtsc\util\src\visitor.js:75:76
    at visitNodes (C:\tmp\ivy-cd\node_modules\typescript\lib\typescript.js:62256:48)
    at visitLexicalEnvironment (C:\tmp\ivy-cd\node_modules\typescript\lib\typescript.js:62289:22)
[0m
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
"dependencies": {
    "@angular/animations": "~7.1.3",
    "@angular/common": "~7.1.3",
    "@angular/compiler": "~7.1.3",
    "@angular/core": "~7.1.3",
    "@angular/forms": "~7.1.3",
    "@angular/platform-browser": "~7.1.3",
    "@angular/platform-browser-dynamic": "~7.1.3",
    "@angular/router": "~7.1.3",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.3",
    "@angular/cli": "~7.1.3",
    "@angular/compiler-cli": "~7.1.3",
    "@angular/language-service": "~7.1.3",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment]
Most likely you didn't run `ivy-ngcc` after the install.

**Comment by klimentru1986** [comment]
@trotyl thanks!!! It works.
