### ISSUE TITLE
BindingParser can't find user-created pipe in html file (Aot Compiler + Ivy)

### ISSUE THREAD

**Issue by leo6104** [angular/angular#27808]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?
It was problem with new Ivy compiler.

### Description
When compile with enableIvy: true and AoT mode, it prints `The pipe {name} cannot be found` error message. 
According to Ivy status website, It seems Pipe should be work in all the case. 
It only occurs in Ivy + Aot compile mode. I have 6 projects in production-level and i got same problem in all projects. Ivy + JIT works well.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 
Sorry for not providing reproduction link. I don't have enough time now. I can try to create reproduction projects in next week.

I create safe pipe in sharedModule 
```
@Pipe({
  name: 'safe'
})
export class SafePipe {

  constructor(protected _sanitizer: DomSanitizer) {
  }

  transform(value: string, type: string): SafeHtml | SafeStyle | SafeScript | SafeUrl | SafeResourceUrl {
    switch (type) {
      case 'html':
        return this._sanitizer.bypassSecurityTrustHtml(value);
      case 'style':
        return this._sanitizer.bypassSecurityTrustStyle(value);
      case 'script':
        return this._sanitizer.bypassSecurityTrustScript(value);
      case 'url':
        return this._sanitizer.bypassSecurityTrustUrl(value);
      case 'resourceUrl':
        return this._sanitizer.bypassSecurityTrustResourceUrl(value);
      default:
        throw new Error(`Unable to bypass security for invalid type: ${type}`);
    }
  }

}
```

and use it in html 
```
<iframe class="embed-responsive-item"
            [src]="'https://www.youtube.com/embed/' + paper.youtube_id +'?autoplay=1&rel=0' | safe: 'resourceUrl'" frameborder="0" allowfullscreen></iframe>
```

## 🔥 Exception or Error
**Exact message (CLI print):**
```
ERROR in : Template parse errors:
The pipe 'safe' could not be found ("
</h2>

<mat-dialog-content [ERROR ->][innerHtml]="content | safe:'html'"></mat-dialog-content>

<button type="button" class="btn btn-gradi"): ~/mms-platform/projects/mms-core/src/shared/component/dialog-alert/dialog-alert.component.html@4:20
```

I got stack trace for debugging through modifying node_modules/@angular/compiler umd file 
Hope this can help.

```
Error
    at ~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:12183:35
    at Map.forEach (<anonymous>)
    at BindingParser._checkPipes (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:12180:33)
    at BindingParser._parseBinding (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:12045:22)
    at BindingParser.parsePropertyBinding (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:12014:51)
    at HtmlAstToIvyAst.parseAttribute (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:12791:40)
    at HtmlAstToIvyAst.visitElement (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:12656:43)
    at Element.visit (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:10183:80)
    at visit (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:10199:41)
    at ~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:10201:29
    at Array.forEach (<anonymous>)
    at visitAll (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:10200:15)
    at htmlAstToRender3Ast (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:12577:24)
    at ~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:23666:38
    at Array.forEach (<anonymous>)
    at AotCompiler._compilePartialModule (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:23654:24)
    at ~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:23636:58
    at Array.forEach (<anonymous>)
    at AotCompiler.emitAllPartialModules (~/mms-platform/node_modules/@angular/compiler/bundles/compiler.umd.js:23636:19)
    at AngularCompilerProgram._emitRender3 (~/mms-platform/node_modules/@angular/compiler-cli/src/transformers/program.js:225:41)
    at AngularCompilerProgram.emit (~/mms-platform/node_modules/@angular/compiler-cli/src/transformers/program.js:211:59)
    at AngularCompilerPlugin._emit (~/mms-platform/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:840:49)     
```

Related code lines:
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/compiler/src/aot/compiler.ts#L377
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/compiler/src/template_parser/binding_parser.ts#L385

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 7.1.4
Node: 10.14.2
OS: darwin x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.4
@angular-devkit/build-angular      0.11.4
@angular-devkit/build-ng-packagr   0.11.4
@angular-devkit/build-optimizer    0.11.4
@angular-devkit/build-webpack      0.11.4
@angular-devkit/core               7.1.4
@angular-devkit/schematics         7.1.4
@angular/cdk                       7.2.0
@angular/material                  7.2.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.4
@schematics/angular                7.1.4
@schematics/update                 0.11.4
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.25.1
```

**Anything else relevant?**

**Comment by webKity** [comment]
I had the same problem.
