### ISSUE TITLE
EmulatedEncapsulationServerRenderer2 DefaultServerRenderer2 setProperty. Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by alikarimii** [angular/angular#27956]
Hi
I use Angular-universal-example with some change in `server.ts`. I add `domino` for define `window` object in server side to prevent some "window not define" error in server side.

this error log in server console.
`ERROR TypeError: Cannot read property 'toLowerCase' of undefined
    at EmulatedEncapsulationServerRenderer2.DefaultServerRenderer2.setProperty (/universal/dist/server.js:125246:34)
    at BaseAnimationRenderer.setProperty (/universal/dist/server.js:124312:27)
    at SafeSubscriber._next (/universal/dist/server.js:161724:28)
    at SafeSubscriber.__tryOrUnsub (/universal/dist/server.js:27968:16)
    at SafeSubscriber.next (/universal/dist/server.js:27906:22)
    at Subscriber._next (/universal/dist/server.js:27849:26)
    at Subscriber.next (/universal/dist/server.js:27826:18)
    at TakeWhileSubscriber.nextOrComplete (/universal/dist/server.js:37724:25)
    at TakeWhileSubscriber._next (/universal/dist/server.js:37719:14)
    at TakeWhileSubscriber.Subscriber.next (/universal/dist/server.js:27826:18)`

 from this file
`angular/platform-server/src/server_renderer.ts` [link](https://github.com/angular/angular/blob/master/packages/platform-server/src/server_renderer.ts)

How can fix this?
this repo is here [angular-universal](https://github.com/alikarimii/angular-universal-nebular-theme)

**Comment by kara** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
