### ISSUE TITLE
Build is failing on DEV build of Dart SDK

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2798]
https://travis-ci.org/angular/angular/jobs/69037072

/cc @kevmoo @sigmundch

**Comment by kevmoo** [comment]
This is related to https://github.com/dart-lang/sdk/issues/23755

We'll need to roll another dart dev build to fix this – Angular may want to disable dev builds until we get there

**Comment by kevmoo** [comment]
My local build output

```
Build error:
Transform InjectorGenerator on benchmarks_external|web/src/tree/tree_benchmark.dart threw error: <rethrow>
Caused by The null object does not have a getter 'importsAndExports'.

NoSuchMethodError: method not found: 'importsAndExports'
Receiver: null
Arguments: []
#0      AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6434:7)
#1      AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6403:7)
#2      AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2804:12)
#3      AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3413:17)
#4      AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3442:14)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1692:7)
#6      ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:157:25)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#8      ListIterable.toList (dart:_internal/iterable.dart:219)
#9      ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:158:10)
#10     _RootZone.runUnary (dart:async/zone.dart:1166)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#13     _Future._completeWithValue (dart:async/future_impl.dart:368)
#14     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#16     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Caused by The null object does not have a getter 'importsAndExports'.

NoSuchMethodError: method not found: 'importsAndExports'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7981:49)
#3      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7993:9)
#4      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7983:9)
#5      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7983:9)
#6      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7983:9)
#7      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7983:9)
#8      LibraryResolver._addToDependencyMap (package:analyzer/src/generated/resolver.dart:7983:9)
#9      LibraryResolver._computeDependencyMap (package:analyzer/src/generated/resolver.dart:8256:5)
#10     LibraryResolver._computeLibrariesInCycles (package:analyzer/src/generated/resolver.dart:8299:9)
#11     LibraryResolver.resolveLibrary (package:analyzer/src/generated/resolver.dart:7861:26)
#12     ResolveDartLibraryTask.internalPerform (package:analyzer/src/generated/engine.dart:10538:15)
#13     AnalysisTask._safelyPerform (package:analyzer/src/generated/engine.dart:6430:7)
#14     AnalysisTask.perform (package:analyzer/src/generated/engine.dart:6403:7)
#15     AnalysisContextImpl._cacheDartResolutionData (package:analyzer/src/generated/engine.dart:2804:12)
#16     AnalysisContextImpl._getDartResolutionData (package:analyzer/src/generated/engine.dart:3413:17)
#17     AnalysisContextImpl._getDartResolutionData2 (package:analyzer/src/generated/engine.dart:3442:14)
#18     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/generated/engine.dart:1692:7)
#19     ResolverImpl._performResolve.<anonymous closure>.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:157:25)
#20     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#21     ListIterable.toList (dart:_internal/iterable.dart:219)
#22     ResolverImpl._performResolve.<anonymous closure> (package:code_transformers/src/resolver_impl.dart:158:10)
#23     _RootZone.runUnary (dart:async/zone.dart:1166)
#24     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#25     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#26     _Future._completeWithValue (dart:async/future_impl.dart:368)
#27     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#29     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)


package:analyzer/src/generated/engine.dart 2456:11            AnalysisContextImpl.recordResolveDartLibraryTaskResults
package:analyzer/src/generated/engine.dart 4866:32            AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask
package:analyzer/src/generated/engine.dart 10530:15           ResolveDartLibraryTask.accept
package:analyzer/src/generated/engine.dart 6411:33            AnalysisTask.perform.<fn>
package:analyzer/src/generated/utilities_general.dart 150:15  _PerformanceTagImpl.makeCurrentWhile
package:analyzer/src/generated/engine.dart 6411:10            AnalysisTask.perform
package:analyzer/src/generated/engine.dart 2804:12            AnalysisContextImpl._cacheDartResolutionData
package:analyzer/src/generated/engine.dart 3413:17            AnalysisContextImpl._getDartResolutionData
package:analyzer/src/generated/engine.dart 3442:14            AnalysisContextImpl._getDartResolutionData2
package:analyzer/src/generated/engine.dart 1692:7             AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25       ResolverImpl._performResolve.<fn>.<fn>
dart:_internal/iterable.dart 413                              MappedListIterable.elementAt
dart:_internal/iterable.dart 219                              ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10       ResolverImpl._performResolve.<fn>
dart:async/zone.dart 1166                                     _RootZone.runUnary
dart:async/future_impl.dart 494                               _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 577                               _Future._propagateToListeners
dart:async/future_impl.dart 368                               _Future._completeWithValue
dart:async/future_impl.dart 422                               _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 43                         _microtaskLoop
dart:async/schedule_microtask.dart 52                         _microtaskLoopEntry
dart:isolate-patch/isolate_patch.dart 96                      _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                     _RawReceivePortImpl._handleMessage

package:analyzer/src/generated/engine.dart 2456:11            AnalysisContextImpl.recordResolveDartLibraryTaskResults
package:analyzer/src/generated/engine.dart 4866:32            AnalysisContextImpl_AnalysisTaskResultRecorder.visitResolveDartLibraryTask
package:analyzer/src/generated/engine.dart 10530:15           ResolveDartLibraryTask.accept
package:analyzer/src/generated/engine.dart 6411:33            AnalysisTask.perform.<fn>
package:analyzer/src/generated/utilities_general.dart 150:15  _PerformanceTagImpl.makeCurrentWhile
package:analyzer/src/generated/engine.dart 6411:10            AnalysisTask.perform
package:analyzer/src/generated/engine.dart 2804:12            AnalysisContextImpl._cacheDartResolutionData
package:analyzer/src/generated/engine.dart 3413:17            AnalysisContextImpl._getDartResolutionData
package:analyzer/src/generated/engine.dart 3442:14            AnalysisContextImpl._getDartResolutionData2
package:analyzer/src/generated/engine.dart 1692:7             AnalysisContextImpl.computeLibraryElement
package:code_transformers/src/resolver_impl.dart 157:25       ResolverImpl._performResolve.<fn>.<fn>
dart:_internal                                                ListIterable.toList
package:code_transformers/src/resolver_impl.dart 158:10       ResolverImpl._performResolve.<fn>
dart:isolate                                                  _RawReceivePortImpl._handleMessage
```

**Comment by sigmundch** [comment]
I have a fix on its way, I'll do some extra testing and file a merge request once it's in. I'll keep you posted

**Comment by sigmundch** [comment]
I submitted the fix in master (https://github.com/dart-lang/sdk/commit/4ec3db6947cdbb554c395d4b98196293bf7de3bc), it should hopefully be available in the next dev release.

**Comment by sigmundch** [comment]
Sure thing. FYI this bug tracks the request to merge this change to the dev channel: https://github.com/dart-lang/sdk/issues/23759, once it gets closed, it should be a matter of time until the bots update and release the new sdk with the fix.

**Comment by tbosch** [comment]
Please revert b3fc357a151ea79decbe49e0f55a461b28a1fc58 once this is version of dart is publicly available on the dev channel.
