### ISSUE TITLE
Angular 7 NodeInvocationException: Can't resolve all parameters for XHRBackend: (?, ?, ?)

### ISSUE THREAD

**Issue by LucianoDiPierno** [angular/angular#28016]
# 🐞 bug report

### Affected Package
@angular/http maybe

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.1.4

### Description

After updating the following packages:

- @Angular (animations, common, compiler, core, forms, http, platform-browser, platform-browser-dynamic, platform-server, router, cli, compiler-cli, language-service) from 6.1.4 to 7.2.0
- rxjs from 6.2.2 to 6.3.3
- @ng-bootstrap/ng-bootstrap from 3.1.0 to 4.0.1
- codelyzer from 4.4.4 to 4.5.0

I get the error "NodeInvocationException: Can't resolve all parameters for XHRBackend: (?,?,?)" at the start of the application.

## 🔬 Minimal Reproduction
I do not know how to reproduce the problem

## 🔥 Exception or Error
<pre><code>
NodeInvocationException: Can't resolve all parameters for XHRBackend: (?, ?, ?).
Error: Can't resolve all parameters for XHRBackend: (?, ?, ?).
at syntaxError (ProjectPath\ClientApp\dist\vendor.js:9799:21)
at CompileMetadataResolver.module.exports../node_modules/@angular/compiler/bundles/compiler.umd.js.CompileMetadataResolver._getDependenciesMetadata (ProjectPath\ClientApp\dist\vendor.js:26048:39)
at CompileMetadataResolver.module.exports../node_modules/@angular/compiler/bundles/compiler.umd.js.CompileMetadataResolver._getTypeMetadata (ProjectPath\ClientApp\dist\vendor.js:25941:30)
at CompileMetadataResolver.module.exports../node_modules/@angular/compiler/bundles/compiler.umd.js.CompileMetadataResolver._getInjectableTypeMetadata (ProjectPath\ClientApp\dist\vendor.js:26163:25)
at CompileMetadataResolver.module.exports../node_modules/@angular/compiler/bundles/compiler.umd.js.CompileMetadataResolver.getProviderMetadata (ProjectPath\ClientApp\dist\vendor.js:26172:26)
at ProjectPath\ClientApp\dist\vendor.js:26110:53
at Array.forEach (<anonymous>)
at CompileMetadataResolver.module.exports../node_modules/@angular/compiler/bundles/compiler.umd.js.CompileMetadataResolver._getProvidersMetadata (ProjectPath\ClientApp\dist\vendor.js:26070:23)
at CompileMetadataResolver.module.exports../node_modules/@angular/compiler/bundles/compiler.umd.js.CompileMetadataResolver.getNgModuleMetadata (ProjectPath\ClientApp\dist\vendor.js:25789:63)
at CompileMetadataResolver.module.exports../node_modules/@angular/compiler/bundles/compiler.umd.js.CompileMetadataResolver.getNgModuleSummary (ProjectPath\ClientApp\dist\vendor.js:25619:39)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.0
Node: 8.12.0
OS: win32 x64
Angular: 7.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.12.0
@angular-devkit/core         0.7.5
@angular-devkit/schematics   7.2.0
@ngtools/webpack             6.1.5
@schematics/angular          7.2.0
@schematics/update           0.12.0
rxjs                         6.3.3
typescript                   2.9.2
webpack                      4.17.1
</code></pre>

**Anything else relevant?**
Link to StackOverflow for more details: [click](https://stackoverflow.com/questions/54089136/angular-7-nodeinvocationexception-cant-resolve-all-parameters-for-xhrbackend)

**Comment by mhevery** [comment]
Sorry without reproduction we can't fix this.

**Comment by lilian131** [comment]
hi @LucianoDiPierno did you find a solution ?

**Comment by lilian131** [comment]
this is resolved for me by : 
`import 'core-js/es7/reflect';`

to polyfills.ts
