### ISSUE TITLE
angular.io doesn't work with IE11

### ISSUE THREAD

**Issue by wKoza** [angular/angular#28177]
Hi,

I have tested angular.io on IE 11 and it doesn't work. The first page is loaded but we have this exception:

```
"TypeError: Objet attendu\n   at e.prototype.reportError (https://angular.io/main.09223f95b24b4723adce.js:1:493566)\n   at e.prototype.handleError (https://angular.io/main.09223f95b24b4723adce.js:1:493467)\n   at next (https://angular.io/main.09223f95b24b4723adce.js:1:65566)\n   at Anonymous function (https://angular.io/main.09223f95b24b4723adce.js:1:46907)\n   at e.prototype.__tryOrUnsub (https://angular.io/main.09223f95b24b4723adce.js:1:147806)\n   at e.prototype.next (https://angular.io/main.09223f95b24b4723adce.js:1:146948)\n   at e.prototype._next (https://angular.io/main.09223f95b24b4723adce.js:1:145958)\n   at e.prototype.next (https://angular.io/main.09223f95b24b4723adce.js:1:145641)\n   at e.prototype.next (https://angular.io/main.09223f95b24b4723adce.js:1:173361)\n   at e.prototype.emit (https://angular.io/main.09223f95b24b4723adce.js:1:46673)"


{
   [functions]: ,
   __proto__: { },
   description: "Objet attendu",
   message: "Objet attendu",
   name: "TypeError",
   number: -2146823281,
   stack: "TypeError: Objet attendu
   at e.prototype.reportError (https://angular.io/main.09223f95b24b4723adce.js:1:493566)
   at e.prototype.handleError (https://angular.io/main.09223f95b24b4723adce.js:1:493467)
   at t.prototype.error (https://angular.io/main.09223f95b24b4723adce.js:1:397062)
   at Anonymous function (https://angular.io/main.09223f95b24b4723adce.js:1:461855)
   at e.prototype.error (https://angular.io/main.09223f95b24b4723adce.js:1:13724)
   at e.prototype._error (https://angular.io/main.09223f95b24b4723adce.js:1:405778)
   at e.prototype.error (https://angular.io/main.09223f95b24b4723adce.js:1:145721)
   at e.prototype.notifyError (https://angular.io/main.09223f95b24b4723adce.js:1:176557)
   at e.prototype._error (https://angular.io/main.09223f95b24b4723adce.js:1:375068)
   at e.prototype.error (https://angular.io/main.09223f95b24b4723adce.js:1:145721)"
}
```

And when I click on an other link, we have this error:

```

ERROR Error: [DocViewer] Error preparing document 'guide/component-interaction': TypeError: L’objet ne gère pas la propriété ou la méthode « remove »
```

 Version: IE 11.0.9600.19129

**Comment by gkalpak** [comment]
The reason is that we call `ChildNode#remove()` [here][1], which is not supported on IE ([according to MDN][2]).
(For reference, this was broken back in 12be31161.)

The fix is to change `anchorLink.remove()` to something like `anchorLink.parentNode.removeChild(anchorLink)`.
@wKoza, interested in taking a stab at it?

[1]: https://github.com/angular/angular/blob/f983e99fb245532b41125672447a7d6756e9da06/aio/src/app/shared/toc.service.ts#L71
[2]: https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove

**Comment by wKoza** [comment]
@gkalpak , I take it!

**Comment by petebacondarwin** [comment]
@gkalpak don't forget that we have `docs-infra...` milestones now!

**Comment by spock123** [comment]
Id' be curious to see some Analytics numbers on the IE11 visitors to that site. Imagine it can be counted  using one hand. Maybe it's time to let go of IE11 support?

**Comment by wKoza** [comment]
My client ( a big company) still uses IE...
