### ISSUE TITLE
Error Navigating To Sibling After Navigation in Named Router Outlet

### ISSUE THREAD

**Issue by cmdickson** [angular/angular#28189]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
Not sure, but I don't think so

### Description
Navigation to a sibling route fails after navigating to a route that includes a named router outlet which is a child of one of sibling routes.

Given the routing configuration, below, and starting with a URL of <code>/1/documents</code>:

1. If link to "other" is triggered from <code>ModuleComponent</code>, URL changes to <code>/1/other</code> and component is loaded successfully.  This is working as expected
2. If a component is loaded into the named outlet (i.e. URL changed to <code>/1/(documents//outlet:test)</code>) and then the same link from (1) is used, then no navigation occurs and an error is logged in the console.

The expectation would be for (2) to result in the navigation completing successfully and for <code>OtherComponent</code> to be displayed.

Another note:  Problem persists even if the named router outlet portion of the route is removed (i.e. <code>[{ outlets: { outlet: null } }]</code>)

<pre><code>
export const appRoutes: Routes = [{
  path: '', component: AppOutletComponent,
  children: [
    { path: ':id/other', component: OtherComponent },
    {
      path: ':id', component: ModuleComponent, pathMatch: 'prefix',
      children: [
        { path: '', redirectTo: 'documents', pathMatch: 'full' },
        { path: 'documents', component: DocumentsComponent },
        {
          path: 'test',
          outlet: 'outlet',
          component: OutletChildComponent
        }
      ]
    }
  ]
}];
</code></pre>

Hopefully I am not simply misunderstanding or abusing the routing system...

## 🔬 Minimal Reproduction
With straight app and child components:
https://outlet-routing-bug-shared-minimal.stackblitz.io
https://stackblitz.com/edit/outlet-routing-bug-shared-minimal

Slightly different behaviour when in lazy-loaded module (this is what I am actually trying to achieve in my app, but tried to pare it down):
https://outlet-routing-bug-shared.stackblitz.io
https://stackblitz.com/edit/outlet-routing-bug-shared

## 🔥 Exception or Error
<pre><code>
ERROR
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '1'
Error: Cannot match any routes. URL Segment: '1'
at ApplyRedirects.noMatchError (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/@angular/router@7.0.1/bundles/router.umd.js:2520:20)
at CatchSubscriber.eval [as selector] (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/@angular/router@7.0.1/bundles/router.umd.js:2501:33)
at CatchSubscriber.error (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/rxjs@6.3.3/internal/operators/catchError.js:48:31)
at MapSubscriber.Subscriber._error (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/rxjs@6.3.3/internal/Subscriber.js:93:26)
at MapSubscriber.Subscriber.error (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/rxjs@6.3.3/internal/Subscriber.js:73:18)
at MapSubscriber.Subscriber._error (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/rxjs@6.3.3/internal/Subscriber.js:93:26)
at MapSubscriber.Subscriber.error (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/rxjs@6.3.3/internal/Subscriber.js:73:18)
at MapSubscriber.Subscriber._error (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/rxjs@6.3.3/internal/Subscriber.js:93:26)
at MapSubscriber.Subscriber.error (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/rxjs@6.3.3/internal/Subscriber.js:73:18)
at TapSubscriber._error (https://outlet-routing-bug-shared-minimal.stackblitz.io/turbo_modules/rxjs@6.3.3/internal/operators/tap.js:75:26)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.1
Node: 8.11.1
OS: darwin x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.1
@angular-devkit/build-angular      0.12.1
@angular-devkit/build-optimizer    0.12.1
@angular-devkit/build-webpack      0.12.1
@angular-devkit/core               7.2.1
@angular-devkit/schematics         7.2.1
@angular/cdk                       7.2.1
@angular/cli                       7.2.1
@angular/flex-layout               7.0.0-beta.21
@angular/material                  7.2.1
@angular/material-moment-adapter   7.2.1
@ngtools/webpack                   7.2.1
@schematics/angular                7.2.1
@schematics/update                 0.12.1
rxjs                               6.3.3
typescript                         3.2.2
webpack                            4.23.1
</code></pre>

Also occurs with Angular 6

**Anything else relevant?**
N/A

**Comment by trotyl** [comment]
@jasonaden Sorry for the late reply, I'm a little busy recently. I have hardly dig into outlet issues as they were usually quite complicate, hard to tell whether it's an existing issue. 😿

**Comment by atscott** [comment]
Closing. Given the configuration, this is expected behavior. `1/other` matches the `':id/other'` route but cannot match the outlet. In addition, there's no match for `'other'` in the `children` with  the outlet. The URL is correct and there is no config which matches.
