### ISSUE TITLE
ivy: ngcc does not compile material module

### ISSUE THREAD

**Issue by thesayyn** [angular/angular#28254]
# 🐞 bug report

### Affected Package
@angular/compiler
@angular/material

### Is this a regression?
No

### Description
Ngcc fails when trying to compile @angular/material package 

I'm thinking that ngcc ignores and removes the @angular/material/progress-bar entrypoint and then trying to resolve it so ngcc fails when could not find it.

Fails at this line: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/ngcc/src/packages/dependency_resolver.ts#L102

## 🔥 Exception or Error
<pre><code>
$ '/Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/.bin/ivy-ngcc'
Failed to read entry point info from /Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/@schematics/angular/workspace/files/package.json with error SyntaxError: Unexpected token < in JSON at position 1121.
Error: Node does not exist: /Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/@angular/material/progress-bar
    at DepGraph.addDependency (/Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/dependency-graph/lib/dep_graph.js:120:13)
    at /Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/@angular/compiler-cli/src/ngcc/src/packages/dependency_resolver.js:61:35
    at Set.forEach (<anonymous>)
    at /Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/@angular/compiler-cli/src/ngcc/src/packages/dependency_resolver.js:57:34
    at Array.forEach (<anonymous>)
    at DependencyResolver.sortEntryPointsByDependency (/Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/@angular/compiler-cli/src/ngcc/src/packages/dependency_resolver.js:42:25)
    at EntryPointFinder.findEntryPoints (/Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/@angular/compiler-cli/src/ngcc/src/packages/entry_point_finder.js:33:34)
    at Object.mainNgcc (/Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/@angular/compiler-cli/src/ngcc/src/main.js:55:38)
    at /Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/@angular/compiler-cli/src/ngcc/main-ngcc.js:17:35
    at /Users/thesayyn/Documents/angular projects/tdadmin-server/dist/composer58a6b/node_modules/@angular/compiler-cli/src/ngcc/main-ngcc.js:4:17
</code></pre>

**Comment by ericmartinezr** [comment]
It sounds like it's a dup of https://github.com/angular/angular/issues/27950, but they said it was already fixed. Would you mind checking?

**Comment by thesayyn** [comment]
I will check it :) Thanks

**Comment by mhevery** [comment]
Thanks for filing the issue, but `ngcc` is still under active development and is not ready for us to support it publicly just yet. I am going to close this issue as to de-cluttered our list.
