### ISSUE TITLE
Cannot set property 'onRemovalComplete' of undefined

### ISSUE THREAD

**Issue by sxlwar** [angular/angular#28258]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/platform-browser/animations/src/animation_renderer.ts

### Is this a regression?

I'm not sure. But it works well at before.

### Description

My project use server side rending, this error happened during server connecting.

I have noticed that the code at animation_renderer.ts:26:29 need a dependance named engine which imported from ‘@angular/animations/browser/src/render/animation_engine_next.ts’.

```ts
export class AnimationEngine {
  ...
  // this method is designed to be overridden by the code that uses this engine
  public onRemovalComplete = (element: any, context: any) => {};
  ...
```
It seems like that the class is not injectable, but it works well at client side or without ssr.

## 🔥 Exception or Error

```bash
ERROR TypeError: Cannot set property 'onRemovalComplete' of undefined
    at new AnimationRendererFactory (/Users/shaoxuelei/packages/platform-browser/animations/src/animation_renderer.ts:26:29)
    at instantiateRendererFactory (/Users/shaoxuelei/packages/platform-browser/animations/src/providers.ts:36:10)
    at _callFactory (/Users/shaoxuelei/ratel/packages/core/src/view/ng_module.ts:194:14)
    at _createProviderInstance (/Users/shaoxuelei/ratel/packages/core/src/view/ng_module.ts:147:20)
    at resolveNgModuleDep (/Users/shaoxuelei/ratel/packages/core/src/view/ng_module.ts:106:13)
    at _createClass (/Users/shaoxuelei/ratel/packages/core/src/view/ng_module.ts:180:11)
    at _createProviderInstance (/Users/shaoxuelei/ratel/packages/core/src/view/ng_module.ts:144:20)
    at resolveNgModuleDep (/Users/shaoxuelei/ratel/packages/core/src/view/ng_module.ts:106:13)
    at _callFactory (/Users/shaoxuelei/ratel/packages/core/src/view/ng_module.ts:201:50)
    at _createProviderInstance (/Users/shaoxuelei/ratel/packages/core/src/view/ng_module.ts:147:20)
Unhandled Promise rejection: Cannot set property 'onRemovalComplete' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'onRemovalComplete' of undefined
....
```

## 🌍   Environment

**Angular Version:** 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.11.1 (cli-only)
@angular-devkit/core         7.1.1 (cli-only)
@angular-devkit/schematics   7.1.1 (cli-only)
@angular/flex-layout         7.0.0-beta.23
@schematics/angular          7.1.1 (cli-only)
@schematics/update           0.11.1 (cli-only)
rxjs                         6.3.3
typescript                   3.2.4
webpack                      4.28.4

**System Version:**
macOS Mojave 10.14.2

**node env**
node: v8.9.4
npm: 6.4.1

**Anything else relevant**

Server side repo: [here](https://github.com/sxlwar/honey-badger)

Client side repo: [here](https://github.com/sxlwar/ratel)

**Comment by andremoniz** [comment]
+1

**Comment by rossanmol** [comment]
This is causing issues on SSR for my project.

**Comment by samvloeberghs** [comment]
Current solution for me was downgrading @angular/platform-browser to 7.1.4

**Comment by JeanMeche** [comment]
I'll close this issue as not relevant anymore. A lot has changed on the SSR side since this issue has been opened.
