### ISSUE TITLE
Angular Websites with service worker breaking in Opera

### ISSUE THREAD

**Issue by shabbir-dhangot** [angular/angular#28612]
# 🐞 bug report

### Affected Package
Angular Websites with service worker not working in opera browser. Its loading first time normally. Reloading page is showing website is Down.

![screenshot from 2019-02-08 09-32-28](https://user-images.githubusercontent.com/8267282/52458336-d4f4c800-2b84-11e9-8d3b-f41f57cef79d.png)

### Is this a regression?

 Not sure.

### Description

 Loading website first time normally. Reloading page showing website is down.
![screenshot from 2019-02-08 09-37-11](https://user-images.githubusercontent.com/8267282/52458398-24d38f00-2b85-11e9-9f1f-ad6a03e54de3.png)

## 🔬 Minimal Reproduction

 First I discovered with my website then I tried other website. Found its happening on angular.io website as well. 

## 🔥 Exception or Error
<pre><code>
09:33:13.399 ngsw-worker.js:2118 Uncaught (in promise) DOMException: Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.
    at Driver.<anonymous> (https://angular.io/ngsw-worker.js:2118:23)
    at Generator.next (<anonymous>)
    at fulfilled (https://angular.io/ngsw-worker.js:1772:62)
    at <anonymous>
(anonymous) @ ngsw-worker.js:2118
fulfilled @ ngsw-worker.js:1772
09:33:13.400 angular.io/:1 GET https://angular.io/ net::ERR_FAILED
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
angular.io --> 7.0.0
greatbuyz.com --> 6.1.7

</code></pre>

**Anything else relevant?**
Its browser specific issue.
Opera : 46.0
OS : ubuntu 16.04

Tested on opera 51 its working fine.

**Comment by shabbir-dhangot** [comment]
Closing as duplicate #20756
