### ISSUE TITLE
Build task cleanup.builder errors with TypeError: Cannot read property 'cleanup' of null

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#2866]
> TypeError: Cannot read property 'cleanup' of null
    at DiffingPluginWrapper.cleanup (/home/travis/build/angular/angular/broccoli/diffing-broccoli-plugin.ts:127:27)
    at NewStyleTreeWrapper.cleanup (/home/travis/build/angular/angular/node_modules/broccoli/lib/api_compat.js:62:30)
    at cleanupTree (/home/travis/build/angular/angular/node_modules/broccoli/lib/builder.js:128:19)
    at /home/travis/build/angular/angular/node_modules/broccoli/node_modules/promise-map-series/index.js:11:14

See: https://travis-ci.org/angular/angular/jobs/69476023

I can see it quite often locally, lately.

**Comment by pkozlowski-opensource** [comment]
Another example of the same pb: https://travis-ci.org/angular/angular/jobs/72478993 

It seams that the cleanup task fails to cleanup properly when DiffingTSCompiler encounters a pb.

**Comment by mhevery** [comment]
This has not been updated for 21 days. Does not seem like a P1. Is this still an issue? If not can we close.

**Comment by pkozlowski-opensource** [comment]
I haven't seen it for a while so we can close. Will open a new issue if I see similar things again.
