### ISSUE TITLE
Change Detector throws TypeError on null object bindings

### ISSUE THREAD

**Issue by justindujardin** [angular/angular#2868]
I'm building a set of UI components that are eventually provided with data at some point after creation.  The change detector throws TypeErrors when it looks at these bindings.

Given the template:

    <div class="hero-card">
      <h1 class="name" [inner-text]="model.attributes.name"></h1>
      ...
    </div>

The below error is produced when `model` is not set to a valid value.

    TypeError: Cannot read property 'attributes' of undefined
    STACKTRACE:
    TypeError: Cannot read property 'attributes' of undefined
        at AbstractChangeDetector.ChangeDetector_PartyInventory_comp_0.detectChangesInRecords (eval at <anonymous> (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:9068:20), <anonymous>:202:28)
        at AbstractChangeDetector.execute.AbstractChangeDetector._detectChanges (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:18944:18)
        at AbstractChangeDetector.execute.AbstractChangeDetector._detectChangesInShadowDomChildren (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:18965:20)
        at AbstractChangeDetector.execute.AbstractChangeDetector._detectChanges (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:18948:18)
        at AbstractChangeDetector.execute.AbstractChangeDetector._detectChangesInShadowDomChildren (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:18965:20)
        at AbstractChangeDetector.execute.AbstractChangeDetector._detectChanges (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:18948:18)
        at AbstractChangeDetector.execute.AbstractChangeDetector.detectChanges (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:18936:18)
        at execute.LifeCycle.tick (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:13242:34)
        at execute.LifeCycle.registerWith.zone.initCallbacks.onTurnDone (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:13232:27)
        at Zone.run (https://code.angularjs.org/2.0.0-alpha.28/angular2.dev.js:115:17)

I would expect that my bindings would not need to be aware of null reference errors, as in Angular 1.x.  Is this the desired behavior?

Example Plunkr is here: http://embed.plnkr.co/WuQE8U/preview

**Comment by wesleycho** [comment]
I'm getting this error from your Plunker:
```
Can't bind to 'ngFor' since it isn't a know property of the 'template' element and there are no matching directives with a corresponding property
```
I think [this](http://plnkr.co/edit/OggyMiBnv20kxoZZJzdd?p=preview) is a more accurate reproduction of the issue.

**Comment by justindujardin** [comment]
@wesleycho I updated the link, thanks.

**Comment by gdi2290** [comment]
Try `model?.attributes?.name`

**Comment by justindujardin** [comment]
@gdi2290 That appears to fix the immediate issue, but is it just a workaround?

**Comment by gdi2290** [comment]
@justindujardin this is called the elvis operator which is equivalent-ish to
`(model) ? model && model.attributes && model.attributes.name : null` 
in Angular 2 everything is more explicit, by design, to ensure predictability of the framework. I'm assuming `model` and or `model` properties are defined at a later time since it's async

**Comment by wesleycho** [comment]
You mean `(model && model.attributes && model.attributes.name) ? model.attributes.name : null` :P

**Comment by justindujardin** [comment]
I'm just trying to make sure I understand what Angular2 requires.  

Marking up my templates with ? creates more work upgrading from 1.x, and might make the templates a bit less readable, so I want to make sure it is "as designed".

**Comment by wesleycho** [comment]
Readability is fine there IMO - it is a little more verbose, mainly because it seems Angular does not swallow the exception as it would in Angular 1 by safely checking in A1 first. There is a minor performance gain by doing so, but a little more developer inconvenience.

**Comment by justindujardin** [comment]
I understand, and appreciate better performing bindings.  My issue is resolved.

**Comment by gdi2290** [comment]
you only need one elvis operator `model?.attributes.name` unless `.name` is also async defined. In angular one you should be defining default values for everything in the template.
