### ISSUE TITLE
Usage of enums in templates not possible?

### ISSUE THREAD

**Issue by jomeier** [angular/angular#2885]
Hi,

I tried to use a typescript enum for an array index in a template to create data binding for an HTML attribute in this way:

```
enum enu{
  ana,
  bana,
  cana
}
...
@View({ 
...
  template: '<input type="text" class="form-control", [value]="measVal[enu.ana]">'      
...
```

It compiles ok with Typescript 1.5 but I get an error message in the browser:

```
TypeError: Cannot read property 'ana' of undefined
STACKTRACE:
TypeError: Cannot read property 'sigImgIdx' of undefined
    at AbstractChangeDetector.ChangeDetector_myAvdaMeas_comp_0.detectChangesInRecords (eval at <anonymous> (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:9068:20), <anonymous>:1007:29)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChanges (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:18944:18)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:18965:20)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChanges (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:18948:18)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:18965:20)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChanges (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:18948:18)
    at AbstractChangeDetector.execute.AbstractChangeDetector.detectChanges (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:18936:18)
    at execute.LifeCycle.tick (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:13242:34)
    at execute.LifeCycle.registerWith.zone.initCallbacks.onTurnDone (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:13232:27)
    at Zone.run (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.28.js:115:17)
```

Are enums not allowed in  templates or is this a bug?

Thanks

**Comment by martinmcwhorter** [comment]
As with Angular 1.x, you have to make the enum a property of your controller/component class. 

    class YourController {
    
        public yourEnum = YourEnum;
    
    . . . 
    }

**Comment by PascalPrecht** [comment]
Correct, as @martinmcwhorter states, your component class is basically your execution context in Angular 2 applications. All properties defined on your component can be interpolated in your component's template.

**Comment by pkozlowski-opensource** [comment]
@jomeier I hope that the above answers provided by @martinmcwhorter and @PascalPrecht (thnx guys!) is sorting out the pb for you. If not, please re-open the issue with a live reproduce scenario. Thnx!

**Comment by jomeier** [comment]
Thanks. That was the problem!

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/35750059/select-based-on-enum-in-angular2 or http://stackoverflow.com/questions/35835984/how-to-use-a-typescript-enum-value-in-an-angular2-ngswitch-statement

**Comment by BlackHawkDesign** [comment]
It doesn't feel really elegant to have a reference of that enum.. why isn't that imported enum not available?

**Comment by martinmcwhorter** [comment]
For one, a typescript enum is really a self referencing javascript literal.
It is a plain old javascript object.

Second, templates cannot access objects that are not exposed by a
controller or component.

This is quite different than how enums work in a language like C#.

There is a good reason for this that becomes apparent if you think about
how it has to work in vanilla JavaScript.

**Comment by canda** [comment]
This solution is not possible with const enums

**Comment by xmeng1** [comment]
:+1:

**Comment by Kunepro** [comment]
I'm sad now, thanks.
The idea of using non const enums because of the template issue really annoys me, and if I have to choose, I decide that I'm just going to ditch Enums in this case then. Sad day.
