### ISSUE TITLE
Exported sparse arrays cause internal errors in the Angular compiler

### ISSUE THREAD

**Issue by benlesh** [angular/angular#28912]
Repro: cl/212429712
Failing test: //cloud/signals/stackdriver/monitoring/frontend/modules/topology/components:tests_chrome-linux
Project: proto_dash.ui
TAP: https://test.corp.google.com/ui#t=//cloud/signals/stackdriver/monitoring/frontend/modules/topology/components:tests_chrome-linux&cl=212429712&flags=CAMQBQ==
Sponge: https://sponge.corp.google.com/target?id=680ad6df-5610-4ae9-8f5a-9df84e608528&target=//cloud/signals/stackdriver/monitoring/frontend/modules/topology/components:tests_chrome-linux
Stack trace:

```
          Error: Uncaught (in promise): TypeError: Cannot read property 'visitExpression' of undefined

TypeError: Cannot read property 'visitExpression' of undefined
    at http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:486:38 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:458:60
    at JitEmitterVisitor.AbstractEmitterVisitor.visitAllObjects (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:507:6 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:477:13)
    at JitEmitterVisitor.AbstractEmitterVisitor.visitAllExpressions (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:486:9 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:458:14)
    at JitEmitterVisitor.AbstractEmitterVisitor.visitLiteralArrayExpr (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:465:9 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:436:14)
    at LiteralArrayExpr.visitExpression (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/output_ast.ts:695:19 <- third_party/javascript/angular2/rc/packages/compiler/src/output/output_ast.js:662:24)
    at http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:473:18 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:445:25
    at JitEmitterVisitor.AbstractEmitterVisitor.visitAllObjects (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:507:6 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:477:13)
    at JitEmitterVisitor.AbstractEmitterVisitor.visitLiteralMapExpr (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:471:9 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:443:14)
    at LiteralMapExpr.visitExpression (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/output_ast.ts:723:19 <- third_party/javascript/angular2/rc/packages/compiler/src/output/output_ast.js:695:24)
    at http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:486:38 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:458:60
    at JitEmitterVisitor.AbstractEmitterVisitor.visitAllObjects (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:507:6 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:477:13)
    at JitEmitterVisitor.AbstractEmitterVisitor.visitAllExpressions (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:486:9 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:458:14)
    at JitEmitterVisitor.AbstractEmitterVisitor.visitInvokeFunctionExpr (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.ts:311:9 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_emitter.js:287:14)
    at JitEmitterVisitor.AbstractJsEmitterVisitor.visitInvokeFunctionExpr (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_js_emitter.ts:112:35 <- third_party/javascript/angular2/rc/packages/compiler/src/output/abstract_js_emitter.js:110:54)
    at InvokeFunctionExpr.visitExpression (http://concatjs../../../third_party/javascript/angular2/rc/packages/compiler/src/output/output_ast.ts:439:19 <- third_party/javascript/angular2/rc/packages/compiler/src/output/output_ast.js:408:24)
    at resolvePromise (http://concatjs../../../third_party/javascript/node_modules/zone_js/v0_8_16/lib/common/promise.ts:160:18 <- third_party/javascript/node_modules/zone_js/v0_8_16/lib/common/promise.js:174:31) [fakeAsyncTestZone for catalyst]
    at resolvePromise (http://concatjs../../../third_party/javascript/node_modules/zone_js/v0_8_16/lib/common/promise.ts:132:8 <- third_party/javascript/node_modules/zone_js/v0_8_16/lib/common/promise.js:145:17) [fakeAsyncTestZone for catalyst]
    at http://concatjs../../../third_party/javascript/node_modules/zone_js/v0_8_16/lib/common/promise.ts:211:8 <- third_party/javascript/node_modules/zone_js/v0_8_16/lib/common/promise.js:222:17 [fakeAsyncTestZone for catalyst]
    at FakeAsyncTestZoneSpec.fakeAsyncTestZoneSpec.onInvokeTask (http://concatjs../../../javascript/angular2/testing/catalyst/helpers.ts:412:36 <- javascript/angular2/testing/catalyst/helpers.js:352:43) [fakeAsyncTestZone for catalyst]
    at FakeAsyncTestZoneSpec.flushMicrotasks 

(http://concatjs../../../third_party/javascript/node_modules/zone_js/v0_8_16/lib/zone-spec/fake-async-test.ts:290:23 <- third_party/javascript/node_modules/zone_js/v0_8_16/lib/zone-spec/fake-async-test.js:269:32) [fakeAsyncTestZone for catalyst]
    at http://concatjs../../../javascript/angular2/testing/catalyst/helpers.ts:1045:39 <- javascript/angular2/testing/catalyst/helpers.js:926:80 [fakeAsyncTestZone for catalyst]
    at callInFakeAsyncZone (http://concatjs../../../javascript/angular2/testing/catalyst/helpers.ts:1023:11 <- javascript/angular2/testing/catalyst/helpers.js:907:16) [fakeAsyncTestZone for catalyst]
    at flushMicroTasks (http://concatjs../../../javascript/angular2/testing/catalyst/helpers.ts:1044:9 <- javascript/angular2/testing/catalyst/helpers.js:926:12) [fakeAsyncTestZone for catalyst]
    at compileComponents (http://concatjs../../../javascript/angular2/testing/catalyst/helpers.ts:632:4 <- javascript/angular2/testing/catalyst/helpers.js:550:9) [fakeAsyncTestZone for catalyst]
```

**Comment by alxhub** [comment]
This may not be a bug of ours, but rather an application passing a random array into metadata which does not belong there. Need to investigate further.

**Comment by alxhub** [comment]
Closing as obsolete - the repro data from TAP for example is long gone.
