### ISSUE TITLE
sporadic recompilation ends with ERROR in : TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by gozzoo** [angular/angular#29204]
### Versions

```
Angular CLI: 7.3.4
Node: 10.14.2
OS: win32 ia32
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.4
@angular/cli                      7.3.4
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
```

### Description

When running `ng serve` sometimes without explicit change in the code the project gets recompiled multiple times in a row. Sometimes this series end with an error:

```
ERROR in : TypeError: Cannot read property 'kind' of undefined
    at getAssignmentTargetKind (C:\work\tansys\node_modules\typescript\lib\typescript.js:10228:28)
    at Object.isAssignmentTarget (C:\work\tansys\node_modules\typescript\lib\typescript.js:10271:16)
    at checkObjectLiteral (C:\work\tansys\node_modules\typescript\lib\typescript.js:47313:45)
    at checkExpressionWorker (C:\work\tansys\node_modules\typescript\lib\typescript.js:51812:28)
    at checkExpression (C:\work\tansys\node_modules\typescript\lib\typescript.js:51757:42)
    at checkExpressionWithContextualType (C:\work\tansys\node_modules\typescript\lib\typescript.js:51587:26)
    at checkApplicableSignature (C:\work\tansys\node_modules\typescript\lib\typescript.js:48906:35)
    at chooseOverload (C:\work\tansys\node_modules\typescript\lib\typescript.js:49225:26)
    at resolveCall (C:\work\tansys\node_modules\typescript\lib\typescript.js:49177:26)
    at resolveCallExpression (C:\work\tansys\node_modules\typescript\lib\typescript.js:49484:20)
    at resolveSignature (C:\work\tansys\node_modules\typescript\lib\typescript.js:49772:28)
    at getResolvedSignature (C:\work\tansys\node_modules\typescript\lib\typescript.js:49804:26)
    at checkCallExpression (C:\work\tansys\node_modules\typescript\lib\typescript.js:49896:29)
    at checkExpressionWorker (C:\work\tansys\node_modules\typescript\lib\typescript.js:51823:28)
    at checkExpression (C:\work\tansys\node_modules\typescript\lib\typescript.js:51757:42)
    at resolveDecorator (C:\work\tansys\node_modules\typescript\lib\typescript.js:49691:28)
    at resolveSignature (C:\work\tansys\node_modules\typescript\lib\typescript.js:49778:28)
    at getResolvedSignature (C:\work\tansys\node_modules\typescript\lib\typescript.js:49804:26)
    at checkDecorator (C:\work\tansys\node_modules\typescript\lib\typescript.js:53129:29)
    at Object.forEach (C:\work\tansys\node_modules\typescript\lib\typescript.js:210:30)
    at checkDecorators (C:\work\tansys\node_modules\typescript\lib\typescript.js:53311:16)
    at checkClassLikeDeclaration (C:\work\tansys\node_modules\typescript\lib\typescript.js:54988:13)
    at checkClassDeclaration (C:\work\tansys\node_modules\typescript\lib\typescript.js:54982:13)
    at checkSourceElement (C:\work\tansys\node_modules\typescript\lib\typescript.js:56153:28)
    at Object.forEach (C:\work\tansys\node_modules\typescript\lib\typescript.js:210:30)
    at checkSourceFileWorker (C:\work\tansys\node_modules\typescript\lib\typescript.js:56317:20)
    at checkSourceFile (C:\work\tansys\node_modules\typescript\lib\typescript.js:56289:13)
    at Object.forEach (C:\work\tansys\node_modules\typescript\lib\typescript.js:210:30)
```

The process stops watching for new changes and no further reompilation is hapening. After I stop it and start it again the compilation completes with no errors and it keeps watching for changes, which trigger healthy recompilation.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gozzoo** [comment]
@ericmartinezr 'this is not a bug' is very different form 'this is a dup of ...'

Thanks for pointing out the duplicates, but all of them are closed now and no further investigation is likely to happen. There is an easy workaround for this (just press Ctrl+C and restart `ng serve`), but it gets frustrating when it keeps happening multple times a day.

**Comment by ericmartinezr** [comment]
@gozzoo then I suggest you to open the issue in the cli's repo 👍

**Comment by gozzoo** [comment]
I'm closing this issue here and moving it to angular-cli
