### ISSUE TITLE
How to make angular render server side?

### ISSUE THREAD

**Issue by chiraggmodi** [angular/angular#29229]
I want to render my app on server side.
I have follow this instruction https://angular.io/guide/universal
but I have stuck in issue. Here is the error what I am getting every time I fire this command
`npm run build:ssr && npm run serve:ssr`
I have done some research but not get any solution.
```

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 3654ec15e293c1198917
Version: webpack 4.29.6
Time: 137ms
Built at: 03/12/2019 12:33:27 AM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in Entry module not found: Error: Can't resolve 'production' in 'C:\Data\Angular\chiragmodi'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! chiragmodi@0.0.0 webpack:server: `webpack --config webpack.server.config.js --progress --colors "production"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the chiragmodi@0.0.0 webpack:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chirag Modi\AppData\Roaming\npm-cache\_logs\2019-03-11T19_03_27_166Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! chiragmodi@0.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run webpack:server --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the chiragmodi@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chirag Modi\AppData\Roaming\npm-cache\_logs\2019-03-11T19_03_27_227Z-debug.log
```

**Comment by brandonroberts** [comment]
@chiraggmodi the Server-Side Rendering guide has been updated with simplified instructions. Take another look and reopen this issue if needed https://angular.io/guide/universal

**Comment by chiraggmodi** [comment]
@brandonroberts i have follow this URL, and I even try with `ng new ` command and then run this tutorial 
then I got this error

```
Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.engine (C:\Data\Angular\chiragmodi\dist\server.js:39238:23)
    at View.render (C:\Data\Angular\chiragmodi\dist\server.js:123884:8)
    at tryRender (C:\Data\Angular\chiragmodi\dist\server.js:121592:10)
    at Function.render (C:\Data\Angular\chiragmodi\dist\server.js:121544:3)
    at ServerResponse.render (C:\Data\Angular\chiragmodi\dist\server.js:130425:7)
    at C:\Data\Angular\chiragmodi\dist\server.js:135:9
    at Layer.handle [as handle_request] (C:\Data\Angular\chiragmodi\dist\server.js:123312:5)
    at next (C:\Data\Angular\chiragmodi\dist\server.js:123060:13)
    at Route.dispatch (C:\Data\Angular\chiragmodi\dist\server.js:123035:3)
    at Layer.handle [as handle_request] (C:\Data\Angular\chiragmodi\dist\server.js:123312:5)
```
