### ISSUE TITLE
DI: Adding bindings to a viewInjector causes ElementRef to not be injectable?

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2936]
Ran into this today.

```dart
@Component(
  selector: 'foo',
  viewInjector: someBindings
)
@View(
  template: ''
)
class FooComponent {}
```

vs adding someBindings to bootstrap function.

The former gives me:

```
Exception: Uncaught Error: No provider for ElementRef! (FooComponent -> ElementRef)
Stack Trace:
#0      Injector._getByKey (package:angular2/src/di/injector.dart:718:7)
#1      Injector.get (package:angular2/src/di/injector.dart:472:17)
#2      Injector._getByKey (package:angular2/src/di/injector.dart:712:23)
#3      Injector._getByDependency (package:angular2/src/di/injector.dart:667:19)
#4      Injector._new (package:angular2/src/di/injector.dart:559:30)
#5      InjectorInlineStrategy.hydrate (package:angular2/src/di/injector.dart:204:13)
```

**Comment by matanlurey** [comment]
This might have been fixed. Assigned self to verify and close.

**Comment by matanlurey** [comment]
Verified.
