### ISSUE TITLE
Dart transformer doesn't add getters for formDirectives

### ISSUE THREAD

**Issue by andresaraujo** [angular/angular#2939]
If you add the transformer to an application that uses `formDirectives` it will result 
in the following error:

From NgModel
```
Exception: Uncaught Error: Cannot find getter update
Stack Trace:
#0      NoReflectionCapabilities.getter (package:angular2/src/reflection/reflection.dart:27:5)
#1      Reflector.getter (package:angular2/src/reflection/reflector.dart:74:42)
#2      _ParseAST.parseAccessMemberOrMethodCall (package:angular2/src/change_detection/parser/parser.dart:457:35)
```

From DefaultValueAccessor
```
Exception: Uncaught Error: Cannot find getter target
Stack Trace:
#0      NoReflectionCapabilities.getter (package:angular2/src/reflection/reflection.dart:27:5)
#1      Reflector.getter (package:angular2/src/reflection/reflector.dart:74:42)
#2      _ParseAST.parseAccessMemberOrMethodCall (package:angular2/src/change_detection/parser/parser.dart:457:35)
```

**Comment by jakemac53** [comment]
@andresaraujo can you add a simple repro program here for context?

**Comment by andresaraujo** [comment]
@jakemac53 On alpha 32 produces the following error:

```
Exception: Uncaught Error: Cannot find method onTouched
Stack Trace:
#0      NoReflectionCapabilities.method (package:angular2/src/reflection/reflection.dart:39:5)
#1      Reflector.method (package:angular2/src/reflection/reflector.dart:91:42)
#2      _ParseAST.parseAccessMemberOrMethodCall (package:angular2/src/change_detection/parser/parser.dart:452:31)
#3      _ParseAST.parsePrimary (package:angular2/src/change_detection/parser/parser.dart:406:19)
#4      _ParseAST.parseCallChain (package:angular2/src/change_detection/parser/parser.dart:354:23)
```

```dart
@Component(
  selector: "my-app"
)
@View(
  template: '''
  <h3>{{name}}</h3>
  <input type="text" [(ng-model)]="name">''',
  directives: const [formDirectives]
)
class App {
  String name;
}
```

**Comment by kegluneq** [comment]
Is this still an issue? It should have been fixed by https://github.com/angular/angular/pull/3203

**Comment by andresaraujo** [comment]
Yeah this is was already fixed. Thanks
