### ISSUE TITLE
DI: hostInjector/viewInjector do not support nested lists

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2954]
I assume, based on both the documentation and API, that the following should be legal:

```dart
class A {}
class B {}

const moduleA = const [
  A  
];

const moduleB = const [
  B
];

@Component(
  selector: 'test',
  hostInjector: const [moduleA, moduleB]
)
@View(
  template: ''
)
class TestComponentWithNestedDependencies {}
```

The following is thrown though:

```
Exception: Uncaught Error: type 'List' is not a subtype of type 'ResolvedBinding' of 'binding'.
```

```
Stack Trace:
#0      BindingWithVisibility.BindingWithVisibility (package:angular2/src/di/injector.dart:371:30)
#1      ProtoElementInjector._createBindingWithVisibility (package:angular2/src/core/compiler/element_injector.dart:378:16)
#2      ProtoElementInjector._createHostInjectorBindingWithVisibility.<anonymous closure>.<anonymous closure> (package:angular2/src/core/compiler/element_injector.dart:369:37)
#3      List.forEach (dart:core-patch/array.dart:77)
#4      ListWrapper.forEach (package:angular2/src/facade/collection.dart:118:10)
#5      ProtoElementInjector._createHostInjectorBindingWithVisibility.<anonymous closure> (package:angular2/src/core/compiler/element_injector.dart:368:19)
#6      List.forEach (dart:core-patch/growable_array.dart:234)
#7      ListWrapper.forEach (package:angular2/src/facade/collection.dart:118:10)
#8      ProtoElementInjector._createHostInjectorBindingWithVisibility (package:angular2/src/core/compiler/element_injector.dart:367:17)
#9      ProtoElementInjector.create (package:angular2/src/core/compiler/element_injector.dart:351:26)
#10     _createProtoElementInjector (package:angular2/src/core/compiler/proto_view_factory.dart:368:49)
#11     _createElementBinders (package:angular2/src/core/compiler/proto_view_factory.dart:332:32)
#12     _createAppProtoView (package:angular2/src/core/compiler/proto_view_factory.dart:260:3)
#13     ProtoViewFactory.createAppProtoViews.<anonymous closure> (package:angular2/src/core/compiler/proto_view_factory.dart:176:26)
#14     List.forEach (dart:core-patch/growable_array.dart:234)
#15     ListWrapper.forEach (package:angular2/src/facade/collection.dart:118:10)
#16     ProtoViewFactory.createAppProtoViews (package:angular2/src/core/compiler/proto_view_factory.dart:175:17)
```

This is also blocking proper use of deferred loading, since ideally you'd have a deferred loaded components declare some dependencies (services, etc).

@vsavkin, @yjbanov could you take a look?

**Comment by vsavkin** [comment]
@matanlurey I will take a look today.

**Comment by matanlurey** [comment]
I still a (different) error today:

```
Exception: Uncaught Error: Class 'List' has no instance getter 'key'.

NoSuchMethodError: method not found: 'key'
Receiver: _List len:0
Arguments: []
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      BindingWithVisibility.getKeyId (package:angular2/src/di/injector.dart:373:25)
#3      ProtoInjectorInlineStrategy.ProtoInjectorInlineStrategy (package:angular2/src/di/injector.dart:76:28)
#4      ProtoInjector.ProtoInjector (package:angular2/src/di/injector.dart:169:15)
#5      ProtoElementInjector.ProtoElementInjector (package:angular2/src/core/compiler/element_injector.dart:392:30)
#6      ProtoElementInjector.create (package:angular2/src/core/compiler/element_injector.dart:354:16)
#7      _createProtoElementInjector (package:angular2/src/core/compiler/proto_view_factory.dart:368:49)
#8      _createElementBinders (package:angular2/src/core/compiler/proto_view_factory.dart:332:32)
#9      _createAppProtoView (package:angular2/src/core/compiler/proto_view_factory.dart:260:3)
#10     ProtoViewFactory.createAppProtoViews.<anonymous closure> (package:angular2/src/core/compiler/proto_view_factory.dart:176:26)
```

**Comment by matanlurey** [comment]
Disregard previous, my bad :) Working great, thanks Victor!
