### ISSUE TITLE
`ng build` throws after `ng add @angular/bazel`

### ISSUE THREAD

**Issue by mgechev** [angular/angular#29573]
# 🐞 bug report

### Affected Package

`@angular/bazel`

### Is this a regression?

No

### Description

```
~/Projects/real-world-bazel master* ng add @angular/bazel --name app
~/Projects/real-world-bazel master* ng build
Could not run bazel. Please make sure that the "bazel" command is installed by running "npm install @bazel/bazel" or "yarn install @bazel/bazel".
Error: Could not run bazel. Please make sure that the "bazel" command is installed by running "npm install @bazel/bazel" or "yarn install @bazel/bazel".
    at Object.checkInstallation (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular/bazel/src/builders/bazel.js:63:23)
    at BazelBuilder.run (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular/bazel/src/builders/index.js:34:34)
    at MergeMapSubscriber.getBuilderDescription.pipe.operators_1.concatMap.builder [as project] (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/src/architect-legacy.js:142:415)
    at MergeMapSubscriber._tryNext (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TapSubscriber._next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/tap.js:65:26)
    at TapSubscriber.Subscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:145:22)
    at Subscriber._next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:145:22)
    at MapSubscriber._next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SafeSubscriber.__tryOrUnsub (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:145:22)
    at Subscriber._next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/mgechev/Projects/real-world-bazel/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
```

## 🔬 Minimal Reproduction

```
ng add @angular/bazel --name app
ng build
```

**Comment by alexeagle** [comment]
does it work to manually run `yarn install` after the `ng add`?

**Comment by mgechev** [comment]
Yes.

**Comment by gund** [comment]
The same error happens when I create a new workspace with angular cli and bazel schematics:
```$ ng new bzl-app --collection=@angular/bazel```

Then when running `ng serve` getting error:
`Could not run bazel. Please make sure that the "bazel" command is installed by running "npm install" or "yarn install".`

**Comment by kyliau** [comment]
> does it work to manually run `yarn install` after the `ng add`?

`ng add` should install node modules if it's being invoked independently (not part of `ng new`). I'll work on this.

> The same error happens when I create a new workspace with angular cli and bazel schematics:
> `$ ng new bzl-app --collection=@angular/bazel`
> 
> Then when running `ng serve` getting error:
> `Could not run bazel. Please make sure that the "bazel" command is installed by running "npm install" or "yarn install".`

@gund the error you saw seems to be different from the one filed in this issue. Does running yarn/npm install manually after `ng new` fix the error?

**Comment by gund** [comment]
Running `yarn/npm install` does not fix the error.

However if I run `bazel run src//devserver` the process starts but then I get the following error:
```
ERROR: C:/users/user/_bazel_user/jyxv5oxk/external/npm_bazel_typescript/internal/build_defs.bzl:17:1: file '@build_bazel_rules_nodejs//internal/common:node_module_info.bzl' does not contain symbol 'NodeModuleSources'
ERROR: C:/users/user/_bazel_user/jyxv5oxk/external/npm_bazel_typescript/internal/build_defs.bzl:388:39: Traceback (most recent call last):
        File "C:/users/user/_bazel_user/jyxv5oxk/external/npm_bazel_typescript/internal/build_defs.bzl", line 265
                rule(_ts_library_impl, attrs = dict(COM...")}), <2 more arguments>)
        File "C:/users/user/_bazel_user/jyxv5oxk/external/npm_bazel_typescript/internal/build_defs.bzl", line 267, in rule
                dict(COMMON_ATTRIBUTES, **{"srcs": attr...")})
        File "C:/users/user/_bazel_user/jyxv5oxk/external/npm_bazel_typescript/internal/build_defs.bzl", line 387, in dict
                attr.label_list(aspects = (DEPS_ASPECTS + [colle...]), ...")
        File "C:/users/user/_bazel_user/jyxv5oxk/external/npm_bazel_typescript/internal/build_defs.bzl", line 388, in attr.label_list
                collect_node_modules_aspect
global variable 'collect_node_modules_aspect' is referenced before assignment.
```

And same error if I run `bazel build //src:bundle`...

**Comment by kyliau** [comment]
@gund It looks like you ran into the same issue as https://github.com/angular/angular-cli/issues/14082.
It will be fixed in angular v8 beta 12, which has not been released. I'll update https://github.com/angular/angular-cli/issues/14082 when v8 beta 12 is out.

Going forward, this issue will be used to track node modules installation after `ng add`.

**Comment by kyliau** [comment]
Unfortunately, the fix didn't make the beta 12 release. It'll be in beta 13.

**Comment by kyliau** [comment]
beta 13 has been released.
