### ISSUE TITLE
Bazel: error for missing dep on @angular/core is a stack trace

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#29672]
If you forget to include `@npm//@angular/core` in your deps, you get a big stack trace from ngc:

```
Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c0aaa094e7be03dbabccfd0d5d7e8a8/execroot/angular_bazel_example/bazel-out/host/bin/external/npm/node_modules/@angular/bazel/ngc-wrapped__bin.runfiles/npm/node_modules/@angular/compiler/bundles/compiler.umd.js:23786:34)
    at StaticReflector.findDeclaration (/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c0aaa094e7be03dbabccfd0d5d7e8a8/execroot/angular_bazel_example/bazel-out/host/bin/external/npm/node_modules/@angular/bazel/ngc-wrapped__bin.runfiles/npm/node_modules/@angular/compiler/bundles/compiler.umd.js:25172:67)
    at StaticReflector.initializeConversionMap (/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c0aaa094e7be03dbabccfd0d5d7e8a8/execroot/angular_bazel_example/bazel-out/host/bin/external/npm/node_modules/@angular/bazel/ngc-wrapped__bin.runfiles/npm/node_modules/@angular/compiler/bundles/compiler.umd.js:25409:55)
    at new StaticReflector (/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c0aaa094e7be03dbabccfd0d5d7e8a8/execroot/angular_bazel_example/bazel-out/host/bin/external/npm/node_modules/@angular/bazel/ngc-wrapped__bin.runfiles/npm/node_modules/@angular/compiler/bundles/compiler.umd.js:25140:18)
```

But if you're missing something like `@angular/router` the error is a bit better:
```
ERROR: /usr/local/google/home/alexeagle/Projects/angular-bazel-example/src/app/home/BUILD.bazel:5:1: Compiling Angular templates (ngc) //src/app/home:home failed (Exit 1)
src/app/home/home.ts(2,28): error TS2307: Cannot find module '@angular/router'.
```

however in all these cases, under Bazel we should mention "maybe you meant to add @angular/package to deps of //path/to:target"

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
