### ISSUE TITLE
NoBindingError thrown after upgrading to Alpha 30 from 28.

### ISSUE THREAD

**Issue by thekhoi** [angular/angular#3005]
Todo example is throwing a NoBindingError from the Injector.execute.Injector._getByKey method when upgrading from to Alpha 30.

Error: null
    at NoBindingError.BaseException (http://localhost:8080/vendor/angular2.dev.js:7254:25)
    at NoBindingError.AbstractBindingError (http://localhost:8080/vendor/angular2.dev.js:10818:66)
    at new NoBindingError (http://localhost:8080/vendor/angular2.dev.js:10836:60)
    at Injector.execute.Injector._getByKey (http://localhost:8080/vendor/angular2.dev.js:26215:21)
    at Injector.execute.Injector._getByDependency (http://localhost:8080/vendor/angular2.dev.js:26173:27)
    at Injector.execute.Injector._new (http://localhost:8080/vendor/angular2.dev.js:26071:68)
    at InjectorInlineStrategy.execute.InjectorInlineStrategy.hydrate (http://localhost:8080/vendor/angular2.dev.js:25812:31)
    at ElementInjector.execute.ElementInjector._reattachInjector (http://localhost:8080/vendor/angular2.dev.js:27275:39)
    at ElementInjector.execute.ElementInjector._hydrateInjector (http://localhost:8080/vendor/angular2.dev.js:27261:20)
    at ElementInjector.execute.ElementInjector.hydrate (http://localhost:8080/vendor/angular2.dev.js:27248:18)

**Comment by thekhoi** [comment]
unable to reproduce after clearing cache
