### ISSUE TITLE
Empty binding attribute in template gives EmptyExpr compiler error

### ISSUE THREAD

**Issue by jponeill** [angular/angular#30076]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler-cli/ngtsc

### Description

Compiling an IVY project that has an empty binding attribute in a component template gives the following error: 

ERROR in : Error: Unknown node type: function EmptyExpr() {
            return _super !== null && _super.apply(this, arguments) || this;
        }

## 🔬 Minimal Reproduction
Add an empty [myBindingAttrib] to any element in template and you get the compiler error in the trace below.

For example, adding the following to a component template:

`<div [innerHTML]> </div>`

 and executing:

`ng build --configuration production`

... gives the error in the trace below 

## 🔥 Exception or Error
<pre><code>

ERROR in : Error: Unknown node type: function EmptyExpr() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
    at astToTypescript (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:142:19)
    at Object.astToTypescript (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:54:20)
    at tcbExpression (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:755:29)
    at TcbUnclaimedInputsOp.execute (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:339:32)
    at Scope.executeOp (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:622:26)
    at Scope.render (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:561:22)
    at Object.generateTypeCheckBlock (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:43:37)
    at TypeCheckFile.addTypeCheckBlock (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_file.js:47:41)
    at TypeCheckContext.addTemplate (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/context.js:98:36)
    at ComponentDecoratorHandler.typeCheck (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:311:21)
    at /Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:328:43
    at Map.forEach (<anonymous>)
    at IvyCompilation.typeCheck (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:321:29)
    at NgtscProgram.getTemplateDiagnostics (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/program.js:362:25)
    at NgtscProgram.getNgSemanticDiagnostics (/Users/jimoneill/WebstormProjects/x/node_modules/@angular/compiler-cli/src/ngtsc/program.js:164:78)
    at checkDiagnostics (/Users/jimoneill/WebstormProjects/x/node_modules/@ngtools/webpack/src/gather_diagnostics.js:38:27)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.0-beta.17
Node: 10.12.0
OS: darwin x64
Angular: 8.0.0-beta.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.17
@angular-devkit/build-angular     0.800.0-beta.17
@angular-devkit/build-optimizer   0.800.0-beta.17
@angular-devkit/build-webpack     0.800.0-beta.17
@angular-devkit/core              8.0.0-beta.17
@angular-devkit/schematics        8.0.0-beta.17
@angular/cli                      8.0.0-beta.17
@angular/events                   <error>
@ngtools/webpack                  8.0.0-beta.17
@schematics/angular               8.0.0-beta.17
@schematics/update                0.800.0-beta.17
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
  
</code></pre>

**Anything else relevant?**
Maybe handle like PR #30024 (w/ a warning?)? Or give a an error with more detail.

**Comment by speige** [comment]
+1

**Comment by yonexbat** [comment]
How do I know which template file generates this error? Would be nice if it is printed along the exception.
