### ISSUE TITLE
Angular Universal server side rendering issue with loadchildren as method

### ISSUE THREAD

**Issue by wilzad** [angular/angular#30078]
# 🐞 bug report

### Affected Package

Can't pin point to a package

### Is this a regression?

I hav't had any experiance with previous versions

### Description
I have an application that lazy loads the modules based on some conditions (like mobile / desktop), it works fine with angular on client side, but when i add angular universal, i am getting error in the terminal even if it loads from the client side fine. the error is given in the below section ( i had to make it work for universal by disabling AOT and build optimizations),
 i can't use the string version of loadchildren in lazy loading since it depends on conditional loading. 

## 🔬 Minimal Reproduction

https://github.com/wilzad/AngularUniversalIssue

## 🔥 Exception or Error
<pre><code>

npm run serve:ssr

> universal@0.0.0 serve:ssr /home/vilsad/Projects/universal
> node dist/server

Node Express server listening on http://localhost:4000
ERROR { Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (/home/vilsad/Projects/universal/dist/server.js:131427:30)
    at Function.requireEnsure [as e] (/home/vilsad/Projects/universal/dist/server.js:131446:25)
    at /home/vilsad/Projects/universal/dist/server.js:131578:25
    at new ZoneAwarePromise (/home/vilsad/Projects/universal/dist/server.js:1055:29)
    at ɵ0 (/home/vilsad/Projects/universal/dist/server.js:131577:31)
    at RouterConfigLoader.loadModuleFactory (/home/vilsad/Projects/universal/dist/server.js:135755:39)
    at RouterConfigLoader.load (/home/vilsad/Projects/universal/dist/server.js:135740:35)
    at MergeMapSubscriber.project (/home/vilsad/Projects/universal/dist/server.js:134743:47)
    at MergeMapSubscriber._tryNext (/home/vilsad/Projects/universal/dist/server.js:31861:27)
    at MergeMapSubscriber._next (/home/vilsad/Projects/universal/dist/server.js:31851:18)
    at resolvePromise (/home/vilsad/Projects/universal/dist/server.js:976:31)
    at resolvePromise (/home/vilsad/Projects/universal/dist/server.js:933:17)
    at /home/vilsad/Projects/universal/dist/server.js:1037:17
    at ZoneDelegate.invokeTask (/home/vilsad/Projects/universal/dist/server.js:568:31)
    at Object.onInvokeTask (/home/vilsad/Projects/universal/dist/server.js:20257:33)
    at ZoneDelegate.invokeTask (/home/vilsad/Projects/universal/dist/server.js:567:60)
    at Zone.runTask (/home/vilsad/Projects/universal/dist/server.js:340:47)
    at drainMicroTaskQueue (/home/vilsad/Projects/universal/dist/server.js:746:35)
    at ZoneTask.invokeTask (/home/vilsad/Projects/universal/dist/server.js:647:21)
    at Server.ZoneTask.invoke (/home/vilsad/Projects/universal/dist/server.js:632:48)
  rejection:
   TypeError: Cannot read property 'call' of undefined
       at __webpack_require__ (/home/vilsad/Projects/universal/dist/server.js:131427:30)
       at Function.requireEnsure [as e] (/home/vilsad/Projects/universal/dist/server.js:131446:25)
       at /home/vilsad/Projects/universal/dist/server.js:131578:25
       at new ZoneAwarePromise (/home/vilsad/Projects/universal/dist/server.js:1055:29)
       at ɵ0 (/home/vilsad/Projects/universal/dist/server.js:131577:31)
       at RouterConfigLoader.loadModuleFactory (/home/vilsad/Projects/universal/dist/server.js:135755:39)
       at RouterConfigLoader.load (/home/vilsad/Projects/universal/dist/server.js:135740:35)
       at MergeMapSubscriber.project (/home/vilsad/Projects/universal/dist/server.js:134743:47)
       at MergeMapSubscriber._tryNext (/home/vilsad/Projects/universal/dist/server.js:31861:27)
       at MergeMapSubscriber._next (/home/vilsad/Projects/universal/dist/server.js:31851:18),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      TypeError: Cannot read property 'call' of undefined
          at __webpack_require__ (/home/vilsad/Projects/universal/dist/server.js:131427:30)
          at Function.requireEnsure [as e] (/home/vilsad/Projects/universal/dist/server.js:131446:25)
          at /home/vilsad/Projects/universal/dist/server.js:131578:25
          at new ZoneAwarePromise (/home/vilsad/Projects/universal/dist/server.js:1055:29)
          at ɵ0 (/home/vilsad/Projects/universal/dist/server.js:131577:31)
          at RouterConfigLoader.loadModuleFactory (/home/vilsad/Projects/universal/dist/server.js:135755:39)
          at RouterConfigLoader.load (/home/vilsad/Projects/universal/dist/server.js:135740:35)
          at MergeMapSubscriber.project (/home/vilsad/Projects/universal/dist/server.js:134743:47)
          at MergeMapSubscriber._tryNext (/home/vilsad/Projects/universal/dist/server.js:31861:27)
          at MergeMapSubscriber._next (/home/vilsad/Projects/universal/dist/server.js:31851:18) },
  zone:
   Zone {
     _parent:
      Zone {
        _parent: null,
        _name: '<root>',
        _properties: {},
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _properties: { isAngularZone: true },
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _parent: [Zone],
        _name: 'angular',
        _properties: [Object],
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         TypeError: Cannot read property 'call' of undefined
             at __webpack_require__ (/home/vilsad/Projects/universal/dist/server.js:131427:30)
             at Function.requireEnsure [as e] (/home/vilsad/Projects/universal/dist/server.js:131446:25)
             at /home/vilsad/Projects/universal/dist/server.js:131578:25
             at new ZoneAwarePromise (/home/vilsad/Projects/universal/dist/server.js:1055:29)
             at ɵ0 (/home/vilsad/Projects/universal/dist/server.js:131577:31)
             at RouterConfigLoader.loadModuleFactory (/home/vilsad/Projects/universal/dist/server.js:135755:39)
             at RouterConfigLoader.load (/home/vilsad/Projects/universal/dist/server.js:135740:35)
             at MergeMapSubscriber.project (/home/vilsad/Projects/universal/dist/server.js:134743:47)
             at MergeMapSubscriber._tryNext (/home/vilsad/Projects/universal/dist/server.js:31861:27)
             at MergeMapSubscriber._next (/home/vilsad/Projects/universal/dist/server.js:31851:18) },
     scheduleFn: undefined,
     cancelFn: undefined,
     callback: [Function],
     invoke: [Function] } }
ERROR { Error: Uncaught (in promise): TypeError: __webpack_require__(...) is not a function
TypeError: __webpack_require__(...) is not a function
    at Function.requireEnsure [as e] (/home/vilsad/Projects/universal/dist/server.js:131446:49)
    at /home/vilsad/Projects/universal/dist/server.js:131578:25
    at new ZoneAwarePromise (/home/vilsad/Projects/universal/dist/server.js:1055:29)
    at ɵ0 (/home/vilsad/Projects/universal/dist/server.js:131577:31)
    at RouterConfigLoader.loadModuleFactory (/home/vilsad/Projects/universal/dist/server.js:135755:39)
    at RouterConfigLoader.load (/home/vilsad/Projects/universal/dist/server.js:135740:35)
    at MergeMapSubscriber.project (/home/vilsad/Projects/universal/dist/server.js:134743:47)
    at MergeMapSubscriber._tryNext (/home/vilsad/Projects/universal/dist/server.js:31861:27)
    at MergeMapSubscriber._next (/home/vilsad/Projects/universal/dist/server.js:31851:18)
    at MergeMapSubscriber.Subscriber.next (/home/vilsad/Projects/universal/dist/server.js:28118:18)
    at resolvePromise (/home/vilsad/Projects/universal/dist/server.js:976:31)
    at resolvePromise (/home/vilsad/Projects/universal/dist/server.js:933:17)
    at /home/vilsad/Projects/universal/dist/server.js:1037:17
    at ZoneDelegate.invokeTask (/home/vilsad/Projects/universal/dist/server.js:568:31)
    at Object.onInvokeTask (/home/vilsad/Projects/universal/dist/server.js:20257:33)
    at ZoneDelegate.invokeTask (/home/vilsad/Projects/universal/dist/server.js:567:60)
    at Zone.runTask (/home/vilsad/Projects/universal/dist/server.js:340:47)
    at drainMicroTaskQueue (/home/vilsad/Projects/universal/dist/server.js:746:35)
    at ZoneTask.invokeTask (/home/vilsad/Projects/universal/dist/server.js:647:21)
    at Server.ZoneTask.invoke (/home/vilsad/Projects/universal/dist/server.js:632:48)
  rejection:
   TypeError: __webpack_require__(...) is not a function
       at Function.requireEnsure [as e] (/home/vilsad/Projects/universal/dist/server.js:131446:49)
       at /home/vilsad/Projects/universal/dist/server.js:131578:25
       at new ZoneAwarePromise (/home/vilsad/Projects/universal/dist/server.js:1055:29)
       at ɵ0 (/home/vilsad/Projects/universal/dist/server.js:131577:31)
       at RouterConfigLoader.loadModuleFactory (/home/vilsad/Projects/universal/dist/server.js:135755:39)
       at RouterConfigLoader.load (/home/vilsad/Projects/universal/dist/server.js:135740:35)
       at MergeMapSubscriber.project (/home/vilsad/Projects/universal/dist/server.js:134743:47)
       at MergeMapSubscriber._tryNext (/home/vilsad/Projects/universal/dist/server.js:31861:27)
       at MergeMapSubscriber._next (/home/vilsad/Projects/universal/dist/server.js:31851:18)
       at MergeMapSubscriber.Subscriber.next (/home/vilsad/Projects/universal/dist/server.js:28118:18),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      TypeError: __webpack_require__(...) is not a function
          at Function.requireEnsure [as e] (/home/vilsad/Projects/universal/dist/server.js:131446:49)
          at /home/vilsad/Projects/universal/dist/server.js:131578:25
          at new ZoneAwarePromise (/home/vilsad/Projects/universal/dist/server.js:1055:29)
          at ɵ0 (/home/vilsad/Projects/universal/dist/server.js:131577:31)
          at RouterConfigLoader.loadModuleFactory (/home/vilsad/Projects/universal/dist/server.js:135755:39)
          at RouterConfigLoader.load (/home/vilsad/Projects/universal/dist/server.js:135740:35)
          at MergeMapSubscriber.project (/home/vilsad/Projects/universal/dist/server.js:134743:47)
          at MergeMapSubscriber._tryNext (/home/vilsad/Projects/universal/dist/server.js:31861:27)
          at MergeMapSubscriber._next (/home/vilsad/Projects/universal/dist/server.js:31851:18)
          at MergeMapSubscriber.Subscriber.next (/home/vilsad/Projects/universal/dist/server.js:28118:18) },
  zone:
   Zone {
     _parent:
      Zone {
        _parent: null,
        _name: '<root>',
        _properties: {},
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _properties: { isAngularZone: true },
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _parent: [Zone],
        _name: 'angular',
        _properties: [Object],
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         TypeError: __webpack_require__(...) is not a function
             at Function.requireEnsure [as e] (/home/vilsad/Projects/universal/dist/server.js:131446:49)
             at /home/vilsad/Projects/universal/dist/server.js:131578:25
             at new ZoneAwarePromise (/home/vilsad/Projects/universal/dist/server.js:1055:29)
             at ɵ0 (/home/vilsad/Projects/universal/dist/server.js:131577:31)
             at RouterConfigLoader.loadModuleFactory (/home/vilsad/Projects/universal/dist/server.js:135755:39)
             at RouterConfigLoader.load (/home/vilsad/Projects/universal/dist/server.js:135740:35)
             at MergeMapSubscriber.project (/home/vilsad/Projects/universal/dist/server.js:134743:47)
             at MergeMapSubscriber._tryNext (/home/vilsad/Projects/universal/dist/server.js:31861:27)
             at MergeMapSubscriber._next (/home/vilsad/Projects/universal/dist/server.js:31851:18)
             at MergeMapSubscriber.Subscriber.next (/home/vilsad/Projects/universal/dist/server.js:28118:18) },
     scheduleFn: undefined,
     cancelFn: undefined,
     callback: [Function],
     invoke: [Function] } }
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.8
Node: 11.5.0
OS: linux x64
Angular: 7.2.13
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
    
</code></pre>

**Anything else relevant?**

IDE VSCode
Package Manager NPM

**Comment by wilzad** [comment]
@alxhub Please let me know if you need any clarifications,

**Comment by tlaverdure** [comment]
Experiencing the same issue. I'm also noticing that SSR doesn't even allow the site to load when the `RouterModule` uses the option `initialNavigation: 'enabled'`.

**Comment by tlaverdure** [comment]
@AndrewKushnir in route definitions is `loadChildren: () => import('lazy.module').then(m => m.LazyModule)` not supported in angular universal yet? Need to decide if I need to revert these changes. Thanks

**Comment by wilzad** [comment]
Hi,
This works fine in angular 8

**Comment by yah0130** [comment]
hi wilzad，
this is not works fine in angular8 for me

**Comment by csbenjamin** [comment]
maybe this is related to https://github.com/angular/angular-cli/issues/14614

**Comment by CaerusKaru** [comment]
Closing as working as fixed in latest. If this is not the case, we can reopen.
