### ISSUE TITLE
Error while compiling "Expected an expression, but saw AST"

### ISSUE THREAD

**Issue by jagjeet1991** [angular/angular#30374]
Getting this following error while compiling ...

## 🔥 Exception or Error
<pre>ERROR in : Error: Expected an expression, but saw AST
    at ensureExpressionMode (E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:7182:19)
    at _AstToIrVisitor.visitImplicitReceiver (E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:7304:13)
    at ImplicitReceiver.visit (E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:6289:28)
    at convertActionBinding (E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:7095:49)
    at E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:22304:26
    at Array.forEach (<anonymous>)
    at ViewBuilder._createElementHandleEventFn (E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:22300:22)
    at nodes.(anonymous function) (E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:21898:27)
    at E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:22262:26
    at Array.map (<anonymous>)
    at ViewBuilder._createNodeExpressions (E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:22261:43)
    at ViewBuilder.build (E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:21733:27)
    at E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:21732:67
    at Array.forEach (<anonymous>)
    at ViewBuilder.build (E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:21732:27)
    at E:\xampp\htdocs\example\node_modules\@angular\compiler\bundles\compiler.umd.js:21732:67</pre>

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 7.3.9                                                 
Node: 10.15.0                                                      
OS: win32 x64                                                      
Angular: 7.2.15                                                    
... animations, common, compiler, compiler-cli, core, forms        
... language-service, platform-browser, platform-browser-dynamic   
... router                                                         
                                                                   
Package                           Version                          
-----------------------------------------------------------        
@angular-devkit/architect         0.13.9                           
@angular-devkit/build-angular     0.13.9                           
@angular-devkit/build-optimizer   0.13.9                           
@angular-devkit/build-webpack     0.13.9                           
@angular-devkit/core              7.3.9                            
@angular-devkit/schematics        7.3.9                            
@angular/cli                      7.3.9                            
@ngtools/webpack                  7.3.9                            
@schematics/angular               7.3.9                            
@schematics/update                0.13.9                           
rxjs                              6.3.3                            
typescript                        3.2.4                            
webpack                           4.29.0                           </pre>

**Anything else relevant?**

**Comment by trotyl** [comment]
Please provide a minimal reproduction via https://stackblitz.com/

**Comment by jagjeet1991** [comment]
I first time use the angular and it is whole project when trying to compiling. it show compiled successfully and when trying to load on browser it give error in console "Error: Expected an expression, but saw AST" and load stopped

**Comment by trotyl** [comment]
The issue channel is [not designed for support questions](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question). If you believe this is an Angular bug, please provide a reproduction that allowing others to investigate.
