### ISSUE TITLE
"Template cache was not found" flake in test_ivy_aot

### ISSUE THREAD

**Issue by kara** [angular/angular#30499]
I've been seeing this one throughout the day:

```ts
Failed: CachedResourceLoader: Template cache was not found in $templateCache.
	Error: CachedResourceLoader: Template cache was not found in $templateCache.
	    at new CachedResourceLoader (packages/platform-browser-dynamic/src/resource_loader/resource_loader_cache.ts:28:12 <- angular/packages/platform-browser-dynamic/src/resource_loader/resource_loader_cache.js:37:23)
	    at UserContext.eval (packages/platform-browser-dynamic/test/resource_loader/resource_loader_cache_spec.ts:50:26 <- angular/packages/platform-browser-dynamic/test/resource_loader/resource_loader_cache_spec.js:55:34)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
	    at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:770:39)
```

Example job: https://circleci.com/gh/angular/angular/322236?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by gkalpak** [comment]
I am surprised this doesn't come up more often. The issue seems to be that `new CachedResourceLoader()` depends on the cache previously set with [setTemplateCache()][1], but [this test][2] does not set the cache, so if it happens to run right after [that test][3] (which clears the cache), then it throws.

I'll send a PR.

[1]: https://github.com/angular/angular/blob/79903b184248a57d7e9e10d69c94098f4fe34fa6/packages/platform-browser-dynamic/test/resource_loader/resource_loader_cache_setter.ts#L9-L11
[2]: https://github.com/angular/angular/blob/79903b184248a57d7e9e10d69c94098f4fe34fa6/packages/platform-browser-dynamic/test/resource_loader/resource_loader_cache_spec.ts#L50
[3]: https://github.com/angular/angular/blob/79903b184248a57d7e9e10d69c94098f4fe34fa6/packages/platform-browser-dynamic/test/resource_loader/resource_loader_cache_spec.ts#L37
