### ISSUE TITLE
Angular builders - more complex testing examples

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#30657]
# 📚 Docs or angular.io bug report

### Description

There is already a pretty good documentation in regards to [Angular CLI Builders](https://next.angular.io/guide/cli-builder), however, I get stuck right after trying something more complex than triggering a simple command.

I am extending the existing `@angular-devkit/build-ng-packagr` builder, so that certain logic is executed after the packagr builder is done. That all works fine, however I don't know how to test it correctly.

I tried to create a fake workspace, where I would run my builder, but obviously that fails due to absence of dependencies, like `@angular/core`.

I as well tried to look into official builder itself where I found that bunch of deprecated API is used, therefore did not proceed there.

### What's the affected URL?**
https://next.angular.io/guide/cli-builder

### Reproduction Steps**
- Clone https://github.com/klemenoslaj/cli-builders-demo
- Navigate to `command-builder`
- Execute `yarn test`

## 🔥 Exception or Error
```
Building Angular Package
Building entry point 'lib'
Compiling TypeScript sources through ngc

BUILD ERROR
Could not resolve module @angular/core
Error: Could not resolve module @angular/core
    at StaticSymbolResolver.getSymbolByModule (/Users/osk/Workspaces/experimental/packages/compiler/src/aot/static_symbol_resolver.ts:521:11)
    at StaticReflector.findDeclaration (/Users/osk/Workspaces/experimental/packages/compiler/src/aot/static_reflector.ts:111:29)
    at StaticReflector.initializeConversionMap (/Users/osk/Workspaces/experimental/packages/compiler/src/aot/static_reflector.ts:367:14)
    at new StaticReflector (/Users/osk/Workspaces/experimental/packages/compiler/src/aot/static_reflector.ts:69:10)
    at Object.createAotCompiler (/Users/osk/Workspaces/experimental/packages/compiler/src/aot/compiler_factory.ts:67:7)
    at AngularCompilerProgram._createCompiler (/Users/osk/Workspaces/packages/compiler-cli/src/transformers/program.ts:651:22)
    at AngularCompilerProgram.get [as hostAdapter] (/Users/osk/Workspaces/packages/compiler-cli/src/transformers/program.ts:531:12)
    at AngularCompilerProgram._createProgramWithBasicStubs (/Users/osk/Workspaces/packages/compiler-cli/src/transformers/program.ts:690:71)
    at /Users/osk/Workspaces/packages/compiler-cli/src/transformers/program.ts:240:17
```

</code></pre>

**Comment by kapunahelewong** [comment]
Status: docs team will need to work with engineering to create more complex examples ensuring that we explain the pertinent points.
