### ISSUE TITLE
"Expression form not supported" when using static "this" with ternary operator

### ISSUE THREAD

**Issue by cfinlinson** [angular/angular#30699]
# 🐞 bug report

### Affected Package

`@angular/compiler`
`@angular/compiler-cli`

### Is this a regression?

Not that I'm aware of.

### Description
Compilation fails when using `this` with the ternary operator in a static method.

## 🔬 Minimal Reproduction

GitHub Repo: https://github.com/cfinlinson/static-this-ternary-bug

Steps:
1. Clone the repo
2. `npm install`
3. `ng run test-lib:build`

## 🔥 Exception or Error
<pre><code>BUILD ERROR
C:/workspace/projects/cli-test/projects/test-lib/src/lib/test-lib.service.ts:3:1: Error encountered in metadata generated for exported symbol 'TestLibService':
 C:/workspace/projects/cli-test/projects/test-lib/src/lib/test-lib.service.ts:18:56: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":17,"character":55}
Error: C:/workspace/projects/cli-test/projects/test-lib/src/lib/test-lib.service.ts:3:1: Error encountered in metadata generated for exported symbol 'TestLibService':
 C:/workspace/projects/cli-test/projects/test-lib/src/lib/test-lib.service.ts:18:56: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":17,"character":55}
    at Object.getOwnPropertyNames.forEach.name (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\metadata\collector.js:648:31)
    at Array.forEach ()
    at validateMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\metadata\collector.js:636:46)
    at MetadataCollector.getMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\metadata\collector.js:492:21)
    at MetadataCache.getMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\transformers\metadata_cache.js:59:43)
    at Object.getSourceFileMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:110:55)
    at Object.readMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\transformers\metadata_reader.js:45:39)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (C:\workspace\projects\cli-test\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:466:38)
    at StaticSymbolResolver.getModuleMetadata (C:\workspace\projects\cli-test\node_modules\@angular\compiler\bundles\compiler.umd.js:23164:49)
    at StaticSymbolResolver._createSymbolsOf (C:\workspace\projects\cli-test\node_modules\@angular\compiler\bundles\compiler.umd.js:22955:33)
</code></pre>

The error can be resolved by replacing `this` with `TestLibService` in the `addAll` method or by using an if block instead of the ternary operator.

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 7.2.1
Node: 10.15.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.12.1
@angular-devkit/core         7.2.1
@angular-devkit/schematics   7.2.1
@schematics/angular          7.2.1
@schematics/update           0.12.1
rxjs                         6.3.3
typescript                   3.2.2
</code></pre>

**Comment by g3rrydanc3** [comment]
Same error when build angular library
Error in _**this**_
```
export abstract class BaseModel {
  static fromJson<T>(this: new () => T, obj: Object) {
    return plainToClass(this, obj, BaseModel.classTransformOption);
  }
}
```

> Metadata collected contains an error that will be reported at runtime: Expression form not supported.

**Comment by JoostK** [comment]
This is no longer an issue in Ivy. Unfortunately it's still an issue for libraries, as these still have to be compiled for ViewEngine.

**Comment by JoostK** [comment]
With v12 now allowing libraries to be compiled with the Ivy compiler, this issue has been resolved.
