### ISSUE TITLE
Error in template-var-assignment migration: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by dddent** [angular/angular#31043]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Description

Running `ng update @angular/core` fails after the Static Query Migration. The output we are getting:

```
Using package manager: 'npm'
Collecting installed dependencies...
Found 99 dependencies.
    ** Executing migrations for package '@angular/core' **
            ------ Static Query Migration ------
            With Angular version 8, developers need to
            explicitly specify the timing of ViewChild and
            ContentChild queries. Read more about this here:
            https://v8.angular.io/guide/static-query-migration
            
            The template migration strategy uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot use the template migration strategy. Please ensure there are no AOT compilation errors.
            ------------------------------------------------
Cannot read property 'start' of null

```

## 🔬 Minimal Reproduction

The error seems to be thrown in [html_variable_assignment_visitor.ts](https://github.com/angular/angular/blob/1a5c7112e0afc33202961bf43cac42b9a49e056d/packages/core/schematics/migrations/template-var-assignment/angular/html_variable_assignment_visitor.ts#L73), where the visitor is called, but span is undefined. In this case the node itself seems to be a variable assignment in a spans click listener:

```
{"span":{"start":37,"end":59},"receiver":{"span":{"start":37,"end":37}},"name":"showDatepicker","value":{"span":{"start":54,"end":59},"value":true}}
```
A stripped down version of the HTML template the node is pointing to:

```
<ng-template #showOnOff let-showDatepicker>
            <span *ngIf="item.status === 'paid' && !showDatepicker" fxLayoutAlign="center center"
              (click)="showDatepicker = true">
              <span class="fa fa-calendar pointer"></span>
            </span>
</ng-template>
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.2
Node: 10.15.0
OS: linux x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              7.2.3
@angular-devkit/schematics        7.2.3
@angular/cdk                      7.2.2
@angular/cli                      8.0.2
@angular/flex-layout              7.0.0-beta.23
@angular/http                     7.2.2
@angular/material                 7.2.2
@angular/pwa                      0.12.3
@ngtools/webpack                  8.0.2
@schematics/angular               7.2.3
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**

Here is the stack trace when the error occurs:

```
Error
    at ExpressionAstVisitor.visitPropertyWrite (/home/david/ltdo/latido-core/client/node_modules/@angular/core/schematics/migrations/template-var-assignment/angular/html_variable_assignment_visitor.js:69:29)
    at PropertyWrite.visit (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:6910:28)
    at ExpressionAstVisitor.RecursiveAstVisitor.visitConditional (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:7174:25)
    at Conditional.visit (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:6881:28)
    at /home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:7239:54
    at Array.forEach (<anonymous>)
    at ExpressionAstVisitor.RecursiveAstVisitor.visitAll (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:7239:18)
    at ExpressionAstVisitor.RecursiveAstVisitor.visitChain (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:7171:90)
    at Chain.visit (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:6866:28)
    at ASTWithSource.visit (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:7123:29)
    at HtmlVariableAssignmentVisitor.visitBoundEvent (/home/david/ltdo/latido-core/client/node_modules/@angular/core/schematics/migrations/template-var-assignment/angular/html_variable_assignment_visitor.js:54:26)
    at BoundEvent.visit (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:3643:74)
    at Object.visitAll (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/src/render3/r3_ast.js:278:40)
    at HtmlVariableAssignmentVisitor.visitElement (/home/david/ltdo/latido-core/client/node_modules/@angular/core/schematics/migrations/template-var-assignment/angular/html_variable_assignment_visitor.js:33:22)
    at Element.visit (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/bundles/compiler.umd.js:3663:71)
    at Object.visitAll (/home/david/ltdo/latido-core/client/node_modules/@angular/compiler/src/render3/r3_ast.js:278:40)
```

**Comment by devversion** [comment]
@dddent Is it possible that the `(click)` listener which contains the template variable assignment does have a conditional inside of it? (you mentioned that you stripped down the HTML template in the issue).

**Comment by dddent** [comment]
@devversion no, I did not change anything about the span itself, just removed some surrounding tags.

I guess there is a good chance #31085 still fixes it, I will try it as soon as it is merged

**Comment by devversion** [comment]
@dddent Thanks for the quick response. I was asking because I saw `visitConditional` in the stack trace you sent.
