### ISSUE TITLE
Angular 8 server side rendering with load children method gives runtime compiler not loaded error at server

### ISSUE THREAD

**Issue by devbenzy** [angular/angular#31249]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
Can't determine the affected package

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

I am trying to lazy load  different modules based on the device type (mobile / desktop). 
If it is a mobile phone then i want to load the mobile module, otherwise i want to load the desktop module. this works fine in the browser, how ever when enabled the server side rendering an error happening when i try to access the lazy loaded module route. how ever there is no issue loading the default routes

## 🔬 Minimal Reproduction

 https://stackblitz.com/...
https://github.com/devbenzy/angularserverside

steps to build : 
npm run build:ssr && npm run serve:ssr

open browser and go to http://localhost:4300 this will work fine
go to http://localhost:4300/desktop, this will give error in the console and the module will not be loaded on the server side.

## 🔥 Exception or Error
<pre><code>

ERROR Error: Uncaught (in promise): Error: Runtime compiler is not loaded
Error: Runtime compiler is not loaded
    at Compiler._throwError (/home/xxxx/projects/serverside/dist/server.js:28089:11)
    at MergeMapSubscriber.project (/home/xxxx/projects/serverside/dist/server.js:141115:93)
    at MergeMapSubscriber._tryNext (/home/xxxx/projects/serverside/dist/server.js:37090:27)
    at MergeMapSubscriber._next (/home/xxxx/projects/serverside/dist/server.js:37080:18)
    at MergeMapSubscriber.Subscriber.next (/home/xxxx/projects/serverside/dist/server.js:33602:18)
    at /home/xxxx/projects/serverside/dist/server.js:36837:28
    at ZoneDelegate.invoke (/home/xxxx/projects/serverside/dist/server.js:543:26)
    at Object.onInvoke (/home/xxxx/projects/serverside/dist/server.js:28556:33)
    at ZoneDelegate.invoke (/home/xxxx/projects/serverside/dist/server.js:542:52)
    at Zone.run (/home/xxxx/projects/serverside/dist/server.js:302:43)
    at resolvePromise (/home/xxxx/projects/serverside/dist/server.js:1004:31)
    at resolvePromise (/home/xxxx/projects/serverside/dist/server.js:961:17)
    at /home/xxxx/projects/serverside/dist/server.js:1065:17
    at ZoneDelegate.invokeTask (/home/xxxx/projects/serverside/dist/server.js:575:31)
    at Object.onInvokeTask (/home/xxxx/projects/serverside/dist/server.js:28547:33)
    at ZoneDelegate.invokeTask (/home/xxxx/projects/serverside/dist/server.js:574:60)
    at Zone.runTask (/home/xxxx/projects/serverside/dist/server.js:347:47)
    at drainMicroTaskQueue (/home/xxxx/projects/serverside/dist/server.js:753:35)
    at ZoneTask.invokeTask (/home/xxxx/projects/serverside/dist/server.js:654:21)
    at Server.ZoneTask.invoke (/home/xxxx/projects/serverside/dist/server.js:639:48) {
  rejection: Error: Runtime compiler is not loaded
      at Compiler._throwError (/home/xxxx/projects/serverside/dist/server.js:28089:11)
      at MergeMapSubscriber.project (/home/xxxx/projects/serverside/dist/server.js:141115:93)
      at MergeMapSubscriber._tryNext (/home/xxxx/projects/serverside/dist/server.js:37090:27)
      at MergeMapSubscriber._next (/home/xxxx/projects/serverside/dist/server.js:37080:18)
      at MergeMapSubscriber.Subscriber.next (/home/xxxx/projects/serverside/dist/server.js:33602:18)
      at /home/xxxx/projects/serverside/dist/server.js:36837:28
      at ZoneDelegate.invoke (/home/xxxx/projects/serverside/dist/server.js:543:26)
      at Object.onInvoke (/home/xxxx/projects/serverside/dist/server.js:28556:33)
      at ZoneDelegate.invoke (/home/xxxx/projects/serverside/dist/server.js:542:52)
      at Zone.run (/home/xxxx/projects/serverside/dist/server.js:302:43),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: Error: Runtime compiler is not loaded
        at Compiler._throwError (/home/xxxx/projects/serverside/dist/server.js:28089:11)
        at MergeMapSubscriber.project (/home/xxxx/projects/serverside/dist/server.js:141115:93)
        at MergeMapSubscriber._tryNext (/home/xxxx/projects/serverside/dist/server.js:37090:27)
        at MergeMapSubscriber._next (/home/xxxx/projects/serverside/dist/server.js:37080:18)
        at MergeMapSubscriber.Subscriber.next (/home/xxxx/projects/serverside/dist/server.js:33602:18)
        at /home/xxxx/projects/serverside/dist/server.js:36837:28
        at ZoneDelegate.invoke (/home/xxxx/projects/serverside/dist/server.js:543:26)
        at Object.onInvoke (/home/xxxx/projects/serverside/dist/server.js:28556:33)
        at ZoneDelegate.invoke (/home/xxxx/projects/serverside/dist/server.js:542:52)
        at Zone.run (/home/xxxx/projects/serverside/dist/server.js:302:43)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: [Zone],
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: [Zone],
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: Error: Runtime compiler is not loaded
          at Compiler._throwError (/home/xxxx/projects/serverside/dist/server.js:28089:11)
          at MergeMapSubscriber.project (/home/xxxx/projects/serverside/dist/server.js:141115:93)
          at MergeMapSubscriber._tryNext (/home/xxxx/projects/serverside/dist/server.js:37090:27)
          at MergeMapSubscriber._next (/home/xxxx/projects/serverside/dist/server.js:37080:18)
          at MergeMapSubscriber.Subscriber.next (/home/xxxx/projects/serverside/dist/server.js:33602:18)
          at /home/xxxx/projects/serverside/dist/server.js:36837:28
          at ZoneDelegate.invoke (/home/xxxx/projects/serverside/dist/server.js:543:26)
          at Object.onInvoke (/home/xxxx/projects/serverside/dist/server.js:28556:33)
          at ZoneDelegate.invoke (/home/xxxx/projects/serverside/dist/server.js:542:52)
          at Zone.run (/home/xxxx/projects/serverside/dist/server.js:302:43)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.4
Node: 12.4.0
OS: linux x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.4
@angular-devkit/build-angular              0.800.4
@angular-devkit/build-optimizer            0.800.4
@angular-devkit/build-webpack              0.800.4
@angular-devkit/core                       8.0.4
@angular-devkit/schematics                 8.0.4
@angular/cli                               8.0.4
@ngtools/webpack                           8.0.4
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   7.0.2
@schematics/angular                        8.0.4
@schematics/update                         0.800.4
rxjs                                       6.4.0
typescript                                 3.4.5
webpack                                    4.30.0
</code></pre>

**Anything else relevant?**

**Comment by mosh-ackosoft** [comment]
Did you try @nguniversal/module-map-ngfactory-loader version8 RC ?

**Comment by devbenzy** [comment]
I just tried with 8.0.0-rc.1, still the same error Runtime compiler is not loaded, am i missing something ? do i need to configure it somehow ?

**Comment by naturalfreak** [comment]
It's not project problem if you replace, may be it is from universal compiler

```
    loadChildren: () => {
      let userAgent: string;
      userAgent = AppConfig();
      if (typeof navigator != "undefined") {
        userAgent = navigator.userAgent;
      }
      if (!Mobile(userAgent)) {
        return import('./desktop/desktop.module').then(mod => mod.DesktopModule)
      }
      else {
        return import('./mobile/mobile.module').then(mod => mod.MobileModule)
      }
    }
```

with: 
`   loadChildren: () => import('./desktop/desktop.module').then(mod => mod.DesktopModule)
`
It's working....

**Comment by mosh-ackosoft** [comment]
> I just tried with 8.0.0-rc.1, still the same error Runtime compiler is not loaded, am i missing something ? do i need to configure it somehow ?

I am using angular universal with lazy loading. [Material Universal](https://github.com/mtushar091/angular-material ) You can check how it's done if you think it might help.

**Comment by devbenzy** [comment]
> It's not project problem if you replace, may be it is from universal compiler
> 
> ```
>     loadChildren: () => {
>       let userAgent: string;
>       userAgent = AppConfig();
>       if (typeof navigator != "undefined") {
>         userAgent = navigator.userAgent;
>       }
>       if (!Mobile(userAgent)) {
>         return import('./desktop/desktop.module').then(mod => mod.DesktopModule)
>       }
>       else {
>         return import('./mobile/mobile.module').then(mod => mod.MobileModule)
>       }
>     }
> ```
> 
> with:
> ` loadChildren: () => import('./desktop/desktop.module').then(mod => mod.DesktopModule)`
> It's working....

Hi,
Thats working, i needed to conditionally load the modules, so i think the approach i took is the only way. i hve aot set to false, so it should be working with JIT, don't know what went wrong.

**Comment by devbenzy** [comment]
> > I just tried with 8.0.0-rc.1, still the same error Runtime compiler is not loaded, am i missing something ? do i need to configure it somehow ?
> 
> I am using angular universal with lazy loading. [Material Universal](https://github.com/mtushar091/angular-material) You can check how it's done if you think it might help.

Hi,
You are using load children like this : loadChildren: () => import('./desktop/desktop.module').then(mod => mod.DesktopModule), which is working fine when i tried too, but i need it like 

if (!Mobile(userAgent)) {
        return import('./desktop/desktop.module').then(mod => mod.DesktopModule)
      }
      else {
        return import('./mobile/mobile.module').then(mod => mod.MobileModule)
      }

**Comment by devbenzy** [comment]
Just another finding

loadChildren: () =>{ 
return  import('./desktop/desktop.module').then(mod => mod.DesktopModule);
}
works, but 
loadChildren: () =>{ 
var x=1;
return  import('./desktop/desktop.module').then(mod => mod.DesktopModule);
}
doesn't

**Comment by naturalfreak** [comment]
It's a compiler error, I think, but you can use router guards and different route for mobile and desktop devices to manipulate this behaviour.

**Comment by alxhub** [comment]
The bug here is that we should produce a better error message in this case.

@devbenzy is correct - your `loadChildren` string should be of the form:

```typescript
 loadChildren: () => import('./desktop/desktop.module').then(mod => mod.DesktopModule)
```

Anything else (custom logic, conditionals, etc) won't work.

**Comment by nud** [comment]
FYI it doesn't work either when doing this:

```typescript
loadchildren: () => {
    return import('./desktop/desktop.module').then(mod => mod.DesktopModule);
}
```

Logically there shouldn't be any difference between these two way (except for the syntax) but it seems to matter to the compiler.

**Comment by zd-dalibor** [comment]
I got the same error with:

```typescript
loadChildren: () => import('./portal-area/portal-area.module').then(mod => mod.PortalAreaModule)
```

*@nguniversal/module-map-ngfactory-loader*: *8.2.6*

```
ERROR Error: Uncaught (in promise): Error: Runtime compiler is not loaded
Error: Runtime compiler is not loaded
    at Compiler._throwError (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:95070:11)
    at MergeMapSubscriber.project (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:115271:93)
    at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:189594:27)
    at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:189584:18)
    at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:184045:18)
    at D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:194805:28
    at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197139:26)
    at Object.onInvoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:95537:33)
    at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197138:52)
    at Zone.../node_modules/zone.js/dist/zone-node.js.Zone.run (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:196898:43)
    at resolvePromise (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197600:31)
    at resolvePromise (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197557:17)
    at D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197661:17
    at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invokeTask (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197171:31)
    at Object.onInvokeTask (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:95528:33)
    at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invokeTask (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197170:60)
    at Zone.../node_modules/zone.js/dist/zone-node.js.Zone.runTask (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:196943:47)
    at drainMicroTaskQueue (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197349:35)
    at ../node_modules/zone.js/dist/zone-node.js.ZoneTask.invokeTask (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197250:21)
    at ZoneTask.invoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197235:48) {
  rejection: Error: Runtime compiler is not loaded
      at Compiler._throwError (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:95070:11)
      at MergeMapSubscriber.project (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:115271:93)
      at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:189594:27)
      at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:189584:18)
      at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:184045:18)
      at D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:194805:28
      at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197139:26)
      at Object.onInvoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:95537:33)
      at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197138:52)
      at Zone.../node_modules/zone.js/dist/zone-node.js.Zone.run (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:196898:43),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: Error: Runtime compiler is not loaded
        at Compiler._throwError (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:95070:11)
        at MergeMapSubscriber.project (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:115271:93)
        at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:189594:27)
        at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:189584:18)
        at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:184045:18)
        at D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:194805:28
        at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197139:26)
        at Object.onInvoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:95537:33)
        at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197138:52)
        at Zone.../node_modules/zone.js/dist/zone-node.js.Zone.run (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:196898:43)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: [Zone],
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: [Zone],
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: Error: Runtime compiler is not loaded
          at Compiler._throwError (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:95070:11)
          at MergeMapSubscriber.project (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:115271:93)
          at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:189594:27)
          at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:189584:18)
          at MergeMapSubscriber.../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:184045:18)
          at D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:194805:28
          at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197139:26)
          at Object.onInvoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:95537:33)
          at ZoneDelegate.../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:197138:52)
          at Zone.../node_modules/zone.js/dist/zone-node.js.Zone.run (D:\Projects\InstaOrder\InstaOrder.Web\client\prerender.js:196898:43)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}
```

**Comment by alxhub** [comment]
Using:

```typescript
loadChildren: () => import('./desktop/desktop.module').then(mod => mod.DesktopModule)
```

worked for me. The CLI was able to identify this as a lazily loaded route and replace it with an import of the `NgModuleFactory`, which doesn't try to use the JIT compiler.
