### ISSUE TITLE
Ivy preview: ERROR in Unable to write a reference to AngularEditorComponent

### ISSUE THREAD

**Issue by kolkov** [angular/angular#31631]
I try to build my library with Ivy and got this error:
```
Compiling @kolkov/angular-editor : es2015 as esm2015                                                                                       10% building
3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html
chunk {main} main.js, main.js.map (main) 2.02 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 694 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2019-07-18T18:36:18.554Z - Hash: 8001275a78f05bdf7f5b - Time: 25892ms

ERROR in Unable to write a reference to AngularEditorComponent in D:/Go/angular-editor/projects/angular-editor/src/lib/angular-editor.component.ts from
D:/Go/angular-editor/projects/angular-editor/src/lib/angular-editor.module.ts
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
i ｢wdm｣: Compiling...

Date: 2019-07-18T18:36:20.396Z - Hash: 8001275a78f05bdf7f5b
5 unchanged chunks

Time: 1425ms

ERROR in Unable to write a reference to AngularEditorComponent in D:/Go/angular-editor/projects/angular-editor/src/lib/angular-editor.component.ts from
D:/Go/angular-editor/projects/angular-editor/src/lib/angular-editor.module.ts
i ｢wdm｣: Failed to compile.
D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:228
                    finally { if (e_2) throw e_2.error; }
                                       ^

Error: Unable to write a reference to AngularEditorComponent in D:/Go/angular-editor/projects/angular-editor/src/lib/angular-editor.component.ts from D:
/Go/angular-editor/projects/angular-editor/src/lib/angular-editor.module.ts
    at ReferenceEmitter.emit (D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\imports\src\emitter.js:55:19)
    at Object.toR3Reference (D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\util.js:134:31)
    at NgModuleDecoratorHandler._toR3Reference (D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:288:31)
    at D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:132:83
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js:132:48)
    at analyze (D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:172:60)
    at _loop_1 (D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:212:25)
    at analyzeClass (D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:220:25)
    at visit (D:\Go\angular-editor\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:234:21)
```
Whats wrong?

https://github.com/kolkov/angular-editor/tree/ivy-preview

**Comment by ericmartinezr** [comment]
Related/dup https://github.com/angular/angular/issues/29361

**Comment by petebacondarwin** [comment]
Closing as a dup.
