### ISSUE TITLE
ERROR in : Error: Internal error: unknown identifier undefined

### ISSUE THREAD

**Issue by earshinov** [angular/angular#31658]
### Bug Report or Feature Request
```
- [x] bug report
- [ ] feature request
```

There are already similar bug reports, for example https://github.com/angular/angular-cli/issues/11359, but such errors seem complicated and difficult to solve enough to justify individual tracking of each problem.

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions

```
> node --version
v8.11.1
> npm --version
5.6.0
> yarn list @angular/cli @angular/core
├─ @angular/cli@1.7.4
└─ @angular/core@5.2.11
```

Windows 10.

### Repro steps

I have prepared a demo: 
https://github.com/earshinov/angular-demo-polymorphic-content-children

Reproduction steps:
1. `git clone` the repo
2. Install node_modules:

```
npm install -g yarn;
cd demo-app;
yarn;
cd ../demo-lib;
yarn;
```

3. (from now on, this is a copy of instructions from the demo repo) Build the library:

```
cd demo-lib;
npm run build;
cd ..;
```

4. Install the built library into the demo app:

```
cd demo-app;
yarn add file:../demo-lib/dist;
cd ..;
```

5. Try building the demo app:

```
npm run -- ng build --prod;
```

### The log given by the failure

```
ERROR in : Error: Internal error: unknown identifier undefined
    at Object.importExpr$$1 [as importExpr] (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:31063:23)
    at tokenExpr (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:20063:39)
    at providerDef (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:19966:20)
    at ViewBuilder._visitProviderOrDirective (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:28177:18)
    at ViewBuilder._visitProvider (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:28110:36)
    at demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:27931:23
    at Array.forEach (<anonymous>)
    at ViewBuilder._visitElementOrTemplate (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:27916:23)
    at ViewBuilder.visitElement (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:27820:23)
    at ElementAst.visit (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:925:24)
    at visit (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:1366:37)
    at demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:1368:42
    at Array.forEach (<anonymous>)
    at templateVisitAll (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:1367:10)
    at ViewBuilder.visitAll (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:27615:9)
    at ViewCompiler.compileComponent (demo-app\node_modules\@angular\compiler\bundles\compiler.umd.js:27539:17)
```

### Mention any other details that might be useful

- Please take a look at git log. Note that the problem appears after introducing an intermediate module with imports and re-exports (`demo-lib/src/util/index.ts`) in [4c68f491](https://github.com/earshinov/angular-demo-polymorphic-content-children/commit/4c68f4913fd784c03994dd2115ee25ddf45c4a02).

- The problem is probably somewhere in the AOT compiler because it does not occur when running `ng serve` or `ng build` without the `--prod` flag.

- The problem might be related to the approach taken by the library to allow for different kinds of children in a container component. This approach is illustrated in this blog post: http://www.mcrook.com/2016/10/angular-2-contentchildren-with-abstract.html

**Comment by sjnorval** [comment]
I am also experiencing the same problem... Has there been any traction on this?

**Comment by alxhub** [comment]
Closing as obsolete - likely fixed by now.

**Comment by mayurimoreengg** [comment]
I figured out my problem, I was adding { provide: Window, useValue: window } in appModule.
When I removed this. My error is gone.

I hope this helps.

**Comment by mayurimoreengg** [comment]
> I figured out my problem, I was adding { provide: Window, useValue: window } in appModule Providers.
> When I removed this. My error is gone.
> 
> I hope this helps.

You can also refer 
https://github.com/angular/angular-cli/issues/11359
