### ISSUE TITLE
Ivy: unknown element test failures with `NO_ERRORS_SCHEMA`

### ISSUE THREAD

**Issue by thecp** [angular/angular#31670]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Is this a regression?

Let's say it works with View Engine.

### Description

We used to test certain components sometimes with `NO_ERRORS_SCHEMA` to not have to bring in all the existing child components into the testing module. Also we mock our services to not use the `HttpClient` but return directly an observable via rxjs's `of`. There seem to be cases where this will fail in <b>Ivy</b> with an unknown element exception for the child components in the template (but that's why I am using `NO_ERRORS_SCHEMA`...) when accessing the service function within `ngOnInit` in the parent function.

## 🔬 Minimal Reproduction

I have made a minimal repo to show the behavior:

https://github.com/thecp/angular-ivy-test-failures

## 🔥 Exception or Error
<pre><code>Error: Template error: Can't bind to 'entry' since it isn't a known property of 'tr'.
            at createUnknownPropertyError (http://localhost:9876/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:15129:1)
            at validateAgainstUnknownProperties (http://localhost:9876/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:15068:1)
            at elementPropertyInternal (http://localhost:9876/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14973:1)
            at ɵɵproperty (http://localhost:9876/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:16578:1)
            at AppComponent_tr_1_Template (ng:///AppComponent.js:10:5)
            at executeTemplate (http://localhost:9876/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14545:1)
            at renderEmbeddedTemplate (http://localhost:9876/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14469:1)
            at refreshDynamicEmbeddedViews (http://localhost:9876/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:15702:1)
            at refreshDescendantViews (http://localhost:9876/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14115:1)
            at checkView (http://localhost:9876/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:15969:1)</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.2.0-next.1
Node: 10.16.0
OS: linux x64
Angular: 8.2.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-next.1
@angular-devkit/build-angular     0.802.0-next.1
@angular-devkit/build-optimizer   0.802.0-next.1
@angular-devkit/build-webpack     0.802.0-next.1
@angular-devkit/core              8.2.0-next.1
@angular-devkit/schematics        8.2.0-next.1
@angular/cli                      8.2.0-next.1
@ngtools/webpack                  8.2.0-next.1
@schematics/angular               8.2.0-next.1
@schematics/update                0.802.0-next.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.3
</code></pre>

**Comment by JoostK** [comment]
Hi @thecp,

The usage of schemas is not supported with Ivy at the moment, there's a PR in progress here in #30301.

**Comment by thecp** [comment]
@JoostK thx for the fast answer, I didn't see this PR :roll_eyes:

**Comment by JoostK** [comment]
@thecp No problem, thank you for taking the time to report!

**Comment by thecp** [comment]
I consider this solved by https://github.com/angular/angular/pull/32171
