### ISSUE TITLE
Zone.js does not work with Zombie/jsdom

### ISSUE THREAD

**Issue by mhevery** [angular/angular#31760]
I'm trying to get an Angular2 app running in Zombie, and seeing the following error (presumably from jsdom):

TypeError: Cannot redefine property: onclick
    at Function.defineProperty (native)
    at canPatchViaPropertyDescriptor (http://localhost:8080/app.js:35698:12)
    at Object.apply (http://localhost:8080/app.js:35677:9)
    at Object.apply (http://localhost:8080/app.js:35288:29)
    at http://localhost:8080/app.js:35165:16
    at linkDynamicModule (http://localhost:8080/app.js:262:32)
    at getModule (http://localhost:8080/app.js:231:9)
    at http://localhost:8080/app.js:266:16
    at http://localhost:8080/app.js:35147:20
    at linkDynamicModule (http://localhost:8080/app.js:262:32)
    in http://localhost:8080/

ORIGINALY FILED AS: https://github.com/angular/angular/issues/3584

**Comment by AndrewKushnir** [comment]
Closing this ticket due to the lack of repro.
