### ISSUE TITLE
Regression Ivy with ComponentFactory

### ISSUE THREAD

**Issue by ErazerBrecht** [angular/angular#31785]
# 🐞 bug report

Tbh: I didn't search if this was already known (no idea how I would have found it 😅)

### Affected Package
The issue is caused by package @angular/core

### Is this a regression?

This works without Ivy enabled.

### Description

I was trying out Angular Ivy in our codebase. One of the last 'problems' that is really blocking seems to be ['ngx-toastr'](https://github.com/scttcper/ngx-toastr).

They dynamically add the [toastr component](https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toast.component.ts) on runtime in the DOM.

[Link to code that is responsible for this](https://github.com/scttcper/ngx-toastr/blob/db3e8fefe79dd66f2610b057a762bb0e668ab417/src/lib/portal/dom-portal-host.ts#L32)

When switching to Ivy this code doesn't work anymore:

```
ERROR DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('') is not a valid name. at DefaultDomRenderer2.createElement
```

After some debugging I found out that it's because the code that's responsible for retrieving the selector of a component in Ivy doesn't work: [Link](https://github.com/angular/angular/blob/c845a7b887d1a85a89acfe5c62b8829079130af3/packages/core/src/render3/component_ref.ts#L124)

In case of the toast component (see link above) it's ['', 'toast-component', '']. As a result the tag name becomes ''. And that explains the error above.

I cloned ngx-toastr, changed the component name from `[toast-component]` to `toast-component` (removed the brackets). And everything seems to be working. This of course changes the result from a div with as attribute 'toast-component' to a custom component with as selector 'toast-component'.

TL;DR: Dynamically generating components on runtime with Ivy doesn't work when using attribute notation.

## 🔬 Minimal Reproduction

Use ngx-toastr with Ivy enabled.
If more time, I'll create a stackblitz.

## 🔥 Exception or Error

```
ERROR DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('') is not a valid name. 
at DefaultDomRenderer2.createElement (http://localhost:4200/vendor.js:82322:25) 
at elementCreate (http://localhost:4200/vendor.js:53703:32) 
at ComponentFactory$1.create (http://localhost:4200/vendor.js:67815:13) 
at DomPortalHost.attachComponentPortal (http://localhost:4200/vendor.js:94547:41) 
at DomPortalHost.attach (http://localhost:4200/vendor.js:94505:21) at OverlayRef.attach (http://localhost:4200/vendor.js:94629:33) 
at ToastrService._buildNotification (http://localhost:4200/vendor.js:94955:35) 
at ToastrService._preBuildNotification (http://localhost:4200/vendor.js:94921:21) 
at ToastrService.success
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.0-next.1
Node: 12.6.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.802.0-next.1
@angular-devkit/core         8.2.0-next.1
@angular-devkit/schematics   8.2.0-next.1
@schematics/angular          8.2.0-next.1
@schematics/update           0.802.0-next.1
rxjs                         6.4.0

</code></pre>

**Anything else relevant?**
Causes https://github.com/scttcper/ngx-toastr/issues/686

**Comment by ErazerBrecht** [comment]
Here is my repro:
https://github.com/ErazerBrecht/AngularIvyBug

If you enable `enableIvy` it doesn't work, if you don't enable Ivy it works.

**Comment by ErazerBrecht** [comment]
Thx @kara for the fix!
Sincerely, Brecht
