### ISSUE TITLE
ci: `Chrome failed to start` flakes on `test_docs_examples[_ivy]`

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#31841]
I've been seeing the following flakes quite often recently on `test_docs_examples`/`test_docs_examples_ivy` CircleCI jobs. (They are not related to a specific example and/or port.)

```
running: yarn e2e --prod --no-webdriver-update --port=4001
...
[13:20:50] I/launcher - Running 1 instances of WebDriver
[13:20:50] I/direct - Using ChromeDriver directly...
[13:20:51] E/launcher - unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}),platform=Linux 4.15.0-1035-aws x86_64)
[13:20:51] E/launcher - WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}),platform=Linux 4.15.0-1035-aws x86_64)
    at Object.checkLegacyResponse (/home/circleci/ng/aio/tools/examples/shared/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/circleci/ng/aio/tools/examples/shared/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/circleci/ng/aio/tools/examples/shared/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/circleci/ng/aio/tools/examples/shared/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/home/circleci/ng/aio/tools/examples/shared/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/home/circleci/ng/aio/tools/examples/shared/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/home/circleci/ng/aio/tools/examples/shared/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/home/circleci/ng/aio/tools/examples/shared/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/home/circleci/ng/aio/tools/examples/shared/node_modules/q/q.js:834:54)
    at /home/circleci/ng/aio/tools/examples/shared/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/circleci/ng/aio/tools/examples/shared/node_modules/q/q.js:796:13)
    at /home/circleci/ng/aio/tools/examples/shared/node_modules/q/q.js:556:49
    at runSingle (/home/circleci/ng/aio/tools/examples/shared/node_modules/q/q.js:137:13)
    at flush (/home/circleci/ng/aio/tools/examples/shared/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
...
```

Sample failures:
- [388736#3][1]
- [391645#1][2]
- [402919#0][3]
- [402919#3][4]
- [402963#1][5]
- [402966#2][6]

[1]: https://circleci.com/gh/angular/angular/388736#tests/containers/3
[2]: https://circleci.com/gh/angular/angular/391645#tests/containers/1
[3]: https://circleci.com/gh/angular/angular/402919#tests/containers/0
[4]: https://circleci.com/gh/angular/angular/402919#tests/containers/3
[5]: https://circleci.com/gh/angular/angular/402963#tests/containers/1
[6]: https://circleci.com/gh/angular/angular/402966#tests/containers/2

**Comment by gkalpak** [comment]
FWIW, I wasn't able to reproduce it by ssh'ing into a container and running the docs examples e2e tests ~25 times 😞
