### ISSUE TITLE
Angular ^6.1.0 seems to have been impacted by yesterdays release

### ISSUE THREAD

**Issue by goldel777** [angular/angular#32073]
Hi,

I am running an Angular 6 application and it seems that yesterday's release was impacting my builds.    I am using Angular libs generated by cli.    

Can you help me understand how this is possible and how I can avoid future releases impacting my code.   At my company we need approval to move up to a new version of Angular.    

    "@angular-devkit/build-angular": "~0.8.0",
    "@angular-devkit/build-ng-packagr": "~0.8.0",
    "@angular/cli": "^6.1.0",

I build and pack my libs as follows - 

ng build --project @my-service/my-app"
npm pack
npm install file:my-app.tgz

I have been include references from one of my libs to another util yesterday.

import { MyModel } from '@my-service/my-other-app';
import { MyService } from '@my-service/my-other-app';

No versions were changed in my package.json.   The company does update software behind the scenes.

The error that started showing up is as follows.  It goes away if I copy the my-other-app code to my-app and reference it directly.

Building Angular Package
Building entry point '@my-service/my-app'
Compiling TypeScript sources through ngc
Bundling to FESM2015

BUILD ERROR
Could not resolve entry (...projects\my-service\my-app\@my-service\my-app\esm2015\my-app.js)
Error: Could not resolve entry (...projects\my-service\my-app\@my-service\my-app\esm2015\my-app.js)
    at error (...node_modules\rollup\dist\rollup.js:3460:30)
    at ...node_modules\rollup\dist\rollup.js:21474:17
    at <anonymous>

Could not resolve entry (...\my-app.js)
Error: Could not resolve entry (... my-service\my-app\@my-service\my-app\esm2015\my-service\my-app.js)
    at error (...node_modules\rollup\dist\rollup.js:3460:30)
    at ...node_modules\rollup\dist\rollup.js:21474:17
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.0.0 build:my-app: `ng build --project @my-service-myapp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.0.0 build:my-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goldlo5\AppData\Roaming\npm-cache\_logs\2019-08-09T12_14_50_264Z-debug.log

ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.2.9
Node: 8.9.4
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.9
@angular-devkit/build-angular      0.8.9
@angular-devkit/build-ng-packagr   0.8.0
@angular-devkit/build-optimizer    0.8.9
@angular-devkit/build-webpack      0.8.9
@angular-devkit/core               0.8.9
@angular-devkit/schematics         0.8.9
@angular/cdk                       6.4.7
@angular/cli                       6.2.9
@angular/flex-layout               6.0.0-beta.18
@angular/material                  6.4.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.9
@schematics/angular                0.8.9
@schematics/update                 0.8.9
ng-packagr                         4.7.1
rxjs                               6.5.2
typescript                         2.9.2
webpack                            4.16.4

**Comment by goldel777** [comment]
Okay - so I found my issue - for all others who may have the same issue - check that your tsconfig.json points to the location of the compiled javascript.
