### ISSUE TITLE
TypeError: Illegal invocation

### ISSUE THREAD

**Issue by mato75** [angular/angular#3219]
angular.js:12330 TypeError: Illegal invocation
    at isArrayLike (http://127.0.0.1:8383/js/components/angular/angular.js:276:46)
    at forEach (http://127.0.0.1:8383/js/components/angular/angular.js:332:32)
    at copy (http://127.0.0.1:8383/js/components/angular/angular.js:928:9)
    at copy (http://127.0.0.1:8383/js/components/angular/angular.js:897:16)
    at copy (http://127.0.0.1:8383/js/components/angular/angular.js:941:32)
    at copy (http://127.0.0.1:8383/js/components/angular/angular.js:897:16)
    at copy (http://127.0.0.1:8383/js/components/angular/angular.js:941:32)
    at copy (http://127.0.0.1:8383/js/components/angular/angular.js:897:16)
    at copy (http://127.0.0.1:8383/js/components/angular/angular.js:941:32)
    at copy (http://127.0.0.1:8383/js/components/angular/angular.js:897:16) undefined

**Comment by pkozlowski-opensource** [comment]
@mato75 this is wrong repo (I guess you wanted to file it at https://github.com/angular/angular.js) and the issue filled like this is not actionable. Please see how to submit an issue with enough context so we can help: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#submitting-an-issue
