### ISSUE TITLE
yarn setup not working in aio

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#32258]
# 📚 Docs or angular.io bug report

### Description

When trying to run `yarn setup` inside **aio** directory, I get an error.

### Reproduction Steps**

1. Clone the `angular` repository
2. Run `yarn` inside the **angular** directory.
3. Run `yarn setup` inside the **aio** directory.

### Expected vs Actual Behavior**

The script should continue to execute instead of throwing an error.

## 🔥 Exception or Error
<pre><code>

yarn run v1.16.0
$ yarn --cwd .. install && yarn install --frozen-lockfile && yarn ~~check-env && yarn ~~clean-generated && yarn boilerplate:remove
$ node tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ yarn update-webdriver && node --preserve-symlinks --preserve-symlinks-main ./tools/postinstall-patches.js
$ webdriver-manager update --gecko false $CI_CHROMEDRIVER_VERSION_ARG
[10:43:23] I/update - chromedriver: file exists C:\Users\aris\Documents\GitHub\angular\node_modules\webdriver-manager\selenium\chromedriver_75.0.3770.140.zip
[10:43:23] I/update - chromedriver: unzipping chromedriver_75.0.3770.140.zip
[10:43:23] I/update - chromedriver: chromedriver_75.0.3770.140.exe up to date
[10:43:23] I/update - selenium standalone: file exists C:\Users\aris\Documents\GitHub\angular\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.141.59.jar
[10:43:23] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
===== about to run the postinstall-patches.js script     =====
cd C:\Users\aris\Documents\GitHub\angular\

# patch: @bazel/karma 0.29.0 to disable chrome sandbox for OSX
sed -i process.platform !== 'linux' process.platform !== 'linux' && process.platform !== 'darwin' node_modules/@bazel/karma/karma.conf.js
===== finished running the postinstall-patches.js script =====
$ node ../tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @google-cloud/functions-emulator@1.0.0-beta.5: The engine "node" is incompatible with this module. Expected version "~6". Got "10.15.3"
info "@google-cloud/functions-emulator@1.0.0-beta.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.7: The platform "win32" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @angular/core@8.1.0-next.1" has incorrect peer dependency "zone.js@~0.9.1".
[5/5] Building fresh packages...
$ node tools/cli-patches/patch.js
$ node scripts/check-environment
$ node --eval "require('shelljs').rm('-rf', 'src/generated')"
$ node ./tools/examples/example-boilerplate remove
$ yarn example-use-npm && yarn aio-use-npm
$ node tools/ng-packages-installer restore ./tools/examples/shared
$ node ../../../../tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @angular/core@8.0.0" has incorrect peer dependency "zone.js@~0.9.1".
warning " > angular-in-memory-web-api@0.8.0" has incorrect peer dependency "@angular/common@>=6.0.0 <8.0.0".
warning " > angular-in-memory-web-api@0.8.0" has incorrect peer dependency "@angular/core@>=6.0.0 <8.0.0".
warning " > webpack-cli@3.1.2" has unmet peer dependency "webpack@^4.x.x".
[5/5] Building fresh packages...
$ yarn webdriver:update
$ webdriver-manager update --standalone false --gecko false $CI_CHROMEDRIVER_VERSION_ARG
[10:46:11] I/file_manager - creating folder C:\Users\aris\Documents\GitHub\angular\aio\tools\examples\shared\node_modules\webdriver-manager\selenium
[10:46:11] I/config_source - curl -oC:\Users\aris\Documents\GitHub\angular\aio\tools\examples\shared\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[10:46:12] I/downloader - curl -oC:\Users\aris\Documents\GitHub\angular\aio\tools\examples\shared\node_modules\webdriver-manager\selenium/chromedriver_75.0.3770.140.zip https://chromedriver.storage.googleapis.com/75.0.3770.140/chromedriver_win32.zip
[10:46:15] I/update - chromedriver: unzipping chromedriver_75.0.3770.140.zip
$ node tools/ng-packages-installer restore .
$ node ../tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info @google-cloud/functions-emulator@1.0.0-beta.5: The engine "node" is incompatible with this module. Expected version "~6". Got "10.15.3"
info "@google-cloud/functions-emulator@1.0.0-beta.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.7: The platform "win32" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @angular/core@8.1.0-next.1" has incorrect peer dependency "zone.js@~0.9.1".
[5/5] Building fresh packages...
$ node tools/cli-patches/patch.js
$ yarn boilerplate:add && yarn extract-cli-command-docs && yarn docs
$ node ./tools/examples/example-boilerplate add
C:\Users\aris\Documents\GitHub\angular\aio\node_modules\yargs\yargs.js:1078
      else throw err
           ^

Error: EPERM: operation not permitted, symlink 'C:/Users/aris/Documents/GitHub/angular/aio/tools/examples/shared/node_modules' -> 'C:/Users/aris/Documents/GitHub/angular/aio/content/examples/ajs-quick-reference/node_modules'
    at Object.symlinkSync (fs.js:904:3)
    at Object.createSymlinkSync (C:\Users\aris\Documents\GitHub\angular\aio\node_modules\fs-extra\lib\ensure\symlink.js:53:25)
    at exampleFolders.forEach.exampleFolder (C:\Users\aris\Documents\GitHub\angular\aio\tools\examples\example-boilerplate.js:93:10)
    at Array.forEach (<anonymous>)
    at ExampleBoilerPlate.add (C:\Users\aris\Documents\GitHub\angular\aio\tools\examples\example-boilerplate.js:88:20)
    at Object.yargs.usage.command [as builder] (C:\Users\aris\Documents\GitHub\angular\aio\tools\examples\example-boilerplate.js:127:79)
    at Object.self.runCommand (C:\Users\aris\Documents\GitHub\angular\aio\node_modules\yargs\lib\command.js:193:35)
    at Object.Yargs.self._parseArgs (C:\Users\aris\Documents\GitHub\angular\aio\node_modules\yargs\yargs.js:990:30)
    at Object.get [as argv] (C:\Users\aris\Documents\GitHub\angular\aio\node_modules\yargs\yargs.js:930:19)
    at ExampleBoilerPlate.main (C:\Users\aris\Documents\GitHub\angular\aio\tools\examples\example-boilerplate.js:130:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</code></pre>

## 🌍  Your Environment
Windows 10
### Anything else relevant?

@kapunahelewong

**Comment by kapunahelewong** [comment]
Thanks for filing this, @bampakoa! Searching for help on this I found this:

```git clone -c core.symlinks=true```

Could you try cloning with that and see if it works?

**Comment by bampakoa** [comment]
@kapunahelewong I tried to clone the repo using the command `git clone -c core.symlinks=true https://github.com/bampakoa/angular.git` but the problem persists

**Comment by kapunahelewong** [comment]
Ok, thanks for trying. I have some new info. This section of our README.md should be helpful: https://github.com/angular/angular/blob/a367b90a8/aio/tools/examples/README.md#a-node_modules-to-share

Plus, creating symlinks requires admin rights on Windows or to have Developer Mode enabled on Windows 10 (see https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10 for details). 

Can you try these and let me know how it goes? As we sort this out, I'll make sure to update the README with clarifying instructions on this point, so please feel free to log your steps and any errors here. Thank you for working with me!

**Comment by bampakoa** [comment]
🎉  your information was very helpful. I run `yarn setup` in a command line with administrator rights (aka the context menu **Run as administrator**) and it worked. Thank you so much! Would you like to add a section in the README file of **aio**, through a PR, that will cover Windows users?

**Comment by santoshyadav198613** [comment]
Hi @bampakoa , we already added it to getting started steps will add for aio. @kapunahelewong i will raise PR tomorrow.

**Comment by bampakoa** [comment]
That's cool @santoshyadav198613 . Thanks for the feedback 😉

**Comment by kapunahelewong** [comment]
@bampakoa Oh great! So glad it worked! 

@santoshyadav198613 A PR would be most welcome - thank you! Will you tag me when you submit it? Could you share with me where you added it for getting started? I looked but didn't see where. 🙏🏼

**Comment by bampakoa** [comment]
@kapunahelewong yes, I asked in case you need any help on that but @santoshyadav198613 got me covered 😄

**Comment by kapunahelewong** [comment]
Thank you @bampakoa 🌸
