### ISSUE TITLE
Support TypeScript 3.6

### ISSUE THREAD

**Issue by EatonZ** [angular/angular#32380]
# 🚀 feature request

### Relevant Package
Everything.

### Description
[TypeScript 3.6 just came out](https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/) and support should be added.🙂

### Describe the solution you'd like
Add support for TypeScript 3.6.
Would be great to see this added for v9 with the Ivy release.

### Describe alternatives you've considered
N/A

**Comment by patrickmichalina** [comment]
I am seeing `ngc` failures when using Typescript 3.6.2

```bash
TypeError: Cannot read property 'kind' of undefined
    at isParameterPropertyDeclaration (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:13411:88)
    at Object.filter (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:469:31)
    at transformClassMembers (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:70627:20)
    at createClassDeclarationHeadWithoutDecorators (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:70479:110)
    at visitClassDeclaration (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:70398:19)
    at visitTypeScript (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:70246:28)
    at visitorWorker (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:70041:24)
    at sourceElementVisitorWorker (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:70066:28)
    at saveStateAndInvoke (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:69979:27)
    at sourceElementVisitor (/Users/patrick/Repos/fusing-angular-2/node_modules/typescript/lib/typescript.js:70051:20)
```

**Comment by sod** [comment]
My guess is, google and their monorepo have the constraint to use the same typescript version across the entire company. And they had some issues going from 3.4 to 3.5 (https://github.com/microsoft/TypeScript/issues/33272)

**Comment by evmar** [comment]
Probably blocked on https://github.com/angular/tsickle/issues/1065

**Comment by EatonZ** [comment]
FYI, [3.7 draws near](https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/).👀

**Comment by lppedd** [comment]
@EatonZ I've already compiled with 3.7, seems fine. Actually 3.6 has an issue which makes it incompatible with Angular. https://github.com/microsoft/TypeScript/issues/33295
