### ISSUE TITLE
ivy template typechecking fails with "ERROR in TypeError: Cannot read property 'getStart' of undefined"

### ISSUE THREAD

**Issue by mattlewis92** [angular/angular#32538]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli

### Is this a regression?
Not sure, it might have worked in previous betas

### Description

When I try and run ivy on my app it fails to run template typechecking.

## 🔬 Minimal Reproduction
https://github.com/mattlewis92/angular-calendar/tree/try-ivy-v2

## 🔥 Exception or Error
<pre><code>
ERROR in TypeError: Cannot read property 'getStart' of undefined
    at makeTemplateDiagnostic (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/diagnostics.js:165:45)
    at Object.translateDiagnostic (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/diagnostics.js:114:16)
    at collectDiagnostics (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/context.js:202:60)
    at TypeCheckContext.calculateTemplateDiagnostics (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/context.js:220:21)
    at NgtscProgram.getTemplateDiagnostics (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@angular/compiler-cli/src/ngtsc/program.js:375:26)
    at NgtscProgram.getNgSemanticDiagnostics (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@angular/compiler-cli/src/ngtsc/program.js:168:78)
    at checkDiagnostics (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@ngtools/webpack/src/gather_diagnostics.js:38:27)
    at Object.gatherDiagnostics (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@ngtools/webpack/src/gather_diagnostics.js:77:13)
    at AngularCompilerPlugin._emit (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:1036:61)
    at AngularCompilerPlugin._update (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:806:50)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async AngularCompilerPlugin._make (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:703:13)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-next.3
Node: 12.6.0
OS: darwin x64
Angular: 9.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-next.3
@angular-devkit/build-angular      0.900.0-next.3
@angular-devkit/build-ng-packagr   0.900.0-next.3
@angular-devkit/build-optimizer    0.900.0-next.3
@angular-devkit/build-webpack      0.900.0-next.3
@angular-devkit/core               9.0.0-next.3
@angular-devkit/schematics         9.0.0-next.3
@angular/cdk                       8.1.3
@angular/cli                       9.0.0-next.3
@ngtools/webpack                   9.0.0-next.3
@schematics/angular                9.0.0-next.3
@schematics/update                 0.900.0-next.3
ng-packagr                         5.5.0
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.3
</code></pre>

**Anything else relevant?**
Nope

**Comment by JoostK** [comment]
So the issue here is that there's an incorrect assumption when the template source mapping info is derived for pre-analyzed templates. The code expects a pre-analyzed template to always originate from an external template, however this is not true: _all_ templates are pre-analyzed as even inline templates can have stylesheets that have to be preloaded.

Looks like this case hasn't been caught in tests as there's no pre-analysis at all when `ResourceLoader.canPreload` is `false`. This is the case in the tests as it's dependent on having `CompilerHost.readResource`, which is only true in the CLI where a `WebpackCompilerHost` is used, whereas ngtsc's tests use a vanilla `ts.CompilerHost`.

**Comment by vgb1993** [comment]
Hy I get the same error quite often

`     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.0.0-next.3
Node: 12.4.0
OS: win32 x64
Angular: 9.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-next.3
@angular-devkit/build-angular      0.900.0-next.3
@angular-devkit/build-ng-packagr   0.900.0-next.3
@angular-devkit/build-optimizer    0.900.0-next.3
@angular-devkit/build-webpack      0.900.0-next.3
@angular-devkit/core               9.0.0-next.3
@angular-devkit/schematics         9.0.0-next.3
@angular/cli                       9.0.0-next.3
@ngtools/webpack                   9.0.0-next.3
@schematics/angular                9.0.0-next.3
@schematics/update                 0.900.0-next.3
ng-packagr                         5.5.0
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.3`

**Comment by vgb1993** [comment]
any workaround to get ng s working for now?

**Comment by mattlewis92** [comment]
Nice one, thanks for the super quick turnaround @JoostK! 😄
