### ISSUE TITLE
RangeError: Maximum call stack size exceeded with flatModuleOutFile is the same as a file

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#32555]
# 🐞 bug report

### Affected Package
@angular/cli

### Is this a regression?
Don't think so

### Description
When enabling flatModuleOutFile and the flat module out file corresponds to an already exiting file a RangeError is thrown.

## 🔬 Minimal Reproduction
Create a typescript file

**tokens.ts**
```
import { InjectionToken } from '@angular/core';

export const REQUEST = new InjectionToken<unkown>('REQUEST');
export const RESPONSE = new InjectionToken<unkown>('RESPONSE');
```

Enable `flat_module_out_file` and name the **flat_module_out_file** the same as the file name
```
ng_module(
    flat_module_out_file = "tokens"
    name = "tokens",
    srcs = glob([
        "*.ts",
    ]),
    module_name = "@nguniversal/tokens",
    deps = [
        "@npm//@angular/core",
    ],
)
```

## 🔥 Exception or Error

Build and notice the exception
```
ERROR: C:/git/universal/modules/hapi-engine/tokens/BUILD.bazel:5:1: Compiling Angular templates (ngc) //modules/hapi-engine/tokens:tokens failed (Exit 1)
RangeError: Maximum call stack size exceeded
    at Object.normalize (path.js:284:32)
    at Object.join (path.js:488:18)
    at resolveModule (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:599:50)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:120:42)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
    at MetadataBundler.exportAll (C:\users\alag\_bazel_alag\wlnuzrpw\external\npm\node_modules\@angular\compiler-cli\src\metadata\bundler.js:122:52)
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
9.0.0-next.5

</code></pre>

**Anything else relevant?**
Related to https://github.com/angular/universal/pull/1234

**Comment by m-henderson** [comment]
@alan-agius4 do you mind updating the description of the bug? 😄

**Comment by alan-agius4** [comment]
@m-henderson thanks for letting me know.

**Comment by m-henderson** [comment]
@alan-agius4 have you diagnosed or looked into the issue at all? If you haven't then that is fine, I was just going to get what information you had found about the issue if you had any at all.

**Comment by alan-agius4** [comment]
No, I didn’t look at what’s causing this issue.

**Comment by JoostK** [comment]
The Ivy compiler no longer has a metadata collector, so closing as resolved in Ivy.
