### ISSUE TITLE
angular 8 ng build --prod EEXIST Differential Loading

### ISSUE THREAD

**Issue by borriej** [angular/angular#32560]
# 🐞 bug report

### Affected Package
```
    "@angular-devkit/build-angular": "~0.803.3",
    "@angular/cli": "~8.3.3",
    "@angular/compiler-cli": "^8.2.5",
```

### Description
I was trying to get SSR to work. So I updated my app to Angular 8 with ```ng update```.
I tried to make a simple build, with:
```
$ ng build --prod
```

But, im now getting an error each time i try to run this build. Error:
```
An unhandled exception occurred: EEXIST: file already exists, copyfile '/Users/username/repos/my-App/node_modules/.cache/angular-build-dl/content-v2/sha512/a5/06/43a8e14ea37961fc632cd7d73e0ee8670511e8c1a1d707ca2782b52d9c18bbd58300435caae575a2eafeae16a6b29a38320da48bad8faab72cb487f42df4' -> '/Users/username/repos/my-App/dist/browser/polyfills-es2015.19c755b1f5464eeeba13.js'
See "/private/var/folders/wh/s6w5z3hs5cb463mgk6z96n480000gn/T/ng-IMxc1r/angular-errors.log" for further details.
```

when i open the log, it looks like
```
[error] Error: EEXIST: file already exists, copyfile '/Users/username/repos/my-App/node_modules/.cache/angular-build-dl/content-v2/sha512/a5/06/43a8e14ea37961fc632cd7d73e0ee8670511e8c1a1d707ca2782b52d9c18bbd58300435caae575a2eafeae16a6b29a38320da48bad8faab72cb487f42df4' -> '/Users/username/repos/my-App/dist/browser/polyfills-es2015.19c755b1f5464eeeba13.js'
    at Object.copyFileSync (fs.js:1743:3)
    at SwitchMapSubscriber.rxjs_1.from.pipe.operators_1.switchMap [as project] (/Users/username/repos/my-App/node_modules/@angular-devkit/build-angular/src/browser/index.js:336:28)
```

## 🔬 Minimal Reproduction
No time atm to make a stackblitz.

## 🌍  Your Environment

**Angular Version:**
<pre>8.3.3<code>

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.3
@angular-devkit/build-angular              0.803.3
@angular-devkit/build-optimizer            0.803.3
@angular-devkit/build-webpack              0.803.3
@angular-devkit/core                       8.3.3
@angular-devkit/schematics                 8.3.3
@angular/cdk                               7.1.0
@angular/cli                               8.3.3
@angular/material                          7.1.0
@angular/material-moment-adapter           7.2.2
@ngtools/webpack                           8.3.3
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.3
@schematics/update                         0.803.3
rxjs                                       6.5.3
typescript                                 3.5.3
webpack                                    4.39.2

</code></pre>

My ```tsconfig.json``` looks like
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
    "downlevelIteration": false,
    "importHelpers": false,
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "module": "esnext",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowJs": true,
        "target": "es2015",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "dom"
        ],
        "paths": {
            "@app/*": ["./src/app/*"],
            "@env/*": ["./src/environments/*"],
            "@routes/*": ["./routes/*"]
        }
    }
}
```

```src/browserlist``` is empty

Hint: ```$ npm ci && ng build --prod``` works one time, but the error comes again after you type ```$ ng build --prod``` for a 2nd time.

**Comment by borriej** [comment]
solved, i had to use npm ```10.16.3``` (stable) instead of v11
