### ISSUE TITLE
Element.classList doesn't work on IE

### ISSUE THREAD

**Issue by mvrcrypto** [angular/angular#32572]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/platform-browser in dom_renderer.ts
The methods that throw an error are :
```javascript
addClass(el: any, name: string): void { el.classList.add(name); }

removeClass(el: any, name: string): void { el.classList.remove(name); }
```

### Is this a regression?
No, it never worked before I think.

### Description
On IE, when using `[ngClass]="isContinentSelected('europe') ? 'active' : 'inactive'"` in a svg, i get a _TypeError_: __Unable to get property 'remove' of undefined or null reference__ 

## 🔬 Minimal Reproduction
[https://stackblitz.com/edit/angular-issue-repro2-camegr](https://stackblitz.com/edit/angular-issue-repro2-camegr)

## 🔥 Exception or Error
<pre><code>
TypeError: Unable to get property 'remove' of undefined or null reference
  at this(./node_modules/@angular/platform-browser/fesm5/platform-browser.js.pre-build-optimizer.js:1113:71)
  at _this(./node_modules/@angular/platform-browser/fesm5/animations.js.pre-build-optimizer.js:240:73)
  at klass(./node_modules/@angular/common/fesm5/common.js.pre-build-optimizer.js:3035:21)
  at e.prototype._toggleClass(./node_modules/@angular/common/fesm5/common.js.pre-build-optimizer.js:3030:13)
  at rawClassVal(./node_modules/@angular/common/fesm5/common.js.pre-build-optimizer.js:3019:56)
  at this(./node_modules/@angular/common/fesm5/common.js.pre-build-optimizer.js:3019:17)
  at klass.set(./node_modules/@angular/common/fesm5/common.js.pre-build-optimizer.js:2929:13)
  at updateProp(./node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:22306:5)
  at Anonymous function(./node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:22104:5)
  at Anonymous function(./node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:23363:13)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.9
Node: 10.9.0
OS: darwin x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@angular/platform-server          7.2.15
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**  
Browsers: Internet Explorer 9/10/11.

**Comment by mvrcrypto** [comment]
For reference: [https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#Browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#Browser_compatibility)  
Maybe, when there is no _classList_, the renderer should work on className ?

**Comment by trotyl** [comment]
> /** IE10 and IE11 requires the following for NgClass support on SVG elements */
> // import 'classlist.js';  // Run `npm install --save classlist.js`.

https://github.com/angular/angular-cli/blob/fe8666073b4f357d4614bf90ac39225980ebe24c/packages/schematics/angular/application/files/src/polyfills.ts.template#L21-L22

**Comment by mvrcrypto** [comment]
Yes, of course 😅
