### ISSUE TITLE
@ngtools/webpack hijacks unrelated imports when Ivy is enabled

### ISSUE THREAD

**Issue by Eugeny** [angular/angular#32611]
# 🐞 bug report

### Affected Package
```@ngtools/webpack```

### Description
With Ivy enabled, ngtools/webpack will force itself onto every possible `import` statement, Typescript or not.

E.g.

```
import 'vendor/fontawesome-pro/fontawesome.scss'
```

leads to:

```
ERROR in Error: ENOTDIR: not a directory, stat 'app/vendor/fontawesome-pro/fontawesome.scss/package.json'
    at Object.statSync (fs.js:898:3)
    at Object.statSync (app/node_modules/graceful-fs/polyfills.js:308:16)
    at Storage.provideSync (app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:98:13)
    at CachedInputFileSystem.statSync (app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:251:28)
    at Observable._subscribe (app/node_modules/@ngtools/webpack/src/webpack-input-host.js:70:52)
    at Observable._trySubscribe (app/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (app/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:29:22)
    at MapOperator.call (app/node_modules/@ngtools/webpack/node_modules/rxjs/internal/operators/map.js:29:23)
    at Observable.subscribe (app/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:24:22)
    at SyncDelegateHost._doSyncCall (app/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.exists (app/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:61:21)
    at WebpackCompilerHost.fileExists (app/node_modules/@ngtools/webpack/src/compiler_host.js:195:44)
    at GeneratedShimsHostWrapper.fileExists (app/node_modules/@angular/compiler-cli/src/ngtsc/shims/src/host.js:72:34)
    at TypeCheckProgramHost.fileExists (app/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/host.js:64:62)
    at getPackageJsonInfo (app/node_modules/typescript/lib/typescript.js:27259:37)
    at loadNodeModuleFromDirectory (app/node_modules/typescript/lib/typescript.js:27250:49)
    at nodeLoadModuleByRelativeName (app/node_modules/typescript/lib/typescript.js:27141:16)
    at tryResolve (app/node_modules/typescript/lib/typescript.js:27094:34)
    at app/node_modules/typescript/lib/typescript.js:27064:69
    at Object.forEach (app/node_modules/typescript/lib/typescript.js:280:30)
    at nodeModuleNameResolverWorker (app/node_modules/typescript/lib/typescript.js:27064:25)
    at nodeModuleNameResolver (app/node_modules/typescript/lib/typescript.js:27057:16)
    at Object.resolveModuleName (app/node_modules/typescript/lib/typescript.js:26834:30)
    at loader_1 (app/node_modules/typescript/lib/typescript.js:89263:99)
    at loadWithLocalCache (app/node_modules/typescript/lib/typescript.js:89096:42)
    at resolveModuleNamesWorker (app/node_modules/typescript/lib/typescript.js:89264:123)
    at resolveModuleNamesReusingOldState (app/node_modules/typescript/lib/typescript.js:89570:19)
    at processImportedModules (app/node_modules/typescript/lib/typescript.js:90833:35)
    at findSourceFile (app/node_modules/typescript/lib/typescript.js:90634:17)
    at app/node_modules/typescript/lib/typescript.js:90480:85
    at getSourceFileFromReferenceWorker (app/node_modules/typescript/lib/typescript.js:90447:34)
    at processSourceFile (app/node_modules/typescript/lib/typescript.js:90480:13)
    at processRootFile (app/node_modules/typescript/lib/typescript.js:90310:13)
    at app/node_modules/typescript/lib/typescript.js:89326:60
    at Object.forEach (app/node_modules/typescript/lib/typescript.js:280:30)
    at Object.createProgram (app/node_modules/typescript/lib/typescript.js:89326:16)
    at TypeCheckContext.calculateTemplateDiagnostics (app/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/context.js:189:39)
    at NgtscProgram.getTemplateDiagnostics (app/node_modules/@angular/compiler-cli/src/ngtsc/program.js:375:26)
    at NgtscProgram.getNgSemanticDiagnostics (app/node_modules/@angular/compiler-cli/src/ngtsc/program.js:168:78)
    at checkDiagnostics (app/node_modules/@ngtools/webpack/src/gather_diagnostics.js:38:27)
    at Object.gatherDiagnostics (app/node_modules/@ngtools/webpack/src/gather_diagnostics.js:68:9)
    at AngularCompilerPlugin._emit (app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:844:65)
    at app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:676:54
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Angular Version:**
```
9.0.0-next.5
```

**Comment by alxhub** [comment]
@Eugeny can you provide a Github repo with a minimal reproduction for this? Thanks!

**Comment by alxhub** [comment]
Closing this issue as without a reproduction it's impossible for us to debug.
