### ISSUE TITLE
why live-server is not working.. I am new here

### ISSUE THREAD

**Issue by Saeem03** [angular/angular#32703]
Serving "C:\Users\User\Desktop\npm" at http://127.0.0.1:8080
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by AndrewKushnir** [comment]
Hi @Saeem03,

It looks like your message doesn't contain enough information to understand what the problem is. Could you please create a new ticket by following a template and providing additional information, like framework and CLI version, OS, etc?

Thank you.

**Comment by Saeem03** [comment]
can this screenshot help? I am just learning to use node.js ... (OS-Windows10)
