### ISSUE TITLE
Updating from 8.0 to 9.0: ERROR in Error: Assertion error: failed to find directive with exportAs: matMenu

### ISSUE THREAD

**Issue by RafaeldelM** [angular/angular#32822]
Hi,
I'm updating my project from 8.0 to 9.0. 
When I run the build, it drops me that error. Any idea?

`ERROR in Error: Assertion error: failed to find directive with exportAs: matMenu
    at /Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28607:31
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28590:29)
    at DirectiveBinder.visitElement (/Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28564:76)
    at Element.visit (/Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:4158:71)
    at /Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28636:67
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28636:27)
    at DirectiveBinder.visitElement (/Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28564:76)
    at Element.visit (/Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:4158:71)
    at /Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28636:67
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28636:27)
    at DirectiveBinder.visitElement (/Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28564:76)
    at Element.visit (/Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:4158:71)
    at /Users/rafaeldelmolino/dev/2shapes-store/node_modules/@angular/compiler/bundles/compiler.umd.js:28636:67`

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by raulicious** [comment]
It's not insufficient information - this is literally the only information that the compiler tells us. I have the same problem blocking me from updating to 9.

**Comment by JoostK** [comment]
@raulicious to be able to investigate an issue certain information is needed, as requested in the issue template. Without this info an issue is not really actionable, as there's no details on e.g. version used, dependencies used, etc. which may affect the situation.

If you can extract a minimum reproduction, possibly by disabling modules one by one, we would gladly look into this issue. Looking at the error message there is absolutely room for improvement, so I'd be keen to look into this problem once there's a reproduction.
