### ISSUE TITLE
Angular.io documentation not loading in Edge/IE11

### ISSUE THREAD

**Issue by RoninKK** [angular/angular#32832]
# 📚 Docs or angular.io bug report

### Description
Getting " Error preparing document 'tutorial/toh-pt1': TypeError: Object doesn't support property or method 'forEach' "
When loading most of the pages on the Angular.io website  in IE11 or Microsoft Edge 40.x and 42.x

![github1](https://user-images.githubusercontent.com/12415261/65646173-2ba1fb80-dfc8-11e9-86c5-3c4b182670dc.gif)
Seeing a blank page when navigating to webpages on Angular.io, i.e.

https://angular.io/tutorial/toh-pt1
https://angular.io/tutorial/toh-pt2

etc..

## 🔬 Minimal Reproduction
Navigate to and Angular.io page using IE 11 or Microsoft Edge 40.x or 42.x
### What's the affected URL?**
Majority of URLs under angular.io:

https://angular.io/tutorial/toh-pt1
https://angular.io/guide/displaying-data

etc..

### Reproduction Steps**
Navigate to 

https://angular.io/tutorial/toh-pt1
https://angular.io/guide/displaying-data

Using IE11 or Microsoft Edge 40.x 42.x

### Expected vs Actual Behavior**
Expected:

https://angular.io/*  pages load with no issues.

Actual:

Blank Screen when navigating to webpages under angular.io

## 🔥 Exception or Error
<pre><code>
ERROR Error: [DocViewer] Error preparing document 'tutorial/toh-pt1': TypeError: Object doesn't support property or method 'forEach'
   at t.prototype.extractHeadingSafeHtml (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:276025)
   at Anonymous function (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:275530)
   at Anonymous function (https://angular.io/polyfills-es5.39ed02ee49092f84045d.js:1:71926)
   at map (https://angular.io/polyfills-es5.39ed02ee49092f84045d.js:1:60758)
   at t.prototype.genToc (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:275510)
   at Anonymous function (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:473432)
   at Anonymous function (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:475742)
   at e.prototype._next (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:412709)
   at e.prototype.next (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:150892)
   at e.prototype._next (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:412792)
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "[DocViewer] Error preparing document 'tutorial/toh-pt1': 
TypeError: Object doesn't support property or method 'forEach'
   at t.prototype.extractHeadingSafeHtml (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:276025)
   at Anonymous function (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:275530)
   at Anonymous function (https://angular.io/polyfills-es5.39ed02ee49092f84045d.js:1:71926)
   at map (https://angular.io/polyfills-es5.39ed02ee49092f84045d.js:1:60758)
   at t.prototype.genToc (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:275510)
   at Anonymous function (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:473432)
   at Anonymous function (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:475742)
   at e.prototype._next (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:412709)
   at e.prototype.next (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:150892)
   at e.prototype._next (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:412792)",
      message: "[DocViewer] Error preparing document 'tutorial/toh-pt1': TypeError: Object doesn't support property or method 'forEach'
   at t.prototype.extractHeadingSafeHtml (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:276025)
   at Anonymous function (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:275530)
   at Anonymous function (https://angular.io/polyfills-es5.39ed02ee49092f84045d.js:1:71926)
   at map (https://angular.io/polyfills-es5.39ed02ee49092f84045d.js:1:60758)
   at t.prototype.genToc (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:275510)
   at Anonymous function (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:473432)
   at Anonymous function (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:475742)
   at e.prototype._next (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:412709)
   at e.prototype.next (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:150892)
   at e.prototype._next (https://angular.io/main-es5.c031d240e815e4bd5049.js:1:412792)",
      name: "Error"
   }

</code></pre>

### Browser info
Tested on IE11, Microsoft Edge 40.x and 42.x

**Comment by dannyskoog** [comment]
So what’s the official backwards compatibility level of the Angular docs?

**Comment by gkalpak** [comment]
I just tested with Edge 44.x and it works fine.
I see the error with IE11. I will look into it.

##
@dannyskoog, you can find here the browsers for which we include polyfills (and thus want the docs app to work) in [aio/browserslist][1]. You can see which browsers this covers [here][2].

That said, we don't actively test on all of them. Evergreen browsers should work. IE may break from time to time and we try (and also welcome pull requests) to fix it on a best effort basis.

[1]: https://github.com/angular/angular/blob/fbad4ff65/aio/browserslist#L8-L12
[2]: https://browserl.ist/?q=%3E+0.5%25%2C+last+2+major+versions%2C+Firefox+ESR%2C+not+dead%2C+IE+11

**Comment by gkalpak** [comment]
The reason this fails is that `NodeList` which is returned by `querySelectorAll()` (e.g. [here][1]) does not support [forEach()][2] on IE. For reference, this was introduced in 007282d2b.

I will send a PR. Thx for reporting, @RoninKK :+1:

[1]: https://github.com/angular/angular/blob/fbad4ff65/aio/src/app/shared/toc.service.ts#L68
[2]: https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach

**Comment by dannyskoog** [comment]
Thanks for that @gkalpak. Good job both of you!

**Comment by RoninKK** [comment]
Great, thank you @gkalpak !
According to the aio/browserslist above you support 2 major versions. Could you add Edge 42 to the PR or are you only looking at addressing this in IE11 at this point?

**Comment by gkalpak** [comment]
I don't see any error in Edge, so I don't know what to fix 🤷‍♂

**Comment by RoninKK** [comment]
@gkalpak @atscott - Just tested again. Looks like it's already been addressed and documentation is now loading with no Issues in both IE 11 and Edge v40/42. Thank you for your quick action!
