### ISSUE TITLE
Unable to change or add new Navigation link

### ISSUE THREAD

**Issue by ethikz** [angular/angular#32857]
# 📚 Docs or angular.io bug report

### Description
I'm new to Angular so forgive my ignorance.

Based on the docs generator listed here, https://github.com/angular/angular/tree/master/aio about contributing to the docs (https://angular.io/guide/docs-style-guide), I am unable to modify the navigation other than title.

Whenever I try to add a new object to the `navigation.json` array, when it builds the docs I get an error. It happens regardless if I add to `TopNav` or even the `SideNav`.

```
"TopBar": [
     ...
    {
      "url": "components",
      "title": "Components"
    }
  ]
```

I see it says that  changing the links is limited to a few on the core team, but even running this locally I am not allowed to changed them?

### Expected vs Actual Behavior**

Basically I am just trying to use the current document/styleguide generator for a library of components already written and want to define my own navigation and route structure.

## 🔥 Exception or Error
<pre><code>

error:   Navigation doc: navigation.json contains invalid urls
[ { path: 'SideNav.1', url: 'components' } ]
error:   Error: processNavigationMap failed
    at Object.$process (~/aio/tools/transforms/angular.io-package/processors/processNavigationMap.js:24:15)
    at ~/aio/node_modules/dgeni/lib/Dgeni.js:183:54
    at _fulfilled (~/aio/node_modules/q/q.js:854:54)
    at ~/aio/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (~/aio/node_modules/q/q.js:816:13)
    at ~/aio/node_modules/q/q.js:624:44
    at runSingle (~/aio/node_modules/q/q.js:137:13)
    at flush (~/aio/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error:   Error processing docs:  Error: processNavigationMap failed
    at Object.$process (~/aio/tools/transforms/angular.io-package/processors/processNavigationMap.js:24:15)
    at ~/aio/node_modules/dgeni/lib/Dgeni.js:183:54
    at _fulfilled (~/aio/node_modules/q/q.js:854:54)
    at ~/aio/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (~/aio/node_modules/q/q.js:816:13)
    at ~/aio/node_modules/q/q.js:624:44
    at runSingle (~/aio/node_modules/q/q.js:137:13)
    at flush (~/aio/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
~/aio/node_modules/q/q.js:155
                throw e;
                ^

Error: processNavigationMap failed
    at Object.$process (~/aio/tools/transforms/angular.io-package/processors/processNavigationMap.js:24:15)
    at ~/aio/node_modules/dgeni/lib/Dgeni.js:183:54
    at _fulfilled (~/aio/node_modules/q/q.js:854:54)
    at ~/aio/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (~/aio/node_modules/q/q.js:816:13)
    at ~/aio/node_modules/q/q.js:624:44
    at runSingle (~/aio/node_modules/q/q.js:137:13)
    at flush (~/aio/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
</code></pre>

### Anything else relevant?

Node 10.16.0
NPM 6.9.0

**Comment by gkalpak** [comment]
The error means that dgeni can't find the `components.json` file in `aio/src/generated/`, which in turn requires an `aio/content/components.md` or `aio/content/components/index.md`. Does any of these files exist?

**Comment by ethikz** [comment]
`aio/content/components/index.md` does exist.  I then ran `docs` and that is where it fails.

**Comment by gkalpak** [comment]
So, in order for a directory in `aio/content/` to be picked up and copied to `aio/src/generated/` (where it can be picked up from `processNavigationMap()`), it must be matched by an entry in [ readFilesProcessor.sourceFiles][1]. 

For example, you could modify [this line][2]:

```diff
-include: CONTENTS_PATH + '/{start,guide,tutorial}/**/*.md',
+include: CONTENTS_PATH + '/{start,guide,tutorial,components}/**/*.md',
```

Note that this only affects top-level directories in `aio/content/`. Sub-directories in `aio/content/guide/` or `aio/content/components/` will be automatically picked up (thx to the `.../**/*.md` pattern).

##
I am going to close this issue, since there is nothing actionable (afaict), but feel free to continue the discussion below.

[1]: https://github.com/angular/angular/blob/e41cbfb585d1e790e5ee8a8b9dc90be0986a0a00/aio/tools/transforms/angular-content-package/index.js#L43-L85
[2]: https://github.com/angular/angular/blob/e41cbfb585d1e790e5ee8a8b9dc90be0986a0a00/aio/tools/transforms/angular-content-package/index.js#L46
