### ISSUE TITLE
Alpha32: IE10/11 doesn't support "remove" in browser_adapter.ts

### ISSUE THREAD

**Issue by jomeier** [angular/angular#3295]
In IE10/11 I get this error message with a simple application (in the end of this text). 

Sorry for the first two messages in german. Didn't get it to switch my IE to the english language :-)

```
TypeError: Das Objekt unterstützt die Eigenschaft oder Methode "remove" nicht

TypeError: Das Objekt unterstützt die Eigenschaft oder Methode "remove" nicht
   at clearNodes (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.32.js:20921:15)
   at appendComponentNodesToHost (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.32.js:16297:7)
   at mergeComponent (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.32.js:16253:5)
   at mergeComponents (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.32.js:16238:9)
   at mergeProtoViewsRecursively (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.32.js:16138:5)
   at mergeProtoViewsRecursively (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.32.js:29185:13)
   at Anonymous function (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.32.js:29571:13)
   at _mergeUnmergedProtoViews (http://localhost:810/javascripts/offline/angular2.dev_2.0.0-alpha.32.js:29
```

```
import {
Component,
View,
bootstrap
} from 'angular2/angular2';

@Component({
    selector: 'app',
})
@View({
    template: '<div></div>',
})
export class MyAppComponent {
    constructor() {
    }
}

bootstrap(MyAppComponent);
```

Chrome and Firefox don't show an error message but also behave "strange" (Zippy example doesn't work where a div is shown/hidden through the click of a mouse).

Setup:
Typescript 1.5 with Visual Studio 2013 or VS Code
Angular 2 Alpha 32
Windows 8.1
IE10 and IE11

**Comment by jomeier** [comment]
@robwormald I'll cite your gitter answer here.
looks like IE doesn't support childEl.remove ():
https://github.com/angular/angular/blob/c2bbda02a12b9803623fb45e1f2f27a7681280b3/modules/angular2/src/dom/browser_adapter.ts#L131-L135

That's also mentioned in:
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove

Regarding to this article:
http://stackoverflow.com/questions/13763/how-do-i-remove-a-child-node-in-html-using-javascript

IE should use ```removeNode()``` instead.

recommends to do it like this:

```
