### ISSUE TITLE
ZoneJS and errors

### ISSUE THREAD

**Issue by aaomidi** [angular/angular#32990]
I'm going to follow up from this comment by @JiaLiPassion 

https://github.com/angular/angular/issues/21841#issuecomment-486005387

No this doesn't really help, sure it reduces it but doesn't get rid of them:

[3664:1003/232319.794:INFO:CONSOLE(234)] "Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:713:5)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at NodeSocket.write (file:///D:/a/1/s/out/vs/base/parts/ipc/node/ipc.net.js:44:25)
    at ProtocolWriter._writeNow (file:///D:/a/1/s/out/vs/base/parts/ipc/common/ipc.net.js:257:26)
    at Immediate.platform.setImmediate (file:///D:/a/1/s/out/vs/base/parts/ipc/common/ipc.net.js:249:26)
    at ZoneDelegate.invokeTask (d:\a\1\s\node_modules\zone.js\dist\zone.js:421:31)
    at Zone.runTask (d:\a\1\s\node_modules\zone.js\dist\zone.js:188:47)
    at ZoneTask.invokeTask (d:\a\1\s\node_modules\zone.js\dist\zone.js:496:34)
    at Immediate.ZoneTask.invoke (d:\a\1\s\node_modules\zone.js\dist\zone.js:485:48)
    at Immediate.timer (d:\a\1\s\node_modules\zone.js\dist\zone.js:2054:29)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)", source: D:\a\1\s\out\bootstrap-window.js (234)

Theres no way for me to see whats happening inside this zone world.

**Comment by JiaLiPassion** [comment]
@aaomidi, if you import `zone.js/dist/zone-error` package, the zone related error will be reduced, but some of the stack will still be there. Currently zone.js doesn't support getting rid of all zone stack traces.

**Comment by JiaLiPassion** [comment]
@aaomidi, if you import `zone.js/dist/zone-error` package, the zone related error will be reduced, but some of the stack will still be there. Currently zone.js doesn't support getting rid of all zone stack traces.
