### ISSUE TITLE
Angular.io documentation not loading in Edge 42.X

### ISSUE THREAD

**Issue by RoninKK** [angular/angular#33031]
# 📚 Docs or angular.io bug report

### Description
Getting " Error preparing document 'tutorial/toh-pt0': 
TypeError: Object doesn't support property or method 'Symbol.iterator'"
When loading most of the pages on the Angular.io website in Microsoft Edge 42.x

Seeing a blank page when navigating to webpages on Angular.io, i.e.
https://angular.io/tutorial/toh-pt1
https://angular.io/tutorial/toh-pt2

### What's the affected URL?**

Majority of URLs under angular.io:
https://angular.io/tutorial/toh-pt1
https://angular.io/guide/displaying-data

### Reproduction Steps**
Navigate to
https://angular.io/tutorial/toh-pt1
https://angular.io/guide/displaying-data
Using Microsoft Edge 42.x

### Expected vs Actual Behavior**

Expected:
https://angular.io/* pages load with no issues.
Actual:
Blank Screen when navigating to webpages under angular.io

## 🔥 Exception or Error

<pre><code>

 ERROR Error: [DocViewer] Error preparing document 'tutorial/toh-pt0': 
TypeError: Object doesn't support property or method 'Symbol.iterator'
   at Anonymous function (https://angular.io/live-example-live-example-module-ngfactory-es2015.69de902f09db17a89e01.js:1:477)
   at s (https://angular.io/live-example-live-example-module-ngfactory-es2015.69de902f09db17a89e01.js:1:387)
   at ia (https://angular.io/main-es2015.ffd6f0b3da0a28fc91c4.js:1:105385)
   at na (https://angular.io/main-es2015.ffd6f0b3da0a28fc91c4.js:1:104315)
   at rc (https://angular.io/main-es2015.ffd6f0b3da0a28fc91c4.js:1:138105)
   at ec (https://angular.io/main-es2015.ffd6f0b3da0a28fc91c4.js:1:136882)
   at _c (https://angular.io/main-es2015.ffd6f0b3da0a28fc91c4.js:1:146370)
   at ko.prototype.create (https://angular.io/main-es2015.ffd6f0b3da0a28fc91c4.js:1:95843)
   at Vr.prototype.create (https://angular.io/main-es2015.ffd6f0b3da0a28fc91c4.js:1:75015)
   at Ee.prototype.initializeComponent (https://angular.io/main-es2015.ffd6f0b3da0a28fc91c4

</code></pre>

### Browser info

Microsoft Edge  42.17134.1.0
### Anything else relevant?
Related to 

https://github.com/angular/angular/issues/32832

Issue was fixed for IE11 and Edge 40.x. However, after further testing,  the issue is still present in Edge 42.X

**Comment by gkalpak** [comment]
Thx for reporting this issue. However, I am a little confused:

In the description you mention the error `TypeError: Object doesn't support property or method 'forEach'`, but in the **Exception or Error** section you have `TypeError: Object doesn't support property or method 'Symbol.iterator'`.

The first error shouldn't happen, because it has been fixed in 85990c321. The second error is also very unexpected, because it seems to be coming from the [live-example][1] component/module, but I don't see any use of iteration there (from a super quick look) 🤷‍♂

To add to my confusion, everything seems to work fine on my machine (with Microsoft Edge 44) 😕

##
@RoninKK, could you please:
1. Clarify what error you are getting.
2. Try if it happens on https://next.angular.io/ as well.
3. Verify whether this happens if you disable/unregister the ServiceWorker.

[1]: https://github.com/angular/angular/blob/ed711418f129c4e1e2b01a890094ea8ed1872a75/aio/src/app/custom-elements/live-example/

**Comment by gkalpak** [comment]
I am afraid we can't do much. It sounds like a bug in Edge 42 (possibly [this bug][1]).
Given that Edge 42 is now an 1.5 years old release (according to [WikiPedia][2]) and things work in the latest Edge version, I don't think it makes sense to spend resources on working arounf the bug in Edge.

(I also don't have access to Edge 42 to investigate this, but if you pinpoint the issue and fix turns out to be simple, feel free to submit a pull request :wink:)

[1]: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18418844/
[2]: https://en.wikipedia.org/wiki/Microsoft_Edge
