### ISSUE TITLE
Broken E2E tests in development mode

### ISSUE THREAD

**Issue by matsko** [angular/angular#3311]
Turns out that when the following commands are run:

`gulp serve.e2e.dev`
`protractor ./protractor-js-dev.conf.js`

The e2e tests are executed and a bunch of the tests inside of **key_events_spec.ts** fail:

```
1) key_events should display correct key names
 Message:
   Expected '' to equal 'enter'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:16:33)
 Message:
   Expected 'shift.' to equal 'shift.enter'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:19:33)
 Message:
   Expected 'control.shift.' to equal 'control.shift.enter'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:22:33)
 Message:
   Expected '' to equal 'space'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:25:33)
 Message:
   Expected '' to equal 'u'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:30:33)
 Message:
   Expected 'control.' to equal 'control.b'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:33:33)
 Message:
   Expected '' to equal 'f1'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:36:33)
 Message:
   Expected 'alt.' to equal 'alt.f1'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:39:33)
 Message:
   Expected 'control.' to equal 'control.f1'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:42:33)

2) key_events should correctly react to the specified key
 Message:
   Expected '' to equal 'You pressed shift.enter!'.
 Stack:
   Error: Failed expectation
       at Object.<anonymous> (/Users/matsko/code/angular/dist/js/cjs/examples/e2e_test/key_events/examples/e2e_test/key_events/key_events_spec.ts:55:34)
```

**Comment by pkozlowski-opensource** [comment]
@divdavem - looks like the e2e tests started to fail, probably due to some changes in the compiler. Maybe you can spot something quickly, as the author of the original code base?

**Comment by ttowncompiled** [comment]
These specs are passing now.
