### ISSUE TITLE
Dart No provider for Http error

### ISSUE THREAD

**Issue by devmetal** [angular/angular#3331]
Hi, i just started a friendship with angular2, i thought i try in dart becaouse i love that language, anyway, i try write n. todo example, but i want a simple restful backend. So the backend is ready, i start developing the client, and when i get the XHR part, i get confused.

Here is my code:
```dart
import 'package:angular2/angular2.dart';
import 'package:angular2/http.dart' show Http, BaseRequestOptions, XHRBackend;
import 'package:angular2/src/reflection/reflection.dart' show reflector;
import 'package:angular2/src/reflection/reflection_capabilities.dart' show ReflectionCapabilities;

var injector = Injector.resolveAndCreate([
    BaseRequestOptions,
    XHRBackend,
    bind(Http).toFactory((backend,defaultOptions) =>
    new Http(backend,defaultOptions),[XHRBackend,BaseRequestOptions])
]);

class Todo {
  String created_at;
  String updated_at;
  String todo;
}

@Injectable()
class TodoService {
  Http _http;

  TodoService(Http http) {
    this._http = http;
  }
}

@Component(
  selector:'todo-app',
  viewInjector: const [TodoService]
)
@View(
  template:'''
  <div class='row'>
    <div class='col-md-8'>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">I have to do:</h3>
        </div>
        <div class="panel-body">
        <label class="control-label">Create new item</label>
          <div class="input-group">
              <input #todotext class="form-control" type="text">
              <span class="input-group-btn">
                  <button class="btn btn-primary" type="button" (click)="addTodo(todotext)">Add</button>
              </span>
          </div>
          <div class="list-group">
            <div class="list-group-item" *ng-for="#todo of todos; #i = index">
              <div class="row-action-primary">
                <i (click) = "setDone(i)" class="mdi-action-done"></i>
              </div>
              <div class="row-content">
                  <h4 class="list-group-item-heading">Todo index: #{{i}}</h4>
                  <p class="list-group-item-text">{{todo}}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class='col-md-4'>
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">I done with:</h3>
        </div>
        <div class="panel-body">
          <ul>
            <li *ng-for="#todo of done">
              {{todo}}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  ''',
  directives: const [NgFor]
)
class TodoApp {

  TodoService _todoServ;

  TodoApp(TodoService service) {
    this._todoServ = service;
  }

  List<String> todos = [
    "Phone calls to friends",
    "Take out the garbage System.gc();"
  ];

  List<String> done = [
    "This is done"
  ];

  addTodo(input) {
    todos.add(input.value);
    input.value = "";
  }

  setDone(int index) {
    String todo = todos.removeAt(index);
    done.add(todo);
  }
}

main() {
  reflector.reflectionCapabilities = new ReflectionCapabilities();
  bootstrap(TodoApp);
}
```

If i run pub serve, the server is stand up, and i get this error in console:
Uncaught Uncaught Error: No provider for Http! (TodoApp -> TodoService -> Http)
Stack Trace:
No provider for Http! (TodoApp -> TodoService -> Http)
    at dart.wrapException (http://localhost:8080/main.dart.js:2804:15)
    at Injector.dart.Injector._getByKey$4 (http://localhost:8080/main.dart.js:13600:17)
    at Injector.dart.Injector._getByDependency$2 (http://localhost:8080/main.dart.js:13550:21)
    at Injector.dart.Injector._new$2 (http://localhost:8080/main.dart.js:13435:41)
    at InjectorInlineStrategy.dart.InjectorInlineStrategy.getObjByKeyId$2 (http://localhost:8080/main.dart.js:13190:20)
    at Injector.dart.Injector._getByKey$4 (http://localhost:8080/main.dart.js:13579:35)
    at Injector.dart.Injector._getByDependency$2 (http://localhost:8080/main.dart.js:13550:21)
    at Injector.dart.Injector._new$2 (http://localhost:8080/main.dart.js:13435:41)
    at InjectorInlineStrategy.dart.InjectorInlineStrategy.hydrate$0 (http://localhost:8080/main.dart.js:13136:25)
    at ElementInjector.dart.ElementInjector.hydrate$3 (http://localhost:8080/main.dart.js:10341:35)dart.wrapException @ js_helper.dart:1384dart._rootHandleUncaughtError_closure.call$0 @ zone.dart:885dart._AsyncCallbackEntry.callback$0 @ future_impl.dart:571dart._asyncRunCallbackLoop @ schedule_microtask.dart:41dart._asyncRunCallback @ schedule_microtask.dart:48dart._AsyncRun__initializeScheduleImmediate_internalCallback.call$1 @ async_patch.dart:48dart.invokeClosure_closure0.call$0 @ js_helper.dart:2024dart._IsolateContext.eval$1 @ isolate_helper.dart:459dart._callInIsolate @ isolate_helper.dart:54dart.invokeClosure @ js_helper.dart:2024(anonymous function) @ js_helper.dart:2044

I don't know, maybe it is a bug, but the Http is injectable, and i don't get whats going on.

**Comment by jeffbcross** [comment]
Hi @devmetal, it looks like you're manually creating an injector which is not actually getting provided to your app (manually creating injectors should usually only be done in tests).

Instead, you should provide your bindings as the second argument to bootstrap, and you should use the already-prepared httpInjectables provided in the `angular2.dart` or `http.dart` modules you're already importing.

`bootstrap(TodoApp, [httpInjectables])`

**Comment by jeffbcross** [comment]
Closing the issue, but feel free to add a comment and mention me if you find problems.

**Comment by devmetal** [comment]
Thank you its working for me :)
