### ISSUE TITLE
error when using bazel build in angular 8

### ISSUE THREAD

**Issue by ipula-cstech** [angular/angular#33319]
INFO: Call stack for the definition of repository 'npm' which is a npm_install (rule definition at /home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/exter
nal/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:294:15):
 - /home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/build_bazel_rules_nodejs/defs.bzl:77:5
 - /var/www/equio_v4/web/WORKSPACE:64:1
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 292
                _create_build_files(repository_ctx, "npm_install", node, r...)
        File "/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 146, in _create_build_files
                fail(("generate_build_file.js failed:...)))
generate_build_file.js failed: 
STDOUT:

STDERR:
fs.js:114
    throw err;
    ^

Error: ENOTDIR: not a directory, open 'npm/BUILD.bazel'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at writeFileSync (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:83:6)
    at generatePackageBuildFiles (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:224:3)
    at pkgs.filter.forEach.pkg (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:113:53)
    at Array.forEach (<anonymous>)
    at generateBuildFiles (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:113:38)
    at main (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:100:3)
    at Object.<anonymous> (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:63:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
ERROR: no such package '@npm//': Traceback (most recent call last):
        File "/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 292
                _create_build_files(repository_ctx, "npm_install", node, r...)
        File "/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 146, in _create_build_files
                fail(("generate_build_file.js failed:...)))
generate_build_file.js failed: 
STDOUT:

STDERR:
fs.js:114
    throw err;
    ^

Error: ENOTDIR: not a directory, open 'npm/BUILD.bazel'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at writeFileSync (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:83:6)
    at generatePackageBuildFiles (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:224:3)
    at pkgs.filter.forEach.pkg (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:113:53)
    at Array.forEach (<anonymous>)
    at generateBuildFiles (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:113:38)
    at main (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:100:3)
    at Object.<anonymous> (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:63:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
ERROR: no such package '@npm//': Traceback (most recent call last):
        File "/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 292
                _create_build_files(repository_ctx, "npm_install", node, r...)
        File "/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 146, in _create_build_files
                fail(("generate_build_file.js failed:...)))
generate_build_file.js failed: 
STDOUT:

STDERR:
fs.js:114
    throw err;
    ^

Error: ENOTDIR: not a directory, open 'npm/BUILD.bazel'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at writeFileSync (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:83:6)
    at generatePackageBuildFiles (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:224:3)
    at pkgs.filter.forEach.pkg (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:113:53)
    at Array.forEach (<anonymous>)
    at generateBuildFiles (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:113:38)
    at main (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:100:3)
    at Object.<anonymous> (/home/ipula/.cache/bazel/_bazel_root/7d47c9500b676f40619e1cd609725676/external/npm/generate_build_file.js:63:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
INFO: Elapsed time: 222.907s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by kyliau** [comment]
Bazel builder for Angular CLI has been deprecated since version 10.
Community support is available via the [Angular Bazel](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular) repo and the [#angular](http://slack.bazel.build/) channel on Slack.
For more info, please see this [migration doc](https://github.com/angular/angular/blob/master/packages/bazel/src/schematics/README.md).
