### ISSUE TITLE
Error in SSR when using a package with Angular Package Format

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#33467]
# 🐞 bug report

### Description

 I created and built my lib using ng-packagr and got angular package format.
When I import module from my lib in universal app I get an error when trying build application
This happens when I add an Input in my component, like this
```js 
@Input()
    get accessKey(): string {
        return this._getOption('accessKey');
    }
    set accessKey(value: string) {
        this._setOption('accessKey', value);
    }
```

## 🔬 Minimal Reproduction

You can reproduce it using the [repo](https://github.com/dxvladislavvolkov/universalExamle)
Following the steps:

npm i
npm run build:ssr
and then you get the error

## 🔥 Exception or Error
<pre><code>

ERROR in ./node_modules/super-toasty/fesm5/super-toasty.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16514:30)
    at Object.forEachChild (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16740:24)
    at checkNodeForDecorators (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16635:21)
    at checkNodeForDecorators (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16692:24)
    at checkNodeForDecorators (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16703:24)
    at checkNodeForDecorators (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
    at visitNode (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16505:24)
    at Object.forEachChild (C:\Users\volkov.vladislav\Downloads\downloadnew\universal\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16599:21)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

8.2.9
</code></pre>

**Anything else relevant?**

**Comment by dxvladislavvolkov** [comment]
The same issue happens if you import MatButtonToggleGroup from @angular/material/button-toggle.

**Comment by IgorMinar** [comment]
This is not a framework or compiler issue, but rather a cli isssue.

can you update to the latest version of @angular/cli v8 and try again?

I'm going to transfer the issue to the cli repo.
