### ISSUE TITLE
ngcc should not crash when scanning a package with "typings" field set to an array value

### ISSUE THREAD

**Issue by dexster** [angular/angular#33646]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Is this a regression?

Probably not

### Description

ng update fails in postinstall running this command: 
`ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
`

## 🔥 Exception or Error
<pre><code>
TypeError: typings.replace is not a function
    at Object.getEntryPointInfo (/Users/brettupton/Development/components/sbg-components/node_modules/@angular/compiler-cli/ngcc/src/packages/entry_point.js:61:74)
    at DirectoryWalkerEntryPointFinder.getEntryPointsForPackage (/Users/brettupton/Development/components/sbg-components/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:91:52)
    at DirectoryWalkerEntryPointFinder.walkDirectoryForEntryPoints (/Users/brettupton/Development/components/sbg-components/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:53:36)
    at /Users/brettupton/Development/components/sbg-components/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:73:76
    at Array.forEach (<anonymous>)
    at DirectoryWalkerEntryPointFinder.walkDirectoryForEntryPoints (/Users/brettupton/Development/components/sbg-components/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:69:18)
    at /Users/brettupton/Development/components/sbg-components/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:43:128
    at Array.reduce (<anonymous>)
    at DirectoryWalkerEntryPointFinder.findEntryPoints (/Users/brettupton/Development/components/sbg-components/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/directory_walker_entry_point_finder.js:43:54)
    at getAllEntryPoints (/Users/brettupton/Development/components/sbg-components/node_modules/@angular/compiler-cli/ngcc/src/main.js:264:23)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>9.0.0-rc.1<code>

</code>Angular CLI: 9.0.0-rc.0
Node: 12.3.1
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.0-rc.0
@angular-devkit/build-angular              0.900.0-rc.0
@angular-devkit/build-ng-packagr           0.900.0-rc.0
@angular-devkit/build-optimizer            0.900.0-rc.0
@angular-devkit/build-webpack              0.900.0-rc.0
@angular-devkit/core                       9.0.0-rc.0
@angular-devkit/schematics                 9.0.0-rc.0
@angular/cdk                               8.2.3
@angular/cli                               9.0.0-rc.0
@angular/material                          8.2.3
@angular/material-moment-adapter           8.2.3
@ngtools/webpack                           9.0.0-rc.0
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        9.0.0-rc.0
@schematics/update                         0.900.0-rc.0
ng-packagr                                 9.0.0-rc.1
rxjs                                       6.5.3
typescript                                 3.6.4
webpack                                    4.39.2
</pre>

**Anything else relevant?**
I have an npm package, csv-parse, which has this array in the types section

```
"types": [
    "./lib/index.d.ts",
    "./lib/sync.d.ts"
  ]
```
This line in entry_point.js expects a string
`var metadataPath = file_system_1.resolve(entryPointPath, typings.replace(/\.d\.ts$/, '') + '.metadata.json');
`

**Comment by dexster** [comment]
Just realised I should've created this in angular-cli repo. Do I need to close and open a new one there?

**Comment by JoostK** [comment]
@dexster  actually this is the correct repo, it's caused by ngcc which is maintained here :)

**Comment by filipbech** [comment]
I have the same issue

**Comment by kungufli** [comment]
I also had a problem while upgrading `@angular/core` from `9.0.0-rc.0` to `9.0.0-rc.1` with a failure in postinstall running the same command:

`ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`

However I got a different error (but possibly related, I suppose):

```aprete@MacBook-Pro my-app % ng update --next
Using package manager: 'npm'
Collecting installed dependencies...
Found 32 dependencies.
    We analyzed your package.json, there are some packages to update:
    
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/core                      9.0.0-rc.0 -> 9.0.0-rc.1 ng update @angular/core --next
aprete@MacBook-Pro my-app % ng update @angular/core --next
Using package manager: 'npm'Collecting installed dependencies...
Found 32 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/core @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
    Updating package.json with dependency @angular/compiler-cli @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
    Updating package.json with dependency @angular/language-service @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
    Updating package.json with dependency @angular/forms @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
    Updating package.json with dependency @angular/compiler @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
    Updating package.json with dependency @angular/animations @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
    Updating package.json with dependency @angular/common @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
    Updating package.json with dependency @angular/platform-browser @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
    Updating package.json with dependency @angular/router @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "9.0.0-rc.1" (was "9.0.0-rc.0")...
UPDATE package.json (1523 bytes)
⠹ Installing packages...
> my-app@0.0.0 postinstall /Users/aprete/Sites/my-app
> ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points

Error: The ngcc compiler has changed since the last ngcc build.
Please remove "/Users/aprete/Sites/my-app/node_modules" and try again.
    at Object.hasBeenProcessed (/Users/aprete/Sites/my-app/node_modules/@angular/compiler-cli/ngcc/src/packages/build_marker.js:44:19)
    at analyzeEntryPoints (/Users/aprete/Sites/my-app/node_modules/@angular/compiler-cli/ngcc/src/main.js:86:62)
    at new ClusterMaster (/Users/aprete/Sites/my-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:40:30)
    at ClusterExecutor.<anonymous> (/Users/aprete/Sites/my-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/executor.js:40:34)
    at step (/Users/aprete/Sites/my-app/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/aprete/Sites/my-app/node_modules/tslib/tslib.js:117:57)
    at /Users/aprete/Sites/my-app/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/aprete/Sites/my-app/node_modules/tslib/tslib.js:106:16)
    at ClusterExecutor.execute (/Users/aprete/Sites/my-app/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/executor.js:35:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.0.0 postinstall: `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aprete/.npm/_logs/2019-11-07T10_24_47_521Z-debug.log
✖ Package install failed, see above.
The update failed. See above.
```
