### ISSUE TITLE
Use released typescript 1.5.3

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#3379]
We should upgrade to the upstream typescript now that https://github.com/Microsoft/TypeScript/issues/1168 is resolved.

**Comment by alexeagle** [comment]
Have an issue with this.
@mhevery has done some clever stuff with the definitions of our decorators, such that they can be used for ES5 DSL as well. So they are callable and newable.

For parameter decorators, I get an error from the compiler:
```
angular2/src/router/router_outlet.ts (31, 56): Unable to resolve signature of parameter decorator when called as an expression.
```
Here is the code
https://github.com/angular/angular/blob/68a581a04ce4afbc3598ba283adb9e713c8dac55/modules/angular2/src/router/router_outlet.ts#L31
you can see this uses `@Attribute('name')` as a parameter decorator.

`Attribute` is defined here with type `AttributeFactory`
https://github.com/angular/angular/blob/68a581a04ce4afbc3598ba283adb9e713c8dac55/modules/angular2/src/core/annotations/decorators.ts#L366
and I cannot replace that type with `lib.d.ts:ParameterDecorator` because we need the additional constructor signature.

So I figured the right thing to do is to add the `ParameterDecorator`s signature
`(target: Object, propertyKey: string | symbol, parameterIndex: number): void;`
as an additional method on `AttributeFactory` so that it should be assignable to a `ParameterDecorator`
(as required by the spec: https://github.com/Microsoft/TypeScript/issues/2249)

But that doesn't resolve the compile error.
I probably need some decorator expert help.

**Comment by alexeagle** [comment]
Work in progress: https://github.com/angular/angular/compare/master...alexeagle:ts1.5.3?expand=1

**Comment by alexeagle** [comment]
Writing it up in detail seems to have helped me. It's the return type of `AttributeFactory(name:string)` that must be assignable to a `ParemeterDecorator`, so adding the signature
`(target: Object, propertyKey: string | symbol, parameterIndex: number): void;`
to `TypeDecorator`
https://github.com/angular/angular/blob/68a581a04ce4afbc3598ba283adb9e713c8dac55/modules/angular2/src/util/decorators.ts#L46

seems to fix it. Now I get a compiler crash in emitSerializedTypeNode instead :)

**Comment by alexeagle** [comment]
I'm on typescript@1.6.0-dev.20150729
and the stack is
```
TypeError: [DiffingTSCompiler]: Cannot read property 'kind' of undefined
    at emitSerializedTypeNode (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:32574:29)
    at emitSerializedTypeOfNode (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:32558:25)
    at emitSerializedParameterTypesOfNode (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:32705:37)
    at emitSerializedTypeMetadata (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:32741:25)
    at emitDecoratorsOfConstructor (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:32355:17)
    at emitDecoratorsOfClass (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:32322:17)
    at emitClassLikeDeclarationBelowES6 (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:32280:17)
    at emitClassLikeDeclaration (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:32071:21)
    at emitClassDeclaration (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:32067:24)
    at emitJavaScriptWorker (/Users/alexeagle/Projects/angular/node_modules/typescript/bin/typescript.js:34327:32)
```

**Comment by alexeagle** [comment]
We decided that we cannot ask users to use 1.6, so angular should continue to build with 1.5.
We could optionally add another build that confirms we work on 1.6 as well.

**Comment by alexeagle** [comment]
Fixed by https://github.com/angular/angular/pull/3400
