### ISSUE TITLE
Add missing documentation for using schematics with array options

### ISSUE THREAD

**Issue by d-koppenhagen** [angular/angular#33851]
# 📚 Docs or angular.io bug report

### Description

Hello! my recently opened issue https://github.com/angular/angular-cli/issues/16104 has been closed (thanks for fixing it!) Unfortunatly I couldn't find any point for how to set multi select options via command line in the docs.
My expectation was to do it this way:

```bash
ng add packageName --param=foo,bar,baz
``` 

or something similar but I tried out a lot of ways without getting it working.
I expected to find it in the @next branch for angular.io -- maybe in the guards section (https://next.angular.io/cli/generate#guard-command : as `--implements` is using it) but it seems not to be documented there as well currently.

Playing a bit around, I found out that this seems to be the solution:

```bash
ng g g foo-bar --implements="CanActivate, CanLoad"
```

This should be documented better. However trying to implement this behaviour the same way failed for some reason. 
When I configure my schematic this way:

```bash
{
  "$schema": "http://json-schema.org/schema",
  "id": "ngx-semantic-version",
  "title": "ngx-semantic-version Schema",
  "description": "configure commitlint, husky, commitizen and standard-version configuration",
  "type": "object",
  "properties": {
    "packages": {
      "type": "array",
      "description": "select the packages that should to be installed and configured",
      "uniqueItems": true,
      "items": {
        "type": "string"
      },
      "default": ["commitlint", "commitizen", "husky", "standard-version"],
      "x-prompt": {
        "message": "What packages do you want to be installed and configured?",
        "type": "list",
        "multiselect": true,
        "items": ["commitlint", "commitizen", "husky", "standard-version"]
      }
    },
  },
  "required": ["packages"]
}
```

and I run my schematic locally using `schematics .:ng-add --debug=false --packages="commitlint, husky"`, I will receive the following output:

```bash
Error: Schematic input does not validate against the Schema: {"packages":"commitlint, husky"}
Errors:

  Data path ".packages" should be array.
    at MapSubscriber.registry.compile.pipe.operators_1.map.result [as project] (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/@angular-devkit/schematics/tools/schema-option-transform.js:31:27)
    at MapSubscriber._next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ThrowIfEmptySubscriber._next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/throwIfEmpty.js:44:26)
    at ThrowIfEmptySubscriber.Subscriber.next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/usr/local/lib/node_modules/@angular-devkit/schematics-cli/node_modules/rxjs/internal/Subscriber.js:66:18)
```

## 🔬 Minimal Reproduction
see above descriptions or https://github.com/d-koppenhagen/ngx-semantic-version/tree/ng9

### What's the affected URL?**
https://next.angular.io

## 📷Screenshot
<img width="1087" alt="Screen Shot 2019-11-15 at 12 30 35" src="https://user-images.githubusercontent.com/4279702/68940576-d43c3280-07a3-11ea-92f4-755258b2fed1.png">

## 🔥 Exception or Error
see above image / pasted output.

**Comment by d-koppenhagen** [comment]
I tried out some modifications but they lead to the same result:

**schema.d.ts:**
```ts
/**
 * ngx-semantic-version Schema
 * configure commitlint, husky, commitizen and standard-version configuration
 */
export interface NgxSemanticVersion {
    /**
     * select the packages that should to be installed and configured
     */
    packages: ("commitlint" | "commitizen" | "husky" | "standard-version")[];
    /**
     * Skip installing the npm packages
     */
    skipInstall?: boolean;
    /**
     * configure an issue prefix that should be checked by each commit
     */
    issuePrefix?: string;
    /**
     * force to override existing configuration params and files
     */
    force?: boolean;
}
```

**schema.json:**

```json
{
  "$schema": "http://json-schema.org/schema",
  "id": "ngx-semantic-version",
  "title": "ngx-semantic-version Schema",
  "description": "configure commitlint, husky, commitizen and standard-version configuration",
  "type": "object",
  "properties": {
    "packages": {
      "type": "array",
      "description": "select the packages that should to be installed and configured",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "enum": ["commitlint", "commitizen", "husky", "standard-version"],
        "type": "string"
      },
      "default": ["commitlint", "commitizen", "husky", "standard-version"],
      "x-prompt": "What packages do you want to be installed and configured?"
    },
  },
}
```

**Comment by d-koppenhagen** [comment]
I wonder why it works for  `--implements` within guard creation. Maybe the magic is hidden in the `schema.d.ts` which is unfortunately not checked in. But there are two things imported here: https://github.com/angular/angular-cli/blob/9.0.x/packages/schematics/angular/guard/index.ts#L25
Would you mind to share the content of `schema.d.ts`?

**Comment by d-koppenhagen** [comment]
Okay, I just forked the angular-cli project and built it locally. The schema produced for the guard seems to look basically like this:

```ts
export interface Schema {
    ...
    implements?: Implement[];
   ...
}

export enum Implement {
    CanActivate = "CanActivate",
    CanActivateChild = "CanActivateChild",
    CanDeactivate = "CanDeactivate",
    CanLoad = "CanLoad",
}
```

I tried to copy the schema and implementation into a very simple example repo:
https://github.com/d-koppenhagen/ngx-multi-select-schematic

But the result will be the same as described in the original issue text. Probably it's a bug and not just a not documented feature?

**Comment by kapunahelewong** [comment]
Update: Docs team would like engineering input here on what exactly to document and/or fix in the current documentation. Thank you!
