### ISSUE TITLE
(dart) using routerDirectives on view annotation, crashes on browser

### ISSUE THREAD

**Issue by avoivo** [angular/angular#3387]
i am using dartium and the error is Exception: Uncaught Error: Cannot find method onClick

Do you have any idea of what is causing this?

Thanx in advance

**Comment by avoivo** [comment]
I changed to version alpha33 and the error changed to

EXCEPTION: Class 'String' has no instance method 'fold'.

NoSuchMethodError: method not found: 'fold'
Receiver: "start"
Arguments: [Instance(length:0) of '_GrowableList', Closure: (dynamic, dynamic) => dynamic] in [start in null]
ORIGINAL EXCEPTION: Class 'String' has no instance method 'fold'.

NoSuchMethodError: method not found: 'fold'
Receiver: "start"
Arguments: [Instance(length:0) of '_GrowableList', Closure: (dynamic, dynamic) => dynamic]
ORIGINAL STACKTRACE:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ListWrapper.reduce (package:angular2/src/facade/collection.dart:128:17)
#3      splitAndFlattenLinkParams (package:angular2/src/router/router.dart:303:22)
#4      Router.generate (package:angular2/src/router/router.dart:228:32)
#5      RouterLink.routeParams= (package:angular2/src/router/router_link.dart:53:41)
#6      _AppComponent_ChangeDetector0.__detectChangesInRecords (package:boilerplate_app/components/app2.ng_deps.dart:169:22)
#7      _AppComponent_ChangeDetector0.detectChangesInRecords (package:boilerplate_app/components/app2.ng_deps.dart:125:7)
#8      AbstractChangeDetector.runDetectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:60:10)
#9      AbstractChangeDetector._detectChangesInShadowDomChildren (package:angular2/src/change_detection/abstract_change_detector.dart:82:12)
#10     AbstractChangeDetector.runDetectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:63:10)
#11     AbstractChangeDetector.detectChanges (package:angular2/src/change_detection/abstract_change_detector.dart:53:10)
#12     LifeCycle.tick (package:angular2/src/core/life_cycle/life_cycle.dart:75:28)
#13     commonBootstrap.<anonymous closure>.<anonymous closure> (package:angular2/src/core/application_common.dart:318:12)
#14     NgZone._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:231:40)
#15     _rootRun (dart:async/zone.dart:900)
#16     _ZoneDelegate.run (dart:async/zone.dart:503)
#17     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:207:21)
#18     NgZone._runUnary (package:angular2/src/core/zone/ng_zone.dart:231:7)
#19     _CustomZone.runUnary (dart:async/zone.dart:811)
#20     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#21     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#22     _Future._completeWithValue (dart:async/future_impl.dart:368)
#23     Future.wait.<anonymous closure> (dart:async/future.dart:299)
#24     NgZone._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:231:40)
#25     _rootRun (dart:async/zone.dart:900)
#26     _ZoneDelegate.run (dart:async/zone.dart:503)
#27     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:207:21)
#28     NgZone._runUnary (package:angular2/src/core/zone/ng_zone.dart:231:7)
#29     _CustomZone.runUnary (dart:async/zone.dart:811)
#30     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#31     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#32     _Future._completeWithValue (dart:async/future_impl.dart:368)
#33     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#34     NgZone._scheduleMicrotask.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:240:11)
#35     _rootRun (dart:async/zone.dart:904)
#36     _ZoneDelegate.run (dart:async/zone.dart:503)
#37     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:207:21)
#38     _CustomZone.run (dart:async/zone.dart:803)
#39     _CustomZone.runGuarded (dart:async/zone.dart:709)
#40     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#42     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#43     _ScheduleImmediateHelper._handleMutation (dart:html:42503)

**Comment by avoivo** [comment]
Just figured out that i had a router-link attribute defined the wrong way.
