### ISSUE TITLE
Vague error when a comment is inside interpolated expression

### ISSUE THREAD

**Issue by coreyknapp** [angular/angular#34084]
# 🐞 bug report

### Affected Package

 The exception is inside @angular/compiler

### Is this a regression?

Untested

### Description

Using comments inside an interpolated expression (like {{ //TODO }}) creates no build errors but generates the below exception. While it's fine that angular doesn't support such expressions, the exception gives no clue as to what went wrong.

## 🔬 Minimal Reproduction

[https://stackblitz.com/edit/angular-issue-repro2-h5bf6a](https://stackblitz.com/edit/angular-issue-repro2-h5bf6a)

## 🔥 Exception or Error
<pre><code>
Uncaught TypeError: Cannot read property 'visit' of undefined
    at convertPropertyBinding (compiler.js:7099)
    at compiler.js:22052
    at Array.map (<anonymous>)
    at createUpdateStatements (compiler.js:22049)
    at compiler.js:22031
    at Array.map (<anonymous>)
    at ViewBuilder$1._createNodeExpressions (compiler.js:22028)
    at ViewBuilder$1.build (compiler.js:21509)
    at ViewCompiler.compileComponent (compiler.js:21434)
    at JitCompiler._compileTemplate (compiler.js:25710)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect           0.801.3
@angular-devkit/build-angular       0.801.3
@angular-devkit/build-optimizer     0.801.3
@angular-devkit/build-webpack       0.801.3
@angular-devkit/core                8.1.3
@angular-devkit/schematics          8.3.19
@angular/animations                 8.1.3
@angular/cli                        8.3.19
@angular/common                     8.1.3
@angular/compiler                   8.1.3
@angular/compiler-cli               8.1.3
@angular/forms                      8.1.3
@angular/language-service           8.1.3
@angular/platform-browser           8.1.3
@angular/platform-browser-dynamic   8.1.3
@angular/router                     8.1.3
@ngtools/webpack                    8.1.3
@schematics/angular                 8.3.19
@schematics/update                  0.803.19
rxjs                                6.5.3
typescript                          3.4.5
webpack                             4.35.2
</code></pre>

**Comment by ajitsinghkaler** [comment]
Can I take this seems easy just a message change

**Comment by pkozlowski-opensource** [comment]
Still the case with 8.x (original stackblitz was done with 6.x): https://stackblitz.com/edit/angular-8tt4yv

**Comment by alxhub** [comment]
And still the case today. Confirmed.

**Comment by JeanMeche** [comment]
Still an issue in v20.1  with a slightly different build error message : 

```
  Error: AssertionError: Unsupported reification of ir.Expression kind: EmptyExpr
      at reifyIrExpression (file:///Users/matthieuriegler/dev/test/node_modules/@angular/compiler/fesm2022/compiler.mjs:24032:19)
      at transformExpressionsInExpression (file:///Users/matthieuriegler/dev/test/node_modules/@angular/compiler/fesm2022/compiler.mjs:10391:12)
      at transformExpressionsInInterpolation (file:///Users/matthieuriegler/dev/test/node_modules/@angular/compiler/fesm2022/compiler.mjs:10146:40)
      at transformExpressionsInOp (file:///Users/matthieuriegler/dev/test/node_modules/@angular/compiler/fesm2022/compiler.mjs:10190:13)
      at reifyUpdateOperations (file:///Users/matthieuriegler/dev/test/node_modules/@angular/compiler/fesm2022/compiler.mjs:23897:9)
```
