### ISSUE TITLE
Unable to write a reference to CdkCopyToClipboard

### ISSUE THREAD

**Issue by rkramakrishna17** [angular/angular#34303]
# 🐞 bug report
Error: Error on worker #2: Error: Unable to write a reference to CdkCopyToClipboard in <projectRoot>/node_modules/@angular/cdk/esm2015/clipboard/copy-to-clipboard.js from <projectRoot>/node_modules/@angular/cdk/esm2015/clipboard/clipboard-module.js

### Affected Package
I think this issue is caused by @angular/cdk: 9.0.0-rc.5

 The issue is caused by package @angular/....

### Is this a regression?
This issue was not produced in angular 8.3.2 but started coming from beta releases of angular 9. Checked on r.c.5 

 Yes, the previous version in which this bug was not present was: ....

### Description
Compiling @angular/cdk/clipboard : esm2015 as esm2015
Error: Error on worker #2: Error: Unable to write a reference to CdkCopyToClipboard in <projectRoot>/node_modules/@angular/cdk/esm2015/clipboard/copy-to-clipboard.js from <projectRoot>/node_modules/@angular/cdk/esm2015/clipboard/clipboard-module.js
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
Git hub repository https://github.com/rkramakrishna17/angular9cdkissue

## 🔥 Exception or Error
<pre><code>
Compiling @angular/cdk/clipboard : esm2015 as esm2015
Error: Error on worker #2: Error: Unable to write a reference to CdkCopyToClipboard in /node_modules/@angular/cdk/esm2015/clipboard/copy-to-clipboard.js from /node_modules/@angular/cdk/esm2015/clipboard/clipboard-module.js
at ReferenceEmitter.emit (/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:55:19)
at Object.toR3Reference (/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:165:31)
at NgModuleDecoratorHandler._toR3Reference (/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:352:31)
at /node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:174:83
at Array.map ()
at NgModuleDecoratorHandler.analyze (/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:174:48)
at Object.analyzeDecorators (/node_modules/@angular/compiler-cli/ngcc/src/analysis/util.js:75:38)
at DecorationAnalyzer.analyzeClass (/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:141:40)
at /node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:134:55
at Array.map ()
at ClusterMaster.onWorkerMessage (/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
at /node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
at ClusterMaster. (/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
at step (/node_modules/tslib/tslib.js:136:27)
at Object.next (/node_modules/tslib/tslib.js:117:57)
at /node_modules/tslib/tslib.js:110:75
at new Promise ()
at Object.__awaiter (/node_modules/tslib/tslib.js:106:16)
at EventEmitter. (/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:232:32)
at EventEmitter.emit (events.js:196:13)
Compiling @angular/cdk/clipboard : esm5 as esm5
Compiling @angular/cdk/clipboard : main as umd
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! enreport@0.0.1 postinstall: ngcc
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the enreport@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /.npm/_logs/2019-12-08T05_48_42_324Z-debug.log

A clear and concise description of the problem...

</code></pre>

## 🌍  Your Environment
**Angular Version:** 9.0.0-rc.5
**Node Version:** v12.0.0
<pre><code>

</code></pre>

**Comment by santoshyadav198613** [comment]
Hi,
If you think it's caused by CDK, you can raise it in Angular Components repository, as CDK is managed in components repo.

**Comment by rkramakrishna17** [comment]
Hi.. Thanks for the info.

**Comment by rkramakrishna17** [comment]
Moved this ticket to components.
https://github.com/angular/components/issues/17897

**Comment by JoostK** [comment]
Actually, this was rightfully reported here. Thanks for reporting!

This issue has been fixed in #34212 but it has not been released yet. It will be available in the next release.

Could you please close angular/components#17897? Thanks!

**Comment by rkramakrishna17** [comment]
Thanks @JoostK
