### ISSUE TITLE
HTML5LocationStrategy doesn't work (even with base attr)

### ISSUE THREAD

**Issue by marian2js** [angular/angular#3441]
Hello, I'm getting this error when I tried to use HTML5LocationStrategy:

```
Error during instantiation of LocationStrategy! (App -> Router -> function (_platformStrategy, href) {
        var $__0 = this;
        this._platformStrategy = _platformStrategy;
        this._subject = new EventEmitter();
        var browserBaseHref = isPresent(href) ? href : this._platformStrategy.getBaseHref();
        if (isBlank(browserBaseHref)) {
          throw new BaseException("No base href set. Either provide a binding to \"appBaseHrefToken\" or add a base element.");
        }
        this._baseHref = stripTrailingSlash(stripIndexHtml(browserBaseHref));
        this._platformStrategy.onPopState((function(_) {
          return $__0._onPopState(_);
        }));
      } -> LocationStrategy). ORIGINAL ERROR: TypeError: baseElement.attr is not a function

 ORIGINAL STACK: TypeError: baseElement.attr is not a function
    at getBaseElementHref (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:20758:24)
    at BrowserDomAdapter.execute.BrowserDomAdapter.getBaseHref (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:21164:24)
    at new $__0 (https://code.angularjs.org/2.0.0-alpha.32/router.dev.js:491:32)
    at execute.ReflectionCapabilities.factory (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:8752:26)
    at Injector.execute.Injector._new (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27630:25)
    at InjectorDynamicStrategy.execute.InjectorDynamicStrategy.getObjByKeyId (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27502:48)
    at Injector.execute.Injector._getByKeyUnbounded (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27761:39)
    at Injector.execute.Injector._getByKey (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27715:27)
    at Injector.execute.Injector._getByDependency (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27703:27)
    at Injector.execute.Injector._new (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27601:68)

Error: null
    at InstantiationError.BaseException (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:7724:25)
    at InstantiationError.AbstractBindingError (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:9577:66)
    at new InstantiationError (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:9624:64)
    at Injector.execute.Injector._new (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27694:21)
    at InjectorDynamicStrategy.execute.InjectorDynamicStrategy.getObjByKeyId (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27502:48)
    at Injector.execute.Injector._getByKeyUnbounded (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27761:39)
    at Injector.execute.Injector._getByKey (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27715:27)
    at Injector.execute.Injector._getByDependency (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27703:27)
    at Injector.execute.Injector._new (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27601:68)
    at InjectorDynamicStrategy.execute.InjectorDynamicStrategy.getObjByKeyId (https://code.angularjs.org/2.0.0-alpha.32/angular2.dev.js:27502:48)
```

I already added the attribute base on the head of my HTML, which in other ticket solved a similar issue.

Here is the bootstrap of my app:

```js
import { App } from './app.ts';
import { bootstrap, bind, httpInjectables } from 'angular2/angular2';
import { routerInjectables, HTML5LocationStrategy, LocationStrategy, appBaseHrefToken } from 'angular2/router';
import { reflector } from 'angular2/src/reflection/reflection';
import { ReflectionCapabilities } from 'angular2/src/reflection/reflection_capabilities';

export function main() {
    reflector.reflectionCapabilities = new ReflectionCapabilities();

    // I tried to fix the issue with this line, but it didn't change anything
    bind(appBaseHrefToken).toValue('/');

    bootstrap(App, [
        routerInjectables,
        httpInjectables,
        bind(LocationStrategy).toClass(HTML5LocationStrategy)
    ]);
}
```

I think that the error could be in this line:
https://github.com/angular/angular/blob/70bc485755e4bc65c27c2fa8998618cb780ac931/modules/angular2/src/dom/browser_adapter.ts#L308

It shouldn't be `return baseElement.getAttribute('href');`?

My environment:
Angular 2.0.0-alpha.32.
Google Chrome 43.0.2357.132 (64-bit) on Fedora 22.
I only have the necessary third party libraries: traceur, systemjs and typescript.

Many Thanks!

**Comment by gdi2290** [comment]
please see pending PR https://github.com/angular/angular/pull/3214 and current workaround fix https://github.com/angular/angular/commit/8296dcec09d9b8be0d4cfcc492000d5cc401cfa0#commitcomment-12314240

**Comment by marian2js** [comment]
That PR fixes the issue, many thanks!
