### ISSUE TITLE
ngcc: packages that fail with errors causes a crash

### ISSUE THREAD

**Issue by JoostK** [angular/angular#34500]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler-cli

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.0.0-rc.6

### Description

When ngcc processes a package that fails to compile, a fatal error that crashes the compiler occurs.

## 🔬 Minimal Reproduction

For example `angular-tree-component` fails to compile:
https://app.circleci.com/jobs/github/angular/ngcc-validation/2459/parallel-runs/1?filterBy=ALL

## 🔥 Exception or Error
<pre><code>
ERROR in Cannot read property 'injectorImports' of undefined
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: 9.0.0-rc.7
</code></pre>

**Anything else relevant?**
n/a

**Comment by exequiel09** [comment]
Experienced the same: 

<img width="823" alt="Screen Shot 2019-12-20 at 8 42 50 AM" src="https://user-images.githubusercontent.com/1289472/71220784-d34b7300-2304-11ea-8db2-85fa727b66c1.png">

**Comment by NicolasKritter** [comment]
Same error, after some investigation the error seems to be from this file :
`node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\ng_module.js`

at the beginning  of the function `NgModuleDecoratorHandler.prototype.compile = function (node, analysis, resolution)`
at line 347

` var ngInjectorDef = compiler_1.compileInjector(tslib_1.__assign(tslib_1.__assign({}, analysis.inj), { imports: tslib_1.__spread(analysis.inj.imports, resolution.injectorImports) }));` 

The problem is that the variable ` resolution` is undefined

**Comment by agustinvinao** [comment]
Trying to compile with bazel, same error for another module:

```Compiling @angular/common/http/testing : main as umd
Error: Error on worker #4: TypeError: Cannot read property 'injectorImports' of undefined
    at NgModuleDecoratorHandler.compile (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:347:174)
    at _loop_1 (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:205:38)
    at DecorationAnalyzer.compileClass (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:220:21)
    at /Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:194:41
    at Array.map (<anonymous>)
    at DecorationAnalyzer.compileFile (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:193:64)
    at /Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:133:90
    at Array.map (<anonymous>)
    at DecorationAnalyzer.analyzeProgram (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:133:47)
    at Transformer.analyzeProgram (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/packages/transformer.js:123:57)
    at ClusterMaster.onWorkerMessage (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
    at /Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
    at ClusterMaster.<anonymous> (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
    at step (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/tslib/tslib.js:117:57)
    at /Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/tslib/tslib.js:106:16)
    at EventEmitter.<anonymous> (/Users/agustinvinao/development/codespacelabs/bookkeeper/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:232:32)
    at EventEmitter.emit (events.js:210:5)
```

**Comment by grapehunter** [comment]
The same error when running `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points`
![image](https://user-images.githubusercontent.com/3354458/71442283-3d6a7a80-2740-11ea-97de-7890a1e1c74d.png)
First execution error, second execution is correct

**Comment by ottodranik** [comment]
Same problem. Tried to upgrade to next because ngx-echarts not compiled with ngcc 8.3.9-21 and got this error on upgrade.

PS. Don't want to whine, but it's really bad, when you read a lot of "fixes" and "improvements" in another angular-RC and in generally you got a knew critical bugs. 50% of my coding time I loose on a fight with this framework and not for a coding.

**Comment by dave0688** [comment]
+1

**Comment by sovushka-utrom** [comment]
Same for me for Angular: 9.0.0-rc.7:  
`Compiling @angular/cdk/observers : es2015 as esm2015    
Error: Error on worker #3: TypeError: Cannot read property 'injectorImports' of undefined  
    at NgModuleDecoratorHandler.compile    
...  
    at EventEmitter.emit (events.js:182:13)    
Compiling @angular/common/http : es2015 as esm2015`.    

Happens on `npm install` that calls the recommended   
` "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"`.

**Comment by sovushka-utrom** [comment]
I had to remove all the node modules folder & run `npm install` again. Then it worked.

**Comment by gustavobmichel** [comment]
Have you guys found a way to check which package is causing the issue? I tried to looking at the logs but it doesn't seem to include the package with the problem.

**Comment by benelliott** [comment]
@gustavobmichel My logs show the symbol that caused the issue. Can you upload yours?

**Comment by gnanakeethan** [comment]
I am using Yarn, and I tried doing a Yarn Upgrade. Then ran the Yarn Install. It worked without an issue.

**Comment by vokeit-gschuster** [comment]
Just FYI, when using the nightly build the bug is fixed.
Simply download @angular/compiler-cli-builds (https://github.com/angular/compiler-cli-builds) and replace it in node_modules.

**Comment by JoostK** [comment]
@vokeit-gschuster The bug itself has not been fixed, the fix PR is still pending. However, it may be that a bug which was causing the library to fail compiling has been fixed, in which case you won't observe the bug anymore.

**Comment by vokeit-gschuster** [comment]
In my case, ngcc failed with the above given message on @angular/http/testing when only running it on node_modules ("ngcc" in the workspace root).

**Comment by wuboy0307** [comment]
In my case, ngcc failed with the above given message on angular-tree-component when compile to esm5

```
Compiling angular-tree-component : module as esm5
Error: Error on worker #3: TypeError: Cannot read property 'injectorImports' of undefined
```

**Comment by kaito3desuyo** [comment]
Exact same error on 9.0.0-rc.10.
```
0% compiling
Compiling <my-angular-component-library> : es2015 as esm2015

ERROR in Cannot read property 'injectorImports' of undefined
```
