### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by skydarkness47** [angular/angular#34577]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

2707/5000
I have a problem with angular and typed in ionic, when compiling I receive the following error:
can help me?
Runtime Error
```
Uncaught (in promise): TypeError: Object(...) is not a function TypeError: Object(...) is not a function at NativeAudio.preloadSimple (http://localhost:8100/build/vendor.js:76738:144) at new HomePage (http://localhost:8100/build/main.js:171:26) at createClass (http://localhost:8100/build/vendor.js:12808:20) at createDirectiveInstance (http://localhost:8100/build/vendor.js:12651:37) at createViewNodes (http://localhost:8100/build/vendor.js:14109:53) at createRootView (http://localhost:8100/build/vendor.js:13998:5) at callWithDebugContext (http://localhost:8100/build/vendor.js:15423:42) at Object.debugCreateRootView [as createRootView] (http://localhost:8100/build/vendor.js:14706:12) at ComponentFactory_.create (http://localhost:8100/build/vendor.js:11603:46) at ComponentFactoryBoundToModule.create (http://localhost:8100/build/vendor.js:4355:29)
Stack
Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at NativeAudio.preloadSimple (http://localhost:8100/build/vendor.js:76738:144)
    at new HomePage (http://localhost:8100/build/main.js:171:26)
    at createClass (http://localhost:8100/build/vendor.js:12808:20)
    at createDirectiveInstance (http://localhost:8100/build/vendor.js:12651:37)
    at createViewNodes (http://localhost:8100/build/vendor.js:14109:53)
    at createRootView (http://localhost:8100/build/vendor.js:13998:5)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15423:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8100/build/vendor.js:14706:12)
    at ComponentFactory_.create (http://localhost:8100/build/vendor.js:11603:46)
    at ComponentFactoryBoundToModule.create (http://localhost:8100/build/vendor.js:4355:29)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at c (http://localhost:8100/build/polyfills.js:3:19461)
    at http://localhost:8100/build/polyfills.js:3:20233
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5076:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)

```

TS file example

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { NativeAudio } from '@ionic-native/native-audio/ngx';


@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

 constructor(public navCtrl: NavController,private nativeAudio: NativeAudio) {
               this.nativeAudio.preloadSimple('tigre', 'assets/sonidos/tigre.mp3');
               this.nativeAudio.preloadSimple('mono', 'assets/sonidos/mono.mp3');
               this.nativeAudio.preloadSimple('cerdo', 'assets/sonidos/cerdo.mp3');
               this.nativeAudio.preloadSimple('gallo', 'assets/sonidos/gallo.mp3');
               this.nativeAudio.preloadSimple('buho', 'assets/sonidos/buho.mp3');
               this.nativeAudio.preloadSimple('vaca', 'assets/sonidos/vaca.mp3');
               this.nativeAudio.preloadSimple('zorro', 'assets/sonidos/zorro.mp3');
               this.nativeAudio.preloadSimple('tortuga', 'assets/sonidos/tortuga.mp3');
               this.nativeAudio.preloadSimple('elefante', 'assets/sonidos/elefante.mp3');
               this.nativeAudio.preloadSimple('perro', 'assets/sonidos/perro.mp3');
               this.nativeAudio.preloadSimple('gato', 'assets/sonidos/gato.mp3');
               this.nativeAudio.preloadSimple('pinguino', 'assets/sonidos/pinguino.mp3');
 }
```
PACKAGE.JSON

```
{
  "name": "botoneraJURIA",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "4.20.0",
    "@ionic-native/file": "^4.20.0",
    "@ionic-native/native-audio": "^5.19.0",
    "@ionic-native/splash-screen": "4.20.0",
    "@ionic-native/status-bar": "4.20.0",
    "@ionic/storage": "2.2.0",
    "ionic-angular": "3.9.9",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.4",
    "typescript": "2.6.2"
  },
  "description": "An Ionic project"
}
```

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
