### ISSUE TITLE
Optional 'as' parameter in Router may cause problems

### ISSUE THREAD

**Issue by larry-fuy** [angular/angular#3488]
Problem (Maybe): If not defined "as" parameter in RouteConfig(MyAppComponent)

```
@RouteConfig([
      { path: '/', component: Main},
      { path: '/home', component: Home},
      { path: '/demo', component: Demo}
])
```
and then use `<a [router-link]="['/home']"><span class="home-button"></span></a>`. An exception will be thrown. 

```
EXCEPTION: Component "MyAppComponent" has no route named "home". in [['/home'] in null]
angular2.min.js:15 ORIGINAL EXCEPTION: Component "MyAppComponent" has no route named "home".
angular2.min.js:15 ORIGINAL STACKTRACE:
angular2.min.js:15 Error: Component "MyAppComponent" has no route named "home".
    at new t (https://code.angularjs.org/2.0.0-alpha.33/angular2.min.js:4:22628)
    at execute.RouteRegistry.generate (https://code.angularjs.org/2.0.0-alpha.33/router.dev.js:1875:21)
    at ChildRouter.execute.Router.generate (https://code.angularjs.org/2.0.0-alpha.33/router.dev.js:1629:46)
    at routeParams (https://code.angularjs.org/2.0.0-alpha.33/router.dev.js:1192:47)
    at e.ChangeDetector_ButtonBar_comp_0.__detectChangesInRecords (eval at <anonymous> (https://code.angularjs.org/2.0.0-alpha.33/angular2.min.js:21:1120), <anonymous>:54:41)
    at e.ChangeDetector_ButtonBar_comp_0.detectChangesInRecords (eval at <anonymous> (https://code.angularjs.org/2.0.0-alpha.33/angular2.min.js:21:1120), <anonymous>:22:16)
    at execute.$traceurRuntime.createClass.runDetectChanges (https://code.angularjs.org/2.0.0-alpha.33/angular2.min.js:19:30779)
    at execute.$traceurRuntime.createClass._detectChangesInShadowDomChildren (https://code.angularjs.org/2.0.0-alpha.33/angular2.min.js:19:31368)
    at execute.$traceurRuntime.createClass.runDetectChanges (https://code.angularjs.org/2.0.0-alpha.33/angular2.min.js:19:30887)
    at execute.$traceurRuntime.createClass._detectChangesInShadowDomChildren (https://code.angularjs.org/2.0.0-alpha.33/angular2.min.js:19:31368)
```

Reasons:
In [route_registry.ts](https://github.com/angular/angular/blob/master/modules/angular2/src/router/route_registry.ts#L174), the code
```
var response = componentRecognizer.generate(segment, params);
```
will generate null response since `generate(segment, params)` uses `this._rules.names` to get route name. However `names` corresponds to "as" parameter in RouteDefinition, which is optional and may not be defined. So this is where the exception comes from.  Am I missing somethings here?

**Comment by btford** [comment]
This is working as expected.

The meaning of `[router-link]="['/home']"` is "go to the route named `home` from the root of the component hierarchy," and not "go to the url path "/home."
