### ISSUE TITLE
[BUG] Intermittent passing & failing tests as a result of compiler errors w/ Ivy

### ISSUE THREAD

**Issue by damienwebdev** [angular/angular#34944]
# 🐞 bug report

### Affected Package
I think this is caused by: `@angular/core`

### Is this a regression?
Yes, these tests passed in v8.2.3.

### Description
When running my tests through Karma w/ Chrome, I intermittently get very strange errors that aren't fixable until after I:

```bash
rm -rf node_modules
rm package-lock.json
npm install
```

## 🔬 Minimal Reproduction
This is very difficult to reproduce, I've been able to successfully make the errors go away by re-running an `npm install`, but it is very inconsistent.

The repro is essentially just testing that a HostBinding on a directive adds a class to its host element, but I can't reproduce this with any semblance of regularity.

## 🔥 Exception or Error
<pre><code>
```txt
Chrome 79.0.3945 (Mac OS X 10.15.2) Directive <my-directive> should add a class of "directive__title" to the host element FAILED
        Error: Unexpected value 'BrowserDynamicTestingModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.
            at verifySemanticsOfNgModuleDef (@angular/core/__ivy_ngcc__/fesm2015/core.js:39418:1)
            at @angular/core/__ivy_ngcc__/fesm2015/core.js:39436:1
            at <Jasmine>
            at verifySemanticsOfNgModuleDef (@angular/core/__ivy_ngcc__/fesm2015/core.js:39430:1)
            at Function.get (@angular/core/__ivy_ngcc__/fesm2015/core.js:39382:1)
            at R3TestBedCompiler.applyProviderOverridesToModule (@angular/core/testing/fesm2015/testing.js:2078:44)
            at R3TestBedCompiler.compileTestModule (@angular/core/testing/fesm2015/testing.js:2387:1)
            at R3TestBedCompiler.finalize (@angular/core/testing/fesm2015/testing.js:1873:1)
            at TestBedRender3.get testModuleRef [as testModuleRef] (@angular/core/testing/fesm2015/testing.js:3254:1)
            at TestBedRender3.inject (@angular/core/testing/fesm2015/testing.js:3111:1)
        TypeError: Cannot read property 'classes' of undefined
            at <Jasmine>
            at UserContext.<anonymous> (my-directive.directive.spec.ts:40:17)
            at ZoneDelegate.invoke (zone.js/dist/zone-evergreen.js:365:1)
            at ProxyZoneSpec.onInvoke (zone.js/dist/zone-testing.js:305:1)
            at ZoneDelegate.invoke (zone.js/dist/zone-evergreen.js:364:1)
            at Zone.run (zone.js/dist/zone-evergreen.js:124:1)
            at runInTestZone (zone.js/dist/zone-testing.js:554:1)
            at UserContext.<anonymous> (zone.js/dist/zone-testing.js:569:1)
```
</code></pre>

I also get this error, but it's in a test that doesn't even import the HttpClientModule, so I'm not sure its related.

```txt
Error: Importing HttpClientModule which does not have a ɵmod property
    at @angular/core/__ivy_ngcc__/fesm2015/core.js:39820:1
    at <Jasmine>
    at transitiveScopesFor (@angular/core/__ivy_ngcc__/fesm2015/core.js:39811:1)
    at @angular/core/__ivy_ngcc__/fesm2015/core.js:39825:1
    at <Jasmine>
    at transitiveScopesFor (@angular/core/__ivy_ngcc__/fesm2015/core.js:39811:1)
    at setScopeOnDeclaredComponents (@angular/core/__ivy_ngcc__/fesm2015/core.js:39699:1)
    at flushModuleScopingQueueAsMuchAsPossible (@angular/core/__ivy_ngcc__/fesm2015/core.js:39283:1)
    at TestBedRender3.checkGlobalCompilationFinished (@angular/core/testing/fesm2015/testing.js:3288:53)
    at TestBedRender3.resetTestingModule (@angular/core/testing/fesm2015/testing.js:3064:1)
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
ngular CLI: 9.0.0-rc.10
Node: 10.15.0
OS: darwin x64

Angular: 9.0.0-rc.10
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.10
@angular-devkit/build-angular      0.900.0-rc.10
@angular-devkit/build-ng-packagr   0.900.0-rc.10
@angular-devkit/build-optimizer    0.900.0-rc.10
@angular-devkit/build-webpack      0.900.0-rc.10
@angular-devkit/core               9.0.0-rc.10
@angular-devkit/schematics         9.0.0-rc.10
@angular/cdk                       8.2.3
@ngtools/webpack                   9.0.0-rc.10
@nguniversal/builders              9.0.0-rc.1
@nguniversal/common                9.0.0-rc.1
@nguniversal/express-engine        9.0.0-rc.1
@schematics/angular                9.0.0-rc.10
@schematics/update                 0.900.0-rc.10
ng-packagr                         9.0.0-rc.7
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Comment by splincode** [comment]
create repo with reproduce

**Comment by damienwebdev** [comment]
Closing as dupe of #32431
