### ISSUE TITLE
Compilation breaks for 9.0rc14.

### ISSUE THREAD

**Issue by himanshugarg574** [angular/angular#35139]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v8.2.11
I have built this project with v9 for the first time.

### Description

 A clear and concise description of the problem...
I have searched my whole codebase for "#option" variable in htmls but I have not found anything.
Same error occurs in browser console when I open app with ng serve or after dev build.
Also error stack also does not point towards anything in my code.
## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

ERROR in Error: Cannot assign value "$event" to template variable "option". Template variables are read-only.
    at _AstToIrVisitor.visitPropertyWrite (D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:8617:31)
    at PropertyWrite.visit (D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:7459:28)
    at convertActionBinding (D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:8224:49)
    at prepareEventListenerParameters (D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:16861:27)
    at Object.params (D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:17952:24)
    at D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:17725:94
    at Array.map (<anonymous>)
    at D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:17725:60
    at D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:17014:87
    at Array.map (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:17014:60)
    at D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:17558:60
    at D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:16992:81
    at Array.forEach (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:16992:37)
    at D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:17558:60
    at D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:16992:81
    at Array.forEach (<anonymous>)
    at TemplateDefinitionBuilder.buildTemplateFunction (D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:16992:37)
    at Object.compileComponentFromMetadata (D:\Development\test\node_modules\@angular\compiler\bundles\compiler.umd.js:18643:58)
    at ComponentDecoratorHandler.compile (D:\Development\test\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:534:34)
    at _loop_2 (D:\Development\test\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:542:53)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.12
Node: 12.3.1
OS: win32 x64

Angular: 9.0.0-rc.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.12
@angular-devkit/build-angular      0.900.0-rc.12
@angular-devkit/build-optimizer    0.900.0-rc.12
@angular-devkit/build-webpack      0.900.0-rc.12
@angular-devkit/core               9.0.0-rc.12
@angular-devkit/schematics         9.0.0-rc.12
@angular/cdk                       9.0.0-rc.9
@angular/cli                       9.0.0-rc.12
@angular/material                  9.0.0-rc.9
@angular/material-moment-adapter   9.0.0-rc.9
@ngtools/webpack                   9.0.0-rc.12
@schematics/angular                9.0.0-rc.12
@schematics/update                 0.900.0-rc.12
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by splincode** [comment]
Please add minimal reproduction example (github)

**Comment by Lonli-Lokli** [comment]
@himanshugarg574 is it related to https://github.com/angular/angular/issues/34405?

**Comment by JoostK** [comment]
Could you try enabling `fullTemplateTypeCheck` or `strictTemplates` according to [the instructions here](https://next.angular.io/guide/template-typecheck) and try again? It could be that a lot of errors are generated, one of which I expect to be related to the error you're seeing. This time however, it should point exactly at the source of the error.

**Comment by himanshugarg574** [comment]
yes it is related to above mentioned. Thnaks. Btw error stack should be indicate problematic lines IMO.

**Comment by himanshugarg574** [comment]
Thanks @Lonli-Lokli and @JoostK . It was indeed related to #34405 . I enabled `strictTemplates` and got the errorneous lines in my code.
