### ISSUE TITLE
`ng add @angular/elements@next` fails with schema.json not found error

### ISSUE THREAD

**Issue by hisham** [angular/angular#35154]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/elements

### Is this a regression?

Yes. Doing `ng add @angular/elements` works fine.

### Description

Creating a new workspace project using angular 9 RC 12. Everything installing fine, but when doing `ng add @angular/elements@next` I get: 

```
`An unhandled exception occurred: Path "<my_dir>/node_modules/@angular/elements/schematics/ng-add/schema.json" does not exist.
See "/private/var/folders/9c/scyzyh01349gnx6qgkp_twzh0000gn/T/ng-GPnlhg/angular-errors.log" for further details.
```

Log shows: 

```
[error] Error: Path "/Users/hisham/src/ess-app/frontend/node_modules/@angular/elements/schematics/ng-add/schema.json" does not exist.
    at readFile (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/tools/file-system-utility.js:17:15)
    at Object.readJsonFile (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/tools/file-system-utility.js:45:29)
    at NodeModulesEngineHost.createSchematicDescription (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:183:48)
    at SchematicEngine.createSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/src/engine/engine.js:219:38)
    at CollectionImpl.createSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at AddCommand.getSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/models/schematic-command.js:134:27)
    at AddCommand.runSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/models/schematic-command.js:296:32)
    at AddCommand.executeSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/commands/add-impl.js:176:31)
    at AddCommand.run (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/commands/add-impl.js:60:29)
    at async AddCommand.validateAndRun (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/models/command.js:134:28)
    at async Object.runCommand (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/models/command-runner.js:201:24)
    at async default_1 (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/lib/cli/index.js:62:31)
```

**Anything else relevant?**

OSX 10.5.12, npm 6.13.2, node 13.2.0

**Comment by cveld** [comment]
Just a note; schema.json is also not present in earlier versions of @angular/elements; checked a couple of versions at unpkg: 6.x, 7.x, 8.x.

**Comment by LayZeeDK** [comment]
This is still a problem with:
* `@angular/cli@9.0.1`
* `@angular/core@9.0.0`
* `@angular/elements@9.0.0`
(on Windows 10)

# Steps to reproduce
1. Execute `ng new elements-app`.
1. Enter the `elements-app` directory.
1. Execute `ng add @angular/elements`.

# Error message
```
An unhandled exception occurred: Path "C:\projects\sandbox\ngx-elements-app\node_modules\@angular\elements\schematics\ng-add\schema.json" does not exist.
See "C:\Users\xxx\AppData\Local\Temp\ng-VV0CPj\angular-errors.log" for further details.
```

## Content of `angular-errors.log`
```
[error] Error: Path "C:\projects\sandbox\ngx-elements-app\node_modules\@angular\elements\schematics\ng-add\schema.json" does not exist.
    at readFile (C:\projects\sandbox\ngx-elements-app\node_modules\@angular-devkit\schematics\tools\file-system-utility.js:17:15)
    at Object.readJsonFile (C:\projects\sandbox\ngx-elements-app\node_modules\@angular-devkit\schematics\tools\file-system-utility.js:45:29)
    at NodeModulesEngineHost.createSchematicDescription (C:\projects\sandbox\ngx-elements-app\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:183:48)
    at SchematicEngine.createSchematic (C:\projects\sandbox\ngx-elements-app\node_modules\@angular-devkit\schematics\src\engine\engine.js:219:38)
    at CollectionImpl.createSchematic (C:\projects\sandbox\ngx-elements-app\node_modules\@angular-devkit\schematics\src\engine\engine.js:69:29)
    at AddCommand.getSchematic (C:\projects\sandbox\ngx-elements-app\node_modules\@angular\cli\models\schematic-command.js:134:27)
    at AddCommand.runSchematic (C:\projects\sandbox\ngx-elements-app\node_modules\@angular\cli\models\schematic-command.js:296:32)
    at AddCommand.executeSchematic (C:\projects\sandbox\ngx-elements-app\node_modules\@angular\cli\commands\add-impl.js:176:31)
    at AddCommand.run (C:\projects\sandbox\ngx-elements-app\node_modules\@angular\cli\commands\add-impl.js:142:21)
    at async AddCommand.validateAndRun (C:\projects\sandbox\ngx-elements-app\node_modules\@angular\cli\models\command.js:134:28)
    at async Object.runCommand (C:\projects\sandbox\ngx-elements-app\node_modules\@angular\cli\models\command-runner.js:201:24)
    at async default_1 (C:\projects\sandbox\ngx-elements-app\node_modules\@angular\cli\lib\cli\index.js:62:31)
```

# Files
In `node_modules/@angular/elements/schematics/ng-add` I have `schema.js`, not `schema.json`.

**Comment by alexander-patton** [comment]
Seeing this same issue following these steps on macOS 10.13

**Comment by aressler38** [comment]
When will the fix be published to the public npm registry?

**Comment by LayZeeDK** [comment]
Probably in 9.0.1. Patch releases are usually weekly.
