### ISSUE TITLE
`ng add @angular/elements@next` fails with schema.json not found error

### ISSUE THREAD

**Issue by hisham** [angular/angular#35152]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/elements

### Is this a regression?

Yes. Doing `ng add @angular/elements` works fine.

### Description

Creating a new workspace project using angular 9 RC 12. Everything installing fine, but when doing `ng add @angular/elements@next` I get: 

`An unhandled exception occurred: Path "<my_dir>/node_modules/@angular/elements/schematics/ng-add/schema.json" does not exist.
See "/private/var/folders/9c/scyzyh01349gnx6qgkp_twzh0000gn/T/ng-GPnlhg/angular-errors.log" for further details.

Log shows: 

```
[error] Error: Path "/Users/hisham/src/ess-app/frontend/node_modules/@angular/elements/schematics/ng-add/schema.json" does not exist.
    at readFile (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/tools/file-system-utility.js:17:15)
    at Object.readJsonFile (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/tools/file-system-utility.js:45:29)
    at NodeModulesEngineHost.createSchematicDescription (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:183:48)
    at SchematicEngine.createSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/src/engine/engine.js:219:38)
    at CollectionImpl.createSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at AddCommand.getSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/models/schematic-command.js:134:27)
    at AddCommand.runSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/models/schematic-command.js:296:32)
    at AddCommand.executeSchematic (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/commands/add-impl.js:176:31)
    at AddCommand.run (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/commands/add-impl.js:60:29)
    at async AddCommand.validateAndRun (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/models/command.js:134:28)
    at async Object.runCommand (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/models/command-runner.js:201:24)
    at async default_1 (/Users/hisham/src/ess-app/frontend/node_modules/@angular/cli/lib/cli/index.js:62:31)
```

**Anything else relevant?**

OSX 10.5.12, npm 6.13.2, node 13.2.0

**Comment by AndrewKushnir** [comment]
Hi @hisham, it looks like the problem is related to Angular CLI, so I'm transferring this issue to Angular CLI repo for further investigation. Thank you.
