### ISSUE TITLE
Update from Angular 8 to 9 leads to “ReferenceError: SomeAbstractModelClass is not defined” for production build

### ISSUE THREAD

**Issue by BuZZ-dEE** [angular/angular#35380]
# 🐞 bug report

### Affected Package

 The issue is caused by package: I don't know.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.0.2

### Description

I have updated an [Angular 8 app to Angular 9][1]. Everything runs fine, if I start the application using `ng serve`, but if I start the app using `ng serve --prod`, I get the following error at runtime.:

## 🔬 Minimal Reproduction

I don't know how to reproduce this issue.

## 🔥 Exception or Error
<pre><code>
ReferenceError: SomeAbstractModelClass is not defined
    at http://localhost:4200/main.js:1:330907
    at Module.zUnb (http://localhost:4200/main.js:1:331001)
    at l (http://localhost:4200/runtime.js:1:552)
    at Object.0 (http://localhost:4200/main.js:1:96)
    at l (http://localhost:4200/runtime.js:1:552)
    at t (http://localhost:4200/runtime.js:1:421)
    at Array.r [as push] (http://localhost:4200/runtime.js:1:293)
    at http://localhost:4200/main.js:1:47
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 10.15.0
OS: linux x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.1
@angular-devkit/build-angular      0.900.1
@angular-devkit/build-ng-packagr   0.900.1
@angular-devkit/build-optimizer    0.900.1
@angular-devkit/build-webpack      0.900.1
@angular-devkit/core               9.0.1
@angular-devkit/schematics         9.0.1
@angular/cli                       9.0.1
@ngtools/webpack                   9.0.1
@schematics/angular                9.0.1
@schematics/update                 0.900.1
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

https://stackoverflow.com/questions/60174263/update-from-angular-8-to-9-leads-to-referenceerror-someabstractmodelclass-is-n

  [1]: https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3

**Comment by pkozlowski-opensource** [comment]
@BuZZ-dEE I'm afraid that we will need a reproduction scenario to be able to progress on this one - it is impossible to diagnose / fix the problem based on just the error message...

**Comment by GistCode** [comment]
I've encountered something similar just now,

I've managed to isolate the problem to 

```
File: tsconfig.json
11:     "emitDecoratorMetadata": true,
```

Try removing that if that exists in your tsconfig

**Comment by mhamern** [comment]
Might be unrelated, but I had the same error message when using custom decorators ([ngx-cacheable](https://github.com/angelnikolov/ngx-cacheable)) on methods. Dev build worked perfectly but production build (aot enabled) produced the same error.

The error was not thrown if the parameters were of type any or primitive types (number, string...) 

I can provide repro if needed but I don't know if it would be helpful since the error is probably caused by something in the library I've used and not directly in my code.

**Comment by andreas-aeschlimann** [comment]
I have the same error with an external JavaScript library named "QRious".

In Angular 8, I had in angular.json a line 
```
"scripts": [
    "node_modules/qrious/dist/qrious.min.js"
],
```
and somewhere in code `declare var QRious: any;`.

In Angular 9, this is broken, it says `ERROR ReferenceError: QRious is not defined`. I am not sure whether this is related to the OP issue, but it could be.

**Comment by BuZZ-dEE** [comment]
Setting `"emitDecoratorMetadata": false` in `tsconfig.json` works. Thx @GistCode

**Comment by tomamatics** [comment]
if you need those decorator metadata, you may also refactor the affected methods like this

from:
`delete(book: Book): Promise<void>`
to:
`delete<T extends Book>(book: T): Promise<void>`

not really fancy, but works until fixed.
