### ISSUE TITLE
Lazy loaded service from library build with ng9(viewEngine) showing NullInjectorError in aot mode in app in ng8

### ISSUE THREAD

**Issue by gmfun** [angular/angular#35402]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core most likely

### Is this a regression?

Yes it worked when library was build with ng8

### Description

 
We have an internal library which is updated to ng9 and ts 3.7. I am building my libarary with --prod flag so make is compatible with ng8. When I use it in another application on ng8,it works fine in JIT mode. But when I build it in aot mode I get the following error for lazy loaded service using `providedIn: 'root'`

## 🔬 Minimal Reproduction

 I was not able to create a reproducable repo as the urrent application is very big,

## 🔥 Exception or Error
<pre><code>

:4200/polyfills.js:659 Unhandled Promise rejection: StaticInjectorError(AppModule)[SiteConfigFeatureService]: 
  StaticInjectorError(Platform: core)[SiteConfigFeatureService]: 
    NullInjectorError: No provider for SiteConfigFeatureService! ; Zone: <root> ; Task: Promise.then ; Value: Error: NullInjectorError: No provider for SiteConfigFeatureService!
    at NullInjector.get (:4200/main.js:35247) [angular]
    at resolveToken (:4200/main.js:50036) [angular]
    at tryResolveToken (:4200/main.js:49962) [angular]
    at StaticInjector.get (:4200/main.js:49813) [angular]
    at resolveToken (:4200/main.js:50036) [angular]
    at tryResolveToken (:4200/main.js:49962) [angular]
    at StaticInjector.get (:4200/main.js:49813) [angular]
    at resolveNgModuleDep (:4200/main.js:60840) [angular]
    at NgModuleRef_.get (:4200/main.js:61904) [angular]
    at injectInjectorOnly (:4200/main.js:35126) [angular]
    at Module.ɵɵinject (:4200/main.js:35136) [angular]
    at SiteService_Factory (:4200/main.js:444512) [angular]
    at _callFactory (:4200/main.js:60933) [angular]
    at _createProviderInstance (:4200/main.js:60876) [angular] Error: NullInjectorError: No provider for SiteConfigFeatureService!
    at NullInjector.get (http://localhost:4200/main.js:35247:27) [angular]
    at resolveToken (http://localhost:4200/main.js:50036:24) [angular]
    at tryResolveToken (http://localhost:4200/main.js:49962:16) [angular]
    at StaticInjector.get (http://localhost:4200/main.js:49813:20) [angular]
    at resolveToken (http://localhost:4200/main.js:50036:24) [angular]
    at tryResolveToken (http://localhost:4200/main.js:49962:16) [angular]
    at StaticInjector.get (http://localhost:4200/main.js:49813:20) [angular]
    at resolveNgModuleDep (http://localhost:4200/main.js:60840:29) [angular]
    at NgModuleRef_.get (http://localhost:4200/main.js:61904:16) [angular]
    at injectInjectorOnly (http://localhost:4200/main.js:35126:33) [angular]
    at Module.ɵɵinject (http://localhost:4200/main.js:35136:57) [angular]
    at SiteService_Factory (http://localhost:4200/main.js:444512:674) [angular]
    at _callFactory (http://localhost:4200/main.js:60933:20) [angular]
    at _createProviderInstance (http://localhost:4200/main.js:60876:26) [angular]

</code></pre>

When I add the above service in providers array, another service throws errors

**Comment by gopinathshiva** [comment]
Any update on this issue. I'm observing same issue, with ng7 service consumed in ng8 project !!!

**Comment by kara** [comment]
@gmfun We're going to need a bit more information to investigate this. Can please provide a minimal repro of the issue?

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
