### ISSUE TITLE
bug(testing): ngOnChanges not called for component via detectChanges()

### ISSUE THREAD

**Issue by fetis** [angular/angular#35614]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core/testing

### Is this a regression?
no, but this bug is older than Universe

### Description

This is basically a duplication of #9866 which was automatically closed.

I would like to know why this was not fixed since Angular 2? Are any limitations to it?

## 🔬 Minimal Reproduction
You need to have `@Input() data: number` in your component and `ngOnChanges` life hook

```
  @Input() data: number;

  ngOnChanges(changes: SimpleChanges) {
    console.log(changes);
  }
```

test suite
```
    it('should trigger ngOnChanges', () => {
      spyOn(component, 'ngOnChanges').and.callThrough();

      component.data = 1;
      fixture.detectChanges();

      expect(component.ngOnChanges).toHaveBeenCalled();
    });
```

## 🔥 Exception or Error
```
	Error: Expected spy ngOnChanges to have been called.
	    at <Jasmine>
	    at UserContext.<anonymous> (http://localhost:9877/_karma_webpack_/src/app/app.component.spec.ts:27:35)
	    at ZoneDelegate.invoke (http://localhost:9877/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:365:1)
	    at ProxyZoneSpec.onInvoke (http://localhost:9877/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:305:1)
```

## 🌍  Your Environment
Angular CLI: 9.0.3
Node: 12.4.0
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

**Comment by fetis** [comment]
@pkozlowski-opensource could you plz add `comp:testing` to have parity with the old ticket.

**Comment by pkozlowski-opensource** [comment]
@fetis this issue is not specific to testing - it is also present for dynamically created components (ex. #22567) as done by TestBed but is equally valid for _any_ component for which you get a reference and manipulate its inputs "directly" (outside of template bindings).

So this is a more general problem and not something specific to testing.

**Comment by miquelnez** [comment]
If i'm not wrong, is the same problem that this other issue:

https://github.com/angular/angular/issues/37465

**Comment by atscott** [comment]
Duplicate of #37465
