### ISSUE TITLE
Angular 9 Production Build Fails during Optimization Phase (terser out of memory)

### ISSUE THREAD

**Issue by PMoransais** [angular/angular#35626]
A new Angular 9 app fails during a production build (ng build --prod).
The application compiles with ng build and ng serve.

This may be similar to 28175
I also found a suggestion to increase the process memory in Nodes (but I do not know how to do that!). I tried to add memory to node but I saw no difference

copy of the command and response
---------------
PS C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder> ng build
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {polyfills} polyfills-es2015.js, polyfills-es2015.js.map (polyfills) 148 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 656 kB [initial] [rendered]
chunk {main} main-es2015.js, main-es2015.js.map (main) 171 kB [initial] [rendered]
chunk {main} main-es5.js, main-es5.js.map (main) 220 kB [initial] [rendered]
chunk {public-public-module} public-public-module-es2015.js, public-public-module-es2015.js.map (public-public-module) 2.59 MB  [rendered]
chunk {public-public-module} public-public-module-es5.js, public-public-module-es5.js.map (public-public-module) 2.92 MB  [rendered]
chunk {vendor} vendor-es2015.js, vendor-es2015.js.map (vendor) 2.74 MB [initial] [rendered]
chunk {vendor} vendor-es5.js, vendor-es5.js.map (vendor) 3.21 MB [initial] [rendered]
chunk {runtime} runtime-es2015.js, runtime-es2015.js.map (runtime) 9.02 kB [entry] [rendered]
chunk {runtime} runtime-es5.js, runtime-es5.js.map (runtime) 9.02 kB [entry] [rendered]
chunk {styles} styles-es2015.js, styles-es2015.js.map (styles) 960 kB [initial] [rendered]
chunk {styles} styles-es5.js, styles-es5.js.map (styles) 962 kB [initial] [rendered]
Date: 2020-02-22T15:29:29.990Z - Hash: 0851422fb8d5b16cbcd5 - Time: 27659ms
PS C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder> ng build --prod

ERROR in main-es2015.7c0f16d0d0f04d486439.js from Terser
RangeError: Maximum call stack size exceeded
    at Array.push (<anonymous>)
    at Tn.push (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:76200)
    at AST_Call.transform (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:79125)
    at C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:80514
    at AST_Return.transform (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:79182)
    at C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:79313
    at l (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:931)
    at e (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:1251)
    at Mn (C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:79287)
    at C:\iBreeder Dev\dev.iBreeder.net\iBreeder.com2\iBreeder\node_modules\terser\dist\bundle.min.js:1:81469

Thanks

**Comment by montella1507** [comment]
Node.js version? try to update to LTS, it solves lot of problems with memory leaks.

**Comment by PMoransais** [comment]
Thanks montella1507.

I reverted to the node version 12.16.1 LTS which is the latest with LTS but it does not solve the problem.
