### ISSUE TITLE
TestBed.overrideProvider fails for service that injects ChangeDetectorRef

### ISSUE THREAD

**Issue by FDIM** [angular/angular#35664]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler?

### Is this a regression?

I'd say so - it works with VE, but breaks with IVY.

### Description

 

We have this one case in the project where we have a service that is always added to component providers list to make sure that each component get's their own instance. 

Main reason is to get access to component change detector and handle cleanup on destroy to simplify usage.

The service itself is not added to any module nor uses providedIn: 'root'/'platform'

Interesting bit is that this continues to work at runtime with IVY enabled, but fails in unit tests where such provider is overriden. If I remove change detector requirement - unit tests pass. Sadly I can't without refactoring existing code and changing the interface.

See the example as I managed to reproduce it in stackblitz. 

I've also tried to use `@Optional` for the value injection, but that did not help:
![image](https://user-images.githubusercontent.com/1985429/75251514-074a8500-57db-11ea-9717-4b5489f6f10b.png)

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-gvxtvu?file=tsconfig.json

## 🔥 Exception or Error
<pre><code>

Failed: No value provided for @angular/core symbol 'ɵɵinjectPipeChangeDetectorRef'.
        Error: No value provided for @angular/core symbol 'ɵɵinjectPipeChangeDetectorRef'.
            at R3JitReflector.resolveExternalReference (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6413:1)
            at JitEmitterVisitor.visitExternalExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6350:1)
            at ExternalExpr.visitExpression (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:1373:1)
            at JitEmitterVisitor.visitInvokeFunctionExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5814:1)
            at JitEmitterVisitor.visitInvokeFunctionExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6156:1)
            at InvokeFunctionExpr.visitExpression (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:1245:1)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5996:1
            at JitEmitterVisitor.visitAllObjects (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6015:1)
            at JitEmitterVisitor.visitAllExpressions (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5996:1)
            at JitEmitterVisitor.visitInstantiateExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5854:1)
        Error: No value provided for @angular/core symbol 'ɵɵinjectPipeChangeDetectorRef'.
            at R3JitReflector.resolveExternalReference (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6413:1)
            at JitEmitterVisitor.visitExternalExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6350:1)
            at ExternalExpr.visitExpression (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:1373:1)
            at JitEmitterVisitor.visitInvokeFunctionExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5814:1)
            at JitEmitterVisitor.visitInvokeFunctionExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6156:1)
            at InvokeFunctionExpr.visitExpression (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:1245:1)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5996:1
            at JitEmitterVisitor.visitAllObjects (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6015:1)
            at JitEmitterVisitor.visitAllExpressions (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5996:1)
            at JitEmitterVisitor.visitInstantiateExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5854:1)
        Error: No value provided for @angular/core symbol 'ɵɵinjectPipeChangeDetectorRef'.
            at R3JitReflector.resolveExternalReference (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6413:1)
            at JitEmitterVisitor.visitExternalExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6350:1)
            at ExternalExpr.visitExpression (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:1373:1)
            at JitEmitterVisitor.visitInvokeFunctionExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5814:1)
            at JitEmitterVisitor.visitInvokeFunctionExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6156:1)
            at InvokeFunctionExpr.visitExpression (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:1245:1)
            at http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5996:1
            at JitEmitterVisitor.visitAllObjects (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:6015:1)
            at JitEmitterVisitor.visitAllExpressions (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5996:1)
            at JitEmitterVisitor.visitInstantiateExpr (http://localhost:9876/node_modules/@angular/compiler/fesm2015/compiler.js:5854:1)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-ng-packagr   0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cdk                       9.0.0
@angular/cli                       9.0.3
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
ng-packagr                         5.7.1
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Looks like this line is wrong:

https://github.com/angular/angular/blob/c2a904da09165609cf408ceee26611f3a8df5326/packages/core/src/di/jit/injectable.ts#L68

The `compiler.R3FactoryTarget.Injectable` option is a more appropriate choice here.

**Comment by JoostK** [comment]
A workaround for now would be to inject `Injector` and get the `ChangeDetectorRef` from there:

```ts
  readonly cdRef: ChangeDetectorRef;

  constructor(injector: Injector) {
    this.cdRef = injector.get(ChangeDetectorRef);
  }
```

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the corresponding PR #35706 with the fix was merged. Thank you.
