### ISSUE TITLE
TypeError: context.getProjectMetadata is not a function

### ISSUE THREAD

**Issue by SanJin-hx** [angular/angular#35680]
"@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",

"@angular-builders/custom-webpack": "^8.4.1",
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.900.3",
    "@angular-devkit/core": "~9.0.3",
    "@angular-devkit/schematics": "~9.0.3",
    "@angular/cli": "~9.0.3",
    "@angular/compiler-cli": "~9.0.2",
    "@angular/language-service": "~9.0.2",
    "@ionic/angular-toolkit": "~2.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.1",

[error] TypeError: context.getProjectMetadata is not a function
    at Object.configureI18nBuild (D:\MyWork\CPS-Mobile-CN\node_modules\@angular-devkit\build-angular\src\utils\i18n-options.js:99:36)
    at Object.generateI18nBrowserWebpackConfigFromContext (D:\MyWork\CPS-Mobile-CN\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:85:57)
    at Object.buildBrowserWebpackConfigFromContext (D:\MyWork\CPS-Mobile-CN\node_modules\@angular-devkit\build-angular\src\browser\index.js:67:41)
    at setup (D:\MyWork\CPS-Mobile-CN\node_modules\@angular-devkit\build-angular\src\dev-server\index.js:103:63)

**Comment by AndrewKushnir** [comment]
Hi @SanJin-hx, thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template. It'd be great if you could provide a minimum repro in a form of Github repository, so that we can perform an investigation.
