### ISSUE TITLE
Can't serve/build after updating from 9.0.2 > 9.0.3

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular#35716]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.2

### Description

 Can't serve or build after updating to Angular 9.0.3 from 9.0.2 using the `ng update @angular/core` command

## 🔬 Minimal Reproduction

 N/A

```
"dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@asymmetrik/ngx-leaflet": "^6.0.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "apexcharts": "^3.15.5",
    "leaflet": "^1.6.0",
    "ng-apexcharts": "^1.2.0",
    "remove": "^0.1.5",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.3",
    "@angular/cli": "~9.0.3",
    "@angular/compiler-cli": "~9.0.2",
    "@angular/language-service": "~9.0.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/leaflet": "^1.5.8",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  }
```

## 🔥 Exception or Error
<pre><code>D:\path\to\project>ng build --prod
0% compiling
Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling @asymmetrik/ngx-leaflet : module as esm5

Compiling @ngx-translate/core : es2015 as esm2015

ERROR in Cannot read property 'push' of undefined
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular 9.0.3 updated from 9.0.2 using the `ng update @angular/core` command
</code></pre>

**Anything else relevant?**

**Comment by MicMicMon** [comment]
Same for me.

**Comment by petebacondarwin** [comment]
Can you try running the following command @Ploppy3 ?

```
yarn ngcc -l debug -t @ngx-translate/core
```

**Comment by leonelvsc** [comment]
Same here i got an `ERROR in Maximum call stack size exceeded` when the serve command tries to compile the @angular/fire library, i have to downgrade to 9.0.2

`node --max_old_space_size=8192 "./node_modules/@angular/cli/bin/ng" serve
0% compiling
Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling @angular/service-worker : es2015 as esm2015

Compiling @angular/common/http : es2015 as esm2015

Compiling @angular/router : es2015 as esm2015

Compiling @angular/fire : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 2.04 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 697 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 910 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.21 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 341 kB [initial] [rendered]
Date: 2020-02-27T11:36:22.466Z - Hash: 6a22c5cc5001ba5d01ec - Time: 16896ms

ERROR in Maximum call stack size exceeded

`

**Comment by Ploppy3** [comment]
@petebacondarwin 

```
D:\ng\project-name>yarn ngcc -l debug -t @ngx-translate/core
yarn run v1.22.0
$ D:\ng\project-name\node_modules\.bin\ngcc -l debug -t @ngx-translate/core
Debug: Running ngcc on ClusterExecutor (using 7 worker processes).
Debug: Analyzing entry-points...
Debug: Analyzed 2 entry-points in 1s. (Total tasks: 10)
Debug: Processing tasks...
Debug: All 1 workers are currently busy and cannot take on more work.
Debug: All 2 workers are currently busy and cannot take on more work.
Debug: All 3 workers are currently busy and cannot take on more work.
Debug: All 4 workers are currently busy and cannot take on more work.
Debug: All 5 workers are currently busy and cannot take on more work.
Debug: All 6 workers are currently busy and cannot take on more work.
Debug: All 7 workers are currently busy and cannot take on more work.
Debug: [Worker #2] Processing task: {entryPoint: @angular/core, formatProperty: fesm5, processDts: false}
Debug: [Worker #1] Processing task: {entryPoint: @angular/core, formatProperty: fesm2015, processDts: false}
Debug: Skipping @angular/core : fesm2015 (already compiled).
Debug: All 7 workers are currently busy and cannot take on more work.
Debug: [Worker #1] Processing task: {entryPoint: @ngx-translate/core, formatProperty: esm2015, processDts: false}
Debug: [Worker #5] Processing task: {entryPoint: @angular/core, formatProperty: main, processDts: false}
Debug: [Worker #4] Processing task: {entryPoint: @angular/core, formatProperty: esm5, processDts: false}
Debug: [Worker #7] Processing task: {entryPoint: @ngx-translate/core, formatProperty: fesm5, processDts: false}
Debug: [Worker #3] Processing task: {entryPoint: @angular/core, formatProperty: esm2015, processDts: false}
Debug: [Worker #6] Processing task: {entryPoint: @ngx-translate/core, formatProperty: fesm2015, processDts: true}
Compiling @ngx-translate/core : fesm5 as esm5
Compiling @ngx-translate/core : esm2015 as esm2015
Debug: Stopping 7 workers...
Error: Error on worker #7: TypeError: Cannot read property 'push' of undefined
    at SourceFile.renderFlattenedSourceMap (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\sourcemaps\source_file.js:73:33)
    at Object.renderSourceAndMap (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\rendering\source_maps.js:34:42)
    at Renderer.renderFile (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\rendering\renderer.js:93:38)
    at D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\rendering\renderer.js:50:84
    at Array.forEach (<anonymous>)
    at Renderer.renderProgram (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\rendering\renderer.js:45:54)
    at Transformer.transform (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:77:42)
    at ClusterWorker.compile (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\main.js:168:42)
    at Worker.<anonymous> (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\worker.js:44:42)
    at Worker.emit (events.js:210:5)
    at ClusterMaster.onWorkerMessage (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:158:27)
    at D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:46:95
    at ClusterMaster.<anonymous> (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:238:57)
    at step (D:\ng\project-name\node_modules\tslib\tslib.js:136:27)
    at Object.next (D:\ng\project-name\node_modules\tslib\tslib.js:117:57)
    at D:\ng\project-name\node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\ng\project-name\node_modules\tslib\tslib.js:106:16)
    at EventEmitter.<anonymous> (D:\ng\project-name\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:232:32)
    at EventEmitter.emit (events.js:210:5)
Debug:   Successfully compiled @ngx-translate/core : esm2015
Compiling @angular/core : fesm5 as esm5
Compiling @ngx-translate/core : fesm2015 as esm2015
Compiling @angular/core : main as umd
Compiling @angular/core : esm5 as esm5
Compiling @angular/core : esm2015 as esm2015
Debug:   Successfully compiled @angular/core : esm5
Debug:   Successfully compiled @angular/core : esm2015
Debug:   Successfully compiled @angular/core : main
Debug:   Successfully compiled @angular/core : fesm5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by petebacondarwin** [comment]
Great. Thanks. Looking into it.

**Comment by AcidSlide** [comment]
I'm also encountering after updating from 9.0.2 to 9.0.3.

![image](https://user-images.githubusercontent.com/6833047/75442607-d618b300-599a-11ea-9cbe-272a2ba07781.png)

`ERROR in Maximum call stack size exceeded`

**Comment by AcidSlide** [comment]
> I'm also encountering after updating from 9.0.2 to 9.0.3.
> 
> ![image](https://user-images.githubusercontent.com/6833047/75442607-d618b300-599a-11ea-9cbe-272a2ba07781.png)
> 
> `ERROR in Maximum call stack size exceeded`

rolled back to 9.0.2 and working as expected, so it is really something broke updating to 9.0.3

**Comment by Ploppy3** [comment]
@petebacondarwin related to https://github.com/angular/angular/issues/35709 , more info available there

**Comment by petebacondarwin** [comment]
Moving the discussion to #35709 since this all seems related to the same change in ngcc
