### ISSUE TITLE
Redefining property 'onclick'

### ISSUE THREAD

**Issue by danhalliday** [angular/angular#3584]
I'm trying to get an Angular2 app running in [Zombie](https://github.com/assaf/zombie/), and seeing the following error (presumably from [jsdom](https://github.com/tmpvar/jsdom)):

    TypeError: Cannot redefine property: onclick
        at Function.defineProperty (native)
        at canPatchViaPropertyDescriptor (http://localhost:8080/app.js:35698:12)
        at Object.apply (http://localhost:8080/app.js:35677:9)
        at Object.apply (http://localhost:8080/app.js:35288:29)
        at http://localhost:8080/app.js:35165:16
        at linkDynamicModule (http://localhost:8080/app.js:262:32)
        at getModule (http://localhost:8080/app.js:231:9)
        at http://localhost:8080/app.js:266:16
        at http://localhost:8080/app.js:35147:20
        at linkDynamicModule (http://localhost:8080/app.js:262:32)
        in http://localhost:8080/

Is this patching just part of how Angular2 works? Is it likely to be a limitation of jsdom? Many thanks.

**Comment by mhevery** [comment]
This is how Zone works, and Angular2 uses Zone. 

Closing in favor of: https://github.com/angular/zone.js/issues/156

**Comment by danhalliday** [comment]
Many thanks
