### ISSUE TITLE
Watch broken in test.unit.dart

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3601]
Steps to reproduce: 
* run `test.unit.dart`
* wait for tests to finish
* touch one of the files (ex. `compiler/integration_spec.ts`)

Problem: 
> [10:46:33] Starting '!build/tree.dart'...
[10:46:35] '!build/tree.dart' errored after 1.83 s
[10:46:35] TypeError: [TSToDartTranspiler]: Cannot read property '0' of undefined
    at FacadeConverter.getFileAndName (/source/facade_converter.ts:147:33)
    at FacadeConverter.visitTypeName (/source/facade_converter.ts:122:30)
    at ModuleTranspiler.visitNode (/source/module.ts:71:17)
    at Transpiler.visit (/source/main.ts:254:31)
    at ModuleTranspiler.TranspilerBase.visit (/source/base.ts:20:39)
    at ModuleTranspiler.TranspilerBase.visitList (/source/base.ts:35:12)
    at ModuleTranspiler.visitNode (/source/module.ts:57:14)
    at Transpiler.visit (/source/main.ts:254:31)
    at ModuleTranspiler.TranspilerBase.visit (/source/base.ts:20:39)
    at ModuleTranspiler.visitNode (/source/module.ts:43:16)

This error makes running tests in Dart pretty miserable experience so I'm short of flagging is as P0....

//cc: @mprobst @IgorMinar

**Comment by caitp** [comment]
I haven't been able to reproduce this on master (218b037d987b2b85a3fb567d71424c9819ac8295) with a clean npm install, with numerous attempts. Have you performed a clean install? Also, sometimes fsevents just breaks on OSX sometimes and doesn't work correctly without a reboot, but usually that manifests itself differently (eg watch just not firing at all).

**Comment by pkozlowski-opensource** [comment]
@caitp I did `npm install` so it should have wiped out `node_modules`. Let me remove `node_modules` manually and try again...

**Comment by pkozlowski-opensource** [comment]
Bah, can't reproduce it anymore, either:
> [14:44:04] Finished '!build/tree.dart' after 2.66 s

Not sure what has happened, I _saw_ this stack trace :-/

Going to close this for now, will re-open if I see it again.

All: sorry for the noise... And thnx @caitp for re-testing this.

**Comment by mprobst** [comment]
From the stacktrace, it looks like you had TypeScript code that wasn't what ts2dart expected. I don't think your stack trace was related to watching, maybe it was just a half written or syntactically incorrect file? I'll add some defensive code for the problem.

**Comment by pkozlowski-opensource** [comment]
@mprobst this is possible, I had some TS error at one point. But I kept seeing the err even after reverting all the changes I did... Anyway, if you could use your super-powers to make sure that in case of TS syntax errors you get the actual TS error instead of this stack trace, it would be awesome!

**Comment by mprobst** [comment]
@pkozlowski-opensource I think we should be reporting TS errors. Odd, maybe some caching effect? In any case, the code is a bit risky how it's written, I'll make it report a proper error for the case that you ran into.
