### ISSUE TITLE
Cannot use 'in' operator to search for 'base10Value' in null

### ISSUE THREAD

**Issue by yangjunfocus** [angular/angular#36253]
# 🐞 bug report
`npm start

> utsource-wap@0.0.0 start E:\Wap-Angular
> ng serve --port 8001

Compiling @angular/animations : module as esm5
Compiling @angular/compiler/testing : module as esm5
Compiling @angular/core : module as esm5
Error: Error on worker #1: TypeError: Cannot use 'in' operator to search for 'base10Value' in null
    at Object.createLiteral (E:\Wap-Angular\node_modules\typescript\lib\typescript.js:66137:56)
    at TypeTranslatorVisitor.visitLiteralExpr (E:\Wap-Angular\node_modules\@angular\compiler-cli\src\ngtsc\translator\src\translator.js:406:48)
    at LiteralExpr.visitExpression (E:\Angular\node_modules\@angular\compiler\bundles\compiler.umd.js:1554:28)
    at TypeTranslatorVisitor.translateExpression (E:\Angular\node_modules\@angular\compiler-cli\src\ngtsc\translator\src\translator.js:490:33)
    at E:\Angular\node_modules\@angular\compiler-cli\src\ngtsc\translator\src\translator.js:448:73
    at Array.map (<anonymous>)
    at TypeTranslatorVisitor.visitLiteralArrayExpr (E:\Angular\node_modules\@angular\compiler-cli\src\ngtsc\translator\src\translator.js:448:38)
    at LiteralArrayExpr.visitExpression (E:\Angular\node_modules\@angular\compiler\bundles\compiler.umd.js:1850:28)
    at TypeTranslatorVisitor.translateExpression (E:\Angular\node_modules\@angular\compiler-cli\src\ngtsc\translator\src\translator.js:490:33)
    at TypeTranslatorVisitor.visitExpressionType (E:\Angular\node_modules\@angular\compiler-cli\src\ngtsc\translator\src\translator.js:357:33)
    at ClusterMaster.onWorkerMessage (E:\Angular\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:165:27)
    at E:\Angular\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:49:95
    at ClusterMaster.<anonymous> (E:\Wap-Angular\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:245:57)
    at step (E:\Angular\node_modules\tslib\tslib.js:139:27)
    at Object.next (E:\Angular\node_modules\tslib\tslib.js:120:57)
    at E:\Angular\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (E:\Angular\node_modules\tslib\tslib.js:109:16)
    at EventEmitter.<anonymous> (E:\Angular\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:239:32)
    at EventEmitter.emit (events.js:223:5)
An unhandled exception occurred: NGCC failed.`

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
Angular CLI: 9.1.0
Node: 12.14.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/compiler-cli             9.0.7
@ngtools/webpack                  9.1.0
@nguniversal/builders             9.0.2
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0
**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Hello @yangjunfocus,

I know this error, as I experienced it while implementing a new feature in the compiler. I fixed this scenario in `@angular/compiler-cli` 9.1.0 but you are still on 9.0.7. This results in an incompatibility between `@angular/compiler` at version 9.1.0.

Please upgrade `@angular/compiler-cli` to 9.1.0 to fix the problem.

**Comment by yangjunfocus** [comment]
> Hello @yangjunfocus,
> 
> I know this error, as I experienced it while implementing a new feature in the compiler. I fixed this scenario in `@angular/compiler-cli` 9.1.0 but you are still on 9.0.7. This results in an incompatibility between `@angular/compiler` at version 9.1.0.
> 
> Please upgrade `@angular/compiler-cli` to 9.1.0 to fix the problem.

thank you very much！

**Comment by eliraneliassy** [comment]
> Hello @yangjunfocus,
> 
> I know this error, as I experienced it while implementing a new feature in the compiler. I fixed this scenario in `@angular/compiler-cli` 9.1.0 but you are still on 9.0.7. This results in an incompatibility between `@angular/compiler` at version 9.1.0.
> 
> Please upgrade `@angular/compiler-cli` to 9.1.0 to fix the problem.

Work for me! Thanks!

**Comment by balaji-b-v** [comment]
> Hello @yangjunfocus,
> 
> I know this error, as I experienced it while implementing a new feature in the compiler. I fixed this scenario in `@angular/compiler-cli` 9.1.0 but you are still on 9.0.7. This results in an incompatibility between `@angular/compiler` at version 9.1.0.
> 
> Please upgrade `@angular/compiler-cli` to 9.1.0 to fix the problem.

Works for me! Thanks.
