### ISSUE TITLE
Getting resource busy or locked, lstat 'C:/hiberfil.sys' Error after upgrading in Angular 9

### ISSUE THREAD

**Issue by Abhilashtiwari0301** [angular/angular#36270]
Hi Everyone , 

I am getting locked or busy error while running  ng serve , angular 8 working fine, Issue comes when i upgrade angular 9.

Error: EBUSY: resource busy or locked, lstat 'C:/hiberfil.sys'
    at Object.lstatSync (fs.js:923:3)
    at NodeJSFileSystem.lstat (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\node_js_file_system.js:41:72)
    at CachedFileSystem.lstat (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\cached_file_system.js:131:38)
    at C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:102:37
    at Array.filter (<anonymous>)
    at DirectoryWalkerEntryPointFinder.walkDirectoryForEntryPoints (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:101:18)
    at DirectoryWalkerEntryPointFinder.findEntryPoints (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\directory_walker_entry_point_finder.js:53:44)
    at analyzeEntryPoints (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\main.js:102:41)
    at new ClusterMaster (C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:40:30)
    at C:\Angular9-Project\MRR\webapp\src\main\webapp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\executor.js:45:46

**Comment by Abhilashtiwari0301** [comment]
hi @petebacondarwin , 
the solution which you given above (Can you try changing "baseUrl": "/", to "baseUrl": "./", in your tsconfig.json) is worked by changing the path in file src/tsconfig.app.json .

Thanks

**Comment by petebacondarwin** [comment]
Oh great! I think that is the correct solution. I thought in https://github.com/angular/angular/issues/36270#issuecomment-604655734 that you said it didn't work. Glad you have things working again. I'm going to close this.
If you have a recurrence or a different problem please open a new issue, linking to this one if necessary.
