### ISSUE TITLE
ng update 8.0 to 9.1 fails during ModuleWithProviders migration 

### ISSUE THREAD

**Issue by kernwig** [angular/angular#36346]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No, since updates are version specific.
### Description

Running `ng update @angular/cli @angular/core` on a fairly simple Angular 8.0.3 application fails with a nondescript error during ModuleWithProviders migration.

I have no custom Module.forRoot() code in my application, and attempted to work around the problem by temporarily removing all 3rd party libraries that do - but the failure persists.

## 🔬 Minimal Reproduction

Without a useful error message, I cannot reduce the problem down to minimal. Fortunately the application is open source and straight forward.

Repository is at https://github.com/kernwig/sqac-amplify
Clone via HTTPS or SSH:
```
git clone https://github.com/kernwig/sqac-amplify.git
git clone git@github.com:kernwig/sqac-amplify.git
```

The `develop` branch is the original working Angular 8 app.
The `update-dependencies` branch has 3rd party libraries with Angular components removed, to take them out of consideration as the problem.

## 🔥 Exception or Error

```
ng update @angular/cli @angular/core
The installed Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 36 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular/compiler-cli" has a missing peer dependency of "tslib" @ "^1.10.0".
                  Package "@angular/core" has a missing peer dependency of "tslib" @ "^1.10.0".
                  Package "@angular/platform-browser-dynamic" has a missing peer dependency of "tslib" @ "^1.10.0".
                  Package "@angular/compiler" has a missing peer dependency of "tslib" @ "^1.10.0".
                  Package "@angular/service-worker" has a missing peer dependency of "tslib" @ "^1.10.0".
                  Package "@angular/animations" has a missing peer dependency of "tslib" @ "^1.10.0".
                  Package "@angular/common" has a missing peer dependency of "tslib" @ "^1.10.0".
                  Package "@angular/platform-browser" has a missing peer dependency of "tslib" @ "^1.10.0".
                  Package "@angular/forms" has a missing peer dependency of "tslib" @ "^1.10.0".
                  Package "@angular/router" has a missing peer dependency of "tslib" @ "^1.10.0".
    Updating package.json with dependency @angular-devkit/build-angular @ "0.901.0" (was "0.803.25")...
    Updating package.json with dependency @angular/compiler-cli @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency @angular/core @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency typescript @ "3.8.3" (was "3.4.5")...
    Updating package.json with dependency @angular/compiler @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency @angular/service-worker @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency @angular/cli @ "9.1.0" (was "8.3.25")...
    Updating package.json with dependency @angular/animations @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency @angular/common @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency @angular/platform-browser @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency @angular/forms @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency @angular/router @ "9.1.0" (was "8.2.14")...
    Updating package.json with dependency zone.js @ "0.10.3" (was "0.9.1")...
UPDATE package.json (2040 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@angular/core' **

❯ Static flag migration.
  Removes the `static` flag from dynamic queries.
  As of Angular 9, the "static" flag defaults to false and is no longer required for your view and content queries.
  Read more about this here: https://v9.angular.io/guide/migration-dynamic-flag
UPDATE src/app/collections/widget/searchable-input.component.ts (5771 bytes)
  Migration completed.

❯ Missing @Injectable and incomplete provider definition migration.
  In Angular 9, enforcement of @Injectable decorators for DI is a bit stricter and incomplete provider definitions behave differently.
  Read more about this here: https://v9.angular.io/guide/migration-injectable
  Migration completed.

❯ ModuleWithProviders migration.
  In Angular 9, the ModuleWithProviders type without a generic has been deprecated.
  This migration adds the generic where it is missing.
  Read more about this here: https://v9.angular.io/guide/migration-module-with-providers
✖ Migration failed: Cannot read property 'lastIndexOf' of undefined
  See "/private/var/folders/vp/4nr1pk5n0mxf2qyy342k_g7h0000gn/T/ng-mFfCPk/angular-errors.log" for further details.

Adams-MacBook-Pro-2:sqac-amplify adamfanello$ ng update @angular/cli
Repository is not clean. Please commit or stash any changes before updating.

$ cat /private/var/folders/vp/4nr1pk5n0mxf2qyy342k_g7h0000gn/T/ng-mFfCPk/angular-errors.log
[error] TypeError: Cannot read property 'lastIndexOf' of undefined
    at Object.startsWith (/Users/adamfanello/dev/sqac/sqac-amplify/node_modules/typescript/lib/typescript.js:2044:20)
    at isPathRelativeToParent (/Users/adamfanello/dev/sqac/sqac-amplify/node_modules/typescript/lib/typescript.js:102732:23)
    at /Users/adamfanello/dev/sqac/sqac-amplify/node_modules/typescript/lib/typescript.js:102691:24
    at Object.firstDefined (/Users/adamfanello/dev/sqac/sqac-amplify/node_modules/typescript/lib/typescript.js:347:26)
    at getPathRelativeToRootDirs (/Users/adamfanello/dev/sqac/sqac-amplify/node_modules/typescript/lib/typescript.js:102689:23)
    at tryGetModuleNameFromRootDirs (/Users/adamfanello/dev/sqac/sqac-amplify/node_modules/typescript/lib/typescript.js:102550:40)
    at getLocalModuleSpecifier (/Users/adamfanello/dev/sqac/sqac-amplify/node_modules/typescript/lib/typescript.js:102408:44)
    at /Users/adamfanello/dev/sqac/sqac-amplify/node_modules/typescript/lib/typescript.js:102395:96
    at Array.map (<anonymous>)
    at Object.getModuleSpecifiers (/Users/adamfanello/dev/sqac/sqac-amplify/node_modules/typescript/lib/typescript.js:102395:57)
```

## 🌍 Your Environment

This is the pre-attempt version:
<pre><code>

Angular CLI: 8.3.25
Node: 12.16.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cli                      8.3.25
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.5.4
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

Nope.

**Comment by kernwig** [comment]
Migration now fails at a later stage. See issue #36582

**Comment by devversion** [comment]
Thanks for reporting back. This has been already solved with https://github.com/angular/angular/commit/ca677481a2ac3675b84698e2d16fd379e1799e2c. Let me know if there is anything else.
