### ISSUE TITLE
Angular 9 Undecorated classes with decorated fields migration fails

### ISSUE THREAD

**Issue by Serginho** [angular/angular#36522]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

## 🔬 Minimal Reproduction

`yarn ng update @angular/core@9 @angular/cli@9 --force`

## 🔥 Exception or Error
<pre><code>

[error] TypeError: Cannot read property 'kind' of undefined
    at Object.isClassDeclaration (/Users/user/company/company-web/node_modules/typescript/lib/typescript.js:11439:21)
    at Object.findBaseClassDeclarations (/Users/user/company/company-web/node_modules/@angular/core/schematics/utils/typescript/find_base_classes.js:31:32)
    at /Users/user/company/company-web/node_modules/@angular/core/schematics/migrations/undecorated-classes-with-decorated-fields/transform.js:83:71
    at Set.forEach (<anonymous>)
    at UndecoratedClassesWithDecoratedFieldsTransform._findUndecoratedAbstractDirectives (/Users/user/company/company-web/node_modules/@angular/core/schematics/migrations/undecorated-classes-with-    decorated-fields/transform.js:82:32)
    at UndecoratedClassesWithDecoratedFieldsTransform.migrate (/Users/user/company/company-web/node_modules/@angular/core/schematics/migrations/undecorated-classes-with-decorated-fields/transform.    js:41:18)
    at runUndecoratedClassesMigration (/Users/user/company/company-web/node_modules/@angular/core/schematics/migrations/undecorated-classes-with-decorated-fields/index.js:49:19)
    at /Users/user/company/company-web/node_modules/@angular/core/schematics/migrations/undecorated-classes-with-decorated-fields/index.js:37:17
    at MergeMapSubscriber.project (/Users/user/company/company-web/node_modules/@angular-devkit/schematics/src/rules/call.js:74:24)
    at MergeMapSubscriber._tryNext (/Users/user/company/company-web/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/user/company/company-web/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/user/company/company-web/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/Users/user/company/company-web/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/Users/user/company/company-web/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/user/company/company-web/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/Users/user/company/company-web/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.0
Node: 12.14.1
OS: darwin x64

Angular: 9.1.1
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      8.2.3
@angular/cli                      9.1.0
@angular/service-worker           8.2.14+3.sha-d2f7315
@bazel/bazel                      2.0.0
@bazel/bazel-darwin_x64           2.0.0
@bazel/hide-bazel-files           1.5.0
@bazel/ibazel                     v0.11.1
@bazel/karma                      1.2.2
@bazel/protractor                 1.2.2
@bazel/rollup                     1.2.2
@bazel/terser                     1.2.2
@bazel/typescript                 1.2.2
@ngtools/webpack                  8.3.25
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.39.2
</code></pre>

**Comment by tabuechn** [comment]
+1

**Comment by stephdz** [comment]
+1

**Comment by devversion** [comment]
Thanks @stephdz for this additional information. I assumed that it's due to unresolved declarations, but this gives me a good test case. Thanks!

**Comment by MariusBo** [comment]
I am still having this isssue 
[angular-errors.txt](https://github.com/angular/angular/files/4469303/angular-errors.txt)
