### ISSUE TITLE
ApplicationModule_Factory inject() must be called from an injection context

### ISSUE THREAD

**Issue by gvonhagel** [angular/angular#36606]
# 🐞 bug report

### Affected Package
@angular/universal

### Is this a regression?
I'm not sure

### Description
I am trying to write my own Universal rendering handler for Fastify. I used the @nguniversal/express-engine schematic but have attempted to implement my own handler using a Fastify middleware plugin. My logic for the rendering is based off of the express-engine and hapi-engine.

## 🔬 Minimal Reproduction

https://gist.github.com/gvonhagel/00e2f1bd9a088a706067d5c5a21d25d9

## 🔥 Exception or Error
<pre><code>
Error: inject() must be called from an injection context
    at injectInjectorOnly (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:4051643)
    at ɵɵinject (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:4051959)
    at Object.ApplicationModule_Factory [as factory] (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:4457212)
    at R3Injector.hydrate (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11583:39)
    at R3Injector.get (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11405:37)
    at D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11345:77
    at Set.forEach ()
    at new R3Injector (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11345:35)
    at createInjector (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11310:16)
    at new NgModuleRef$1 (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:24357:33)
    at NgModuleFactory.create (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:24424:20)
    at D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:28119:47
    at ZoneDelegate.invoke (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:3902460)
    at Object.onInvoke (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:27590:37)
    at ZoneDelegate.invoke (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:3902356)
    at Zone.run (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:3894874)
    at NgZone.run (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:27487:32)
    at PlatformRef.bootstrapModuleFactory (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:28115:27)
    at Object.renderModuleFactory (D:\StreetMetrics\Hyperion\node_modules\@angular\platform-server\bundles\platform-server.umd.js:1117:43)
    at CommonEngine. (D:\StreetMetrics\Hyperion\node_modules\@nguniversal\common\bundles\common-engine.umd.js:75:66)
    at step (D:\StreetMetrics\Hyperion\node_modules\tslib\tslib.js:139:27)
    at Object.next (D:\StreetMetrics\Hyperion\node_modules\tslib\tslib.js:120:57)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.3
Node: 12.16.1
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular-devkit/schematics-cli    0.13.8
@angular/cdk                      8.2.3
@angular/cli                      9.0.3
@angular/platform-server          9.0.7
@ngtools/webpack                  9.0.3
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.0.1
@schematics/angular               9.0.3
@schematics/schematics            0.13.8
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.1

</code></pre>

**Comment by gvonhagel** [comment]
Some additional information, if it's helpful:

I am able to successfully render content using the exported `renderModule` method from main.server.ts. I understand this is probably not the best way to go about things. Trying to import and use `renderModule` from `@angular/platform-server` throws the same error as above.

**Comment by JoostK** [comment]
It looks like you're bundling two copies of `@angular/core` somehow. The call stack refers to both `core.umd.js` and `main.js`, which causes the injector state to have been setup inside `core.umd.js` not to be available in the `main.js` module. Could you verify your bundling setup? I don't think this is an Angular issue.

**Comment by gvonhagel** [comment]
I was able to fix the issue. I'm not sure if it was necessary, but I wiped node_modules and reinstalled. Then I started getting "No NgModule metadata found for 'AppServerModule'.". Following #1363 I included `"bundleDependencies": false` in my angular.json because I do not include my server file in the bundle. Then I ran `ngcc` manually and was able to render using CommonEngine!

**Comment by petebacondarwin** [comment]
Glad you are fixed.
