### ISSUE TITLE
ngcc timeout does not quit process

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#36616]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
I don't know.

### Description
ngcc timeout does not stop the execution and the process will run infinitely. I have seen this behavior on our CI, where the build runs since 3 days.
The error occurs if there are multiple ng builds in parallel.

## 🔬 Minimal Reproduction
1. run a long running ngcc process
2. run another ngcc process which would run into the 25 seconds timeout.

## 🔥 Exception or Error
<pre><code>
[2020-04-11T11:56:45.990Z] > ng build "portal" "--prod" "--progress=false" "--i18n-locale=de" "--source-map"
[2020-04-11T11:57:09.822Z] Another process, with id 23892, is currently running ngcc.
[2020-04-11T11:57:09.822Z] Waiting up to 25s for it to finish.
[2020-04-11T11:57:36.823Z] Error: Timed out waiting 25s for another ngcc process, with id 23892, to complete.
[2020-04-11T11:57:36.823Z] (If you are sure no ngcc process is running then you should delete the lock-file at /.../node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
[2020-04-11T11:57:36.823Z]     at AsyncLocker.<anonymous> (/.../node_modules/@angular/compiler-cli/ngcc/src/locking/async_locker.js:91:31)
[2020-04-11T11:57:36.823Z]     at step (/.../node_modules/tslib/tslib.js:139:27)
[2020-04-11T11:57:36.823Z]     at Object.next (/.../node_modules/tslib/tslib.js:120:57)
[2020-04-11T11:57:36.823Z]     at fulfilled (/.../node_modules/tslib/tslib.js:110:62)
// end
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.1
Node: 12.16.1
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-ng-packagr   0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
ng-packagr                         9.1.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**
I think the spawned ngcc does not return correctly, because the error "NGCC failed" is missing.

https://github.com/angular/angular-cli/blob/00bf30650507b9f5d6c1cf91b483b8b64b98e096/packages/ngtools/webpack/src/ngcc_processor.ts#L75-L97

_EDIT:_
If the process is killed by Jenkins the output looks like:

<pre><code>
[2020-04-14T07:18:27.026Z] Sending interrupt signal to process
[2020-04-14T07:18:27.185Z] Sending interrupt signal to process
[2020-04-14T07:18:27.226Z] Sending interrupt signal to process
[2020-04-14T07:18:27.262Z] Sending interrupt signal to process
[2020-04-14T07:18:28.154Z] An unhandled exception occurred: NGCC failed.
</code></pre>

But it also does not return a non zero return code, the script execution is successful.

**Comment by petebacondarwin** [comment]
Hopefully #36622 will fix this...
