### ISSUE TITLE
Updated Angular 7 to 8 - Cannot set property 'urlAfterRedirects' of undefined

### ISSUE THREAD

**Issue by alecoder** [angular/angular#36866]
# 🐞 bug report

### Affected Package

{
  "name": "*****",
  "version": "3.0.1",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "build": "ng build --prod --aot --build-optimizer=true --extract-css",
    "serve": "ng serve --host \"dev.****.com\"  --port 443 --disableHostCheck --ssl true ",
    "serve:am": "ng serve --host \"dev.****.am\" --port 443 --ssl true",
    "start": "npm run serve",
    "start:am": "npm run serve:am",
    "tune-to:mob": "node build-tools/edit-to-mobile.js",
    "tune-to:desktop": "node build-tools/edit-to-desktop.js",
    "tune-to:desk": "npm run tune-to:desktop"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/platform-server": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@ngrx/effects": "^7.4.0",
    "@ngrx/entity": "^7.4.0",
    "@ngrx/router-store": "^7.4.0",
    "@ngrx/store": "^7.4.0",
    "@ngrx/store-devtools": "^7.4.0",
    "@types/stacktrace-js": "0.0.32",
    "core-js": "^3.1.3",
    "google-maps": "^3.3.0",
    "ng-un-slider": "1.1.67-alpha-2",
    "ng2-nouislider": "1.7.13",
    "ngrx-store-localstorage": "^7.0.0",
    "node-sass": "^4.12.0",
    "nouislider": "^12.1.0",
    "rxjs": "^6.5.0",
    "rxjs-compat": "6.5.2",
    "stacktrace-js": "^2.0.0",
    "webpack-dev-server": "^3.7.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.0",
    "@angular/cli": "^8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@types/google-maps": "^3.2.1",
    "@types/jasmine": "^3.5.10",
    "@types/node": "^13.13.4",
    "codelyzer": "^5.2.2",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^5.0.2",
    "karma": "^5.0.3",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-jasmine": "^3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "ngrx-store-freeze": "^0.2.4",
    "protractor": "^5.4.4",
    "rxjs-tslint": "^0.1.8",
    "ts-node": "~5.0.1",
    "tslint": "^6.1.2",
    "typescript": "~3.4.5",
    "webpack": "^4.43.0"
  }
}

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 After updating Angular 7 to Angular 8, build process and serve are working, but running project in browser throws these errors

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

core.js:5847 ERROR TypeError: Cannot set property 'urlAfterRedirects' of undefined
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.getTransition (router.js:4050)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.scheduleNavigation (router.js:4308)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.navigateByUrl (router.js:4229)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.initialNavigation (router.js:4062)
    at RouterInitializer.push../node_modules/@angular/router/fesm5/router.js.RouterInitializer.bootstrapListener (router.js:5693)
    at core.js:25244
    at Array.forEach (<anonymous>)
    at ApplicationRef.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef._loadComponent (core.js:25244)
    at ApplicationRef.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap (core.js:25157)
    at core.js:24872
defaultErrorLogger @ core.js:5847
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:5895
(anonymous) @ core.js:24934
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:24296
(anonymous) @ core.js:24934
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:386
onInvoke @ core.js:24337
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:385
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:143
(anonymous) @ zone.js:891
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:24328
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:601
Promise.then (async)
scheduleMicroTask @ zone.js:584
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:231
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:251
scheduleResolveOrReject @ zone.js:881
ZoneAwarePromise.then @ zone.js:1027
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:24867
./src/main.ts @ main.js:137008
__webpack_require__ @ bootstrap:78
0 @ main.js:137082
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:44
webpackJsonpCallback @ bootstrap:31
(anonymous) @ main.js:1
zone.js:690 Unhandled Promise rejection: Cannot set property 'urlAfterRedirects' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'urlAfterRedirects' of undefined
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.getTransition (router.js:4050)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.scheduleNavigation (router.js:4308)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.navigateByUrl (router.js:4229)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.initialNavigation (router.js:4062)
    at RouterInitializer.push../node_modules/@angular/router/fesm5/router.js.RouterInitializer.bootstrapListener (router.js:5693)
    at core.js:25244
    at Array.forEach (<anonymous>)
    at ApplicationRef.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef._loadComponent (core.js:25244)
    at ApplicationRef.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap (core.js:25157)
    at core.js:24872 TypeError: Cannot set property 'urlAfterRedirects' of undefined
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.getTransition (https://dev.*****.com/vendor.js:80861:38)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.scheduleNavigation (https://dev.*****.com/vendor.js:81119:35)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.navigateByUrl (https://dev.*****.com/vendor.js:81040:21)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.initialNavigation (https://dev.*****.com/vendor.js:80873:18)
    at RouterInitializer.push../node_modules/@angular/router/fesm5/router.js.RouterInitializer.bootstrapListener (https://dev.*****.com/vendor.js:82504:20)
    at https://dev.*****.com/vendor.js:61319:56
    at Array.forEach (<anonymous>)
    at ApplicationRef.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef._loadComponent (https://dev.*****.com/vendor.js:61319:19)
    at ApplicationRef.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap (https://dev.*****.com/vendor.js:61232:14)
    at https://dev.*****.com/vendor.js:60947:81
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.0
Node: 12.16.2
OS: linux x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular/http                     7.2.16
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.5.0
typescript                        3.4.5
webpack                           4.43.0
    

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Could you please provide a repro using stackblitz.com or in a form of a Github repo? Also, could you please try to run an app with v9 to see if you have the same problem?

**Comment by atscott** [comment]
Closing, per Andrew Kushnir's comment above. If you're still experiencing this problem, please submit a new issue with a reproduction.
