### ISSUE TITLE
Build error on Windows Subsystem Ubuntu 

### ISSUE THREAD

**Issue by symphony2014** [angular/angular#36900]
# 🐞 bug report

### Is this a regression?

 no

### Description

 I just fllow the (https://github.com/angular/angular/blob/master/docs/DEVELOPER.md) try to build angular from Windows Subsystem Ubuntu , bellow exception was threw.

## 🔬 Minimal Reproduction

 
1. Open windows Subsytem Ubuntu Command Promat.
2. `yarn install`
3. `node ./scripts/build/build-packages-dist.js `

## 🔥 Exception or Error
<pre><code>

symphony@symphony:/mnt/d/projects/angular$ node ./scripts/build/build-packages-dist.js
/home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/execroot/angular/bazel-out/k8-fastbuild/bin
##################################
scripts/build/build-packages-dist.js:
  Building @angular/* npm packages
  Mode: Production
##################################
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
//packages/upgrade:npm_package
//packages/service-worker:npm_package
//packages/router:npm_package
//packages/platform-webworker-dynamic:npm_package
//packages/platform-webworker:npm_package
//packages/platform-server:npm_package
//packages/platform-browser-dynamic:npm_package
//packages/platform-browser:npm_package
//packages/localize:npm_package
//packages/language-service:npm_package
//packages/forms:npm_package
//packages/elements:npm_package
//packages/core:npm_package
//packages/compiler-cli:npm_package
//packages/compiler:npm_package
//packages/common:npm_package
//packages/bazel:npm_package
//packages/animations:npm_package
INFO: Build options --define and --stamp have changed, discarding analysis cache.
DEBUG: Rule 'com_google_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1542334746 -0800"
DEBUG: Call stack for the definition of repository 'com_google_protobuf' which is a git_repository (rule definition at /home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/external/io_bazel_skydoc/setup.bzl:6:9
 - /home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/external/io_bazel_skydoc/setup.bzl:6:9
 - /home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/external/io_bazel_skydoc/setup.bzl:74:5
 - /mnt/d/projects/angular/WORKSPACE:84:1
INFO: Analyzed 18 targets (1 packages loaded, 13193 targets configured).
INFO: Found 18 targets...
ERROR: /mnt/d/projects/angular/packages/zone.js/lib/BUILD.bazel:9:1: Compiling TypeScript (devmode) //packages/zone.js/lib:zone_d_ts failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Broken pipe
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.base/java.io.BufferedOutputStream.write(Unknown Source)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3003)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2935)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:2954)
        at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1331)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2751)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2724)
        at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:2721)
        at com.google.devtools.build.lib.worker.WorkerProtocol$Input.writeTo(WorkerProtocol.java:220)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2800)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2775)
        at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:1040)
        at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
        at com.google.devtools.build.lib.worker.Worker.putRequest(Worker.java:125)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:353)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:190)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:129)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:229)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:124)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:89)
        at com.google.devtools.build.lib.actions.SpawnActionContext.beginExecution(SpawnActionContext.java:41)
        at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:331)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:124)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:931)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1070)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1041)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:608)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:903)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at /home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/bazel-workers/worker-17-TypeScriptCompile.log ---8<---8<---
[link_node_modules.js] [Error: EISDIR: illegal operation on a directory, symlink '/home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/execroot/angular/bazel-out/k8-fastbuild/bin' -> 'angular'] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'symlink',
  path: '/home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/execroot/angular/bazel-out/k8-fastbuild/bin',
  dest: 'angular'
}
---8<---8<--- End of log ---8<---8<---
INFO: Elapsed time: 3.218s, Critical Path: 1.07s
INFO: 2 processes: 2 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn --cwd "/mnt/d/projects/angular" --silent bazel build --config=release --config=view-engine //packages/upgrade:npm_package //packages/service-worker:npm_package //packages/router:npm_package //packages/platform-webworker-dynamic:npm_package //packages/platform-webworker:npm_package //packages/platform-server:npm_package //packages/platform-browser-dynamic:npm_package //packages/platform-browser:npm_package //packages/localize:npm_package //packages/language-service:npm_package //packages/forms:npm_package //packages/elements:npm_package //packages/core:npm_package //packages/compiler-cli:npm_package //packages/compiler:npm_package //packages/common:npm_package //packages/bazel:npm_package //packages/animations:npm_package
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at exec (/mnt/d/projects/angular/scripts/build/package-builder.js:116:18)
    at buildTargetPackages (/mnt/d/projects/angular/scripts/build/package-builder.js:76:3)
    at Object.<anonymous> (/mnt/d/projects/angular/scripts/build/build-packages-dist.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2572,
  stdout: null,
  stderr: null
}
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
This looks like a problem with the Bazel Java interaction. Perhaps you need to update your version of Java on your machine? I have:

```
java --version
java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

**Comment by alexeagle** [comment]
Java should be fetched by Bazel, shouldn't matter what's on your machine. (If it did, that would be a hermeticity bug)

Workaround is to turn off worker strategy for spawning the action: `--spawn_strategy=TypeScriptCompile=local`

**Comment by alexeagle** [comment]
(BTW the fact that Bazel prints a Java stack is purely noise here, it's just saying the compiler program wrote something to stdout when Bazel expects it to be reserved for the worker protocol.

Ultimate cause here is
```
  code: 'EISDIR',
  syscall: 'symlink',
  path: '/home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/execroot/angular/bazel-out/k8-fastbuild/bin',
```
so maybe hop into your ubuntu shell and see if you can repro such a problem without bazel?

**Comment by sonukapoor** [comment]
I actually have the same problem running in the regular `cmd`:

https://github.com/angular/angular/issues/35891

**Comment by symphony2014** [comment]
> Java should be fetched by Bazel, shouldn't matter what's on your machine. (If it did, that would be a hermeticity bug)
> 
> Workaround is to turn off worker strategy for spawning the action: `--spawn_strategy=TypeScriptCompile=local`

With thanks, I have tried that, but still got the  same exception.

**Comment by symphony2014** [comment]
Sorry too slow response on this, since I got a headache. I got more detail with `--verborse`.
```
$ yarn --cwd "/mnt/d/projects/angular" --verbose bazel build --config=release --config=view-engine //packages/upgrade:npm_package //packages/service-worker:npm_package //packages/router:npm_package //packages/platform-webworker-dynamic:npm_package //packages/platform-webworker:npm_package //packages/platform-server:npm_package //packages/platform-browser-dynamic:npm_package //packages/platform-browser:npm_package //packages/localize:npm_package //packages/language-service:npm_package //packages/forms:npm_package //packages/elements:npm_package //packages/core:npm_package //packages/compiler-cli:npm_package //packages/compiler:npm_package //packages/common:npm_package //packages/bazel:npm_package //packages/animations:npm_package
yarn run v1.21.1
verbose 0.2351562 Checking for configuration file "/mnt/d/projects/angular/.npmrc".
verbose 0.2361101 Checking for configuration file "/home/symphony/.npmrc".
verbose 0.2368521 Checking for configuration file "/usr/etc/npmrc".
verbose 0.2374671 Checking for configuration file "/mnt/d/projects/angular/.npmrc".
verbose 0.2378641 Checking for configuration file "/mnt/d/projects/.npmrc".
verbose 0.2382601 Checking for configuration file "/mnt/d/.npmrc".
verbose 0.2386734 Checking for configuration file "/mnt/.npmrc".
verbose 0.2395828 Checking for configuration file "/mnt/d/projects/angular/.yarnrc".
verbose 0.2399093 Found configuration file "/mnt/d/projects/angular/.yarnrc".
verbose 0.2405423 Checking for configuration file "/home/symphony/.yarnrc".
verbose 0.2408073 Found configuration file "/home/symphony/.yarnrc".
verbose 0.2417168 Checking for configuration file "/usr/etc/yarnrc".
verbose 0.2420314 Checking for configuration file "/mnt/d/projects/angular/.yarnrc".
verbose 0.2424435 Found configuration file "/mnt/d/projects/angular/.yarnrc".
verbose 0.2430668 Checking for configuration file "/mnt/d/projects/.yarnrc".
verbose 0.2433896 Checking for configuration file "/mnt/d/.yarnrc".
verbose 0.2437984 Checking for configuration file "/mnt/.yarnrc".
verbose 0.2496163 current time: 2020-05-09T01:07:47.889Z
$ bazelisk build --config=release --config=view-engine //packages/upgrade:npm_package //packages/service-worker:npm_package //packages/router:npm_package //packages/platform-webworker-dynamic:npm_package //packages/platform-webworker:npm_package //packages/platform-server:npm_package //packages/platform-browser-dynamic:npm_package //packages/platform-browser:npm_package //packages/localize:npm_package //packages/language-service:npm_package //packages/forms:npm_package //packages/elements:npm_package //packages/core:npm_package //packages/compiler-cli:npm_package //packages/compiler:npm_package //packages/common:npm_package //packages/bazel:npm_package //packages/animations:npm_package
INFO: Analyzed 18 targets (1 packages loaded, 175 targets configured).
INFO: Found 18 targets...
ERROR: /mnt/d/projects/angular/packages/zone.js/lib/BUILD.bazel:9:1: Compiling TypeScript (devmode) //packages/zone.js/lib:zone_d_ts failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: Broken pipe
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.base/java.io.BufferedOutputStream.write(Unknown Source)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3003)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2935)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:2954)
        at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1331)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2751)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2724)
        at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:2721)
        at com.google.devtools.build.lib.worker.WorkerProtocol$Input.writeTo(WorkerProtocol.java:220)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2800)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2775)
        at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:1040)
        at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:98)
        at com.google.devtools.build.lib.worker.Worker.putRequest(Worker.java:125)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:353)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.actuallyExec(WorkerSpawnRunner.java:190)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:129)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:229)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:124)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:89)
        at com.google.devtools.build.lib.actions.SpawnActionContext.beginExecution(SpawnActionContext.java:41)
        at com.google.devtools.build.lib.exec.ProxySpawnActionContext.beginExecution(ProxySpawnActionContext.java:60)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:331)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:124)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$4.execute(SkyframeActionExecutor.java:931)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1070)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1041)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:116)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:77)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:608)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:903)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:297)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:438)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at /home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/bazel-workers/worker-10-TypeScriptCompile.log ---8<---8<---
[link_node_modules.js] [Error: EISDIR: illegal operation on a directory, symlink '/home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/execroot/angular/bazel-out/host/bin' -> 'angular'] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'symlink',
  path: '/home/symphony/.cache/bazel/_bazel_symphony/9006a800b518625a1a1487fcdf47a323/execroot/angular/bazel-out/host/bin',
  dest: 'angular'
}
---8<---8<--- End of log ---8<---8<---
INFO: Elapsed time: 4.883s, Critical Path: 1.71s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
verbose 5.257231 Error: Command failed with exit code 1.
    at /mnt/d/projects/angular/.yarn/releases/yarn-1.21.1.js:36439:32
    at Generator.throw (<anonymous>)
    at step (/mnt/d/projects/angular/.yarn/releases/yarn-1.21.1.js:310:30)
    at /mnt/d/projects/angular/.yarn/releases/yarn-1.21.1.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
