### ISSUE TITLE
upgrade-phonecat-2-hybrid docs example fails with APF v10

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#36957]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

In https://github.com/angular/angular/pull/36944 we introduced APF v10, but this resulted in odd uglify error in the `upgrade-phonecat-2-hybrid` example.

The error looks like this:

```
(!) uglify plugin: The transformBundle hook used by plugin uglify is deprecated. The renderChunk hook should be used instead.
 
[!] (uglify plugin) SyntaxError: Error transforming bundle with 'uglify' plugin: Unexpected token: punc ())
 
SyntaxError: Error transforming bundle with 'uglify' plugin: Unexpected token: punc ())
 
    at JS_Parse_Error.get (eval at <anonymous> (/home/circleci/ng/aio/tools/examples/shared/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
 
    at handleError (/home/circleci/ng/aio/tools/examples/shared/node_modules/rollup/bin/rollup:606:35)
 
    at /home/circleci/ng/aio/tools/examples/shared/node_modules/rollup/bin/rollup:1093:9
```

And the most likely root cause is that the uglify version is very old. We tried switching that example over to use terser didn't help for some reason, but it's possible that the switch to terser was not performed correctly.

To unblock #36944 we temporarily disabled the example test. This issues is here to remind us to come back and resolve this minor issue.

For future reference the terser patch looked like this:

```
From 3f8cf1232650be5c3eecb20ec012814986413e16 Mon Sep 17 00:00:00 2001
From: Igor Minar <igor@angular.io>
Date: Wed, 6 May 2020 10:13:21 -0700
Subject: [PATCH] build: update upgrade-phonecat-2-hybrid to use terser instead
 of old uglify

This should hopefully resolve the following issue we see:

(!) uglify plugin: The transformBundle hook used by plugin uglify is deprecated. The renderChunk hook should be used instead.
[!] (uglify plugin) SyntaxError: Error transforming bundle with 'uglify' plugin: Unexpected token: punc ())
SyntaxError: Error transforming bundle with 'uglify' plugin: Unexpected token: punc ())
    at JS_Parse_Error.get (eval at <anonymous> (/home/circleci/ng/aio/tools/examples/shared/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at handleError (/home/circleci/ng/aio/tools/examples/shared/node_modules/rollup/bin/rollup:606:35)
    at /home/circleci/ng/aio/tools/examples/shared/node_modules/rollup/bin/rollup:1093:9
---
 .../rollup-config.js                          |  4 +-
 aio/tools/examples/shared/package.json        |  1 +
 aio/tools/examples/shared/yarn.lock           | 40 +++++++++++++++++++
 3 files changed, 43 insertions(+), 2 deletions(-)

diff --git a/aio/content/examples/upgrade-phonecat-2-hybrid/rollup-config.js b/aio/content/examples/upgrade-phonecat-2-hybrid/rollup-config.js
index c431e9d8e5e2..d0a29462c2f4 100644
--- a/aio/content/examples/upgrade-phonecat-2-hybrid/rollup-config.js
+++ b/aio/content/examples/upgrade-phonecat-2-hybrid/rollup-config.js
@@ -1,7 +1,7 @@
 // #docregion
 import nodeResolve from 'rollup-plugin-node-resolve'
 import commonjs from 'rollup-plugin-commonjs';
-import uglify from 'rollup-plugin-uglify'
+import terser from 'rollup-plugin-terser'
 
 //paths are relative to the execution path
 export default {
@@ -17,6 +17,6 @@ export default {
     commonjs({
       include: ['node_modules/rxjs/**']
     }),
-    uglify()
+    terser()
   ]
 }
diff --git a/aio/tools/examples/shared/package.json b/aio/tools/examples/shared/package.json
index a3c63cf4cd8d..766d0913af4b 100644
--- a/aio/tools/examples/shared/package.json
+++ b/aio/tools/examples/shared/package.json
@@ -81,6 +81,7 @@
     "rollup-plugin-commonjs": "^9.2.1",
     "rollup-plugin-node-resolve": "^4.0.0",
     "rollup-plugin-uglify": "^1.0.1",
+    "rollup-plugin-terser": "5.3.0",
     "source-map-explorer": "^1.3.2",
     "ts-node": "~8.3.0",
     "tslint": "~6.1.0",
diff --git a/aio/tools/examples/shared/yarn.lock b/aio/tools/examples/shared/yarn.lock
index 30760bdb6c23..5d5028ece880 100644
--- a/aio/tools/examples/shared/yarn.lock
+++ b/aio/tools/examples/shared/yarn.lock
@@ -4545,6 +4545,11 @@ estree-walker@^0.6.0:
   resolved "https://registry.yarnpkg.com/estree-walker/-/estree-walker-0.6.0.tgz#5d865327c44a618dde5699f763891ae31f257dae"
   integrity sha512-peq1RfVAVzr3PU/jL31RaOjUKLoZJpObQWJJ+LgfcxDUifyLZ1RjPQZTl0pzj2uJ45b7A7XpyppXvxdEqzo4rw==
 
+estree-walker@^0.6.1:
+  version "0.6.1"
+  resolved "https://registry.yarnpkg.com/estree-walker/-/estree-walker-0.6.1.tgz#53049143f40c6eb918b23671d1fe3219f3a1b362"
+  integrity sha512-SqmZANLWS0mnatqbSfRP5g8OXZC12Fgg1IwNtLsyHDzJizORW4khDfjPqJZsemPWBB2uqykUah5YpQ6epsqC/w==
+
 esutils@^2.0.2:
   version "2.0.2"
   resolved "https://registry.yarnpkg.com/esutils/-/esutils-2.0.2.tgz#0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b"
@@ -6495,6 +6500,14 @@ jest-worker@25.1.0, jest-worker@^25.1.0:
     merge-stream "^2.0.0"
     supports-color "^7.0.0"
 
+jest-worker@^24.9.0:
+  version "24.9.0"
+  resolved "https://registry.yarnpkg.com/jest-worker/-/jest-worker-24.9.0.tgz#5dbfdb5b2d322e98567898238a9697bcce67b3e5"
+  integrity sha512-51PE4haMSXcHohnSMdM42anbvZANYTqMrr52tVKPqqsPJMzoP6FYYDVqahX/HrAoKEKz3uUPzSvKs9A3qR4iVw==
+  dependencies:
+    merge-stream "^2.0.0"
+    supports-color "^6.1.0"
+
 js-tokens@^3.0.0:
   version "3.0.2"
   resolved "https://registry.yarnpkg.com/js-tokens/-/js-tokens-3.0.2.tgz#9866df395102130e38f7f996bceb65443209c25b"
@@ -9797,6 +9810,17 @@ rollup-plugin-node-resolve@^4.0.0:
     is-module "^1.0.0"
     resolve "^1.10.0"
 
+rollup-plugin-terser@5.3.0:
+  version "5.3.0"
+  resolved "https://registry.yarnpkg.com/rollup-plugin-terser/-/rollup-plugin-terser-5.3.0.tgz#9c0dd33d5771df9630cd027d6a2559187f65885e"
+  integrity sha512-XGMJihTIO3eIBsVGq7jiNYOdDMb3pVxuzY0uhOE/FM4x/u9nQgr3+McsjzqBn3QfHIpNSZmFnpoKAwHBEcsT7g==
+  dependencies:
+    "@babel/code-frame" "^7.5.5"
+    jest-worker "^24.9.0"
+    rollup-pluginutils "^2.8.2"
+    serialize-javascript "^2.1.2"
+    terser "^4.6.2"
+
 rollup-plugin-uglify@^1.0.1:
   version "1.0.2"
   resolved "https://registry.yarnpkg.com/rollup-plugin-uglify/-/rollup-plugin-uglify-1.0.2.tgz#d4aa6f5df13522eae1ba17780c7c4c7096038359"
@@ -9811,6 +9835,13 @@ rollup-pluginutils@^2.3.3:
     estree-walker "^0.6.0"
     micromatch "^3.1.10"
 
+rollup-pluginutils@^2.8.2:
+  version "2.8.2"
+  resolved "https://registry.yarnpkg.com/rollup-pluginutils/-/rollup-pluginutils-2.8.2.tgz#72f2af0748b592364dbd3389e600e5a9444a351e"
+  integrity sha512-EEp9NhnUkwY8aif6bxgovPHMoMoNr2FulJziTndpt5H9RdwC47GSGuII9XxpSdzVGM0GWrNPHV6ie1LTNJPaLQ==
+  dependencies:
+    estree-walker "^0.6.1"
+
 rollup@2.1.0:
   version "2.1.0"
   resolved "https://registry.yarnpkg.com/rollup/-/rollup-2.1.0.tgz#552e248e397a06b9c6db878c0564ca4ee06729c9"
@@ -11095,6 +11126,15 @@ terser@^4.4.3:
     source-map "~0.6.1"
     source-map-support "~0.5.12"
 
+terser@^4.6.2:
+  version "4.6.13"
+  resolved "https://registry.yarnpkg.com/terser/-/terser-4.6.13.tgz#e879a7364a5e0db52ba4891ecde007422c56a916"
+  integrity sha512-wMvqukYgVpQlymbnNbabVZbtM6PN63AzqexpwJL8tbh/mRT9LE5o+ruVduAGL7D6Fpjl+Q+06U5I9Ul82odAhw==
+  dependencies:
+    commander "^2.20.0"
+    source-map "~0.6.1"
+    source-map-support "~0.5.12"
+
 tfunk@^3.0.1:
   version "3.1.0"
   resolved "https://registry.yarnpkg.com/tfunk/-/tfunk-3.1.0.tgz#38e4414fc64977d87afdaa72facb6d29f82f7b5b"
```

**Comment by alan-agius4** [comment]
This error is also typically shown when there is a trailing comma in a function call.

I’ll have a chat with @devversion tomorrow.

**Comment by devversion** [comment]
@alan-agius4 I confirmed locally that switching to `terser` worked. It initially didn't work in https://github.com/IgorMinar/angular/commit/3f8cf1232650be5c3eecb20ec012814986413e16 because the rollup config change has not been applied to the AIO boilerplate, but rather to the concrete rollup config primarily used for doc regions.

So this change was actually a noop and on CI uglify was still used. I'll double-check tomorrow again.

**Comment by devversion** [comment]
The context for the failure is that now uglify runs on ES2015 output, as there is no downleveling step that converts the Angular framework es2015 output to ES5. Uglify does not support ES2015.

**Comment by alan-agius4** [comment]
@devversion glad to hear it’s fixed.  Feel free to add me as a reviewer.
