### ISSUE TITLE
@angular/compiler-cli:9.1.7 gives below error : Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by KrishnaAnanthi** [angular/angular#37173]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes it was working with 9.1.6 version

### Description

 A clear and concise description of the problem...
Angular/compiler-cli is not able to build angular 9.1.2 project

## 🔬 Minimal Reproduction

Do ng serve or ng build with angular project 9.1.2 using @angular/compiler-cli 9.1.7 gives the below error

[0m[91mCompiling @angular/forms : es2015 as esm2015
[0m[91mCompiling @angular/common/testing : es2015 as esm2015
[0m[91mCompiling @angular/router : es2015 as esm2015
[0m[91mCompiling ng2-tooltip-directive : es2015 as esm2015
[0m[91mCompiling @angular/platform-browser-dynamic : es2015 as esm2015
[0m[91mCompiling @angular/platform-browser/testing : es2015 as esm2015
[0m[91mCompiling @angular/platform-browser/animations : es2015 as esm2015
[0m[91mCompiling ngx-pagination : module as esm5
[0m[91mCompiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
[0m[91mCompiling @angular/common/http/testing : es2015 as esm2015
[0m[91mCompiling @ngx-translate/http-loader : es2015 as esm2015
[0m[91mCompiling @angular/router/testing : es2015 as esm2015
[0m[91m
[0m[91m
[0m[91m
ERROR in TypeError: Cannot read property 'start' of undefined
    at Object.addParseSpanInfo (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/diagnostics.js:54:32)
    at AstTranslator.visitPropertyRead (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:202:27)
    at PropertyRead.visit (/home/app/static/node_modules/@angular/compiler/bundles/compiler.umd.js:7753:28)
    at AstTranslator.translate (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:73:24)
    at AstTranslator.visitPropertyRead (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:200:66)
    at PropertyRead.visit (/home/app/static/node_modules/@angular/compiler/bundles/compiler.umd.js:7753:28)
    at AstTranslator.translate (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:73:24)
    at Object.astToTypescript (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:50:27)
    at TcbExpressionTranslator.translate (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1212:33)
    at tcbExpression (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1200:27)
    at processAttribute (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1474:24)
    at Array.forEach (<anonymous>)
    at tcbGetDirectiveInputs (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1427:30)
    at TcbDirectiveOp.execute (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:342:26)
    at Scope.executeOp (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:975:26)
    at Scope.render (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:888:22)

## 🔥 Exception or Error
<pre><code>

ng build:

> @angular/cli@9.1.1 postinstall /usr/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

+ @angular/cli@9.1.1
added 271 packages from 206 contributors in 7.516s

> node-sass@4.14.1 install /home/app/static/node_modules/node-sass
> node scripts/install.js

node-sass build Binary found at /home/app/static/node_modules/node-sass/vendor/linux_musl-x64-64/binding.node

> node-sass@4.14.1 postinstall /home/app/static/node_modules/node-sass
> node scripts/build.js

Binary found at /home/app/static/node_modules/node-sass/vendor/linux_musl-x64-64/binding.node
Testing binary
Binary is fine
node-sass@4.14.1 /home/app/static/node_modules/node-sass
[91mCompiling @angular/core : es2015 as esm2015
[0m[91mCompiling @angular/animations : es2015 as esm2015
[0m[91mCompiling @angular/compiler/testing : es2015 as esm2015
[0m[91mCompiling @angular/common : es2015 as esm2015
[0m[91mCompiling @angular/core/testing : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
[0m[91mCompiling @ngx-translate/core : es2015 as esm2015
[0m[91mCompiling @angular/common/http : es2015 as esm2015
[0m[91mCompiling @angular/platform-browser : es2015 as esm2015
[0m[91mCompiling @angular/animations/browser/testing : es2015 as esm2015
[0m[91mCompiling @angular/forms : es2015 as esm2015
[0m[91mCompiling @angular/common/testing : es2015 as esm2015
[0m[91mCompiling @angular/router : es2015 as esm2015
[0m[91mCompiling ng2-tooltip-directive : es2015 as esm2015
[0m[91mCompiling @angular/platform-browser-dynamic : es2015 as esm2015
[0m[91mCompiling @angular/platform-browser/testing : es2015 as esm2015
[0m[91mCompiling @angular/platform-browser/animations : es2015 as esm2015
[0m[91mCompiling ngx-pagination : module as esm5
[0m[91mCompiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
[0m[91mCompiling @angular/common/http/testing : es2015 as esm2015
[0m[91mCompiling @ngx-translate/http-loader : es2015 as esm2015
[0m[91mCompiling @angular/router/testing : es2015 as esm2015
[0m[91m
[0m[91m
[0m[91m
ERROR in TypeError: Cannot read property 'start' of undefined
    at Object.addParseSpanInfo (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/diagnostics.js:54:32)
    at AstTranslator.visitPropertyRead (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:202:27)
    at PropertyRead.visit (/home/app/static/node_modules/@angular/compiler/bundles/compiler.umd.js:7753:28)
    at AstTranslator.translate (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:73:24)
    at AstTranslator.visitPropertyRead (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:200:66)
    at PropertyRead.visit (/home/app/static/node_modules/@angular/compiler/bundles/compiler.umd.js:7753:28)
    at AstTranslator.translate (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:73:24)
    at Object.astToTypescript (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:50:27)
    at TcbExpressionTranslator.translate (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1212:33)
    at tcbExpression (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1200:27)
    at processAttribute (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1474:24)
    at Array.forEach (<anonymous>)
    at tcbGetDirectiveInputs (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1427:30)
    at TcbDirectiveOp.execute (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:342:26)
    at Scope.executeOp (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:975:26)
    at Scope.render (/home/app/static/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:888:22)

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

ng build/serve of angular 9 project doesnt work with 9.1.7 compiler-cli in windows 10, debian os or jenkins also

**Comment by JoostK** [comment]
Hi,

using different versions of Angular framework is not supported. So `@angular/compiler-cli` 9.1.7 requires the usage of `@angular/compiler` 9.1.7 and also the other Angular framework versions need to be the same version, except for the CLI (`@angular/cli`) as it follows its own release cycle.
