### ISSUE TITLE
Confusing error when route's matcher is not exported

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular#37290]
### Versions
```
Angular CLI: 1.5.0
Node: 8.2.1
OS: darwin x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular/platform-server: 5.0.0-rc.8
@angular/service-worker: 1.0.0-beta.16
@angular-devkit/build-optimizer: 0.0.31
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
typescript: 2.4.2
webpack: 3.8.1
```

### Repro steps

Use a matcher which is not an exported function.

```
// dummy matcher
function matcher() { return null }

const routes = [
  { matcher, loadChildren: 'a/valid/path#GoesHere' }
]
```

### Observed behavior
```
ERROR in TypeError: Cannot read property 'loadChildren' of undefined
    at _collectLoadChildren (.../node_modules/@angular/compiler/bundles/compiler.umd.js:28561:20)
    at listLazyRoutes (.../node_modules/@angular/compiler/bundles/compiler.umd.js:28536:49)
    at visitLazyRoute (.../node_modules/@angular/compiler/bundles/compiler.umd.js:29937:47)
    at AotCompiler.listLazyRoutes (.../node_modules/@angular/compiler/bundles/compiler.umd.js:29905:20)
    at AngularCompilerProgram.listLazyRoutes (.../node_modules/@angular/compiler-cli/src/transformers/program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (.../node_modules/@angular/compiler-cli/src/ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (.../node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:246:66)
    at Promise.resolve.then.then (.../node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:542:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

### Desired behavior

A non-cryptic error message, like the usual AOT one about "consider replacing lambda with an exported function" or whatever it was.

**Comment by alxhub** [comment]
This is indeed a bug with View Engine's route enumeration. Ivy does not rely on this code (and eventually, it won't rely on the enumeration of routes in general), so the fix here is to update to Ivy.

**Comment by jamie-pate** [comment]
Can you run ivy with aot: false? or does that automatically revert to view engine? I'm getting a similar error when using the spread operator inside a route list with route objects generated by a function call.

**Comment by JoostK** [comment]
> Can you run ivy with aot: false? or does that automatically revert to view engine? I'm getting a similar error when using the spread operator inside a route list with route objects generated by a function call WITH ivy (but only when aot: false)

Disabling AOT but not Ivy would be the JIT support in Ivy, **if `@angular/core` has been processed with ngcc**. If ngcc has not run then the runtime will not have been switched from View Engine to Ivy, so you'd then incorrectly get View Engine.

I am closing this issue as resolved in Ivy, as provider definitions are no longer processed in any way by the compiler.
