### ISSUE TITLE
Elements lazy load make unable to use providers in modules

### ISSUE THREAD

**Issue by richardlnnr** [angular/angular#37441]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/elements.

### Is this a regression?

I'm not sure.

### Description

When you export a Custom Element that contains a lazy load module, you aren't able to create a service without the providedIn: 'root'.
If you create a service with a @Injectable() and than make the provider in a module under the lazy load module, it'll break the application and throw a no provider error.

[The service code](https://github.com/richardlnnr/angular-lazy-load-injectable/blob/master/src/app/feature/content/content.service.ts#L3)

[The providers in the module under a Lazy load route](https://github.com/richardlnnr/angular-lazy-load-injectable/blob/master/src/app/feature/content/content.module.ts#L13)

## 🔬 Minimal Reproduction

https://richardlnnr.github.io/angular-lazy-load-injectable/

https://github.com/richardlnnr/angular-lazy-load-injectable

## 🔥 Exception or Error
<pre><code>
core.js:6228 ERROR NullInjectorError: R3InjectorError(AppModule)[ContentService -> ContentService -> ContentService]: 
  NullInjectorError: No provider for ContentService!
    at NullInjector.get (http://localhost:4200/vendor.js:8310:27)
    at R3Injector.get (http://localhost:4200/vendor.js:22304:33)
    at R3Injector.get (http://localhost:4200/vendor.js:22304:33)
    at R3Injector.get (http://localhost:4200/vendor.js:22304:33)
    at NgModuleRef$1.get (http://localhost:4200/vendor.js:39605:33)
    at Object.get (http://localhost:4200/vendor.js:37339:35)
    at getOrCreateInjectable (http://localhost:4200/vendor.js:12112:39)
    at Module.ɵɵdirectiveInject (http://localhost:4200/vendor.js:26119:12)
    at NodeInjectorFactory.ContentComponent_Factory [as factory] (http://localhost:4200/feature-feature-module.js:26:162)
    at getNodeInjectable (http://localhost:4200/vendor.js:12257:44)
</code></pre>

<pre><code>
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[ContentService -> ContentService -> ContentService]: 
  NullInjectorError: No provider for ContentService!
NullInjectorError: R3InjectorError(AppModule)[ContentService -> ContentService -> ContentService]: 
  NullInjectorError: No provider for ContentService!
    at NullInjector.get (core.js:1085)
    at R3Injector.get (core.js:16955)
    at R3Injector.get (core.js:16955)
    at R3Injector.get (core.js:16955)
    at NgModuleRef$1.get (core.js:36329)
    at Object.get (core.js:33972)
    at getOrCreateInjectable (core.js:5848)
    at Module.ɵɵdirectiveInject (core.js:21103)
    at NodeInjectorFactory.ContentComponent_Factory [as factory] (content.component.ts:9)
    at getNodeInjectable (core.js:5993)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.7
Node: 10.18.0
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by andersonmelo** [comment]
I have the same problem in my project

**Comment by wellingtonngallo** [comment]
I have the same problem here

**Comment by marcelobotega** [comment]
Hello, i have the same problem here :)

**Comment by gkalpak** [comment]
The problem is that you never load `ContentModule` (where the `ContentService` is provided). In `FeatureRoutingModule` you load the `ContentComponent` [directly][1], so `ContentModule` is never loaded into the app.

For service provided in `@NgModule.providers` to be available you need to ensure that the corresponding module is loaded into the app. In your case, you have the following options:

1. Use `providedIn: 'root'` (which is the recommended way in most cases, as it [allows tree-shaking][2]) :grin:
2. In `FeatureRoutingModule`, load the `ContentModule` (via `loadChildren: () => import('./content/content.module').then(m => m.ContentModule)`) and in `ContentModule` import `RouterModule.forChild([{path: '', component: ContentComponent}])`.
3. Provide the `ContentService` in the `FeatureModule` (which is already loaded into the app).
4. Provide `ContentService` on the `ContentComponent` (via [@Component.providers][3].

##
Closing since everything works as expected, but feel free to continue the discussion below (in case I missed something or you need more info).

[1]: https://github.com/richardlnnr/angular-lazy-load-injectable/blob/ef389396369f745b63ad21f6dbf00a7e89414dfa/src/app/feature/feature-routing.module.ts#L15
[2]: https://v9.angular.io/guide/dependency-injection-providers#creating-tree-shakable-providers
[3]: https://v9.angular.io/api/core/Directive#providers

**Comment by richardlnnr** [comment]
Thanks @gkalpak it really works

**Comment by richardlnnr** [comment]
Hey @gkalpak I have a doubt.
Why this code works without custom elements? When you do the bootstrap of the AppComponent at AppModule, this code works normally.

**Comment by gkalpak** [comment]
Can you show an example of it working?

**Comment by richardlnnr** [comment]
Of course, if you see this branch.
https://github.com/richardlnnr/angular-lazy-load-injectable/tree/feat/without-custom-element

You'll see that this same code work normally

**Comment by gkalpak** [comment]
It turns out my analysis in https://github.com/angular/angular/issues/37441#issuecomment-639737971 is completely wrong :grin:
I didn't realize that you _are_ importing `ContentModule` [in `FeatureModule`][1] and therefore it should work.

The problem seems to be how we create the component in `@angular/elements` and in particular how we pass in the injector. This line seems to be the problem:

https://github.com/angular/angular/blob/1197965e69d658c92422d49b1f2a1ba90498af67/packages/elements/src/component-factory-strategy.ts#L153

Replacing that with `Injector.NULL` (which is how components are created [outside of `@angular/elements`][2]) seems to fix the problem. I am not an expert on `Injector`s, so I am not sure what is the correct way to fix this (and how much of a breaking change it will be).

[1]: https://github.com/richardlnnr/angular-lazy-load-injectable/blob/ef389396369f745b63ad21f6dbf00a7e89414dfa/src/app/feature/feature.module.ts#L14
[2]: https://github.com/angular/angular/blob/1197965e69d658c92422d49b1f2a1ba90498af67/packages/core/src/application_ref.ts#L690

**Comment by JoostK** [comment]
Minimum repro without `@angular/elements` nor `@angular/router`, as they complicate debugging significantly (it took me over an hour to figure out where the root cause was):

https://stackblitz.com/edit/angular-ivy-n9vavs?file=src%2Fapp%2Fapp.component.ts

The issue originates from to the fact that an Angular element is registered using a _module injector_, whereas dynamic components are typically created from _element injectors_.  There's a special design at play which only deals with _element injectors_, [original design doc can be found here](https://docs.google.com/document/d/1OEUIwc-s69l1o97K0wBd_-Lth5BBxir1KuCRWklTlI4/edit#heading=h.xgjl2srtytjt).

**Comment by JoostK** [comment]
Below is a diagram of the injector tree.

![Unknown](https://user-images.githubusercontent.com/123679/85201783-55434580-b302-11ea-9252-c6d97c88c1f2.png)

On the left, the typical scenario is outlined. In `ComponentFactory.create`, one can pass an `Injector` and `NgModuleRef` for which a "switch" injector is created (in purple). The numbers show the path that is followed when injecting `NgModuleRef` and the injector with a thicker outline is the `NgModuleRef` that is resolved. The numbers in red indicate that this request is "tainted" with a default value, which is interpreted in the purple injectors to instruct them to skip their NgModule injector. This is why the `AppModule` is not considered after step 5, but instead the resolution continues from the first purple injector. This allows the resolution to properly resolve `NgModuleRef` from `LazyModule` as desired.

From the above, it can be observed that the node injector tree and NgModule injector tree are only ever connected through the switch injector which is aware of the tainted resolutions, allowing for the system to work.

The scenario on the right is how things are setup with `@angular/elements`. When registering an NgElement, you pass it an `Injector`. This is typically the `NgModule` itself, or a derived injector using `Injector.create({ parent: ngModuleInjector })`. This injector will be considered to represent the "view injector", hence a "tainted" resolution will first attempt to use this injector (step 2) before considered its NgModule injector (which is `LazyMod` in this case). However, no switch injector will be hit this time, so  there is nothing to detect the magic default that should prevent resolution further up the tree. As such, `AppModule` will happily resolve its own `NgModuleRef<AppModule>` and that will be injected, whereas `AppModuleRef<LazyModule>` was expected.

---

The suggestion proposed by @gkalpak of changing `childInjector` into `Injector.NULL` does indeed prevent this particular issue, as doing so changes step 2 to end up in the null injector, allowing the switch injector to switch to the NgModule injector tree which starts at `LazyMod` as desired. _However_ this approach has a major flaw: a custom injector created using `Injector.create` that provides additional tokens will be ignored altogether, which is most certainly an issue.

---

One could argue that `ComponentFactory.create` could inspect the `injector` to see if it corresponds with a module injector, or a view injector and configure the switch injector accordingly. Unfortunately, I don't think this can work correctly in the presence of custom injectors, as there is no way to detect what would be the cut-off point between a custom injector and an NgModule injector (essentially the point where the switch injector would typically exist).

A possible resolution could be to move the recognition of the magic default value into `NgModuleRef`, so that module injectors themselves will identity the cut-off point instead of the switch injector created by `ComponentFactory.create`.

---

Errata: where I mention the _switch injector_ the original design doc refers to it as _merge injector_.

**Comment by JoostK** [comment]
@richardlnnr A silly workaround could be to create a "fake" element injector by instantiating a component and using its injector:

```ts
@Component({ template: '' })
export class Workaround37441Component {}

export function createInjector_workaround37441(ngModule: NgModuleRef<unknown>): Injector {
  const cf = ngModule.componentFactoryResolver.resolveComponentFactory(Workaround37441Component);
  return cf.create(Injector.NULL, undefined, undefined, ngModule).injector;
}
```

Then change `AppModule` to inject `NgModuleRef<unknown>` instead of `Injector` and manually create an injector using the above fn:

```ts
export class AppModule {
  constructor(module: NgModuleRef<AppModule>) {
    const injector = createInjector_workaround37441(module);
    const el = createCustomElement(AppComponent, { injector });
    customElements.define('element-injectable', el);
  }

  ngDoBootstrap() {}
}
```

**Comment by richardlnnr** [comment]
Hey @JoostK this workaround can generate any side effect?

**Comment by JoostK** [comment]
@richardlnnr I can't think of any, no.

**Comment by ericferreira1992** [comment]
I'm was having the same problem. I added all providers in module, also removed the ``provideIn: root`` of these providers wich is injected on my component and added these providers in ``providers: [ ... ]`` of it. In my case, it worked for me.

**Comment by erosmazza** [comment]
> Minimum repro without `@angular/elements` nor `@angular/router`, as they complicate debugging significantly (it took me over an hour to figure out where the root cause was):
> 
> https://stackblitz.com/edit/angular-ivy-n9vavs?file=src%2Fapp%2Fapp.component.ts
> 
> The issue originates from to the fact that an Angular element is registered using a _module injector_, whereas dynamic components are typically created from _element injectors_. There's a special design at play which only deals with _element injectors_, [original design doc can be found here](https://docs.google.com/document/d/1OEUIwc-s69l1o97K0wBd_-Lth5BBxir1KuCRWklTlI4/edit#heading=h.xgjl2srtytjt).

I tried to correct this project to have a working solution:
https://stackblitz.com/edit/angular-ivy-jwxrj1

the trick is to get the new injector in the moduleFatcory obtained from lazyModule.create(). This injector has the LazyService instance to make it available for injection!
Hope this could help

**Comment by gpavankv** [comment]
> > Minimum repro without `@angular/elements` nor `@angular/router`, as they complicate debugging significantly (it took me over an hour to figure out where the root cause was):
> > https://stackblitz.com/edit/angular-ivy-n9vavs?file=src%2Fapp%2Fapp.component.ts
> > The issue originates from to the fact that an Angular element is registered using a _module injector_, whereas dynamic components are typically created from _element injectors_. There's a special design at play which only deals with _element injectors_, [original design doc can be found here](https://docs.google.com/document/d/1OEUIwc-s69l1o97K0wBd_-Lth5BBxir1KuCRWklTlI4/edit#heading=h.xgjl2srtytjt).
> 
> I tried to correct this project to have a working solution: https://stackblitz.com/edit/angular-ivy-jwxrj1
> 
> the trick is to get the new injector in the moduleFatcory obtained from lazyModule.create(). This injector has the LazyService instance to make it available for injection! Hope this could help

In real life there's no chance an app.component contains a lazy module, a component and a service. Also, example talks about a single module but what if there are multiple lazy loaded modules and nested providers?

Feel like we will need a better solution and eagerly waiting on it.

Thanks in advance!

**Comment by phoenix741** [comment]
I have the same problem too, the workaround seems to resolve the problem in my case. 

Is the issue will be resolved in the @angular/elements ?

**Comment by jberndsen** [comment]
I just want to share that this issue still exists for me using Angular 15.2.9

**Comment by jayordway** [comment]
> I just want to share that this issue still exists for me using Angular 15.2.9

Yes, the issue is present and the suggested workaround doesn't seem to work on versions of angular on and past v14.

**Comment by arturovt** [comment]
@JeanMeche I tried to reproduce this on current `main` and it no longer happens.

I used the same setup as the reproduction: a custom element created with `createCustomElement`, whose component creates a child component with a lazy NgModule injector (the same way `router-outlet` does for a lazy route). The child injects a service that only the lazy module provides. The service now resolves without a `NullInjectorError`.

This was likely fixed when `Injector.create` switched from the old `StaticInjector` to `R3Injector`. `createCustomElement` wraps the given injector with `Injector.create`, and `StaticInjector` threw instead of letting the lookup continue to the lazy module's injector. That is why the error came from `R3InjectorError(AppModule)`.

Note: I tested without the router itself, but the injector setup is the same one `router-outlet` uses. If anyone still sees this on a recent Angular version, please share a StackBlitz. Otherwise I think this can be closed.
