### ISSUE TITLE
fix(ngcc): error in async mode when worker crashes while writing files

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#37743]
When ngcc runs in async mode and one of the worker processes crashes while writing files, other worker processes may crash with the error `The given rootPath undefined in not a file of the program` ([example failure][1]):

```
...
Warning: Worker #2 exited unexpectedly (code: null | signal: SIGKILL).
  Current task: {entryPoint: @angular/material/button-toggle, formatProperty: es2015, processDts: true}
  Current phase: writing files
...
Error: Error on worker #9: Error: The given rootPath undefined is not a file of the program.
    at getRootFileOrFail (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:2323:19)
    at Esm2015ReflectionHost.computePublicDtsDeclarationMap (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:1647:27)
    at Esm2015ReflectionHost.getDtsDeclaration (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/ngcc/src/host/esm2015_host.js:457:53)
    at DelegatingReflectionHost.getDtsDeclaration (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/ngcc/src/host/delegating_host.js:62:34)
    at Object.wrapTypeReference (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:463:34)
    at extractDirectiveMetadata (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.js:256:27)
    at DirectiveDecoratorHandler.analyze (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.js:81:35)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:346:40)
    at analyze (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:298:58)
    at _loop_1 (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:320:21)
    at ClusterMaster.onWorkerMessage (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /home/circleci/ng/aio/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:140:27)
    at Object.next (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:121:57)
    at /home/circleci/ng/aio/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:110:16)
    at EventEmitter.<anonymous> (/home/circleci/ng/aio/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (events.js:223:5)
```

[1]: https://circleci.com/gh/angular/angular/747404

**Comment by gkalpak** [comment]
From a quick investigation I haven't found out why this could be happening. Also, I haven't seen it recently, so maybe this has been fixed in recent versions.

Closing this issue for now. (I will re-open it if I see it again.)
