### ISSUE TITLE
[ng10] ng build causes TS RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ScarletFlash** [angular/angular#37748]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular-devkit/build-angular

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ^0.901.7

### Description

After upgrading from ng 9.1.9 to 10.0.0, `ng build` causes error.

## 🔬 Minimal Reproduction
Build huge project and observe terminal output.

## 🔥 Exception or Error
<pre><code>
ERROR in RangeError: Maximum call stack size exceeded
    at typeParameterToName (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:39678:41)
    at typeParameterToDeclarationWithConstraint (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:39337:28)
    at typeToTypeNodeHelper (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38771:55)
    at typeReferenceToTypeNode (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38968:43)
    at typeToTypeNodeHelper (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38766:95)
    at typeToTypeNodeHelper (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38823:43)
    at mapToTypeNodes (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:39236:40)
    at typeToTypeNodeHelper (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38790:37)
    at typeToTypeNodeHelper (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38825:40)
    at mapToTypeNodes (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:39236:40)
    at typeToTypeNodeHelper (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38790:37)
    at typeToTypeNodeHelper (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38825:40)
    at mapToTypeNodes (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:39236:40)
    at typeToTypeNodeHelper (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38790:37)
    at typeToTypeNodeHelper (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:38825:40)
    at mapToTypeNodes (/home/console/projects/___-__________/__________/___________frontend/node_modules/typescript/lib/typescript.js:39236:40)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.18.1
OS: linux x64

Angular: 10.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
Same reproduction on node v14.

Relative issue: https://github.com/microsoft/TypeScript/issues/39138

**Comment by JoostK** [comment]
Heya @ScarletFlash,

could you try upgrading to TypeScript 3.9.6, as the issue you linked (https://github.com/microsoft/TypeScript/issues/39138) has been closed as fixed in that version, and I'm hoping this resolves the issue for you.

**Comment by ScarletFlash** [comment]
> Heya @ScarletFlash,
> 
> could you try upgrading to TypeScript 3.9.6, as the issue you linked ([microsoft/TypeScript#39138](https://github.com/microsoft/TypeScript/issues/39138)) has been closed as fixed in that version, and I'm hoping this resolves the issue for you.

Sure. I'll try to do it ASAP.

**Comment by ScarletFlash** [comment]
So, with TypeScript 3.9.6 `ng build` goes well.
