### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: spawn ENOMEM

### ISSUE THREAD

**Issue by GlauberF** [angular/angular#37856]
# 🐞 bug report

### Affected Package
@angular/*

### Description
when running the command `node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng serve --open` I get an error.

## 🔥 Exception or Error
<pre><code>
(node:7700) UnhandledPromiseRejectionWarning: Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at Object.spawn (child_process.js:548:9)
    at module.exports (/var/www/html/pwa_vimbo/node_modules/open/index.js:144:34)
(node:7700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1469)
(node:7700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.0
Node: 12.18.1
OS: linux x64

Angular: 10.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cli                      10.0.0
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  10.0.0
@nguniversal/builders             10.0.0
@nguniversal/common               10.0.0
@nguniversal/express-engine       10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0

</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @GlauberF,

It looks like the problem might be related to the Angular CLI, so I'm transferring this issue there for further investigation.

Also, it'd be helpful if you could provide some additional information about this issue:

- is this problem appeared after Angular upgrade (if so, which versions you had before) or NodeJS upgrade
- if the project was created using Angular CLI (`ng new`)
- if the problem started to happen after you added/removed some packages

Thank you.
