### ISSUE TITLE
[BUG]:  Cannot determine the module for class AbstractFormGroupDirective in @angular/forms/forms.d.ts! Add AbstractFormGroupDirective to the NgModule to fix it.

### ISSUE THREAD

**Issue by splincode** [angular/angular#37926]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/form

### Is this a regression?

Yes

### Description

Our NGXS `@ngxs/form-plugin` use FormGroupDirective for inject in own FormDirective:
https://github.com/ngxs/store/blob/master/packages/form-plugin/src/directive.ts#L32

But after upgrade to Angular 10 we have problem with building package:

```
------------------------------------------------------------------------------
Building entry point '@ngxs/form-plugin'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: : Cannot determine the module for class AbstractFormGroupDirective in /Users/splincode/Downloads/Develop/store/node_modules/@angular/forms/forms.d.ts! Add AbstractFormGroupDirective to the NgModule to fix it.

ngPackagr build failed Error: : Cannot determine the module for class AbstractFormGroupDirective in /Users/splincode/Downloads/Develop/store/node_modules/@angular/forms/forms.d.ts! Add AbstractFormGroupDirective to the NgModule to fix it.

    at Object.<anonymous> (/Users/splincode/Downloads/Develop/store/build/angular-7/node_modules/src/lib/ngc/compile-source-files.ts:103:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/splincode/Downloads/Develop/store/build/angular-7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:4:58)
Error building ngxs Error: : Cannot determine the module for class AbstractFormGroupDirective in /Users/splincode/Downloads/Develop/store/node_modules/@angular/forms/forms.d.ts! Add AbstractFormGroupDirective to the NgModule to fix it.

    at Object.<anonymous> (/Users/splincode/Downloads/Develop/store/build/angular-7/node_modules/src/lib/ngc/compile-source-files.ts:103:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/splincode/Downloads/Develop/store/build/angular-7/node_modules/ng-packagr/lib/ngc/compile-source-files.js:4:58)
error Command failed with exit code 111.
```

## 🔬 Minimal Reproduction

```
$ git clone https://github.com/ngxs/store.git
$ git checkout -b feat/ng10 origin/feat/ng10
$ yarn install 
$ yarn build
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular 10.0.2
</code></pre>

**Comment by JoostK** [comment]
I am confused by the reproduction + "exception or error" above, which don't appear to be related to the description?

**Comment by JoostK** [comment]
About the log in the description and after looking at the draft PR to upgrade to NG10, you appear to be compiling using Angular 7,8,9,10 with an Angular installation of just v10? It's no surprise to me that v10 cannot necessarily be compiled using an older version of the compiler, that is not something that is supported.

**Comment by splincode** [comment]
```
I am confused by the reproduction + "exception or error" above
```

Sorry, updated

**Comment by splincode** [comment]
@markwhitfeld `you appear to be compiling using Angular 7,8,9,10 with an Angular installation of just v10`
what do you think about? I know that the old compiler is used for backward compatibility with older versions of Angular app

**Comment by JoostK** [comment]
I think the right thing to do for the backward compatibility support is to depend on the desired version in full, instead of just the compiler.

**Comment by splincode** [comment]
@JoostK When we build with `@angular/compiler@10` it's success. But when we running `yarn integration:ng6` or `yarn integration:ng8` we have problem:

```
Hash: 004442c04b217230e68d
Time: 3706ms
chunk {0} runtime.6afe30102d8fe7337431.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} polyfills.845bd3cdedc13b3c53dd.js (polyfills) 130 bytes [initial] [rendered]
chunk {2} main.6a9fd9a4fd7f03800813.js (main) 128 bytes [initial] [rendered]

ERROR in node_modules/@ngxs/store/internals/ngxs-bootstrapper.d.ts(7,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/store/src/symbols.d.ts(9,51): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/store/src/plugin-manager.d.ts(7,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/store/src/internal/config-validator.d.ts(7,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/store/src/internal/config-validator.d.ts(8,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/store/src/internal/state-factory.d.ts(23,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/store/src/internal/state-factory.d.ts(25,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/store/src/internal/state-factory.d.ts(27,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/store/src/internal/state-factory.d.ts(46,71): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/store/src/actions/actions.d.ts(6,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/store/src/actions/actions.d.ts(13,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(6,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(18,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(35,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(51,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(59,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(64,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(74,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(84,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(89,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/actions.d.ts(97,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/form-plugin/src/directive.d.ts(19,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/devtools-plugin/src/symbols.d.ts(40,60): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/devtools-plugin/src/devtools.module.d.ts(10,51): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/devtools-plugin/src/devtools.plugin.d.ts(17,17): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/logger-plugin/src/symbols.d.ts(12,65): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/logger-plugin/src/logger.module.d.ts(3,51): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/storage-plugin/src/symbols.d.ts(56,66): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/storage-plugin/src/symbols.d.ts(57,53): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/storage-plugin/src/storage.module.d.ts(3,51): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/websocket-plugin/src/symbols.d.ts(2,61): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/websocket-plugin/src/symbols.d.ts(51,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/websocket-plugin/src/symbols.d.ts(59,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/websocket-plugin/src/symbols.d.ts(66,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/websocket-plugin/src/symbols.d.ts(72,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/websocket-plugin/src/symbols.d.ts(78,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/websocket-plugin/src/symbols.d.ts(85,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/websocket-plugin/src/symbols.d.ts(92,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/websocket-plugin/src/websocket.module.d.ts(13,51): error TS2304: Cannot find name 'unknown'.
node_modules/@ngxs/router-plugin/src/router.actions.d.ts(10,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/router-plugin/src/router.actions.d.ts(25,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/router-plugin/src/router.actions.d.ts(36,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/router-plugin/src/router.actions.d.ts(47,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/router-plugin/src/router.actions.d.ts(57,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/hmr-plugin/src/actions/hmr-init.action.d.ts(4,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngxs/hmr-plugin/src/actions/hmr-before-destroy.action.d.ts(4,16): error TS1086: An accessor cannot be declared in an ambient context.
```

**Comment by JoostK** [comment]
These messages occur because you're using an incompatible version of TypeScript, which is unable to parse these declaration files simply because it's too old. I'm sorry but that is not something we can assist with.
