### ISSUE TITLE
"window is not defined" when run app-shell on ver 9.1 or above

### ISSUE THREAD

**Issue by anndyd** [angular/angular#38309]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/platform-server

### Is this a regression?
Yes, the previous version in which this bug was not present was: 9.0.0
I tested on 3 versions: The error occurs on 9.1.4, 10.0.3 

### Description
use window.sessionStorage to save some values in the Angular project and add app-shell,
the error occurs when run command: ng run <project name>:app-shell.

## 🔬 Minimal Reproduction
1. stackblitz.com
I added code in
https://stackblitz.com/edit/angular-app-shell-error?file=src%2Fapp%2Fapp.component.ts
But, I don't know how to run command on stackblitz.com, so, with this code and add app-shell, then run project with app-shell can reproduce this error.

2. github.com
Download the code from https://github.com/anndyd/app-shell-try, then run the following command can reproduce
_ng run app-shell-try:app-shell_

## 🔥 Exception or Error
<pre><code>
ERROR ReferenceError: window is not defined
    at new AppComponent (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:121327:9)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:121330:63)
    at getNodeInjectable (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:47162:44)
    at instantiateRootComponent (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:51087:23)
    at createRootComponent (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:61606:23)
    at ComponentFactory$1.create (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:65422:25)
    at ApplicationRef.bootstrap (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:71163:42)
    at /Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70874:64
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70874:44)
    at /Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70844:26
    at ZoneDelegate.invoke (/Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:386:30)
    at Object.onInvoke (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70281:33)
    at ZoneDelegate.invoke (/Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:385:36)
    at Zone.run (/Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:143:47)
    at /Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:891:38
Unhandled Promise rejection: window is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: window is not defined
    at new AppComponent (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:121327:9)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:121330:63)
    at getNodeInjectable (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:47162:44)
    at instantiateRootComponent (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:51087:23)
    at createRootComponent (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:61606:23)
    at ComponentFactory$1.create (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:65422:25)
    at ApplicationRef.bootstrap (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:71163:42)
    at /Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70874:64
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70874:44)
    at /Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70844:26
    at ZoneDelegate.invoke (/Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:386:30)
    at Object.onInvoke (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70281:33)
    at ZoneDelegate.invoke (/Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:385:36)
    at Zone.run (/Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:143:47)
    at /Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:891:38 ReferenceError: window is not defined
    at new AppComponent (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:121327:9)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:121330:63)
    at getNodeInjectable (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:47162:44)
    at instantiateRootComponent (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:51087:23)
    at createRootComponent (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:61606:23)
    at ComponentFactory$1.create (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:65422:25)
    at ApplicationRef.bootstrap (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:71163:42)
    at /Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70874:64
    at Array.forEach (<anonymous>)
    at PlatformRef._moduleDoBootstrap (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70874:44)
    at /Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70844:26
    at ZoneDelegate.invoke (/Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:386:30)
    at Object.onInvoke (/Users/dcl/work/learn/app-shell-try/dist/app-shell-try/server/main.js:70281:33)
    at ZoneDelegate.invoke (/Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:385:36)
    at Zone.run (/Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:143:47)
    at /Users/dcl/work/learn/app-shell-try/node_modules/zone.js/dist/zone-node.js:891:38
window is not defined
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.0.4
Node: 12.14.1
OS: darwin x64

Angular: 10.0.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.1000.4
@angular-devkit/build-webpack     0.1000.4
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.4
@angular/cli                      10.0.4
@ngtools/webpack                  10.0.4
@schematics/angular               10.0.4
@schematics/update                0.1000.4
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
NA

**Comment by anndyd** [comment]
I found it caused by app-shell code used window.sessionStorage.
The app-shell component will be rendered with on server mode when calling ng run command.
There is no window object.
Close this issue.
