### ISSUE TITLE
Dynamic routing and cached routes don't work together

### ISSUE THREAD

**Issue by TheZwieback** [angular/angular#38326]
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
Not that I'm aware of

### Description

There is an issue with dynamic routes and keeping snapshots of components already attached to existing routes. My use case involves adding dynamic routes by calling router resetConfig(routes). Previous untouched routes have snapshots which should be retrievable after reset but give an error after reset.

## 🔬 Minimal Reproduction
I added a Stackblitz for the example code here:
https://stackblitz.com/edit/router-reset-config?file=src/index.html
To reproduce my case:
click Route A
click Route B
click Route A again (same random number should be displayed)
click reset router
click Route B -> error message in console:

## 🔥 Exception or Error
<pre><code>
ERROR
Error: Uncaught (in promise): Error: Cannot reattach ActivatedRouteSnapshot created from a different route
Error: Cannot reattach ActivatedRouteSnapshot created from a different route
at setFutureSnapshotsOfActivatedRoutes (https://router-reset-config.stackblitz.io/turbo_modules/@angular/router@10.0.1/__ivy_ngcc__/bundles/router.umd.js:2150:19)
at createNode (https://router-reset-config.stackblitz.io/turbo_modules/@angular/router@10.0.1/__ivy_ngcc__/bundles/router.umd.js:2138:17)
at eval (https://router-reset-config.stackblitz.io/turbo_modules/@angular/router@10.0.1/__ivy_ngcc__/bundles/router.umd.js:2178:20)
at Array.map (<anonymous>)
at createOrReuseChildren (https://router-reset-config.stackblitz.io/turbo_modules/@angular/router@10.0.1/__ivy_ngcc__/bundles/router.umd.js:2161:30)
at createNode (https://router-reset-config.stackblitz.io/turbo_modules/@angular/router@10.0.1/__ivy_ngcc__/bundles/router.umd.js:2130:28)
at createRouterState (https://router-reset-config.stackblitz.io/turbo_modules/@angular/router@10.0.1/__ivy_ngcc__/bundles/router.umd.js:2122:20)
at MapSubscriber.eval [as project] (https://router-reset-config.stackblitz.io/turbo_modules/@angular/router@10.0.1/__ivy_ngcc__/bundles/router.umd.js:4366:45)
at MapSubscriber._next (https://router-reset-config.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/operators/map.js:49:35)
at MapSubscriber.Subscriber.next (https://router-reset-config.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Subscriber.js:66:18)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 9.1.10
Node: 12.13.0
OS: win32 x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.10
@angular-devkit/build-angular     0.901.10
@angular-devkit/build-optimizer   0.901.10
@angular-devkit/build-webpack     0.901.10
@angular-devkit/core              9.1.10
@angular-devkit/schematics        9.1.10
@angular/cli                      9.1.10
@ngtools/webpack                  9.1.10
@schematics/angular               9.1.10
@schematics/update                0.901.10
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
Maybe there is way to manually attach a snapshot? That would also work for me.

**Comment by atscott** [comment]
Right, this wouldn't work because the `standardizeConfig` makes a copy of the config so no stored configs will ever pass the object equality check of `setFutureSnapshotsOfActivatedRoutes`. I don't think there's a workaround for this right now -- route reuse wasn't designed to work for this use-case.

**Comment by atscott** [comment]
Closing as a "won't fix". `resetConfig` is a config reset and should be assumed to be treated as a completely new config. As such, the previously stored routes cannot be re-used. That said, you can directly access and modify the `router.config` so that the object equality still works. https://angular.io/api/router/Router#config
