### ISSUE TITLE
Error: [jqLite:onargs] jqLite#on() does not support the `selector` or `eventData` parameters 

### ISSUE THREAD

**Issue by nicolabortignon** [angular/angular#3844]
Hi, I'm using Angular 1.3.18.

I haven't build my project in a while. Today when i started the production pipeline, I saw that there is an error after i concatenate angular with all the other js file. When the files are not concatenated but just used like in developing stage it does work.

It's a long shot, but let see if you have any suggestions here:

It is basically a 

Error: [jqLite:onargs] jqLite#on() does not support the `selector` or `eventData` parameters
http://errors.angularjs.org/1.3.18/jqLite/onargs

With a stack trace of:
```
    at REGEX_STRING_REGEXP (http://localhost:9000/js/app.min.js:63:12)
    at jqLiteOn (http://localhost:9000/js/app.min.js:3067:39)
    at Object.JQLite.(anonymous function) (http://localhost:9000/js/app.min.js:3285:17)
    at link (http://localhost:9000/js/app.min.js:49514:12)
    at invokeLinkFn (http://localhost:9000/js/app.min.js:8290:9)
    at nodeLinkFn (http://localhost:9000/js/app.min.js:7800:11)
    at compositeLinkFn (http://localhost:9000/js/app.min.js:7149:13)
    at compositeLinkFn (http://localhost:9000/js/app.min.js:7152:13)
    at compositeLinkFn (http://localhost:9000/js/app.min.js:7152:13)
    at publicLinkFn (http://localhost:9000/js/app.min.js:7028:30) <nav ui-nav="" class="navi clearfix">
```

The starting error, the tag mentioned at the bottom of the stack, is this tag: 

    
    <nav ui-nav class="navi clearfix" ng-include="'tpl/blocks/nav.html'"></nav>
    

That is some UI code for the navigation menu of my site.

**Comment by nicolabortignon** [comment]
Issues closed and move to angular 1.x repo
