### ISSUE TITLE
Compiler Failing in Linux but not Windows

### ISSUE THREAD

**Issue by phantomcosmonaut** [angular/angular#38475]
# Affected Package
angular-devkit

### Is this a regression?
Idk

### Description
Compiler fails on build in Linux. The project was created on Windows where the build does work.

## 🔬 Minimal Reproduction
Here is the repository: https://github.com/phantomcosmonaut/angular-gitapi
I run an Ubuntu container in Docker with the latest version of npm, clone the repo, do an npm install for all the dependencies and then run `ng build` or `npm run build`. I've also tried verbose logging but it didn't help.
Other than that I don't know how to reproduce this build issue

## 🔥 Exception or Error
<pre><code>
[error] Error: NGCC failed.
at NgccProcessor.process (/home/angular-gitapi/node_modules/@ngtools/webpack/src/ngcc_processor.js:69:19)
at compiler.hooks.environment.tap (/home/angular-gitapi/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:576:31)
at SyncHook.eval [as call] (eval at create (/home/angular-gitapi/node_modules/tapable/lib/HookCodeFactory.js:19:10), :9:1 )
at SyncHook.lazyCompileHook (/home/angular-gitapi/node_modules/tapable/lib/Hook.js:154:20)
at Object.webpack [as webpackFactory] (/home/angular-gitapi/node_modules/webpack/lib/webpack.js:55:30)
at createWebpack (/home/angular-gitapi/node_modules/@angular-devkit/build-webpack/src/webpack/index.js:20:36)
at Object.runWebpack (/home/angular-gitapi/node_modules/@angular-devkit/build-webpack/src/webpack/index.js:34:12)
at SwitchMapSubscriber.rxjs_1.from.pipe.operators_1.switchMap [as project] (/home/angular-gitapi/node_modules/@angular-devkit/build- angular/src/browser/index.js:142:32)
at SwitchMapSubscriber._next (/home/angular-gitapi/node_modules/rxjs/internal/operators/switchMap.js:49:27)
at SwitchMapSubscriber.Subscriber.next (/home/angular-gitapi/node_modules/rxjs/internal/Subscriber.js:66:18)
at /home/angular-gitapi/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24 at process._tickCallback (internal/process/next_tick.js:68:7)
at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.6
Node: 10.19.0
OS: linux x64

Angular: 10.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.6
@angular-devkit/build-angular     0.1000.6
@angular-devkit/build-optimizer   0.1000.6
@angular-devkit/build-webpack     0.1000.6
@angular-devkit/core              10.0.6
@angular-devkit/schematics        10.0.6
@angular/cli                      10.0.6
@ngtools/webpack                  10.0.6
@schematics/angular               10.0.6
@schematics/update                0.1000.6
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
No

**Comment by petebacondarwin** [comment]
I feel like there might be some authorisation issues with your Docker setup that is preventing ngcc from writing to the disk perhaps? There is nothing particularly unusual about the repository that you linked above.

**Comment by petebacondarwin** [comment]
Could you provide your Docker setup that is failing?

**Comment by phantomcosmonaut** [comment]
I ran some tests and it turns out the build stage consumes an enormous amount of memory which was causing my ec2 instance to crash.

**Comment by petebacondarwin** [comment]
OK, I think we can close this then?

**Comment by Splaktar** [comment]
In some CI environments, we've had to disable the `--async` option and run `ngcc` in the `postinstall` script on lower memory VMs. Here's an example:
```sh
ngcc --async false --properties es2015 browser module main --first-only --create-ivy-entry-points
```
