### ISSUE TITLE
The_global_type_JSX_0_may_not_have_more_than_one_property: diag(2608, ts.DiagnosticCategory.Error, "The_global_type_JSX_

### ISSUE THREAD

**Issue by Javaman2** [angular/angular#38489]
# 🐞 bug report

### Affected Package

Not sure what package is the issue other than after upgrade to version 10 running ng build will not compile. 

### Is this a regression?

Don't know. 

### Description

When using ng build after upgrade to version 10 this error is shown.

```

[error] C:\Users\John\source\cc\node_modules\typescript\lib\typescript.js:7403
        The_global_type_JSX_0_may_not_have_more_than_one_property: diag(2608, ts.DiagnosticCategory.Error, "The_global_type_JSX_
                                                                                                           ^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at C:\Users\John\source\cc\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\compiler_host.js:22:14
    at C:\Users\John\source\cc\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\compiler_host.js:10:17
    at Object.<anonymous> (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\src\ngtsc\file_system\src\compiler_host.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)

```

## 🔬 Minimal Reproduction

https://github.com/Javaman2/cc/tree/UpgradeTo10

## 🔥 Exception or Error
<pre><code>
 
[error] C:\Users\John\source\cc\node_modules\typescript\lib\typescript.js:7403
        The_global_type_JSX_0_may_not_have_more_than_one_property: diag(2608, ts.DiagnosticCategory.Error, "The_global_type_JSX_
                                                                                                           ^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.6
Node: 12.14.1
OS: win32 x64

Angular: 10.0.9
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.6
@angular-devkit/build-angular      0.1000.6
@angular-devkit/build-ng-packagr   0.1000.6
@angular-devkit/build-optimizer    0.1000.6
@angular-devkit/build-webpack      0.1000.6
@angular-devkit/core               10.0.6
@angular-devkit/schematics         10.0.6
@angular/cdk                       10.1.3
@angular/cli                       10.0.6
@angular/material                  10.1.3
@ngtools/webpack                   10.0.6
@schematics/angular                10.0.6
@schematics/update                 0.1000.6
ng-packagr                         10.0.4
rxjs                               6.6.2
typescript                         3.9.7
webpack                            4.43.0

</code></pre>

**Anything else relevant?**

**Comment by Javaman2** [comment]
When down-leveling Typescript to 3.9.4 the error message changes to this:

```
[error] Error: The given rootPath undefined is not a file of the program.
    at getRootFileOrFail (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\ngcc\src\host\esm2015_host.js:2330:19)
    at Esm2015ReflectionHost.computePublicDtsDeclarationMap (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\ngcc\src\host\esm2015_host.js:1654:27)
    at Esm2015ReflectionHost.getDtsDeclaration (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\ngcc\src\host\esm2015_host.js:458:53)
    at DelegatingReflectionHost.getDtsDeclaration (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\ngcc\src\host\delegating_host.js:62:34)
    at Object.wrapTypeReference (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\util.js:514:34)
    at extractInjectableMetadata (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:125:27)
    at InjectableDecoratorHandler.analyze (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:67:24)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:346:40)
    at analyze (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:298:58)
    at _loop_1 (C:\Users\John\source\cc\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:320:21)


```

**Comment by Javaman2** [comment]
Changing root path to bundle.path as shown here. 

```typescript
 function getRootFileOrFail(bundle) {
        var rootFile = bundle.program.getSourceFile(bundle.path);
        if (rootFile === undefined) {
            throw new Error("The given rootPath " + bundle.path + " is not a file of the program.");
        }
        return rootFile;
    }
```

The error says: node_modules/@angular/core/core.d.ts is not a file of the program.
core.d.ts is not a file of the program?

**Comment by Javaman2** [comment]
npm install @angular/core seemed to help however, @angular/material had to be down-leveled.

Final working versions were:
```
Angular CLI: 10.0.6
Node: 12.14.1
OS: win32 x64

Angular: 10.0.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.6
@angular-devkit/build-angular      0.1000.6
@angular-devkit/build-ng-packagr   0.1000.6
@angular-devkit/build-optimizer    0.1000.6
@angular-devkit/build-webpack      0.1000.6
@angular-devkit/core               10.0.6
@angular-devkit/schematics         10.0.6
@angular/cdk                       10.0.0
@angular/cli                       10.0.6
@angular/material                  10.0.0
@ngtools/webpack                   10.0.6
@schematics/angular                10.0.6
@schematics/update                 0.1000.6
ng-packagr                         10.0.4
rxjs                               6.6.2
typescript                         3.9.4
webpack                            4.43.0
```

**Comment by Javaman2** [comment]
I still think Angular Compiler Error messaging is bad.
