### ISSUE TITLE
Cannot read property 'hasInlines' of undefined

### ISSUE THREAD

**Issue by shyamal890** [angular/angular#38582]
🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.2.2

### Description
`ng build --prod` is giving the following error after upgrade to 10.0.12. While `ng serve` is working perfectly

## 🔥 Exception or Error
```
ERROR in TypeError: Cannot read property 'hasInlines' of undefined
    at TemplateTypeCheckerImpl.getDiagnosticsForFile (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\checker.js:123:28)
    at NgCompiler.getTemplateDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:487:106)
    at NgCompiler.getDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:141:97)
    at NgtscProgram.getNgSemanticDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@angular\compiler-cli\src\ngtsc\program.js:152:45)
    at checkDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@ngtools\webpack\src\diagnostics.js:47:27)
    at Object.gatherDiagnostics (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@ngtools\webpack\src\diagnostics.js:86:13)
    at AngularCompilerPlugin._emit (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:1081:54)
    at AngularCompilerPlugin._update (E:\Dropbox\SmartTask\SmartTask.App\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:872:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## 🌍 Your Environment
```
Angular CLI: 10.0.7
Node: 10.16.1
OS: win32 x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cdk                      10.1.3
@angular/cli                      10.0.7
@angular/http                     7.2.16
@angular/material                 10.1.3
@ngtools/webpack                  10.0.7
@nguniversal/common               10.0.2
@nguniversal/express-engine       10.0.2
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0
```

**Comment by JoostK** [comment]
What @alan-agius4 said! :D

**Comment by shyamal890** [comment]
@JoostK can you atleast tell me why this error may occur? As its a large repo and its really difficult reproduce this. Having some idea on the reasons behind this error may help.

**Comment by JoostK** [comment]
@shyamal890 the error is related to how the template type checker expects type-check information to be available for all regular TS files in the program. In this case, is appears as if some files don't have type-check information available, but are still type-checked. I don't really know how they get misaligned in this case; I notice you're using Windows, that might contribute to the issue.

What might help diagnose the cause is to insert some console.logs before `node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\checker.js:123` to log `sfPath`. Additionally, you may want to log the `sfPath` for each iteration of the loop in `ensureAllShimsForAllFiles` in the same file.

**Comment by shyamal890** [comment]
There is a very weird issue. 

I was able to identify a file. In it if I change an import's filename Capital letter to Lowercase it works! although the imported file does start with Capital letter. 

How to solve this?

**Comment by liquidsnk** [comment]
I think this should be reopened, it's either a bug or an opportunity to provide clearer information about the problem.
I don't think I would've ever figured out what the issue was without this ticket.

**Comment by hoefken** [comment]
Opened a new Issue https://github.com/angular/angular/issues/39040
