### ISSUE TITLE
Angular 10.1.0-rc.0 - I18n build failed

### ISSUE THREAD

**Issue by muehle28** [angular/angular#38627]
The build process of a multilingual app (ivy=true activated in @angular-devkit/build-angular:extract-i18n) failed with the error
`Localized bundle generation failed: Cannot read property 'value' of undefined`

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/m/.nvm/versions/node/v12.16.1/bin/node',
1 verbose cli   '/home/m/.nvm/versions/node/v12.16.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle mm-app@0.0.1~prebuild: mm-app@0.0.1
6 info lifecycle mm-app@0.0.1~build: mm-app@0.0.1
7 verbose lifecycle mm-app@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle mm-app@0.0.1~build: PATH: /home/m/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/m/development/projects/mm-app/node_modules/.bin:/home/m/.nvm/versions/node/v12.16.1/bin:/home/m/.local/bin:/home/m/bin:/usr/bin:/home/m/.nvm/versions/node/v12.16.1/bin:/home/m/.local/bin:/home/m/bin:/usr/share/Modules/bin:/usr/condabin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
9 verbose lifecycle mm-app@0.0.1~build: CWD: /home/m/development/projects/mm-app
10 silly lifecycle mm-app@0.0.1~build: Args: [ '-c', 'ng build' ]
11 silly lifecycle mm-app@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle mm-app@0.0.1~build: Failed to exec build script
13 verbose stack Error: mm-app@0.0.1 build: `ng build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/m/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/m/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid mm-app@0.0.1
15 verbose cwd /home/m/development/projects/mm-app
16 verbose Linux 5.7.16-200.fc32.x86_64
17 verbose argv "/home/m/.nvm/versions/node/v12.16.1/bin/node" "/home/m/.nvm/versions/node/v12.16.1/bin/npm" "run" "build"
18 verbose node v12.16.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error mm-app@0.0.1 build: `ng build`
22 error Exit status 1
23 error Failed at the mm-app@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

With the Angular version 10.0.14 the build worked.

**Comment by muehle28** [comment]
There was a library mismatch. Deleting node_modules and reinstalling them solved the problem.

**Comment by petebacondarwin** [comment]
Oh great! I was just trying to work out how to help you. Phew!
