### ISSUE TITLE
Compiler.compileModuleAndAllComponentsSync “Runtime compiler is not loaded” in Angular 10

### ISSUE THREAD

**Issue by namikarif** [angular/angular#39159]
I designed a dynamic form. It works well in Angular 5 version. However, after upgrading the Angular version to 10, it started malfunctioning.

Error message returned from **compiler.compileModuleAndAllComponentsSync** line:
```
Error: Runtime compiler is not loaded
    at Compiler._throwError (http://localhost:8001/vendor.js:39209:11)
    at SectorFormComponent.createComponent (http://localhost:8001/main.js:122993:33)
    at SectorFormComponent.compileTemplate (http://localhost:8001/main.js:122845:30)
    at SectorFormComponent.ngOnInit (http://localhost:8001/main.js:122838:14)
    at checkAndUpdateDirectiveInline (http://localhost:8001/vendor.js:33918:19)
    at checkAndUpdateNodeInline (http://localhost:8001/vendor.js:42831:20)
    at checkAndUpdateNode (http://localhost:8001/vendor.js:42793:16)
    at debugCheckAndUpdateNode (http://localhost:8001/vendor.js:43420:21)
    at debugCheckDirectivesFn (http://localhost:8001/vendor.js:43384:13)
    at Object.updateDirectives (http://localhost:8001/main.js:152469:420)
```

It doesn't give this error when I close AOT. This time, ngModel is not working. How can I solve this problem without closing AOT?

```ts
import {Compiler, Component, ComponentFactory, ComponentRef, Input, NgModule, OnInit, ViewChild, ViewContainerRef} from '@angular/core';
import {SharedModule} from '@app/modules/shared/shared.module';
import {CommonModule} from '@angular/common';
import {UtilService} from '@app/modules/shared/services/util.service';
import {FormBuilder, FormControl, FormGroup, FormsModule, ReactiveFormsModule} from '@angular/forms';

@Component({
  selector: 'kl-sector-form',
  templateUrl: './sector-form.component.html'
})
export class SectorFormComponent implements OnInit {
  @ViewChild('container', {read: ViewContainerRef, static: true}) private container: ViewContainerRef;
  private componentRef: ComponentRef<{}>;

  constructor(private compiler: Compiler) {
  }

  ngOnInit() {
    this.compileTemplate();
  }

  compileTemplate() {
    const metadata = {
      selector: 'dynamic-form',
      template: this.template
    };
    const factory = this.createComponent(this.compiler, metadata);
    if (this.componentRef) {
      this.componentRef.destroy();
      this.componentRef = null;
    }
    this.componentRef = this.container.createComponent(factory);
    const instance: any = this.componentRef.instance;
  }

  private createComponent(compiler: Compiler, metadata: Component): ComponentFactory<any> {
    const component = class DynamicComponent implements OnInit {

      ngOnInit() {
      }
    };
    const dynamicComponent = Component(metadata)(component);

    @NgModule({
      imports: [
        CommonModule,
        SharedModule.forRoot(),
        FormsModule,
        ReactiveFormsModule,
      ],
      declarations: [dynamicComponent],
      providers: [FormBuilder]
    })
    class DynamicFormModule {
    }

    const module = compiler.compileModuleAndAllComponentsSync(DynamicFormModule);
    return module.componentFactories.find(f => f.componentType === dynamicComponent);
  }
}
```

```
Angular CLI: 10.1.1
Node: 10.16.0
OS: darwin x64

Angular: 10.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1001.1
@angular-devkit/build-angular              0.1001.1
@angular-devkit/build-optimizer            0.1001.1
@angular-devkit/build-webpack              0.1001.1
@angular-devkit/core                       10.1.1
@angular-devkit/schematics                 10.1.1
@angular/cdk                               10.2.1
@angular/http                              5.2.11
@angular/material                          10.2.1
@ngtools/webpack                           10.1.1
@nguniversal/common                        10.1.0
@nguniversal/express-engine                10.1.0
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        10.1.1
@schematics/update                         0.1001.1
rxjs                                       6.6.3
typescript                                 4.0.2
webpack                                    4.44.1
```

**Comment by petebacondarwin** [comment]
By "closing AOT" do you mean "disabling AOT?
What you are trying to do requires that the Angular Compiler is deployed at runtime in the browser. A simple way to do this is to import it in your `main.ts` file, I believe.

**Comment by JoostK** [comment]
There's something funny going on as well, as `checkAndUpdateNode` in the stack trace indicates the usage of ViewEngine renderer and not the Ivy renderer, unlike the `Ivy Workspace: Yes` note in the CLI's version output.

**Comment by petebacondarwin** [comment]
Oh it seems that AOT + JIT in the same program is not really supported at the moment. See https://github.com/angular/angular-cli/issues/17663

**Comment by petebacondarwin** [comment]
Closing as this is not a supported scenario - see https://github.com/angular/angular-cli/issues/17663#issuecomment-705737272

**Comment by namikarif** [comment]
Dear Friends,

This problem happened after pass to Anglar 10 from V5. The sample codes above were working without any problem in Angual 5. What is the reason that it is not working in Angular 10. As I said I have used it the same codes for Angular 5, it is working without problem. I am waiting for your valuable ideas.
