### ISSUE TITLE
Building the `language-service` package fails on  Windows

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#39363]
Since recently-ish, building the Angular packages (for example, via `node scripts/build/build-packages-dist`) on Windows fails with the error below. The error is related to building the `language-service` package and in particular to running command `yarn --silent bazel build --config=release --config=view-engine //packages/language-service:npm_package`.

<details>
<summary><b>ERROR</b> <i>(click to expand)</i></summary>

```
##################################
scripts\build\build-packages-dist.js:
  Building @angular/* npm packages
  Mode: Production
##################################
Loading: 265 packages loaded
//packages/upgrade:npm_package       
//packages/service-worker:npm_package
//packages/router:npm_package
//packages/platform-server:npm_package
//packages/platform-browser-dynamic:npm_package
//packages/platform-browser:npm_package
//packages/localize:npm_package
//packages/language-service:npm_package
//packages/forms:npm_package
//packages/elements:npm_package
//packages/core:npm_package
//packages/compiler-cli:npm_package
//packages/compiler:npm_package
//packages/common:npm_package
//packages/bazel:npm_package
//packages/animations:npm_package
INFO: Analyzed 16 targets (243 packages loaded, 20133 targets configured).
INFO: Found 16 targets...
ERROR: C:/<...>/angular/packages/language-service/bundles/BUILD.bazel:23:17: Bundling JavaScript packages/language-service/bundles/ivy.js [rollup] failed (Exit 1)
(!) Missing exports
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
bazel-out\x64_windows-fastbuild\bin\packages\language-service\ivy\utils.mjs
PropertyWrite is not exported by node_modules\@angular\compiler\src\expression_parser\ast.js
16:         return toTextSpan(node.keySpan);
17:     }
18:     else if (node instanceof e.PropertyWrite || node instanceof e.MethodCall ||
                                   ^
19:         node instanceof e.BindingPipe || node instanceof e.PropertyRead) {
20:         // The `name` part of a `PropertyWrite`, `MethodCall`, and `BindingPipe` does not
bazel-out\x64_windows-fastbuild\bin\packages\language-service\ivy\utils.mjs
MethodCall is not exported by node_modules\@angular\compiler\src\expression_parser\ast.js
16:         return toTextSpan(node.keySpan);
17:     }
18:     else if (node instanceof e.PropertyWrite || node instanceof e.MethodCall ||
                                                                      ^
19:         node instanceof e.BindingPipe || node instanceof e.PropertyRead) {
20:         // The `name` part of a `PropertyWrite`, `MethodCall`, and `BindingPipe` does not
bazel-out\x64_windows-fastbuild\bin\packages\language-service\ivy\utils.mjs
BindingPipe is not exported by node_modules\@angular\compiler\src\expression_parser\ast.js
17:     }
18:     else if (node instanceof e.PropertyWrite || node instanceof e.MethodCall ||
19:         node instanceof e.BindingPipe || node instanceof e.PropertyRead) {
                              ^
20:         // The `name` part of a `PropertyWrite`, `MethodCall`, and `BindingPipe` does not
21:         // have its own AST so there is no way to retrieve a `Symbol` for just the `name` via a specific
bazel-out\x64_windows-fastbuild\bin\packages\language-service\ivy\utils.mjs
PropertyRead is not exported by node_modules\@angular\compiler\src\expression_parser\ast.js
17:     }
18:     else if (node instanceof e.PropertyWrite || node instanceof e.MethodCall ||
19:         node instanceof e.BindingPipe || node instanceof e.PropertyRead) {
                                                               ^
20:         // The `name` part of a `PropertyWrite`, `MethodCall`, and `BindingPipe` does not
21:         // have its own AST so there is no way to retrieve a `Symbol` for just the `name` via a specific
[!] Error: 'AbsoluteSourceSpan' is not exported by node_modules\@angular\compiler\index.js, imported by bazel-out\x64_windows-fastbuild\bin\packages\language-service\ivy\utils.mjs
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
bazel-out\x64_windows-fastbuild\bin\packages\language-service\ivy\utils.mjs (8:9)
 6:  * found in the LICENSE file at https://angular.io/license
 7:  */
 8: import { AbsoluteSourceSpan, CssSelector, ParseSourceSpan, SelectorMatcher } from '@angular/compiler';
             ^
 9: import * as e from '@angular/compiler/src/expression_parser/ast'; // e for expression AST
10: import * as t from '@angular/compiler/src/render3/r3_ast'; // t for template AST
Error: 'AbsoluteSourceSpan' is not exported by node_modules\@angular\compiler\index.js, imported by bazel-out\x64_windows-fastbuild\bin\packages\language-service\ivy\utils.mjs
    at error (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:213:30)
    at Module.error (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:15199:16)
    at handleMissingExport (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:15094:28)     
    at Module.traceVariable (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:15574:24)    
    at ModuleScope.findVariable (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:14227:39)    at FunctionScope.findVariable (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:9697:38)
    at ChildScope.findVariable (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:9697:38)  
    at Identifier$1.bind (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:10115:40)       
    at BinaryExpression.bind (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:9741:23)    
    at IfStatement.bind (<output_base>\execroot\angular\node_modules\rollup\dist\shared\rollup.js:9741:23)

INFO: Elapsed time: 135.411s, Critical Path: 112.33s
INFO: 20 processes: 9 local, 11 worker.
FAILED: Build did NOT complete successfully
child_process.js:674
    throw err;      
    ^

Error: Command failed: yarn --cwd "C:\<...>\angular" --silent bazel build --config=release --config=view-engine //packages/upgrade:npm_package //packages/service-worker:npm_package //packages/router:npm_package //packages/platform-server:npm_package //packages/platform-browser-dynamic:npm_package //packages/platform-browser:npm_package //packages/localize:npm_package //packages/language-service:npm_package //packages/forms:npm_package //packages/elements:npm_package //packages/core:npm_package //packages/compiler-cli:npm_package //packages/compiler:npm_package //packages/common:npm_package //packages/bazel:npm_package //packages/animations:npm_package
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at exec (C:\<...>\angular\scripts\build\package-builder.js:122:18)
    at buildTargetPackages (C:\<...>\angular\scripts\build\package-builder.js:81:3)
    at Object.<anonymous> (C:\<...>\angular\scripts\build\build-packages-dist.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10864,
  stdout: null,
  stderr: null
}
```

</details>

##
One difference I have found between Windows and Linux is that on Windows Rollup is looking for the exports in `node_modules/@angular/compiler/index.js`, while on Linux it is looking in `node_modules/@angular/compiler/index.mjs` (notice the `.js` vs `.mjs` extension).

The reason is that on Windows `bazel` does not generate any `.mjs` files (e.g. `compiler/index.mjs`) as happens on Linux and Rollup falls back to `.js` files (which are in AMD format, where Rollup cannot read exports from).

##
**NOTE:** This might (or might not) be related to bazelbuild/rules_nodejs#1689.

**Comment by AndrewKushnir** [comment]
@gkalpak, I've set the priority as `P3` for now, please change it if needed. Thank you.

**Comment by gkalpak** [comment]
Some more info (in case it helps someone diagnose the issue):

On Windows, the importing file (for example, `packages/language-service/ivy/utils.mjs`) is inside a `C:/users/gkalpak/_bazel_gkalpak/wokxvvpa/execroot/angular/bazel-out/x64_windows-fastbuild/bin/packages/language-service/ivy/` directory, while the file it tries (and fails) to import from is inside the `C:/users/gkalpak/_bazel_gkalpak/wokxvvpa/execroot/angular/node_modules/@angular/compiler/` directory.

Also, `C:/users/gkalpak/_bazel_gkalpak/wokxvvpa/execroot/angular/node_modules/@angular/compiler/` (as well as `<WORKING_DIR>/node_modules/@angular/compiler/`) are symlinks to `/.../bazel-out/host/bin/packages/compiler/` (instead of to `/.../bazel-out/x64_windows-fastbuild/bin/packages/compiler/`, where the importing `language-service` files are located).

**Comment by gkalpak** [comment]
(Not sure how, but) this seems to have sorted itself out :tada:
Closing.
