### ISSUE TITLE
TypeError: Cannot read property 'ngModule' of undefined

### ISSUE THREAD

**Issue by damingerdai** [angular/angular#39573]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
i am not sure.

### Description

 A clear and concise description of the problem...
when i run `ng test`, the some unit case fail for this reason:
```
TypeError: Cannot read property 'ngModule' of undefined

TypeError: Cannot read property 'ngModule' of undefined
    at isModuleWithProviders (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26229:18)
    at map (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26223:9)
    at <Jasmine>
    at Function.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:25879:26)
    at getNgModuleDef (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:1853:29)
    at isNgModule (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26232:14)
    at forEach (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26174:14)
    at <Jasmine>
    at transitiveScopesFor (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26172:32)
    at forEach (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26179:31)
    at <Jasmine>
    at transitiveScopesFor (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26172:32)
    at forEach (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26179:31)
    at <Jasmine>
    at transitiveScopesFor (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26172:32)
```

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

this is the private code. so i can not show the all code. I can only share the simplest case.
ts code
```
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
	selector: 'slate-initials-user-icon',
	templateUrl: './initials-user-icon.component.html',
	styleUrls: ['./initials-user-icon.component.scss'],
	changeDetection: ChangeDetectionStrategy.OnPush
})
export class InitialsUserIconComponent {
	@Input()
	public initials;
}
```
html
```
<p>
  {{ initials }}
</p>

```
test code
```
import { waitForAsync, ComponentFixture, TestBed } from '@angular/core/testing';

import { InitialsUserIconComponent } from './initials-user-icon.component';

describe('InitialsUserIconComponent', () => {
	let component: InitialsUserIconComponent;
	let fixture: ComponentFixture<InitialsUserIconComponent>;

	beforeEach(
		waitForAsync(() => {
			TestBed.configureTestingModule({
				declarations: [InitialsUserIconComponent]
			}).compileComponents();
		})
	);

	beforeEach(() => {
		fixture = TestBed.createComponent(InitialsUserIconComponent);
		component = fixture.componentInstance;
		fixture.detectChanges();
	});

	it('should create', () => {
		expect(component).toBeTruthy();
	});
});

```

## 🔥 Exception or Error
<pre><code>

TypeError: Cannot read property 'ngModule' of undefined
    at isModuleWithProviders (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26229:18)
    at map (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26223:9)
    at <Jasmine>
    at Function.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:25879:26)
    at getNgModuleDef (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:1853:29)
    at isNgModule (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26232:14)
    at forEach (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26174:14)
    at <Jasmine>
    at transitiveScopesFor (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26172:32)
    at forEach (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26179:31)
    at <Jasmine>
    at transitiveScopesFor (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26172:32)
    at forEach (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26179:31)
    at <Jasmine>
    at transitiveScopesFor (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:26172:32)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.2.0
Node: 12.16.2
OS: darwin x64

Angular: 10.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1002.0
@angular-devkit/build-angular      0.1002.0
@angular-devkit/core               10.2.0
@angular-devkit/schematics         10.2.0
@angular/cdk                       10.2.7
@angular/cli                       10.2.0
@angular/fire                      6.0.4
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.2.7
@angular/material-moment-adapter   10.2.7
@schematics/angular                10.2.0
@schematics/update                 0.1002.0
rxjs                               6.6.3
typescript                         3.9.7
</code></pre>

**Anything else relevant?**

Chrome version: Version 86.0.4240.183 (Official Build) (x86_64)

**Comment by damingerdai** [comment]
i use [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack) to run unit test.
this is the test config in angular.json
```
	"test": {
					"builder": "@angular-builders/custom-webpack:karma",
					"options": {
						"customWebpackConfig": {
							"path": "./extra-webpack.config.js"
						},
						"main": "src/test.ts",
						"polyfills": "src/polyfills.ts",
						"tsConfig": "src/tsconfig.spec.json",
						"karmaConfig": "src/karma.conf.js",
						"styles": ["src/styles.scss", "src/icon.scss"],
						"scripts": [],
						"assets": ["src/favicon.ico", "src/assets"],
						"codeCoverage": false
					}
```

**Comment by petebacondarwin** [comment]
For us to debug this issue, can you extract out the snippet given above into a runnable project that demonstrates the error, please.

**Comment by damingerdai** [comment]
it looks like the circular dependency issue.
when i fixed the  circular dependency issue, this error has not exist.
so i have an another question: how to throw error instead of circular dependency warning when building?

**Comment by petebacondarwin** [comment]
We have discussed making circular dependencies an error in the past, and I believe it is on the road map to be implemented cc @alxhub. In fact I think that https://github.com/angular/angular/issues/38211 is exactly this, yes?

**Comment by JoostK** [comment]
In this case the circular dep must have occurred in user code, as the compiler refrains from introducing new cycles. So I don't think that #38211 is relevant here.

I believe it's not possible to error for circular deps; they aren't always a problem. It may be possible for the runtime JIT logic to detect an `undefined` NgModule import and produce a more helpful error.

**Comment by EvgeniyaTaran** [comment]
Fixing circular dependencies has helped me with "Cannot read property 'ngModule' of undefined error" in jest test.
Thanks a lot!

**Comment by pkozlowski-opensource** [comment]
This sounds like a support request that was since resolved. Closing.
