### ISSUE TITLE
Ivy (aot) Could not resolve [object Object] / undefined at Scope.resolve

### ISSUE THREAD

**Issue by jaffbeto** [angular/angular#39744]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli

### Description

 
this its only in Angular 11.0.0

enable ivy
`run ng build --aot `
or `"aot": true` in angular.json

this same bug [30677](https://github.com/angular/angular/issues/30677)

## 🔥 Exception or Error
<pre><code>

Error: Error: Could not resolve [object Object] / undefined
    at Scope.resolve (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1318:23)
    at TcbEventHandlerTranslator.TcbExpressionTranslator.resolveTarget (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1877:35)
    at TcbEventHandlerTranslator.TcbExpressionTranslator.resolve (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1786:29)
    at TcbEventHandlerTranslator.resolve (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:2034:45)
    at AstTranslator.maybeResolve (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1771:84)
    at AstTranslator.translate (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:74:33)
    at Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:204:68
    at Array.map (<anonymous>)
    at AstTranslator.visitMethodCall (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:204:33)
    at MethodCall.visit (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler\bundles\compiler.umd.js:8218:28)
    at AstTranslator.translate (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:78:24)
    at Object.astToTypescript (Z:\GIT_LOCAL\tools\CloudTool\CloudWebTool\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:55:27)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
@jaffbeto Heya, this looks like a bug but it's unclear what the cause is. Could you share a reproduction for us to investigate? Thanks!

**Comment by joebieb** [comment]
I was able to reproduce this error by accidently using a capital "F" in a form control...
`<Form class="login-form" #f="ngForm" (ngSubmit)="onSubmit(f)">`

once I changed it to...
`<form class="login-form" #f="ngForm" (ngSubmit)="onSubmit(f)">`
the error went away.

**Comment by AlonsoK28** [comment]
Same for me, after update from `ng 9` to `ng 11`

**error log**
```
Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.
✔ Browser application bundle generation complete.

Error: Error: Could not resolve [object Object] / undefined
    at Scope.resolve (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1318:23)
    at Scope.resolve (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1315:36)
    at TcbExpressionTranslator.resolveTarget (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1877:35)
    at TcbExpressionTranslator.resolve (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1786:29)
    at AstTranslator.maybeResolve (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1771:84)
    at AstTranslator.translate (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:74:33)
    at AstTranslator.visitPropertyRead (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:227:66)
    at PropertyRead.visit (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:8168:28)
    at AstTranslator.translate (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:78:24)
    at Object.astToTypescript (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/expression.js:55:27)
    at TcbExpressionTranslator.translate (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1771:33)
    at tcbExpression (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1759:27)
    at TcbUnclaimedInputsOp.execute (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:848:32)
    at Scope.executeOp (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1428:26)
    at Scope.render (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:1335:22)
    at TcbTemplateBodyOp.execute (/Users/vn09gav/Documents/dev/sif-frontend/node_modules/@angular/compiler-cli/src/ngtsc/typecheck/src/type_check_block.js:318:40)
```

**node** `v12.18.2`

**angular cli**
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.2
Node: 12.18.2
OS: darwin x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1100.2 (cli-only)
@angular-devkit/build-angular      0.1100.2
@angular-devkit/core               11.0.2 (cli-only)
@angular-devkit/schematics         11.0.2
@angular/cdk                       11.0.0
@angular/flex-layout               9.0.0-beta.29
@angular/material                  11.0.0
@angular/material-moment-adapter   9.0.0
@schematics/angular                11.0.2
@schematics/update                 0.1100.2
ng-packagr                         11.0.2
rxjs                               6.6.3
typescript                         4.0.5
```

I´ve tried to reinstall `npm` dependencies several times but still with this error

**Comment by georgemichalagas** [comment]
Same problem for me when i updated angular from 10 to 11.

Error:

PS C:\Dev\Repos\IPDB\leaf.client.v.4> ng build
√ Browser application bundle generation complete.

Error: Error: Could not resolve [object Object] / undefined
    at Scope.resolve (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1318:23)
    at TcbEventHandlerTranslator.TcbExpressionTranslator.resolveTarget (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1877:35)
    at TcbEventHandlerTranslator.TcbExpressionTranslator.resolve (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1786:29)
    at TcbEventHandlerTranslator.resolve (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:2034:45)
    at AstTranslator.translate (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:74:33)
    at AstTranslator.visitMethodCall (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:201:66)
    at MethodCall.visit (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler\bundles\compiler.umd.js:8389:28)
    at AstTranslator.translate (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:78:24)
    at Object.astToTypescript (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:55:27)
    at TcbEventHandlerTranslator.TcbExpressionTranslator.translate (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1771:33)
    at tcbEventHandlerExpression (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:2016:27)
    at tcbCreateEventHandler (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1974:23)
    at TcbUnclaimedOutputsOp.execute (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1050:39)
    at Scope.executeOp (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1428:26)
    at Scope.render (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1335:22)

Version
PS C:\Dev\Repos\IPDB\leaf.client.v.4> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.2
Node: 10.16.3
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.0
@angular/material               11.0.0
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5


**Package.json.**

{
  "name": "leaf",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.1",
    "@angular/cdk": "^11.0.0",
    "@angular/common": "~11.0.1",
    "@angular/compiler": "~11.0.1",
    "@angular/core": "~11.0.1",
    "@angular/forms": "~11.0.1",
    "@angular/material": "^11.0.0",
    "@angular/platform-browser": "~11.0.1",
    "@angular/platform-browser-dynamic": "~11.0.1",
    "@angular/router": "~11.0.1",
    "angular-password-strength-meter": "^3.0.1",
    "bootstrap": "^4.5.3",
    "mat-table-exporter": "^9.0.2",
    "ngx-cookie-service": "^10.1.1",
    "ngx-device-detector": "^2.0.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2",
    "zxcvbn3": "^0.1.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.2",
    "@angular/cli": "~11.0.2",
    "@angular/compiler-cli": "~11.0.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "^4.0.5"
  }
}

**Comment by JoostK** [comment]
> I was able to reproduce this error by accidently using a capital "F" in a form control...
> `<Form class="login-form" #f="ngForm" (ngSubmit)="onSubmit(f)">`
> 
> once I changed it to...
> `<form class="login-form" #f="ngForm" (ngSubmit)="onSubmit(f)">`
> the error went away.

@joebieb Thank you, that has helped in finding the issue. It appears to have regressed in #38618, where referring a reference that is bound to an unknown directive now crashes. Before, it would have reported an error:

```
ERROR in src/app/app.component.html:1:10 - error NG8003: No directive found with exportAs 'test'.

1 <div #a="test"></div> {{ a() }}
           ~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
```

I'm working on a fix.

**Comment by georgemichalagas** [comment]
The problem in my project, is inside this page. When i comment out all the code, is working. when i enable the code, i get this error. 
below the code.

`
<div class="example-container mat-elevation-z8">
  <mat-table matTableExporter [dataSource]="dataSource" #exporter="matTableExporter" [hiddenColumns]="[0]">

    <ng-container matColumnDef="position">
      <mat-header-cell *matHeaderCellDef> No. </mat-header-cell>
      <mat-cell *matCellDef="let element"> {{element.position}} </mat-cell>
    </ng-container>

    <ng-container matColumnDef="name">
      <mat-header-cell *matHeaderCellDef> Name </mat-header-cell>
      <mat-cell *matCellDef="let element"> {{element.name}} </mat-cell>
    </ng-container>

    <ng-container matColumnDef="surname">
      <mat-header-cell *matHeaderCellDef> Surname </mat-header-cell>
      <mat-cell *matCellDef="let element"> {{element.surname}} </mat-cell>
    </ng-container>

    <ng-container matColumnDef="birth">
      <mat-header-cell *matHeaderCellDef> Birth </mat-header-cell>
      <mat-cell *matCellDef="let element"> {{element.birth}} </mat-cell>
    </ng-container>

    <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>
  </mat-table>
  <mat-paginator [pageSizeOptions]="[5, 10, 20]" showFirstLastButtons></mat-paginator>
</div>
<button mat-raised-button
  (click)="exporter.exportTable('xlsx', {fileName:'test', sheet: 'sheet_name', Props: {Author: 'Talha'}})">Excel</button>
<button mat-raised-button (click)="exporter.exportTable('csv')">Csv</button>
<button mat-raised-button (click)="exporter.exportTable('json')">Json</button>
<button mat-raised-button (click)="exporter.exportTable('txt')">Txt</button>
<div>
`

`
import { Component, Inject, Input, OnInit, ViewChild } from '@angular/core';
import { MatDialog, MatDialogRef, } from '@angular/material/dialog';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';

export interface Element {
  name: string;
  position: number;
  surname: string;
  birth: string;
}

const ELEMENT_DATA: Element[] = [
  {position: 1, name: 'Albert', surname: 'Einstein', birth: '1879'},
  {position: 2, name: 'Marie', surname: 'Curie', birth: '1867'},
  {position: 3, name: 'Enrico', surname: 'Fermi', birth: '1901'},
  {position: 4, name: 'Dmitri', surname: 'Mendeleev', birth: '1834'},
  {position: 5, name: 'Alfred', surname: 'Nobel', birth: '1833'},
  {position: 6, name: 'Ernest', surname: 'Lawrence', birth: '1901'},
  {position: 7, name: 'Glenn', surname: 'Seaborg', birth: '1912'},
  {position: 8, name: 'Niels', surname: 'Bohr', birth: '1885'},
  {position: 9, name: 'Lise', surname: 'Meitner', birth: '1878'},
  {position: 10, name: 'Wilhelm', surname: 'Röntgen', birth: '1845'},
  {position: 11, name: 'Nicolaus', surname: 'Copernicus', birth: '1473'},
  {position: 12, name: 'Georgy', surname: 'Flyorov', birth: '1913'},
  {position: 13, name: 'Yuri', surname: 'Oganessian', birth: '1933'},
  {position: 14, name: 'Johan', surname: 'Gadolin', birth: '1760'},
  {position: 15, name: 'Pierre', surname: 'Curie', birth: '1859'},
];

@Component({
  selector: 'app-export-table',
  templateUrl: './export-table.component.html',
  styleUrls: ['./export-table.component.scss']
})

export class ExportTableComponent implements OnInit {
  @Input() dataRows: any[] = [];
  @Input() datacolumns: any[] = [];

  constructor(public dialogRef: MatDialogRef<ExportTableComponent>,
    public dialog: MatDialog) { }

    title = 'mte-test';
    displayedColumns = ['position', 'name', 'surname', 'birth'];
    @ViewChild(MatPaginator, { static: true }) paginator: MatPaginator;
    dataSource: MatTableDataSource<Element>;

    ngOnInit(): void {
      this.dataSource = new MatTableDataSource<Element>(ELEMENT_DATA);
      this.dataSource.paginator = this.paginator;
    }
}
`
