### ISSUE TITLE
Angular valid template with all the strict flags on results in DOMException.

### ISSUE THREAD

**Issue by spwin** [angular/angular#39781]
# 🐞 bug report

### Description
When compiling angular template there are no issues having `<app-test-component ([var1]="true">` but this results in `DOMException`. Angular is fine having any gibberish atributes, not only `([var1]`, it's just an example of a typo that is more likely to happen in real life scenario. IMO it should fail on compile. This happens even turning all strict flags on:
<pre><code>
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictTemplates": true,
    "strictInputTypes": true,
    "strictNullInputTypes": true,
    "strictAttributeTypes": true,
    "strictSafeNavigationTypes": true,
    "strictDomLocalRefTypes": true,
    "strictOutputEventTypes": true,
    "strictDomEventTypes": true,
    "strictContextGenerics": true,
    "strictLiteralTypes": true,
    "enableIvy": true
  }
</code></pre> 

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-wgnb8w

## 🔥 Exception or Error
Console error in browser:
<pre><code>
ERROR DOMException: Failed to execute 'setAttribute' on 'Element': '([var2]' is not a valid attribute name.
    at EmulatedEncapsulationDomRenderer2.setAttribute (http://localhost:4200/vendor.js:44711:16)
    at setUpAttributes (http://localhost:4200/vendor.js:16006:30)
    at ɵɵelementStart (http://localhost:4200/vendor.js:25426:9)
    at Module.ɵɵelement (http://localhost:4200/vendor.js:25500:5)
    at AppComponent_Template (http://localhost:4200/main.js:67:64)
    at executeTemplate (http://localhost:4200/vendor.js:20205:9)
    at renderView (http://localhost:4200/vendor.js:20012:13)
    at renderComponent (http://localhost:4200/vendor.js:21274:5)
    at renderChildComponents (http://localhost:4200/vendor.js:19877:9)
    at renderView (http://localhost:4200/vendor.js:20037:13)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.2
Node: 12.13.1
OS: linux x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by JoostK** [comment]
Relates to #39114.

**Comment by mcalmus** [comment]
I received the same exception when I accidentally put an extra equals sign ```[myAttibute]=="foo"```
