### ISSUE TITLE
Error: Error: Could not resolve [object Object] / undefined

### ISSUE THREAD

**Issue by georgemichalagas** [angular/angular#39798]
# 🐞 bug report
The issue is caused by package @angular\compiler-cli

### Is this a regression?
No

 
### Description
When i build the app, i get the below error, after angular updated to 11 (from 10).

## 🔬 Minimal Reproduction
I dont know.

## 🔥 Exception or Error
<pre><code>

PS C:\Dev\Repos\IPDB\leaf.client.v.4> ng build
√ Browser application bundle generation complete.

Error: Error: Could not resolve [object Object] / undefined
    at Scope.resolve (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1318:23)
    at TcbEventHandlerTranslator.TcbExpressionTranslator.resolveTarget (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1877:35)
    at TcbEventHandlerTranslator.TcbExpressionTranslator.resolve (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1786:29)
    at TcbEventHandlerTranslator.resolve (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:2034:45)
    at AstTranslator.maybeResolve (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1771:84)
    at AstTranslator.translate (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:74:33)
    at AstTranslator.visitMethodCall (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:201:66)
    at MethodCall.visit (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler\bundles\compiler.umd.js:8389:28)
    at AstTranslator.translate (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:78:24)
    at Object.astToTypescript (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\expression.js:55:27)
    at TcbEventHandlerTranslator.TcbExpressionTranslator.translate (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1771:33)
    at tcbEventHandlerExpression (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:2016:27)
    at tcbCreateEventHandler (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1974:23)
    at TcbUnclaimedOutputsOp.execute (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1050:39)
    at Scope.executeOp (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1428:26)
    at Scope.render (C:\Dev\Repos\IPDB\leaf.client.v.4\node_modules\@angular\compiler-cli\src\ngtsc\typecheck\src\type_check_block.js:1335:22)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

PS C:\Dev\Repos\IPDB\leaf.client.v.4> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.2
Node: 10.16.3
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.0
@angular/material               11.0.0
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**
Package.json:
<pre><code>
{
  "name": "",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.1",
    "@angular/cdk": "^11.0.0",
    "@angular/common": "~11.0.1",
    "@angular/compiler": "~11.0.1",
    "@angular/core": "~11.0.1",
    "@angular/forms": "~11.0.1",
    "@angular/material": "^11.0.0",
    "@angular/platform-browser": "~11.0.1",
    "@angular/platform-browser-dynamic": "~11.0.1",
    "@angular/router": "~11.0.1",
    "angular-password-strength-meter": "^3.0.1",
    "bootstrap": "^4.5.3",
    "mat-table-exporter": "^9.0.2",
    "ngx-cookie-service": "^10.1.1",
    "ngx-device-detector": "^2.0.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2",
    "zxcvbn3": "^0.1.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.2",
    "@angular/cli": "~11.0.2",
    "@angular/compiler-cli": "~11.0.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "^4.0.5"
  }
}
</code></pre>

**Comment by JoostK** [comment]
It looks like there has been a regression in Angular 11's template type checking, which has already been reported in #39744. Unfortunately there's hasn't been a reproduction provided, so I'd like to ask you to share yours in #39744 for us to investigate what causes this.
