### ISSUE TITLE
No provider for Console!

### ISSUE THREAD

**Issue by schematical** [angular/angular#39934]
# 🐞 bug report

### Affected Package
@angular/platform-browser

### Is this a regression?
I dont actually know

### Description
Having trouble getting the BrowserModule to load in an Angular Library module. Getting this error:
```
NullInjectorError: StaticInjectorError(AppModule)[ApplicationRef -> Console]: 
  StaticInjectorError(Platform: core)[ApplicationRef -> Console]: 
    NullInjectorError: No provider for Console!
```

Looking at the code here is the DI for Console: 
https://github.com/angular/angular/blob/453b32f4b9936b78cfb2991b64d78c0509c94514/packages/platform-browser/src/dom/events/hammer_gestures.ts#L167

Full Error:

```

@NgModule({
  declarations: [],
  imports: [
     CommonModule,
     BrowserModule,
     HttpClientModule,
    // HttpLinkModule,
    // ApolloModule
  ],
  exports: [],
  providers: [
  
  ]

})```


packages
```
 "@angular/animations": "~10.1.3",
    "@angular/common": "~10.1.3",
    "@angular/compiler": "~10.1.3",
    "@angular/core": "~10.1.3",
    "@angular/forms": "~10.1.3",
    "@angular/platform-browser": "~10.1.3",
    "@angular/platform-browser-dynamic": "~10.1.3",
    "@angular/router": "~10.1.3",
```
I also added the following to my `tsconfig.json`:
```
...
"paths": {
      "@angular/*": [
        "./node_modules/@angular/*",
      ]
      ...
```
## 🔬 Minimal Reproduction
It seems to happen no matter what I did once I added it to the module. 


## 🔥 Exception or Error
<pre><code>
main.ts:13 NullInjectorError: StaticInjectorError(AppModule)[ApplicationRef -> Console]: 
  StaticInjectorError(Platform: core)[ApplicationRef -> Console]: 
    NullInjectorError: No provider for Console!
    at NullInjector.get (http://localhost:4200/vendor.js:145147:27)
    at resolveToken (http://localhost:4200/vendor.js:160065:24)
    at tryResolveToken (http://localhost:4200/vendor.js:159991:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:159841:20)
    at resolveToken (http://localhost:4200/vendor.js:160065:24)
    at tryResolveToken (http://localhost:4200/vendor.js:159991:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:159841:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:171028:29)
    at _createClass (http://localhost:4200/vendor.js:171105:32)
    at _createProviderInstance (http://localhost:4200/vendor.js:171061:26)
(anonymous) @ main.ts:13
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:40600
./src/main.ts @ main.ts:12
__webpack_require__ @ bootstrap:84
0 @ types.ts:3530
__webpack_require__ @ bootstrap:84
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.7
Node: 12.13.1
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
ng-packagr                      10.1.2
rxjs                            6.6.3
typescript                      4.0.5


</code></pre>

**Anything else relevant?**
Im testing in the latest chrome primarily but it also fails the ng-tests that are generated with the library.

**Comment by jessicajaniuk** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by schematical** [comment]
So this is functionality that you expect normally @jessicajaniuk ?

**Comment by jessicajaniuk** [comment]
@schematical As mentioned in [this explaination](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem), the best place to ask support questions is to go to repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`. If you believe this to be an actual bug, please create a minimal reproduction on [StackBlitz](https://stackblitz.com/) with the latest version of angular, add it to your description, and re-open the issue.
