### ISSUE TITLE
When IVY enable I get the following error:  Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by YonathanB** [angular/angular#40188]
# 🐞 bug report

### Affected Package

 THe issue happens when IVY enable

### Is this a regression?

 If it is because IVY I think it is a regression

### Description

 I try to genereate components dynamically using projectableNodes.
When doing so with a component and a template it works well. 
If I want to get RID of the template and use a directive I get an error (only when IVY enable)

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-h3wqc4

## 🔥 Exception or Error
<pre><code>

preview-fef3604083950c709c52b.js:1 ERROR DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at DefaultDomRenderer2.insertBefore (https://angular-h3wqc4.stackblitz.io/turbo_modules/@angular/platform-browser@10.0.0/__ivy_ngcc__/bundles/platform-browser.umd.js:930:24)
    at nativeInsertBefore (https://angular-h3wqc4.stackblitz.io/turbo_modules/@angular/core@10.0.0/__ivy_ngcc__/bundles/core.umd.js:9674:22)
    at applyToElementOrContainer (https://angular-h3wqc4.stackblitz.io/turbo_modules/@angular/core@10.0.0/__ivy_ngcc__/bundles/core.umd.js:9234:17)
    at applyNodes (https://angular-h3wqc4.stackblitz.io/turbo_modules/@angular/core@10.0.0/__ivy_ngcc__/bundles/core.umd.js:9865:21)
    at applyView (https://angular-h3wqc4.stackblitz.io/turbo_modules/@angular/core@10.0.0/__ivy_ngcc__/bundles/core.umd.js:9897:9)
    at addRemoveViewFromContainer (https://angular-h3wqc4.stackblitz.io/turbo_modules/@angular/core@10.0.0/__ivy_ngcc__/bundles/core.umd.js:9260:13)
    at ViewContainerRef.insert (https://angular-h3wqc4.stackblitz.io/turbo_modules/@angular/core@10.0.0/__ivy_ngcc__/bundles/core.umd.js:10698:21)
    at ViewContainerRef.createComponent (https://angular-h3wqc4.stackblitz.io/turbo_modules/@angular/core@10.0.0/__ivy_ngcc__/bundles/core.umd.js:10665:26)
    at DirDirective.ngAfterViewInit (https://angular-h3wqc4.stackblitz.io/~/src/app/dir.directive.ts:18:18)
    at callHook (https://angular-h3wqc4.stackblitz.io/turbo_modules/@angular/core@10.0.0/__ivy_ngcc__/bundles/core.umd.js:3154:22)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by YonathanB** [comment]
Seems to be a reference to the bug https://github.com/angular/angular/issues/35412.

It says there that the bug is closed because:

> I'm going to close this issue since the root cause here is the manual DOM manipulation outside of the framework / incorrect use of the existing APIs. While this particular scenario might have worked in the past, it would also fail in VE under slightly different condition - simply put this is not the pattern we want to encourage.

Well, please look at the [stackblitz](https://stackblitz.com/edit/angular-h3wqc4?file=package.json), you will see that there is no DOM manipulation outside of the framework

**Comment by AndrewKushnir** [comment]
Hi @YonathanB,

Thanks for creating a repro, it's very helpful.

I perform further investigation and found out that the problem happens because of the code in `dir.directive.ts` ([link](https://stackblitz.com/edit/angular-h3wqc4?file=src%2Fapp%2Fdir.directive.ts)):

```
const compARef = this.vcr.createComponent(compAFactory);

this.vcr.createComponent(compBFactory, 0, undefined, [
  [compARef.location.nativeElement]
]);
```

What happens here is that an instance of ComponentA is created and corresponding element is inserted into the DOM. After that an instance of ComponentB is created which uses the ComponentA's host element as a projectable node, so you end up with something like this:

```
<app-comp-a></comp-a>
<app-comp-b>
  <!-- we try to project <app-comp-a> here -->
</app-comp-b>
```

I believe the intention is to just have `<app-comp-a>` as a child of `<app-comp-b>` (without having `<app-comp-a>` at the top level) and if that's the case, I'd like to propose the following solution instead ([see full example here](https://stackblitz.com/edit/angular-gz9rwc?file=src%2Fapp%2Fdir.directive.ts)):

```
const compAInstance = compAFactory.create(this.injector);

this.vcr.createComponent(compBFactory, 0, undefined, [
  [compAInstance.location.nativeElement]
]);
```

It's very similar but instead of calling `this.vcr.createComponent` which creates a component and inserts it into view container, you can use `compAFactory.create` and after that use underlying DOM element as a projectable node. It looks like using `create` method is more inline with what you are trying to achieve.

I'm keeping this ticket open since this scenario used to work with ViewEngine (tested with Stackblitz), so we can look into handling this better and/or throwing a more descriptive error message.

**Comment by YonathanB** [comment]
Hi @AndrewKushnir,
thanks for the response.
The repro in the link you provided is not matching my goal., but I tried the code you posted and it works.

Anyway, if you disable IVY you will see that the same code (mine) will work. 
I understand your answer, it makes me understand some few things about `ViewContainerRef` my question is why it used to work before IVY?

**Comment by AndrewKushnir** [comment]
> my question is why it used to work before IVY?

My current understanding is that it used to work by accident - there was no code that triggered an error. However the fact is that the DOM structure and underlying data structure in the framework (that holds `ComponentRef`s) were out of sync when you projected a host node of `ComponentA` into `ComponentB`, so having an error there might makes sense from that perspective.
 
I've left this ticket open so that we can perform more investigation to see if Ivy should be updated to detect these cases and either process them (move DOM nodes without errors) or throw more descriptive error.
