### ISSUE TITLE
Karma tests exit with "Cannot read property 'range' of undefined" with node >=v14.15.2

### ISSUE THREAD

**Issue by DavideViolante** [angular/angular#40232]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core/testing I think

### Description

 Running `ng test` using node >=v14.15.2 returns:
```
⠙ Generating browser application bundles (phase: building)...22 12 2020 12:04:26.906:WARN [karma]: No captured browser, open http://localhost:9876/
22 12 2020 12:04:26.910:INFO [karma-server]: Karma v5.1.1 server started at http://localhost:9876/
22 12 2020 12:04:26.911:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
22 12 2020 12:04:26.917:INFO [launcher]: Starting browser Chrome
✔ Browser application bundle generation complete.
22 12 2020 12:04:38.116:WARN [karma]: No captured browser, open http://localhost:9876/
22 12 2020 12:04:38.338:INFO [Chrome 87.0.4280.88 (Linux x86_64)]: Connected on socket q9H-XQKOR1UxhC76AAAA with id 44160212
Chrome 87.0.4280.88 (Linux x86_64): Executed 1 of 54 SUCCESS (0 secs / 0.075 secs)
22 12 2020 12:04:41.304:ERROR [karma-server]: UnhandledRejection: Cannot read property 'range' of undefined
22 12 2020 12:04:41.380:ERROR [karma-server]: TypeError: Cannot read property 'range' of undefined
    at handleRangeHeaders (/home/dave/projects/myproject/node_modules/webpack-dev-middleware/lib/util.js:131:21)
    at processRequest (/home/dave/projects/myproject/node_modules/webpack-dev-middleware/lib/middleware.js:98:19)
    at ready (/home/dave/projects/myproject/node_modules/webpack-dev-middleware/lib/util.js:53:12)
    at handleRequest (/home/dave/projects/myproject/node_modules/webpack-dev-middleware/lib/util.js:182:5)
    at /home/dave/projects/myproject/node_modules/webpack-dev-middleware/lib/middleware.js:64:7
    at new Promise (<anonymous>)
    at middleware (/home/dave/projects/myproject/node_modules/webpack-dev-middleware/lib/middleware.js:63:12)
    at /home/dave/projects/myproject/node_modules/@angular-devkit/build-angular/src/webpack/plugins/karma.js:288:13
    at call (/home/dave/projects/myproject/node_modules/connect/index.js:239:7)
    at next (/home/dave/projects/myproject/node_modules/connect/index.js:183:5)
    at /home/dave/projects/myproject/node_modules/karma/lib/web-server.js:24:9
    at call (/home/dave/projects/myproject/node_modules/connect/index.js:239:7)
    at next (/home/dave/projects/myproject/node_modules/connect/index.js:183:5)
    at nullProxy (/home/dave/projects/myproject/node_modules/karma/lib/middleware/proxy.js:86:52)
    at call (/home/dave/projects/myproject/node_modules/connect/index.js:239:7)
    at next (/home/dave/projects/myproject/node_modules/connect/index.js:183:5)
```
Going back to the past commits is the same results, so I assume it's not my code problem.

Another similar or same problem: https://stackoverflow.com/questions/64752689/karma-server-typeerror-cannot-read-property-range-of-undefined-angular-u
Note the comment `having the same issue with v14.15.2. Switching to v14.15.1 works. – user985409 Dec 17 at 7:28`

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.1
Node: 14.15.2
OS: linux x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.2
</code></pre>

**Anything else relevant?**

**Comment by DavideViolante** [comment]
I found out that is not related to Angular, neither to Karma, but to Node itself.
Upgrading to node v14.15.3 solves the problem. Closing.
