### ISSUE TITLE
Updating to Angular 10: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SinghManvir** [angular/angular#40495]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.1.9

### Description

Trying to update the app from version 9.1.9 to version 11. Following the Update Guide, I am doing it one major version at a time.
When I run the update command to update to version 10, it updates the package.json and runs yarn to install the packages. Once, yarn is completed, it runs the `ngcc` command and breaks with the `RangeError`.
Build (with and without --prod) works fine.
## 🔬 Minimal Reproduction
`ng update @angular/core@10 @angular/cli@10`

package.json
```
"dependencies": {
    "@agm/core": "~1.1.0",
    "@angular/animations": "~9.1.11",
    "@angular/cdk": "~9.2.4",
    "@angular/common": "~9.1.11",
    "@angular/compiler": "~9.1.11",
    "@angular/core": "~9.1.11",
    "@angular/flex-layout": "~9.0.0-beta.29",
    "@angular/forms": "~9.1.11",
    "@angular/material": "~9.2.4",
    "@angular/material-moment-adapter": "^9.2.4",
    "@angular/platform-browser": "~9.1.11",
    "@angular/platform-browser-dynamic": "~9.1.11",
    "@angular/router": "~9.1.11",
    "@fortawesome/angular-fontawesome": "0.6.1",
    "@fortawesome/fontawesome-svg-core": "1.2.29",
    "@fortawesome/free-brands-svg-icons": "^5.13.1",
    "@fortawesome/free-regular-svg-icons": "^5.13.1",
    "@fortawesome/free-solid-svg-icons": "^5.13.1",
    "@ngu/carousel": "2.0.3",
    "@ngx-translate/core": "~11.0.1",
    "@ngx-translate/http-loader": "~4.0.0",
    "@swimlane/ngx-datatable": "~17.0.0",
    "angular-calendar": "~0.28.2",
    "angular-web-storage": "~7.0.0-beta.1",
    "chart.js": "^2.8.0",
    "classlist.js": "1.1.20150312",
    "core-js": "^3.1.4",
    "css-star-rating": "1.2.4",
    "date-fns": "1.28.5",
    "echarts": "4.2.1",
    "file-saver": "2.0.2",
    "flag-icon-css": "3.3.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "2.0.8",
    "highlight.js": "9.15.6",
    "hopscotch": "0.3.1",
    "install": "0.12.2",
    "moment": "2.24.0",
    "ng2-charts": "^2.3.2",
    "ng2-dragula": "2.1.1",
    "ng2-file-upload": "1.4.0",
    "ngx-color-picker": "7.5.0",
    "ngx-custom-validators": "^9.1.0",
    "ngx-echarts": "4.1.1",
    "ngx-pagination": "3.2.1",
    "ngx-perfect-scrollbar": "^8.0.0",
    "ngx-quill": "^11.1.0",
    "node-gyp": "^5.0.0",
    "npm": "6.13.7",
    "oidc-client": "^1.8.0",
    "perfect-scrollbar": "1.4.0",
    "popper.js": "^1.15.0",
    "quill": "1.3.6",
    "replace-in-file": "^4.1.3",
    "rxjs": "^6.5.5",
    "ts-nameof": "^3.1.0",
    "tslib": "^1.11.0",
    "web-animations-js": "^2.3.2",
    "xlsx": "0.15.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.9",
    "@angular-devkit/core": "9.1.9",
    "@angular/cli": "~9.1.9",
    "@angular/compiler-cli": "~9.1.11",
    "@angular/language-service": "~9.1.11",
    "@ngneat/spectator": "^5.9.1",
    "@types/hopscotch": "0.2.30",
    "@types/jasmine": "~3.3.13",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "moq.ts": "^3.0.0",
    "protractor": "~5.4.2",
    "rxjs-tslint-rules": "^4.33.1",
    "ts-node": "~8.3.0",
    "tslint": "~5.17.0",
    "typescript": "~3.8.3"
  }
```

## 🔥 Exception or Error
<pre><code>
...
Compiling @ngneat/spectator/jest : esm5 as esm5
Compiling @ngneat/spectator/jest : main as umd
Compiling @ngu/carousel : fesm5 as esm5
Compiling @ngu/carousel : esm2015 as esm2015
Compiling @ngu/carousel : esm5 as esm5
Compiling @ngu/carousel : main as umd
Error: Error on worker angular/angular-cli#3: RangeError: Maximum call stack size exceeded
    at resolveEntityName (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\typescript\lib\typescript.js:44990:35)
    at getSymbolOfNameOrPropertyAccessExpression (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\typescript\lib\typescript.js:75600:28)
    at getSymbolAtLocation (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\typescript\lib\typescript.js:75665:28)
    at Object.getSymbolAtLocation (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\typescript\lib\typescript.js:42656:31)
    at UmdReflectionHost.findUmdImportParameter (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:341:45)
    at UmdReflectionHost.getImportPathFromParameter (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:424:40)
    at UmdReflectionHost.getUmdModuleDeclaration (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:412:35)
    at UmdReflectionHost.getDeclarationOfIdentifier (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:54:70)
    at UmdReflectionHost.Esm2015ReflectionHost.getDeclarationOfExpression (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\host\esm2015_host.js:1788:29)
    at UmdReflectionHost.getDeclarationOfExpression (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:455:64)
    at ClusterMaster.onWorkerMessage (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
    at C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:140:27)
    at Object.next (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:121:57)
    at C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\node_modules\tslib\tslib.js:110:16)
    at EventEmitter.<anonymous> (C:\Development\foo\foo-WebApp\src\foo.WebApp\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
    at EventEmitter.emit (events.js:315:20)
error Command failed with exit code 1.
× Package install failed, see above.
× Migration failed. See above for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.9
Node: 14.15.4
OS: win32 x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.9
@angular-devkit/build-angular      0.901.9
@angular-devkit/build-optimizer    0.901.9
@angular-devkit/build-webpack      0.901.9
@angular-devkit/core               9.1.9
@angular-devkit/schematics         9.1.9
@angular/cdk                       9.2.4
@angular/cli                       9.1.9
@angular/flex-layout               9.0.0-beta.31
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.9
@schematics/angular                9.1.9
@schematics/update                 0.901.9
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**
I have tried removing `ng_modules` folder and reinstalling the packages several times. 
I have updated Node version to 14.15.
I have also tried running `node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng update @angular/core@10 @angular/cli@10`

**Comment by petebacondarwin** [comment]
Do you have a `postinstall` script in your `package.json` that is running ngcc?
Can you try removing this? I suspect it was added at some point by a migration, but it is no longer needed.

**Comment by SinghManvir** [comment]
@petebacondarwin - Yes, I do, and it works fine without that. But is it okay to remove that? Angular update guide recommends adding it in.

**Comment by petebacondarwin** [comment]
Yes, please remove it. I can't remember where but certainly by v11 it should not be there. Probably by v10. @alan-agius4 can confirm.

**Comment by alan-agius4** [comment]
Yeah, the postinstall script shouldn’t be needed.

**Comment by SinghManvir** [comment]
Thanks @alan-agius4 and @petebacondarwin

**Comment by GHVladimir** [comment]
@alan-agius4 Hi, I also have ngcc running before tests. Can I remove it there since it is causing the same stack exceeded error, and if I remove it, will it still run tests with Ivy?

**Comment by GHVladimir** [comment]
If I remove ngcc before tests are ran, I will receive errors like: No component factory found for ***Component. Did you add it to @NgModule.entryComponents? This would mean tests are not ran with Ivy. But running ngcc will cause RangeError. What can I do to prevent this from happening?
