### ISSUE TITLE
Error: [object Object] is not a PostCSS plugin After updating to Angular 11.1.0

### ISSUE THREAD

**Issue by mrctrifork** [angular/angular#40503]
# 🐞 bug report

### Affected Package
 the application itself

### Is this a regression?
Not a regression

### Description

I updated my app from Angular 11.0.9 to Angular 11.1.0 because there was a bug with the HttpClient and now it doesn't compile

## 🔬 Minimal Reproduction

I ran

```ng update @angular/cdk @angular/core @angular/cli @angular/material```

## 🔥 Exception or Error
<pre><code>
✔ Browser application bundle generation complete.

Error: ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss-loader/dist/index.js:94:41)
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/webpack/lib/NormalModule.js:313:13
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/@ngtools/webpack/src/ivy/loader.js:57:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ multi ./src/main.ts main[0]

Error: ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss-loader/dist/index.js:94:41)
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/webpack/lib/NormalModule.js:313:13
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/@ngtools/webpack/src/ivy/loader.js:57:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ multi ./src/polyfills.ts polyfills[0]

Error: ./src/bootstrap-grid.min.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss-loader/dist/index.js:94:41)
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss-loader/dist/index.js:103:7)
 @ multi ./src/assets/style/tailwind-out.css ./src/bootstrap-grid.min.css ./src/assets/style/styles.scss styles[1]

Error: ./src/assets/style/tailwind-out.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss-loader/dist/index.js:94:41)
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/Users/miquel/AngularProjects/mit-evida/frontend/web/node_modules/postcss-loader/dist/index.js:103:7)
 @ multi ./src/assets/style/tailwind-out.css ./src/bootstrap-grid.min.css ./src/assets/style/styles.scss styles[0]

Error: ./src/assets/style/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.0
Node: 14.15.0
OS: darwin x64

Angular: 11.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0
@angular-devkit/build-angular   0.1101.0
@angular-devkit/core            11.1.0
@angular-devkit/schematics      11.1.0
@schematics/angular             11.1.0
@schematics/update              0.1101.0
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**
Nothing else, can't build the app

**Comment by jerkovicl** [comment]
got the same error for HttpClient
![image](https://user-images.githubusercontent.com/5444153/105355353-515a0780-5bf2-11eb-8705-60f05f9ce24c.png)

**Comment by ghaschel** [comment]
I solved this by running:
`rm -rf node_modules && npm cache clear --force && npm install`

**Comment by petebacondarwin** [comment]
Yes, please try removing `node_modules` and reinstalling.

**Comment by jerkovicl** [comment]
@petebacondarwin i did that still same error `HttpClient is not defined`

**Comment by acalvo** [comment]
I'm having the same problem as OP, and neither `npm ci` nor ` rm -rf node_modules && npm cache clear --force && npm install` solved it 😬

**Comment by petebacondarwin** [comment]
Please can one of you provide a reproduction that we can debug?

**Comment by mrctrifork** [comment]
I've removed node_modules, cleared npm's cache and reinstalled everything. Not fixed

**Comment by mrctrifork** [comment]
I have a strong belief that is due to the PostCSS update. Before Angular 11 used PostCSS 7 and now I've seen on my package-lock.json plenty of references to PostCSS 8.


I am freaking out a little bit because this error:

![imagen](https://user-images.githubusercontent.com/45353144/105358443-75b7e300-5bf6-11eb-9c13-c739ec861b07.png)


Is a PostCSS error when referencing the `main.ts` file

**Comment by jerkovicl** [comment]
@mrctrifork  if you do npm i postcss -D that error will be gone atleast in my case but HttpClient is still not defined

**Comment by mrctrifork** [comment]
I confirm that running `npm i postcss -D` makes the error about PostCSS go away. 
I have no injection errors in regards of the HttpClient.

**Comment by jerkovicl** [comment]
@petebacondarwin where can i send code for you to reproduce ?

**Comment by petebacondarwin** [comment]
@jerkovicl - I have emailed you at your protonmail account.

**Comment by jerkovicl** [comment]
@petebacondarwin yeah i sent app code to you

**Comment by leonelvsc** [comment]
Same here

```
Error: (webpack)-dev-server/client?http://0.0.0.0:0&sockPath=/sockjs-node
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:313:13
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@ngtools/webpack/src/ivy/loader.js:57:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Error: ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:313:13
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@ngtools/webpack/src/ivy/loader.js:57:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Error: ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
NonErrorEmittedError: (Emitted value instead of an instance of Error) Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:313:13
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@ngtools/webpack/src/ivy/loader.js:57:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Error: ./src/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)

Error: ./node_modules/text-security/text-security.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)

Error: ./node_modules/text-security/text-security-circle.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)

Error: ./node_modules/swiper/swiper-bundle.min.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)

Error: ./node_modules/@clr/icons/clr-icons.min.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)

Error: ./node_modules/@clr/ui/clr-ui.min.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)

Error: ./node_modules/flatpickr/dist/flatpickr.min.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)

Error: ./node_modules/select2/dist/css/select2.min.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)

Error: ./node_modules/ag-grid-community/dist/styles/ag-grid.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)

Error: ./node_modules/ag-grid-community/dist/styles/ag-theme-balham.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss/lib/postcss.js:55:10)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:94:41)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.loader (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/postcss-loader/dist/index.js:103:7)
```

**Comment by petebacondarwin** [comment]
OK so there are two issues here:

1. PostCSS dependency - this can be worked around by installing it directly at the top level `npm i postcss -D`
2. Missing HttpClient import - looking into this now.

**Comment by petebacondarwin** [comment]
Transferring to the CLI project, since we think it is most likely a problem there.
