### ISSUE TITLE
Unknown version 87 of chrome when compiling an Angular library project

### ISSUE THREAD

**Issue by wendellestradairely** [angular/angular#40535]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

This error is now appearing after upgrading from Angular 10 to Angular 11.

Run: `ng build <angular library>`

```
× Compiling TypeScript sources through NGC
ERROR: Unknown version 87 of chrome
An unhandled exception occurred: Unknown version 87 of chrome
```

[error] BrowserslistError: Unknown version 87 of chrome
    at Function.select (C:\Projects\MyProjectNg9\MyProject\src\Hris\ClientApp\myproj\node_modules\autoprefixer\node_modules\browserslist\index.js:1086:17)
    at C:\Projects\MyProjectNg9\MyProject\src\Hris\ClientApp\myproj\node_modules\autoprefixer\node_modules\browserslist\index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (C:\Projects\MyProjectNg9\MyProject\src\Hris\ClientApp\myproj\node_modules\autoprefixer\node_modules\browserslist\index.js:318:18)
    at browserslist (C:\Projects\MyProjectNg9\MyProject\src\Hris\ClientApp\myproj\node_modules\autoprefixer\node_modules\browserslist\index.js:443:21)
    at Browsers.parse (C:\Projects\MyProjectNg9\MyProject\src\Hris\ClientApp\myproj\node_modules\autoprefixer\lib\browsers.js:64:12)
    at new Browsers (C:\Projects\MyProjectNg9\MyProject\src\Hris\ClientApp\myproj\node_modules\autoprefixer\lib\browsers.js:46:26)
    at loadPrefixes (C:\Projects\MyProjectNg9\MyProject\src\Hris\ClientApp\myproj\node_modules\autoprefixer\lib\autoprefixer.js:97:20)
    at plugin (C:\Projects\MyProjectNg9\MyProject\src\Hris\ClientApp\myproj\node_modules\autoprefixer\lib\autoprefixer.js:108:20)
    at LazyResult.run (C:\Projects\MyProjectNg9\MyProject\src\Hris\ClientApp\myproj\node_modules\ng-packagr\node_modules\postcss\lib\lazy-result.js:288:14)

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

It looks like you have a problem with your browserslist configuration, please open a new issue at https://github.com/angular/angular-cli/issues/new if you cannot work out the problem We keep Angular CLI issues in a separate repository.

**Comment by s-gurevich** [comment]
I had the exactly same problem after having upgraded from angular 10 to angular 11 using the cli. Only in my case it was "version 88 of edge".

Was able to solve it by running that in project root:

`npx browserslist --update-db`

It made changes to `package-lock.json`: Versions of `caniuse-lite` were changed

Maybe the angular-cli team could take that into consideration?
