### ISSUE TITLE
RouterLink fails to generate links for nested routes with dynamic parameters

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular#4054]
When I try to generate a link to a nested router path with a dynamic parameter I receive an error. 

```
EXCEPTION: Route generator for 'param' was not included in parameters passed. in [null]
angular2.min.js:11 ORIGINAL EXCEPTION: Route generator for 'param' was not included in parameters passed.
angular2.min.js:11 ORIGINAL STACKTRACE:
angular2.min.js:11 Error: Route generator for 'param' was not included in parameters passed.
    at new t (https://code.angularjs.org/2.0.0-alpha.36/angular2.min.js:3:22875)
    at DynamicSegment.execute.name.generate (https://code.angularjs.org/2.0.0-alpha.36/router.dev.js:1200:21)
    at PathRecognizer.execute.handler.generate (https://code.angularjs.org/2.0.0-alpha.36/router.dev.js:1296:35)
    at RouteRecognizer.execute.RouteRecognizer.generate (https://code.angularjs.org/2.0.0-alpha.36/router.dev.js:1590:35)
    at execute.RouteRegistry.generate (https://code.angularjs.org/2.0.0-alpha.36/router.dev.js:2228:48)
    at RootRouter.execute.hostComponent.generate (https://code.angularjs.org/2.0.0-alpha.36/router.dev.js:1920:49)
    at routeParams (https://code.angularjs.org/2.0.0-alpha.36/router.dev.js:1455:54)
    at e.ChangeDetector_App_comp_0.detectChangesInRecordsInternal (eval at <anonymous> (https://code.angularjs.org/2.0.0-alpha.36/angular2.min.js:17:8), <anonymous>:252:40)
    at execute.$traceurRuntime.createClass.detectChangesInRecords (https://code.angularjs.org/2.0.0-alpha.36/angular2.min.js:14:30297)
    at execute.$traceurRuntime.createClass.runDetectChanges (https://code.angularjs.org/2.0.0-alpha.36/angular2.min.js:14:30019)
angular2.min.js:11 ERROR CONTEXT:
angular2.min.js:11 e {element: a.ng-binding, componentElement: app, context: App, locals: Object, injector: e…}
```

If I generate a link without using a dynamic parameter to a nested router path it works correctly, and if i use a regular href with an absolute path, the link does navigate correctly.

Issue reproduced here: http://plnkr.co/edit/zoSAcCkAwQ1TfzxJaiSI?p=info

**Comment by btford** [comment]
I think you want `[router-link]="['/users', { 'param': user }, 'profile' ]`. Params are component-specific.

I tested with your plunker, and this appears to work as expected, but if I'm incorrect, please comment and I'll reopen for discussion. Thanks!

**Comment by brandonroberts** [comment]
Thanks for the clarification
