### ISSUE TITLE
Angular Universal unknown err

### ISSUE THREAD

**Issue by mbabaei0** [angular/angular#40652]
# 🐞 bug report

### Affected Package
    "@angular/animations": "~11.0.3",
    "@angular/cdk": "^11.0.3",
    "@angular/common": "~11.0.3",
    "@angular/compiler": "~11.0.3",
   "@nguniversal/express-engine": "^11.0.1",

## 🔥 Exception or Error
<pre><code>
ERROR TypeError: Cannot read property 'display' of undefined
    at cloakElement (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278935:36)
    at /home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278941:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278941:14)
    at TransitionAnimationEngine._flushAnimations (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278501:38)
    at TransitionAnimationEngine.flush (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278283:32)
    at InjectableAnimationEngine.flush (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:279145:32)
    at /home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:152070:29
    at ZoneDelegate.crGB.ZoneDelegate.invoke (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:181534:30)
    at Zone.crGB.Zone.run (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:181291:47)
    at NgZone.runOutsideAngular (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:220502:28)
    at AnimationRendererFactory.end (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:152068:24)
    at renderComponentOrTemplate (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:201590:29)
    at tickRootContext (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:202812:9)
    at detectChangesInRootView (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:202837:5)
    at RootViewRef.detectChanges (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:214842:9)

</code></pre>

**Comment by mbabaei0** [comment]
> #  bug report
> ### Affected Package
> ```
> "@angular/animations": "~11.0.3",
> "@angular/cdk": "^11.0.3",
> "@angular/common": "~11.0.3",
> "@angular/compiler": "~11.0.3",
> ```
> 
> "@nguniversal/express-engine": "^11.0.1",
> 
> ##  Exception or Error
> ```
> 
> ERROR TypeError: Cannot read property 'display' of undefined
>     at cloakElement (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278935:36)
>     at /home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278941:48
>     at Set.forEach ()
>     at cloakAndComputeStyles (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278941:14)
>     at TransitionAnimationEngine._flushAnimations (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278501:38)
>     at TransitionAnimationEngine.flush (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:278283:32)
>     at InjectableAnimationEngine.flush (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:279145:32)
>     at /home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:152070:29
>     at ZoneDelegate.crGB.ZoneDelegate.invoke (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:181534:30)
>     at Zone.crGB.Zone.run (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:181291:47)
>     at NgZone.runOutsideAngular (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:220502:28)
>     at AnimationRendererFactory.end (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:152068:24)
>     at renderComponentOrTemplate (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:201590:29)
>     at tickRootContext (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:202812:9)
>     at detectChangesInRootView (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:202837:5)
>     at RootViewRef.detectChanges (/home/mohammad/projects/front-end-zhaak/dist/server/server/main.js:214842:9)
> ```

https://www.zhaak.com/blog/7/%DA%86%D8%B7%D9%88%D8%B1-%D9%85%DB%8C%D8%B2%D8%A7%D9%86-%D8%AA%D8%B9%D8%A7%D9%85%D9%84-%D8%B1%D8%A7-%D8%AF%D8%B1-%D8%A2%DA%A9%D8%A7%D8%AF%D9%85%DB%8C-%D8%A2%D9%86%D9%84%D8%A7%DB%8C%D9%86-%D8%A8%D9%87-%D8%AD%D8%AF%D8%A7%DA%A9%D8%AB%D8%B1-%D8%A8%D8%B1%D8%B3%D8%A7%D9%86%DB%8C%D9%85
