### ISSUE TITLE
Error After update Angular 9 to Angular 10

### ISSUE THREAD

**Issue by HamzaAyada** [angular/angular#40701]
Hello, after update my angular project from version 9 to version 10 i get error with running project,
i thing the problème it's with the anguar-font-awesome but i uninstall it and installed again but the problème not fixed. 
any help to resolve this issue 

```
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.2.1
Node: 14.15.4
OS: linux x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.1
@angular-devkit/build-angular   0.1002.1
@angular-devkit/core            10.2.1
@angular-devkit/schematics      11.1.2
@angular/cdk                    7.3.7
@angular/cli                    10.2.1
@angular/material               7.3.7
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.0.5
```
```

{
  "name": "dashboard-angular",
  "version": "2.2.6",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular-devkit/build-angular": "~0.1002.1",
    "@angular/animations": "^10.2.4",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^10.2.4",
    "@angular/compiler": "^10.2.4",
    "@angular/core": "^10.2.4",
    "@angular/forms": "^10.2.4",
    "@angular/localize": "^10.2.4",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "^10.2.4",
    "@angular/platform-browser-dynamic": "^10.2.4",
    "@angular/router": "^10.2.4",
    "@angular/service-worker": "^10.2.4",
    "@covalent/code-editor": "^2.1.1",
    "@covalent/core": "^3.1.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@w11k/angular-sticky-things": "^1.2.3",
    "angular-datatables": "^11.1.1",
    "angular-dropdown": "^0.5.5",
    "angular-font-awesome": "^3.1.2",
    "angular-gridster2": "^9.3.4",
    "angular-highcharts": "^7.2.0",
    "angular-notifier": "^4.1.2",
    "angular2-query-builder": "0.4.2",
    "body-parser": "^1.19.0",
    "bootstrap": "^4.3.1",
    "cdk-drag-scroll": "0.0.4",
    "chokidar": "^3.5.1",
    "ckeditor5-simple-upload": "^1.0.7",
    "core-js": "^2.6.10",
    "core-util-is": "^1.0.2",
    "cors": "^2.8.5",
    "datatables.net-dt": "^1.10.20",
    "date-fns": "^1.30.1",
    "express": "^4.17.1",
    "font-awesome": "^4.7.0",
    "formBuilder": "^3.2.5",
    "highcharts": "^7.2.0",
    "jquery": "^3.5.1",
    "material-design-icons": "^3.0.1",
    "moment-timezone": "^0.5.27",
    "mongoose": "^5.7.5",
    "ng-animate-scroll": "^7.1.0",
    "ng-bootstrap-form-validation": "^9.0.0",
    "ng-pick-datetime": "^7.0.0",
    "ng-select2": "1.1.2",
    "ng2-ace-editor": "^0.3.7",
    "ng5-slider": "^1.2.4",
    "ngx-bootstrap": "^6.2.0",
    "ngx-contextmenu": "^5.2.0",
    "ngx-image-cropper": "^1.5.1",
    "ngx-json-viewer": "^2.4.0",
    "ngx-lightbox": "^2.1.1",
    "ngx-monaco-editor": "^8.1.1",
    "ngx-spinner": "^9.0.2",
    "ngx-summernote": "^0.7.8",
    "node-geocoder": "3.25.0",
    "node-sass": "^5.0.0",
    "nyc": "^15.1.0",
    "popper.js": "^1.16.0",
    "reconnecting-websocket": "^4.4.0",
    "rrule": "^2.6.2",
    "rxjs": "6.6.3",
    "rxjs-compat": "6.3.3",
    "select2": "^4.0.13",
    "socket.io-client": "^2.3.0",
    "summernote": "^0.8.18",
    "tslib": "^2.0.0",
    "webpack-dev-server": "^3.8.2",
    "xlsx": "^0.16.7",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular/cli": "^10.2.1",
    "@angular/compiler-cli": "^10.2.4",
    "@angular/language-service": "^10.2.4",
    "@types/datatables.net": "^1.10.18",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "^2.0.8",
    "@types/jquery": "^3.3.31",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "4.0.5"
  },
  "description": "This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 7.3.1.",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC"
}

```

```

> dashboard-angular@2.2.6 start /home/tabhotel/tabhotel_dev/dashboard-angular
> ng serve

Warning: Entry point 'angular-highcharts' contains deep imports into '/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/highcharts/highmaps', '/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/highcharts/highstock'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point 'ng2-ace-editor' contains deep imports into '/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/brace/theme/monokai'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point 'ng5-slider' contains deep imports into '/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/ng5-slider/node_modules/rxjs/operators'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Compiling angular-font-awesome : es2015 as esm2015
Compiling angular-notifier : es2015 as esm2015
Compiling angular2-query-builder : module as esm5
Compiling ng-pick-datetime : module as esm5
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: LocationStrategy, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: PlatformLocation, },
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [APP_BASE_HREF,] },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: PlatformLocation, },
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [APP_BASE_HREF,] },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: IterableDiffers, },
    { type: KeyValueDiffers, },
    { type: ElementRef, },
    { type: Renderer, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
    { type: TemplateRef, },
    { type: IterableDiffers, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
    { type: TemplateRef, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
    { type: TemplateRef, },
    { type: NgSwitch, decorators: [{ type: Host },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
    { type: TemplateRef, },
    { type: NgSwitch, decorators: [{ type: Host },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: NgLocalization, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Attribute, args: ['ngPluralCase',] },] },
    { type: TemplateRef, },
    { type: ViewContainerRef, },
    { type: NgPlural, decorators: [{ type: Host },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: KeyValueDiffers, },
    { type: ElementRef, },
    { type: Renderer, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ChangeDetectorRef, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: NgLocalization, },
]; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Error: Error on worker #1: Error: Failed to find exported name of node (CommonModule = (function () {
    function CommonModule() {
    }
    return CommonModule;
}())) in '/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/angular-font-awesome/dist/angular-font-awesome.js'.
    at Object.findExportedNameOfNode (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/find_export.js:36:19)
    at LogicalProjectStrategy.emit (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:233:38)
    at ReferenceEmitter.emit (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:249:31)
    at NgModuleDecoratorHandler._toR3Reference (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:418:31)
    at /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:195:72
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:195:38)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:346:40)
    at analyze (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:298:58)
    at ClusterMaster.onWorkerMessage (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:124:57)
    at /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:113:16)
    at EventEmitter.<anonymous> (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (events.js:315:20)
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-rSFxKk/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! dashboard-angular@2.2.6 start: `ng serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the dashboard-angular@2.2.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tabhotel/.npm/_logs/2021-02-04T09_21_31_444Z-debug.log
tabhotel@tabhotel:~/tabhotel_dev/dashboard-angular$ (node:91120) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at process.target._send (internal/child_process.js:832:20)
    at process.target.send (internal/child_process.js:703:19)
    at /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:51:21
    at new Promise (<anonymous>)
    at Object.exports.sendMessageToMaster (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:46:16)
    at /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:104:66
    at step (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:124:57)
    at rejected (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:91120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:91120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:91127) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at process.target._send (internal/child_process.js:832:20)
    at process.target.send (internal/child_process.js:703:19)
    at /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:51:21
    at new Promise (<anonymous>)
    at Object.exports.sendMessageToMaster (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:46:16)
    at /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:104:66
    at step (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:124:57)
    at rejected (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:91127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:91127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:91134) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at process.target._send (internal/child_process.js:832:20)
    at process.target.send (internal/child_process.js:703:19)
    at /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:51:21
    at new Promise (<anonymous>)
    at Object.exports.sendMessageToMaster (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:46:16)
    at /home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:104:66
    at step (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:124:57)
    at rejected (/home/tabhotel/tabhotel_dev/dashboard-angular/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:91134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:91134) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by JoostK** [comment]
`angular-font-awesome` is embedding `@angular/core` `4.1.3` [into its main bundle](https://unpkg.com/browse/angular-font-awesome@3.1.2/dist/angular-font-awesome.js), which is definitely a problem.

Please reach out to the authors of `angular-font-awesome` for them to publish a new build that is targeting newer versions of Angular, or migrate away from that dependency.

I don't think this is otherwise actionable for us, so I'll go ahead and close this.
