### ISSUE TITLE
outerHTML binding update causes error

### ISSUE THREAD

**Issue by BerenOneHand** [angular/angular#41131]
### Description
The [outerHTML] binding shown below works when rendering, however when the value is updated it results in a console error.
core.js:6006 ERROR DOMException: Failed to set the 'outerHTML' property on 'Element': This element has no parent node.

<ng-container *ngFor="let m of models; index as i;">
  <span class="textbox-textfield" [outerHTML]="m.text"></span>
</ng-container>

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-ab1fn1?file=src/app/app.component.ts

## 🔥 Exception or Error
<pre><code>
preview-c9f765cddfc622204e06b.js:1 ERROR DOMException: Failed to set the 'outerHTML' property on 'Element': This element has no parent node.
    at EmulatedEncapsulationDomRenderer2.DefaultDomRenderer2.setProperty (https://angular-ivy-ab1fn1.stackblitz.io/turbo_modules/@angular/platform-browser@11.0.8/__ivy_ngcc__/bundles/platform-browser.umd.js:1069:22)
    at elementPropertyInternal (https://angular-ivy-ab1fn1.stackblitz.io/turbo_modules/@angular/core@11.0.8/__ivy_ngcc__/bundles/core.umd.js:10235:26)
    at Object.ɵɵproperty (https://angular-ivy-ab1fn1.stackblitz.io/turbo_modules/@angular/core@11.0.8/__ivy_ngcc__/bundles/core.umd.js:15010:13)
    at AppComponent_ng_container_2_Template (https://angular-ivy-ab1fn1.stackblitz.io/~/src/app/app.component.ts:16:8)
    at executeTemplate (https://angular-ivy-ab1fn1.stackblitz.io/turbo_modules/@angular/core@11.0.8/__ivy_ngcc__/bundles/core.umd.js:9809:13)
    at refreshView (https://angular-ivy-ab1fn1.stackblitz.io/turbo_modules/@angular/core@11.0.8/__ivy_ngcc__/bundles/core.umd.js:9678:17)
    at refreshEmbeddedViews (https://angular-ivy-ab1fn1.stackblitz.io/turbo_modules/@angular/core@11.0.8/__ivy_ngcc__/bundles/core.umd.js:10800:21)
    at refreshView (https://angular-ivy-ab1fn1.stackblitz.io/turbo_modules/@angular/core@11.0.8/__ivy_ngcc__/bundles/core.umd.js:9702:13)
    at refreshComponent (https://angular-ivy-ab1fn1.stackblitz.io/turbo_modules/@angular/core@11.0.8/__ivy_ngcc__/bundles/core.umd.js:10846:17)
    at refreshChildComponents (https://angular-ivy-ab1fn1.stackblitz.io/turbo_modules/@angular/core@11.0.8/__ivy_ngcc__/bundles/core.umd.js:9475:13)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
This is kind of expected to me... the initial binding replaces the `span` element, so its DOM node is detached from the parent. Angular will still be updating this detached node, though, causing a subsequent update to fail.

**Comment by BerenOneHand** [comment]
The workaround is to wrap the ngfor in an element that forces re-rendering:
https://stackblitz.com/edit/angular-ivy-qih5zb?file=src%2Fapp%2Fapp.component.ts

**Comment by jelbourn** [comment]
Angular doesn't support binding to `outerHTML` like this because `outerHTML` replaces the element upon which it is set.

**Comment by BerenOneHand** [comment]
Is there any alternative to putting plain HTML into an element without it having a container? ( such as the example on stackblitz above) 
If possible something like a {{}} tag that outputs pure html instead of text? or an <ng-container [innerHTML]></ng-container>
?
