### ISSUE TITLE
After updating Angular from 8 to 11 got error in SSR: "Error: inject() must be called from an injection context"

### ISSUE THREAD

**Issue by TrueOleg** [angular/angular#41151]
# 🐞 bug report

### Description

I suppose this happens because of Angular Ivy compiler.  Application worked correctly in SSR mode in Angular 8. But after update Angular  version to 11 - application works only in serve mode. When I built it and launched "server.js" file, I have got the error "Error: inject() must be called from an injection context"

## 🔥 Exception or Error
<pre><code>
Error: inject() must be called from an injection context
    at injectInjectorOnly (/Users/olegzaichkin/Documents/Projects/awarenow/awarenow_v2/dist/server.js:185726:15)
    at Module.ɵɵinject (/Users/olegzaichkin/Documents/Projects/awarenow/awarenow_v2/dist/server.js:185736:61)
    at Object.RouterModule_Factory [as factory] (/Users/olegzaichkin/Documents/Projects/awarenow/awarenow_v2/dist/server.js:349504:215)
    at R3Injector.hydrate (/Users/olegzaichkin/Documents/Projects/awarenow/awarenow_v2/dist/server.js:15683:35)
    at R3Injector.get (/Users/olegzaichkin/Documents/Projects/awarenow/awarenow_v2/dist/server.js:15504:33)
    at /Users/olegzaichkin/Documents/Projects/awarenow/awarenow_v2/dist/server.js:15541:55
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (/Users/olegzaichkin/Documents/Projects/awarenow/awarenow_v2/dist/server.js:15541:31)
    at new NgModuleRef$1 (/Users/olegzaichkin/Documents/Projects/awarenow/awarenow_v2/dist/server.js:29572:26)
    at NgModuleFactory$1.create (/Users/olegzaichkin/Documents/Projects/awarenow/awarenow_v2/dist/server.js:29626:16)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect                  0.1101.4
@angular-devkit/build-angular              0.1101.4
@angular-devkit/core                       11.2.3
@angular-devkit/schematics                 11.2.3
@angular/cdk                               11.2.3
@angular/cli                               11.2.3
@angular/http                              7.2.16
@nguniversal/common                        11.2.1
@nguniversal/express-engine                11.2.1
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        11.2.3
@schematics/update                         0.1102.3
rxjs                                       6.6.6
typescript                                 4.0.7

</code></pre>

**Anything else relevant?**
I tried to debug server.js to find a place where error was happening and I got the following:
![err](https://user-images.githubusercontent.com/34263861/110611599-6ab61380-81a0-11eb-97b6-5fac6d1bb611.png)

**Comment by alan-agius4** [comment]
It also appears that you are using packages which are no longer supported and are not guaranteed to work with Angular 11.

- @nguniversal/module-map-ngfactory-loader   8.2.6
- @angular/http                              7.2.16

Moreover, while you are using Angular 11, you are still generating `server.js`, this probably means that you didn't update Angular Universal using `ng update` and hence ended up in a broken state.


Try running the below command
```
ng update @nguniversal/express-engine --migrate-only --from=8 --to 11
```
