### ISSUE TITLE
devcontainer is not working from this repository. 🐞 

### ISSUE THREAD

**Issue by anirugu** [angular/angular#41361]
# 🐞 bug report

Today I try to create a container by rename the file but it's failed to do so. Here is the logs. Pleas look 

Configuration starting...
2021-03-29T05:02:49: $ nvidia-smi 
2021-03-29T05:02:49: @microsoft/vscode-dev-containers-cli 0.0.23.
2021-03-29T05:02:50: Start: Resolving Remote
2021-03-29T05:02:50: $ docker ps -q -a --filter label=Type=codespaces
2021-03-29T05:02:50: $ docker build -f /var/lib/docker/codespacemount/workspace/angular/.devcontainer/Dockerfile -t vsc-angular-3d5c00cb55cf9e954264fb62e24ec400 /var/lib/docker/codespacemount/workspace/angular/.devcontainer
2021-03-29T05:02:50: Sending build context to Docker daemon   7.68kB
2021-03-29T05:02:50: 
2021-03-29T05:02:50: 
2021-03-29T05:02:50: Error response from daemon: dockerfile parse error line 2: FROM requires either one or three arguments
2021-03-29T05:02:50: Failed to create container.Error: Error: Command failed: docker build -f /var/lib/docker/codespacemount/workspace/angular/.devcontainer/Dockerfile -t vsc-angular-3d5c00cb55cf9e954264fb62e24ec400 /var/lib/docker/codespacemount/workspace/angular/.devcontainer     at E$ (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:247:11834)     at async v$ (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:247:9668)     at async D0 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:247:6418)     at async zq (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:228:7469)     at async zA (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:257:6578)     at async k2 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:257:14088)     at async T2 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:257:13832) {"outcome":"error","message":"Command failed: docker build -f /var/lib/docker/codespacemount/workspace/angular/.devcontainer/Dockerfile -t vsc-angular-3d5c00cb55cf9e954264fb62e24ec400 /var/lib/docker/codespacemount/workspace/angular/.devcontainer","description":"An error occurred building the image.","backgroundProcessPID":19268}Error Code: 1302Container creation failed.Creating recovery container
2021-03-29T05:02:50: $ nvidia-smi 
2021-03-29T05:02:50:

**Comment by jelbourn** [comment]
@anirugu it's not really clear what you're trying to do here. Feel free to open a new issue that follows the issue template.

**Comment by gkalpak** [comment]
@anirugu is referring to using VSCode's remote development using the files in [.devcontainer/][1].
I am working on a fix.

[1]: https://github.com/angular/angular/tree/master/.devcontainer

**Comment by flash-me** [comment]
https://docs.docker.com/engine/reference/builder/#format

> Docker treats lines that begin with # as a comment, unless the line is a valid parser directive. A # marker anywhere else in a line is treated as an argument.

Someone may have a look at line 2 and 19 in https://github.com/angular/angular/blob/master/.devcontainer/recommended-Dockerfile :p 

cheers
flash ⚡

**Comment by anirugu** [comment]
@gkalpak  Thanks for your PR, Is your PR merged, I just check now and not able to build. I see some changes in file for devcontainer.

**Comment by gkalpak** [comment]
Can you try with the latest version from master and if you get any errors post them here?

**Comment by gkalpak** [comment]
Oh, wait. Actually, you should wait for #41396 to be merged first (or grab the changes from there) 😅
