### ISSUE TITLE
Migration failed from Angular 8 universal to 9 Universal Version : require.resolve is not a function

### ISSUE THREAD

**Issue by ryan1509** [angular/angular#41532]
![image](https://user-images.githubusercontent.com/14803182/114193207-e8ba3580-996b-11eb-836e-a74d5f8c114d.png)

**Comment by ryan1509** [comment]
digging angular-errors , I found the below error : 
```
[error] TypeError: require.resolve is not a function
    at SchematicImpl.<anonymous> (E:\B2C-NG-9\b2c\node_modules\@nguniversal\express-engine\schematics\migrations\update-9\index.js:42:44)
    at Generator.next (<anonymous>)
    at E:\B2C-NG-9\b2c\node_modules\@nguniversal\express-engine\schematics\migrations\update-9\index.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (E:\B2C-NG-9\b2c\node_modules\@nguniversal\express-engine\schematics\migrations\update-9\index.js:16:12)
    at E:\B2C-NG-9\b2c\node_modules\@nguniversal\express-engine\schematics\migrations\update-9\index.js:38:26
    at MergeMapSubscriber.project (C:\Users\YOURTR~1\AppData\Local\Temp\angular-cli-packages-YWauXm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\rules\call.js:75:24)
    at MergeMapSubscriber._tryNext (C:\Users\YOURTR~1\AppData\Local\Temp\angular-cli-packages-YWauXm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:67:27)
    at MergeMapSubscriber._next (C:\Users\YOURTR~1\AppData\Local\Temp\angular-cli-packages-YWauXm\node_modules\@angular\cli\node_modules\rxjs\internal\operators\mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\YOURTR~1\AppData\Local\Temp\angular-cli-packages-YWauXm\node_modules\@angular\cli\node_modules\rxjs\internal\Subscriber.js:66:18)
```

**Comment by zarend** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).
