### ISSUE TITLE
$localize function undefined although imported in polyfills.ts

### ISSUE THREAD

**Issue by jepetko** [angular/angular#42017]
# Bug Report

### Affected Package

```
@angular/localize
```

### Description

I added the localize module using:

```
ng add @angular/localize
```

This also adapted the polyfills by adding this lines:

```
/***************************************************************************************************
 * Load `$localize` onto the global scope - used if i18n tags appear in Angular templates.
 */
import '@angular/localize/init';
```

While the processing of `message.xlf` for the particular language works, the global function `$localize` is:

```
function () {
        throw new Error('It looks like your application or one of its dependencies is using i18n.\n' +
            'Angular 9 introduced a global `$localize()` function that needs to be loaded.\n' +
            'Please run `ng add @angular/localize` from the Angular CLI.\n' +
            '(For non-CLI projects, add `import \'@angular/localize/init\';` to your `polyfills.ts` file.\n' +
            'For server-side rendering applications add the import to your `main.server.ts` file.)');
    };
```
(because it is undefined and falls back to a function throwing an error).

Since it refers to `@angular/localize/init`, it should basically recognize typings from `localize/init/index.d.ts`. `@angular/localize/init/package.json` specifies for fesm2015 the script:

```
"fesm2015": "../fesm2015/init.js",
```

which finally contains the implementation:

```
const __globalThis = typeof globalThis !== 'undefined' && globalThis;
// ...
const $localize = function (messageParts, ...expressions) {
// ...
}
// ...
_global.$localize = $localize;
```

However, the script is even not loaded (neither from fesm2015 nor from bundles etc.). On the contrary, if I put

```
import * as mod from "@angular/localize";
```

into `polyfills.ts` then `mod` contains the ES module from `@angular/localize/fesm2015/localize.js` with the following methods:
* clearTranslations
* loadTranslations
...
* ɵtranslate:

To me it looks like the secondary entry point is not working (**this is just an assumption and might be wrong**). 

The postinstall command looks like this:

```
"postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",
```

It needs to be mentioned that I tried out couple of fixes:

1.  I followed the recommendation from here: https://angular.io/guide/ivy 

> "Don't use --create-ivy-entry-points as this will cause Node not to resolve the Ivy version of the packages correctly."

and changed the postinstall command:

```
"postinstall": "ngcc --loglevel debug --error-on-failed-entry-point false",
```

It compiles the packages until it hits @ngxs and @ngneat related repos, respectively, and then fails with:

```
Compiling @ngx-translate/core : fesm5 as esm5
Debug: Stopping 4 workers...
Debug: Attempting to remove lock-file at C:/data/workspaces/my-project/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: PIDs match (3536), so removing C:/data/workspaces/my-project/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Error: Error on worker #3: RangeError: Maximum call stack size exceeded
    at resolveNameHelper (C:\data\workspaces\my-project\node_modules\typescript\lib\typescript.js:43778:35)
    at resolveName (C:\data\workspaces\my-project\node_modules\typescript\lib\typescript.js:43776:20)
    at resolveEntityName (C:\data\workspaces\my-project\node_modules\typescript\lib\typescript.js:44999:42)
    at getSymbolOfNameOrPropertyAccessExpression 
```
	
2. I also created ngcc.config.js in the project. 

```
module.exports = {
  packages: {
    '@angular/localize': {
      entryPoints: {
        '.': {
          typings: './localize.d.ts',
          main: './fesm2015/localize.js',
        },
        './init': {
          typings: './init.d.ts',
          main: './fesm2015/init.js',
        },
      },
    },
  },
};
```

Altough `ngcc` fails later on (see the 1. point), it manages to create `*.__ivy_ngcc_bak` files alongside of the actual js files. However, in the application the `$localize` function is still:

```
function () {
        throw new Error('It looks like...)');
    };	
```

## Exception or Error

1. `$localize` undefined after execution of `import @angular/localize/init` in `polyfills.ts`
2. when **not** using `--create-ivy-entry-points`,  the command `ngcc` fails with:

```
Compiling @ngx-translate/core : fesm5 as esm5
Debug: Stopping 4 workers...
Debug: Attempting to remove lock-file at C:/data/workspaces/my-project/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Debug: PIDs match (3536), so removing C:/data/workspaces/my-project/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.
Error: Error on worker #3: RangeError: Maximum call stack size exceeded
    at resolveNameHelper (C:\data\workspaces\my-project\node_modules\typescript\lib\typescript.js:43778:35)
    at resolveName (C:\data\workspaces\my-project\node_modules\typescript\lib\typescript.js:43776:20)
    at resolveEntityName (C:\data\workspaces\my-project\node_modules\typescript\lib\typescript.js:44999:42)
    at getSymbolOfNameOrPropertyAccessExpression (C:\data\workspaces\my-project\node_modules\typescript\lib\typescript.js:75600:28)
    at getSymbolAtLocation (C:\data\workspaces\my-project\node_modules\typescript\lib\typescript.js:75665:28)
    at Object.getSymbolAtLocation (C:\data\workspaces\my-project\node_modules\typescript\lib\typescript.js:42656:31)
    at UmdReflectionHost.findUmdImportParameter (C:\data\workspaces\my-project\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:341:45)
    at UmdReflectionHost.getImportPathFromParameter (C:\data\workspaces\my-project\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:424:40)
    at UmdReflectionHost.getUmdModuleDeclaration (C:\data\workspaces\my-project\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:412:35)
    at UmdReflectionHost.getDeclarationOfIdentifier (C:\data\workspaces\my-project\node_modules\@angular\compiler-cli\ngcc\src\host\umd_host.js:54:70)
    at ClusterMaster.onWorkerMessage (C:\data\workspaces\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
    at C:\data\workspaces\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (C:\data\workspaces\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (C:\data\workspaces\my-project\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\data\workspaces\my-project\node_modules\tslib\tslib.js:124:57)
    at C:\data\workspaces\my-project\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\data\workspaces\my-project\node_modules\tslib\tslib.js:113:16)
    at EventEmitter.<anonymous> (C:\data\workspaces\my-project\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
    at EventEmitter.emit (events.js:189:13)
```

## Your Environment

**The project is using AOT.**

```
C:\data\workspaces\my-project>npm -v
6.4.1

C:\data\workspaces\my-project>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.5
Node: 10.15.3
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    9.2.4
@angular/material               9.2.4
@schematics/angular             11.0.7
@schematics/update              0.1100.5
rxjs                            6.5.5
typescript                      4.0.5
```

**Comment by jepetko** [comment]
happy to read this, @petebacondarwin.

This is my `angular.json`:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "projects": {
    "my-project": {
      "projectType": "application",
	  ...
	  
      "i18n": {
        "sourceLocale": "en-US",
        "locales": {
          "en": "apps/my-project/src/locale/messages.en.xlf"
        }
      },


...

         // is this the catch ? 
          "configurations": {
            "en": {
              "localize": ["en"]
            },
			
...

        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
		  ...
            "en": {
              "browserTarget": "my-project:build:en"
            }
          }
...
```			
	
The `serve` command:

```
"start": "ng serve --proxy-config proxy.config.js --configuration=en",			
```

**Comment by petebacondarwin** [comment]
Indeed I think that:

```
         // is this the catch ? 
          "configurations": {
            "en": {
              "localize": ["en"]
            },
```

This is your problem.

By adding that config you are telling the CLI to replace all `$localize` tagged strings with their translations. So it then also removes `$localize` itself.

**Comment by jepetko** [comment]
Awesome. 👍

Now, the angular.json contains only:

```
      "i18n": {
        "sourceLocale": "en-US",
        "locales": {
          "en": "apps/my-project/src/locale/messages.en.xlf"
        }
      },
```

(of course, I also removed `--configuration=en` from package.json)

The `$localize` function is present (indeed, loaded from the `@angular/localize/fesm2015/init.js` 👍), however, the static translation is no longer executed, meaning that every HTML tag with `i18n` marker is not translated anymore using `apps/my-project/src/locale/messages.en.xlf`. How can I achieve that the application is translated using the prepared (aka default) messages which can be still overridden at runtime? I'm confused...😕 

I also read in the documentation of `$localize` (https://angular.io/api/localize) that it survives minification and thus can be used at runtime:

> This $localize identifier can be a real function that can do the translation at runtime, in the browser. But, significantly, it is also a global identifier that survives minification. This means it can act simply as a marker in the code that a static post-processing tool can use to replace the original text with translated text before the code is deployed.

I did not find any hint to function "erasure" when using `localize: true` or any other `localize` usages (such as those pointing to a language as it was in my case). Can you provide the documentation link?

Thank you very much.

**Comment by petebacondarwin** [comment]
Compile time and runtime translation are mutually exclusive.

If you do compile time translation then, by definition, every instance of `$localize` will be translated and removed from your code at compile time. For example the following:

```
$localize `hello ${name}!`
```

would be converted to (e.g. french):

```
"bonjour " + name + "!"
```

So it is not then possible to have some `$localize` tagged strings that are left behind for runtime translation.

**Comment by jepetko** [comment]
Thank you for the confirmation that this is the intended behavior.

The solution for using runtime translations appears to be:

* configure `APP_INITIALIZER` using a function:

```js
const appInitializerFn = (configService: EnvironmentConfigService) => {
  return (): Promise<EnvironmentConfigModel> => {

    // 1. take the opportunity to load a file (or multiple files) at runtime configured in configService
    // 2. fill loadTranslations using the loaded files
    loadTranslations({
      'contact-form--contact-us': 'Kontaktiere uns',
      'contact-form--label-lastName': 'Mein Nachname ist {$INTERPOLATION} :-)',
    });

    return configService.loadEnvironmentConfig();
  };
};
```

* provide 1st level translations in the template:

```html
<!-- 1st level translation (template value) still kept as there is no runtime translation for that. -->
<div>
	<label for="firstName" i18n>
	  Name
	</label>
	<input class="uk-input" id="firstName" type="text" formControlName="firstName" />
</div>
```

Result: Name

```html
<!-- 1st level translation overridden by runtime translations (see loadTranslations above) -->
<div>
	<label for="lastName" i18n="@@contact-form--label-lastName">
		Last name is {{contactForm?.get('lastName').value}}.
	</label>
	<input id="lastName" type="text" formControlName="lastName" />
</div>
```

Result: Mein Nachname ist WHATEVER-YOU-PUT-IN-INPUT-FIELD :-)

A good starting point to learn more about the formatting of the TargetMessage is the unit test:
https://github.com/angular/angular/blob/9b4b281c5223084834019664fbe5248521caadae/packages/core/test/acceptance/i18n_spec.ts
