### ISSUE TITLE
ng build not working after v12 upgrade

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular#42091]
# Bug Report

### Affected Package
@angular/cli

### Is this a regression?
yes

### Description
ng build fails with error below

## Minimal Reproduction

 https://stackblitz.com/...

## Exception or Error
```
c:\development\SDS\core-ui-v3>ng build
"BuildCustomWebpackBrowserSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
√ Browser application bundle generation complete.

Error: ./apps/enerest-v4/src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getNextProgram is not a function
    at c:\development\SDS\core-ui-v3\node_modules\@ngtools\webpack\src\ivy\plugin.js:390:61
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ multi ./apps/enerest-v4/src/main.ts main[0]

Error: ./apps/enerest-v4/src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getNextProgram is not a function
    at c:\development\SDS\core-ui-v3\node_modules\@ngtools\webpack\src\ivy\plugin.js:390:61
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ multi ./apps/enerest-v4/src/polyfills.ts polyfills[0]

Error: ./apps/enerest-v4/src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getNextProgram is not a function
    at c:\development\SDS\core-ui-v3\node_modules\@ngtools\webpack\src\ivy\plugin.js:390:61
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./apps/enerest-v4/src/main.ts

Error: ./apps/enerest-v4/src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getNextProgram is not a function
    at c:\development\SDS\core-ui-v3\node_modules\@ngtools\webpack\src\ivy\plugin.js:390:61
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./apps/enerest-v4/src/polyfills.ts

```

## Your Environment

**Angular Version:**
<pre><code>

c:\development\SDS\core-ui-v3>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.0
Node: 14.16.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            11.2.2
@angular-devkit/schematics      12.0.0
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             12.0.0
rxjs                            6.6.3
typescript                      4.2.4

</code></pre>

**Anything else relevant?**
upgrade was made successfully by nrwl NX migrate tool.

**Comment by petebacondarwin** [comment]
May be related to https://github.com/angular/angular/commit/852b5e366e2df104cd2b5a93abf683f7bb01f682

Can you check that the compiler-cli is definitely updated?

**Comment by GeorgeKnap** [comment]
@petebacondarwin  looks good to me
```
    "@angular/compiler-cli": {
      "version": "12.0.0",
      "resolved": "https://registry.npmjs.org/@angular/compiler-cli/-/compiler-cli-12.0.0.tgz",
      "integrity": "sha512-6cBocQd/Umi8gVI6Jo8VsyvHuRjDO4TrFFUkbVwNAG9FacXEFP0zYABT5ywe2lVkUxs5e8WyDqvDf7fxr7CI4Q==",
      "dev": true,
      "requires": {
        "@babel/core": "^7.8.6",
        "@babel/types": "^7.8.6",
        "canonical-path": "1.0.0",
        "chokidar": "^3.0.0",
        "convert-source-map": "^1.5.1",
        "dependency-graph": "^0.11.0",
        "magic-string": "^0.25.0",
        "minimist": "^1.2.0",
        "reflect-metadata": "^0.1.2",
        "semver": "^7.0.0",
        "source-map": "^0.6.1",
        "sourcemap-codec": "^1.4.8",
        "tslib": "^2.1.0",
        "yargs": "^16.2.0"
      },
      "dependencies": { ...}
}
```

**Comment by GeorgeKnap** [comment]
Turning Ivy off removed the errors. But that's not a solution.

I think I'll first wait for upgrade of custom webpack builder.
https://github.com/nrwl/nx/issues/5655#issuecomment-841135635
