### ISSUE TITLE
Issue during update existing project on Angular 11 to version 12 

### ISSUE THREAD

**Issue by yuriy-donskikh** [angular/angular#42163]
# Bug Report

### Issue
During execution of:
<pre><code>
ng update @angular/core@12 @angular/cli@12
</code></pre>
Get an exception:
<pre><code>
An unhandled exception occurred: The "path" argument must be of type string. Received undefined
See "C:\Users\YX5870~1.DON\AppData\Local\Temp\ng-0ukmwd\angular-errors.log" for further details.
</code></pre>
The context of file:
<pre><code>
[error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:154:9)
    at isInside (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:192:35)
    at C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:202:28
    at Array.filter (<anonymous>)
    at findProjectByPath (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:202:10)
    at getProjectByCwd (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:231:21)
    at Object.getConfiguredPackageManager (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:256:25)
    at async Object.getPackageManager (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\package-manager.js:35:27)
    at async UpdateCommand.initialize (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\commands\update-impl.js:46:31)
</code></pre>

### Environment
**Angular version**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: <error>
OS: win32 ia32

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            12.0.0 (cli-only)
@angular-devkit/schematics      12.0.0 (cli-only)
@angular/cli                    12.0.0 (cli-only)
@schematics/angular             12.0.0 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      <error>
</code></pre>

**package.json**
<pre><code>
{
  "name": "Res",
  "version": "3.1.20",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "increase-version": "node ./build/version-increment.js",
    "post-build": "node ./build/post-build.js",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/schematics": "^11.1.0",
    "@angular/animations": "11.1.0",
    "@angular/cdk": "^11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "11.1.0",
    "@angular/core": "11.1.0",
    "@angular/forms": "11.1.0",
    "@angular/localize": "^11.1.0",
    "@angular/platform-browser": "11.1.0",
    "@angular/platform-browser-dynamic": "11.1.0",
    "@angular/router": "11.1.0",
    "@angularclass/hmr": "^3.0.0",
    "@ng-bootstrap/ng-bootstrap": "^9.0.1",
    "@ng-select/ng-select": "5.1.0",
    "@ngx-progressbar/core": "^5.3.2",
    "@ngx-progressbar/http": "^5.3.2",
    "@ngx-progressbar/router": "^5.3.2",
    "angular-in-memory-web-api": "0.11.0",
    "angular-oauth2-oidc": "10.0.3",
    "bootstrap": "4.6.0",
    "bootstrap-select": "1.13.18",
    "core-js": "3.8.3",
    "hammerjs": "2.0.8",
    "jquery": "3.5.1",
    "jwt-decode": "3.1.2",
    "lodash-es": "^4.17.20",
    "ng-multiselect-dropdown": "^0.2.14",
    "ngx-scrollbar": "^7.5.3",
    "ngx-toastr": "13.2.0",
    "popper.js": "1.16.1",
    "rxjs": "6.6.3",
    "ts-debug": "1.3.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.0",
    "@angular-eslint/builder": "1.1.0",
    "@angular-eslint/eslint-plugin": "1.1.0",
    "@angular-eslint/eslint-plugin-template": "1.1.0",
    "@angular-eslint/schematics": "1.1.0",
    "@angular-eslint/template-parser": "1.1.0",
    "@angular/cli": "^11.1.0",
    "@angular/compiler-cli": "11.1.0",
    "@angular/language-service": "11.1.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jwt-decode": "^3.1.0",
    "@types/node": "^14.14.22",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/eslint-plugin-tslint": "^4.14.1",
    "@typescript-eslint/parser": "4.3.0",
    "codelyzer": "^6.0.0",
    "eslint": "^7.6.0",
    "eslint-plugin-deprecation": "^1.2.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "iframe-resizer": "^4.3.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~6.0.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~9.1.1",
    "typescript": "~4.1.3"
  }
}
</code></pre>

**Comment by AndrewKushnir** [comment]
It looks like the error is coming from the CLI code, so I'm transferring the issue to the CLI repo for further investigation.
