### ISSUE TITLE
Agnular 12 project fails to build with inline styles

### ISSUE THREAD

**Issue by schoel-bis** [angular/angular#42218]
# Bug Report

### Is this a regression?

Yes, I am only observing this behaviour since 12.0

### Description

`ng build` and friends fail to build if the project contains a component with inline styles.

## Minimal Reproduction

```TypeScript
@Component({
  selector: 'app-test',
  template: '<p>Lorem ipsum dolor sit amet consectetur.</p>',
  styles: ['p { text-color: blue }']
})
export class TestComponent { }
```

A test repo is here: https://github.com/schoel-bis/angular-compile-failure-with-inlinse-style

clone it, install dependencies with `npm install, then run `ng build` to trigger the issue

`src/app/test.component.ts` has the inline style.

## Exception or Error
<pre><code>
 Browser application bundle generation complete.

angular-resource:// - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: SassError: Expected newline.
  ╷
1 │ p { text-color: blue }
  │   ^
  ╵
  angular-resource: 1:3  root stylesheet
    at Object.callback (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/sass-loader/dist/index.js:54:16)
    at Worker.<anonymous> (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/@angular-devkit/build-angular/src/sass/sass-service.js:123:25)
    at Worker.emit (events.js:315:20)
    at MessagePort.<anonymous> (internal/worker.js:207:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)

angular-resource-output-1.css - Error: angular-resource-output-1.css from Css Minimizer 
/home/schoel@BISYSTEMS.local/scratch/test-app/src/app/angular-resource-output-1.css:1:1: Unknown word [angular-resource-output-1.css:1,1]
    at Input.error (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/postcss/lib/input.js:123:16)
    at Parser.unknownWord (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/postcss/lib/parser.js:518:22)
    at Parser.other (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/postcss/lib/parser.js:149:12)
    at Parser.parse (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/postcss/lib/parser.js:59:16)
    at parse (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/postcss/lib/parse.js:11:12)
    at new LazyResult (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/postcss/lib/lazy-result.js:122:16)
    at Processor.process (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/postcss/lib/processor.js:33:12)
    at cssnanoMinify (eval at transform (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/css-minimizer-webpack-plugin/dist/minify.js:34:28), <anonymous>:51:61)
    at minify (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/css-minimizer-webpack-plugin/dist/minify.js:15:32)
    at Object.transform (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/css-minimizer-webpack-plugin/dist/minify.js:35:24)
</code></pre>

In addition, this shows in the console when running `ng serve`:
<pre><code>
Object { moduleIdentifier: "/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/raw-loader/dist/cjs.js!/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[11].use[1]!/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[11].use[2]!/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[11].use[3]!angular-resource://", moduleName: "angular-resource://", message: "Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nSassError: SassError: Expected newline.\n  ╷\n1 │ p { text-color: blue }\n  │   ^\n  ╵\n  angular-resource: 1:3  root stylesheet\n    at Object.callback (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/sass-loader/dist/index.js:54:16)\n    at Worker.<anonymous> (/home/schoel@BISYSTEMS.local/scratch/test-app/node_modules/@angular-devkit/build-angular/src/sass/sass-service.js:123:25)\n    at Worker.emit (events.js:315:20)\n    at MessagePort.<anonymous> (internal/worker.js:207:53)\n    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)\n    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)" }
index.js:159
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.1
Node: 14.16.1
Package Manager: npm 6.14.12
OS: linux x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
I can confirm that the example error reproduces locally for me.

Transferring to CLI project.
