### ISSUE TITLE
Error when ng serve 

### ISSUE THREAD

**Issue by arpitBhalla** [angular/angular#42311]
An unhandled exception occurred: Class extends value undefined is not a constructor or null
```
[error] TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/arpit/Desktop/work/COVID_Resources/node_modules/webpack/lib/MainTemplate.js:56:45)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/arpit/Desktop/work/COVID_Resources/node_modules/webpack/lib/Compilation.js:24:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

Angular CLI: 11.2.12
Node: 14.16.0
OS: linux x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

This looks like a problem due to a circular import, where an `extends` clause references a class that depends on the file with the `extends` class. Please reach out on StackOverflow or Discord as this is not an Angular issue.
