### ISSUE TITLE
routerLink produces wrong routes for named outlets

### ISSUE THREAD

**Issue by max-vogler** [angular/angular#42806]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

When navigated to a sub-route `/foo`, a correct outlet route would look like `/foo(outletname:outletroute)`.

1. `<a [routerLink]="[{ outlets: { outletname: ['outletroute'] } }]">` links to `/foo/(outletname:outletroute)` when being placed in the **main** outlet. The trailing slash in `/foo/` breaks routing and throws `Cannot match any routes. URL Segment: 'foo'`.

2. When manually navigating to the correct route `/foo(outletname:outletroute)`, the above routerLink navigates to `/foo/(outletname:outletroute)(outletname:outletroute)` if the link is placed in the **main** outlet. This again fails with `Error: Cannot match any routes. URL Segment: 'foo'`.

3. When manually navigating to the correct route `/foo(outletname:outletroute)`, the above routerLink navigates to  `/foo(outletname:outletroute/(outletname:outletroute))` if the link is placed in the **second** outlet. This fails with `Cannot match any routes. URL Segment: 'outletroute'`.

Related to, but not a duplicate of #13006 (which incorrectly is marked as feature request).

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-mj7vf1?file=src/app/hello.component.ts

### Please provide the exception or error you saw

```true
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'foo'
Error: Cannot match any routes. URL Segment: 'foo'
at ApplyRedirects.noMatchError (https://angular-tpunqp.stackblitz.io/turbo_modules/@angular/router@12.1.1/bundles/router.umd.js:3124:20)
at eval (https://angular-tpunqp.stackblitz.io/turbo_modules/@angular/router@12.1.1/bundles/router.umd.js:3105:33)
at eval (https://angular-tpunqp.stackblitz.io/turbo_modules/rxjs@7.1.0/dist/cjs/internal/operators/catchError.js:13:46)
at OperatorSubscriber._this._error (https://angular-tpunqp.stackblitz.io/turbo_modules/rxjs@7.1.0/dist/cjs/internal/operators/OperatorSubscriber.js:38:21)
at OperatorSubscriber.Subscriber.error (https://angular-tpunqp.stackblitz.io/turbo_modules/rxjs@7.1.0/dist/cjs/internal/Subscriber.js:80:18)
at OperatorSubscriber.Subscriber._error (https://angular-tpunqp.stackblitz.io/turbo_modules/rxjs@7.1.0/dist/cjs/internal/Subscriber.js:104:30)
at OperatorSubscriber.Subscriber.error (https://angular-tpunqp.stackblitz.io/turbo_modules/rxjs@7.1.0/dist/cjs/internal/Subscriber.js:80:18)
at OperatorSubscriber.Subscriber._error (https://angular-tpunqp.stackblitz.io/turbo_modules/rxjs@7.1.0/dist/cjs/internal/Subscriber.js:104:30)
at OperatorSubscriber.Subscriber.error (https://angular-tpunqp.stackblitz.io/turbo_modules/rxjs@7.1.0/dist/cjs/internal/Subscriber.js:80:18)
at OperatorSubscriber.Subscriber._error (https://angular-tpunqp.stackblitz.io/turbo_modules/rxjs@7.1.0/dist/cjs/internal/Subscriber.js:104:30)
```

### Please provide the environment you discovered this bug in

```true
Angular Router: 12.1.1
```

**Comment by max-vogler** [comment]
In addition to (3), prefixing the outlet link with a `/` to `[routerLink]="[{ outlets: { outletname: ['/outletroute'] } }]`, in order to enforce a top-level link for the outlet also does not work, producing links like `/foo/(outletname:%2Foutletroute)`.

**Comment by atscott** [comment]
This is actually working correctly. Routes are always built relative to a particular place in the route tree. By default, `routerLink` uses the `ActivatedRoute` from the component. 

So in your case, you are already on `foo` and are attempting to navigate from that point in the tree to a child. This isn't specific to named outlets either. If you were to change the `routerLink` to be `[routerLink]="['xyz']"`, the generated route would be `/foo/xyz`.

Because you're trying to navigate to an outlet that lives at the root of the tree, you need to specify that in the `relativeTo` input of `routerLink`:
```
<a
      [routerLink]="[{ outlets: { outletname: ['outletroute'] } }]"
      [relativeTo]="route.root"
      >Navigate in second outlet
</a>
```
https://stackblitz.com/edit/angular-ivy-kadf7m?file=src%2Fapp%2Fapp.module.ts
