### ISSUE TITLE
Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by RoopanV** [angular/angular#42851]
### Which @angular/* package(s) are the source of the bug?

language-service

### Description

Angular Language service is crashing with below error. I recently updated my Angular from 10 to 12. If i trun on "View Legacy View Engine Service" from Setting in VScode => Extension, the error goes away.

### Please provide the exception or error you saw

```true
[Error - 7:58:54 PM] No config file for /Users/pc.name/project/src/my.component.html
[Info  - 7:58:57 PM] Enabling Ivy language service for /Users/pc.name/project/tsconfig.json.
(node:29683) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at new Set (<anonymous>)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:31758:40)
    at LocalModuleScopeRegistry.getExportedScope (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:31968:29)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:31852:42)
    at LocalModuleScopeRegistry.getExportedScope (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:31968:29)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:31852:42)
    at LocalModuleScopeRegistry.getExportedScope (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:31968:29)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:31852:42)
    at LocalModuleScopeRegistry.getExportedScope (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:31968:29)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:31852:42)
(Use `Code Helper (Renderer) --trace-warnings ...` to show where the warning was created)
(node:29683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:29683) UnhandledPromiseRejectionWarning: Error: AssertionError: Expected successfully analyzed compilation.
    at IncrementalCompilation.priorTypeCheckingResultsFor (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:30431:23)
    at TemplateTypeCheckerImpl.maybeAdoptPriorResultsForFile (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:37580:53)
    at TemplateTypeCheckerImpl.ensureShimForComponent (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:37631:18)
    at TemplateTypeCheckerImpl.getDiagnosticsForComponent (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:37502:18)
    at /Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:42226:53
    at /Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:42450:71
    at ActivePerfRecorder.inPhase (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:23996:24)
    at LanguageService.withCompilerAndPerfTracing (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:42450:50)
    at LanguageService.getSemanticDiagnostics (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:42189:25)
    at Object.getSemanticDiagnostics (/Users/pc.name/.vscode/extensions/angular.ng-template-12.1.1/node_modules/@angular/language-service/bundles/ivy.js:42633:38)
(node:29683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.1
Node: 14.17.3
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
ng-packagr                      12.1.0
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by JoostK** [comment]
This seems like a bug, but it's unclear why this happens. Could you please provide a reproduction of the issue?

**Comment by JoostK** [comment]
I suspect you have a cyclic NgModule import somewhere. The compiler should report an error for this instead of crashing so there's definitely a bug there. It would be good for you to confirm it's indeed a cyclic NgModule, but I realize it may be a bit hard to investigate where the cycle occurs.

**Comment by RoopanV** [comment]
@JoostK yes you are correct. I have cyclic module import. Thanks a lot for your time.
