### ISSUE TITLE
function return with forwardRef error with NgModule.declarations

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular#42865]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

```ts
function test() {
  // return AppComponent;
  return forwardRef(() => AppComponent);
}
@NgModule({
  declarations: [test()],
  imports: [BrowserModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```
throw error `Error: Symbol AppComponent declared in xxx/src/app/app.component.ts is not exported from @angular/core (import into xxx/src/app/app.module.ts)`

I read source code and find ngModule meta support `forwardRef` so want to try, but throw error.
And I guess becase of forwardRef is `@angular/core` ,when StaticInterpreter run in packages/compiler-cli/src/ngtsc/partial_evaluator/src/interpreter.ts(line 468),context change,so make `bestGuessOwningModule` change?

### Please provide a link to a minimal reproduction of the bug

in Description

### Please provide the exception or error you saw

```true
Error: Symbol AppComponent declared in xxx/src/app/app.component.ts is not exported from @angular/core (import into xxx/src/app/app.module.ts)
    at AbsoluteModuleStrategy.emit (xxx/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:171:23)
    at ReferenceEmitter.emit (xxx/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (xxx/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:247:18)
    at NgModuleDecoratorHandler._toR3Reference (xxx/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:527:31)
    at xxx/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:265:83
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (xxx/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:265:48)
    at TraitCompiler.analyzeTrait (xxx/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:365:40)
    at analyze (xxx/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:315:58)
    at _loop_1 (xxx/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:337:21)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.0.3
Node: 14.17.1
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@schematics/angular             12.0.3
ng-packagr                      12.0.5
rxjs                            6.5.5
typescript                      4.2.4
```

**Comment by JoostK** [comment]
I think you are right in your analysis.
