### ISSUE TITLE
ERROR in TypeError: Cannot read property 'flags' of undefined - Angular 11

### ISSUE THREAD

**Issue by jblayneyXpanxion** [angular/angular#42930]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I'm getting the Cannot read property 'flags' of undefined - Angular 11 with the following dependencies:

```
  "dependencies": {
    "@angular-architects/module-federation": "12.2.0",
    "@angular/animations": "^11.2.14",
    "@angular/cdk": "^11.2.13",
    "@angular/common": "^11.2.14",
    "@angular/compiler": "^11.2.14",
    "@angular/core": "^11.2.14",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "^11.2.14",
    "@angular/localize": "^11.2.14",
    "@angular/material": "^11.2.13",
    "@angular/platform-browser": "^11.2.14",
    "@angular/platform-browser-dynamic": "^11.2.14",
    "@angular/router": "^11.2.14",
    "@ng-bootstrap/ng-bootstrap": "9.1.3",
    "@ng-idle/core": "^10.0.0-beta.1",
    "@ng-idle/keepalive": "^10.0.0-beta.1",
    "@stomp/ng2-stompjs": "^7.2.0",
    "@types/lodash": "^4.14.168",
    "ag-grid-angular": "^25.3.0",
    "ag-grid-community": "^25.3.0",
    "ag-grid-enterprise": "^25.3.0",
    "angular-progress-bar": "^1.0.11",
    "angular2-moment": "^1.9.0",
    "bootstrap": "4.5.2",
    "classlist.js": "1.1.20150312",
    "core-js": "3.6.5",
    "if-env": "1.0.4",
    "jquery": "3.3.1",
    "moment": "^2.27.0",
    "ngx-build-plus": "^12.0.1",
    "ngx-json-viewer": "2.4.0",
    "ngx-markdown": "11.1.3",
    "ngx-skeleton-loader": "^2.9.1",
    "ngx-toast-notifications": "^1.3.0",
    "ngx-webstorage-service": "4.1.0",
    "rxjs": "6.6.0",
    "vanilla-text-mask": "^5.1.1",
    "web-animations-js": "2.3.1",
    "zone.js": "^0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.1.0",
    "@angular/cli": "~11.2.14",
    "@angular/compiler-cli": "^11.2.14",
    "@angular/language-service": "^11.2.14",
    "@rxts/rxjs-tslint": "^0.2.1",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.8",
    "@types/jquery": "^3.5.1",
    "@types/node": "^14.6.0",
    "codelyzer": "^6.0.0",
    "husky": "^4.3.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "^5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.2.1",
    "pretty-quick": "^3.1.0",
    "protractor": "^7.0.0",
    "ts-node": "~8.10.2",
    "tslint": "^6.1.3",
    "typescript": "~4.1.6",
    "webpack": "^5.0.0"
  }
}
```

full error:

```
C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:43068
if (!(currentFlow.flags & 1 /* Unreachable */)) {
^

TypeError: Cannot read property 'flags' of undefined
at checkUnreachable (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:43068:31)
at bindChildren (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:40593:17)
at bind (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:42163:21)
at bindSourceFile (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:40138:17)
at Object.bindSourceFile (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:40075:9)
at initializeTypeChecker (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:78652:20)
at Object.createTypeChecker (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:44220:9)
at Object.getTypeChecker (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:106114:79)
at new NgCompiler (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:204:79)
at Function.NgCompiler.fromTicket (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:243:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-ui@1.0.1 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project-ui@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-07-22T17_34_58_126Z-debug.log
```

### Please provide the exception or error you saw

```true
C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:43068
if (!(currentFlow.flags & 1 /* Unreachable */)) {
^

TypeError: Cannot read property 'flags' of undefined
at checkUnreachable (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:43068:31)
at bindChildren (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:40593:17)
at bind (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:42163:21)
at bindSourceFile (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:40138:17)
at Object.bindSourceFile (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:40075:9)
at initializeTypeChecker (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:78652:20)
at Object.createTypeChecker (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:44220:9)
at Object.getTypeChecker (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\typescript\lib\typescript.js:106114:79)
at new NgCompiler (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:204:79)
at Function.NgCompiler.fromTicket (C:\Users\user\Documents\Work\Dev\project3\project-master\project-ui\node_modules\@angular\compiler-cli\src\ngtsc\core\src\compiler.js:243:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project-ui@1.0.1 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project-ui@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-07-22T17_34_58_126Z-debug.log
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.2.14
Node: 14.8.0
OS: darwin x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/cdk                    11.2.13
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.2.13
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.6.0
typescript                      4.1.6
webpack                         5.40.0
```

### Anything else?

Thanks for any help :)

**Comment by JoostK** [comment]
This looks like a TypeScript bug, as the stack trace shows that the error occurs in during symbol binding which is not affected by Angular.

Can you try using the `tsc` binary `./node_modules/.bin/tsc -p tsconfig.app.json` (possibly change the path to the tsconfig file) to verify what happens if you just use TS.

**Comment by alan-agius4** [comment]
It appears that you using a mixture of version 11 and 12 packages.  `@angular-devkit/build-angular`, version `12.1.0` requires `@angular/` version 12.

Please downgrade `@angular-devkit/build-angular` to `~0.1102.9`, or update to everything to version 12 using `ng update`.

**Comment by JoostK** [comment]
Closing as there has not been any follow up.
