### ISSUE TITLE
SwUpdate#checkForUpdate promise not triggered on iOS

### ISSUE THREAD

**Issue by vcs38** [angular/angular#43036]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

Hi,

On any devices, this code on my application works well except on iOS devices where promise is never resolved nor rejected:
`this.swUpdate.checkForUpdate().then(() => { console.log('test OK'); }, () => { console.log('test KO'); });`

I can not understand why.

Thanks for your help.

### Please provide the environment you discovered this bug in

```true
Angular CLI: 9.1.12
Node: 10.16.3
OS: win32 x64

Angular: 9.1.12
... animations, cli, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/common                   9.1.13
@angular/localize                 9.1.13
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.2
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by gkalpak** [comment]
Thx for reporting this, @vcs38. I don't have direct access to an iOS device to check myself, so it would help if you provided some more info. On a device that exhibits the problem:
- What does `navigator.serviceWorker.controller` return in the DevTools Console?
- What is shown when you navigate to [/ngsw/state][1]?

[1]: https://angular.io/guide/service-worker-devops#locating-and-analyzing-debugging-information

**Comment by vcs38** [comment]
Thank youo @gkalpak for paying attention.
On other devices I can see the debug page but never on safari.
navigator.serviceWorker.controller is null only for safari browser

**Comment by naveedahmed1** [comment]
In my case the Service Worker of https://www.mustakbil.com/ is not activating the new version of my Angular app unless the browser cache is cleared (on Windows and Android both).

Below is the output of ngsw/state from Android device:

```
NGSW Debug Info:

Driver version: 12.2.0-rc.0
Driver state: EXISTING_CLIENTS_ONLY (Degraded due to failed initialization: Hash mismatch (cacheBustedFetchFromNetwork): https://www.mustakbil.com/styles.dbc7cf3b891664628fe9.css: expected 02817d65d4e9df85dab3d21324d5ec2c105fa165, got 3aa6510e4f778214e6e6958b7bcea9398baf9d8b (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://www.mustakbil.com/styles.dbc7cf3b891664628fe9.css: expected 02817d65d4e9df85dab3d21324d5ec2c105fa165, got 3aa6510e4f778214e6e6958b7bcea9398baf9d8b (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://www.mustakbil.com/combined-sw.js:1:9886)
    at Generator.next (<anonymous>)
    at fulfilled (https://www.mustakbil.com/combined-sw.js:1:175))
Latest manifest hash: 226aa816c81da75f68299ffb568a41bd7f881589
Last update check: 2s922u

=== Version 226aa816c81da75f68299ffb568a41bd7f881589 ===

Clients: 1c822e1d-9199-41f9-ad57-3cda8a91bfd9

=== Idle Task Queue ===
Last update tick: 8s736u
Last update run: 3s730u
Task queue:


Debug log:

[17s149u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://www.mustakbil.com/styles.dbc7cf3b891664628fe9.css: expected 02817d65d4e9df85dab3d21324d5ec2c105fa165, got 3aa6510e4f778214e6e6958b7bcea9398baf9d8b (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://www.mustakbil.com/styles.dbc7cf3b891664628fe9.css: expected 02817d65d4e9df85dab3d21324d5ec2c105fa165, got 3aa6510e4f778214e6e6958b7bcea9398baf9d8b (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://www.mustakbil.com/combined-sw.js:1:9886)
    at Generator.next (<anonymous>)
    at fulfilled (https://www.mustakbil.com/combined-sw.js:1:175)) Error occurred while updating to manifest 7bc1992cebed8206fd5798aaeae287c4b5038c1f
[1s976u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://www.mustakbil.com/styles.dbc7cf3b891664628fe9.css: expected 02817d65d4e9df85dab3d21324d5ec2c105fa165, got 3aa6510e4f778214e6e6958b7bcea9398baf9d8b (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://www.mustakbil.com/styles.dbc7cf3b891664628fe9.css: expected 02817d65d4e9df85dab3d21324d5ec2c105fa165, got 3aa6510e4f778214e6e6958b7bcea9398baf9d8b (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://www.mustakbil.com/combined-sw.js:1:9886)
    at Generator.next (<anonymous>)
    at fulfilled (https://www.mustakbil.com/combined-sw.js:1:175)) Error occurred while updating to manifest 7bc1992cebed8206fd5798aaeae287c4b5038c1f
```

If I refresh the page (Pull Refresh), it does load new version but when I close the browser and open website again, it loads the same old version.

**Comment by gkalpak** [comment]
> On other devices I can see the debug page but never on safari.
> `navigator.serviceWorker.controller` is `null` only for safari browser.

@vcs38, these imply that the SW is never registered.

Do you get any errors in the console?
Maybe you could try using a different [registration strategy][1] (such as `registerImmediately`) in your [ServiceWorkerModule#register()][2] call or manually register the SW (with something like `navigator.serviceWorker.register('./ngsw-worker.js')`) to see if that fixes the issue.

[1]: https://angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy
[2]: https://angular.io/api/service-worker/ServiceWorkerModule#register

**Comment by gkalpak** [comment]
Closing due to lack of response. If the problem still exists, please open a new issue.
