### ISSUE TITLE
exception occurred: NGCC failed.

### ISSUE THREAD

**Issue by TLKG** [angular/angular#43397]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

`ng serve` resulted `Error: Error on worker #1: TypeError: compiler_1.createR3ProviderExpression is not a function`. Please see details of output below

### Please provide the exception or error you saw

```true
ng serve                                                            ar\compiler-cli\src\ngtsc\transform\src
Compiling @angular/core : es2015 as esm2015
Error: Error on worker #1: TypeError: compiler_1.createR3ProviderExpression is not a function                                                                     \ngcc\src\analysis\ngcc_trait_compiler.
    at extractInjectableMetadata (c:\foler\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:140:40)                                                                                                                      -cli\ngcc\src\analysis\decoration_analy
    at InjectableDecoratorHandler.analyze (c:\foler\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:70:24)                                                                                                              cc\src\packages\transformer.js:135:57) 
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (c:\foler\node_modules\@angulc\packages\transformer.js:77:27)       ar\compiler-cli\src\ngtsc\transform\src\compilation.js:421:40)                                                                                                    \ngcc\src\execution\cluster\master.js:1
    at analyze (c:\foler\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:371:58)                                                                                                                                         ter.js:55:95
    at _loop_1 (c:\foler\node_modules\@angular\compiler-cli\src\ngtsc\transform\sc\src\execution\cluster\master.js:293:5rc\compilation.js:393:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (c:\foler\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:399:35)
    at NgccTraitCompiler.analyzeFile (c:\foler\node_modules\@angular\compiler-cli\ngcc\src\analysis\ngcc_trait_compiler.js:49:26)
    at DecorationAnalyzer.analyzeProgram (c:\foler\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:150:39)                                                                                                             \src\execution\cluster\master.js:287:32
    at Transformer.analyzeProgram (c:\foler\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:135:57)
    at Transformer.transform (c:\foler\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:77:27)
    at ClusterMaster.onWorkerMessage (c:\foler\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
    at c:\foler\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (c:\foler\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (c:\foler\node_modules\tslib\tslib.js:143:27)
    at Object.next (c:\foler\node_modules\tslib\tslib.js:124:57)
    at c:\foler\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (c:\foler\node_modules\tslib\tslib.js:113:16)
    at EventEmitter.<anonymous> (c:\foler\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
    at EventEmitter.emit (events.js:315:20)


================ complete error log below ==========================
[error] Error: NGCC failed.
    at NgccProcessor.process (c:\foler\node_modules\@ngtools\webpack\src\ngcc_processor.js:129:19)
    at c:\foler\node_modules\@ngtools\webpack\src\ivy\plugin.js:112:27
    at SyncHook.eval [as call] (eval at create (c:\foler\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (c:\foler\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (c:\foler\node_modules\webpack\lib\Compiler.js:630:30)
    at c:\foler\node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\foler\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (c:\foler\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (c:\foler\node_modules\webpack\lib\Compiler.js:662:28)
    at c:\foler\node_modules\webpack\lib\Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\foler\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (c:\foler\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at Watching._go (c:\foler\node_modules\webpack\lib\Watching.js:41:32)
    at c:\foler\node_modules\webpack\lib\Watching.js:33:9
    at Compiler.readRecords (c:\foler\node_modules\webpack\lib\Compiler.js:529:11)
    at new Watching (c:\foler\node_modules\webpack\lib\Watching.js:30:17)


=============== package.json =======================
{
  "name": "ng2-forms",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/cli": "^11.2.14",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "^11.2.7",
    "@angular/compiler-cli": "^12.2.5",
    "@angular/core": "~11.2.7",
    "@angular/forms": "~11.2.7",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "core-js": "^2.4.1",
    "jquery": "^3.1.1",
    "karma-cli": "^2.0.0",
    "karma-remap-istanbul": "^0.6.0",
    "rxjs": "^6.6.7",
    "ts-helpers": "^1.1.1",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.13",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-jasmine": "~4.0.0",
    "protractor": "~7.0.0",
    "ts-node": "8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}

==================== angular.json =======================
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "ng2-forms": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.json",
            "assets": [],
            "styles": [
              "src/styles.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js"
            ],
            "aot": true
          },
          "configurations": {
            "source": {
              "fileReplacements": [
                {
                  "replace": "src/undefined",
                  "with": "src/environments/environment.ts"
                }
              ],
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ]
            },
            "dev": {
              "fileReplacements": [
                {
                  "replace": "src/undefined",
                  "with": "src/environments/environment.ts"
                }
              ],
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ]
            },
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/undefined",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "ng2-forms:build"
          },
          "configurations": {
            "source": {
              "browserTarget": "ng2-forms:build:source"
            },
            "dev": {
              "browserTarget": "ng2-forms:build:dev"
            },
            "production": {
              "browserTarget": "ng2-forms:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "ng2-forms:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js"
            ],
            "styles": [
              "src/styles.css"
            ],
            "assets": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [],
            "exclude": []
          }
        }
      }
    },
    "ng2-forms-e2e": {
      "root": "e2e",
      "sourceRoot": "e2e",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "ng2-forms:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [],
            "exclude": []
          }
        }
      }
    }
  },
  "defaultProject": "ng2-forms",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "app",
      "style": "css"
    },
    "@schematics/angular:directive": {
      "prefix": "app"
    }
  }
}
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.2.6
Node: 14.15.5
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.6 (cli-only)
@angular-devkit/core         11.2.6 (cli-only)
@angular-devkit/schematics   11.2.6 (cli-only)
@schematics/angular          11.2.6 (cli-only)
@schematics/update           0.1102.6 (cli-only)

npm version:
{
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.15.5',
  openssl: '1.1.1i',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.18',
  zlib: '1.2.11'
}

tsc -v
Version 4.3.5
```

=================== tsconfig.json ========================
{
  "compilerOptions": {
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es2020",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es2015",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "files": [
    "main.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}

**Comment by gkalpak** [comment]
This is most likely caused by the version mismatch between the `compiler-cli` (v12.2.5) and the other Angular framework packages (v11.2.7):

```json
    ...
    "@angular/compiler": "^11.2.7",
    "@angular/compiler-cli": "^12.2.5",
    ...
```

Please, make sure that you use the exact same version for all Angular framework packages (including `@angular/compiler-cli`).
(NOTE: Angular CLI `(@angular/cli` and `@angular-devkit/*`) don't have to match exactly with the Angular framework packages.)
