### ISSUE TITLE
Angular Reactive Forms Testing not working

### ISSUE THREAD

**Issue by stimitom** [angular/angular#43400]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I ran into problems testing reactive forms in a project, so I tried to reproduce the tests for reactive forms provided in the [official documentation ](https://angular.io/guide/forms-overview#testing-reactive-forms). 
Both the Model-To-View and View-To-Model test are not working as intended. 
Am I doing something wrong or is this a bug? 

Thank you very much in advance.

**App Component**

```
import { Component } from '@angular/core';
import {FormControl} from "@angular/forms";

@Component({
  selector: 'app-root',
  template: `
    Favorite Color: <input type="text" [formControl]="favoriteColorControl">
  `,
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  constructor() {
  }

  favoriteColorControl = new FormControl('');

}
```

**App Component Specs**

```
import {ComponentFixture, TestBed} from '@angular/core/testing';
import {AppComponent} from './app.component';

describe('AppComponent', () => {
  let component: AppComponent;
  let fixture: ComponentFixture<AppComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],

    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(AppComponent);
    component = fixture.componentInstance;
  })

  it('should create the app', () => {
    expect(component).toBeTruthy();
  });

  // View To Model
  it('should update the value of the input field', () => {
    const input = fixture.nativeElement.querySelector('input');
    const event = new Event('input');

    input.value = 'Red';
    input.dispatchEvent(event);

    expect(fixture.componentInstance.favoriteColorControl.value).toEqual('Red');
  });

  // Model To View
  it('should update the value in the control', () => {
    component.favoriteColorControl.setValue('Blue');

    const input = fixture.nativeElement.querySelector('input');

    expect(input.value).toBe('Blue');
  });

});
```

### Please provide the exception or error you saw

```true
Chrome 93.0.4577.63 (Windows 10) AppComponent should update the value of the input field FAILED
        Error: Expected '' to equal 'Red'.
            at <Jasmine>
            at UserContext.<anonymous> (src/app/app.component.spec.ts:34:66)
            at ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:1)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)
Chrome 93.0.4577.63 (Windows 10) AppComponent should update the value in the control FAILED
        Error: Expected '' to be 'Blue'.
            at <Jasmine>
            at UserContext.<anonymous> (src/app/app.component.spec.ts:43:25)
            at ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:1)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)
Chrome 93.0.4577.63 (Windows 10): Executed 3 of 3 (2 FAILED) (0.272 secs / 0.227 secs)
TOTAL: 2 FAILED, 1 SUCCESS
```

### Please provide the environment you discovered this bug in

```true
"@angular/core": "~12.2.0",
"@angular/forms": "~12.2.0",

"@angular-devkit/build-angular": "~12.2.1",
"@angular/cli": "~12.2.1",
"@angular/compiler-cli": "~12.2.0",
"@types/jasmine": "~3.8.0",
"@types/node": "^12.11.1",
"jasmine-core": "~3.8.0",
"karma": "~6.3.0",
"karma-chrome-launcher": "~3.1.0",
"karma-coverage": "~2.0.3",
"karma-jasmine": "~4.0.0",
"karma-jasmine-html-reporter": "~1.7.0",
"typescript": "~4.3.5"
```

**Comment by jnizet** [comment]
Hi @stimitom 

Yes, you're doing two things wrong:
1. you're not importing `ReactingFormsModule` in your testing module, so `[formControl]` in your template has no effect at all.
2. you must call `fixture.detectChanges()` at the begining of each test (or inside your beforeEach) to initialize your component.

This should be a StackOverflow question, not an issue.

**Comment by stimitom** [comment]
> 
> 
> Hi @stimitom
> 
> Yes, you're doing two things wrong:
> 
>     1. you're not importing `ReactingFormsModule` in your testing module, so `[formControl]` in your template has no effect at all.
> 
>     2. you must call `fixture.detectChanges()` at the begining of each test (or inside your beforeEach) to initialize your component.
> 
> 
> This should be a StackOverflow question, not an issue.

Thank you very much @jnizet ! 
It's always the silly mistakes like those 🙃
