### ISSUE TITLE
Outlet route is not recognised if URL is encoded 

### ISSUE THREAD

**Issue by yuriykuzin** [angular/angular#43523]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

In fact, I want to re-open this issue: https://github.com/angular/angular/issues/26035

## Current behaviour
Some software tools change URLs escaping some symbols, like `(` and `)`
So URL like this: `https://site.com/(modal:reset)`
Becomes: `https://site.com/%28modal:reset%29` which is still a valid URL.

When such URL is opened, Angular cannot find such route (reproduced on the latest Angular 12.2.5 - https://stackblitz.com/edit/angular-9xudgi?file=src/app/app.component.html).

## Expected behaviour
URL should be decoded before looking for an activated route.

## Minimal reproduction of the problem with instructions
- Setup a route that has an outlet.
- Replace parentheses with %28 and %29 respectively
- Open the URL directly

## Possible solution
To solve this I use custom `UrlSerializer` like suggested here: https://digitalflask.com/blog/extend-angular-router

This works fine, but I wonder why decoding isn't implemented by default?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-9xudgi?file=src/app/app.component.html

### Please provide the exception or error you saw

```true
ERROR
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '%28modal:modal%29'
Error: Cannot match any routes. URL Segment: '%28modal:modal%29'
at ApplyRedirects.noMatchError (https://angular-9xudgi.stackblitz.io/turbo_modules/@angular/router@12.2.5/bundles/router.umd.js:3126:20)
at eval (https://angular-9xudgi.stackblitz.io/turbo_modules/@angular/router@12.2.5/bundles/router.umd.js:3107:33)
at eval (https://angular-9xudgi.stackblitz.io/turbo_modules/rxjs@7.3.0/dist/cjs/internal/operators/catchError.js:13:46)
at OperatorSubscriber._this._error (https://angular-9xudgi.stackblitz.io/turbo_modules/rxjs@7.3.0/dist/cjs/internal/operators/OperatorSubscriber.js:38:21)
at OperatorSubscriber.Subscriber.error (https://angular-9xudgi.stackblitz.io/turbo_modules/rxjs@7.3.0/dist/cjs/internal/Subscriber.js:81:18)
at OperatorSubscriber.Subscriber._error (https://angular-9xudgi.stackblitz.io/turbo_modules/rxjs@7.3.0/dist/cjs/internal/Subscriber.js:105:30)
at OperatorSubscriber.Subscriber.error (https://angular-9xudgi.stackblitz.io/turbo_modules/rxjs@7.3.0/dist/cjs/internal/Subscriber.js:81:18)
at OperatorSubscriber.Subscriber._error (https://angular-9xudgi.stackblitz.io/turbo_modules/rxjs@7.3.0/dist/cjs/internal/Subscriber.js:105:30)
at OperatorSubscriber.Subscriber.error (https://angular-9xudgi.stackblitz.io/turbo_modules/rxjs@7.3.0/dist/cjs/internal/Subscriber.js:81:18)
at OperatorSubscriber.Subscriber._error (https://angular-9xudgi.stackblitz.io/turbo_modules/rxjs@7.3.0/dist/cjs/internal/Subscriber.js:105:30)
```

### Please provide the environment you discovered this bug in

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 11.2.13
Node: 12.16.1
OS: darwin x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cdk                    10.2.0
@angular/cli                    11.2.13
@angular/material               10.2.0
@schematics/angular             11.2.13
@schematics/update              0.1102.13
rxjs                            6.6.3
typescript                      4.0.2
```

**Comment by atscott** [comment]
Closing this as **not planned** / **won't fix**.
In standard URL grammar (RFC 3986), percent-encoding is used to indicate that a character should be treated as literal data within a path segment rather than a structural delimiter. If the router's default parser treated `%28` and `%29` as outlet group delimiters, it would cause regressions for applications with legitimate encoded parentheses in path segments (such as `/files/%281%29.pdf` or search parameters).
For applications that receive links from third-party clients (such as email software) that percent-encode parentheses, the recommended solution is to use a custom `UrlSerializer` to normalize the URL before parsing:
```typescript
@Injectable()
export class OutletNormalizingUrlSerializer extends DefaultUrlSerializer {
  override parse(url: string): UrlTree {
    return super.parse(url.replace(/%28/gi, '(').replace(/%29/gi, ')'));
  }
}
// In application config:
provideRouter(routes, withUrlSerializer(OutletNormalizingUrlSerializer))
