### ISSUE TITLE
`ngcc` compilation fails as a result of changes in v10 -> v11. 

### ISSUE THREAD

**Issue by damienwebdev** [angular/angular#43570]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

This didn't happen in ng10, but is now happening in v11.

In Daffodil, we have a token called `Constructor` located in a folder called [`constructor`.](https://github.com/graycoreio/daffodil/tree/develop/libs/design/src/core/constructor) As a result, when we try to test our library and `ngcc` kicks in, we get an error.
    
This error is a result of [this line](https://github.com/angular/angular/blob/master/packages/compiler-cli/ngcc/src/packages/configuration.ts#L285) that does a lookup on the key `constructor`. 
    
```
findSatisfactoryVersion(this.projectConfig.packages[packageName], version) 
```

should be replaced with

```
findSatisfactoryVersion(this.projectConfig.packages.hasOwnProperty(packageName), version) 
```

For a trivial comparison, see the following. 
   
```ts
({})["constructor"]
({}).hasOwnProperty("constructor")
```

This bug is present in the current `master` as well.

### Please provide the exception or error you saw

```true
TypeError: Cannot read property 'entryPoints' of undefined
    at new ProcessedNgccPackageConfig (/home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/packages/configuration.js:88:25)
    at NgccConfiguration.getPackageConfig (/home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/packages/configuration.js:155:20)
    at Object.getEntryPointInfo (/home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/packages/entry_point.js:60:36)
    at EntryPointCollector.walkDirectoryForPackages (/home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/entry_point_collector.js:37:51)
    at EntryPointCollector.walkDirectoryForPackages (/home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/entry_point_collector.js:75:79)
    at EntryPointCollector.walkDirectoryForPackages (/home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/entry_point_collector.js:75:79)
    at /home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/program_based_entry_point_finder.js:124:100
    at Object.trackDuration (/home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/utils.js:154:22)
    at ProgramBasedEntryPointFinder.walkBasePathForPackages (/home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/program_based_entry_point_finder.js:124:39)
    at ProgramBasedEntryPointFinder.findOrLoadEntryPoints (/home/damien/daffodil/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/program_based_entry_point_finder.js:89:34)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.2.14
Node: 12.22.1
OS: linux x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14 (cli-only)
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/cdk                    11.2.13
@nguniversal/builders           10.1.0
@nguniversal/express-engine     10.1.0
@schematics/angular             10.2.1
@schematics/update              0.1102.14
ng-packagr                      11.2.4
rxjs                            6.6.3
typescript                      4.1.6
```

### Anything else?

No.

**Comment by JoostK** [comment]
You may be able to workaround by actually creating configuration for the package:

`./ngcc.config.js`
```js
module.exports = {
  packages: {
    'constructor': {}
  }
};
```
