### ISSUE TITLE
Cannot read properties of undefined (reading 'display')

### ISSUE THREAD

**Issue by all2pie** [angular/angular#44028]
# 🐞 Bug report 

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [x] express-engine
- [ ] hapi-engine

### Description

On running `npm run dev:ssr` the code is compiled successfully but when i open the link then error occurs which is added in the exception below. 

I have imported **NoopAnimationsModule** in _app.server.module_ and i have also separated the _app.module.ts_ and _app.browser.module.ts_

## 🔥 Exception or Error

<pre><code>

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR Error: Uncaught (in promise): [object Undefined]
    at resolvePromise (/home/haris/Work/TN/website/dist/website/server/main.js:208374:21)
    at /home/haris/Work/TN/website/dist/website/server/main.js:208269:11
    at /home/haris/Work/TN/website/dist/website/server/main.js:137200:32
    at ZoneDelegate.invoke (/home/haris/Work/TN/website/dist/website/server/main.js:207382:160)
    at Object.onInvoke (/home/haris/Work/TN/website/dist/website/server/main.js:79008:33)
    at ZoneDelegate.invoke (/home/haris/Work/TN/website/dist/website/server/main.js:207382:48)
    at Zone.run (/home/haris/Work/TN/website/dist/website/server/main.js:207110:37)
    at /home/haris/Work/TN/website/dist/website/server/main.js:208447:28
    at ZoneDelegate.invokeTask (/home/haris/Work/TN/website/dist/website/server/main.js:207415:173)
    at Object.onInvokeTask (/home/haris/Work/TN/website/dist/website/server/main.js:78995:33) {
  rejection: undefined,
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: undefined
  },
  zone: <ref *1> Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: <ref *2> ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular *1],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular *1],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular *1],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular *1],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular *1],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular *1],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular *2],
      _hasTaskCurrZone: [Circular *1]
    }
  },
  task: ZoneTask {
    _zone: <ref *1> Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: true,
      __zone_symbol__value: undefined
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function (anonymous)],
    invoke: [Function (anonymous)]
  }
}

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR NetworkError
    at XMLHttpRequest.send (/home/haris/Work/TN/website/dist/website/server/main.js:205262:19)
    at Observable._subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:16380:17)
    at Observable._trySubscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195988:25)
    at Observable.subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195974:22)
    at scheduleTask (/home/haris/Work/TN/website/dist/website/server/main.js:94831:32)
    at Observable._subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:94869:13)
    at Observable._trySubscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195988:25)
    at Observable.subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195974:22)
    at innerSubscribe (/home/haris/Work/TN/website/dist/website/server/main.js:196991:23)
    at MergeMapSubscriber._innerSub (/home/haris/Work/TN/website/dist/website/server/main.js:198335:98)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR NetworkError
    at XMLHttpRequest.send (/home/haris/Work/TN/website/dist/website/server/main.js:205262:19)
    at Observable._subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:16380:17)
    at Observable._trySubscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195988:25)
    at Observable.subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195974:22)
    at scheduleTask (/home/haris/Work/TN/website/dist/website/server/main.js:94831:32)
    at Observable._subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:94869:13)
    at Observable._trySubscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195988:25)
    at Observable.subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195974:22)
    at innerSubscribe (/home/haris/Work/TN/website/dist/website/server/main.js:196991:23)
    at MergeMapSubscriber._innerSub (/home/haris/Work/TN/website/dist/website/server/main.js:198335:98)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Invalid event target
    at setupSubscription (/home/haris/Work/TN/website/dist/website/server/main.js:197551:15)
    at Observable._subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:197525:9)
    at Observable._trySubscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195988:25)
    at Observable.subscribe (/home/haris/Work/TN/website/dist/website/server/main.js:195974:22)
    at HeaderComponent.ngOnInit (/home/haris/Work/TN/website/dist/website/server/main.js:211931:99)
    at callHook (/home/haris/Work/TN/website/dist/website/server/main.js:52862:22)
    at callHooks (/home/haris/Work/TN/website/dist/website/server/main.js:52831:17)
    at executeInitAndCheckHooks (/home/haris/Work/TN/website/dist/website/server/main.js:52782:9)
    at selectIndexInternal (/home/haris/Work/TN/website/dist/website/server/main.js:58783:17)
    at Module.ɵɵadvance (/home/haris/Work/TN/website/dist/website/server/main.js:58766:5)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at /home/haris/Work/TN/website/dist/website/server/main.js:14561:32
    at Array.forEach (<anonymous>)
    at HttpHeaders.lazyInit (/home/haris/Work/TN/website/dist/website/server/main.js:14555:38)
    at HttpHeaders.init (/home/haris/Work/TN/website/dist/website/server/main.js:14659:22)
    at HttpHeaders.keys (/home/haris/Work/TN/website/dist/website/server/main.js:14598:14)
    at HttpBatchLinkHandler.createBatchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138956:29)
    at OperationBatcher.HttpBatchLinkHandler.batchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138907:29)
    at OperationBatcher.enqueueRequest (/home/haris/Work/TN/website/dist/website/server/main.js:106957:24)
    at BatchLink._this.request (/home/haris/Work/TN/website/dist/website/server/main.js:107070:73)
    at HttpBatchLinkHandler.request (/home/haris/Work/TN/website/dist/website/server/main.js:138965:29)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at /home/haris/Work/TN/website/dist/website/server/main.js:14561:32
    at Array.forEach (<anonymous>)
    at HttpHeaders.lazyInit (/home/haris/Work/TN/website/dist/website/server/main.js:14555:38)
    at HttpHeaders.init (/home/haris/Work/TN/website/dist/website/server/main.js:14659:22)
    at HttpHeaders.keys (/home/haris/Work/TN/website/dist/website/server/main.js:14598:14)
    at HttpBatchLinkHandler.createBatchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138956:29)
    at OperationBatcher.HttpBatchLinkHandler.batchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138907:29)
    at OperationBatcher.enqueueRequest (/home/haris/Work/TN/website/dist/website/server/main.js:106957:24)
    at BatchLink._this.request (/home/haris/Work/TN/website/dist/website/server/main.js:107070:73)
    at HttpBatchLinkHandler.request (/home/haris/Work/TN/website/dist/website/server/main.js:138965:29)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at /home/haris/Work/TN/website/dist/website/server/main.js:14561:32
    at Array.forEach (<anonymous>)
    at HttpHeaders.lazyInit (/home/haris/Work/TN/website/dist/website/server/main.js:14555:38)
    at HttpHeaders.init (/home/haris/Work/TN/website/dist/website/server/main.js:14659:22)
    at HttpHeaders.keys (/home/haris/Work/TN/website/dist/website/server/main.js:14598:14)
    at HttpBatchLinkHandler.createBatchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138956:29)
    at OperationBatcher.HttpBatchLinkHandler.batchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138907:29)
    at OperationBatcher.enqueueRequest (/home/haris/Work/TN/website/dist/website/server/main.js:106957:24)
    at BatchLink._this.request (/home/haris/Work/TN/website/dist/website/server/main.js:107070:73)
    at HttpBatchLinkHandler.request (/home/haris/Work/TN/website/dist/website/server/main.js:138965:29)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at /home/haris/Work/TN/website/dist/website/server/main.js:14561:32
    at Array.forEach (<anonymous>)
    at HttpHeaders.lazyInit (/home/haris/Work/TN/website/dist/website/server/main.js:14555:38)
    at HttpHeaders.init (/home/haris/Work/TN/website/dist/website/server/main.js:14659:22)
    at HttpHeaders.keys (/home/haris/Work/TN/website/dist/website/server/main.js:14598:14)
    at HttpBatchLinkHandler.createBatchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138956:29)
    at OperationBatcher.HttpBatchLinkHandler.batchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138907:29)
    at OperationBatcher.enqueueRequest (/home/haris/Work/TN/website/dist/website/server/main.js:106957:24)
    at BatchLink._this.request (/home/haris/Work/TN/website/dist/website/server/main.js:107070:73)
    at HttpBatchLinkHandler.request (/home/haris/Work/TN/website/dist/website/server/main.js:138965:29)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at /home/haris/Work/TN/website/dist/website/server/main.js:14561:32
    at Array.forEach (<anonymous>)
    at HttpHeaders.lazyInit (/home/haris/Work/TN/website/dist/website/server/main.js:14555:38)
    at HttpHeaders.init (/home/haris/Work/TN/website/dist/website/server/main.js:14659:22)
    at HttpHeaders.keys (/home/haris/Work/TN/website/dist/website/server/main.js:14598:14)
    at HttpBatchLinkHandler.createBatchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138956:29)
    at OperationBatcher.HttpBatchLinkHandler.batchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138907:29)
    at OperationBatcher.enqueueRequest (/home/haris/Work/TN/website/dist/website/server/main.js:106957:24)
    at BatchLink._this.request (/home/haris/Work/TN/website/dist/website/server/main.js:107070:73)
    at HttpBatchLinkHandler.request (/home/haris/Work/TN/website/dist/website/server/main.js:138965:29)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at /home/haris/Work/TN/website/dist/website/server/main.js:14561:32
    at Array.forEach (<anonymous>)
    at HttpHeaders.lazyInit (/home/haris/Work/TN/website/dist/website/server/main.js:14555:38)
    at HttpHeaders.init (/home/haris/Work/TN/website/dist/website/server/main.js:14659:22)
    at HttpHeaders.keys (/home/haris/Work/TN/website/dist/website/server/main.js:14598:14)
    at HttpBatchLinkHandler.createBatchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138956:29)
    at OperationBatcher.HttpBatchLinkHandler.batchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138907:29)
    at OperationBatcher.enqueueRequest (/home/haris/Work/TN/website/dist/website/server/main.js:106957:24)
    at BatchLink._this.request (/home/haris/Work/TN/website/dist/website/server/main.js:107070:73)
    at HttpBatchLinkHandler.request (/home/haris/Work/TN/website/dist/website/server/main.js:138965:29)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at /home/haris/Work/TN/website/dist/website/server/main.js:14561:32
    at Array.forEach (<anonymous>)
    at HttpHeaders.lazyInit (/home/haris/Work/TN/website/dist/website/server/main.js:14555:38)
    at HttpHeaders.init (/home/haris/Work/TN/website/dist/website/server/main.js:14659:22)
    at HttpHeaders.keys (/home/haris/Work/TN/website/dist/website/server/main.js:14598:14)
    at HttpBatchLinkHandler.createBatchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138956:29)
    at OperationBatcher.HttpBatchLinkHandler.batchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138907:29)
    at OperationBatcher.enqueueRequest (/home/haris/Work/TN/website/dist/website/server/main.js:106957:24)
    at BatchLink._this.request (/home/haris/Work/TN/website/dist/website/server/main.js:107070:73)
    at HttpBatchLinkHandler.request (/home/haris/Work/TN/website/dist/website/server/main.js:138965:29)

ERROR TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at /home/haris/Work/TN/website/dist/website/server/main.js:91846:29

ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at /home/haris/Work/TN/website/dist/website/server/main.js:14561:32
    at Array.forEach (<anonymous>)
    at HttpHeaders.lazyInit (/home/haris/Work/TN/website/dist/website/server/main.js:14555:38)
    at HttpHeaders.init (/home/haris/Work/TN/website/dist/website/server/main.js:14659:22)
    at HttpHeaders.keys (/home/haris/Work/TN/website/dist/website/server/main.js:14598:14)
    at HttpBatchLinkHandler.createBatchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138956:29)
    at OperationBatcher.HttpBatchLinkHandler.batchKey (/home/haris/Work/TN/website/dist/website/server/main.js:138907:29)
    at OperationBatcher.enqueueRequest (/home/haris/Work/TN/website/dist/website/server/main.js:106957:24)
    at BatchLink._this.request (/home/haris/Work/TN/website/dist/website/server/main.js:107070:73)
    at HttpBatchLinkHandler.request (/home/haris/Work/TN/website/dist/website/server/main.js:138965:29)

TypeError: Cannot read properties of undefined (reading 'display')
    at cloakElement (/home/haris/Work/TN/website/dist/website/server/main.js:4985:36)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4991:48
    at Set.forEach (<anonymous>)
    at cloakAndComputeStyles (/home/haris/Work/TN/website/dist/website/server/main.js:4991:14)
    at /home/haris/Work/TN/website/dist/website/server/main.js:4560:13
    at Map.forEach (<anonymous>)
    at TransitionAnimationEngine._flushAnimations (/home/haris/Work/TN/website/dist/website/server/main.js:4559:22)
    at TransitionAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:4333:32)
    at InjectableAnimationEngine.flush (/home/haris/Work/TN/website/dist/website/server/main.js:5196:32)
    at InjectableAnimationEngine.ngOnDestroy (/home/haris/Work/TN/website/dist/website/server/main.js:92016:14)

</code></pre>

## 🌍 Environment

<pre><code>

Angular CLI: 12.2.4
Node: 16.9.0 (Unsupported)
Package Manager: npm 7.22.0
OS: linux x64

Angular: 12.2.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.4
@angular-devkit/build-angular   12.2.4
@angular-devkit/core            12.2.4
@angular-devkit/schematics      12.2.4
@nguniversal/builders           12.1.0
@nguniversal/express-engine     12.1.0
@schematics/angular             11.2.14
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Comment by dario-piotrowicz** [comment]
I've found an extremely simple solution to this, seems like the animation `clockElement` gets an element with an `undefined` `style` field here:
https://github.com/angular/angular/blob/155742e305cad4b367267c03250d465ce9339587/packages/animations/browser/src/render/transition_animation_engine.ts#L1629-L1630

before accessing `style` we could just add something like:
```ts
 if(!element.style) {
     return null;
 }
```
I just tried that and it does seem to work pretty nicely

but I doubt that this is the right solution (but it could be?... :shrug:) I am not very familiar with SSR/Universal, so I have no idea why the element there doesn't get a `style` nor if that is the expected behavior for SSR elements :shrug:

**Comment by harshpals** [comment]
### _**_**demo**_**_

**Comment by CaerusKaru** [comment]
This was introduced as part of https://github.com/angular/angular/pull/41059; as noted in the breaking changes for that PR there are some areas where SSR users need to take extra caution. I'm unclear as to why that PR was merged without SSR test coverage, so I'll have to check with the team (and decide whether we should rollback until we have the docs changes ready or not).
