### ISSUE TITLE
Cannot add @angular/elements with Angular 13

### ISSUE THREAD

**Issue by sfragis** [angular/angular#44160]
### Which @angular/* package(s) are the source of the bug?

elements, Don't known / other

### Is this a regression?

Yes

### Description

Installing Angular Elements on a fresh new Angular project (version 13) doesn't work:

```
$ ng new test
[output omitted for brevity]
$ cd test
$ ng add @angular/elements
ℹ Using package manager: npm
✔ Found compatible package version: @angular/elements@13.0.1.
✔ Package information loaded.

The package @angular/elements@13.0.1 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
An unhandled exception occurred: Collection "/Users/fast/test/node_modules/@angular/elements/schematics/collection.json" cannot be resolved.
See "/private/var/folders/ht/t8mxy07x6m102vgzy2xkw5s80000gn/T/ng-GV5Ld1/angular-errors.log" for further details.
```

This works fine with Angular 12 instead.

### Please provide the exception or error you saw

```true
[error] Error: Collection "/Users/fast/test/node_modules/@angular/elements/schematics/collection.json" cannot be resolved.
    at SchematicEngineHost.resolve (/Users/fast/test/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:75:19)
    at SchematicEngineHost.resolve (/Users/fast/test/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:55:35)
    at SchematicEngineHost._resolveCollectionPath (/Users/fast/test/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:80:37)
    at SchematicEngineHost.createCollectionDescription (/Users/fast/test/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:118:27)
    at SchematicEngine._createCollectionDescription (/Users/fast/test/node_modules/@angular-devkit/schematics/src/engine/engine.js:162:40)
    at SchematicEngine.createCollection (/Users/fast/test/node_modules/@angular-devkit/schematics/src/engine/engine.js:155:43)
    at AddCommand.getCollection (/Users/fast/test/node_modules/@angular/cli/models/schematic-command.js:143:35)
    at AddCommand.runSchematic (/Users/fast/test/node_modules/@angular/cli/models/schematic-command.js:336:50)
    at AddCommand.executeSchematic (/Users/fast/test/node_modules/@angular/cli/commands/add-impl.js:263:31)
    at AddCommand.run (/Users/fast/test/node_modules/@angular/cli/commands/add-impl.js:208:21)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.2
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.0.1
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@schematics/angular             13.0.2
ng-packagr                      13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by gkalpak** [comment]
The `@angular/elements` `ng-add` schematic has been removed in v13, because it is no longer needed. In the past, we needed it to add the necessary polyfills to `package.json` and `polyfills.ts`, etc.

Since v13, all browsers that Angular supports also natively support Custom Elements, so the only thing you need to do is add `@angular/elements` as a dependency (for example, `npm install @angular/elements --save` or `yarn add @angular/elements`).

See also 619b7cc3857b34598a0036f8ebf9bc2eb27f5507.

**Comment by devversion** [comment]
I think one issue is that the `@angular/elements` package.json file still refers to a non-existent schematic collection that causes the runtime error when `ng add` is invoked. We should remove that so that a proper message like the following is printed:

```
yarn ng add X
yarn run v1.22.17
$ ng add X
ℹ Using package manager: yarn
✔ Found compatible package version: elements@0.6.0.
✔ Package information loaded.

The package X@0.6.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.

```

**Comment by gkalpak** [comment]
Oh, good catch, @devversion :100:
