### ISSUE TITLE
Can't import the named export from non EcmaScript module

### ISSUE THREAD

**Issue by dilanthas** [angular/angular#44169]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

Hi,
I have install @angular/elements to my project and when i do a `ng build` im getting the below error. 

### Please provide the exception or error you saw

```true
Error: ./node_modules/@angular/elements/fesm2015/elements.mjs 328:49-63
Can't import the named export 'ApplicationRef' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/Users/Development/form-test/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (/Users/Development/form-test/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/Development/form-test/node_modules/webpack/lib/Compilation.js:1463:22)
    at /Users/Development/form-test/node_modules/webpack/lib/Compilation.js:1258:10
    at _next0 (eval at create (/Users/Development/form-test/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at eval (eval at create (/Users/Development/form-test/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

Error: ./node_modules/@angular/elements/fesm2015/elements.mjs 323:68-85
Can't import the named export 'ChangeDetectorRef' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (/Users/Development/form-test/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (/Users/Development/form-test/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/Development/form-test/node_modules/webpack/lib/Compilation.js:1463:22)
    at /Users/Development/form-test/node_modules/webpack/lib/Compilation.js:1258:10
    at _next0 (eval at create (//Users/Development/form-test/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at eval (eval at create (/Users/Development/form-test/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.1.4
Node: 14.15.4
OS: darwin x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cli                    11.1.4
@angular/elements               13.0.1
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.7
typescript                      4.1.6
```

**Comment by JoostK** [comment]
Using `@angular/elements` 13.0.1 is not supported with Angular 11. Please install `@angular/elements` using the exact same version as `@angular/core`.
