### ISSUE TITLE
Migrating from Angular 12.2.13 to Angular 13.0.2 Unsuccessful

### ISSUE THREAD

**Issue by benedict-chng** [angular/angular#44272]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi,

I'm unable to migrate our existing application from Angular 12.2.13 to Angular 13.0.2. It is a moderately complex application and use the following command to do the migration as advised by on:

https://update.angular.io/?l=2&v=12.0-13.0

Has anyone seen this?

Rgds,
Benedict

### Please provide the exception or error you saw

```true
Microsoft Windows [Version 10.0.19043.1348]
(c) Microsoft Corporation. All rights reserved.

C:\angular_upgrade\Nova>npx @angular/cli@13 update @angular/core@13 @angular/cli@13
Using package manager: 'npm'
Collecting installed dependencies...
An unhandled exception occurred: Could not find package.json
See "C:\Users\BENEDI~1\AppData\Local\Temp\ng-F4zzJ2\angular-errors.log" for further details.

C:\angular_upgrade\Nova>cd Avatar

C:\angular_upgrade\Nova\Avatar>npx @angular/cli@13 update @angular/core@13 @angular/cli@13
Using package manager: 'npm'
Collecting installed dependencies...
Found 79 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "13.0.3" (was "12.2.13")...
    Updating package.json with dependency @angular/cli @ "13.0.3" (was "12.2.13")...
    Updating package.json with dependency @angular/compiler-cli @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/language-service @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency typescript @ "4.4.4" (was "4.3.5")...
    Updating package.json with dependency @angular/animations @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/common @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/compiler @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/core @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/forms @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/localize @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/platform-browser @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/router @ "13.0.2" (was "12.2.13")...
  UPDATE package.json (5301 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/cli' **

> Remove polyfills required only for Internet Explorer which is no longer supported.
  UPDATE package.json (5267 bytes)
  UPDATE apps/snapp/src/polyfills.ts (2961 bytes)
  UPDATE apps/member/src/polyfills.ts (3053 bytes)
  UPDATE apps/staff/src/polyfills.ts (2961 bytes)
✔ Packages installed successfully.
  Migration completed.

> Remove no longer valid Angular schematic options from `angular.json`.
  Migration completed.

> Remove deprecated options from 'angular.json' that are no longer present in v13.
  UPDATE angular.json (29522 bytes)
  Migration completed.

> Updating '.gitignore' to include '.angular/cache'.
  UPDATE .gitignore (547 bytes)
  Migration completed.

> Update library projects to be published in partial mode and removed deprecated options from ng-packagr configuration.
  Migration completed.

** Executing migrations of package '@angular/core' **

> Migrates `[routerLink]=""` in templates to `[routerLink]="[]"` because these links are likely intended to route to the current page with updated fragment/query params.
× Migration failed: Cannot read property 'readWorkspace' of undefined
  See "C:\Users\BENEDI~1\AppData\Local\Temp\ng-0SNaUB\angular-errors.log" for further details.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
C:\Workspace\Nova\Avatar>ng version

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.13
Node: 14.18.1
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 12.2.13
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.13.10
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            7.3.10
@angular-devkit/schematics      12.2.13
@schematics/angular             12.2.13
rxjs                            6.5.5
typescript                      4.3.5


C:\Workspace\Nova\Avatar>
```

**Comment by benedict-chng** [comment]
This is the content of "C:\Users\BENEDI~1\AppData\Local\Temp\ng-0SNaUB\angular-errors.log"

[error] TypeError: Cannot read property 'readWorkspace' of undefined
    at C:\angular_upgrade\Nova\Avatar\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js:117:59
    at Generator.next (<anonymous>)
    at C:\angular_upgrade\Nova\Avatar\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (C:\angular_upgrade\Nova\Avatar\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js:10:12)
    at getWorkspace (C:\angular_upgrade\Nova\Avatar\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js:115:16)
    at C:\angular_upgrade\Nova\Avatar\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js:40:37
    at Generator.next (<anonymous>)
    at C:\angular_upgrade\Nova\Avatar\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js:14:71
    at new Promise (<anonymous>)

**Comment by alan-agius4** [comment]
@benedict-chng, 

Can you please try the following;


```
npm i @angular/cli@latest -g
ng update @angular/core@13 @angular/cli@13
```
