### ISSUE TITLE
NGCC failed

### ISSUE THREAD

**Issue by ekram0** [angular/angular#44290]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

i run command ng server -o , this error appears to me.
please support 

### Please provide the exception or error you saw

```true
⠙ Generating browser application bundles (phase: setup)...Warning: Entry point 'ngx-swiper-wrapper' contains deep imports into 'd:/00-Trashes/we/node_modules/swiper/types/swiper-events'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Processing legacy "View Engine" libraries:
- ngx-bootstrap/datepicker [es2015/esm2015] (git+ssh://git@github.com/valor-software/ngx-bootstrap.git)
- angular-font-awesome [es2015/esm2015] (git+ssh://git@github.com:baruchvlz/angular-font-awesome.git)
- ngx-bootstrap/tabs [es2015/esm2015] (git+ssh://git@github.com/valor-software/ngx-bootstrap.git)
- ngx-bootstrap/pagination [es2015/esm2015] (git+ssh://git@github.com/valor-software/ngx-bootstrap.git)
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: LocationStrategy, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: PlatformLocation, },
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [APP_BASE_HREF,] },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: PlatformLocation, },
    { type: undefined, decorators: [{ type: Optional }, { type: Inject, args: [APP_BASE_HREF,] },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: IterableDiffers, },
    { type: KeyValueDiffers, },
    { type: ElementRef, },
    { type: Renderer, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
    { type: TemplateRef, },
    { type: IterableDiffers, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
    { type: TemplateRef, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
    { type: TemplateRef, },
    { type: NgSwitch, decorators: [{ type: Host },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
    { type: TemplateRef, },
    { type: NgSwitch, decorators: [{ type: Host },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: NgLocalization, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Attribute, args: ['ngPluralCase',] },] },
    { type: TemplateRef, },
    { type: ViewContainerRef, },
    { type: NgPlural, decorators: [{ type: Host },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: KeyValueDiffers, },
    { type: ElementRef, },
    { type: Renderer, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ViewContainerRef, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: ChangeDetectorRef, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: undefined, decorators: [{ type: Inject, args: [LOCALE_ID,] },] },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return [
    { type: NgLocalization, },
]; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Warning: Invalid constructor parameter decorator in D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js:
 function () { return []; }
Error: Error on worker #2: Error: Failed to find exported name of node (CommonModule = (function () {
    function CommonModule() {
    }
    return CommonModule;
}())) in 'D:/00-Trashes/we/node_modules/angular-font-awesome/dist/angular-font-awesome.js'.
    at findExportedNameOfNode (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:848:11)
    at LogicalProjectStrategy.emit (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:971:18)
    at ReferenceEmitter.emit (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:867:32)
    at toR3Reference (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:4904:22)
    at NgModuleDecoratorHandler._toR3Reference (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:6217:14)
    at file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:6029:50
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:6029:32)
    at NgccTraitCompiler.analyzeTrait (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:3807:30)
    at analyze (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:3778:34)
    at ClusterMaster.onWorkerMessage (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:5139:15)
    at file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:5049:72
    at EventEmitter.<anonymous> (file:///D:/00-Trashes/we/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:5207:15)
    at EventEmitter.emit (node:events:390:28)
    at Worker.<anonymous> (node:internal/cluster/primary:186:13)
    at Worker.emit (node:events:390:28)
    at ChildProcess.<anonymous> (node:internal/cluster/worker:33:12)
    at ChildProcess.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
D:\00-Trashes\we\node_modules\@ngtools\webpack\src\ngcc_processor.js:146
            throw new Error(errorMessage + `NGCC failed${errorMessage ? ', see above' : ''}.`);
                  ^

Error: NGCC failed.
    at NgccProcessor.process (D:\00-Trashes\we\node_modules\@ngtools\webpack\src\ngcc_processor.js:146:19)
    at D:\00-Trashes\we\node_modules\@ngtools\webpack\src\ivy\plugin.js:141:27
    at Hook.eval [as call] (eval at create (D:\00-Trashes\we\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:20:1)
    at Hook.CALL_DELEGATE [as _call] (D:\00-Trashes\we\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (D:\00-Trashes\we\node_modules\webpack\lib\Compiler.js:1054:30)
    at D:\00-Trashes\we\node_modules\webpack\lib\Compiler.js:1099:29
    at eval (eval at create (D:\00-Trashes\we\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: npm 8.1.4
OS: win32 x64

Angular: 13.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by JoostK** [comment]
Hi @ekram0.

The `angular-font-awesome` dependency is not compatible with latest Angular (starting from v9) as it's been published over 3 years ago for Angular 5. It has been incorrectly published to NPM, where all of `@angular/common` is included [in the dependency itself](https://unpkg.com/browse/angular-font-awesome@3.1.2/dist/angular-font-awesome.js). I'd recommend that you update to `@fortawesome/angular-fontawesome` or an alternative package.
