### ISSUE TITLE
Error on worker #1: TypeError: compiler_1.createMayBeForwardRefExpression is not a function

### ISSUE THREAD

**Issue by mayarafernandes** [angular/angular#44404]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

I cloned a working angular application on a new environment and ran a clean install of packages, after the installation some postinstall routines are executed and at that point I'm getting an angular compiling error.

### Please provide the exception or error you saw

```true
> ngcc

Compiling @angular/core : fesm2015 as esm2015
Compiling @angular/compiler/testing : esm2015 as esm2015
Error: Error on worker #1: TypeError: compiler_1.createMayBeForwardRefExpression is not a function
    at extractInjectableMetadata (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:140:40)
    at InjectableDecoratorHandler.analyze (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:70:24)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:421:40)
    at analyze (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:371:58)
    at _loop_1 (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:393:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:399:35)
    at NgccTraitCompiler.analyzeFile (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\analysis\ngcc_trait_compiler.js:49:26)
    at DecorationAnalyzer.analyzeProgram (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:150:39)
    at Transformer.analyzeProgram (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:135:57)
    at Transformer.transform (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\packages\transformer.js:77:27)
    at ClusterMaster.onWorkerMessage (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:195:27)
    at D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:55:95
    at ClusterMaster.<anonymous> (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:293:57)
    at step (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\tslib\tslib.js:143:27)
    at Object.next (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\tslib\tslib.js:124:57)
    at D:\TSS\CDE\CDE.Web\ClientApp\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\tslib\tslib.js:113:16)
    at EventEmitter.<anonymous> (D:\TSS\CDE\CDE.Web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:287:32)
    at EventEmitter.emit (events.js:400:28)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.13
Node: 14.18.2
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 12.0.1
... animations, cdk, common, compiler, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1202.13
@angular-devkit/build-angular              12.2.13
@angular-devkit/core                       12.2.13
@angular-devkit/schematics                 12.2.13
@angular/cli                               12.2.13
@angular/compiler-cli                      12.2.14
@angular/language-service                  12.2.14
@angular/material                          12.2.13
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        12.2.13
rxjs                                       6.6.7
typescript                                 4.2.4
```

**Comment by gkalpak** [comment]
This error is caused by the following version mismatch:
You are using v12.0.1 for most Angular framework packages, but you are using v12.2.14 for `@angular/compiler-cli` and `@angular/language-service`.

You should always use the same versions of these packages.
(Using [ng update][1] should help you keep the necessary versions in sync.)

[1]: https://angular.io/cli/update
