### ISSUE TITLE
Incorrect typescript version in examples

### ISSUE THREAD

**Issue by jrvidal** [angular/angular#44480]
### Description

Many of the current examples (I imagine that all the examples for Angular 13?) seem to have incorrect dependencies, and they fail to run in Stackblitz. See for instance https://github.com/stackblitz/webcontainer-core/issues/473 and all the linked issues.

### What is the affected URL?

https://angular.io/generated/live-examples/getting-started-v0/stackblitz.html

### Please provide the steps to reproduce the issue

* Go to URL
* Wait for automatic scripts in Stackblitz to run (`npm install && turbo start`)
* Observe following error:
```
node:6) UnhandledPromiseRejectionWarning: Error: The Angular Compiler requires TypeScript >=4.4.2 and <4.5.0 but 4.5.4 was found instead.
    at checkVersion (file:///home/projects/j2wdau--run/node_modules/@angular/compiler-cli/bundles/index.js:17524:11)
    at verifySupportedTypeScriptVersion (file:///home/projects/j2wdau--run/node_modules/@angular/compiler-cli/bundles/index.js:17528:3)
    at new NgtscProgram (file:///home/projects/j2wdau--run/node_modules/@angular/compiler-cli/bundles/index.js:17678:7)
    at AngularWebpackPlugin.updateAotProgram (/home/projects/j2wdau--run/node_modules/@ngtools/webpack/src/ivy/plugin.js:321:32)
    at eval (/home/projects/j2wdau--run/node_modules/@ngtools/webpack/src/ivy/plugin.js:198:24)
    at Hook.eval [as call] (eval at _0x5eef21 (https://j2wdau--run.w.staticblitz.com/blitz.731360fb19d99dfc563f19370095b1e3465a14ed.js:11:221412), <anonymous>:20:1)
    at Hook.CALL_DELEGATE [as _call] (/home/projects/j2wdau--run/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/projects/j2wdau--run/node_modules/webpack/lib/Compiler.js:1054:30)
    at eval (/home/projects/j2wdau--run/node_modules/webpack/lib/Compiler.js:1099:29)
    at eval (eval at _0x5eef21 (https://j2wdau--run.w.staticblitz.com/blitz.731360fb19d99dfc563f19370095b1e3465a14ed.js:11:221412), <anonymous>:31:1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠼ Generating browser application bundles (phase:
```

### Please provide the expected behavior vs the actual behavior you encountered

Compilation should run without issues.

### Please provide a screenshot if possible

![screenshot](https://user-images.githubusercontent.com/22328440/145593232-f1052cfc-e9ed-4d91-96db-536750e87028.png)

**Comment by crisbeto** [comment]
I'm guessing that we'll have to update the examples to use Angular 13.1.
