### ISSUE TITLE
The requested module '@angular/compiler' does not provide an export named 'isSyntaxError'

### ISSUE THREAD

**Issue by cesco69** [angular/angular#44709]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

After update to Angular 13.1.2 `ng serve` show this error

```
[error] /node_modules/@angular/compiler-cli/bundles/chunk-P5ZW5MI4.js:7205
import { isSyntaxError } from "@angular/compiler";
         ^^^^^^^^^^^^^
SyntaxError: The requested module '@angular/compiler' does not provide an export named 'isSyntaxError'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:142:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async readTsconfig \node_modules\@angular-devkit\build-angular\src\utils\read-tsconfig.js:44:54)
    at async configureI18nBuild (\node_modules\@angular-devkit\build-angular\src\utils\i18n-options.js:124:22)
    at async generateI18nBrowserWebpackConfigFromContext (\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:68:36)
    at async setup (\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js:127:47)
```

### Please provide the exception or error you saw

```true
The requested module '@angular/compiler' does not provide an export named 'isSyntaxError'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.2
Node: 12.22.1
Package Manager: npm 8.3.0
OS: win32 x64

Angular: 13.1.2
... animations, cdk, cli, common, compiler, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/compiler-cli           13.1.1
@schematics/angular             13.1.2
rxjs                            7.5.2
typescript                      4.5.4
```

**Comment by JoostK** [comment]
Your `@angular/compiler-cli` package must align with the rest of the framework packages, so it needs to be updated to `13.1.2`.

**Comment by cesco69** [comment]
Why `ng update` says  everything is updated?

```
ng update

Using package manager: 'npm'
Collecting installed dependencies...
Found 59 dependencies.
    We analyzed your package.json and everything seems to be in order. Good work!
```

**Comment by JoostK** [comment]
I have no idea. I just checked and `@angular/compiler-cli@13.1.2` is available on NPM, so it should be able to update to that.
