### ISSUE TITLE
Missing EventEmitter produces a tricky message

### ISSUE THREAD

**Issue by mhevery** [angular/angular#4473]
```
@Component({
  outputs: ['myEvent']
})
@View(...)
class {
  myEvent:EventEmitter; // <<< Missing new EventEmitter()
}
```

Produces this error. The error is hard to understand since it is not clear what the issue is.

```
ERROR: 'TypeError: Cannot read property 'observer' of undefined
    at Function.ObservableWrapper.subscribe (http://localhost:9876/base/dist/js/dev/es5/angular2/src/core/facade/async.js:69:23)
    at EventEmitterAccessor.subscribe (http://localhost:9876/base/dist/js/dev/es5/angular2/src/core/compiler/element_injector.js:211:42)
    at AppViewManagerUtils._setUpEventEmitters (http://localhost:9876/base/dist/js/dev/es5/angular2/src/core/compiler/view_manager_utils.js:209:38)
    at AppViewManagerUtils._hydrateView (http://localhost:9876/base/dist/js/dev/es5/angular2/src/core/compiler/view_manager_utils.js:179:30)
    at AppViewManagerUtils.hydrateRootHostView (http://localhost:9876/base/dist/js/dev/es5/angular2/src/core/compiler/view_manager_utils.js:105:14)
    at AppViewManager.createRootHostView (http://localhost:9876/base/dist/js/dev/es5/angular2/src/core/compiler/view_manager.js:157:21)
    at Ng2ComponentFacade.bootstrapNg2 (http://localhost:9876/base/dist/js/dev/es5/upgrade/src/upgrade_module.js:175:30)
```

**Comment by pkozlowski-opensource** [comment]
Totally agree :-)
This is why I've opened https://github.com/angular/angular/issues/3664 :-)

**Comment by mhevery** [comment]
Closing as dup of #3664
