### ISSUE TITLE
language-service: Recursive resolve error when module imports itself

### ISSUE THREAD

**Issue by alorle** [angular/angular#44873]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No

### Description

1. Start from a minimal Angular project created with `angular-cli@13`.
2. Create a module that imports itself:
```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

@NgModule({
  declarations: [],
  imports: [CommonModule, TestModule]
})
export class TestModule { }
```
3. The language-service crashes.

**Expected behaviour:** The language-service should inform you that the module definition is wrong.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-8cephx

### Please provide the exception or error you saw

```true
[Info  - 9:13:41] Angular language server process ID: 94614
[Info  - 9:13:41] Using typescript/lib/tsserverlibrary v4.5.5 from /home/alvaro.orduna/test/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 9:13:41] Using @angular/language-service v13.2.0 from /home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/index.js
[Info  - 9:13:41] Logging is turned off. To enable, run command 'Open Angular server log'.
[Info  - 9:13:45] Enabling Ivy language service for /home/alvaro.orduna/test/tsconfig.json.
(node:94614) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at MetadataDtsModuleScopeResolver.resolve (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33182:31)
    at LocalModuleScopeRegistry.getExportedScope (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33680:51)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33510:42)
    at LocalModuleScopeRegistry.getExportedScope (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33684:29)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33510:42)
    at LocalModuleScopeRegistry.getExportedScope (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33684:29)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33510:42)
    at LocalModuleScopeRegistry.getExportedScope (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33684:29)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33510:42)
    at LocalModuleScopeRegistry.getExportedScope (/home/alvaro.orduna/.vscode/extensions/angular.ng-template-13.2.0/node_modules/@angular/language-service/bundles/language-service.js:33684:29)
(Use `code --trace-warnings ...` to show where the warning was created)
(node:94614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:94614) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.0
Node: 12.22.7
Package Manager: npm 6.14.15
OS: linux x64

Angular: 13.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.0
@angular-devkit/build-angular   13.2.0
@angular-devkit/core            13.2.0
@angular-devkit/schematics      13.2.0
@schematics/angular             13.2.0
rxjs                            7.5.2
typescript                      4.5.5
```

### Anything else?

I know the example is silly, and a module shouldn't import itself. However, the language-service should not explode, but instead report that there is an error in the module code.

**Comment by JoostK** [comment]
This is a known compiler bug, see #14649.
