### ISSUE TITLE
ng build success but throwing error on ng serve -- return new error

### ISSUE THREAD

**Issue by jagdishj** [angular/angular#44996]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I am getting the below issue in my angular project on ng serve but ng build is successful.

I have done the below trials to resolve the error
trial 1: Removed the .angular folder and node modules folder and tried to install the modules again but no luck.
trial 2: removed the angular and node packages and tried to install again but got same error.
trial 3: my ng version is up-to-date confirmed using ng update command.

### Please provide the exception or error you saw

```true
node_modules\webpack-sources\lib\SizeOnlySource.js:16
return new Error(
^

Error: Content and Map of this Source is not available (only size() is supported)
at SizeOnlySource._error (node_modules\webpack-sources\lib\SizeOnlySource.js:16:10)
at SizeOnlySource.buffer (node_modules\webpack-sources\lib\SizeOnlySource.js:30:14)
at _isSourceEqual (node_modules\webpack\lib\util\source.js:21:51)
at isSourceEqual (node_modules\webpack\lib\util\source.js:43:17)
at Compilation.emitAsset (node_modules\webpack\lib\Compilation.js:4215:9)
at node_modules\webpack\lib\Compiler.js:553:28
at node_modules\webpack\lib\Compiler.js:1183:17
at eval (eval at create (node_modules\tapable\lib\HookCodeFactory.js:33:10), :13:1)
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.2
Node: 16.13.2
Package Manager: npm 8.1.4
OS: win32 x64

Angular: 13.2.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
```

**Comment by jagdishj** [comment]
finally got the solution
the issue is resolved by altering the app.module page to force angular to throw errors and then undo it and tried to run the code.

Note: in my trials, I have done cache clear many times but still it's not resolved at that time.
