### ISSUE TITLE
change detector throws exception when triggering .next on an instance of EventEmitter

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#4514]
I create a custom checkbox component:
```js
import {
	Inject,
	Input,
	Output,
	HostBinding,
	HostListener,
	EventEmitter,
	Component,
	View,
	Self,
	Attribute,
	ViewEncapsulation,
	ControlValueAccessor,
	CheckboxControlValueAccessor,
	NgControl,
	OpaqueToken,
	forwardRef,
	Binding,
	Renderer,
	ElementRef
} from 'angular2/angular2';

import { isPresent, isNativeShadowDomSupported } from 'common/lang';
import { KEY_CODES } from 'common/key_codes';
import { Icon } from '../icon/icon';

const NG_VALUE_ACCESSOR: OpaqueToken = new OpaqueToken("NgValueAccessor");
const CHECKBOX_VALUE_ACCESSOR = new Binding(
	NG_VALUE_ACCESSOR,
	{
		toAlias: forwardRef(() => Checkbox),
		multi: true
	}
);

@Component({
	selector: 'checkbox[ng-control], checkbox[ng-form-control], checkbox[ng-model]',
	bindings: [
		CHECKBOX_VALUE_ACCESSOR
	],
	inputs: [
		'disabled'
	]
})

@View({
	// encapsulation: isNativeShadowDomSupported ? ViewEncapsulation.Native : ViewEncapsulation.Emulated, // Emulated, Native, None (default)
	encapsulation: ViewEncapsulation.Emulated, // Emulated, Native, None (default)
	templateUrl: 'app/components/checkbox/checkbox.html',
	styleUrls: [
		'app/components/checkbox/checkbox.css'
	],
	directives: [
		Icon
	]
})

export class Checkbox implements ControlValueAccessor {
	@Input('checked') _checked: boolean = false;
	@Output() change: EventEmitter = new EventEmitter();	
	
	private _tabindex: number;
	private _disabled: boolean = false;

	constructor(@Self() cd: NgControl, @Inject(Renderer) private _renderer, @Inject(ElementRef) private _elementRef, @Attribute('tabindex') tabindex: string) {
		this._tabindex = isPresent(tabindex) ? parseInt(tabindex, 10) : 0;
		cd.valueAccessor = this; // validation will not work if we don't set the control value accessor
	}
	
	@HostBinding('attr.tabindex')
	get tabindex(): number {
		return this._tabindex;
	}
	
	@HostBinding('attr.aria-checked')
	get checked(): boolean {
		return this._checked;
	}
	
	@HostBinding('attr.aria-disabled')
	get disabled() {
		return this._disabled;
	}
	
	@HostBinding('attr.role')
	get role(): string {
		return 'checkbox';
	}

	set disabled(value) {
		this._disabled = isPresent(value) && value !== false;
	}

	toggle(event) {
		if (this.disabled) return event.stopPropagation();
		this._checked = !this._checked;
		this.onChange(this._checked);
		console.log(this.change)
		this.change.next(this._checked);
	}
	registerOnChange(fn: (_: any) => void): void {
		this.onChange = fn;
	}
	registerOnTouched(fn: () => void): void {
		this.onTouched = fn;
	}
	writeValue(value: any): void {
		this._checked = value;
	}

	@HostListener('keydown', [
		'$event'
	])
	onKeydown(event: KeyboardEvent) {
		if (event.keyCode !== KEY_CODES.SPACE) return;
		event.preventDefault();
		this.toggle(event);
	}
	
	@HostListener('change', [
		'$event.target.value'
	])
	onChange: Function = (_) => {};
	
	@HostListener('blur', [
		'$event'
	])
	onTouched: Function = () => {};
}
```
```html
<div class="checkbox" (click)="toggle($event)">
	<icon src="media/checkbox.svg"></icon>
</div>
```
that is used as such:
```html
<checkbox ng-control="status" [(ng-model)]="model.completed" (change)="onStatusChange()"></checkbox>
```
But it looks like after I made the update to the latest alpha version I keep getting an exception thrown whenever I try to click/keydown on the checkbox:

<img width="1440" alt="screenshot 2015-10-04 14 40 40" src="https://cloud.githubusercontent.com/assets/1479737/10267878/f70e2948-6aa5-11e5-8a80-4d40aff10274.png">

Stacktrace:
```js
EXCEPTION: Error during evaluation of "change"
angular2.js:18606 EXCEPTION: Error during evaluation of "change"BrowserDomAdapter.logError @ angular2.js:18606BrowserDomAdapter.logGroup @ angular2.js:18617ExceptionHandler.call @ angular2.js:4259(anonymous function) @ angular2.js:19287NgZone._onError @ angular2.js:11859errorHandling.onError @ angular2.js:11778run @ angular2.js:123(anonymous function) @ angular2.js:11792zoneBoundFn @ angular2.js:93
angular2.js:18606 ORIGINAL EXCEPTION: TypeError: Cannot read property 'value' of undefinedBrowserDomAdapter.logError @ angular2.js:18606ExceptionHandler.call @ angular2.js:4268(anonymous function) @ angular2.js:19287NgZone._onError @ angular2.js:11859errorHandling.onError @ angular2.js:11778run @ angular2.js:123(anonymous function) @ angular2.js:11792zoneBoundFn @ angular2.js:93
angular2.js:18606 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ angular2.js:18606ExceptionHandler.call @ angular2.js:4271(anonymous function) @ angular2.js:19287NgZone._onError @ angular2.js:11859errorHandling.onError @ angular2.js:11778run @ angular2.js:123(anonymous function) @ angular2.js:11792zoneBoundFn @ angular2.js:93
angular2.js:18606 TypeError: Cannot read property 'value' of undefined
    at AbstractChangeDetector.ChangeDetector_TodoItem_0.handleEventInternal (eval at <anonymous> (http://localhost:3000/lib/angular2.js:20042:14), <anonymous>:730:25)
    at AbstractChangeDetector.handleEvent (http://localhost:3000/lib/angular2.js:19802:22)
    at AppView.dispatchEvent (http://localhost:3000/lib/angular2.js:17191:39)
    at AppView.triggerEventHandlers (http://localhost:3000/lib/angular2.js:17106:12)
    at Object.next (http://localhost:3000/lib/angular2.js:23198:21)
    at http://localhost:3000/lib/angular2.js:24683:28
    at cb (http://localhost:3000/lib/angular2.js:11835:15)
    at arguments.(anonymous function) (http://localhost:3000/lib/angular2.js:464:24)
    at http://localhost:3000/lib/angular2.js:100:23
    at Zone.run (http://localhost:3000/lib/angular2.js:120:17)
```

**Comment by IgorMinar** [comment]
@vicb can you please take a look at this today and determine if we need to fix this in a39 (due tomorrow/Wed). if it's likely to affect g3 sync, then it should be in a39

**Comment by IgorMinar** [comment]
I'm triaging it for a39 for now, @vsavkin reassign if not likely to affect g3 sybc

**Comment by tbosch** [comment]
Ok, I think this is a bug in your code:

1. In the `toggle(event)` method you are firing a `change` event with the value of `this._checked`, which is a boolean
2. `HostListener` is listening to the `change` event as well and tries to evaluate `$event.target.value`.
3. This will throw, as `$event` is a boolean now.

I.e. `@HostListener` is listening to events that your component is firing as well.

The solution is to use a different event name...

**Comment by tbosch** [comment]
I created another issue to discuss whether we want to prevent directives from listenting to their own events: https://github.com/angular/angular/issues/4593

**Comment by IgorMinar** [comment]
thanks @tbosch!

**Comment by rolandjitsu** [comment]
@tbosch which event name should I rename, `@Output() change: EventEmitter = new EventEmitter();`? Also, should I be calling `this.onChange(this._checked);` or that is unnecessary?
