### ISSUE TITLE
gulp test.unit.js failing on Windows with Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by mlaval** [angular/angular#4525]
The issue appeared with the update to node 4.1.1, npm 2.14.5, Karma 0.13.10, etc.

After upgrading node and npm, and doing a clean `npm install`, running `gulp test.unit.js` raises the following error on 2 different machines (Windows 7 and Windows 10):
```
05 10 2015 18:53:26.961:ERROR [karma]: { [Error: EMFILE: too many open files, open 'D:\Github\angular_mlaval\node_modules\chokidar\node_modules\readdirp\stream-api.js']
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'D:\\Github\\angular_mlaval\\node_modules\\chokidar\\node_modules\\readdirp\\stream-api.js' }
Error: EMFILE: too many open files, open 'D:\Github\angular_mlaval\node_modules\chokidar\node_modules\readdirp\stream-api.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.Module._extensions..js (module.js:451:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at readdir (D:\Github\angular_mlaval\node_modules\chokidar\node_modules\readdirp\readdirp.js:52:25)
    at EventEmitter.<anonymous> (D:\Github\angular_mlaval\node_modules\chokidar\lib\nodefs-handler.js:353:5)
    at EventEmitter.NodeFsHandler._handleDir (D:\Github\angular_mlaval\node_modules\chokidar\lib\nodefs-handler.js:402:18)
    at EventEmitter.<anonymous> (D:\Github\angular_mlaval\node_modules\chokidar\lib\nodefs-handler.js:450:19)
    at EventEmitter.<anonymous> (D:\Github\angular_mlaval\node_modules\chokidar\lib\nodefs-handler.js:455:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
```
Running `gulp test.unit.js/ci` raises:
```
05 10 2015 18:54:19.816:ERROR [karma]: { [Error: EMFILE: too many open files, open 'D:\Github\angular_mlaval\npm-shrinkwrap.json']
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'D:\\Github\\angular_mlaval\\npm-shrinkwrap.json' }
Error: EMFILE: too many open files, open 'D:\Github\angular_mlaval\npm-shrinkwrap.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at _checkCache (D:\Github\angular_mlaval\tools\npm\check-node-modules.js:41:26)
    at checkNodeModules (D:\Github\angular_mlaval\tools\npm\check-node-modules.js:13:23)
    at D:\Github\angular_mlaval\tools\check-environment.js:25:10
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
Note that `gulp test.unit.dart` and `gulp test.unit.cjs` are working fine

**Comment by IgorMinar** [comment]
there is an issue with [tmp folder not being cleaned up properly #4441](https://github.com/angular/angular/issues/4441) which might be related. can you verify that you can repro this issue with tmp folder manually removed?

**Comment by mlaval** [comment]
It doesn't help, investigating ...

**Comment by mlaval** [comment]
Some more observations:
 - ` karma start karma-js.conf.js` works
 - `gulp test.unit.js/ci` works when commenting out the `./tools/check-environment` part: https://github.com/angular/angular/blob/master/gulpfile.js#L47-L50
 - `gulp test.unit.js` works when commenting out the watcher part: https://github.com/angular/angular/blob/master/gulpfile.js#L601-L606

Could it be some kind of race condition on the filesystem access?

**Comment by IgorMinar** [comment]
I don't know.

commenting out ` ./tools/check-environment ` helps? that's really odd. can
you trace it what inside of check-environment is causing the problem? that
could give us some hints..

**Comment by mlaval** [comment]
`fs.readFileSync` is obviously the cause of the problem as it tries to open a file when too many are already opened.

Digging a bit more, I found out that after executing `new karma.Server({...}).start()`, there is no more file handle available. This means that the very next file access will fail, be it `chokidar` or `check-node-modules`.
Karma itself is not impacted because it uses `graceful-fs` to open files.

Adding a long synchronous wait loop after the start doesn't solve the problem.
But adding a setTimeout does, e.g:
```
gulp.task('test.unit.js', ['build.js.dev'], function (done) {
  runSequence(
    '!test.unit.js/karma-server',
    function() {
      setTimeout(() => {
        watch('modules/**', [
          '!broccoli.js.dev',
          '!test.unit.js/karma-run'
        ]);
      }, 1000);
    }
  );
});
```

It is not yet clear if it comes from Karma, graceful-fs, node or Windows ...

**Comment by alfonso-presa** [comment]
@mlaval Your patch worked perfectly for me, thanks!

Is there any possibility of adding this patch to the main branch to fix the situation until karma/graceful-fs/node get's fixed? It's a little bit of a pain having that file always dirty in the local folder, but anyway is something I can live with, I guess (sigh).

**Comment by alfonso-presa** [comment]
BTW just in case it gives you some more clues, what I was doing to run the tests (before applying your patch that is a lot much better), was watching only the `gulpfile.js` instead of the full modules folder. This way it runs, so it seems like there are still some file handles avail (at least one :-) )....

**Comment by ericmartinezr** [comment]
Sorry for bumping this issue, but just upgraded to a.44 and I ran into this issue (prior to a.44 this didn't happen to me). I tried @mlaval patch but doesn't work for me, instead of failing and crashing, it just throws the error message, pass it and gets stuck in a posterior step, here's part of the log http://pastebin.com/N0CZzPUm (It just get stuck in the last line). I even tried with giving more time to the setTimeout).

**Comment by mlaval** [comment]
On Windows, still the same situation with latest master.
Upgrading to node 4.2.1 doesn't help

**Comment by IgorMinar** [comment]
Marc, let's debug this after Angular Connect when I'm at your office.

**Comment by comdiv** [comment]
While it marked as closed I catch it in Windows 10 1511 build:
```
[00:03:36] Using gulpfile D:\testrepo\angular\gulpfile.js
[00:03:36] Starting 'test.unit.js/ci'...
30 11 2015 00:03:38.200:ERROR [karma]: { [Error: EMFILE: too many open files, op
en 'D:\testrepo\angular\npm-shrinkwrap.json']
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'D:\\testrepo\\angular\\npm-shrinkwrap.json' }
Error: EMFILE: too many open files, open 'D:\testrepo\angular\npm-shrinkwrap.jso
n'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at _checkCache (D:\testrepo\angular\tools\npm\check-node-modules.js:41:26)
    at checkNodeModules (D:\testrepo\angular\tools\npm\check-node-modules.js:13:
23)
    at D:\testrepo\angular\tools\check-environment.js:25:10
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
[00:03:38] 'test.unit.js/ci' errored after 1.53 s
```

**Comment by jfarid27** [comment]
I'm not sure about the status of this bug, but this might be a Karma or Node issue. I was brought here trying to search for the same "too many files" issue, specifically using [this project](https://github.com/jfarid27/frilio-front) I started a few months ago. I'm having this problem now on a MacPro 2015 on OSX El Capitan, using Node 4.2.2 and npm 2.14.7. Along with this, it was tested on Karma 0.13.15. All the dependencies are the same in the package as well if anyone wants to try and recreate. It is strange that the project starts fine with the standard npm start, so I'm starting to be sure it's a Karma or Node issue somewhere around versions 0.13.x and 4.2.x. I'll try to get an update with Node 5 and see if it works out.

**Comment by karlderkaefer** [comment]
ty cleaning %TEMP% worked for me on Win10
