### ISSUE TITLE
"Unexpected token ILLEGAL" when trying to run npm install

### ISSUE THREAD

**Issue by hterkelsen** [angular/angular#4527]
On a fresh clone of angular:

```
$ npm install

> angular@2.0.0-alpha.38 preinstall /tmp/angular
> node tools/npm/check-node-modules --purge

:-( npm dependencies are stale or in an in unknown state!
    purging...
npm WARN prefer global marked@0.3.3 should be installed with -g
npm WARN prefer global karma-cli@0.1.0 should be installed with -g
npm WARN peerDependencies The peer dependency dgeni@^0.4.0 included from dgeni-packages will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN prefer global js-beautify@1.5.5 should be installed with -g
npm WARN engine joi-assert@0.0.3: wanted: {"node":">= 0.10.0 <= 0.11.0"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN peerDependencies The peer dependency ministyle@~0.1.2 included from minitable will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN installMany tap-consumer was bundled with tap@0.3.3, but bundled package wasn't found in unpacked tree
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.10.0"})
 
> sauce-connect-launcher@0.11.1 postinstall /tmp/angular/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher
> node scripts/install.js

 
> spawn-sync@1.0.13 postinstall /tmp/angular/node_modules/gulp-sass/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

 
> utf-8-validate@1.2.1 install /tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
 
> bufferutil@1.2.1 install /tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
 
> utf-8-validate@1.2.1 install /tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
npm WARN optional dep failed, continuing fsevents@1.0.0
 
> bufferutil@1.2.1 install /tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/tmp/angular/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
npm WARN prefer global tsd@0.6.5-beta should be installed with -g
 
> node-sass@3.3.3 install /tmp/angular/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /tmp/angular/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node
npm WARN prefer global bower@1.4.1 should be installed with -g
 
> node-sass@3.3.3 postinstall /tmp/angular/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /tmp/angular/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-14/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
\
> angular@2.0.0-alpha.38 postinstall /tmp/angular
> node tools/npm/copy-npm-shrinkwrap && node tools/chromedriverpatch.js && webdriver-manager update && bower install && gulp pubget.dart && tsd reinstall --overwrite --clean --config modules/angular2/tsd.json && tsd reinstall --overwrite --clean --config tools/tsd.json && tsd reinstall --overwrite --config modules/upgrade/tsd.json

Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.14/chromedriver_linux64.zip...
chromedriver_2.14.zip downloaded to /tmp/angular/node_modules/protractor/selenium/chromedriver_2.14.zip
selenium-server-standalone-2.45.0.jar downloaded to /tmp/angular/node_modules/protractor/selenium/selenium-server-standalone-2.45.0.jar
bower polymer#0.8.0-preview not-cached git://github.com/dart-lang/polymer_js.git#0.8.0-preview
bower polymer#0.8.0-preview    resolve git://github.com/dart-lang/polymer_js.git#0.8.0-preview
bower polymer#0.8.0-preview   checkout 0.8.0-preview
bower polymer#0.8.0-preview     invalid-meta polymer is missing "main" entry in bower.json
bower polymer#0.8.0-preview     invalid-meta polymer is missing "ignore" entry in bower.json
bower polymer#0.8.0-preview         resolved git://github.com/dart-lang/polymer_js.git#331963e89e
bower polymer#0.8.0-preview          install polymer#331963e89e

polymer#331963e89e bower_components/polymer
/tmp/angular/tools/build/pubget.js:14
    var travisFoldEnd = travisFoldStart(`pubget-${config.dir}`);
                                        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/angular/gulpfile.js:23:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "node" "/usr/local/google/home/het/.nvm/versions/node/v0.12.2/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE
npm ERR! angular@2.0.0-alpha.38 postinstall: `node tools/npm/copy-npm-shrinkwrap && node tools/chromedriverpatch.js && webdriver-manager update && bower install && gulp pubget.dart && tsd reinstall --overwrite --clean --config modules/angular2/tsd.json && tsd reinstall --overwrite --clean --config tools/tsd.json && tsd reinstall --overwrite --config modules/upgrade/tsd.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular@2.0.0-alpha.38 postinstall script 'node tools/npm/copy-npm-shrinkwrap && node tools/chromedriverpatch.js && webdriver-manager update && bower install && gulp pubget.dart && tsd reinstall --overwrite --clean --config modules/angular2/tsd.json && tsd reinstall --overwrite --clean --config tools/tsd.json && tsd reinstall --overwrite --config modules/upgrade/tsd.json'.
npm ERR! This is most likely a problem with the angular package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/npm/copy-npm-shrinkwrap && node tools/chromedriverpatch.js && webdriver-manager update && bower install && gulp pubget.dart && tsd reinstall --overwrite --clean --config modules/angular2/tsd.json && tsd reinstall --overwrite --clean --config tools/tsd.json && tsd reinstall --overwrite --config modules/upgrade/tsd.json
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/angular/npm-debug.log
```

**Comment by IgorMinar** [comment]
hi there, please update your node version to 4.1.1 (I recommend using [nvm](https://github.com/creationix/nvm))
