### ISSUE TITLE
Promise.resolve('Breaks ng test')

### ISSUE THREAD

**Issue by patrickbussmann** [angular/angular#45655]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I had this issue in my personal project and thought that this is not normal.
Then I created a new project:
```
ng new angular-tour-of-heroes
```

And added my test case.
It was working fine and then I continue to search the issue.

And then I found out that a simple `await Promise.resolve('Doesnt matter');` breaks the test.

When I comment this line out its working.
But in my real repository it's used to get something from `localStorage` so I need this promise there.

And I cant believe that this simple promise should break the test.

Maybe its a configuration issue? That a `async`/`await` is missing?

Breaking line: https://github.com/patrickbussmann/ng-test-issue-promise-resolve/blob/main/src/app/app.component.ts#L16
Test: https://github.com/patrickbussmann/ng-test-issue-promise-resolve/blob/main/src/app/app.component.spec.ts#L37

### Please provide a link to a minimal reproduction of the bug

https://github.com/patrickbussmann/ng-test-issue-promise-resolve

### Please provide the exception or error you saw

```true
Error: Expected one matching request for criteria "Match URL: http://localhost", found none.
    at HttpClientTestingBackend.expectOne (http://localhost:9877/_karma_webpack_/webpack:/node_modules/@angular/common/fesm2015/http/testing.mjs:288:19)
    at UserContext.<anonymous> (http://localhost:9877/_karma_webpack_/webpack:/src/app/app.component.spec.ts:41:39)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:9877/_karma_webpack_/webpack:/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
    at _next (http://localhost:9877/_karma_webpack_/webpack:/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:1)
    at http://localhost:9877/_karma_webpack_/webpack:/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:32:1
    at new ZoneAwarePromise (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:1427:1)
    at UserContext.<anonymous> (http://localhost:9877/_karma_webpack_/webpack:/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:21:1)
    at _ZoneDelegate.invoke (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:372:1)
    at ProxyZoneSpec.onInvoke (http://localhost:9877/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:287:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.3
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.3.3
... cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@angular/animations             <error>
@schematics/angular             13.3.3
rxjs                            7.5.5
typescript                      4.6.3
```

**Comment by JoostK** [comment]
This seems to be working as expected; the `await`-point in `executeHttpRequest` introduces an asynchronous tick into its execution, but the test invokes `expectOne` synchronously _before_ the request has been sent, as that is pending a microtick. Hence, there is no request pending and the test fails.

Introducing a microtick into the test itself before `expectOne` allows the test to pass:

```
    await Promise.resolve();

    const req = httpTestingController.expectOne('http://localhost');
```

There is #25965 for scenarios where it may not be as simple to "synchronize" the test with the production code.
