### ISSUE TITLE
Angular 13 - ERROR RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by suriyaJaay** [angular/angular#46036]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I Just created brand new project with below Angular Version. When i hit ng serve, compilation is success but in browser am getting 

I'm not able to find the exact reason behind this, because i've created 2 new projects couple of days before for learning purpose which is still working fine and i could able compile and see the application running in the browser.

but today **18-05-2022** the new project i created is not working. Kindly help me to understand this. 

Thanks

### Please provide the exception or error you saw

```true
core.mjs:6461 ERROR RangeError: Maximum call stack size exceeded
    at renderView (core.mjs:9435:1)
    at renderComponent$1 (core.mjs:10677:1)
    at renderChildComponents (core.mjs:9261:1)
    at renderView (core.mjs:9421:1)
    at renderComponent$1 (core.mjs:10677:1)
    at renderChildComponents (core.mjs:9261:1)
    at renderView (core.mjs:9421:1)
    at renderComponent$1 (core.mjs:10677:1)
    at renderChildComponents (core.mjs:9261:1)
    at renderView (core.mjs:9421:1)
defaultErrorLogger @ core.mjs:6461
handleError @ core.mjs:6508
(anonymous) @ core.mjs:26133
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.mjs:25356
(anonymous) @ core.mjs:26133
invoke @ zone.js:372
onInvoke @ core.mjs:25457
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:25444
invokeTask @ zone.js:405
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
Promise.then (async)
nativeScheduleMicroTask @ zone.js:561
scheduleMicroTask @ zone.js:572
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1265
then @ zone.js:1450
bootstrapModule @ core.mjs:26055
4431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.ts:12
(anonymous) @ main.ts:12
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.ts:12
webpackJsonpCallback @ jsonp chunk loading:34
(anonymous) @ main.js:2
main.ts:12 RangeError: Maximum call stack size exceeded
    at renderView (core.mjs:9435:1)
    at renderComponent$1 (core.mjs:10677:1)
    at renderChildComponents (core.mjs:9261:1)
    at renderView (core.mjs:9421:1)
    at renderComponent$1 (core.mjs:10677:1)
    at renderChildComponents (core.mjs:9261:1)
    at renderView (core.mjs:9421:1)
    at renderComponent$1 (core.mjs:10677:1)
    at renderChildComponents (core.mjs:9261:1)
    at renderView (core.mjs:9421:1)
(anonymous) @ main.ts:12
invoke @ zone.js:372
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
Promise.then (async)
nativeScheduleMicroTask @ zone.js:561
scheduleMicroTask @ zone.js:572
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1265
then @ zone.js:1450
bootstrapModule @ core.mjs:26055
4431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.ts:12
(anonymous) @ main.ts:12
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.ts:12
webpackJsonpCallback @ jsonp chunk loading:34
(anonymous) @ main.js:2
index.js:548 [webpack-dev-server] Live Reloading enabled.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
{
  "name": "form-and-test-framework",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.1.0",
    "@angular/common": "~13.1.0",
    "@angular/compiler": "~13.1.0",
    "@angular/core": "~13.1.0",
    "@angular/forms": "~13.1.0",
    "@angular/platform-browser": "~13.1.0",
    "@angular/platform-browser-dynamic": "~13.1.0",
    "@angular/router": "~13.1.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.1",
    "@angular/cli": "~13.1.1",
    "@angular/compiler-cli": "~13.1.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.5.2"
  }
}
```

### Anything else?
3.reactiveForm validation and jest framework\form-and-test-framework>ng serve
√ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   2.00 MB |
polyfills.js          | polyfills     | 334.15 kB |
styles.css, styles.js | styles        | 213.00 kB |
main.js               | main          |   7.58 kB |
runtime.js            | runtime       |   6.88 kB |

                      | Initial Total |   2.55 MB

Build at: 2022-05-18T13:31:13.411Z - Hash: 63e6f3550b7922c5 - Time: 10655ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
_No response_

**Comment by jessicajaniuk** [comment]
Based on the stack size, it looks to me that you have a circular reference issue going on with the components.

**Comment by suriyaJaay** [comment]
> Based on the stack messages, it looks to me that you have a circular reference issue going on with the components.

No it's not an circular reference @jessicajaniuk, if it is so, it would never compile my app i guess. 

my issue got resolved by deleting all 'node_modules' and 'hitting 'npm cache clean --force' then running npm i or you create new app.


Thanks for quick jump,


Happy weekdays

**Comment by jessicajaniuk** [comment]
@suriyaJaay Ah, that makes sense. Without a posted reproduction, it's very difficult for us to do anything but guess. Glad you figured it out.
