### ISSUE TITLE
Angular 13 Forms NgSelectOption throws exception on destruction

### ISSUE THREAD

**Issue by jessharrell** [angular/angular#46071]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

After upgrading to Angular 13, our tests are failing due to an exception thrown by the NgSelectOption OnDestroy. I believe that the issue may have been present for some time but is being exposed by the new default behavior of always calling the OnDestroys. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/jessharrell/angular13-dropdown-testing

### Please provide the exception or error you saw

```true
TypeError: 'set' on proxy: trap returned falsish for property 'value'
at DefaultDomRenderer2.setProperty (node_modules/@angular/platform->browser/fesm2020/platform-browser.mjs:642:12)
at BaseAnimationRenderer.setProperty (node_modules/@angular/platform-browser/fesm2020/animations.mjs:292:27)
at SelectControlValueAccessor.setProperty (node_modules/@angular/forms/fesm2020/forms.mjs:49:24)
at SelectControlValueAccessor.writeValue (node_modules/@angular/forms/fesm2020/forms.mjs:6065:14)
at NgSelectOption.ngOnDestroy (node_modules/@angular/forms/fesm2020/forms.mjs:6155:26)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.5
Node: 16.14.2
Package Manager: npm 8.5.0
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.5 (cli-only)
@angular-devkit/core         13.3.5 (cli-only)
@angular-devkit/schematics   13.3.5 (cli-only)
@schematics/angular          13.3.5 (cli-only)
```

### Anything else?

This issue seems to be exposed when using jest and masked when using other test runners

**Comment by JoostK** [comment]
This is failing because `@testing-library/user-events` defines a property `value` on the `HTMLSelectElement` during `userEvent.selectOptions`:

<img width="1764" alt="image" src="https://user-images.githubusercontent.com/123679/169894281-ad9e16b4-ca47-40ab-be23-03ba48e3adb9.png">

Of particular interest is the fact that the `HTMLSelectElement.constructor.prototype`'s property descriptor is non-writable, which causes the property descriptor that is assigned to the `HTMLSelectElement` to also not be writable. Subsequently when Angular writes to the `value` property of such instance the write is not accepted by a `Proxy` instance, as the descriptor is non-writable (this happens within `jsdom`).

I'm not sure whether `@testing-library/user-events` should be storing the property descriptor with an explicit `writable: true` flag, or if there's some other issue at play here. In any case, `HTMLSelectElement.value` _is_ writable per the spec so Angular's write should not fail.

This problem surfaced in v13 because `destroyAfterEach` became enabled by default. [Please refer to this article for more info](https://dev.to/this-is-angular/improving-angular-tests-by-enabling-angular-testing-module-teardown-38kh). A workaround might be to disable that for the time being, and I'd suggest to raise this issue with the maintainers of `@testing-library/user-events`.
