### ISSUE TITLE
Nested value accessor with standalone components

### ISSUE THREAD

**Issue by syrok0010** [angular/angular#46083]
### Which @angular/* package(s) are the source of the bug?

core, forms

### Is this a regression?

No

### Description

If you have multiple standalone components with nested value accessor, you'll get an error. The form won't work.

### Please provide a link to a minimal reproduction of the bug

https://github.com/syrok0010/accessor-sample

### Please provide the exception or error you saw

```true
ERROR Error: No value accessor for form control with name: 'name'
    at _throwError (forms.mjs:3114:11) [angular]
    at setUpControl (forms.mjs:2902:13) [angular]
    at FormGroupDirective.addControl (forms.mjs:4767:9) [angular]
    at FormControlName._setUpControl (forms.mjs:5323:43) [angular]
    at FormControlName.ngOnChanges (forms.mjs:5268:18) [angular]
    at FormControlName.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1518:14) [angular]
    at callHook (core.mjs:2585:18) [angular]
    at callHooks (core.mjs:2544:17) [angular]
    at executeInitAndCheckHooks (core.mjs:2495:9) [angular]
    at selectIndexInternal (core.mjs:8652:17) [angular]
    at Module.ɵɵadvance (core.mjs:8635:5) [angular]
    at BusFormCoreComponent_Template (bus-form-core.component.html:9:13) [angular]
    at executeTemplate (core.mjs:9892:9) [angular]
    at refreshView (core.mjs:9755:13) [angular]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.0-rc.1
Node: 18.2.0 (Unsupported)
Package Manager: npm 8.10.0 
OS: Arch Linux x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1400.0-rc.1 (cli-only)
@angular-devkit/core         14.0.0-rc.1 (cli-only)
@angular-devkit/schematics   14.0.0-rc.1 (cli-only)
@schematics/angular          14.0.0-rc.1 (cli-only)
```

**Comment by pkozlowski-opensource** [comment]
@syrok0010 I've looked into it and it turns out that you've missed an import to the inner standalone component. I've PR-ed your repo with the details: https://github.com/syrok0010/accessor-sample/pull/1

While this particular situation can be seen as a "user error" it is unfortunate that we are not giving any details in the error that would help diagnose the problem. I'm going to open a separate issue to improve the error message.
