### ISSUE TITLE
Linking an Angular library to an Angular app throw an error after calling the page via localhost

### ISSUE THREAD

**Issue by obas9000** [angular/angular#46207]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

###  Linking an Angular library to an Angular app throws the following error:

```
core.mjs:6494 ERROR TypeError: Cannot read properties of null (reading 'bindingStartIndex')
    at Module.ɵɵelementStart (core:14545:1)
    at GreenTextComponent_Template (libs-my-lib.mjs:13:199)
    at executeTemplate (core.mjs:9632:1)
    at renderView (core.mjs:9432:1)
    at renderComponent$1 (core.mjs:10739:1)
    at renderChildComponents (core.mjs:9297:1)
    at renderView (core.mjs:9457:1)
    at renderComponent$1 (core.mjs:10739:1)
    at renderChildComponents (core.mjs:9297:1)
    at renderView (core.mjs:9457:1)

```
For reproduction purposes I have created a very simple Angular app und library.   
The app simple uses the library to display some green text. 

**Library**:   
https://github.com/obas9000/my-lib  

**App**: 
https://github.com/obas9000/my-app

Using node `v14.15.0 (npm v6.14.8)` everything works fine.
Since using` v16.15.0 (npm v8.5.5)` the above described error appears. 

Steps: 

1. Clone the lib
2. `cd pathToLib/my-lib`
3. `nvm use 16.15`
4. `npm i`
5. `npm run build`
7. `npm run link`
8. Clone the app
9. `cd pathToApp/my-app`
10. `nvm use 16.15`
11. `npm i`
12. `npm link @libs/my-lib`
13. `ng serve`
14. go to localhost:4200

I  you use `nvm use 14.15` everything would work without any error.

### Please provide a link to a minimal reproduction of the bug

See description

### Please provide the exception or error you saw

```true
core.mjs:6494 ERROR TypeError: Cannot read properties of null (reading 'bindingStartIndex')
    at Module.ɵɵelementStart (core:14545:1)
    at GreenTextComponent_Template (libs-my-lib.mjs:13:199)
    at executeTemplate (core.mjs:9632:1)
    at renderView (core.mjs:9432:1)
    at renderComponent$1 (core.mjs:10739:1)
    at renderChildComponents (core.mjs:9297:1)
    at renderView (core.mjs:9457:1)
    at renderComponent$1 (core.mjs:10739:1)
    at renderChildComponents (core.mjs:9297:1)
    at renderView (core.mjs:9457:1)

```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.7
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 13.3.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.3.7
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cli                    13.3.7
@schematics/angular             13.3.7
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by JoostK** [comment]
This is a duplicate of #35586; the linked library is pulling in its own copy of `@angular/core` which causes two runtimes to exist, resulting in uninitialized state in one of the runtimes.

The typical workaround here is to enable `preserveSymlinks`, or include an [explicit path mapping for `@angular` packages](https://github.com/angular/angular/issues/35586#issuecomment-630774572). More details are in #35586.
