### ISSUE TITLE
Throw Error "Cannot add property 0, object is not extensible" when use ViewRef.onDestroy and Forms' ngModel

### ISSUE THREAD

**Issue by why520crazy** [angular/angular#46484]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

inject(ChangeDetectorRef)  and invoke viewRef.onDestroy pass a callback, it's ok in simple scenarios, but when add ngModel  `<input [(ngModel)]="name" />` to template, it throw error "Cannot add property 0, object is not extensible"

```
import { ChangeDetectorRef, Component, inject, ViewRef } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  name = 'test';

  destroy$ = (() => {
    const destroy$ = new Subject<void>();

    const viewRef = inject(ChangeDetectorRef) as ViewRef;

    viewRef.onDestroy(() => {
      destroy$.next();
      destroy$.complete();
    });

    return takeUntil(destroy$.asObservable());
  })();
}
```

<img width="965" alt="image" src="https://user-images.githubusercontent.com/3959960/175472148-79b05a83-8de6-465d-a0f7-ab31ed1b6ad4.png">

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-khumf9?file=src/app/app.component.html

### Please provide the exception or error you saw

```true
Cannot add property 0, object is not extensible


core.mjs:6397 ERROR Error: Uncaught (in promise): TypeError: Cannot add property 0, object is not extensible
TypeError: Cannot add property 0, object is not extensible
    at TCleanup.push (<anonymous>)
    at listenerInternal (core.mjs:15594:38)
    at Module.ɵɵlistener (core.mjs:15471:5)
    at Object.DefaultValueAccessor_HostBindings [as hostBindings] (forms.mjs:255:1)
    at invokeHostBindingsInCreationMode (core.mjs:12596:13)
    at invokeDirectivesHostBindings (core.mjs:12579:17)
    at createDirectivesInstances (core.mjs:11947:9)
    at Module.ɵɵelementStart (core.mjs:15234:9)
    at InjectHomeComponent_Template (home.component.html:2:1)
    at executeTemplate (core.mjs:11916:9)
    at resolvePromise (zone.js:1213:31)
    at resolvePromise (zone.js:1167:17)
    at zone.js:1279:17
    at ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26478:33)
    at ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:582:35)
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.2
Node: 16.15.0
Package Manager: npm 8.5.5 
OS: darwin x64

Angular: 14.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@schematics/angular             14.0.2
rxjs                            6.6.7
typescript                      4.7.4
```

**Comment by JoostK** [comment]
Duplicate of #46119. The cast from `ChangeDetectorRef` to `ViewRef` relies on an implementation detail and is not part of the public API, so this usage pattern is not supported.

**Comment by why520crazy** [comment]
> Duplicate of #46119. The cast from `ChangeDetectorRef` to `ViewRef` relies on an implementation detail and is not part of the public API, so this usage pattern is not supported.

Thank you very much for your reply, i hope that support public API for do this.
