### ISSUE TITLE
Angular does not build with Dart SDK 1.13

### ISSUE THREAD

**Issue by kmillikin** [angular/angular#4677]
The next Dart SDK release will be 1.13.  The build step build/pubbuild.dart fails with 1.13 because it tries to build Angular 1.1.2 for benchmarks_external.  Angular 1.1.2 uses (and depends on packages that use) the dart:profiler package which will be removed in 1.13.

```
$ $(npm bin)/gulp build/pubbuild.dart
Dart SDK detected:
[10:28:32] Using gulpfile ~/angular.git/angular/gulpfile.js
[10:28:32] Starting 'build/pubbuild.dart'...
Loading source assets... 
Loading di/module_transformer, observe and smoke/src/default_transformer transformers... 
The built-in library 'dart:profiler' is not available on the stand-alone VM.
'package:analyzer/src/generated/utilities_general.dart': error: line 10 pos 1: library handler failed
import 'dart:profiler';
^
dart:isolate-patch/isolate_patch.dart 398  Isolate._spawnUri
dart:isolate-patch/isolate_patch.dart 346  Isolate.spawnUri
package:pub/src/dart.dart 221              _isolateBuffer
dart:isolate-patch/isolate_patch.dart 266  _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 150  _RawReceivePortImpl._handleMessage
[10:28:34] 'build/pubbuild.dart' errored after 1.86 s
[10:28:34] Error: 1
    at formatError (/usr/local/google/home/kmillikin/angular.git/angular/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/google/home/kmillikin/angular.git/angular/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/usr/local/google/home/kmillikin/angular.git/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /usr/local/google/home/kmillikin/angular.git/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/usr/local/google/home/kmillikin/angular.git/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /usr/local/google/home/kmillikin/angular.git/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
    at _rejected (/usr/local/google/home/kmillikin/angular.git/angular/node_modules/q/q.js:830:24)
    at /usr/local/google/home/kmillikin/angular.git/angular/node_modules/q/q.js:856:30
    at Promise.when (/usr/local/google/home/kmillikin/angular.git/angular/node_modules/q/q.js:1108:31)
    at Promise.promise.promiseDispatch (/usr/local/google/home/kmillikin/angular.git/angular/node_modules/q/q.js:774:41)
    at /usr/local/google/home/kmillikin/angular.git/angular/node_modules/q/q.js:590:44
    at runSingle (/usr/local/google/home/kmillikin/angular.git/angular/node_modules/q/q.js:123:13)
    at flush (/usr/local/google/home/kmillikin/angular.git/angular/node_modules/q/q.js:111:13)
    at doNTCallback0 (node.js:408:9)
```

This failure is in the Dart Analyzer 0.24.6.  Just overriding that dependency to a newer Analyzer without dart:profiler is not enough.  I think Angular 1.1.2 has to be changed or we have to ship a version built with an SDK before 1.13.

**Comment by IgorMinar** [comment]
I believe that this is a known issue. @yjbanov, can you confirm?

**Comment by yjbanov** [comment]
Yep, I sent a PR to fix it: https://github.com/angular/angular.dart/pull/1744

**Comment by IgorMinar** [comment]
@yjbanov that pr is for angular/angular.dart and not for angular/angular

**Comment by yjbanov** [comment]
@IgorMinar that is right. AngularDart breaks us because we run external_benchmarks.

**Comment by IgorMinar** [comment]
ah! thanks

**Comment by yjbanov** [comment]
This is fixed now.

**Comment by rightisleft** [comment]
I get this when running alpha 44

$ pub get
...

Loading observe and smoke/src/default_transformer transformers...
The built-in library 'dart:profiler' is not available on the stand-alone VM.
'package:analyzer/src/generated/utilities_general.dart': error: line 10 pos 1: library handler failed
import 'dart:profiler';
^
dart:isolate-patch/isolate_patch.dart 404  Isolate._spawnUri
dart:isolate-patch/isolate_patch.dart 352  Isolate.spawnUri
package:pub/src/dart.dart 221              _isolateBuffer
dart:isolate-patch/isolate_patch.dart 266  _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 150  _RawReceivePortImpl._handleMessage

**Comment by yjbanov** [comment]
@rightisleft does `pub upgrade` help?
