### ISSUE TITLE
BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status

### ISSUE THREAD

**Issue by ashide2729** [angular/angular#46985]
### Which @angular/* package(s) are the source of the bug?

bazel

### Is this a regression?

Yes

### Description

When running 'yarn build' command in the angular root folder i am getting the following error

'BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status'

### Please provide the exception or error you saw

```true
ERROR: <builtin>: BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 1
C:\users\deshw\desktop\projects\angular\node_modules\ts-node\src\index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: Γ¿» Unable to compile TypeScript:
error TS5083: Cannot read file 'C:\.ng-dev\tsconfig.json'.

    at createTSError (C:\users\deshw\desktop\projects\angular\node_modules\ts-node\src\index.ts:843:12)
    at reportTSError (C:\users\deshw\desktop\projects\angular\node_modules\ts-node\src\index.ts:847:19)
    at createFromPreloadedConfig (C:\users\deshw\desktop\projects\angular\node_modules\ts-node\src\index.ts:858:36)
    at create (C:\users\deshw\desktop\projects\angular\node_modules\ts-node\src\index.ts:613:10)
    at register (C:\users\deshw\desktop\projects\angular\node_modules\ts-node\src\index.ts:580:15)
    at Object.registerAndCreateEsmHooks (C:\users\deshw\desktop\projects\angular\node_modules\ts-node\src\esm.ts:116:34)
    at file:///C:/users/deshw/desktop/projects/angular/node_modules/ts-node/esm.mjs:8:7       
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24) {
  diagnosticCodes: [ 5083 ]
}
INFO: Elapsed time: 40.438s, Critical Path: 2.02s
INFO: 287 processes: 285 internal, 2 local.
FAILED: Build did NOT complete successfully
Error: Command failed: yarn -s bazel build --config=snapshot-build //packages/animations:npm_package //packages/bazel:npm_package //packages/common:npm_package //packages/compiler:npm_package //packages/compiler-cli:npm_package //packages/core:npm_package //packages/elements:npm_package //packages/forms:npm_package //packages/language-service:npm_package //packages/localize:npm_package //packages/platform-browser:npm_package //packages/platform-browser-dynamic:npm_package //packages/platform-server:npm_package //packages/router:npm_package //packages/service-worker:npm_package //packages/upgrade:npm_package
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at exec (file:///C:/Users/deshw/Desktop/projects/angular/scripts/build/package-builder.mts:126:18)
    at buildReleasePackages (file:///C:/Users/deshw/Desktop/projects/angular/scripts/build/package-builder.mts:80:3)
    at performDefaultSnapshotBuild (file:///C:/Users/deshw/Desktop/projects/angular/scripts/build/package-builder.mts:45:10)
    at file:///C:/Users/deshw/Desktop/projects/angular/scripts/build/build-packages-dist.mts:17:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 936,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: Angular project from git with the latest pull
OS: Windows only as it is working for me in Mac
```

### Anything else?

Past discussion around the same issue: https://github.com/bazelbuild/bazel/issues/4802

**Comment by jessicajaniuk** [comment]
This is an issue with `ts-node` that affects Windows users. You can see #46780 as a reference, but the recommendation until that ts-node issue is fixed is to use git-bash.

**Comment by ashide2729** [comment]
thanks, using git bash worked
also, I see there was  a suggestion to add this in documentation until we support powershell/cmd
so if this will take time then I suggest we add this to the documentation
@jessicajaniuk @pkozlowski-opensource if you guys give a go ahead I can create a ticket along with PR for the same

**Comment by jessicajaniuk** [comment]
@ashide2729 Go right ahead! We'd appreciate the change.

**Comment by l1987lll** [comment]
There is still a similar issue when run yarn run build in git bash.
![image](https://user-images.githubusercontent.com/5010054/187062460-7b1070c7-9ff9-4b85-9a57-68d28f2bc5b3.png)

**Comment by JoostK** [comment]
@l1987lll That's a known issue due to a ts-node bug: #46858
