### ISSUE TITLE
Error: Optimization error [main-es2015.74a2d661cbb17311202b.js]

### ISSUE THREAD

**Issue by NareshSmith** [angular/angular#47005]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

After migrating our project from Angular Version 11.2.7 to 12.2.13., We are facing an Optimization error on production build in Jenkins, but when we try to build our project in local machine its working fine.
Kindly request some one to help fixing this issue ASAP. Please find the below error for your reference:

**Error: Optimization error [main-es2015.74a2d661cbb17311202b.js]: Error: The service was stopped
    at /docker/backup/.jenkins/workspace/xxx//xxx/node_modules/esbuild-wasm/lib/main.js:1276:29
    at /docker/backup/.jenkins/workspace//xxx//xxx/node_modules/esbuild-wasm/lib/main.js:629:9
    at Socket.afterClose (/docker/backup/.jenkins/workspace/xxx//xxx/node_modules/esbuild-wasm/lib/main.js:607:7)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)**

### Please provide the exception or error you saw

```true
Error: Optimization error [main-es2015.74a2d661cbb17311202b.js]: Error: The service was stopped
    at /docker/backup/.jenkins/workspace/xxx//xxx/node_modules/esbuild-wasm/lib/main.js:1276:29
    at /docker/backup/.jenkins/workspace//xxx//xxx/node_modules/esbuild-wasm/lib/main.js:629:9
    at Socket.afterClose (/docker/backup/.jenkins/workspace/xxx//xxx/node_modules/esbuild-wasm/lib/main.js:607:7)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
-------------------------------------------------------------
@angular-devkit/architect           0.1202.13
@angular-devkit/build-angular       12.2.13
@angular-devkit/core                12.2.13
@angular-devkit/schematics          12.2.13
@angular/animations                 12.2.3
@angular/cdk                        11.2.6
@angular/cli                        12.2.13
@angular/language-service           12.2.3
@angular/material                   11.2.6
@angular/material-moment-adapter    11.2.6
@angular/platform-browser-dynamic   12.2.3
@angular/router                     12.2.3
@schematics/angular                 11.2.6
ng-packagr                          12.2.7
rxjs                                6.6.7
typescript                          4.3.5
```

**Comment by jinadevi** [comment]
i am also facing the same issue pls help
