### ISSUE TITLE
Production build removes important information from error

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular#47076]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, it was working in some previous ng versions
### Description

Production minified build remove importannt information from error, while dev stays correct

## 🔬 Minimal Reproduction
Create app, make service with some unknown parameters

## 🔥 Exception or Error

DEV
<pre><code>
Uncaught Error: NG0204: Can't resolve all parameters for AuthHttpInterceptor: (?, ?, ?).
    at getUndecoratedInjectableFactory (core.mjs:6940:15)
    at injectableDefOrInjectorDefFactory (core.mjs:6930:16)
    at providerToFactory (core.mjs:6998:51)
    at providerToRecord (core.mjs:6960:25)
    at R3Injector.processProvider (core.mjs:6863:24)
    at core.mjs:6694:59
    at forEachSingleProvider (core.mjs:7034:13)
    at forEachSingleProvider (core.mjs:7031:13)
    at new R3Injector (core.mjs:6694:9)
    at new EnvironmentNgModuleRefAdapter (core.mjs:21774:26)
</code></pre>

PROD
<pre><code>
Uncaught Error: NG0204
    at ko (main.bae0f627af79e371.js:1:544663)
    at sc (main.bae0f627af79e371.js:1:545181)
    at dh (main.bae0f627af79e371.js:1:545572)
    at Q0 (main.bae0f627af79e371.js:1:543856)
    at la.processProvider (main.bae0f627af79e371.js:1:543866)
    at main.bae0f627af79e371.js:1:541614
    at bd (main.bae0f627af79e371.js:1:545810)
    at bd (main.bae0f627af79e371.js:1:545786)
    at new la (main.bae0f627af79e371.js:1:541601)
    at new ig (main.bae0f627af79e371.js:1:588517)
    at yf (main.bae0f627af79e371.js:1:588800)
    at main.bae0f627af79e371.js:1:609449
    at v.invoke (polyfills.d621b0e3244453cd.js:1:6539)
    at Object.onInvoke (main.bae0f627af79e371.js:1:604415)
    at v.invoke (polyfills.d621b0e3244453cd.js:1:6479)
    at M.run (polyfills.d621b0e3244453cd.js:1:1935)
    at Qo.run (main.bae0f627af79e371.js:1:605036)
    at jD (main.bae0f627af79e371.js:1:609432)
    at on (main.bae0f627af79e371.js:1:634979)
    at 2730 (main.bae0f627af79e371.js:1:275935)
    at r (runtime.c90347ac34a249b3.js:1:143)
    at main.bae0f627af79e371.js:1:802061
    at n (runtime.c90347ac34a249b3.js:1:2856)
    at main.bae0f627af79e371.js:1:47
</code></pre>
## 🌍 Your Environment

<pre><code>
Angular CLI: 14.1.1
Node: 14.18.2
Package Manager: yarn 3.2.1
OS: win32 x64

Angular: 14.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.1 (cli-only)
@angular-devkit/build-angular   14.1.1
@angular-devkit/core            14.1.1 (cli-only)
@angular-devkit/schematics      14.1.1 (cli-only)
@schematics/angular             14.1.1 (cli-only)
rxjs                            7.5.6
typescript                      4.7.4
</code></pre>

**Comment by alan-agius4** [comment]
This is because certain error information tree-shaken when `ngDevMode` is false.

**Comment by Lonli-Lokli** [comment]
I understand that, but I am sure that `Can't resolve all parameters for AuthHttpInterceptor: (?, ?, ?).` shouldn't be tree-shaken, it's too important.

Also, this error is not documented - there is no NG0204 here in the tree or url, like https://angular.io/errors/NG0203

**Comment by AndrewKushnir** [comment]
@Lonli-Lokli this is working as intended: we optimize production builds to remove all dev-mode-only content (in this case, the error message string as well as supporting code to produce it). We are adding more error guides incrementally, but didn't have a chance to do that for this particular error and we'd welcome a community contribution on this (or any other error message guide).

**Comment by Lonli-Lokli** [comment]
@AndrewKushnir @alan-agius4 I can understand that you would like to minimize bundle and remove strings which are static, but `AuthHttpInterceptor: (?, ?, ?)` obviously is a runtime information and so cannot increase bundle size.

Why you don't want to include that? In theory prod build can produce result different than dev, so might be situation when this error do not occur in dev

**Comment by alan-agius4** [comment]
> Why you don't want to include that? In theory prod build can produce result different than dev, so might be situation when this error do not occur in dev

That shouldn’t not happen.
