### ISSUE TITLE
Angular dependency injection in constructor functions does not work in a rails app with webpacker v6.0.0.rc.5 + webpack5

### ISSUE THREAD

**Issue by patrick99e99** [angular/angular#47317]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

A rails app involving  v6.0.0.rc.5 + webpack5 + angular for some reason cannot handle:
`constructor (service: MyService) { }`

It throws:
>core.mjs:7643 ERROR Error: NG0202: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid. This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

However if I do instead:
```
constructor () {
  this.service = inject(MyService)
}
```

Then it works fine...  I have posted about this on stackoverflow, but no one has answered me --> https://stackoverflow.com/questions/73548046/webpack-seems-to-be-breaking-dependency-injection-in-angular

I have created a repo out of desperation with detailed steps in the README on how to reproduce.

### Please provide a link to a minimal reproduction of the bug

https://github.com/patrick99e99/angular-dependency-injection

### Please provide the exception or error you saw

```true
core.mjs:7643 ERROR Error: NG0202: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid. This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors. at ɵɵinvalidFactoryDep (core.mjs:4798:1) at NodeInjectorFactory.AppComponent_Factory [as factory] (ɵfac.js? [sm]:1:1) at getNodeInjectable (core.mjs:3523:1) at instantiateRootComponent (core.mjs:12580:1) at createRootComponent (core.mjs:14048:1) at ComponentFactory.create (core.mjs:13925:1) at ApplicationRef.bootstrap (core.mjs:27360:1) at core.mjs:27020:1 at Array.forEach () at PlatformRef._moduleDoBootstrap (core.mjs:27020:1) handleError @ core.mjs:7643 (anonymous) @ core.mjs:27101 invoke @ zone.js:372 run @ zone.js:134 runOutsideAngular @ core.mjs:26190 (anonymous) @ core.mjs:27101 invoke @ zone.js:372 onInvoke @ core.mjs:26291 invoke @ zone.js:371 run @ zone.js:134 (anonymous) @ zone.js:1275 invokeTask @ zone.js:406 onInvokeTask @ core.mjs:26278 invokeTask @ zone.js:405 runTask @ zone.js:178 drainMicroTaskQueue @ zone.js:585 Promise.then (async) nativeScheduleMicroTask @ zone.js:561 scheduleMicroTask @ zone.js:572 scheduleTask @ zone.js:396 scheduleTask @ zone.js:221 scheduleMicroTask @ zone.js:241 scheduleResolveOrReject @ zone.js:1265 then @ zone.js:1461 bootstrapModule @ core.mjs:27015 ./app/javascript/packs/application.ts @ application.ts:5 webpack_require @ bootstrap:19 webpack_exec @ application.ts:5 (anonymous) @ application.ts:5 webpack_require.O @ chunk loaded:23 (anonymous) @ application.ts:5 webpackJsonpCallback @ jsonp chunk loading:34 (anonymous) @ application.js:2 zone.js:372 Error: NG0202: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid. This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

Please check that 1) the type for the parameter at index 0 is correct and 2) the correct Angular decorators are defined for this class and its ancestors. at ɵɵinvalidFactoryDep (core.mjs:4798:1) at NodeInjectorFactory.AppComponent_Factory [as factory] (ɵfac.js? [sm]:1:1) at getNodeInjectable (core.mjs:3523:1) at instantiateRootComponent (core.mjs:12580:1) at createRootComponent (core.mjs:14048:1) at ComponentFactory.create (core.mjs:13925:1) at ApplicationRef.bootstrap (core.mjs:27360:1) at core.mjs:27020:1 at Array.forEach () at PlatformRef._moduleDoBootstrap (core.mjs:27020:1)>
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
I am using webpack directly via the rails webpacker gem, not using the cli, but here it is anyway..

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.2.1
Node: 14.19.2
Package Manager: npm 8.7.0
OS: darwin arm64

Angular: 14.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cli                    14.2.1
@schematics/angular             14.2.1
rxjs                            7.4.0
```

### Anything else?

I am really hopeful someone can explain to me why this is not working...  Thank you.

**Comment by patrick99e99** [comment]
I found: https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_webpack/test/angular-app/angular.json

Which pointed me in the right direction..  I believe my issues was ts-loader is what breaks dependency injection.  So changing that to use @ngtools/webpack solved my problem, so I am closing this.
