### ISSUE TITLE
Angular Dev Tools - Can't use when 3rd party adds empty div to DOM

### ISSUE THREAD

**Issue by macgregor-thompson** [angular/angular#47357]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

We rely on several third party tools in our app for our marketing team and help desk, etc.  

App Cues, Segment, Intercom, and more.

At some point, one of them adds a couple of empty divs to the dom and this crashes/prevents Angular Dev Tools from working.

Here is a link to the open issue from the old repo.  Our entire dev team would love to use these dev tools, but it's not possible.

https://github.com/rangle/angular-devtools/issues/910

### Please provide the exception or error you saw

```true
polyfills.js:22576 Uncaught Error: ASSERTION ERROR: The provided value must be an instance of a DOM Node but got [object HTMLScriptElement]
    at throwError (vendor.js:215325:9)
    at assertDomNode (vendor.js:215331:5)
    at getLContext (vendor.js:224057:18)
    at getDirectives (vendor.js:240462:19)
    at kt (render-tree.ts:15:26)
    at render-tree.ts:52:23
    at NodeList.forEach (<anonymous>)
    at kt (render-tree.ts:51:28)
    at render-tree.ts:52:23
    at NodeList.forEach (<anonymous>)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.1
Node: 16.14.2
Package Manager: npm 8.5.0 
OS: darwin arm64

Angular: 14.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      12.2.18
@angular/cli                    14.2.1
@angular/flex-layout            14.0.0-beta.40
@schematics/angular             14.2.1
rxjs                            7.5.6
typescript                      4.8.2
webpack                         5.74.0
```

**Comment by AleksanderBodurri** [comment]
I'll look into the best way to fix this in the next couple of days. @mhthompson86 Thank you for opening this issue 🙏 

For readers an explanation of why this happens is available here: https://github.com/rangle/angular-devtools/issues/910#issuecomment-905206933

**Comment by yhaiovyi-tripactions** [comment]
Quite craze it's still an issue.

**Comment by chrised123** [comment]
was able to reproduce this even in angular 17.0.6

**Comment by bulldog98** [comment]
Strange thing is for me the reproduction works with the firefox plugin, but not with the chromium one.

**Comment by Sammaye** [comment]
I am finding this happen once every so often depending on how fast the app loads,  if the app is slow then it never happens but if the app is fast then it happens all the time when using intercom, all I do is comment out the script loader and it works fine with no errors

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular/pull/57518
