### ISSUE TITLE
angular2 Alpha42 routing error

### ISSUE THREAD

**Issue by Nayyarjamal** [angular/angular#4759]
***this is my app.ts***

```
import {Component, View, CORE_DIRECTIVES, bootstrap} from 'angular2/angular2';
import {RouteConfig, ROUTER_DIRECTIVES, ROUTER_BINDINGS} from 'angular2/router';

import {NavbarApp} from './components/navbar/navbar';


@Component({
  selector: 'app',
})

@RouteConfig([
  { path: '/navbar', component: NavbarApp, as: 'NavbarCmp' }
])

@View({
  template: `<a [router-link]="['/navbar']">navbar</a>`,
  directives: [CORE_DIRECTIVES, ROUTER_DIRECTIVES]
})
class App {}

bootstrap(App, [ROUTER_BINDINGS]);
```
***this is my navbar.ts***
```
import {Component, View} from 'angular2/angular2';

@Component({
  selector: 'navbar-app',
})
@View({
  template : '<h1>hiii</h1>'
 })
 
export class NavbarApp {
  
}
```
***this is my index.html***
```
<html>
	<head>
		<meta charset="UTF-8">
		<title>Angular 2 Quickstart</title>
		<base href="/">
  		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.js"></script>
 		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css">
		<script src="node_modules/angular2/bundles/traceur-runtime.js"></script>
		<script src="node_modules/angular2/bundles/system.src.js"></script>
		<script>
   
            System.config({
                defaultJSExtensions: true,
                transpiler: 'typescript',
                typescriptOptions: {
                emitDecoratorMetadata: true
                },
                map: {
                typescript: 'typescript.js',
                }
            });
        </script>

        <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
        <script src="node_modules/angular2/bundles/router.dev.js"></script>
        
        
	</head>
	<body>
	
		<app>loading...</app>
		<script>
   
            System.import('app').catch(console.log.bind(console));
        </script>
       
		
	</body>
</html>


```
***i am getting this error***
```
EXCEPTION: Component "App" has no route named "navbar". in [null]
angular2.dev.js:19231 EXCEPTION: Component "App" has no route named "navbar". in [null]BrowserDomAdapter.logError @ angular2.dev.js:19231BrowserDomAdapter.logGroup @ angular2.dev.js:19242ExceptionHandler.call @ angular2.dev.js:4431(anonymous function) @ angular2.dev.js:19957NgZone._onError @ angular2.dev.js:10622errorHandling.onError @ angular2.dev.js:10541run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10581run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:19231 ORIGINAL EXCEPTION: Component "App" has no route named "navbar".BrowserDomAdapter.logError @ angular2.dev.js:19231ExceptionHandler.call @ angular2.dev.js:4440(anonymous function) @ angular2.dev.js:19957NgZone._onError @ angular2.dev.js:10622errorHandling.onError @ angular2.dev.js:10541run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10581run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:19231 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:19231ExceptionHandler.call @ angular2.dev.js:4443(anonymous function) @ angular2.dev.js:19957NgZone._onError @ angular2.dev.js:10622errorHandling.onError @ angular2.dev.js:10541run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10581run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:19231 Error: Component "App" has no route named "navbar".
    at new BaseException (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:16007:21)
    at RouteRegistry.generate (http://127.0.0.1:8080/node_modules/angular2/bundles/router.dev.js:1661:17)
    at RootRouter.Router.generate (http://127.0.0.1:8080/node_modules/angular2/bundles/router.dev.js:2044:43)
    at RouterLink.Object.defineProperty.set [as routeParams] (http://127.0.0.1:8080/node_modules/angular2/bundles/router.dev.js:1323:52)
    at AbstractChangeDetector.ChangeDetector_App_0.detectChangesInRecordsInternal (eval at <anonymous> (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:20829:14), <anonymous>:43:40)
    at AbstractChangeDetector.detectChangesInRecords (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:20623:14)
    at AbstractChangeDetector.runDetectChanges (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:20606:12)
    at AbstractChangeDetector._detectChangesInShadowDomChildren (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:20673:14)
    at AbstractChangeDetector.runDetectChanges (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:20610:12)
    at AbstractChangeDetector.detectChanges (http://127.0.0.1:8080/node_modules/angular2/bundles/angular2.dev.js:20597:12)BrowserDomAdapter.logError @ angular2.dev.js:19231ExceptionHandler.call @ angular2.dev.js:4444(anonymous function) @ angular2.dev.js:19957NgZone._onError @ angular2.dev.js:10622errorHandling.onError @ angular2.dev.js:10541run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10581run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:19231 ERROR CONTEXT:BrowserDomAdapter.logError @ angular2.dev.js:19231ExceptionHandler.call @ angular2.dev.js:4447(anonymous function) @ angular2.dev.js:19957NgZone._onError @ angular2.dev.js:10622errorHandling.onError @ angular2.dev.js:10541run @ angular2.dev.js:141(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1507lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1519lib$es6$promise$$internal$$publish @ angular2.dev.js:1490(anonymous function) @ angular2.dev.js:219microtask @ angular2.dev.js:10581run @ angular2.dev.js:138(anonymous function) @ angular2.dev.js:10555zoneBoundFn @ angular2.dev.js:111lib$es6$promise$asap$$flush @ angular2.dev.js:1301
angular2.dev.js:19231 _Context {element: a, componentElement: app, context: App, locals: Object, injector: Injector…}
```

**Comment by PascalPrecht** [comment]
@Nayyarjamal this is because the `[router-link]` consumes a DSL where you use the alias (`as`) of your route configuration.

Try `[router-link]="['/NavBarCmp']"`

**Comment by Nayyarjamal** [comment]
now its working.. thanks :+1: :blush:

**Comment by evanplaice** [comment]
References:

- Changelog [angular@2.0.0-alpha.38][changelog] 
- Issue #4083
- Commit 5298eb0709dd85081372e89c6f81bebdfaaefd94

[changelog]: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha38-2015-10-03
