### ISSUE TITLE
 NullInjectorError: No provider for TranslateService!

### ISSUE THREAD

**Issue by RihabEA** [angular/angular#47691]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi,

After upgrade angular from 14.1.0 to 14.2.5, an error occurred when run my unit tests :

NullInjectorError: R3InjectorError(CompilerModule)[TranslateService -> TranslateService]:
      NullInjectorError: No provider for TranslateService!
    error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'TranslateService', 'TranslateService' ] })

PS: in the app.module.ts I added the TranslateModule:

export function HttpLoaderFactory(http: HttpClient): TranslateLoader {
    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({
    imports: [
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [HttpClient]
            }
        }),
        SharedModule
    ],
    declarations: [
        AppComponent
    ],
    providers: [
        {
            provide: APP_INITIALIZER,
            useFactory: loadAgGridLicense,
            multi: true,
            deps: [LicenseService]
        }
    ]

and in the test file I added the below code:

imports: [
        TranslateModule.forRoot({}),
        HttpClientModule
    ],
    exports: [
        HttpClientModule,
        TranslateModule,
        TranslatePipe
    ]

### Please provide the exception or error you saw

```true
NullInjectorError: R3InjectorError(CompilerModule)[TranslateService -> TranslateService]:
      NullInjectorError: No provider for TranslateService!
    error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'TranslateService', 'TranslateService' ] })
        at NullInjector.get (node_modules/@angular/core/fesm2020/core.mjs:6359:27)
        at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:6786:33)
        at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:6786:33)
        at TestBedImpl.inject (node_modules/@angular/core/fesm2020/testing.mjs:26162:62)
        at Function.inject (node_modules/@angular/core/fesm2020/testing.mjs:26028:37)
        at UserContext.apply (test/app/shared/core/services/i18n.service.spec.ts:18:28)
        at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:26)
        at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:39)
        at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:371:52)
        at Zone.run (node_modules/zone.js/fesm2015/zone.js:134:43)
        at runInTestZone (node_modules/zone.js/fesm2015/zone-testing.js:582:34)
        at UserContext.<anonymous> (node_modules/zone.js/fesm2015/zone-testing.js:597:20)
        at <Jasmine>
        at _ZoneDelegate.invokeTask (node_modules/zone.js/fesm2015/zone.js:406:31)
        at Zone.runTask (node_modules/zone.js/fesm2015/zone.js:178:47)
        at drainMicroTaskQueue (node_modules/zone.js/fesm2015/zone.js:585:35)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/cli: 14.2.5,
Node: 16.16.0
Package manager: yarn 1.22.19
OS: windows 11
Angular: 14.2.5
```

**Comment by JoostK** [comment]
Please provide a runnable reproduction of the issue.

**Comment by RihabEA** [comment]
I don't think I can, because the issue occurred when I run the unit test

**Comment by JoostK** [comment]
Without a reproduction we won't be able to investigate.

**Comment by jessicajaniuk** [comment]
I'm going to close this as not actionable for us. It also seems to fall in the category of support request, which is something we don't cover in the issue tracker. You're welcome to post the issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
