### ISSUE TITLE
Issue with angular matdialog

### ISSUE THREAD

**Issue by dileep999999** [angular/angular#47743]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When we try to open a matdialog from the solution the _parentDialog is being set as empty object hence in the openDialogs()
as the we have an empty object it is taking this._parentDialog.openDialogs which is being called in the getDialogById() where we are trying to find the value of a null item 

Fix: in the openDialogs() please provide  a condition to check if there are any openDialogs 

return this._parentDialog && this._parentDialog.openDialogs ? this._parentDialog.openDialogs : this._openDialogsAtThisLevel;

### Please provide the exception or error you saw

```true
core.mjs:7621 ERROR TypeError: Cannot read properties of undefined (reading 'find')
    at Ye.getDialogById (dialog.mjs:511:33)
    at Ye.open (dialog.mjs:481:18)
    at Re.open (dialog.mjs:481:37)
    at n.showConfirmDialog (contact-options.component.ts:1111:28)
    at n.goToPhone (contact-options.component.ts:1095:18)
    at n.goTo (contact-options.component.ts:974:22)
    at contact-options.component.html:193:214
    at Ip (core.mjs:15624:16)
    at g (core.mjs:15659:22)
    at HTMLDivElement.<anonymous> (platform-browser.mjs:463:38)
handleError @ core.mjs:7621
handleError @ frontend-vanilla-core.mjs:6741
gp @ core.mjs:13269
Ip @ core.mjs:15627
g @ core.mjs:15659
(anonymous) @ platform-browser.mjs:463
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:26194
invokeTask @ zone.js:405
runTask @ zone.js:178
invokeTask @ zone.js:487
Ct @ zone.js:1661
Lt @ zone.js:1692
Ht @ zone.js:1725
```

**Comment by dileep999999** [comment]
issue will come if the _parentDialog is empty object
