### ISSUE TITLE
NullInjectorError: No provider for TranslateService!

### ISSUE THREAD

**Issue by RihabEA** [angular/angular#47742]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After upgrade angular from 14.1.0 to 14.2.5, an error occurred when run my unit tests :

NullInjectorError: R3InjectorError(CompilerModule)[TranslateService -> TranslateService]:
NullInjectorError: No provider for TranslateService!
error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'TranslateService', 'TranslateService' ] })

Kindly find below the Github repo link for my issue

### Please provide a link to a minimal reproduction of the bug

https://github.com/RihabEA/Angular-14-ngx-translate

### Please provide the exception or error you saw

```true
NullInjectorError: R3InjectorError(CompilerModule)[TranslateService -> TranslateService]:
      NullInjectorError: No provider for TranslateService!
    error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'TranslateService', 'TranslateService' ] })
        at NullInjector.get (node_modules/@angular/core/fesm2020/core.mjs:6359:27)
        at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:6786:33)
        at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:6786:33)
        at TestBedImpl.inject (node_modules/@angular/core/fesm2020/testing.mjs:26162:62)
        at Function.inject (node_modules/@angular/core/fesm2020/testing.mjs:26028:37)
        at UserContext.apply (test/app/shared/core/services/i18n.service.spec.ts:18:28)
        at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:26)
        at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:39)
        at _ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:371:52)
        at Zone.run (node_modules/zone.js/fesm2015/zone.js:134:43)
        at runInTestZone (node_modules/zone.js/fesm2015/zone-testing.js:582:34)
        at UserContext.<anonymous> (node_modules/zone.js/fesm2015/zone-testing.js:597:20)
        at <Jasmine>
        at _ZoneDelegate.invokeTask (node_modules/zone.js/fesm2015/zone.js:406:31)
        at Zone.runTask (node_modules/zone.js/fesm2015/zone.js:178:47)
        at drainMicroTaskQueue (node_modules/zone.js/fesm2015/zone.js:585:35)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular/cli: 14.2.5,
Node: 16.16.0
Package manager: yarn 1.22.19
OS: windows 11
Angular: 14.2.5
```

**Comment by jnizet** [comment]
You're not setting up the testing module in your test, and TranslateService is not providedIn: root. 

Add

```ts
    TestBed.configureTestingModule({
      imports: [TranslateModule.forRoot()]
    });
```

in your beforeEach.

**Comment by RihabEA** [comment]
I already wrote that in test/support/test-helper-app.module.ts, and I tried your solution directly in the configureTestingModule, it doesn't work!

**Comment by JoostK** [comment]
You are resetting `TestBed.resetTestingModule` on the static `TestBed` symbol, which is just a delegate method that is not the one being called internally by `TestBed` hence the second test doesn't include the `TestHelperAppModule` NgModule. Attempts to rewrite Angular API like this is not something we support.
