### ISSUE TITLE
angular2 Alpha42 gulp error

### ISSUE THREAD

**Issue by Nayyarjamal** [angular/angular#4783]
i have get a project from a repository [GitHub](https://github.com/shatakshidixit1/shatakshiGulpBrowsersync) 

when i try to run this project it works first time but after some time it automatically disconnects and shows following errors

```
sourabh@1233:~/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject$ npm run gulp

> gulpProject@0.0.0 gulp /home/sourabh/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject
> gulp

[11:36:21] Using gulpfile ~/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject/gulpfile.js
[11:36:21] Starting 'ts-lint'...
[11:36:21] Starting 'compile-ts'...
app.ts(6,19): error TS2307: Cannot find module 'components/nav/nav'.
[11:36:27] TypeScript: 1 semantic error
[11:36:27] TypeScript: emit succeeded (with errors)
[11:36:28] [gulp-tslint] error app.ts[21, 10]: trailing whitespace
[11:36:28] [gulp-tslint] error app.ts[22, 2]: trailing whitespace
[11:36:28] [gulp-tslint] error app.ts[3, 9]: unused variable: 'RouteConfig'
[11:36:28] Finished 'ts-lint' after 6.82 s
[11:36:28] Finished 'compile-ts' after 6.82 s
[11:36:28] Starting 'serve'...
[11:36:28] Finished 'serve' after 254 ms
[11:36:28] Starting 'default'...
[11:36:28] Finished 'default' after 13 μs
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/gulp/node_modules/gulp-util/node_modules/dateformat/node_modules/meow/node_modules/normalize-package-data/node_modules/validate-npm-package-license/index.js ENOSPC
    at exports._errnoException (util.js:874:11)
    at FSWatcher.start (fs.js:1239:19)
    at Object.fs.watch (fs.js:1267:11)
    at createFsWatchInstance (/home/sourabh/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/sourabh/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/sourabh/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/home/sourabh/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/home/sourabh/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:468:21)
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gulp"
npm ERR! node v4.2.0
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! gulpProject@0.0.0 gulp: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gulpProject@0.0.0 gulp script 'gulp'.
npm ERR! This is most likely a problem with the gulpProject package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls gulpProject
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sourabh/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject/npm-debug.log

```

**Comment by shatakshidixit1** [comment]
@Nayyarjamal  You just have to clone my repository and use the command gulp not npm run gulp.
Is your browserSync is Connecting?

**Comment by Nayyarjamal** [comment]
@shatakshidixit1 i have tried this too. but still its not working it shows another error if i use "gulp" to run the project

***error***

```
sourabh@1233:~/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject$ gulp
No command 'gulp' found, did you mean:
Command 'gslp' from package 'ghostscript' (main)
gulp: command not found
sourabh@1233:~/Documents/angular2gulp/shatakshiGulpBrowsersync/gulpProject$ 
```

**Comment by robwormald** [comment]
@Nayyarjamal this looks like a problem specific to your project setup itself - you might try asking in the gitter channel or on stackoverflow. Please try to use GitHub only for reporting issues specific to the framework itself, thanks! :octocat: 

Closing this, but feel free to discuss with @shatakshidixit1 

See also gitter.im/angular/angular
