### ISSUE TITLE
bug(MatFormField): Prerendering Angular universal fails

### ISSUE THREAD

**Issue by Tom4U** [angular/angular#47928]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If running `npm run prerender` and a component template, considered for prerendering, contains a MatFormField component, the prerendering fails:

```
⠋ Prerendering 6 route(s) to <DRIVE_LETTER>:\<project>\dist\<project>\browser...Unhandled Promise rejection: Cannot read properties of undefined (reading 'type') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading 'type')
    at TokenStream.LA (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:626334)
    at TokenStream.advance (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:624983)
    at Parser._readDeclarations (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:659046)
    at Parser.parseStyleAttribute (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:660636)
    at parseStyles (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:344961)
    at CSSStyleDeclaration.get (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:345316)
    at CSSStyleDeclaration.value (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:346137)
    at CSSStyleDeclaration.get (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:359933)
    at cloakElement (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:3558188)
    at <DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:3558406 TypeError: Cannot read properties of undefined (reading 'type')      
    at TokenStream.LA (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:626334)
    at TokenStream.advance (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:624983)
    at Parser._readDeclarations (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:659046)
    at Parser.parseStyleAttribute (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:660636)
    at parseStyles (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:344961)
    at CSSStyleDeclaration.get (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:345316)
    at CSSStyleDeclaration.value (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:346137)
    at CSSStyleDeclaration.get (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:359933)
    at cloakElement (<DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:3558188)
    at <DRIVE_LETTER>:\<project>\dist\<project>\server\main.js:1:3558406
✖ Prerendering routes to <DRIVE_LETTER>:\<project>\dist\<project>\browser failed.
Cannot read properties of undefined (reading 'type')
```

### Reproduction

Steps to reproduce:
1. install **nguniversal/express-engine**
2. import **MatFormFieldModule** and **MatInputModule**
3. add code to a component template:
   ```html
   <form class="form">
        <mat-form-field appearance="fill">
            <input matInput>                
        </mat-form-field>
    </form>
   ```
4. run `npm run prerender`

### Expected Behavior

Prerendering should not fail.

### Actual Behavior

Prerendering fails.

### Environment

```
@angular-devkit/architect       0.1402.7
@angular-devkit/build-angular   14.2.7
@angular-devkit/core            14.2.7
@angular-devkit/schematics      14.2.7
@angular/cdk                    14.2.6
@angular/cli                    14.2.7
@angular/fire                   7.4.1
@angular/material               14.2.6
@nguniversal/builders           14.2.0
@nguniversal/express-engine     14.2.0
@schematics/angular             14.2.7
ng-packagr                      14.2.2
rxjs                            7.5.7
typescript                      4.7.4
```
- Browser(s): not relevant
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11

**Comment by crisbeto** [comment]
It looks like this is captured already in https://github.com/angular/angular/issues/42170. Closing as a duplicate.
