### ISSUE TITLE
Angular doesn't find module - why?

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#4829]
I have set up a simple and small text application for using ui-grid/RequireJS.

My problem with the setup below is that Angular starts searching for the ng-app directive before the HTML has finished loading. So randomly I get an Angular error stating that module "gridtest" could not be found:

```
 [$injector:modulerr] Failed to instantiate module gridtest due to:

Error: [$injector:nomod] Module 'gridtest' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

http://errors.angularjs.org/1.4.7/$injector/nomod?p0=gridtest
   at Anonymous function (http://localhost:2920/_Mocks/uiGuid/js/angular.js:1986:11)
   at ensure (http://localhost:2920/_Mocks/uiGuid/js/angular.js:1910:5)
   at module (http://localhost:2920/_Mocks/uiGuid/js/angular.js:1984:7)
...
```

What am I doing wrong? Why is AngularJS searching for the module before the DOM has completely been loaded?

Here's my source:
```javascript
require(["uiGrid"], function ()
{
    angular.module("gridtest", ["ui.grid"])
    .factory("loaddata", ["$http", function ($http)
    {
        return function ()
        {
            return [
                { name: "John", Address: "Texas" },
                { name: "Doe", Address: "Florida" }
            ];
        };
    }])
    .controller("gridCtrl", ["$scope", "loaddata", function ($scope, loaddata)
    {
        $scope.data = loaddata();
    }]);
});
```

```html
<!DOCTYPE html>
<html>
<head>
    <title>jqGrid Test Page</title>
    <link type="text/css" rel="stylesheet" href="css/ui-grid.min.css" />
</head>
<body ng-app="gridtest">
    <div ng-controller="gridCtrl" style="padding: 2em; background-image: linear-gradient(rgb(56,77,112), white)">
        <div ui-grid="{ data: data }"></div>
    </div>

    <script type="text/javascript">
        var require =
            {
                paths:
                    {
                        jquery: "../../../Content/js/jquery-2.1.4/jquery-2.1.4.min",
                        angular: "angular",
                        uiGrid: "ui-grid.min"
                    },
                shim:
                    {
                        "angular": { deps: ["jquery"] },
                        "uiGrid": { deps: ["angular"] }
                    }

            };
    </script>
    <script type="text/javascript" src="js/require.js" defer="defer" data-main="js/GridTest.js"></script>
</body>
</html>
```

**Comment by ericmartinezr** [comment]
Hey @SetTrend this repo is for ng2, you are looking for this one https://github.com/angular/angular.js :v:

**Comment by SetTrend** [comment]
Oops... Sorry, I didn't recognize the distinction!! \*blush\*
