### ISSUE TITLE
TypeError while using Forms: Cannot read properties of null (reading '_rawValidators')

### ISSUE THREAD

**Issue by musheghz** [angular/angular#48379]
### Description

core.mjs:9229 ERROR TypeError: Cannot read properties of null (reading '_rawValidators')
    at getControlValidators (forms.mjs:901:20)
    at setUpValidators (forms.mjs:3110:24)
    at setUpControl (forms.mjs:3031:5)
    at FormGroupDirective.addControl (forms.mjs:4927:9)
    at FormControlName._setUpControl (forms.mjs:5491:43)
    at FormControlName.ngOnChanges (forms.mjs:5436:18)
    at FormControlName.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:1779:14)
    at callHook (core.mjs:2762:18)
    at callHooks (core.mjs:2721:17)
    at executeInitAndCheckHooks (core.mjs:2672:9)

### Proposed solution

I think somehow we can add missed field name

### Alternatives considered

This will help with dynamic forms

**Comment by AndrewKushnir** [comment]
@musheghz could you please create a repro using [StackBlitz](https://stackblitz.com), so that we can investigate what causes the problem in that scenario (to see how to handle it better)?

**Comment by musheghz** [comment]
@AndrewKushnir thank you for your response.

This is not an issue. it is very easy. when you use formControlName and do not add it to your formControls in component.ts, then you will see issue Cannot read properties of null (reading '_rawValidators'), we can have more clear message here for example, you do not declares **** control name.

**Comment by AndrewKushnir** [comment]
@musheghz I'm looking at the Forms code and there are a number of places that verify whether a control is defined, so it'd be helpful to have a repro that leads to that particular error. In this case we'll be able to see a code path where an error handling can be added.
