### ISSUE TITLE
error: no member named 'kFinalizer' when installing dependencies from scratch

### ISSUE THREAD

**Issue by aegonz** [angular/angular#48599]
### Is this a bug report or a feature request?

- [ ] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

1. Create a new project
2. Remove node_modules folder
3. re-install dependencies

> Host: `macOS Monterey Version 12.6`
> Chip: `Apple M1 Pro`
> Node: `v18.12.1`
> npm: `8.19.2`
> clang: 
> 
> > Apple clang version 14.0.0 (clang-1400.0.29.202)
> Target: arm64-apple-darwin21.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> 
> XCode  tools: `xcode-select version 2395`
> 

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

The package `fibers` is being used by `"@angular-devkit/build-angular": "^15.0.4"` but it is incompatible with Node version 16 and up. The latest LTS is Node 18.

### Please provide a screenshot if possible [Bug Report only]

```
1445 verbose stack Error: command failed
1445 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
1445 verbose stack     at ChildProcess.emit (node:events:513:28)
1445 verbose stack     at maybeClose (node:internal/child_process:1091:16)
1445 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
1445 verbose stack     at Socket.emit (node:events:513:28)
1445 verbose stack     at Pipe.<anonymous> (node:net:313:12)
1446 verbose pkgid fibers@5.0.3
1447 verbose cwd /Users/redacted/projects/my-app
1448 verbose Darwin 21.6.0
1449 verbose node v18.12.1
1450 verbose npm  v8.19.2
1451 error code 127
1452 error path /Users/redacted/projects/my-app/node_modules/fibers
1453 error command failed
1454 error command sh -c -- node build.js || nodejs build.js
1455 error `darwin-arm64-108` exists; testing
1455 error Problem with the binary; manual build incoming
1455 error   CXX(target) Release/obj.target/fibers/src/fibers.o
1456 error gyp info it worked if it ends with ok
1456 error gyp info using node-gyp@8.4.1
1456 error gyp info using node@18.12.1 | darwin | arm64
1456 error gyp info find Python using Python version 3.10.9 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
1456 error gyp info spawn /opt/homebrew/opt/python@3.10/bin/python3.10
1456 error gyp info spawn args [
1456 error gyp info spawn args   '/Users/redacted/projects/my-app/node_modules/node-gyp/gyp/gyp_main.py',
1456 error gyp info spawn args   'binding.gyp',
1456 error gyp info spawn args   '-f',
1456 error gyp info spawn args   'make',
1456 error gyp info spawn args   '-I',
1456 error gyp info spawn args   '/Users/redacted/projects/my-app/node_modules/fibers/build/config.gypi',
1456 error gyp info spawn args   '-I',
1456 error gyp info spawn args   '/Users/redacted/projects/my-app/node_modules/node-gyp/addon.gypi',
1456 error gyp info spawn args   '-I',
1456 error gyp info spawn args   '/Users/redacted/Library/Caches/node-gyp/18.12.1/include/node/common.gypi',
1456 error gyp info spawn args   '-Dlibrary=shared_library',
1456 error gyp info spawn args   '-Dvisibility=default',
1456 error gyp info spawn args   '-Dnode_root_dir=/Users/redacted/Library/Caches/node-gyp/18.12.1',
1456 error gyp info spawn args   '-Dnode_gyp_dir=/Users/redacted/projects/my-app/node_modules/node-gyp',
1456 error gyp info spawn args   '-Dnode_lib_file=/Users/redacted/Library/Caches/node-gyp/18.12.1/<(target_arch)/node.lib',
1456 error gyp info spawn args   '-Dmodule_root_dir=/Users/redacted/projects/my-app/node_modules/fibers',
1456 error gyp info spawn args   '-Dnode_engine=v8',
1456 error gyp info spawn args   '--depth=.',
1456 error gyp info spawn args   '--no-parallel',
1456 error gyp info spawn args   '--generator-output',
1456 error gyp info spawn args   'build',
1456 error gyp info spawn args   '-Goutput_dir=.'
1456 error gyp info spawn args ]
1456 error gyp info spawn make
1456 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
1456 error ../src/fibers.cc:27:65: error: no member named 'kFinalizer' in 'v8::WeakCallbackType'
1456 error                 handle.SetWeak(val, WeakCallbackShim<F, P>, WeakCallbackType::kFinalizer);
1456 error                                                             ~~~~~~~~~~~~~~~~~~^
1456 error 1 error generated.
1456 error make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
1456 error gyp ERR! build error 
1456 error gyp ERR! stack Error: `make` failed with exit code: 2
1456 error gyp ERR! stack     at ChildProcess.onExit (/Users/redacted/projects/my-app/node_modules/node-gyp/lib/build.js:194:23)
1456 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
1456 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
1456 error gyp ERR! System Darwin 21.6.0
1456 error gyp ERR! command "/usr/local/bin/node" "/Users/redacted/projects/my-app/node_modules/.bin/node-gyp" "rebuild" "--release"
1456 error gyp ERR! cwd /Users/redacted/projects/my-app/node_modules/fibers
1456 error gyp ERR! node -v v18.12.1
1456 error gyp ERR! node-gyp -v v8.4.1
1456 error gyp ERR! not ok 
1456 error node-gyp exited with code: 1
1456 error Please make sure you are using a supported platform and node version. If you
1456 error would like to compile fibers on this machine please make sure you have setup your
1456 error build environment--
1456 error Windows + OS X instructions here: https://github.com/nodejs/node-gyp
1456 error Ubuntu users please run: `sudo apt-get install g++ build-essential`
1456 error RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
1456 error Alpine users please run: `sudo apk add python make g++`
1456 error sh: nodejs: command not found
1457 verbose exit 127
1458 timing npm Completed in 25521ms
1459 verbose unfinished npm timer reify 1672198749980
1460 verbose unfinished npm timer reify:build 1672198764053
1461 verbose unfinished npm timer build 1672198764054
1462 verbose unfinished npm timer build:deps 1672198764054
1463 verbose unfinished npm timer build:run:install 1672198764098
1464 verbose unfinished npm timer build:run:install:node_modules/fibers 1672198764119
1465 verbose code 127
1466 error A complete log of this run can be found in:
1466 error     /Users/redacted/.npm/_logs/2022-12-28T03_39_09_892Z-debug-0.log

```

**Comment by JeanMeche** [comment]
Do you have `fibers` as dependecy your `package.json` ?  Because it's not a dependency of `@angular-devkit/build-angular`. It's a peer dependency of `sass-loader` which is pulled by `@angular-devkit/build-angular`

**Comment by aegonz** [comment]
I do not. Even just doing a `npm install @angular-devkit/build-angular` in a fresh folder it throws the same exception
