### ISSUE TITLE
Angular 14 App not loading on Edge 18 cordova app

### ISSUE THREAD

**Issue by snehasis** [angular/angular#48602]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

No

### Description

Edge version : Mozilla/5.0 (Windows NT 10.0; WOW64; MSAppHost/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763

System:
Node : v14.19.1
npm : 6.14.16

**Package.json** 

`"dependencies": {
    "@angular/common": "^14.1.1",
    "@angular/core": "^14.1.1",
    "@angular/forms": "^14.1.1",
    "@angular/material": "^14.1.2",
    "@angular/platform-browser": "^14.1.1",
    "@angular/platform-browser-dynamic": "^14.1.1",
    "@angular/router": "^14.1.1",
    "@ionic-native/core": "5.36.0",
    "@ionic-native/splash-screen": "^5.36.0",
    "@ionic-native/status-bar": "^5.36.0",
    "ionic-native": "2.4.1",
    "@ionic/angular": "^6.2.1",
    "@ionic/cli": "~6.20.1",
    "angular2-jwt": "0.2.3",
    "core-js": "^2.5.4",
    "immer": "^9.0.15",
    "moment": "^2.29.0",
    "ng2-dragula": "^2.1.1",
    "redux": "4.0.1",
    "reflect-metadata": "0.1.8",
    "rollup-plugin-typescript2": "^0.27.1",
    "rxjs": "~6.6.0",
    "rxjs-compat": "^6.6.3",
    "systemjs": "0.19.39",
    "tslib": "^1.14.0",
    "zone.js": "~0.11.7"
  }`

When I launch the app I am seeing below errors and app is not loading

### Please provide the exception or error you saw

```true
Exception was thrown at line 1, column 68901 in ms-appx-web://com.xxx.xxx/www/polyfills.js
0x800a139e - JavaScript runtime error: Uncaught (in promise): TypeError: Unable to get property 'isProxied' of undefined or null reference
TypeError: Unable to get property 'isProxied' of undefined or null reference
at Anonymous function (ms-appx-web://com.xxx.xxx/www/vendor.js:1:157012)
at Generator.prototype.next (native code)
at e (ms-appx-web://com.xxx.xxx/www/vendor.js:1:15114568)
at A (ms-appx-web://com.xxx.xxx/www/vendor.js:1:15114780)
at at.prototype.invoke (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:59971)
at at.prototype.run (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:55007)
at Anonymous function (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:71254)
at at.prototype.invokeTask (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:60637)
at at.prototype.runTask (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:55699)
at $t (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:63207)
Exception was thrown at line 1, column 55276 in ms-appx-web://com.xxx.xxx/www/polyfills.js
0x800a139e - JavaScript runtime error: Uncaught (in promise): TypeError: Unable to get property 'isProxied' of undefined or null reference
TypeError: Unable to get property 'isProxied' of undefined or null reference
at Anonymous function (ms-appx-web://com.xxx.xxx/www/vendor.js:1:157012)
at Generator.prototype.next (native code)
at e (ms-appx-web://com.xxx.xxx/www/vendor.js:1:15114568)
at A (ms-appx-web://com.xxx.xxx/www/vendor.js:1:15114780)
at at.prototype.invoke (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:59971)
at at.prototype.run (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:55007)
at Anonymous function (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:71254)
at at.prototype.invokeTask (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:60637)
at at.prototype.runTask (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:55699)
at $t (ms-appx-web://com.xxx.xxx/www/polyfills.js:1:63207)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.2.10
Node: 14.18.0
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 14.2.12
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.3
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    14.2.7
@angular/cli                    14.2.10
@angular/http                   7.2.16
@angular/material               14.2.7
@schematics/angular             14.2.10
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by alxhub** [comment]
Hello @snehasis,

This is very likely an issue related to Ionic or Cordova or some other part of the stack, and it's very likely that we can't help. Just looking at the stack trace, the symptom seems to relate to an `isProxied` function - Angular itself doesn't have any functions by this name.

If you can reproduce this issue in a plain Angular application, feel free to open another issue!
