### ISSUE TITLE
value.trim is not a function [15.1.1]

### ISSUE THREAD

**Issue by TheRealGI** [angular/angular#48780]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

While I updated angular from version 15.1.0 to 15.1.1 I noticed that the dropdown component  didn't worked properly. See error below.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/primengdropdownerror?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
ERROR TypeError: value.trim is not a function
    at set klass [as klass] (common.mjs:2641:53)
    at setInputsForProperty (core.mjs:11741:34)
    at setDirectiveInputsWhichShadowsStyling (core.mjs:13650:5)
    at checkStylingMap (core.mjs:15612:13)
    at Module.ɵɵclassMap (core.mjs:15529:5)
    at Overlay_div_0_Template (primeng-overlay.mjs:358:93)
    at executeTemplate (core.mjs:10534:9)
    at refreshView (core.mjs:10419:13)
    at refreshEmbeddedViews (core.mjs:11434:17)
    at refreshView (core.mjs:10443:9)
handleError @ core.mjs:8506
handleError @ core.mjs:11719
detectChangesInternal @ core.mjs:11628
detectChanges @ core.mjs:12075
onMouseclick @ primeng-dropdown.mjs:385
Dropdown_Template_div_click_0_listener @ primeng-dropdown.mjs:810
executeListenerWithErrorHandling @ core.mjs:14090
wrapListenerIn_markDirtyAndPreventDefault @ core.mjs:14123
(anonymous) @ platform-browser.mjs:402
invokeTask @ zone.js:406
(anonymous) @ core.mjs:23999
onInvokeTask @ core.mjs:23999
invokeTask @ zone.js:405
onInvokeTask @ core.mjs:24300
invokeTask @ zone.js:405
runTask @ zone.js:178
invokeTask @ zone.js:487
invokeTask @ zone.js:1661
globalCallback @ zone.js:1692
globalZoneAwareCallback @ zone.js:1725
Zone - HTMLDivElement.addEventListener:click (async)
onScheduleTask @ core.mjs:23993
scheduleTask @ zone.js:386
onScheduleTask @ zone.js:283
scheduleTask @ zone.js:386
scheduleTask @ zone.js:221
scheduleEventTask @ zone.js:247
(anonymous) @ zone.js:1964
addEventListener @ platform-browser.mjs:657
addEventListener @ platform-browser.mjs:232
listen @ platform-browser.mjs:581
listen @ animations.mjs:299
listenerInternal @ core.mjs:14052
ɵɵlistener @ core.mjs:13933
Dropdown_Template @ primeng-dropdown.mjs:37
executeTemplate @ core.mjs:10534
renderView @ core.mjs:10356
renderComponent @ core.mjs:11529
renderChildComponents @ core.mjs:10216
renderView @ core.mjs:10381
renderComponent @ core.mjs:11529
renderChildComponents @ core.mjs:10216
renderView @ core.mjs:10381
create @ core.mjs:12273
bootstrap @ core.mjs:25368
(anonymous) @ core.mjs:25028
_moduleDoBootstrap @ core.mjs:25028
(anonymous) @ core.mjs:24998
invoke @ zone.js:372
onInvoke @ core.mjs:24313
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
(anonymous) @ core.mjs:23999
onInvokeTask @ core.mjs:23999
invokeTask @ zone.js:405
onInvokeTask @ core.mjs:24300
invokeTask @ zone.js:405
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
Zone - Promise.then (async)
onScheduleTask @ core.mjs:23993
scheduleTask @ zone.js:386
onScheduleTask @ zone.js:283
scheduleTask @ zone.js:386
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1265
then @ zone.js:1461
(anonymous) @ core.mjs:24994
_callAndReportToErrorHandler @ core.mjs:25106
(anonymous) @ core.mjs:24991
invoke @ zone.js:372
onInvoke @ core.mjs:24313
invoke @ zone.js:371
run @ zone.js:134
run @ core.mjs:24167
bootstrapModuleFactory @ core.mjs:24973
(anonymous) @ core.mjs:25023
invoke @ zone.js:372
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
Promise.then (async)
nativeScheduleMicroTask @ zone.js:561
scheduleMicroTask @ zone.js:572
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1265
then @ zone.js:1461
bootstrapModule @ core.mjs:25023
4431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.ts:12
(anonymous) @ main.ts:12
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.ts:12
webpackJsonpCallback @ jsonp chunk loading:34
(anonymous) @ main.js:2
Show 95 more frames
main.ts:11 ERROR TypeError: value.trim is not a function
    at set klass [as klass] (common.mjs:2641:53)
    at setInputsForProperty (core.mjs:11741:34)
    at setDirectiveInputsWhichShadowsStyling (core.mjs:13650:5)
    at checkStylingMap (core.mjs:15612:13)
    at Module.ɵɵclassMap (core.mjs:15529:5)
    at Overlay_div_0_Template (primeng-overlay.mjs:358:93)
    at executeTemplate (core.mjs:10534:9)
    at refreshView (core.mjs:10419:13)
    at refreshEmbeddedViews (core.mjs:11434:17)
    at refreshView (core.mjs:10443:9)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.2
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64
Angular: 15.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Package             Version
---------------------------------------------------------
@angular-devkit/architect    0.1501.2
@angular-devkit/build-angular  15.1.2
@angular-devkit/core      15.1.2
@angular-devkit/schematics   15.1.2
@angular/cli          15.1.2
@schematics/angular       15.1.2
rxjs              6.6.7
typescript           4.9.4
```

**Comment by TheRealGI** [comment]
Bug report already submitted by #48779. Closing it.
