### ISSUE TITLE
"Uncaught TypeError: Cannot read properties of undefined" on static properties while executing ng test

### ISSUE THREAD

**Issue by codng101** [angular/angular#49160]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

This issue appeared on a project after  migration from angular 14 to 15, but can also be observed on new project. 

When executing `ng test` every `static` variable used to initialise other `static` variable are reported as `undefined` in afterAll. This can be reproduced simply by  creating two static variable in a class with on depending on the other to be initialised.

![Screenshot 2023-02-22 at 14 50 09](https://user-images.githubusercontent.com/33670394/220639888-e158391d-e82b-49b0-95f5-230b99664f62.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/node-anr2pt?file=test-project/src/app/app.component.ts

### Please provide the exception or error you saw

```true
❯ ng test
✔ Browser application bundle generation complete.
22 02 2023 14:15:17.005:WARN [karma]: No captured browser, open http://localhost:9877/
22 02 2023 14:15:17.019:INFO [karma-server]: Karma v6.4.1 server started at http://localhost:9877/
22 02 2023 14:15:17.020:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
22 02 2023 14:15:17.023:INFO [launcher]: Starting browser Chrome
22 02 2023 14:15:22.257:INFO [Chrome 110.0.0.0 (Mac OS 10.15.7)]: Connected on socket LAu2UV7RFkyLC-G5AAAB with id 41268440
Chrome 110.0.0.0 (Mac OS 10.15.7) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: Cannot read properties of undefined (reading 'string1')
  TypeError: Cannot read properties of undefined (reading 'string1')
      at Object.5041 (http://localhost:9877/_karma_webpack_/webpack:/src/app/app.component.ts:11:52)
      at __webpack_require__ (http://localhost:9877/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.4882 (http://localhost:9877/_karma_webpack_/main.js:14:72)
      at __webpack_require__ (http://localhost:9877/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9877/_karma_webpack_/main.js:134:48)
      at http://localhost:9877/_karma_webpack_/main.js:135:102
      at Function.__webpack_require__.O (http://localhost:9877/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9877/_karma_webpack_/main.js:136:56
      at webpackJsonpCallback (http://localhost:9877/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)
      at http://localhost:9877/_karma_webpack_/main.js:1:77
Chrome 110.0.0.0 (Mac OS 10.15.7): Executed 0 of 0 ERROR (0 secs / 0 secs)
Chrome 110.0.0.0 (Mac OS 10.15.7) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: Cannot read properties of undefined (reading 'string1')
  TypeError: Cannot read properties of undefined (reading 'string1')
      at Object.5041 (http://localhost:9877/_karma_webpack_/webpack:/src/app/app.component.ts:11:52)
      at __webpack_require__ (http://localhost:9877/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.4882 (http://localhost:9877/_karma_webpack_/main.js:14:72)
      at __webpack_require__ (http://localhost:9877/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9877/_karma_webpack_/main.js:134:48)
      at http://localhost:9877/_karma_webpack_/main.js:135:102
      at Function.__webpack_require__.O (http://localhost:9877/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9877/_karma_webpack_/main.js:136:56
      at webpackJsonpCallback (http://localhost:9877/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)
Chrome 110.0.0.0 (Mac OS 10.15.7): Executed 0 of 0 ERROR (0.357 secs / 0 secs)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.6
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 15.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.6
@angular-devkit/build-angular   15.1.6
@angular-devkit/core            15.1.6
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@schematics/angular             15.1.6
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by JeanMeche** [comment]
That's a dupe of #48764, the root-cause being in TS: microsoft/TypeScript#52004.

**Comment by codng101** [comment]
Thank you for you response !

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular/issues/48764
