### ISSUE TITLE
Headers assertValidHeaders is breacking my local environment.

### ISSUE THREAD

**Issue by danilobassi8** [angular/angular#49353]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I was having an error in my local that I was not able to reproduce it in production.
I am in a big project with a lot of dependencies, and was Migrating from Angular 13 to 14.

The error is this one:

app.module.ts:71 ERROR Error: Unexpected value of the `Content-Length` header provided. Expecting either a string or an array, but got: `281`.
    at assertValidHeaders (http.mjs:287:19)
    at HttpHeaders.lazyInit (http.mjs:100:21)
    at HttpHeaders.init (http.mjs:207:22)
    at HttpHeaders.copyFrom (http.mjs:217:15)
    at HttpHeaders.init (http.mjs:204:22)
    at HttpHeaders.has (http.mjs:125:14)
    at HttpXSRFInterceptor.intercept (http-xsrf-interceptor.ts:36:40)

I started reading the source code to see what's happening and I found this lines in `headers.ts`

```typescript
/**
 * Verifies that the headers object has the right shape: the values
 * must be either strings or arrays. Throws an error if an invalid
 * header value is present.
 */
function assertValidHeaders(headers) {
    for (const [key, value] of Object.entries(headers)) {
        if (typeof value !== 'string' && !Array.isArray(value)) {
            throw new Error(`Unexpected value of the \`${key}\` header provided. ` +
                `Expecting either a string or an array, but got: \`${value}\`.`);
        }
    }
}
```

As Far as i understood, this is only being called if we are in devMode. Check this lines:
```typescript
if (typeof ngDevMode === 'undefined' || ngDevMode) { 
      assertValidHeaders(headers);
}
```

I've got 3 questions:
- Is it correct that we're doing those kinds of evaluations in dev Environment and not in production envs? asking this because I'm running on dockers and my local is like my production environment and this is breaking my entire application, since its trowing an error.
- Wouldn't be better if instead of trowing an error we just inform to the user using a console.error, or something like this? Those kind of lines are being evaluated when I do something like `request.headers.has('OtherHeaderName')`.
- Is there a way to fix this? this is the only thing preventing me to migrate to Angular 14. Didn't find a solution yet. What surpriced me the most is that I'm not seeing any request on the network tab, and I also have this line in the interceptor that's being executed:
```typescript
    // Setting a `host` header is being refused because it's unsafe. So let's just drop it.
    httpHeaders = httpHeaders.delete('Host');
    httpHeaders = httpHeaders.delete('Content-Length');

    request = request.clone({
      headers: httpHeaders,
    });

    return next.handle(request);
```

### Please provide the exception or error you saw

```true
app.module.ts:71 ERROR Error: Unexpected value of the `Content-Length` header provided. Expecting either a string or an array, but got: `281`.
    at assertValidHeaders (http.mjs:287:19)
    at HttpHeaders.lazyInit (http.mjs:100:21)
    at HttpHeaders.init (http.mjs:207:22)
    at HttpHeaders.copyFrom (http.mjs:217:15)
    at HttpHeaders.init (http.mjs:204:22)
    at HttpHeaders.has (http.mjs:125:14)
    at HttpXSRFInterceptor.intercept (http-xsrf-interceptor.ts:36:40)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.10
Node: 16.13.2
Package Manager: npm 8.1.2 
OS: linux x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    14.2.7
@angular/cli                    14.2.10
@schematics/angular             14.2.10
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by JeanMeche** [comment]
Hi, 

To answer the first 2 points : to reduce and optimize the payload size, multiple errors and validations/assertions from the Angular framework are tree shaken at build time by the optimizer. 

To get to the bottom of you problem. I looks like #46059 has introduced this regression. `assertValidHeaders` should be accepting numbers.

**Comment by danilobassi8** [comment]
Hi, I don't know how the usually flow is. But I opened a PR to the main branch with some changes to fix that issue.
Thanks in advance.

**Comment by AurelienLoyer** [comment]
Same issue on our side with a simple interceptor get the header... 😭

```
Error: Unexpected value of the `normalizedNames` header provided. Expecting either a string or an array, but got: `[object Map]`.
    at assertValidHeaders (http.mjs:287:19)
    at HttpHeaders.lazyInit (http.mjs:100:21)
    at HttpHeaders.init (http.mjs:207:22)
    at HttpHeaders.copyFrom (http.mjs:217:15)
    at HttpHeaders.init (http.mjs:204:22)
    at HttpHeaders.get (http.mjs:136:14)
    at InspectionInterceptor.intercept (inspection.interceptor.ts:259:32)
    at HttpInterceptorHandler.handle (http.mjs:1443:33)
    at ErrorHandlerInterceptor.intercept (error-handler.interceptor.ts:28:17)
    at HttpInterceptorHandler.handle (http.mjs:1443:33)
```

And the famous interceptor 👇
```ts
public intercept(request: HttpRequest<unknown>, next: HttpHandler): Observable<HttpEvent<unknown>> {
    if (!this._accountService.isInspector() || request.headers.has(INTERCEPTOR_SKIP_HEADER)) {
      return next.handle(request);
    }

    // ...
}
```

**Comment by jbmgrtn** [comment]
> Same issue on our side with a simple interceptor getting the header... 😭
> 
> ```
> Error: Unexpected value of the `normalizedNames` header provided. Expecting either a string or an array, but got: `[object Map]`.
>     at assertValidHeaders (http.mjs:287:19)
>     at HttpHeaders.lazyInit (http.mjs:100:21)
>     at HttpHeaders.init (http.mjs:207:22)
>     at HttpHeaders.copyFrom (http.mjs:217:15)
>     at HttpHeaders.init (http.mjs:204:22)
>     at HttpHeaders.get (http.mjs:136:14)
>     at InspectionInterceptor.intercept (inspection.interceptor.ts:259:32)
>     at HttpInterceptorHandler.handle (http.mjs:1443:33)
>     at ErrorHandlerInterceptor.intercept (error-handler.interceptor.ts:28:17)
>     at HttpInterceptorHandler.handle (http.mjs:1443:33)
> ```
> 
> And the famous interceptor 👇
> 
> ```ts
> public intercept(request: HttpRequest<unknown>, next: HttpHandler): Observable<HttpEvent<unknown>> {
>     if (!this._accountService.isInspector() || request.headers.has(INTERCEPTOR_SKIP_HEADER)) {
>       return next.handle(request);
>     }
> 
>     // ...
> }
> ```

According to the code I see in my browser
```javascript
/**
 * Verifies that the headers object has the right shape: the values
 * must be either strings or arrays. Throws an error if an invalid
 * header value is present.
 */
function assertValidHeaders(headers) {
    for (const [key, value] of Object.entries(headers)) {
        if (typeof value !== 'string' && !Array.isArray(value)) {
            throw new Error(`Unexpected value of the \`${key}\` header provided. ` +
                `Expecting either a string or an array, but got: \`${value}\`.`);
        }
    }
}
```

shouldn't this method called on headers.headers instead because headers is
```json
{
    "normalizedNames": [],
    "lazyUpdate": [
        {
            "name": "authorization",
            "op": "d"
        }
    ],
    "headers": [],
    "lazyInit": {
        "normalizedNames": [
            [
                "authorization",
                "Authorization"
            ]
        ],
        "lazyUpdate": null,
        "headers": [
            [
                "authorization",
                [
                    "OBFUSCATED_FOR_SHARING_PURPOSE"
                ]
            ]
        ],
        "lazyInit": null
    }
}
```

**Comment by danilobassi8** [comment]
oh.. @AurelienLoyer my PR wont cover that case because you are sending a Map. I could add it pretty easy. But I don't really know why they added that validation at first place. I'm guessing that we'll need to cast that Map into an Array, as I did it with numerical values.
