### ISSUE TITLE
public static readonly members not available in test

### ISSUE THREAD

**Issue by mchlbld** [angular/angular#49522]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

No

### Description

# Description
After upgrading from Angular 15 to 15.1 I'm encountering an error when executing tests in my angular project. I could reproduce this by simply setting up a new Angular 15.1 project via the CLI and generating a service using the same semantic as the (probably problematic) service in my project.

## Service
```typescript
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class StorageServiceService {
  public static readonly A = 'a';
  public static readonly B = StorageServiceService.A + 'b';
  public static readonly C = StorageServiceService.A + 'c';

  constructor() { }
```

## Test
```typescript
import { TestBed } from '@angular/core/testing';

import { StorageServiceService } from './storage-service.service';

describe('StorageServiceService', () => {
  let service: StorageServiceService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(StorageServiceService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('test', () => {
    expect(StorageServiceService.A).toEqual('a')
    expect(StorageServiceService.B).toEqual('ab')
    expect(StorageServiceService.C).toEqual('ac')
  })
});
```
## package.json
```typescript
{
  "name": "test-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/router": "^15.1.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.1.1",
    "@angular/cli": "~15.1.1",
    "@angular/compiler-cli": "^15.1.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.9.4"
  }
}
```

### Please provide a link to a minimal reproduction of the bug

[GitHub](https://github.com/mchlbld/angular-test)

### Please provide the exception or error you saw

```true
Chrome 111.0.0.0 (Mac OS 10.15.7) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: Cannot read properties of undefined (reading 'A')
  TypeError: Cannot read properties of undefined (reading 'A')
      at Object.2494 (http://localhost:9877/_karma_webpack_/webpack:/src/app/storage-service.service.ts:8:43)
      at __webpack_require__ (http://localhost:9877/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Object.283 (http://localhost:9877/_karma_webpack_/main.js:86:82)
      at __webpack_require__ (http://localhost:9877/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at __webpack_exec__ (http://localhost:9877/_karma_webpack_/main.js:186:48)
      at http://localhost:9877/_karma_webpack_/main.js:187:126
      at Function.__webpack_require__.O (http://localhost:9877/_karma_webpack_/webpack:/webpack/runtime/chunk loaded:23:1)
      at http://localhost:9877/_karma_webpack_/main.js:188:56
      at webpackJsonpCallback (http://localhost:9877/_karma_webpack_/webpack:/webpack/runtime/jsonp chunk loading:34:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.6
Node: 18.12.1
Package Manager: npm 9.2.0
OS: darwin x64

Angular: 15.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.2.0
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@schematics/angular             15.1.6
rxjs                            7.8.0
typescript                      4.9.5
```

### Anything else?

When Using this code with Angular 15.0 everything works as intended.
This only affects the Tests. Running this code via `ng serve` does not raise an error and the app works as intended.

**Comment by mchlbld** [comment]
Thank you, I'll close this one.
