### ISSUE TITLE
Errors running stackblitz example locally

### ISSUE THREAD

**Issue by phalgunv** [angular/angular#49709]
### Describe the problem that you experienced

As per https://angular.io/start/start-deployment#running-your-application-locally, one should be able to download stackblitz project and run `npm install` and then `npm start`. However, `ng serve` fails with multiple issue even for a simple Hello World app.

Steps:
1. Download source code from Stackblitz: https://stackblitz.com/edit/angular-fmcr1r?file=src%2Fmain.ts
2. Unzip, cd, install dependencies and start the app
```
cd angular-fmcr1r
npm install
npm start
```

### Enter the URL of the topic with the problem

https://angular.io/start/start-deployment#running-your-application-locally

### Describe what you were looking for in the documentation

Exact steps, which when executed runs the the project locally.

### Describe the actions that led you to experience the problem

I wanted to run Angular projects created on stackblitz locally on my PC.

### Describe what you want to experience that would fix the problem

Seamless bootstrapping of Angular app using source code downloaded from Stackblitz.

### If this problem caused an exception or error, please paste it here

```true
Error: Schema validation failed with the following errors:
  Data path "" must have required property 'tsConfig'.
```
After updating `angular.json` architect->build->options with `"tsConfig": "src/tsconfig.app.json"`. I get the next error:
```
⠋ Generating browser application bundles (phase: setup)...    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
⠙ Generating browser application bundles (phase: setup)...Error: ENOENT: no such file or directory, open 'C:/Custom/code/angular-15-starter/angular-fmcr1r/src/polyfills.ts'
    at Object.openSync (fs.js:498:3)
    at Module.readFileSync (fs.js:394:35)
    at NodeJSFileSystem.readFile (file:///C:/Custom/code/angular-15-starter/angular-fmcr1r/node_modules/@angular/compiler-cli/bundles/chunk-E7DPJFUS.js:333:16)
    at EsmDependencyHost.recursivelyCollectDependencies (file:///C:/Custom/code/angular-15-starter/angular-fmcr1r/node_modules/@angular/compiler-cli/bundles/chunk-PPWXQG65.js:217:34)
    at EsmDependencyHost.processFile (file:///C:/Custom/code/angular-15-starter/angular-fmcr1r/node_modules/@angular/compiler-cli/bundles/chunk-PPWXQG65.js:246:12)
    at EsmDependencyHost.collectDependenciesInFiles (file:///C:/Custom/code/angular-15-starter/angular-fmcr1r/node_modules/@angular/compiler-cli/bundles/chunk-PPWXQG65.js:213:12)
    at ProgramBasedEntryPointFinder.getInitialEntryPointPaths (file:///C:/Custom/code/angular-15-starter/angular-fmcr1r/node_modules/@angular/compiler-cli/bundles/chunk-PPWXQG65.js:864:10)
    at ProgramBasedEntryPointFinder.findEntryPoints (file:///C:/Custom/code/angular-15-starter/angular-fmcr1r/node_modules/@angular/compiler-cli/bundles/chunk-PPWXQG65.js:823:35)
    at file:///C:/Custom/code/angular-15-starter/angular-fmcr1r/node_modules/@angular/compiler-cli/bundles/chunk-PPWXQG65.js:1273:33
    at new ClusterMaster (file:///C:/Custom/code/angular-15-starter/angular-fmcr1r/node_modules/@angular/compiler-cli/bundles/chunk-PPWXQG65.js:1375:22)
```
Removing "polyfills.ts" from `src/tsconfig.app.json ->files` fixes the issue.
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

_No response_

### Provide any additional information here in as much as detail as you can

```true
OS: Windows 10 21H2
node: V14.20.0
angular-cli: 15.1.2
```

**Comment by phalgunv** [comment]
I see an issue is raised for this https://github.com/stackblitz/core/issues/2413
