### ISSUE TITLE
Writing to signals is not allowed in callbacks

### ISSUE THREAD

**Issue by peterpeterparker** [angular/angular#49871]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I gave a try to `Signals` in `v16.0.0-rc.0` and noticed that they cannot be set in callbacks which can be for example a drawback when using third party libraries.

```
import { Injectable, signal } from '@angular/core';

const test = (callback: (user: number) => void) => callback(1);

@Injectable({
  providedIn: 'root',
})
export class DemoService {
  private value = signal<number | undefined>(undefined);

  constructor() {
    test((state) => this.value.set(state))
  }
}
```

### Please provide the exception or error you saw

```true
Lead to following error at runtime:

> in.ts:6 ERROR Error: NG0600: Writing to signals is not allowed in a `computed` or an `effect` by default. Use `allowSignalWrites` in the `CreateEffectOptions` to enable this inside effects.
>     at core.mjs:26485:15
>     at throwInvalidWriteToSignalError (core.mjs:2549:5)
>     at WritableSignalImpl.set (core.mjs:2584:13)
>     at demo.service.ts:12:32
>     at test (demo.service.ts:3:52)
>     at new DemoService (demo.service.ts:12:5)
>     at Object.DemoService_Factory [as factory] (demo.service.ts:8:25)
>     at R3Injector.hydrate (core.mjs:9162:35)
>     at R3Injector.get (core.mjs:9050:33)
>     at ChainedInjector.get (core.mjs:12850:36)
> h
```

### Anything else?

Last login: Sun Apr 16 08:17:47 on ttys001
❯ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.0.0-rc.0
Node: 18.15.0
Package Manager: npm 9.6.1
OS: darwin arm64

Angular: 16.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0-rc.0
@angular-devkit/build-angular   16.0.0-rc.0
@angular-devkit/core            16.0.0-rc.0
@angular-devkit/schematics      16.0.0-rc.0
@angular/cdk                    16.0.0-rc.0
@angular/cli                    16.0.0-rc.0
@angular/material               16.0.0-rc.0
@schematics/angular             16.0.0-rc.0
rxjs                            7.8.0
typescript                      4.9.5

**Comment by JeanMeche** [comment]
Hi, could you provide a stackblitz repro ? (I could not repoduce it with your code).

**Comment by peterpeterparker** [comment]
@JeanMeche indeed it seems to happen only when the service is injected in a standalone component.

Note: I don't use Angular myself anymore, so might good be that the way I injected the service in the standalone component is incorrect. If it's the root cause of the problem, then I would say it's just the error message that would deserve some love.

Here a sample repo:

```
git clone https://github.com/peterpeterparker/signals
cd signals
npm ci
npm run start
```

**Comment by JeanMeche** [comment]
Ok, so the issue happens when the service is instantiated in a child component. 

Also, we can note that there is no issue if that same component is instantiated by the router.

**Comment by peterpeterparker** [comment]
Thanks for the debugging.

**Comment by pkozlowski-opensource** [comment]
Thnx for reporting, fix in https://github.com/angular/angular/pull/49883
