### ISSUE TITLE
Error with legacy dependency after typescript upgrade: TypeError: Cannot set property getExpandoInitializer

### ISSUE THREAD

**Issue by d-eder** [angular/angular#49922]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

After we upgraded to typescript 5.0.4, the build of the angular application doesn't work anymore.
According to the stacktrace, this is because of some legacy dependencies. 
We are using for example https://github.com/olivierlsc/angular-page-visibility or  https://github.com/sapozhnikovay/ngx-mat-datefns-date-adapter and some others.

### Please provide the exception or error you saw

```true
[07:59:16] :		 [:uf-ui:clfNpmBuild] > ng build
[07:59:16] :		 [:uf-ui:clfNpmBuild] 
[07:59:16] :		 [:uf-ui:clfNpmBuild] Building Angular Package
[07:59:17]W:		 [:uf-ui:clfNpmBuild] - Compiling with Angular sources in Ivy full compilation mode.
[07:59:17] :		 [:uf-ui:clfNpmBuild] 
[07:59:17] :		 [:uf-ui:clfNpmBuild] ------------------------------------------------------------------------------
[07:59:17] :		 [:uf-ui:clfNpmBuild] Building entry point '@my-project/modules'
[07:59:17] :		 [:uf-ui:clfNpmBuild] ------------------------------------------------------------------------------
[07:59:19]W:		 [:uf-ui:clfNpmBuild] Processing legacy "View Engine" libraries:
[07:59:20]W:		 [:uf-ui:clfNpmBuild] - angular-page-visibility [es2015/esm2015] (git+https://github.com/olivierlsc/angular-page-visibility.git)
[07:59:20]W:		 [:uf-ui:clfNpmBuild] Error: Error on worker #1: TypeError: Cannot set property getExpandoInitializer of #<Object> which has only a getter
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at patchTsGetExpandoInitializer (file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/chunk-BGY2CNQJ.js:2601:29)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at isTs31778GetExpandoInitializerFixed (file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/chunk-BGY2CNQJ.js:2621:43)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at patchTsGetExpandoInitializer (file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/chunk-BGY2CNQJ.js:2594:7)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at makeBundleProgram (file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/chunk-BGY2CNQJ.js:2700:41)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at makeEntryPointBundle (file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/chunk-BGY2CNQJ.js:2891:15)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/chunk-BGY2CNQJ.js:4762:22
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at Worker.<anonymous> (file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:71:24)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at Worker.emit (node:events:513:28)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at process.<anonymous> (node:internal/cluster/worker:35:12)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at process.emit (node:events:513:28)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at ClusterMaster.onWorkerMessage (file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/chunk-TYAEIVDA.js:1469:15)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/chunk-TYAEIVDA.js:1379:71
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at EventEmitter.<anonymous> (file:///data/home/agent-01/agent/work/a0adebd003e98f8d/uf-ui/node_modules/@angular/compiler-cli/bundles/chunk-TYAEIVDA.js:1539:15)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at EventEmitter.emit (node:events:513:28)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at Worker.<anonymous> (node:internal/cluster/primary:171:13)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at Worker.emit (node:events:513:28)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at ChildProcess.<anonymous> (node:internal/cluster/worker:35:12)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at ChildProcess.emit (node:events:513:28)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at emit (node:internal/child_process:937:14)
[07:59:20]W:		 [:uf-ui:clfNpmBuild]     at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[07:59:20]W:		 [:uf-ui:clfNpmBuild] ✖ Compiling with Angular sources in Ivy full compilation mode.
[07:59:20]W:		 [:uf-ui:clfNpmBuild] NGCC failed.
[07:59:20]W:		 [:uf-ui:clfNpmBuild]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.6
Node: 18.13.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 15.2.7
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.6
@angular-devkit/build-angular   15.2.6
@angular-devkit/core            15.2.6
@angular-devkit/schematics      15.2.6
@angular/cli                    15.2.6
@schematics/angular             15.2.6
ng-packagr                      15.0.3
rxjs                            7.8.0
typescript                      5.0.4
```

**Comment by JoostK** [comment]
TypeScript 5.0 is not supported in Angular 15, you will have to wait for Angular 16 for TS 5.0 support.
