### ISSUE TITLE
dart build fails building examples, 2.0.0-alpha.45

### ISSUE THREAD

**Issue by mark1010** [angular/angular#4996]
2.0.0-alpha.45

dart --version
Dart VM version: 1.13.0-dev.7.4 (Tue Oct 27 14:56:01 2015) on "macos_x64"

```
> $(npm bin)/gulp build.dart
...
Could not find a file named "pubspec.yaml" in "/Users/mh/WebstormProjects/angular/dist/dart/examples".
[12:30:17] 'build/pubspec.dart' errored after 1 min
[12:30:17] Error: 1
    at formatError (/Users/mh/WebstormProjects/angular/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/mh/WebstormProjects/angular/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/mh/WebstormProjects/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/mh/WebstormProjects/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/mh/WebstormProjects/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/mh/WebstormProjects/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
    at _rejected (/Users/mh/WebstormProjects/angular/node_modules/q/q.js:830:24)
    at /Users/mh/WebstormProjects/angular/node_modules/q/q.js:856:30
    at Promise.when (/Users/mh/WebstormProjects/angular/node_modules/q/q.js:1108:31)
    at Promise.promise.promiseDispatch (/Users/mh/WebstormProjects/angular/node_modules/q/q.js:774:41)
    at /Users/mh/WebstormProjects/angular/node_modules/q/q.js:590:44
    at runSingle (/Users/mh/WebstormProjects/angular/node_modules/q/q.js:123:13)
    at flush (/Users/mh/WebstormProjects/angular/node_modules/q/q.js:111:13)
    at doNTCallback0 (node.js:417:9)
[12:30:17] 'build.dart' errored after 2.33 min
```

**Comment by vicb** [comment]
I think I saw this error earlier and the reason was that there is no `examples` folder in the project any more (I has been move to `playground`). If you had some local files in this folder, the build system will try to build the `examples` folder and will not find some of the dart files.

The solution is to remove this folder completely (`/modules/examples`) - you might want to transfer your files/folders in the `playground` folder.

Feel free to re-open if this does not fix your issue.
