### ISSUE TITLE
custom validator class not work in typed form

### ISSUE THREAD

**Issue by Laffery** [angular/angular#49974]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

When I use custom validator class in typed form in angular v15,  I got a strange error that `getSource` is undefined, which I had it initialized in constructor. However, functional validator works well.

```ts
class NotDuplicateValidator implements Validator {
  constructor(private getSource: () => string[]) {}

  public validate(control: AbstractControl): ValidationErrors | null {
    if (this.getSource().indexOf(control.value) !== -1) {
      return { duplicate: { duplicate: control.value } };
    } else {
      return null;
    }
  }
}

function notDuplicateValidator(getSource: () => string[]): ValidatorFn {
  return (control: AbstractControl): ValidationErrors | null => {
    if (getSource().indexOf(control.value) !== -1) {
      return { duplicate: { duplicate: control.value } };
    } else {
      return null;
    }
  };
}

@Component({
  // ...
})
class App {
  listOfName = ['jack', 'tom'];
  form = this.formBuilder.group({
    name: this.formBuilder.control('', {
      validators: [
        Validators.required,
        new NotDuplicateValidator(() => this.listOfName).validate,
        // notDuplicateValidator(() => this.listOfName), // functional validator works well
      ],
    }),
  });

  // ...
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ipmdtt?file=src/main.ts

### Please provide the exception or error you saw

```true
ERROR
Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'getSource')
TypeError: Cannot read properties of undefined (reading 'getSource')
at validate (https://angular-ipmdtt.stackblitz.io/~/src/main.ts:16:18)
at eval (https://angular-ipmdtt.stackblitz.io/turbo_modules/@angular/forms@15.1.2/fesm2015/forms.mjs:802:40)
at Array.map (<anonymous>)
at executeValidators (https://angular-ipmdtt.stackblitz.io/turbo_modules/@angular/forms@15.1.2/fesm2015/forms.mjs:802:23)
at FormControl.eval [as _composedValidatorFn] (https://angular-ipmdtt.stackblitz.io/turbo_modules/@angular/forms@15.1.2/fesm2015/forms.mjs:833:28)
at FormControl._runValidator (https://angular-ipmdtt.stackblitz.io/turbo_modules/@angular/forms@15.1.2/fesm2015/forms.mjs:2201:38)
at FormControl.updateValueAndValidity (https://angular-ipmdtt.stackblitz.io/turbo_modules/@angular/forms@15.1.2/fesm2015/forms.mjs:2178:32)
at new FormControl (https://angular-ipmdtt.stackblitz.io/turbo_modules/@angular/forms@15.1.2/fesm2015/forms.mjs:3590:14)
at FormBuilder.control (https://angular-ipmdtt.stackblitz.io/turbo_modules/@angular/forms@15.1.2/fesm2015/forms.mjs:7026:20)
at new App (https://angular-ipmdtt.stackblitz.io/~/src/main.ts:43:36)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.6
Node: 16.18.0
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.2.8
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.6
@angular-devkit/build-angular   15.2.6
@angular-devkit/core            15.2.6
@angular-devkit/schematics      15.2.6
@angular/cli                    15.2.6
@schematics/angular             15.2.6
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by JeanMeche** [comment]
Hi, 

You're running into a js runtime context issue. `this` is undefined when you call validate.

**Comment by JeanMeche** [comment]
Have you already read about the specificity of `this` is JS ? 
For example here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Laffery** [comment]
> Have you already read about the specificity of `this` is JS ? For example here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

I got it. 

It seems that custom class validator isn't the best practice in FormControl API, we'd better use functional validator.
