### ISSUE TITLE
Angular fresh application npm ci gyp command failure

### ISSUE THREAD

**Issue by Serehactka** [angular/angular#50052]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Create fresh application:
```bash
ng new Application
```
Wait till setup is complete.

Try to test out `npm ci` command
Result:
![image](https://user-images.githubusercontent.com/13600914/234979979-43652adc-ceaa-4f0e-b84c-d1885e1e8d2f.png)

I'm not using anything which could intercept with default environment (only `nvm`) and as well not sure why node-gyp-build 've been called. But I've traced deps and found that `node-gyp-build` is dependency of `nice-napi` which is dependency of `piscina` which is dependency of `@angular-devkit/build-angular`.

`node-gyp-build` < `nice-napi` < `piscina` < `@angular-devkit/build-angular`

P.S. Sorry if it is wrong thread but I wasn't able to find correct one

### Please provide the exception or error you saw

```true
npm ci
npm WARN prepare removing existing node_modules/ before installation


> nice-napi@1.0.2 install I:\Developer\Angular\TestCI\node_modules\nice-napi
> node-gyp-build


I:\Developer\Angular\TestCI\node_modules\nice-napi>if not defined npm_config_node_gyp (node "E:\Programs\nvm\v14.20.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "E:\Programs\nvm\v14.20.1\node_modules\npm\node_modules\node-gyp\bi
n\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  nothing.c
  win_delay_load_hook.cc
  nothing.vcxproj -> I:\Developer\Angular\TestCI\node_modules\nice-napi\build\Release\\nothing.lib
  binding.cc
  win_delay_load_hook.cc
I:\Developer\Angular\TestCI\node_modules\nice-napi\binding.cc(2,10): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [I:\Developer\Angular\TestCI\node_modules\nice-napi\build\nice_napi.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\Programs\nvm\v14.20.1\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Programs\\nvm\\v14.20.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd I:\Developer\Angular\TestCI\node_modules\nice-napi
gyp ERR! node -v v14.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> esbuild@0.17.8 postinstall I:\Developer\Angular\TestCI\node_modules\@angular-devkit\build-angular\node_modules\esbuild
> node install.js

added 952 packages in 50.507s
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI 15.2.7
Node 14.20.1
Package Manager: npm 6.14.17
OS: Windows 10 x64

Angular: ^15.0.0
animations, common, compiler, core, forms, platform-browser, platform-browser-dynamic, router
```

**Comment by spock123** [comment]
@Serehactka I'm not sure Node 14 is supported any longer.
Make sure you're on Node 16+, and you are using Python3+

**Comment by JeanMeche** [comment]
v15 support node 14.20 cf https://angular.io/guide/versions
