### ISSUE TITLE
Angular 16 SSR initial app load is long

### ISSUE THREAD

**Issue by armingdev** [angular/angular#50288]
### Which @angular/* package(s) are the source of the bug?

platform-server, upgrade, Don't known / other

### Is this a regression?

Yes

### Description

After upgrading the app from 15.3 to 16 (and soon after 16.0.1) initial load time is very long. It took about a minute to load the app, then the app worked correctly (you can use the app usually, switch, pages ..). When I start the app with ng serve, the app works fine, but with npm run dev:ssr issue happens. Also, it happens when I deploy a site to the server and build it and run it from dist. I have provided a staging link.

[![Screenshot-2023-05-14-at-16-22-35.png](https://i.postimg.cc/CxjFDHSY/Screenshot-2023-05-14-at-16-22-35.png)](https://postimg.cc/75Z8rz5Q)

### Please provide a link to a minimal reproduction of the bug

https://stage.gamers.ba

### Please provide the exception or error you saw

```true
There is no errors in console:

npm run dev:ssr

> gamers-client@0.0.0 dev:ssr
> ng run gamers-client:serve-ssr

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
The esbuild-based browser application builder ('browser-esbuild') is currently in developer preview and is not yet recommended for production use. For additional information, please see https://angular.io/guide/esbuild
The 'namedChunks' option is not used by this builder and will be ignored.
The 'vendorChunk' option is not used by this builder and will be ignored.
✔ Server application bundle generation complete.

Initial Chunk Files | Names                                          | Raw Size
vendor.js           | vendor                                         |  6.65 MB |
main.js             | main                                           |  6.49 MB |

                    | Initial Total                                  | 13.13 MB

Lazy Chunk Files    | Names                                          | Raw Size
84.js               | features-news-news-module                      | 14.26 MB |
306.js              | pages-pages-module                             | 12.98 MB |
388.js              | features-esport-esport-module                  |  9.72 MB |
471.js              | features-forum-forum-module                    |  8.76 MB |
326.js              | features-homepage-homepage-module              |  8.08 MB |
171.js              | features-clan-clan-module                      |  6.89 MB |
403.js              | features-daily-picture-daily-picture-module    |  6.54 MB |
397.js              | features-user-user-module                      |  6.17 MB |
340.js              | admin-esport-admin-esport-module               |  1.10 MB |
387.js              | admin-user-admin-user-module                   |  1.10 MB |
242.js              | admin-news-admin-news-module                   |  1.10 MB |
330.js              | features-administration-administration-module  | 72.89 kB |
35.js               | xhr2                                           | 43.54 kB |
344.js              | admin-daily-picture-admin-daily-picture-module |  6.62 kB |
244.js              | admin-forum-admin-forum-module                 |  6.09 kB |
284.js              | features-streaming-streaming-module            |  3.29 kB |

Build at: 2023-05-14T13:04:51.319Z - Hash: 0c1d65ee146b333b - Time: 16348ms

Initial Chunk Files                    | Names         |   Raw Size
main.js                                | main          |    2.57 MB |
styles.css                             | styles        | 1003.13 kB |
polyfills.js                           | polyfills     |   82.88 kB |

                                       | Initial Total |    3.63 MB

Lazy Chunk Files                       | Names         |   Raw Size
news.module-MAHVQVT7.js                | -             |   20.99 MB |
pages.module-2ITG4FMB.js               | -             |   19.51 MB |
forum.module-4I6F4QEL.js               | -             |   12.93 MB |
esport.module-DYSHFDAV.js              | -             |   12.33 MB |
homepage.module-XXE7L2WO.js            | -             |   12.27 MB |
clan.module-QMZQE5UV.js                | -             |    9.84 MB |
daily-picture.module-OB2T6AUD.js       | -             |    9.76 MB |
user.module-RECSCOR7.js                | -             |    8.70 MB |
chunk-BNSHXA3C.js                      | -             |    7.42 MB |
chunk-XESVUIN5.js                      | -             |  810.96 kB |
chunk-KQJ6VHA3.js                      | -             |  429.67 kB |
chunk-HA76PMJY.js                      | -             |  298.03 kB |
chunk-ACGQPL24.js                      | -             |  275.35 kB |
chunk-OVDAMZXV.js                      | -             |  260.21 kB |
chunk-7MQHIVYY.js                      | -             |  183.32 kB |
chunk-X33WPSBW.js                      | -             |  118.14 kB |
chunk-T4XHN7RM.js                      | -             |   94.96 kB |
chunk-Z453O26S.js                      | -             |   82.11 kB |
chunk-QVZLTR3H.js                      | -             |   71.13 kB |
chunk-O3R7LPY6.js                      | -             |   66.12 kB |
chunk-Z7ZBG2BC.js                      | -             |   56.66 kB |
administration.module-MKQS55DO.js      | -             |   48.04 kB |
admin-esport.module-FDFIAVSG.js        | -             |   41.64 kB |
admin-user.module-LOOPD7T3.js          | -             |   37.34 kB |
admin-news.module-VQ27TVMG.js          | -             |   35.74 kB |
chunk-OCAZJ2GF.js                      | -             |   34.77 kB |
chunk-VJF7O6YP.js                      | -             |   30.98 kB |
chunk-VSY7ZGPP.js                      | -             |   29.11 kB |
chunk-UQRM5CW2.js                      | -             |   21.52 kB |
chunk-SNEEZHT6.js                      | -             |   21.22 kB |
chunk-X3SU24NO.js                      | -             |   16.90 kB |
chunk-ZEEAIQZS.js                      | -             |   13.90 kB |
chunk-NEKG3SLI.js                      | -             |   12.95 kB |
chunk-RWI2Y6U4.js                      | -             |   10.20 kB |
chunk-663GXPGE.js                      | -             |    6.55 kB |
chunk-6IYI7IJV.js                      | -             |    6.39 kB |
chunk-H6JIBRCA.js                      | -             |    5.59 kB |
admin-daily-picture.module-YLDY65KR.js | -             |    4.16 kB |
admin-forum.module-KVFAOXIS.js         | -             |    3.80 kB |
chunk-BELNFT5O.js                      | -             |    3.65 kB |
chunk-K3NTOBNJ.js                      | -             |    3.59 kB |
chunk-7DGAGFTQ.js                      | -             |    3.57 kB |
chunk-FGUGYKKC.js                      | -             |    2.98 kB |
chunk-D3Q3W7CI.js                      | -             |    2.92 kB |
chunk-TEW55TLO.js                      | -             |    2.39 kB |
chunk-LV4DE6NK.js                      | -             |    2.29 kB |
chunk-3L3T4IBG.js                      | -             |    2.26 kB |
streaming.module-QXTIA2NE.js           | -             |    1.80 kB |
chunk-M3SEBM6O.js                      | -             |    1.47 kB |
chunk-6VXAC77B.js                      | -             |    1.45 kB |
chunk-3MSCK7TP.js                      | -             |    1.23 kB |
chunk-6UYUG4Q2.js                      | -             |    1.22 kB |
chunk-7QGIZ4XQ.js                      | -             |    1.17 kB |
chunk-OPEXLCGD.js                      | -             |    1.15 kB |

Application bundle generation complete. [37.541 seconds]
Watch mode enabled. Watching for file changes...

Compiled successfully.
** Angular Universal Live Development Server is listening on http://localhost:4200, open your browser on http://localhost:4200 **
Angular is running in development mode.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.1
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 16.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@nguniversal/builders           16.0.1
@nguniversal/express-engine     16.0.1
@schematics/angular             16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

package.json
```
{
  "name": "gamers-client",
  "version": "0.0.0",
  "engines": {
    "node": "17.x"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "start:dev": "ng serve -c staging",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test --watch=false --browsers ChromeHeadless",
    "lint": "npx eslint \"src/**/*.{js,jsx,ts,tsx,html,css,scss}\" --quiet --fix",
    "format": "npx prettier \"src/**/*.{js,jsx,ts,tsx,html,css,scss}\" --write",
    "e2e": "ng e2e",
    "prepare": "husky install",
    "dev:ssr": "ng run gamers-client:serve-ssr",
    "serve:ssr": "node dist/gamers-client/server/main.js",
    "build:prod:ssr": "ng build && gzipper compress ./dist && ng run gamers-client:server",
    "build:stage:ssr": "ng build -c staging && gzipper compress ./dist && ng run gamers-client:server",
    "prerender": "ng run gamers-client:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.0.1",
    "@angular/cdk": "^16.0.1",
    "@angular/common": "^16.0.1",
    "@angular/compiler": "^16.0.1",
    "@angular/core": "^16.0.1",
    "@angular/forms": "^16.0.1",
    "@angular/platform-browser": "^16.0.1",
    "@angular/platform-browser-dynamic": "^16.0.1",
    "@angular/platform-server": "^16.0.1",
    "@angular/router": "^16.0.1",
    "@auth0/angular-jwt": "^5.1.2",
    "@nguniversal/express-engine": "^16.0.1",
    "express": "^4.18.2",
    "gzipper": "^7.2.0",
    "primeflex": "^3.3.0",
    "primeicons": "^6.0.1",
    "primeng": "^16.0.0-rc.1",
    "pusher-js": "^8.0.2",
    "quill": "^1.3.7",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.1",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.0.1",
    "@angular-eslint/builder": "16.0.1",
    "@angular-eslint/eslint-plugin": "16.0.1",
    "@angular-eslint/eslint-plugin-template": "16.0.1",
    "@angular-eslint/schematics": "16.0.1",
    "@angular-eslint/template-parser": "16.0.1",
    "@angular/cli": "^16.0.1",
    "@angular/compiler-cli": "^16.0.1",
    "@nguniversal/builders": "^16.0.1",
    "@types/express": "^4.17.13",
    "@types/jasmine": "~4.3.0",
    "@types/node": "^18.15.1",
    "@typescript-eslint/eslint-plugin": "^5.59.2",
    "@typescript-eslint/parser": "^5.59.2",
    "eslint": "^8.39.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsdoc": "39.3.14",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "eslint-plugin-prettier": "^4.2.1",
    "husky": "^8.0.3",
    "jasmine-core": "~4.5.0",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "prettier": "2.8.7",
    "protractor": "~7.0.0",
    "ts-node": "~10.9.1",
    "typescript": "~5.0.4"
  }
}
```

**Comment by JoostK** [comment]
This sounds like a long-running task (for example `setTimeout`) that prevents the app from becoming stable until after a minute has passed, which prevents the response to be sent.

This won't be actionable without reproduction; the staging link does not provide any insights since the stall occurs in the backend.

**Comment by armingdev** [comment]
> This sounds like a long-running task (for example `setTimeout`) that prevents the app from becoming stable until after a minute has passed, which prevents the response to be sent.
> 
> This won't be actionable without reproduction; the staging link does not provide any insights since the stall occurs in the backend.

I will try to set up a fresh angular app with the same packages and dependencies to see if I can reproduce it and share.

Besides that, I have found a new issue on a fresh angular app created with Angular CLI. I have just added angular universal and started the app with: ```npm run dev:ssr```.

If I open localhost:4200 with Chrome browser, there is no errors in the console, but with Mozilla Firefox Developer Edition, it throws error:

```shell
ng run angapp:serve-ssr
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
✔ Browser application bundle generation complete.
✔ Server application bundle generation complete.

Initial Chunk Files | Names         | Raw Size
vendor.js           | vendor        |  4.82 MB |
main.js             | main          | 67.95 kB |

                    | Initial Total |  4.89 MB

Lazy Chunk Files    | Names         | Raw Size
35.js               | xhr2          | 43.54 kB |

Build at: 2023-05-14T21:53:19.169Z - Hash: 4115159459e5d6de - Time: 2031ms
✔ Index html generation complete.

5 unchanged chunks

Build at: 2023-05-14T21:53:19.250Z - Hash: 47bb0bc060990eac - Time: 2965ms

Compiled successfully.
** Angular Universal Live Development Server is listening on http://localhost:4200, open your browser on http://localhost:4200 **
Angular is running in development mode.
Angular is running in development mode.
Angular is running in development mode.
./node_modules/@angular/router/fesm2022/router.mjs:3655
        return new ɵRuntimeError(4002 /* RuntimeErrorCode.NO_MATCH */, (typeof ngDevMode === 'undefined' || ngDevMode) &&
               ^


RuntimeError: NG04002: Cannot match any routes. URL Segment: 'robots.txt'
    at noMatchError (./node_modules/@angular/router/fesm2022/router.mjs:3655:16)
    at e (./node_modules/@angular/router/fesm2022/router.mjs:3670:28)
    at onError (./node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51)
    at _error (./node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
    at error (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at _error (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at error (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at _error (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at error (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at OperatorSubscriber.Subscriber._error (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30) {
  code: 4002
}

Node.js v18.16.0
A server error has occurred.
node exited with 1 code.
```

**Comment by armingdev** [comment]
After a couple of days of debugging, I figured out the issue and fixed it. I will write it down if someone had a similar issue.

The issue was caused by my pusher service. I have added a check for a platform to be sure that the connection is being made only on the client side. 

The old version of a file:

```typescript
import { Injectable } from '@angular/core';

import { environment } from '../../../environments/environment';
import { AuthService } from './auth.service';
import Pusher from 'pusher-js';

@Injectable({
  providedIn: 'root',
})
export class PusherService {
  private readonly pusher: Pusher;

  constructor(private readonly authService: AuthService) {
    this.pusher = new Pusher(environment.pusher.key, {
      cluster: environment.pusher.cluster,
      authEndpoint: environment.pusher.authEndpoint,
      forceTLS: true,
      auth: {
        headers: {
          Authorization: `Bearer ${this.authService.getToken()}`,
        },
      },
    });
  }

  getPusher(): any {
    return true;
  }
}

``` 

New version of the file:

```typescript
import { Injectable, Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { environment } from '../../../environments/environment';
import { AuthService } from './auth.service';
import Pusher from 'pusher-js';

@Injectable({
  providedIn: 'root',
})
export class PusherService {
  private pusher: Pusher | null = null;

  constructor(@Inject(PLATFORM_ID) private platformId: Object, private readonly authService: AuthService) {}

  getPusher(): Pusher {
    if (!this.pusher && isPlatformBrowser(this.platformId)) {
      this.pusher = new Pusher(environment.pusher.key, {
        cluster: environment.pusher.cluster,
        authEndpoint: environment.pusher.authEndpoint,
        forceTLS: true,
        auth: {
          headers: {
            Authorization: `Bearer ${this.authService.getToken()}`,
          },
        },
      });
    }
    if (this.pusher) {
      return this.pusher;
    } else {
      throw new Error('Pusher is not initialized');
    }
  }
}

``` 

Load time is fine now and everything works fine.

**Comment by AndrewKushnir** [comment]
@armingdev thanks for the update 👍 Happy to hear that the problem is now resolved.
