### ISSUE TITLE
ReferenceError: i0 is not defined - angular 16 - platformBrowserDynamic()

### ISSUE THREAD

**Issue by MateuszCieslak** [angular/angular#50360]
### Which @angular/* package(s) are the source of the bug?

platform-browser-dynamic

### Is this a regression?

No

### Description

Hey, 
I'm working on angular upgrade in my company project. It's quite complicated project which use webpack, karma etc. tools. I'm upgrading from angular 15.0.3. I have problem running tests and it looks like bug in platform-browser-dynamic. Error occurs when I jus call platfomBrowserDynamic() function for ex:
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
platformBrowserDynamic();
```

The error is: 
 An error was thrown in afterAll
  ReferenceError: i0 is not defined
      at <static_initializer> (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:31710:26)
      at ../../common/temp/node_modules/.pnpm/@angular/common@16.0.2_@angular+core@16.0.2+rxjs@7.5.0/node_modules/@angular/common/fesm2022/common.mjs (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:31682:18)
      at __webpack_require__ (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/runtime.js:23:42)
      at ../../common/temp/node_modules/.pnpm/@angular/platform-browser-dynamic@16.0.2_79799a0a44845b8f7c89830587e6b018/node_modules/@angular/platform-browser-dynamic/fesm2022/platform-browser-dynamic.mjs (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:123940:73)
      at __webpack_require__ (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/runtime.js:23:42)
      at ../../common/temp/node_modules/.pnpm/@angular/platform-browser-dynamic@16.0.2_79799a0a44845b8f7c89830587e6b018/node_modules/@angular/platform-browser-dynamic/fesm2022/testing.mjs (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:124178:91)
      at __webpack_require__ (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/runtime.js:23:42)
      at ./test/unit/index.ts (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:25907:17)
      at __webpack_require__ (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/runtime.js:23:42)
      at __webpack_exec__ (index.2224284476.js:4:48)
Chrome Headless 113.0.5672.63 (Mac OS 10.15.7): Executed 0 of 0 ERROR (0.012 secs / 0 secs)

If I switch back to 15.0.3 everything is fine. Any ideas?

### Please provide the exception or error you saw

```true
An error was thrown in afterAll
  ReferenceError: i0 is not defined
      at <static_initializer> (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:31710:26)
      at ../../common/temp/node_modules/.pnpm/@angular/common@16.0.2_@angular+core@16.0.2+rxjs@7.5.0/node_modules/@angular/common/fesm2022/common.mjs (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:31682:18)
      at __webpack_require__ (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/runtime.js:23:42)
      at ../../common/temp/node_modules/.pnpm/@angular/platform-browser-dynamic@16.0.2_79799a0a44845b8f7c89830587e6b018/node_modules/@angular/platform-browser-dynamic/fesm2022/platform-browser-dynamic.mjs (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:123940:73)
      at __webpack_require__ (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/runtime.js:23:42)
      at ../../common/temp/node_modules/.pnpm/@angular/platform-browser-dynamic@16.0.2_79799a0a44845b8f7c89830587e6b018/node_modules/@angular/platform-browser-dynamic/fesm2022/testing.mjs (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:124178:91)
      at __webpack_require__ (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/runtime.js:23:42)
      at ./test/unit/index.ts (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/commons.js:25907:17)
      at __webpack_require__ (/var/folders/s3/2hwn00rj6ss1p58tcykkg3cx4c_3km/T/_karma_webpack_968000/runtime.js:23:42)
      at __webpack_exec__ (index.2224284476.js:4:48)
Chrome Headless 113.0.5672.63 (Mac OS 10.15.7): Executed 0 of 0 ERROR (0.012 secs / 0 secs)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular cli 16.0.3
Node 16.17.1
npm 8.15.0
```

**Comment by JoostK** [comment]
Angular 16 switched to ES2022, which likely results in a miscompile due to some configuration options. Without a reproduction this isn't actionable for us though.

**Comment by MateuszCieslak** [comment]
Hey, 
Adding reproduction code: 

Here is repo: https://github.com/MateuszCieslak/angular-16-i0-is-not-defined

or if you just want to see it here I paste files below. 

package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node node_modules/karma/bin/karma start karma.config.js --browsers=ChromeHeadlessNoSandbox --single-run"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/compiler": "16.0.2",
    "@angular/core": "16.0.2",
    "@angular/forms": "16.0.2",
    "@angular/platform-browser": "16.0.2",
    "@angular/platform-browser-dynamic": "16.0.2",
    "file-loader": "6.2.0",
    "sass-loader": "13.0.0",
    "html-loader": "3.1.0",
    "html-webpack-plugin": "5.5.0",
    "css-loader": "6.7.1",
    "style-loader": "3.3.1",
    "ts-loader": "9.4.2",
    "jasmine": "4.5.0",
    "jasmine-core": "4.5.0",
    "jasmine-spec-reporter": "7.0.0",
    "karma": "6.3.20",
    "karma-chrome-launcher": "3.1.1",
    "karma-coverage": "2.2.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-file-fixtures-preprocessor": "3.0.1",
    "karma-html-reporter": "0.2.7",
    "karma-istanbul-threshold": "1.2.3",
    "karma-jasmine": "2.0.1",
    "karma-junit-reporter": "2.0.1",
    "karma-remap-coverage": "0.1.5",
    "karma-sourcemap-loader": "0.3.8",
    "karma-spec-reporter": "0.0.34",
    "karma-viewport": "1.0.9",
    "karma-webpack": "5.0.0",
    "webpack": "5.73.0",
    "webpack-cli": "4.10.0",
    "webpack-config": "7.5.0",
    "webpack-dev-server": "4.9.2",
    "@types/webpack": "5.28.0",
    "@types/webpack-env": "1.17.0",
    "@types/jasmine": "4.3.0"
  },
  "devDependencies": {}
}
```

karma.config.json
```
const path = require('path');
const cwd = process.cwd();

const isTestDebug = process.argv.some(arg => arg === '--auto-watch');

module.exports = config => {
    config.set({
        browsers: ['Chrome'],
        client: {
            jasmine: {
                random: false,
            },
            captureConsole: true,
            useIframe: true, 
        },
        colors: true,
    
        coverageReporter: {
            type: 'html',
            dir: path.resolve(cwd, 'coverage'),
            subdir: '.', 
            check: {
                global: {
                    statements: 80,
                    branches: 80,
                    functions: 80,
                    lines: 80,
                },
            },
            instrumenterOptions: {
                istanbul: { noCompact: true },
            },
        },
    
        customLaunchers: {
            ChromeHeadlessNoSandbox: {
                base: 'ChromeHeadless',
                flags: ['--no-sandbox'],
            },
        },
        
        mime: { 'text/x-typescript': ['ts', 'tsx'] },
    
        port: 9876,
    
        singleRun: true,

        basePath: cwd,

        files: ['test/unit/index.@(js|ts)'],
        preprocessors: {
            'test/unit/index.@(js|ts)': ['webpack', 'sourcemap'],
        },

        frameworks: [
            'jasmine', 'viewport', 'webpack'
        ],
        plugins: [
            'karma-chrome-launcher',
            'karma-coverage',
            'karma-jasmine',
            'karma-junit-reporter',
            'karma-viewport', 'karma-sourcemap-loader', 'karma-webpack'
        ],

        logLevel: config.LOG_ERROR,

        webpackMiddleware: {
            logLevel: 'error',
        },
        webpack: {
            stats: 'errors-only',
            mode: 'development',
            devtool: 'inline-source-map',
            watch: isTestDebug,
            resolve: {
                extensions: ['.ts', '.tsx', '.js', '.jsx', '.scss'],
                alias: {

                },
                symlinks: true,
                fallback: {
                    path: false, 
                },
            },
            module: {
                rules: [
                    {
                        test: /\.(ts|tsx|jsx)$/,
                        include: [
                            path.resolve(cwd, 'app'),
                            path.resolve(cwd, 'src'),
                            path.resolve(cwd, 'test'),
                        ],
                        exclude: /node_modules/,
                        use: [
                            {
                                loader: 'ts-loader',
                                options: {
                                    compilerOptions: {
                                        declaration: false,
                                        noEmit: false,
                                    },
                                },
                            },
                        ],
                    }
                ],
                noParse: /typescript[\\/]lib[\\/]typescript\.js$/,
            },
            output: {
                pathinfo: false,
            },
            // resolveLoader: { modules: ['node_modules/gs-uitk-build/node_modules'] },
        },
    });
};
```

tsconfig.json
```
{
    "compilerOptions": {
        "target": "es2022",
        "declaration": true,
        "skipLibCheck": true,
        "importHelpers": true,
        "downlevelIteration": true,
        "strict": true,
        "alwaysStrict": true,
        "noUnusedLocals": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "esModuleInterop": true,
        "sourceMap": true,
        "inlineSourceMap": false,
        "inlineSources": true,
        "emitDecoratorMetadata": true,
        "outDir": "./dist",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "lib": ["dom", "es2022"],
        "jsx": "react",
        "rootDir": "..",
        "module": "commonjs",
        "types": ["webpack-env", "jasmine"]
    },
    "include": ["../src/**/*", "./test/**/*"],
}
```

test/unit/index.ts
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
platformBrowserDynamic();

describe('foo', () => {
    it('bar', () => {
        expect(true).toBe(true);
    });
})
```

**Comment by JoostK** [comment]
es2022 syntax was not supported prior to webpack [5.74.0](https://github.com/webpack/webpack/releases/tag/v5.74.0), so updating webpack resolves this issue.
