### ISSUE TITLE
TypeError: Cannot read property '_inFakeAsyncZone' of undefined

### ISSUE THREAD

**Issue by fcoury** [angular/angular#5053]
When trying to use `fakeAsync` on the following test:

```
  describe('searchTrack', () => {
    it('searches type and term',
      inject([SpotifyService, MockBackend], fakeAsync((svc, backend) => {
        var res;
        expectURL(backend, 'https://api.spotify.com/v1/search?q=TERM&type=track');
        svc.searchTrack("TERM").subscribe((_res) => {
          res = _res;
        });
        tick();
        expect(res).toBe({name: 'felipe'});
      }))
    );
  });
```

I get the following failure:

```
TypeError: Cannot read property '_inFakeAsyncZone' of undefined
    at Object.fakeAsync (http://localhost:9876/base/test.bundle.js:26900:28)
    at Suite.<anonymous> (http://localhost:9876/base/test.bundle.js:48369:137)
    at Suite.<anonymous> (http://localhost:9876/base/test.bundle.js:48368:16)
    at Object.<anonymous> (http://localhost:9876/base/test.bundle.js:48350:2)
    at __webpack_require__ (http://localhost:9876/base/test.bundle.js:20:30)
    at webpackContext (http://localhost:9876/base/test.bundle.js:1078:10)
    at Array.forEach (native)
    at Array.forEach (http://localhost:9876/base/vendor/es6-shim.js:1159:14)
    at Object.<anonymous> (http://localhost:9876/base/test.bundle.js:54:17)
    at __webpack_require__ (http://localhost:9876/base/test.bundle.js:20:30)
    at http://localhost:9876/base/test.bundle.js:40:18
    at http://localhost:9876/base/test.bundle.js:43:10window.__karma__.result @ debug.html:38KarmaReporter.specDone @ adapter.js:252dispatch @ jasmine.js:1869(anonymous function) @ jasmine.js:1852specResultCallback @ jasmine.js:813complete @ jasmine.js:362clearStack @ jasmine.js:605QueueRunner.run @ jasmine.js:1784QueueRunner.execute @ jasmine.js:1762Env.queueRunnerFactory @ jasmine.js:627Spec.execute @ jasmine.js:353fn @ jasmine.js:2360attemptAsync @ jasmine.js:1819QueueRunner.run @ jasmine.js:1774QueueRunner.execute @ jasmine.js:1762Env.queueRunnerFactory @ jasmine.js:627fn @ jasmine.js:2345attemptAsync @ jasmine.js:1819QueueRunner.run @ jasmine.js:1774QueueRunner.execute @ jasmine.js:1762Env.queueRunnerFactory @ jasmine.js:627fn @ jasmine.js:2345attemptAsync @ jasmine.js:1819QueueRunner.run @ jasmine.js:1774QueueRunner.execute @ jasmine.js:1762Env.queueRunnerFactory @ jasmine.js:627TreeProcessor.execute @ jasmine.js:2209Env.execute @ jasmine.js:678(anonymous function) @ adapter.js:318window.__karma__.loaded @ debug.html:42(anonymous function) @ debug.html:66
debug.html:35 FAILED SpotifyService getArtist encountered a declaration exception
```

Tracing the error I found that the offending line is the following:

```
	function fakeAsync(fn) {
	    if (lang_1.global.zone._inFakeAsyncZone) { // <-- offending line
	        throw new Error('fakeAsync() calls can not be nested');
	    }
	    var fakeAsyncZone = lang_1.global.zone.fork({
	        setTimeout: _setTimeout,
```

It seems that `global.zone` is not defined anywhere. What can I be doing wrong?

**Comment by fcoury** [comment]
It seems zone.js isn't being loaded before my tests run. After I did everything works again.
