### ISSUE TITLE
Application doesn't boot with static fields and turned off aot

### ISSUE THREAD

**Issue by B1Z1** [angular/angular#50695]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Hi! After upgrading from version 15 to version 16, we encountered an error. The application fails to start when a static field utilizes another static field within the class. Although it works fine with Ahead-of-Time (AOT) compilation, we are unable to use AOT as it is twice as slow as Just-in-Time (JiT) compilation.

This issue is preventing us from updating Angular to the latest version, but resolving it will enable us to proceed with the update.

### Please provide a link to a minimal reproduction of the bug

https://github.com/B1Z1/angular-16-aot-bug

### Please provide the exception or error you saw

```true
Uncaught TypeError: Cannot read properties of undefined (reading 'STATIC_FIELD')
    at 5041 (main.js:30:75)
    at __webpack_require__ (runtime.js:23:42)
    at 6747 (main.js:54:72)
    at __webpack_require__ (runtime.js:23:42)
    at 4431 (main.js:79:73)
    at __webpack_require__ (runtime.js:23:42)
    at __webpack_exec__ (main.js:117:48)
    at main.js:118:78
    at __webpack_require__.O (runtime.js:57:23)
    at main.js:119:56
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.5
Node: 16.16.0
Package Manager: npm 9.6.0
OS: darwin arm64

Angular: 16.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.5
@angular-devkit/build-angular   16.0.5
@angular-devkit/core            16.0.5
@angular-devkit/schematics      16.0.5
@schematics/angular             16.0.5
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by JoostK** [comment]
This is because of https://github.com/microsoft/TypeScript/issues/52004, more info available in https://github.com/angular/angular/issues/48764#issuecomment-1407755457.

The TypeScript issue has been addressed in TypeScript 5.1, which will be supported by Angular 16.1 (slated for release during this week).
