### ISSUE TITLE
RuntimeError: NG0205 error on subscribe http client

### ISSUE THREAD

**Issue by NeerajThapliyal** [angular/angular#50739]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

error in ssr http call
RuntimeError: NG0205
    at R3Injector.assertNotDestroyed (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1861905)
    at R3Injector.runInContext (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1859941)
    at HttpInterceptorHandler2.chain (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1696306)
    at HttpInterceptorHandler2.handle (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1698111)
    at MergeMapSubscriber.project (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1693839)
    at MergeMapSubscriber._tryNext (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1150870)
    at MergeMapSubscriber._next (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1150762)
    at MergeMapSubscriber.next (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1079637)
    at Observable3._subscribe (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1202036)
    at Observable3._trySubscribe (/Users/neerajthapliyal/Documents/projects/toolsvila/tools-web/dist/server/main.js:1:1067917) {
  code: 205

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node: v18.12.1
Package Manager: npm 8.19.2 
OS: Mac OS

Angular: 16
```

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
