### ISSUE TITLE
Parentheses in url cause Error: NG04002: Cannot match any routes.

### ISSUE THREAD

**Issue by michaelbromley** [angular/angular#50787]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

When a url contains parentheses such as `localhost:4200/(1)`, the router will throw the error `Error: NG04002: Cannot match any routes.`

In an Angular Universal app I have, this causes the entire node process to crash (which is another issue....).

Some notes on what type of urls cause the issue:

- `/(1)` -> Cannot match any routes. URL Segment: '1'
- `/(foo)` -> Cannot match any routes. URL Segment: 'foo'
- `/(foo:bar)` -> Cannot match any routes. URL Segment: 'bar'
- `/(foo;bar)` -> Cannot match any routes. URL Segment: 'foo;bar='
- `/(foo?)` ->no error
- `/()` -> no error
- `/(foo` -> no error
- `/foo)` -> no error

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-router-parentheses-issue?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Error: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: '1'
Error: NG04002: Cannot match any routes. URL Segment: '1'
at Recognizer.noMatchError (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/@angular/router@16.1.1/fesm2022/router.mjs:3713:16)
at eval (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/@angular/router@16.1.1/fesm2022/router.mjs:3728:28)
at eval (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/rxjs@7.8.1/dist/cjs/internal/operators/catchError.js:13:51)
at OperatorSubscriber._this._error (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/rxjs@7.8.1/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
at Subscriber.error (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/rxjs@7.8.1/dist/cjs/internal/Subscriber.js:60:18)
at Subscriber._error (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/rxjs@7.8.1/dist/cjs/internal/Subscriber.js:84:30)
at Subscriber.error (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/rxjs@7.8.1/dist/cjs/internal/Subscriber.js:60:18)
at Subscriber._error (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/rxjs@7.8.1/dist/cjs/internal/Subscriber.js:84:30)
at Subscriber.error (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/rxjs@7.8.1/dist/cjs/internal/Subscriber.js:60:18)
at Subscriber._error (https://angular-router-parentheses-issue.stackblitz.io/turbo_modules/rxjs@7.8.1/dist/cjs/internal/Subscriber.js:84:30)
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular core, route @ 16.1.1
```

**Comment by JeanMeche** [comment]
You can't use parenthesis in URLs in Angular as they are used for [named outlets](https://angular.io/api/router/RouterOutlet#description).

See #24921

**Comment by michaelbromley** [comment]
Thanks for the reference! 

The situation is that we have migrated a site to Angular Universal, and some old legacy URLs have parentheses in them, so links to these urls are still being used. So I have no control over the encoding in this case.

Due to this issue, whenever somebody visits one of these URLs, the Angular Universal server crashes (!!!!), bringing our website down until the container is restarted. 

As I said - the issue of runtime errors causing the Angular Universal server to crash is a whole separate (and serious) issue.

But in terms on the angular router, it seems like it should be able to handle these characters gracefully - if they are interpreted as named outlets and don't match anything, just use my catchall `**` route.

**Comment by michaelbromley** [comment]
The work-around given in the linked issue is to use a custom UrlSerializer. Here's what works for me. Note that using this work-around means that you cannot then use named outlets in your app.

```ts
import { DefaultUrlSerializer, UrlTree } from "@angular/router";
import { Injectable } from "@angular/core";

/**
 * A workaround for this issue: https://github.com/angular/angular/issues/50787
 */
@Injectable({ providedIn: 'root' })
export class CustomUrlSerializer extends DefaultUrlSerializer {
    parse(url: string): UrlTree {
        return super.parse(this.removeParentheses(url));
    }

    private removeParentheses(url: string): string {
        return url.replace(/\(.+\)/g, '');
    }
}
```

```ts
@NgModule({
    declarations: [AppComponent],
    imports: [
        // ...
    ],
    bootstrap: [AppComponent],
    providers: [
        // ...
        {
            provide: UrlSerializer,
            useClass: CustomUrlSerializer,
        }
    ],
})
export class AppModule {}
```

**Comment by michaelbromley** [comment]
Update: we just had our production ecommerce app crash multiple times today due to this issue.

We were being probed by an attacker with urls like this:

```
domain.com/(select(0)from(select(sleep(15)))v)%2f*'+(select(0)from(select(sleep(15)))v)+'%22+(select(0)from(select(sleep(15)))v)+%22*%2f
```

A url like this `domain.com/((1))` will crash an Angular Universal express server, even with the custom UrlSerializer given in my above comment, due to the nested parens. I updated it to this which now prevents crashes even in this case:

```ts
@Injectable({ providedIn: 'root' })
export class CustomUrlSerializer extends DefaultUrlSerializer {
    parse(url: string): UrlTree {
        return super.parse(this.removeParentheses(url));
    }

    private removeParentheses(url: string): string {
        const regex = /(\(|\))/g;
        const encodedString = url.replace(regex, (match) => {
            if (match === '(') {
                return '%28'; // URL-encoded version of "("
            } else {
                return '%29'; // URL-encoded version of ")"
            }
        });
        return encodedString;
    }
}
```

**Comment by abishai53** [comment]
`url.replace(/[()]/g, '');`

**Comment by debdolph** [comment]
Any progress here? This is a very critical issue. One special crafted request can lead the whole application to crash!

**Comment by abishai53** [comment]
There are resolutions provided above. You didn't see any?

**Comment by mdjuric-itk** [comment]
Does anyone have a problem when pasting a link to the url? Angular always redirects me to home page and link in Navigation start looks like this `'/http:%2F%2Flocalhost:4200%2Fconfiguration'`, instead of `'/configuration'`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
