### ISSUE TITLE
aio build failed on Windows/Vercel (v16)

### ISSUE THREAD

**Issue by han41858** [angular/angular#50982]
### Describe the problem that you experienced

Hi, I'm the maintainer of angular.kr.
After new version released, I'm updating docs for v16.

After for a long time to merge codes, I did run `yarn build`.

But builds failed in Windows environment.
And I'm using vercel.com for hosting and CI/CD,
build failed with same reason.
This is logs.

```
[11:56:17.044] Running build in San Francisco, USA (West) – sfo1
[11:56:17.104] Cloning github.com/han41858/angular-ko (Branch: main, Commit: 7b22519)
[11:56:17.226] Previous build cache not available
[11:56:22.990] Cloning completed: 5.886s
[11:56:23.959] Running "vercel build"
[11:56:24.436] Vercel CLI 31.0.1
[11:56:25.313] Warning: Detected "engines": { "node": ">=16.14.0" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[11:56:25.315] Installing dependencies...
[11:56:25.733] yarn install v1.22.17
[11:56:25.820] [1/5] Validating package.json...
[11:56:25.824] [2/5] Resolving packages...
[11:56:26.340] [3/5] Fetching packages...
[11:56:52.949] [4/5] Linking dependencies...
[11:56:52.952] warning " > @angular/material@16.0.0" has incorrect peer dependency "@angular/cdk@16.0.0".
[11:56:52.957] warning "@angular/build-tooling > @bazel/concatjs@5.8.1" has unmet peer dependency "karma-firefox-launcher@>=1.0.0".
[11:56:52.958] warning "@angular/build-tooling > @bazel/concatjs@5.8.1" has unmet peer dependency "karma-junit-reporter@>=2.0.0".
[11:56:52.958] warning "@angular/build-tooling > @bazel/concatjs@5.8.1" has unmet peer dependency "karma-requirejs@>=1.0.0".
[11:56:52.958] warning "@angular/build-tooling > @bazel/concatjs@5.8.1" has unmet peer dependency "karma-sourcemap-loader@>=0.3.0".
[11:56:52.958] warning "@angular/build-tooling > @bazel/terser@5.8.1" has unmet peer dependency "terser@>=4.0.0 <5.9.0".
[11:56:52.958] warning "@angular/build-tooling > @angular/benchpress > @angular/core@14.3.0" has incorrect peer dependency "zone.js@~0.11.4 || ~0.12.0".
[11:56:52.960] warning " > tsec@0.2.7" has unmet peer dependency "@bazel/concatjs@>=5.3.0".
[11:57:23.332] [5/5] Building fresh packages...
[11:57:25.378] $ node tools/cli-patches/patch.js
[11:57:25.503] /bin/sh: patch: command not found
[11:57:25.509] /vercel/path0/aio/node_modules/shelljs/src/common.js:401
[11:57:25.509]       if (config.fatal) throw e;
[11:57:25.509]                         ^
[11:57:25.509] 
[11:57:25.509] Error: exec: /bin/sh: patch: command not found
[11:57:25.509] 
[11:57:25.509]     at Object.error (/vercel/path0/aio/node_modules/shelljs/src/common.js:110:27)
[11:57:25.509]     at execSync (/vercel/path0/aio/node_modules/shelljs/src/exec.js:120:12)
[11:57:25.509]     at Object._exec (/vercel/path0/aio/node_modules/shelljs/src/exec.js:223:12)
[11:57:25.509]     at Object.exec (/vercel/path0/aio/node_modules/shelljs/src/common.js:335:23)
[11:57:25.510]     at /vercel/path0/aio/tools/cli-patches/patch.js:11:27
[11:57:25.510]     at Array.forEach (<anonymous>)
[11:57:25.510]     at Object.<anonymous> (/vercel/path0/aio/tools/cli-patches/patch.js:11:8)
[11:57:25.510]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[11:57:25.510]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[11:57:25.510]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[11:57:25.510] 
[11:57:25.511] Node.js v18.16.1
[11:57:25.521] error Command failed with exit code 1.
[11:57:25.521] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[11:57:25.565] Error: Command "yarn install" exited with 1
```

Build success on Mac.

I think, the build script is verified only Mac.
Do I need to do anything further to fix the problem?

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
build success on Mac
but failed on Windows, Vercel
```

**Comment by JoostK** [comment]
This has been the case since Angular 10, as changed in #37896.

The [developer docs](https://github.com/angular/angular/blob/2b0850331105f72d9128e63dfffbb1d8af883525/docs/DEVELOPER.md) mention the environment requirements. Specifically:

> **Windows Users:** Git Bash or an equivalent shell is required
_Windows Powershell and cmd shells are not supported https://github.com/angular/angular/issues/46780 so some commands might fail_

I am not familiar with Vercel's build images to tell what's going on there. It's probably a slim Linux container without the necessary dependencies; you'll have to determine how to install additional dependencies in said image.

**Comment by sunilbaba** [comment]
Hi @han41858 ,

  I was able to solve this issue for my local environment by running the below steps in the same order. Can you try these steps to see if it works?
 
 1) yarn
 2) yarn postinstall
 3) yarn rebuild
 4) yarn build

**Comment by han41858** [comment]
Hey~ I solved it.

I found the linux on Vercel is amazon linux.
So, I added install dependency script into settings.

`yum install patch;yarn`

Everything is ok & angular.kr is updated to v16.
Thanks!!
