### ISSUE TITLE
all our unit test don't run anymore after upgrade from 15.2 to 16.1 of angular (NG0402)

### ISSUE THREAD

**Issue by jcompagner** [angular/angular#50998]
### Command

test

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.2.9

### Description

suddenly i get this:

```
 Error: NG0402: A required Injectable was not found in the dependency injection tree. If you are bootstrapping an NgModule, make sure that the `BrowserModule` is imported.
        error properties: Object({ code: 402 })
            at Object.useFactory (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:27584:27)
            at Object.factory (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:9383:38)
            at R3Injector.hydrate (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:9290:35)
            at R3Injector.get (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:9178:33)
            at injectInjectorOnly (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:651:33)
            at ɵɵinject (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:655:60)
            at injectArgs (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:783:23)
            at Object.factory (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:9270:45)
            at R3Injector.hydrate (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:9290:35)
            at R3Injector.get (projects/servoy-public/node_modules/@angular/core/fesm2022/core.mjs:9178:33)
```

i tried to do that BrowserModule import but that didn't help
The message is just not really helpfull if it was something like
Tried to get to inject Constructor from class A with params B and C and trying to create C but that fails. then i did know where the start looking.

the test that fails is i think quite simple and doesn't need a lot of injection:

https://github.com/Servoy/servoy-eclipse/blob/master/com.servoy.eclipse.ngclient.ui/node/projects/servoy-public/src/lib/directives/decimalkeyconverter.directive.spec.ts#L32

if  i comment out this line:
 fixture = TestBed.createComponent(TestDecimalKeyConverterComponent);

then the test runs (and i get just errors that the fixture is not there)

 but if i leave that in i get the above errors..
the only real injection that component needs is:

https://github.com/Servoy/servoy-eclipse/blob/master/com.servoy.eclipse.ngclient.ui/node/projects/servoy-public/src/lib/directives/decimalkeyconverter.directive.ts#L14

so that is the elementRef and our service which i provide as a value:

https://github.com/Servoy/servoy-eclipse/blob/master/com.servoy.eclipse.ngclient.ui/node/projects/servoy-public/src/lib/directives/decimalkeyconverter.directive.spec.ts#L29

i can't find in the release notes or the upgrade path from 15 to 16 what i should change, and from the error message i also don't know what todo (i tried to import BrowserModule in that configureTestBed or just in that ServoyPublicTestingModule which it then imports and exports that all doesn't help

### Minimal Reproduction

see the above git urls.
I can try to make a sample by itself if needed.

### Your Environment

```text
Angular CLI: 16.1.3
Node: 18.16.0
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 16.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.3
@angular-devkit/build-angular   16.1.3
@angular-devkit/core            16.1.3
@angular-devkit/schematics      16.1.3
@schematics/angular             16.1.3
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      5.1.6
```

**Comment by JeanMeche** [comment]
Basicaly looks like a related issue of #35586.
