### ISSUE TITLE
FetchBackend call aborter.abort() in teardown logic even its observer closed.

### ISSUE THREAD

**Issue by leo6104** [angular/angular#51054]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

It raises AbortError for successful api request and it causes unhandled promise error. 

It should check observer.closed condition & aborter.signal.aborted case in teardown logic. 

https://github.com/angular/angular/blob/main/packages/common/http/src/fetch.ts#L57

### Please provide the exception or error you saw

```true
ERROR Error: Uncaught (in promise): AbortError: This operation was aborted
AbortError: This operation was aborted
    at new DOMException (node:internal/per_context/domexception:53:5)
    at AbortController.abort (node:internal/abort_controller:342:18)
    at finalizer (./node_modules/@angular/common/fesm2022/http.mjs:1419:34)
    at execFinalizer (./node_modules/rxjs/dist/cjs/internal/Subscription.js:172:9)
    at call (./node_modules/rxjs/dist/cjs/internal/Subscription.js:89:29)
    at call (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:75:42)
    at unsubscribe (./node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:72:42)
    at execFinalizer (./node_modules/rxjs/dist/cjs/internal/Subscription.js:175:19)
    at call (./node_modules/rxjs/dist/cjs/internal/Subscription.js:89:29)
    at OperatorSubscriber.Subscriber.unsubscribe (./node_modules/rxjs/dist/cjs/internal/Subscriber.js:75:42)
    at resolvePromise (./node_modules/zone.js/fesm2015/zone-node.js:1124:31)
    at v (./node_modules/zone.js/fesm2015/zone-node.js:1031:17)
    at Object.reject (./node_modules/zone.js/fesm2015/zone-node.js:1047:33)
    at abortFetch (node:internal/deps/undici/undici:10687:9)
    at requestObject.signal.addEventListener.once (node:internal/deps/undici/undici:10618:9)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at EventTarget.dispatchEvent (node:internal/event_target:679:26)
    at abortSignal (node:internal/abort_controller:314:10)
    at AbortController.abort (node:internal/abort_controller:344:5)
    at EventTarget.abort (node:internal/deps/undici/undici:7174:18) {
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 16.1.5
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@angular/cdk                    16.2.0-next.0
@angular/cli                    16.1.4
@angular/material               16.2.0-next.0
@angular/youtube-player         16.2.0-next.0
@nguniversal/builders           16.1.1
@nguniversal/common             16.1.1
@nguniversal/express-engine     16.1.1
@schematics/angular             16.1.4
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by JeanMeche** [comment]
Hi Leo, wouldn't you mind sharing a stackblitz repro of the issue ?

**Comment by leo6104** [comment]
@JeanMeche I was tried to build that but... It is quite tricky to reproduce in stackblitz because it seems only appears in node 18 SSR. I will spend more time on the repro. 

I think it is clear to found the causes without reproduction. 

Here is the call stack when its observer.closed == true case in teardown logic. 
Its observer was completed with native SocketError from Node Fetch API. 
<img width="1244" alt="image" src="https://github.com/angular/angular/assets/7777929/f4c07958-464b-498b-a6b6-d4ecba8549f3">

The reason it raises SocketError `UND_ERR_SOCKET` is node internally use `undici` and it doesn't support Http 2 (https://github.com/nodejs/undici/issues/902) 

Our server supports http/2 through nginx.

**Comment by JeanMeche** [comment]
I did poke the same API as you with SSR I couldn't get the error (the endpoint supports `http/1.1`). 

```ts
this.http
  .post(
    'https://mms.sg.mapia.io/mms/graphql',
    { query: '{\n  country\n}' },
    { responseType: 'text' }
  )
  .subscribe(console.log);
```

Are you somehow using an endpoint that only support `http/2` ?

**Comment by JeanMeche** [comment]
@leo6104 Any news about the reproduction ?

**Comment by JeanMeche** [comment]
Without any news, we'll close this. Feel free to reopen if you can provide a repro.
