### ISSUE TITLE
NullInjectorError after Angular 15 upgrade when using custom service to open mat-bottom sheet

### ISSUE THREAD

**Issue by Ranindu15** [angular/angular#51214]
### Which @angular/* package(s) are the source of the bug?

core, upgrade, Don't known / other

### Is this a regression?

No

### Description

After upgrading our Angular application to version 15, we encountered a NullInjectorError when attempting to open a mat-bottom sheet using a custom service. Interestingly, this issue was not present in Angular version 12.

The application should open the mat-bottom sheet without errors, as in Angular version 12. However, after the upgrade to Angular 15, the application throws a NullInjectorError. This error suggests that the custom service's required dependency (DynamicRenderer) is not provided correctly during the injection process.

The DynamicRenderService is used to handle the logic of opening either a mat-bottom sheet or a mat-right sheet based on the device type (mobile, tablet, or desktop). The issue seems specific to the Angular 15 upgrade, as the application works flawlessly in Angular 12.

### Please provide the exception or error you saw

```true
ERROR NullInjectorError: R3InjectorError(DefaultWrapperModule)[DynamicRenderer -> DynamicRenderer -> DynamicRenderer -> DynamicRenderer]: 
  NullInjectorError: No provider for DynamicRenderer!
    at NullInjector.get (vendor.js:53182:21)
    at R3Injector.get (vendor.js:53604:27)
    at R3Injector.get (vendor.js:53604:27)
    at R3Injector.get (vendor.js:53604:27)
    at R3Injector.get (vendor.js:53604:27)
    at ChainedInjector.get (vendor.js:57618:32)
    at lookupTokenUsingModuleInjector (vendor.js:49056:31)
    at getOrCreateInjectable (vendor.js:49099:10)
    at Module.ɵɵdirectiveInject (vendor.js:55652:10)
    at NodeInjectorFactory.RightBottomSheetComponent_Factory [as factory] (default-src_app_core_services_document-generate_service_ts-src_app_core_utils_ui_modal_service_ts.js:479:110)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.9
Node: 16.20.0
Package Manager: npm 8.19.4
OS: linux x64

Angular: 15.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.8
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.9
@angular-devkit/schematics      15.2.9
@schematics/angular             15.2.9
rxjs                            6.6.7
typescript                      4.9.5
```

**Comment by JoostK** [comment]
Unfortunately without a reproduction this won't be actionable.

**Comment by Ranindu15** [comment]
@JoostK what do you mean? This bottom sheet open was working fine in Angular 12. This happen for only this component. That's the case

**Comment by JeanMeche** [comment]
We can't do anything with the info you gave us. A stackblitz reproduction of your issue would be a first step.

**Comment by Ranindu15** [comment]
@JeanMeche i just created the stackblitz project. can you please check this. URL is  `{{base_url}}/menu-items`
 https://stackblitz.com/edit/stackblitz-starters-tfcm2j

**Comment by pkozlowski-opensource** [comment]
@Ranindu15 there is a _lot_ going on in the shared stackblitz - could you please try to narrow down the reproduction scenario to the absolute minimum?

**Comment by JeanMeche** [comment]
@Ranindu15 Can you check the stackblitz you shared, the app doesn't even start and locally it's just a blank screen (an empty router-outlet) .

**Comment by Ranindu15** [comment]
@JeanMeche  please someone can check this. I created test project for that same scenario. This is the stackblitz link. PLEASE NOTE this was working fine in Angular 12.  This is the new link. (APP URL- https://stackblitz-starters-ggh39v.stackblitz.io/menu-items )

this is the stackblitz url : https://stackblitz.com/edit/stackblitz-starters-ggh39v?file=src%2Fapp%2Fmodules%2Ffeedback-menu-items%2Ffeedback-menu-items.component.html

**Comment by JeanMeche** [comment]
@Ranindu15 please provide a working reproduction of your issue. There is still the same issue I mentionned before.

**Comment by Ranindu15** [comment]
@JeanMeche idk this is not working on stackblitz. but working on my local machine. Can u check it? https://stackblitz.com/edit/stackblitz-starters-41vxw2?file=README.md

**Comment by alxhub** [comment]
I'm closing this issue as a working minimal reproduction was not provided, and none of the types mentioned in the error are Angular types. Without a working reproduction it's not possible for us to make any progress on this issue.

@Ranindu15, please feel free to open a new issue with a minimal reproduction of the problem. A minimal reproduction should strip away all unnecessary code, including things like styling, any unnecessary elements in templates, unnecessary indirection or wrapping, etc. It should also include clear instructions on which actions to take to trigger the problem and what the undesired behavior is.
