### ISSUE TITLE
Jest erroring with "Method Promise.prototype.then called on incompatible receiver"

### ISSUE THREAD

**Issue by tonysamperi** [angular/angular#51285]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I did as explained in the article [here](https://blog.angular.io/moving-angular-cli-to-jest-and-web-test-runner-ef85ef69ceca) and have now in my *angular.json*

```
        "test": {
          "builder": "@angular-devkit/build-angular:jest",
          "options": {
            "tsConfig": "tsconfig.spec.json",
            "polyfills": ["zone.js", "zone.js/testing"]
          }
        }
```

But when I run `ng test` I always get the following error.

```
Test suite failed to run

    TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]

      at new SafePromise (../../https:/angular16floatingui-oacd.w-credentialless.staticblitz.com/blitz.d5d65229.js:67:12019)
      at arrayToSafePromiseIterable (../../https:/angular16floatingui-oacd.w-credentialless.staticblitz.com/blitz.d5d65229.js:67:12301)
      at A.SafePromiseAll (../../https:/angular16floatingui-oacd.w-credentialless.staticblitz.com/blitz.d5d65229.js:67:12380)
```

I thought it might have something to do with some async function, so I tried having simply a very basic test. 
But it doesn't seem to have any effect.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-16-floating-ui

### Please provide the exception or error you saw

```true
Test suite failed to run

    TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]

      at new SafePromise (../../https:/angular16floatingui-oacd.w-credentialless.staticblitz.com/blitz.d5d65229.js:67:12019)
      at arrayToSafePromiseIterable (../../https:/angular16floatingui-oacd.w-credentialless.staticblitz.com/blitz.d5d65229.js:67:12301)
      at A.SafePromiseAll (../../https:/angular16floatingui-oacd.w-credentialless.staticblitz.com/blitz.d5d65229.js:67:12380)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.8
Node: 16.20.0
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 16.1.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.8
@angular-devkit/build-angular   16.1.8
@angular-devkit/core            16.1.8
@angular-devkit/schematics      16.1.8
@schematics/angular             16.1.8
rxjs                            7.8.0
typescript                      5.0.4
zone.js                         0.13.1
```

### Anything else?

jest                            29.6.2

It seems it runs just fine on Windows. While I get the error on Stackblitz. Maybe some problem on their side?

**Comment by tonysamperi** [comment]
Most probably related to Stackblitz. Opening an issue on their side.
