### ISSUE TITLE
Uncaught ReferenceError: beforeEach is not defined

### ISSUE THREAD

**Issue by abdurrahmanar** [angular/angular#51382]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

After updated Angular version 15 to 16.2 while application starting testing.mjs throws error.

Uncaught ReferenceError: beforeEach is not defined

![image](https://github.com/angular/angular/assets/46883926/ad8a6367-da6c-4740-a7c7-43ab0e13e906)

### Please provide the exception or error you saw

```true
Uncaught ReferenceError: beforeEach is not defined
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.0
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 16.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
"@angular/animations": "^16.2.0",
    "@angular/cdk": "^16.2.0",
    "@angular/common": "^16.2.0",
    "@angular/compiler": "^16.2.0",
    "@angular/core": "^16.2.0",
    "@angular/forms": "^16.2.0",
    "@angular/localize": "^16.2.0",
    "@angular/platform-browser": "^16.2.0",
    "@angular/platform-browser-dynamic": "^16.2.0",
    "@angular/router": "^16.2.0",
    "@angular/service-worker": "^16.2.0",
    "@babel/core": "^7.22.10",
     *
     *
     *
   "rxjs": "~7.6.0",
    "sass-loader": "10.4.1",
    "shake.js": "^1.2.2",
    "subsink": "^1.0.0",
    "tabulator-tables": "^5.5.0",
    "tempusdominus-bootstrap-4": "^5.39.0",
    "tslib": "^2.6.1",
    "utif": "^3.1.0",
    "uuid": "^8.3.2",
    "validate.js": "^0.13.1",
    "@types/node": "^18.17.0",
    "@types/signalr": "^2.2.35",
    "@typescript-eslint/eslint-plugin": "6.4.0",
    "@typescript-eslint/parser": "6.4.0",
    "cordova-plugin-camera": "^4.0.3",
    "vis-network": "^5.4.1",
    "wnumb": "^1.2.0",
    "xlsx": "^0.17.5",
    "zone.js": "~0.13.1"

  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.0",
    "@angular-devkit/schematics": "^16.2.0",
    "@angular-eslint/builder": "16.1.0",
    "@angular-eslint/eslint-plugin": "16.1.0",
    "@angular-eslint/eslint-plugin-template": "16.1.0",
    "@angular-eslint/schematics": "16.1.0",
    "@angular-eslint/template-parser": "16.1.0",
    "@angular/cli": "^16.2.0",
    "@angular/compiler-cli": "^16.2.0",
    "@angular/language-service": "^16.2.0",
    "eslint": "^8.47.0",
    "jasmine-core": "^5.1.0",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "^6.4.2",
    "karma-chrome-launcher": "^3.2.0",
    "karma-coverage-istanbul-reporter": "^3.0.3",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.1.0",
    "karma-viewport": "^1.0.9",
    "protractor": "~7.0.0",
```

**Comment by JoostK** [comment]
Your production code (`route-state.service.ts`) seems to be importing code that eventually (through `router.util.ts`) imports from a testing module, which is unexpected. I don't know how the update to Angular 16 has made a difference here, but such setup is to be avoided.

**Comment by JoostK** [comment]
It was changed in #50063. I'd be interested to learn your exact setup to determine if that is a reasonable thing to do or not.

**Comment by abdurrahmanar** [comment]
this is router.util.ts, it's not importing any test code;

export class RouterUtil {
    static getRouterData(state, parent, propertyName: string): Array<any> {
        let data = [];
        if (parent && parent.snapshot.data && parent.snapshot.data[propertyName] && parent.component) {
            data.push({
                url: '/' + RouterUtil.getFullUrl(parent.snapshot).reverse().join('/'),
                property: parent.snapshot.data[propertyName]
            });
        }

        if (state && parent) {
            data.push(...RouterUtil.getRouterData(state, state.firstChild(parent), propertyName));
        }
        return data;
    }

    static getFullUrl(snapshot): string[] {
        let data = [];
        if (snapshot.routeConfig && snapshot.routeConfig.path) {
            let url = snapshot.routeConfig.path;
            if (snapshot.params) {
                Object.keys(snapshot.params).forEach((key: string) => {
                    url = url.replace(':' + key, snapshot.params[key]);
                });
            }
            data.push(url);
        }

        if (snapshot.parent) {
            data.push(...RouterUtil.getFullUrl(snapshot.parent));
        }
        return data;
    }
}

**Comment by JeanMeche** [comment]
Are there no imports in your file ?

**Comment by JoostK** [comment]
The stack trace seems to indicate that there is an import (somehow). Could you share a runnable reproduction that showcases the issue? With just code snippets we aren't able to investigate, unfortunately.

**Comment by abdurrahmanar** [comment]
> Are there no imports in your file ?

yes, it's just utility class, there are two functions in this class.

**Comment by JeanMeche** [comment]
Then you'll have to provide a reproduction (on stackblitz or a github repo). There is nothing actionnable right now with the information you gave us !

**Comment by kussmaul** [comment]
FWIW, I got the same error today when updating 16.1 to 16.2 (no error with 16.1). 
After the normal update failed, I rolled back changes, and updated just `@angular/core` (not `cdk`, `cli`, `material`) and got the same error.

```
Uncaught ReferenceError: beforeEach is not defined
    at 46517 (testing.mjs:27113:1)
    at __webpack_require__ (bootstrap:19:1)
    at 87783 (router.mjs:6964:1)
    at __webpack_require__ (bootstrap:19:1)
    at 23830 (login.module.ts:19:35)
    at __webpack_require__ (bootstrap:19:1)
    at 79804 (abs.component.ts:223:27)
    at __webpack_require__ (bootstrap:19:1)
    at 28746 (app.component.ts:88:3)
    at __webpack_require__ (bootstrap:19:1)

46517			@	testing.mjs:27113
__webpack_require__	@	bootstrap:19
87783			@	router.mjs:6964
__webpack_require__	@	bootstrap:19
23830			@	login.module.ts:19
__webpack_require__	@	bootstrap:19
79804			@	abs.component.ts:223
__webpack_require__	@	bootstrap:19
28746			@	app.component.ts:88
__webpack_require__	@	bootstrap:19
14913			@	environment.ts:23
__webpack_require__	@	bootstrap:19
__webpack_exec__	@	lib|url:1
(anonymous)		@	lib|url:1
__webpack_require__.O	@	chunk loaded:23
(anonymous)		@	lib|url:1
webpackJsonpCallback	@	jsonp chunk loading:34
(anonymous)		@	main.js:1
```

**Current versions:**
```
$ ng version

Angular CLI: 16.2.0
Node: 16.18.1
Package Manager: npm 8.18.0
OS: linux x64

Angular: 16.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cdk                    16.2.0
@angular/cli                    16.2.0
@angular/material               16.2.0
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Before update:**
```
$ npm outdated
Package                            Current  Wanted  Latest  Location                                        Depended by
@angular-devkit/build-angular       16.1.6  16.2.0  16.2.0  node_modules/@angular-devkit/build-angular      gilt
@angular/animations                 16.1.7  16.2.1  16.2.1  node_modules/@angular/animations                gilt
@angular/cdk                        16.1.6  16.2.0  16.2.0  node_modules/@angular/cdk                       gilt
@angular/cli                        16.1.6  16.2.0  16.2.0  node_modules/@angular/cli                       gilt
@angular/common                     16.1.7  16.2.1  16.2.1  node_modules/@angular/common                    gilt
@angular/compiler                   16.1.7  16.2.1  16.2.1  node_modules/@angular/compiler                  gilt
@angular/compiler-cli               16.1.7  16.2.1  16.2.1  node_modules/@angular/compiler-cli              gilt
@angular/core                       16.1.7  16.2.1  16.2.1  node_modules/@angular/core                      gilt
@angular/forms                      16.1.7  16.2.1  16.2.1  node_modules/@angular/forms                     gilt
@angular/material                   16.1.6  16.2.0  16.2.0  node_modules/@angular/material                  gilt
@angular/platform-browser           16.1.7  16.2.1  16.2.1  node_modules/@angular/platform-browser          gilt
@angular/platform-browser-dynamic   16.1.7  16.2.1  16.2.1  node_modules/@angular/platform-browser-dynamic  gilt
@angular/router                     16.1.7  16.2.1  16.2.1  node_modules/@angular/router                    gilt

```

**Comment by JeanMeche** [comment]
If you enable the sourcemap you'll be able to tell us which file is throwing.  Set `"sourceMap": { "scripts": true,  "vendor": true }` in your `angular.json`.

**Comment by kussmaul** [comment]
@JeanMeche, thank you for the suggestion. Here's what I get:

```
Uncaught ReferenceError: beforeEach is not defined
    at 46517 (test_hooks.ts:19:1)
    at __webpack_require__ (bootstrap:19:1)
    at 87783 (router.ts:3:4)
    at __webpack_require__ (bootstrap:19:1)
    at 23830 (login.module.ts:19:35)
    at __webpack_require__ (bootstrap:19:1)
    at 79804 (abs.component.ts:223:27)
    at __webpack_require__ (bootstrap:19:1)
    at 28746 (app.component.ts:88:3)
    at __webpack_require__ (bootstrap:19:1)
46517			@	test_hooks.ts:19
__webpack_require__	@	bootstrap:19
87783			@	router.ts:3
__webpack_require__	@	bootstrap:19
23830			@	login.module.ts:19
__webpack_require__	@	bootstrap:19
79804			@	abs.component.ts:223
__webpack_require__	@	bootstrap:19
28746			@	app.component.ts:88
__webpack_require__	@	bootstrap:19
14913			@	environment.ts:23
__webpack_require__	@	bootstrap:19
__webpack_exec__	@	lib|url:1
(anonymous)		@	lib|url:1
__webpack_require__.O	@	chunk loaded:23
(anonymous)		@	lib|url:1
webpackJsonpCallback	@	jsonp chunk loading:34
(anonymous)		@	main.js:1

```

**Comment by JoostK** [comment]
@JeanMeche I'd suggest that `beforeEach(getCleanupHook(false));` (and the other one) is changed to `globalThis.beforeEach?.(getCleanupHook(false));`, given that the change in #50063 is legitimately breaking since the call is now unguarded where it used to be guarded.

**Comment by JeanMeche** [comment]
Yes I was thinking about adding that guard back. But it's weird that the content of this file can make it into a build.

**Comment by JoostK** [comment]
Yeah I agree it would be best if we'd know what exactly is going on here.

**Comment by JeanMeche** [comment]
@kussmaul By any chance, could you provide a narrowed down repro on stackblitz or a github repo ? 

Even though we have a "workaround" fix, we'd like to understand how this even happening. This is a file that should only be loaded with unit tests.

**Comment by jyuan-alterdomus** [comment]
Using Nx and upgraded from 15 to latest with Angular 16.2.0 yesterday also has this issue when import RouterTestingModule in storybook. Thought it was caused by new version of nx or storybook, but finally figured out this is from angular, fixed by downgrade to 16.1.9.

**Comment by junyuan** [comment]
Using Nx and upgraded from 15 to latest with Angular 16.2.0 yesterday also has this issue when import RouterTestingModule in storybook. Thought it was caused by new version of nx or storybook, but finally figured out this is from angular, fixed by downgrade to 16.1.9.

**Comment by JeanMeche** [comment]
Out of curiosity, do you reproduce the issue with the esbuild builder ?

**Comment by kussmaul** [comment]
@JeanMeche 
You asked about `@angular/core/testing` - it's only imported in my `.spec.ts` files and in `test.ts` (required by Karma).

I got the ReferenceError with `ng serve`. With `ng build` and the default builder, there are no build errors and `http-server` serves without errors. With `ng build` and `esbuild` (which I've never tried), there were some warnings (some of which I fixed), and `http-server` serves - not perfectly, but nothing like this issue. 

So (at least for me) the problem only occurs with `ng serve`, which wasn't clear from the earlier discussion. Thank you for catching this.

I understand the value of a minimal repro. I will try to work on it, but have some pressing deadlines. :-)

**Comment by dzhavat** [comment]
> Using Nx and upgraded from 15 to latest with Angular 16.2.0 yesterday also has this issue when import RouterTestingModule in storybook. Thought it was caused by new version of nx or storybook, but finally figured out this is from angular, fixed by downgrade to 16.1.9.

I had the exact same issue after upgrading from 16.1.7 to 16.2.0, and using `RouterTestingModule` in Storybook. Fixed it by replacing `RouterTestingModule` with `provideRouter` + `provideLocationMocks`. (PR https://github.com/Energinet-DataHub/greenforce-frontend/pull/1964)

**Comment by JeanMeche** [comment]
This is a whole other issue. Why are your test files run by your app ?

**Comment by skog-newglue** [comment]
@JeanMeche This is something I would like to know as well 😀 Would this be a problem with the tsconfig for the libraries that have spec files or where should I even start looking? I haven't changed anything that Nx generates, so I'm not sure what or where the problem comes from.

**Comment by JeanMeche** [comment]
Could you be able to share a narrowed down repro on github ? That would ease the investigation.

**Comment by JeanMeche** [comment]
@skog-newglue In your case, I'm not sure `libs/stylekit/src/index.ts` should export the spec tests and the storybook stories.

**Comment by skog-newglue** [comment]
@JeanMeche Ahaaa, completely missed that those were included. The script which creates the index file should exclude them indeed. Thank you 🥇
