### ISSUE TITLE
Server: relative URLs are not converted to absolute URLs

### ISSUE THREAD

**Issue by KostyaTretyak** [angular/angular#51626]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Description

Actually, this is a copy angular/universal#1669 and angular/universal#1747, but since they locked, I created this issue. Please do not close this issue for the third time. Let's wait until it is really fixed.

According to the [documentation](https://angular.io/guide/universal#using-absolute-urls-for-http-data-requests-on-the-server), `@nguniversal/express-engine` should take care of converting relative URLs to absolute ones. In this example need converting `/api/heroes` to `http://localhost:4000/api/heroes`, but it doesn't seem to be happening.

## 🔬 Minimal Reproduction
From first terminal:
```bash
git clone git@github.com:KostyaTretyak/example-universal-issue.git
cd example-universal-issue
yarn
yarn dev:ssr
```

See which port the previous command started on, suppose this is port 4200, and from second terminal:
```bash
curl -isS localhost:4200/heroes
```

## 🔥 Exception or Error
<details>
<summary>Error trace</summary>
<pre><code>
ERROR Error: Uncaught (in promise): Error
Error
    at XMLHttpRequest.send (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:58831:19)
    at Observable._subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:128552:17)
    at Observable._trySubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46117:25)
    at Observable.subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46103:22)
    at scheduleTask (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:42838:32)
    at Observable._subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:42876:13)
    at Observable._trySubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46117:25)
    at Observable.subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46103:22)
    at innerSubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:145075:23)
    at MergeMapSubscriber._innerSub (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:39945:105)
    at resolvePromise (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:65088:39)
    at resolvePromise (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:65040:21)
    at /srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:65150:21
    at ZoneDelegate.crGB.ZoneDelegate.invokeTask (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:64677:35)
    at Object.onInvokeTask (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:97388:33)
    at ZoneDelegate.crGB.ZoneDelegate.invokeTask (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:64676:40)
    at Zone.crGB.Zone.runTask (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:64444:51)
    at drainMicroTaskQueue (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:64857:39)
    at crGB.ZoneTask.invokeTask (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:64763:25)
    at Server.ZoneTask.invoke (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:64748:52) {
  rejection: NetworkError
      at XMLHttpRequest.send (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:58831:19)
      at Observable._subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:128552:17)
      at Observable._trySubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46117:25)
      at Observable.subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46103:22)
      at scheduleTask (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:42838:32)
      at Observable._subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:42876:13)
      at Observable._trySubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46117:25)
      at Observable.subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46103:22)
      at innerSubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:145075:23)
      at MergeMapSubscriber._innerSub (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:39945:105),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: NetworkError
        at XMLHttpRequest.send (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:58831:19)
        at Observable._subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:128552:17)
        at Observable._trySubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46117:25)
        at Observable.subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46103:22)
        at scheduleTask (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:42838:32)
        at Observable._subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:42876:13)
        at Observable._trySubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46117:25)
        at Observable.subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46103:22)
        at innerSubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:145075:23)
        at MergeMapSubscriber._innerSub (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:39945:105)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true, maybeDelayChangeDetection: false },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: NetworkError
          at XMLHttpRequest.send (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:58831:19)
          at Observable._subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:128552:17)
          at Observable._trySubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46117:25)
          at Observable.subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46103:22)
          at scheduleTask (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:42838:32)
          at Observable._subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:42876:13)
          at Observable._trySubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46117:25)
          at Observable.subscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:46103:22)
          at innerSubscribe (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:145075:23)
          at MergeMapSubscriber._innerSub (/srv/git/angular/test-universal-issue/dist/test-universal-issue/server/main.js:39945:105)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}
</code></pre>
</details>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.0
Node: 12.18.3
OS: linux x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@ngtools/webpack                  10.1.0
@nguniversal/builders             10.1.0
@nguniversal/common               10.1.0
@nguniversal/express-engine       10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.2
typescript                        3.9.5
webpack                           4.44.1
</code></pre>

**Comment by seeplusplus** [comment]
> Following the investigation of @alexjavier15 I was able to solve the problem by setting the `useAbsoluteUrl ` parameter of `PlatformConfig` in `app.server.module.ts` file:
> 
> ```
> export class AppServerModule {
>     constructor(@Inject(INITIAL_CONFIG) private config: PlatformConfig) {
>         this.config.useAbsoluteUrl = true;
>     }
> }
> ```
> 
> @CaerusKaru Absolute urls work, but apparently that parameter is not set in any _@nguniversal_ package and relative urls are not converted by default, as is claimed in the documentation.

This fix no longer seems to work in Ng 17, which no longer bootsraps with a dedicated `AppServerModule` and trying to `@Inject(INITIAL_CONFIG)` in the default `AppComponent` results in:

```
✘ [ERROR] Could not resolve "url"

    node_modules/@angular/platform-server/fesm2022/platform-server.mjs:14:21:
      14 │ import * as url from 'url';
         ╵                      ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```
