### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ɵcmp')

### ISSUE THREAD

**Issue by azankorejo** [angular/angular#51649]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have created a custom ui library using only standalone components and here's my public-api.ts file.

`
/*
 * Public API Surface of ih-ui-lib
 */

export * from './lib/ui-lib.service';
export * from './lib/ui-lib.component';
export * from './lib/ui-lib.module';

// Exporting components
export * from './lib/components/card/card.component';
export * from './lib/components/card/card-heading/card-heading.component';
export * from './lib/components/card/card-content/card-content.component';
export * from './lib/components/cards-responsive/cards-responsive.component';
export * from './lib/components/collapsible/collapsible.component';
export * from './lib/components/heading/heading.component';
export * from './lib/components/icon/icon.component';
export * from './lib/components/paragraph/paragraph.component';
export * from './lib/components/pill/pill.component';
export * from './lib/components/scrollbar/scrollbar.component';
export * from './lib/components/search/search.component';
export * from './lib/components/search/components/search-column/search-column.component';
export * from './lib/components/search/components/search-row/search-row.component';
export * from './lib/components/status-bar/status-bar.component';
export * from './lib/components/timeline/timeline.component';
`

Here's a example of a component:

`
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css']
})
export class CardComponent implements OnInit {

  @Input() classes: string = '';
  @Input() width: string = '';
  @Input() radius: string = 'sm';

  constructor() { }

  ngOnInit(): void {
  }

}
`
Here's how I'm adding to my app's package.json

`  "ui-library": "git+repo+url.git#branch",`

I also have index.ts file at the root of my lib which just exports the public-api.ts file so I can access it from the root.

export * from './dist/ih-ui-lib/public-api';

I created a new standalone component in my app and tried to import that component into my app.

And that is when I get this error: TypeError: Cannot read properties of undefined (reading 'ɵcmp')

I'm using angular 16.

I tried using modules for components and still it is the same. I tried importing standalone component to a module in my app and it failed to recognise that component.

### Please provide the exception or error you saw

```true
errorhandler.js:23 TypeError: Cannot read properties of undefined (reading 'ɵcmp')
    at getComponentDef (core.mjs:1930:16)
    at extractDirectiveDef (core.mjs:1759:12)
    at core.mjs:1992:21
    at Array.map (<anonymous>)
    at core.mjs:1992:10
    at createTView (core.mjs:11540:63)
    at getOrCreateComponentTView (core.mjs:11489:28)
    at addComponentLogic (core.mjs:12224:19)
    at instantiateAllDirectives (core.mjs:12027:9)
    at createDirectivesInstances (core.mjs:11452:5)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.0
Node: 18.14.1
Package Manager: npm 9.3.1
OS: win32 x64

Angular: 16.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1602.1
@angular-devkit/build-angular      16.2.1
@angular-devkit/core               16.2.1
@angular-devkit/schematics         16.2.0
@angular/cdk                       16.2.1
@angular/cli                       16.2.0
@angular/flex-layout               15.0.0-beta.42
@angular/material                  16.2.1
@angular/material-moment-adapter   16.2.1
@ngtools/webpack                   14.2.7
@schematics/angular                16.2.0
rxjs                               7.8.1
typescript                         4.9.5
zone.js                            0.13.1
```

**Comment by JoostK** [comment]
This is likely due to an import cycle, but we cannot tell without a reproduction.

**Comment by azankorejo** [comment]
Using npm link or publishing the package seem to put away the error.
I had used the repo by the url which caused issues.
