### ISSUE TITLE
Unable to run tests due to Error: NG0203 regarding injection of services

### ISSUE THREAD

**Issue by brianpilati** [angular/angular#52246]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I have upgraded multiple repositories from angular 14 to angular 16. Each repository's tests are failing with the same error. The tests passed at 100% in angular 14.

The build is succeeding.

The error is the result of tests (.spec.ts) files not being able to inject in services. 55/58 tests that have an injected provider are failing.

**Test Error**
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203

One service that is failing - `MoneyService` from another library installed via npm.

**Test:**

```
beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        HttpClientTestingModule,
        FormsModule,
        MatDatepickerModule,
        MatExpansionModule,
        MatFormFieldModule,
        MatIconModule,
        MatIconTestingModule,
        MatInputModule,
        MatNativeDateModule,
        MatOptionModule,
        MatSelectModule,
        NoopAnimationsModule,
        ReactiveFormsModule,
        PrismTestingModule
      ],
      providers: [MoneyService],
      declarations: [ProductDisplayComponent]
    }).compileComponents();
  });
```

**Service from the other library:**

```
/**
 * The Money service
 */
@Injectable()
export class MoneyService {
  /**
   *  instantiates the Money Service with di parameters
   *
   * @param PRISM_CURRENCY - the prism currency from DI
   * @param locale - the locale configuration from DI
   */
  constructor(
    @Inject('PRISM_CURRENCY') private prismCurrency: CurrencyPipe,
    @Inject('LOCALE') private locale: LocaleConfigurationModel
  ) {}

  /**
   * new
   *
   * @description Instantiate a new money class
   *
   * @param amount The initial amount in number or string
   */
  new(amount: number | string = 0): Money {
    return new MoneyClass(amount, this.prismCurrency, this.locale.currency);
  }
}
```

**The library module**

The service is exported from the library module
```
export { MoneyService } from './packages/money/money.service';
```

The service is a provider in the module

```
@NgModule({
  providers: [
    MoneyService,
  ]
})
export class LibraryModule {
```

**This is how the service is injected into a component**

FormBuilder is injected correctly

```/**
   * Subscription Products Constructor
   *
   * @param formBuilder FormBuilder from DI
   * @param moneyService MoneyService from DI
   */
  constructor(
    private formatBuilder: FormBuilder,
    private moneyService: MoneyService,
  ) {
```

**tsconfig.json file**

```{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "paths": {
      "@prism/subscription-modeling-web": [
        "dist/prism-subscription-modeling"
      ],
      "@prism/subscription-modeling-web/*": [
        "dist/prism-subscription-modeling/*"
      ],
      "crypto": [
        "node_modules/crypto-js",
        "node_modules/@prism/web-core/node_modules/crypto-js"
      ]
    },
    "useDefineForClassFields": false,
    "lib": [
      "ES2022",
      "dom"
    ],
    "noUnusedLocals": true,
    "types": ["node", "jasmine"],
    "removeComments": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "skipLibCheck": true ,
    "skipDefaultLibCheck": true ,
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
  }
}
```

**tsconfig.spec.json file**

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/spec",
    "types": ["jasmine", "node"],
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "useUnknownInCatchVariables": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "strict": false
  },
  "include": ["**/*.spec.ts", "**/*.d.ts"]
}
```

**Angular.json test configuration**

``` "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "poll": 3000,
            "codeCoverage": false,
            "sourceMap": true,
            "polyfills": [
              "zone.js",
              "zone.js/testing"
            ],
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.css"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        }
```

**Karma.conf.js file**

```// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    files: [],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true,
      watermarks: {
        statements: [90, 100],
        functions: [90, 100],
        branches: [90, 100],
        lines: [90, 100]
      },
      check: {
        emitWarning: true,
        global: {
          statements: 100,
          branches: 100,
          functions: 100,
          lines: 100,
          excludes: [
            // 'foo/bar/**/*.js'
          ]
        }
      }
    },
    reportSlowerThan: 1000,
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadless'],
    singleRun: false
  });
};
```

### Please provide the exception or error you saw

```true
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203
	error properties: Object({ code: -203 })
	    at injectInjectorOnly (node_modules/@prism/web-core/node_modules/@angular/core/fesm2020/core.mjs:611:15)
	    at Module.ɵɵinject (node_modules/@prism/web-core/node_modules/@angular/core/fesm2020/core.mjs:622:60)
	    at Object.factory (node_modules/@prism/web-core/fesm2022/prism-web-core.mjs:65:103)
	    at callback (node_modules/@angular/core/fesm2022/core.mjs:9432:43)
	    at runInInjectorProfilerContext (node_modules/@angular/core/fesm2022/core.mjs:694:9)
	    at R3Injector.hydrate (node_modules/@angular/core/fesm2022/core.mjs:9431:17)
	    at R3Injector.get (node_modules/@angular/core/fesm2022/core.mjs:9301:33)
	    at ChainedInjector.get (node_modules/@angular/core/fesm2022/core.mjs:14001:36)
	    at lookupTokenUsingModuleInjector (node_modules/@angular/core/fesm2022/core.mjs:4504:39)
	    at getOrCreateInjectable (node_modules/@angular/core/fesm2022/core.mjs:4552:12)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.6
Node: 16.20.2
Package Manager: npm 8.19.4
OS: darwin x64

Angular: 16.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.6
@angular-devkit/build-angular   16.2.6
@angular-devkit/core            16.2.6
@angular-devkit/schematics      16.2.6
@angular/cdk                    16.2.8
@angular/cli                    16.2.6
@angular/flex-layout            15.0.0-beta.42
@angular/material               16.2.8
@schematics/angular             16.2.6
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

### Anything else?

This is quite surprising for this to be happening on an angular upgrade.

**Comment by JoostK** [comment]
This indicates that you have multiple copies of `@angular/core` being bundled into your test (and possibly production) bundle. You can check using e.g. `npm ls`/`pnpm why`/`yarn why` to see which versions are present and why.

**Comment by brianpilati** [comment]
> This indicates that you have multiple copies of `@angular/core` being bundled into your test (and possibly production) bundle. You can check using e.g. `npm ls`/`pnpm why`/`yarn why` to see which versions are present and why.

$ npm ls

```
├── @angular-devkit/build-angular@16.2.6
├── @angular-eslint/builder@16.2.0
├── @angular-eslint/eslint-plugin-template@16.2.0
├── @angular-eslint/eslint-plugin@16.2.0
├── @angular-eslint/schematics@16.2.0
├── @angular-eslint/template-parser@16.2.0
├── @angular/animations@16.2.9
├── @angular/cdk@16.2.8
├── @angular/cli@16.2.6
├── @angular/common@16.2.9
├── @angular/compiler-cli@16.2.9
├── @angular/compiler@16.2.9
├── @angular/core@16.2.9
├── @angular/flex-layout@15.0.0-beta.42
├── @angular/forms@16.2.9
├── @angular/language-service@16.2.9
├── @angular/material@16.2.8
├── @angular/platform-browser-dynamic@16.2.9
├── @angular/platform-browser@16.2.9
├── @angular/router@16.2.9
├── @compodoc/compodoc@1.1.21
├── @prism/assets-core@0.37.142
├── @prism/modeling-core@0.5.22
├── @prism/modeling-engine@0.11.33
├── @prism/public-core@0.24.66
├── @prism/web-core@0.32.212
├── @types/jasmine@5.1.0
├── @types/jasminewd2@2.0.11
├── @types/node@20.8.5
├── @typescript-eslint/eslint-plugin@6.7.5
├── @typescript-eslint/parser@6.7.5
├── angular-in-memory-web-api@0.16.0
├── eslint@8.51.0
├── husky@8.0.3
├── jasmine-core@5.1.1
├── karma-chrome-launcher@3.2.0
├── karma-coverage@2.2.1
├── karma-jasmine-html-reporter@2.1.0
├── karma-jasmine@5.1.0
├── karma@6.4.2
├── material-design-icons@3.0.1
├── ng-packagr@16.2.3
├── npm-run-all@4.1.5
├── prettier@2.6.2
├── pretty-quick@3.1.3
├── protractor@7.0.0
├── rxjs@7.8.1
├── tslib@2.6.2
├── typescript@5.1.6
├── webpack-bundle-analyzer@4.9.1
└── zone.js@0.13.3
```

**Comment by JoostK** [comment]
Sorry, it should include `@angular/core` as that output only shows your own package.json dependencies, not transitive dependencies.

```bash
npm ls @angular/core
```

or perhaps better yet is `npm explain`:

```bash
npm explain @angular/core
```

(I am not too familiair with NPM's commands)

**Comment by JoostK** [comment]
I have seen this error in many issues before, and it's _always_ been this problem.

**Comment by brianpilati** [comment]
Somehow, angular should add this to their error handling. It would have solved me many days of work.

**Comment by JoostK** [comment]
I see your point, but it's not that simple; there can be scenarios where multiple, different runtimes can coexist within a single page, as long as they don't depend on each other.

That said, it should be possible to detect this case and report a more meaningful error, or even simpler to always hint towards the possibility of two versions of `@angular/core` in the error message.

**Comment by spock123** [comment]
It's especially a big issue with pnpm, not really the fault of Angular though. 

Pnpm has become quite a nightmare for us in a large mono repo, and every time we migrate/upgrade angular versions we find ourselves in trouble regarding versioning across the various local sites.
