### ISSUE TITLE
File is not defined in a new project Angular 17

### ISSUE THREAD

**Issue by ebiton-eig** [angular/angular#52392]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Create a new standalone projet with Angular 17 RC1 and simply declare a variable of type File :

```ts
import { CommonModule } from '@angular/common';
import { AfterViewInit, Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule,
    RouterOutlet
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'test';
  test: File;

  constructor() {
    this.test = new File([''], 'test', { type: 'text/plain' });
  }
}
```

When executing:

```
File is not defined
    at new _AppComponent (/main.server.mjs:41:23)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (/main.server.mjs:49:12)
    at getNodeInjectable (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:4265:44)
    at createRootComponent (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:14412:35)
    at ComponentFactory.create (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:14276:25)
    at ApplicationRef.bootstrap (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:31127:42)
    at file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:30649:32
    at _ZoneDelegate.invoke (F:\source\test\node_modules\zone.js\fesm2015\zone-node.js:368:26)
    at Object.onInvoke (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:11190:33)
    at _ZoneDelegate.invoke (F:\source\test\node_modules\zone.js\fesm2015\zone-node.js:367:52
```

### Please provide the exception or error you saw

```true
File is not defined
    at new _AppComponent (/main.server.mjs:41:23)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (/main.server.mjs:49:12)
    at getNodeInjectable (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:4265:44)
    at createRootComponent (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:14412:35)
    at ComponentFactory.create (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:14276:25)
    at ApplicationRef.bootstrap (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:31127:42)
    at file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:30649:32
    at _ZoneDelegate.invoke (F:\source\test\node_modules\zone.js\fesm2015\zone-node.js:368:26)
    at Object.onInvoke (file:///F:/source/test/node_modules/@angular/core/fesm2022/core.mjs:11190:33)
    at _ZoneDelegate.invoke (F:\source\test\node_modules\zone.js\fesm2015\zone-node.js:367:52
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-rc.1
Node: 18.18.2
Package Manager: npm 9.5.0
OS: Windows 11 x64

Angular: 17.0.0-rc.1
... animations, cdk, common, compiler, core, forms, material
... platform-browser, platform-browser-dynamic, plateform-server
... router, ssr

express 4.18.2
rxjs 7.8.1
tslib 2.6.2
zone.js 0.14.0
```

**Comment by JeanMeche** [comment]
Hi this is expected, `File` does not exist in the  Node.js runtine, where the SSR runs.

**Comment by ebiton-eig** [comment]
How do you use the files in this case?

**Comment by JeanMeche** [comment]
File are located on the client side. You likely want to guard it with `isPlatformBrowser`.

**Comment by ebiton-eig** [comment]
Ok, thanks, I try this.
