### ISSUE TITLE
Zone.js destroys ckeditor for vue

### ISSUE THREAD

**Issue by sschoeb** [angular/angular#52466]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

No

### Description

First of all: I'm not sure if this is the correct repository to post this issue. But as zone.js is the reason for the issue, I think I'm at least not completely wrong. Please let me know if you think otherwise.

My setup:

- I'm runnign a vue-application usign the ckeditor as described here: https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/vuejs-v3.html
- The Vuew app does have tow pages: Startpage and about. On the about-page, I've included the ckeditor.
- In a different project we have built an angular element which should be integratable on any other website (e.g. in vue application stated above)
- Including the angular element within the vue-app (adding a script tag loading the js and adding the tag) does show the element, everything looks fine

The issue:

Navigating from the about-page back to the starpage, does throw an error in the console and breaks the Vue app. I do see the following error:

```
widget.js:96697 Unhandled Promise rejection: Cannot read properties of undefined (reading 'data-ck-expando') ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read properties of undefined (reading 'data-ck-expando')
    at emittermixin.ts:361:9
    at No (emittermixin.ts:362:1)
    at Ii._getProxyEmitter (emittermixin.ts:152:40)
    at emittermixin.ts:166:27
    at Array.map (<anonymous>)
    at Ii._getAllProxyEmitters (emittermixin.ts:166:6)
    at Ii.stopListening (emittermixin.ts:126:32)
    at Ii.destroy (focustracker.ts:106:8)
    at yf.destroy (editorui.ts:179:21)
    at yf.destroy (classiceditorui.ts:117:9) TypeError: Cannot read properties of undefined (reading 'data-ck-expando')
    at http://localhost:5173/node_modules/.vite/deps/@ckeditor_ckeditor5-build-classic.js?v=78e69277:3817:22
    at No (http://localhost:5173/node_modules/.vite/deps/@ckeditor_ckeditor5-build-classic.js?v=78e69277:3818:12)
    at Ii._getProxyEmitter (http://localhost:5173/node_modules/.vite/deps/@ckeditor_ckeditor5-build-classic.js?v=78e69277:3776:23)
    at http://localhost:5173/node_modules/.vite/deps/@ckeditor_ckeditor5-build-classic.js?v=78e69277:3779:180
    at Array.map (<anonymous>)
    at Ii._getAllProxyEmitters (http://localhost:5173/node_modules/.vite/deps/@ckeditor_ckeditor5-build-classic.js?v=78e69277:3779:163)
    at Ii.stopListening (http://localhost:5173/node_modules/.vite/deps/@ckeditor_ckeditor5-build-classic.js?v=78e69277:3766:33)
    at Ii.destroy (http://localhost:5173/node_modules/.vite/deps/@ckeditor_ckeditor5-build-classic.js?v=78e69277:4385:18)
    at yf.destroy (http://localhost:5173/node_modules/.vite/deps/@ckeditor_ckeditor5-build-classic.js?v=78e69277:16201:53)
    at yf.destroy (http://localhost:5173/node_modules/.vite/deps/@ckeditor_ckeditor5-build-classic.js?v=78e69277:16751:19)
```

Workaround:
There are two options to fix the issue:

1. Remove zone.js completely from the angular element.
2. Add the following line to the widget: `(window as any).__Zone_disable_toString = true;`

I've attached a repository which does include the vue app mentioned above. It does load our angular element in HomeView.vue. When you start it and then navigate from about to the startpage, you'll see the error. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/sschoeb/vue-ckeditor-zone-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 15.2.0
```

### Anything else?

Question: How big is the impact when disabling toString() using the workaround number 2 described above? Is that more cosmetic or do I have to expect issues?

**Comment by atscott** [comment]
I don't have any answers but after some archeology I found that ironically the `toString` patch was added as a result of an issue found with CKEditor and Zone.JS

https://github.com/angular/zone.js/issues/666, https://github.com/ckeditor/ckeditor5/issues/413

It's hard to say exactly what the impact might be when disabling the `toString` patch. Based on the above issues, I'd say that it's more than just a cosmetic change but I can't say what types of problems, if any, might occur by removing the patch without looking at those in more detail. 

@JiaLiPassion

**Comment by JiaLiPassion** [comment]
@sschoeb , could you check your repro repo? I didn't find any angular element there.

**Comment by alxhub** [comment]
I'm going to close this as it's been over a year and we don't have a reproduction. Please feel free to open a new issue with a reproduction if this is still a problem!
