### ISSUE TITLE
angular-compiler: Cannot read properties of undefined (reading 'startName')

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#52540]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Hi.
After updating to rc3 my project is not going to compile/build. Also my build process in dev server is never-ending and doesn't give me error.
Also i see these errors, which are not true, because they are persist in my tsconfig and everything seems to be building on rc2:

```
File 'server.ts' is missing from the TypeScript compilation
File 'src\main.server.ts' is missing from the TypeScript compilation.
```

I ran schematics to migrate to new control flow, maybe this is related.
Still need to review 400 components and will give you repro.

### Minimal Reproduction

ng serve / ng build

### Exception or Error

```text
X [ERROR] Cannot read properties of undefined (reading 'startName') [plugin angular-compiler]

  This error came from the "onStart" callback registered here:

    node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compiler-plugin.js:89:18:
      89 │             build.onStart(async () => {
         ╵                   ~~~~~~~

    at setup (C:\node_modules\@angular-devkit\build-angular\src\tools\esbuild\angular\compiler-plugin.js:89:19)
    at async handlePlugins (C:\node_modules\esbuild\lib\main.js:1340:9)


X [ERROR] File 'src\main.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.


X [ERROR] File 'src\main.server.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.


X [ERROR] File 'server.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.


Application bundle generation failed. [17.522 seconds]
```

### Your Environment

```text
Angular CLI: 17.0.0-rc.3
Node: 18.18.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.0-rc.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.3
@angular-devkit/build-angular   17.0.0-rc.3
@angular-devkit/core            17.0.0-rc.3
@angular-devkit/schematics      17.0.0-rc.3
@angular/cli                    17.0.0-rc.3
@angular/ssr                    17.0.0-rc.3
@schematics/angular             17.0.0-rc.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by zip-fa** [comment]
> Transfer to the FW repo since this is not caused by the CLI.

But with esbuild-builders there is no visible errors on Windows PC, it just shows “Building…” text in console indefinitely. On other hand, webpack gives trace to what caused this

**Comment by vpallathu** [comment]
I still see the error with version v17.0.0. I don't see any new npm version than v17.0.0.
