### ISSUE TITLE
devtools ɵgetInjectorMetadata is not a function

### ISSUE THREAD

**Issue by ngmariusz** [angular/angular#52786]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

```

  "dependencies": {
        "@angular/animations": "^16.1.8",
        "@angular/cdk": "^16.1.8",
        "@angular/common": "^16.1.8",
        "@angular/compiler": "^16.1.8",
        "@angular/core": "^16.1.8",
        "@angular/forms": "^16.1.8",
        "@angular/material": "^16.1.8",
        "@angular/platform-browser": "^16.1.8",
        "@angular/platform-browser-dynamic": "^16.1.8",
        "@angular/router": "^16.1.8",
        "material-icons": "^1.13.12",
        "path-browserify": "^1.0.1",
        "roboto-fontface": "^0.10.0",
        "rxjs": "~6.6.0",
        "tslib": "^2.3.0",
        "zone.js": "~0.13.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^16.1.8",
        "@angular/cli": "^16.1.8",
        "@angular/compiler-cli": "^16.1.8",
        "@types/jasmine": "~3.8.2",
        "@types/node": "^16.18.60",
        "autoprefixer": "^10.4.16",
        "jasmine-core": "~3.8.0",
        "karma": "~6.3.4",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage": "~2.0.3",
        "karma-jasmine": "~4.0.1",
        "karma-jasmine-html-reporter": "^1.7.0",
        "postcss": "^8.4.31",
        "prettier": "^3.0.3",
        "tailwindcss": "^3.3.5",
        "typescript": "~4.9.5"
    },

```

-

-

<img width="234" alt="image" src="https://github.com/angular/angular/assets/3337832/21159437-04e3-4842-8ac6-69e8c7512e81">

-

-

### Please provide a screenshot if possible [Bug Report only]

```
zone.js:1681 Uncaught TypeError: F(...).ɵgetInjectorMetadata is not a function
    at rt (component-tree.ts:61:20)
    at Jo (component-tree.ts:436:20)
    at De (component-tree.ts:234:7)
    at component-tree.ts:105:50
    at Array.map (<anonymous>)
    at nn (component-tree.ts:104:83)
    at client-event-subscribers.ts:101:21
    at n (same-page-message-bus.ts:41:12)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Zone.runTask (zone.js:173:47)
rt @ component-tree.ts:61
Jo @ component-tree.ts:436
De @ component-tree.ts:234
(anonymous) @ component-tree.ts:105
nn @ component-tree.ts:104
(anonymous) @ client-event-subscribers.ts:101
n @ same-page-message-bus.ts:41
invokeTask @ zone.js:402
runTask @ zone.js:173
invokeTask @ zone.js:483
invokeTask @ zone.js:1631
globalCallback @ zone.js:1674
globalZoneAwareCallback @ zone.js:1695
postMessage (async)
emit @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
s @ content_script_bundle.js:1
Show 9 more frames
Show less
```

**Comment by NachmanBerkowitz** [comment]
I am having the same issue.
![image](https://github.com/angular/angular/assets/38742354/81135f17-f85b-4fa7-906e-31b194d7b024)

**Comment by JoostK** [comment]
Ah, Iit looks like the devtools plugin is not backwards compatible with older versions of Angular.

/cc @AleksanderBodurri

**Comment by AleksanderBodurri** [comment]
@ngmariusz thanks for the flag 🙏  I have a PR open here that should fix this issue https://github.com/angular/angular/pull/52791

**Comment by AndrewKushnir** [comment]
Closing this ticket, since PR https://github.com/angular/angular/pull/52791 is merged.
