### ISSUE TITLE
Unable to setup 'adev' local environment

### ISSUE THREAD

**Issue by mattveraldi** [angular/angular#52839]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi, \
I am trying to setup the local development environment for 'adev'. My goal is to study your website, it's amazing. \
I have `node`, `yarn` and  `bazel` installed. After I install dependencies, in the `post-install` hook there is an error.

Can you help me please? Thank you in advance.

### Please provide a link to a minimal reproduction of the bug

I just cloned the repo.

### Please provide the exception or error you saw

```
Error: Cannot find module './generate-tutorials.ts'
Require stack:
- /home/mveraldi/angular/adev/scripts/tutorials/imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.resolve (node:internal/modules/helpers:136:19)
    at requireResolveNonCached (/home/mveraldi/angular/adev/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/home/mveraldi/angular/adev/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/home/mveraldi/angular/adev/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/home/mveraldi/angular/adev/node_modules/ts-node/dist/bin.js:47:30)
    at main (/home/mveraldi/angular/adev/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/mveraldi/angular/adev/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/mveraldi/angular/adev/scripts/tutorials/imaginaryUncacheableRequireResolveScript'
  ]
}

Node.js v20.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Anything else?

I am using WSL2 for Windows 11 (Ubuntu distro).

**Comment by mvdluit** [comment]
The new site hasn't been fully open-sourced yet, so it's not possible to build it yet. It will probably happen once they finish some work on infra for adev in a few weeks.

**Comment by john-kontralto** [comment]
Closed as 'not planned'? Is that to mean it will never be released in a state we can set up locally?

**Comment by JeanMeche** [comment]
It surely will ! But we need to land some changes to this to work ! Stay tunes.

**Comment by john-kontralto** [comment]
> It surely will ! But we need to land some changes to this to work ! Stay tunes.

Awesome! Any tasks we in the community could take on to speed it along?

**Comment by JeanMeche** [comment]
We'll open some issues with the dedicated labels if such need arises !
