### ISSUE TITLE
Cannot possibly build @nguniversal when Windows was installed with a windows username containing a space

### ISSUE THREAD

**Issue by PieterjanDeClippel** [angular/angular#52952]
### Which @angular/* package(s) are the source of the bug?

bazel, Don't known / other

### Is this a regression?

No

### Description

I tried all sorts of commands, but the parameter doesn't seem to be passed on to `bazel`.

    npm run build -- --output_user_root="C:\repos\universal\tmp\out"
    npm run build -- -- --output_user_root="C:\repos\universal\tmp\out"

How is paths containing spaces still an issue in 2024?

```
PS C:\repos\universal> $HOME
C:\Users\Pieterjan De Clippel
PS C:\repos\universal> npm run build -- --output_user_root="C:\repos\universal\tmp\out"

> nguniversal@17.0.0 build
> npm run bazel:build --output_user_root=C:\repos\universal\tmp\out


> nguniversal@17.0.0 bazel:build
> bazel build //modules/...

WARNING: Output user root "C:/Users/Pieterjan De Clippel/_bazel_Pieterjan De Clippel" contains a space. This will probably break the build. You should set a different --output_user_root.
DEBUG: C:/users/pieterjan de clippel/_bazel_pieterjan de clippel/r3nyaeul/external/build_bazel_rules_nodejs/index.bzl:73:14: yarn_install#yarn attribute not set and no repository named 'yarn' exists; installing default yarn
INFO: Analyzed 45 targets (0 packages loaded, 0 targets configured).
INFO: Found 45 targets...
ERROR: C:/repos/universal/modules/common/tools/BUILD.bazel:5:10: Compiling Angular templates (full devmode) //modules/common/tools:tools failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:

---8<---8<--- Exception details ---8<---8<---
java.io.IOException: ERROR: src/main/native/windows/processes-jni.cc(408): NativeProcess:WriteStdin(40260): De pipes wordt gesloten.

        at com.google.devtools.build.lib.windows.WindowsSubprocess.writeStream(WindowsSubprocess.java:283)
        at com.google.devtools.build.lib.windows.WindowsSubprocess.access$000(WindowsSubprocess.java:30)
        at com.google.devtools.build.lib.windows.WindowsSubprocess$ProcessOutputStream.write(WindowsSubprocess.java:51)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.doFlush(CodedOutputStream.java:3062)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:2994)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:3013)
        at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1392)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2801)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2775)
        at com.google.devtools.build.lib.worker.WorkerProtocol$Input.writeTo(WorkerProtocol.java:238)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessageNoTag(CodedOutputStream.java:2855)
        at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeMessage(CodedOutputStream.java:2824)
        at com.google.devtools.build.lib.worker.WorkerProtocol$WorkRequest.writeTo(WorkerProtocol.java:1171)
        at com.google.protobuf.AbstractMessageLite.writeDelimitedTo(AbstractMessageLite.java:95)
        at com.google.devtools.build.lib.worker.ProtoWorkerProtocol.putRequest(ProtoWorkerProtocol.java:38)
        at com.google.devtools.build.lib.worker.SingleplexWorker.putRequest(SingleplexWorker.java:127)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.execInWorker(WorkerSpawnRunner.java:419)
        at com.google.devtools.build.lib.worker.WorkerSpawnRunner.exec(WorkerSpawnRunner.java:209)
        at com.google.devtools.build.lib.exec.SpawnRunner.execAsync(SpawnRunner.java:245)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:146)
        at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:108)
        at com.google.devtools.build.lib.actions.SpawnStrategy.beginExecution(SpawnStrategy.java:47)
        at com.google.devtools.build.lib.exec.SpawnStrategyResolver.beginExecution(SpawnStrategyResolver.java:68)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.beginExecution(SpawnAction.java:328)
        at com.google.devtools.build.lib.actions.Action.execute(Action.java:133)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:907)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1076)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:1031)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:152)
        at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:91)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:492)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:856)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.computeInternal(ActionExecutionFunction.java:349)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:590)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:382)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log, file at C:/users/pieterjan de clippel/_bazel_pieterjan de clippel/r3nyaeul/bazel-workers/worker-7-AngularTemplateCompile.log ---8<---8<---
(empty)
---8<---8<--- End of log ---8<---8<---
INFO: Elapsed time: 1.766s, Critical Path: 0.94s
INFO: 13 processes: 13 internal.
FAILED: Build did NOT complete successfully
```

### Please provide the exception or error you saw

```true
WARNING: Output user root "C:/Users/Pieterjan De Clippel/_bazel_Pieterjan De Clippel" contains a space. This will probably break the build. You should set a different --output_user_root.
    
ERROR: C:/repos/universal/modules/common/tools/BUILD.bazel:5:10: Compiling Angular templates (full devmode) //modules/common/tools:tools failed: Worker process quit or closed its stdin stream when we tried to send a WorkRequest:
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
PS C:\repos\universal> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.1
Node: 18.17.1
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 17.0.3
... animations, common, compiler, compiler-cli, core
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.1
@angular-devkit/build-angular   17.0.1
@angular-devkit/core            17.0.1
@angular-devkit/schematics      17.0.1
@angular/bazel                  16.0.0-next.6+sha-3b863dd
@angular/build-tooling          0.0.0-8776e14b397b6136c87e7334375cb91917466ee0
@angular/cli                    17.0.1
@angular/ng-dev                 <error>
@bazel/bazelisk                 1.12.1
@bazel/buildifier               6.1.2
@bazel/concatjs                 5.8.1
@bazel/esbuild                  5.8.1
@bazel/ibazel                   v0.16.2
@bazel/jasmine                  5.8.1
@schematics/angular             17.0.1
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by PieterjanDeClippel** [comment]
It seems that adding

    startup --output_user_root=C:/repos/universal/tmp/out

at the top of the root `.bazelrc` fixes the issue
