### ISSUE TITLE
Broken depencency injection when using @angular-devkit/build-angular:application

### ISSUE THREAD

**Issue by davidpanic** [angular/angular#52962]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Dependency Injection doesn't work when using `@angular-devkit/build-angular:application`, even for a basic app with no content.

I've prepared a stripped down version of the broken app: [broken-inject.zip](https://github.com/angular/angular/files/13379476/broken-inject.zip)
run `pnpm i && npx nx serve broken-inject` to start it.

If you stop serving and apply the following patch, the app starts up and shows the text "WORKS!"

```patch
diff --git a/apps/broken-inject/project.json b/apps/broken-inject/project.json
index db3f497a..78ecfc03 100644
--- a/apps/broken-inject/project.json
+++ b/apps/broken-inject/project.json
@@ -7,12 +7,12 @@
   "tags": [],
   "targets": {
     "build": {
-      "executor": "@angular-devkit/build-angular:application",
+      "executor": "@angular-devkit/build-angular:browser",
       "outputs": ["{options.outputPath}"],
       "options": {
         "outputPath": "dist/apps/broken-inject",
         "index": "apps/broken-inject/src/index.html",
-        "browser": "apps/broken-inject/src/main.ts",
+        "main": "apps/broken-inject/src/main.ts",
         "polyfills": ["zone.js", "@angular/localize/init", "apps/broken-inject/src/polyfills.ts"],
         "tsConfig": "apps/broken-inject/tsconfig.app.json",
         "assets": ["apps/broken-inject/src/favicon.ico", "apps/broken-inject/src/assets"],
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/angular/angular/files/13379476/broken-inject.zip

### Please provide the exception or error you saw

```true
{
    "originalStack": "Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203\n    at new ZoneAwareError (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/zone__js_plugins_zone-error.js?v=8fea9958:56:29)\n    at new RuntimeError (http://localhost:4200/main.js:81:5)\n    at injectInjectorOnly (http://localhost:4200/main.js:458:11)\n    at ɵɵinject (http://localhost:4200/main.js:468:59)\n    at Object.factory (http://localhost:4200/main.js:5705:43)\n    at http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:3520:33\n    at runInInjectorProfilerContext (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:481:5)\n    at R3Injector.hydrate (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:3519:9)\n    at R3Injector.get (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:3418:23)\n    at definition.getStandaloneInjector (http://localhost:4200/main.js:5713:27)\n    at ComponentFactory.create (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:9314:51)\n    at _ApplicationRef.bootstrap (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:18513:38)\n    at http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:18204:20\n    at _ZoneDelegate.invoke (http://localhost:4200/polyfills.js:310:158)\n    at Object.onInvoke (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:8870:25)",
    "zoneAwareStack": "Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203\n    at new RuntimeError (http://localhost:4200/main.js:81:5) [angular]\n    at injectInjectorOnly (http://localhost:4200/main.js:458:11) [angular]\n    at ɵɵinject (http://localhost:4200/main.js:468:59) [angular]\n    at Object.factory (http://localhost:4200/main.js:5705:43) [angular]\n    at http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:3520:33 [angular]\n    at runInInjectorProfilerContext (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:481:5) [angular]\n    at R3Injector.hydrate (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:3519:9) [angular]\n    at R3Injector.get (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:3418:23) [angular]\n    at definition.getStandaloneInjector (http://localhost:4200/main.js:5713:27) [angular]\n    at ComponentFactory.create (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:9314:51) [angular]\n    at _ApplicationRef.bootstrap (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:18513:38) [angular]\n    at http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:18204:20 [angular]\n    at Object.onInvoke (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:8870:25) [angular]",
    "stack": "Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203\n    at new RuntimeError (http://localhost:4200/main.js:81:5) [angular]\n    at injectInjectorOnly (http://localhost:4200/main.js:458:11) [angular]\n    at ɵɵinject (http://localhost:4200/main.js:468:59) [angular]\n    at Object.factory (http://localhost:4200/main.js:5705:43) [angular]\n    at http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:3520:33 [angular]\n    at runInInjectorProfilerContext (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:481:5) [angular]\n    at R3Injector.hydrate (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:3519:9) [angular]\n    at R3Injector.get (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:3418:23) [angular]\n    at definition.getStandaloneInjector (http://localhost:4200/main.js:5713:27) [angular]\n    at ComponentFactory.create (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:9314:51) [angular]\n    at _ApplicationRef.bootstrap (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:18513:38) [angular]\n    at http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:18204:20 [angular]\n    at Object.onInvoke (http://localhost:4200/@fs/home/david/Documents/broken-inject/.angular/cache/17.0.1/vite/deps/chunk-WSIVR65F.js?v=18728d8a:8870:25) [angular]",
    "message": "NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203",
    "code": -203
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.1
Node: 21.1.0 (Unsupported)
Package Manager: pnpm 8.10.2
OS: linux x64

Angular: 17.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.1 (cli-only)
@angular-devkit/build-angular   17.0.1
@angular-devkit/core            17.0.1
@angular-devkit/schematics      17.0.1
@angular/cdk                    17.0.0
@angular/cli                    17.0.1
@angular/material               17.0.0
@schematics/angular             17.0.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JeanMeche** [comment]
Can you check if removing following in tsconfig fixes your issue ? 

```
    "paths": {
      "@angular/*": [
        "./node_modules/@angular/*"
      ],
    }
```
