### ISSUE TITLE
manifest.webmanifest hash mismatch after upgrade to Angular 17 prohibits service worker version installation

### ISSUE THREAD

**Issue by Raul52** [angular/angular#53136]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

I was on Angular 16 and the service worker worked with no issue. It worked exactly as described in the server-side docs:

> If you are using Angular on the server in combination with the Angular service worker, the behavior deviates from the normal server-side rendering behavior. The initial server request will be rendered on the server as expected. However, after that initial request, subsequent requests are handled by the service worker and always client-side rendered.

After the upgrade to Angular 17, this has stopped working. My requests are always bypassing the service-worker cache and retrieve the resources from the server.

I am using a basic setup.

Here is the content of `ngsw-config.json`:

```JSON
{
  "$schema": "./node_modules/@angular/service-worker/config/schema.json",
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html",
          "/manifest.webmanifest",
          "/*.css",
          "/*.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**",
          "/*.(svg|cur|jpg|jpeg|png|apng|webp|avif|gif|otf|ttf|woff|woff2)"
        ]
      }
    }
  ],
  "dataGroups": [
    {
      "name": "translations",
      "urls": [
        "api/translation/i18n/**"
      ],
      "cacheConfig": {
        "strategy": "performance",
        "maxAge": "15m",
        "maxSize": 50
      }
    }
  ]
}
```

I have debugged `ngsw-worker.js` and found out that inside the `assignVersion(event)` we have this part of the code that returns null after the update to Angular 17.

```
if (this.state !== DriverReadyState.NORMAL) {
   return null;
}
```

This is caused by the fact that the state value in my case is  `DriverReadyState.EXISTING_CLIENTS_ONLY`.

So the next question was why? With a longer debug found that the state is set like this inside the `async versionFailed(appVersion, err)` method with the following error

```
Error: Hash mismatch (cacheBustedFetchFromNetwork): dummy/manifest.webmanifest: expected 28e5100762138d95be65b2e1ab570f2055dc0ade, got 61f2946b132d6d0633a3ab5eaba61cc869bae4bf (after cache busting)
    at PrefetchAssetGroup.cacheBustedFetchFromNetwork (dummy/ngsw-worker.js:479:21)
    at async PrefetchAssetGroup.fetchFromNetwork (dummy/ngsw-worker.js:454:19)
    at async PrefetchAssetGroup.fetchAndCacheOnce (dummy/ngsw-worker.js:433:21)
    at async dummy/ngsw-worker.js:538:9
    at async dummy/ngsw-worker.js:524:9
```

Contents of the manifest file:

```JSON
{
  "name": "Dummy",
  "short_name": "Dummy",
  "theme_color": "#1976d2",
  "background_color": "#fafafa",
  "display": "standalone",
  "scope": "./",
  "start_url": "./",
  "icons": [
    {	
		"src": "assets/android-chrome-192x192.png",
		"sizes": "192x192",
		"type": "image/png"
    }, {
		"src": "assets/android-chrome-512x512.png",
		"sizes": "512x512",
		"type": "image/png"
    },
    {
      "src": "assets/icons/icon-72x72.png",
      "sizes": "72x72",
      "type": "image/png",
      "purpose": "maskable any"
    },
    {
      "src": "assets/icons/icon-96x96.png",
      "sizes": "96x96",
      "type": "image/png",
      "purpose": "maskable any"
    },
    {
      "src": "assets/icons/icon-128x128.png",
      "sizes": "128x128",
      "type": "image/png",
      "purpose": "maskable any"
    },
    {
      "src": "assets/icons/icon-144x144.png",
      "sizes": "144x144",
      "type": "image/png",
      "purpose": "maskable any"
    },
    {
      "src": "assets/icons/icon-152x152.png",
      "sizes": "152x152",
      "type": "image/png",
      "purpose": "maskable any"
    },
    {
      "src": "assets/icons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable any"
    },
    {
      "src": "assets/icons/icon-384x384.png",
      "sizes": "384x384",
      "type": "image/png",
      "purpose": "maskable any"
    },
    {
      "src": "assets/icons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable any"
    }
  ]
}
```

I checked the contents of manifest file after build and it is the same file that we transfer to the frontend. How can the hash mismatch from the has provided in the ngsw.json and the hash made by the service worker locally? Did something change from v16 to v17 in this regard?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.3
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cli                    17.0.3
@angular/ssr                    17.0.3
@schematics/angular             17.0.3
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

The contents of the `dist` folder are compressed after build and inside the `server.ts` I serve them using:

```javascript
    server.get("*.*", expressStaticGzip(distFolder, {
        enableBrotli: true,
        orderPreference: ['br', 'gz'],
    }));
```

**Comment by Raul52** [comment]
The issue was identified.

We are using a Spring Boot server that had a different `manifest.webmanifest` file than the one provided in the `dist` folder.
We had this only now because we made our first change in the `manifest.webmanifest` after the upgrade to Angular 17 by changing the icons to `webp`.
