### ISSUE TITLE
Hydration fails for dynamic lazy loaded components with esbuild

### ISSUE THREAD

**Issue by koenig-dominik** [angular/angular#53191]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Webpack

### Description

The hydration does not detect dynamically rendered components that are lazy loaded when using esbuild, this used to work with webpack

### Minimal Reproduction

Here is a minimal reproduction repository with both a working and a broken version:
Broken (Esbuild) https://github.com/koenig-dominik/ng-hydration-regression/tree/ng17-broken
Working (Webpack) https://github.com/koenig-dominik/ng-hydration-regression/tree/ng17-working

Relevant file: https://github.com/koenig-dominik/ng-hydration-regression/blob/ng17-broken/src/app/dynamic.directive.ts

Just execute `npm run start` and see the difference of hydrated components in the console output

### Your Environment

```text
Angular CLI: 17.0.3
Node: 18.17.1
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3 (cli-only)
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3 (cli-only)
@angular-devkit/schematics      17.0.3
@angular/cli                    17.0.3
@angular/ssr                    17.0.3
@schematics/angular             17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by koenig-dominik** [comment]
Honestly I didn't even see that in my minimal reproduction it didnt output the dynamic component. In my more complex production application this did work.

I have updated the repo to reproduce this state: https://github.com/koenig-dominik/ng-hydration-regression/tree/cf741f658cef1d62d2813c3e3c5a37be13b8b010

## `@angular-devkit/build-angular:application`

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html><html lang="en"><head>
  <script type="module" src="/@vite/client"></script>

  <meta charset="utf-8">
  <title>NgHydrationRegression</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.css"><style ng-app-id="ng">

[_nghost-ng-c3597624338] {
  display: block;
}
/*# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsic3JjL2FwcC9keW5hbWljL2R5bmFtaWMuY29tcG9uZW50LmNzcyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiOmhvc3Qge1xuICBkaXNwbGF5OiBibG9jaztcbn1cbiJdLAogICJtYXBwaW5ncyI6ICI7QUFBQTtBQUNFLFdBQVM7QUFDWDsiLAogICJuYW1lcyI6IFtdCn0K */</style></head>
<body><!--nghm-->
  <app-root ng-version="17.0.4" ngh="1" ng-server-context="ssr"><app-dynamic _nghost-ng-c3597624338="" ngh="0"><p _ngcontent-ng-c3597624338="">dynamic works!</p></app-dynamic><!--container--></app-root>
<script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"t":{"0":"t1"},"c":{"0":[{"i":"c3597624338","r":1}]}}]}</script></body></html>
```
</details>

even though it does output <app-dynamic> in the server generated it, the hydration still doesn't work.
But this can still be caused by a wrong stable detection.

**Comment by alan-agius4** [comment]
I looked at this a bit more today, and I am suspecting that this is an issue with Zone.js and it's patching of promises.

Having the below code:
```ts
import { ApplicationRef, Component, inject } from '@angular/core';
import { tap } from 'rxjs';

@Component({
  selector: 'app-root',
  standalone: true,
  template: '',
})
export class AppComponent {
  constructor() {
    inject(ApplicationRef)
      .isStable.pipe(tap((isStable) => console.log('- isStable: ' + isStable)))
      .subscribe();
  }

  async ngOnInit() {
    console.log('ngOnInit');
    await Promise.resolve()
      .then(() => import('./dynamic-data'))
      .then(
        () =>
          new Promise<void>((resolve) => {
            setTimeout(() => {
              resolve();
            }, 5000);
          })
      )
      .then(() => console.log('- Promise resolved.'));
  }
}

```

The app will go to stable and unstable:

```
app.component.ts:12 - isStable: false
app.component.ts:17 ngOnInit
app.component.ts:12 - isStable: true
app.component.ts:12 - isStable: false
app.component.ts:28 - Promise resolved.
app.component.ts:12 - isStable: true
```

However, if from the above code we comment `.then(() => import('./dynamic-data'))`

In the console we observe:
```
app.component.ts:17 - isStable: false
app.component.ts:17 ngOnInit
app.component.ts:28 - Promise resolved.
app.component.ts:12 - isStable: true
```

**Comment by koenig-dominik** [comment]
I created a new branch in my repository that I created with the most recent angular version: https://github.com/koenig-dominik/ng-hydration-regression/tree/fresh
Here I have added all possible ways to create a dynamic component that i know of.
I even added the possibility to start the development server with webpack and esbuild at the same time, just open two terminals and execute `npm run start` and `npm run start:webpack`

What i learned from this:

## ngComponentOutlet

[eager](https://github.com/koenig-dominik/ng-hydration-regression/blob/2494627fa5110b6ae39f068ceb1e361653eee409/src/app/app.component.ts#L13) Works with webpack & esbuild
[lazy](https://github.com/koenig-dominik/ng-hydration-regression/blob/2494627fa5110b6ae39f068ceb1e361653eee409/src/app/app.component.ts#L14C76-L14C76) Works with webpack, not with esbuild

## ViewContainerRef.CreateComponent

[eager](https://github.com/koenig-dominik/ng-hydration-regression/blob/2494627fa5110b6ae39f068ceb1e361653eee409/src/app/app.component.ts#L62C20-L62C20) Works with webpack & esbuild
[lazy](https://github.com/koenig-dominik/ng-hydration-regression/blob/2494627fa5110b6ae39f068ceb1e361653eee409/src/app/app.component.ts#L65) Works with webpack, not with esbuild

## CreateComponent.attachView

[eager](https://github.com/koenig-dominik/ng-hydration-regression/blob/2494627fa5110b6ae39f068ceb1e361653eee409/src/app/app.component.ts#L75) Works with webpack & esbuild
[lazy](https://github.com/koenig-dominik/ng-hydration-regression/blob/2494627fa5110b6ae39f068ceb1e361653eee409/src/app/app.component.ts#L82) Works with webpack, not with esbuild

## CreateComponent.insert

[eager](https://github.com/koenig-dominik/ng-hydration-regression/blob/2494627fa5110b6ae39f068ceb1e361653eee409/src/app/app.component.ts#L97) Does **not** work with webpack & esbuild
[lazy](https://github.com/koenig-dominik/ng-hydration-regression/blob/2494627fa5110b6ae39f068ceb1e361653eee409/src/app/app.component.ts#L103C9-L103C9) Does **not** work with webpack & esbuild

**Comment by alan-agius4** [comment]
The root cause here is that `import` returns a Native Promises which are not patchable by Zone.js.

**Comment by pappkamerad** [comment]
Is there any update to this?

**Comment by koenig-dominik** [comment]
I updated the repository to angular 18 (and made it a bit clearer how to test)
But the result is still the same as before: https://github.com/koenig-dominik/ng-hydration-regression/tree/44ffc155eb104c4f93a8154c0046a4a9da5f5530

**Comment by koenig-dominik** [comment]
I thought a bit more about [this](https://github.com/angular/angular/issues/53191#issuecomment-1845669433) and came to the conclusion, that is just need something that actually is patched by zone.js to wait for the promises, so i implemented the following workaround: https://github.com/koenig-dominik/ng-hydration-regression/commit/9083a666c27c0b07ab8a0d6c2396c2440473450b
This basically creates a long running timeout that is cleared once all import promises are complete.
But this still spams the `isStable: false / true` so i wouldn't consider this a full fix.

**Comment by arturovt** [comment]
For everyone who has stumbled upon this issue: you will encounter the same problem when enabling zoneless change detection, as there is nothing that patches promises, regardless of whether you use Webpack or ESBuild. Essentially, there is nothing that tells Angular whether there are any running tasks (stable or unstable).

You need to use the pending tasks service (https://angular.dev/guide/experimental/zoneless#experimentalpendingtasks-for-server-side-rendering-ssr) to prevent hydration cleanup until dynamic components are loaded and rendered. Here’s a quick example based on the provided repository in the issue source:

```ts
import {
  DestroyRef,
  Directive,
  ExperimentalPendingTasks,
  inject,
  ViewContainerRef,
} from '@angular/core';

@Directive({
  selector: '[appDynamic]',
  standalone: true,
})
export class DynamicDirective {
  private viewContainerRef = inject(ViewContainerRef);
  private pendingTasks = inject(ExperimentalPendingTasks);
  private destroyed = false;

  constructor() {
    inject(DestroyRef).onDestroy(() => (this.destroyed = true));
  }

  ngOnInit(): void {
    this.render();
  }

  private async render() {
    const removeTask = this.pendingTasks.add();

    // Wrap the code in a try-catch block to ensure the task is
    // removed at the end and to prevent blocking rendering if an
    // error occurs during creation.
    try {
      // Note that `async-await` is being used instead of RxJS `from`
      // and other pipeable operators, as this makes the following code
      // harder to read...
      const component = await import('./dynamic/dynamic.component').then(
        ({ DynamicComponent }) => DynamicComponent
      );

      // If component loading takes longer than expected and the
      // component is destroyed before it finishes loading, we will simply exit.
      if (this.destroyed) return;

      const ref = this.viewContainerRef.createComponent(component);
      ref.changeDetectorRef.detectChanges();
    } finally {
      removeTask();
    }
  }
}
```

**Comment by Aukevanoost** [comment]
I recreated @arturovt 's solution and it works great in ng18, however in ng19, the application is struggling with an [NG0203](https://angular.dev/errors/NG0203) error: 

```
C [Error]: NG0203
    at eI (file:///_angular_core.GUO3wft64J.js:2:2769)
    at me (file:///_angular_core.GUO3wft64J.js:2:2896)
    at Object.factory (file:///_angular_core.GUO3wft64J.js:31:31626)
    at file:///chunk-6WG5ED2O.mjs:18723:39
    at runInInjectorProfilerContext (file:///chunk-6WG5ED2O.mjs:3387:5)
    at R3Injector.hydrate (file:///chunk-6WG5ED2O.mjs:18722:15)
    at R3Injector.get (file:///chunk-6WG5ED2O.mjs:18617:27)
    at Te.getStandaloneInjector (file:///_angular_core.GUO3wft64J.js:31:31971)
    at ComponentFactory.create (file:///chunk-6WG5ED2O.mjs:21039:57)
    at ViewContainerRef2.createComponent (file:///chunk-6WG5ED2O.mjs:21275:47) {
  code: -203
}
```

**Comment by sfinoteffy** [comment]
Don't know if it could help anyone, but when I migrated my SSR Angular 20 App to esbuild I also had NG0203 error when lazy loading my components while inside other components. Now I lazy load them in resolvers and I don't have the issue anymore (was pretty painful to do and don't know why exactly it did the trick)

**Comment by spawnrider** [comment]
I reproduced the solution provided by @arturovt on my Angular v20.3 SSR / Zoneless  / estbuild application and it seems to works perfectly. 
By the way, PendingTask is not anymore in experimental preview (https://angular.dev/guide/zoneless) ... it's now fully stable.

Here's my Hello World class to reproduce the issue and test some fixes... 
```
export class HelloWorldComponent implements OnInit {
  /** Holds the lazily loaded component type once resolved */
  protected readonly cardComponent = signal<Type<unknown> | null>(null);
  private readonly platformId = inject(PLATFORM_ID);
  private pendingTasks = inject(PendingTasks);
  private ref = inject(ChangeDetectorRef);
  private transferState = inject(TransferState);
  private destroyed = false;

  constructor() {
    inject(DestroyRef).onDestroy(() => (this.destroyed = true));
  }

  ngOnInit() {
    if (isPlatformServer(this.platformId)) {
      const key = pickRandomKey();
      this.transferState.set(COMPONENT_KEY, key);
      console.log('HelloWorldComponent selected key:', key);
      // Wrap the code in a try-catch block to ensure the task is
      // removed at the end and to prevent blocking rendering if an
      // error occurs during creation.
      const removeTask = this.pendingTasks.add();
      try {
        // Only load the static version on the server side for immediate rendering.
        // Use a dynamic import to avoid bundling these components in the initial client bundle.
        import('./component-registry').then((mod) => {
          console.log('HelloWorldComponent loading key:', key);
          COMPONENT_REGISTRY[key]().then((cmp) => {
            this.cardComponent.set(cmp);
            this.ref.detectChanges();
          });
        });
      } finally {
        removeTask();
      }
    } else {
      const key = this.transferState.get(COMPONENT_KEY, '');
      console.log('HelloWorldComponent reusing key from TransferState:', key);
      // Lazy client: keep the actual dynamic import by key.
      console.log('HelloWorldComponent lazy loading key:', key);
      COMPONENT_REGISTRY[key]().then((cmp) => this.cardComponent.set(cmp));
    }
  }
}
```

Note that the transferState is only used to render the right component on the client side.

My cardComponent is a signal passed to a ngComponentOutlet and my component registry looks like : 
```
/**
 * Lazy component registry: map an identifier to a dynamic import function.
 * Each entry returns a Promise resolving to an Angular standalone component Type.
 */
export const COMPONENT_REGISTRY: Record<string, () => Promise<Type<unknown>>> = {
  hello: () => import('./hello-card/hello-card').then((m) => m.HelloCardComponent),
  alt: () => import('./hello-alt-card/hello-alt-card').then((m) => m.HelloAltCardComponent),
};
```
