### ISSUE TITLE
ERROR: Top-level await is not available in the configured target environment

### ISSUE THREAD

**Issue by x-wk** [angular/angular#53211]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

```js
17349 │ /******/ __webpack_exports__ = globalThis.pdfjsLib = await (globalThis.pdfjsLibPromise = __webpack_exports__);


01:55:45 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/pdfjs-dist/build/pdf.mjs:17349:53: ERROR: Top-level await is not available in the configured target environment ("chrome118.0", "edge118.0", "firefox115.0", "
ios16.0", "safari16.0" + 7 overrides)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

**Comment by JeanMeche** [comment]
Hi, do you use a custom browserlist ?

**Comment by x-wk** [comment]
Almost all default configurations

**Comment by x-wk** [comment]
Of course, as follows:
and_chr 119
and_ff 119 
and_qq 13.1
and_uc 15.5
android 119
chrome 119
firefox 119
firefox 118
firefox 115
ios_saf 17.1
ios_saf 17.0
ios_saf 16.6-16.7
ios_saf 16.3
ios_saf 16.1
ios_saf 15.6-15.7
kaios 3.0-3.1
kaios 2.5
op_mini all
op_mob 73
opera 103
opera 102
safari 17.1
safari 17.0
safari 16.6
safari 15.6
samsung 23
samsung 22

**Comment by x-wk** [comment]
Exception information seen in the browser console:

```js
core.mjs:10614  ERROR Error: Uncaught (in promise): TypeError: Failed to fetch dynamically imported module: http://localhost:4200/.angular/cache/16.2.10/vite/deps/pdfjs-dist.js?v=a9ded181
TypeError: Failed to fetch dynamically imported module: http://localhost:4200/.angular/cache/16.2.10/vite/deps/pdfjs-dist.js?v=a9ded181
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:11070:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at _Zone.runTask (zone.js:173:47)
```
