### ISSUE TITLE
toObservables(undefined) gives an unclear exception

### ISSUE THREAD

**Issue by ShacharHarshuv** [angular/angular#53495]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In some scenarios, you can initialize your class properties in such a way that when calling `toObservable` the signal you are passing was actually not initialized yet. Typescript can't always guard against this. This is potentially a pretty common mistake. 

In that case, there is an exception when subscribing to the resulting observable, that is not only very vague, but don't point to the offending code. Making it very hard to debug. 

Here's a code example that reproduces it:

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  template: ``,
  imports: [AsyncPipe],
})
export class App {
  counter$ = this._getCounterStream();
  counter = signal(0);

  private _getCounterStream() {
    return toObservable(this.counter);
  }

  constructor() {
    this.counter$.subscribe((counter) => {
      console.log('counter', counter);
    });
  }
}

bootstrapApplication(App);
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-h9blsj?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
ERROR TypeError: source is not a function
  at watcher.injector.injector [as effectFn] (rxjs_interop.mjs:51:21)
  at EffectHandle.runEffect (core.mjs:14202:18)
  at Object.fn (core.mjs:14197:58)
  at Object.run (signals.mjs:529:18)
  at EffectHandle.run (core.mjs:14209:22)
  at ZoneAwareQueueingScheduler.flushQueue (core.mjs:14148:20)
  at core.mjs:14138:41
  at ZoneDelegate.invoke (zone.js:368:26)
  at Object.onInvoke (core.mjs:14697:33)
  at _ZoneDelegate.invoke (zone.js:367:52)
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.1
Node: 20.10.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 17.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1700.1
@angular-devkit/build-angular      17.0.1
@angular-devkit/core               17.0.1
@angular-devkit/schematics         17.0.1
@angular/cdk                       17.0.1
@angular/cli                       17.0.1
@angular/material                  17.0.1
@angular/material-moment-adapter   17.0.1
@schematics/angular                17.0.1
ng-packagr                         17.0.1
rxjs                               7.4.0
typescript                         5.2.2
zone.js                            0.14.2
```

**Comment by JoostK** [comment]
I don't think this is Angular's job to guard against; _every_ function can be called with a value that does not conform to its type and this will behave in unspecified ways.

**Comment by ShacharHarshuv** [comment]
I get it, but I expect a better error in this case.
