### ISSUE TITLE
TestComponentBuilder overrideProviders fails if providers don't exist on the component

### ISSUE THREAD

**Issue by rkirov** [angular/angular#5354]
Only repo-ed in dart.

**Comment by rkirov** [comment]
The issue is in the following line 
https://github.com/angular/angular/blob/c1c54ed0f22df5d7c5bddc3f1cde9bed8dd85c01/modules/angular2/src/mock/directive_resolver_mock.ts#L24

```
    if (isPresent(providerOverrides)) {
      providers = dm.providers.concat(providerOverrides);
    }
```

does not consider what happens when ```dm.providers``` is not defined.

**Comment by laurelnaiad** [comment]
Not sure what only repo'ed in dart means... like reproduced? I'm hitting this in (transpiled) typescript.

```
TypeError: Cannot read property 'concat' of undefined
    at MockDirectiveResolver.resolve (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/mock/directive_resolver_mock.js:46:31)
    at RuntimeMetadataResolver.getDirectiveMetadata (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/compiler/runtime_metadata.js:52:45)
    at TemplateCompiler.compileHostComponentRuntime (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/compiler/template_compiler.js:78:50)
    at RuntimeCompiler_.compileInHost (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/compiler/runtime_compiler.js:47:35)
    at DynamicComponentLoader_.loadAsRoot (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/core/linker/dynamic_component_loader.js:88:27)
    at TestComponentBuilder.createAsync (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/testing/test_component_builder.js:142:62)
    at eval (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/app/feat/auth/components/credentialsPrompt.unit.js:26:147)
    at FunctionWrapper.apply (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/facade/lang.js:317:64)
    at FunctionWithParamTokens.execute (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/testing/test_injector.js:119:35)
    at TestInjector.execute (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/testing/test_injector.js:40:15)
    at Object.eval (/Users/dmaddox/Documents/_ws/myproj/builds/app/browser/jspm_packages/npm/angular2@2.0.0-beta.9/src/testing/testing.js:46:42)
    at /Users/dmaddox/Documents/_ws/myproj/builds/app/browser/testing/karma-system.js:28:13
```
