### ISSUE TITLE
error executing test with beforeAll in Angular 14

### ISSUE THREAD

**Issue by Skumm** [angular/angular#53973]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

running a test with beforeEach works and running the same test with beforeAll returns an error with version 14

```typescript
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-14';

  constructor(private router: Router, private activatedRoute: ActivatedRoute) {

  }
}
```

```javascript
import { TestBed } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeAll(async () => {
    await TestBed.configureTestingModule({
      imports: [
        RouterTestingModule
      ],
      declarations: [
        AppComponent
      ]
    }).compileComponents();
  });

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });

  it(`should have as title 'angular-14'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app.title).toEqual('angular-14');
  });

  it('should render title', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.nativeElement as HTMLElement;
    expect(compiled.querySelector('.content span')?.textContent).toContain('angular-14 app is running!');
  });
});
```

### Please provide the exception or error you saw

```true
Chrome 120.0.0.0 (Windows 10) AppComponent should render title FAILED
        NullInjectorError: R3InjectorError(DynamicTestModule)[ActivatedRoute -> ActivatedRoute]:
          NullInjectorError: No provider for ActivatedRoute!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'ActivatedRoute', 'ActivatedRoute' ] })
            at NullInjector.get (node_modules/@angular/core/fesm2020/core.mjs:8191:27)
            at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:8618:33)
            at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:8618:33)
            at ChainedInjector.get (node_modules/@angular/core/fesm2020/core.mjs:13811:36)
            at lookupTokenUsingModuleInjector (node_modules/@angular/core/fesm2020/core.mjs:3293:39)
            at getOrCreateInjectable (node_modules/@angular/core/fesm2020/core.mjs:3338:12)
            at ɵɵdirectiveInject (node_modules/@angular/core/fesm2020/core.mjs:10913:12)
            at NodeInjectorFactory.factory (ng:///AppComponent/ɵfac.js:4:78)
            at getNodeInjectable (node_modules/@angular/core/fesm2020/core.mjs:3523:44)
            at instantiateRootComponent (node_modules/@angular/core/fesm2020/core.mjs:12592:23)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.13
Node: 16.20.2
Package Manager: npm 8.19.4
OS: win32 x64

Angular: 14.3.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.13
@angular-devkit/build-angular   14.2.13
@angular-devkit/core            14.2.13
@angular-devkit/schematics      14.2.13
@angular/cli                    14.2.13
@schematics/angular             14.2.13
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by atscott** [comment]
This is expected. TestBed cleans up after each test so your setup needs to be beforeEach
