### ISSUE TITLE
Global window vite error

### ISSUE THREAD

**Issue by YashrajDawkhar** [angular/angular#54000]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

![image](https://github.com/angular/angular/assets/67941618/826a16f1-7281-4107-8290-014465a94231)

### Please provide the exception or error you saw

```true
ERROR ReferenceError: window is not defined
    at Object.eval [as next] (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:9454:7)       
    at ConsumerObserver.next (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:406:29)       
    at SafeSubscriber._next (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:380:26)        
    at SafeSubscriber.next (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:353:16)
    at eval (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:917:24)
    at errorContext (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:285:5)
    at Subject.next (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:910:9)
    at Object.eval [as next] (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:3991:24)      
    at ConsumerObserver.next (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:406:29)       
    at SafeSubscriber._next (eval at instantiateModule (file:///C:/Working%20Folder/Intelliassist/homePageIntelliassist/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50858:28), <anonymous>:380:26)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

**Comment by JeanMeche** [comment]
You are running your app with ssr/prerendering enabled. The `window` global is only available in browser environement. 

You need to either disable ssr or you need to manage to not call code that relies on `window` when on the server side (using functions like `isPlatformBrowser`)
