### ISSUE TITLE
I am getting ERROR z [Error]: NG04002: 'cart.json'

### ISSUE THREAD

**Issue by theutkarshjaiswal** [angular/angular#54080]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I have freshly installed node.js v20.11.0 and "@angular/cli": "^17.1.1", with angular ssr  "@angular/ssr": "^17.1.1",
and use the ng build command and after that I have used node dist/my-app/server/server.mjs
everything works fine but when I open the url it also works
but i am getting an error in console

### Please provide the exception or error you saw

```true
ERROR z [Error]: NG04002: 'cart.json'
    at ih.noMatchError (file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:43:73691)
    at file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:43:74388
    at file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:4:16474
    at xl._error (file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:4:5497)
    at xl.error (file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:4:2594)
    at xl._error (file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:4:2834)
    at xl.error (file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:4:2594)
    at xl._error (file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:4:2834)
    at xl.error (file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:4:2594)
    at xl._error (file:///Users/utkarsh/Downloads/projects/my-app/dist/my-app/server/chunk-SEBMPKJZ.mjs:4:2834) {
  code: 4002
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.1.1
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

NG04002 is an error thrown by the router. It appears somewhere you application attempts to navigation to `cart.json`
