### ISSUE TITLE
injector yields wrong result inside embedded view

### ISSUE THREAD

**Issue by bgotink** [angular/angular#54097]
### Which @angular/* package(s) are the source of the bug?

core, forms

### Is this a regression?

No

### Description

Inside an embedded view with an associated injector the injector seems to return an unexpected result, even if the host flag is used.

We've got a nested form, and `formControlName` uses `@Host()` when injecting its container

https://github.com/angular/angular/blob/c3b00959659ca20d3f798820dfcb4dee250a32ac/packages/forms/src/directives/reactive_directives/form_control_name.ts#L129

Our inner form is contained in an ng-template. In the repro below we just instantiate it next to the ng-template itself, in our real code the template outlet would be somewhere else entirely in the application (and DOM).

```html
<!-- outer component -->
<form [formGroup]="outerForm">
  <wrapper-component />
</form>

<!-- wrapper component -->
<ng-container [ngTemplateOutlet]="tpl" [ngTemplateOutletInjector]="injector" />

<ng-template #tpl>
  <inner-component />
</ng-template>

<!-- inner component -->
<form [formGroup]="innerForm">
  <input formControlName="innerInput">
</form>
```

While registering the `formControlName="innerInput"` an error is thrown. Debugging the issue shows that the `formControlName` actually gets the outer form as its form.

<img width="559" alt="image" src="https://github.com/angular/angular/assets/821510/2dd63fd3-5e91-426a-9ff7-7d7f5b1e68af">

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-vvqjnr?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Error: Cannot find control with name: 'innerInput'
    at _throwError (forms.mjs:3208:11)
    at setUpControl (forms.mjs:2991:13)
    at FormGroupDirective.addControl (forms.mjs:4902:9)
    at FormControlName._setUpControl (forms.mjs:5499:43)
    at FormControlName.ngOnChanges (forms.mjs:5444:18)
    at FormControlName.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:2561:14)
    at callHookInternal (core.mjs:3603:14)
    at callHook (core.mjs:3634:9)
    at callHooks (core.mjs:3585:17)
    at executeInitAndCheckHooks (core.mjs:3535:9)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
I've verified the described behaviour is present in Angular 16.1.9, 16.2.12, and 17.1.1.
```

### Anything else?

Removing the `ngTemplateOutletInjector` solves the issue, which makes me question whether it's necessary to pass along an injector. The documentation on the injector input/parameter (both for the `ngTemplateOutlet` directive and for `createEmbeddedView` on `ViewContainerRef` or `TemplateRef`) doesn't really yield any useful information.

**Comment by ChristofferGersen** [comment]
I also ran into this today, with Angular version 18.2.1. I believe the problem here is that once you specify `ngTemplateOutletInjector`, then that injector is always consulted first inside the referenced template. You would expect element injectors to be consulted first, up to the top of the referenced template, and only then consult the provided `ngTemplateOutletInjector`.

This breaks the reactive form directives, because they try to resolve a `ControlContainer`. So if the provided `ngTemplateOutletInjector` provides that, then all reactive form directives inside the referenced template will use that value, regardless of any directives that provide a new value.

**Comment by Markiewic** [comment]
Ran into this after upgrading from Angular 15 to 16. Looks like it's a regression after all.
