### ISSUE TITLE
Client hydration breaks in module bootstrap with AOT disabled

### ISSUE THREAD

**Issue by griest024** [angular/angular#54168]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

When trying to use client hydration with AOT disabled, the app fails to run from the dev server. Building and running SSR appears to work, though there is no message about hydration succeeding.

The following things cause the app to work as expected:
- Enabling AOT or prerendering
- [Rendering the child component directly](https://github.com/griest024/ng17-repro/tree/direct-render)
- Using standalone/function bootstrap method

### Please provide a link to a minimal reproduction of the bug

https://github.com/griest024/ng17-repro/tree/hydration

### Please provide the exception or error you saw

```true
ERROR Error: ASSERTION ERROR: Unexpected state: no hydration info available for a given TNode, which represents a view container. [Expected=> null != undefined <=Actual]
    at throwError2 (core.mjs:473:11)
    at assertDefined (core.mjs:469:9)
    at populateDehydratedViewsInLContainerImpl (core.mjs:17518:9)
    at locateOrCreateAnchorNode (core.mjs:17535:10)
    at createContainerRef (core.mjs:17432:5)
    at injectViewContainerRef (core.mjs:17192:12)
    at core.mjs:4269:29
    at runInInjectorProfilerContext (core.mjs:948:9)
    at lookupTokenUsingNodeInjector (core.mjs:4268:17)
    at getOrCreateInjectable (core.mjs:4235:23)
handleError @ core.mjs:11809
(anonymous) @ core.mjs:31652
invoke @ zone.js:368
run @ zone.js:129
runOutsideAngular @ core.mjs:14677
(anonymous) @ core.mjs:31652
invoke @ zone.js:368
onInvoke @ core.mjs:14781
invoke @ zone.js:367
run @ zone.js:129
(anonymous) @ zone.js:1257
invokeTask @ zone.js:402
(anonymous) @ core.mjs:14455
onInvokeTask @ core.mjs:14455
invokeTask @ zone.js:401
onInvokeTask @ core.mjs:14768
invokeTask @ zone.js:401
runTask @ zone.js:173
drainMicroTaskQueue @ zone.js:581
Zone - Promise.then (async)
onScheduleTask @ core.mjs:14449
scheduleTask @ zone.js:382
onScheduleTask @ zone.js:279
scheduleTask @ zone.js:382
scheduleTask @ zone.js:216
scheduleMicroTask @ zone.js:236
scheduleResolveOrReject @ zone.js:1247
resolvePromise @ zone.js:1184
(anonymous) @ zone.js:1264
invokeTask @ zone.js:402
(anonymous) @ core.mjs:14455
onInvokeTask @ core.mjs:14455
invokeTask @ zone.js:401
onInvokeTask @ core.mjs:14768
invokeTask @ zone.js:401
runTask @ zone.js:173
drainMicroTaskQueue @ zone.js:581
Zone - Promise.then (async)
onScheduleTask @ core.mjs:14449
scheduleTask @ zone.js:382
onScheduleTask @ zone.js:279
scheduleTask @ zone.js:382
scheduleTask @ zone.js:216
scheduleMicroTask @ zone.js:236
scheduleResolveOrReject @ zone.js:1247
then @ zone.js:1453
(anonymous) @ core.mjs:32444
_callAndReportToErrorHandler @ core.mjs:31649
(anonymous) @ core.mjs:32441
invoke @ zone.js:368
onInvoke @ core.mjs:14781
invoke @ zone.js:367
run @ zone.js:129
run @ core.mjs:14632
bootstrapModuleFactory @ core.mjs:32420
(anonymous) @ core.mjs:32473
invoke @ zone.js:368
run @ zone.js:129
(anonymous) @ zone.js:1257
invokeTask @ zone.js:402
runTask @ zone.js:173
drainMicroTaskQueue @ zone.js:581
Promise.then (async)
nativeScheduleMicroTask @ zone.js:557
scheduleMicroTask @ zone.js:568
scheduleTask @ zone.js:392
scheduleTask @ zone.js:216
scheduleMicroTask @ zone.js:236
scheduleResolveOrReject @ zone.js:1247
then @ zone.js:1453
bootstrapModule @ core.mjs:32473
(anonymous) @ main.ts:5
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.0
Node: 18.19.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

### Anything else?

possibly related to #50175

**Comment by topdev658** [comment]
Check if there are any updates for your dependencies, especially Angular-related ones. Running " npm update " or " yarn upgrade " might help to fetch the latest compatible versions.

If you are using the Angular CLI, try running commands like " ng update " or " ng serve --prod " to ensure that everything is set up correctly.

**Comment by JeanMeche** [comment]
I gave it a quick look, it looks like no hydration data are provided in the `TransferState`, not sure why yet.

**Comment by gp187** [comment]
+1

**Comment by VarunS1997** [comment]
This issue is also present on the latest version of angular (v18).

And seems to respond exactly the same, with AOT enabling as well as direct rendering both fixing the issue.

**Comment by thePunderWoman** [comment]
I just updated the repro here to v20, and I'm not seeing any issues with hydration. This seems to have been resolved with recent fixes.

![Image](https://github.com/user-attachments/assets/94db0d22-4d2f-4c99-864b-d5e41f99d924)

**Comment by griest024** [comment]
@jessicajaniuk With which SSR engine is that?

**Comment by thePunderWoman** [comment]
@griest024 This is using whatever the reproduction had set up. I literally just took the reproduction repository and did `ng update` 3 times to get to 20.
