### ISSUE TITLE
contributing from windows: 'patch' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular#54382]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

this affects only windows contributors
in this file https://github.com/angular/angular/blob/main/aio/tools/cli-patches/patch.js#L11
the patch command isn't available in windows, and so it fails

steps to reproduce (in windows only)
1. clone the project or run `git clean -dfx`
2. cd to `aio`
3. run `yarn`

### Please provide the exception or error you saw

```true
PS C:\Users\rober\WebstormProjects\angular\aio> yarn
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ node tools/cli-patches/patch.js && patch-package --patch-dir ../tools/npm-patches/
'patch' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\common.js:401
      if (config.fatal) throw e;
                        ^

Error: exec: 'patch' is not recognized as an internal or external command,
operable program or batch file.

    at Object.error (C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\common.js:110:27)
    at execSync (C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\exec.js:120:12)
    at Object._exec (C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\exec.js:223:12)
    at Object.exec (C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\common.js:335:23)
    at C:\Users\rober\WebstormProjects\angular\aio\tools\cli-patches\patch.js:11:27
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\rober\WebstormProjects\angular\aio\tools\cli-patches\patch.js:11:8)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\Users\rober\WebstormProjects\angular\aio> node tools/cli-patches/patch.js
'patch' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\common.js:401
      if (config.fatal) throw e;
                        ^

Error: exec: 'patch' is not recognized as an internal or external command,
operable program or batch file.

    at Object.error (C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\common.js:110:27)
    at execSync (C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\exec.js:120:12)
    at Object._exec (C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\exec.js:223:12)
    at Object.exec (C:\Users\rober\WebstormProjects\angular\aio\node_modules\shelljs\src\common.js:335:23)
    at C:\Users\rober\WebstormProjects\angular\aio\tools\cli-patches\patch.js:11:27
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\rober\WebstormProjects\angular\aio\tools\cli-patches\patch.js:11:8)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)

Node.js v18.16.0
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.0-rc.0
Node: 18.16.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: undefined
...

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0-next.0
@angular-devkit/architect-cli   0.1702.0-next.0
@angular-devkit/build-angular   17.2.0-rc.0
@angular-devkit/core            17.2.0-rc.0
@angular-devkit/schematics      17.2.0-rc.0
@angular/animations             17.2.0-next.0
@angular/build-tooling          0.0.0-c83e99a12397014162531ca125c94549db55dd84
@angular/cdk                    17.2.0-rc.0
@angular/cli                    17.2.0-rc.0
@angular/docs                   0.0.0-c83e99a12397014162531ca125c94549db55dd84
@angular/material               17.2.0-rc.0
@angular/ng-dev                 <error>
@schematics/angular             17.2.0-rc.0
rxjs                            7.8.1
typescript                      5.3.2
```

### Anything else?

workaround: run yarn from git bash
while it seems easy fix, the error happens when you run `yarn test:ci` and it's not obvious it's caused by failing `yarn install` or that running it from git bash will fix it

**Comment by JeanMeche** [comment]
Hi, 
As you mentionned, there workarounds : either use a gitbash or you can also run it in WSL.

Also, since we plan to deprecate angular.io in favor of angular.dev, we don't plan to work on the improving the tooling around AIO.

**Comment by robertIsaac** [comment]
> Hi, As you mentionned, there workarounds : either use a gitbash or you can also run it in WSL.
> 
> Also, since we plan to deprecate angular.io in favor of angular.dev, we don't plan to work on the improving the tooling around AIO.

could it be written at least that this only works from bash somewhere?
