### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by windmillcode0** [angular/angular#54401]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

It a flaky test the test claims that the varable is never spied on when it is clearly spied on it is shown in these 2 videos

### Please provide a link to a minimal reproduction of the bug

https://www.youtube.com/playlist?list=PLDBs2y4Hd-dru81ZvPh0ccrMP-i_OPemx

### Please provide the exception or error you saw

```true
An error was thrown in afterAll
  Error: <toHaveBeenCalledWith> : Expected a spy, but got Function.
  Usage: expect(<spyObj>).toHaveBeenCalledWith(...arguments)
      at <Jasmine>
      at Object.next (http://localhost:9876/_karma_webpack_/webpack:/src/app/core/utility/scroll-utils.spec.ts:499:53)
      at ConsumerObserver.next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/dist/cjs/internal/Subscriber.js:113:33)
      at SafeSubscriber._next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/dist/cjs/internal/Subscriber.js:80:26)
      at SafeSubscriber.next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
      at onNext (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:192)
      at OperatorSubscriber._next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
      at OperatorSubscriber.Subscriber.next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)```
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.3
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.3
@angular-devkit/build-angular   17.1.3
@angular-devkit/core            17.1.3
@angular-devkit/schematics      17.1.3
@angular/cdk                    17.1.2
@schematics/angular             17.1.3
ng-packagr                      17.1.2
rxjs                            7.5.7
typescript                      5.2.2
zone.js                         0.14.3
```

### Anything else?

See the descripancy between the test case name and the error
![Captura de pantalla 2024-02-12 163655](https://github.com/angular/angular/assets/101383925/8bf6612d-c62e-449c-827a-1bd0c346b5bd)
heres the describe block 
```ts
    // TODO: Test cases here are flaky its saying  method is not a spied when it has clearly became a spy
    xdescribe('listenForScroll', () => {
      beforeEach(() => {
        // @ts-ignore
        scrollPageParams.getTargetElement = () => of(document.createElement('div'));
        spyOn(scrollPageParams, 'getTargetElement').and.callThrough();
        spyOn(scrollPageParams, 'populateWhenEndIsReached').and.returnValue(of(null));
        scrollPageParams.ngUnsub = new Subject<void>();
        scrollPageParams.listenForScollDebounceTime = 500;
        scrollPageParams._keepMakingAPICalls = true;
      });

      it(`when called |
        and target element is obtained |
        should listen for scroll and resize events`, fakeAsync(() => {
        // Arrange
        const targetElement = document.createElement('div');
        let nextFn = (res) => {
          // Assert
          expect(scrollPageParams.getTargetElement).toHaveBeenCalledWith();
          discardPeriodicTasks();
        }
        // Act
        scrollPageParams.listenForScroll().subscribe({next:nextFn});
        tick(scrollPageParams.listenForScollDebounceTime);

      }));

      it(`when called |
        and _keepMakingAPICalls is false |
        should not call populateWhenEndIsReached`, fakeAsync(() => {
        // Arrange
        scrollPageParams._keepMakingAPICalls = false;
        let nextFn = (res) => {
          // Assert
          expect(scrollPageParams.populateWhenEndIsReached).not.toHaveBeenCalled();
          discardPeriodicTasks();
        }
        // Act
        scrollPageParams.listenForScroll().subscribe({next:nextFn});
        tick(scrollPageParams.listenForScollDebounceTime);

      }));

      it(`when called |
        and populateWhenEndIsReached is triggered |
        should call populateWhenEndIsReached`, fakeAsync(() => {
        // Arrange
        scrollPageParams._keepMakingAPICalls = true;
        let nextFn = (res) => {
        // Assert
        expect(scrollPageParams.populateWhenEndIsReached).toHaveBeenCalled();
        discardPeriodicTasks();
        }
        // Act
        scrollPageParams.listenForScroll().subscribe({next:nextFn});
        tick(scrollPageParams.listenForScollDebounceTime);


      }));
    });
```

* heres  the target function
```ts
  listenForScroll=()=>{
    return this.getTargetElement()
    .pipe(
      takeUntil(this.ngUnsub),
      switchMap((res)=>{
        this._targetElement = res
        return  merge(
          fromEvent(res, 'scroll'),
          fromEvent(window, 'resize')
        )
        .pipe(
          debounceTime(this.listenForScollDebounceTime),
          takeUntil(this.ngUnsub),
          takeWhile(()=>this._keepMakingAPICalls),
          concatMap(this.populateWhenEndIsReached)
        )
      })
    )
  }
```
* heres its whole class
```ts
export class ScrollPageParams<T=any>  {
  constructor(params: Partial<ScrollPageParams > = {}) {
    let origParams = Object.entries(params)
      .filter(([key,val]) => {
        return !key.startsWith('param');
      });
    Object.assign(this, {
      ...Object.fromEntries(origParams),
      direction:params.direction ?? "vertical"
    });
    this.populateItemsAtStart().subscribe()
    this.listenForScroll().subscribe()
  }

  _keepMakingAPICalls = true


  targetElement:HTMLElement |string  = document.documentElement
  _targetElement:HTMLElement
  targetElementPollingInterval = 500
  dataSource:WMLDataSource<T> = new WMLDataSource<T>()
  pageReqBody = new WMLAPIPaginationRequestModel()
  listenForScollDebounceTime = 500
  amntOfPixelsFromEndBeforeRetrievingData = 5
  _direction:{
    scrollBegin:string,
    scrollDim:string,
    clientDim:string
  }
  get direction(){
    // @ts-ignore
    return this._direction
  }
  set direction(val:"horizontal" | "vertical"){
    this._direction = {
      "vertical":{
        "scrollBegin":"scrollTop",
        "scrollDim":"scrollHeight",
        "clientDim":"clientHeight"
      },
      "horizontal":{
        "scrollBegin":"scrollLeft",
        "scrollDim":"scrollWidth",
        "clientDim":"clientWidth"
      }
    }[val] ?? this._direction
  }
  ngUnsub:Subject<void>

  beforeItemsRetrievedListener = ()=>{}
  onItemsRetrievedListener = (res)=>{}
  onItemsErrorListener = (err)=>{}
  readonly getTargetElement = ()=>{
    return of(null)
    .pipe(
      takeUntil(this.ngUnsub),
      concatMap(()=>{
        if(this.targetElement instanceof HTMLElement){
          return of(this.targetElement)
        }
        else {
          return this.listenForWhenElementBecomesPresentViaMutationObserverSubj(this.targetElement)
        }

      }),
      catchError(()=>{
        if(this.targetElement instanceof HTMLElement){
          return of(this.targetElement)
        }
        return this.listenForWhenElementBecomesPresentViaPolling(this.targetElement as string)
      })
    )

  }
  readonly listenForWhenElementBecomesPresentViaMutationObserverSubj =(targetSelector:string)=> {

    let subj = new Subject<HTMLElement>()
    let mutationObserver = new MutationObserver(mutations => {
      for (const mutation of mutations) {
        if (mutation.type === 'childList') {
          const targetElement = documentQuerySelector(targetSelector) ;

          if (targetElement) {
            subj.next(targetElement);
            mutationObserver.disconnect();
            break;
          }
        }
      }
    });

    mutationObserver.observe(document.body, { childList: true, subtree: true });
    return subj
  }

  // TODO check and handle accordingly if these methods block
  quitAfterXAttemptsAtPolling =Infinity
  readonly listenForWhenElementBecomesPresentViaPolling=(targetSelector:string) =>{
    let subj = new Subject<HTMLElement>()
    let counter = 0
    let pollingInterval = window.setInterval(() => {
      let targetElement = documentQuerySelector(targetSelector) ;

      if (targetElement) {
        clearInterval(pollingInterval);
        subj.next(targetElement);
      }
      else if(counter > this.quitAfterXAttemptsAtPolling){
        clearInterval(pollingInterval);
        subj.error("Element not found")
      }
      counter++

    }, this.targetElementPollingInterval);

    return subj
  }
  determineXPixelsFromEnd=()=> {
    let element = this._targetElement;

    let xPixelsFromEnd = Math.abs(
      ((element[this._direction.scrollDim] - element[this._direction.scrollBegin]) - element[this._direction.clientDim])
    );
    return xPixelsFromEnd;
  }
  getMoreItems =()=>{
    this.pageReqBody.pageNum +=1
    this.beforeItemsRetrievedListener()
    return this.dataSource.queryDataFromSource(this.pageReqBody)
    .pipe(
      takeUntil(this.ngUnsub),
      tap(this.onItemsRetrievedListener),
      retry(3),
      catchError((err)=>{
        this.pageReqBody.pageNum -=1
        this.onItemsErrorListener(err)
        return of(null)
      })
    )
  }
  populateWhenEndIsReached=(res) => {
    let xPixelsFromEnd = this.determineXPixelsFromEnd();
    this._keepMakingAPICalls = this.dataSource.currentSource.totalItems > this.dataSource.currentSource.data.length

    if(xPixelsFromEnd < this.amntOfPixelsFromEndBeforeRetrievingData && this._keepMakingAPICalls  ){

      return this.getMoreItems()
    }
    return of(null)
  }
  populateItemsAtStart=()=>{
    this.pageReqBody.pageNum = -1
    return this.getMoreItems()
  }
  listenForScroll=()=>{
    return this.getTargetElement()
    .pipe(
      takeUntil(this.ngUnsub),
      switchMap((res)=>{
        this._targetElement = res
        return  merge(
          fromEvent(res, 'scroll'),
          fromEvent(window, 'resize')
        )
        .pipe(
          debounceTime(this.listenForScollDebounceTime),
          takeUntil(this.ngUnsub),
          takeWhile(()=>this._keepMakingAPICalls),
          concatMap(this.populateWhenEndIsReached)
        )
      })
    )
  }

}
```
In addition it might be a simpler replacement to any scroll logic you may be using!!

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by windmillcode0** [comment]
Wait this is not a support request there is a clear bug here, were you able to even watch the video . Did you happen to look at the test case names
