### ISSUE TITLE
NG0911: View has already been destroyed.

### ISSUE THREAD

**Issue by dwilches** [angular/angular#54527]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I recently introduced to my app `DestroyRef` to replace `@ngneat/until-destroy` and I started getting an error in automated tests: `NG0911: View has already been destroyed.`

This issue doesn't manifest while users are interacting with the app, but when I'm testing the app via automated means (where I click very fast in buttons and components are created and destroyed too quickly).

The code where the exception happened is the following (I marked which one is line 76, the one mentioned in the stack trace):

```
    ngOnInit() {
        this.myHttpClient.getCharts()
            .then(allCharts => {
                this.allCharts = allCharts;

                this.myService.getPerms$("SOME_PERM")
                    .pipe(takeUntilDestroyed(this.destroyRef))
                    .subscribe(hasPerms => this.refreshChartDetails(hasPerms)); # line 76
            })
            .catch(error => this.myErrorService.showError(error));
    }
```

### Please provide the exception or error you saw

```true
NG0911: View has already been destroyed.
    at storeLViewOnDestroy (core.mjs:2846:15)
    at NodeInjectorDestroyRef.onDestroy (core.mjs:14215:9)
    at Observable._subscribe (rxjs-interop.mjs:27:41)
    at Observable._trySubscribe (Observable.js:37:25)
    at Observable.js:31:30
    at errorContext (errorContext.js:19:9)
    at Observable.subscribe (Observable.js:22:21)
    at takeUntil.js:7:29
    at SafeSubscriber.<anonymous> (lift.js:10:28)
    at Observable.js:26:30
    at errorContext (errorContext.js:19:9)
    at AnonymousSubject.subscribe (Observable.js:22:21)
    at my-chart-component.component.ts:76:22
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:14832:33)
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.2
Node: 18.13.0
Package Manager: npm 8.19.3
OS: linux x64

Angular: 17.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@schematics/angular             17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alxhub** [comment]
Without a running reproduction it's difficult to be certain, but this seems like it's WAI. By the time the `Promise` resolves, the containing component is already destroyed. The `.then` callback does `.subscribe()`, which subscribes through the `takeUntilDestroyed` operator, which tries to use the `DestroyRef` but it's too late - the component is already dead.

The root cause here is the promise callback which executes the `.subscribe` unconditionally, even if the component is already destroyed.

**Comment by dwilches** [comment]
@alxhub Thanks, that explanation makes sense.

I feel that Angular shouldn't be logging an error in that case though, as it's a normal use case, otherwise users will need to add a second validation before each "subscribe" that involves "takeUntilDestroyed" to make sure the component has not been destroyed already.

Even if this is just a log, and not a real error, this causes trouble for tools that monitor the health of the application, for example we have `failOnConsoleError` in Cypress, so this makes the tests fail from time to time (as it acts as a race-condition). Similarly, error reporting tools like Rollbar would need adjustment to learn to ignore errors if this happens in production.

**Comment by sysmat** [comment]
yes, have the same problem, but in runtime

**Comment by sysmat** [comment]
I moved to old way `OnDestroy` hook and `takeUntil` and error is gone

**Comment by sysmat** [comment]
- je for monitoring I use sentry and if not sentry error report I would probably not now for error
- NG0911 no documentation

**Comment by DmSor** [comment]
It would be convenient if [DestroyRef](https://angular.io/api/core/DestroyRef) had a destroyed flag.
It would be possible to check before creating a subscription.
```typescript
abstract class DestroyRef {
  onDestroy(callback: () => void): () => void;
  readonly destroyed: boolean;
}
```

**Comment by alexkunin** [comment]
> [...] this seems like it's working as intended. By the time the `Promise` resolves, the containing component is already destroyed. The `.then` callback does `.subscribe()`, which subscribes through the `takeUntilDestroyed` operator, which tries to use the `DestroyRef` but it's too late - the component is already dead.

I tend to agree with @alxhub, things work as intended. It's not totally unreasonable to not log the error in this particular case, but generally I'd rather know if my code accesses resources that have been already freed.

Maybe it would be better to fix the code snippet listed above, instead of extending Angular responsibility with detecting right or wrong cases of "View has already been destroyed" error.

For example, that code snippet uses three somewhat orthogonal concepts:
* a class field that holds value -- just a plain value, nothing reactive here
* a promise -- which loads data for that value
* an observable -- that does some additional processing after promise is complete

What if we rewrite code like this:
```ts
ngOnInit() {
    from(this.myHttpClient.getCharts()).pipe(
        catchError(error => this.myErrorService.showError(error)),
        tap(allCharts => this.allCharts = allCharts),
        switchMap(() => this.myService.getPerms$("SOME_PERM")),
        tap(() => hasPerms => this.refreshChartDetails(hasPerms)),
        takeUntilDestroyed(this.destroyRef),
    ).subscribe();
}
```
So, now:
* we have single flow of events/data
* everything is bound during component initialization
* destroying component early will also cancel promise in progress

Also, I'd suggest to rewrite code to be more reactive, e.g.:
```ts
class Component {
  readonly allCharts$ = defer(() => this.myHttpClient.getCharts());
}
```
But I see too little context to be sure that's viable in your case.

**Comment by smleake** [comment]
We've recently started experiencing this issue within our codebase as well and have identified that it's coming from our usages of `takeUntilDestroyed`. We have found that a likely significant contributor to the errors is an Observable that shouldn't be using the operator in the first place (because it's within a hot function that get's invoked multiple times throughout the life of the component, `take(1)` would likely be a better fit). Just so I'm absolutely clear, this error occurs whenever we try to subscribe to an Observable utilizing `takeUntilDestroyed` but the view has been destroyed already. Is that a fair assumption? Thanks guys, appreciate your time!

**Comment by CosmoFruit** [comment]
Reproduced error NG0911 case with CVA:
https://stackblitz.com/edit/stackblitz-starters-ef36xs?file=src%2Fmain.ts

**Comment by waterplea** [comment]
I think if we use `takeUntilDestroyed` on an already destroyed view it should immediately terminate the subscription, rather than throw an error.

**Comment by splincode** [comment]
https://github.com/taiga-family/taiga-ui/pull/7302/files#diff-fe4437041f452cadbc616f8feea30b6f2a28fa203be1a92ec7abcc7fb366c529R32

**Comment by dwilches** [comment]
@alxhub You previously added the `needs reproduction` label to this issue, CosmoFruit added one last week: https://github.com/angular/angular/issues/54527#issuecomment-2073408658

**Comment by alexkunin** [comment]
@dwilches It seems with CVA it's a somewhat different issue, albeit with a similar symptom.

There is a `cleanUpControl` function ([source code](https://github.com/angular/angular/blob/58a8f124b0b61ae3ac59339ce0ae0dd444246b52/packages/forms/src/directives/shared.ts#L94-L132)) which:

> Reverts configuration performed by the `setUpControl` control function. Effectively disconnects form control with a given form directive. This function is typically invoked when corresponding form directive is being destroyed.

So, `forms` package treats `registerOnChange()` as a callback setter, and the mental model is "only one callback at a time" along with "we can pass NOOP there to disable previously set callback".

In the reproduction code, `registerOnChange()` actually sets up many callbacks, which is breaks the way CVA works.

TBF [docs](https://angular.io/api/forms/ControlValueAccessor#registeronchange) are clear re how to use the `registerOnChange()`, but not clear re why:

> Usage Notes
> Store the change function
> The following example stores the provided function as an internal method.
> 
> ```ts
> registerOnChange(fn: (_: any) => void): void {
>   this._onChange = fn;
> }
> ```

And also, docs don't mention that function can be called as a cleanup step. Only setup part is mentioned:

> This method is called by the forms API on initialization to update the form model when values propagate from the view to the model.

As a conclusion, it seems that setting up a subscription in `registerOnChange()` is wrong, and leads to weird and seemingly unrelated error message.

**Comment by waterplea** [comment]
Sure, but unless we immediately unsubscribe instead of throwing an error we would either need to remember **all** the places like that or have Angular to trigger `DestroyRef` as the very last step of the destruction process. I don't think there are many benefits to throwing an error vs to just terminating the subscription. At least in `takeUntilDestroyed` as opposed to manual use of `DestroyRef`. All we are doing this way is forcing people who got burned by that to implement their own `takeUntilDestroyed`, wrapping the bundled one in `catchError`. Unless I'm missing something, in which case I'd like to hear the Angular team share their thoughts on throwing the error.

**Comment by fen89** [comment]
> All we are doing this way is forcing people who got burned by that to implement their own `takeUntilDestroyed`, wrapping the bundled one in `catchError`. Unless I'm missing something, in which case I'd like to hear the Angular team share their thoughts on throwing the error.

This is something which really bothers me - years before we added functions, e.g. a  decorator like `@UntilDestroy` or created our own implementations before `takeUntilDestroyed` came. Now we migrated everything to this **core** functionality, which is now throwing an error in scenarios we can't control without wrapping it again.

I am agreeing with @waterplea here: Imho a core functionality should not throw an error in such cases where it can't be completely controlled. 

We had problems in production apps because this error caused the app to not work propertly after in some cases. If instead it only had printed a warning instead of throwing an error everything would be just fine.

**Comment by sysmat** [comment]
- The same here, it didn't work in production
- I had to revert to old way `OnDestroy, #onDestroyComponent$ = new Subject<void>();, takeUntil`
- NG0911 is not listed in angular doc pages

**Comment by grosch-intl** [comment]
Agree, this is horrible behavior. If we do it the way Angular tells us to, there shouldn't be errors.

**Comment by waterplea** [comment]
> - The same here, it didn't work in production
> - I had to revert to old way `OnDestroy, #onDestroyComponent$ = new Subject<void>();, takeUntil`
> - NG0911 is not listed in angular doc pages

There's a good chance you have a memory leak this way, if the new behavior throws an error for you. Change that to `ReplaySubject` so it terminates subscriptions that happened after `ngOnDestroy`. And don't complete that subject.

**Comment by sysmat** [comment]
- @waterplea This way is working, and every rxjs is unsubscribed
- problem is when using `#destroyRef = inject(DestroyRef); takeUntilDestroyed(this.#destroyRef)`

**Comment by waterplea** [comment]
> * @waterplea This way is working, and every rxjs is unsubscribed
> * problem is when using `#destroyRef = inject(DestroyRef); takeUntilDestroyed(this.#destroyRef)`

Here's a fork of the reproduction above, with CVA:
https://stackblitz.com/edit/stackblitz-starters-jo9x3a
The memory leak is present, you can see subscription still posting in console after component is destroyed. If you are **sure** in your code every rxjs is unsubscribed — that's just luck based on the order of execution. There are a lot of cases where subscription can happen after `ngOnDestroy`, using `ReplaySubject` instead of `Subject` makes you safe from those hard to track memory leaks. `takeUntilDestroyed` currently exposes the memory leaks by throwing an error, rather than taking care of it for us, like `ReplaySubject` would.

**Comment by waterplea** [comment]
While we wait, here's a little wrapper that takes care of the error and memory leaks:
```ts
export function safeTakeUntilDestroyed<T>(destroyRef?: DestroyRef): MonoTypeOperatorFunction<T> {
  return pipe(
    takeUntil(
      NEVER.pipe(
        takeUntilDestroyed(destroyRef),
        catchError(() => EMPTY),
        defaultIfEmpty(null)
      )
    )
  );
}
```
`NEVER` does not emit any values and does not complete, unless `takeUntilDestroyed` is triggered. If it causes an error — `catchError` switches to `EMPTY` which immediately completes. `defaultIfEmpty` takes care of emitting `null` which triggers topmose `takeUntil`. For showing it works properly:
https://stackblitz.com/edit/stackblitz-starters-wsk1wx

**Comment by sysmat** [comment]
@waterplea I try it in my app, but still getting NG0911

**Comment by waterplea** [comment]
> @waterplea I try it in my app, but still getting NG0911

Make sure you copy-paste exactly as it is written and do not have any other places with another `takeUntilDestroyed`. There can be no error since there's a `catchError` right under `takeUntilDestroyed`.

**Comment by qwekelly** [comment]
maybe He should run `onDestroyCallback ` directly instead of throwing an error, right?
```typescript
export function storeLViewOnDestroy(lView: LView, onDestroyCallback: () => void) {
  if ((lView[FLAGS] & LViewFlags.Destroyed) === LViewFlags.Destroyed) {
    onDestroyCallback && onDestroyCallback();
    // throw new RuntimeError(RuntimeErrorCode.VIEW_ALREADY_DESTROYED, ngDevMode && 'View has already been destroyed.');
  }
  if (lView[ON_DESTROY_HOOKS] === null) {
    lView[ON_DESTROY_HOOKS] = [];
  }
  lView[ON_DESTROY_HOOKS].push(onDestroyCallback);
}
```

**Comment by sysmat** [comment]
@waterplea I did and ng 18.0.1 still getting NG0911

**Comment by waterplea** [comment]
> @waterplea I did and ng 18.0.1 still getting NG0911

Can you provide a reproduction repo?

**Comment by fabiendv** [comment]
Is there a way to catch the error until a fix is made?

**Comment by dwilches** [comment]
@fabiendv The workaround is to use https://github.com/ngneat/until-destroy

There is no solution nor workaround from part of the Angular team.

I've been using NgNeat's implementation for years without issues, we tested Angular's implementation but had to go back to NgNeat because of the NG0911.

**Comment by dwilches** [comment]
@alxhub @waterplea 

I'm attaching here a reproduction.

Basically the code does [this](https://github.com/dwilches/NG0911-Reproduction/blob/master/src/app/page1.component.ts), to make the promise resolve after the component has been destroyed:

```typescript
    ngOnInit() {
        this.router.navigate(["page2"])

        Promise.resolve()
            .then(() => {
                console.log("Page1Component: Promise resolved")

                of(null)
                    .pipe(takeUntilDestroyed(this.destroyRef))
                    .subscribe(() => {
                        console.log("Page1Component: Observable resolved");
                    });
            })
            .catch(error => {
                console.log("Page1Component: Exception found", error)
            });
    }

    ngOnDestroy() {
        console.log("Page1Component: destroyed (ngOnDestroy)")
    }
```

This code would print:

![image](https://github.com/user-attachments/assets/67daca54-f539-4b00-94eb-d8a63a04f2d5)

Each time you press the HTML button, you'll get another NG0911.

**Comment by MartirosyanMarat** [comment]
I have the same issue with Angular v17
In my case it was obvious.
In ngAfterViewInit() I have used setTimeout(this.trackFormChanges(), 1000),
And if the user immideately leaved the component, then when the Macrotask(setTimeout) finally worked, it realized the component has already be destroyed, and cant find the ref. Bellow is the full example.

` ngAfterViewInit() {
setTimeout(() => {
this.formValueChanges();
}, 1000)
}

private formValueChanges() {
this.formGroup.valueChanges
.pipe(takeUntilDestroyed(this.destroyRef))
.subscribe(() => {
this.postChanged.emit(this.getPostFromForm() as unknown as PostModel);
})
}`

But when I removed the setTimeout it doesn't throw this error anymore NG0911: View has already been destroyed.

**Comment by MartirosyanMarat** [comment]
I have the same issue with Angular v17
In my case it was obvious.
In `ngAfterViewInit()` I have used `setTimeout(this.trackFormChanges(), 1000)`,
And if the user immideately leaved the component, then when the Macrotask(setTimeout) finally worked, it realized the component has already be destroyed, and cant find the ref. Bellow is the full example.

` ngAfterViewInit() {
setTimeout(() => {
this.formValueChanges();
}, 1000)
}

private formValueChanges() {
this.formGroup.valueChanges
.pipe(takeUntilDestroyed(this.destroyRef))
.subscribe(() => {
this.postChanged.emit(this.getPostFromForm() as unknown as PostModel);
})
}`

But when I removed the `setTimeout` it doesn't throw this error anymore `NG0911: View has already been destroyed`

**Comment by vytautas-pranskunas-** [comment]
any update?

**Comment by ricardoferreirades** [comment]
I recently faced the same issue. What I could notice is that this started to happen when I implemented the OnDestroy lifecycle method manually and used the pipe takeUntilDestroyed. When I removed the OnDestroy method from my component the issue did not happen anymore.

My assumption is that the pipe is not getting the ngOnDestroy method reference correctly.

**Comment by pburgmer** [comment]
> [@alxhub](https://github.com/alxhub) [@waterplea](https://github.com/waterplea)
> 
> I'm attaching here a reproduction.
> 
> Basically the code does [this](https://github.com/dwilches/NG0911-Reproduction/blob/master/src/app/page1.component.ts), to make the promise resolve after the component has been destroyed:
> 
>     ngOnInit() {
>         this.router.navigate(["page2"])
> 
>         Promise.resolve()
>             .then(() => {
>                 console.log("Page1Component: Promise resolved")
> 
>                 of(null)
>                     .pipe(takeUntilDestroyed(this.destroyRef))
>                     .subscribe(() => {
>                         console.log("Page1Component: Observable resolved");
>                     });
>             })
>             .catch(error => {
>                 console.log("Page1Component: Exception found", error)
>             });
>     }
> 
>     ngOnDestroy() {
>         console.log("Page1Component: destroyed (ngOnDestroy)")
>     }
> This code would print:
> 
> ![image](https://github.com/user-attachments/assets/67daca54-f539-4b00-94eb-d8a63a04f2d5)
> 
> Each time you press the HTML button, you'll get another NG0911.

Reproduction still "works" with Angular 19.2.0

**Comment by arturovt** [comment]
@dwilches you can close the issue since the fix has been merged.

**Comment by canutoalex** [comment]
@dwilches @thePunderWoman Any changes on making this available not only in major, but in a next 19.x version? We are experiencing it right now and we would like to avoid workarounds.

**Comment by JeanMeche** [comment]
I'll re-open this issue for tracking purposes, 

We decided to revert #58008, because it introduces a semi-synchronous behaviour that we'd like to avoid in the framework. 

For those interested, a [short read on mixing sync & async callbacks ](https://blog.izs.me/2013/08/designing-apis-for-asynchrony/).
