### ISSUE TITLE
Cant Install angular libary into angular app for local development

### ISSUE THREAD

**Issue by windmillcode0** [angular/angular#54543]
### Which @angular/* package(s) are the source of the bug?

compiler, core

### Is this a regression?

Yes

### Description

So it used to be I can simply build a library with ng build --watch 
make the project avaiable with npm link
run npm link my-lib in the consumer
run the consumer
edit the library and see the changes in the consumer

Now the consumer says nothing has changed
I think the compiler or change detection may have beceome too complicated to the point where its failing to see changes
and created a minimal reproduction with the latest angular stable version v 17.2.1 and even trying to use the library in the application throws a bug indicating something wrong with angular interals as referendec in the video

### Please provide a link to a minimal reproduction of the bug

https://github.com/windmillcode0/angular-lib-changes-dont-take-effect

### Please provide the exception or error you saw

```true
TypeError: Cannot read properties of null (reading 'bindingStartIndex')
    at ɵɵelementStart (core.mjs:23476:46)
    at MyLibComponent_Template (my-lib.component.ts:14:28)
    at executeTemplate (core.mjs:10537:9)
    at renderView (core.mjs:11735:13)
    at renderComponent (core.mjs:11682:5)
    at renderChildComponents (core.mjs:11783:9)
    at renderView (core.mjs:11763:13)
    at renderComponent (core.mjs:11682:5)
    at renderChildComponents (core.mjs:11783:9)
    at renderView (core.mjs:11763:13)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.2.0
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0
@angular-devkit/build-angular   17.2.0
@angular-devkit/core            17.2.0
@angular-devkit/schematics      17.2.0
@angular/cli                    17.2.0
@schematics/angular             17.2.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

### Anything else?

Link to video https://www.youtube.com/watch?v=TMiGOxrSSdo

**Comment by windmillcode0** [comment]
Hold on not quite man at least watch the video I felt you took a glance. With an upgraded application there is no such error. Please watch the video to get the full context this does happen in upgraded angular apps only new ones. in upgraded apps change detection does not happen at all. Please watch the video to get a better understanding

**Comment by windmillcode0** [comment]
Greetings please watch the video for full context. I would suppose mutliple instances of angular/core has to run. its the only way to do development on an external library from a consumer app. How else would this be done?
