### ISSUE TITLE
Unable to unit test stuff inside effect

### ISSUE THREAD

**Issue by rip222** [angular/angular#54545]
### Which @angular/* package(s) are the source of the bug?

compiler, core

### Is this a regression?

Yes

### Description

I'm trying to assert a method of the component is called when a signal emits `true` inside `effect`. 

Since no one else reported such an issue yet I assume I might be doing something wrong, but then again there are no docs explaining how to do these things right. So there.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-p37z7j?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=package.json,setup-jest.ts,jest.config.js,tsconfig.spec.json,src%2Fmain.ts,src%2Fapp.component.spec.ts&template=node&title=Angular%20Starter

### Please provide the exception or error you saw

```true
Message:
      expect(jest.fn()).toHaveBeenCalled()
    
    Expected number of calls: >= 1
    Received number of calls:    0
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17.2
Node 18
Package Manager: npm / pnpm
OS: Linux, Mac, Windows
```

### Anything else?

I tried:

- wrapping the test with `fakeAsync`
- Moving `TestBed.flushEffects()` around

**Comment by alxhub** [comment]
Just as a note, the reproduction doesn't work for me. I get some internal stackblitz/Jest error:

```
✘ [ERROR] Angular compilation initialization failed. [plugin angular-compiler]

  TypeError: t.record is not a function
      at RecordableHistogram.record (https://stackblitzstartersbtwp9l-4g0d.w-credentialless.staticblitz.com/blitz.a9c8a5a3.js:160:3579)
      at ThreadPool.runTask (file:///home/projects/stackblitz-starters-btwp9l/node_modules/piscina/dist/src/index.js:699:23)
      at Piscina.run (file:///home/projects/stackblitz-starters-btwp9l/node_modules/piscina/dist/src/index.js:912:65)
```

**Comment by JeanMeche** [comment]
@alxhub this is a stackblitz issue due to an incompatibility with a CLI deps. You can fixe this by downgrading `piscina`.

```
  "overrides": {
    "piscina": "4.2.1"
  }
```

**Comment by rip222** [comment]
@alxhub fixed it

**Comment by atscott** [comment]
https://github.com/angular/angular/blob/55fd7b3c85253554d579a3fc807349f32e60a89a/packages/core/src/render3/reactivity/effect.ts#L258

Effects do not execute until components have been change detected. If you add fixture.detectChanges() after createComponent, does that resolve your issue?

**Comment by rip222** [comment]
> https://github.com/angular/angular/blob/55fd7b3c85253554d579a3fc807349f32e60a89a/packages/core/src/render3/reactivity/effect.ts#L258
> 
> Effects do not execute until components have been change detected. If you add fixture.detectChanges() after createComponent, does that resolve your issue?

As far as I know effects do not rely on change detection. They have their own scheduler

**Comment by atscott** [comment]
> As far as I know effects do not rely on change detection. They have their own scheduler.

Yes, they do. I've linked to the bit of code that explains why.

> And no, it does not resolve the issue :(

I do believe that it does: https://stackblitz.com/edit/stackblitz-starters-sdhdqy?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=package.json,setup-jest.ts,jest.config.js,tsconfig.spec.json,src%2Fmain.ts,src%2Fapp.component.spec.ts&template=node&title=Angular%20Starter

**Comment by rip222** [comment]
> > As far as I know effects do not rely on change detection
> 
> Yes, they do. I've linked to the bit of code that explains why.
> 
> > And no, it does not resolve the issue :(
> 
> I do believe that it does: https://stackblitz.com/edit/stackblitz-starters-sdhdqy?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=package.json,setup-jest.ts,jest.config.js,tsconfig.spec.json,src%2Fmain.ts,src%2Fapp.component.spec.ts&template=node&title=Angular%20Starter

Amazing! Strangely enough though in my production code it still does not work, but stackblitz example does :)
