### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by bcherkezovtf** [angular/angular#54646]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

I'm trying to build a library, and I'm receiving the error bellow.
It is something related to typescript version, it can be seen from the exception too. When i change the ts version to 5.0 for example the error changes.

### Please provide the exception or error you saw

```true
TypeError: Cannot read properties of undefined (reading 'length')
    at fileExtensionIs (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:6601:17)
    at tryRemoveExtension (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:18585:12)
    at removeFileExtension (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:18577:29)
    at getOutputPathsForBundle (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:109938:81)
    at getOutputPathsFor (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:109946:14)
    at forEachEmittedFile (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:109894:33)
    at verifyCompilerOptions (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:119001:9)
    at Object.createProgram (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:116897:5)
    at file:///Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/@angular/compiler-cli/bundles/chunk-QRYLMBG3.js:7334:89
    at ActivePerfRecorder.inPhase (file:///Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/@angular/compiler-cli/bundles/chunk-HJOPJLIM.js:134:14)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.12
Node: 18.19.1
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 16.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.12
@angular-devkit/build-angular   16.2.12
@angular-devkit/core            16.2.12
@angular-devkit/schematics      16.2.12
@angular/google-maps            16.0.4
@schematics/angular             17.2.1
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by JoostK** [comment]
There seems to be an issue with your TypeScript config file, as TS crashes when trying to process it.

Without a reproduction this isn't otherwise actionable to us.

**Comment by bcherkezovtf** [comment]
Thank you for the direction. I start debugging it and find out it was looking for out || outFile property from my tsconfig, so I added one, but now i failed with:

```TypeError: Cannot read properties of undefined (reading 'flags')
    at checkUnreachable (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:44035:25)
    at bindChildren (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:41851:11)
    at bind (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:43164:11)
    at bindSourceFile2 (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:41492:9)
    at bindSourceFile (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:41434:5)
    at initializeTypeChecker (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:83891:9)
    at createTypeChecker (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:46011:5)
    at Object.getTypeChecker (/Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/typescript/lib/typescript.js:117526:44)
    at new NgCompiler (file:///Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/@angular/compiler-cli/bundles/chunk-QRYLMBG3.js:6539:73)
    at NgCompiler.fromTicket (file:///Users/bozhidarcherkezov/projects/geoscan-angular-8-nx-work/node_modules/@angular/compiler-cli/bundles/chunk-QRYLMBG3.js:6504:16```

**Comment by JoostK** [comment]
Please provide a reproduction; the `out`/`outFile` being omitted shouldn't cause TS to crash, nor should the newly shared stacktrace. But without further insight into your setup, this won't be actionable.

**Comment by bcherkezovtf** [comment]
I found out what was causing it. After going through all dependeces again I noticed that @nx/angular was 17.1, not 16.2 like the others deps. After changing it to 16.2 it start building again.
