### ISSUE TITLE
Error Application start, functional guard injection in the app_routes_config

### ISSUE THREAD

**Issue by tonia211262** [angular/angular#54692]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

```
ERROR Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
  at injectInjectorOnly (core.mjs:3824:15)
    at ɵɵinject2 (core.mjs:3837:42)
    at inject2 (core.mjs:3921:12)
    **at app.routes.ts:75:15**
    at Generator.next (<anonymous>)
    at chunk-5AA32OEI.js:44:61
    at new ZoneAwarePromise (zone.js:1425:21)
    at __async (chunk-5AA32OEI.js:28:10)
    at routes.canActivate (app.routes.ts:74:73)
    at router.mjs:3357:134
```

### app.routes.ts
```
export const routes: Routes = [
  {
    path: 'login',
    component: LoginComponent,
    title: '..'
  },
  {
    path: '',
    resolve: {},
    canActivate: [
      **async (route: ActivatedRouteSnapshot, state: RouterStateSnapshot) =>
        await inject(AuthenticationGuard).canActivate(route, state)**
    ],
    component: NavigationComponent,
    children: [...]
  }
];
```
### authentication.guard.ts
```
export type CanActivateType =
  | Observable<boolean | UrlTree>
  | Promise<boolean | UrlTree>
  | boolean
  | UrlTree;

@Injectable({
  providedIn: 'root'
})
export class AuthenticationGuard {
  canActivate: CanActivateFn = (
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): CanActivateType => {
    // const authentication = route.data.authentication;
    const authentication = inject(AuthenticationService).getAuthentication();

    if (!authentication || FunctionDates.lessNow(authentication.dataScadenza)) {
      inject(GlobalService).clear();

      return inject(Router).createUrlTree(['login']);
    }
    return !!authentication; // eslint-disable-line
  };
}
```

**Comment by JeanMeche** [comment]
Hi, your code doesn't reproduce the issue. Could you try to provide a reproduction on stackblitz ? 

Also is your Guard comming from a library ?

**Comment by tonia211262** [comment]
> Hi, your code doesn't reproduce the issue. Could you try to provide a reproduction on stackblitz ?
> 
> Also is your Guard comming from a library ? **Not. It's the functional version of the framework's native guard.**
The project is very large, I encountered this error after upgrading angular to the latest version and integrating the new features offered such as standalone components. Please try checking here first for errors:

**app.config.ts**
```
export const appConfig: ApplicationConfig = {
  providers: [
    importProvidersFrom([
      CalendarModule.forRoot({ provide: DateAdapter, useFactory: adapterFactory })
    ]),
    provideLocaleConfig(),
    provideCharts(withDefaultRegisterables()),
    provideRouter(
      routes,
      withComponentInputBinding(),
      withDebugTracing(),
      withInMemoryScrolling({
        anchorScrolling: 'enabled',
        scrollPositionRestoration: 'enabled'
      }),
      withDisabledInitialNavigation(),
      withEnabledBlockingInitialNavigation(),
      withPreloading(PreloadAllModules),
      withRouterConfig({ onSameUrlNavigation: 'reload' }),
      withViewTransitions({ skipInitialTransition: true }),
      withPreloading(PreloadAllModules),
      withDebugTracing()
    ),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:10000'
    }),
    provideHttpClient(
      withFetch(),
      withInterceptors([
        authInterceptor,
        errorInterceptor,
        loaderInterceptor,
        retryInterceptor(RETRY_INTERCEPTOR_CONFIG)
      ]),
      withJsonpSupport(),
      withXsrfConfiguration({ cookieName: 'TOKEN', headerName: 'X-TOKEN' })
    ),
    provideAnimations(),
    provideClientHydration(withHttpTransferCacheOptions({ includePostRequests: true })),
    { provide: APP_ID, useValue: 'serverApp' },
    { provide: APP_BASE_HREF, useValue: '/app-noleggi' },
    {
      provide: APP_INITIALIZER,
      multi: true,
      deps: [SwUpdate, AppConfigService],
      useFactory: (swUpdate: SwUpdate, appConfigService: AppConfigService) => {
        return async () => {
          const config = await appConfigService.loadAppConfig();

          checkForUpdates(swUpdate);

          return config;
        };
      }
    },
    {
      provide: IMAGE_CONFIG,
      useValue: {
        disableImageSizeWarning: false,
        disableImageLazyLoadWarning: false
      }
    },
    { provide: LocationStrategy, useClass: PathLocationStrategy }
  ]
};
```

**Comment by JoostK** [comment]
At least `checkForUpdates` is using `inject` while being called from inside a `useFactory` callback _after_ an await point, so `checkForUpdates` doesn't run in an injection context there (everything after the `await` executes in a microtick in a new stack). There's likely a similar thing going on in your `CanActivateFn` callback.

**Comment by JoostK** [comment]
I won't be able to help further without runnable reproduction.

**Comment by tonia211262** [comment]
I add [project](https://stackblitz.com/edit/stackblitz-starters-9bflyh) on stackblitz.

**Comment by JoostK** [comment]
It's the same as in https://github.com/angular/angular-cli/issues/27122. The path mapping for `@angular` causes `@angular/core` to be included multiple times during `ng serve` (with the Vite devserver), each having their own, independent, injection context.
