### ISSUE TITLE
after render hook test is flaky in the repository

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#54813]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

[The "does not execute queueStateUpdate if application is destroyed" test](https://github.com/angular/angular/blob/54340a9fffcc9e35efa4134840a96df41ebaface/packages/core/test/acceptance/after_render_hook_spec.ts#L141-L168) is flaky when running `test packages/core/test/acceptance` and fails with:

```
Error: 'expect' was used when there was no current spec, this could be because an asynchronous test timed out
    at Env.expect (/Users/pkozlowski/work/github/pkozlowski-opensource/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1945:15)
    at expect (/Users/pkozlowski/work/github/pkozlowski-opensource/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:8267:18)
    at file:///packages/core/test/acceptance/after_render_hook_spec.ts:165:12
```

**Comment by JoostK** [comment]
I have a fix for this in #54801
