### ISSUE TITLE
Angular QuickStart Application will not run when upgrading to v17

### ISSUE THREAD

**Issue by Billy-BermanDS** [angular/angular#54967]
### Describe the problem that you experienced

I need to perform a hybrid upgrade from AngularJS to the latest version of Angular v17.  In following the guide here:  [Angular Upgrade](https://angular.io/guide/upgrade)  , it instructs that the Quickstart repo should be used.
![image](https://github.com/angular/angular/assets/163567838/0be94a81-c29d-4753-8861-36006667e134)

After following the steps in [Steps for Upgrading from AngularJS](https://angular.io/guide/upgrade-setup) I'm unable to get the application to successfully execute.  There's a browser error that is being encountered related to loading the @Angular/Platform-Browser-Dynamic library via systemjs-plugin-babel.  

Is this guide still the recommended approach for starting an AngularJS Hybrid upgrade?

Here's a github repo that was created following the guide that can be used to reproduce the issue and also a Stackblitz that shows the issue.

[GitHub Repo](https://github.com/Billy-BermanDS/Angular17-Quickstart)
[StackBlitz](https://stackblitz.com/edit/angularquickstartv17)

### Enter the URL of the topic with the problem

https://angular.io/guide/upgrade-setup

### Describe what you were looking for in the documentation

I anticipated that upon completion of the guide, I would have a version of the Quickstart repo that will run the latest version of Angular.

### Describe the actions that led you to experience the problem

I followed the guide step-by-step but was unable to get the component to load due to the error loading the @Angular/Platform-browser-dynamic library

### Describe what you want to experience that would fix the problem

I need steps to clarify how to either resolve the issues currently experienced when following the guide for a hybrid implementation or clarification on the recommended approach if the prior suggestion no longer works with the latest version of Angular.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/163567838/74d73af7-ba2f-40b1-9e3c-21358495d940)
![image](https://github.com/angular/angular/assets/163567838/c4296299-7ae7-44cd-8a2c-b5399bdbf6d7)

### If this problem caused an exception or error, please paste it here

```true
(SystemJS) https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/@angular/platform-browser-dynamic/fesm2022/platform-browser-dynamic.mjs: Unexpected token (114:11)
	  112 |         return promise;
	  113 |     }
	> 114 |     static { this.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "17.3.0", ngImport: i0, type: ResourceLoaderImpl, deps: null, target: i0.ɵɵFactoryTarget.Injectable }); }
	      |            ^
	  115 |     static { this.ɵprov = i0.ɵɵngDeclareInjectable({ minVersion: "12.0.0", version: "17.3.0", ngImport: i0, type: ResourceLoaderImpl }); }
	  116 | }
	  117 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "17.3.0", ngImport: i0, type: ResourceLoaderImpl, decorators: [{
	SyntaxError: https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/@angular/platform-browser-dynamic/fesm2022/platform-browser-dynamic.mjs: Unexpected token (114:11)
	  112 |         return promise;
	  113 |     }
	> 114 |     static { this.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "17.3.0", ngImport: i0, type: ResourceLoaderImpl, deps: null, target: i0.ɵɵFactoryTarget.Injectable }); }
	      |            ^
	  115 |     static { this.ɵprov = i0.ɵɵngDeclareInjectable({ minVersion: "12.0.0", version: "17.3.0", ngImport: i0, type: ResourceLoaderImpl }); }
	  116 | }
	  117 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "17.3.0", ngImport: i0, type: ResourceLoaderImpl, decorators: [{
	    at _.raise (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:533149)
	    at aa.unexpected (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:486489)
	    at ga.parseIdentifier (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:531425)
	    at ga.parsePropertyName (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:528873)
	    at ba.parseClassBody (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:499181)
	    at ba.parseClass (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:497736)
	    at ba.parseStatement (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:487659)
	    at ba.parseBlockBody (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:495459)
	    at ba.parseTopLevel (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:486625)
	    at b.parse (https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js:1:485384)
	Error loading https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/node_modules/@angular/platform-browser-dynamic/fesm2022/platform-browser-dynamic.mjs as "@angular/platform-browser-dynamic" from https://angularquickstartv17-15dl--3000--810981ba.local-credentialless.webcontainer.io/main.js
```

### Provide any additional information here in as much as detail as you can

```true
I've created a git hub repository that has the steps performed for upgrading the quickstart repo to the latest version of Angular following the steps in the guide.  This can be used to reproduce the issue.   I also have a Stackblitz that reproduces the issue as well.

https://github.com/Billy-BermanDS/Angular17-Quickstart
https://stackblitz.com/edit/angularquickstartv17
```

**Comment by dylhunn** [comment]
IIRC AngularJS Upgrade is no longer supported as of a couple versions ago (maybe Angular v16?). @alxhub is this correct?

**Comment by Billy-BermanDS** [comment]
Thank you so much for this information.  Can someone on the Angular team update the documentation to indicate the most recent version that is compatible?

**Comment by JeanMeche** [comment]
Angular.io is now in maintenance mode and angular.dev doesn't mention anymore the support of AngularJS with the upgrade package. 

As such, I'll close the issue.
