### ISSUE TITLE
Can't build angular after fresh clone

### ISSUE THREAD

**Issue by matthewdenobrega** [angular/angular#5514]
I cloned the angular repo and went through the steps in the developer docs (https://github.com/angular/angular/blob/master/DEVELOPER.md), but the build is failing:

Steps to reproduce:
 - clone master at https://github.com/angular/angular
 - install dart sdk 1.14.0-dev.1.0
 - install dartium
 - set dart env variables
 - running node 4.2.1
 - running npm 2.14.7
 - npm install - looks good
 - run: node_modules\.bin\gulp build

[22:47:10] 'lint_protos.dart' errored after 74 ms
[22:47:10] Error: Generated Dart protobuf files are out of date. Please run `gulp gen_protos.dart`.
  2b2f5f597ee120bc7e24a9c2e1dbbdd8b7687e0c not found in modules_dart/transform/lib/src/transform/common/model/annotation_model.pb.dart
  6112d707f25d153bd9320aaa2a1125aef5dea41b not found in modules_dart/transform/lib/src/transform/common/model/import_export_model.pb.dart
  a3d7d6b3ccf05c9f46d306c3147aa26de3d4e250 not found in modules_dart/transform/lib/src/transform/common/model/parameter_model.pb.dart
  97d13247500278d3270edea3c874ec53ff47a5c7 not found in modules_dart/transform/lib/src/transform/common/model/ng_deps_model.pb.dart
  d23a644e9a9319d3f52bfc8070b4f39986a18f9f not found in modules_dart/transform/lib/src/transform/common/model/reflection_info_model.pb.dart

    at completeCallback (C:\Users\Generic Name\Documents\GitHub\3rd party\angular\tools\build\proto.js:115:14)
    at C:\Users\Generic Name\Documents\GitHub\3rd party\angular\tools\build\proto.js:32:13
    at C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\hash-files\lib\hash.js:71:4
    at C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\hash-files\node_modules\async\lib\async.js:251:17
    at C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\hash-files\node_modules\async\lib\async.js:200:33
    at C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\hash-files\node_modules\async\lib\async.js:248:21
    at C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\hash-files\node_modules\async\lib\async.js:572:34
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

 - run: node_modules\.bin\gulp gen_protos.dart
Dart SDK detected:
[22:48:32] Using gulpfile ~\Documents\GitHub\3rd party\angular\gulpfile.js
[22:48:32] Starting 'gen_protos.dart'...
[22:48:32] 'gen_protos.dart' errored after 16 ms
[22:48:32] Error: Could not detect protoc - failed to rebuild Dart proto code.
    at Object.module.exports.generate (C:\Users\Generic Name\Documents\GitHub\3rd party\angular\tools\build\proto.js:51:12)
    at Gulp.<anonymous> (C:\Users\Generic Name\Documents\GitHub\3rd party\angular\gulpfile.js:1164:16)
    at module.exports (C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Generic Name\Documents\GitHub\3rd party\angular\node_modules\gulp\bin\gulp.js:129:20
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3

The process in general is very picky about node and npm versions, but with the right versions installed npm installed correctly. But I can't build the project. Machine is running Windows 10.0.10240.

**Comment by matthewdenobrega** [comment]
Happening with dart 1.13.0 as well.

**Comment by shlomiassaf** [comment]
Same here, windows 8.1

**Comment by shlomiassaf** [comment]
This is an issue related to windows and relative paths.

See __Installing NPM Modules and Dart Packages__ in [DEVELOPER.md](https://github.com/shlomiassaf/angular/blob/master/DEVELOPER.md)

To workaround this I used option 2:
Executed 
```
alias nbin='PATH=$(npm bin):$PATH'
```

Then ran `nbin gulp build` or basically `nbin gulp <whatever>`

I used __git Bash__ to run everything, this makes it a bit easier since I avoid conversions from CMD to BASH.
