### ISSUE TITLE
API for ngModule bootstrap for SSR? - `platformServer.bootstrapModule` vs `bootstrapApplication` of `@angular/platform-server`?

### ISSUE THREAD

**Issue by SamuelMarks** [angular/angular#55341]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

Yes

### Description

I've been maintaining a simple scaffold since Angular 4; and just did my first re-generation since Angular 13 and wanted to enable SSR. I don't want or need to use standalone components.

Which means I don't want to use `bootstrapApplication` in **main.server.ts** [attempt below]:
```ts
import { provideServerRendering, platformServer } from "@angular/platform-server"
import { AppModule } from "./app/app.module";

const bootstrap = () => platformServer([provideServerRendering()])
  .bootstrapModule(AppModule);
// bootstrapApplication(AppComponent, config);

export default bootstrap;
```

Which is not what is wanted by the `commonEngine.render` function:
```ts
commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [{ provide: APP_BASE_HREF, useValue: baseUrl }],
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
```

Comparing this to my carefully modified client side code in **main.ts**:
```ts
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";

import { AppModule } from "./app/app.module";

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/SamuelMarks/ng-material-scaffold/tree/3a58e also tried making my component standalone with in this branch https://github.com/SamuelMarks/ng-material-scaffold/tree/ssr-app-module-to-standalone

### Please provide the exception or error you saw

```true
`[provideServerRendering()]`; for the `extraProviders` argument to `platformServer`; gives this error:
> Error:(4, 41) TS2322: Type 'EnvironmentProviders' is not assignable to type 'StaticProvider'.

This fails:

commonEngine
      .render({
        bootstrap,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [{ provide: APP_BASE_HREF, useValue: baseUrl }],
      })


…because rather than an `ApplicationRef` it gets an `NgModuleRef<AppModule>`.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.4
Node: 20.12.2
Package Manager: npm 10.5.2
OS: linux x64

Angular: 17.3.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.4
@angular-devkit/build-angular   17.3.4
@angular-devkit/core            17.3.4
@angular-devkit/schematics      17.3.4
@angular/flex-layout            15.0.0-beta.42
@schematics/angular             17.3.4
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

### Anything else?

PS: `platformServerDynamic().bootstrapModule()` is what this old Medium article recommends - https://medium.com/@stream2085/server-side-rendering-ssr-with-angular-41daa76ec72a - but that doesn't seem to be available anymore.

**Comment by alan-agius4** [comment]
In the case of an NGModule based application the `bootstrap` property should be set to the server application NgModule.

See: https://angular.io/guide/ssr#configure-server-side-rendering

Worth mentioning that the highlighted article is rather updated.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by SamuelMarks** [comment]
```
$ ng build
⠙ Building...
ERROR Error [NullInjectorError]: R3InjectorError[i -> i]: 
  NullInjectorError: No provider for i!
    at xr.get (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-XZDAVMYQ.mjs:8:1131)
    at ln.get (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-XZDAVMYQ.mjs:8:10704)
    at ln.get (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-XZDAVMYQ.mjs:8:10704)
    at ds.get (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-XZDAVMYQ.mjs:34:10359)
    at wl (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-XZDAVMYQ.mjs:8:22403)
    at El (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-XZDAVMYQ.mjs:8:22637)
    at X (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-XZDAVMYQ.mjs:8:44759)
    at i.ɵfac [as factory] (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-AQQEVEE4.mjs:3:425)
    at it (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-XZDAVMYQ.mjs:8:23825)
    at fy (.angular/prerender-root/5bf47949-e5e9-482b-8f5b-0027d1e3ff31/chunk-XZDAVMYQ.mjs:8:50986) {
  ngTempTokenPath: null,
  ngTokenPath: [ 'i', 'i' ]
An unhandled exception occurred: R3InjectorError[i -> i]: 
  NullInjectorError: No provider for i!
See "/tmp/ng-DTDdZb/angular-errors.log" for further details.
```
