### ISSUE TITLE
ESBuild not calling any http request in server side

### ISSUE THREAD

**Issue by alisafariir** [angular/angular#55440]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When I use an http request on the page, the request is not executed on the server side and the HTML content is without the request content.

This problem does not exist in webpack and according to the checks I made, it happens when the project builder is on esbuild
I have created a repository for this problem at the address below:
[Repo](https://github.com/alisafariir/angular-esbuild-http-ssr-issue)

If you run the project, you will notice that the value of No SSR is rendered in the view page source.
But on the user side (inspect element) API is called and displays the correct value.
This hypothesis proves that when creating a page with SSR, the API is not called on the server side.
There is also the following error in the console (exception section)

Considering that I put a version with http on the server, but there is still a problem

### Please provide a link to a minimal reproduction of the bug

https://github.com/alisafariir/angular-esbuild-http-ssr-issue

### Please provide the exception or error you saw

```true
ERROR HttpErrorResponse {
  headers: _HttpHeaders {
    normalizedNames: Map(0) {},
    lazyUpdate: null,
    headers: Map(0) {}
  },
  status: 0,
  statusText: 'Unknown Error',
  url: 'https://jsonplaceholder.typicode.com/todos/1',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for https://jsonplaceholder.typicode.com/todos/1: 0 undefined',
  error: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11730:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    cause: Error: unable to verify the first certificate
        at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
        at _ZoneDelegate.invokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:403:31)
        at eval (c:/Users/a.safari/Desktop/angular-app/node_modules/@angular/core/fesm2022/core.mjs:14556:55)
        at AsyncStackTaggingZoneSpec.onInvokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/@angular/core/fesm2022/core.mjs:14556:36)
        at _ZoneDelegate.invokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:402:36)
        at Object.onInvokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/@angular/core/fesm2022/core.mjs:14869:33)
        at _ZoneDelegate.invokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:402:36)
        at _Zone.runTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:174:47)
        at invokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:484:34)
        at TLSSocket.ZoneTask.invoke (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:473:48) {
      code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
    }
  }
}
ERROR HttpErrorResponse {
  headers: _HttpHeaders {
    normalizedNames: Map(0) {},
    lazyUpdate: null,
    headers: Map(0) {}
  },
  status: 0,
  statusText: 'Unknown Error',
  url: 'https://jsonplaceholder.typicode.com/todos/1',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for https://jsonplaceholder.typicode.com/todos/1: 0 undefined',
  error: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11730:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    cause: Error: unable to verify the first certificate
        at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
        at _ZoneDelegate.invokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:403:31)
        at eval (c:/Users/a.safari/Desktop/angular-app/node_modules/@angular/core/fesm2022/core.mjs:14556:55)
        at AsyncStackTaggingZoneSpec.onInvokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/@angular/core/fesm2022/core.mjs:14556:36)
        at _ZoneDelegate.invokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:402:36)
        at Object.onInvokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/@angular/core/fesm2022/core.mjs:14869:33)
        at _ZoneDelegate.invokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:402:36)
        at _Zone.runTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:174:47)
        at invokeTask (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:484:34)
        at TLSSocket.ZoneTask.invoke (c:/Users/a.safari/Desktop/angular-app/node_modules/zone.js/fesm2015/zone-node.js:473:48) {
      code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
    }
  }
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.5
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.3.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
As you can see in the error log, there is a certificate issue. This is not related to angular itself. 

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
