### ISSUE TITLE
@for and ngFor reporting errors but still iterating over data

### ISSUE THREAD

**Issue by metalised** [angular/angular#55601]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When using @for or ngFor on an array returned from an HTTPClient request errors are being report but the data is still iterated over and the page rendered as expected.

@for reports newCollection[Symbol.iterator] is not a function
ngFor reports NG02200: Cannot find a differ supporting object '[object Object]' of type 'object'.

If I return the a hard-coded array of the same data from the service it does not report any errors, only with data returned from the API call.
Dumping the data to the page using the JSON pipe shows the expected array, as does logging to console.

### Please provide the exception or error you saw

```true
@for
main.ts:11 ERROR TypeError: newCollection[Symbol.iterator] is not a function
    at reconcile (core.mjs:22563:69)
    at Module.ɵɵrepeater (core.mjs:22925:9)
    at PortfolioBarComponent_Template (portfolio.component.html:5:13)
    at executeTemplate (core.mjs:11268:9)
    at refreshView (core.mjs:12791:13)
    at detectChangesInView$1 (core.mjs:13015:9)
    at detectChangesInViewIfAttached (core.mjs:12978:5)
    at detectChangesInComponent (core.mjs:12967:5)
    at detectChangesInChildComponents (core.mjs:13028:9)
    at refreshView (core.mjs:12841:13)

ngFor
main.ts:11 ERROR Error: NG02200: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables, such as Arrays. Did you mean to use the keyvalue pipe? Find more at https://angular.io/errors/NG02200
    at NgForOf.ngDoCheck (common.mjs:3150:31)
    at callHookInternal (core.mjs:5136:14)
    at callHook (core.mjs:5167:9)
    at callHooks (core.mjs:5118:17)
    at executeInitAndCheckHooks (core.mjs:5068:9)
    at refreshView (core.mjs:12806:21)
    at detectChangesInView$1 (core.mjs:13015:9)
    at detectChangesInViewIfAttached (core.mjs:12978:5)
    at detectChangesInComponent (core.mjs:12967:5)
    at detectChangesInChildComponents (core.mjs:13028:9)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.6
Node: 18.13.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 17.3.6
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
```

**Comment by JeanMeche** [comment]
Hi, I'm not sure what the issue is. You're not handling an error, what would you expect ?

**Comment by alxhub** [comment]
We will definitely need a reproduction in Stackblitz in order to investigate further. I suspect whatever data library you're using is returning an object that isn't actually an `Array` (maybe a proxy?) `[Symbol.iterator]` should definitely be a function for any collection that `@for` supports.

**Comment by metalised** [comment]
I'll see whether I can put one together. As noted it only seems to happen when using the response from the API.
Checking all the points through the code (browser debug console, console logging & dumping the JSON) shows it as an array.
The API endpoint is written in nest.js, so is also typescript based. I've hard-coded the data in the API to be an array to make sure that's what was being returned, but it still fails.

**Comment by metalised** [comment]
@alxhub Based on your comment about a proxy I changed the code to use the API directly and it works. Seems to be something in how I've implemented ngrx/store which is causing the error.

Once I've found the problem I'll add a comment here in case anyone else comes across the same thing.

Thanks for the help.

**Comment by metalised** [comment]
The issue was down to a typo in the definition of the initial state object.

Instead of "array: <Type[]>[];" it was "array: <Type[]>{};" so the initial value in the store was not an array type., causing the error.
