### ISSUE TITLE
Help me - could not resolve module angular/node_modules/mermaid/dist/mermaid.js

### ISSUE THREAD

**Issue by fendypurnomo** [angular/angular#55657]
### Describe the problem that you experienced
```
Administrator@DESKTOP-19BVUE8 MINGW64 /d/Applications/docs/angular.io
$ yarn run docs
yarn run v1.22.19

warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ [[ -n $CI ]] && echo 'Cannot run this yarn script on CI' && exit 1 || yarn bazel run //adev:serve --fast_adev
'[[' is not recognized as an internal or external command,
operable program or batch file.

warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ D:\Applications\docs\angular.io\node_modules\.bin\bazel run //adev:serve --fast_adev    
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
INFO: Analyzed target //adev:serve (1384 packages loaded, 84466 targets configured).      
INFO: Found 1 target...
INFO: From Bundling JavaScript packages/core/primitives/event-dispatch/contract_bundle.js 
[rollup]:

bazel-out/x64_windows-fastbuild-ST-2e5f3376adb5/bin/packages/core/primitives/event-dispatch/contract_binary.mjs ΓåÆ bazel-out/x64_windows-fastbuild-ST-2e5f3376adb5/bin/packages/core/primitives/event-dispatch/contract_bundle.js...
created bazel-out/x64_windows-fastbuild-ST-2e5f3376adb5/bin/packages/core/primitives/event-dispatch/contract_bundle.js in 1.1s

ERROR: D:/applications/docs/angular.io/adev/src/content/guide/components/BUILD.bazel:3:16: Action adev/src/content/guide/components/advanced-configuration.md.html failed: (Exit 1): markdown.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat ... (remaining 2 arguments skipped)      
Error: could not resolve module angular/node_modules/mermaid/dist/mermaid.js
Please report this to https://github.com/markedjs/marked.
    at Runfiles.resolve (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48611:19)
    at Runfiles.resolveWorkspaceRelative (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48620:21)   
    at getMermaidScriptTagData (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48699:36)
    at Object.processMermaidCodeBlock (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48712:29)      
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:447:9)
    at async Promise.all (index 265)
    at main (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:52239:31)

ERROR: D:/applications/docs/angular.io/adev/src/content/introduction/essentials/BUILD.bazel:3:16: Action adev/src/content/introduction/essentials/components.md.html failed: (Exit 1): markdown.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat bazel-out/x64_windows-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params ... (remaining 1 argument skipped)
Error: could not resolve module angular/node_modules/mermaid/dist/mermaid.js
Please report this to https://github.com/markedjs/marked.
    at Runfiles.resolve (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48611:19)
    at Runfiles.resolveWorkspaceRelative (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48620:21)   
    at getMermaidScriptTagData (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48699:36)
    at Object.processMermaidCodeBlock (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48712:29)      
    at async Promise.all (index 7)
    at main (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:52239:31)
Target //adev:serve failed to build    
Use --verbose_failures to see the command lines of failed build steps.

ERROR: D:/applications/docs/angular.io/adev/src/assets/BUILD.bazel:5:18 Copying files to directory failed: (Exit 1): markdown.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat bazel-out/x64_windows-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params 
... (remaining 1 argument skipped)

INFO: Elapsed time: 1630.401s, Critical Path: 344.29s
INFO: 725 processes: 50 internal, 426 local, 249 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.      
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JeanMeche** [comment]
Hi, can you check if mermaid is present in your `node_modules` ?

**Comment by fendypurnomo** [comment]
I have check mermaid deps and mermaid deps already in node_modules

**Comment by alan-agius4** [comment]
I suspect that https://github.com/angular/dev-infra/pull/2047 should fix it.

**Comment by alan-agius4** [comment]
Can you please verify if the problem is solved?

**Comment by fendypurnomo** [comment]
I'm still got error like this:

Administrator@DESKTOP-19BVUE8 MINGW64 /d/applications/docs/angular.io (main)
$ yarn docs
yarn run v1.22.19
$ [[ -n $CI ]] && echo 'Cannot run this yarn script on CI' && exit 1 || yarn bazel run //adev:serve --fast_adev
'[[' is not recognized as an internal or external command,
operable program or batch file.
$ D:\applications\docs\angular.io\node_modules\.bin\bazel run //adev:serve --fast_adev
2024/05/04 10:00:08 Downloading https://releases.bazel.build/5.0.0/release/bazel-5.0.0-windows-x86_64.exe...
Downloading: 44 MB out of 44 MB (100%)
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...

INFO: Analyzed target //adev:serve (1319 packages loaded, 82781 targets configured).
INFO: Found 1 target...

ERROR: D:/applications/docs/angular.io/adev/src/content/introduction/essentials/BUILD.bazel:3:16: Action adev/src/content/introduction/essentials/components.md.html failed: (Exit 1): markdown.
bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat bazel-out/x64_windows-fastbuild/bin/adev/src/content/introducti
on/essentials/components.md.html-0.params ... (remaining 1 argument skipped)
Error: could not resolve module angular/node_modules/mermaid/dist/mermaid.js
Please report this to https://github.com/markedjs/marked.
    at Runfiles.resolve (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48611:19)
    at Runfiles.resolveWorkspaceRelative (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48620:21)
    at getMermaidScriptTagData (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48699:36)
    at Object.processMermaidCodeBlock (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48712:29)
    at async Promise.all (index 7)
    at main (file:///D:/programs/vcs/git/cmd/_bazel_administrator/qjhjlh55/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:52240:31)
Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.

ERROR: D:/applications/docs/angular.io/adev/src/assets/BUILD.bazel:5:18 Copying files to directory failed: (Exit 1): markdown.bat failed: error executing command bazel-out\x64_windows-opt-exec
-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat bazel-out/x64_windows-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params ... (remaining 1 argumen
t skipped)

INFO: Elapsed time: 752.304s, Critical Path: 126.63s
INFO: 477 processes: 358 internal, 119 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by fendypurnomo** [comment]
I'am using windows 10 and git bash to build angular docs from repo
