### ISSUE TITLE
is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by fendypurnomo** [angular/angular#55856]
### Describe the problem that you experienced

D:\Applications\docs\angular.io\angular>yarn docs
yarn run v1.22.19
$ [[ -n $CI ]] && echo 'Cannot run this yarn script on CI' && exit 1 || yarn bazel run //adev:serve --fast_adev
'[[' is not recognized as an internal or external command,
operable program or batch file.
$ D:\Applications\docs\angular.io\angular\node_modules\.bin\bazel run //adev:serve --fast_adev
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //adev:serve (1319 packages loaded, 82779 targets configured).
INFO: Found 1 target...
ERROR: D:/applications/docs/angular.io/angular/adev/src/content/tutorials/homepage/BUILD.bazel:12:20: Action adev/src/content/tutorials/homepage/homepage failed: (Exit 1): playground.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\playground.bat adev/src/content/tutorials/homepage external/npm/@angular/docs/pipeline/tutorials/common ... (remaining 2 arguments skipped)
'""' is not recognized as an internal or external command,
operable program or batch file.
ERROR: D:/applications/docs/angular.io/angular/adev/src/content/tutorials/playground/BUILD.bazel:10:20: Action adev/src/content/tutorials/playground/playground failed: (Exit 1): playground.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\playground.bat adev/src/content/tutorials/playground external/npm/@angular/docs/pipeline/tutorials/common ... (remaining 2 arguments skipped)
'""' is not recognized as an internal or external command,
operable program or batch file.
ERROR: D:/applications/docs/angular.io/angular/adev/src/content/tutorials/first-app/BUILD.bazel:21:18: Action adev/src/content/tutorials/first-app/first-app failed: (Exit 1): tutorial.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\tutorial.bat adev/src/content/tutorials/first-app external/npm/@angular/docs/pipeline/tutorials/common ... (remaining 2 arguments skipped)
'""' is not recognized as an internal or external command,
operable program or batch file.
ERROR: D:/applications/docs/angular.io/angular/packages/platform-server/init/BUILD.bazel:20:8: Bundling Javascript ../npm/node_modules/domino/lib/index.js [esbuild] failed: (Exit 1): _bundled_domino_esbuild_launcher.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6-ST-2e5f3376adb5\bin\packages\platform-server\init\_bundled_domino_esbuild_launcher.bat ... (remaining 3 arguments skipped)
'""' is not recognized as an internal or external command,
operable program or batch file.
Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1020.285s, Critical Path: 1.58s
INFO: 1396 processes: 1112 internal, 284 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Describe what you were looking for in the documentation

I'm cloning angular repo and i want to serve locally, but when i run command "yarn docs", i got an error

**Comment by JeanMeche** [comment]
In which kind of command line are you running the script ?

**Comment by fendypurnomo** [comment]
I am running command line in the command propmt as administrator, windows 10

**Comment by JeanMeche** [comment]
You need to run this script in a bash compatible command line.

**Comment by fendypurnomo** [comment]
Which kind a bash compatible with there script?

**Comment by JeanMeche** [comment]
WSL will work for sure.

**Comment by fendypurnomo** [comment]
I tried using `git bash` to build `angular docs`, but I got this error:

```
Administrator@Acer-4739 MINGW64 /d/applications/docs/angular.io/angular (main)
$ yarn docs
yarn run v1.22.19
$ [[ -n $CI ]] && echo 'Cannot run this yarn script on CI' && exit 1 || yarn bazel run //adev:serve --fast_adev
'[[' is not recognized as an internal or external command,
operable program or batch file.
$ D:\applications\docs\angular.io\angular\node_modules\.bin\bazel run //adev:serve --fast_adev
INFO: Analyzed target //adev:serve (1 packages loaded, 2635 targets configured).
INFO: Found 1 target...
ERROR: D:/applications/docs/angular.io/angular/adev/src/content/introduction/essentials/BUILD.bazel:3:16: Action adev/src/content/introduction/essentials/components.md.html failed: (Exit 1): markdown.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat bazel-out/x64_windows-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params ... (remaining 1 argument skipped)
Error: could not resolve module angular/node_modules/mermaid/dist/mermaid.js
Please report this to https://github.com/markedjs/marked.
    at Runfiles.resolve (file:///D:/programs/vcs/git/cmd/_bazel_administrator/j2fjd65f/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48611:19)
    at Runfiles.resolveWorkspaceRelative (file:///D:/programs/vcs/git/cmd/_bazel_administrator/j2fjd65f/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48620:21)
    at getMermaidScriptTagData (file:///D:/programs/vcs/git/cmd/_bazel_administrator/j2fjd65f/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48699:36)
    at Object.processMermaidCodeBlock (file:///D:/programs/vcs/git/cmd/_bazel_administrator/j2fjd65f/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48712:29)
    at async Promise.all (index 7)
    at main (file:///D:/programs/vcs/git/cmd/_bazel_administrator/j2fjd65f/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:52240:31)
Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: D:/applications/docs/angular.io/angular/adev/src/assets/BUILD.bazel:5:18 Copying files to directory failed: (Exit 1): markdown.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm\@angular\docs\pipeline\markdown.bat bazel-out/x64_windows-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params ... (remaining 1 argument skipped)
INFO: Elapsed time: 631.634s, Critical Path: 145.90s
INFO: 157 processes: 5 internal, 151 local, 1 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JeanMeche** [comment]
Following up from what you mentioned in #55877, could you try to run that command with `bash` or `zsh`shell  instead of just `sh` ?

**Comment by fendypurnomo** [comment]
```
ERROR: /home/ubuntu/angular/adev/src/content/introduction/essentials/BUILD.bazel:3:16: Action adev/src/content/introduction/essentials/components.md.html failed: (Exit 1): markdown.sh failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh bazel-out/k8-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox

/home/ubuntu/.cache/bazel/_bazel_ubuntu/d3c6983be73d8c916ce88d5800bb1c6f/sandbox/processwrapper-sandbox/8/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:48704
  const browser = await chromium.launch({
                                 ^
browserType.launch: Target page, context or browser has been closed
```
