### ISSUE TITLE
withEventReplay breaks the build

### ISSUE THREAD

**Issue by geromegrignon** [angular/angular#56122]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

The new `withEventReplay` developer preview feature breaks the application upon usage.

Using both`ng serve` and `ng build` results in the following error.

Reproduced on a brand new Angular v18 project by just adding `withEventReplay()`as a parameter of `provideClientHydration`

### Please provide a link to a minimal reproduction of the bug

https://github.com/geromegrignon/with-event-replay

### Please provide the exception or error you saw

```true
10:16:51 AM [vite] Internal server error: Cannot read properties of null (reading 'type')
      at setJSActionAttribute (/Users/gerome/Documents/workspace/oneshots/with-event-replay/node_modules/@angular/core/fesm2022/core.mjs:36686:15)
      at serializeLView (/Users/gerome/Documents/workspace/oneshots/with-event-replay/node_modules/@angular/core/fesm2022/core.mjs:36972:13)
      at annotateHostElementForHydration (/Users/gerome/Documents/workspace/oneshots/with-event-replay/node_modules/@angular/core/fesm2022/core.mjs:37174:21)
      at annotateComponentLViewForHydration (/Users/gerome/Documents/workspace/oneshots/with-event-replay/node_modules/@angular/core/fesm2022/core.mjs:36776:16)
      at annotateForHydration (/Users/gerome/Documents/workspace/oneshots/with-event-replay/node_modules/@angular/core/fesm2022/core.mjs:36841:17)
      at prepareForHydration (/Users/gerome/Documents/workspace/oneshots/with-event-replay/node_modules/@angular/platform-server/fesm2022/platform-server.mjs:16982:34)
      at eval (/Users/gerome/Documents/workspace/oneshots/with-event-replay/node_modules/@angular/platform-server/fesm2022/platform-server.mjs:17042:3)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/gerome/Documents/workspace/oneshots/with-event-replay/.angular/vite-root/with-event-replay/chunk-QDHZVCWX.mjs:50:24)
      at _ZoneDelegate.invoke (/Users/gerome/Documents/workspace/oneshots/with-event-replay/node_modules/zone.js/fesm2015/zone-node.js:365:28)
```
```


### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.1
Node: 20.12.2
Package Manager: npm 10.3.0
OS: darwin arm64

Angular: 18.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.1
@angular-devkit/build-angular   18.0.1
@angular-devkit/core            18.0.1
@angular-devkit/schematics      18.0.1
@angular/cli                    18.0.1
@angular/ssr                    18.0.1
@schematics/angular             18.0.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by pkozlowski-opensource** [comment]
I believe that this is a duplicate of #56073 which was already fixed via https://github.com/angular/angular/pull/56076 but not released yet (will be part of the next patch release this Wednesday).

**Comment by geromegrignon** [comment]
Thanks @pkozlowski-opensource, closing it.
