### ISSUE TITLE
Add a way to receive old value when a signal changes

### ISSUE THREAD

**Issue by bellostom** [angular/angular#56186]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Hi

Long time react/mobx dev, me and the team are looking into moving to Angular.
Our timing seems to be ideal, with the launch of signals, which seem promising.

Coming from MobX which is awesome, signals share several similarities. 
We would like to use signals for a lightweight state management, however the API is limited
For example, there is no way for someone to "observe" a signal and once it changes, to have access to the previous value within the callback.
A similar request was added here for computed.
https://github.com/angular/angular/issues/54339

I would really like to see something like signal.subscribe(previousValue => {}) in order to avoid any issues or concerns as dicussed in the computed thread

 Inspired by MobX's reaction (which can track multiple observables) 
https://mobx.js.org/reactions.html#reaction

### Proposed solution

Introduce a subscription method to signals where the previous value is available. 
The subscription should return a disposer function, to stop the unsubscription 

### Alternatives considered

Currently we have added our own workaround, but it has its own limitations, since you need to always pass the same object that wraps the signal in order to function correctly. 

`
export class SubscriptableSignal<T>{
    private subscribers: ISubscribers<T> = {};
    protected model: WritableSignal<T>;
    public signal: Signal<T>;

    constructor(model: T) {
        this.model = signal<T>(model);
        this.signal = this.model.asReadonly();
    }

    /**
     * Subscribe to the model to be notified each time a change is made
     * @param fn
     */
    subscribe(fn: subscriber<T>){
        const uniqueId = `${Date.now()}-${Math.random()}`;
        this.subscribers[uniqueId] = fn;
        return this.disposerCallback(uniqueId);
    }

    /**
     * Return a function that cancels the subscription
     * @param subscription
     * @protected
     */
    protected disposerCallback(subscription: string){
        return () => {
            this.unSubscribe(subscription);
        }
    }

    /**
     * Removes subscription
     * @param uniqueId
     */
    protected unSubscribe(uniqueId: string){
        delete this.subscribers[uniqueId];
    }

    /**
     * Inform subscribers of model change
     * Subscribers receive previous and current value
     * @param previousValue
     * @param currentValue
     * @protected
     */
    protected informSubscribers(previousValue: T, currentValue: T){
        Object.values(this.subscribers).forEach(fn => {
            fn(previousValue, currentValue);
        });
    }

    /**
     * Wrap signal's update and after the update is done, notify subscribers
     * @param fn
     */
    update(fn: (value: T) => T){
        const previousValue = this.model();
        this.model.update(fn);
        this.informSubscribers(previousValue, this.model());
    }
}`

**Comment by eneajaho** [comment]
Hi, to overcome this issue I created an utility

```ts
import { computed, untracked, type Signal } from '@angular/core';

/**
 * Returns a signal that emits the previous value of the given signal.
 * The first time the signal is emitted, the previous value will be the same as the current value.
 *
 * @example
 * ```ts
 * const value = signal(0);
 * const previous = computedPrevious(value);
 *
 * effect(() => {
 *  console.log('Current value:', value());
 *  console.log('Previous value:', previous());
 * });
 *
 * Logs:
 * // Current value: 0
 * // Previous value: 0
 *
 * value.set(1);
 *
 * Logs:
 * // Current value: 1
 * // Previous value: 0
 *
 * value.set(2);
 *
 * Logs:
 * // Current value: 2
 * // Previous value: 1
 *```
 *
 * @param s Signal to compute previous value for
 * @returns Signal that emits previous value of `s`
 */
export function computedPrevious<T>(s: Signal<T>): Signal<T> {
	let current = null as T;
	let previous = untracked(() => s()); // initial value is the current value

	return computed(() => {
		current = s();
		const result = previous;
		previous = current;
		return result;
	});
}
```

It's published here: 
https://ngxtension.netlify.app/utilities/signals/computed-previous/

**Comment by pkozlowski-opensource** [comment]
Thnx for sharing your experience here @bellostom - this is good timing as we are looking into stabilizing the effects API. 

We still need to dig deeper into reports we've got for effects but the API similar to MobX's [reaction](https://mobx.js.org/reactions.html#reaction) sounds interesting. 

At the same time I don't think we want to introduce something akin to the prosed `subscribe` API on a signal for a couple of reasons:
* we really believe that the access to signals should be auto-tracked instead of explicitly subscribing;
* having the `subscribe` method would raise the question of the timing for it to fire and this can be extremely subtle;
* this would be code that can't be tree-shaken and increasing bundle size for people that don't want to use it.

**Comment by pkozlowski-opensource** [comment]
> having the subscribe method would raise the question of the timing for it to fire and this can be extremely subtle;

To be more precise here: we very much do _not_ want to provide a callback when a signal is set / updated as this would allow people to observe inconsistent state of the reactive graph (notification firing when more signals are about to be changed).

**Comment by bellostom** [comment]
> Thnx for sharing your experience here @bellostom - this is good timing as we are looking into stabilizing the effects API.
> 
> We still need to dig deeper into reports we've got for effects but the API similar to MobX's [reaction](https://mobx.js.org/reactions.html#reaction) sounds interesting.
> 
> At the same time I don't think we want to introduce something akin to the prosed `subscribe` API on a signal for a couple of reasons:
> 
> * we really believe that the access to signals should be auto-tracked instead of explicitly subscribing;
> * having the `subscribe` method would raise the question of the timing for it to fire and this can be extremely subtle;
> * this would be code that can't be tree-shaken and increasing bundle size for people that don't want to use it.

Hi
The subscription approach was just an idea. An approach similar to mobx reaction will do just fine.
It is nice that you consider it as an enhancement 
Keep it up!

**Comment by sysmat** [comment]
ng 18.1.0 & ngxtension:4.0.0 throw error: 

```
Error: NG0950: Input is required but no value is available yet. Find more at https://angular.dev/errors/NG0950
    at inputValueFn (core.mjs:96:13)
    at ngxtension-computed-previous.mjs:39:34
    at untracked (core.mjs:37064:12)
    at computedPrevious (ngxtension-computed-previous.mjs:39:18)
```

**Comment by alxhub** [comment]
I'm going to consider this as closed by `linkedSignal`, which _does_ provide an API for processing previous values during computations.
