### ISSUE TITLE
Angular Devtools throw errors due to unsafe property accesses

### ISSUE THREAD

**Issue by mwaibel-go** [angular/angular#56755]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

[stackblitz](https://stackblitz.com/edit/stackblitz-starters-eanrmy?file=src%2Fmain.ts)

Consider this accessor in a directive:

```ts
  foo: { bar: number } | undefined;

  get bar(): number {
    return this.foo!.bar;
  }
```

Before accessing the getter myself, I can make sure that `foo` is actually defined. The devtools don’t do that and try to access the `bar` property of the undefined `foo` when evaluating the `bar` accessor.

This prevents any debugging info about the selected component from rendering. (Note: the inspector panel still shows ‘No selected Element’, even though I did select the app-root, resulting in the error.)

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

At the very least, reading getters should happen in a try…catch block, so the error is caught. It is expected (in the example application) that `bar` cannot be accessed ‘blindly’, i.e. without prior checks.

I find that the devtools should not invoke getters at all automatically, since that may trigger unintended side-effects. I propose that getters only get evaluated upon demand, like the Chrome devtools do:

![image](https://github.com/angular/angular/assets/92570274/6eeccecf-5cbe-4bc5-855a-02af4a4837ff)

### Please provide a screenshot if possible [Bug Report only]

![image](https://github.com/angular/angular/assets/92570274/29513eae-3442-481c-86ae-509a48c24c4b)

### Please provide the exception or error you saw [Bug Report only]

```true
Uncaught TypeError: Cannot read properties of undefined (reading 'bar')
    at get bar (main.ts:14:22)
    at ft (state-serializer.ts:85:32)
    at state-serializer.ts:115:20
    at Array.forEach (<anonymous>)
    at ut (state-serializer.ts:111:18)
    at c (component-tree.ts:131:16)
    at kn (component-tree.ts:149:5)
    at client-event-subscribers.ts:148:19
    at n (same-page-message-bus.ts:46:21)
    at _ZoneDelegate.invokeTask (zone__js.js?v=4bf4bc0c:326:171)
```

**Comment by JeanMeche** [comment]
Noticed this is still an issue.
