### ISSUE TITLE
18.1.0.: "Class extends value undefined is not a constructor or null"

### ISSUE THREAD

**Issue by niwolf** [angular/angular#56949]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After updating to version 18.1.0. I am getting the following error on `ng-serve`: 
```
Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
Re-optimizing dependencies because lockfile has changed
  ➜  Local:   http://localhost:4200/
  ➜  press h + enter to show help
Re-optimizing dependencies because lockfile has changed
15:17:17 [vite] Error when evaluating SSR module /@fs/{pathToRepo}/.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js?v=de27081b:
|- TypeError: Class extends value undefined is not a constructor or null
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (/{pathToRepo}/.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5662:36)
```

### Please provide a link to a minimal reproduction of the bug

-

### Please provide the exception or error you saw

```true
15:17:17 [vite] Error when evaluating SSR module /@fs/{pathToRepo}/.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js?v=de27081b:
|- TypeError: Class extends value undefined is not a constructor or null
    at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (/{pathToRepo}/.angular/cache/18.1.0/vite/deps_ssr/@angular_fire_firestore.js:5662:36)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.0
Node: 18.20.2
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 18.1.0
... animations, build, cdk, cli, common, compiler, compiler-cli
... core, forms, material, platform-browser
... platform-browser-dynamic, platform-server, router, ssr

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1801.0
@angular-devkit/core         18.1.0
@angular-devkit/schematics   18.1.0
@angular/fire                18.0.1
@schematics/angular          18.1.0
rxjs                         7.8.1
typescript                   5.4.5
zone.js                      0.14.7
```

**Comment by thePunderWoman** [comment]
@niwolf Can you provide a minimal reproduction for us? Otherwise there's nothing actionable here for us to look into.
