### ISSUE TITLE
Problem adding firebase

### ISSUE THREAD

**Issue by Ken-Wainwright** [angular/angular#57040]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

I have a problem. I have setup a new web app project in Visual Code and did not change any code at all. Everything works fine. then I add @angular/fire and the first error I got was No overload matches this call.
Overload 1 of 3, '(options: FirebaseOptions, name?: string | undefined): FirebaseApp', gave the following error.
Object literal may only specify known properties, and '"locationId"' does not exist in type 'FirebaseOptions'.
Overload 2 of 3, '(options: FirebaseOptions, config?: FirebaseAppSettings | undefined): FirebaseApp', gave the following error.
Object literal may only specify known properties, and '"locationId"' does not exist in type 'FirebaseOptions'. [plugin angular-compiler]

I commented out the locationID line but then I got 0:48:08 [vite] Error when evaluating SSR module /@fs/C:/Users/HP ProDesk i5/angularWorkspace/web-app/.angular/cache/18.1.1/vite/deps_ssr/chunk-UEELBQ5E.js?v=9fb4ba3a:
|- TypeError: Class extends value undefined is not a constructor or null
at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (eval
at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :5603:36)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)
at node_modules/@firebase/auth/node_modules/undici/lib/fetch/formdata.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :5795:9)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)
at node_modules/@firebase/auth/node_modules/undici/lib/fetch/body.js (eval
at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :5971:9)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)
at node_modules/@firebase/auth/node_modules/undici/lib/fetch/response.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :13858:9)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)
at node_modules/@firebase/auth/node_modules/undici/index.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :19773:33)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)

10:48:08 [vite] Error when evaluating SSR module /@fs/C:/Users/HP ProDesk i5/angularWorkspace/web-app/.angular/cache/18.1.1/vite/deps_ssr/@angular_fire_firestore.js?v=9fb4ba3a:
|- TypeError: Class extends value undefined is not a constructor or null
at node_modules/@firebase/auth/node_modules/undici/lib/fetch/file.js (eval
at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :5603:36)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)
at node_modules/@firebase/auth/node_modules/undici/lib/fetch/formdata.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :5795:9)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)
at node_modules/@firebase/auth/node_modules/undici/lib/fetch/body.js (eval
at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :5971:9)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)
at node_modules/@firebase/auth/node_modules/undici/lib/fetch/response.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :13858:9)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)
at node_modules/@firebase/auth/node_modules/undici/index.js (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :19773:33)
at __require2 (eval at instantiateModule (file:///C:/Users/HP%20ProDesk%20i5/angularWorkspace/web-app/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:53441:24), :53:50)

I I decided to check things out and the app runs fine if I comment out
//provideFirestore(() => getFirestore()),
//provideStorage(() => getStorage()),

### Please provide the expected behavior vs the actual behavior you encountered [Bug Report only]

![Screenshot 2024-07-18 113005](https://github.com/user-attachments/assets/6b0b6963-7f78-41a8-b583-237e4147f008)

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
