### ISSUE TITLE
docs-infra: Can't serve locally adev 

### ISSUE THREAD

**Issue by vladboisa** [angular/angular#57117]
### Describe the problem that you experienced

When i start to serve locally the [Angular repo](https://github.com/angular/angular/tree/main/adev), see the error

### Enter the URL of the topic with the problem

https://github.com/angular/angular/tree/main/adev

### Describe the actions that led you to experience the problem

Clone the angular repo, start locally in WSL1 Ubuntu bash, and see the error

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/433d5e7b-db90-4a6b-bb0c-25882c5d6456)
![image](https://github.com/user-attachments/assets/7bab9df2-9207-4b38-a271-bca17ef562d5)

### If this problem caused an exception or error, please paste it here

```true
INFO: Analyzed target //adev:serve (1408 packages loaded, 88024 targets configured).
INFO: Found 1 target...
INFO: From Action adev/src/content/cli/help/cli_docs_html:
Could not find the language 'jsonc', did you forget to load/include a language module?
ERROR: /mnt/m/Polka/angular/adev/src/content/guide/di/BUILD.bazel:3:16: Action adev/src/content/guide/di/creating-injectable-service.md.html failed: (Exit 1): markdown.sh failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh bazel-out/k8-fastbuild/bin/adev/src/content/guide/di/creating-injectable-service.md.html-0.params ... (remaining 1 argument skipped)
`
Use --sandbox_debug to see verbose messages from the sandbox

/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1320/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:49691
  const browser = await chromium.launch({
                                 ^
browserType.launch: Target page, context or browser has been closed

Browser logs:

<launching> /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1320/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-UQO2K2 --remote-debugging-pipe --no-startup-window
<launched> pid=23351
[pid=23351][err] /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1320/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
[pid=23351] <process did exit: exitCode=127, signal=null>
[pid=23351] starting temporary directories cleanup`

Call log:
  <launching> /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1320/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-UQO2K2 --remote-debugging-pipe --no-startup-window
 
<launched> pid=23351
  `[pid=23351][err] /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1320/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
  [pid=23351] <process did exit: exitCode=127, signal=null>
  [pid=23351] starting temporary directories cleanup
    at Object.processMermaidCodeBlock (/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1320/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:49691:34)
    at Marked.walkTokens2 (/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1320/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:53186:84)
    at main (/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1320/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:53227:31)
Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /mnt/m/Polka/angular/adev/src/assets/BUILD.bazel:5:18 Copying files to directory failed: (Exit 1): markdown.sh failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh bazel-out/k8-fastbuild/bin/adev/src/content/guide/di/creating-injectable-service.md.html-0.params ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 618.369s, Critical Path: 171.25s
INFO: 1621 processes: 807 internal, 402 local, 240 processwrapper-sandbox, 172 worker.
FAILED: Build did NOT complete successfully`
```
### The Log with `--verbose-failures`
```
ERROR: /mnt/m/Polka/angular/adev/src/content/introduction/essentials/BUILD.bazel:3:16: Action adev/src/content/introduction/essentials/components.md.html failed: (Exit 1): markdown.sh failed: error executing command
  (cd /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1604/execroot/angular && \
  exec env - \
    BAZEL_NODE_MODULES_ROOTS='' \
    COMPILATION_MODE=fastbuild \
  bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh bazel-out/k8-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params '--bazel_node_modules_manifest=bazel-out/k8-fastbuild/bin/adev/src/content/introduction/essentials/_essentials.module_mappings.json')
# Configuration: 8e09024857d4ba063228921961a60e2fad19d91ef3af17888baa4d42fc3dc2bf
# Execution platform: @local_config_platform//:host
```
```
  at Object.processMermaidCodeBlock (/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1604/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:49691:34)
    at Marked.walkTokens2 (/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1604/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:53186:84)
    at main (/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1604/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:53227:31)
Target //adev:serve failed to build
ERROR: /mnt/m/Polka/angular/adev/src/assets/BUILD.bazel:5:18 Copying files to directory failed: (Exit 1): markdown.sh failed: error executing command
  (cd /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/1604/execroot/angular && \
  exec env - \
    BAZEL_NODE_MODULES_ROOTS='' \
    COMPILATION_MODE=fastbuild \
  bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh bazel-out/k8-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params '--bazel_node_modules_manifest=bazel-out/k8-fastbuild/bin/adev/src/content/introduction/essentials/_essentials.module_mappings.json')
# Configuration: 8e09024857d4ba063228921961a60e2fad19d91ef3af17888baa4d42fc3dc2bf
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 478.022s, Critical Path: 169.29s
```
### The Log with `--sandbox_debug`
```
$ /mnt/m/Polka/angular/node_modules/.bin/bazel run //adev:serve --fast_adev --sandbox_debug
INFO: Analyzed target //adev:serve (1408 packages loaded, 88024 targets configured).
INFO: Found 1 target...
INFO: From Bundling Javascript packages/core/schematics/ng-generate/standalone-migration/index.ts [esbuild]:
▲ [WARNING] "import.meta" is not available in the configured target environment ("es2015") and will be empty [empty-import-meta]

    bazel-out/k8-fastbuild/bin/packages/compiler-cli/src/ngtsc/file_system/src/node_js_file_system.mjs:55:43:
      55 │ const currentFileUrl = isCommonJS ? null : import.meta.url;
         ╵                                            ~~~~~~~~~~~

INFO: From Action adev/src/content/cli/help/cli_docs_html:
Could not find the language 'jsonc', did you forget to load/include a language module?
ERROR: /mnt/m/Polka/angular/adev/src/content/introduction/essentials/BUILD.bazel:3:16: Action adev/src/content/introduction/essentials/components.md.html failed: (Exit 1): process-wrapper failed: error executing command
  (cd /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular && \
  exec env - \
    BAZEL_NODE_MODULES_ROOTS='' \
    COMPILATION_MODE=fastbuild \
    TMPDIR=/tmp \
  /home/scorp32/.cache/bazel/_bazel_scorp32/install/c87283ec3a7822eea44f4cecb6db792e/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh bazel-out/k8-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params '--bazel_node_modules_manifest=bazel-out/k8-fastbuild/bin/adev/src/content/introduction/essentials/_essentials.module_mappings.json')

/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:49691
  const browser = await chromium.launch({
                                 ^
browserType.launch: Target page, context or browser has been closed
Browser logs:

<launching> /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-PfnQJx --remote-debugging-pipe --no-startup-window
<launched> pid=13620
[pid=13620][err] /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
[pid=13620] <process did exit: exitCode=127, signal=null>
[pid=13620] starting temporary directories cleanup
Call log:
  - <launching> /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-PfnQJx --remote-debugging-pipe --no-startup-window
  - <launched> pid=13620
  - [pid=13620][err] /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh.runfiles/org_chromium_chromium_linux_x64/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
  - [pid=13620] <process did exit: exitCode=127, signal=null>
  - [pid=13620] starting temporary directories cleanup

    at Object.processMermaidCodeBlock (/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:49691:34)
    at Marked.walkTokens2 (/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:53186:84)
    at main (/home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular/external/npm/@angular/docs/pipeline/guides.mjs:53227:31)
Target //adev:serve failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /mnt/m/Polka/angular/adev/src/assets/BUILD.bazel:5:18 Copying files to directory failed: (Exit 1): process-wrapper failed: error executing command
  (cd /home/scorp32/.cache/bazel/_bazel_scorp32/e2f937d30d70b3d2dbf1e45fe5ca017a/sandbox/processwrapper-sandbox/2723/execroot/angular && \
  exec env - \
    BAZEL_NODE_MODULES_ROOTS='' \
    COMPILATION_MODE=fastbuild \
    TMPDIR=/tmp \
  /home/scorp32/.cache/bazel/_bazel_scorp32/install/c87283ec3a7822eea44f4cecb6db792e/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/k8-opt-exec-2B5CBBC6/bin/external/npm/@angular/docs/pipeline/markdown.sh bazel-out/k8-fastbuild/bin/adev/src/content/introduction/essentials/components.md.html-0.params '--bazel_node_modules_manifest=bazel-out/k8-fastbuild/bin/adev/src/content/introduction/essentials/_essentials.module_mappings.json')
INFO: Elapsed time: 937.670s, Critical Path: 188.99s
INFO: 1916 processes: 807 internal, 403 local, 450 processwrapper-sandbox, 256 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Windows 10 21H1 19043.1200, WSL Ubuntu, bash
```

**Comment by mvdluit** [comment]
Do you have `chromium` installed in your WSL environment? You can check with `which chromium` (or `which chromium-browser` if it's not aliased yet)

If not installed:
`$ sudo apt update`
`$ sudo apt install chromium-browser`

**Comment by vladboisa** [comment]
> Do you have `chromium` installed in your WSL environment? You can check with `which chromium` (or `which chromium-browser` if it's not aliased yet)
> 
> If not installed: `$ sudo apt update` `$ sudo apt install chromium-browser`

Thank you for a hint, after this package, i also needed to install libnss3 & upgrade Ubuntu
