### ISSUE TITLE
Problem with canvas in Agular SSR

### ISSUE THREAD

**Issue by luisalejandrofigueredo** [angular/angular#57182]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

## I'm the creator the library ng-gd.
[ng-gd] (https://www.npmjs.com/package/ng-gd)

Mi library have a problem when build in Angular SSR. But it works the same.
 
 ng build --watch --configuration development
- Building...
ERROR Error: NotYetImplemented
    at HTMLCanvasElement.exports.nyi (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\platform-server\fesm2022\platform-server.mjs:347:13)
    at _NgGdComponent2.ngOnInit (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\src\app\ng-gd\ng-gd.component.ts:26:71)
    at callHookInternal (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:5150:14)
    at callHook (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:5177:13)
    at callHooks (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:5131:17)
    at executeInitAndCheckHooks (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:5081:9)
    at refreshView (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:13253:21)
    at detectChangesInView (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:13454:9)
    at detectChangesInViewIfAttached (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:13414:5)
    at detectChangesInEmbeddedViews (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:1337

## this is the line this.ctx = this.elementRef.nativeElement.querySelector('canvas')?.getContext('2d')!;

    The source is from my resume web page for view the problem.
    [the source in git hub](https://github.com/luisalejandrofigueredo/luisfigueredo_ssr)

#I'm sorry for my English, I'm dyslexic and I speak Spanish.

### Please provide a link to a minimal reproduction of the bug

at _NgGdComponent2.ngOnInit (D:\luisfigueredo_ssr.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\src\app\ng-gd\ng-gd.component.ts:26:71)

### Please provide the exception or error you saw

```true
Building...                                                                                                                                                           
ERROR Error: NotYetImplemented                                                                                                                                          
   at HTMLCanvasElement.exports.nyi (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\platform-server\fesm2022\p
atform-server.mjs:347:13)                                                                                                                                              
   at _NgGdComponent2.ngOnInit (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\src\app\ng-gd\ng-gd.component.ts:26:71)              
   at callHookInternal (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:5150:14)        
   at callHook (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:5177:13)                
   at callHooks (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:5131:17)               
   at executeInitAndCheckHooks (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:5081:9) 
   at refreshView (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:13253:21)            
   at detectChangesInView (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:13454:9)     
   at detectChangesInViewIfAttached (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:134
4:5)                                                                                                                                                                   
   at detectChangesInEmbeddedViews (D:\luisfigueredo_ssr\.angular\prerender-root\2e215f83-4783-4d1f-adfb-0a82e5db5c3e\node_modules\@angular\core\fesm2022\core.mjs:1337
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.7                                            
Node: 20.16.0                                                  
Package Manager: npm 10.8.1                                    
OS: win32 x64                                                  
                                                               
Angular: 18.0.6                                                
... animations, common, compiler, compiler-cli, core, forms    
... platform-browser, platform-browser-dynamic, platform-server
... router                                                     
                                                               
Package                         Version                        
---------------------------------------------------------      
@angular-devkit/architect       0.1800.7                       
@angular-devkit/build-angular   18.0.7                         
@angular-devkit/core            18.0.7                         
@angular-devkit/schematics      18.0.7                         
@angular/cdk                    18.1.1                         
@angular/cli                    18.0.7                         
@angular/material               18.1.1                         
@angular/ssr                    18.0.7                         
@schematics/angular             18.0.7                         
rxjs                            7.8.1                          
typescript                      5.4.5                          
zone.js                         0.14.7
```

**Comment by alan-agius4** [comment]
In general, interacting with HTML elements on the server when using Server-Side Rendering (SSR) is not recommended. SSR is designed to pre-render HTML on the server to improve performance and SEO, but it should not be used to manipulate HTML elements directly. Such interactions can lead to potential issues with hydration, where the client-side JavaScript takes over the server-rendered HTML.

Instead, you should use client-side hooks like `afterNextRender` to interact with HTML elements after the initial render. This approach ensures that all necessary elements are available and fully rendered before any JavaScript manipulations occur. You can read more about the `afterNextRender` hook and its usage in Angular's official documentation [here](https://angular.dev/guide/components/lifecycle#afterrender-and-afternextrender).

**Comment by luisalejandrofigueredo** [comment]
Thanks
