### ISSUE TITLE
[Testing] Router returns wrong url after calling navigate(...) with RouterTestingHarness

### ISSUE THREAD

**Issue by someApprentice** [angular/angular#57250]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I am following [the documentation for testing the Routing component](https://angular.dev/guide/testing/components-scenarios#routing-component) and in my case the Router.url assertion fails.

Here is a minimal test reproduction:

```
@Component({
  selector: 'app-main',
  standalone: true,
  imports: [],
  template: `
    <p>
      main works!
    </p>

    <button (click)="go()">Go</button>
  `,
  styles: ``
})
export class MainComponent {
  constructor(private router: Router) {}

  go() {
    this.router.navigate(['routed']);
  }
}

@Component({
  selector: 'app-routed',
  standalone: true,
  imports: [],
  template: `
    <p>
      routed works!
    </p>
  `,
  styles: ``
})
export class RoutedComponent { }

describe('AppComponent', () => {
  let harness: RouterTestingHarness

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      providers: [
        provideRouter([
          { path: '', component: MainComponent },
          { path: 'routed', component: RoutedComponent }
        ])
      ]
    }).compileComponents();

    harness = await RouterTestingHarness.create();
  });

  it('should create the app', async () => {
    let component = await harness.navigateByUrl('', MainComponent);

    expect(component).toBeTruthy()
  });

  it('should navigate to routed page', async () => {
    await harness.navigateByUrl('', MainComponent);

    let router = TestBed.inject(Router);
    let navigateSpy = spyOn(router, 'navigate');

    let hostElement: HTMLElement = harness.routeNativeElement!;
    let goButton: HTMLButtonElement = hostElement.querySelector('button')!;

    goButton.click();

    expect(navigateSpy).toHaveBeenCalledWith(['routed']); // pass
    expect(router.url).toEqual('/routed'); // Expected '/' to equal '/routed'.
  });
});
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/someApprentice/angular-testing-router-returns-wrong-url

### Please provide the exception or error you saw

```true
Expected '/' to equal '/routed'.
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/app.component.spec.ts:42:24)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
    at _next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:17:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.3
Node: 22.4.0
Package Manager: npm 10.8.1
OS: linux x64

Angular: 18.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.3
@angular-devkit/build-angular   18.1.3
@angular-devkit/core            18.1.3
@angular-devkit/schematics      18.1.3
@schematics/angular             18.1.3
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```

**Comment by JoostK** [comment]
The assertion failure is correct, as the installed spy on `router.navigate` is configured not to invoke the original function, so the actual routing doesn't happen.

You could make the test pass by using `spyOn(router, 'navigate').and.callThrough()`, but I'd recommend _not_ to use spies in this case as they make for brittle tests.

**Comment by someApprentice** [comment]
The spy was implemented just to test that the navigate method was at least called, [as it used to do in older versions of Angular.](https://v14.angular.io/guide/testing-components-scenarios#routing-component)

I initially tested only with RouterTestingHarness without using spy, and the assertion did not pass.

```
  it('should navigate to routed page', async () => {
    await harness.navigateByUrl('', MainComponent);

    let hostElement: HTMLElement = harness.routeNativeElement!;
    let goButton: HTMLButtonElement = hostElement.querySelector('button')!;

    goButton.click();

    expect(TestBed.inject(Router).url).toEqual('/routed'); // Expected '/' to equal '/routed'.
  });
```

```
Expected '/' to equal '/routed'.
    at <Jasmine>
    at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/src/app/app.component.spec.ts:41:40)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
    at _next (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:17:1)
```
