### ISSUE TITLE
HammerGestureConfig malfunctions in Angular 18....

### ISSUE THREAD

**Issue by wacilpong** [angular/angular#57284]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

Hi. I am updating Angular from v16 to v18 now. And I have serious issue with [HammerGestureConfig](https://angular.dev/api/platform-browser/HammerGestureConfig).

## I was using it below:

```
// app.module.ts
@Injectable()
class HammerConfig extends HammerGestureConfig {
  overrides = {
    swipe: {direction: DIRECTION_ALL},
  };
}

@NgModule({
  ...
  providers: [
    ...
    {provide: HAMMER_GESTURE_CONFIG, useClass: HammerConfig},
  ]
})
export class AppModule {...}
```

## and I got errors like this:
```
Error: NG0200: Circular dependency in DI detected for RendererFactory2. Find more at https://angular.dev/errors/NG0200
    at throwCyclicDependencyError (vendor.js:58661:9)
    at R3Injector.hydrate (vendor.js:60827:9)
    at R3Injector.get (vendor.js:60705:23)
    at ApplicationRef.detectChangesInAttachedViews (vendor.js:89619:40)
    at ApplicationRef._tick (vendor.js:89601:12)
    at ApplicationRef.tick (vendor.js:89590:10)
    at vendor.js:89988:31
    at _ZoneDelegate.invoke (polyfills.js:1366:158)
    at Object.onInvoke (vendor.js:73417:25)
    at _ZoneDelegate.invoke (polyfills.js:1366:46)

TypeError: Class constructor HammerGestureConfig cannot be invoked without 'new'
    at new HammerConfig (main.js:4319:24)
    at Object.factory (vendor.js:60936:25)
    at vendor.js:60832:35
    at runInInjectorProfilerContext (vendor.js:58563:5)
    at R3Injector.hydrate (vendor.js:60831:11)
    at R3Injector.get (vendor.js:60705:23)
    at injectInjectorOnly (vendor.js:58792:36)
    at ɵɵinject (vendor.js:58798:59)
    at injectArgs (vendor.js:58923:17)
    at Object.factory (vendor.js:60936:41)

ReferenceError: Hammer is not defined  
```

## So... I debugged and I found a solution, but there is a problem.

Remove `overrides` and provide `HAMMER_GESTURE_CONFIG` with only `HammerGestureConfig`. and also provide `HAMMER_LOADER` too.
```
// app.module.ts
@NgModule({
  ...
  providers: [
    ...
    {provide: HAMMER_GESTURE_CONFIG, useClass: HammerConfig},
    {provide: HAMMER_LOADER, useValue: () => import('hammerjs')},
  ]
})
export class AppModule {...}
```

it works in short... but when route to another page(with another module like _detail.module.ts_), I got `ReferenceError: Hammer is not defined ` again. In the end, I solved it as below, but I don't know if it's right way.

```
// detail.module.ts
// (I only use Hammerjs functions in detail.module, so I move providers from app.module to detail.module)
@NgModule({
  ...
  providers: [
    ...
    {provide: HAMMER_GESTURE_CONFIG, useClass: HammerConfig},
    {provide: HAMMER_LOADER, useValue: () => import('hammerjs')},
  ]
})
export class DetailModule {...}
```
If I do this, I have to provide the same when using Hammerjs functions in other modules later. Could you please give me the right guide on Angular v18? Thanks.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: v18.1.0
Node: v20.15.0
Package Manager: yarn v1.22.10

Angular: v18.1.1

  "dependencies": {
    "@angular/animations": "^18.1.0",
    "@angular/common": "^18.1.0",
    "@angular/compiler": "^18.1.0",
    "@angular/core": "^18.1.0",
    "@angular/forms": "^18.1.0",
    "@angular/platform-browser": "^18.1.0",
    "@angular/platform-browser-dynamic": "^18.1.0",
    "@angular/router": "^18.1.0",
    "@egjs/agent": "^2.1.5",
    "@ngneat/until-destroy": "^9.2.2",
    "@ngrx/component": "^18.0.1",
    "@ngrx/effects": "^18.0.1",
    "@ngrx/entity": "^18.0.1",
    "@ngrx/store": "^18.0.1",
    "@ngrx/store-devtools": "^18.0.1",
    "clipboard": "^2.0.4",
    "core-js": "^3.23.4",
    "fast-average-color": "^9.3.0",
    "hammerjs": "^2.0.8",
    "intersection-observer": "^0.11.0",
    "jsbarcode": "3.11.5",
    "lodash-es": "^4.17.21",
    "luxon": "^3.0.0",
    "ngrx-etc": "^6.0.0",
    "ngx-barcode6": "^1.0.23",
    "raven-js": "^3.27.2",
    "rxjs": "^7.5.6",
    "rxjs-shell": "0.0.7",
    "stringz": "^2.1.0",
    "tslib": "^2.0.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.14.7"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.1.0",
    "@angular-eslint/builder": "^18.1.0",
    "@angular-eslint/eslint-plugin": "^18.1.0",
    "@angular-eslint/eslint-plugin-template": "^18.1.0",
    "@angular-eslint/schematics": "^18.1.0",
    "@angular-eslint/template-parser": "^18.1.0",
    "@angular/cli": "^18.1.0",
    "@angular/compiler-cli": "^18.1.0",
    "@angular/language-service": "^18.1.0",
    "@commitlint/cli": "^16.2.1",
    "@commitlint/config-conventional": "^16.2.1",
    "@sentry/browser": "^5.18.1",
    "@types/hammerjs": "^2.0.41",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "^2.0.6",
    "@types/lodash-es": "^4.17.5",
    "@types/luxon": "^1.22.0",
    "@types/node": "^12.20.25",
    "@typescript-eslint/eslint-plugin": "^7.17.0",
    "@typescript-eslint/parser": "^7.17.0",
    "cypress": "^12.2.0",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.26.4",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-rxjs": "^5.0.2",
    "git-branch-is": "^4.0.0",
    "husky": "^7.0.4",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "lint-staged": "^12.3.4",
    "ng-packagr": "^18.1.0",
    "prettier": "^2.5.1",
    "prettier-plugin-organize-imports": "^3.2.2",
    "sort-package-json": "^1.54.0",
    "standard-version": "^9.3.2",
    "ts-node": "^3.0.0",
    "typescript": "~5.5.3"
  },
```

**Comment by JoostK** [comment]
> TypeError: Class constructor HammerGestureConfig cannot be invoked without 'new'

This indicates that the `HammerGestureConfig` has been compiled as ES5 class, whereas `HammerGestureConfig` is ES2015+. Extending ES2015+ from ES5 doesn't work and results in this error.

---

This would require a runnable reproduction as without it this isn't actionable.

**Comment by pkozlowski-opensource** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
