### ISSUE TITLE
Paginator in child class is undefined

### ISSUE THREAD

**Issue by AntonBobylev** [angular/angular#57638]
### Which @angular/* package(s) are the source of the bug?

core, Don't known / other

### Is this a regression?

Yes

### Description

Hi there!
I've faced with strange issue.

Look, I have the app-table component which was created as a base table of the application.
Also, I have the patients-table component that inherits the app-table.

The problem is with paginator and sort, when I'm trying to refreshGrid.

There is a base component - patients. It has a two components inside it - patients-options-panel and patients-table.
I'm trying to call refreshGrid method with filters of the patients-options-panel inside patients component.

It successfully calls that method, but paginator and sort members are undefined. Why? It shoulda been initialized in the parent component - app-table. What am I doing wrong?

Also, using Chrome DevTools I see that we are in the PatientsTableComponent when I click search in options panel. And sort with paginator isn't defined here. This is really upsets me.

<hr>

app-table.component.ts
```ts
import { AfterViewInit, Component, inject, Input, ViewChild } from '@angular/core';
import { SelectionModel } from '@angular/cdk/collections';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { MatSort, MatSortModule, Sort } from '@angular/material/sort';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';
import { LiveAnnouncer } from '@angular/cdk/a11y';
import { MatProgressSpinner } from '@angular/material/progress-spinner';
import { NgIf } from '@angular/common';
import { MatCheckbox } from '@angular/material/checkbox';
import { MatDialog } from '@angular/material/dialog';
import { MatCard, MatCardContent } from '@angular/material/card';
import { MatTooltip } from '@angular/material/tooltip';
import { CdkDrag, CdkDragDrop, CdkDropList, moveItemInArray } from '@angular/cdk/drag-drop';

import EmsowAngular from '../../../../../EmsowAngular';
import Fetcher from '../../../../../utils/fetcher/Fetcher';

import AppDialogComponent from '../../dialogs/app-dialog/app-dialog.component';
import AppToolbarComponent, { AppToolbarButton } from '../../toolbars/app-toolbar/app-toolbar.component';

import Timeout from '../../../../../utils/fetcher/Timeout';
import { SortDirection } from '../../../../types/SortDirection';
import AppButtonComponent from '../../buttons/app-button/app-button.component';
import { ResponseCodes } from '../../../../enumerates/ResponseCode';
import { DialogType } from '../../../../enumerates/DialogType';
import { IKeyable } from '../../../../interfaces/IKeyable';

export type AppTableColumn = {
    displayName: string,
    valueRenderer?: Function,
    name: string,
    dataIndex: string,
    sortable?: boolean,
    width?: number
}

export type AppTableUrl = {
    url: string,
    timeout?: number
}

@Component({
    selector: 'app-table',
    standalone: true,
    imports: [
        MatTableModule, MatPaginatorModule, MatSortModule,
        MatProgressSpinner, NgIf, MatCheckbox, MatPaginator,
        MatCard, MatCardContent, AppToolbarComponent,
        AppButtonComponent, MatTooltip, CdkDropList, CdkDrag
    ],
    templateUrl: './app-table.component.html',
    styleUrl: './app-table.component.css'
})

export default class AppTableComponent implements AfterViewInit
{
    @Input() public columns: AppTableColumn[] = [];

    @Input() public data: any = [];
    @Input() public dataRoot: string = 'data';

    private defaultUrlParameters: AppTableUrl = {
        url: '',
        timeout: Timeout.timeout
    }

    @Input() public loadUrl: AppTableUrl = this.defaultUrlParameters;
    @Input() public removeUrl: AppTableUrl = this.defaultUrlParameters;

    @Input() public toolbarRequired: boolean = true;
    @Input() public toolbarCustomButtons: AppToolbarButton[] = [];
    @Input() public requiredBaseButtons: 'all' | string[] = 'all';

    @Input() public selectRequired: boolean = true;
    @Input() public selectColumnWidth: number | undefined;

    @Input() public useRemoteSorting: boolean = true;
    @Input() public useDefaultSort: boolean = false;
    @Input() public defaultColumnForSort: string = '';
    @Input() public defaultSortDirection: SortDirection = 'asc';

    @Input() public useRemotePagination: boolean = true;

    @Input() public showFirstLastButton: boolean = true;

    protected readonly EmsowAngular = EmsowAngular;

    protected readonly queryController = new AbortController();

    protected readonly paginatorDefaultPageSize: number = 50;
    protected readonly paginatorPagesSizes: number[] = [5, 10, 25, 50, 100, 150, 200, 300, 500, 1000];

    protected readonly selectColumnDefaultName: string = 'select';

    protected defaultColumnsValues = { sortable: true };

    protected initialSelection: [] = [];
    protected allowMultiSelect: boolean = true;

    protected selection: SelectionModel<any> = new SelectionModel<any>(this.allowMultiSelect, this.initialSelection);
    protected readonly selectColumnDefaultConfig: AppTableColumn = {
        name: this.selectColumnDefaultName,
        dataIndex: '',
        width: 50,
        sortable: false,
        displayName: ''
    };

    protected isLoading: boolean = false;

    protected dataSource = new MatTableDataSource(this.data);

    @ViewChild(MatSort, { static: false }) sort!: MatSort;
    @ViewChild(MatPaginator, { static: false }) paginator!: MatPaginator;

    protected paginatorLength: number = 0;
    protected paginatorPageIndex: number = 0;
    protected paginatorPageSize: number = this.paginatorDefaultPageSize;

    // TODO: inject it in EmsowAngular. And make call like EmsowAngular.showMsg()
    private readonly dialog: MatDialog = inject(MatDialog);

    constructor(private _liveAnnouncer: LiveAnnouncer)
    {
    }

    ngOnInit(): void
    {
        if (!EmsowAngular.isEmpty(this.loadUrl)) {
            this.isLoading = true;
        }

        if (this.selectRequired) {
            let me = this,
                selectAlreadyPresent: boolean = false;

            EmsowAngular.each(this.columns, function (column: AppTableColumn) {
                if (column.name.toLowerCase() === me.selectColumnDefaultName.toLowerCase()) {
                    selectAlreadyPresent = true;

                    column.width = me.selectColumnWidth ?? column.width;

                    return;
                }
            });

            if (!selectAlreadyPresent) {
                this.selectColumnDefaultConfig.width = me.selectColumnWidth ?? this.selectColumnDefaultConfig.width;
                this.columns.splice(0, 0, this.selectColumnDefaultConfig);
            }
        }
    }

    ngAfterViewInit(): void
    {
        let me = this;

        if (!me.useRemoteSorting) {
            me.dataSource.sort = me.sort;
        }

        if (!me.useRemotePagination) {
            me.dataSource.paginator = me.paginator;
        }

        if (EmsowAngular.isEmpty(me.loadUrl.url)) {
            me.isLoading = false;

            if (EmsowAngular.isEmpty(me.data)) {
                me.data = [];
            }

            me.dataSource.data = me.data;

            return;
        }

        me.refreshGrid();

        this.applyColumnsWidth();
    }

    private applyColumnsWidth(): void
    {
        // Timeout is a crutch to display a correct width of columns
        setTimeout(() => {
            // TODO: how to avoid the code below?
            EmsowAngular.each(this.columns, function (column: AppTableColumn) {
                if (EmsowAngular.isEmpty(column.width)) {
                    return;
                }

                let columnName = column.name.replaceAll('.', '-'),
                    className = EmsowAngular.format('mat-column-{0}', [columnName]),
                    columnEl = document.getElementsByClassName(className)[0];

                if (EmsowAngular.isEmpty(columnEl) || columnEl === null) {
                    return;
                }

                columnEl?.setAttribute('style', EmsowAngular.format('width: {0}px', [column.width]))
            });
        }, 50);
    }

    public ngOnDestroy(): void
    {
        this.queryController.abort();
    }

    private cleanTableData(): void
    {
        this.data = [];
        this.dataSource.data = this.data;
    }

    public refreshGrid(filters: IKeyable[] = []): void
    {
        let me = this;
        me.isLoading = true;

        me.cleanTableData();

        let params = {};
        if (me.useRemotePagination) {
            params = EmsowAngular.mergeObjects(params, {
                limit: me.paginator.pageSize,
                start: me.paginator.pageIndex
            });
        }

        if (me.useRemoteSorting) {
            params = EmsowAngular.mergeObjects(params, {
                sort: me.sort.active,
                dir: me.sort.direction
            });
        }

        if (filters) {
            console.log(filters);
        }

        (new Fetcher).request({
            url: me.loadUrl.url,
            timeout: me.loadUrl.timeout,
            params: params,
            signal: this.queryController.signal,
            success: function (_response: any, _request: any, result: any): void {
                me.isLoading = false;

                me.data = result[me.dataRoot];
                me.dataSource.data = me.data;

                me.paginatorLength = Number(result.total);
            },
            failure: function (response: any, _request: any, result: any): void {
                me.isLoading = false;

                if (response === ResponseCodes.CANCELED) {
                    return;
                }

                me.dialog.open(AppDialogComponent, {
                    data: {
                        message: result.msg,
                        type: DialogType.ERROR
                    },
                    disableClose: true
                });
            }
        });
    }

    onSortChange(sortState: Sort): void
    {
        this.announceSortChange(sortState);

        if (this.useRemoteSorting) {
            this.refreshGrid();
        }
    }

    announceSortChange(sortState: Sort): void
    {
        sortState.direction
            ? this._liveAnnouncer.announce(EmsowAngular.format('Sorted {0}ending', [sortState.direction]))
            : this._liveAnnouncer.announce('Sorting cleared');
    }

    toggleAllRows(): void
    {
        this.isAllSelected() ?
            this.selection.clear() :
            this.dataSource.data.forEach(row => this.selection.select(row));
    }

    isAllSelected(): boolean
    {
        const numSelected: number = this.selection.selected.length,
            numRows: number = this.dataSource.data.length;

        return numSelected == numRows;
    }

    getColumnsNames(): string[]
    {
        return this.columns.map(column => column.name);
    }

    protected getRecordValue(record: any, key: string): string
    {
        let value: any = record[key];

        if (value !== undefined) {
            return value;
        }

        value = this.lookupByPath(record, key);

        return EmsowAngular.isEmpty(value) ? '-' : value;
    }

    protected lookupByPath(obj: any, path: string): string
    {
        let parts: string[] = path.split('.');
        if (parts.length == 1) {
            return obj[parts[0]];
        }
        return this.lookupByPath(obj[parts[0]], parts.slice(1).join('.'));
    }

    protected setRowSelected(row: Object): void
    {
        this.selection.setSelection(row);
    }

    protected onToolbarButtonClick(button: any)
    {
        switch (button.buttonType) {
            case 'add':
                this.onToolbarAddClick(button.button);
                break;
            case 'edit':
                this.onToolbarEditClick(button.button);
                break;
            case 'remove':
                this.onToolbarRemoveClick(button.button);
                break;
            default:
                this.onToolbarCustomButtonClick(button.buttonType, button.button);
                break;
        }
    }

    @Input() public onToolbarAddClick(button: any): void
    {
        // implement in child
    }

    @Input() public onToolbarEditClick(button: any): void
    {
        // implement in child
    }

    @Input() public onToolbarRemoveClick(button: any): void
    {
        // TODO: implement

        console.log('Remove');
    }

    @Input() public onToolbarCustomButtonClick(buttonType: any, button: any): void
    {
        // implement switch in child
    }

    @Input() public onRefreshClick(): void
    {
        this.refreshGrid();
    }

    @Input() public onPageChange(): void
    {
        this.refreshGrid();
    }

    dropColumn(event: CdkDragDrop<string[]>): void
    {
        moveItemInArray(this.columns, event.previousIndex, event.currentIndex);
        this.applyColumnsWidth();
    }
}
```

app-table.html
```html
<mat-card appearance="outlined">
    <mat-card-content>
        @if (toolbarRequired) {
            <app-toolbar (onToolbarButtonClick)="onToolbarButtonClick($event)"
                         [customButtons]="toolbarCustomButtons"
                         [requiredBaseButtons]="requiredBaseButtons"
                         [disabled]="isLoading"
            />
        }

        <div class="app-table">
            <table
                mat-table
                [dataSource]="dataSource"
                matSort
                (matSortChange)="onSortChange($event)"
                [matSortActive]="useDefaultSort ? defaultColumnForSort : ''"
                [matSortDirection]="useDefaultSort ? defaultSortDirection : ''"
                class="mat-elevation-z8"
                cdkDropList cdkDropListLockAxis="x"
                cdkDropListOrientation="horizontal"
                (cdkDropListDropped)="dropColumn($event)"
            >
                <ng-container matColumnDef="{{selectColumnDefaultName}}">
                    <th mat-header-cell *matHeaderCellDef cdkDrag>
                        <mat-checkbox (change)="$event ? toggleAllRows() : null"
                                      [disabled]="isLoading"
                                      [checked]="selection.hasValue() && isAllSelected()"
                                      [indeterminate]="selection.hasValue() && !isAllSelected()">
                        </mat-checkbox>
                    </th>
                    <td mat-cell *matCellDef="let row">
                        <mat-checkbox (click)="$event.stopPropagation()"
                                      (change)="$event ? selection.toggle(row) : null"
                                      [checked]="selection.isSelected(row)">
                        </mat-checkbox>
                    </td>
                </ng-container>

                @for (column of columns; track column.name) {
                    <ng-container
                        *ngIf="column.name !== this.selectColumnDefaultName"
                        matColumnDef="{{column.name}}"
                    >
                        <th
                            mat-header-cell
                            *matHeaderCellDef
                            [mat-sort-header]="column.name"
                            [disabled]="column.sortable === undefined ? !defaultColumnsValues.sortable : !column.sortable"
                            sortActionDescription="Sort by {{column.name}}"
                            class="app-table-header-row"
                            cdkDrag
                        >
                            {{ column.displayName }}
                        </th>

                        <td mat-cell *matCellDef="let element">
                            @if (column.valueRenderer) {
                                {{ column.valueRenderer(getRecordValue(element, column.dataIndex)) }}
                            } @else {
                                {{ getRecordValue(element, column.dataIndex) }}
                            }
                        </td>
                    </ng-container>
                }

                <tr mat-header-row
                    *matHeaderRowDef="getColumnsNames()"
                    style="border: 1px solid var(--app-theme-table-border-color)"
                ></tr>

                <tr mat-row
                    [className]="selection.isSelected(row) ? 'table-data-row-selected' : 'table-data-row'"
                    *matRowDef="let row; columns: getColumnsNames();"
                    style="border: 1px solid var(--app-theme-table-border-color)"
                    (click)="setRowSelected(row)"
                ></tr>
            </table>

            <div *ngIf="isLoading"
                 style="display: flex; justify-content: center; align-items: center; background: white; margin-top: 20px;">
                <mat-progress-spinner
                    diameter="30"
                    color="primary"
                    mode="indeterminate">
                </mat-progress-spinner>
            </div>
        </div>

        <div class="app-table-footer">
            <app-button class="refresh-button"
                        icon="refresh"
                        (click)="onRefreshClick()"
                        [matTooltip]="EmsowAngular.Translator.translate('refresh')"
                        [disabled]="isLoading"
            />
            <mat-paginator [pageSize]="useRemotePagination ? paginatorPageSize : paginatorDefaultPageSize"
                           [pageIndex]="useRemotePagination ? paginatorPageIndex : null"
                           [length]="useRemotePagination ? paginatorLength : null"
                           [pageSizeOptions]="paginatorPagesSizes"
                           [showFirstLastButtons]="showFirstLastButton"
                           [disabled]="isLoading"
                           (page)="useRemotePagination ? onPageChange() : null"
                           aria-label="Select page of periodic elements"
            >
            </mat-paginator>
        </div>
    </mat-card-content>
</mat-card>
```

<hr>

patients-table.component.ts:
```ts
import { Component } from '@angular/core';

import AppTableComponent, {
    AppTableColumn,
    AppTableUrl
} from '../../../components/core/tables/app-table/app-table.component';

import EmsowAngular from '../../../../EmsowAngular';
import { AppToolbarButton } from '../../../components/core/toolbars/app-toolbar/app-toolbar.component';

@Component({
    selector: 'app-patients-table',
    standalone: true,
    imports: [AppTableComponent],
    templateUrl: './patients-table.component.html',
    styleUrl: './patients-table.component.css'
})

export class PatientsTableComponent extends AppTableComponent
{
    public override columns: AppTableColumn[] = [{
        name: 'patient_id',
        dataIndex: 'patient_id',
        displayName: this.EmsowAngular.Translator.translate('id'),
        width: 60
    }, {
        name: 'patient_last_name',
        dataIndex: 'patient_last_name',
        displayName: this.EmsowAngular.Translator.translate('last_name'),
        width: 200
    }, {
        name: 'patient_first_name',
        dataIndex: 'patient_first_name',
        displayName: this.EmsowAngular.Translator.translate('first_name'),
        width: 200
    }, {
        name: 'patient_middle_name',
        dataIndex: 'patient_middle_name',
        displayName: this.EmsowAngular.Translator.translate('middle_name'),
        width: 200
    }, {
        name: 'patient_dob',
        dataIndex: 'patient_dob',
        displayName: this.EmsowAngular.Translator.translate('dob'),
        width: Number.parseInt(EmsowAngular.Translator.translate('patients_view.table.columns.width.patient_dob')),
        valueRenderer: function (value: any) {
            return EmsowAngular.Format.dateShort(value);
        }
    }, {
        name: 'patient_sex',
        dataIndex: 'patient_sex',
        displayName: this.EmsowAngular.Translator.translate('gender'),
        width: 100,
        valueRenderer: function (value: any) {
            return EmsowAngular.Format.genderFullname(value);
        }
    }, {
        name: 'patient_ssn',
        dataIndex: 'patient_ssn',
        displayName: EmsowAngular.Translator.translate('ssn')
    }, {
        name: 'patient_mrn',
        dataIndex: 'patient_mrn',
        displayName: EmsowAngular.Translator.translate('patient_no'),
        width: Number.parseInt(EmsowAngular.Translator.translate('patients_view.table.columns.width.patient_mrn'))
    }, {
        name: 'patient_address',
        dataIndex: 'patient_address',
        displayName: EmsowAngular.Translator.translate('address'),
        width: 200
    }, {
        name: 'patient_room',
        dataIndex: 'patient_room',
        displayName: EmsowAngular.Translator.translate('room'),
        width: Number.parseInt(EmsowAngular.Translator.translate('patients_view.table.columns.width.patient_room'))
    }, {
        name: 'patient_city',
        dataIndex: 'patient_city',
        displayName: EmsowAngular.Translator.translate('city'),
        width: 200
    }, {
        name: 'patient_state',
        dataIndex: 'patient_state',
        displayName: EmsowAngular.Translator.translate('state'),
        width: Number.parseInt(EmsowAngular.Translator.translate('patients_view.table.columns.width.patient_state'))
    }, {
        name: 'patient_zip',
        dataIndex: 'patient_zip',
        displayName: EmsowAngular.Translator.translate('zip')
    }, {
        name: 'patient_cell_phone',
        dataIndex: 'patient_cell_phone',
        displayName: EmsowAngular.Translator.translate('cell_phone'),
        width: Number.parseInt(EmsowAngular.Translator.translate('patients_view.table.columns.width.patient_cell_phone'))
    }, {
        name: 'patient_home_phone',
        dataIndex: 'patient_home_phone',
        displayName: EmsowAngular.Translator.translate('home_phone'),
        width: Number.parseInt(EmsowAngular.Translator.translate('patients_view.table.columns.width.patient_home_phone'))
    }, {
        name: 'patient_work_phone',
        dataIndex: 'patient_work_phone',
        displayName: EmsowAngular.Translator.translate('work_phone'),
        width: Number.parseInt(EmsowAngular.Translator.translate('patients_view.table.columns.width.patient_work_phone'))
    }, {
        name: 'patient_email',
        dataIndex: 'patient_email',
        displayName: EmsowAngular.Translator.translate('email'),
        width: 250
    }];

    public override data = [];
    public override dataRoot = 'patients';

    public override loadUrl: AppTableUrl = { url: 'ajax_srv.php?request=getPatientsAngular' };
    public override removeUrl: AppTableUrl = { url: 'ajax_srv.php?request=removePatientAngular' };

    public override useDefaultSort: boolean = true;
    public override defaultColumnForSort: string = 'patient_id';

    public override toolbarCustomButtons: AppToolbarButton[] = [{
        title: EmsowAngular.Translator.translate('patients_view.toolbar.invite_patient'),
        type: 'invite',
        icon: 'notifications_active',
        iconColor: '#faca22'
    }];

    override ngAfterViewInit(): void
    {
    }

    override onToolbarAddClick(button: any): void
    {
        super.onToolbarAddClick(button);

        console.log('Add');

        // TODO: implement
    }

    override onToolbarEditClick(button: any): void
    {
        super.onToolbarEditClick(button);

        console.log('Edit');

        // TODO: implement
    }

    override onToolbarCustomButtonClick(buttonType: any, button: any): void
    {
        switch (buttonType) {
            case 'invite': {
                console.log('Invite');

                // TODO: implement

                break;
            }
        }
    }
}
```

patients-table.component.html:
```html
<app-table [columns]="columns"
           [data]="data"
           [dataRoot]="dataRoot"
           [loadUrl]="loadUrl"
           [removeUrl]="removeUrl"
           [onToolbarAddClick]="onToolbarAddClick"
           [onToolbarEditClick]="onToolbarEditClick"
           [onToolbarCustomButtonClick]="onToolbarCustomButtonClick"
           [toolbarCustomButtons]="toolbarCustomButtons"
           [useDefaultSort]="useDefaultSort"
           [defaultColumnForSort]="defaultColumnForSort"
></app-table>
```

<hr>

patients.component.ts
```ts
import { Component, ViewChild } from '@angular/core';
import { MatGridList, MatGridTile } from '@angular/material/grid-list';

import { PatientsTableComponent } from './patients-table/patients-table.component';
import { PatientsOptionsPanelComponent } from './patients-options-panel/patients-options-panel.component';
import AppTableComponent from '../../components/core/tables/app-table/app-table.component';

@Component({
    selector: 'app-patients',
    standalone: true,
    imports: [PatientsTableComponent, MatGridList, MatGridTile, PatientsOptionsPanelComponent],
    templateUrl: './patients.component.html',
    styleUrl: './patients.component.css',
    host: { 'class': 'module-container' }
})

export class PatientsComponent
{
    @ViewChild('patientsTable', { static: false })
    protected table!: AppTableComponent;

    @ViewChild(PatientsOptionsPanelComponent, { static: false })
    protected optionsPanel!: PatientsOptionsPanelComponent;

    protected onSearch()
    {
        this.table.refreshGrid(this.optionsPanel.formValues);
    }
}
```

patients.component.html
```html
<mat-grid-list cols="4" [gutterSize]="'10px'">
    <mat-grid-tile>
        <app-patients-options-panel (search)="onSearch()"/>
    </mat-grid-tile>
    <mat-grid-tile colspan="3">
        <div class="patients-table">
            <app-patients-table #patientsTable  />
        </div>
    </mat-grid-tile>
</mat-grid-list>
```
<hr>

patients-options-panel.component.ts
```ts
import { Component, EventEmitter, Input, Output, QueryList, ViewChildren } from '@angular/core';
import {
    MatCard,
    MatCardActions,
    MatCardContent,
    MatCardFooter,
    MatCardHeader,
    MatCardTitle
} from '@angular/material/card';
import { MatFormField, MatLabel, } from '@angular/material/form-field';
import { MatInput } from '@angular/material/input';
import {
    MatAccordion,
    MatExpansionPanel,
    MatExpansionPanelHeader,
    MatExpansionPanelTitle
} from '@angular/material/expansion';

import EmsowAngular from '../../../../EmsowAngular';

import {
    AppCollapsibleFieldsetComponent, AppCollapsibleFieldsetElement,
    AppCollapsibleFieldsetField
} from '../../../components/core/collapsible-fieldset/app-collapsible-fieldset.component';
import AppButtonComponent from '../../../components/core/buttons/app-button/app-button.component';
import { FieldType } from '../../../enumerates/FieldType';
import { IKeyable } from '../../../interfaces/IKeyable';

type fieldsConfig = {
    title: string,
    fields: AppCollapsibleFieldsetField[]
}

@Component({
    selector: 'app-patients-options-panel',
    standalone: true,
    imports: [
        MatCard,
        MatCardContent,
        MatCardHeader,
        MatCardTitle,
        MatFormField,
        MatLabel,
        MatInput,
        MatAccordion,
        MatExpansionPanel,
        MatExpansionPanelTitle,
        MatExpansionPanelHeader,
        AppCollapsibleFieldsetComponent,
        MatCardFooter,
        MatCardActions,
        AppButtonComponent
    ],
    templateUrl: './patients-options-panel.component.html',
    styleUrl: './patients-options-panel.component.css'
})

export class PatientsOptionsPanelComponent
{
    @Input() public formValues: IKeyable[] = [];
    @Output() public search: EventEmitter<any> = new EventEmitter<any>();

    protected readonly EmsowAngular = EmsowAngular;

    protected readonly fieldsConfig: fieldsConfig[] = this.getOptionsPanelFields();

    @ViewChildren(AppCollapsibleFieldsetComponent) fields: QueryList<AppCollapsibleFieldsetComponent> | undefined;

    public ngOnInit(): void
    {
        this.clearFormValues();
    }

    protected fieldUpdated(updatedField: any): void
    {
        // todo: implement
        console.log(updatedField);
    }

    protected clearFormValues(): void
    {
        // todo: implement
        console.log('clearing form values...');
    }

    protected reload(): void
    {
        // todo: implement
        console.log('reloading...');
    }

    protected onSearch(): void
    {
        this.formValues = this.getFormValues();
        this.search.emit();
    }

    protected getFormValues(): IKeyable[]
    {
        let result: IKeyable[] = [];

        if (!this.fields) {
            return result;
        }

        let allFields: AppCollapsibleFieldsetElement[] = [],
            fields = this.fields.toArray();

        if (EmsowAngular.isEmpty(fields)) {
            return result;
        }

        fields.map(function (field) {
            field.elements.map(function(element) {
                allFields.push(element);
            });
        }, this);

        EmsowAngular.each(allFields, function (field: AppCollapsibleFieldsetElement) {
            result.push({
                ...field,
                value: field.getValue(field.element)
            });
        });

        return result;
    }

    protected getOptionsPanelFields(): fieldsConfig[]
    {
        return [{
            title: EmsowAngular.Translator.translate('demographics'),
            fields: this.getDemographicsFields()
        }, {
            title: EmsowAngular.Translator.translate('contacts'),
            fields: this.getContactsFields()
        }, {
            title: EmsowAngular.Translator.translate('options_panel.patients.insurances_information'),
            fields: this.getInsurancesInformationFields()
        }, {
            title: EmsowAngular.Translator.translate('entities.services') + ' / ' + EmsowAngular.Translator.translate('entities.studies'),
            fields: this.getServicesStudies()
        }];
    }

    protected getDemographicsFields(): AppCollapsibleFieldsetField[]
    {
        return [{
            label: EmsowAngular.Translator.translate('id'),
            type: FieldType.TEXT,
            name: 'patient_id'
        }, {
            label: EmsowAngular.Translator.translate('last_name'),
            type: FieldType.TEXT,
            name: 'patient_last_name'
        }, {
            label: EmsowAngular.Translator.translate('first_name'),
            type: FieldType.TEXT,
            name: 'patient_first_name'
        }, {
            label: EmsowAngular.Translator.translate('middle_name'),
            type: FieldType.TEXT,
            name: 'patient_middle_name'
        }];
    }

    protected getContactsFields(): AppCollapsibleFieldsetField[]
    {
        return [{
            label: EmsowAngular.Translator.translate('city'),
            type: FieldType.TEXT,
            name: 'patient_city'
        }, {
            label: EmsowAngular.Translator.translate('state'),
            type: FieldType.TEXT,
            name: 'patient_state'
        }, {
            label: EmsowAngular.Translator.translate('zip'),
            type: FieldType.TEXT,
            name: 'patient_zip'
        }];
    }

    protected getInsurancesInformationFields(): AppCollapsibleFieldsetField[]
    {
        return [{
            label: EmsowAngular.Translator.translate('entities.insurances'),
            type: FieldType.TEXT,
            name: 'insurances'
        }, {
            label: EmsowAngular.Translator.translate('member_id'),
            type: FieldType.TEXT,
            name: 'patient_insurance_member_id'
        }, {
            label: EmsowAngular.Translator.translate('group_no'),
            type: FieldType.TEXT,
            name: 'patient_insurance_group_no'
        }];
    }

    protected getServicesStudies(): AppCollapsibleFieldsetField[]
    {
        return [{
            label: EmsowAngular.Translator.translate('dos_full'),
            type: FieldType.TEXT,
            name: 'dos'
        }, {
            label: EmsowAngular.Translator.translate('order_id'),
            type: FieldType.TEXT,
            name: 'order_id'
        }, {
            label: EmsowAngular.Translator.translate('service_id'),
            type: FieldType.TEXT,
            name: 'service_id'
        }, {
            label: EmsowAngular.Translator.translate('an_middle'),
            type: FieldType.TEXT,
            name: 'accession_number'
        }];
    }
}
```

patients-options-panel.component.html
```html
<mat-card appearance="outlined" class="fully-height">
    <mat-card-header>
        <mat-card-title>{{ EmsowAngular.Translator.translate('options_panel.title') }}</mat-card-title>
    </mat-card-header>

    <hr />

    <mat-card-content class="fully-height">
        <mat-accordion multi>
            @for (fieldConfig of fieldsConfig; track fieldConfig) {
                <app-collapsible-fieldset
                    [title]="fieldConfig.title"
                    [fields]="fieldConfig.fields"
                    (fieldUpdated)="fieldUpdated($event)"
                ></app-collapsible-fieldset>
            }
        </mat-accordion>
    </mat-card-content>

    <hr style="margin: 10px"/>

    <mat-card-footer>
        <mat-card-actions class="options-panel-buttons fully-height">
            <app-button buttonTitle="{{EmsowAngular.Translator.translate('clear')}}"
                        icon="cleaning_services"
                        iconColor="#9acbeb"
                        (click)="clearFormValues()"
            />
            <app-button buttonTitle="{{EmsowAngular.Translator.translate('reload')}}"
                        icon="refresh"
                        (click)="reload()"
            />
            <app-button buttonTitle="{{EmsowAngular.Translator.translate('search')}}"
                        icon="search"
                        (click)="onSearch()"
            />
        </mat-card-actions>
    </mat-card-footer>
</mat-card>
```

### Please provide the exception or error you saw

```true
TypeError: Cannot read properties of undefined (reading 'pageSize')
    at _PatientsTableComponent.refreshGrid (app-table.component.ts:227:37)
    at _PatientsComponent.onSearch (patients.component.ts:27:20)
    at PatientsComponent_Template_app_patients_options_panel_search_2_listener (patients.component.html:3:47)
    at executeListenerWithErrorHandling (core.mjs:25777:12)
    at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (core.mjs:25809:18)
    at ConsumerObserver.next (Subscriber.js:87:25)
    at SafeSubscriber._next (Subscriber.js:56:22)
    at SafeSubscriber.next (Subscriber.js:29:12)
    at Subject.js:34:20
    at errorContext (errorContext.js:24:5)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.2
Node: 20.16.0
Package Manager: yarn 1.22.22
OS: linux x64

Angular: 18.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.2
@angular-devkit/build-angular   18.2.2
@angular-devkit/core            18.2.2
@angular-devkit/schematics      18.2.2
@schematics/angular             18.2.2
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.15.0
```

### Anything else?

![paginator_undefined](https://github.com/user-attachments/assets/94aa2016-ddf4-4033-9db3-a5e1b267b47e)

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
