### ISSUE TITLE
flaky perf test on Firefox

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5769]
This is currently the most common flake that I know of, can we disable the test on FF or do something else to prevent it from failing the builds several times a day?

```
Failures:
1) firefox extension should measure performance
  Message:
    Expected false to be truthy.
  Stack:
    Error: Failed expectation
        at assertEventsContainsName (benchpress/test/firefox_extension/spec.ts:13:17)
        at benchpress/test/firefox_extension/spec.ts:32:11
        at Array.forEach (native)
        at process._tickCallback (node.js:366:9)
2 specs, 1 failure
Finished in 132.347 seconds
Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
+killServer
+kill 3378
The command "./scripts/ci/build_and_test.sh ${MODE}" exited with 1.
```

**Comment by vicb** [comment]
Dup of #5611

**Comment by IgorMinar** [comment]
closing in favor of #5611
