### ISSUE TITLE
[Duplicate][Testing] Router returns wrong url after calling navigate(...) with RouterTestingHarness

### ISSUE THREAD

**Issue by someApprentice** [angular/angular#57769]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I created an issue about a month ago, and it was closed without further investigation while the problem is still persistent.

 #57250

Here is a brief description of the issue:
When testing navigation using RouterTestingHarness, the router returns an incorrect url.

```
@Component({
  selector: 'app-main',
  standalone: true,
  imports: [],
  template: `
    <p>
      main works!
    </p>

    <button (click)="go()">Go</button>
  `,
  styles: ``
})
export class MainComponent {
  constructor(private router: Router) {}

  go() {
    this.router.navigate(['routed']);
  }
}

@Component({
  selector: 'app-routed',
  standalone: true,
  imports: [],
  template: `
    <p>
      routed works!
    </p>
  `,
  styles: ``
})
export class RoutedComponent { }

describe('AppComponent', () => {
  let harness: RouterTestingHarness

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      providers: [
        provideRouter([
          { path: '', component: MainComponent },
          { path: 'routed', component: RoutedComponent }
        ])
      ]
    }).compileComponents();

    harness = await RouterTestingHarness.create();
  });

  it('should create the app', async () => {
    let component = await harness.navigateByUrl('', MainComponent);

    expect(component).toBeTruthy()
  });

  it('should navigate to routed page', async () => {
    await harness.navigateByUrl('', MainComponent);

    let hostElement: HTMLElement = harness.routeNativeElement!;
    let goButton: HTMLButtonElement = hostElement.querySelector('button')!;

    goButton.click();

    expect(TestBed.inject(Router).url).toEqual('/routed'); // Expected '/' to equal '/routed'.
  });
});
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/someApprentice/angular-testing-router-returns-wrong-url

### Please provide the exception or error you saw

```true
Expected '/' to equal '/routed'.
    at <Jasmine>
    at UserContext.<anonymous> (src/app/app.component.spec.ts:38:40)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:1)
at _next (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:17:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.3
Node: 22.8.0
Package Manager: npm 10.8.3
OS: linux x64

Angular: 18.2.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.3
@angular-devkit/build-angular   18.2.3
@angular-devkit/core            18.2.3
@angular-devkit/schematics      18.2.3
@schematics/angular             18.2.3
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
The router does not operate synchronously, so clicking the button won't immediately result in updating the URL.

If you await stability before the assertion, the tests pass:

```ts
await harness.fixture.whenStable();
```

Closing as working as expected.
