### ISSUE TITLE
alpha.51/52 regression: Typescript error - Type expected

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#5784]
```
[DiffingTSCompiler]: Typescript found the following errors:
  node_modules/angular2/src/core/metadata/di.d.ts (32, 12): Type expected.
Error: [DiffingTSCompiler]: Typescript found the following errors:
  node_modules/angular2/src/core/metadata/di.d.ts (32, 12): Type expected.
    at DiffingTSCompiler.doFullBuild (/Users/iminar/Dev/angular-cli-tests/sample-41/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:141:29)
    at DiffingTSCompiler.rebuild (/Users/iminar/Dev/angular-cli-tests/sample-41/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:71:18)
    at DiffingPluginWrapper.rebuild (/Users/iminar/Dev/angular-cli-tests/sample-41/node_modules/angular-cli/lib/broccoli/diffing-broccoli-plugin.js:86:45)
    at /Users/iminar/Dev/angular-cli-tests/sample-41/node_modules/angular-cli/node_modules/ember-cli/node_modules/broccoli/lib/api_compat.js:42:21
    at lib$rsvp$$internal$$tryCatch (/Users/iminar/Dev/angular-cli-tests/sample-41/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/iminar/Dev/angular-cli-tests/sample-41/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/iminar/Dev/angular-cli-tests/sample-41/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/iminar/Dev/angular-cli-tests/sample-41/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

This seems to be a bug in typescript 1.7.3 introduced in alpha.51. The d.ts that we produce now and publish to npm fail the type-check when compiled against an angular app.

originally reported as https://github.com/angular/angular-cli/pull/98

// @mhegazy - known issue? This seems related to the other changes I had to make in angular/angular to get us onto 1.7.3: https://github.com/angular/angular/commit/51cb7586e0851734f497a7f6d0f6d68d818a963e#diff-e9823adbf8e551100ff36e0a9b9607ecL184

**Comment by IgorMinar** [comment]
@robwormald pointed out that the issue doesn't happen with typescript@1.7.3 but only with typescript@1.6.2.

So we don't need to rush to cut a new alpha because by updating typescript people can resolve this issue locally.

**Comment by mhegazy** [comment]
@IgorMinar, The issue is that ["this" types](https://github.com/Microsoft/TypeScript/pull/4910) were introduced in TS 1.7.3; they are not a supported syntax in 1.6.*. Looking at the code base, this seems to be the only location of "this" types in the angular code base. so your change in #5784 should be sufficient.
There are some [documentation about the breaking change](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#changes-in-inferring-the-type-from-this), but we will try to think how we could mitigate issues like these in the future. sorry for the trouble.

**Comment by IgorMinar** [comment]
OK. Thanks!
