### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'c')

### ISSUE THREAD

**Issue by sonnyk22** [angular/angular#57886]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

No

### Description

Large-scale web-application is developed using Angular SSR v18.2.3.  Although, this app runs great during the local development, and it builds and runs fine via the `ng build`, it gives us this `console error` when we directly browse to any page via the browser's Url Address-Bar.  However, this error does not come up when we redirect to another page via the Routher.Navigate.

![image](https://github.com/user-attachments/assets/b1e9bd1b-0269-451c-957b-090fcdcff1ad)

The `initEventReplay` function in the Figure below gets called multiple times.
The first time call, the `earlyJsactionData` object has data, as seen below:
![image](https://github.com/user-attachments/assets/95a9e329-e41c-4fd3-a01d-3cde99bf9d3c)

but, on the next calls to the `initEventReplay` function, the `earlyJsactionData`  returns null, as seen below:
![image](https://github.com/user-attachments/assets/ce7e5e3c-152f-417c-9508-6ed6da18192e)

Please note that this comment in the `initEventReplay` function is clearly saying that it is related to the platform-server:
      `// This is set in packages/platform-server/src/utils.ts`

### Please provide the exception or error you saw

```true
`ERROR TypeError: Cannot read properties of undefined (reading 'c')
    at initEventReplay (core.mjs:36081:115)
    at core.mjs:36064:13
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:7025:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at _ZoneImpl.run (zone.js:111:43)
    at zone.js:2538:40
    at _ZoneDelegate.invokeTask (zone.js:402:33)
    at core.mjs:6706:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:6706:30)`
```

### Anything else?

Angular CLI: 18.2.3
Node: 18.19.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 18.2.0
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.3
@angular-devkit/build-angular   18.2.3
@angular-devkit/core            18.2.3
@angular-devkit/schematics      18.2.3
@angular/cli                    18.2.3
@angular/ssr                    18.2.4
@schematics/angular             18.2.3
rxjs                            7.8.0
typescript                      5.5.2
zone.js                         0.14.10

**Comment by sonnyk22** [comment]
Solved!  It was related to the PaceJs.
