### ISSUE TITLE
*ng-if="someNonBoolVar" fails (for me) in Dartium

### ISSUE THREAD

**Issue by kwalrath** [angular/angular#5818]
...but it's working for @tomplusplus. It should work, right? Because even if that would be an illegal expression in Dart, the HTML template language isn't Dart.

Background: We're both on Macs, using the same version of dart (1.13.0 stable channel). It's possible we're using different versions of Dartium, since I used to be running dev channel (first 1.14.0-dev.1.0, and then 1.14.0-dev.3.0) and might not have uninstalled dartium when I uninstalled all of homebrew's dart versions. How do you check the Dartium version?

To reproduce:
1. Download the files added in https://github.com/angular/angular.io/pull/448.
2. Run the example in Dartium. (Tom & I both used WebStorm 11's right-click on index.html, and then choose either **Run 'index.html'** or **Open in Browser > Dartium**.)

If you see only one line (Hero List), the sample is broken. If you see more lines, it's working.

For me, it's always broken in Dartium but works in Chrome. Changing `lib/hero_list_component.html` on line 8 to `<hero-detail *ng-if="selectedHero != null" ...></hero-detail>` fixes the problem.

Here's the error I see in Dartium:

```
EXCEPTION: Failed assertion: boolean expression must not be null in [selectedHero in HeroListComponent@7:13]
(program):1 EXCEPTION: Failed assertion: boolean expression must not be null in [selectedHero in HeroListComponent@7:13]
(program):1 ORIGINAL EXCEPTION: Failed assertion: boolean expression must not be null
(program):1 ORIGINAL STACKTRACE:
(program):1 #0      NgIf.ngIf= (package:angular2/src/common/directives/ng_if.dart:36:9)
#1      _HeroListComponent_0.detectChangesInRecordsInternal (package:developer_guide_intro/hero_list_component.template.dart:62:26)
#2      AbstractChangeDetector.detectChangesInRecords (package:angular2/src/core/change_detection/abstract_change_detector.dart:141:12)
#3      AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:115:10)
#4      AbstractChangeDetector._detectChangesInViewChildren (package:angular2/src/core/change_detection/abstract_change_detector.dart:224:12)
#5      AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:118:10)
#6      AbstractChangeDetector.detectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:101:10)
#7      ChangeDetectorRef_.detectChanges (package:angular2/src/core/change_detection/change_detector_ref.dart:209:14)
#8      ApplicationRef_.tick.<anonymous closure> (package:angular2/src/core/application_ref.dart:484:63)
#9      List.forEach (dart:core-patch/growable_array.dart:233)
#10     ApplicationRef_.tick (package:angular2/src/core/application_ref.dart:484:32)
#11     ApplicationRef_._loadComponent (package:angular2/src/core/application_ref.dart:454:10)
#12     ApplicationRef_.bootstrap.<anonymous closure>.<anonymous closure> (package:angular2/src/core/application_ref.dart:426:16)
#13     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:134:26)
#14     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
#15     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:134:14)
#16     NgZone._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:321:40)
#17     _rootRun (dart:async/zone.dart:903)
#18     _ZoneDelegate.run (dart:async/zone.dart:502)
#19     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#20     NgZone._runUnary (package:angular2/src/core/zone/ng_zone.dart:321:7)
#21     _CustomZone.runUnary (dart:async/zone.dart:810)
#22     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#23     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#24     _Future._completeWithValue (dart:async/future_impl.dart:376)
#25     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#26     NgZone._scheduleMicrotask.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:331:11)
#27     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
#28     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:48)
#29     _rootRun (dart:async/zone.dart:907)
#30     _ZoneDelegate.run (dart:async/zone.dart:502)
#31     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#32     _CustomZone.run (dart:async/zone.dart:802)
#33     _CustomZone.runGuarded (dart:async/zone.dart:708)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#36     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#37     _ScheduleImmediateHelper._handleMutation (dart:html:49298)
#38     MutationObserver._create.<anonymous closure> (dart:html:27545)

(program):1 ERROR CONTEXT:
(program):1 DartObject
index.html:1 Uncaught Unhandled exception:
EXCEPTION: Failed assertion: boolean expression must not be null in [selectedHero in HeroListComponent@7:13]
ORIGINAL EXCEPTION: Failed assertion: boolean expression must not be null
ORIGINAL STACKTRACE:
#0      NgIf.ngIf= (package:angular2/src/common/directives/ng_if.dart:36:9)
#1      _HeroListComponent_0.detectChangesInRecordsInternal (package:developer_guide_intro/hero_list_component.template.dart:62:26)
#2      AbstractChangeDetector.detectChangesInRecords (package:angular2/src/core/change_detection/abstract_change_detector.dart:141:12)
#3      AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:115:10)
#4      AbstractChangeDetector._detectChangesInViewChildren (package:angular2/src/core/change_detection/abstract_change_detector.dart:224:12)
#5      AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:118:10)
#6      AbstractChangeDetector.detectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:101:10)
#7      ChangeDetectorRef_.detectChanges (package:angular2/src/core/change_detection/change_detector_ref.dart:209:14)
#8      ApplicationRef_.tick.<anonymous closure> (package:angular2/src/core/application_ref.dart:484:63)
#9      List.forEach (dart:core-patch/growable_array.dart:233)
#10     ApplicationRef_.tick (package:angular2/src/core/application_ref.dart:484:32)
#11     ApplicationRef_._loadComponent (package:angular2/src/core/application_ref.dart:454:10)
#12     ApplicationRef_.bootstrap.<anonymous closure>.<anonymous closure> (package:angular2/src/core/application_ref.dart:426:16)
#13     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:134:26)
#14     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
#15     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:134:14)
#16     NgZone._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:321:40)
#17     _rootRun (dart:async/zone.dart:903)
#18     _ZoneDelegate.run (dart:async/zone.dart:502)
#19     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#20     NgZone._runUnary (package:angular2/src/core/zone/ng_zone.dart:321:7)
#21     _CustomZone.runUnary (dart:async/zone.dart:810)
#22     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#23     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#24     _Future._completeWithValue (dart:async/future_impl.dart:376)
#25     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#26     NgZone._scheduleMicrotask.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:331:11)
#27     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
#28     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:48)
#29     _rootRun (dart:async/zone.dart:907)
#30     _ZoneDelegate.run (dart:async/zone.dart:502)
#31     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#32     _CustomZone.run (dart:async/zone.dart:802)
#33     _CustomZone.runGuarded (dart:async/zone.dart:708)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#36     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#37     _ScheduleImmediateHelper._handleMutation (dart:html:49298)
#38     MutationObserver._create.<anonymous closure> (dart:html:27545)

ERROR CONTEXT:
Instance of '_Context'
#0      AbstractChangeDetector._throwError (package:angular2/src/core/change_detection/abstract_change_detector.dart:350:5)
#1      AbstractChangeDetector.detectChangesInRecords (package:angular2/src/core/change_detection/abstract_change_detector.dart:147:12)
#2      AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:115:10)
#3      AbstractChangeDetector._detectChangesInViewChildren (package:angular2/src/core/change_detection/abstract_change_detector.dart:224:12)
#4      AbstractChangeDetector.runDetectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:118:10)
#5      AbstractChangeDetector.detectChanges (package:angular2/src/core/change_detection/abstract_change_detector.dart:101:10)
#6      ChangeDetectorRef_.detectChanges (package:angular2/src/core/change_detection/change_detector_ref.dart:209:14)
#7      ApplicationRef_.tick.<anonymous closure> (package:angular2/src/core/application_ref.dart:484:63)
#8      List.forEach (dart:core-patch/growable_array.dart:233)
#9      ApplicationRef_.tick (package:angular2/src/core/application_ref.dart:484:32)
#10     ApplicationRef_._loadComponent (package:angular2/src/core/application_ref.dart:454:10)
#11     ApplicationRef_.bootstrap.<anonymous closure>.<anonymous closure> (package:angular2/src/core/application_ref.dart:426:16)
#12     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:134:26)
#13     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
#14     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:134:14)
#15     NgZone._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:321:40)
#16     _rootRun (dart:async/zone.dart:903)
#17     _ZoneDelegate.run (dart:async/zone.dart:502)
#18     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#19     NgZone._runUnary (package:angular2/src/core/zone/ng_zone.dart:321:7)
#20     _CustomZone.runUnary (dart:async/zone.dart:810)
#21     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#22     _Future._propagateToListeners (dart:async/future_impl.dart:585)
#23     _Future._completeWithValue (dart:async/future_impl.dart:376)
#24     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#25     NgZone._scheduleMicrotask.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:331:11)
#26     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:205:15)
#27     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:124:48)
#28     _rootRun (dart:async/zone.dart:907)
#29     _ZoneDelegate.run (dart:async/zone.dart:502)
#30     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#31     _CustomZone.run (dart:async/zone.dart:802)
#32     _CustomZone.runGuarded (dart:async/zone.dart:708)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#35     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#36     _ScheduleImmediateHelper._handleMutation (dart:html:49298)
#37     MutationObserver._create.<anonymous closure> (dart:html:27545)
```

**Comment by kwalrath** [comment]
It turns out that I was starting Dartium in checked mode, and Tom wasn't. (Tiny checkbox deep in WS's UI.)

But still... This was way too hard to pin down. And should it really fail in checked mode?

**Comment by yjbanov** [comment]
Yes, it should fail. `null`s in boolean expressions usually indicate a problem. That's why checked mode is checking for it.

**Comment by kwalrath** [comment]
But... this code is in the HTML, not in the Dart. My understanding is that the template code is not specific to JS or Dart (should be the same, no matter which language you're using), and thus Dart shouldn't be checking it.

**Comment by yjbanov** [comment]
Here's my attempt to explain the reasoning behind this:

The core concept in Angular is that you _bind_ your Dart code _to_ the HTML template. Constructs, such as `[property]="expression"` and `*ngIf` are implemented in Dart. The HTML template describes the structure of the UI and binding locations, but not the behavior. In fact at runtime these things disappear entirely. For example, pick an element where you have a property binding or an `*ng-if`. Then in the browser do "Inpect Element" on it. You will notice that they do not exist on the element. This is because these things live in Dart. In fact, Angular transformer internally turns these expressions to Dart before serving them to the browser. So it seems natural to me to adopt Dart semantics for properties, events, expressions and directives, including the semantics of checked mode, to all things that have no meaning in the results HTML DOM of the application.

However, we could certainly choose to see it differently and apply different semantics and behaviors. We'd have to be careful about performance though. Please reopen the bug with a counter-proposal for language semantics if my explanation isn't convincing.

**Comment by tomplusplus** [comment]
@yjbanov Your explanation is convincing. As a JS guy I really want to be able to use `null` in a boolean expression here, but if your writing Dart, then your writing Dart! I get it.
