### ISSUE TITLE
Problem with Angular client-side rendered application conversion into sever side rendering (SSR)

### ISSUE THREAD

**Issue by rushinagarkar** [angular/angular#59290]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

Yes

### Description

In an Angular client-side rendered application conversion into sever side rendering (SSR), I am facing the below issue after serving the local Angular setup project.

### Please provide the exception or error you saw

```true
`aws-amplify-angular` has been deprecated and will be removed in a future major version of `aws-amplify`. Please visit https://ui.docs.amplify.aws/ for more info on Amplify UI.
Unhandled Promise rejection: NotYetImplemented ; Zone: <root> ; Task: Promise.then ; Value: Error: NotYetImplemented
    at exports2.nyi (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:3720712)
    at bootstrapLazy (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:1:1110456)
    at C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:1:1009404
    at _ZoneDelegate.invoke (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6183618)
    at Zone2.run (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6176429)
    at C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6203264
    at _ZoneDelegate.invokeTask (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6184460)        
    at Zone2.runTask (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6177442)
    at drainMicroTaskQueue (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6187795)
    at invokeTask (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6186012) Error: NotYetImplemented
    at exports2.nyi (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:3720712)
    at bootstrapLazy (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:1:1110456)
    at C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:1:1009404
    at _ZoneDelegate.invoke (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6183618)
    at Zone2.run (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6176429)
    at C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6203264
    at _ZoneDelegate.invokeTask (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6184460)        
    at Zone2.runTask (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6177442)
    at drainMicroTaskQueue (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6187795)
    at invokeTask (C:\letek-project\tresorvino_fe_ssr\tresorvino_frontend\dist\tresorvino\server\main.js:2454:6186012)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.10
Node: 18.20.3 (Unsupported)
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1402.10
@angular-devkit/build-angular              14.2.10
@angular-devkit/core                       14.2.10
@angular-devkit/schematics                 14.2.10
@angular/cdk                               14.2.7
@angular/cli                               14.2.10
@angular/fire                              16.0.0
@angular/material                          14.2.7
@angular/platform-server                   14.3.0
@nguniversal/builders                      14.2.3
@nguniversal/express-engine                14.2.3
@nguniversal/module-map-ngfactory-loader   v8.2.6
@schematics/angular                        14.2.10
rxjs                                       7.4.0
typescript                                 4.6.4
```

**Comment by alan-agius4** [comment]
Angular version 14 is no longer under support. 

Please see: https://angular.dev/reference/releases
