### ISSUE TITLE
Using required input from other directive in template throws an error

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular#59311]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I want to use a computed property from a directive to my component using template reference, but it is throwing an error saying that input required but no value provided. 

```ts
import { Component, input, computed, Directive } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';

@Directive({
  selector: '[appTest]',
  exportAs: 'appTest',
})
export class AppTest {
  readonly appTest = input.required<string>();

  // using this classNames computed throwing error
  readonly classNames = computed(() => {
    return this.appTest();
  });
}

@Component({
  selector: 'app-hello',
  imports: [AppTest],
  template: `
      <div
           #app="appTest"
           [appTest]="name()"
           class="{{ 'sample' + (app.classNames() ? ' 1234' : ' 456')}}"
        >
           This is great
       </div>`,
})
export class HelloComponent {
  readonly name = input.required<string>();

  // using this classNames computed not throwing error
  readonly classNames = computed(() => {
    return this.name();
  });
}

@Component({
  selector: 'app-root',
  imports: [HelloComponent],
  template: `
    <h1>Hello from {{ name }}!</h1>
    <a target="_blank" href="https://angular.dev/overview">
      Learn more about Angular
    </a>
    <app-hello name="name" />
  `,
})
export class App {
  name = 'Angular';
}

bootstrapApplication(App);
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-prs3pysu?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
ERROR RuntimeError: NG0950: Input is required but no value is available yet. Find more at https://angular.dev/errors/NG0950
    at Object.computation (main.ts:13:17)
    at HelloComponent_Template (main.ts:20:53)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.0
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 19.0.0
... animations, build, cli, common, compiler, compiler-cli, core
... forms, platform-browser, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1900.0
@angular-devkit/core         19.0.0
@angular-devkit/schematics   19.0.0
@schematics/angular          19.0.0
rxjs                         7.8.1
typescript                   5.6.3
zone.js                      0.15.0
```

**Comment by JeanMeche** [comment]
Hi, 

This is a great example of a wrong assumption that templates are executed in the order you write them. 

Check the [compiled output of the compiler](https://jeanmeche.github.io/angular-compiler-output/?template=PGRpdgogxIXEhsSHICNhcHA9IsSLcFRlc3QixITEiMSIW8SQxJLElF3Ejm5hbWUoKcSWxJjEiGNsYXNzxI57eyAnc8ShcGxlJyArICjEkC7EqcSrc07EocSTxKQgP8SxIDEyMzTEuDrFiDQ1NicpfX3EpsSnPsSXxKfEhVRoaXMgxaAgZ3JlYXTFm8SHPC%2FEgXY%2B). 

```
      ɵɵclassMap('sample' + (app_r1.classNames() ? ' 1234' : ' 456'));
      ɵɵproperty('appTest', ctx.name());
```

The class bindings is executed before the property is set.

**Comment by sheikalthaf** [comment]
> Hi,
> 
> This is a great example of a wrong assumption that templates are executed in the order you write them.
> 
> Check the [compiled output of the compiler](https://jeanmeche.github.io/angular-compiler-output/?template=PGRpdgogxIXEhsSHICNhcHA9IsSLcFRlc3QixITEiMSIW8SQxJLElF3Ejm5hbWUoKcSWxJjEiGNsYXNzxI57eyAnc8ShcGxlJyArICjEkC7EqcSrc07EocSTxKQgP8SxIDEyMzTEuDrFiDQ1NicpfX3EpsSnPsSXxKfEhVRoaXMgxaAgZ3JlYXTFm8SHPC%2FEgXY%2B).
> 
> ```
>       ɵɵclassMap('sample' + (app_r1.classNames() ? ' 1234' : ' 456'));
>       ɵɵproperty('appTest', ctx.name());
> ```
> 
> The class bindings are executed before the property is set.

@JeanMeche Thanks for sharing the compiled output, Any specific reason why we are executing the `style` and `class` before property execution. 
My assumption is that interpolation only executes after property initialization. It is working fine with `ngClass` because it is executed after property initialization as per compiled. 

I did the refactor to avoid `ngClass` but after hitting this error, i feel like `ngClass` going to stay for now.

**Comment by pkozlowski-opensource** [comment]
As @JeanMeche mentioned, example code in the stackblitz makes lots of assumptions about the inner workings of Angular (those can change over time and break your application). More importantly, the code uses change detection ... (binding to an input) to drive more change detection (binding to a class). Those patterns are very hard to reason about and should be avoided.

I would suggest re-thinking interactions between the component and a directive in question - happy to help more given a real-life use case (hard to suggest something given an example code snippet).
