### ISSUE TITLE
ngRouteShim doesn't load before Map is Undefined for $router is thrown

### ISSUE THREAD

**Issue by mbordogna** [angular/angular#6187]
luckily, I found someone else had a route example, I modified to add the ng_route_shim.js. 
Using IE 10 or switch from edge to 10 in dev mode and you get the error at the bottom of this post.

The angular.run() method in the ng_route_shim.js doesn't run before the error occurs. 

http://embed.plnkr.co/HESGv4mzyihdyHfFKLJa/

HTML1300: Navigation occurred.
File: MxzjC99l8WDbuEu14ws2
ReferenceError: 'Map' is undefined
   at RouteRegistry (http://run.plnkr.co/plunks/MxzjC99l8WDbuEu14ws2/angular_1_router.js:1741:9)
   at routerFactory (http://run.plnkr.co/plunks/MxzjC99l8WDbuEu14ws2/angular_1_router.js:2476:3)
   at invoke (https://code.angularjs.org/1.4.6/angular.js:4476:7)
   at enforcedReturnValue (https://code.angularjs.org/1.4.6/angular.js:4328:7)
   at invoke (https://code.angularjs.org/1.4.6/angular.js:4476:7)
   at Anonymous function (https://code.angularjs.org/1.4.6/angular.js:4293:13)
   at getService (https://code.angularjs.org/1.4.6/angular.js:4435:11)
   at invoke (https://code.angularjs.org/1.4.6/angular.js:4464:9)
   at Anonymous function (https://code.angularjs.org/1.4.6/angular.js:7071:17)
   at forEach (https://code.angularjs.org/1.4.6/angular.js:336:11)
ReferenceError: 'Map' is undefined
   at RouteRegistry (http://run.plnkr.co/plunks/MxzjC99l8WDbuEu14ws2/angular_1_router.js:1741:9)
   at routerFactory (http://run.plnkr.co/plunks/MxzjC99l8WDbuEu14ws2/angular_1_router.js:2476:3)
   at invoke (https://code.angularjs.org/1.4.6/angular.js:4476:7)
   at enforcedReturnValue (https://code.angularjs.org/1.4.6/angular.js:4328:7)
   at invoke (https://code.angularjs.org/1.4.6/angular.js:4476:7)
   at Anonymous function (https://code.angularjs.org/1.4.6/angular.js:4293:13)
   at getService (https://code.angularjs.org/1.4.6/angular.js:4435:11)
   at invoke (https://code.angularjs.org/1.4.6/angular.js:4464:9)
   at Anonymous function (https://code.angularjs.org/1.4.6/angular.js:9127:11)
   at nodeLinkFn (https://code.angularjs.org/1.4.6/angular.js:8239:13)

**Comment by brandonroberts** [comment]
@mbordogna are you using ngRoute currently? ng_route_shim is optional

**Comment by mbordogna** [comment]
using the component router by actual app looks like this

  angular
    .module('app', [
        // Angular modules
        'ngComponentRouter',
        'ngRouteShim',
        'ngMaterial',

    ])

angular is the rtm 1.5 now an not the rc

with bower

 "dependencies": {
    "angular": "1.5.0-rc.0",
    "angular-resource": "1.5.0-rc.0",
    "angular-messages": "1.5.0-rc.0",
    "angular-sanitize": "1.5.0-rc.0",
    "angular-animate": "1.5.0-rc.0",
    "angular-aria": "1.5.0-rc.0",
    "angular-material": "~1.0.1"
  },

and this from npm

  "@angular/router": "0.0.1"

**Comment by brandonroberts** [comment]
@mbordogna ok, but you don't need the route shim unless your using the component router with an existing ngRoute configuration.

**Comment by mbordogna** [comment]
Forgot to mention that it works in n and n-1 chrome safari firefox, and
just ie11 its  a timing issue. not sure how to move the .run()
implementation earlier up the load process to correct the issue.
Also, without the shim,  same issue is observed, ie10- just prints out the
error to the console instead of breaking on the line

**Comment by mbordogna** [comment]
Crossed streams on the last email didn't see your reply before i sent it.

So then the issue is with the ngComponentRouter and not the shim. I thought
the shim was to fix the error, I get it now. So I am looking in the wrong
place to fix the error.

does the ng Component router support ie10, I can reconfigure the plunker to
get the same issue without the shim?

**Comment by mbordogna** [comment]
http://plnkr.co/edit/HESGv4mzyihdyHfFKLJa

here is the edit link to a clean component example that isolates the issue.
I believe its using angular 1.4, but I have the same issue in my code base
using 1.5. may or may not be much of a difference for this since the error
is the same either way.

btw, thanks for the quick reply and the help, I have been beating my head
on this for hours, if nothing else stopping me from the shim rabbit hole is
very much appreciated.
Mike

**Comment by brandonroberts** [comment]
Add the es6-shim to your script tags: <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.0/es6-shim.js"></script>

**Comment by mbordogna** [comment]
Brandon,
Thanks a bunch, that did it.
Glad it was something simple.
