### ISSUE TITLE
Error with route in production

### ISSUE THREAD

**Issue by mariomatar** [angular/angular#6211]
Hi juste create a little projet with 2 pages.

The problem is the views in components are not displayed

app.component.ts

import {Component} from 'angular2/core';
    import {RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';
    
    import {HomeComponent} from './home.components'
    import {CommandezComponent} from './commandez.components'
    import {ValidezComponent} from './validez.components'
    import {InformationService} from './information.service'
    
    @Component({
        selector: 'my-app',
        template:
            '<div class="container"><router-outlet></router-outlet></div>',
        directives: [ROUTER_DIRECTIVES],
        providers: [InformationService]
    })
    
    @RouteConfig([
        {path:'/',             name: 'Home',          component: HomeComponent,        useAsDefault: true},
        {path:'/commandez',    name: 'Commandez',     component: CommandezComponent},
        {path:'/validation',      name: 'Validez',       component: ValidezComponent}
    ])
    
    export class AppComponent {
    }

boot.ts

    import {bootstrap}    from 'angular2/platform/browser';
    import {ROUTER_PROVIDERS} from 'angular2/router';
    import {InformationService} from './information.service';
    import {AppComponent} from './app.component';
    
    bootstrap(AppComponent, [
        ROUTER_PROVIDERS, InformationService
    ]).catch(err => console.error(err));

index.html

    <html>
    <head>
        <title>MyApp</title>
    
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
    
        <link rel="stylesheet" href="src/assets/style/bootstrap.min.css" type="text/css">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="src/assets/style/animate.min.css" type="text/css">
        <link rel="stylesheet" href="src/assets/style/style.css" type="text/css">
    
        <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
        <script src="node_modules/systemjs/dist/system.src.js"></script>
        <script src="node_modules/rxjs/bundles/Rx.js"></script>
        <script src="node_modules/angular2/bundles/angular2.js"></script>
        <script src="node_modules/angular2/bundles/http.js"></script>
        <script src="node_modules/angular2/bundles/router.js"></script>
        <base href="/">

        <script>
            System.config({
                packages: {
                    app: {
                        format: 'register',
                        defaultExtension: 'js'
                    }
                }
            });
            System.import('app/boot')
                    .then(null, console.error.bind(console));
        </script>
    
        <html lang="fr">
    </html>
    </head>
    <body>
        <my-app>Loading...</my-app>
    </body>
    </html>

HomeComponent

    import {Component} from 'angular2/core';
    import {RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';
    import {NgForm}    from 'angular2/common';
    import {InformationService} from './information.service';
    @Component({
        selector: 'home',
        template: `
    
        <div class="header-content-inner">
            ....
        </div>
        `,
        directives: [ROUTER_DIRECTIVES]
    })
    export class HomeComponent {
        constructor(public informationService:InformationService) { }
        onSubmit() { }
    }

====> And it produce this HTML : 

    <html lang="fr">
    <head>
         Header ...
        <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
        <script src="node_modules/systemjs/dist/system.src.js"></script>
        <script src="node_modules/rxjs/bundles/Rx.js"></script>
        <script src="node_modules/angular2/bundles/angular2.js"></script>
        <script src="node_modules/angular2/bundles/http.js"></script>
        <script src="node_modules/angular2/bundles/router.js"></script>
        <base href="/">

        <script>
            System.config({
                packages: {
                    app: {
                        format: 'register',
                        defaultExtension: 'js'
                    }
                }
            });
            System.import('app/boot')
                    .then(null, console.error.bind(console));
        </script>
    </head>

    <body>
        <my-app><div class="container"><router-outlet></router-outlet></div></my-app>
    </body>
    </html>

No error in console

So router-outlet does not works ?

Is there a problem in my code ?

gulpfil.js

    var gulp = require('gulp');
    
    var plugins = require('gulp-load-plugins')();
    var del = require('del');
    var plumber = require('gulp-plumber');
    var rename = require('gulp-rename');
    var tsc = require('gulp-typescript');
    var sourcemaps = require('gulp-sourcemaps');
    var path = require('path');
    var fs = require('fs');
    
    
    var PATHS = {
        src: {
            root: 'src',
            ts: 'app/*.ts',
            html: '*.html',
            css: 'src/assets/style/*.css',
            fonts: 'src/assets/fonts/*.*'
        },
        lib: [
            'angular2/bundles/*.js',
            'angular2/bundles/*.map',
            'systemjs/dist/*.js',
            'systemjs/dist/*.map',
            'es6-shim/*.js',
            'rxjs/bundles/*.js'
        ]
    };
    
    var tsProject = tsc.createProject('tsconfig.json', {typescript: require('typescript')});
    
    gulp.task('clean', function(done) {
        del(['dist'], done);
    });
    
    gulp.task('ts', function () {
        return gulp.src(PATHS.src.ts)
            .pipe(plumber())
            .pipe(sourcemaps.init())
            .pipe(tsc(tsProject))
            .pipe(sourcemaps.write('source'))
            .pipe(gulp.dest('dist/app/'));
    });
    
    gulp.task('html', function () {
        return gulp.src(PATHS.src.html)
            .pipe(gulp.dest('dist'));
    });
    
    gulp.task('css', function () {
        return gulp.src(PATHS.src.css).pipe(gulp.dest('dist/src/assets/style'));
    });
    
    gulp.task('fonts', function () {
        return gulp.src(PATHS.src.fonts).pipe(gulp.dest('dist/src/assets/fonts'));
    });
    
    gulp.task('libs', function () {
        var size = require('gulp-size');
        return gulp.src(PATHS.lib, { cwd : 'node_modules/**' })
            .pipe(size({showFiles: true, gzip: true}))
            .pipe(gulp.dest('dist/node_modules'));
    });
    
    gulp.task('default', ['ts', 'css', 'fonts', 'html', 'libs']);

**Comment by rosendi** [comment]
Try to reproduce it in a plunk.

**Comment by mariomatar** [comment]
may I give you a zip ?
[myapp.zip](https://github.com/angular/angular/files/75985/myapp.zip)

**Comment by rosendi** [comment]
Next time try to isolate the issue and provide a plunk. But in your case I didn't find a serve task like:

```
let connect = require('gulp-connect');

gulp.task('serve',() => {
  connect.server({ port: '8000', root: 'dist' });
})
```

With this task it works as expected.

Without that task you should change the base href from `"/"` to `""`, since if you open `index.html` directly in a browser the pathname would be something like `"/Downloads/myapp/dist/index.html"` and as you can see it doesn't equal to `"/"`. That's why you have to use a relative base href `""`.

The last point is that without a serve task you can't use the push location strategy, only the hash location strategy will pass due the security reasons.

**Comment by mariomatar** [comment]
Thank you for your respons. It's clean !

**Comment by mariomatar** [comment]
I have a question, I need to use this app inside apache server

so I user this url
    <base href="">

But I have a lot exception in JS consol : 

EXCEPTION: SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 
angular2.dev.js:23514 Error: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///Users/maryo/prive/dev/app/dist/index.html' cannot be created in a document with origin 'null'.
    at Error (native)
    at PlatformLocation.pushState (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2018:21)
    at PathLocationStrategy.pushState (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:1222:30)
    at Location.go (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:1764:29)
    at file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2836:27
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:5719:32)
    at zoneBoundFn (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
    at lib$es6$promise$$internal$$tryCatch (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1511:16)
    at lib$es6$promise$$internal$$invokeCallback (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1523:17)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at Zone.bind (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:109:48)
    at bindArguments (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:980:29)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1000:37)
    at RootRouter.commit (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2835:27)
    at file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2627:26
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:5719:32)
    at zoneBoundFn (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:111:19)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at Zone.bind (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:109:48)
    at bindArguments (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:980:29)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1000:37)
    at file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2625:56
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:5719:32)
    at zoneBoundFn (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
    at lib$es6$promise$$internal$$tryCatch (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1511:16)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at Zone.bind (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:109:48)
    at bindArguments (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:980:29)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1000:37)
    at RootRouter.Router._navigate (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2621:10)
    at file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2598:24
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:5719:32)
    at zoneBoundFn (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:111:19)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at Zone.bind (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:109:48)
    at bindArguments (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:980:29)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1000:37)
    at file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2594:73
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at Zone.run (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:5719:32)
    at zoneBoundFn (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
    at lib$es6$promise$$internal$$tryCatch (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1511:16)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at Zone.bind (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:109:48)
    at bindArguments (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:980:29)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1000:37)
    at RootRouter.Router.navigateByUrl (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2591:64)
    at new RootRouter (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2821:12)
    at routerFactory (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/router.dev.js:2956:22)
    at Injector._instantiate (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:11929:19)
    at Injector._instantiateProvider (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:11859:21)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at Zone.bind (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:109:48)
    at bindArguments (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:980:29)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:1000:37)
    at DynamicComponentLoader_.loadAsRoot (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:14530:49)
    at di_1.provide.useFactory (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:14672:39)
    at Injector._instantiate (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:11926:19)
    at Injector._instantiateProvider (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:11859:21)
    at Injector._new (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:11849:19)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at NgZone._createInnerZone (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:5707:39)
    at new NgZone (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:5573:32)
    at createNgZone (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:14693:12)
    at PlatformRef_.application (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:14768:31)
    at Object.bootstrap (file:///Users/maryo/prive/dev/app/dist/node_modules/angular2/bundles/angular2.dev.js:25054:64)
    at execute (file:///Users/maryo/prive/dev/app/dist/app/boot.js:18:23)
    at ensureEvaluated (file:///Users/maryo/prive/dev/app/dist/node_modules/systemjs/dist/system.src.js:3078:26)
    at Object.execute (file:///Users/maryo/prive/dev/app/dist/node_modules/systemjs/dist/system.src.js:3196:13)

**Comment by pkozlowski-opensource** [comment]
Sounds like a support question that should be asked on a dedicated support channel: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
