### ISSUE TITLE
Use inject in nodejs

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular#6319]
When I run unit test with nodejs and use inject in beforeEach then throw me an error:
```
 TypeError: Cannot read property 'getXHR' of null
        at _runtimeCompilerBindings (angular2/src/testing/test_injector.ts:129:32)
        at Object.createTestInjectorWithRuntimeCompiler (angular2/src/testing/test_injector.ts:141:48)
        at Object.<anonymous> (angular2/src/testing/testing.ts:247:20)
```

becouse DOM is null in nodejs :(
```
function _runtimeCompilerBindings() {
  return [
    provide(XHR, {useClass: DOM.getXHR()}),
    COMPILER_PROVIDERS,
  ];
}
```

**Comment by tamascsaba** [comment]
Reference: https://github.com/angular/angular/issues/6034
