### ISSUE TITLE
How to configure an application linked to the TypeScript sources of Angular2

### ISSUE THREAD

**Issue by templth** [angular/angular#6323]
Hi all,

First of all, sorry if my question is a silly one!

I would like to contribute implement a patch for a small bug / strange behavior I saw. My problem is that I would like to be comfortable to implement this. I mean having a small project that shows the problem linked with the TypeScript sources of Angular2 and when I update something it's taken into account without having to build the whole framework.

So my question actually is: how to link the TypeScript sources of Angular2 to this application? I'm using the `tsc` module to compile TypeScript files. I did some tries. The TypesScript files of Angular2 are compiled into JavaScript but have some JavaScript errors when loading my test application. The remaining error I have is:

```
Error: Cannot read property 'resolve' of undefined(…)Promise.reject (async)g @ system.src.js:4597(anonymous function) @ system.src.js:4597y @ system.src.js:4597w @ system.src.js:4597p @ system.src.js:4597h @ system.src.js:4597(anonymous function) @ system.src.js:4597run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305Promise.resolve (async)(anonymous function) @ angular2-polyfills.js:235asap @ angular2-polyfills.js:1232scheduleMicrotask @ angular2-polyfills.js:250(anonymous function) @ angular2-polyfills.js:242lib$es6$promise$$internal$$fulfill @ angular2-polyfills.js:1454lib$es6$promise$$internal$$resolve @ angular2-polyfills.js:1435resolvePromise @ angular2-polyfills.js:1559f @ system.src.js:4597run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111
extensions::uncaught_exception_handler:8 Error in event handler for extension.onRequest: TypeError: Q.updateOutliners is not a function
    at Object.x.Messenger.handlers.globalDataChanged (chrome-extension://pnhplgjpclknigjpccbcnmicgcieojbh/js/content/diigolet.js:312:493)
    at Object.x.Messenger.onMessage (chrome-extension://pnhplgjpclknigjpccbcnmicgcieojbh/js/content/diigolet.js:309:171)
    at chrome-extension://pnhplgjpclknigjpccbcnmicgcieojbh/js/content/diigolet.js:308:74handler @ extensions::uncaught_exception_handler:8exports.handle @ extensions::uncaught_exception_handler:100EventImpl.dispatch_ @ extensions::event_bindings:376EventImpl.dispatch @ extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94messageListener @ extensions::messaging:179target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:387target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94EventImpl.dispatch_ @ extensions::event_bindings:371EventImpl.dispatch @ extensions::event_bindings:393target.(anonymous function) @ extensions::SafeBuiltins:19publicClass.(anonymous function) @ extensions::utils:94dispatchOnMessage @ extensions::messaging:310
```

Here is the content of my `index.html` file:

```
<!DOCTYPE html>
<html>
  <head>
    <script>document.write('<base href="' + document.location + '" />');</script>
    <title>Angular 2 Tests</title>
    <script src="https://code.angularjs.org/2.0.0-beta.0/angular2-polyfills.js"></script>
    <script src="https://rawgithub.com/systemjs/systemjs/0.19.6/dist/system.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.0/Rx.js"></script>
    <script>
      System.config({
        packages: {        
          angular2: {
            format: 'register',
            defaultExtension: 'js'
          },
          src: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
      });
      System.import('src/boot')
            .then(null, console.error.bind(console));
    </script>
  </head>
  <body>
    <test-app>Loading...</test-app>
  </body>
</html>
```

If someone could give me some hints or link(s) to some docs, it would be awesome. Thanks a lot by advance!

Thierry

**Comment by alexeagle** [comment]
So you want to modify the angular sources, and then include a reproduction of a problem in a minimal application that's observable when run against that version of angular?
This is not really easy right now. Our build system is complicated and can't be reproduced with a simple `tsc` command line.

**Comment by alexeagle** [comment]
please re-open if you're still looking for guidance.
