### ISSUE TITLE
Operating on classes doesn't work with SVG elements in IE 11

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#6327]
That means `NgClass` is broken.

The reason is annoyingly that IE 11 [doesn't support `classList` on SVG elements](https://connect.microsoft.com/IE/feedback/details/1046039/classlist-not-working-on-svg-elements), so `add`ing to `undefined` in the BrowserDomAdapter throws.

**Comment by Tragetaschen** [comment]
Not only that, but also `hasClass` throws, so `NgSwitch` is affected as well:

```
   at BrowserDomAdapter.prototype.hasClass (http://localhost:4145/lib/angular2/angular2.dev.js:23744:7)
   at DomRenderer_.prototype.animateNodeEnter (http://localhost:4145/lib/angular2/angular2.dev.js:15273:7)
   at DomRenderer.prototype.animateNodesEnter (http://localhost:4145/lib/angular2/angular2.dev.js:15134:9)
   at DomRenderer.prototype.attachFragmentAfterElement (http://localhost:4145/lib/angular2/angular2.dev.js:15141:7)
   at AppViewManager_.prototype._attachRenderView (http://localhost:4145/lib/angular2/angular2.dev.js:11326:9)
   at AppViewManager_.prototype._createViewInContainer (http://localhost:4145/lib/angular2/angular2.dev.js:11311:9)
   at AppViewManager_.prototype.createEmbeddedViewInContainer (http://localhost:4145/lib/angular2/angular2.dev.js:11288:7)
   at ViewContainerRef_.prototype.createEmbeddedView (http://localhost:4145/lib/angular2/angular2.dev.js:6632:7)
   at SwitchView.prot […]
```

**Comment by Tragetaschen** [comment]
There is a shim in [eligrey/classList.js](https://github.com/eligrey/classList.js), but there isn't a release yet (at least in bower)

**Comment by woppa684** [comment]
NgIf is affected as well by the way ...

**Comment by zoechi** [comment]
@woppa684 Can you please provide more details (Plunker, error message, ...)

**Comment by woppa684** [comment]
https://plnkr.co/edit/QHAI7sPG0dwZAQriSmuI?p=preview

```
EXCEPTION: TypeError: Unable to get property 'contains' of undefined or null reference in [test==='yeah' in function App() {
@1:9]
ORIGINAL EXCEPTION: TypeError: Unable to get property 'contains' of undefined or null reference
ORIGINAL STACKTRACE:
TypeError: Unable to get property 'contains' of undefined or null reference
   at t.prototype.hasClass (https://code.angularjs.org/2.0.0-beta.0/angular2.min.js:17:29514)
   at t.prototype.animateNodeEnter (https://code.angularjs.org/2.0.0-beta.0/angular2.min.js:11:27290)
   at t.prototype.animateNodesEnter (https://code.angularjs.org/2.0.0-beta.0/angular2.min.js:11:23807)
   at t.prototype.attachFragmentAfterElement (https://code.angularjs.org/2.0.0-beta.0/angular2.min.js:11:23964)
   at t.prototype._attachRenderView (https://code.angularjs.org/2.0.0-beta.0/angular2.min.js:8:23777)
   at t.prototype._createViewInContainer (https://code.angularjs.org/2.0.0-beta.0/angular2.min.js:8:23456)
   at t.prototype.createEmbeddedViewInContainer (https://code.angularjs.org/2.0.
```

**Comment by theFifthElf** [comment]
I'm encountering this same error.

**Comment by theFifthElf** [comment]
A small shim like this gets around the the missing classList on IE11.

if (!("classList" in document.createElementNS("http://www.w3.org/2000/svg","g"))) {
       var descr = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'classList');
       Object.defineProperty(SVGElement.prototype, 'classList', descr);
}

I'm not suggestiing it's a solution. The more interesting thing is that with that shim in place the SVG rendering works but the performance is very slow.

**Comment by theFifthElf** [comment]
... but setting enableProdMode makes a huge difference :) !!

**Comment by dozingcat** [comment]
Renderer.detachView throws an exception attempting to remove SVG elements in IE11 for the same reason.

**Comment by klinki** [comment]
I have the same issue with `ngFor`

http://plnkr.co/edit/Pllxbksk2pSYh8yTduoa?p=preview

**Comment by evgeniynet** [comment]
me too
even Im using node_modules/angular2/es6/dev/src/testing/shims_for_IE.js

**Comment by epascales** [comment]
Anyone have working shims fo this issue or any workaround?

**Comment by Tragetaschen** [comment]
The shim in the third comment works
```
"dependencies": {
  "classlist.js": "1.1.20150312"
}
```

**Comment by vicb** [comment]
shim available

**Comment by Tragetaschen** [comment]
Will there be documentation that enlists all the shims that angular2 needs for full browser support or certain scenarios and doesn't ship by itself?

Issues like this are hard to figure out when running into and all pieces of information are scattered through a lot of places at the moment.

**Comment by vicb** [comment]
Could you please check if there is an issue opened in angular/angular.io (the doc repo) and create one if none exists ? Thanks.

**Comment by kylecordes** [comment]
I just had this issue pointed out to me (because we headed in a project) and it seems like a good place to add another of my amazingly boring browser support comments:

Here is a reasonable and obvious browser support policy. Maybe the Angular project will end up with something vaguely like this.

Figure out what list the browsers to support.
* Put that list in an obvious and findable place.
* Make the published first party examples (anything on angular.io or *.angular.io) shipped by default with the correct set of polyfills in place to support that list of browsers.
* Support should mean that all of the features work, not that some of the features work and others will need application authors to stumble across a broken feature, find it in a list somewhere, and add polyfills as they rediscover the needs.
* Make the CLI configure projects by default to support that list of browsers.
* Include some documentation or settings or CLI features or all of the above, to optionally strip out some of those polyfils to reduce the size for applications that don't need to support the standard supported list of browsers.

**Comment by pkozlowski-opensource** [comment]
@kylecordes the documentation for all the points you are raising is currently work in progress. cc @mlaval @wardbell
