### ISSUE TITLE
angular router: why dont we have redirectTo option for AsyncRoute

### ISSUE THREAD

**Issue by mkrishna4u** [angular/angular#6333]
It is a very common scenario that if we are working on the parent child view then i generally want to load component lazily but also i want to redirect to another child url so that i can maintain the complete state. So redirectTo option should be supported for all kind of routes including AsyncRoute.

Like example: 
TopLevel Menu Items: home, admin
Child menu items of admin: security-management, system-config

If view is associated with all the menu items and all menu items are part of AsyncRoute then i would like to load admin view first and redirect to system-config view automatically.

Example code:
--------------------------------------
@Component({
selector: 'main-dashboard',
templateUrl: 'app/main-dashboard.html',
directives: [MainNavbar, ROUTER_DIRECTIVES]
})
@RouteConfig([ 
new AsyncRoute({
path: '/admin',
loader: () => System.import('app/admin/admin').then(m => m.Admin),
name: 'Admin'
})
])
export class MainDashboard {
constructor(router: Router, location: Location) { 
}

}
------------------------------------
@RouteConfig([ 
new AsyncRoute({
path: '/securitymgmt',
loader: () => System.import('app/admin/security-mgmt/security-mgmt').then(m => m.SecurityMgmt),
name: 'SecurityMgmt',
useAsDefault: true
}),
new AsyncRoute({
path: '/systemconfig',
loader: () => System.import('app/admin/system-config/system-config').then(m => m.SystemConfig),
name: 'SystemConfig'
})
])
export class Admin {

}
---------------------------
@Component({
selector: 'admin-security-mgmt',
templateUrl: 'app/admin/security-mgmt/security-mgmt.html',
directives: []
})
export class SecurityMgmt {

}

**Comment by zoechi** [comment]
Please wrap source code with ``` for proper formatting and better readability.

**Comment by ocombe** [comment]
Agreed that would help also when you have to call a WS to check for something before redirecting to another route (kinda like the "resolve" from the angular 1 router)

**Comment by mkrishna4ua** [comment]
i think redirectTo option should be available for all type of angular routes.

**Comment by nolazybits** [comment]
+1.
Just faced the same problem
```typescript
@RouteConfig([
    //  default redirects to login
    { path: '/', redirectTo: ['Login'] },
    //  login parent path
    {
        path: '/login',
        loader: () => System.import('app/features/login/login.component').then(
            (module: systemjs.Module) => (<any>module).LoginComponent
        ),
        as: 'Login'
    }
])
```

throws
```
Potentially unhandled rejection [2] TypeError: Cannot set property 'reuse' of undefined
    at http://localhost:7855/libs/angular2/bundles/router.dev.js:2638:37
    at tryCatchReject (http://localhost:7855/libs/systemjs/dist/system-polyfills.src.js:1257:30)
    at runContinuation1 (http://localhost:7855/libs/systemjs/dist/system-polyfills.src.js:1216:4)
    at Fulfilled.when (http://localhost:7855/libs/systemjs/dist/system-polyfills.src.js:1004:4)
    at ContinuationTask.run (http://localhost:7855/libs/systemjs/dist/system-polyfills.src.js:1114:24)
    at Scheduler._drain (http://localhost:7855/libs/systemjs/dist/system-polyfills.src.js:171:19)
    at Scheduler.drain (http://localhost:7855/libs/systemjs/dist/system-polyfills.src.js:136:9)
    at MutationObserver.run (http://localhost:7855/libs/systemjs/dist/system-polyfills.src.js:342:4)
    at Zone.run (http://localhost:7855/libs/angular2/bundles/angular2-polyfills.js:138:17)
    at MutationObserver.zoneBoundFn (http://localhost:7855/libs/angular2/bundles/angular2-polyfills.js:111:19)(anonymous function) @ system-polyfills.src.js:214report @ system-polyfills.src.js:241flush @ system-polyfills.src.js:263arguments.(anonymous function) @ angular2-polyfills.js:493(anonymous function) @ angular2-polyfills.js:118run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111
```

**Comment by vicb** [comment]
obsolete - old router
