### ISSUE TITLE
MockBackend does not catch missing wiring if not properly configured

### ISSUE THREAD

**Issue by krimple** [angular/angular#6375]
If you incorrectly wire your tests by providing MockBackend, and then injecting using inject(MockBackend), it will not properly handle mock connections but will not throw an error. Hard to detect problems in your tests when you do it wrong.

Given 

```
beforeEach(() => {
    let injector: Injector = Injector.resolveAndCreate([
      HTTP_PROVIDERS,
      BaseRequestOptions,
      MockBackend,   // this is in error
      provide(XHRBackend, {useClass: MockBackend}),
      BlogService
    ]);
```

This properly sets up mock responses:

```
// because you ask for the right one
let mockBackend: MockBackend = injector.get(XHRBackend);
```

However, this silently ignores your test conditions:

```
// grabs the accidentally provided one
let mockBackend: MockBackend = injector.get(MockBackend);
```

If you inject the mock directly, the code below seems to be silently is ignored:

```
 mockBackend.connections.subscribe((c) => {
        c.mockRespond(...)
 });
```

Which causes the actual thing under test not to receive a subscription, so no expectations are fired. That means you might get a falsely passing test when in fact it is logically in error.

Conversely, the whole thing works if you properly call the inject:

```
let mockBackend = injector.get(XHRBackend);
```

It works.  Also if you properly set up the injector by NOT providing MockBackend, it will detect it and throw the appropriate error:

```
Error: No provider for MockBackend!
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (https://code.angularjs.org/2.0.0-beta.0/angular2.js:8080:21)
    at NoProviderError.AbstractProviderError [as constructor] (https://code.angularjs.org/2.0.0-beta.0/angular2.js:1609:14)
    at new NoProviderError (https://code.angularjs.org/2.0.0-beta.0/angular2.js:1633:14)
    at Injector._throwOrNull (https://code.angularjs.org/2.0.0-beta.0/angular2.js:12009:15)
    at Injector._getByKeyDefault (https://code.angularjs.org/2.0.0-beta.0/angular2.js:12054:19)
    at Injector._getByKey (https://code.angularjs.org/2.0.0-beta.0/angular2.js:12002:21)
    at Injector.get (https://code.angularjs.org/2.0.0-beta.0/angular2.js:11804:19)
    at Object.<anonymous> (http://run.plnkr.co/LJ70AKLPF7t8X4Ju/src/myservice.spec.ts!transpiled:31:40)
    at attemptSync (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1886:24)
    at QueueRunner.run (https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.js:1874:9)
```

I would prefer the MockBackend detects that it doesn't have mock connections available to it and then throws a similar error, is that possible? It seems to throw one when it can't get a connection, but not on the connections.mockRespond when improperly wired.

**Comment by krimple** [comment]
See http://plnkr.co/edit/vUjNLCVG8SVRYK6ZnKG0 for a gist where this silently passes tests expecting a mocked response. comment out the MockBackend from the provide and you'll see the failure case that is more easily detected.

**Comment by krimple** [comment]
I've updated my plunker with a specific failed test.  It is a check to make sure the _backend provided by the injector is the same instance as one fetched by injecting it directly (i.e. making it a singleton to the injector).  I don't know if this is possible, but it should be a good enhancement to finding a very nasty testing mistake otherwise...

**Comment by vijayaragavendiran** [comment]
I am new to testing angular2 . I am using angular-seed project from git huh.
I wrote a simple observable and trying to test the observable. But I am getting below error. Please giude me . I dont have any idea.
 Error: No provider for MockBackend! (line 777)
 Error: No provider for NameListService! (line 777)

Spec
====
import {NameListService} from './name-list.service';
import {Http} from 'angular2/http';
import {
  describe,
  expect,
  beforeEach,
  it,
  inject,
  injectAsync,
  beforeEachProviders
} from 'angular2/testing';
import {HTTP_PROVIDERS, BaseRequestOptions, XHRBackend, Response,ResponseOptions} from 'angular2/http';
import {provide} from 'angular2/core';
import {MockBackend,MockConnection} from 'angular2/http/testing';

export function main() {
  describe('NameList Service', () => {

    beforeEachProviders(() => {
      HTTP_PROVIDERS,
      NameListService,
      BaseRequestOptions,
       provide(Http, {
          useFactory: (backend: MockBackend, defaultOptions: BaseRequestOptions) => {
            return new Http(backend, defaultOptions);
          },
          deps: [MockBackend, BaseRequestOptions]
        });
    });
    beforeEach(inject([MockBackend], (backend: MockBackend) => {
      const baseResponse = new Response(new ResponseOptions({body: 'got response'}));
      backend.connections.subscribe((c: MockConnection) => c.mockRespond(baseResponse));
    }));

    /*beforeEach(() => {
      nameListService = new NameListService(http);
    });*/

    it('should return response when subscribed to getUsers',
      inject([NameListService], (nameListService: NameListService) => {
        nameListService.getBlogs().subscribe((res: Response) => {
          expect(res.text()).toBe('got response');
        });
      })
    );

  });
}

**Comment by samvloeberghs** [comment]
I'm feeling the same pain. I don't seem to be able to mock out a err case when testing against HTTP

**Comment by thiagoh** [comment]
Same here. 

```
Error: No provider for MockBackend!
[1] 	Error: DI Exception
[1] 	    at NoProviderError.BaseException [as constructor] (/data/dev/javascript/xblood/node_modules/@angular/core/src/facade/exceptions.js:17:23)
[1] 	    at NoProviderError.AbstractProviderError [as constructor] (/data/dev/javascript/xblood/node_modules/@angular/core/src/di/reflective_exceptions.js:39:16)
[1] 	    at new NoProviderError (/data/dev/javascript/xblood/node_modules/@angular/core/src/di/reflective_exceptions.js:75:16)
[1] 	    at ReflectiveInjector_._throwOrNull (/data/dev/javascript/xblood/node_modules/@angular/core/src/di/reflective_injector.js:776:19)
[1] 	    at ReflectiveInjector_._getByKeyDefault (/data/dev/javascript/xblood/node_modules/@angular/core/src/di/reflective_injector.js:804:25)
[1] 	    at ReflectiveInjector_._getByKey (/data/dev/javascript/xblood/node_modules/@angular/core/src/di/reflective_injector.js:767:25)
[1] 	    at ReflectiveInjector_.get (/data/dev/javascript/xblood/node_modules/@angular/core/src/di/reflective_injector.js:576:21)
[1] 	    at eval (/data/dev/javascript/xblood/node_modules/@angular/core/testing/test_injector.js:46:71)
[1] 	    at Array.map (native)
[1] 	    at TestInjector.execute (/data/dev/javascript/xblood/node_modules/@angular/core/testing/test_injector.js:46:29)
[1] 	    at eval (/data/dev/javascript/xblood/node_modules/@angular/core/testing/test_injector.js:135:55)
[1] 	    at Object.eval (/data/dev/javascript/xblood/node_modules/@angular/core/testing/testing.js:98:26)
[1] 	    at g (/data/dev/javascript/xblood/node_modules/core-js/client/shim.min.js:8:10176)
[1] 	    at /data/dev/javascript/xblood/node_modules/core-js/client/shim.min.js:8:10298
[1] 	    at MutationObserver.k (/data/dev/javascript/xblood/node_modules/core-js/client/shim.min.js:8:14321)
[1] 	    at ZoneDelegate.invoke (/data/dev/javascript/xblood/node_modules/zone.js/dist/zone.js:323:29)
[1] 	    at Zone.runGuarded (/data/dev/javascript/xblood/node_modules/zone.js/dist/zone.js:230:48)
[1] 	    at MutationObserver.<anonymous> (/data/dev/javascript/xblood/node_modules/zone.js/dist/zone.js:206:30)
```

**Comment by dennispark** [comment]
in RC4,

`
    beforeEach(() => {
        addProviders([MockBackend, BaseRequestOptions]);
    }

    .....
   // then in the it block:
 it('should login', async(inject([UserService, MockBackend], (serviceInstance: UserService, backend: MockBackend) => {
        const mockedResponse = new ResponseOptions({ body: '{"token": "eyJhb$2dG^cc1giOi"}'});

        backend.connections.subscribe((connection: MockConnection) => {
            if(connection.request.url.endsWith('api/authenticate')) {
                connection.mockRespond(new Response(mockedResponse));
            }
        });
        expect(serviceInstance.isLoggedIn()).toBe(false);
        serviceInstance.login({user: 'user1', password: 'xyz'}).subscribe(
            data => {
                expect(serviceInstance.isLoggedIn()).toBe(true);
            },
            err => {
                console.log(err);
                expect(serviceInstance.isLoggedIn()).toBe(false);
            },
            () => {
                expect(serviceInstance.isLoggedIn()).toBe(true);
            }
        );
`

works for me.

**Comment by frankcarey** [comment]
nothing in `.subscribe()` seems to run when I'm testing this locally

**Comment by patrickoneill46** [comment]
I am having a similar problem in my tests. Trying to log out when a connection is made but I can see the connection callback is never even being run. Pulling my hair out! I'm running off angular 2.0.0 tho

`   beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        TradeService,
        { provide: XHRBackend, useClass: MockBackend},
        {
           provide: Http, useFactory: (backend, options) => {
             return new Http(backend, options);
           },
           deps: [MockBackend, BaseRequestOptions]
        },
        MockBackend,
        BaseRequestOptions
      ]
    });
  });

  it('should ...', inject([XHRBackend, TradeService], (mockBackend, service: TradeService) => {

    mockBackend.connections.subscribe(
      (connection: MockConnection) => {

        console.log('connection made');
        connection.mockRespond(new Response(
          new ResponseOptions({
              body: [
                {
                  id: 26,
                  contentRendered: "<p><b>Hi there</b></p>",
                  contentMarkdown: "*Hi there*"
                }]
            }
          )));
      });

      service.placeTrade({some: 'trade'}).subscribe((response) => {
        expect(response).toBeTruthy();
      });
  }));
`

**Comment by alxhub** [comment]
This is truly an issue, and you're right, it's hard to debug if you've set it up wrong.

One workaround is to use `{provide: XHRBackend, useExisting: MockBackend}` instead of `useClass`. This ensures that only one instance of `MockBackend` is ever created.

The right solution, though, is for `MockBackend` to come with a module that you can drop in to your testing configuration that sets up the override correctly, so this can't happen.

**Comment by alxhub** [comment]
We won't be developing new features for `Http`, use `HttpClient` instead (which has a testing module which sets everything up correctly).
