### ISSUE TITLE
rxjs take operator in testing.dev.js loads incorrectly

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#6421]
I seem to be having some issues when I try to run some unit tests on a service that uses `Http` and the `.map()` operator. Because I use the operator I have to import the patch using `import 'rxjs/operator/map'`. And configured System to point to:
```js
System.config({
	packages: {
		'app': {defaultExtension: 'js'},
		'rxjs': {defaultExtension: 'js'}
	},
	paths: {
		'rxjs/operator/*': 'lib/rxjs/add/operator/*',
		'rxjs/*': 'lib/rxjs/*'
	}
});
```

But when I run tests and I use the `testing.dev.js` lib, I get:
```js
Failed: EXCEPTION: TypeError: Cannot read property 'call' of undefined in [glyph.svg in ]
	ORIGINAL EXCEPTION: TypeError: Cannot read property 'call' of undefined
	ORIGINAL STACKTRACE:
	TypeError: Cannot read property 'call' of undefined
	    at new MockConnection (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:492:34 <- ../dev/es5/angular2/src/http/backends/mock_backend.js:25:34)
	    at MockBackend.createConnection (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:539:24 <- ../dev/es5/angular2/src/http/backends/mock_backend.js:145:25)
	    at httpRequest (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/http.dev.js:933:20)
	    at Http.get (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/http.dev.js:972:14)
	    at Icon.get (/Users/rolandjitsu/Projects/ng2-lab/dist/public/app/services/icon.js:28:22 <- /source/app/services/icon.ts:29:5)
	    at Glyph.Object.defineProperty.set [as src] (/Users/rolandjitsu/Projects/ng2-lab/dist/public/app/common/glyph/glyph.js:20:24 <- /source/app/common/glyph/glyph.ts:31:13)
	    at AbstractChangeDetector.ChangeDetector_GlyphTest_0.detectChangesInRecordsInternal (eval at <anonymous> (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2.dev.js:10897:14), <anonymous>:33:32)
	    at AbstractChangeDetector.detectChangesInRecords (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2.dev.js:8824:14)
	    at AbstractChangeDetector.runDetectChanges (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2.dev.js:8807:12)
	    at AbstractChangeDetector._detectChangesInViewChildren (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2.dev.js:8877:14)
	    at AbstractChangeDetector.runDetectChanges (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2.dev.js:8811:12)
	    at AbstractChangeDetector.detectChanges (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2.dev.js:8796:12)
	    at ComponentFixture_.detectChanges (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2054:48 <- ../dev/es5/angular2/src/testing/test_component_builder.js:43:47)
	    at /Users/rolandjitsu/Projects/ng2-lab/dist/public/app/common/glyph/glyph.spec.js:56:25 <- /source/app/common/glyph/glyph.spec.ts:80:13
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2544:30 <- ../dev/es5/angular2/src/testing/testing.js:108:35)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2544:30 <- ../dev/es5/angular2/src/testing/testing.js:108:35)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2544:30 <- ../dev/es5/angular2/src/testing/testing.js:108:35)
	    at zoneBoundFn (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
	    at lib$es6$promise$$internal$$tryCatch (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:1511:16)
	    at lib$es6$promise$$internal$$invokeCallback (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:1523:17)
	    at lib$es6$promise$$internal$$publish (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:1494:11)
	    at /Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:243:5
	    at microtask (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2557:15 <- ../dev/es5/angular2/src/testing/testing.js:122:25)
	    at microtask (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2557:15 <- ../dev/es5/angular2/src/testing/testing.js:122:25)
	    at microtask (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2557:15 <- ../dev/es5/angular2/src/testing/testing.js:122:25)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2544:30 <- ../dev/es5/angular2/src/testing/testing.js:108:35)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2544:30 <- ../dev/es5/angular2/src/testing/testing.js:108:35)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2544:30 <- ../dev/es5/angular2/src/testing/testing.js:108:35)
	    at zoneBoundFn (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
	    at lib$es6$promise$asap$$flush (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:1305:9)
	ERROR CONTEXT:
	[object Object]
```

Is there another way of loading operators so that it works with tests as well? Because if I configure System as such:
```js
System.config({
	packages: {
		'app': {defaultExtension: 'js'},
		'rxjs': {defaultExtension: 'js'}
	},
	paths: {
		'rxjs/operator/*': 'lib/rxjs/operator/*',
		'rxjs/*': 'lib/rxjs/*'
	}
});
```
I no longer get that error, but the `.map()` operator no longer works:
```js
Failed: this._http.get(...).map is not a function
	TypeError: this._http.get(...).map is not a function
	    at Icon.get (/Users/rolandjitsu/Projects/ng2-lab/dist/public/app/services/icon.js:29:22 <- /source/app/services/icon.ts:30:5)
	    at /Users/rolandjitsu/Projects/ng2-lab/dist/public/app/services/icon.spec.js:60:23 <- /source/app/services/icon.spec.ts:84:10
	    at FunctionWrapper.apply (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2.dev.js:325:17)
	    at FunctionWithParamTokens.execute (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2479:37 <- ../dev/es5/angular2/src/testing/test_injector.js:169:36)
	    at /Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2601:25 <- ../dev/es5/angular2/src/testing/testing.js:168:76
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2544:30 <- ../dev/es5/angular2/src/testing/testing.js:108:35)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2544:30 <- ../dev/es5/angular2/src/testing/testing.js:108:35)
	    at runInTestZone (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2588:23 <- ../dev/es5/angular2/src/testing/testing.js:154:20)
	    at Object.<anonymous> (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2600:33 <- ../dev/es5/angular2/src/testing/testing.js:168:36)
	    at Zone.lang_1.global.zone.fork.onError (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2539:9 <- ../dev/es5/angular2/src/testing/testing.js:104:32)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:141:14)
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2544:30 <- ../dev/es5/angular2/src/testing/testing.js:108:35)
	    at runInTestZone (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2588:23 <- ../dev/es5/angular2/src/testing/testing.js:154:20)
	    at Object.<anonymous> (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/testing.dev.js:2600:33 <- ../dev/es5/angular2/src/testing/testing.js:168:36)
	    at /Users/rolandjitsu/Projects/ng2-lab/test.js:52:14
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
	    at zoneBoundFn (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
	    at lib$es6$promise$$internal$$tryCatch (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:1511:16)
	    at lib$es6$promise$$internal$$invokeCallback (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:1523:17)
	    at lib$es6$promise$$internal$$publish (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:1494:11)
	    at /Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:243:5
	    at Zone.run (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
	    at zoneBoundFn (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:111:19)
	    at lib$es6$promise$asap$$flush (/Users/rolandjitsu/Projects/ng2-lab/node_modules/angular2/bundles/angular2-polyfills.js:1305:9)
```

**Comment by JessieAMorris** [comment]
I had this issue with my tests for a MockBackend from the HTTP service. The MockBackend isn't returning a fully functional Observable for some reason. Instead, it's returning a "Subject" (or at least, that what it looks like in the console).

My solution, and it's an awful hack that I'd love to see resolved, was to call `.asObservable` on the object returned by `http.get`. Real observables don't have that method, but this so called `Subject` does.

It looks like MockBackend should be returning Observables not Subjects.

**Comment by JessieAMorris** [comment]
Okay, so I think the issue I have vs the one you have are slightly different. Try importing all of the observable operators inside your spec file.

For example:
```
import {Observable} from 'rxjs/Rx';
```

or post your spec file here

**Comment by pkozlowski-opensource** [comment]
Obsolete since we no longer publish those bundles.

**Comment by prasikumbhare** [comment]
@JessieAMorris

I am facing the same issue. Can you please post of a snippet of your solution. 

Thanks
