### ISSUE TITLE
beta1 Renderer#setElementClass does not work

### ISSUE THREAD

**Issue by webnobushi** [angular/angular#6456]
After running the following error has occurred .
```
renderer.setElementClass(elementRef, "className", true)
```

```
TypeError: Cannot read property 'add' of undefined
    at BrowserDomAdapter.addClass (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:22914:24)
    at DomRenderer.setElementClass (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:13750:27)
```

This method was operating normally in beta0.

**Comment by SebastianM** [comment]
Try:
```typescript
renderer.setElementClass(elementRef.nativeElement, "className", true)
```

It's a breaking change in beta 1. The renderer expects a native element.

**Comment by webnobushi** [comment]
Problem was resolved.
Thank you for your quick reply.
