### ISSUE TITLE
TypeError: Object doesn't support property or method 'keys'

### ISSUE THREAD

**Issue by andycwk** [angular/angular#6479]
Hi,

I'm using Angular 2.0.0-beta.1 and have the following exception in Internet Explorer 11 (think it also shows in 9 & 10 too but with less info)

```
TypeError: Object doesn't support property or method 'keys'
   at Anonymous function (http://localhost:5000/app/angular2.dev.js:783:5)
   at Anonymous function (http://localhost:5000/app/angular2.dev.js:781:3)
   at linkDynamicModule (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3130:5)
   at getModule (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3098:9)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3134:9)
   at Anonymous function (http://localhost:5000/app/angular2.dev.js:10795:3)
   at linkDynamicModule (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3130:5)
   at getModule (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3098:9)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3134:9)
   at Anonymous function (http://localhost:5000/app/angular2.dev.js:12011:3) 
```

The start of my index.html looks like the following at the moment..
```
<head>
    <title ng-bind="title">xxx</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />
    <base href="/">

    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/main.css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.4.1/es5-sham.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-sham.min.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.1/angular2-polyfills.js"></script>
    
    <script src="https://code.angularjs.org/tools/typescript.js"></script>

    <script src="/app/reflect.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system-polyfills.src.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.1/Rx.js"></script>
    <!--<script src="https://code.angularjs.org/2.0.0-beta.1/angular2.dev.js"></script>-->
    <script src="/app/angular2.dev.js"></script>

    <script src="/app/shims_for_IE.js"></script>

    <script>
        System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
      });
      System.import('app/boot')
            .then(function(){
            }, function(err){
                console.log(err.stack);
            });
    </script>
</head>
```

As you can see, I've thrown all sorts into the mix to try and resolve the issue!

Any thoughts... is it a bug? Am I missing something obvious?

**Comment by pkozlowski-opensource** [comment]
See https://github.com/johnpapa/angular2-tour-of-heroes/issues/24 and https://github.com/mgechev/angular2-seed/pull/143. In short: you need https://github.com/paulmillr/es6-shim (I'm not sure what es6-sham.min.js that you are including is) and you should include it as early as possible

**Comment by andycwk** [comment]
This is really why developers need a cardboard cutout!

I went back and looked... I copied the wrong link from the cdn provider!

After testing with the es6-shim.js from paulmillr (placed above all other js in the head section) and seeing it working I turned back to why the es6-shim (https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-shim.js -- https://github.com/es-shims/es6-shim/) did not work... 
 
Using the correct shims from CloudFlare does indeed work 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.4.1/es5-shim.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-shim.js"></script>

Sorry for wasting your time - I really thought I had hit a snag - was trying to get this working from about 3pm until 12 am last night, it really does pay to look closely at the code :(

Thanks :)
