### ISSUE TITLE
Testing - Intermittent error: 'Failed: The selector "#root0" did not match any elements'

### ISSUE THREAD

**Issue by cangosta** [angular/angular#6483]
Hi, I'm building an application in angular2 beta version (with jasmine and karma for testing) and when I'm running my test case, I randomly get a 'The selector "#root0" did not match any elements' error. It follows the test code:

```js
@Component({
  template: '',
  directives: [GroupBox, GroupBoxHeader]
})
class TestComponent {
}

describe('group-box control', () => {

  it('should show the title', injectAsync([TestComponentBuilder], (tcb) => {
    return tcb.overrideTemplate(TestComponent, '<group-box><group-box-header>Title Content</group-box-header></group-box>')
      .createAsync(TestComponent).then( (fixture) => {
        fixture.detectChanges();
        let compiled = fixture.debugElement.nativeElement;
        expect(compiled).toContainText('Title Content');
    });
  }));

  it('should show the body', injectAsync([TestComponentBuilder], (tcb) => {
    return tcb.overrideTemplate(TestComponent, '<group-box><group-box-header>Title Content</group-box-header>Body Content</group-box>')
      .createAsync(TestComponent).then( (fixture) => {
        fixture.detectChanges();
        let compiled = fixture.debugElement.nativeElement;
        expect(compiled).toContainText('Body Content');
    });
  }));
});
```

StackTrace:

14 01 2016 11:40:32.073:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
14 01 2016 11:40:32.078:INFO [launcher]: Starting browser Chrome
14 01 2016 11:40:32.669:INFO [Chrome 47.0.2526 (Windows 8.1 0.0.0)]: Connected on socket /#9hKZqsNbKFPfYWzIAAAA with id 50428936
Chrome 47.0.2526 (Windows 8.1 0.0.0) group-box control should show the body FAILED
        Failed: The selector "#root0" did not match any elements
        Error: The selector "#root0" did not match any elements
            at new BaseException (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2.dev.js:8080:21)
            at DomRenderer_.createRootHostView (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2.dev.js:15248:15)
            at AppViewManager_.createRootHostView (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2.dev.js:11265:52)
            at C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2.dev.js:14531:46
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:138:17)
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2544:30)
            at zoneBoundFn (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:111:19)
            at lib$es6$promise$$internal$$tryCatch (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1511:16)
            at lib$es6$promise$$internal$$invokeCallback (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1523:17)
            at lib$es6$promise$$internal$$publish (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1494:11)
            at C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:243:5
            at microtask (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2557:15)
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:138:17)
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2544:30)
            at zoneBoundFn (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:111:19)
            at lib$es6$promise$asap$$flush (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1305:9)
        Failed: Cannot read property 'hostView' of undefined
        TypeError: Cannot read property 'hostView' of undefined
            at new ComponentFixture_ (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2047:97)
            at C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2145:16
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:138:17)
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2544:30)
            at zoneBoundFn (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:111:19)
            at lib$es6$promise$$internal$$tryCatch (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1511:16)
            at lib$es6$promise$$internal$$invokeCallback (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1523:17)
            at lib$es6$promise$$internal$$publish (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1494:11)
            at C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:243:5
            at microtask (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2557:15)
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:138:17)
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2544:30)
            at zoneBoundFn (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:111:19)
            at lib$es6$promise$asap$$flush (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1305:9)
        Failed: Cannot read property 'detectChanges' of undefined
        TypeError: Cannot read property 'detectChanges' of undefined
            at C:/Projectos/Fontes/Stratus-HTML/build/test/infrastructure/controls/group-box.test.js:52:20
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:138:17)
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2544:30)
            at zoneBoundFn (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:111:19)
            at lib$es6$promise$$internal$$tryCatch (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1511:16)
            at lib$es6$promise$$internal$$invokeCallback (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1523:17)
            at lib$es6$promise$$internal$$publish (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1494:11)
            at C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:243:5
            at microtask (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2557:15)
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:138:17)
            at Zone.run (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/testing.dev.js:2544:30)
            at zoneBoundFn (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:111:19)
            at lib$es6$promise$asap$$flush (C:/Projectos/Fontes/Stratus-HTML/build/assets/js/angular2-polyfills.js:1305:9)
Chrome 47.0.2526 (Windows 8.1 0.0.0): Executed 59 of 60 (1 FAILED) (skipped 1) (0.519 secs / 0.51 secs)
[11:40:33] 'test' errored after 2.01 s
[11:40:33] Error: 1
    at formatError (C:\Users\LSANTOS\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\LSANTOS\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Projectos\Fontes\Stratus-HTML\node_modules\orchestrator\index.js:264:8)
    at C:\Projectos\Fontes\Stratus-HTML\node_modules\orchestrator\index.js:275:23
    at finish (C:\Projectos\Fontes\Stratus-HTML\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\Projectos\Fontes\Stratus-HTML\node_modules\orchestrator\lib\runTask.js:29:3)
    at removeAllListeners (C:\Projectos\Fontes\Stratus-HTML\node_modules\karma\lib\server.js:333:7)
    at Server.<anonymous> (C:\Projectos\Fontes\Stratus-HTML\node_modules\karma\lib\server.js:344:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1518:8)
    at doNTCallback1 (node.js:418:9)
    at process._tickCallback (node.js:340:17)

**Comment by ericmartinezr** [comment]
@cangosta I've read that this is because of using templateUrl in any of the components, but there are cases where is not that the reason. Can you share a repo? I tried it in my env and I couldn't reproduce it.

**Comment by cangosta** [comment]
@ericmartinezr Yes, I've also heard about that. I'll try to share a repo with this issue. Make sure you run it several times, since this bug only happens sometimes...

**Comment by cangosta** [comment]
@ericmartinezr in this repo you can reproduce the error: https://github.com/cangosta/ng2_testing_controls

**Comment by cangosta** [comment]
@ericmartinezr I've updated the repository with a simplified version. thx

**Comment by ericmartinezr** [comment]
@cangosta is really hard to say. I've been trying for a while and nothing happens. I don't know what may be the conditions to make it fail. I would recommend you to avoid `templateUrl` and see if that makes a difference (there are already cases where that's the cause, so avoiding it can help to isolate the issue). Besides that I see that you're including `traceur` and `es6-module-loader` , libraries that were removed a long time ago.

**Comment by cangosta** [comment]
@ericmartinezr in fact, if I replace the templateUrl with an inline template, everything runs fine. But it is impractical, since I have huge templates throughout my application. There is also another workaround:  remove the component moduleId and use an absolute template path in the  templateUrl configuration.

**Comment by ericmdantas** [comment]
Here's another repo which can be used to see such errors:

https://github.com/ericmdantas/angular2-typescript-todo

Also, when I switched from `templateUrl` to `template` it still had the same intermittent errors.

**Comment by mhevery** [comment]
@tbosch could you have a look at this issue (just text, not actual code), to see if it something obvious?

**Comment by ericmartinezr** [comment]
After all the conversation this is dup of https://github.com/angular/angular/issues/5662

**Comment by ericmdantas** [comment]
@ericmartinezr it's weird that I had not problem with the version used in such issue, though.

**Comment by andrashatvani** [comment]
I suddenly started seeing this error in our project, too. Interestingly, I only see it during the first test run; if I repeat the test with the same running Karma-Node instance, then it's fine.

**Comment by ericmartinezr** [comment]
Since beta.2 this is no longer an issue and the templates loaded through templateUrl load just fine. I think this issue can be closed already.

**Comment by ericmdantas** [comment]
@ericmartinezr I'm afraid I won't be able to do it until sunday, but I'll let you guys know.

**Comment by ericmdantas** [comment]
Welp, now I'm having the following error:

```
Failed: No provider for TestComponentBuilder!
  Error: DI Exception at NoProviderError.BaseException [as constructor] 
```

Gotta see how it's done in beta2 now.

**Comment by cangosta** [comment]
@ericmartinezr , I'm having the same error as @ericmdantas . I'll try to have a deep look at it later.

**Comment by fatsu** [comment]
see #6813. 

Beta2 changed the way the providers have to be loaded for testing (https://github.com/angular/angular/blob/master/CHANGELOG.md#features). 

Unfortunately, something appears to have gone wrong and the necessary System.register for 'angular2/platform/testing/browser' is missing in angular2/bundles/testing.dev.js of the 2.0.0-beta.2 version that is on NPM, but is present in https://code.angularjs.org/2.0.0-beta.2/testing.dev.js.

**Comment by ericmdantas** [comment]
All running fine with beta3!

Again, here's the repo in case someone needs help:

https://github.com/ericmdantas/angular2-typescript-todo

Basically, what I had to do:

- Manually add typings for jasmine with `tsd install jasmine -so` and add `///<reference...` in the test files;
- Add this in my imports: 

```ts
import {
  TEST_BROWSER_PLATFORM_PROVIDERS,
  TEST_BROWSER_APPLICATION_PROVIDERS
} from 'angular2/platform/testing/browser';
```

- Add this before my Component tests:

```ts
  setBaseTestProviders(TEST_BROWSER_PLATFORM_PROVIDERS, TEST_BROWSER_APPLICATION_PROVIDERS);
```

--

Thanks for the quick fix, guys.

**Comment by cangosta** [comment]
It is working now. Thanks @ericmdantas

**Comment by ericmdantas** [comment]
:smile:

**Comment by JohnVNguyen** [comment]
@ericmdantas I tried angular2-typescript-todo and the tests pass, but if I try to fail one with expect(1).toEqual(2), it still passes. Is yours doing the same?

**Comment by ericmdantas** [comment]
@johnvnguyen hello!

That only happens in the component test, right? I updated the repo to use `injectAsync` instead of `inject` and now tests are failing when the assertion is falsy.

Thanks for pointing it out :smile:

**Comment by johnvnguyen** [comment]
@ericmdantas YES thank you. I haven't checked the other tests yet. I'm just happy to see a test with templateUrl working. I've been stuck on it for days!

**Comment by ericmdantas** [comment]
Last time I checked, they were switching from `injectAsync` (which you have to return a promise, so it works correctly) in favor of `inject` which would use `zone.js` to verify the changes and suchs.

I don't remember if it was a internal change or if it was supposed to leak to the public api, because when they're using only `inject`, they're using `AsyncTestCompleter` too, to let it be known that spec has finished [see here](https://github.com/angular/angular/blob/cee2318110eeea115e5f6fc5bfc814cbaa7d90d8/modules/angular2/test/common/directives/ng_for_spec.ts#L99-L127).

But maybe someone from the core team can let us know better.
