### ISSUE TITLE
CI Flaky Test Failure: Router should replace history when triggered by a hashchange with a redirect

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#6566]
This flake has occurred in at least 3 recent CI runs: https://travis-ci.org/angular/angular/jobs/102726579

```
Failures:
1) Router should replace history when triggered by a hashchange with a redirect
  Message:
    Expected [ 'hash: a' ] to equal [ 'hash: a', 'replace: /b' ].
  Stack:
    Error: Expected [ 'hash: a' ] to equal [ 'hash: a', 'replace: /b' ].
        at Object.next (/home/travis/build/angular/angular/dist/js/cjs/angular2/test/router/router_spec.js:89:68)
        at null._onTimeout (/home/travis/build/angular/angular/dist/js/cjs/angular2/src/facade/async.js:121:110)
        at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by btford** [comment]
Seems like this is resolved.
