### ISSUE TITLE
Unable to use where method in EventEmitter in Dart

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular#6685]
consider this very simple angular 2 app:

```dart
import 'package:angular2/bootstrap.dart';
import 'package:angular2/angular2.dart';

main() {
  bootstrap(AppComponent);
}

@Component(selector: 'body', template: '')
class AppComponent {
  AppComponent() {
    testEmitter.where((e) => e == 'test').forEach(print);
    testEmitter.add('test');
  }

  EventEmitter<String> testEmitter = new EventEmitter();
}
```

I get this below error only if I add the where method.

I changed the EventEmitter implementation, in my app to this:

```
class EventEmitter<T> extends Stream<T> {
  StreamController<dynamic> _controller;

  /// Creates an instance of [EventEmitter], which depending on [isAsync],
  /// delivers events synchronously or asynchronously.
  EventEmitter([bool isAsync = true]) {
    _controller = new StreamController.broadcast(sync: !isAsync);
  }

  StreamSubscription listen(void onData(dynamic line),
      {/*BEGIN CHANGED */,Function onError /*END CHANGED */, void onDone(), bool cancelOnError}) {
    return _controller.stream.listen(onData,
        onError: onError, onDone: onDone, cancelOnError: cancelOnError);
  }
  ... (more)
}
```

And now it works good.

This is the error:
```
 EXCEPTION: Error during instantiation of AppComponent!.
(program):1 EXCEPTION: Error during instantiation of AppComponent!.(program):1 (anonymous function)
(program):1 ORIGINAL EXCEPTION: type '(dynamic, StackTrace) => void' is not a subtype of type '(Error) => void' of 'onError'.
(program):1 ORIGINAL STACKTRACE:
(program):1 #0      EventEmitter.listen (package:angular2/src/facade/async.dart:85:13)
#1      _ForwardingStreamSubscription._ForwardingStreamSubscription (dart:async/stream_pipe.dart:129)
#2      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:96)
#3      _ForwardingStream.listen (dart:async/stream_pipe.dart:88)
#4      Stream.forEach (dart:async/stream.dart:706)
#5      AppComponent.AppComponent (http://localhost:63342/untitled49/web/main.dart:11:43)
#6      initReflector.<anonymous closure> (http://localhost:63342/untitled49/web/main.ng_deps.dart:16:11)
#7      Injector._instantiate (package:angular2/src/core/di/injector.dart:893:24)
#8      Injector._instantiateProvider (package:angular2/src/core/di/injector.dart:793:12)
#9      Injector._new (package:angular2/src/core/di/injector.dart:779:17)
#10     InjectorInlineStrategy.instantiateProvider (package:angular2/src/core/di/injector.dart:234:26)
#11     ElementInjectorInlineStrategy.hydrate (package:angular2/src/core/linker/element_injector.dart:868:11)
#12     ElementInjector.hydrate (package:angular2/src/core/linker/element_injector.dart:415:20)
#13     AppViewManagerUtils._hydrateView (package:angular2/src/core/linker/view_manager_utils.dart:241:29)
#14     AppViewManagerUtils.hydrateRootHostView (package:angular2/src/core/linker/view_manager_utils.dart:142:10)
#15     AppViewManager_.createRootHostView (package:angular2/src/core/linker/view_manager.dart:234:17)
#16     DynamicComponentLoader_.loadAsRoot.<anonymous closure> (package:angular2/src/core/linker/dynamic_component_loader.dart:261:12)
#17     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:137:26)
#18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#19     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:137:14)
#20     NgZone._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:321:40)
#21     _rootRun (dart:async/zone.dart:903)
#22     _ZoneDelegate.run (dart:async/zone.dart:502)
#23     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#24     NgZone._runUnary (package:angular2/src/core/zone/ng_zone.dart:321:7)
#25     _CustomZone.runUnary (dart:async/zone.dart:810)
#26     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#27     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#28     _Future._completeWithValue (dart:async/future_impl.dart:424)
#29     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#30     NgZone._scheduleMicrotask.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:331:11)
#31     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#32     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:127:48)
#33     _rootRun (dart:async/zone.dart:907)
#34     _ZoneDelegate.run (dart:async/zone.dart:502)
#35     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#36     _CustomZone.run (dart:async/zone.dart:802)
#37     _CustomZone.runGuarded (dart:async/zone.dart:708)
#38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#41     _ScheduleImmediateHelper._handleMutation (dart:html:49254)
#42     MutationObserver._create.<anonymous closure> (dart:html:27525)

(program):1 ERROR CONTEXT:
(program):1 DartObject
(program):1 Uncaught Unhandled exception:
EXCEPTION: Error during instantiation of AppComponent!.
ORIGINAL EXCEPTION: type '(dynamic, StackTrace) => void' is not a subtype of type '(Error) => void' of 'onError'.
ORIGINAL STACKTRACE:
#0      EventEmitter.listen (package:angular2/src/facade/async.dart:85:13)
#1      _ForwardingStreamSubscription._ForwardingStreamSubscription (dart:async/stream_pipe.dart:129)
#2      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:96)
#3      _ForwardingStream.listen (dart:async/stream_pipe.dart:88)
#4      Stream.forEach (dart:async/stream.dart:706)
#5      AppComponent.AppComponent (http://localhost:63342/untitled49/web/main.dart:11:43)
#6      initReflector.<anonymous closure> (http://localhost:63342/untitled49/web/main.ng_deps.dart:16:11)
#7      Injector._instantiate (package:angular2/src/core/di/injector.dart:893:24)
#8      Injector._instantiateProvider (package:angular2/src/core/di/injector.dart:793:12)
#9      Injector._new (package:angular2/src/core/di/injector.dart:779:17)
#10     InjectorInlineStrategy.instantiateProvider (package:angular2/src/core/di/injector.dart:234:26)
#11     ElementInjectorInlineStrategy.hydrate (package:angular2/src/core/linker/element_injector.dart:868:11)
#12     ElementInjector.hydrate (package:angular2/src/core/linker/element_injector.dart:415:20)
#13     AppViewManagerUtils._hydrateView (package:angular2/src/core/linker/view_manager_utils.dart:241:29)
#14     AppViewManagerUtils.hydrateRootHostView (package:angular2/src/core/linker/view_manager_utils.dart:142:10)
#15     AppViewManager_.createRootHostView (package:angular2/src/core/linker/view_manager.dart:234:17)
#16     DynamicComponentLoader_.loadAsRoot.<anonymous closure> (package:angular2/src/core/linker/dynamic_component_loader.dart:261:12)
#17     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:137:26)
#18     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#19     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:137:14)
#20     NgZone._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:321:40)
#21     _rootRun (dart:async/zone.dart:903)
#22     _ZoneDelegate.run (dart:async/zone.dart:502)
#23     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#24     NgZone._runUnary (package:angular2/src/core/zone/ng_zone.dart:321:7)
#25     _CustomZone.runUnary (dart:async/zone.dart:810)
#26     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#27     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#28     _Future._completeWithValue (dart:async/future_impl.dart:424)
#29     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#30     NgZone._scheduleMicrotask.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:331:11)
#31     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#32     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:127:48)
#33     _rootRun (dart:async/zone.dart:907)
#34     _ZoneDelegate.run (dart:async/zone.dart:502)
#35     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#36     _CustomZone.run (dart:async/zone.dart:802)
#37     _CustomZone.runGuarded (dart:async/zone.dart:708)
#38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#41     _ScheduleImmediateHelper._handleMutation (dart:html:49254)
#42     MutationObserver._create.<anonymous closure> (dart:html:27525)

ERROR CONTEXT:
Instance of '_Context'
#0      Injector._instantiate (package:angular2/src/core/di/injector.dart:964:7)
#1      Injector._instantiateProvider (package:angular2/src/core/di/injector.dart:793:12)
#2      Injector._new (package:angular2/src/core/di/injector.dart:779:17)
#3      InjectorInlineStrategy.instantiateProvider (package:angular2/src/core/di/injector.dart:234:26)
#4      ElementInjectorInlineStrategy.hydrate (package:angular2/src/core/linker/element_injector.dart:868:11)
#5      ElementInjector.hydrate (package:angular2/src/core/linker/element_injector.dart:415:20)
#6      AppViewManagerUtils._hydrateView (package:angular2/src/core/linker/view_manager_utils.dart:241:29)
#7      AppViewManagerUtils.hydrateRootHostView (package:angular2/src/core/linker/view_manager_utils.dart:142:10)
#8      AppViewManager_.createRootHostView (package:angular2/src/core/linker/view_manager.dart:234:17)
#9      DynamicComponentLoader_.loadAsRoot.<anonymous closure> (package:angular2/src/core/linker/dynamic_component_loader.dart:261:12)
#10     StackZoneSpecification.registerUnaryCallback.<anonymous closure>.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:137:26)
#11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#12     StackZoneSpecification.registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:137:14)
#13     NgZone._runUnary.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:321:40)
#14     _rootRun (dart:async/zone.dart:903)
#15     _ZoneDelegate.run (dart:async/zone.dart:502)
#16     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#17     NgZone._runUnary (package:angular2/src/core/zone/ng_zone.dart:321:7)
#18     _CustomZone.runUnary (dart:async/zone.dart:810)
#19     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#20     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#21     _Future._completeWithValue (dart:async/future_impl.dart:424)
#22     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#23     NgZone._scheduleMicrotask.<anonymous closure> (package:angular2/src/core/zone/ng_zone.dart:331:11)
#24     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#25     StackZoneSpecification.registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:127:48)
#26     _rootRun (dart:async/zone.dart:907)
#27     _ZoneDelegate.run (dart:async/zone.dart:502)
#28     NgZone._run (package:angular2/src/core/zone/ng_zone.dart:291:21)
#29     _CustomZone.run (dart:async/zone.dart:802)
#30     _CustomZone.runGuarded (dart:async/zone.dart:708)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:733)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#34     _ScheduleImmediateHelper._handleMutation (dart:html:49254)
#35     MutationObserver._create.<anonymous closure> (dart:html:27525)
```

**Comment by zoechi** [comment]
This is not the intended use case for `EventEmitter`. `EventEmitter` should only be used for `@Output()` for binding (`<my-comp (someOutput)="doSomething()">`). Just use a `StreamController` instead.

**Comment by pkozlowski-opensource** [comment]
Obsolete.
