### ISSUE TITLE
Build fails due to unavailable `-o` option for `pub` command

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#670]
Hi there.

I pulled the latest changes from this repository and ran `gulp build`. Here's the output:

```sh
$ gulp build
Dart SDK detected
[12:48:45] Using gulpfile ~/projects/angular/angular/gulpfile.js
[12:48:45] Starting 'build.js.dev'...
[12:48:45] Starting 'build/deps.js.dev'...
[12:48:45] Starting 'build/transpile.js.dev'...
[12:48:45] Starting 'build/transpile.js.dev.es6'...
[12:48:45] Starting 'build/html.js.dev'...
[12:48:45] Starting 'build/copy.js.dev'...
[12:48:45] Starting 'build.js.prod'...
[12:48:45] Starting 'build/deps.js.prod'...
[12:48:45] Starting 'build/transpile.js.prod'...
[12:48:45] Starting 'build/transpile.js.prod.es6'...
[12:48:45] Starting 'build/html.js.prod'...
[12:48:45] Starting 'build/copy.js.prod'...
[12:48:45] Starting 'build.js.cjs'...
[12:48:45] Starting 'build/transpile.js.cjs'...
[12:48:45] Starting 'build.dart'...
[12:48:45] Starting 'build/deps.js.dart2js'...
[12:48:45] Starting 'build/transpile.dart'...
[12:48:45] Starting 'build/html.dart'...
[12:48:46] Finished 'build/deps.js.dart2js' after 853 ms
[12:48:46] Finished 'build/copy.js.prod' after 955 ms
[12:48:46] Finished 'build/copy.js.dev' after 1.11 s
[12:48:47] Finished 'build/deps.js.dev' after 2.13 s
[12:48:47] Finished 'build/deps.js.prod' after 1.97 s
[12:48:48] Finished 'build/html.js.prod' after 2.74 s
[12:48:48] Finished 'build/html.js.dev' after 2.9 s
[12:48:48] Finished 'build/html.dart' after 2.74 s
[12:48:51] Finished 'build/transpile.dart' after 6.25 s
[12:48:51] Starting 'build/pubspec.dart'...
[12:48:51] Finished 'build/pubspec.dart' after 105 ms
[12:48:51] Starting 'build/multicopy.dart'...
[12:48:51] Finished 'build/multicopy.dart' after 8.44 ms
[12:48:51] Starting 'build/pubbuild.dart'...
Could not find an option or flag "-o".
Run "pub help" to see available options.
[12:48:52] 'build/pubbuild.dart' errored after 319 ms
[12:48:52] Error: 64
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
    at _rejected (/Users/pp/projects/angular/angular/node_modules/q/q.js:804:24)
    at /Users/pp/projects/angular/angular/node_modules/q/q.js:830:30
    at Promise.when (/Users/pp/projects/angular/angular/node_modules/q/q.js:1064:31)
[12:48:52] 'build.js.dev' errored after 6.87 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build/transpile.js.dev' errored after 6.87 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.js.prod' errored after 6.72 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build/transpile.js.prod' errored after 6.72 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.js.cjs' errored after 6.71 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.dart' errored after 6.7 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.dart' errored after 6.7 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.js.cjs' errored after 6.72 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.dart' errored after 6.71 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build/transpile.js.prod' errored after 6.72 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.js.cjs' errored after 6.72 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.dart' errored after 6.71 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.js.prod' errored after 6.73 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build/transpile.js.prod' errored after 6.73 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.js.cjs' errored after 6.72 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.dart' errored after 6.71 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build/transpile.js.dev' errored after 6.88 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.js.prod' errored after 6.73 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build/transpile.js.prod' errored after 6.73 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.js.cjs' errored after 6.73 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:52] 'build.dart' errored after 6.72 s
[12:48:52] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/pp/projects/angular/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/pp/projects/angular/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
[12:48:55] Finished 'build/transpile.js.prod.es6' after 10 s
[12:48:55] Finished 'build/transpile.js.dev.es6' after 10 s
[12:48:55] Finished 'build/transpile.js.cjs' after 10 s
```

I'm not into Dart nor am I super familiar with the `pub` command line tool. However, as the error says, the flag `-o` is apparently not supported. Might be due to an outdated version of `pub`.

Gonna verify that. Just letting you know because we might want to update the Readme accordingly, that a specific version of `pub` is required.

**Comment by PascalPrecht** [comment]
Okay, turns out `angular/angular` required `pub` in version `>=1.4.0`

```sh
$ pub upgrade
$ Resolving dependencies...
$ Package angular requires SDK version >=1.4.0 but the current SDK is 1.3.6.
```

**Comment by PascalPrecht** [comment]
@vicb sorry, forgot to close this one.
