### ISSUE TITLE
Issue with Hero Form Angular 2 

### ISSUE THREAD

**Issue by zackzulg** [angular/angular#6720]
Good afternoon, I try to use Angular2 instead of angular 1.4. and I'd like to run Hero project but It seems doesn't work to me because when I run the app it stays on loading .... When I check my console I found these problems : 
EXCEPTION: Unexpected directive value 'undefined' on the View of component 'class0'
angular2-all.umd.js:28551 
EXCEPTION: Unexpected directive value 'undefined' on the View of component 'class0'BrowserDomAdapter.logError @ angular2-all.umd.js:28551BrowserDomAdapter.logGroup @ angular2-all.umd.js:28561ExceptionHandler.call @ angular2-all.umd.js:4479(anonymous function) @ angular2-all.umd.js:12592NgZone._notifyOnError @ angular2-all.umd.js:13233collection_1.StringMapWrapper.merge.onError @ angular2-all.umd.js:13128run @ angular2-polyfills.js:141(anonymous function) @ angular2-all.umd.js:13146zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243microtask @ angular2-all.umd.js:13186run @ angular2-polyfills.js:138(anonymous function) @ angular2-all.umd.js:13146zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
angular2-all.umd.js:28551 STACKTRACE:BrowserDomAdapter.logError @ angular2-all.umd.js:28551ExceptionHandler.call @ angular2-all.umd.js:4481(anonymous function) @ angular2-all.umd.js:12592NgZone._notifyOnError @ angular2-all.umd.js:13233collection_1.StringMapWrapper.merge.onError @ angular2-all.umd.js:13128run @ angular2-polyfills.js:141(anonymous function) @ angular2-all.umd.js:13146zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243microtask @ angular2-all.umd.js:13186run @ angular2-polyfills.js:138(anonymous function) @ angular2-all.umd.js:13146zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
angular2-all.umd.js:28551 Error: Unexpected directive value 'undefined' on the View of component 'class0'
    at new BaseException (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:4357:24)
    at RuntimeMetadataResolver.getViewDirectivesMetadata (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:26819:24)
    at TemplateCompiler._compileNestedComponentRuntime (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:21503:66)
    at http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:21488:88
    at Array.forEach (native)
    at Object.Call (http://localhost:8082/Orsyss/node_modules/es6-shim/es6-shim.min.js:10:4567)
    at Array.forEach (http://localhost:8082/Orsyss/node_modules/es6-shim/es6-shim.min.js:10:20139)
    at http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:21488:44
    at Zone.run (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at Zone.run (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:13146:43)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at Zone.bind (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:109:48)
    at bindArguments (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:980:29)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:1000:37)
    at TemplateCompiler._compileComponentRuntime (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:21482:19)
    at TemplateCompiler.compileHostComponentRuntime (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:21432:19)
    at RuntimeCompiler_.compileInHost (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:21333:40)
    at DynamicComponentLoader_.loadAsRoot (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:13556:32)
    at di_1.provide.useFactory (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:12438:48)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:2195:26)
    at Zone.fork (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:2253:40)
    at NgZone._createInnerZone (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:13134:15)
    at new NgZone (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:12920:37)
    at createNgZone (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:12461:13)
    at PlatformRef_.application (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:12562:34)
    at Object.bootstrap (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-all.umd.js:27121:65)
    at HTMLDocument.<anonymous> (http://localhost:8082/Orsyss/app/boot.js:3:25)
    at Zone.run (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:138:17)
    at HTMLDocument.zoneBoundFn (http://localhost:8082/Orsyss/node_modules/angular2/bundles/angular2-polyfills.js:111:19)

**Comment by mgupta82** [comment]
Even I am facing the same issue

**Comment by zackzulg** [comment]
Thanx mgupta82 :-) actually i missed  to add some ligns.

**Comment by mgupta82** [comment]
What was those. It migh help me as well :)

**Comment by xcash** [comment]
@zackzulg @mgupta82 me too!

**Comment by zackzulg** [comment]
Good morning guys,
you have to add this code in your app.component.js file :
})(window.app || (window.app = {}));

**Comment by xcash** [comment]
Oh finally i got it. In my case was something else.
My setup was with gulp concatenating separate js files. 
The style used in this example (calling the anonymous function immediately) will results in undefined variables if the resulted file is not in the correct order.
So watch out if modifying original example. :/

**Comment by kara** [comment]
Looks like this is a docs issue for angular.io. Please file there if you're still seeing some missing lines.
