### ISSUE TITLE
Flaky test on travis

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#6732]
Seeing this frequently:
```
Failures:
1) Router should replace history when triggered by a hashchange with a redirect
  Message:
    Expected [ 'hash: a' ] to equal [ 'hash: a', 'replace: /b' ].
  Stack:
    Error: Expected [ 'hash: a' ] to equal [ 'hash: a', 'replace: /b' ].
        at Object.next (/home/travis/build/angular/angular/dist/js/cjs/angular2/test/router/router_spec.js:89:68)
        at null._onTimeout (/home/travis/build/angular/angular/dist/js/cjs/angular2/src/facade/async.js:121:110)
        at Timer.listOnTimeout (timers.js:92:15)
```

eg. https://travis-ci.org/angular/angular/jobs/105280926

**Comment by pkozlowski-opensource** [comment]
Yup, saw this one several times as well

**Comment by alexeagle** [comment]
Still hurting the caretaker.
https://travis-ci.org/angular/angular/jobs/106297836

**Comment by vicb** [comment]
outdated
