### ISSUE TITLE
flaky js build on travis

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#6851]
Causing a lot of red and failure to merge presubmits.

https://travis-ci.org/angular/angular/jobs/106581397
Failures:
1) WebWorkers Kitchen Sink should change greeting
  Message:
    Failed: No element found using locator: By.cssSelector("hello-app .changeButton")
  Stack:
    NoSuchElementError: No element found using locator: By.cssSelector("hello-app .changeButton")
        at process._tickCallback (node.js:401:9)
    Error
        at Object.<anonymous> (playground/e2e_test/web_workers/kitchen_sink/kitchen_sink_spec.ts:28:48)
    From: Task: Run it("should change greeting") in control flow
        at attemptAsync (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
        at QueueRunner.run (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
        at QueueRunner.execute (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1762:10)
        at Spec.Env.queueRunnerFactory (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:627:35)
        at Spec.execute (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:353:10)
        at Object.fn (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2360:37)
        at attemptAsync (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1819:24)
        at QueueRunner.run (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1774:9)
        at /home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1801:16
    From asynchronous test: 
    Error
        at Suite.<anonymous> (playground/e2e_test/web_workers/kitchen_sink/kitchen_sink_spec.ts:22:3)
        at addSpecsToSuite (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:743:25)
        at Env.describe (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:713:7)
        at jasmineInterface.describe (/home/travis/build/angular/angular/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3219:18)
        at Object.<anonymous> (playground/e2e_test/web_workers/kitchen_sink/kitchen_sink_spec.ts:4:1)
Ran 47 of 48 specs

**Comment by jteplitz602** [comment]
@alexeagle Is it always this specific test or just WebWorker e2e tests in general?

**Comment by alexeagle** [comment]
I've seen this particular failure a couple times. Sorry we don't gather
better data on flaky failures, you currently have to comb through logs to
see them.
