### ISSUE TITLE
How to emit a data from outlet tag?

### ISSUE THREAD

**Issue by dreambo8563** [angular/angular#6883]
I have a requirement;

there is a footer tag in app component

app.ts
```js
@RouteConfig([
    { path: '/', name: 'Home', component: Home, useAsDefault: true }
])
```

Is there a way to let Home emit a data to app component?
I hope home can run some animation before the footer display.
I use outputs in Home. but got exception

```
@Component({
    selector: 'home',
    directives: [BackgroundLayer, FirstName, LastName],
    styles: [require('./home.css')],
    template: require('./home.html'),
    outputs: ['showBasic']
})

export class Home implements OnInit, AfterViewInit {

    showBasic: EventEmitter<boolean>;
    constructor(public _animationBuilder: AnimationBuilder) {
        this.showBasic = new EventEmitter();
    }
    ngOnInit() { }
    ngAfterViewInit() {
    }

    showOthers(showOthers: boolean) {
        this.showBasic.emit(true);
    }
}

```

exception:

```
browser_adapter.ts:73 EXCEPTION: Error during evaluation of "showBasic"BrowserDomAdapter.logError @ browser_adapter.ts:73BrowserDomAdapter.logGroup @ browser_adapter.ts:84ExceptionHandler.call @ exception_handler.ts:49(anonymous function) @ application_ref.ts:262NgZone._notifyOnError @ ng_zone.ts:453collection_1.StringMapWrapper.merge.onError @ ng_zone.ts:352run @ core.js:99(anonymous function) @ ng_zone.ts:370zoneBoundFn @ core.js:69
2016-02-04 16:17:38.563 browser_adapter.ts:73 ORIGINAL EXCEPTION: TypeError: this.directive_0_0.showBasic is not a functionBrowserDomAdapter.logError @ browser_adapter.ts:73ExceptionHandler.call @ exception_handler.ts:61(anonymous function) @ application_ref.ts:262NgZone._notifyOnError @ ng_zone.ts:453collection_1.StringMapWrapper.merge.onError @ ng_zone.ts:352run @ core.js:99(anonymous function) @ ng_zone.ts:370zoneBoundFn @ core.js:69
2016-02-04 16:17:38.564 browser_adapter.ts:73 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:73ExceptionHandler.call @ exception_handler.ts:65(anonymous function) @ application_ref.ts:262NgZone._notifyOnError @ ng_zone.ts:453collection_1.StringMapWrapper.merge.onError @ ng_zone.ts:352run @ core.js:99(anonymous function) @ ng_zone.ts:370zoneBoundFn @ core.js:69
2016-02-04 16:17:38.564 browser_adapter.ts:73 TypeError: this.directive_0_0.showBasic is not a function
    at AbstractChangeDetector.ChangeDetector_HostHome_0.handleEventInternal (viewFactory_HostHome:38:37)
    at AbstractChangeDetector.handleEvent (http://localhost:3000/main.bundle.js:15402:30)
    at AbstractChangeDetector.eval (viewFactory_HostHome:57:108)
    at http://localhost:3000/main.bundle.js:1106:111
    at cb (http://localhost:3000/main.bundle.js:10934:26)
    at arguments.(anonymous function) (http://localhost:3000/polyfills.bundle.js:16697:25)
    at http://localhost:3000/polyfills.bundle.js:16402:24
    at Zone.run (http://localhost:3000/polyfills.bundle.js:16422:18)
    at Zone.run (http://localhost:3000/main.bundle.js:10876:43)
    at zoneBoundFn (http://localhost:3000/polyfills.bundle.js:16395:20)
```

**Comment by zoechi** [comment]
GitHub issues are for bug reports and feature requests. 
For support questions please use other channels like StackOverflow.com, Gitter https://gitter.im/angular/angular, Google groups https://groups.google.com/forum/#!forum/angular, ...
You might looking for something like

    - https://github.com/escardin/angular2-community-faq/blob/master/services.md#how-do-i-communicate-between-components-using-a-shared-service
    - http://stackoverflow.com/questions/34700438/global-events-in-angular-2

I don't know about animation though.

**Comment by dreambo8563** [comment]
thank you, I can resolve the requirement by rxjs. close
