### ISSUE TITLE
Error building - seems like `pub install` is not being run in `dist/dart/benmarks` before build

### ISSUE THREAD

**Issue by kevmoo** [angular/angular#694]
Thoughts @yjbanov ?

This is as of fa259659395cf9f5b5f754af0c145302cafd9385

```
[Info from Dart2JS]:
Took 0:00:03.727866 to compile benchmarks|web/src/tree/tree_benchmark.dart.
Cannot open file, path = '/Users/kevmoo/source/github/angular/dist/dart/benchmarks/packages/browser/dart.js' (OS Error: No such file or directory, errno = 2)
[17:12:48] 'build/pubbuild.dart' errored after 1.37 min
[17:12:48] Error: 1
    at formatError (/Users/kevmoo/.homebrew/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/kevmoo/.homebrew/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/kevmoo/source/github/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/kevmoo/source/github/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/kevmoo/source/github/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/kevmoo/source/github/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
    at _rejected (/Users/kevmoo/source/github/angular/node_modules/q/q.js:804:24)
    at /Users/kevmoo/source/github/angular/node_modules/q/q.js:830:30
    at Promise.when (/Users/kevmoo/source/github/angular/node_modules/q/q.js:1064:31)
[17:12:48] 'build.dart' errored after 1.52 min
[17:12:48] Error: [object Object]
    at formatError (/Users/kevmoo/.homebrew/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/kevmoo/.homebrew/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/kevmoo/source/github/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/kevmoo/source/github/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/kevmoo/source/github/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/kevmoo/source/github/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/kevmoo/source/github/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/Users/kevmoo/source/github/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.emit (events.js:129:20)
```

**Comment by yjbanov** [comment]
Do you get this from `gulp build`? Try `gulp clean` then `gulp build`.

**Comment by kevmoo** [comment]
'gulp clean fixes' – although I'm wondering if there is a 'pub install'
when there should be a 'pub upgrade'

**Comment by yjbanov** [comment]
We probably use `pub get`. I'd be worried about `pub upgrade` because it hits the server each time making the build longer.

**Comment by kevmoo** [comment]
Hmm... true.

On travis, this happens anyway – since there is no pubspec.lock file

Locally, we can run into issues since we may be building with an outdated
set of dependencies – or at least not the latest.

So we pay a bit for local build time (not for travis) but we avoid issues
like the one I reported – and we make sure that the local build matches
what happens on travis, even if we forget to clean.

**Comment by yjbanov** [comment]
Perhaps we should add a gulp/dart.upgrade target that does just that. This
would be consistent with how you use pub. You use pub get, pub build mostly
and pub upgrade occasionally.

**Comment by mhevery** [comment]
I think this is obsolete. Closing, reopen if still an issue.
