### ISSUE TITLE
No provider for ControlContainer! (NgControlName -> ControlContainer)

### ISSUE THREAD

**Issue by wangzilong** [angular/angular#6988]
package.json 
```
"dependencies": {
    "angular2": "2.0.0-beta.3",
    "systemjs": "0.19.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.11"
  },
```
I want to create a form , and app.component.ts:
```
import {Component} from 'angular2/core';
@Component({
    selector: 'my-app',
    template: `
        <form id="profile_form" role="form" #profileForm="ngForm">
            <div class="form-group" [class.has-error]="!_first">
                <input type="text" class="form-control" [(ngModel)]="_first" value="{{_first}}" required ngControl="firstName" #firstName="ngForm" #spy>
            </div>
        </form>
    `
})

export class AppComponent {
    _first:string;
}
```

but it throw:
```
EXCEPTION: No provider for ControlContainer! (NgControlName -> ControlContainer)BrowserDomAdapter.logError @ angular2.dev.js:22911
angular2.dev.js:22911 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:22911
angular2.dev.js:22911 Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:7325:21)
    at NoProviderError.AbstractProviderError [as constructor] (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:1646:14)
    at new NoProviderError (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:1670:14)
    at Injector._throwOrNull (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11518:15)
    at Injector._getPrivateDependency (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11548:55)
    at Injector._getByKeyHost (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11529:23)
    at Injector._getByKey (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11509:21)
    at Injector._getByDependency (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11499:21)
    at Injector._instantiate (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11396:32)
    at Injector._instantiateProvider (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11368:21)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at Zone.bind (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at DynamicComponentLoader_.loadAsRoot (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:12326:49)
    at di_1.provide.useFactory (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:12424:39)
    at Injector._instantiate (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11435:19)
    at Injector._instantiateProvider (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11368:21)
    at Injector._new (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:11358:19)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2-polyfills.js:2236:29)
    at Zone.fork (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2-polyfills.js:2285:47)
    at NgZone._createInnerZone (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:13396:39)
    at new NgZone (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:13262:32)
    at createNgZone (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:12446:12)
    at PlatformRef_.application (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:12521:31)
    at Object.bootstrap (http://127.0.0.1:8888/node_modules/angular2/bundles/angular2.dev.js:24631:64)
    at execute (http://127.0.0.1:8888/app/main.js:12:23)
    at ensureEvaluated (http://127.0.0.1:8888/node_modules/systemjs/dist/system.src.js:2981:26)
    at Object.execute (http://127.0.0.1:8888/node_modules/systemjs/dist/system.src.js:3099:13)
```

Is there any wrong code? Please help me.

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/6374

**Comment by wangzilong** [comment]
Thanks.
