### ISSUE TITLE
NgUpgrade "directives: [MyNg2Component]" does not work

### ISSUE THREAD

**Issue by Zizzamia** [angular/angular#7075]
In my ng1 application (es5) I have an ng2 component that I successfully downgrade by using `downgradeNg2Component`.
I tried to include a child ng2 component, by using the syntax

``` js
var navbarSettings = ng.core.Component({
  selector: 'navbar-settings',
  inputs: ['user'],
  template: navbarSettingsTemplate,
  directives: [myNg2ChildComponent]
})
...
```

But anytime I do that looks that my `navbarSettings` loose all the information in his contructor and also any appearance of the `myNg2ChildComponent`

**Comment by teropa** [comment]
I made [a plunker](https://plnkr.co/edit/YYZmpuzFtYfnguaTABKP?p=preview) where a downgraded Angular 2 component is successfully using another Angular 2 component (with beta.6).

Can you modify to reproduce your failure case?

**Comment by Zizzamia** [comment]
Here the error that I got,
```js
RangeError: Maximum call stack size exceeded
    at Function.toString (native)
    at HTMLElement.obj.addEventListener (http://localhost:1337/angular2-polyfills.js:1482:34)
    at BrowserDomAdapter.onAndCancel (http://localhost:1337/angular2-all.umd.js:28857:13)
    at http://localhost:1337/angular2-all.umd.js:27561:97
    at Zone.run (http://localhost:1337/angular2-polyfills.js:1243:25)
    at NgZone.runOutsideAngular (http://localhost:1337/angular2-all.umd.js:13244:37)
    at DomEventsPlugin.addEventListener (http://localhost:1337/angular2-all.umd.js:27561:40)
    at EventManager.addEventListener (http://localhost:1337/angular2-all.umd.js:27609:24)
    at DomRenderer.listen (http://localhost:1337/angular2-all.umd.js:28064:49)
    at DebugDomRenderer.listen (http://localhost:1337/angular2-all.umd.js:29561:32) <navbar-settings class="col-xs-9 navbar-settings" [user]="user" id="NG2_UPGRADE_0_navbarSettings_c0">
```

**Comment by Zizzamia** [comment]
Hi @teropa 
Having the two component in the same file, as showed in your plunker works fine.
In case I import the second component from a separate file, I get the error above.

**Comment by petebacondarwin** [comment]
@Zizzamia - can you modify the plunker that @teropa provided to demo your problem, if you still have it.

**Comment by petebacondarwin** [comment]
Closing due to lack of response. @Zizzamia if you are still having this issue, please reopen and post a reproduction.
