### ISSUE TITLE
Quickstart with Angular 2.0.0-beta.6 doesn't work

### ISSUE THREAD

**Issue by Vrael** [angular/angular#7138]
I have just run [Quick-Start Tutorial](https://angular.io/docs/ts/latest/quickstart.html) but it doesn't work. With Angular 2.0.0-beta.3 there wasn't problem but for this new version when I launch: `npm start` the following error is displayed:

```
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] 16.02.17 15:58:27 200 GET /index.html
[0] 3:58:27 PM - Compilation complete. Watching for file changes.
[1] [BS] File changed: app/app.component.js
[1] [BS] File changed: app/main.js
[1] 16.02.17 15:58:27 304 GET /node_modules/es6-shim/es6-shim.min.js
[1] 16.02.17 15:58:27 304 GET /node_modules/systemjs/dist/system-polyfills.js
[1] 16.02.17 15:58:27 304 GET /node_modules/angular2/bundles/angular2-polyfills.js
[1] 16.02.17 15:58:27 304 GET /node_modules/systemjs/dist/system.src.js
[1] 16.02.17 15:58:27 304 GET /node_modules/rxjs/bundles/Rx.js
[1] 16.02.17 15:58:27 304 GET /node_modules/angular2/bundles/angular2.dev.js
[1] 16.02.17 15:58:28 404 GET /favicon.ico
[1] 16.02.17 15:58:28 200 GET /app/main.js
[1] 16.02.17 15:58:29 200 GET /app/app.component.js
[1] events.js:154
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: watch node_modules/lite-server/node_modules/browser-sync/node_modules/localtunnel/node_modules/yargs/node_modules/cliui/node_modules/wrap-ansi/index.js ENOSPC
[1]     at exports._errnoException (util.js:856:11)
[1]     at FSWatcher.start (fs.js:1313:19)
[1]     at Object.fs.watch (fs.js:1341:11)
[1]     at createFsWatchInstance (/home/ciro/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[1]     at setFsWatchListener (/home/ciro/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ciro/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleFile (/home/ciro/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:255:21)
[1]     at FSWatcher.<anonymous> (/home/ciro/workspace/angular2-quickstart/node_modules/lite-server/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:473:21)
[1]     at FSReqWrap.oncomplete (fs.js:82:15)
[1] 
[1] npm 
[1] ERR! Linux 4.2.0-27-generic
[1] npm
[1]  ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "lite"
[1] npm 
[1] ERR! node v5.6.0
[1] npm 
[1] ERR! npm  v3.6.0
[1] npm
[1]  ERR! code ELIFECYCLE
[1] npm ERR! angular2-quickstart@1.0.0 lite: `lite-server`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the angular2-quickstart@1.0.0 lite script 'lite-server'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     lite-server
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs angular2-quickstart
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls angular2-quickstart
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR!
[1]  Please include the following file with any support request:
[1] npm ERR!     /home/ciro/workspace/angular2-quickstart/npm-debug.log
[1] npm run lite exited with code 1
```

**Comment by rdphv** [comment]
+1

**Comment by NaotoE0** [comment]
I've got the same problem.

**Comment by AndresRCB** [comment]
The problem is with lite-server (probably just for some OS; I was having the same issue). Try http-server or something similar while this is either updated in the quickstart or the issue with lite-server is fixed.

**Comment by AndresRCB** [comment]
Or just use an older version of lite-server in the meantime.

These devDependencies work fine for me on Ubuntu 14.04 with angular 2.0.0-beta.7
```json
"devDependencies": {
    "concurrently": "^1.0.0",
    "lite-server": "^1.3.1",
    "typescript": "^1.7.5",
    "typings": "^0.6.8"
  }
```

**Comment by Vrael** [comment]
I tried with that dependencies but they don't work properly for Ubuntu 15.10 with angular 2.0.0-beta.6. I have replaced lite-server for [nano-server](https://github.com/tsherif/nano-server) and that is working right.

**Comment by 21th** [comment]
[nano-server](https://github.com/tsherif/nano-server) works fine. Thank you Vrael.

**Comment by 592da** [comment]
Same problem here for  Angular 2.0.0-beta.7 :(

**Comment by SanderPs** [comment]
This could be a rights issue.
Did you start your shell with administrator rights (Windows)? Or run `npm start` with `sudo` (Mac)?

**Comment by sinatosk** [comment]
same issue with beta 8

**Comment by aplatypus** [comment]
Same error on linux mint .

The web page comes up in the browser, then then the 'connection' drops and the page fails.  I don't understand that part where a single page 'fails' like that.

The error is a connection error

      Firefox can't establish a connection to the server at localhost:3000

I am supposing that the page is being reloaded or refreshed on the server-side.  My Angular-1 experience was that a page's logic was single-page (client side) in the browser?

Anyhow the flaw is in the server.  When lite-server installs on Linux it can't install optional dependencies for:
      npm WARN optional Skipping failed optional dependency /lite-server/chokidar/fsevents:
      npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8

Which apparently only work on Mac.  Not surprising then that the reports here are for Linux machines if there is part of the issue.

Log attached:
[npm-debug.log.txt](https://github.com/angular/angular/files/163943/npm-debug.log.txt)

**Comment by melkir** [comment]
Hello, 
I have a bug with lite-server too. It's start, open my browser, display the message "My First Angular 2 App" and crash.
My system : Linux 4.4.3-1-ARCH

The error : 

> events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: watch node_modules/angular2/es6/prod/src/platform/dom/debug/ng_probe.js ENOSPC
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/melkir/WebstormProjects/angular2-quickstart/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/melkir/WebstormProjects/angular2-quickstart/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/melkir/WebstormProjects/angular2-quickstart/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/melkir/WebstormProjects/angular2-quickstart/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/melkir/WebstormProjects/angular2-quickstart/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by AndresRCB** [comment]
From [this answer](http://stackoverflow.com/questions/34335340/angular2-quickstart-npm-start-is-not-working-correctly/35317737#35317737) in Stackoverflow:

To resolve ENOSPC errors, run this console command:
```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
Then run npm install again (it works even though I'm still getting the fsevents dependency warning).

Running that command works for my VM (Ubuntu 14.04) and a friend's environment (Ubuntu 15.10) on Betas 6, 7 and 8. The whole post seems helpful but I don't see any need to install lite-server or anything else globally.

**Comment by aplatypus** [comment]
@AndresRGB -- Good find, yes it also got me working.  It is a very large number of user waits though:

     fs.inotify.max_user_watches=524288

Hope that isn't likely to be a fixture.  I know some very busy apps now running in Java that may '_need_' numbers like that.  If I want to port any of that kind of thing, I'd need a quantum computer!

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166473.
------------------------------------------------------------------------------------------------------------


[[ff688442c20745ca909f059fc1c37b7e350b836e-673073585]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166484.
------------------------------------------------------------------------------------------------------------


[[af43e9195e119e1af6013d1c803607604ddd0a35-673073780]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166498.
------------------------------------------------------------------------------------------------------------


[[4300fa98441f59b4a99dfc8ef2e94dca391f96a0-673073824]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166520.
------------------------------------------------------------------------------------------------------------


[[1b2f3c5c990478f8603af61ab8cbc096946e41df-673073938]]

**Comment by alexeagle** [comment]
`lite-server` is no longer in `package.json`

**Comment by saadaouad** [comment]
Must change the file "package.json" below : 
`{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "npm run lite",
    "lite": "lite-server"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",

    "core-js": "^2.4.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12",

    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0"
  }
}`

**Comment by saadaouad** [comment]
Must change the file "package.json" by this :point_down:
`
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "npm run lite",
    "lite": "lite-server"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",

    "core-js": "^2.4.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12",

    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0"
  }
}
`

**Comment by saadaouad** [comment]
Must change the file "package.json" by this : 
:point_down:
`{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "npm run lite",
    "lite": "lite-server"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",

    "core-js": "^2.4.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "0.6.12",

    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0"
  }
}`
