### ISSUE TITLE
ngFor trackBy error

### ISSUE THREAD

**Issue by park9140** [angular/angular#7193]
I am getting the below error when doing a bunch of changes while using trackBy.  It appears to happen whenever I have outstanding changes and swap put the source array of the ngFor.

```
EXCEPTION: TypeError: Cannot read property 'ref' of undefined in [tasks in TaskListComponent@3:12]
browser_adapter.js:81 EXCEPTION: TypeError: Cannot read property 'ref' of undefined in [tasks in TaskListComponent@3:12]BrowserDomAdapter.logError @ browser_adapter.js:81BrowserDomAdapter.logGroup @ browser_adapter.js:92ExceptionHandler.call @ exception_handler.js:53(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82(anonymous function) @ ng_zone.js:174NgZone.run @ ng_zone.js:137(anonymous function) @ application_ref.js:265schedulerFn @ async.js:112SafeSubscriber.__tryOrUnsub @ Subscriber.js:163SafeSubscriber.next @ Subscriber.js:118Subscriber._next @ Subscriber.js:78Subscriber.next @ Subscriber.js:55Subject._finalNext @ Subject.js:124Subject._next @ Subject.js:116Subject.next @ Subject.js:75EventEmitter.emit @ async.js:93(anonymous function) @ ng_zone.js:68Zone.run @ core.js:79NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 ORIGINAL EXCEPTION: TypeError: Cannot read property 'ref' of undefinedBrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:62(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82(anonymous function) @ ng_zone.js:174NgZone.run @ ng_zone.js:137(anonymous function) @ application_ref.js:265schedulerFn @ async.js:112SafeSubscriber.__tryOrUnsub @ Subscriber.js:163SafeSubscriber.next @ Subscriber.js:118Subscriber._next @ Subscriber.js:78Subscriber.next @ Subscriber.js:55Subject._finalNext @ Subject.js:124Subject._next @ Subject.js:116Subject.next @ Subject.js:75EventEmitter.emit @ async.js:93(anonymous function) @ ng_zone.js:68Zone.run @ core.js:79NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:65(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82(anonymous function) @ ng_zone.js:174NgZone.run @ ng_zone.js:137(anonymous function) @ application_ref.js:265schedulerFn @ async.js:112SafeSubscriber.__tryOrUnsub @ Subscriber.js:163SafeSubscriber.next @ Subscriber.js:118Subscriber._next @ Subscriber.js:78Subscriber.next @ Subscriber.js:55Subject._finalNext @ Subject.js:124Subject._next @ Subject.js:116Subject.next @ Subject.js:75EventEmitter.emit @ async.js:93(anonymous function) @ ng_zone.js:68Zone.run @ core.js:79NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 TypeError: Cannot read property 'ref' of undefined
    at ViewContainerRef_.get (view_container_ref.js:47)
    at ng_for.js:84
    at DefaultIterableDiffer.forEachIdentityChange (default_iterable_differ.js:105)
    at NgFor._applyChanges (ng_for.js:82)
    at NgFor.ngDoCheck (ng_for.js:58)
    at AbstractChangeDetector.ChangeDetector_TaskListComponent_1.detectChangesInRecordsInternal (viewFactory_TaskListComponent:207)
    at AbstractChangeDetector.detectChangesInRecords (abstract_change_detector.js:105)
    at AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:88)
    at AbstractChangeDetector._detectChangesContentChildren (abstract_change_detector.js:167)
    at AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:89)BrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:66(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82(anonymous function) @ ng_zone.js:174NgZone.run @ ng_zone.js:137(anonymous function) @ application_ref.js:265schedulerFn @ async.js:112SafeSubscriber.__tryOrUnsub @ Subscriber.js:163SafeSubscriber.next @ Subscriber.js:118Subscriber._next @ Subscriber.js:78Subscriber.next @ Subscriber.js:55Subject._finalNext @ Subject.js:124Subject._next @ Subject.js:116Subject.next @ Subject.js:75EventEmitter.emit @ async.js:93(anonymous function) @ ng_zone.js:68Zone.run @ core.js:79NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:69(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82(anonymous function) @ ng_zone.js:174NgZone.run @ ng_zone.js:137(anonymous function) @ application_ref.js:265schedulerFn @ async.js:112SafeSubscriber.__tryOrUnsub @ Subscriber.js:163SafeSubscriber.next @ Subscriber.js:118Subscriber._next @ Subscriber.js:78Subscriber.next @ Subscriber.js:55Subject._finalNext @ Subject.js:124Subject._next @ Subject.js:116Subject.next @ Subject.js:75EventEmitter.emit @ async.js:93(anonymous function) @ ng_zone.js:68Zone.run @ core.js:79NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 _Context {element: comment, componentElement: comment, context: TaskListComponent, locals: Object, injector: Injector…}BrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:70(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82(anonymous function) @ ng_zone.js:174NgZone.run @ ng_zone.js:137(anonymous function) @ application_ref.js:265schedulerFn @ async.js:112SafeSubscriber.__tryOrUnsub @ Subscriber.js:163SafeSubscriber.next @ Subscriber.js:118Subscriber._next @ Subscriber.js:78Subscriber.next @ Subscriber.js:55Subject._finalNext @ Subject.js:124Subject._next @ Subject.js:116Subject.next @ Subject.js:75EventEmitter.emit @ async.js:93(anonymous function) @ ng_zone.js:68Zone.run @ core.js:79NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:91 EXCEPTION: TypeError: Cannot read property 'ref' of undefined in [tasks in TaskListComponent@3:12]
browser_adapter.js:81 EXCEPTION: TypeError: Cannot read property 'ref' of undefined in [tasks in TaskListComponent@3:12]BrowserDomAdapter.logError @ browser_adapter.js:81BrowserDomAdapter.logGroup @ browser_adapter.js:92ExceptionHandler.call @ exception_handler.js:53(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 ORIGINAL EXCEPTION: TypeError: Cannot read property 'ref' of undefinedBrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:62(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:65(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 TypeError: Cannot read property 'ref' of undefined
    at ViewContainerRef_.get (view_container_ref.js:47)
    at ng_for.js:84
    at DefaultIterableDiffer.forEachIdentityChange (default_iterable_differ.js:105)
    at NgFor._applyChanges (ng_for.js:82)
    at NgFor.ngDoCheck (ng_for.js:58)
    at AbstractChangeDetector.ChangeDetector_TaskListComponent_1.detectChangesInRecordsInternal (viewFactory_TaskListComponent:207)
    at AbstractChangeDetector.detectChangesInRecords (abstract_change_detector.js:105)
    at AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:88)
    at AbstractChangeDetector._detectChangesContentChildren (abstract_change_detector.js:167)
    at AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:89)BrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:66(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 ERROR CONTEXT:BrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:69(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
browser_adapter.js:81 _Context {element: comment, componentElement: comment, context: TaskListComponent, locals: Object, injector: Injector…}BrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:70(anonymous function) @ application_ref.js:166NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156Zone.run @ core.js:82NgZone._notifyOnTurnDone @ ng_zone.js:67(anonymous function) @ ng_zone.js:182arguments.(anonymous function) @ functions.js:30
exception_handler.js:74 Uncaught EXCEPTION: TypeError: Cannot read property 'ref' of undefined in [tasks in TaskListComponent@3:12]
ORIGINAL EXCEPTION: TypeError: Cannot read property 'ref' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'ref' of undefined
    at ViewContainerRef_.get (http://tm.daptiv.com/main.js:46579:46)
    at http://tm.daptiv.com/main.js:22571:44
    at DefaultIterableDiffer.forEachIdentityChange (http://tm.daptiv.com/main.js:47130:9)
    at NgFor._applyChanges (http://tm.daptiv.com/main.js:22570:15)
    at NgFor.ngDoCheck (http://tm.daptiv.com/main.js:22545:16)
    at AbstractChangeDetector.ChangeDetector_TaskListComponent_1.detectChangesInRecordsInternal (viewFactory_TaskListComponent:207:48)
    at AbstractChangeDetector.detectChangesInRecords (http://tm.daptiv.com/main.js:51037:14)
    at AbstractChangeDetector.runDetectChanges (http://tm.daptiv.com/main.js:51020:12)
    at AbstractChangeDetector._detectChangesContentChildren (http://tm.daptiv.com/main.js:51099:14)
    at AbstractChangeDetector.runDetectChanges (http://tm.daptiv.com/main.js:51021:12)
ERROR CONTEXT:
[object Object]
```
 
Offending Component implementation
```typescript
@Component({
    selector: 'task-list.block-component',
    inputs: ['tasks'],
    directives: [NgFor, NgIf, TaskItemComponent],
    template: `
    <div *ngIf="tasks.length > 0">
        <task-item
            *ngFor="var task of tasks; #i=index; trackBy:taskTrackBy"
            [task]="task"
            (taskFlagChanged)="taskFlagStateChanged(task, $event)"
            (dragstart)="$event.dataTransfer.setData('task', task.id)"></task-item>
    </div>
    <div *ngIf="tasks.length === 0">No Tasks available.</div>
    `
})
export class TaskListComponent {
    constructor(private dispatcher: Dispatcher) {
    }

    taskTrackBy(index: number, task: Task) {
        return task.id;
    }

    taskFlagStateChanged(task: Task, flagState: boolean) {
        if (flagState) {
            this.dispatcher.sendAction(TaskActions.Flag.create(task));
        } else {
            this.dispatcher.sendAction(TaskActions.Unflag.create(task));
        }
    }
```

**Comment by ericmdantas** [comment]
I'm getting this error when adding stuff to a list and then removing.

This works (no track by):

http://plnkr.co/edit/AHokJdeO9ussO4mEm3cZ?p=preview

This doesn't (with track by):

http://plnkr.co/edit/jvAg7SwwhYEBdCIZHMvs?p=preview

**Comment by park9140** [comment]
@ericmdantas, with a small change to make the items you are adding and removing have different indexes then problem goes away.   
http://plnkr.co/edit/HV1uckdwKMGsKoez1tYF?p=preview

I think the underlaying issue is when the view is re-rendered when the underlaying object changes but the key reported by the trackBy function is reported as the same.   In your example you add something with a value of a number like 2 and it has index 2 then you delete one and the thing with index 2 is now index 1.  By having unique keys added and removed it works fine. 

Just what I am noticing, hope this helps.

**Comment by ericmdantas** [comment]
That works, thanks!

**Comment by park9140** [comment]
@ericmdantas, Also my new version has a reverse button.  If you add more than one item then click reverse everything locks up tight in chrome.  Doing a change in sort order if you create new objects is apparently failing as well.

**Comment by park9140** [comment]
@vsavkin,  I have been looking at fixing this tonight but I may be over my head a bit as I haven't had much experience in the core of angular 2 yet. You were the last person I see to have touched the code i've been looking at.

 I ran through the itterable change detector logic
https://github.com/angular/angular/blob/master/modules/angular2/src/core/change_detection/differs/default_iterable_differ.ts#L471-L492
This method seems to be the core of the problem.  When items are evicted their '_nextIdentityChange' value doesn't seem to get removed and when it is brought back by the following 
https://github.com/angular/angular/blob/master/modules/angular2/src/core/change_detection/differs/default_iterable_differ.ts#L242-L253 
It has hanging references.  In my second case where I reverse and rebuild the objects it causes an infinite loop in the change detector.  In the first case where we lose the ref object I'm not sure what is happening yet.

If you have any insight you can give it would be great.

**Comment by park9140** [comment]
@vsavkin I looked a little deeper and the same lack of removal of `_nextIdentityChange` seems to cause the issue in the ngFor change detection
https://github.com/angular/angular/blob/master/modules/angular2/src/common/directives/ng_for.ts#L121-L124

The change detection when using index pulls in removed instances and they all have existing and non removed `_nextIdentityChange` values set.

**Comment by kara** [comment]
@park9140 I'll look into this. Preliminarily, I think you're right that we forgot to clean out the _nextIdentityChanges props when we reset the iterable differ.  PR to come soon.

**Comment by park9140** [comment]
@kara, thanks looking forward to this being fixed :+1:

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166491.
------------------------------------------------------------------------------------------------------------


[[7d0bfc07d5004b828443580512305c7aba221883-673073804]]

**Comment by tom10271** [comment]
I need to provide a trackBy method to ngFor? It would be great with syntax like:`*ngFor="#page of book; trackBy = page.id"`.

Most of the time we are tracking object by one of the attribute only right?
