### ISSUE TITLE
Quickstart SyntaxError in IE10

### ISSUE THREAD

**Issue by Slowbad** [angular/angular#7263]
Followed the Angular 2 quickstart. The page works fine in Chrome and Firefox but the browser we use at work, IE10, dumps the following error into the console. 

```
SyntaxError: Expected ';'
   at evalExpression (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:451:5)
   at _createViewFactoryRuntime (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24364:9)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24318:13)
   at run (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1243:14)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:13558:15)
   at zoneBoundFn (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1220:14)
   at lib$es6$promise$$internal$$tryCatch (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:468:10)
   at lib$es6$promise$$internal$$invokeCallback (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:480:10)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1028:14)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:123:10)

-----async gap-----
Error
   at _getStacktraceWithCaughtError (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:2248:10)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:2293:14)
   at bind (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1218:10)
   at bindArguments (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1401:14)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1413:18)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24316:11)
   at run (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1243:14)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:13558:15)
   at zoneBoundFn (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1220:14)
   at lib$es6$promise$$internal$$tryCatch (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:468:10)

-----async gap-----
Error
   at _getStacktraceWithCaughtError (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:2248:10)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:2293:14)
   at bind (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1218:10)
   at bindArguments (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1401:14)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1413:18)
   at _compileComponentRuntime (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24305:9)
   at _compileNestedComponentRuntime (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24333:7)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24314:13)
   at forEach (http://localhost:59813/node_modules/es6-shim/es6-shim.min.js:10:16871)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24313:11)

-----async gap-----
Error
   at _getStacktraceWithCaughtError (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:2248:10)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:2293:14)
   at bind (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1218:10)
   at bindArguments (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1401:14)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:1413:18)
   at _compileComponentRuntime (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24305:9)
   at compileHostComponentRuntime (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24259:9)
   at compileInHost (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24610:7)
   at loadAsRoot (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:12355:7)
   at useFactory (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:12453:9)

-----async gap-----
Error
   at _getStacktraceWithCaughtError (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:2248:10)
   at Anonymous function (http://localhost:59813/node_modules/angular2/bundles/angular2-polyfills.js:2293:14)
   at _createInnerZone (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:13546:7)
   at NgZone (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:13412:9)
   at createNgZone (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:12475:5)
   at application (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:12550:7)
   at bootstrap (http://localhost:59813/node_modules/angular2/bundles/angular2.dev.js:24805:5)
   at execute (eval code:14:13)
   at ensureEvaluated (http://localhost:59813/node_modules/systemjs/dist/system.src.js:3186:5)
   at execute (http://localhost:59813/node_modules/systemjs/dist/system.src.js:3304:13) 
```

Using these dependencies

```
"dependencies": {
    "angular2": "2.0.0-beta.7",
    "systemjs": "0.19.22",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.5.15"
  }
```

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/6501

**Comment by Slowbad** [comment]
Thanks @ericmartinezr. Closing the issue.
