### ISSUE TITLE
Web Worker error

### ISSUE THREAD

**Issue by jimitndiaye** [angular/angular#7392]
I have the following worker app:
```typescript
import 'es6-shim';
import 'es6-promise';
import 'reflect-metadata';
import 'zone.js/dist/zone-microtask';
import 'zone.js/dist/long-stack-trace-zone';

import { FormBuilder } from 'angular2/common';
import { APP_BASE_HREF, Router, ROUTER_BINDINGS  } from 'angular2/router';
import { Http, HTTP_PROVIDERS } from 'angular2/http';

import { App } from './components/app/app';

// browser bootstrap
// import { bootstrap } from 'angular2/platform/browser';
//bootstrap(App, [ROUTER_BINDINGS, HTTP_PROVIDERS, FormBuilder]); 

// worker imports
import { platform, provide, ApplicationRef, ComponentRef, Injector } from 'angular2/core';
import { WORKER_APP_PLATFORM, WORKER_APP_APPLICATION, WORKER_APP_ROUTER } from 'angular2/platform/worker_app';

// worker bootstrap
platform(WORKER_APP_PLATFORM).asyncApplication(() => Promise.resolve([
    WORKER_APP_APPLICATION,
    WORKER_APP_ROUTER,
    provide(APP_BASE_HREF, { useValue: '/' }),
]))
    .then((appRef: ApplicationRef) => {
        return appRef.bootstrap(App, [ROUTER_BINDINGS, HTTP_PROVIDERS, FormBuilder]);
    })
    .then((compRef: ComponentRef) => {
        const injector: Injector = compRef.injector;
        const router: Router = injector.get(Router);

        return (<any>router)._currentNavigation;
    })
    .then(() => {
        setTimeout(() => {
            postMessage('APP_READY', undefined);
        });
    });

// Basic hot reloading support. Automatically reloads and restarts the Angular 2 app each time
// you modify source files. This will not preserve any application state other than the URL.
declare var module: any;
if (module.hot) {
    module.hot.accept();
}
```
When the worker loads I get the following error
```
EXCEPTION: Error during instantiation of PlatformLocation! (RouterLink -> Router -> Location -> LocationStrategy -> PlatformLocation).
vendor.js:1 STACKTRACE:
vendor.js:1 

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:5000/dist/vendor.js:103:18839)
    at Zone.fork (http://localhost:5000/dist/vendor.js:103:20207)
    at Zone.bind (http://localhost:5000/dist/vendor.js:110:18797)
    at bindArguments (http://localhost:5000/dist/vendor.js:110:22448)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://localhost:5000/dist/vendor.js:110:22625)
    at DynamicComponentLoader_.loadAsRoot (http://localhost:5000/dist/vendor.js:35:31134)
    at di_1.provide.useFactory (http://localhost:5000/dist/vendor.js:49:5231)
    at Injector._instantiate (http://localhost:5000/dist/vendor.js:52:3613)
    at Injector._instantiateProvider (http://localhost:5000/dist/vendor.js:52:1650)
    at Injector._new (http://localhost:5000/dist/vendor.js:52:1279)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:5000/dist/vendor.js:103:18839)
    at Zone.fork (http://localhost:5000/dist/vendor.js:103:20207)
    at NgZone._createInnerZone (http://localhost:5000/dist/vendor.js:39:25809)
    at new NgZone (http://localhost:5000/dist/vendor.js:39:22738)
    at createNgZone (http://localhost:5000/dist/vendor.js:49:5876)
    at PlatformRef_.asyncApplication (http://localhost:5000/dist/vendor.js:49:8966)
    at Object.<anonymous> (http://localhost:5000/dist/main.js:12:23695)
    at __webpack_require__ (http://localhost:5000/dist/main.js:1:229)
    at Object.<anonymous> (http://localhost:5000/dist/main.js:1:540)
    at __webpack_require__ (http://localhost:5000/dist/main.js:1:229)
vendor.js:1 ORIGINAL EXCEPTION: not implemented
```

**Comment by zoechi** [comment]
looks like https://angular.io/docs/ts/latest/api/router/ROUTER_PROVIDERS-let.html is missing

For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by jimitndiaye** [comment]
Thanks. Adding that fixed that problem but ended up with more errors that I'll forward through the channels you suggest above.
