### ISSUE TITLE
npm run build failing on Windows

### ISSUE THREAD

**Issue by davidreher** [angular/angular#7457]
Hey,

I did a fresh checkout of master today 75ae4a9 and tried to do a `npm run build`. I have the same issue on Windows 7 and Windows 10 (both x64).

Here is the log:
```
C:\dev\angular [master ≡]> npm run build

> angular-srcs@2.0.0-beta.8 build C:\dev\angular
> node --max-old-space-size=2048 ./node_modules/.bin/gulp build.js

C:\dev\angular\node_modules\.bin\gulp:4
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular-srcs@2.0.0-beta.8 build: `node --max-old-space-size=2048 ./node_modules/.bin/gulp build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-srcs@2.0.0-beta.8 build script 'node --max-old-space-size=2048 ./node_modules/.bin/gulp build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-srcs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --max-old-space-size=2048 ./node_modules/.bin/gulp build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-srcs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-srcs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\angular\npm-debug.log
```

The complete log can be found here http://paste.ubuntu.com/15320322/

When doing a `gulp build.js` I am running out of disk space after quite some time (> 10GB are free before and afterwards)

Replacing the command with `node --max-old-space-size=2048 ./node_modules/gulp/bin/gulp.js build.js` does not fail immediately but I am running out of space again :/

**Comment by davidreher** [comment]
When doing a gulp build I am running out of disk space after quite some time (> 10GB are free before and afterwards)

**Comment by zackhall** [comment]
I'm also having trouble building on Windows.

**I need to run `npm i` twice**
The first time it fails with an error message like this: 

```
npm ERR! Windows_NT 10.0.14317
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\zackhall\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v5.7.1
npm ERR! npm  v3.8.0
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
```

**If I run `npm run build` or `node --max_old_space_size=2048 ./node_modules/.../gulp build.js`**
It fails immediately with this message.
```
> node --max_old_space_size=2048 ./node_modules/.bin/gulp build.js
E:\github\ng2\node_modules\.bin\gulp:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**If I simply run `gulp build.js`**
I get some output, but then it gets stuck at this last stage and never changes.

```
> gulp build.js
Dart SDK is not available, Dart tasks will be skipped.
[13:09:07] Using gulpfile E:\github\ng2\gulpfile.js
[13:09:07] Starting 'build/clean.js'...
[13:09:07] Starting 'build/clean.tools'...
[13:09:07] Starting 'build/clean.dart'...
Dart SDK is not available. Skipping task: build/clean.dart
[13:09:07] Finished 'build/clean.dart' after 279 μs
[13:09:07] Starting 'build/clean.docs'...
[13:09:07] Starting 'build/clean.bundles'...
[13:09:07] Starting 'build/clean.bundles.benchpress'...
[13:09:07] Finished 'build/clean.docs' after 32 ms
[13:09:07] Finished 'build/clean.bundles' after 32 ms
[13:09:07] Finished 'build/clean.bundles.benchpress' after 33 ms
[13:09:07] Finished 'build/clean.js' after 222 ms
[13:09:07] Starting 'build.js.dev'...
[13:09:07] Finished 'build/clean.tools' after 230 ms
[13:09:07] Starting 'build.tools'...
[13:09:07] Starting '!build.tools'...
[13:09:10] Starting 'clean'...
[13:09:10] Finished 'clean' after 7.41 μs
[13:09:10] Starting '!bundle.ng.polyfills'...
[13:09:14] Starting '!bundles.js.docs'...
[13:09:14] Finished '!bundles.js.docs' after 94 ms
[13:09:14] Finished '!bundle.ng.polyfills' after 4.4 s
[13:09:22] Finished '!build.tools' after 15 s
[13:09:22] Finished 'build.tools' after 15 s
[13:09:22] Starting 'broccoli.js.dev'...
[13:09:22] Starting '!broccoli.js.dev'...
[13:09:22] Starting 'build.js.prod'...
[13:09:22] Starting '!broccoli.js.prod'...
[13:09:22] Starting 'build.js.cjs'...
[13:09:22] Starting '!build.js.cjs'...
```

**Comment by IgorMinar** [comment]
obsolete. we have limited support for building on windows at the moment.

**Comment by zackhall** [comment]
cc/ @jdalton

**Comment by jdalton** [comment]
Thanks for the ping @zackhall!

**Comment by jdalton** [comment]
@IgorMinar Is there an issue/pr/wiki tracking what's missing for full Windows support?
