### ISSUE TITLE
Using a selector for the main AppComponent other than my-app fails

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [angular/angular#7514]
I'm submitting a bug report

* **What is the current behavior?**
When I choose a selector for the AppComponent (the component that we bootstrap in main) other than 'my-app'. The application fails with the exception:

EXCEPTION: The selector "the-name-that-I-chose" did not match any elements

- Angular version: 2.0.0-beta.8
- Browser: all
- Language: TypeScript

Detailed Error:

> Error: The selector "saugo-viewer" did not match any elements
    at new BaseException (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:7385:21)
    at DomRenderer.selectRootElement (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:13731:15)
    at DebugDomRenderer.selectRootElement (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:7196:37)
    at HostViewFactory.viewFactory_HostAppComponent0 [as viewFactory] (viewFactory_HostAppComponent:72:18)
    at AppViewManager_.createRootHostView (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:6500:34)
    at http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:12254:46
    at Zone.run (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:13456:32)
    at zoneBoundFn (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)
    at lib$es6$promise$$internal$$tryCatch (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:468:17)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29)
    at Zone.fork (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47)
    at Zone.bind (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at DynamicComponentLoader_.loadAsRoot (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:12253:49)
    at di_1.provide.useFactory (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:12351:39)
    at Injector._instantiate (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:11361:19)
    at Injector._instantiateProvider (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:11294:21)
    at Injector._new (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:11284:19)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29)
    at Zone.fork (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47)
    at NgZone._createInnerZone (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:13444:39)
    at new NgZone (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:13310:32)
    at createNgZone (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:12373:12)
    at PlatformRef_.application (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:12448:31)
    at Object.bootstrap (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:25239:64)
    at execute (http://localhost:3000/app/compiledJS/main.js:14:23)
    at ensureEvaluated (http://localhost:3000/node_modules/systemjs/dist/system.src.js:3186:26)
    at Object.execute (http://localhost:3000/node_modules/systemjs/dist/system.src.js:3304:13)

**Comment by brandonroberts** [comment]
Did you update your index.html to match the selector for your app?

**Comment by AbdulRahmanAlHamali** [comment]
I'm using SystemJS, as in the tutorial, so I did not actually write the selector anywhere other than in the component decorator

**Comment by brandonroberts** [comment]
Ok, so your index.html it has the selector for your application in it. It needs to match the selector in your component decorator.

**Comment by AbdulRahmanAlHamali** [comment]
Apologies, you are right.

I will delete the issue

**Comment by danbachar** [comment]
I have the same issue, but my selector matches. I have checked that my module isn't being bootstrapped anywhere other then in main.ts. Any suggestions?

**Comment by danbachar** [comment]
My app component is as following: 

`import {Component} from '@angular/core';

      @Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
})
export class AppComponent{
}
`

My module is as following:
`
import { NgModule } from '@angular/core'
import { RouterModule } from '@angular/router';
import { rootRouterConfig } from './app.routes';
import { AppComponent } from './app.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';

import { LocationStrategy, HashLocationStrategy } from '@angular/common';
import {AboutComponent} from "./components/about/about.component";
import {CampaignsComponent} from "./components/campaigns/campaigns.component";
import {ListComponent} from "./components/list/list.component";
import {ContactComponent} from "./components/contact/contact.component";

@NgModule({
  declarations: [
    AppComponent,
    ... other components
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    RouterModule.forRoot(rootRouterConfig, { useHash: true })
  ],
  bootstrap: [ AppComponent]
})
export class AppModule {

}
`

my main.ts is as following: 
`
import './polyfills.browser';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';
import {platformBrowser} from "@angular/platform-browser";

platformBrowser().bootstrapModule(AppModule);

`

**Comment by brandonroberts** [comment]
@danbachar you should be using 

```ts
platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by danbachar** [comment]
I had been using this before and changed to this bootstrap because it
didn't work as well.
