### ISSUE TITLE
Unexpected directive value 'undefined' on the View of component 'HeroDetailComponent'

### ISSUE THREAD

**Issue by lburkovsky** [angular/angular#7526]
Hi,

I'm getting an exception:

EXCEPTION: Unexpected directive value 'undefined' on the View of component 'HeroDetailComponent'
STACKTRACE:
Error: Unexpected directive value 'undefined' on the View of component 'HeroDetailComponent'
    at new BaseException (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:7464:21)
    at RuntimeMetadataResolver.getViewDirectivesMetadata (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:22884:17)
    at TemplateCompiler._compileNestedComponentRuntime (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:24859:63)
    at http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:24844:26
    at Array.forEach (native)
    at Array.forEach (http://localhost:3000/node_modules/es6-shim/es6-shim.min.js:10:16878)
    at http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:24843:37
    at Zone.run (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:13543:32)
    at zoneBoundFn (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1220:26)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29)
    at Zone.fork (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47)
    at Zone.bind (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at TemplateCompiler._compileComponentRuntime (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:24837:14)
    at TemplateCompiler.compileHostComponentRuntime (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:24789:14)
    at RuntimeCompiler_.compileInHost (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:25140:37)
    at DynamicComponentLoader_.loadNextToLocation (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:12368:29)
    at RouterOutlet.activate (http://localhost:3000/node_modules/angular2/bundles/router.dev.js:2113:27)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:2244:29)
    at Zone.fork (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:2293:47)
    at Zone.bind (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1218:53)
    at bindArguments (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1401:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1413:46)
    at RootRouter.Router.commit (http://localhost:3000/node_modules/angular2/bundles/router.dev.js:3060:47)
    at RootRouter.commit (http://localhost:3000/node_modules/angular2/bundles/router.dev.js:3177:45)
    at http://localhost:3000/node_modules/angular2/bundles/router.dev.js:2981:26
    at Zone.run (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:1243:24)
    at Zone.run (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:13543:32)

I downloaded the Tour of Heroes. Updated the angular2 package to beta9.
And changed the hero-detail.component.ts to:

import { Component, Input, OnInit } from 'angular2/core';
import { RouteParams, ROUTER_DIRECTIVES } from 'angular2/router';
import { Hero, HeroService } from './hero.service';
**import { HeroesComponent} from "./heroes.component";**

@Component({
  selector: 'my-hero-detail',
  templateUrl: 'app/hero-detail.component.html',
  styleUrls: ['app/hero-detail.component.css'],
  directives: [ROUTER_DIRECTIVES, **HeroesComponent**]
})
export class HeroDetailComponent implements OnInit {
  @Input() hero: Hero;

  constructor(private _heroService: HeroService,
    private _routeParams: RouteParams) {
  }

  ngOnInit() {
    if (!this.hero) {
      let id = +this._routeParams.get('id');
      this._heroService.getHero(id).then(hero => this.hero = hero);
    }
  }
}

I need the conditional template recursion in my project.

Regards,
Ladislav

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/issues/7433 , don't mix single quotes and double quotes in your imports.

**Comment by lburkovsky** [comment]
the problem persists after changing to 
import { HeroesComponent} from './heroes.component';

I'm using the typescript 1.8

**Comment by ericmartinezr** [comment]
@lburkovsky reproduce it a in plnkr pls

**Comment by lburkovsky** [comment]
http://plnkr.co/edit/gi9ec34l9AV4fnkLISjY
click on a hero

**Comment by ericmartinezr** [comment]
@lburkovsky I see now, that seems to be a circular reference issue

**hero-detail.component.ts**
```
import { HeroesComponent } from './heroes.component';
```

**heroes.component**
```
import { HeroDetailComponent } from './hero-detail.component';
```

If you add `forwardRef` you can avoid the error message

hero-detail.component.ts
```
import { ..., forwardRef } from 'angular2/core';
directives:[forwardRef(() => HeroesComponent)]
```

I found the plnkr in the tutorial here https://angular.io/resources/live-examples/toh-5/ts/plnkr.html and it's working, `hero-detail.component.ts` doesn't import `HeroComponent`. Try following that plnkr.

**Comment by scaryroy** [comment]
Is there any way to get around this circular dependency issue?

I have a situation where on a student detail page, I have a list of lessons that the student has had.
The list of lessons also shows other students belonging to that lesson.

I then try to show a dialog of the details of another student (which uses the same view) and it causes this error.

**Comment by lburkovsky** [comment]
Look at https://angular.io/docs/ts/latest/api/core/forwardRef-function.html

**Comment by scaryroy** [comment]
@lburkovsky DCL seems to take in a TYPE whereas forwardRef only seems to work with objects? Am I misunderstanding something here?

**Comment by zoechi** [comment]
@scaryroy `forwardRef` is for types

**Comment by justin-romano** [comment]
AHHHHHHH.... ok thats better.
If you are using a child component declared in the same module as you parent. 
Make sure your child component is declared "Above" (yes literally in the file)
otherwise it will not work even though the typescript compiles perfectly
The below code will not work but *will* compile
```ts
@Component({
  selector: "parent",
  template: `
    <label>
      {{label}}
    </label>
   <span>hi from parent.</span>
    <child></child>
    `,
  directives: [Child] //<==== because child is declared under parent.
})
export class Parent  {
  constructor() {
  }
}
@Component({
  selector: "child",
  template: `
  <span>hi. from child I wont work because im down here</span>
  `  
})
class Child{
  constructor() {
  }
}


```

**Comment by EdmondWang** [comment]
@justin-romano, it works for me. I moved one Pipe up to its parent component declare text,

**Comment by db6edr** [comment]
Please excuse me for chiming in to an already closed issue.

This happened to me as well: I have an index.ts as a barrel, which re-exports classes A, B and C from the files a.ts, b.ts and c.ts in that order.
In file b.ts, the line `import { C } from './index';` results in above error. This makes perfectly sense because C has **not yet** been imported in index.ts. So, the fix is to `import { C } from './c';`and you're fine.
