### ISSUE TITLE
IE11 EXCEPTION: SyntaxError: Expected ')'

### ISSUE THREAD

**Issue by MichaelThessel** [angular/angular#7632]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error in IE11 console & site doesn't render.

```
SyntaxError: Expected ')'
   at evalExpression (http://vm:3000/node_modules/angular2/bundles/angular2.dev.js:452:5)
   at TemplateCompiler.prototype._createViewFactoryRuntime (http://vm:3000/node_modules/angular2/bundles/angular2.dev.js:24895:9)
   at Anonymous function (http://vm:3000/node_modules/angular2/bundles/angular2.dev.js:24849:13)
   at e.prototype.run (http://vm:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:8698)
   at Anonymous function (http://vm:3000/node_modules/angular2/bundles/angular2.dev.js:13544:15)
   at Anonymous function (http://vm:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:8363)
   at x (http://vm:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:3165)
   at L (http://vm:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:3253)
   at Anonymous function (http://vm:3000/node_modules/angular2/bundles/angular2-polyfills.min.js:1:6757)
   at Anonymous function (http://vm:3000/node_modules/angular2/bundles/angular2-polyfills.min.js
```

angular2.dev.js:452:
```
return new (Function.bind.apply(Function, [void 0].concat(fnArgNames.concat(fnBody))))().apply(void 0, fnArgValues);
```

I added a console.log(fnBody) to before the statement.

First run output:

```
      var ChangeDetector_AppComponent_0 = function ChangeDetector_AppComponent_0() {
        AbstractChangeDetector.call(
            this, "AppComponent_0", 3,
            ChangeDetector_AppComponent_0.gen_propertyBindingTargets, ChangeDetector_AppComponent_0.gen_directiveIndices,
            5);
        this.dehydrateDirectives(false);
      }

      ChangeDetector_AppComponent_0.prototype = Object.create(AbstractChangeDetector.prototype);

      ChangeDetector_AppComponent_0.prototype.detectChangesInRecordsInternal = function(throwOnChange) {
        var l_context = this.context,l_literal0,l_getCopyYear1,c_getCopyYear1,l_interpolate2;c_getCopyYear1 = false;
        var isChanged = false;
        var changes = null;

        
        this.propertyBindingIndex = 0;
        
      l_literal0 = 2016;
      
      l_getCopyYear1 = l_context.getCopyYear(l_literal0);
    
      
        if (throwOnChange && !ChangeDetectionUtil.devModeEqual(this.getCopyYear1, l_getCopyYe
```

I then removed the getCopyYear() call from the template and ran it again. I got the same error for a different code part:

```

      var ChangeDetector_AppComponent_0 = function ChangeDetector_AppComponent_0() {
        AbstractChangeDetector.call(
            this, "AppComponent_0", 0,
            ChangeDetector_AppComponent_0.gen_propertyBindingTargets, ChangeDetector_AppComponent_0.gen_directiveIndices,
            5);
        this.dehydrateDirectives(false);
      }

      ChangeDetector_AppComponent_0.prototype = Object.create(AbstractChangeDetector.prototype);

      ChangeDetector_AppComponent_0.prototype.detectChangesInRecordsInternal = function(throwOnChange) {
        var l_context = this.context;
        var isChanged = false;
        var changes = null;

        
      }

      ChangeDetector_AppComponent_0.prototype.hydrateDirectives = function(directives) {
      this.directive_0_0 = this.getDirectiveFor(directives, 0);
      
    }

      ChangeDetector_AppComponent_0.prototype.dehydrateDirectives = function(destroyPipes) {
        if (destroyPipes) {
          
          this.directive_0_0.ngO
```

tsc doesn't output any errors.

**What is the expected behavior?**

No error.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

Windows 10
IE11.162
Angular2.beta9

This doesn't happen in the recent versions of FF, Chrome or Opera. 

Demo: http://pop-tours.com/

**Comment by ericmartinezr** [comment]
See this comment https://github.com/angular/angular/issues/7144#issuecomment-190012839

**Comment by MichaelThessel** [comment]
I got those already in place. I just double checked and replaced the local version with the CDN version to make sure I got the most recent ones but the error still persists.

**Comment by vicb** [comment]
obsolete
