### ISSUE TITLE
 Attempt to use a dehydrated detector on event/output

### ISSUE THREAD

**Issue by staeke** [angular/angular#7664]
Type: bug report
Plunkr: http://plnkr.co/edit/oK7ZF85WDOJ55FcDFFSx?p=preview
Version (UPDATED): Angular 2 beta 11

It seems Angular doesn't correctly handle cases where the following happens

1. A component's change detector ref's event handler for an event is queued for running
2. The component is destroyed
3. The event handler runs...boom

Stack trace
```
VM2930 angular2.min.js:17 Error: Attempt to use a dehydrated detector: App_1 -> clicks
    at t [as constructor] (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:5:22480)
    at new t (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:3:28022)
    at e.throwDehydratedError (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:6:10228)
    at e.handleEvent (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:6:5620)
    at eval (viewFactory_App:188:105)
    at https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:10:8834
    at c (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:10:17643)
    at https://code.angularjs.org/2.0.0-beta.9/angular2-polyfills.js:1679:44
    at Zone.run (https://code.angularjs.org/2.0.0-beta.9/angular2-polyfills.js:1243:24)
    at Zone.run (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:10:16921)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (https://code.angularjs.org/2.0.0-beta.9/angular2-polyfills.js:2244:29)
    at Zone.fork (https://code.angularjs.org/2.0.0-beta.9/angular2-polyfills.js:2293:47)
    at arguments.(anonymous function) (https://code.angularjs.org/2.0.0-beta.9/angular2-polyfills.js:1671:82)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (https://code.angularjs.org/2.0.0-beta.9/angular2-polyfills.js:2244:29)
    at Zone.fork (https://code.angularjs.org/2.0.0-beta.9/angular2-polyfills.js:2293:47)
    at e._createInnerZone (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:10:16710)
    at new e (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:10:14209)
    at i (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:9:25536)
    at t.application (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:9:27579)
    at Object.n [as bootstrap] (https://code.angularjs.org/2.0.0-beta.9/angular2.min.js:19:7168)
    at execute (http://run.plnkr.co/bxjqwalPIFfg456r/src/main.ts!transpiled:12:23)
    at u (https://code.angularjs.org/tools/system.js:5:97)
    at Object.execute (https://code.angularjs.org/tools/system.js:5:3188)
```

**Comment by zoechi** [comment]
dup of #6786 ?

**Comment by staeke** [comment]
@zoechi very likely, but i guess it should be verified by angular team

**Comment by vicb** [comment]
obsolete
