### ISSUE TITLE
Task does not support cancellation, or is already canceled in beta.11

### ISSUE THREAD

**Issue by todoubaba** [angular/angular#7671]
* **I'm submitting a**
  [x] bug report
  [  ] feature request

* **What is the current behavior?**
  When bootstrap modal dialog been open and closed twice, throws the following error:

  ```
browser_platform_location.ts:58 Error: Task does not support cancellation, or is already canceled.
    at ZoneDelegate.cancelTask (http://localhost/static/js/app/angular2.js:385:25)
    at Zone.cancelTask (http://localhost/static/js/app/angular2.js:295:46)
    at zoneAwareRemoveEventListener (http://localhost/static/js/app/angular2.js:888:26)
    at removeEventListener (eval at createNamedFn (http://localhost/static/js/app/angular2.js:969:19), <anonymous>:3:46)
    at Function.n.removeEvent (http://localhost/static/js/lib/jquery.min.js:3:9907)
    at Object.n.event.remove (http://localhost/static/js/lib/jquery.min.js:3:6844)
    at http://localhost/static/js/lib/jquery.min.js:3:11523
    at Function.n.extend.each (http://localhost/static/js/lib/jquery.min.js:2:2773)
    at n.fn.n.each (http://localhost/static/js/lib/jquery.min.js:2:845)
    at n.fn.extend.off (http://localhost/static/js/lib/jquery.min.js:3:11499)
  -------------   Elapsed: 814 ms; At: Sat Mar 19 2016 17:04:08 -------------  
    at Object.Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost/static/js/app/angular2.js:1340:24)
    at ZoneDelegate.scheduleTask (http://localhost/static/js/app/angular2.js:348:51)
    at Zone.scheduleEventTask (http://localhost/static/js/app/angular2.js:292:41)
    at zoneAwareAddEventListener (http://localhost/static/js/app/angular2.js:876:12)
    at HTMLDivElement.addEventListener (eval at createNamedFn (http://localhost/static/js/app/angular2.js:969:19), <anonymous>:3:43)
    at Object.n.event.add (http://localhost/static/js/lib/jquery.min.js:3:6064)
    at HTMLDivElement.<anonymous> (http://localhost/static/js/lib/jquery.min.js:3:5282)
    at Function.n.extend.each (http://localhost/static/js/lib/jquery.min.js:2:2773)
  -------------   Elapsed: 5 ms; At: Sat Mar 19 2016 17:04:08 -------------  
    at Object.Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost/static/js/app/angular2.js:1340:24)
    at ZoneDelegate.scheduleTask (http://localhost/static/js/app/angular2.js:348:51)
    at Zone.scheduleMicroTask (http://localhost/static/js/app/angular2.js:286:41)
    at scheduleResolveOrReject (http://localhost/static/js/app/angular2.js:581:16)
    at resolvePromise (http://localhost/static/js/app/angular2.js:545:23)
    at http://localhost/static/js/app/angular2.js:583:19
    at ZoneDelegate.invokeTask (http://localhost/static/js/app/angular2.js:371:39)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://localhost/static/js/app/angular2.js:16908:42)
  -------------   Elapsed: 1 ms; At: Sat Mar 19 2016 17:04:08  -------------  
    at Object.Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost/static/js/app/angular2.js:1340:24)
    at ZoneDelegate.scheduleTask (http://localhost/static/js/app/angular2.js:348:51)
    at Zone.scheduleMicroTask (http://localhost/static/js/app/angular2.js:286:41)
    at scheduleResolveOrReject (http://localhost/static/js/app/angular2.js:581:16)
    at resolvePromise (http://localhost/static/js/app/angular2.js:545:23)
    at http://localhost/static/js/app/angular2.js:583:19
    at ZoneDelegate.invokeTask (http://localhost/static/js/app/angular2.js:371:39)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://localhost/static/js/app/angular2.js:16908:42)
  -------------   Elapsed: 0 ms; At: Sat Mar 19 2016 17:04:08  -------------  
    at Object.Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost/static/js/app/angular2.js:1340:24)
    at ZoneDelegate.scheduleTask (http://localhost/static/js/app/angular2.js:348:51)
    at Zone.scheduleMicroTask (http://localhost/static/js/app/angular2.js:286:41)
    at scheduleResolveOrReject (http://localhost/static/js/app/angular2.js:581:16)
    at resolvePromise (http://localhost/static/js/app/angular2.js:545:23)
    at http://localhost/static/js/app/angular2.js:583:19
    at ZoneDelegate.invokeTask (http://localhost/static/js/app/angular2.js:371:39)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://localhost/static/js/app/angular2.js:16908:42)
  -------------   Elapsed: 1 ms; At: Sat Mar 19 2016 17:04:08  -------------  
    at Object.Zone.longStackTraceZoneSpec.onScheduleTask (http://localhost/static/js/app/angular2.js:1340:24)
    at ZoneDelegate.scheduleTask (http://localhost/static/js/app/angular2.js:348:51)
    at Zone.scheduleMicroTask (http://localhost/static/js/app/angular2.js:286:41)
    at scheduleResolveOrReject (http://localhost/static/js/app/angular2.js:581:16)
    at ZoneAwarePromise.then (http://localhost/static/js/app/angular2.js:656:19)
    at TemplateCompiler.compileHostComponentRuntime (http://localhost/static/js/app/angular2.js:28060:15)
    at RuntimeCompiler_.compileInHost (http://localhost/static/js/app/angular2.js:27957:40)
    at DynamicComponentLoader_.loadNextToLocation (http://localhost/static/js/app/angular2.js:17304:32)
```

  It works fine in beta.9.

* **Please tell us about your environment:**

 - Angular version: 2.0.0-beta.11
 - Browser: Chrome 49.0.2623.87
 - Language: TypeScript 1.8.9

**Comment by mlow991** [comment]
What process is triggering the modal dialog?

**Comment by todoubaba** [comment]
```typescript
this.$modal = $(this.elementRef.nativeElement).find('.modal');

// show
this.$modal.modal('show');

// hide
this.$modal.modal('hide');
```

**Comment by Alberplz** [comment]
Same problem adding(addEventListener) and removing(removeEventListener) events twice in native elements inside dynamic components

**Comment by todoubaba** [comment]
https://github.com/angular/zone.js/pull/284 will fix this.

**Comment by ericmartinezr** [comment]
dup of https://github.com/angular/angular/issues/7666

**Comment by Futourism** [comment]
I applied the workaround but still I get the error "angular2-polyfills.js:142 Uncaught TypeError: Cannot read property 'zone' of undefined"; the error is in the 3rd line of this code out of the polyfills file:
```
var clearNative = utils_1.patchMethod(window, cancelName, function () { return function (self, args) {
	        var task = args[0];
	        task.zone.cancelTask(task);
	    }; });
```

**Comment by todoubaba** [comment]
@Futourism Maybe https://github.com/angular/zone.js/commit/5783663a80926b6154d5c900a3a5645be7bd53bb fixed the undefined error.

**Comment by uNki23** [comment]
@todoubaba Didn't help. Same error like **Futourism** - I'm using Semantic UI dropdown.

**Comment by uNki23** [comment]
any updated on this? :/

**Comment by todoubaba** [comment]
It's fixed in beta.12

**Comment by no-more** [comment]
Hello,

I have the same issue with beta 14 when I'm trying to use forerunnerdb. It's working fine the first time, but not the second time I come to the page.

Here is the full stack trace:
`
?d41d:73 Error: Task does not support cancellation, or is already canceled.
    at ZoneDelegate.cancelTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:219:23)
    at Zone.cancelTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:129:44)
    at eval (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:88:23)
    at clearTimeout (eval at createNamedFn (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0)), <anonymous>:3:39)
    at Events.deferEmit (eval at <anonymous> (http://localhost:3000/main.bundle.js:1:0), <anonymous>:188:5)
    at Collection._insertHandle (eval at <anonymous> (http://localhost:3000/main.bundle.js:1:0), <anonymous>:1609:7)
    at Collection.insert (eval at <anonymous> (http://localhost:3000/main.bundle.js:1:0), <anonymous>:1535:14)
    at TodoList.ngOnInit (eval at <anonymous> (http://localhost:3000/2.chunk.js:1:0), <anonymous>:73:24)
    at AbstractChangeDetector.ChangeDetector_HostTodoList_0.detectChangesInRecordsInternal (viewFactory_HostTodoList:21:99)
    at AbstractChangeDetector.detectChangesInRecords (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:104:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:81:14)
    at AbstractChangeDetector._detectChangesContentChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:174:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:82:14)
    at AbstractChangeDetector._detectChangesInViewChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:181:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:85:14)
    at AbstractChangeDetector._detectChangesContentChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:174:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:82:14)
    at AbstractChangeDetector._detectChangesInViewChildren (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:181:18)
    at AbstractChangeDetector.runDetectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:85:14)
    at AbstractChangeDetector.detectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:70:73)
    at ChangeDetectorRef_.detectChanges (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:21:73)
    at eval (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:387:84)
    at Array.forEach (native)
    at ApplicationRef_.tick (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:387:38)
    at eval (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:304:129)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:172:28)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:44:41)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:171:34)
    at Zone.runGuarded (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:81:47)
    at NgZoneImpl.runInner (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:75:71)
    at NgZone.run (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:220:66)
    at Object.eval (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:304:105)
    at SafeSubscriber.schedulerFn [as _next] (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:122:52)
    at SafeSubscriber.__tryOrUnsub (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:166:16)
    at SafeSubscriber.next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:115:22)
    at Subscriber._next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:74:26)
    at Subscriber.next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:51:18)
    at EventEmitter.Subject._finalNext (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:124:30)
    at EventEmitter.Subject._next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:116:18)
    at EventEmitter.Subject.next (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:73:14)
    at EventEmitter.emit (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:111:76)
    at NgZone._checkStable (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:140:44)
    at NgZoneImpl.NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:116:23)
    at Object.NgZoneImpl.inner.inner.fork.onHasTask (eval at <anonymous> (http://localhost:3000/vendor.bundle.js:1:0), <anonymous>:56:35)
    at ZoneDelegate.hasTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:231:55)
    at ZoneDelegate._updateTaskCount (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:248:26)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:209:26)
    at Zone.runTask (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:103:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:322:35)
    at HTMLAnchorElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:274:21)BrowserDomAdapter.logError @ ?d41d:73ExceptionHandler.call @ ?d41d:66(anonymous function) @ ?d41d:258schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM87216:166SafeSubscriber.next @ VM87216:115Subscriber._next @ VM87216:74Subscriber.next @ VM87216:51Subject._finalNext @ VM87211:124Subject._next @ VM87211:116Subject.next @ VM87211:73EventEmitter.emit @ ?d41d:113NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ?d41d:134NgZoneImpl.inner.inner.fork.onHandleError @ ?d41d:88ZoneDelegate.handleError @ zone.ts?949c:703Zone.runGuarded @ zone.ts?949c:557NgZoneImpl.runInner @ ?d41d:97NgZone.run @ ng_zone.ts?0378:204(anonymous function) @ ?d41d:399schedulerFn @ ?d41d:127SafeSubscriber.__tryOrUnsub @ VM87216:166SafeSubscriber.next @ VM87216:115Subscriber._next @ VM87216:74Subscriber.next @ VM87216:51Subject._finalNext @ VM87211:124Subject._next @ VM87211:116Subject.next @ VM87211:73EventEmitter.emit @ ?d41d:113NgZone._checkStable @ ?d41d:144NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask @ ?d41d:131NgZoneImpl.inner.inner.fork.onHasTask @ ?d41d:78ZoneDelegate.hasTask @ zone.ts?949c:755ZoneDelegate._updateTaskCount @ zone.ts?949c:774ZoneDelegate.invokeTask @ zone.ts?949c:733Zone.runTask @ zone.ts?949c:577drainMicroTaskQueue @ zone.ts?949c:873ZoneTask.invoke @ zone.ts?949c:810`

Thanks a lot.
