### ISSUE TITLE
Problems with JQuery (and external scripts in general?) in beta.11

### ISSUE THREAD

**Issue by skovmand** [angular/angular#7714]
* **I'm submitting a ... **
[X] bug report

* **What is the current behavior?**
After upgrading from angular 2 beta.9 to beta 11, using native Twitter Bootstrap tooltips on my page throws a ```TypeError: Cannot read property 'zone' of null```. 

Also, I have noticed that the live reload functionality of ```lite-server``` has stopped. Perhaps angular 2 beta.11 causes problems for external scripts in general?

Anyway, the Twitter Bootstrap tooltips works fine in beta.9, but after upgrading to beta.11 my custom directive for them crashes with the following console output when I hover the mouse over the element with the tooltip:

```
angular2.js:23730 TypeError: Cannot read property 'zone' of null
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.11/angular2-polyfills.min.js:1:725
    at clearTimeout (eval at d (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.11/angular2-polyfills.min.js:1:13443), <anonymous>:3:39)
    at c.enter (https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js:6:22170)
    at HTMLElement.n.isFunction.f (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js:2:3610)
    at HTMLElement.n.event.special.(anonymous function).handle (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js:3:11029)
    at HTMLElement.n.event.dispatch (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js:3:7516)
    at HTMLElement.r.handle (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js:3:5597)
    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.11/angular2-polyfills.min.js:1:7376)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.11/angular2.js:2208:31)
    at e.invokeTask (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.11/angular2-polyfills.min.js:1:7312)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

It can be reproduced [with this plunkr](http://plnkr.co/edit/gqlggzxcKwm69JHBbufq), which includes my small tooltip directive. It should be the same for native bootstrap elements. 

To reproduce the error: Change all the angular2-scripts in index.html from beta.9 to beta.11 to see the error in the console when hovering the mouse over the button.

* **What is the expected behavior?**

That a tooltip text appears over the button when hovering the mouse over it.

* **What is the motivation / use case for changing the behavior?**

?

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.11
- Browser: [Chrome 49]
- Language: [TypeScript 1.7.3 and 1.8.2]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by zoechi** [comment]
Sounds like #7652

**Comment by dna2github** [comment]
For a quick fix, you can modify one line at Line 142, angular2-polyfills.js, beta.11 (for min version, compress it):
task.zone.cancelTask(task); => if(task) task.zone.cancelTask(task);
(addition: Line 147, agular2-polyfills.js, beta.12)

**Comment by skovmand** [comment]
It is working again in beta.13, I'm not sure when it was fixed.
