### ISSUE TITLE
HostBinding does not work on attribute bindings

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#7833]
When using a directive with a attribute binding, the `HostBinding` on css classes does not work and throws an exception. So take the following:

```
<button long-press></button>
```

with the following code, I'd like to add a css class to the button after long press:

```
import {
  Directive,
  Output,
  EventEmitter,
  HostBinding,
  HostListener
} from 'angular2/core.js';

@Directive({
  selector: '[long-press]'
})
export class LongPressButton {
  
  @Output()
  onLongPress = new EventEmitter();
  
  @Output()
  onLongPressing = new EventEmitter();
  
  @HostBinding('[class.press]') // <== Does not work
  get press() { return this._pressing; }
  
  @HostBinding('[class.longpress]')  // <== Does not work
  get longPress() { return this._longPressing; }
  
  @HostListener('mousedown', ['$event'])
  onMouseDown(event) {
    this._pressing = true;
    this._longPressing = false;
    
    this._timeout = setTimeout(() => {
      this._longPressing = true;
      this.onLongPress.emit(event);
      
      this._interval = setInterval(() => {
        this.onLongPressing.emit(event);
      }, 50);
    }, 300); 
  }
  
  @HostListener('mouseup')
  onMouseUp = () => this.endPress()
  
  @HostListener('mouseleave')
  onMouseLeave = () => this.endPress()
  
  endPress() {
    clearTimeout(this._timeout);
    clearInterval(this._interval);
    
    this._longPressing = false;
    this._pressing = false;
  }
  
}
```

will result in the following exception:

```
angular.js:13294 Error: Failed to execute 'setAttribute' on 'Element': '[[class.longpress]]' is not a valid attribute name.
    at Error (native)
    at BrowserDomAdapter.setAttribute (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-beta.12/src/platform/browser/browser_adapter.js:252:90)
    at DomRenderer.setElementAttribute (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-beta.12/src/platform/dom/dom_renderer.js:178:35)
    at DebugDomRenderer.setElementAttribute (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-beta.12/src/core/debug/debug_renderer.js:101:31)
    at viewFactory_Controls0 (viewFactory_Controls:198:10)
    at viewFactory_Viz0 (viewFactory_Viz:821:1)
    at HostViewFactory.viewFactory_HostViz0 [as viewFactory] (viewFactory_HostViz:106:1)
    at AppViewManager_.createRootHostView (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-beta.12/src/core/linker/view_manager.js:93:36)
    at DowngradeNg2ComponentAdapter.bootstrapNg2 (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-beta.12/src/upgrade/downgrade_ng2_adapter.js:30:45)
    at link.post (http://localhost:8080/jspm_packages/npm/angular2@2.0.0-beta.12/src/upgrade/upgrade_adapter.js:474:28) <graph-viz-page [model]="model" class="ng-scope" id="NG2_UPGRADE_0_graphVizPage_c0">
```

I'm not quite sure if this is on purpose given the context of it being a directive binding on a attribute tag but I think other would expect this to work.

**Comment by ericmartinezr** [comment]
The problem are the `[]`, your code should be

```
@HostBinding('class.press') // No [ ]
```

See https://github.com/angular/angular/issues/7500

**Comment by amcdnl** [comment]
@ericmartinezr Works, thanks for the tip! 

FYI I took this example code from the Material2 Official Project: https://github.com/angular/material2/blob/master/src/components/button/button.ts#L23

**Comment by ericmartinezr** [comment]
@amcdnl you're welcome, read this https://github.com/angular/angular.io/issues/904#issuecomment-190918002, there's explained why with `host : {}` brackets are required and why with `@HostBinding` they're not.

**Comment by adrian-the-git** [comment]
Cheatsheet should be updated to reflect this
