### ISSUE TITLE
ngFor is not creating any elements in Chrome....

### ISSUE THREAD

**Issue by janbaer** [angular/angular#7871]
I have a real strange problem with my Angular2 project but only in Chrome Canary and the normal Chrome on a Mac. Maybe someone has a tip for me. The problem doesn't occur in Safari, Firefox and also not in Chrome under Linux and Windows. Only on the latest version of MacOS.

The problem can be reproduced under www.howcani.eu. It's a project which is written in Angular 2 (not finished). So will the page be shown in Safari.

(https://cloud.githubusercontent.com/assets/528331/14217128/90b65f28-f84c-11e5-919c-5589a98d5585.png)

In Chrome it looks so. In the screenshot you can also see that no content was created by the ngFor directive. In Safari the same code works.

(https://cloud.githubusercontent.com/assets/528331/14217201/eb0ccbec-f84c-11e5-9ff5-9221a744909d.png)

The second problem you can see in the following screenshot.

(https://cloud.githubusercontent.com/assets/528331/14217278/6184b41a-f84d-11e5-9732-da83b79b5ab8.png)

Both fields should have a value which comes from a object in the Component and they are bound with two way binding. In Safari both fields are prefilled, in Chrome I've to click in both fields to see the values.

I've no idea where the problem can be, I also removed the CSS-Framework MaterialCSS which I use in this project, but it's the same problem.. I'm wondering that I've the problem with Chrome and Mac (on two different Macs) and not since I think this combination is also used by the developers from Google. I also just installed a fresh version of Chrome without any extensions but with the same result.

The app will be transpiled by Webpack and Babel and the problem is also in the non minified code.

It would be interesting for me, if any other Mac User have the same problem and if yes, what the problem could be.. Thanks!

**Comment by janbaer** [comment]
What I also found out is, that the ngInit event will be called whenever I destroy the component and thats really strange.

I should mention that I don't use Typescript. I just use ES6 with the some babel plugins. I would understand when it wouldn't run on any browser. But it runs on every browser except the Google Chrome on MacOS. There's also no log output that could give me a hint, what's going wrong... Thanks for help in advance!

In case someone would take a look on the bootstrapping of my project, the source is here: https://github.com/howcani-project/howcani

**Comment by mwawrusch** [comment]
I do have massive ngFor problems since chrome updated a few days ago. In particular I get the following:

```
angular2.js:23877 TypeError: iterator1.next is not a function
    at Object.areIterablesEqual (http://localhost:7600/node_modules/angular2/bundles/angular2.js?1460040514707:1135:29)
    at ChangeDetectionUtil.devModeEqual (http://localhost:7600/node_modules/angular2/bundles/angular2.js?1460040514707:8203:29)
    at Object.areIterablesEqual (http://localhost:7600/node_modules/angular2/bundles/angular2.js?1460040514707:1141:12)
    at Function.ChangeDetectionUtil.devModeEqual (http://localhost:7600/node_modules/angular2/bundles/angular2.js?1460040514707:8203:29)
    at AbstractChangeDetector.ChangeDetector_UsersAccountSelectionComponent_3.detectChangesInRecordsInternal (viewFactory_UsersAccountSelectionComponent:283:51)
    at AbstractChangeDetector.detectChangesInRecords (http://localhost:7600/node_modules/angular2/bundles/angular2.js?1460040514707:9609:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:7600/node_modules/angular2/bundles/angular2.js?1460040514707:9592:12)
    at AbstractChangeDetector._detectChangesContentChildren (http://localhost:7600/node_modules/angular2/bundles/angular2.js?1460040514707:9665:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:7600/node_modules/angular2/bundles/angular2.js?1460040514707:9593:12)
    at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:7600/node_modules/angular2/bundles/angular2.js?1460040514707:9671:14)BrowserDomAdapter.logError @ angular2.js:23877ExceptionHandler.call @ angular2.js:1330(anonymous function) @ angular2.js:12763schedulerFn @ angular2.js:13167SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244NgZoneImpl.runInner @ angular2.js:2140NgZone.run @ angular2.js:13649(anonymous function) @ angular2.js:12862schedulerFn @ angular2.js:13167SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.js:13148NgZone._checkStable @ angular2.js:13589NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask @ angular2.js:13560NgZoneImpl.inner.inner.fork.onHasTask @ angular2.js:2120ZoneDelegate.hasTask @ angular2-polyfills.js:391ZoneDelegate._updateTaskCount @ angular2-polyfills.js:408ZoneDelegate.invokeTask @ angular2-polyfills.js:369Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434nrWrapper @ :4
angular2.js:23877 ERROR CONTEXT:BrowserDomAdapter.logError @ angular2.js:23877ExceptionHandler.call @ angular2.js:1333(anonymous function) @ angular2.js:12763schedulerFn @ angular2.js:13167SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244NgZoneImpl.runInner @ angular2.js:2140NgZone.run @ angular2.js:13649(anonymous function) @ angular2.js:12862schedulerFn @ angular2.js:13167SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.js:13148NgZone._checkStable @ angular2.js:13589NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask @ angular2.js:13560NgZoneImpl.inner.inner.fork.onHasTask @ angular2.js:2120ZoneDelegate.hasTask @ angular2-polyfills.js:391ZoneDelegate._updateTaskCount @ angular2-polyfills.js:408ZoneDelegate.invokeTask @ angular2-polyfills.js:369Zone.runTask @ angular2-polyfills.js:263drainMicroTaskQueue @ angular2-polyfills.js:482ZoneTask.invoke @ angular2-polyfills.js:434nrWrapper @ :4
```

which effs up the angular app. Works on safari

**Comment by pkozlowski-opensource** [comment]
@janbaer @mwawrusch hard to progress on this one without a minimal reproduction scenario in a plunker....

**Comment by janbaer** [comment]
I think the problem in my case is not with ngFor. It's that in the environment I described, some events (like ngOnInit) will not be fired in the expected moment. It's reproducable in a the deployed version on www.howcani.eu. And the code is in github. To rebuild the whole environment in plunkr is a bit too much effort. To reproduce it, just clone the project, npm i and gulp serve. And then you can reproduce it in under a minute...

**Comment by janbaer** [comment]
I just closed the issue since in the meantime I found out that the problem has nothing todo with **ngFor**. It's a problem with the router, since it only occurs with components that are shown within the **router-outlet** element. Will create an separate issue for that...

**Comment by luvcreative** [comment]
Hey @janbaer where is the new issue? I think I'm having the same issue with chrome and iterator1.next. Did you find a solution?

**Comment by ogsmelvin05** [comment]
ORIGINAL EXCEPTION: TypeError: iterator1.next is not a function
  ORIGINAL STACKTRACE:
  TypeError: iterator1.next is not a function
    at Object.areIterablesEqual (http://2e11074c.ngrok.io/assets/js/app.js:2127:32)
    at devModeEqual (http://2e11074c.ngrok.io/assets/js/app.js:8277:30)
    at Object.areIterablesEqual (http://2e11074c.ngrok.io/assets/js/app.js:2133:15)
    at Object.devModeEqual (http://2e11074c.ngrok.io/assets/js/app.js:8277:30)
    at checkBinding (http://2e11074c.ngrok.io/assets/js/app.js:11194:34)
    at AppView._View_AppComponent0.detectChangesInternal (AppComponent.template.js:60:7)
    at AppView.detectChanges (http://2e11074c.ngrok.io/assets/js/app.js:26842:23)
    at AppView.detectViewChildrenChanges (http://2e11074c.ngrok.io/assets/js/app.js:26871:35)
    at AppView.detectChangesInternal (http://2e11074c.ngrok.io/assets/js/app.js:26862:15)
    at AppView.detectChanges (http://2e11074c.ngrok.io/assets/js/app.js:26842:23)

Hi, also encountering the issue but happens intermittently. this code using webpack

**Comment by zoechi** [comment]
This issue is closed and you didn't provide a repo case. I wouldn't expect anything to happen because of your comment.

**Comment by ivangabriele** [comment]
+1

I have the same issue. No problem on Edge. Only in Chrome and Firefox. I tried to use the deprecated `#` instead of `let`, in vain.

And it looks like somebody else got also this problem :

* http://stackoverflow.com/questions/37472155/error-using-ngfor-with-object-array-in-angular-2

**Comment by janbaer** [comment]
@luvcreative In my case it was a problem with the order of the registration of the polyfills and it had nothing todo with the ngFor directive. Therefore I closed this issue here.
