### ISSUE TITLE
Component router not working with downgraded angular 2 component in hybrid app

### ISSUE THREAD

**Issue by robianmcd** [angular/angular#7960]
**Steps to reproduce and a minimal demo of the problem**

I'm trying to create a hybrid Angular 1/2 app for demonstrating how to migrate from Angular 1 to 2. I figured the easiest way to migrate from 1 to 2 would be to use the component router in Angular 1 but I'm having trouble getting it working in a hybrid app.

I created a simple app here that demonstrates the problem: https://github.com/robianmcd/angular-migration/tree/hybrid
There is a running instance of it here: http://robianmcd.github.io/angular-migration/

I have an angular 2 component that I am trying to downgrade and use as a route in angular 1's component router

```
angular.module('imageShare', ['ngComponentRouter'])
    .value('$routerRootComponent', 'app')
    .component('app', {
        template: '<ng-outlet></ng-outlet>',
        $routeConfig: [
            {path: '/home', name: 'ImageList', component: 'imageList', useAsDefault: true}
        ]
    })
    .directive('imageList', <ng.IDirectiveFactory>adapter.downgradeNg2Component(ImageList))
```

**Current behavior**
When the page loads it logs the following error:
```
TypeError: Cannot read property '$routerOnActivate' of undefined
    at link (http://robianmcd.github.io/angular-migration/node_modules/@angular/router/angular1/angular_1_router.js:190:33)
    at invokeLinkFn (http://robianmcd.github.io/angular-migration/node_modules/angular/angular.js:9623:9)
    at nodeLinkFn (http://robianmcd.github.io/angular-migration/node_modules/angular/angular.js:9022:11)
    at compositeLinkFn (http://robianmcd.github.io/angular-migration/node_modules/angular/angular.js:8333:13)
    at publicLinkFn (http://robianmcd.github.io/angular-migration/node_modules/angular/angular.js:8213:30)
    at link (http://robianmcd.github.io/angular-migration/node_modules/@angular/router/angular1/angular_1_router.js:177:41)
    at invokeLinkFn (http://robianmcd.github.io/angular-migration/node_modules/angular/angular.js:9623:9)
    at nodeLinkFn (http://robianmcd.github.io/angular-migration/node_modules/angular/angular.js:9022:11)
    at compositeLinkFn (http://robianmcd.github.io/angular-migration/node_modules/angular/angular.js:8333:13)
    at publicLinkFn (http://robianmcd.github.io/angular-migration/node_modules/angular/angular.js:8213:30) <image-list $router="::$$router" class="ng-scope">
```

It looks like the source code for the angular 1 component router is trying to get the controller for the active component by running something like `element.data('$imageListController')` which returns `undefined`. If I take a look at the `data` of a downgraded component's element it only has a scope field. e.g. if I inspect the element in chrome and run `angular.element($0).data()` I get back `{$scope: Scope}`

**Comment by Sodman** [comment]
I too am seeing similar behavior in my app while trying to set up the new component router. My app looks very similar to robianmcd's.

**Comment by solojavier** [comment]
I added this change and it worked:

```
if (currentComponent && currentComponent.$routerOnActivate) {
```

But not sure if that is the correct thing to do...

**Comment by TSilviu** [comment]
Having the same issue. Any other thoughts on this?

**Comment by vsavkin** [comment]
Could you provide a plunkr reproducing the issue?

**Comment by vsavkin** [comment]
Closing it. Please reopen the issue with the plunkr reproducing it.
