### ISSUE TITLE
angular2 attributes break templateUrl

### ISSUE THREAD

**Issue by cescoferraro** [angular/angular#8001]
#2779 solution does not work  btw

### Versions

```
  "dependencies": {
    "angular2": "2.0.0-beta.14",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "system-text": "^0.1.0",
    "systemjs": "0.19.25",
    "zone.js": "0.6.6"
  }
```

### Working code:
```
@Component({
	encapsulation: ViewEncapsulation.Native,
	selector: 'login',
	template: ` 
  <form [ngFormModel]="myform" (ngSubmit)="onSubmit(myform.value)" method="post">
   ....
  </form>`,
	directives: [
		RouterLink,
		MdButton,
		MdInput
	],
	providers: [LoginService, FormBuilder],
	styleUrls: ['css/login.css']
})


export class LoginComponent {

	myform:ControlGroup;
	status:string;
	reason:string;

	onSubmit() {
		//noinspection TypeScriptUnresolvedVariable
		this._loginService.goPOST(this.myform.value).subscribe(
			##UNRELATED STUFF
                );
	}

	constructor(private _loginService:LoginService, private _formBuilder:FormBuilder, private router:Router) {
	}


	ngOnInit():any {
		this.myform = this._formBuilder.group({
			'email': ['francescoaferraro@gmail.com', Validators.required],
			'password': ['1234567', Validators.required]
		});
	}
}
```

### Error code( Using templateurl served via golang backend)

```
@Component({
	encapsulation: ViewEncapsulation.Native,
	selector: 'login',
	templateUrl: 'ts/login/login.html',
	directives: [
		RouterLink,
		MdButton,
		MdInput
	],
	providers: [LoginService, FormBuilder, FORM_DIRECTIVES],
	styleUrls: ['css/login.css']
})
```

### Console Output

```

Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
angular2.dev.js:23951 EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'ngformmodel' since it isn't a known native property ("<form [ERROR ->][ngformmodel]="myform" (ngsubmit)="onSubmit(myform.value)" method="post"><div><md-input [ngformcontro"): LoginComponent@0:6
angular2.dev.js:23941 EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'ngformmodel' since it isn't a known native property ("<form [ERROR ->][ngformmodel]="myform" (ngsubmit)="onSubmit(myform.value)" method="post"><div><md-input [ngformcontro"): LoginComponent@0:6BrowserDomAdapter.logError @ angular2.dev.js:23941BrowserDomAdapter.logGroup @ angular2.dev.js:23952ExceptionHandler.call @ angular2.dev.js:1317(anonymous function) @ angular2.dev.js:12763schedulerFn @ angular2.dev.js:13167SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.dev.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244drainMicroTaskQueue @ angular2-polyfills.js:495ZoneTask.invoke @ angular2-polyfills.js:434
angular2.dev.js:23941 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1319(anonymous function) @ angular2.dev.js:12763schedulerFn @ angular2.dev.js:13167SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.dev.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244drainMicroTaskQueue @ angular2-polyfills.js:495ZoneTask.invoke @ angular2-polyfills.js:434
angular2.dev.js:23941 Error: Uncaught (in promise): Template parse errors:
Can't bind to 'ngformmodel' since it isn't a known native property ("<form [ERROR ->][ngformmodel]="myform" (ngsubmit)="onSubmit(myform.value)" method="post"><div><md-input [ngformcontro"): LoginComponent@0:6
    at resolvePromise (angular2-polyfills.js:543)
    at angular2-polyfills.js:520
    at ZoneDelegate.invoke (angular2-polyfills.js:332)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (angular2.dev.js:2111)
    at ZoneDelegate.invoke (angular2-polyfills.js:331)
    at Zone.run (angular2-polyfills.js:227)
    at angular2-polyfills.js:576
    at ZoneDelegate.invokeTask (angular2-polyfills.js:365)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (angular2.dev.js:2103)
    at ZoneDelegate.invokeTask (angular2-polyfills.js:364)BrowserDomAdapter.logError @ angular2.dev.js:23941ExceptionHandler.call @ angular2.dev.js:1320(anonymous function) @ angular2.dev.js:12763schedulerFn @ angular2.dev.js:13167SafeSubscriber.__tryOrUnsub @ Rx.js:10775SafeSubscriber.next @ Rx.js:10730Subscriber._next @ Rx.js:10690Subscriber.next @ Rx.js:10667Subject._finalNext @ Rx.js:11191Subject._next @ Rx.js:11183Subject.next @ Rx.js:11142EventEmitter.emit @ angular2.dev.js:13148NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ angular2.dev.js:13566NgZoneImpl.inner.inner.fork.onHandleError @ angular2.dev.js:2128ZoneDelegate.handleError @ angular2-polyfills.js:336Zone.runGuarded @ angular2-polyfills.js:244drainMicroTaskQueue @ angular2-polyfills.js:495ZoneTask.invoke @ angular2-polyfills.js:434
angular2-polyfills.js:469 Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngformmodel' since it isn't a known native property ("<form [ERROR ->][ngformmodel]="myform" (ngsubmit)="onSubmit(myform.value)" method="post"><div><md-input [ngformcontro"): LoginComponent@0:6 ; Zone: angular ; Task: Promise.then ; Value: BaseException {message: "Template parse errors:↵Can't bind to 'ngformmodel'…div><md-input [ngformcontro"): LoginComponent@0:6", stack: "Error: Template parse errors:↵Can't bind to 'ngfor…alhost:9000/node_modules/angular2.dev.js:2103:31)"}message: "Template parse errors:↵Can't bind to 'ngformmodel' since it isn't a known native property ("<form [ERROR ->][ngformmodel]="myform" (ngsubmit)="onSubmit(myform.value)" method="post"><div><md-input [ngformcontro"): LoginComponent@0:6"stack: "Error: Template parse errors:↵Can't bind to 'ngformmodel' since it isn't a known native property ("<form [ERROR ->][ngformmodel]="myform" (ngsubmit)="onSubmit(myform.value)" method="post"><div><md-input [ngformcontro"): LoginComponent@0:6↵    at new BaseException (http://localhost:9000/node_modules/angular2.dev.js:7521:21)↵    at TemplateParser.parse (http://localhost:9000/node_modules/angular2.dev.js:24479:15)↵    at http://localhost:9000/node_modules/angular2.dev.js:25192:54↵    at ZoneDelegate.invoke (http://localhost:9000/node_modules/angular2-polyfills.js:332:29)↵    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:9000/node_modules/angular2.dev.js:2111:31)↵    at ZoneDelegate.invoke (http://localhost:9000/node_modules/angular2-polyfills.js:331:35)↵    at Zone.run (http://localhost:9000/node_modules/angular2-polyfills.js:227:44)↵    at http://localhost:9000/node_modules/angular2-polyfills.js:576:58↵    at ZoneDelegate.invokeTask (http://localhost:9000/node_modules/angular2-polyfills.js:365:38)↵    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://localhost:9000/node_modules/angular2.dev.js:2103:31)"__proto__: ErrorconsoleError @ angular2-polyfills.js:469drainMicroTaskQueue @ angular2-polyfills.js:498ZoneTask.invoke @ angular2-polyfills.js:434
angular2-polyfills.js:471 Error: Uncaught (in promise): Template parse errors:(…)consoleError @ angular2-polyfills.js:471drainMicroTaskQueue @ angular2-polyfills.js:498ZoneTask.invoke @ angular2-polyfills.js:434


```

**Comment by frederikschubert** [comment]
It seems that in the template you are loading via templateUrl there is a typo. ngformmodel -> ngFormModel

**Comment by CaptainCodeman** [comment]
Lots of tools lowercase attributes as they are considered to be case-insensitive.

**Comment by cescoferraro** [comment]
Thanks @frederikschubert. Gulp somewhy is lowercasing that.
Works without minification. 
maybe its gulp-htmlmin issue or I am missing some options.

```
gulp.task('html:compile', function() {
	return gulp.src('**/*.html' ,{cwd: conf.paths.Html})
		.pipe(htmlmin({collapseWhitespace: true}))
		.pipe(gulp.dest(conf.paths.htmlOutputPath))
});

```

**Comment by ericmartinezr** [comment]
@cescoferraro gulp-htmlmin points to https://github.com/kangax/html-minifier and the table with the [options](https://github.com/kangax/html-minifier#options-quick-reference) there's one called `caseSensitive` you could try setting that one to true.

**Comment by cescoferraro** [comment]
great @ericmartinezr it works
