### ISSUE TITLE
Dart DirectiveProcessor warning and error

### ISSUE THREAD

**Issue by frankpepermans** [angular/angular#8019]
I'm using the tuple library from pub, when I do pub serve, the following stack trace is generated:
The source code of the tuple class can be found here:
https://github.com/kseo/tuple/blob/master/lib/src/tuple.dart

(this is with Angular 2 beta 13.1 and Dart)

```
[Warning from DirectiveProcessor on taurus_main|packages/tuple/tuple.dart with input tuple|lib/src/tuple.dart]:
line 27, column 1 of tuple.dart: Failed while reading part at 'package:tuple/src/tuple.dart'. Ignoring.
Error: Invalid argument(s): Illegal character in path
Stack Trace: #0      Uri._checkWindowsPathReservedCharacters (dart:core/uri.dart:855)
#1      Uri._makeWindowsFileUrl (dart:core/uri.dart:956)
#2      Uri.Uri.file (dart:core/uri.dart:738)
#3      StringSource.StringSource (package:analyzer/src/string_source.dart:30:45)
#4      parseDirectives (package:analyzer/analyzer.dart:80:20)
#5      _getAllDeclarations.<anonymous closure>.<anonymous closure> (package:angular2/src/transform/directive_processor/inliner.dart:68:30)
#6      _rootRunUnary (dart:async/zone.dart:902)
#7      _CustomZone.runUnary (dart:async/zone.dart:798)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#10     _Future._completeWithValue (dart:async/future_impl.dart:424)
#11     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#12     _rootRun (dart:async/zone.dart:895)
#13     _CustomZone.run (dart:async/zone.dart:790)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:723)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

part 'package:tuple/src/tuple.dart';
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[DirectiveProcessor]:
  Failed with 2 errors
Error 1: line 27, column 1 of packages\tuple\tuple.dart and parts: Expected a method, getter, setter or operator declaration
null
^^^^
Error 2: line 27, column 1 of packages\tuple\tuple.dart and parts: Unexpected token 'null'
null
^^^^
Build error:
Transform DirectiveProcessor on taurus_main|packages/tuple/tuple.dart threw error: Error in packages/tuple/tuple.dart and parts: Expected a method, getter, setter or operator declaration

Error in packages/tuple/tuple.dart and parts: Unexpected token 'null'

package:analyzer/analyzer.dart 110:52                                  _parseSource
package:analyzer/analyzer.dart 39:10                                   parseCompilationUnit
package:angular2/src/transform/directive_processor/rewriter.dart 31:7  createNgMeta.<async>
dart:async-patch/async_patch.dart 27                                   _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 902                                               _rootRunUnary
dart:async/zone.dart 798                                               _CustomZone.runUnary
dart:async/future_impl.dart 551                                        _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 637                                        _Future._propagateToListeners
dart:async/future_impl.dart 414                                        _Future._complete
dart:async/future_impl.dart 52                                         _SyncCompleter.complete
package:angular2/src/transform/common/logging.dart 26:3                logElapsedAsync.<async>
dart:async-patch/async_patch.dart 27                                   _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 902                                               _rootRunUnary
dart:async/zone.dart 798                                               _CustomZone.runUnary
dart:async/future_impl.dart 551                                        _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 637                                        _Future._propagateToListeners
dart:async/future_impl.dart 424                                        _Future._completeWithValue
dart:async/future.dart 299                                             Future.wait.<fn>
dart:async/zone.dart 902                                               _rootRunUnary
dart:async/zone.dart 798                                               _CustomZone.runUnary
dart:async/future_impl.dart 551                                        _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 637                                        _Future._propagateToListeners
dart:async/future_impl.dart 424                                        _Future._completeWithValue
dart:async/future_impl.dart 479                                        _Future._asyncComplete.<fn>
dart:async/zone.dart 895                                               _rootRun
dart:async/zone.dart 790                                               _CustomZone.run
dart:async/zone.dart 723                                               _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41                                  _microtaskLoop
dart:async/schedule_microtask.dart 50                                  _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                               _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                              _RawReceivePortImpl._handleMessage

package:analyzer/analyzer.dart 110:52                                  _parseSource
package:analyzer/analyzer.dart 39:10                                   parseCompilationUnit
package:angular2/src/transform/directive_processor/rewriter.dart 31:7  createNgMeta.<async>
dart:async                                                             _SyncCompleter.complete
package:angular2/src/transform/common/logging.dart 26:3                logElapsedAsync.<async>
```

**Comment by zoechi** [comment]
I found #5587 which seems related. I'm not sure how to interpret the discussion though. I got the impression the transformer chokes on libraries where the `part` and `part of` files are not in the same directory.

**Comment by pkozlowski-opensource** [comment]
Obsolete.
