### ISSUE TITLE
Trying to load everything from cdn and getting various errors

### ISSUE THREAD

**Issue by vineetshopo** [angular/angular#8062]
I tried to load everything from CDN and I am getting errors of various kinds:

My index.html looks like this:

<!doctype html>
<html lang="en">
<head>
    <title>Angular 2 Boilerplate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    

    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.0/es6-shim.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.26/system-polyfills.js"></script>

    <script src="node_modules/angular2/es6/dev/src/testing/shims_for_IE.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2-polyfills.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.26/system.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/Rx.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/router.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/http.min.js"></script>

    <link rel="stylesheet" href="src/css/app.css">

</head>
<base href="/">
<body>
<my-app>Loading...</my-app>

<script>
    System.config({
        packages: {
            app: {
                format: 'register',
                defaultExtension: 'js'
            }
        }
    });
    System.import('app/boot')
            .then(null, console.error.bind(console));
</script>
</body>
</html>

I am getting various kinds of errors from this which are written in RED. Only one is written in Black, that is:

EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error during instantiation of t!.
ORIGINAL EXCEPTION: Primary outlet is already registered.
ORIGINAL STACKTRACE:
Error: Primary outlet is already registered.
    at new t (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2.min.js:5:22658)
    at e.t.registerPrimaryOutlet (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/router.min.js:3:2864)
    at new t (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/router.min.js:2:14643)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2.min.js:1:21641
    at e._instantiate (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2.min.js:9:3204)
    at e._instantiateProvider (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2.min.js:9:1927)
    at e._new (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2.min.js:9:1656)
    at e.instantiateProvider (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2.min.js:8:29085)
    at e.init (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2.min.js:6:25102)
    at new e (https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.15/angular2.min.js:6:18000)
ERROR CONTEXT:
[object Object]

What would be the best approach to use CDN while developing an angular2 app.

**Comment by brandonroberts** [comment]
See #6380. Minified bundles are currently broken, but will be fixed soon. Use the dev bundles instead of the minified bundles.

**Comment by vineetshopo** [comment]
Thanks :)
