### ISSUE TITLE
[TESTING] XHR error while writing unit tests for Components

### ISSUE THREAD

**Issue by abhinavmsra** [angular/angular#8084]
I have following component:

``` typescript
///<reference path="../../node_modules/angular2/typings/browser.d.ts"/>

import { Component, OnInit } from 'angular2/core';
import { ROUTER_DIRECTIVES } from 'angular2/router';

import { Employee } from '../models/employee';
import { EmployeeListServiceComponent } from '../services/employee-list-service.component';

@Component({
  selector: 'employee-list',
  templateUrl: 'src/pages/employee-list.component.html',
  directives: [ROUTER_DIRECTIVES],
  providers: [EmployeeListServiceComponent]
})

export class EmployeeListComponent implements OnInit {
  public employees: Employee[];
  public errorMessage: string;

  constructor(
    private _listingService: EmployeeListServiceComponent
  ){}

  ngOnInit() {
    this._listingService.getEmployees().subscribe(
                     employees => this.employees = employees,
                     error =>  this.errorMessage = <any>error
                   );
  }
}

```

Now I want to test it. So I did the following:

``` typescript
/// <reference path="../../typings/main/ambient/jasmine/jasmine.d.ts" />

import {
    it,
    describe,
    expect,
    TestComponentBuilder,
    injectAsync,
    setBaseTestProviders,
    beforeEachProviders
} from "angular2/testing";
import { provide } from "angular2/core";
import {
    TEST_BROWSER_PLATFORM_PROVIDERS,
    TEST_BROWSER_APPLICATION_PROVIDERS
} from "angular2/platform/testing/browser";
import {
    HTTP_PROVIDERS,
    XHRBackend,
    ResponseOptions,
    Response
} from "angular2/http";
import {
    MockBackend,
    MockConnection
} from "angular2/src/http/backends/mock_backend";
import { ROUTER_PROVIDERS } from 'angular2/router';
import 'rxjs/Rx';

import { EmployeeListComponent } from './list.component';
import { EmployeeListServiceComponent } from '../services/employee-list-service.component';


describe('MyList Tests', () => {
    setBaseTestProviders(TEST_BROWSER_PLATFORM_PROVIDERS, TEST_BROWSER_APPLICATION_PROVIDERS);

    beforeEachProviders(() => {
        return [
            HTTP_PROVIDERS,
            provide(XHRBackend, {useClass: MockBackend}),
            EmployeeListServiceComponent
        ]
    });

    it('Should create a component MyList',
        injectAsync([XHRBackend, EmployeeListServiceComponent, TestComponentBuilder], (backend, service, tcb) => {
            backend.connections.subscribe(
                (connection:MockConnection) => {
                    var options = new ResponseOptions({
                        body: [
                            {
                                "name": "Abhinav Mishra",
                                "id": 1
                            },
                            {
                                "name": "Abhinav Mishra",
                                "id": 2
                            }
                        ]
                    });

                    var response = new Response(options);

                    connection.mockRespond(response);
                }
            );

            return tcb
                .overrideProviders(EmployeeListComponent,
                                [
                                    ROUTER_PROVIDERS,
                                    EmployeeListServiceComponent
                                ]
                            )
                .createAsync(EmployeeListComponent)
                .then((fixture) => {
                    fixture.detectChanges();
                    expect(true).toBe(true);
                });
        })
    );
});

```

However I keep getting the routing error:

```
Chrome 49.0.2623 (Linux 0.0.0) ERROR
  Error: XHR error (404 Not Found) loading http://localhost:9876/angular2/router
      at error (/home/abhi/Desktop/angular2-testing/node_modules/systemjs/dist/system.src.js:1026:16)
      at XMLHttpRequest.xhr.onreadystatechange (/home/abhi/Desktop/angular2-testing/node_modules/systemjs/dist/system.src.js:1047:13)
      at XMLHttpRequest.wrapFn [as _onreadystatechange] (/home/abhi/Desktop/angular2-testing/node_modules/angular2/bundles/angular2-polyfills.js:771:30)
      at ZoneDelegate.invokeTask (/home/abhi/Desktop/angular2-testing/node_modules/angular2/bundles/angular2-polyfills.js:365:38)
      at Zone.runTask (/home/abhi/Desktop/angular2-testing/node_modules/angular2/bundles/angular2-polyfills.js:263:48)
      at XMLHttpRequest.ZoneTask.invoke (/home/abhi/Desktop/angular2-testing/node_modules/angular2/bundles/angular2-polyfills.js:431:34)
```

Where have I messed up?

**Comment by zoechi** [comment]
Can you try inline template instead of `templateUrl: 'src/pages/employee-list.component.html',` There was an issue, I don't know if it is fixed already.

**Comment by abhinavmsra** [comment]
@zoechi still getting the same error. Reading the error its some kind of routing error. Dont expect to result from a template issue.

**Comment by zoechi** [comment]
Did you include `<script src="https://code.angularjs.org/2.0.0-beta.15/router.dev.js"></script>` in HTML?

**Comment by abhinavmsra** [comment]
I am using Karma as a test runner. The app is running fine. Anyway here's how my `.html` looks like:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="/" />
    <meta charset="UTF-8">
    <title>Angular 2 Testing</title>

    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">

    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <script>
        System.config({
            defaultJSExtensions: true
        });
    </script>

    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
    <script src="node_modules/angular2/bundles/router.dev.js"></script>
    <script src="node_modules/angular2/bundles/http.dev.js"></script>

    <script>
        System.import('dist/main').catch(console.log.bind(console));
    </script>

</head>
<body>

<my-app></my-app>

</body>
</html>


```

**Comment by wardbell** [comment]
The `beta-15` testing framework did not support any XHR requests during component instantiation as I recall. Is there some reason you're not on RC1?

Still some problems with that, btw, but better.

**Comment by DzmitryShylovich** [comment]
is this still an issue after final?
