### ISSUE TITLE
Uncaught (in promise): No provider for t! (t -> t)

### ISSUE THREAD

**Issue by vaudy** [angular/angular#8171]
Using angular min I got this issue while loading the app but not with the unminify version.

**Comment by ericmartinezr** [comment]
minification has been broken since beta.1. It has been fixed in latest master though. See https://github.com/angular/angular/issues/6380

**Comment by vaudy** [comment]
heres the stack I got

EXCEPTION: Error: Uncaught (in promise): No provider for t! (t -> t)
STACKTRACE:
Error: Uncaught (in promise): No provider for t! (t -> t)
at l (http://.../vendor/angular2/bundles/angular2-polyfills.min.js:1:3479)
at http://.../vendor/angular2/bundles/angular2-polyfills.min.js:1:3229
at e.invoke (http://.../vendor/angular2/bundles/angular2-polyfills.min.js:1:7701)
at Object.inner.inner.fork.onInvoke (http://.../vendor/angular2/bundles/angular2.min.js:2:3528)
at e.invoke (http://.../vendor/angular2/bundles/angular2-polyfills.min.js:1:7652)
at e.run (http://.../vendor/angular2/bundles/angular2-polyfills.min.js:1:5088)
at http://.../vendor/angular2/bundles/angular2-polyfills.min.js:1:3822
at e.invokeTask (http://.../vendor/angular2/bundles/angular2-polyfills.min.js:1:8332)
at Object.inner.inner.fork.onInvokeTask (http://.../vendor/angular2/bundles/angular2.min.js:2:3428)
at e.invokeTask (http://.../vendor/angular2/bundles/angular2-polyfills.min.js:1:8268)

**Comment by vaudy** [comment]
@ericmartinezr well not a fan of using master has a thirdparty :/

**Comment by ericmartinezr** [comment]
@vaudy ? I didn't get that last. My point is that with the next release all these minification issues should go awat. Meanwhile don't use minified bundles, and see the issue I referenced, you'll find useful workarounds.

**Comment by vaudy** [comment]
@ericmartinezr you mean beta 16 will contain fixed minified bundles?

**Comment by ericmartinezr** [comment]
@vaudy hopefully

**Comment by pkozlowski-opensource** [comment]
Guess it is fixed now.
