### ISSUE TITLE
styleUrls can't handle a CSS file with block comments which include back tick characters

### ISSUE THREAD

**Issue by nosachamos** [angular/angular#8213]
Whenever CSS files include block comments with a back tick character on them, the compiler is thrown off and the generated component code ends up invalid. 

The problematic comment in my css was:

```
/*Additional properties for button version
 iOS requires the button element instead of an anchor tag.
 If you want the anchor version, it requires `href="#"`.*/
```

When the content of the referenced `styleUrls` file is embedded into the compiled component js file, the CSS is split wherever a back tick character appeared in the original file.

For example, my component annotation looked like this:
```
@Component({
  selector: 'toast-container',
  styleUrls: ['./components/toast-container/toast-container.styles.css'],
  templateUrl: './components/toast-container/toast-container.template.html'
})
```

The compiled component ended up with multiple items in the `styles` array [note that I use (...) twice to skip irrelevant sections of CSS, for brevity purposes]:

```
    ToastContainer = __decorate([
        core_1.Component({
            selector: 'toast-container',
            styles: ["\n    .toast-title {\n      font-weight: bold; } (...) "], _a.raw = [".*/\n    button.toast-close-button {\n      padding: 0; width: 25em; } }\n  (...)  "], ("#")(_a))],,
            template: "\n    <div id=\"toast-container\" [style.position]=\"position\" class=\"{{positionClass}}\">\n      <div *ngFor=\"#toast of toasts\" class=\"toast-{{toast.type}}\" (click)=\"dismiss(toast)\">\n        <div *ngIf=\"toast.title\" class=\"{{titleClass}}\">{{toast.title}}</div>\n        <div class=\"{{messageClass}}\">{{toast.message}}</div>\n      </div>\n    </div>\n  "
        }),
        __param(0, core_1.Optional()),
        __param(0, core_1.Inject(toast_service_options_1.ToastOptions)), 
        __metadata('design:paramtypes', [Object])
    ], ToastContainer);
```

Which caused the app to fail to start with the error:

```
signup:71 Error: TypeError: "#" is not a function
	    at eval (http://localhost:5555/components/toast-container/toast-container.component.js:67:14227)
	    at Object.eval (http://localhost:5555/components/toast-container/toast-container.component.js:76:3)
	    at eval (http://localhost:5555/components/toast-container/toast-container.component.js:80:4)
	    at Object.eval (http://localhost:5555/services/toast.service.js:14:35)
	Evaluating http://localhost:5555/components/toast-container/toast-container.component.js
	Evaluating http://localhost:5555/services/toast.service.js
	Evaluating http://localhost:5555/services/http-extended.service.js
	Evaluating http://localhost:5555/bootstrap.js
	Error loading http://localhost:5555/bootstrap.js
```

Instead, the expected behavior was to have all comments stripped off before the content was embedded into the component, back ticks included. But as you can see above, the `styles` array ended up having three items instead of just one.

I created a plunker, but for some reason this can't be reproed there. Anyways, here it is:
http://plnkr.co/edit/ozj2TkCIDYSxNeGL7DYN?p=preview

When I run this on my local environment, the `styleUrls` and `templateUrl` have been converted to `styles` and `template`, and I can see the issue. On plunker, the component does not have these expanded. So you don't get the issue:

```
ToastContainer = __decorate([
                    core_1.Component({
                        selector: 'toast-container',
                        styleUrls: ['./app/toast-container.styles.css'],
                        templateUrl: './app/toast-container.template.html'
                    }),
                    __param(0, core_1.Optional()),
                    __param(0, core_1.Inject(toast_service_options_1.ToastOptions)), 
                    __metadata('design:paramtypes', [Object])
                ], ToastContainer);
```

I reproed this on Beta 13 and 15.

My env looks like this:

```
  "dependencies": {
    "@ngrx/store": "^1.3.3",
    "angular2": "2.0.0-beta.13",
    "es6-module-loader": "^0.17.8",
    "es6-promise": "^3.1.2",
    "es6-shim": "0.35.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.3",
    "store-saga": "^1.0.0-beta.6",
    "systemjs": "~0.19.18",
    "zone.js": "^0.6.6"
  }
```

**Comment by vicb** [comment]
Might be an error generated by one of your build tools, what do you use ?

**Comment by vicb** [comment]
closing as can not reproduce.
