### ISSUE TITLE
Custom pipes not found when using TestComponentBuilder.overrideTemplate()

### ISSUE THREAD

**Issue by michaelbromley** [angular/angular#8306]
* Testing a component which uses a custom pipe.
* The component under test (and the pipe it makes use of) works fine when not using an overridden template.
* When using [overrideTemplate()](https://angular.io/docs/ts/latest/api/testing/TestComponentBuilder-class.html#!#overrideTemplate-anchor), even with the *exact same* template markup, the following error is thrown:

```
Error: Template parse errors:
The pipe 'myPipe' could not be found ("[ERROR ->]{{ 'hello' | myPipe }}"): MyComponent@0:0
    at new BaseException (https://code.angularjs.org/2.0.0-beta.15/angular2.js:7587:21)
    at TemplateParser.parse (https://code.angularjs.org/2.0.0-beta.15/angular2.js:24799:15)
    at https://code.angularjs.org/2.0.0-beta.15/angular2.js:25527:54
    at ZoneDelegate.invoke (https://code.angularjs.org/2.0.0-beta.15/angular2-polyfills.js:390:29)
    at Zone.run (https://code.angularjs.org/2.0.0-beta.15/angular2-polyfills.js:283:44)
    at https://code.angularjs.org/2.0.0-beta.15/angular2-polyfills.js:635:58
    at ZoneDelegate.invokeTask (https://code.angularjs.org/2.0.0-beta.15/angular2-polyfills.js:423:38)
    at Zone.runTask (https://code.angularjs.org/2.0.0-beta.15/angular2-polyfills.js:320:48)
    at drainMicroTaskQueue (https://code.angularjs.org/2.0.0-beta.15/angular2-polyfills.js:541:36)
    at XMLHttpRequest.ZoneTask.invoke (https://code.angularjs.org/2.0.0-beta.15/angular2-polyfills.js:493:22)
```

**Demo**: https://plnkr.co/edit/38X1of?p=preview (using **beta.15** since I could not get testing in beta.16 working in the Plunk)

_What steps should we try in your demo to see the problem?_

Just let the demo run and look at the output from Jasmine.

**Current behavior**

The above error is output.

**Expected/desired behavior**

No errors. The test should pass.

**Other information**

When using a built-in pipe such as `date` or `json`, no errors are thrown. This only seems to be a problem with user-defined pipes.

**Comment by michaelbromley** [comment]
Just tested this locally with **beta.17** and it is still an issue.

**Comment by michaelbromley** [comment]
Just tested locally with rc.1 and it still seems to be an issue.

**Comment by bczengel** [comment]
This also seems to happen when you use .overrideDirective().  I'm on rc.1 as well.

**Comment by yjaaidi** [comment]
+1

**Comment by vicb** [comment]
Could someone please provide a plunker on rc2 ?

**Comment by vicb** [comment]
@juliemr could you please take a look ?

**Comment by michaelbromley** [comment]
@vicb @juliemr Just put together a plunk on rc.2 and it looks like it is fixed: https://plnkr.co/edit/P9TqOG?p=preview

To confirm that it is fixed from rc.1, you can change line 9 of config.js to `var ngVer = '@2.0.0-rc.1';` and the second test will fail.

**Comment by vicb** [comment]
@michaelbromley thanks for investigating
