### ISSUE TITLE
beta.16 `(click)="foo = []"` error: "Unsupported number of argument for pure functions"

### ISSUE THREAD

**Issue by tycho01** [angular/angular#8336]
I had snippets in my templates like `<button (click)="foo = []">clear foo</button>`. After upgrading from beta 15 to 16, such actions in assignment format (`foo = []`) now throw with the following error: `Unsupported number of argument for pure functions: 0`, and would need to be refactored to method calls. Plunker [here](http://plnkr.co/edit/Yyby58) -- if you change the angular version to 15 it works.

If this break was intentional, then so be it, but I hadn't been under the impression I'd seen mention of changes like this in the log. If I didn't just miss it in the changelog, I wonder if that means this change was an unintended side-effect of recent refactoring.

**Comment by vikerman** [comment]
This is a regression. Looking at it.

**Comment by vikerman** [comment]
Stack trace when I put this in a test - 

ERROR: Error{rejection: BaseException{message: 'Unsupported number of argument for pure functions: 0', stack: 'Error: Unsupported number of argument for pure functions: 0
    at new BaseException (http://localhost:9876/base/dist/js/dev/es5/angular2/src/facade/exceptions.js:17:23)
    at Object.createPureProxy (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/util.js:85:15)
    at CompileView.createLiteralArray (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/compile_view.js:124:16)
    at _AstToIrVisitor.visitLiteralArray (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/expression_converter.js:154:68)
    at LiteralArray.visit (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/expression_parser/ast.js:211:24)
    at _AstToIrVisitor.visitPropertyWrite (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/expression_converter.js:210:87)
    at PropertyWrite.visit (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/expression_parser/ast.js:127:24)
    at ASTWithSource.visit (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/expression_parser/ast.js:326:25)
    at Object.convertCdStatementToIr (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/expression_converter.js:24:28)
    at CompileEventListener.addAction (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/event_binder.js:37:50)
    at http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/event_binder.js:100:18
    at Array.forEach (native)
    at Object.collectEventListeners (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/event_binder.js:97:16)
    at ViewBinderVisitor.visitElement (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/view_binder.js:30:45)
    at ElementAst.visit (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/template_ast.js:137:24)
    at http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/template_ast.js:280:29
    at Array.forEach (native)
    at Object.templateVisitAll (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/template_ast.js:279:10)
    at Object.bindView (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/view_binder.js:9:20)
    at ViewCompiler.compileComponent (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/view_compiler/view_compiler.js:37:23)
    at RuntimeCompiler._compileComponent (http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/runtime_compiler.js:90:48)
    at http://localhost:9876/base/dist/js/dev/es5/angular2/src/compiler/runtime_compiler.js:81:49

**Comment by tbosch** [comment]
The problem here is the empty array. If the array is non empty, this is not a problem.
Will fix this still...
