### ISSUE TITLE
angular_1_router doesn't build

### ISSUE THREAD

**Issue by dpogue** [angular/angular#8395]
```
$ gulp buildRouter.dev

[14:50:36] Using gulpfile /mnt/users/dpogue/Coding/angular/gulpfile.js
[14:50:36] Starting 'buildRouter.dev'...
[14:50:36] 'buildRouter.dev' errored after 346 μs
[14:50:36] Error: ENOENT: no such file or directory, open '/mnt/users/dpogue/Coding/angular/modules/angular2/src/router/utils.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at /mnt/users/dpogue/Coding/angular/modules/angular1_router/build.js:40:32
    at Array.reduce (native)
    at main (/mnt/users/dpogue/Coding/angular/modules/angular1_router/build.js:39:26)
    at module.exports (/mnt/users/dpogue/Coding/angular/modules/angular1_router/build.js:88:49)
    at Gulp.<anonymous> (/mnt/users/dpogue/Coding/angular/gulpfile.js:664:3)
    at module.exports (/mnt/users/dpogue/Coding/angular/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/mnt/users/dpogue/Coding/angular/node_modules/orchestrator/index.js:273:3)
```

**Comment by Josh68** [comment]
+1, same issue here, same path not found: '/angular/modules/angular2/src/router/utils.ts'

**Comment by jrauschenbusch** [comment]
There are some fixes needed in file [build.js](https://github.com/angular/angular/blob/master/modules/angular1_router/build.js).

[build.js?#L38](https://github.com/angular/angular/blob/master/modules/angular1_router/build.js?#L38):

`var dir = modulesDirectory + '/angular2/src/router/';`
should be replaced with
`var dir = modulesDirectory + '/@angular/router-deprecated/src/';`

[build.js?#L54](https://github.com/angular/angular/blob/master/modules/angular1_router/build.js?#L54):

The import regex is not sufficient on Windows OS. Hence replace ...
`var IMPORT_RE = new RegExp("import \\{?([\\w\\n_, ]+)\\}? from '(.+)';?", 'g');` 
with 
`var IMPORT_RE = new RegExp("import \\{?([\\w\\t\\r\\n_, ]+)\\}? from '(.+)';?", 'g');`

[build.js?#L78](https://github.com/angular/angular/blob/master/modules/angular1_router/build.js?#L78):
```
function isFacadeModule(modulePath) {
  return modulePath.indexOf('facade') > -1 ||
    modulePath === 'angular2/src/core/reflection/reflection';
}
```
should be replaced with
```
function isFacadeModule(modulePath) {
  return modulePath.indexOf('facade') > -1 ||
    modulePath === '@angular/core/src/reflection/reflection';
}
```

**Comment by vicb** [comment]
obsolete
