### ISSUE TITLE
Gulp gives horrible errors

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#850]
My build failed and reported errors like:

```
[11:36:43] 'build.js.dev' errored after 11 s
[11:36:43] Error: [object Object]
    at formatError (/home/deboer/github/nvm/v0.10.22/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/deboer/github/nvm/v0.10.22/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/run-sequence/index.js:38:5)
    at Gulp.onError (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/run-sequence/index.js:45:4)
    at Gulp.EventEmitter.emit (events.js:117:20)
```

This error does not help me debug my issue and should be improved.

**Comment by buberdds** [comment]
Hi there, tried to play with angular2. Same problem here, I think it's failing while creating symlinks (Win8.1, I'll check other OS later)

example:
\Github\angular\tools\build\linknodemodules.js

With try/catch statement users will get more info
 
        try {
          fs.symlinkSync(sourceDir, linkDir, 'dir');
        } catch (e) {
          console.log('Cannot create a symlink! linkDir:' + linkDir + ' sourceDir: ' + sourceDir);
          process.exit(0);
        }

[10:07:41] Starting 'build/linknodemodules.js.cjs'...
creating link dist\js\cjs\node_modules\benchmarks ..\benchmarks
Cannot create a symlink! linkDir:dist\js\cjs\node_modules\benchmarks sourceDir: ..\benchmarks

this is a gulp-debug output 
[10:04:16] Error: EPERM, operation not permitted 'D:\Github\angular\dist\js\cjs\node_modules\benchmarks'

**Comment by jphedley** [comment]
I'm having build problems also, but my error is different from yours. On Win 7, with 
-a---          3/4/2015   7:54 AM      17648 gulpfile.js (Pacific Standard Time)

C:\progs\JavaScript\AngularJS\src\angular>gulp build.js.dev
Dart SDK is not available, Dart tasks will be skipped.

AssertionError: path must be a string
    at Module.require (module.js:362:3)
    at require (module.js:380:17)
    at requireFn (C:\progs\JavaScript\AngularJS\src\angular\node_modules\gulp-lo
ad-plugins\index.js:37:14)
    at Object.defineProperty.get (C:\progs\JavaScript\AngularJS\src\angular\node
_modules\gulp-load-plugins\index.js:68:18)
    at Object.<anonymous> (C:\progs\JavaScript\AngularJS\src\angular\gulpfile.js
:151:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Line 42 is
{src: 'node_modules/zone.js/long-stack-trace-zone.js', mimeType: 'text/javascript', copy: true},
which looks like a string to me. I had this error on Fri, but I thought it might be due to these being files I didn't have, which have now become node_modules, which I was expected to happen & waited. But alas, no difference.

Anyone have any ideas?

**Comment by marshallmick007** [comment]
@buberdds I had a similar problem on Windows and solved it by running a command prompt as Administrator and then launching `gulp build`. `fs.symlinkSync()` requires elevated privileges on a Windows platform.

I would agree that it would be nice to trap that error and notify Windows users to run this under Administrator privileges.

@jbdeboer Those errors were similar to the ones I was seeing on Windows. I suspect one of the gulp tasks failed with some error that you might be able to research (for me it was the same error as @buberdds). When one task fails, it looks like the rest of the gulp tasks in the pipeline begin to fail with the pattern you posted as well, instead of the system halting. Since it looks like you are on a unix-like system, you could try `sudo`

**Comment by mhevery** [comment]
I think this is an error from dart formatter. Are you using Dart v1.9(dev) ?

**Comment by tbosch** [comment]
@buberdds Yes, sorry, we all use Linux / Mac dev environment, so we don't know whether Windows is broken...

@jbdeboer 
If you get an error before that points to `dart_format` with something like "wrong snapshot", you should clean your global pub cache, i.e. `rm -rm ~/.pub-cache`.
Background: We are using `dart_style` to format the Dart code. For this, we need to install it globally. However, when you update Dart, this pub cache might be outdated and you get this weird error.

**Comment by jbdeboer** [comment]
@tbosch I fixed the underlying issue in my environment.  The point of this issue is that the error that gulp gives is unhelpful. A good error message would not only tell me that the build failed, but also why it failed and how I might fix the issue.

**Comment by mhevery** [comment]
Switched over to broccoli for build. Lot's of cleanup on dart analyzer error messages. Closing.

**Comment by jbdeboer** [comment]
So what do the build errors look like now? Do you have tests to ensure that these issues do not reoccur?

**Comment by jbdeboer** [comment]
I verified that these errors still exist at  b9eab463f7e009f9de802f4a39735506721ef402

Steps to reproduce:
1. Simulate a broken dart environment:

    touch $(which dart) $(which pub)

2. Follow the instructions on https://github.com/angular/angular/blob/master/DEVELOPER.md

    npm install
    $(npm bin)/gulp build

Expected, an error with sane output

Actual:

[14:11:31] 'build/pubspec.dart' errored after 544 ms
[14:11:31] Error: 1
    at formatError (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.EventEmitter.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /usr/local/google/home/deboer/gits/angular2/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:45:4
    at _rejected (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/q/q.js:804:24)
    at /usr/local/google/home/deboer/gits/angular2/angular/node_modules/q/q.js:830:30
    at Promise.when (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/q/q.js:1064:31)
    at Promise.promise.promiseDispatch (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/q/q.js:748:41)
    at /usr/local/google/home/deboer/gits/angular2/angular/node_modules/q/q.js:564:44
    at flush (/usr/local/google/home/deboer/gits/angular2/angular/node_modules/q/q.js:110:17)
    at process._tickCallback (node.js:415:13)

**Comment by IgorMinar** [comment]
closing in favor of #2021
