### ISSUE TITLE
Angular-2.0.0-rc.1 does not work on Android 4.3 (missing polyfills)

### ISSUE THREAD

**Issue by capi** [angular/angular#8504]
After upgrading from `beta-12` to `rc-1` I noticed that some polyfills seem to be missing, causing the angular application to no longer running on Android 4.3 (not tested with others).

Previous versions provided the polyfills for IE which also fixed this on Android 4.3.

**Steps to reproduce and a minimal demo of the problem**

    git clone https://github.com/angular/quickstart.git angular2-quickstart
    cd angular2-quickstart
    npm install
    npm run

On Android 4.3 device: open URL to test system.

**Error message**

Happens with the quickstart tutorial.

    TypeError: Object [object DOMWindow] has no method 'requestAnimationFrame'
      at BrowserDomAdapter.requestAnimationFrame (eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18))
      at RafQueue._raf (eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18))
      at new RafQueue (eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18))
      at BrowserDetails.raf (eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18))
      at BrowserDetails.doesElapsedTimeIncludesDelay (eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18))
      at new BrowserDetails (eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18))
      at eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18)
      at ReflectiveInjector_._instantiate (eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18))
      at ReflectiveInjector_._instantiateProvider (eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18))
      at ReflectiveInjector_._new (eval at <anonymous> (http://10.20.1.10:3000/node_modules/systemjs/dist/system.src.js:1510:18)) at null:77

**Comment by pkozlowski-opensource** [comment]
Indeed, Android 4.3 doesn't support rAF: http://caniuse.com/#feat=requestanimationframe
Having said this, we are not distributing general polyffils as part of the framework (in some cases there are licensing issues that prevents doing so).

**Comment by capi** [comment]
You did in the betas, that's why I raised the ticket. If it is an intentional change and Android 4.3 is out-of-scope for supporting out-of-the-box, please close the ticket, I do understand.

**Comment by smith64fx** [comment]
Same Problem here with RC1

**Comment by wesleycho** [comment]
One can easily polyfill for rAF if one wants - [here](https://gist.github.com/paulirish/1579671) is a popular snippet.

Maybe this could be noted in the documentation about Android, but this isn't really an issue with Angular itself & maybe an issue should be opened in the docs repo instead.

**Comment by vicb** [comment]
we don't use rAF any more for now IIRC
