### ISSUE TITLE
CLI template compiler error on Windows

### ISSUE THREAD

**Issue by lmcnulty4** [angular/angular#8582]
The CLI template compiler is failing on Windows with the following:

```
> ngc -p .

can't resolve module @angular/core/src/di/provider from C:\ng2-compiler-test2-master\index.ts
Error: Could not resolve module @angular/core/src/di/provider relative to C:\ng2-compiler-test2-master\index.ts
    at NodeReflectorHost.findDeclaration (C:\ng2-compiler-test2-master\node_modules\@angular\compiler-cli\reflector_host.js:90:23)
    at StaticReflector.initializeConversionMap (C:\ng2-compiler-test2-master\node_modules\@angular\compiler-cli\static_reflector.js:127:55)
    at new StaticReflector (C:\ng2-compiler-test2-master\node_modules\@angular\compiler-cli\static_reflector.js:33:14)
    at Function.CodeGenerator.create (C:\ng2-compiler-test2-master\node_modules\@angular\compiler-cli\codegen.js:122:31)
    at main (C:\ng2-compiler-test2-master\node_modules\@angular\compiler-cli\main.js:37:37)
    at Object.<anonymous> (C:\ng2-compiler-test2-master\node_modules\@angular\compiler-cli\main.js:62:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
Compilation failed

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\L\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "_codegen"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-compiler-test2@1.0.0 _codegen: `ngc -p .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-compiler-test2@1.0.0 _codegen script 'ngc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-compiler-test2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-compiler-test2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-compiler-test2
npm ERR! There is likely additional logging output above.
```

This is due to path.join using backslashes in Windows. TypeScript is not normalizing these backslashes into forward slashes (despite having an unexposed normalizePath function) and so can't properly resolve modules.

A possible correction for this is, in modules/@angular/compiler_cli/src/reflector_host.ts, update the resolve function from the following: 

```
  private resolve(m: string, containingFile: string) {
    const resolved =
        ts.resolveModuleName(m, containingFile, this.options, this.compilerHost).resolvedModule;
    return resolved ? resolved.resolvedFileName : null;
  };
```

to the following:

```
  private resolve(m: string, containingFile: string) {
    const resolved =
        ts.resolveModuleName(m, containingFile.replace(/\\/g,'/'), this.options, this.compilerHost).resolvedModule;
    return resolved ? resolved.resolvedFileName : null;
  };
```

**Comment by xogeny** [comment]
As a data point, this fix did get me past this error (and on to whole new ones :frowning:)

**Comment by alexeagle** [comment]
@vladima it looks like a bug to me, that program.ts has some methods which accept `containingFile: string` and expect it to be already normalized (eg. they call `ts.getDirectoryPath` on the value. which searches for `directorySeparator`). Yet `ts.normalize` is in `core.ts` which is all marked `@internal`. Seems like TypeScript ought to normalize all paths that originate from API users?

**Comment by mlaval** [comment]
This issue is no longer occurring, but the compiler still doesn't work on Windows.
See https://github.com/angular/angular/issues/10792 for the resolution.
