### ISSUE TITLE
Angular Build fails on Windows 10

### ISSUE THREAD

**Issue by marcengeler** [angular/angular#8594]
I currently have some issues trying to install and build angular in Windows 10 while running

`npm install`

I run the Command Shell as Administrator. I specifically use the Visual Studio 2013 Command shell, as the npm install tries to recompile the code during installation. In the end I get the following output:

`19829 error Windows_NT 10.0.10240`
`19830 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\engmar\\AppData\\Roaming`
`\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"`
`19831 error node v6.1.0`
`19832 error npm  v3.8.9`
`19833 error code ELIFECYCLE`
`19834 error node-sass@3.4.2 postinstall: `node scripts/build.js``
`19834 error Exit status 1`
`19835 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.`
`19835 error Make sure you have the latest version of node.js and npm installed.``

I assume the error comes from

`node scripts/build.js`

`Building: C:\Program Files\nodejs\node.exe D:\Angular\angular\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=`

where the installation tries to build node-gyp. The build fails with 461 Errors and the following error:

`gyp ERR! build error`
`gyp ERR! stack Error: `msbuild` failed with exit code: 1`
`gyp ERR! stack     at ChildProcess.onExit (D:\Angular\angular\node_modules\node-gyp\lib\build.js:276:23)`
`gyp ERR! stack     at emitTwo (events.js:106:13)`
`gyp ERR! stack     at ChildProcess.emit (events.js:191:7)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)`
`gyp ERR! System Windows_NT 10.0.10240`
`gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Angular\\angular\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="`
`gyp ERR! cwd D:\Angular\angular\node_modules\node-sass`
`gyp ERR! node -v v6.1.0`
`gyp ERR! node-gyp -v v3.2.1`
`gyp ERR! not ok`
[npm-debug.txt](https://github.com/angular/angular/files/259431/npm-debug.txt)
[npm-debug.txt](https://github.com/angular/angular/files/259433/npm-debug.txt)
[npm-debug.txt](https://github.com/angular/angular/files/259435/npm-debug.txt)

I tried various error solutions throughout google and github, so by now everything is up to date:

- node.js
- grunt
- Windows 7 SDK
- Visual Studio 2015, Visual Studio 2013 (Tried both with the same result)
- Python 2.7
- bower
- grunt-node-inspector

And I am up to the point, where I think I need to post my issue here. So if anybody knows what I am doing wrong, I'd apreciate the help.

Best Regards
Marc

**Comment by marcengeler** [comment]
From another solution:

Make sure your NodeJS version is >= 5.4.1 but < 6.0 (check with node -v)
If your distro is already on Node 6.x, use nvm to install NodeJS 5.11.1 locally.

Did the job!
