### ISSUE TITLE
ng serve breaks silently if Service (@Injectable()) is imported via index.js

### ISSUE THREAD

**Issue by delight** [angular/angular#8620]
If an service is exported via index.js 
``` export { TaskService } from './task.service';```
and imported at the `@Component` that uses it via DI 
```import { TaskService } from './';```
instead of 
```import { TaskService } from './'task.service;```
the app won't come up no longer and no error in ng serve what so ever.

I have a little demo with the breaking change commit in the `breakingChange`branch
[https://github.com/delight/ng2import-problem/tree/breakingChange](https://github.com/delight/ng2import-problem/tree/breakingChange)

It is possible with all kind of other modules (`@Component` / Model) and even the service can be imported from within the index.js anywhere else were it is not needed via DI. So done in Specs or in the Component that is providing the service.

---

- App is generated with the latest angular-cli
- Problem is easily re-produced when app ist trying to be started (branch master vs. breakingChange)

This behavior is inconsistent. While export / import via index.js works for most module types it breaks for service and component via DI.

I guess the problem is with the `@Injectable` Decorator.

**Comment by pkozlowski-opensource** [comment]
I don't think browser's loader is supposed to understand `index.js` the way node.js. Are you sure this is ng2-specific? This sounds like loader-related issue so not related to Angular.

**Comment by delight** [comment]
Well as mentioned it works for everything but the place were DI kicks into place, so I guess it is ng2-specific.

If it is not supposed to work with index.js export/import then it works correctly ;)

**Comment by mhevery** [comment]
This sounds like your loader set up. Angular in no way understands imports/exports and so it can not influence your code.

Please verify that 

```
import { TaskService as TaskService0} from './';
import { TaskService as TaskService1} from './'task.service;

assert(TaskService0 === TaskService1)
```

It sounds like in your case that is not true. In other words it sounds like your application loads the same file twice which results in two different instances of the same type.

**Comment by robwormald** [comment]
`import { TaskService } from './'` is bad syntax and causes weird errors - typescript should really explode but doesn't.

**Comment by delight** [comment]
If it is not supposed to work this way its ok.

@robwormald I don't know if that is such a bad syntax in general. Because that allows you to do things like `import {TaskComponent, Task, TaskService} from ./task-list/;` instead of having a single import line for each module `import {TaskComponent} from ./task-list/task.component;` and so on - and as mentioned it works almost everywhere.

@mhevery 
I tried `TaskService0 === TaskService1` and it's true. Though DI only works with TaskService1.

There is also a browser_adapter.js / zone.js stacktrace in the browser-console that is not very helpful: `EXCEPTION: TypeError: Cannot read property 'query' of null`.
And today I saw that the tests are failing though with TaskService0 / import from index.ts ! While TaskService1 work fine.

ng test:
```
Chrome 50.0.2661 (Mac OS X 10.11.4) Component: TaskList should inject the component FAILED
	Error: Cannot resolve all parameters for 'TaskListComponent'(undefined). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'TaskListComponent' is decorated with Injectable.
	    at NoAnnotationError.BaseException [as constructor] (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/facade/exceptions.js:17:23)
	    at new NoAnnotationError (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_exceptions.js:217:16)
	    at _extractToken (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:232:15)
	    at eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:184:45)
	    at Array.map (native)
	    at _dependenciesFor (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:184:19)
	    at resolveReflectiveFactory (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:72:24)
	    at resolveReflectiveProvider (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:96:97)
	    at Array.map (native)
	    at Object.resolveReflectiveProviders (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:104:31)
	    at Function.ReflectiveInjector.resolve (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_injector.js:357:38)
	    at ReflectiveInjector_.resolveAndCreateChild (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_injector.js:595:62)
	    at TestInjector.createInjector (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:31:39)
	    at TestInjector.execute (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:44:18)
	    at eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:135:55)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:98:26)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at ZoneDelegate.invoke (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:323:29)
	    at Zone.run (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:216:44)
	    at /Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:571:58
	    at ZoneDelegate.invokeTask (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:256:48)
	    at drainMicroTaskQueue (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:474:36)
	    at XMLHttpRequest.ZoneTask.invoke (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:426:22)
	Error: Cannot resolve all parameters for 'TaskListComponent'(undefined). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'TaskListComponent' is decorated with Injectable.
	    at NoAnnotationError.BaseException [as constructor] (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/facade/exceptions.js:17:23)
	    at new NoAnnotationError (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_exceptions.js:217:16)
	    at _extractToken (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:232:15)
	    at eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:184:45)
	    at Array.map (native)
	    at _dependenciesFor (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:184:19)
	    at resolveReflectiveFactory (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:72:24)
	    at resolveReflectiveProvider (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:96:97)
	    at Array.map (native)
	    at Object.resolveReflectiveProviders (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:104:31)
	    at Function.ReflectiveInjector.resolve (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_injector.js:357:38)
	    at ReflectiveInjector_.resolveAndCreateChild (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_injector.js:595:62)
	    at TestInjector.createInjector (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:31:39)
	    at TestInjector.execute (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:44:18)
	    at eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:135:55)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:98:26)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at ZoneDelegate.invoke (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:323:29)
	    at Zone.run (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:216:44)
	    at /Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:571:58
	    at ZoneDelegate.invokeTask (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:256:48)
	    at drainMicroTaskQueue (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:474:36)
	    at XMLHttpRequest.ZoneTask.invoke (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:426:22)
Chrome 50.0.2661 (Mac OS X 10.11.4) Component: TaskList should create the component FAILED
	Error: Cannot resolve all parameters for 'TaskListComponent'(undefined). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'TaskListComponent' is decorated with Injectable.
	    at NoAnnotationError.BaseException [as constructor] (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/facade/exceptions.js:17:23)
	    at new NoAnnotationError (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_exceptions.js:217:16)
	    at _extractToken (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:232:15)
	    at eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:184:45)
	    at Array.map (native)
	    at _dependenciesFor (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:184:19)
	    at resolveReflectiveFactory (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:72:24)
	    at resolveReflectiveProvider (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:96:97)
	    at Array.map (native)
	    at Object.resolveReflectiveProviders (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:104:31)
	    at Function.ReflectiveInjector.resolve (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_injector.js:357:38)
	    at ReflectiveInjector_.resolveAndCreateChild (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_injector.js:595:62)
	    at TestInjector.createInjector (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:31:39)
	    at TestInjector.execute (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:44:18)
	    at eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:135:55)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:98:26)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at ZoneDelegate.invoke (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:323:29)
	    at Zone.run (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:216:44)
	    at /Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:571:58
	    at ZoneDelegate.invokeTask (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:256:48)
	    at drainMicroTaskQueue (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:474:36)
	    at XMLHttpRequest.ZoneTask.invoke (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:426:22)
	Error: Cannot resolve all parameters for 'TaskListComponent'(undefined). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'TaskListComponent' is decorated with Injectable.
	    at NoAnnotationError.BaseException [as constructor] (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/facade/exceptions.js:17:23)
	    at new NoAnnotationError (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_exceptions.js:217:16)
	    at _extractToken (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:232:15)
	    at eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:184:45)
	    at Array.map (native)
	    at _dependenciesFor (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:184:19)
	    at resolveReflectiveFactory (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:72:24)
	    at resolveReflectiveProvider (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:96:97)
	    at Array.map (native)
	    at Object.resolveReflectiveProviders (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_provider.js:104:31)
	    at Function.ReflectiveInjector.resolve (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_injector.js:357:38)
	    at ReflectiveInjector_.resolveAndCreateChild (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/src/di/reflective_injector.js:595:62)
	    at TestInjector.createInjector (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:31:39)
	    at TestInjector.execute (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:44:18)
	    at eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/test_injector.js:135:55)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:98:26)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at Object.eval (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/@angular/core/testing/testing.js:105:17)
	    at ZoneDelegate.invoke (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:323:29)
	    at Zone.run (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:216:44)
	    at /Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:571:58
	    at ZoneDelegate.invokeTask (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:256:48)
	    at drainMicroTaskQueue (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:474:36)
	    at XMLHttpRequest.ZoneTask.invoke (/Users/koko/devel/nggenerate/pomodoro/dist/vendor/zone.js/dist/zone.js:426:22)
Chrome 50.0.2661 (Mac OS X 10.11.4): Executed 5 of 5 (2 FAILED) (0.09 secs / 0.049 secs)
```

**Comment by delight** [comment]
[B like Barrel !](https://angular.io/docs/ts/latest/guide/glossary.html#!#B)

this suggests to just with index.js files

**Comment by delight** [comment]
Also in the styleguide:

**Create and Import Barrels**


Style 04-10

Do create a file that imports, aggregates, and re-exports items. We call this technique a barrel.

**Do** name this barrel file **index.ts**.

Why? A barrel aggregates many imports into a single import.

Why? A barrel reduces the number of imports a file may need.

Why? A barrel shortens import statements.

**Comment by mhevery** [comment]
@delight can you create a repro case in plunker? As of right now, from my point of view, it works as expected. A plunker would really help to focus this conversation.

**Comment by schmuli** [comment]
The issue here is actually a combination of following the Style Guide on creating barrels, and the way that SystemJS works in the browser.

On the one hand, the Style Guide recommends creating an `index.ts|js` barrel for each folder in an app, including each subfolder.

On the other hand, SystemJS doesn't automatically load `index.js` when importing a folder, unless it has been configured correctly. However, in order to configure SystemJS to correctly support barrels, this would require specifying **every** folder/subfolder and mapping them to index.js.

Please see the following:
1. https://groups.google.com/forum/#!topic/angular/GdKwt18wQdA
2. https://www.reddit.com/r/Angular2/comments/4i2d9x/support_problem_with_barrels/
