### ISSUE TITLE
Improve the error message when a component's template is not a string

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#8708]
Today after some refactorings, I was faced with this stack trace upon launching my application:

```
Error: Uncaught (in promise): TypeError: Object doesn't support property or method 'charCodeAt'
   at resolvePromise (http://localhost:4146/vendor-dev.js:99618:27)
   at Anonymous function (http://localhost:4146/vendor-dev.js:99595:15)
   at Anonymous function (http://localhost:4146/vendor-dev.js:7373:26)
   at ZoneDelegate.prototype.invoke (http://localhost:4146/vendor-dev.js:99401:15)
   at onInvoke (http://localhost:4146/vendor-dev.js:9189:26)
   at ZoneDelegate.prototype.invoke (http://localhost:4146/vendor-dev.js:99401:15)
   at Zone.prototype.run (http://localhost:4146/vendor-dev.js:99296:19)
   at Anonymous function (http://localhost:4146/vendor-dev.js:99651:19)
   at ZoneDelegate.prototype.invokeTask (http://localhost:4146/vendor-dev.js:99434:19)
   at onInvokeTask (http://localhost:4146/vendor-dev.js:9180:26)
vendor-dev.js (36611,14)
```

The reason for this stack trace was that I had omitted a `.html` when `require`ing a component's template. This resulted in webpack adding a default `.ts` extension and using my component's module instead of the actual HTML template and the component itself became the template.

The same effect and stack trace can be achieved by

``` ts
@Component({
    //....
    template: <string>{}
})
```

I think there should be a better error message / stack trace to quicker get to the bottom of this.

**Comment by arthur801031** [comment]
@vicb @mhevery  @pkozlowski-opensource  May I work on this? I'm a first time contributor to angular. Thank you!

**Comment by vicb** [comment]
@arthur801031 yep, any "hotlist: community-help" issues are usually good to start with. Also it's a good think to let people know when you are working on an issue by adding a comment.

Thanks and let us know if you need some directions.

**Comment by arthur801031** [comment]
@vicb Could you please provide some guidance on the following issues that I encountered? 

- I'm not sure which file I need to edit to handle this error. 

- Besides running the tests, how do I run the angular program on my machine to test the code I modified? 

Thank you very much!

**Comment by laumair** [comment]
@vicb @arthur801031 Any update on this? I can take this on.

**Comment by arthur801031** [comment]
@laumair I'm still working on this, but I'm waiting for @vicb to reply to my questions.
