### ISSUE TITLE
Quickstart "npm start" script update

### ISSUE THREAD

**Issue by perrierism** [angular/angular#8713]
**Reproduction**
1. Quickstart tutorial to "[Step 5: Build and run the app!](https://angular.io/docs/ts/latest/quickstart.html#!#build-and-run)" ( `npm start` )

In packages.json, I had to change the start script as suggested in [#6097](https://github.com/angular/angular/issues/6097#issuecomment-212483740) :
```"start" :  "concurrently \"npm run tsc:w\" \"npm run lite\" "```

Otherwise was getting:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular2-quickstart@1.0.0
6 info start angular2-quickstart@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info angular2-quickstart@1.0.0 Failed to exec start script
9 verbose stack Error: angular2-quickstart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
9 verbose stack Exit status 2
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid angular2-quickstart@1.0.0
11 verbose cwd /Users/lpg/Workspace/an2/angular2-quickstart/app
12 error Darwin 15.5.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.4
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error angular2-quickstart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
17 error Exit status 2
18 error Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
18 error This is most likely a problem with the angular2-quickstart package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     tsc && concurrently "npm run tsc:w" "npm run lite"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs angular2-quickstart
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls angular2-quickstart
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Other information**

OSX 10.11.5
lite-server@2.2.0
concurrently@2.1.0
```
npm version
{ npm: '2.15.1',
  ares: '1.10.1-DEV',
  http_parser: '2.5.2',
  icu: '56.1',
  modules: '46',
  node: '4.4.4',
  openssl: '1.0.2h',
  uv: '1.8.0',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

**Comment by bodikqlar** [comment]
I have the same problem

**Comment by BrewDawg** [comment]
Try running the sample using node.exe directly, it will never work, that is our problem, there are some real loading/startup issues with Angular 2, everyone is using that "npm run lite" syntax but these applications cannot be launched directly via node.exe

**Comment by bodikqlar** [comment]
I resolved the issue when I updated nodejs to the 5th version.

**Comment by pkozlowski-opensource** [comment]
Sounds like it was solved with the node update. If not docs are living in a separate repo: https://github.com/angular/angular.io
