### ISSUE TITLE
Not compatible with your operating system or architecture: fsevents@1.0.6

### ISSUE THREAD

**Issue by NullVoxPopuli** [angular/angular#8815]
* **I'm submitting a ...**
- [ x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

npm install -g https://github.com/angular/angular.git

```
$ npm install -g https://github.com/angular/angular.git
npm WARN engine joi-assert@0.0.3: wanted: {"node":">= 0.10.0 <= 0.11.0"} (current: {"node":"5.10.1","npm":"2.14.21"})
 
> utf-8-validate@1.2.1 install /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
../src/validation.cc:15:17: fatal error: nan.h: No such file or directory
compilation terminated.
validation.target.mk:91: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory '/home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/webdev/ClientDevelopment/ATI/Portal.Librarian/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command "/home/webdev/.nvm/versions/node/v5.10.1/bin/node" "/home/webdev/ClientDevelopment/ATI/Portal.Librarian/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/utf-8-validate
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
 
> bufferutil@1.2.1 install /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/bufferutil
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.cc:16:17: fatal error: nan.h: No such file or directory
compilation terminated.
bufferutil.target.mk:91: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory '/home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/webdev/ClientDevelopment/ATI/Portal.Librarian/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command "/home/webdev/.nvm/versions/node/v5.10.1/bin/node" "/home/webdev/ClientDevelopment/ATI/Portal.Librarian/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/bufferutil
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
 
> spawn-sync@1.0.13 postinstall /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/spawn-sync
> node postinstall

npm WARN peerDependencies The peer dependency typescript@^1.8.0 || ^1.9.0-dev included from tsickle will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> node-sass@3.4.2 install /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/node-sass/vendor/linux-x64-47/binding.node
 
> node-sass@3.4.2 postinstall /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/node-sass
> node scripts/build.js

` /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/node-sass/vendor/linux-x64-47/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
 
> sauce-connect-launcher@0.13.0 postinstall /home/webdev/.nvm/versions/node/v5.10.1/lib/node_modules/angular-srcs/node_modules/sauce-connect-launcher
> node scripts/install.js

npm WARN peerDependencies The peer dependency typescript@>=1.7.3 || >=1.8.0-dev || >=1.9.0-dev included from tslint will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/home/webdev/.nvm/versions/node/v5.10.1/bin/node" "/home/webdev/ClientDevelopment/ATI/Portal.Librarian/node_modules/.bin/npm" "install" "-g" "https://github.com/angular/angular.git"
npm ERR! node v5.10.1
npm ERR! npm  v2.14.21
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/webdev/ClientDevelopment/ATI/Portal.Librarian/npm-debug.log

```

**Comment by jeffbcross** [comment]
The repo isn't really meant to be npm installed directly. If you want to build locally, use `git clone`, otherwise npm install packages from npm. https://angular.io/docs/ts/latest/quickstart.html

If I misunderstood your use case, please open a new issue describing what you're trying to accomplish.

**Comment by NullVoxPopuli** [comment]
ok, cool. thanks!
