### ISSUE TITLE
Offline compiler broken by `--stripInternal`

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#8819]
https://github.com/angular/angular/commit/0035575c821aa16bdc7cd8d45c715f003c37cad0 turned on `--stripInternal`
and now eg.
https://github.com/angular/core-builds/blob/master/esm/src/application_ref.metadata.json contains `PLATFORM_CORE_PROVIDERS` but https://github.com/angular/core-builds/blob/master/esm/src/application_ref.d.ts does not.

This causes the compiler to try to locate the declaration of the symbol but fail with 
```
Error: can't find symbol PLATFORM_CORE_PROVIDERS exported from module /Users/alexeagle/Projects/compiler_cli_user2/node_modules/@angular/core/src/application_ref.d.ts
    at NodeReflectorHost.findDeclaration (/Users/alexeagle/Projects/compiler_cli_user2/node_modules/@angular/compiler-cli/src/reflector_host.js:104:23)
    at CodeGenerator.readComponents (/Users/alexeagle/Projects/compiler_cli_user2/node_modules/@angular/compiler-cli/src/codegen.js:52:49)
    at generateOneFile (/Users/alexeagle/Projects/compiler_cli_user2/node_modules/@angular/compiler-cli/src/codegen.js:93:38)
    at Array.map (native)
    at CodeGenerator.codegen (/Users/alexeagle/Projects/compiler_cli_user2/node_modules/@angular/compiler-cli/src/codegen.js:120:14)
```

Root cause is that the integration test for compiler-cli is running against the wrong `.d.ts` files.

cc @IgorMinar

**Comment by IgorMinar** [comment]
@alexeagle I have a fix for this pending already

**Comment by alexeagle** [comment]
I assume your fix does not address the problem with the test? I'll do that
next

**Comment by alexeagle** [comment]
What makes you think this is the only @internal symbol that breaks it?

**Comment by IgorMinar** [comment]
There is no other top level symbol in our codebase marked as internal
(except for one in the router but that is being rewritten anyway).

+1 for adding e2e tests though. do you plan to resurrect the old typings
test and make it offline?

**Comment by alexeagle** [comment]
I think the bug is the offline compiler integration test is using the
internal .d.ts file.

We separately need a typings test that our NPM distro can type-check
against user app. It didn't occur to me that we're missing that
verification too.
