### ISSUE TITLE
[bug] `ng-content` with line breaks but no content causes errors

### ISSUE THREAD

**Issue by amcdnl** [angular/angular#8840]
## Bug
Line breaks and/or empty text between `ng-content` tags causes error.

## Scenario
When I have a ES6 string template I often add line returns to break up attributes as they can become rather long. When I'm using `ng-content` and do the same I receive errors.

**Example Component**
```
@Component({
  selector: 'dialog',
  template: `
    <div class="modal">
        <ng-content
            *ngIf="title"
            select="dialog-header">
        </ng-content>
    </div>
  `
})
export class MyDialog {}
```

which produced something like the following from the compiler ( babel ):

```
template: '\n    <div\n      class="modal"\n      [class.open]="visible"\n      *ngClass="{ in: visible, fade: visible }"\n      tabindex="-1"\n      role="dialog">\n      <div class="modal-dialog">\n        <div class="modal-content">\n          <div class="modal-header">\n            <ng-content\n              *ngIf="title"\n              select="dialog-header">\n            </ng-content>\n            <div *ngIf="title || closeButton">\n              <button\n                *ngIf="closeButton"\n                type="button"\n                class="close"\n                (click)="hide()">\n                <span class="icon-x"></span>\n              </button>\n              <h2\n                *ngIf="title"\n                class="modal-title">\n                {{title}}\n              </h2>\n            </div>\n          </div>\n          <div class="modal-body">\n            <ng-content select="dialog-content"></ng-content>\n          </div>\n          <div class="modal-footer" *ngIf="!footer">\n            <ng-content select="dialog-footer"></ng-content>\n          </div>\n        </div>\n      </div>\n    </div>\n  '})
```

which results in the following error:

```
BaseException {message: "Template parse errors:↵<ng-content> element cannot…         select="dialog-header">↵"): Dialog@10:12", stack: "Error: Template parse errors:↵<ng-content> element…_packages/npm/zone.js@0.6.12/dist/zone.js:206:30)"}
message
:
"Template parse errors:↵<ng-content> element cannot have content. <ng-content> must be immediately followed by </ng-content> ("↵        <div class="modal-content">↵          <div class="modal-header">↵            [ERROR ->]<ng-content↵              *ngIf="title"↵              select="dialog-header">↵"): Dialog@10:12"
stack
:
"Error: Template parse errors:↵<ng-content> element cannot have content. <ng-content> must be immediately followed by </ng-content> ("↵        <div class="modal-content">↵          <div class="modal-header">↵            [ERROR ->]<ng-content↵              *ngIf="title"↵              select="dialog-header">↵"): Dialog@10:12↵    at new BaseException (http://127.0.0.1/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/facade/exceptions.js:17:23)↵    at TemplateParser.parse (http://127.0.0.1/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/template_parser.js:87:19)↵    at eval (http://127.0.0.1/jspm_packages/npm/@angular/compiler@2.0.0-rc.1/src/runtime_compiler.js:64:64)↵    at run (http://127.0.0.1/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:104:47)↵    at eval (http://127.0.0.1/jspm_packages/npm/core-js@1.2.6/modules/es6.promise.js:115:28)↵    at MutationObserver.flush (http://127.0.0.1/jspm_packages/npm/core-js@1.2.6/modules/$.microtask.js:19:5)↵    at ZoneDelegate.invoke (http://127.0.0.1/jspm_packages/npm/zone.js@0.6.12/dist/zone.js:323:29)↵    at Zone.runGuarded (http://127.0.0.1/jspm_packages/npm/zone.js@0.6.12/dist/zone.js:230:48)↵    at MutationObserver.eval (http://127.0.0.1/jspm_packages/npm/zone.js@0.6.12/dist/zone.js:206:30)"
```

**Comment by vicb** [comment]
Angular html parser is strict for empty-element. 
Work as expected, the error message is explicit.

**Comment by amcdnl** [comment]
why not just ignore white/empty space?
