### ISSUE TITLE
Bad error reporting from ngc

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#8845]
reported by @robwormald 
If an import is missing, ngc crashes in metadata collection before doing type checking, and no TS diagnostic is printed, making it impossible to track down the problem (workaround is to run vanilla `tsc` on the program)

```
TypeError: Cannot read property 'flags' of undefined
    at Evaluator.evaluateNode (/Users/alexeagle/Projects/angular/dist/tools/tsc-wrapped/src/evaluator.js:308:27)
    at objFromDecorator (/Users/alexeagle/Projects/angular/dist/tools/tsc-wrapped/src/collector.js:63:30)
    at /Users/alexeagle/Projects/angular/dist/tools/tsc-wrapped/src/collector.js:77:73
    at Array.map (native)
    at getDecorators (/Users/alexeagle/Projects/angular/dist/tools/tsc-wrapped/src/collector.js:77:39)
    at classMetadataOf (/Users/alexeagle/Projects/angular/dist/tools/tsc-wrapped/src/collector.js:136:50)
    at MetadataCollector.getMetadata (/Users/alexeagle/Projects/angular/dist/tools/tsc-wrapped/src/collector.js:160:68)
    at NodeReflectorHost.getMetadataFor (/Users/alexeagle/Projects/angular/dist/all/@angular/compiler_cli/src/reflector_host.js:139:47)
    at StaticReflector.getModuleMetadata (/Users/alexeagle/Projects/angular/dist/all/@angular/compiler_cli/src/static_reflector.js:307:40)
    at CodeGenerator.readComponents (/Users/alexeagle/Projects/angular/dist/all/@angular/compiler_cli/src/codegen.js:40:45)
Compilation failed
```

**Comment by alexeagle** [comment]
talked to @chuckjaz - the right fix is for evaluator to stop using the `typeChecker` at all - we already collect the imports in `collector.ts` and we can consult them to determine the origin for each symbol.
Then the metadata collection can continue even if the program has semantic errors, and this error would be reported when we typecheck the program.

**Comment by chuckjaz** [comment]
This has been fixed
