### ISSUE TITLE
MockBackend.createConnection throws Exception 

### ISSUE THREAD

**Issue by dlevkov** [angular/angular#9170]
- **I'm submitting a bug in core Class MockBackend.ts**
- [x] bug report

According to code example in [Http.ts](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/http.ts#L80)

**Current behavior**
Using Http with MockBackend in tests, throws Exception 

> Error: createConnection requires an instance of Request, got [object Object]

Looks like the problem is between Http and MockBackend

**Expected/desired behavior**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal Example:

``` typescript
import { BaseRequestOptions,  Response, ResponseOptions, Http} from '@angular/http';
import {provide, ReflectiveInjector} from '@angular/core';
import {MockBackend} from '@angular/http/testing';
import {it,  describe} from '@angular/core/testing';

describe('MockBackend: TestService', () => {
    it('should return response when subscribed to getItems', () => {
        let injector = ReflectiveInjector.resolveAndCreate([
            MockBackend, BaseRequestOptions,
            provide(Http, {
                useFactory: (backend, options) => {
                    return new Http(backend, options);
                }, deps: [MockBackend, BaseRequestOptions]
            }),
            provide(NanaDal, {
                useFactory: (http: Http) => {
                    return new NanaDal(http);
                },
                deps: [Http]
            }),
        ]);
        let backEnd: MockBackend = injector.get(MockBackend);

        backEnd.connections.subscribe((data: MockConnection) => {
            expect(data.request.url).toContain('service/126');
            data.mockRespond(new Response(new ResponseOptions({ body: { NavigateID: 1, NavigateName: 'name1' } })));
        });

        let testService: NanaDal = injector.get(NanaDal);

        expect(testService instanceof (NanaDal)).toBe(true);
        expect(NanaDal.getInstance()).toEqual(testService);
        testService.setFactory('service', 126);

        testService.getItems().subscribe((res: Navigation) => {
            expect(res).toEqual({ NavigateID: 1, NavigateName: 'name1' });
        });
    });
});
```

Http calls to MockBackend.createConnection and throws Exception.

[mock_backend.ts](https://github.com/angular/angular/blob/master/modules/%40angular/http/testing/mock_backend.ts#L223)

``` typescript
createConnection(req: Request): MockConnection {
    if (!isPresent(req) || !(req instanceof Request)) {
      throw new BaseException(`createConnection requires an instance of Request, got ${req}`);
    }
```

more specific:
`req instanceof Request` returns `false`
- **What is the expected behavior?**
  Expected to NOT throw exception. 
- **What is the motivation / use case for changing the behavior?**
  Current code does not allows to provide any fakes for Http class, so needed change in function preconditions or add instantiated parameter  on caller function in [Http.ts](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/http.ts#L14)

``` typescript
function httpRequest(backend: ConnectionBackend, request: Request): Observable<Response> {
  return backend.createConnection(request).response;
}
```
- **Please tell us about your environment:**
  VS Code on Windows 10 x64
- **Angular version:** 2.0.0-rc.1 
- **Browser:** [Chrome 51 ] 
- **Language:** [ TypeScript 1.8.10  | ES5 ]

**Comment by templth** [comment]
I made some tests and I can't reproduce your problem on RC1. Could you give me more details about the content of the `NanaDal` class.

I tried a simple HTTP call like this:

```
import {Injectable} from '@angular/core';
import {Http} from '@angular/http';
import 'rxjs/Rx';

@Injectable()
export class NanaDal {
  constructor(private http: Http) {
  }

  getItems() {
    return this.http.get('http://localhost/service/126').map(res => res.json());
  }
}
```

Thanks!

**Comment by willm** [comment]
I think I'm seeing the same problem. The issue is in the test code, not in the implementation. When you try and make a request with the mocked Http service, you get this error.

```javascript
import { describe, inject, it, beforeEachProviders } from '@angular/core/testing';
import { Http, BaseRequestOptions, Response, ResponseOptions } from '@angular/http';
import { MockBackend, MockConnection } from '@angular/http/testing';
describe('When recieving an OK response', () => {
		beforeEachProviders(() => [
			NanaDal,
            MockBackend,
            BaseRequestOptions,
            {
				provide: Http,
				useFactory: (backend, options) => new Http(backend, options),
                deps: [MockBackend, BaseRequestOptions]
			}]
		);

		it('returns the items', inject([NanaDal, MockBackend], (nanaDal:NanaDal, mockBackEnd:MockBackend) => {
            mockBackEnd.connections.subscribe((connection:MockConnection) => {
             connection.mockRespond(new Response(new ResponseOptions({body: JSON.stringify({id: 666})})));
            });

			return nanaDal.getItems(); // <= this line throws instead of making a request with themock backend
		}));
	});

```

**Comment by dlevkov** [comment]
@templth the problem is not exists in real code,
only in tests using MockBackend with real Http

**Comment by dlevkov** [comment]
@templth the problem is not exists in real code,
only in tests using MockBackend with real Http

**Comment by templth** [comment]
@dlevkov I believe you ;-) Here is a sample repo I created from your code: https://github.com/templth/mockbackend-test. After executing `npm install`, run `npm run start`. On my side, the test passes. Is it the same for you?

**Comment by dlevkov** [comment]
@templth Your code working just fine, now i'm trying to find the difference.
my getItems look asame
```typescript
getItems(): Observable<any> {
        let headers = new Headers();
        headers.append('Content-Type', 'application/json');
        console.log(this._http);
        return this._http.get(this._dataDomain + this._factoryname + '/' + this._itemId)
            .map(response => response.json())
            .do(data => console.log(data))
            .catch(this.handleError);
    }
```
my inner _http is a singletone, but it doesn't matter.
```typescript
constructor( @Inject(Http) private _http: Http) {
        NanaDal._instance = this;
    }
```
I also changed my Http provider to Your version- same result
i think, the black magic is in async injector or in Http ctor timing, but i can't be more specific.

I copied Your test case 'AS-IS' and got this error:

> Failed: AsyncTestZoneSpec is not a constructor
```
TypeError: AsyncTestZoneSpec is not a constructor
    at eval (http://127.0.0.1:8080/node_modules/@angular/core/testing/async.js:21:32)
    at new ZoneAwarePromise (http://127.0.0.1:8080/node_modules/zone.js/dist/zone.js:584:30)
    at eval (http://127.0.0.1:8080/node_modules/@angular/core/testing/async.js:19:16)
    at Object.eval (http://127.0.0.1:8080/node_modules/@angular/core/testing/testing.js:98:26)
    at attemptAsync (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1916:24)
    at QueueRunner.run (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1871:9)
    at QueueRunner.execute (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1859:10)
    at Spec.queueRunnerFactory (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:697:35)
    at Spec.execute (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:359:10)
    at Object.fn (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2479:37)
```

**Comment by willm** [comment]
I spent the afternoon looking for the difference to, I think the answer lies in the system js config, but haven't extrapolated exactly what part yet.

@dlevkov I also ran into this problem, you need to add the async script to your test html file as @templth has done https://github.com/templth/mockbackend-test/blob/master/index.html#L17

**Comment by templth** [comment]
Yes the `node_modules/zone.js/dist/async-test.js` file provides the `AsyncTestZoneSpec` class.

**Comment by dlevkov** [comment]
well, dear @templth  and @willm adding async changed the situation, but

> createConnection requires an instance of Request, got [object Object]

same-same.
 ```
Error: createConnection requires an instance of Request, got [object Object]
    at new BaseException (http://127.0.0.1:8080/node_modules/@angular/http/src/facade/exceptions.js:17:23)
    at MockBackend.createConnection (http://127.0.0.1:8080/node_modules/@angular/http/testing/mock_backend.js:105:19)
    at httpRequest (http://127.0.0.1:8080/node_modules/@angular/http/http.umd.js:989:24)
    at Http.get (http://127.0.0.1:8080/node_modules/@angular/http/http.umd.js:1038:20)
    at NanaDal.getItems (http://127.0.0.1:8080/app/nanaDataService/DAL/nana.dal.js:68:27)
    at eval (http://127.0.0.1:8080/app/nanaDataService/nanaserviceService/nanaservice.service.test.js:103:24)
    at FunctionWrapper.apply (http://127.0.0.1:8080/node_modules/@angular/core/src/facade/lang.js:342:64)
    at TestInjector.execute (http://127.0.0.1:8080/node_modules/@angular/core/testing/test_injector.js:47:39)
    at eval (http://127.0.0.1:8080/node_modules/@angular/core/testing/test_injector.js:135:55)
    at ZoneDelegate.invoke (http://127.0.0.1:8080/node_modules/zone.js/dist/zone.js:323:29)
```
Soon i'll try to run my test code on @templth enviroment

**Comment by willm** [comment]
@dlevkov are you using system js? can you post your config if so.

**Comment by dlevkov** [comment]
@willm sure,
```
/**
 * System configuration for Angular 2 apps
 * Adjust as necessary for your application needs.
 */
(function(global) {

  // map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',

    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs'
  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
  };

  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
    'testing'
  ];

  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }

  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
  };

  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;

  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);

  var config = {
    map: map,
    packages: packages
  }

  System.config(config);

})(this);
```

**Comment by templth** [comment]
@dlevkov could you create a pull request after having cloned my repository? I would be very interested in seeing the differences between our two codes!

It's definitely a problem with the SystemJS configuration since I have the following error with your configuration:

```
zone.js:461 Unhandled Promise rejection: Cannot resolve all parameters for 'ViewUtils'(RootRenderer, undefined @Inject(Token AppId), SanitizationService). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'ViewUtils' is decorated with Injectable. ; Zone: <root> ; Task: Promise.then ; Value: NoAnnotationErrorconsoleError @ zone.js:461
zone.js:463 Error: Uncaught (in promise): Cannot resolve all parameters for 'ViewUtils'(RootRenderer, undefined @Inject(Token AppId), SanitizationService). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'ViewUtils' is decorated with Injectable.(…)consoleError @ zone.js:463
```

**Comment by dlevkov** [comment]
:open_mouth:  @templth , it's an Injector.
ok, i'll do it tomorrow ASAP :ok_hand:

**Comment by templth** [comment]
It seems that there is a problem with umd packaging.

If

```
//var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
// Not working
var setPackageConfig = packUmd;
// Working
var setPackageConfig = packIndex;
```

**Comment by dlevkov** [comment]
Good morning @templth , i did some tests and tried to pull request to Your git, but 403, no permissions for me.

**Comment by willm** [comment]
I can also confirm, I had the same systemjs config as @templth and I switched to using the `packIndex` function instead of `packUmd` and everything worked.

**Comment by willm** [comment]
I've made a pull request in @templth's repository highlighting the issue, it's a combination of using the umd packages and importing the `platform-browser-testing` packages in the test html file (which I was not doing).

**Comment by landryraccoon** [comment]
Just wanted to chime in that I've seen the same issue, willm's suggestion to switch to packIndex instead of packUmd fixed it.

**Comment by akosbordas** [comment]
Could someone find a soultion for use it with `packUmd`?

**Comment by foch** [comment]
The workaround we used was to hack into the SystemJS configuration file so that it always uses the `packIndex` for `http` module:

```
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
    'testing'
  ];

  var ngIndexPackageNames = [
    'http'
  ];

  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }

  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
  };

  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;

  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  ngIndexPackageNames.forEach(packIndex);
```

**Comment by gspanoae** [comment]
many thanks for this workaround @foch

**Comment by vikerman** [comment]
@kyliau  - Consider a mock backend example - #12409
