### ISSUE TITLE
 Error: Invalid provider - only instances of Provider and Type are allowed, got: [object Object]

### ISSUE THREAD

**Issue by pricks44** [angular/angular#9306]
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

When using a jasmine test that requires a provider, the test creates an error of Error: Invalid provider - only instances of Provider and Type are allowed, got: [object Object].  The code is below, the pipe uses ReservationsService to pull the data.  The script was then loaded into a html file.  

```
@Injectable()
class TestService {
    getReservationsByVenue(id: number): Observable<any> {
        return new Observable(ob => {
            ob.complete();
        });
    }
};

describe("getPendingCount.pipe: transform", () => {
    let pipe: GetPendingCountPipe;

    beforeEachProviders(() => [
        provide(ReservationsService, { useClass: TestService })
    ]);

    it("empty observable", inject([ReservationsService], (service: ReservationsService) => {
        pipe = new GetPendingCountPipe(service);
        expect(pipe.transform(0)).toEqual(0);
    }));
});
```

Here is the full stack trace:
```
Error: Invalid provider - only instances of Provider and Type are allowed, got: [object Object]
    at InvalidProviderError.BaseException [as constructor] (http://localhost:56672/node_modules/@angular/core/src/facade/exceptions.js:17:23)
    at new InvalidProviderError (http://localhost:56672/node_modules/@angular/core/src/di/reflective_exceptions.js:180:16)
    at eval (http://localhost:56672/node_modules/@angular/core/src/di/reflective_provider.js:162:19)
    at Array.forEach (native)
    at _normalizeProviders (http://localhost:56672/node_modules/@angular/core/src/di/reflective_provider.js:145:15)
    at Object.resolveReflectiveProviders (http://localhost:56672/node_modules/@angular/core/src/di/reflective_provider.js:103:22)
    at Function.ReflectiveInjector.resolve (http://localhost:56672/node_modules/@angular/core/src/di/reflective_injector.js:357:38)
    at ReflectiveInjector_.resolveAndCreateChild (http://localhost:56672/node_modules/@angular/core/src/di/reflective_injector.js:595:62)
    at TestInjector.createInjector (http://localhost:56672/node_modules/@angular/core/testing/test_injector.js:31:39)
    at TestInjector.execute (http://localhost:56672/node_modules/@angular/core/testing/test_injector.js:44:18)
```

* **Angular version:** 2.0.0-rc.1
 
* **Browser:**  Chrome 
 
* **Language: TypeScript 1.8.10

**Comment by vicb** [comment]
please add a plunker

**Comment by zoechi** [comment]
I think this is a dup of #8867

Maybe this works

```
new Provider(ReservationsService, { useClass: TestService })
```

**Comment by pricks44** [comment]
This is a dub of [#8867](https://github.com/angular/angular/issues/8867), which better documented and points at the method that is failing, so im closing this issue
