### ISSUE TITLE
compiler-cli does not work on windows

### ISSUE THREAD

**Issue by kondi** [angular/angular#9663]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

ngc on windows can not compile the components.

**Reproduction of the problem**

A very simple project with only one basic component. On linux it is working (actually not because of #9540, but this path issue is not a problem).

```
$ ./node_modules/.bin/ngc -p .
can't resolve module @angular/core/src/di/opaque_token from D:\Projects\ngc-test\index.ts
Error: Could not resolve module @angular/core/src/di/opaque_token relative to D:\Projects\ngc-test\index.ts
    at ReflectorHost.findDeclaration (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\reflector_host.js:96:23)
    at StaticReflector.initializeConversionMap (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\static_reflector.js:133:38)
    at new StaticReflector (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\static_reflector.js:34:14)
    at Function.CodeGenerator.create (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\codegen.js:134:31)
    at codegen (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (D:\Projects\ngc-test\node_modules\@angular\tsc-wrapped\src\main.js:25:16)
    at Object.<anonymous> (D:\Projects\ngc-test\node_modules\@angular\compiler-cli\src\main.js:12:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
Compilation failed
```

**Dirty quick fix**

https://github.com/kondi/angular/commit/4091738222f48138637c27e14fea53a5734f47aa

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
* **Operating system:** Windows 10

**Comment by vicb** [comment]
@mlaval do you have time to look at this ? Is the proposed fix the only place required to be updated ? 
Could you submit a PR using `path.normalize` ? Thanks

**Comment by kondi** [comment]
`path.normalize` does not solve this as it keeps the backslash as separator on windows.

**Comment by ashumaher** [comment]
https://github.com/angular/angular/issues/8582

**Comment by mlaval** [comment]
@vicb I'm off until mid-July :/

**Comment by mlaval** [comment]
This issue is no longer occurring, but the compiler still doesn't work on Windows.
See https://github.com/angular/angular/issues/10792 for the resolution.
