### ISSUE TITLE
ngc not working with static symbols used with Angular 1 code (ngUpgrade)

### ISSUE THREAD

**Issue by marcalj** [angular/angular#9670]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
I'm getting this error:

```
$ ./node_modules/.bin/ngc
Failed on type {"filePath":"/.../testApp/app/scripts/core/sectionhelp.component.ts","name":"SectionHelpComponent"} with error Error: Error encountered resolving symbol values statically. Qualified type names not supported (position 18:53 in the original .ts file), resolving symbol SectionHelpComponent in /.../testApp/app/scripts/core/section-help.component.ts
Error: Error encountered resolving symbol values statically. Qualified type names not supported (position 18:53 in the original .ts file), resolving symbol SectionHelpComponent in /.../testApp/app/scripts/core/section-help.component.ts
at simplifyInContext (/.../testApp/node_modules/@angular/compiler-cli/src/static_reflector.js:409:23)
at StaticReflector.simplify (/.../testApp/node_modules/@angular/compiler-cli/src/static_reflector.js:412:22)
at StaticReflector.parameters (/.../testApp/node_modules/@angular/compiler-cli/src/static_reflector.js:85:47)
at CompileMetadataResolver.getDependenciesMetadata (/.../testApp/node_modules/@angular/compiler/src/metadata_resolver.js:224:86)
at CompileMetadataResolver.getTypeMetadata (/.../testApp/node_modules/@angular/compiler/src/metadata_resolver.js:173:26)
at CompileMetadataResolver.getDirectiveMetadata (/.../testApp/node_modules/@angular/compiler/src/metadata_resolver.js:136:28)
at CompileMetadataResolver.maybeGetDirectiveMetadata (/.../testApp/node_modules/@angular/compiler/src/metadata_resolver.js:158:25)
at CodeGenerator.readComponents (/.../testApp/node_modules/@angular/compiler-cli/src/codegen.js:62:39)
at generateOneFile (/.../testApp/node_modules/@angular/compiler-cli/src/codegen.js:100:38)
at Array.map (native)
Compilation failed
```

On this code:

```ts
@Component({
    selector: 'section-help',
    templateUrl: 'scripts/core/section-help.component.html',
    directives: [CORE_DIRECTIVES],
    pipes: [TranslateNG1Pipe],
})
export class SectionHelpComponent implements OnInit {
    private language:string;
    private locationHash:string;
    private loading:boolean;
    private helpList:any[];
    private glossaryList:any[];

    constructor(@Inject('$timeout') private $timeout:ng.ITimeoutService,
                @Inject('$location') private $location:ng.ILocationService,
                private HelpService:HelpService) {
    }
```

If I remove the types from Angular 1 it successfully compiles using ```ngc```:

```ts
    constructor(@Inject('$timeout') private $timeout,
                @Inject('$location') private $location,
                private HelpService:HelpService) {
    }
```

This code works perfectly compiling using ```tsc``` in dynamic mode.

**Expected/desired behavior**
Be able to compile using Angular 1 types and custom interfaces.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
  
* **Language:** TypeScript 1.9

@alexeagle

**Comment by vicb** [comment]
The error reads `Qualified type names not supported` meaning that `ng.ITimeoutService` is not supported - try to import it directly and write something like

```
constructor(@Inject('$timeout') private $timeout:ITimeoutService,
                @Inject('$location') private $location:ILocationService,
                private HelpService:HelpService) {
```

(notice how `ng.` has been removed)

@chuckjaz could we discard the type when `@Inject()` is specified ?

**Comment by chuckjaz** [comment]
Can I get a complete example instead of a fragment?

**Comment by marcalj** [comment]
@vicb It doesn't work neither like this:

```ts
import {ITimeoutService, ILocationService} from 'angular';
...
constructor(@Inject('$timeout') private $timeout:ITimeoutService,
                @Inject('$location') private $location:ILocationService,
                private HelpService:HelpService) {
    }
```

@chuckjaz 

section-help.component.ts
```ts
import {Component, Inject} from '@angular/core';
import {ITimeoutService} from 'angular';

@Component({
    selector: 'section-help',
    template: '<p>{{ value }}</p>'
})
export class SectionHelpComponent {
    private value:number;
    constructor(@Inject('$timeout') private $timeout:ITimeoutService) {
        this.value = 0;

        this.$timeout(():void => {
            this.value += 1;
        }, 333);
    }
}
```

app.ts
```ts
import {SectionHelpComponent} from './section-help.component.ts';
import {UpgradeAdapter} from '@angular/upgrade';

const upgradeAdapter = new UpgradeAdapter();

upgradeAdapter.upgradeNg1Provider('$timeout');

angular
    .module('dashboardHelpApp', [])
    .directive('sectionHelp', <angular.IDirectiveFactory>upgradeAdapter.downgradeNg2Component(SectionHelpComponent));

angular.element(document).ready(function () {
    upgradeAdapter.bootstrap(document.body, ['dashboardHelpApp']);
});
```

index.html
```html
<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <title>ng2 test</title>
</head>
<body>
<section-help>

<script src="node_modules/core-js/client/shim.min.js"></script>
<script src="node_modules/zone.js/dist/zone.js"></script>
<script src="node_modules/reflect-metadata/Reflect.js"></script>
<script src="node_modules/systemjs/dist/system.src.js"></script>
<script src="node_modules/angular/angular.js"></script>
<script>
System.config({
    baseURL: '/',
    defaultJSExtensions: true,
    paths: {
        'npm:*': 'node_modules/*'
    },
    packages: {
        'scripts': {defaultJSExtensions: true},
        'rxjs': {defaultExtension: 'js'},
        '@angular/common': {main: 'index.js', defaultExtension: 'js'},
        '@angular/compiler': {main: 'index.js', defaultExtension: 'js'},
        '@angular/core': {main: 'index.js', defaultExtension: 'js'},
        '@angular/http': {main: 'index.js', defaultExtension: 'js'},
        '@angular/platform-browser': {main: 'index.js', defaultExtension: 'js'},
        '@angular/platform-browser-dynamic': {main: 'index.js', defaultExtension: 'js'},
        '@angular/router': {main: 'index.js', defaultExtension: 'js'},
        '@angular/router-deprecated': {main: 'index.js', defaultExtension: 'js'},
        '@angular/upgrade': {main: 'index.js', defaultExtension: 'js'}
    },
    map: {
        'system-polyfills': 'npm:systemjs/dist/system-polyfills.js',
        'system': 'npm:systemjs/dist/system.js',

        'rxjs': 'npm:rxjs',
        '@angular': 'npm:@angular'
    },
    meta: {
        'angular': {
            format: 'global',
            exports: 'angular'
        }
    }
});

    System
        .import('app')
        .catch(console.error.bind(console));
</script>
</body>
</html>
```

**Comment by chuckjaz** [comment]
@vicb We cannot simply ignore the type in `@Inject` because, at the point the error is generated, there is no type information to tell if this is Angular's `@Inject` and that the type should be elided.

I believe the fix would be instead of encoding this an error in the metadata file, we should encode the type reference as an expression allowing the `StaticResolver`, which does have type information, to determine that the referenced type is an interface and should be ignored.

**Comment by sod** [comment]
Yes, the offline compiler seems to behave differently as the runtime one. The runtime ignores the typehint, if the `@Inject` has a string as token. The offline compiler tries to always resolve the typehint, if its an interface.

So a token `'foo'` inject as: `constructor(@Inject('foo') foo: FooType) {}` provided as: `provide('foo', 1)` works in runtime, but throws `Could not resolve FooType` by `ngc`.

**Comment by chuckjaz** [comment]
@marcalj, @sod Can you test this patch to see if it solves your issues. I produced similar problem which this fixes but want to make sure it actually solves the issues you are having.

FYI: see `scripts/ci-lite/offline_compiler_test.sh` for an example of how to install or modules from built sources.

**Comment by sod** [comment]
@chuckjaz 

Is this the right way to test this?

* clone your branch
* build via `./build.sh`
* copy the hole thing into my `node_modules/@angular` via `cp -R /Users/avweiss/dev/playground/angular-chuckjaz/dist/packages-dist/* .`
* try compiler-cli again via `node_modules/.bin/ngc --noEmit --pretty --project app/Resources/public/js`

Now I get

```sh
Error: Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced (position 25:21 in the original .ts file), resolving symbol ROUTER_PROVIDERS in /Users/avweiss/dev/rebuy/blue-web/node_modules/@angular/router-deprecated/src/router_providers.d.ts, resolving symbol FilterComponent in /Users/avweiss/dev/my-brand/my-app/app/Resources/public/js/application/filter/component/filter-component.ts, resolving symbol FilterComponent in /Users/avweiss/dev/my-brand/my-app/app/Resources/public/js/application/filter/component/filter-component.ts
```

But the previous errors I got, where I had to replace all Interfaces with `any` did indeed go away with your PR. But I can't say if the app works without the runtime compiler, as I never actually got to the point where `ngc` works :(

**Comment by marcalj** [comment]
@chuckjaz I'm not able to compile Angular using node 6.2 :( there's a way to download builded ngc with your patch?

**Comment by chuckjaz** [comment]
@sod Thanks for verifying this. The error with the ROUTER_PROVIDERS is known and we should fix that soon. The current way ROUTER_PROVIDERS is initialized will not work with the offline compiler but the fix is relatively simple.

@marcalj Not easily. Could you use nvm to change to 5.5?

**Comment by fabiopaiva** [comment]
I am getting a similar error, using Node 5.5 and npm 3.10.3

```
Error: Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced (position 6:20 in the original .ts file), resolving symbol MD_CARD_DIRECTIVES in /media/fabio/storage/workspace/qlv/node_modules/@angular2-material/card/card.d.ts, resolving symbol MyFeaturedProductsComponent in /media/fabio/storage/workspace/qlv/src/app/my-featured-products/my-featured-products.component.ts, resolving symbol MyFeaturedProductsComponent in /media/fabio/storage/workspace/qlv/src/app/my-featured-products/my-featured-products.component.ts
    at simplifyInContext (/media/fabio/storage/workspace/qlv/node_modules/@angular/compiler-cli/src/static_reflector.js:416:23)
    at StaticReflector.simplify (/media/fabio/storage/workspace/qlv/node_modules/@angular/compiler-cli/src/static_reflector.js:419:22)
    at StaticReflector.annotations (/media/fabio/storage/workspace/qlv/node_modules/@angular/compiler-cli/src/static_reflector.js:52:36)
    at DirectiveResolver.resolve (/media/fabio/storage/workspace/qlv/node_modules/@angular/compiler/src/directive_resolver.js:26:44)
    at CompileMetadataResolver.getDirectiveMetadata (/media/fabio/storage/workspace/qlv/node_modules/@angular/compiler/src/metadata_resolver.js:108:51)
    at CompileMetadataResolver.maybeGetDirectiveMetadata (/media/fabio/storage/workspace/qlv/node_modules/@angular/compiler/src/metadata_resolver.js:180:25)
    at CodeGenerator.readComponents (/media/fabio/storage/workspace/qlv/node_modules/@angular/compiler-cli/src/codegen.js:69:39)
    at generateOneFile (/media/fabio/storage/workspace/qlv/node_modules/@angular/compiler-cli/src/codegen.js:94:38)
    at Array.map (native)
    at CodeGenerator.codegen (/media/fabio/storage/workspace/qlv/node_modules/@angular/compiler-cli/src/codegen.js:115:14)
Compilation failed

npm ERR! Linux 3.16.0-73-generic
npm ERR! argv "/home/fabio/.nvm/versions/node/v5.5.0/bin/node" "/home/fabio/.nvm/versions/node/v5.5.0/bin/npm" "run" "ngc"
npm ERR! node v5.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! qlv@0.0.1 ngc: `ngc -p . && cp app/* compiled`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the qlv@0.0.1 ngc script 'ngc -p . && cp app/* compiled'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the qlv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc -p . && cp app/* compiled
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs qlv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls qlv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/fabio/storage/workspace/qlv/npm-debug.log
```
my code:

```typescript
import { Component, OnInit } from '@angular/core';
import { MD_CARD_DIRECTIVES } from '@angular2-material/card';
import { MyFeaturedProductsService } from '../my-featured-products.service';
import { Product } from '../product';

@Component({
  moduleId: module.id,
  selector: 'app-my-featured-products',
  template: `
  <h3 class="title">{{title}}</h3>
  <div class="card-container">
    <md-card *ngFor="let product of products">
      <img md-card-image [alt]="product.name" src="{{product.image.thumb}}">
      <md-card-title>{{product.name}}</md-card-title>
      <md-card-content class="secondary">
        {{product.shortDescription | slice:0:200}}
      </md-card-content>
      <md-card-actions align="end">
        <button md-button color="primary">SNIFF</button>
        <button md-button color="primary">WOOF</button>
      </md-card-actions>
    </md-card>
  </div>
  `,
  styleUrls: ['my-featured-products.component.css'],
  providers: [MyFeaturedProductsService],
  directives: [MD_CARD_DIRECTIVES]
})

export class MyFeaturedProductsComponent implements OnInit {

  products: Product[];
  error: any;
  title = 'Destaques';

  constructor(private featuredProductsService: MyFeaturedProductsService ) {}

  ngOnInit() {
    this.featuredProductsService.getFeaturedProducts()
        .then( (products: Product[] ) => this.products = products)
        .catch( (error: any) => this.error = error);
  }

}
```

**Comment by marcalj** [comment]
@chuckjaz Sorry, can test it and I'm going on holidays tomorrow :( :)

**Comment by marcalj** [comment]
@fabiopaiva Are you using the patch in https://github.com/chuckjaz/angular/commit/d14edc0595fd87bdc18b0ef33c257f1df6744184 ?

**Comment by chuckjaz** [comment]
@fabiopaiva Material design is not prepared yet for offline compile we are working on it...

**Comment by chuckjaz** [comment]
@marcalj No problem. I will commit this as is. It seems to be fixing the underlying problem.

**Comment by fabiopaiva** [comment]
@chuckjaz ok, thank you for your reply.

**Comment by marcalj** [comment]
I'm getting this error :(

```bash
$ ./node_modules/.bin/ngc
TypeError: compiler.ViewResolver is not a constructor
    at Function.CodeGenerator.create (/Users/foo/node_modules/@angular/compiler-cli/src/codegen.js:146:164)
    at codegen (/Users/foo/node_modules/@angular/compiler-cli/src/main.js:7:36)
    at Object.main (/Users/foo/node_modules/@angular/tsc-wrapped/src/main.js:25:16)
    at Object.<anonymous> (/Users/foo/node_modules/@angular/compiler-cli/src/main.js:12:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
Compilation failed
```

**Comment by marcalj** [comment]
Sorry, I wasn't using latest ```@angular/compiler-cli```. Now I'm getting other errors about not using NgModules :)
