### ISSUE TITLE
TypeError in gulp-traceur during Angular-Build on Windows 8.1 x64

### ISSUE THREAD

**Issue by brakmic** [angular/angular#972]
Hello,

I've tried to build the current sources by following the given steps but unfortunately there's an error at *DestroyableTransform._transform* in *gulp-traceur*. 

I run the VisualStudio 2013 Toolchain and therefore I always use *npm install --msvs_version=2013*
I encountered no problems with downloading/building npm's. All needed prerequisites are in place (gulp, protractor,  webdriver-manager etc.). I'm not using Dart SDK, only JS.

Before posting here I've tried to find similar issues but no luck.

Here's the complete error output:

```console
Dart SDK is not available, Dart tasks will be skipped.
[14:22:50] Using gulpfile d:\src\js\angular2\angular\gulpfile.js
[14:22:50] Starting 'build.js.dev'...
[14:22:50] Starting 'build/transpile.js.dev'...
[14:22:50] Starting 'build/transpile.js.dev.es6'...
[14:22:50] Starting 'build/html.js.dev'...
[14:22:50] Starting 'build/copy.js.dev'...
[14:22:50] Starting 'build/multicopy.js.dev.es6'...
[14:22:50] Starting 'build.js.prod'...
[14:22:50] Starting 'build/transpile.js.prod'...
[14:22:50] Starting 'build/transpile.js.prod.es6'...
[14:22:50] Starting 'build/html.js.prod'...
[14:22:50] Starting 'build/copy.js.prod'...
[14:22:50] Starting 'build/multicopy.js.prod.es6'...
[14:22:51] Starting 'build.js.cjs'...
[14:22:51] Starting 'build/transpile.js.cjs'...
[14:22:51] Starting 'build/copy.js.cjs'...
[14:22:51] Starting 'build/multicopy.js.cjs'...
[14:22:51] Starting 'build.dart'...
Dart SDK is not available. Skipping task: build.dart
[14:22:51] Finished 'build.dart' after 209 μs
[14:22:52] Finished 'build/copy.js.dev' after 1.01 s
[14:22:52] Finished 'build/copy.js.prod' after 1.01 s
[14:22:52] Finished 'build/multicopy.js.cjs' after 1.52 s
[14:22:52] Finished 'build/multicopy.js.dev.es6' after 1.56 s
[14:22:52] Finished 'build/multicopy.js.prod.es6' after 1.57 s
[14:22:52] Finished 'build/copy.js.cjs' after 1.69 s
[14:22:56] Finished 'build/html.js.dev' after 5.98 s
[14:22:56] Finished 'build/html.js.prod' after 5.98 s
[14:23:01] Finished 'build/transpile.js.prod.es6' after 11 s
[14:23:01] Starting 'build/transpile.js.prod.es5'...
[14:23:02] Finished 'build/transpile.js.dev.es6' after 11 s
[14:23:02] Starting 'build/transpile.js.dev.es5'...
[14:23:02] Finished 'build/transpile.js.cjs' after 11 s
[14:23:02] Starting 'build/linknodemodules.js.cjs'...
creating link dist\js\cjs\node_modules\angular2 ..\angular2
creating link dist\js\cjs\node_modules\benchmarks ..\benchmarks
creating link dist\js\cjs\node_modules\benchmarks_external ..\benchmarks_external
creating link dist\js\cjs\node_modules\benchpress ..\benchpress
creating link dist\js\cjs\node_modules\examples ..\examples
creating link dist\js\cjs\node_modules\rtts_assert ..\rtts_assert
[14:23:02] Finished 'build/linknodemodules.js.cjs' after 3.35 ms
[14:23:02] Starting 'build/transformCJSTests'...
d:\src\js\angular2\angular\node_modules\gulp-traceur\index.js:36
                        this.emit('error', new gutil.PluginError('gulp-traceur', errs.join('\n'), {
                                                                                      ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (d:\src\js\angular2\angular\node_modules\gulp-traceur\index.js:36:66)
    at DestroyableTransform.Transform._read (d:\src\js\angular2\angular\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (d:\src\js\angular2\angular\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (d:\src\js\angular2\angular\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (d:\src\js\angular2\angular\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (d:\src\js\angular2\angular\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (d:\src\js\angular2\angular\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (d:\src\js\angular2\angular\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (d:\src\js\angular2\angular\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
```

**Comment by brakmic** [comment]
I changed index.js of gulp-traceur to use the err-object only if there's a proper function join(). I know it's an ugly hack but I wanted to know if the angular can be built at all.

*index.js* **36-43**
```javascript
} catch (errs) {
			if(errs && errs.join){
			this.emit('error', new gutil.PluginError('gulp-traceur', errs.join('\n'), {
				fileName: file.path,
				showStack: false
			}));
			}else{
				console.log('error in gulp-traceur but the errs-object is empty!');
			}
		}
```

Now I get the build and all other files. Of course, there are now a lot of warnings that the err-object is empty. :smile: 

```shell

error in gulp-traceur but the errs-object is empty!
error in gulp-traceur but the errs-object is empty!
error in gulp-traceur but the errs-object is empty!
error in gulp-traceur but the errs-object is empty!
error in gulp-traceur but the errs-object is empty!
error in gulp-traceur but the errs-object is empty!
error in gulp-traceur but the errs-object is empty!
[14:57:06] Finished 'build/transpile.js.prod.es5' after 13 s
[14:57:06] Finished 'build/transpile.js.prod' after 23 s
[14:57:06] Finished 'build.js.prod' after 23 s
[14:57:06] Finished 'build/transpile.js.dev.es5' after 13 s
[14:57:06] Finished 'build/transpile.js.dev' after 23 s
[14:57:06] Finished 'build.js.dev' after 23 s
[14:57:06] Starting 'build.js'...
[14:57:06] Finished 'build.js' after 6.02 μs
[14:57:06] Starting 'build'...
[14:57:06] Finished 'build' after 4.25 μs
```

**Comment by mhevery** [comment]
We no longer use traceur. Closing as obsolete.
