### ISSUE TITLE
RouterLink generation throws exception on parameters not yet present

### ISSUE THREAD

**Issue by mattes42** [angular/angular#9801]
**I'm submitting a ...**  (check one with "x")

[ ] bug report
[X ] feature request
[ ] support request

**Current behavior**
The following snippet used to work in router v2, when the user is initialized as an empty object , but don't hold `id` and`'name`. A scenario for this would be when the `user` is resolved asynchronously.
```<a [routerLink]="['/user',user.id]">{{user.name}}</a>```

The console logs the following now in v3.0.0-beta.2:
```
browser_adapter.js:84 TypeError: Cannot read property 'toString' of undefined
    at getPath (http://127.0.0.1:3000/vendor.bundle.js:61185:24)
    at prefixedWith (http://127.0.0.1:3000/vendor.bundle.js:61241:21)
    at updateSegment (http://127.0.0.1:3000/vendor.bundle.js:61202:14)
    at updateSegmentChildren (http://127.0.0.1:3000/vendor.bundle.js:61224:33)
    at Object.createUrlTree (http://127.0.0.1:3000/vendor.bundle.js:61083:10)
    at Router.createUrlTree (http://127.0.0.1:3000/vendor.bundle.js:20669:35)
    at RouterLinkWithHref.updateTargetUrlAndHref (http://127.0.0.1:3000/vendor.bundle.js:32176:37)
    at RouterLinkWithHref.ngOnChanges (http://127.0.0.1:3000/vendor.bundle.js:32164:75)
    at DebugAppView._View_ShowEventsComponent0.detectChangesInternal (ShowEventsComponent.template.js:283:59)
    at DebugAppView.AppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55473:15)
    at DebugAppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55578:45)
    at DebugAppView.AppView.detectViewChildrenChanges (http://127.0.0.1:3000/vendor.bundle.js:55499:20)
    at DebugAppView.AppView.detectChangesInternal (http://127.0.0.1:3000/vendor.bundle.js:55484:15)
    at DebugAppView.AppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55473:15)
    at DebugAppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55578:45)
    at DebugAppView.AppView.detectContentChildrenChanges (http://127.0.0.1:3000/vendor.bundle.js:55491:20)
    at DebugAppView.AppView.detectChangesInternal (http://127.0.0.1:3000/vendor.bundle.js:55483:15)
    at DebugAppView.AppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55473:15)
    at DebugAppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55578:45)
    at DebugAppView.AppView.detectViewChildrenChanges (http://127.0.0.1:3000/vendor.bundle.js:55499:20)
    at DebugAppView._View_ClubDelegate_Host0.detectChangesInternal (ClubDelegate.template.js:31:8)
    at DebugAppView.AppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55473:15)
    at DebugAppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55578:45)
    at DebugAppView.AppView.detectContentChildrenChanges (http://127.0.0.1:3000/vendor.bundle.js:55491:20)
    at DebugAppView._View_SportsbyMainComponent0.detectChangesInternal (SportsbyMainComponent.template.js:246:8)
    at DebugAppView.AppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55473:15)
    at DebugAppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55578:45)
    at DebugAppView.AppView.detectViewChildrenChanges (http://127.0.0.1:3000/vendor.bundle.js:55499:20)
    at DebugAppView.AppView.detectChangesInternal (http://127.0.0.1:3000/vendor.bundle.js:55484:15)
    at DebugAppView.AppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55473:15)
    at DebugAppView.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:55578:45)
    at ViewRef_.detectChanges (http://127.0.0.1:3000/vendor.bundle.js:41719:66)
```

If I initialize the user object in the component with a dummy id like this 
``` user={id:1} ```
everything works fine. 

**Expected/desired behavior**
The router refuses to create a (href) link on the respective element, but does return silently without throwing an exception. 

**What is the motivation / use case for changing the behavior?**
To avoid to implement (many) `ngIf` directives to check if ansynchronously resolved objects are present or dummy initializations with dummy properties.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4, router v3.0.0-beta2
 
* **Browser:** Chromium 51.0.2704.79 ,  FF v47, both on Linux Mint
 
* **Language:** TypeScript compiled to ES5

**Comment by brandonroberts** [comment]
Have you tried using the safe-navigation operator?

```html
<a [routerLink]="['/user', user?.id]">{{ user?.name }}</a>
```

**Comment by akirasosa** [comment]
I have encountered the same problem in migrating deprecated router.

@brandonroberts 
I tried it, but got ```TypeError: Cannot read property 'toString' of null```, though it worked in deprecated router. Still have not found any workaround..

**Comment by st0nie** [comment]
@brandonroberts I have the problem and the safe-navigation operator also does not work for me :(

**Comment by brandonroberts** [comment]
@akirasosa @st0nie will you reproduce this in a plunker? Here is one you can work from.

http://plnkr.co/edit/UGFzs6?p=preview

**Comment by st0nie** [comment]
Sure: http://plnkr.co/edit/J8estcmCxqUWJZZ1eO28?p=preview

Go to "Product list" > "Show details broken..." and "Show details fixed..."

**Comment by brandonroberts** [comment]
@akirasosa @st0nie I confirmed that this is a bug. You can also write routerLinks as one long string, so the following will work also.

```html
<a [routerLink]="['/product-editor' + product.id]">Edit product</a>
```

**Comment by st0nie** [comment]
Great. Thank you for the workaround!

**Comment by tviel** [comment]
Nice. Workaround is doing the magic. However, for path variables you have to add the slash yourself.

`<a [routerLink]="['/product-editor/' + product.id]">Edit product</a>`

**Comment by zifnab87** [comment]
I have a page that is routed to entity/someUUID

I am trying to get that through
```
ngOnInit() {
        let uuid: string = this.route.params["uuid"];
        this.uuid = uuid;
        this.entityService.fetchEntity(uuid).subscribe(
            data => {
                this.entity = EntityModel.fromJson(JSON.parse(data));
            },
            err => console.log(err)
        );
    }
```

it was breaking for me as well - I did the work around but the template link I have now:

```<a [routerLink]="['/entity/'+ uuid + '/edit']">Edit</a>```

returns 
```/entity/undefined/edit``` instead ```of /entity/someUUID/edit```

**Comment by vsavkin** [comment]
if the `user` variable is undefined, then it should throw an error.  The `['/user',user.id]` expression is evaluated by the change detection system, not by the router. The router cannot delay the evaluation. The '?.' operator is the way to go. If it doesn't work, please open an issue.

**Comment by jjlorenzo** [comment]
I don't understand why this is closed since the '?' operator doesn't work, What I'm missing?

Doesn't work:
``` html
<a [routerLink]="['/preview/referral/', report?.referral?.id]">#{{ report?.referral?.id }}</a>
```
But this, that I understand it is the workaround, works

``` html
<a [routerLink]="['/preview/referral/' + report?.referral?.id]">#{{ report?.referral?.id }}</a>
```
Thanks

**Comment by brandonroberts** [comment]
@jjlorenzo items in the `routerLink` array cannot be undefined, which explains why the first example doesn't work. The `report` can initially be undefined, and then become set. The second example has a defined, but incomplete URL which is valid.

**Comment by jjlorenzo** [comment]
Thanks, but for what I see, I can't use the array syntax in the common scenario when the UI react to data changes, right? Thanks.

**Comment by brandonroberts** [comment]
I don't see why this prevents you from using it with the array syntax unless your entire URL is dynamically defined.

**Comment by dgroh** [comment]
Could please someone help?

I have the following code:

```
<div class="menu">
  <ul>
    <li>
      <a routerLink="{{contract?.id}}/Letztverbrauch" routerLinkActive="active">Letztverbrauch</a>
    </li>    
  </ul>
</div>
```

And I get the following error:

> TypeError: Cannot read property 'subscribe' of undefined
            at new RouterLinkWithHref

**contract** is a `@Input()` property.

```
@Component({
  selector: "app-menu",
  templateUrl: "./menu.component.html",
  styleUrls: ["./menu.component.scss"]
})
export class MenuComponent {

  @Input() public contract: Contract;

  constructor() { }

}
```
