### ISSUE TITLE
Angular 2 RC 4 New Animations not supported in Directives

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#9947]
Hi,

It seems that in current release we can add animations to components only and cannot define them as directives. I mean:

**the below works**

```
@Component({
    selector: "animate-demo",
    animations: [
        trigger('openClose', [
            state('closed, void',
                style({ height: "0px" })),
            state('open',
                style({ height: "*" })),
            transition("* => *", animate(200))
        ])
    ]
})
```

**Whereas the below doesn't work:**

```
@Directive({
    selector: "animate-demo",
    animations: [
        trigger('openClose', [
            state('closed, void',
                style({ height: "0px" })),
            state('open',
                style({ height: "*" })),
            transition("* => *", animate(200))
        ])
    ]
})
```

**And gives compilation error in visual studio:**

"Argument of type '{ selector: string; animations: AnimationEntryMetadata[]; template: string; }' is not assignable to parameter of type '{ selector?: string; inputs?: string[]; outputs?: string[]; properties?: string[]; events?: strin...'.  
"

Usually we might want to have the commonly used animations such as slideDown, sliddeUp, fadeIn, fadeOut defined at one place as a directive and then in components where we want to use them we would just want to import the directive and use the animation instead of redefining animation in each component.

**Comment by ericmartinezr** [comment]
I don't think that would work as of now. The animations so  far work only on elements in the view, and directives don't have a view. There's this issue though https://github.com/angular/angular/issues/9044 that will add the possibility to animate the element itself

**Comment by naveedahmed1** [comment]
Thank you so much Eric fro your reply. Then whats the best way if we want to make reusable animations? Apparently it seems that if n of my components requires slide up/down animation, I will have to write the same animation n times i.e. in each component, correct?

I believe the ability to define animations as structural directive would embrace re-usability of animations, what do you think?

**Comment by ericmartinezr** [comment]
I'm not the one to answer that. @matsko may give you a good answer.

**Comment by matsko** [comment]
Even though directives are not attached to a view, they should still be able to place animations on the host element that they are attached to.

Say for example you wanted to create a directive to manipulate `animate.css` animations:

```ts
@Directive({
   styleUrls: ['animate.css'],
   selector: '[animateCss]',
   host: {
      '[@currentAnimation]': 'animationState'
   },
   animations: [
      trigger('currentAnimation', [
         transition('* => rotate3d', animate(1000, keyframes('rotate3d'))),
         transition('* => hinge', animate(1000, keyframes('hinge'))),
         transition('* => flipX', animate(1000, keyframes('flipX')))
      ])
   ]
})
class AnimatorMan {
   @Input("animateCss")
   public animationState;
}
```

(The use of using CSS classes/keyframes within `animate` will be possible once the CSS parser is integrated. The example above is just to show how useful it can be to make a directive that manages animations.)

**Comment by matsko** [comment]
As of #9933 we can set animation hooks on the `:host` properties within a `@Component`. It shouldn't be much more work getting them to work on `@Directive`.

**Comment by naveedahmed1** [comment]
Thank you so much @matsko for your reply, his looks really exciting. Can you please also create a Plunker for this?

**Comment by bergben** [comment]
Any news on this?

Also, is it (will it be) somehow possible that the user can pass in an animation to a directive @matsko? 
I would like to create a directive that, at some special point, triggers an animation. This should be either a default animation or if wanted, the user can pass in a default animation to the directive. 
I think the possibiltiy for that would be really useful.

**Comment by amcdnl** [comment]
@matsko - Trying this on 2.0.1 and getting an error.

```
import {
  Component,
  Directive, Input, Output, EventEmitter,
  HostListener, HostBinding, trigger,
  transition, animate, style, state
} from '@angular/core';

@Directive({
  selector: 'swui-overlay',
  host: {
    class: 'swui-overlay'
  },
  styles: [`
    .swui-overlay {
      position: fixed;
      top: 0;
      left: 0;
      bottom: 0;
      right: 0;
      width: 100%;
      overflow: hidden;
      height: 100%;
      background-color: #000;
      opacity: 0;
      visibility: hidden;
    }
  `],
  animations: [
    trigger('overlayTransition', [
      state('active', style({
        opacity: 0.8,
        visibility: 'visible'
      })),
      state('inactive', style({
        visibility: 'hidden',
        opacity: 0
      })),
      transition('* => active', [
        animate('100ms ease-in')
      ]),
      transition('* => inactive', [
        animate('100ms ease-out')
      ])
    ])
  ]
})
export class OverlayDirective {

  @HostBinding('@overlayTransition')
  get animationState() {
    return this.visible ? 'active' : 'inactive';
  }

  @Input() visible: boolean = false;

  @HostBinding('style.zIndex')
  @Input() zIndex: number = 990;

  @Output() onClick = new EventEmitter();

  @HostListener('click')
  backdropClick() {
    this.onClick.emit(true);
  }

}
```

which gives me:

```
bootstrap.ts?b333:9 TypeError: Cannot read property 'prop' of undefined
    at eval (eval at ./node_modules/@angular/compiler/src/view_compiler/property_binder.js (http://localhost:9999/vendor.js:967:1), <anonymous>:127:63)
    at Array.forEach (native)
    at bindAndWriteToRenderer (eval at ./node_modules/@angular/compiler/src/view_compiler/property_binder.js (http://localhost:9999/vendor.js:967:1), <anonymous>:81:16)
    at bindDirectiveHostProps (eval at ./node_modules/@angular/compiler/src/view_compiler/property_binder.js (http://localhost:9999/vendor.js:967:1), <anonymous>:181:5)
    at eval (eval at ./node_modules/@angular/compiler/src/view_compiler/view_binder.js (http://localhost:9999/vendor.js:983:1), <anonymous>:61:116)
    at Array.forEach (native)
    at ViewBinderVisitor.visitElement (eval at ./node_modules/@angular/compiler/src/view_compiler/view_binder.js (http://localhost:9999/vendor.js:983:1), <anonymous>:57:24)
    at ElementAst.visit (eval at ./node_modules/@angular/compiler/src/template_parser/template_ast.js (http://localhost:9999/vendor.js:847:1), <anonymous>:154:24)
    at eval (eval at ./node_modules/@angular/compiler/src/template_parser/template_ast.js (http://localhost:9999/vendor.js:847:1), <anonymous>:284:29)
    at Array.forEach (native)
```

of coursing switching this to a `Component` and it works fine.

**Comment by tinchou** [comment]
It seems that `animations` is not a part of the `@Directive` parameters anymore. What's the recommended way to encapsulate an animation that we're using across multiple components?

**Comment by amcdnl** [comment]
@tinchou - Animations on directives are important for components on things like svg or tables that rely on parent-child specific dom hierarchy.

**Comment by goldenbearkin** [comment]
Would this happen soon? I have been writing lots of components with similar animation applied. Directive is so desirable to make the code dry.

**Comment by molcik** [comment]
As a workaround you can create ```animations.ts``` file like:
```ts
export class Animations: [
    public static heroState = trigger('heroState', [
      state('inactive', style({
        backgroundColor: '#eee',
        transform: 'scale(1)'
      })),
      state('active',   style({
        backgroundColor: '#cfd8dc',
        transform: 'scale(1.1)'
      })),
      transition('inactive => active', animate('100ms ease-in')),
      transition('active => inactive', animate('100ms ease-out'))
    ])
  ]
}
```

And then use it in components like: 
```ts 
import { Animations }                          from './animations';

@Component({
  selector: 'myapp-hero',
  styleUrls: ['./hero.component.css'],
  templateUrl: './heor.component.html',
  animations: [Animations.heroState]
})
```

**Comment by msc117** [comment]
@molcik Any idea why that doesn't work for AOT?
```
> ngc -p tsconfig.aot.json

Error: Error encountered resolving symbol values statically. Expression form not supported (position 130:18 in the original .ts file), resolving symbol Animations
```

**Comment by molcik** [comment]
@msc117 I have no idea, only using JIT currently..

**Comment by msc117** [comment]
It was because I was using ES2015 string template literals in my
animations. Not sure why that can't be exported for AOT.

**Comment by waveywhite** [comment]
@molcik this workaround is useful but without encapsulating the triggering we're only half way there. A particular problem is animating the revealing of items that are present based on *ngIf, because you have to add in timeouts manage the appearance & animation properly. It would be great to define this sort of logic once.

**Comment by qiluo** [comment]
I've created some animation directive by following this post https://www.joshmorony.com/create-a-sliding-item-animation-with-a-directive-in-ionic-2/

However animation only happened once, cannot switch state (e.g. active & inactive), any better solution now?

**Comment by fayezmm** [comment]
I have a suggestion for the angular team regarding animation. I wonder if it is possible to introduce a new way to manage animation similar to the way angular is currently managing Components and Directives; I mean through dependency injection. 

**Something like:** 

`
import { Animation, OnAnimate, AnimationMetadata } from '@angular/animation';

@Animation {
    selector: 'collapse'
}
export class CollapseAnimation implements OnAnimate {
    constructor() {}
    onAnimate() : AnimationMetadata {
        return [
            state('0', style({
                height: '0',
                opacity: '0'
            })),
            state('1', style({
                height: '*',
                opacity: '1'
            })),
            transition('0 => 1', animate('200ms ease-in')),
            transition('1 => 0', animate('200ms ease-out'))
        ];
    }
}
`

**then used in templates like:**

`
import { Component } from '@angular/core';

@Component({
    selector: 'my-component',
    template: '<div [@collapse]="isCollabsed"> Some content </div>',
    animations: [CollapseAnimation]
})
export class MyComponent {
    public isCollabsed: boolean = false; // set to true to trigger animation 
    constructor() {}
}
`

**Comment by fayezmm** [comment]
Ok, I have managed to do animation using a directive. Here is an example: 

```TypeScript

import { Directive, Input, Renderer2 } from '@angular/core';
import { trigger, state, style, transition, animate } from '@angular/animations';
import { ɵAnimationEngine as AnimationEngine } from '@angular/animations/browser';

@Directive({ 
    selector: '[collapse]',
    host: {
      '[@animation]': 'collapse'
    }
})
export class Collapse {
    @Input() collapse: boolean;

    constructor( private animation: AnimationEngine,  private renderer: Renderer2) {
        
        const namespaceId = (<any>renderer).delegate._namespaceId; // this is a hack 
        const name = 'animation';
        
        this.animation.registerTrigger(trigger(`${namespaceId}#${name}`, [
            state('0', style({ height: '0', opacity: '0' })),
            state('1', style({ height: '*', opacity: '1' })),
            transition('0 => 1', animate('200ms ease-in')),
            transition('1 => 0', animate('200ms ease-out'))
        ]));
    }
}

```

and then use it like this : 

```TypeScript 
import { Component } from '@angular/core';

@Component({
    selector: 'my-component',
    template: '<div [collapse]="isCollabsed"> Some content </div>'
})
export class MyComponent {
    public isCollabsed: boolean = false; // set to true to trigger animation 
    constructor() {}
}
```

**Comment by naveedahmed1** [comment]
@matsko can you please share if there is any progress on this?

**Comment by cvharris** [comment]
@fayezmm this did the trick for me, but I wonder why it has to be this way? Also, how would this be rewritten using @HostBinding like the code style says we should?

**Comment by cvharris** [comment]
@fayezmm I had to eventually ditch the directive approach, it cannot bind to the animation on `enableProdMode()` like what it does in the angular-cli.

However, animating with a reusable is not difficult to put together, it a bit illogical from a syntax, structure, and philosophy point of view. Here's what I did to get my reusable collapsing working, even in prod mode!

```js
import { Component, Input, HostBinding } from '@angular/core'
import { trigger, state, style, transition, animate } from '@angular/animations'

@Component({
  selector: '[collapse]',
  template: '<ng-content></ng-content>',
  animations: [trigger('collapseAni', [
    state('0', style({ height: '0', opacity: '0' })),
    state('1', style({ height: '*', opacity: '1' })),
    transition('0 => 1', animate('400ms ease-in')),
    transition('1 => 0', animate('400ms ease-out'))
  ])],
})
export class CollapseComponent {
  @HostBinding('@collapseAni')
  @Input()
  collapse: boolean

  constructor() { }
}
```

**Comment by BartoszBaczek** [comment]
hey @cvharris, could you please share code on how component uses this animation?

**Comment by calebeno** [comment]
@matsko Hasn't been an update in awhile.  Was wondering if this was still in the works?

**Comment by matsko** [comment]
Yes there is a plan in the works. I will update this thread once I get a go-ahead on this.

**Comment by shyamal890** [comment]
+1

**Comment by programmermurali** [comment]
+1

**Comment by calebeno** [comment]
@matsko Been a few months since your last update.  Any news?

**Comment by laurencefass** [comment]
hi is there any news on this feature?

**Comment by McQuinTrix** [comment]
I did something that @molcik mentioned above. 

Gist here: https://gist.github.com/McQuinTrix/3bd041a4ffefc53633d38d927c782db7

**Comment by jotatoledo** [comment]
@McQuinTrix thats the standard approach, you arent using a directive to control the animation.

**Comment by MrCroft** [comment]
@laurencefass 
That's what I've been using also... at least until now. I've just found out that this doesn't work when using AnimationPlayer & AnimationBuilder:
```
animate('200ms ease-out', style({
  height: '!'
})),
```
I'm getting the warning and error that you see in the attached image :(
If I change `height: '!'` to `height: 100` or any value, it works. Don't know why it doesn't want to work with '!'. Using the same animation directly in a component, works just fine. And '!' is needed when you don't know what height your element should have.

Forked your blitz to create an example with height, to illustrate the error: https://stackblitz.com/edit/github-d1umhe?file=src%2Fapp%2Ffade-in-out.directive.ts


![image](https://user-images.githubusercontent.com/2809154/50863316-f48eaa00-13a6-11e9-8dca-b0b57abbe1fa.png)

**Comment by petebacondarwin** [comment]
The concern with adding this functionality to directives, is that animations require a specific "animation renderer".
This renderer is created for a component when rendering its template. And we are able to create the correct kind of renderer by looking at whether the component decorator has the `animations` property.
But a directive does not have its own renderer, it inherits it from the containing component. It will be quite difficult to ensure that the containing component creates an "animation renderer" if only some directives within its template define animations.

**Comment by thePunderWoman** [comment]
This issue was closed as obsolete due to the introduction of the new `animate.enter` and `animate.leave` APIs. The `@angular/animations` package is now deprecated and will be removed in Angular v23. We hope you give the new APIs a try.
