### ISSUE TITLE
TypeError exception when using foreach inside switch

### ISSUE THREAD

**Issue by divdavem** [angular/angular#997]
An exception (`TypeError: Cannot read property 'removeChild' of null`) happens when the value of a `[switch]` directive changes in a way that should hide a nested `*foreach`.

**Template / component**

```html
<input type="text" (input)="onInput($event)" placeholder="Type something here"><br>
<ul [switch]="getSwitchValue()">
    <li *switch-when="'empty'">No suggestion</li>
    <li *switch-when="'waiting'">Loading suggestions...</li>
    <template [switch-default]>
      <li *foreach="#suggestion in list">{{suggestion}}</li>
    </template>
</ul>
```

```js
    onInput($event) {
      var value = $event.target.value;
      if (value) {
        var promise = this.list = new Promise((resolve) => {
          resolve(["Suggestion 1 for " + value, "Suggestion 2 for " + value]);
        });
        promise.then((resolvedList) => {
          if (this.list != promise) {
            return;
          }
          this.list = resolvedList;
        });
      } else {
        this.list = null;
      }
    }
    getSwitchValue() {
      if (!this.list || this.list.length == 0) {
        return "empty";
      } else if (this.list.then) {
        return "waiting";
      } else {
        return "results";
      }
    }
```

Cf [here](https://github.com/divdavem/ng2-play/blob/switchIssue/src/hello.js) for the full file.

**Steps to reproduce**

To reproduce the issue:
* git clone https://github.com/divdavem/ng2-play.git -b switchIssue
* npm install && gulp play
* Type something in the field
* When typing the second char, the `TypeError: Cannot read property 'removeChild' of null` exception is raised [from here](https://github.com/angular/angular/blob/master/modules/angular2/src/dom/browser_adapter.es6#L91).
* The exception prevents the list of suggestions from disappearing and reappearing as it should.

Here is the stack trace of the exception:
```
TypeError: Cannot read property 'removeChild' of null
    at BrowserDomAdapter.execute.$__export.removeChild (angular2\src\dom\browser_adapter.js:108:15)
    at Function.execute.$__export.removeViewNodesFromParent (angular2\src\core\compiler\view_container.js:165:19)
    at ViewContainer.execute.$__export.detach (angular2\src\core\compiler\view_container.js:126:29)
    at ViewContainer.execute.$__export.remove (angular2\src\core\compiler\view_container.js:115:29)
    at ViewContainer.execute.$__export.clear (angular2\src\core\compiler\view_container.js:68:20)
    at ViewContainer.execute.$__export.dehydrate (angular2\src\core\compiler\view_container.js:64:18)
    at View.execute.$__export.dehydrate (angular2\src\core\compiler\view.js:220:40)
    at ViewContainer.execute.$__export.remove (angular2\src\core\compiler\view_container.js:116:18)
    at Switch.execute.$__export._emptyAllActiveViewContainers (angular2\src\directives\switch.js:81:35)
    at Switch.value (angular2\src\directives\switch.js:49:18)
```

**Angular version**

Tested with version 2.0.0-alpha.13

**Comment by divdavem** [comment]
The issue also happens with different directives than `switch` and `foreach`:

```html
<ul>
    <li *if="getSwitchValue() == 'empty'">No suggestion</li>
    <li *if="getSwitchValue() == 'waiting'">Loading suggestions...</li>
    <template [if]="getSwitchValue() == 'results'">
      <li *if="true">{{list[0]}}</li>
    </template>
</ul>
```

Having a template directly inside another one seems to trigger the exception when the child view is detached (`<li *if="true">...</li>` is equivalent to `<template [if]="true"><li>...</li></template>` which is directly inside another `template` tag) .
