### ISSUE TITLE
ngc fails to compile when using external directives

### ISSUE THREAD

**Issue by ghostofcain** [angular/angular#9971]
[x ] bug report
[ ] feature request

**Current behavior**
When using external directives (such as the ones from Angular/Material2 or ng2-file-upload, the compiler fails with "Error encountered resolving symbol value statically". tsc is successful compiling and when running the project, they behave as expected.

Actual error: (example when using FILE_UPLOAD_DIRECTIVES from https://github.com/valor-software/ng2-file-upload):

```
>> Error: Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced (position 3:20 in the original .ts file), resolving symbol FILE_UPLOAD_DIRECTIVES in /angular-test/node_modules/ng2-file-upload/ng2-file-upload.d.ts, resolving symbol PublishComponent in /angular-test//App/components/publish/publish.component.ts, resolving symbol PublishComponent in /angular-test/App/components/publish/publish.component.ts
>>     at simplifyInContext (/angular-test/node_modules/@angular/compiler-cli/src/static_reflector.js:416:23)
>>     at StaticReflector.simplify (/angular-test/node_modules/@angular/compiler-cli/src/static_reflector.js:419:22)
>>     at StaticReflector.annotations (/angular-test/node_modules/@angular/compiler-cli/src/static_reflector.js:52:36)
>>     at DirectiveResolver.resolve (/angular-test/node_modules/@angular/compiler/src/directive_resolver.js:26:44)
>>     at CompileMetadataResolver.getDirectiveMetadata (/angular-test/node_modules/@angular/compiler/src/metadata_resolver.js:108:51)
>>     at CompileMetadataResolver.maybeGetDirectiveMetadata (/angular-test/node_modules/@angular/compiler/src/metadata_resolver.js:180:25)
>>     at CodeGenerator.readComponents (/angular-test/node_modules/@angular\compiler-cli/src/codegen.js:69:39)
>>     at generateOneFile (/angular-test/node_modules/@angular/compiler-cli/src/codegen.js:94:38)
>>     at Array.map (native)
>>     at CodeGenerator.codegen (/angular-test/node_modules/@angular/compiler-cli/src/codegen.js:115:14)
>> Compilation failed
>> Exited with code: 1.
Warning: Task "exec:ngc" failed. Use --force to continue.
```

Content of the file it's complaining about:

```
ng2-file-upload.d.ts:
export * from './components/file-upload/file-select.directive';
export * from './components/file-upload/file-drop.directive';
export * from './components/file-upload/file-uploader.class';
export declare const FILE_UPLOAD_DIRECTIVES: [any];
declare var _default: {
    directives: [any][];
};
export default _default;
```

Sample code using said directive:

```
> import { FILE_UPLOAD_DIRECTIVES, FileUploader} from 'ng2-file-upload';
> ...
> @Component({
>     templateUrl: 'publish.component.html',
>     selector: 'publish',
>     directives: [FILE_UPLOAD_DIRECTIVES, CORE_DIRECTIVES, FORM_DIRECTIVES]
> })
```

**Expected/desired behavior**
I believe this should compile correctly.

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScrip^1.8.10]

**Comment by chuckjaz** [comment]
Working as intended.

The offline compiler does not support generating code for components that reference directives lists whose value can only be determined dynamically such as references to `export declare const FILE_UPLOAD_DIRECTIVES: [any]`.
